"""
RECO — AI Firewall v0.2.0-web

Analyzes text to estimate whether it was generated by an AI model.
"""

import collections
import logging
import math
import re
import time

from flask import Blueprint, jsonify, request

logger = logging.getLogger(__name__)

# =============================================================================
# Constants
# =============================================================================

FIREWALL_VERSION = "0.2.0-web"
FIREWALL_STATUS = "active"
K_DEFAULT = 1.5

# Classification thresholds
LEVEL_THRESHOLDS = {
    "high":   0.33,  # conf >= 0.33 → likely AI-generated
    "medium": 0.25,  # 0.25 <= conf < 0.33 → mixed / uncertain
    "low":    0.0,   # conf < 0.25 → likely human-written
}

# =============================================================================
# Blueprint
# =============================================================================

firewall_bp = Blueprint("firewall", __name__, url_prefix="/api/firewall")

# Module-level state for /status
_state = {
    "total_requests": 0,
    "last_analysis": None,
    "started_at": None,
}


def _init_state():
    """Initialise the started_at timestamp on first import / registration."""
    if _state["started_at"] is None:
        _state["started_at"] = time.time()


# =============================================================================
# Text feature extraction
# =============================================================================

def _tokenize(text: str) -> list[str]:
    """Simple whitespace + punctuation tokenizer."""
    return re.findall(r"[A-Za-z\u3040-\u9FFF\uF900-\uFAFF]+'?[a-z]*|[^\s]", text)


def _sentence_split(text: str) -> list[str]:
    """Split text into sentences (handles Japanese period as well)."""
    parts = re.split(r'(?<=[.!?。])\s+', text.strip())
    return [s for s in parts if s]


def _compute_burstiness(sentences: list[str]) -> float:
    """
    Burstiness: variance in sentence lengths normalised by mean.
    AI text tends to have low burstiness (uniform sentence lengths).
    Returns 0-1 where lower means more uniform (more AI-like).
    """
    if len(sentences) < 2:
        return 0.5
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    if mean_len == 0:
        return 0.5
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std = math.sqrt(variance)
    # Coefficient of variation, clamped to [0, 1]
    cv = min(std / mean_len, 2.0) / 2.0
    return cv


def _compute_repetition(tokens: list[str]) -> float:
    """
    Repetition score based on bigram frequency.
    AI text often reuses certain phrase patterns.
    Returns 0-1 where higher means more repetitive.
    """
    if len(tokens) < 4:
        return 0.0
    bigrams = [f"{tokens[i]} {tokens[i+1]}" for i in range(len(tokens) - 1)]
    counter = collections.Counter(bigrams)
    total = len(bigrams)
    repeated = sum(c for c in counter.values() if c > 1)
    return min(repeated / total, 1.0)


def _compute_vocab_richness(tokens: list[str]) -> float:
    """
    Type-token ratio as a proxy for vocabulary richness.
    Returns 0-1 where lower means less diverse (more AI-like patterns).
    """
    if not tokens:
        return 0.5
    lower_tokens = [t.lower() for t in tokens]
    return min(len(set(lower_tokens)) / len(lower_tokens), 1.0)


def _compute_divergence(text: str) -> tuple[float, dict]:
    """
    Compute divergence score D from multiple text features.
    Higher D = more likely human, Lower D = more likely AI.

    Returns (D, features_dict).
    """
    sentences = _sentence_split(text)
    tokens = _tokenize(text)

    burstiness = _compute_burstiness(sentences)
    repetition = _compute_repetition(tokens)
    vocab_richness = _compute_vocab_richness(tokens)

    # AI text: low burstiness, moderate-high repetition, lower vocab richness
    # Human text: high burstiness, lower repetition, higher vocab richness
    # D represents how "human-like" the text is; lower D = more AI-like
    D = (burstiness * 0.40) + ((1.0 - repetition) * 0.30) + (vocab_richness * 0.30)

    features = {
        "burstiness": round(burstiness, 4),
        "repetition": round(repetition, 4),
        "vocab_richness": round(vocab_richness, 4),
        "sentence_count": len(sentences),
        "token_count": len(tokens),
    }
    return D, features


# =============================================================================
# Core scoring
# =============================================================================

def compute_confidence(text: str, k: float = K_DEFAULT) -> dict:
    """Compute confidence score for AI-generated text detection."""
    tokens = _tokenize(text)
    T = math.log1p(len(tokens)) / 10.0  # Length dampening factor

    D, features = _compute_divergence(text)

    conf = math.exp(-k * D) / (1.0 + T)
    conf = max(0.0, min(1.0, conf))  # Clamp to [0, 1]

    # Classify level
    if conf >= LEVEL_THRESHOLDS["high"]:
        level = "high"
        label = "AI-generated"
    elif conf >= LEVEL_THRESHOLDS["medium"]:
        level = "medium"
        label = "uncertain"
    else:
        level = "low"
        label = "human-written"

    return {
        "confidence": round(conf, 6),
        "level": level,
        "label": label,
    }


# =============================================================================
# Endpoints
# =============================================================================

@firewall_bp.route("/analyze", methods=["POST"])
def analyze():
    """POST /api/firewall/analyze — テキストレベルを判定"""
    _init_state()

    data = request.get_json(silent=True)
    if not data or "text" not in data:
        return jsonify({
            "error": "リクエストボディに 'text' フィールドが必要です",
            "usage": {"method": "POST", "body": {"text": "分析するテキスト", "k": "(optional) float"}}
        }), 400

    text = data["text"]
    if not isinstance(text, str) or len(text.strip()) == 0:
        return jsonify({"error": "テキストが空です"}), 400

    k = data.get("k", K_DEFAULT)
    if not isinstance(k, (int, float)) or k <= 0:
        k = K_DEFAULT

    result = compute_confidence(text, k=k)

    _state["total_requests"] += 1
    _state["last_analysis"] = {
        "timestamp": time.time(),
        "level": result["level"],
        "confidence": result["confidence"],
    }

    return jsonify({
        "firewall": "RECO",
        "version": FIREWALL_VERSION,
        "result": result,
    })


@firewall_bp.route("/health", methods=["GET"])
def health():
    """GET /api/firewall/health — ヘルスチェック"""
    _init_state()
    return jsonify({
        "status": "healthy",
        "name": "RECO — AI Firewall",
        "version": FIREWALL_VERSION,
    })


@firewall_bp.route("/status", methods=["GET"])
def status():
    """GET /api/firewall/status — 現在の判定状態"""
    _init_state()
    uptime = time.time() - _state["started_at"] if _state["started_at"] else 0
    return jsonify({
        "name": "RECO — AI Firewall",
        "version": FIREWALL_VERSION,
        "status": FIREWALL_STATUS,
        "total_requests": _state["total_requests"],
        "uptime_seconds": round(uptime, 1),
        "last_analysis": _state["last_analysis"],
    })


@firewall_bp.route("/docs", methods=["GET"])
def docs():
    """GET /api/firewall/docs — API ドキュメント"""
    _init_state()
    return jsonify({
        "name": "RECO — AI Firewall",
        "version": FIREWALL_VERSION,
        "description": "テキストがAI生成かどうかを判定するファイアウォールAPI",
        "endpoints": {
            "POST /api/firewall/analyze": {
                "description": "テキストレベルを判定",
                "request_body": {
                    "text": "(必須) 分析対象のテキスト",
                },
                "response": {
                    "result": {
                        "confidence": "float (0-1)",
                        "level": "high | medium | low",
                        "label": "AI-generated | uncertain | human-written",
                    },
                },
            },
            "GET /api/firewall/health": {
                "description": "ヘルスチェック",
            },
            "GET /api/firewall/status": {
                "description": "現在の判定状態 (リクエスト数、稼働時間など)",
            },
            "GET /api/firewall/docs": {
                "description": "このドキュメント",
            },
        },
        "levels": {
            "high": "AI生成の可能性が高い",
            "medium": "判定が不確実",
            "low": "人間が書いた可能性が高い",
        },
    })
