"""Disease supplement recommendations and care guide data.

Contains DISEASE_SUPPLEMENTS mapping and get_treatment_recommendations_for_disease().
"""

DISEASE_SUPPLEMENTS = {
    # =========================================================================
    # Canine Vet Nutrition (caninevet.jp) サプリメント製品マッピング
    # 製品ラインナップ:
    #   1. MSM＋アミノコンプリート - 関節・筋肉・腱・アミノ酸サポート
    #   2. For Antioxidant Asta-Melon・VitaminE・Cysteine - 抗酸化サポート
    #   3. For Joint - 関節ケア
    #   4. Prebiotics & Probiotics & サイリウム - 消化器・腸内環境
    #   5. Canine Vet Relax & CBD - リラックス・疼痛緩和
    #   6. Canine Vet Protain - タンパク質・筋肉維持
    #   7. NMN-ミトコンドリアアシスト - 代謝活性・細胞エネルギー
    #   8. Canine Vet Booster & Relax - 活力・体力回復
    #   9. カミデミルク - 栄養補給ミルク
    #  10. No Pain Quick Stop - 止血パウダー
    # =========================================================================
    # --- Respiratory (呼吸器) ---
    "brachycephalic_airway_syndrome": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "気道粘膜の抗酸化保護・炎症軽減",
            "reason_en": "Antioxidant protection for airway mucosa and inflammation reduction",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "気道周囲組織の修復・アミノ酸による回復サポート",
            "reason_en": "Tissue repair around airways and amino acid recovery support",
        },
    ],
    "canine_parvovirus": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内フローラの回復・消化機能再建",
            "reason_en": "Restore intestinal flora and rebuild digestive function",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "回復期の必須アミノ酸補給・組織修復促進",
            "reason_en": "Essential amino acid supplementation and tissue repair during recovery",
        },
        {
            "name_ja": "カミデミルク",
            "name_en": "Kamide Milk",
            "dosage": "体重に応じて調整",
            "frequency": "1日1〜2回",
            "reason_ja": "回復期の栄養補給・消化吸収しやすい栄養源",
            "reason_en": "Easily digestible nutrition source during recovery",
        },
    ],
    "canine_distemper": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "ウイルス感染による酸化ストレスから神経・免疫細胞を保護",
            "reason_en": "Protect neural and immune cells from viral oxidative stress",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "神経機能回復のためのアミノ酸サポート",
            "reason_en": "Amino acid support for neurological recovery",
        },
        {
            "name_ja": "Canine Vet Booster & Relax",
            "name_en": "Canine Vet Booster & Relax",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "体力回復・免疫力の活性化サポート",
            "reason_en": "Support physical recovery and immune system activation",
        },
    ],
    "kennel_cough": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "気道の免疫力向上・抗酸化保護",
            "reason_en": "Boost airway immunity and antioxidant protection",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸管免疫の強化による全身免疫サポート",
            "reason_en": "Systemic immune support via gut immunity enhancement",
        },
    ],
    "canine_influenza": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "ウイルス感染時の免疫・抗酸化サポート",
            "reason_en": "Immune and antioxidant support during viral infection",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内環境改善による免疫力向上",
            "reason_en": "Improve immunity through gut health optimization",
        },
        {
            "name_ja": "カミデミルク",
            "name_en": "Kamide Milk",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "食欲低下時の栄養補給",
            "reason_en": "Nutritional support during appetite loss",
        },
    ],
    # --- Gastrointestinal (消化器) ---
    "gdv_bloat": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "術後の消化機能回復・腸内環境再建",
            "reason_en": "Post-surgical digestive recovery and gut flora restoration",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "術後の組織修復・アミノ酸による回復促進",
            "reason_en": "Post-surgical tissue repair and amino acid recovery",
        },
    ],
    "pancreatitis": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内環境の改善・消化負担の軽減",
            "reason_en": "Improve gut environment and reduce digestive burden",
        },
        {
            "name_ja": "カミデミルク",
            "name_en": "Kamide Milk",
            "dosage": "体重に応じて調整",
            "frequency": "1日1〜2回",
            "reason_ja": "膵臓に負担の少ない消化吸収しやすい栄養源",
            "reason_en": "Easily digestible nutrition that is gentle on the pancreas",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "膵臓の炎症に伴う酸化ストレスの軽減",
            "reason_en": "Reduce oxidative stress from pancreatic inflammation",
        },
    ],
    "ibd": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内細菌叢の正常化・腸管バリア機能強化",
            "reason_en": "Normalize gut microbiota and strengthen intestinal barrier",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸管組織の修復・吸収不良による栄養補給",
            "reason_en": "Intestinal tissue repair and nutrition for malabsorption",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸管の慢性炎症による酸化ダメージの軽減",
            "reason_en": "Reduce oxidative damage from chronic intestinal inflammation",
        },
    ],
    "megaesophagus": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "消化機能サポート・腸内環境の維持",
            "reason_en": "Digestive support and gut health maintenance",
        },
        {
            "name_ja": "カミデミルク",
            "name_en": "Kamide Milk",
            "dosage": "体重に応じて調整",
            "frequency": "1日2〜3回",
            "reason_ja": "嚥下しやすい流動性栄養源・栄養吸収不良の補正",
            "reason_en": "Easy-to-swallow liquid nutrition to compensate for malabsorption",
        },
    ],
    # --- Musculoskeletal / Orthopedic (筋骨格・整形) ---
    "hip_dysplasia": [
        {
            "name_ja": "For Joint",
            "name_en": "Canine Vet For Joint",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "関節軟骨の保護・修復・可動域改善",
            "reason_en": "Joint cartilage protection, repair, and mobility improvement",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "MSMによる関節炎症軽減・筋肉維持のためのアミノ酸補給",
            "reason_en": "MSM for joint inflammation and amino acids for muscle maintenance",
        },
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "関節痛の緩和・リラックス効果",
            "reason_en": "Joint pain relief and relaxation",
        },
    ],
    "elbow_dysplasia": [
        {
            "name_ja": "For Joint",
            "name_en": "Canine Vet For Joint",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "肘関節軟骨の保護・修復",
            "reason_en": "Elbow joint cartilage protection and repair",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "MSMによる関節炎症軽減・関節周囲筋のサポート",
            "reason_en": "MSM for joint inflammation and periarticular muscle support",
        },
    ],
    "ivdd": [
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "脊椎周囲の炎症軽減・神経組織修復のためのアミノ酸",
            "reason_en": "Spinal inflammation reduction and amino acids for nerve repair",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "神経組織の抗酸化保護",
            "reason_en": "Antioxidant protection for neural tissue",
        },
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1〜2回",
            "reason_ja": "椎間板疾患に伴う疼痛緩和・リラックス",
            "reason_en": "Pain relief and relaxation for disc disease",
        },
    ],
    "patellar_luxation": [
        {
            "name_ja": "For Joint",
            "name_en": "Canine Vet For Joint",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "膝関節軟骨の保護・関節機能改善",
            "reason_en": "Knee cartilage protection and joint function improvement",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "関節周囲の炎症軽減・筋肉強化サポート",
            "reason_en": "Reduce periarticular inflammation and support muscle strengthening",
        },
    ],
    "cruciate_ligament_rupture": [
        {
            "name_ja": "For Joint",
            "name_en": "Canine Vet For Joint",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "関節機能の回復支援・軟骨保護",
            "reason_en": "Support joint function recovery and cartilage protection",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "靱帯・結合組織の修復に必要なアミノ酸・MSM補給",
            "reason_en": "Amino acids and MSM for ligament and connective tissue repair",
        },
        {
            "name_ja": "Canine Vet Protain",
            "name_en": "Canine Vet Protain",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "術後の筋肉量維持・コラーゲン合成サポート",
            "reason_en": "Maintain muscle mass and support collagen synthesis post-surgery",
        },
    ],
    # --- Neurological (神経) ---
    "degenerative_myelopathy": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "神経細胞の抗酸化保護・変性進行の抑制",
            "reason_en": "Antioxidant neuroprotection and slow degenerative progression",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "筋萎縮防止のためのアミノ酸補給・神経組織サポート",
            "reason_en": "Amino acids to prevent muscle atrophy and support neural tissue",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "神経細胞のミトコンドリア機能活性化・代謝サポート",
            "reason_en": "Activate neuronal mitochondrial function and metabolic support",
        },
    ],
    "epilepsy": [
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1〜2回",
            "reason_ja": "CBDによる発作閾値の上昇・神経の安定化",
            "reason_en": "CBD to raise seizure threshold and stabilize neural activity",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "脳の抗酸化保護・発作後の酸化ダメージ軽減",
            "reason_en": "Brain antioxidant protection and post-seizure oxidative damage reduction",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "脳神経細胞のエネルギー代謝改善",
            "reason_en": "Improve energy metabolism in brain neurons",
        },
    ],
    "wobbler_syndrome": [
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "脊椎周囲の炎症軽減・神経組織サポート",
            "reason_en": "Spinal inflammation reduction and neural tissue support",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "神経保護・抗酸化作用",
            "reason_en": "Neuroprotection and antioxidant action",
        },
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "頸部痛の緩和・リラックス",
            "reason_en": "Cervical pain relief and relaxation",
        },
    ],
    "laryngeal_paralysis": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "喉頭神経の抗酸化保護",
            "reason_en": "Antioxidant protection for laryngeal nerves",
        },
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "呼吸困難時の不安緩和・リラックス",
            "reason_en": "Anxiety relief and relaxation during breathing difficulty",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "神経修復のためのアミノ酸サポート",
            "reason_en": "Amino acid support for nerve repair",
        },
    ],
    "lumbar_sacral_disease": [
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腰仙部の炎症軽減・筋肉サポート",
            "reason_en": "Lumbosacral inflammation reduction and muscle support",
        },
        {
            "name_ja": "For Joint",
            "name_en": "Canine Vet For Joint",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "脊椎関節の保護",
            "reason_en": "Spinal joint protection",
        },
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腰仙部疼痛の緩和",
            "reason_en": "Lumbosacral pain relief",
        },
    ],
    # --- Dermatological (皮膚) ---
    "atopic_dermatitis": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "皮膚の抗酸化保護・炎症軽減・バリア機能改善",
            "reason_en": "Skin antioxidant protection, inflammation reduction, barrier improvement",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内免疫バランスの調整によるアレルギー反応の抑制",
            "reason_en": "Modulate allergic response via gut immune balance",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "MSMによる皮膚炎症の軽減・皮膚組織修復",
            "reason_en": "MSM for skin inflammation reduction and tissue repair",
        },
    ],
    "pyoderma": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "皮膚の免疫防御・抗酸化保護",
            "reason_en": "Skin immune defense and antioxidant protection",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "皮膚組織の修復促進・治癒サポート",
            "reason_en": "Promote skin tissue repair and healing",
        },
    ],
    "demodex_mange": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "免疫機能サポート・皮膚バリア修復",
            "reason_en": "Immune support and skin barrier repair",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "皮膚組織の再生・炎症軽減",
            "reason_en": "Skin tissue regeneration and inflammation reduction",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内免疫の強化による皮膚免疫サポート",
            "reason_en": "Skin immune support via gut immunity enhancement",
        },
    ],
    "allergic_dermatitis": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "アレルギー性炎症による酸化ストレスの軽減",
            "reason_en": "Reduce oxidative stress from allergic inflammation",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内免疫の調整・アレルギー反応の抑制",
            "reason_en": "Modulate intestinal immunity and suppress allergic response",
        },
    ],
    "food_allergy": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内環境改善・食物アレルギー反応の軽減",
            "reason_en": "Improve gut environment and reduce food allergy response",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "消化管・皮膚の抗酸化保護",
            "reason_en": "Antioxidant protection for GI tract and skin",
        },
    ],
    # --- Endocrine (内分泌) ---
    "hypothyroidism": [
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "低下した代謝機能の活性化サポート",
            "reason_en": "Support activation of reduced metabolic function",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "代謝低下に伴う酸化ストレスの軽減",
            "reason_en": "Reduce oxidative stress associated with metabolic decline",
        },
        {
            "name_ja": "Canine Vet Booster & Relax",
            "name_en": "Canine Vet Booster & Relax",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "活力・体力の回復サポート",
            "reason_en": "Support vitality and physical recovery",
        },
    ],
    "cushings_disease": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "コルチゾール過剰による酸化ストレスの軽減・皮膚改善",
            "reason_en": "Reduce oxidative stress from cortisol excess and improve skin",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "ホルモン異常による代謝機能のサポート",
            "reason_en": "Support metabolic function impaired by hormonal imbalance",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "クッシング症候群に伴う消化器症状のサポート",
            "reason_en": "GI support for Cushing's-associated digestive issues",
        },
    ],
    "addisons_disease": [
        {
            "name_ja": "Canine Vet Booster & Relax",
            "name_en": "Canine Vet Booster & Relax",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "副腎機能低下によるエネルギー不足の改善",
            "reason_en": "Improve energy deficiency from adrenal insufficiency",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "消化機能のサポート・ストレス性消化障害の改善",
            "reason_en": "Digestive support and stress-related GI improvement",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "ストレス対応のためのアミノ酸補給",
            "reason_en": "Amino acid supplementation for stress response",
        },
    ],
    "diabetes_mellitus": [
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "細胞のエネルギー代謝改善・インスリン感受性サポート",
            "reason_en": "Improve cellular energy metabolism and insulin sensitivity",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "糖尿病に伴う酸化ストレスの軽減",
            "reason_en": "Reduce oxidative stress associated with diabetes",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "サイリウムの食物繊維による血糖値安定化サポート",
            "reason_en": "Psyllium fiber for blood glucose stabilization",
        },
    ],
    "obesity": [
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "代謝活性化・脂肪燃焼効率の改善",
            "reason_en": "Metabolic activation and improved fat burning efficiency",
        },
        {
            "name_ja": "Canine Vet Protain",
            "name_en": "Canine Vet Protain",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "減量中の筋肉量維持・タンパク質補給",
            "reason_en": "Maintain muscle mass during weight loss",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内環境改善・満腹感サポート",
            "reason_en": "Gut health and satiety support",
        },
    ],
    # --- Renal / Urinary (腎・泌尿器) ---
    "chronic_kidney_disease": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "尿毒素の腸内排出促進・腸腎連関サポート",
            "reason_en": "Promote uremic toxin excretion via gut-kidney axis",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腎機能低下による栄養不良の補正・必須アミノ酸補給",
            "reason_en": "Correct malnutrition and supply essential amino acids for renal decline",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腎細胞のミトコンドリア機能サポート",
            "reason_en": "Support renal cell mitochondrial function",
        },
    ],
    "urinary_stones": [
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "尿路の健康維持・腸内環境改善による代謝サポート",
            "reason_en": "Urinary health and metabolic support via gut improvement",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "尿路の炎症・酸化ストレスの軽減",
            "reason_en": "Reduce urinary inflammation and oxidative stress",
        },
    ],
    # --- Cardiac (心臓) ---
    "dcm": [
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心筋に必要なアミノ酸（タウリン・L-カルニチン含む）の補給",
            "reason_en": "Supply cardiac amino acids including taurine and L-carnitine",
        },
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心筋細胞の抗酸化保護",
            "reason_en": "Antioxidant protection for cardiomyocytes",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心筋ミトコンドリアのエネルギー産生改善",
            "reason_en": "Improve cardiac mitochondrial energy production",
        },
    ],
    "mitral_valve_disease": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心臓の抗酸化保護・心筋ダメージ軽減",
            "reason_en": "Cardiac antioxidant protection and myocardial damage reduction",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心筋機能維持のためのアミノ酸サポート",
            "reason_en": "Amino acid support for cardiac muscle function maintenance",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心臓細胞のエネルギー代謝サポート",
            "reason_en": "Cardiac cellular energy metabolism support",
        },
    ],
    "pda": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心臓の抗酸化保護",
            "reason_en": "Cardiac antioxidant protection",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心臓細胞のエネルギー産生サポート",
            "reason_en": "Support cardiac cellular energy production",
        },
    ],
    "aortic_stenosis": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心筋の酸化ストレス軽減",
            "reason_en": "Reduce cardiac oxidative stress",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "心筋エネルギー代謝の改善",
            "reason_en": "Improve cardiac energy metabolism",
        },
        {
            "name_ja": "Canine Vet Relax & CBD",
            "name_en": "Canine Vet Relax & CBD",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "運動不耐性に伴うストレスの緩和",
            "reason_en": "Stress relief for exercise intolerance",
        },
    ],
    # --- Ophthalmic (眼科) ---
    "cataracts": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "水晶体の抗酸化保護・白内障進行抑制（アスタキサンチン・VitE・システイン）",
            "reason_en": "Lens antioxidant protection to slow cataract progression",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "眼組織の加齢性変化に対する細胞代謝サポート",
            "reason_en": "Cellular metabolic support against age-related ocular changes",
        },
    ],
    "glaucoma": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "視神経の抗酸化保護・眼内炎症の軽減",
            "reason_en": "Optic nerve antioxidant protection and intraocular inflammation reduction",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "網膜神経節細胞のミトコンドリア保護",
            "reason_en": "Mitochondrial protection for retinal ganglion cells",
        },
    ],
    "pra": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "網膜細胞の抗酸化保護・変性進行の抑制",
            "reason_en": "Retinal antioxidant protection and slow degenerative progression",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "網膜細胞のミトコンドリア機能維持",
            "reason_en": "Maintain retinal cell mitochondrial function",
        },
    ],
    "cherry_eye": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "眼周囲の炎症軽減・抗酸化保護",
            "reason_en": "Periocular inflammation reduction and antioxidant protection",
        },
    ],
    # --- Hepatic (肝臓) ---
    "liver_disease": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "肝臓の抗酸化保護・システインによる解毒サポート",
            "reason_en": "Hepatic antioxidant protection and cysteine for detox support",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "肝細胞の修復・再生に必要なアミノ酸補給",
            "reason_en": "Amino acids for hepatocyte repair and regeneration",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "肝細胞のミトコンドリア代謝活性化",
            "reason_en": "Activate hepatocyte mitochondrial metabolism",
        },
    ],
    "portosystemic_shunt": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "肝臓保護・解毒機能サポート",
            "reason_en": "Liver protection and detoxification support",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腸内アンモニア産生の抑制・腸肝循環改善",
            "reason_en": "Reduce intestinal ammonia and improve enterohepatic circulation",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "肝機能サポートのためのアミノ酸補給",
            "reason_en": "Amino acid supply for liver function support",
        },
    ],
    # --- Oncology (腫瘍) ---
    "hemangiosarcoma": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腫瘍関連の酸化ストレス軽減・細胞保護",
            "reason_en": "Reduce tumor-related oxidative stress and cell protection",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "がん悪液質予防のための栄養・アミノ酸サポート",
            "reason_en": "Nutritional and amino acid support to prevent cancer cachexia",
        },
        {
            "name_ja": "Canine Vet Protain",
            "name_en": "Canine Vet Protain",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "体力・筋肉量維持のためのタンパク質補給",
            "reason_en": "Protein supplementation to maintain strength and muscle mass",
        },
    ],
    "lymphoma": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "化学療法に伴う酸化ストレスの軽減",
            "reason_en": "Reduce oxidative stress from chemotherapy",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "化学療法中の消化器サポート・腸内環境維持",
            "reason_en": "GI support and gut health during chemotherapy",
        },
        {
            "name_ja": "Canine Vet Protain",
            "name_en": "Canine Vet Protain",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "がんによる筋肉消耗の予防",
            "reason_en": "Prevent cancer-related muscle wasting",
        },
    ],
    "osteosarcoma": [
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "骨・筋肉組織のサポート・栄養補給",
            "reason_en": "Bone and muscle tissue support and nutrition",
        },
        {
            "name_ja": "For Joint",
            "name_en": "Canine Vet For Joint",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "残存関節・対側肢の関節保護",
            "reason_en": "Protect remaining joints and contralateral limb",
        },
        {
            "name_ja": "Canine Vet Protain",
            "name_en": "Canine Vet Protain",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "術後・療養中の体力維持",
            "reason_en": "Maintain strength during treatment and post-surgery",
        },
    ],
    "mast_cell_tumor": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "腫瘍関連炎症の調節・抗酸化保護",
            "reason_en": "Modulate tumor inflammation and antioxidant protection",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "免疫機能サポートのためのアミノ酸・MSM補給",
            "reason_en": "Amino acid and MSM for immune function support",
        },
    ],
    "mammary_gland_tumor": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "抗酸化保護・腫瘍関連酸化ストレスの軽減",
            "reason_en": "Antioxidant protection and tumor-related oxidative stress reduction",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "体力維持のためのアミノ酸サポート",
            "reason_en": "Amino acid support for maintaining strength",
        },
        {
            "name_ja": "Canine Vet Protain",
            "name_en": "Canine Vet Protain",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "術後回復・筋肉量維持のためのタンパク質補給",
            "reason_en": "Protein for post-surgical recovery and muscle maintenance",
        },
    ],
    # --- Hematologic (血液) ---
    "von_willebrand_disease": [
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "出血による栄養損失の補正・組織修復アミノ酸",
            "reason_en": "Correct nutritional loss from bleeding and tissue repair amino acids",
        },
        {
            "name_ja": "No Pain Quick Stop",
            "name_en": "No Pain Quick Stop",
            "dosage": "出血時に患部に適量塗布",
            "frequency": "出血時",
            "reason_ja": "外傷・爪切り等の出血時の迅速な止血",
            "reason_en": "Rapid hemostasis for wounds and nail trimming bleeds",
        },
    ],
    "imha": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "赤血球膜の抗酸化保護・免疫介在性ダメージ軽減",
            "reason_en": "RBC membrane antioxidant protection and immune-mediated damage reduction",
        },
        {
            "name_ja": "MSM＋アミノコンプリート",
            "name_en": "MSM + Amino Complete",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "貧血による栄養不足の補正・赤血球産生サポート",
            "reason_en": "Correct nutritional deficiency from anemia and support RBC production",
        },
        {
            "name_ja": "NMN-ミトコンドリアアシスト",
            "name_en": "NMN Mitochondria Assist",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "貧血時の細胞エネルギー代謝サポート",
            "reason_en": "Cellular energy metabolism support during anemia",
        },
    ],
    # --- Ear (耳) ---
    "otitis_externa": [
        {
            "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
            "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "耳道の炎症・酸化ストレス軽減",
            "reason_en": "Reduce ear canal inflammation and oxidative stress",
        },
        {
            "name_ja": "Prebiotics & Probiotics & サイリウム",
            "name_en": "Prebiotics & Probiotics & Psyllium",
            "dosage": "体重に応じて調整",
            "frequency": "1日1回",
            "reason_ja": "全身免疫の強化による耳道感染の再発予防",
            "reason_en": "Prevent ear infection recurrence via systemic immune support",
        },
    ],
}

# Default fallback supplement for diseases without specific mapping
_DEFAULT_SUPPLEMENTS = [
    {
        "name_ja": "For Antioxidant Asta-Melon・VitaminE・Cysteine",
        "name_en": "For Antioxidant (Astaxanthin, Melon SOD, VitE, Cysteine)",
        "dosage": "体重に応じて調整",
        "frequency": "1日1回",
        "reason_ja": "全般的な抗酸化・健康サポート",
        "reason_en": "General antioxidant and health support",
    },
    {
        "name_ja": "MSM＋アミノコンプリート",
        "name_en": "MSM + Amino Complete",
        "dosage": "体重に応じて調整",
        "frequency": "1日1回",
        "reason_ja": "全般的なアミノ酸・栄養サポート",
        "reason_en": "General amino acid and nutritional support",
    },
]


def get_treatment_recommendations_for_disease(disease_id: str, breed_id=None, age_years=None) -> dict:
    """Get care guide including supplement reference and test information."""
    from api.diagnostic_chat import _DISEASES_BY_ID

    disease_record = _DISEASES_BY_ID.get(disease_id, {})

    if disease_id:
        supplements = DISEASE_SUPPLEMENTS.get(disease_id, _DEFAULT_SUPPLEMENTS)
        supplements = [{**s, "reference": "https://www.caninevet.jp/"} for s in supplements]
    else:
        supplements = []

    recommendations = {
        "primary_care_plan_ja": "こちらは参考情報です（獣医師監修：上手健太郎／南相馬動物病院）。具体的なケアについては獣医師にご相談ください。",
        "primary_care_plan_en": "This is reference information (supervised by Kentaro Kaimide, DVM / Minamisoma Vet Clinic). Please consult a veterinarian for specific care.",
        "supplements": supplements,
        "diagnostic_tests": [
            {
                "test_id": test_id,
                "test_name_ja": test_id.replace("_", " ").title(),
                "test_name_en": test_id.replace("_", " ").title(),
                "priority": idx + 1,
                "description_ja": "獣医師指示による検査",
                "description_en": "Veterinary recommended test",
            }
            for idx, test_id in enumerate(disease_record.get("recommended_tests", [])[:3])
        ],
        "follow_up_schedule_ja": "初診より2週間後の再診を推奨",
        "follow_up_schedule_en": "Follow-up recommended in 2 weeks",
    }

    return recommendations
