"""Symptom alias dictionary for natural language matching.

Maps JP/EN colloquial expressions to canonical symptom IDs.
530+ aliases covering veterinary clinical terminology.
"""

SYMPTOM_ALIASES = {
    # English variants
    "cough": "coughing",
    "coughs": "coughing",
    "coughing": "coughing",
    "sneeze": "sneezing",
    "sneezes": "sneezing",
    "sneezing": "sneezing",
    "runny nose": "nasal_discharge",
    "nasal discharge": "nasal_discharge",
    "discharge": "nasal_discharge",
    "breathing difficulty": "labored_breathing",
    "breathing problems": "labored_breathing",
    "labored breathing": "labored_breathing",
    "gasping": "labored_breathing",
    "not breathing": "labored_breathing",
    "cyanosis": "labored_breathing",
    "cyanotic": "labored_breathing",
    "reverse sneeze": "reverse_sneezing",
    "reverse sneezing": "reverse_sneezing",
    "wheeze": "wheezing",
    "wheezing": "wheezing",
    "vomit": "vomiting",
    "vomiting": "vomiting",
    "throw up": "vomiting",
    "throws up": "vomiting",
    "diarrhea": "diarrhea",
    "diarrhoea": "diarrhea",
    "loose stool": "diarrhea",
    "loose stools": "diarrhea",
    "no appetite": "loss_of_appetite",
    "loss of appetite": "loss_of_appetite",
    "not eating": "loss_of_appetite",
    "anorexia": "loss_of_appetite",
    "drool": "excessive_drooling",
    "drooling": "excessive_drooling",
    "excessive drool": "excessive_drooling",
    "bloat": "bloating",
    "bloating": "bloating",
    "abdominal distension": "bloating",
    "constipation": "constipation",
    "not pooping": "constipation",
    "blood in stool": "blood_in_stool",
    "bloody stool": "blood_in_stool",
    "bloody diarrhea": "blood_in_stool",
    "seizure": "seizures",
    "seizures": "seizures",
    "fits": "seizures",
    "convulsion": "seizures",
    "limping": "lameness_or_limping",
    "lameness": "lameness_or_limping",
    "lame": "lameness_or_limping",
    "leg pain": "lameness_or_limping",
    "swelling": "lameness_or_limping",
    "joint pain": "joint_pain_or_stiffness",
    "joint stiffness": "joint_pain_or_stiffness",
    "stiff": "joint_pain_or_stiffness",
    "arthritis": "joint_pain_or_stiffness",
    "tremor": "tremors",
    "tremors": "tremors",
    "shaking": "tremors",
    "shakes": "tremors",
    "paralysis": "paralysis_or_paresis",
    "paresis": "paralysis_or_paresis",
    "paralyzed": "paralysis_or_paresis",
    "can't move": "paralysis_or_paresis",
    "lump": "lumps_and_bumps",
    "lumps": "lumps_and_bumps",
    "bump": "lumps_and_bumps",
    "lumpy": "lumps_and_bumps",
    "pee frequently": "frequent_urination",
    "frequent urination": "frequent_urination",
    "peeing a lot": "frequent_urination",
    "polyuria": "frequent_urination",
    "pollakiuria": "frequent_urination",
    "urinating often": "frequent_urination",
    "small frequent urination": "frequent_urination",
    "blood in urine": "blood_in_urine",
    "bloody urine": "blood_in_urine",
    "red urine": "blood_in_urine",
    "pink urine": "blood_in_urine",
    "hematuria": "blood_in_urine",
    "straining to pee": "straining_to_urinate",
    "straining to urinate": "straining_to_urinate",
    "difficult urination": "straining_to_urinate",
    "dysuria": "straining_to_urinate",
    "stranguria": "straining_to_urinate",
    "painful urination": "straining_to_urinate",
    "crying when urinating": "straining_to_urinate",
    "vocalizing in litter box": "straining_to_urinate",
    "posturing to urinate": "straining_to_urinate",
    "unable to urinate": "straining_to_urinate",
    "can't urinate": "straining_to_urinate",
    "cant urinate": "straining_to_urinate",
    "only drops of urine": "straining_to_urinate",
    "cloudy urine": "cloudy_urine",
    "turbid urine": "cloudy_urine",
    "smelly urine": "foul_smelling_urine",
    "strong urine odor": "foul_smelling_urine",
    "foul-smelling urine": "foul_smelling_urine",
    "incontinence": "incontinence",
    "incontinent": "incontinence",
    "peeing in house": "incontinence",
    "leaking urine": "incontinence",
    "drinking a lot": "excessive_thirst",
    "excessive thirst": "excessive_thirst",
    "polydipsia": "excessive_thirst",
    "eye discharge": "eye_discharge",
    "eye gunk": "eye_discharge",
    "discharge from eyes": "eye_discharge",
    "red eyes": "redness_in_eyes",
    "eye redness": "redness_in_eyes",
    "redness in eyes": "redness_in_eyes",
    "conjunctivitis": "redness_in_eyes",
    "cloudy eyes": "cloudiness_in_eyes",
    "cloudiness in eyes": "cloudiness_in_eyes",
    "eye cloudiness": "cloudiness_in_eyes",
    "cataracts": "cloudiness_in_eyes",
    "squinting": "squinting",
    "squint": "squinting",
    "eye swelling": "eye_swelling",
    "swollen eyes": "eye_swelling",
    "eyes puffed up": "eye_swelling",
    "exercise intolerance": "exercise_intolerance",
    "can't exercise": "exercise_intolerance",
    "tires easily": "exercise_intolerance",
    "tired": "exercise_intolerance",
    "fainting": "fainting",
    "faints": "fainting",
    "syncope": "fainting",
    "collapses": "fainting",
    "fast breathing": "rapid_breathing",
    "rapid breathing": "rapid_breathing",
    "tachypnea": "rapid_breathing",
    "panting": "rapid_breathing",
    "lethargy": "lethargy",
    "lethargic": "lethargy",
    "depression": "lethargy",
    "sluggish": "lethargy",
    "no energy": "lethargy",
    "aggression": "aggression",
    "aggressive": "aggression",
    "irritability": "aggression",
    "irritable": "aggression",
    "anxiety": "anxiety",
    "anxious": "anxiety",
    "restlessness": "anxiety",
    "restless": "anxiety",
    "nervous": "anxiety",
    "excessive licking": "excessive_licking",
    "licking": "excessive_licking",
    "licks": "excessive_licking",
    "lick dermatitis": "excessive_licking",
    "fever": "fever",
    "high temperature": "fever",
    "pyrexia": "fever",
    "hot": "fever",
    "weight loss": "weight_loss",
    "losing weight": "weight_loss",
    "thin": "weight_loss",
    "swollen lymph nodes": "swollen_lymph_nodes",
    "lymphadenopathy": "swollen_lymph_nodes",
    "lymph node swelling": "swollen_lymph_nodes",
    "bumps under skin": "swollen_lymph_nodes",
    "pale gums": "pale_gums",
    "gum color pale": "pale_gums",
    "pallor": "pale_gums",
    "pale": "pale_gums",
    "jaundice": "jaundice",
    "yellowing": "jaundice",
    "yellow gums": "jaundice",
    "yellow skin": "jaundice",
    "icterus": "jaundice",
    # Japanese entries - formal/medical
    "咳": "coughing",
    "くしゃみ": "sneezing",
    "鼻水": "nasal_discharge",
    "呼吸困難": "labored_breathing",
    "チアノーゼ": "labored_breathing",
    "息をしてない": "labored_breathing",
    "息をしていない": "labored_breathing",
    "逆くしゃみ": "reverse_sneezing",
    "喘鳴": "wheezing",
    "嘔吐": "vomiting",
    "下痢": "diarrhea",
    "食欲不振": "loss_of_appetite",
    "よだれ": "excessive_drooling",
    "腹部膨満": "bloating",
    "便秘": "constipation",
    "血便": "blood_in_stool",
    "けいれん": "seizures",
    "発作": "seizures",
    "跛行": "lameness_or_limping",
    "関節痛": "joint_pain_or_stiffness",
    "振戦": "tremors",
    "麻痺": "paralysis_or_paresis",
    "しこり": "lumps_and_bumps",
    "頻尿": "frequent_urination",
    "少量ずつ頻回排尿": "frequent_urination",
    "ポラキウリア": "frequent_urination",
    "血尿": "blood_in_urine",
    "尿が赤い": "blood_in_urine",
    "尿がピンク": "blood_in_urine",
    "排尿困難": "straining_to_urinate",
    "排尿時痛": "straining_to_urinate",
    "有痛性排尿": "straining_to_urinate",
    "排尿時に鳴く": "straining_to_urinate",
    "トイレで力む": "straining_to_urinate",
    "尿が出ない": "decreased_urination",
    "尿が少ししか出ない": "straining_to_urinate",
    "ストランギュリア": "straining_to_urinate",
    "ディスユリア": "straining_to_urinate",
    "尿が濁る": "cloudy_urine",
    "混濁尿": "cloudy_urine",
    "尿臭が強い": "foul_smelling_urine",
    "尿のにおいが強い": "foul_smelling_urine",
    "悪臭尿": "foul_smelling_urine",
    "尿失禁": "incontinence",
    "多飲": "excessive_thirst",
    "目やに": "eye_discharge",
    "目の充血": "redness_in_eyes",
    "目の白濁": "cloudiness_in_eyes",
    "目を細める": "squinting",
    "目を細めて": "squinting",
    "まぶしそう": "squinting",
    "目の腫れ": "eye_swelling",
    "運動不耐性": "exercise_intolerance",
    "失神": "fainting",
    "頻呼吸": "rapid_breathing",
    "無気力": "lethargy",
    "攻撃性": "aggression",
    "不安行動": "anxiety",
    "舐め行動": "excessive_licking",
    "発熱": "fever",
    "発熱している": "fever",
    "発熱しています": "fever",
    "発熱中": "fever",
    "体重減少": "weight_loss",
    "リンパ節腫脹": "swollen_lymph_nodes",
    "歯茎の蒼白": "pale_gums",
    "黄疸": "jaundice",
    # ---------------------------------------------------------------
    # 曖昧・口語表現 (colloquial/ambiguous Japanese expressions)
    # ---------------------------------------------------------------
    # 全身状態
    "元気がない": "lethargy",
    "元気がなく": "lethargy",
    "元気ない": "lethargy",
    "元気なくなった": "lethargy",
    "元気なく": "lethargy",
    "ぐったり": "lethargy",
    "ぐったりしてる": "lethargy",
    "ぐたっとしてる": "lethargy",
    "だるそう": "lethargy",
    "しんどそう": "lethargy",
    "動かない": "lethargy",
    "動きたがらない": "lethargy",
    "寝てばかり": "lethargy",
    "寝てばっかり": "lethargy",
    "起きない": "lethargy",
    "起きてこない": "lethargy",
    "おとなしい": "lethargy",
    "なんか変": "lethargy",
    "具合悪そう": "lethargy",
    "具合が悪い": "lethargy",
    "調子悪い": "lethargy",
    "調子が悪い": "lethargy",
    "様子がおかしい": "lethargy",
    "おかしい": "lethargy",
    "いつもと違う": "lethargy",
    "活気がない": "lethargy",
    "沈鬱": "lethargy",
    "嗜眠": "lethargy",
    "傾眠": "lethargy",
    "obtunded": "lethargy",
    "obtundation": "lethargy",
    "depressed": "lethargy",
    # NOTE: "depression" / "立てない" defined earlier — kept here as commented context only
    "起立不能": "weakness",
    "起き上がれない": "weakness",
    "横臥": "weakness",
    "横臥位": "weakness",
    "recumbency": "weakness",
    "recumbent": "weakness",
    "lateral recumbency": "weakness",
    # 食欲
    "食べない": "loss_of_appetite",
    "食べなくなった": "loss_of_appetite",
    "ご飯食べない": "loss_of_appetite",
    "ごはん食べない": "loss_of_appetite",
    "ご飯を食べない": "loss_of_appetite",
    "エサ食べない": "loss_of_appetite",
    "えさ食べない": "loss_of_appetite",
    "食が細い": "loss_of_appetite",
    "食欲がない": "loss_of_appetite",
    "食欲もない": "loss_of_appetite",
    "食欲なく": "loss_of_appetite",
    "食欲ない": "loss_of_appetite",
    "食欲減退": "loss_of_appetite",
    "食欲なくなった": "loss_of_appetite",
    "食べる量が減った": "loss_of_appetite",
    "フードを残す": "loss_of_appetite",
    "おやつしか食べない": "loss_of_appetite",
    # 獣医臨床用語（追加: 食欲廃絶=absolute anorexia, 食欲低下=hyporexia, 拒食=food refusal）
    "食欲廃絶": "loss_of_appetite",
    "食欲低下": "loss_of_appetite",
    "拒食": "loss_of_appetite",
    "摂食障害": "loss_of_appetite",
    # NOTE: "anorexia" mapped at top of dict — kept commented for context
    "hyporexia": "loss_of_appetite",
    "inappetence": "loss_of_appetite",
    "decreased appetite": "loss_of_appetite",
    "anorexic": "loss_of_appetite",
    # 食欲増進（多食）— 甲状腺機能亢進症・糖尿病・クッシングの主徴
    "食欲増加": "increased_appetite",
    "食欲増進": "increased_appetite",
    "食欲亢進": "increased_appetite",
    "多食": "increased_appetite",
    "過食": "increased_appetite",
    "よく食べるのに痩せる": "increased_appetite",
    # 飼い主の口語表現（「水をよく飲む 痩せてきた 食欲はすごくある」で
    # 多食が抽出されず、猫の甲状腺機能亢進症/糖尿病の古典的三徴が欠けていた）
    "食欲はすごくある": "increased_appetite",
    "食欲がすごい": "increased_appetite",
    "食欲旺盛": "increased_appetite",
    "食欲が増えた": "increased_appetite",
    "食べる量が増えた": "increased_appetite",
    "たくさん食べる": "increased_appetite",
    "よく食べる": "increased_appetite",
    "polyphagia": "increased_appetite",
    "increased appetite": "increased_appetite",
    "polyphagic": "increased_appetite",
    # 嘔吐
    "吐いた": "vomiting",
    "吐く": "vomiting",
    "吐いてる": "vomiting",
    "吐き気": "vomiting",
    "戻した": "vomiting",
    "もどした": "vomiting",
    "ゲロ": "vomiting",
    "げろ": "vomiting",
    "吐き戻し": "vomiting",
    "何回も吐く": "vomiting",
    "何度も吐く": "vomiting",
    "食べた後吐く": "vomiting",
    "草食べて吐く": "vomiting",
    "黄色い液を吐く": "vomiting",
    "白い泡を吐く": "vomiting",
    # 下痢
    "うんちがゆるい": "diarrhea",
    "軟便": "diarrhea",
    "水っぽいうんち": "diarrhea",
    "水様便": "diarrhea",
    "おなか壊した": "diarrhea",
    "お腹壊した": "diarrhea",
    "お腹こわした": "diarrhea",
    "お腹をこわした": "diarrhea",
    "ベタベタのうんち": "diarrhea",
    "ゆるいうんち": "diarrhea",
    "下痢してる": "diarrhea",
    "下痢気味": "diarrhea",
    "うんちの回数が多い": "diarrhea",
    # 便秘
    "うんちが出ない": "constipation",
    "うんちしない": "constipation",
    "排便しない": "constipation",
    "うんち出ない": "constipation",
    "いきんでる": "constipation",
    "いきんでいる": "constipation",
    "踏ん張ってる": "constipation",
    # 血便
    "うんちに血": "blood_in_stool",
    "血が混じったうんち": "blood_in_stool",
    "赤いうんち": "blood_in_stool",
    "黒いうんち": "blood_in_stool",
    "タール便": "blood_in_stool",
    # 咳
    "咳が出る": "coughing",
    "咳してる": "coughing",
    "咳する": "coughing",
    "せきする": "coughing",
    "せき": "coughing",
    "えずく": "coughing",
    "ケッケッ": "coughing",
    "ゲホゲホ": "coughing",
    "ガーガー": "coughing",
    "変な咳": "coughing",
    "乾いた咳": "coughing",
    "湿った咳": "coughing",
    # 呼吸
    "息が荒い": "rapid_breathing",
    "ハアハア": "rapid_breathing",
    "はあはあ": "rapid_breathing",
    "ゼーゼー": "wheezing",
    "ぜーぜー": "wheezing",
    "息苦しそう": "labored_breathing",
    "呼吸が辛そう": "labored_breathing",
    "呼吸がつらそう": "labored_breathing",
    "呼吸が早い": "rapid_breathing",
    "呼吸が荒い": "labored_breathing",
    "呼吸が苦しそう": "labored_breathing",
    "口で息してる": "labored_breathing",
    "口呼吸": "labored_breathing",
    "開口呼吸": "labored_breathing",
    # 鼻
    "鼻が出てる": "nasal_discharge",
    "鼻が詰まってる": "nasal_discharge",
    "鼻づまり": "nasal_discharge",
    "鼻汁": "nasal_discharge",
    "青っ鼻": "nasal_discharge",
    # くしゃみ
    "くしゃみする": "sneezing",
    "くしゃみが止まらない": "sneezing",
    "くしゃみが多い": "sneezing",
    # 水を飲む
    "水をたくさん飲む": "excessive_thirst",
    "水ばっかり飲む": "excessive_thirst",
    "水飲みすぎ": "excessive_thirst",
    "よく水を飲む": "excessive_thirst",
    "水をよく飲む": "excessive_thirst",
    "水がぶ飲み": "excessive_thirst",
    "多飲多尿": "excessive_thirst",
    "pu/pd": "excessive_thirst",
    "pu pd": "excessive_thirst",
    "pupd": "excessive_thirst",
    # 排尿
    "おしっこの回数が多い": "frequent_urination",
    "おしっこが多い": "frequent_urination",
    "何度もトイレに行く": "frequent_urination",
    "トイレが近い": "frequent_urination",
    "おしっこが出にくい": "straining_to_urinate",
    "おしっこが出ない": "decreased_urination",
    "おしっこ出ない": "straining_to_urinate",
    "おしっこに血": "blood_in_urine",
    "ピンクのおしっこ": "blood_in_urine",
    "赤いおしっこ": "blood_in_urine",
    "おしっこ漏れ": "incontinence",
    "おもらし": "incontinence",
    # 体重
    "痩せた": "weight_loss",
    "痩せてきた": "weight_loss",
    "やせた": "weight_loss",
    "やせてきた": "weight_loss",
    "ガリガリ": "weight_loss",
    "肋骨が見える": "weight_loss",
    "あばらが見える": "weight_loss",
    "削痩": "weight_loss",
    "るいそう": "weight_loss",
    "cachexia": "weight_loss",
    "cachectic": "weight_loss",
    "emaciation": "weight_loss",
    "emaciated": "weight_loss",
    "muscle wasting": "weight_loss",
    "筋萎縮": "weight_loss",
    # 足・歩行
    "足を引きずる": "lameness_or_limping",
    "足をひきずる": "lameness_or_limping",
    "びっこ": "lameness_or_limping",
    "足をかばう": "lameness_or_limping",
    "足を上げてる": "lameness_or_limping",
    "歩き方がおかしい": "lameness_or_limping",
    "歩けない": "lameness_or_limping",
    "立てない": "lameness_or_limping",
    "足が痛そう": "lameness_or_limping",
    "ふらふら": "ataxia",
    "フラフラ": "tremors",
    "ふらつき": "tremors",
    "よろよろ": "tremors",
    "ヨロヨロ": "tremors",
    "ふるえてる": "tremors",
    "震えてる": "tremors",
    "ブルブル": "tremors",
    "ぶるぶる": "tremors",
    "ガクガク": "tremors",
    # 発作・痙攣
    "ひきつけ": "seizures",
    "痙攣": "seizures",
    "ピクピク": "seizures",
    "バタバタ": "seizures",
    "白目向いてる": "seizures",
    "泡吹いてる": "seizures",
    "意識がない": "seizures",
    "意識ない": "seizures",
    "倒れた": "collapse",
    "倒れる": "collapse",
    "気絶": "collapse",
    "虚脱": "collapse",
    "コラプス": "collapse",
    "卒倒": "collapse",
    "ぐったりして倒れた": "collapse",
    "collapse": "collapse",
    "collapsed": "collapse",
    "collapsing": "collapse",
    # 皮膚 — 痒み表現は itching に直接解決（旧: excessive_licking 経由）。
    # itching↔excessive_licking は _ID_SYNONYMS で双方向ブリッジ済みなので、
    # どちらの語彙しか持たない種でも解決される。舐め行動そのものの表現のみ
    # excessive_licking を保持。
    "かゆい": "itching",
    "痒い": "itching",
    "かゆがる": "itching",
    "痒がる": "itching",
    "かゆがって": "itching",
    "痒がって": "itching",
    "掻いてる": "itching",
    "かいてる": "itching",
    "しきりに舐める": "excessive_licking",
    "体を掻く": "itching",
    "できもの": "lumps_and_bumps",
    "しこりがある": "lumps_and_bumps",
    "できものがある": "lumps_and_bumps",
    "腫瘍": "lumps_and_bumps",
    "ふくらみ": "lumps_and_bumps",
    "膨らんでる": "bloating",
    "腫れてる": "bloating",
    "お腹が張ってる": "bloating",
    "お腹が膨れて": "bloating",
    "お腹が張っている": "bloating",
    "腹が張っている": "bloating",
    "おなかが張っている": "bloating",
    "おなかが張ってる": "bloating",
    "おなかが膨れてる": "bloating",
    "お腹パンパン": "bloating",
    "腹部膨隆": "bloating",
    "distended abdomen": "bloating",
    "distended belly": "bloating",
    "distended stomach": "bloating",
    "abdominal distention": "bloating",
    "swollen abdomen": "bloating",
    "pot belly": "bloating",
    "pot-bellied": "bloating",
    "potbelly": "bloating",
    "pot-bellied appearance": "bloating",
    # 目
    "目が赤い": "redness_in_eyes",
    "目が白い": "cloudiness_in_eyes",
    "目が白くなった": "cloudiness_in_eyes",
    "目が曇ってる": "cloudiness_in_eyes",
    "目がしょぼしょぼ": "squinting",
    "涙が出る": "eye_discharge",
    "涙が多い": "eye_discharge",
    "涙目": "eye_discharge",
    "目が腫れてる": "eye_swelling",
    "まぶたが腫れてる": "eye_swelling",
    # よだれ
    "よだれが多い": "excessive_drooling",
    "よだれダラダラ": "excessive_drooling",
    "口からよだれ": "excessive_drooling",
    "涎": "excessive_drooling",
    # 発熱
    "熱がある": "fever",
    "熱っぽい": "fever",
    "体が熱い": "fever",
    "触ると熱い": "fever",
    "鼻が乾いてる": "fever",
    "耳が熱い": "fever",
    # 行動
    "噛みつく": "aggression",
    "唸る": "aggression",
    "怒りっぽい": "aggression",
    "攻撃的": "aggression",
    "落ち着かない": "anxiety",
    "落ち着きがない": "anxiety",
    "ウロウロ": "anxiety",
    "うろうろ": "anxiety",
    "そわそわ": "anxiety",
    "ソワソワ": "anxiety",
    # 夜鳴き: nocturnal vocalization is the classic sign of feline
    # hyperthyroidism/hypertension and canine CDS — map to
    # vocalization_changes (the legacy dog path bridges it to anxiety, a CDS
    # DISHA sign, via _LEGACY_FALLBACK).
    "夜鳴き": "vocalization_changes",
    "夜泣き": "vocalization_changes",
    "怖がる": "anxiety",
    # おしりこすり（スクーティング）— 肛門嚢疾患のパトグノモニックな主訴
    "おしりを地面にこすりつける": "scooting",
    "お尻を地面にこすりつける": "scooting",
    "おしりをこすりつける": "scooting",
    "お尻をこすりつける": "scooting",
    "おしりを引きずって歩く": "scooting",
    "お尻を引きずって歩く": "scooting",
    "おしり歩き": "scooting",
    "お尻歩き": "scooting",
    "スクーティング": "scooting",
    # 起立困難 — 変形性関節症・神経疾患の古典的主訴
    "立ち上がりにくい": "difficulty_standing",
    "立ち上がれない": "difficulty_standing",
    "立ち上がりが遅い": "difficulty_standing",
    "立ち上がるのがつらそう": "difficulty_standing",
    "立ち上がるのが大変そう": "difficulty_standing",
    # そのう膨満（鳥）— そ嚢うっ滞・サワークロップの主訴
    "そのうが膨らんでる": "crop_distension",
    "そのうがふくらんでる": "crop_distension",
    "そ嚢が膨らんでる": "crop_distension",
    "そのうが大きい": "crop_distension",
    "そのうがパンパン": "crop_distension",
    # その他
    "脱水": "excessive_thirst",
    "肌が黄色い": "jaundice",
    "白目が黄色い": "jaundice",
    "歯茎が白い": "pale_gums",
    "歯茎が蒼白": "pale_gums",
    "リンパが腫れてる": "swollen_lymph_nodes",
    "しこりが首にある": "swollen_lymph_nodes",
    "首が腫れてる": "swollen_lymph_nodes",
    "すぐ疲れる": "exercise_intolerance",
    "散歩行きたがらない": "exercise_intolerance",
    "散歩嫌がる": "exercise_intolerance",
    "運動嫌がる": "exercise_intolerance",
    "すぐバテる": "exercise_intolerance",
    "息切れ": "exercise_intolerance",
    # ---------------------------------------------------------------
    # 魚病用エイリアス (Fish disease aliases)
    # ---------------------------------------------------------------
    # 白点病
    "白い点": "white_spots",
    "白点": "white_spots",
    "白い斑点": "white_spots",
    "白い点々": "white_spots",
    "白いぶつぶつ": "white_spots",
    "ich": "white_spots",
    "white spot": "white_spots",
    "white dots": "white_spots",
    # 綿状付着物・水カビ
    "綿みたい": "cotton_like_growth",
    "綿状": "cotton_like_growth",
    "白いもやもや": "cotton_like_growth",
    "白いふわふわ": "cotton_like_growth",
    "カビ": "cotton_like_growth",
    "水カビ": "cotton_like_growth",
    "cotton": "cotton_like_growth",
    "fungus": "cotton_like_growth",
    # 鰭
    "ヒレがボロボロ": "fin_rot",
    "ひれがぼろぼろ": "fin_rot",
    "尾ぐされ": "fin_rot",
    "鰭が溶ける": "fin_rot",
    "ヒレが溶ける": "fin_rot",
    "fin rot": "fin_rot",
    "tail rot": "fin_rot",
    "ヒレをたたむ": "clamped_fins",
    "ひれをたたむ": "clamped_fins",
    "ヒレが閉じてる": "clamped_fins",
    "鰭をたたむ": "clamped_fins",
    "clamped fins": "clamped_fins",
    "ヒレが赤い": "fin_hemorrhage",
    "ヒレの充血": "fin_hemorrhage",
    # 体表
    "鱗が逆立つ": "raised_scales",
    "松かさ": "raised_scales",
    "鱗が逆立ってる": "raised_scales",
    "うろこが逆立ってる": "raised_scales",
    "お腹が膨れてきた": "bloating",
    "お腹膨れてる": "bloating",
    "目が飛び出してる": "pop_eye",
    "まつかさ": "raised_scales",
    "マツカサ": "raised_scales",
    "鱗が立ってる": "raised_scales",
    "うろこが逆立つ": "raised_scales",
    "pinecone": "raised_scales",
    "dropsy": "dropsy",
    "腹水": "dropsy",
    "ascites": "dropsy",
    "ascitic": "dropsy",
    "浮腫んでる": "dropsy",
    "むくんでる": "dropsy",
    "お腹が膨れてる": "bloating",
    "腹が膨れてる": "bloating",
    "体が膨らんでる": "bloating",
    "膨満": "bloating",
    "ただれ": "ulcers",
    "潰瘍": "ulcers",
    "穴が開いてる": "ulcers",
    "穴あき": "ulcers",
    "赤くなってる": "redness_skin",
    "充血": "redness_skin",
    "出血してる": "redness_skin",
    "赤い斑点": "redness_skin",
    "体表が赤い": "redness_skin",
    "粘液": "mucus_overproduction",
    "ぬめり": "mucus_overproduction",
    "ヌルヌル": "mucus_overproduction",
    "色が薄くなった": "discoloration",
    "退色": "discoloration",
    "色が変わった": "discoloration",
    "体が黒くなった": "dark_coloration",
    "黒ずんでる": "dark_coloration",
    "コショウ病": "gold_dust",
    "金粉": "gold_dust",
    "金色の粉": "gold_dust",
    "velvet": "gold_dust",
    # 眼（魚用 — dog用と重複しない表現のみ）
    "目が飛び出てる": "pop_eye",
    "目が出てる": "pop_eye",
    "ポップアイ": "pop_eye",
    "pop eye": "pop_eye",
    "目が白く濁ってる": "cloudy_eye",
    # 鰓
    "エラが赤い": "gill_redness",
    "鰓が赤い": "gill_redness",
    "エラが白い": "gill_paleness",
    "鰓が白い": "gill_paleness",
    "エラが腫れてる": "gill_swelling",
    "エラの動きが速い": "rapid_gill_movement",
    "鰓蓋パタパタ": "rapid_gill_movement",
    "エラをパタパタ": "rapid_gill_movement",
    # 行動（魚用 — dog用と重複しない表現のみ）
    "体を擦りつける": "flashing",
    "擦りつけ": "flashing",
    "底石にこすりつける": "flashing",
    "フラッシング": "flashing",
    "flashing": "flashing",
    "scratching": "flashing",
    "底にじっとしてる": "lethargy",
    "じっとしてる": "lethargy",
    "じっとしてて": "lethargy",
    "沈んでる": "lethargy",
    "パクパク": "gasping_surface",
    "鼻上げ": "gasping_surface",
    "水面でパクパク": "gasping_surface",
    "水面に上がってくる": "gasping_surface",
    "暴れる": "erratic_swimming",
    "急に暴れる": "erratic_swimming",
    "ビュンビュン泳ぐ": "erratic_swimming",
    "ひっくり返る": "swimming_upside_down",
    "転覆": "swimming_upside_down",
    "逆さま": "swimming_upside_down",
    "ひっくり返って泳ぐ": "swimming_upside_down",
    "upside down": "swimming_upside_down",
    "バランスが取れない": "loss_of_balance",
    "傾いてる": "loss_of_balance",
    "横になってる": "loss_of_balance",
    "listing": "loss_of_balance",
    "隠れてる": "hiding",
    "出てこない": "hiding",
    "群れから離れてる": "isolation",
    "旋回": "erratic_swimming",
    "くるくる回る": "erratic_swimming",
    # 排泄
    "白い糞": "white_stringy_feces",
    "白い糸みたいな糞": "white_stringy_feces",
    "透明な糞": "white_stringy_feces",
    "糞がぶら下がってる": "white_stringy_feces",
    # 寄生虫
    "イカリムシ": "anchor_worm",
    "糸みたいなのがついてる": "anchor_worm",
    "虫がついてる": "worm_like_parasites",
    "ウオジラミ": "worm_like_parasites",
    # 痩せ（魚用 — dog用 weight_loss と異なるID emaciation を使用）
    "魚が痩せた": "emaciation",
    "魚がやせた": "emaciation",
    "痩せ細った": "emaciation",
    # 背骨
    "背骨が曲がってる": "bent_spine",
    "体が曲がってる": "bent_spine",
    # 餌を食べない（魚用 — dog用と重複しない表現のみ）
    "餌を食べない": "loss_of_appetite",
    "エサを食べない": "loss_of_appetite",
    # 大量死
    "大量に死んでる": "mass_mortality",
    "何匹も死んだ": "mass_mortality",
    "次々死ぬ": "mass_mortality",
    "全滅": "mass_mortality",
    "突然死んだ": "sudden_death",
    # 過抱卵
    "卵が出ない": "egg_binding",
    "卵詰まり": "egg_binding",
    # ---------------------------------------------------------------
    # 全種共通の追加エイリアス（多種のSYMPTOM_NAMES IDにマッチ）
    # ---------------------------------------------------------------
    # 皮膚・被毛
    "毛が抜ける": "hair_loss",
    "毛が抜けてきた": "hair_loss",
    "脱毛": "hair_loss",
    "ハゲ": "hair_loss",
    "はげ": "hair_loss",
    "毛が薄い": "hair_loss",
    "毛並みが悪い": "hair_loss",
    "羽が抜ける": "hair_loss",
    "羽毛が抜ける": "hair_loss",
    "itching": "itching",
    "かゆそう": "itching",
    "掻く": "itching",
    "皮膚が赤い": "skin_lesions",
    "皮膚炎": "skin_lesions",
    "かさぶた": "skin_lesions",
    "フケ": "skin_lesions",
    "ふけ": "skin_lesions",
    "皮膚が荒れてる": "skin_lesions",
    # 頭部
    "首が傾いてる": "head_tilt",
    "首が曲がってる": "head_tilt",
    "首傾げてる": "head_tilt",
    "斜頸": "head_tilt",
    "head tilt": "head_tilt",
    # 眼
    "目が濁ってる": "cloudy_eyes",
    "目が白っぽい": "cloudy_eyes",
    # 呼吸
    "口を開けて呼吸": "open_mouth_breathing",
    "口開けてる": "open_mouth_breathing",
    "開口呼吸してる": "open_mouth_breathing",
    # 鳥
    "羽を膨らませてる": "fluffed_feathers",
    "羽を膨らませている": "fluffed_feathers",
    "もこもこしてる": "fluffed_feathers",
    # 爬虫類
    "脱皮不全": "dysecdysis",
    "脱皮がうまくいかない": "dysecdysis",
    "脱皮できない": "dysecdysis",
    "皮が残ってる": "dysecdysis",
    "retained shed": "dysecdysis",
    # 関節
    "足が腫れてる": "lameness_or_limping",
    # ---------------------------------------------------------------
    # 口腔・歯科
    # ---------------------------------------------------------------
    "口が臭い": "bad_breath",
    "口臭": "bad_breath",
    "息が臭い": "bad_breath",
    "よだれが出る": "excessive_drooling",
    "食べにくそう": "loss_of_appetite",
    "食べるのを嫌がる": "loss_of_appetite",
    # 口の痛みは疼痛IDに直接解決する（pain は ID_SYNONYMS で lethargy/vocalization に
    # フォールバックするため、pain を持たない種でも安全）。従来の excessive_drooling への
    # マッピングは「よだれ」と二重計上になるだけで、口内炎/FCGS の痛み情報が失われていた。
    "口を痛がる": "pain",
    "口を痛がって": "pain",
    "口が痛そう": "pain",
    "口を触ると嫌がる": "pain",
    # 「食べられない」= 摂食困難（口の問題で食べたいのに食べられない）
    "食べられない": "difficulty_eating",
    "食べたそうなのに食べない": "difficulty_eating",
    "歯が折れた": "excessive_drooling",
    "歯肉が赤い": "excessive_drooling",
    "口内炎": "oral_ulcers",
    "歯周病": "bad_breath",
    # ---------------------------------------------------------------
    # ウサギ追加
    # ---------------------------------------------------------------
    "うんちが小さい": "small_fecal_pellets",
    "糞が小さい": "small_fecal_pellets",
    "small feces": "small_fecal_pellets",
    "small droppings": "small_fecal_pellets",
    "small poops": "small_fecal_pellets",
    "うんちが少ない": "reduced_fecal_output",
    "糞が少ない": "reduced_fecal_output",
    "歯ぎしり": "teeth_grinding",
    "歯ぎしりしてる": "teeth_grinding",
    "お腹を痛がる": "abdominal_pain",
    "丸まってる": "abdominal_pain",
    "お腹を触ると嫌がる": "abdominal_pain",
    # ---------------------------------------------------------------
    # ハムスター追加
    # ---------------------------------------------------------------
    "お尻が濡れてる": "wet_tail",
    "おしりが汚れてる": "wet_tail",
    "ウェットテイル": "wet_tail",
    "wet tail": "wet_tail",
    "頬袋が腫れてる": "cheek_swelling",
    "頬が膨らんでる": "cheek_swelling",
    # ---------------------------------------------------------------
    # 爬虫類追加
    # ---------------------------------------------------------------
    "口を開けたまま": "open_mouth_breathing",
    "粘液が出る": "nasal_discharge",
    "口から粘液": "nasal_discharge",
    "骨が柔らかい": "soft_bones",
    "骨軟化": "soft_bones",
    "甲羅が柔らかい": "soft_bones",
    "甲羅がぶよぶよ": "soft_bones",
    "手足が変形してる": "bone_deformity",
    "顎が柔らかい": "jaw_softening",
    "代謝性骨疾患": "soft_bones",
    "mbd": "soft_bones",
    "後ろ足が弱い": "hind_limb_weakness",
    "後肢麻痺": "hind_limb_weakness",
    "後ろ足ふらふら": "hind_limb_weakness",
    "後ろ足に力が入らない": "hind_limb_weakness",
    "後肢が弱い": "hind_limb_weakness",
    "口の中に病変": "mouth_lesions",
    "口の中が腫れてる": "mouth_lesions",
    "口に粘液": "mucus_in_mouth",
    # ---------------------------------------------------------------
    # ハリネズミ追加
    # ---------------------------------------------------------------
    "針が抜ける": "quill_loss",
    "クイルロス": "quill_loss",
    "quilling": "hair_loss",
    "ふらふら歩く": "ataxia",
    "wobbly hedgehog": "ataxia",
    "後ろ足が動かなくなってきた": "paralysis_or_paresis",
    "ふらつく": "ataxia",
    "ふらついてる": "ataxia",
    "耳にかさぶた": "skin_lesions",
    # ---------------------------------------------------------------
    # 猫追加（臨床的に重要な症状）
    # ---------------------------------------------------------------
    "お腹が大きくなった": "bloating",
    "お腹が大きくなってきた": "bloating",
    "お腹が膨らんできた": "bloating",
    "急に後ろ足が動かなくなった": "paralysis_or_paresis",
    "後ろ足が冷たい": "cold_extremities",
    "痛がる": "pain",
    "鳴いて痛がる": "pain",
    "口の中が赤い": "stomatitis",
    "トイレで鳴く": "straining_to_urinate",
    "黄疸が出てる": "jaundice",
    # ---------------------------------------------------------------
    # ウサギ追加
    # ---------------------------------------------------------------
    "目が揺れてる": "nystagmus",
    "眼振": "nystagmus",
    "目がぐるぐる": "nystagmus",
    "お尻が汚れてる": "diarrhea",
    "ウジがわいてる": "diarrhea",
    "歯が伸びすぎ": "teeth_grinding",
    "歯が長い": "teeth_grinding",
    "噛み合わせが悪い": "teeth_grinding",
    # ---------------------------------------------------------------
    # 鳥追加
    # ---------------------------------------------------------------
    "吐き戻してる": "vomiting",
    "首を振る": "head_shaking",
    "尾を振る": "labored_breathing",
    "呼吸のたびに尾を振る": "labored_breathing",
    # 足底病変（ソアホック/バンブルフット/足底皮膚炎）は足特異的IDに解決し、
    # 足ID非保有種のみ ID_SYNONYMS 経由で跛行にフォールバックする。
    "足の裏が赤い": "foot_sores",
    "足の裏が腫れてる": "foot_sores",
    "足の裏が赤く腫れている": "foot_sores",
    "足裏が赤い": "foot_sores",
    "バンブルフット": "lameness_or_limping",
    "bumblefoot": "lameness_or_limping",
    # ---------------------------------------------------------------
    # 爬虫類追加
    # ---------------------------------------------------------------
    "目が腫れて開かない": "eye_swelling",
    "目が開かない": "eye_swelling",
    "甲羅に白い斑点": "skin_lesions",
    "甲羅が変色": "skin_lesions",
    "柔らかい部分がある": "soft_bones",
    # ---------------------------------------------------------------
    # 魚追加
    # ---------------------------------------------------------------
    "エラが腫れて": "gill_swelling",
    "エラが白くなった": "gill_paleness",
    # ---------------------------------------------------------------
    # モルモット追加
    # ---------------------------------------------------------------
    "関節が腫れてる": "swollen_joints",
    "関節が腫れて": "swollen_joints",
    "関節腫れ": "swollen_joints",
    "キーキー鳴く": "lethargy",
    "鳴き声が変": "lethargy",
    # ---------------------------------------------------------------
    # 獣医師監査: 追加エイリアス (全種共通 + 種別)
    # ---------------------------------------------------------------
    # 猫 — 耳（耳の痒みは ear_scratching → scratching_ears ブリッジで外耳炎/耳ダニがランク）
    "耳をかく": "ear_scratching",
    "耳が臭い": "ear_discharge",
    "黒い耳垢": "ear_discharge",
    "耳垢が多い": "ear_discharge",
    # 猫 — 眼
    "目をしょぼしょぼ": "squinting",
    "片目だけ涙": "eye_discharge",
    # 猫 — 体型
    "急に太った": "bloating",
    "お腹だけ大きい": "bloating",
    # 猫 — 脱水
    "脱水してる": "lethargy",
    # 猫 — 毛
    "毛艶が悪い": "weight_loss",
    # ウサギ
    "膿が出てる": "abscess",
    "下顎が腫れてる": "jaw_swelling",
    "目から膿が出る": "eye_discharge",
    "目から膿": "eye_discharge",
    "顔が腫れてる": "facial_swelling",
    "顔が腫れた": "facial_swelling",
    "うずくまってる": "hunched_posture",
    # ハムスター/ハリネズミ — 眼球突出
    "眼球突出": "eye_bulging",
    "頬袋が出たまま": "cheek_pouch_prolapse",
    "頬袋が戻らない": "cheek_pouch_prolapse",
    # 鳥
    "糞が水っぽい": "diarrhea",
    "糞が緑色": "diarrhea",
    "嘴が伸びてる": "loss_of_appetite",
    "嘴過長": "loss_of_appetite",
    "眠ってばかり": "lethargy",
    # モルモット
    "歯茎から出血": "bleeding_gums",
    "歯茎から血が出て": "bleeding_gums",
    "歯ぐきから出血": "bleeding_gums",
    "歯ぐきから血": "bleeding_gums",
    "壊血病": "weight_loss",
    # フェレット
    "低血糖": "lethargy",
    # 爬虫類
    "脱皮が途中で止まってる": "dysecdysis",
    "脱皮途中": "dysecdysis",
    "水疱": "skin_lesions",
    # 魚
    "ふわふわした白いもの": "cotton_like_growth",
    "白いもやもやがついてる": "cotton_like_growth",
    "白い綿": "cotton_like_growth",
    "急に死んだ": "sudden_death",
    # ---------------------------------------------------------------
    # 獣医師監査 第2回: 不足エイリアス追加
    # ---------------------------------------------------------------
    # 猫 — 耳疾患
    "耳だれ": "ear_discharge",
    "耳から臭い": "ear_discharge",
    "耳垢が黒い": "ear_discharge",
    "耳の中が汚い": "ear_discharge",
    "耳が痒い": "ear_scratching",
    "耳をかゆがる": "ear_scratching",
    # 猫 — 便秘（追加表現）
    "便が硬い": "constipation",
    "排便時に鳴く": "constipation",
    # ハムスター/ハリネズミ — 眼球突出
    "目が出てきた": "eye_bulging",
    "目が出ている": "eye_bulging",
    "目が大きくなった": "eye_bulging",
    "目が飛び出した": "eye_bulging",
    "目が膨らんでる": "eye_bulging",
    "眼が出てる": "eye_bulging",
    "目が丸くなってる": "eye_bulging",
    # ウサギ — 涙
    "涙が止まらない": "eye_discharge",
    "目の周りが汚れてる": "eye_discharge",
    "目の周りが濡れてる": "eye_discharge",
    # 鳥 — 毛引き/嘴
    # 毛引き（feather destructive behavior）は行動学的疾患で、受動的な羽毛脱落
    # （feather_loss/hair_loss）とは別概念。鳥語彙の feather_plucking に直接解決し、
    # feather_plucking を持たない種では ID_SYNONYMS 経由で feather_loss/self_mutilation
    # にフォールバックする（毛引き症とPBFDの鑑別はどちらも候補に残る）。
    "羽を抜いてる": "feather_plucking",
    "羽を抜いて": "feather_plucking",
    "羽をむしって": "feather_plucking",
    "羽をむしる": "feather_plucking",
    "自咬": "self_mutilation",
    "自分で羽を抜く": "feather_plucking",
    "毛引き": "feather_plucking",
    # 呼吸努力のテイルボビング（尾の上下動）— 鳥の呼吸困難の教科書的所見
    "尾が上下に動": "tail_bobbing",
    "尾が上下して": "tail_bobbing",
    "尻尾が上下に動": "tail_bobbing",
    "テイルボビング": "tail_bobbing",
    "嘴が長い": "loss_of_appetite",
    # モルモット — 壊血病の症状
    "歯茎が腫れてる": "bleeding_gums",
    "関節が痛そう": "swollen_joints",
    "毛がバサバサ": "hair_loss",
    # フェレット — 副腎
    "外陰部が腫れてる": "vulvar_swelling",
    "外陰部腫大": "vulvar_swelling",
    "尻尾の毛が抜ける": "hair_loss",
    "体の毛が薄くなった": "hair_loss",
    "前立腺が大きい": "prostatic_enlargement",
    # 爬虫類 — 甲羅/寄生虫
    "甲羅がカビみたい": "shell_discoloration",
    "甲羅が白い": "shell_discoloration",
    "甲羅が変色してる": "shell_discoloration",
    "便に虫がいる": "diarrhea",
    "虫が出た": "diarrhea",
    "寄生虫": "diarrhea",
    # ウサギ — 肛門/子宮
    "肛門が腫れてる": "perineal_swelling",
    "肛門周囲が腫れ": "perineal_swelling",
    "陰部から出血": "blood_in_urine",
    # 鳥 — 貧血
    "貧血": "lethargy",
    "anemia": "lethargy",
    "黒い便": "blood_in_stool",
    # ---------------------------------------------------------------
    # 獣医師監査 第3回
    # ---------------------------------------------------------------
    # 体重・体型
    "太ってきた": "weight_gain",
    "太った": "weight_gain",
    "毛が薄くなった": "hair_loss",
    "寒がる": "lethargy",
    # 鳥 — そのう
    "口をパクパク": "vomiting",
    "口をパクパクさせてる": "vomiting",
    "泡が出てる": "vomiting",
    "口から泡": "vomiting",
    # フェレット
    "まだらに抜ける": "hair_loss",
    "腫瘤": "lumps_and_bumps",
    "お腹に腫瘤": "lumps_and_bumps",
    # 魚 — 白点病補強
    "白い点々が全身に": "white_spots",
    "エラが速く動いてる": "rapid_gill_movement",
    # ハリネズミ
    "毛が逆立ってる": "lethargy",
    # ---------------------------------------------------------------
    # 獣医師監査 第4回: 日本語チャット精度向上
    # ---------------------------------------------------------------
    # 体型・体重 (修正: 太った=weight_gain, not weight_loss)
    "体重が増えた": "weight_gain",
    "体重増加": "weight_gain",
    # 皮膚
    "皮膚がカサカサ": "dry_skin",
    "カサカサしてる": "dry_skin",
    "肌がカサカサ": "dry_skin",
    "粉ふいてる": "dry_skin",
    # 四肢冷感
    "足が冷たい": "cold_extremities",
    "冷たい": "cold_extremities",
    "手足が冷たい": "cold_extremities",
    "末端が冷たい": "cold_extremities",
    # 虚脱・倒れる
    "崩れ落ちた": "collapse",
    "バタッと倒れた": "collapse",
    # 呼吸 (鳥・爬虫類向け)
    "口を開けて息してる": "open_mouth_breathing",
    "息が苦しそう": "labored_breathing",
    # 魚 — 擦り付け行動
    "体を擦り付ける": "flashing",
    "擦り付けてる": "flashing",
    "体をこすりつける": "flashing",
    "底砂に体を擦る": "flashing",
    # ハリネズミ — 針
    "針がボロボロ抜ける": "quill_loss",
    "針がたくさん抜ける": "quill_loss",
    # --- 2026-03 追加: 曖昧な主訴 ---
    "具合が悪そう": "lethargy",
    "何か変": "lethargy",
    "動きが遅い": "lethargy",
    # --- 猫特有 ---
    "ゴロゴロ言わなくなった": "behavioral_changes",
    "毛玉を吐く": "vomiting",
    "トイレに何度も行く": "frequent_urination",
    # --- ウサギ特有 ---
    "盲腸便を食べない": "abnormal_cecotropes",
    # --- 鳥特有 ---
    "卵が詰まってる": "egg_binding",
    "羽がボロボロ": "feather_loss",
    "止まり木に止まれない": "weakness",
    "くちばしが伸びてる": "beak_deformity",
    # --- 魚特有 ---
    "底でじっとしている": "lethargy",
    "体が白い": "white_spots",
    # --- 犬特有 ---
    "後ろ足が立たない": "hind_leg_weakness",
    "散歩を嫌がる": "exercise_intolerance",
    "お座りできない": "hind_leg_weakness",
    "耳を掻く": "ear_scratching",
    "お尻を引きずる": "scooting",
    "目やにが多い": "eye_discharge",
    # --- フェレット特有 ---
    "しっぽが細い": "hair_loss",
    "後ろ足がふらつく": "hind_leg_weakness",
    # --- モルモット特有 ---
    "歯が伸びてる": "visible_tooth_overgrowth",
    # --- ハリネズミ特有 ---
    "丸まったまま": "lethargy",
    # --- English colloquial additions ---
    "not eating well": "loss_of_appetite",
    "off feed": "loss_of_appetite",
    "struggling to breathe": "labored_breathing",
    "can't walk": "paralysis",
    "wobbly gait": "ataxia",
    "stumbling": "ataxia",
    "blood in pee": "blood_in_urine",
    "blood in poop": "blood_in_stool",
    "puking": "vomiting",
    "throwing up": "vomiting",
    "swollen belly": "abdominal_distension",
    "lost weight": "weight_loss",
    "gaining weight": "weight_gain",
    "can't poop": "constipation",
    "itchy skin": "scratching",
    "bald patches": "hair_loss",
    "lumps on body": "lumps",
    "bad smell": "foul_odor",
    # ── チンチラ固有エイリアス (Chinchilla-specific aliases) ──
    "ファースリップ": "fur_loss_patches",
    "毛が抜けた": "fur_loss_patches",
    "毛が束で抜ける": "fur_loss_patches",
    "毛が束で抜けた": "fur_loss_patches",
    "毛が大量に抜けた": "fur_loss_patches",
    "fur slip": "fur_loss_patches",
    "毛噛み": "fur_chewing",
    "毛を噛んでいる": "fur_chewing",
    "毛を噛む": "fur_chewing",
    "自分の毛を噛む": "fur_chewing",
    "バーバリング": "fur_chewing",
    "fur chewing": "fur_chewing",
    "barbering": "fur_chewing",
    "砂浴びしない": "poor_coat",
    "砂浴びをしない": "poor_coat",
    "被毛がベタベタ": "poor_coat",
    "よだれで顎が濡れている": "wet_chin",
    "顎が濡れている": "wet_chin",
    "顎が汚れている": "wet_chin",
    "歯が伸びている": "visible_tooth_overgrowth",
    "歯ぎしりしている": "teeth_grinding",
    "食べ方がおかしい": "difficulty_eating",
    "えり好みする": "selective_eating",
    "ペレットしか食べない": "selective_eating",
    "牧草を食べない": "selective_eating",
    "暑がっている": "excessive_panting",
    "耳が赤い": "red_ears",
    "ぐったりしている": "lethargy",
    # ジャンプ回避は猫DJDの最重要飼い主所見（Lascelles 2010）— reluctance_to_jump に
    # 解決し、語彙に無い種は ID_SYNONYMS で reluctance_to_move へフォールバック
    "ジャンプしない": "reluctance_to_jump",
    "ジャンプしなくなった": "reluctance_to_jump",
    "陰茎に毛が巻きついている": "fur_ring_penis",
    "ペニスリング": "fur_ring_penis",
    "penile fur ring": "fur_ring_penis",
    "首が傾いている": "head_tilt",
    "お尻が汚い": "soiled_perineum",
    "お腹が膨れている": "abdominal_distension",
    "糞が出ない": "reduced_fecal_output",
    "便が出ない": "reduced_fecal_output",
    "痙攣している": "seizures",
    # ---------------------------------------------------------------
    # 両生類用エイリアス (Amphibian-specific aliases) — 重複なし
    # ---------------------------------------------------------------
    # 皮膚・体表
    "皮膚が白い": "white_patches_skin",
    "体が白くなった": "white_patches_skin",
    "白いカビ": "cotton_like_growth",
    "綿みたいなのがついてる": "cotton_like_growth",
    "体が赤い": "skin_redness",
    "お腹が赤い": "red_ventrum",
    "足が赤い": "red_legs",
    "レッドレッグ": "red_legs",
    "red leg": "red_legs",
    "red legs": "red_legs",
    "皮がむけてる": "skin_shedding",
    "皮膚がただれてる": "skin_ulcers",
    "皮膚に穴が開いてる": "skin_ulcers",
    "体にできものがある": "raised_nodules",
    "黒いできもの": "dark_skin_nodules",
    "体がぬるぬる": "excessive_mucus",
    "粘液が多い": "excessive_mucus",
    # 行動・全身 (重複する一般的表現は既存エイリアスに委譲)
    "太ってる": "obesity",
    # 浮腫・膨満
    "お腹が膨らんでる": "bloating",
    "体が膨れてる": "edema",
    "パンパンに膨れてる": "edema",
    "風船みたい": "edema",
    "balloon frog": "edema",
    "水ぶくれ": "skin_blistering",
    "体が浮いてる": "buoyancy_problems",
    "沈めない": "buoyancy_problems",
    "浮いたまま": "buoyancy_problems",
    # 呼吸
    "口を開けてる": "open_mouth_breathing",
    # 鰓（アホロートル等）
    "エラが縮んでる": "gill_shrinkage",
    "エラが小さくなった": "gill_shrinkage",
    "エラがカールしてる": "gill_curling",
    "エラにカビ": "cotton_like_growth",
    # 消化器 (重複する一般的表現は既存エイリアスに委譲)
    "フンが出ない": "constipation",
    "おしりから何か出てる": "cloacal_prolapse",
    # 骨格・四肢
    "足が曲がってる": "limb_deformity",
    "顎が変形してる": "jaw_deformity",
    "後ろ足が動かない": "paralysis",
    "足が細い": "spindly_legs",
    "指が黒くなった": "digit_necrosis",
    "指が取れた": "missing_digits",
    # 眼
    "目がくぼんでる": "sunken_eyes",
    # 神経
    "痙攣してる": "seizures",
    "ふらふらしてる": "incoordination",
    # 英語 (amphibian-specific)
    "shedding too much": "excessive_shedding",
    "skin peeling": "skin_shedding",
    "bloated frog": "bloating",
    "floating upside down": "buoyancy_problems",
    "not metamorphosing": "metamorphosis_failure",
    "won't transform": "metamorphosis_failure",
    "gills shrinking": "gill_shrinkage",
    "gill curl": "gill_curling",
    "spindly legs": "spindly_legs",
    "short tongue": "inability_to_feed",
    "can't catch food": "inability_to_feed",
    "chytrid": "skin_shedding",
    "ツボカビ": "skin_shedding",
    # ---------------------------------------------------------------
    # スパースカバレッジ症状の補強 (Sparse coverage symptom aliases)
    # ---------------------------------------------------------------
    # 口腔
    "mouth ulcer": "oral_ulcers",
    "mouth ulcers": "oral_ulcers",
    "mouth sores": "oral_ulcers",
    "mouth inflammation": "stomatitis",
    "oral inflammation": "stomatitis",
    "口臭がひどい": "foul_breath",
    "halitosis": "foul_breath",
    "飲水量が増えた": "increased_water_intake",
    # 骨格・四肢
    "足が変形してる": "bone_deformity",
    "骨が曲がってる": "bone_deformity",
    "bent legs": "bone_deformity",
    "limb deformity": "bone_deformity",
    "bowed legs": "bone_deformity",
    "よろよろしている": "ataxia",
    "wobbly": "ataxia",
    # 皮膚
    "フケが多い": "dandruff",
    "フケが出る": "dandruff",
    "かさぶたがある": "crusting",
    "scabs": "crusting",
    "scabby": "crusting",
    # 呼吸
    "ゼーゼーいってる": "wheezing",
    "ヒューヒュー音がする": "wheezing",
    "鼻水が出る": "nasal_discharge",
    # 眼
    "watery eyes": "epiphora",
    "tearing": "epiphora",
    # 行動・神経
    "ぐるぐる回る": "circling",
    "同じところを回る": "circling",
    "頭を壁に押し付ける": "head_pressing",
    "head pressing": "head_pressing",
    "体が震える": "tremors",
    "shivering": "tremors",
    # 泌尿
    "おしっこに血が混じる": "blood_in_urine",
    "おしっこが赤い": "blood_in_urine",
    # ---------------------------------------------------------------
    # 飼い主の日常表現（追加カバレッジ）
    # ---------------------------------------------------------------
    "血が出る": "bleeding",
    "出血": "bleeding",
    "血が止まらない": "bleeding",
    "体重が減った": "weight_loss",
    "ゴホゴホ": "coughing",
    "コンコン": "coughing",
    "ブルブル震える": "tremors",
    "腫れている": "swelling",
    "おなかがゴロゴロ": "abdominal_pain",
    "ヨダレ": "drooling",
    "歩き方が変": "limping",
    "ゲーゲー": "vomiting",
    "水ばかり飲む": "increased_water_intake",
    "丸まっている": "hunched_posture",
    "丸くなっている": "hunched_posture",
    # English pet owner phrases (additional)
    "runny eyes": "eye_discharge",
    "watery eye": "eye_discharge",
    "bald spots": "fur_loss_patches",
    "bald patch": "fur_loss_patches",
    "losing fur": "fur_loss_patches",
    "losing hair": "hair_loss",
    "won't walk": "reluctance_to_move",
    "stopped eating": "appetite_loss",
    "throwing up blood": "bloody_stool",
    "swollen eye": "eye_swelling",
    "puffy eye": "eye_swelling",
    "keeps scratching": "itching",
    "constantly scratching": "itching",
    "trouble breathing": "dyspnea",
    "hard to breathe": "dyspnea",
    "peeing blood": "blood_in_urine",
    "straining to poop": "straining_to_defecate",
    # ---------------------------------------------------------------
    # 繁殖関連症状（Reproductive Health）
    # ---------------------------------------------------------------
    # 異常出血・陰部分泌物
    "異常な出血": "genital_discharge",
    "出血がある": "genital_discharge",
    "血が出ている": "genital_discharge",
    "不正出血": "genital_discharge",
    "陰部からの出血": "genital_discharge",
    "陰部分泌物": "genital_discharge",
    "膣からの出血": "genital_discharge",
    "膣からの分泌": "genital_discharge",
    "abnormal bleeding": "genital_discharge",
    "vaginal bleeding": "genital_discharge",
    "genital discharge": "genital_discharge",
    "genital bleeding": "genital_discharge",
    "bleeding from genitals": "genital_discharge",
    "vaginal discharge": "genital_discharge",
    # 発情異常
    "発情がない": "prolonged_estrus",
    "ヒートが来ない": "prolonged_estrus",
    "発情がこない": "prolonged_estrus",
    "発情来ない": "prolonged_estrus",
    "無発情": "prolonged_estrus",
    "発情停止": "prolonged_estrus",
    "サイレントヒート": "prolonged_estrus",
    "隠れた発情": "prolonged_estrus",
    "no heat": "prolonged_estrus",
    "no estrus": "prolonged_estrus",
    "anoestrus": "prolonged_estrus",
    "silent heat": "prolonged_estrus",
    "not coming into heat": "prolonged_estrus",
    "absent estrus": "prolonged_estrus",
    # 乳腺関連
    "乳房が腫れている": "mammary_swelling",
    "乳房が大きくなった": "mammary_swelling",
    "乳房炎": "mammary_swelling",
    "乳房が硬い": "mammary_swelling",
    "乳房が熱い": "mammary_swelling",
    "乳房が痛い": "mammary_swelling",
    "乳が出ている": "mammary_swelling",
    "乳汁分泌": "mammary_swelling",
    "乳房から膿": "mammary_swelling",
    "乳房から液": "mammary_swelling",
    "swollen udder": "mammary_swelling",
    "inflamed udder": "mammary_swelling",
    "mastitis": "mammary_swelling",
    "swollen breast": "mammary_swelling",
    "hot udder": "mammary_swelling",
    "painful udder": "mammary_swelling",
    "lactation": "mammary_swelling",
    "milk production": "mammary_swelling",
    "discharge from udder": "mammary_swelling",
    "pus from udder": "mammary_swelling",
    # 難産関連
    "出産が進まない": "genital_discharge",
    "難産の兆候": "genital_discharge",
    "子犬が出てこない": "genital_discharge",
    "分娩困難": "genital_discharge",
    "陣痛が続いている": "genital_discharge",
    "出産で苦しんでいる": "genital_discharge",
    "長時間の陣痛": "genital_discharge",
    "分娩がこない": "genital_discharge",
    "prolonged labor": "genital_discharge",
    "dystocia signs": "genital_discharge",
    "labor not progressing": "genital_discharge",
    "difficult birth": "genital_discharge",
    "straining to give birth": "genital_discharge",
    "birth difficulty": "genital_discharge",
    "extended labor": "genital_discharge",
    "no puppies coming": "genital_discharge",
    # 胎児水腫・アナサーカ（新生子犬の全身浮腫）
    "子犬がむくんでいる": "swelling",
    "子犬が腫れている": "swelling",
    "新生子犬の浮腫": "swelling",
    "子犬の全身浮腫": "swelling",
    "生まれた子犬がパンパン": "swelling",
    "子犬が膨らんでいる": "bloated_abdomen",
    "アナサーカ": "swelling",
    "水腫胎児": "swelling",
    "ワルラス症候群": "swelling",
    "胎児水腫": "swelling",
    "子犬が大きすぎる": "swelling",
    "子犬がチアノーゼ": "difficulty_breathing",
    "子犬が青い": "difficulty_breathing",
    "子犬が息をしていない": "difficulty_breathing",
    "puppy swollen": "swelling",
    "swollen puppy": "swelling",
    "anasarca": "swelling",
    "walrus syndrome": "swelling",
    "walrus puppy": "swelling",
    "hydrops fetalis": "swelling",
    "fetal anasarca": "swelling",
    "water puppy": "swelling",
    "water baby puppy": "swelling",
    "neonatal edema": "swelling",
    "puppy edema": "swelling",
    "generalized edema puppy": "swelling",
    "puppy not breathing": "difficulty_breathing",
    "cyanotic puppy": "difficulty_breathing",
    # 流産・妊娠喪失
    "流産した": "genital_discharge",
    "子犬を失った": "genital_discharge",
    "妊娠がダメになった": "genital_discharge",
    "胎仔を失った": "genital_discharge",
    "流産の兆候": "genital_discharge",
    "妊娠を失った": "genital_discharge",
    "子猫が産まれなかった": "genital_discharge",
    "仔馬を失った": "genital_discharge",
    "miscarriage": "genital_discharge",
    "abortion": "genital_discharge",
    "loss of puppies": "genital_discharge",
    "loss of kittens": "genital_discharge",
    "loss of foals": "genital_discharge",
    "pregnancy loss": "genital_discharge",
    "fetal loss": "genital_discharge",
    "miscarriage signs": "genital_discharge",
    # 精液・繁殖オス関連
    "精液が少ない": "genital_discharge",
    "精液が出ない": "genital_discharge",
    "精液がない": "genital_discharge",
    "精子が少ない": "genital_discharge",
    "精液異常": "genital_discharge",
    "精子異常": "genital_discharge",
    "精巣が腫れている": "genital_discharge",
    "精巣のしこり": "genital_discharge",
    "精巣が硬い": "genital_discharge",
    "陰嚢が腫れている": "genital_discharge",
    "poor semen quality": "genital_discharge",
    "low sperm count": "genital_discharge",
    "abnormal semen": "genital_discharge",
    "no sperm": "genital_discharge",
    "azoospermia": "genital_discharge",
    "testicular swelling": "genital_discharge",
    "testicular tumor": "genital_discharge",
    "swollen testes": "genital_discharge",
    "enlarged testicles": "genital_discharge",
    "hard testicles": "genital_discharge",
    # 子宮・生殖器感染
    "子宮感染": "genital_discharge",
    "子宮問題": "genital_discharge",
    "子宮の感染": "genital_discharge",
    "子宮内膜炎": "genital_discharge",
    "子宮蓄膿症": "genital_discharge",
    "膿が溜まった": "genital_discharge",
    "産後出血が続く": "genital_discharge",
    "産後感染": "genital_discharge",
    "uterine infection": "genital_discharge",
    "uterine problem": "genital_discharge",
    "endometritis": "genital_discharge",
    "pyometra": "genital_discharge",
    "pus accumulation": "genital_discharge",
    "postpartum infection": "genital_discharge",
    # 繁殖実績関連
    "受胎困難": "prolonged_estrus",
    "妊娠しない": "prolonged_estrus",
    "何度も妊娠しない": "prolonged_estrus",
    "不妊症": "prolonged_estrus",
    "受精卵着床不全": "prolonged_estrus",
    "着床不全": "prolonged_estrus",
    "失敗した交配": "prolonged_estrus",
    "受胎失敗": "prolonged_estrus",
    "failed conception": "prolonged_estrus",
    "infertility": "prolonged_estrus",
    "implantation failure": "prolonged_estrus",
    "conception failure": "prolonged_estrus",
    "breeding problems": "prolonged_estrus",
    "repeated breeding failures": "prolonged_estrus",
    # 乳汁分泌不全・乳房発育関連
    "乳汁が出ない": "mammary_swelling",
    "乳が出ていない": "mammary_swelling",
    "乳汁分泌が少ない": "mammary_swelling",
    "乳の分泌が悪い": "mammary_swelling",
    "乳房が発達していない": "mammary_swelling",
    "乳房の発育が悪い": "mammary_swelling",
    "分娩後乳房が腫れない": "mammary_swelling",
    "乳房が発育不十分": "mammary_swelling",
    "low milk supply": "mammary_swelling",
    "poor milk production": "mammary_swelling",
    "inadequate lactation": "mammary_swelling",
    "failed lactation": "mammary_swelling",
    "poor mammary development": "mammary_swelling",
    "underdeveloped udder": "mammary_swelling",
    # 胎盤停滞・分娩後関連
    "後産が出てこない": "genital_discharge",
    "胎盤が出ない": "genital_discharge",
    "分娩後の胎盤が出ない": "genital_discharge",
    "胎盤残留": "genital_discharge",
    "分娩後に膜が残る": "genital_discharge",
    "出産後に膜が出ない": "genital_discharge",
    "retained placenta": "genital_discharge",
    "retained fetal membranes": "genital_discharge",
    "afterbirth not coming out": "genital_discharge",
    "placenta not expelled": "genital_discharge",
    "retained membranes": "genital_discharge",
    "placental retention": "genital_discharge",
    # 陣痛・分娩困難関連
    "陣痛が弱い": "genital_discharge",
    "陣痛が来ない": "genital_discharge",
    "陣痛がない": "genital_discharge",
    "分娩陣痛が不足": "genital_discharge",
    "仔馬が出てこない": "genital_discharge",
    "仔犬が出てこない": "genital_discharge",
    "子猫が出てこない": "genital_discharge",
    "分娩が止まった": "genital_discharge",
    "分娩が進行しない": "genital_discharge",
    "出産が停滞": "genital_discharge",
    "weak labor": "genital_discharge",
    "no contractions": "genital_discharge",
    "foal not coming": "genital_discharge",
    "puppy stuck": "genital_discharge",
    "kitten stuck": "genital_discharge",
    "delivery stalled": "genital_discharge",
    "uterine inertia": "genital_discharge",
    "labor halted": "genital_discharge",
    # 出産困難・仔馬救助関連
    "子馬が動かない": "genital_discharge",
    "子馬が出ない": "genital_discharge",
    "難産": "genital_discharge",
    "仔馬の難産": "genital_discharge",
    "出産時トラブル": "genital_discharge",
    "分娩援助が必要": "genital_discharge",
    "foal dystocia": "genital_discharge",
    "difficult foaling": "genital_discharge",
    "delivery complications": "genital_discharge",
    "birthing assistance needed": "genital_discharge",
    # 産道・膣関連損傷
    "産道が裂けた": "genital_discharge",
    "膣が裂けた": "genital_discharge",
    "会陰部が裂けた": "genital_discharge",
    "肛門と陰部の間が裂けた": "genital_discharge",
    "出産による外傷": "genital_discharge",
    "分娩による裂傷": "genital_discharge",
    "perineal laceration": "genital_discharge",
    "vaginal tear": "genital_discharge",
    "birth trauma": "genital_discharge",
    "genital tract injury": "genital_discharge",
    # --- Standard clinical terminology that was previously unmatched ---
    # Respiratory distress (clinical synonyms for labored breathing)
    "dyspnea": "labored_breathing",
    "dyspnoea": "labored_breathing",
    "dyspneic": "labored_breathing",
    "respiratory distress": "labored_breathing",
    "increased respiratory effort": "labored_breathing",
    "呼吸窮迫": "labored_breathing",
    # GI hemorrhage (melena / hematochezia)
    "melena": "blood_in_stool",
    "black stool": "blood_in_stool",
    "black tarry stool": "blood_in_stool",
    "tarry stool": "blood_in_stool",
    "hematochezia": "blood_in_stool",
    "黒色便": "blood_in_stool",
    # Regurgitation (esophageal — distinct from vomiting; falls back to vomiting on legacy dog vocab)
    "regurgitation": "regurgitation",
    "regurgitate": "regurgitation",
    "regurgitating": "regurgitation",
    "食べ物を戻す": "regurgitation",
    # Generalized weakness
    "weakness": "weakness",
    "generalized weakness": "weakness",
    "脱力": "weakness",
    "全身の脱力": "weakness",
    # Ataxia / incoordination
    "ataxia": "ataxia",
    "incoordination": "ataxia",
    "運動失調": "ataxia",
    # Lymphadenopathy
    "enlarged lymph nodes": "swollen_lymph_nodes",
    "リンパ節腫大": "swollen_lymph_nodes",
    "リンパ節が腫れてる": "swollen_lymph_nodes",
    # --- 2026-08 精度監査 第2弾: 実臨床フレーズの抽出漏れ ---
    # 猫 動脈血栓塞栓症（ATE）: 「後ろ足が"突然"動かない」は既存キーの
    # 「後ろ足が動かない」に部分一致しないため抽出ゼロだった
    "後ろ足が突然動かない": "hind_limb_paralysis",
    "後肢が動かない": "hind_limb_paralysis",
    "後ろ足を引きずる": "hind_limb_weakness",
    "痛がって鳴く": "vocalization_changes",
    "鳴き叫ぶ": "vocalization_changes",
    # GDV: 非生産性嘔吐（吐きたそうで吐けない = GDVの定義的サイン）
    "吐きたそうで吐けない": "unproductive_retching",
    "吐こうとして吐けない": "unproductive_retching",
    "吐きたそうにしている": "unproductive_retching",
    "空嘔吐": "unproductive_retching",
    # 犬 外耳炎: 頭を振る（耳系の既存エイリアスと違い未登録だった）
    "頭を振る": "head_shaking",
    "頭をよく振る": "head_shaking",
    # 爬虫類 MBD: ひらがな表記（既存はソフト（漢字）のみ）
    "甲羅がやわらかい": "soft_bones",
    # 鳥: 「羽を膨らませて」（てる/ている/動かない等の続きに関わらず一致する前方形）
    "羽を膨らませて": "fluffed_feathers",
    "羽がふくらんでいる": "fluffed_feathers",
    # 猫 尿道閉塞: 排尿時の啼鳴
    "おしっこの時に鳴く": "vocalization_changes",
    "鳴き続ける": "vocalization_changes",
    "鳴く": "vocalization_changes",
    # 甲状腺機能亢進症の hallmark「食べるのに痩せる」
    "食べるのに痩せる": "weight_loss",
    "食べても痩せる": "weight_loss",
    "食べているのに痩せる": "weight_loss",
    # フェレット インスリノーマ triad（後肢のふらつき・ぼーっとする・流涎）
    "後ろ足のふらつき": "hind_leg_weakness",
    "後肢のふらつき": "hind_leg_weakness",
    "ぼーっとする": "staring",
    "ぼーっと": "staring",
    "ぼんやりしている": "staring",
    # （馬の疝痛行動サインは diagnostic_chat.EQUINE_SYMPTOM_ALIASES に登録 —
    #   馬チャットはこの辞書ではなく専用辞書で抽出するため）
    # 前方形（て形）: 「首が傾いて目が揺れている」のように後続語が続いても一致する
    "首が傾いて": "head_tilt",
    "首をかしげて": "head_tilt",
    "目が揺れて": "nystagmus",
    "眼が揺れて": "nystagmus",
    # 爬虫類 マウスロット（感染性口内炎）: 口腔内の膿・開口不能は定義的サイン
    "口の中に膿": "mouth_lesions",
    "口内に膿": "mouth_lesions",
    "口が閉じない": "mouth_lesions",
    "口の周りが汚れて": "mouth_lesions",
    # 口腔内のチーズ状（乾酪様）滲出物 — 爬虫類マウスロットの教科書的所見。
    # mucus_in_mouth は爬虫類系の語彙にのみ存在するため、他種では抽出段階で
    # 自動的に落ちる（誤爆しない）。
    "口の中にチーズ状": "mucus_in_mouth",
    "口の周りにチーズ状": "mucus_in_mouth",
    "口にチーズ状": "mucus_in_mouth",
    "口内にチーズ状": "mucus_in_mouth",
    "チーズ状の膿": "mucus_in_mouth",
    "チーズ様物質": "mucus_in_mouth",
    "乾酪様物質": "mucus_in_mouth",
    # --- 2026-08 第8回精度スイープで検出した抽出漏れ ---
    # 犬: 運動不耐（心疾患の飼い主表現）
    "座り込む": "exercise_intolerance",
    "座りこむ": "exercise_intolerance",
    "散歩の途中で止まる": "exercise_intolerance",
    # 犬: スクーティング（肛門嚢疾患の定義的サイン）
    "おしりを地面にこすりつけ": "scooting",
    "お尻を地面にこすりつけ": "scooting",
    "おしりをこすりつけ": "scooting",
    "お尻をこすりつけ": "scooting",
    "おしりを擦る": "scooting",
    "お尻を擦る": "scooting",
    # 内分泌性脱毛（クッシング/甲状腺機能低下の左右対称性脱毛）
    "左右対称に毛が抜け": "hair_loss",
    "左右対称に抜け": "hair_loss",
    "毛が薄くなって": "hair_loss",
    # 疼痛姿勢（IVDD等）: 背中を丸める → hunched_posture
    # （ID_SYNONYMS で abdominal_pain、犬レガシーでは reluctance_to_move に解決）
    "背中を丸めて": "hunched_posture",
    "背中を丸めながら": "hunched_posture",
    # 振戦の部位付き表現（「震えてる」だけでは「足が震える」を取りこぼしていた）
    "足が震え": "tremors",
    "脚が震え": "tremors",
    # 爬虫類MBD: 四肢の弯曲（limb_deformity → ID_SYNONYMS で soft_bones 等に解決）
    "脚が曲がって": "limb_deformity",
    "手足が曲がって": "limb_deformity",
    # 直腸脱/クロアカ脱の飼い主表現（rectal_prolapse → ID_SYNONYMS で
    # rectal_protrusion/cloacal_prolapse に解決。該当IDのない種では安全に脱落）
    "お尻から赤いもの": "rectal_prolapse",
    "お尻から何かが出て": "rectal_prolapse",
    "お尻から何か出て": "rectal_prolapse",
    "肛門から何か出て": "rectal_prolapse",
    "肛門から赤いもの": "rectal_prolapse",
    # 注: 「脱腸」はマッピングしない — 獣医学的には鼠径/腹壁ヘルニアを指す用語であり、
    # 直腸脱に解決すると獣医師入力を誤誘導する
    # フェレット副腎疾患: 外陰部腫脹（「外陰部が腫れてる」だけでは
    # 「陰部が腫れている」を取りこぼしていた）
    "陰部が腫れて": "vulvar_swelling",
    "陰部の腫れ": "vulvar_swelling",
    # 尾部脱毛（フェレット副腎の初発サイン）
    "尻尾がハゲ": "hair_loss",
    "しっぽがハゲ": "hair_loss",
    "尻尾の毛が抜け": "hair_loss",
    "しっぽの毛が抜け": "hair_loss",
    # --- 2026-08 精度スイープ第6弾 ---
    # 爬虫類の脱皮不全: 「できない」形が欠落していた（「うまくいかない」のみ収載）
    "脱皮がうまくできない": "dysecdysis",
    "脱皮が残っている": "dysecdysis",
    "皮が残っている": "dysecdysis",
    # 空吐き・悪心の仕草（フェレット胃潰瘍/ヘリコバクターの古典徴候）
    "吐きそうにする": "unproductive_retching",
    "吐きそうな仕草": "unproductive_retching",
    # 鳥の神経徴候: 止まり木からの落下（重金属中毒・痙攣疾患の主訴）
    "止まり木から落ちる": "falling_off_perch",
    "止まり木から落ちた": "falling_off_perch",
    # 円形脱毛（皮膚糸状菌症の教科書的パターン）
    "毛が円形に抜ける": "circular_hair_loss",
    "円形に毛が抜ける": "circular_hair_loss",
    "円形脱毛": "circular_hair_loss",
    # 移動を嫌がる（疼痛の非特異的サイン、草食小動物で重要）
    "歩きたがらない": "reluctance_to_move",
    # --- 2026-08 ホットスポット/暑熱関連皮膚炎 ---
    # 「暑がっている」は既存（→excessive_panting）。基本形と口語形を補完。
    "暑がる": "excessive_panting",
    "暑そうにしている": "excessive_panting",
    # 湿潤性皮膚病変（ホットスポットの owner-reported 表現）。
    # hot_spots はレガシー犬語彙のID — 他種では ID_SYNONYMS 経由で
    # skin_lesions/skin_rashes にフォールバックする。
    "皮膚がジュクジュク": "hot_spots",
    "皮膚がじゅくじゅく": "hot_spots",
    "ジュクジュクしている": "hot_spots",
    "じゅくじゅくしている": "hot_spots",
    "ホットスポット": "hot_spots",
    "急に皮膚がただれた": "hot_spots",
    # 連用形（〜赤く…と続く複合文）は既存の「皮膚が赤い」ではマッチしない
    "皮膚が赤く": "skin_lesions",
    # 「舐めている/舐めてる」（しきりに舐める・executive licking の口語形）
    "舐めている": "excessive_licking",
    "よく舐める": "excessive_licking",
    # 発疹・湿疹・ブツブツ（皮疹の一般語が未収載だった）
    "発疹": "skin_rashes",
    "湿疹": "skin_rashes",
    "皮膚にブツブツ": "skin_rashes",
    "ブツブツができ": "skin_rashes",
    # --- 2026-08 稀少疾患乗っ取り監査 ---
    # 低体温・擬似冬眠（ハムスター/ハリネズミの torpor 主訴が抽出ゼロだった）。
    # cold_body 等は該当種の語彙にのみ存在 — 他種では抽出段階で安全に落ちる。
    "体が冷たい": "cold_body",
    "体が冷たくなって": "cold_body",
    "呼吸がゆっくり": "slow_breathing",
    "呼吸が遅い": "slow_breathing",
    "反応がない": "unresponsiveness",
    "反応が薄い": "unresponsiveness",
    "動かないが息はしている": "unresponsiveness",
    # --- 2026-08 精度スイープ第8弾 ---
    # 鼻出血（エピスタキシス）— 鼻腔内腫瘍・凝固障害（vWD）・真菌性鼻炎の主訴。
    # epistaxis はウサギ語彙の正規ID。犬レガシーDBにも同IDを追加済み。
    "鼻血": "epistaxis",
    "鼻から血": "epistaxis",
    "鼻から出血": "epistaxis",
    # 視覚喪失（白内障・PRA・緑内障）— 「物にぶつかる」は飼い主の定番表現
    "物にぶつかる": "vision_loss",
    "目が見えていない": "vision_loss",
    "目が見えてない": "vision_loss",
    "目が見えない": "vision_loss",
    "視力が落ちた": "vision_loss",
    "夜目が見えない": "vision_loss",
    # 白内障の飼い主表現（「目が白く濁っている」「目が白い」は既存 — 「見える」形が欠落）
    "目が白く見える": "cloudy_eyes",
    # EPI（膵外分泌不全）の hallmark: 大量の便（voluminous stool）
    "便の量が多い": "voluminous_stool",
    "便がたくさん出る": "voluminous_stool",
    "大量の便": "voluminous_stool",
    # 膝蓋骨脱臼のスキップ様歩行（飼い主の定番表現）
    "スキップするように歩く": "lameness_or_limping",
    "けんけんで歩く": "lameness_or_limping",
    "けんけん歩き": "lameness_or_limping",
    "後ろ足を上げて歩く": "lameness_or_limping",
    # 歯根膿瘍（眼窩下瘻管）: 顔面腫脹＋目の下からの排膿
    "顔が腫れて": "facial_swelling",
    "顔の片側が腫れて": "facial_swelling",
    "目の下から膿": "eye_discharge",
    "目の下が腫れて": "facial_swelling",
    # 猫の変形性関節症（DJD）: ジャンプ回避が最重要の飼い主観察所見（Lascelles 2010）
    "ジャンプを嫌がる": "reluctance_to_jump",
    "ジャンプできない": "reluctance_to_jump",
    "高いところに登らなくなった": "reluctance_to_jump",
    "段差を嫌がる": "reluctance_to_jump",
    # 心因性脱毛・過剰グルーミング
    "毛づくろいしすぎ": "excessive_grooming",
    "過剰な毛づくろい": "excessive_grooming",
    "毛づくろいが増えた": "excessive_grooming",
    "毛づくろいばかりして": "excessive_grooming",
    # 2026-08 第9回精度スイープ: 実主訴20例の抽出ゼロ・誤抽出を是正
    # 急性緑内障・眼球突出（「目が赤い」の連用形と「大きく見える」形が欠落していた）
    "目が赤く": "redness_in_eyes",
    "目が大きく見える": "eye_bulging",
    # 心不全の運動不耐・チアノーゼ（飼い主表現）—「すぐ疲れる」は既存キー
    "疲れやすい": "exercise_intolerance",
    "舌が紫": "cyanosis",
    "舌が青い": "cyanosis",
    "歯茎が紫": "cyanosis",
    # 頸部痛（IVDD頸部型の古典的主訴: 疼痛性啼鳴＋頸部保持）
    "キャンと鳴": "pain",
    "首を動かさない": "neck_stiffness",
    "首を触ると痛がる": "neck_stiffness",
    # 鳥の緑色便（ビリベルジン尿 — 肝疾患・オウム病の古典的所見）
    "便が緑": "diarrhea_green",
    "緑色の便": "diarrhea_green",
    "緑色の下痢": "diarrhea_green",
    # セキセイの呼吸器（副鼻腔炎・気嚢炎の飼い主表現）
    "呼吸のたびに音": "wheezing",
    "呼吸するたびに音": "wheezing",
    "呼吸音がする": "wheezing",
    "鼻の周りが汚れ": "nasal_discharge",
    # 爬虫類肺炎（かな表記「あけて」と鼻腔泡沫）
    "口をあけて呼吸": "open_mouth_breathing",
    "口をあけたまま": "open_mouth_breathing",
    "鼻から泡": "nasal_discharge",
    # チンチラ白癬（て形 — 「毛が円形に抜ける」の辞書形のみ収載だった）
    "毛が円形に抜けてる": "circular_hair_loss",
    # クイック入力ボタン新設分（リクガメ・ヘビ・両生類・デグー・フクロモモンガ）
    "甲羅に傷": "shell_lesions",
    "ダニがついてる": "visible_mites",
    "ダニが見える": "visible_mites",
    "皮膚に白いもの": "white_patches_skin",
    "尻尾の皮がむけた": "tail_injury",
    "しっぽの皮がむけた": "tail_injury",
    "自分を噛んでしまう": "self_mutilation",
    "自分を噛んでる": "self_mutilation",
    # --- 2026-08 第10回精度スイープ: 実主訴の抽出ゼロを是正 ---
    # 泌尿器（ポラキウリア連用形・猫の尿閉サイン）
    "おしっこの回数が多く": "frequent_urination",
    "トイレの回数が多い": "frequent_urination",
    "おしっこが少ししか出ない": "straining_to_urinate",
    "砂が濡れていない": "decreased_urination",
    "鳴きながらいきむ": "straining_to_urinate",
    # GDV（膨らんで形・吐こうとしても形）
    "お腹が膨らんで": "bloating",
    "お腹がふくらんで": "bloating",
    "吐こうとしても吐けない": "unproductive_retching",
    "吐こうとするが吐けない": "unproductive_retching",
    # 喉頭麻痺（GOLPP: 誤嚥性むせ＋声の変化）
    "むせる": "coughing",
    "むせている": "coughing",
    "声がかすれる": "voice_change",
    "声がかすれて": "voice_change",
    "声が変わった": "voice_change",
    "鳴き声がかすれる": "voice_change",
    # 消化器（ボルボリグミ＋草食べ＝悪心プロキシ）
    "お腹がキュルキュル": "stomach_gurgling",
    "お腹がゴロゴロ鳴": "stomach_gurgling",
    "草を食べたがる": "nausea",
    "草ばかり食べる": "nausea",
    # 眼（進行形「濁ってきた」）
    "目が白く濁ってきた": "cloudy_eye",
    "目が濁ってきた": "cloudy_eyes",
    # 鳥のテイルボビング（する形）と趾瘤症（て形・タコ表現）
    "尾が上下する": "tail_bobbing",
    "呼吸のたびに尾": "tail_bobbing",
    "足の裏が腫れて": "foot_sores",
    "タコのようになって": "foot_sores",
    # フェレット副腎（尾部脱毛の語順違い＋菲薄皮膚）
    "尻尾から毛が抜け": "hair_loss",
    "毛が尻尾から抜け": "hair_loss",
    "皮膚が薄い": "thinning_skin",
    "皮膚が薄く": "thinning_skin",
    # 猫ノトエドレス疥癬（耳介先端の痂皮）・カサカサのて形
    # （「耳にかさぶた」は既存キー(skin_lesions)を維持）
    "耳の先が黒く": "crusting",
    "カサカサして": "dry_skin",
    # 犬の趾間皮膚炎・アトピー（足舐め＋趾間紅斑）
    "足を舐め": "excessive_licking",
    "足の裏を舐め": "excessive_licking",
    "舐め続ける": "excessive_licking",
    "指の間が赤い": "skin_redness",
    "指の間が赤く": "skin_redness",
    # ポラキウリア（1回量の減少 — 飼い主表現では主語が省略されがち）
    "少ししか出ない": "straining_to_urinate",
}

# --- 縮約形「〜てる/〜でる」と完全形「〜ている/〜でいる」の相互補完 ---
# 口語エイリアスの多くは縮約形（「目が揺れてる」）のみ登録されており、
# 完全形（「目が揺れている」）の入力を取りこぼしていた（125キーで欠落）。
# 双方向に自動生成することで、どちらの形で入力されても同じ症状IDに解決する。
for _k, _v in list(SYMPTOM_ALIASES.items()):
    if _k.endswith("てる") or _k.endswith("でる"):
        SYMPTOM_ALIASES.setdefault(_k[:-1] + "いる", _v)
    elif _k.endswith("ている") or _k.endswith("でいる"):
        SYMPTOM_ALIASES.setdefault(_k[:-2] + "る", _v)
del _k, _v
