"""amphibian_diseases.py – 両生類の代表的な疾患

カエル、イモリ、サンショウウオなどの両生類に発生する代表的な疾患を網羅的に
取り上げ、簡易的な鑑別診断を提供するモジュールです。情報は教育目的であり、
専門的な診断や治療は獣医師が行うべきです。
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import analyze_symptoms_generic, ADVICE


SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "skin_shedding": {"ja": "皮膚の脱落", "en": "Skin shedding"},
    "excessive_shedding": {"ja": "過剰な脱皮", "en": "Excessive shedding"},
    "skin_discoloration": {"ja": "皮膚の変色", "en": "Skin discoloration"},
    "skin_ulcers": {"ja": "皮膚潰瘍", "en": "Skin ulcers"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "skin_sloughing": {"ja": "皮膚の剥離", "en": "Skin sloughing"},
    "white_patches_skin": {"ja": "皮膚の白斑", "en": "White patches on skin"},
    "cotton_like_growth": {"ja": "綿状の増殖物", "en": "Cotton-like growth on skin"},
    "raised_nodules": {"ja": "隆起性結節", "en": "Raised nodules"},
    "dark_skin_nodules": {"ja": "暗色皮膚結節", "en": "Dark skin nodules"},
    "skin_thickening": {"ja": "皮膚の肥厚", "en": "Skin thickening"},
    "hemorrhage": {"ja": "出血", "en": "Hemorrhage"},
    "petechiae": {"ja": "点状出血", "en": "Petechiae"},
    "red_legs": {"ja": "四肢の発赤", "en": "Red legs"},
    "red_ventrum": {"ja": "腹部の発赤", "en": "Red ventrum"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "abnormal_posture": {"ja": "異常な姿勢", "en": "Abnormal posture"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "seizures": {"ja": "痙攣", "en": "Seizures"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "incoordination": {"ja": "運動失調", "en": "Incoordination"},
    "soft_bones": {"ja": "骨軟化", "en": "Soft bones"},
    "jaw_deformity": {"ja": "顎の変形", "en": "Jaw deformity"},
    "limb_deformity": {"ja": "四肢の変形", "en": "Limb deformity"},
    "spinal_deformity": {"ja": "脊椎の変形", "en": "Spinal deformity"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "bloating": {"ja": "腹部膨満", "en": "Bloating"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "subcutaneous_gas": {"ja": "皮下ガス", "en": "Subcutaneous gas bubbles"},
    "buoyancy_problems": {"ja": "浮力異常", "en": "Buoyancy problems"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "intestinal_prolapse": {"ja": "腸脱", "en": "Intestinal prolapse"},
    "cloacal_prolapse": {"ja": "総排泄腔脱", "en": "Cloacal prolapse"},
    "gastric_prolapse": {"ja": "胃脱", "en": "Gastric prolapse"},
    "visible_worms": {"ja": "虫体の確認", "en": "Visible worms"},
    "dyspnea": {"ja": "呼吸困難", "en": "Dyspnea"},
    "open_mouth_breathing": {"ja": "開口呼吸", "en": "Open-mouth breathing"},
    "gasping": {"ja": "あえぎ呼吸", "en": "Gasping"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "corneal_opacity": {"ja": "角膜混濁", "en": "Corneal opacity"},
    "cataracts": {"ja": "白内障", "en": "Cataracts"},
    "sunken_eyes": {"ja": "眼窩陥没", "en": "Sunken eyes"},
    "dry_skin": {"ja": "乾燥肌", "en": "Dry skin"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "decreased_skin_elasticity": {"ja": "皮膚弾力低下", "en": "Decreased skin elasticity"},
    "mass_growth": {"ja": "腫瘤", "en": "Mass/growth"},
    "spindly_legs": {"ja": "細い四肢", "en": "Spindly legs"},
    "failure_to_thrive": {"ja": "発育不全", "en": "Failure to thrive"},
    "hyperactivity": {"ja": "過活動", "en": "Hyperactivity"},
    "erratic_swimming": {"ja": "異常遊泳", "en": "Erratic swimming"},
    "loss_of_righting_reflex": {"ja": "立ち直り反射消失", "en": "Loss of righting reflex"},
    "color_change": {"ja": "体色変化", "en": "Color change"},
    "excessive_mucus": {"ja": "過剰な粘液分泌", "en": "Excessive mucus production"},
    "abrasions": {"ja": "擦傷", "en": "Abrasions"},
    "wound": {"ja": "創傷", "en": "Wound"},
    "necrosis": {"ja": "壊死", "en": "Necrosis"},
    "tail_rot": {"ja": "尾腐れ", "en": "Tail rot"},
    "fin_rot": {"ja": "ひれ腐れ", "en": "Fin/gill rot"},
    "gill_abnormality": {"ja": "鰓異常", "en": "Gill abnormality"},
    "rapid_breathing": {"ja": "頻呼吸", "en": "Rapid breathing"},
    "organ_failure": {"ja": "臓器不全", "en": "Organ failure"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to move"},
    "inability_to_feed": {"ja": "摂食不能", "en": "Inability to feed"},
    "regurgitation": {"ja": "吐き戻し", "en": "Regurgitation"},
    "white_feces": {"ja": "白色便", "en": "White feces"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "pale_coloration": {"ja": "退色", "en": "Pale coloration"},
    # --- 追加症状 (DISEASES内で使用されている未登録項目) ---
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "appetite_loss": {"ja": "食欲低下", "en": "Appetite loss"},
    "bone_deformity": {"ja": "骨変形", "en": "Bone deformity"},
    "bone_weakness": {"ja": "骨脆弱", "en": "Bone weakness"},
    "chronic_edema": {"ja": "慢性浮腫", "en": "Chronic edema"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    "dark_skin_masses": {"ja": "暗色皮膚腫瘤", "en": "Dark skin masses"},
    "death": {"ja": "死亡", "en": "Death"},
    "dermatitis": {"ja": "皮膚炎", "en": "Dermatitis"},
    "extra_limbs": {"ja": "過剰肢", "en": "Extra limbs"},
    "failure_to_metamorphose": {"ja": "変態不全", "en": "Failure to metamorphose"},
    "gasping_at_surface": {"ja": "水面でのあえぎ", "en": "Gasping at surface"},
    "generalized_swelling": {"ja": "全身性腫脹", "en": "Generalized swelling"},
    "gill_curling": {"ja": "鰓のカール", "en": "Gill curling"},
    "gill_damage": {"ja": "鰓損傷", "en": "Gill damage"},
    "gill_irritation": {"ja": "鰓の刺激", "en": "Gill irritation"},
    "gill_necrosis": {"ja": "鰓壊死", "en": "Gill necrosis"},
    "gill_retention": {"ja": "鰓残存", "en": "Gill retention"},
    "gill_shrinkage": {"ja": "鰓萎縮", "en": "Gill shrinkage"},
    "gold_dust_appearance": {"ja": "金粉様外観", "en": "Gold dust appearance"},
    "granulomatous_lesions": {"ja": "肉芽腫性病変", "en": "Granulomatous lesions"},
    "hind_limb_weakness": {"ja": "後肢の衰弱", "en": "Hind limb weakness"},
    "immunosuppression": {"ja": "免疫抑制", "en": "Immunosuppression"},
    "inability_to_sink": {"ja": "沈降不能", "en": "Inability to sink"},
    "inability_to_use_limb": {"ja": "四肢使用不能", "en": "Inability to use limb"},
    "incontinence": {"ja": "失禁", "en": "Incontinence"},
    "internal_hemorrhage": {"ja": "内出血", "en": "Internal hemorrhage"},
    "intestinal_obstruction": {"ja": "腸閉塞", "en": "Intestinal obstruction"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "jaw_softening": {"ja": "顎軟化", "en": "Jaw softening"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "limb_swelling": {"ja": "四肢腫脹", "en": "Limb swelling"},
    "liver_enlargement": {"ja": "肝臓腫大", "en": "Liver enlargement"},
    "maggots_visible": {"ja": "蛆虫の確認", "en": "Maggots visible"},
    "metamorphosis_failure": {"ja": "変態失敗", "en": "Metamorphosis failure"},
    "missing_digits": {"ja": "指趾欠損", "en": "Missing digits"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "muscle_weakness": {"ja": "筋力低下", "en": "Muscle weakness"},
    "neck_swelling": {"ja": "頸部腫脹", "en": "Neck swelling"},
    "neurological_signs": {"ja": "神経症状", "en": "Neurological signs"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "orange_red_nodules": {"ja": "橙赤色結節", "en": "Orange-red nodules"},
    "organ_cysts": {"ja": "臓器嚢胞", "en": "Organ cysts"},
    "organ_enlargement": {"ja": "臓器腫大", "en": "Organ enlargement"},
    "pale_skin": {"ja": "皮膚蒼白", "en": "Pale skin"},
    "poor_appetite": {"ja": "食欲減退", "en": "Poor appetite"},
    "poor_shedding": {"ja": "脱皮不全", "en": "Poor shedding"},
    "rapid_death": {"ja": "急死", "en": "Rapid death"},
    "rapid_growth": {"ja": "急速な増殖", "en": "Rapid growth"},
    "respiratory_distress": {"ja": "呼吸窮迫", "en": "Respiratory distress"},
    "septicemia": {"ja": "敗血症", "en": "Septicemia"},
    "skin_blistering": {"ja": "皮膚水疱", "en": "Skin blistering"},
    "skin_cysts": {"ja": "皮膚嚢胞", "en": "Skin cysts"},
    "skin_erosion": {"ja": "皮膚びらん", "en": "Skin erosion"},
    "skin_hemorrhage": {"ja": "皮膚出血", "en": "Skin hemorrhage"},
    "skin_irritation": {"ja": "皮膚刺激", "en": "Skin irritation"},
    "skin_masses": {"ja": "皮膚腫瘤", "en": "Skin masses"},
    "skin_nodules": {"ja": "皮膚結節", "en": "Skin nodules"},
    "skin_papillomas": {"ja": "皮膚乳頭腫", "en": "Skin papillomas"},
    "skin_ulceration": {"ja": "皮膚潰瘍化", "en": "Skin ulceration"},
    "skin_vesicles": {"ja": "皮膚小水疱", "en": "Skin vesicles"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "stunted_growth": {"ja": "発育阻害", "en": "Stunted growth"},
    "tetany": {"ja": "テタニー", "en": "Tetany"},
    "tissue_necrosis": {"ja": "組織壊死", "en": "Tissue necrosis"},
    "tissue_protruding": {"ja": "組織突出", "en": "Tissue protruding"},
    "ulcerated_lesions": {"ja": "潰瘍性病変", "en": "Ulcerated lesions"},
    "ulceration": {"ja": "潰瘍形成", "en": "Ulceration"},
    "wart_like_growths": {"ja": "疣贅様増殖", "en": "Wart-like growths"},
    "white_fuzzy_appearance": {"ja": "白色綿毛状外観", "en": "White fuzzy appearance"},
    "wrinkled_skin": {"ja": "皮膚のしわ", "en": "Wrinkled skin"},
}


DISEASES: List[Dict[str, Any]] = [
    # ── Chytrid / Fungal ──────────────────────────────────────────────
    {
        "name": "Chytridiomycosis (Bd)",
        "name_ja": "ツボカビ症（Bd）",
        "symptoms": {"skin_shedding", "excessive_shedding", "skin_thickening", "lethargy", "anorexia", "loss_of_righting_reflex", "sudden_death"},
        "description": "Infection by Batrachochytrium dendrobatidis causing devastating epidermal disruption and electrolyte imbalance; responsible for global amphibian declines.",
        "description_ja": "ツボカビ菌（Bd）による感染で皮膚の電解質輸送が障害され、世界的な両生類減少の原因となっている致死的疾患。",
        "urgency": "emergency",
        "recommended_tests": ["PCR検査", "皮膚スクレイピング", "組織病理検査"],
    },
    {
        "name": "Chytridiomycosis (Bsal)",
        "name_ja": "ツボカビ症（Bsal）",
        "symptoms": {"skin_ulcers", "skin_lesions", "skin_sloughing", "anorexia", "lethargy", "sudden_death"},
        "description": "Infection by Batrachochytrium salamandrivorans primarily affecting salamanders; causes deep ulcerative skin lesions.",
        "description_ja": "Bsal菌による感染で主にサンショウウオ類に深部潰瘍性皮膚病変を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["PCR検査", "皮膚生検", "組織病理検査"],
    },
    {
        "name": "Saprolegniasis",
        "name_ja": "ミズカビ症",
        "symptoms": {"cotton_like_growth", "white_patches_skin", "skin_lesions", "lethargy", "anorexia"},
        "description": "Infection by Saprolegnia spp. causing cotton-like white growths on skin, eggs, and gills.",
        "description_ja": "ミズカビ属による感染で皮膚や卵に綿状の白色増殖物を形成する。",
        "urgency": "moderate",
        "recommended_tests": ["皮膚スクレイピング", "真菌培養", "顕微鏡検査"],
    },
    {
        "name": "Mucormycosis",
        "name_ja": "ムコール症",
        "symptoms": {"skin_lesions", "skin_discoloration", "necrosis", "lethargy", "anorexia"},
        "description": "Fungal infection by Mucor spp. causing tissue necrosis and systemic illness.",
        "description_ja": "ムコール属真菌による感染で組織壊死と全身症状を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["真菌培養", "組織病理検査", "皮膚生検"],
    },
    {
        "name": "Chromomycosis",
        "name_ja": "クロモミコーシス（黒色真菌症）",
        "symptoms": {"dark_skin_nodules", "raised_nodules", "skin_lesions", "skin_discoloration"},
        "description": "Chronic fungal infection causing dark pigmented nodular lesions in the skin.",
        "description_ja": "慢性真菌感染で皮膚に暗色の結節性病変を形成する。",
        "urgency": "moderate",
        "recommended_tests": ["皮膚生検", "真菌培養", "組織病理検査"],
    },
    # ── Bacterial ─────────────────────────────────────────────────────
    {
        "name": "Red Leg Syndrome",
        "name_ja": "レッドレッグ症候群",
        "symptoms": {"red_legs", "red_ventrum", "hemorrhage", "petechiae", "lethargy", "anorexia", "edema", "skin_ulcers"},
        "description": "Bacterial dermatosepticemia (often Aeromonas, Pseudomonas, or Citrobacter) causing erythema of ventral skin and limbs with systemic signs.",
        "description_ja": "エロモナスなどの細菌感染による皮膚敗血症で腹面や四肢の発赤と全身症状を示す。",
        "urgency": "high",
        "recommended_tests": ["細菌培養", "感受性試験", "血液検査", "皮膚スワブ"],
    },
    {
        "name": "Bacterial Dermatitis",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_redness", "skin_ulcers", "skin_lesions", "excessive_mucus", "lethargy"},
        "description": "Superficial bacterial infection of the skin, often secondary to trauma or poor water quality.",
        "description_ja": "外傷や水質悪化に続発する表在性細菌性皮膚感染症。",
        "urgency": "moderate",
        "recommended_tests": ["細菌培養", "感受性試験", "皮膚スクレイピング"],
    },
    {
        "name": "Mycobacteriosis",
        "name_ja": "マイコバクテリウム症",
        "symptoms": {"raised_nodules", "skin_lesions", "weight_loss", "anorexia", "lethargy", "bloating"},
        "description": "Chronic granulomatous infection by Mycobacterium spp. causing nodular lesions in skin and internal organs.",
        "description_ja": "マイコバクテリウム属による慢性肉芽腫性感染で皮膚や臓器に結節を形成する。",
        "urgency": "high",
        "recommended_tests": ["抗酸菌染色", "組織病理検査", "PCR検査", "細菌培養"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"lethargy", "anorexia", "hemorrhage", "petechiae", "red_ventrum", "edema", "sudden_death"},
        "description": "Systemic bacterial infection overwhelming the immune system; often rapidly fatal.",
        "description_ja": "細菌が血流に侵入し全身感染を引き起こす重篤な状態。",
        "urgency": "emergency",
        "recommended_tests": ["血液培養", "血液検査", "感受性試験"],
    },
    {
        "name": "Chlamydiosis",
        "name_ja": "クラミジア症",
        "symptoms": {"lethargy", "anorexia", "skin_lesions", "weight_loss", "organ_failure"},
        "description": "Infection by Chlamydia spp. causing systemic disease with hepatic and splenic involvement.",
        "description_ja": "クラミジア属による全身性感染で肝臓・脾臓障害を伴う。",
        "urgency": "high",
        "recommended_tests": ["PCR検査", "血液検査", "組織病理検査"],
    },
    # ── Viral ─────────────────────────────────────────────────────────
    {
        "name": "Ranavirus Infection",
        "name_ja": "ラナウイルス感染症",
        "symptoms": {"hemorrhage", "skin_ulcers", "edema", "lethargy", "anorexia", "organ_failure", "sudden_death"},
        "description": "Iridovirus family infection causing hemorrhagic disease with high mortality in amphibian populations.",
        "description_ja": "ラナウイルスによる出血性疾患で両生類集団に高い致死率をもたらす。",
        "urgency": "emergency",
        "recommended_tests": ["PCR検査", "ウイルス分離", "組織病理検査"],
    },
    {
        "name": "Iridovirus Infection (non-Ranavirus)",
        "name_ja": "イリドウイルス感染症（ラナウイルス以外）",
        "symptoms": {"skin_lesions", "lethargy", "anorexia", "hemorrhage", "edema", "sudden_death"},
        "description": "Infection by iridoviruses other than ranaviruses causing similar hemorrhagic and systemic disease.",
        "description_ja": "ラナウイルス以外のイリドウイルスによる出血性・全身性疾患。",
        "urgency": "high",
        "recommended_tests": ["PCR検査", "電子顕微鏡検査", "組織病理検査"],
    },
    {
        "name": "Herpesvirus Infection",
        "name_ja": "ヘルペスウイルス感染症",
        "symptoms": {"skin_lesions", "skin_ulcers", "lethargy", "anorexia", "organ_failure"},
        "description": "Herpesvirus infection reported in various frog species causing renal and skin disease.",
        "description_ja": "カエル類に報告されるヘルペスウイルス感染で腎臓・皮膚疾患を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["PCR検査", "組織病理検査", "ウイルス分離"],
    },
    # ── Parasitic ─────────────────────────────────────────────────────
    {
        "name": "Nematode Infection",
        "name_ja": "線虫感染症",
        "symptoms": {"weight_loss", "anorexia", "bloating", "diarrhea", "visible_worms", "lethargy"},
        "description": "Intestinal nematode parasitism causing malnutrition and gastrointestinal disturbance.",
        "description_ja": "腸管内線虫の寄生による栄養不良と消化器症状。",
        "urgency": "moderate",
        "recommended_tests": ["糞便検査", "浮遊法", "顕微鏡検査"],
    },
    {
        "name": "Trematode Infection",
        "name_ja": "吸虫感染症",
        "symptoms": {"bloating", "weight_loss", "anorexia", "limb_deformity", "edema", "lethargy"},
        "description": "Trematode parasites (flukes) infecting skin, kidneys, or other organs; some species cause limb malformations.",
        "description_ja": "吸虫類の寄生で皮膚、腎臓、その他臓器に障害を与え、一部の種は四肢奇形を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["糞便検査", "組織病理検査", "顕微鏡検査"],
    },
    {
        "name": "Coccidiosis",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "bloody_stool", "weight_loss", "anorexia", "lethargy", "dehydration"},
        "description": "Protozoal infection of the intestinal tract by Eimeria or Isospora spp.",
        "description_ja": "コクシジウム原虫による腸管感染で下痢や血便を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["糞便浮遊法", "糞便塗抹検査", "顕微鏡検査"],
    },
    {
        "name": "Myxosporean Infection",
        "name_ja": "粘液胞子虫感染症",
        "symptoms": {"skin_lesions", "raised_nodules", "bloating", "lethargy", "organ_failure"},
        "description": "Parasitic infection by myxosporean organisms forming cysts in various tissues.",
        "description_ja": "粘液胞子虫による各組織でのシスト形成を伴う寄生虫感染症。",
        "urgency": "moderate",
        "recommended_tests": ["組織病理検査", "顕微鏡検査", "湿潤標本検査"],
    },
    {
        "name": "Ichthyophthirius (White Spot Disease)",
        "name_ja": "白点病（イクチオフチリウス症）",
        "symptoms": {"white_patches_skin", "excessive_mucus", "skin_redness", "lethargy", "erratic_swimming", "gasping"},
        "description": "Parasitic skin infection by Ichthyophthirius multifiliis causing white spots on aquatic amphibian larvae.",
        "description_ja": "白点虫の寄生により水生両生類幼生の皮膚に白点を形成する。",
        "urgency": "moderate",
        "recommended_tests": ["皮膚スクレイピング", "顕微鏡検査", "水質検査"],
    },
    {
        "name": "Capillariasis",
        "name_ja": "毛細線虫症",
        "symptoms": {"weight_loss", "anorexia", "diarrhea", "lethargy", "weakness"},
        "description": "Infection by Capillaria spp. nematodes affecting the gastrointestinal tract.",
        "description_ja": "毛細線虫の消化管寄生による栄養障害と衰弱。",
        "urgency": "moderate",
        "recommended_tests": ["糞便検査", "顕微鏡検査"],
    },
    {
        "name": "Leech Infestation",
        "name_ja": "ヒル寄生症",
        "symptoms": {"skin_lesions", "hemorrhage", "anorexia", "lethargy", "pale_coloration"},
        "description": "External parasitism by leeches causing blood loss and secondary infections.",
        "description_ja": "ヒルの体表寄生による失血と二次感染。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "血液検査"],
    },
    # ── Metabolic / Nutritional ───────────────────────────────────────
    {
        "name": "Metabolic Bone Disease",
        "name_ja": "代謝性骨疾患",
        "symptoms": {"soft_bones", "jaw_deformity", "limb_deformity", "spinal_deformity", "fractures", "tremors", "weakness", "inability_to_feed"},
        "description": "Calcium, phosphorus, or vitamin D3 imbalance leading to skeletal deformities and pathological fractures.",
        "description_ja": "カルシウム・リン・ビタミンD3の不均衡による骨格変形と病的骨折。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "X線検査", "食事内容評価"],
    },
    {
        "name": "Hypovitaminosis A",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"cloudy_eyes", "skin_lesions", "skin_shedding", "anorexia", "lethargy", "eye_swelling"},
        "description": "Vitamin A deficiency causing squamous metaplasia of epithelial tissues, particularly the eyes.",
        "description_ja": "ビタミンA不足による上皮組織の扁平上皮化生、特に眼に顕著。",
        "urgency": "moderate",
        "recommended_tests": ["血液検査", "食事内容評価", "眼科検査"],
    },
    {
        "name": "Calcium Deficiency (Hypocalcemia)",
        "name_ja": "カルシウム欠乏症（低カルシウム血症）",
        "symptoms": {"tremors", "seizures", "weakness", "soft_bones", "tetany", "lethargy"},
        "description": "Acute or chronic calcium deficiency causing neuromuscular dysfunction.",
        "description_ja": "急性または慢性のカルシウム不足による神経筋機能障害。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "イオン化カルシウム測定", "食事内容評価"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"soft_bones", "weakness", "fractures", "limb_deformity", "lethargy", "anorexia"},
        "description": "Insufficient vitamin D3 from diet or UVB exposure leading to impaired calcium metabolism.",
        "description_ja": "食事またはUVB照射不足によるビタミンD3欠乏でカルシウム代謝が障害される。",
        "urgency": "moderate",
        "recommended_tests": ["血液検査", "X線検査", "飼育環境評価"],
    },
    {
        "name": "Thiamine Deficiency",
        "name_ja": "チアミン（ビタミンB1）欠乏症",
        "symptoms": {"incoordination", "seizures", "tremors", "weakness", "anorexia", "paralysis"},
        "description": "Vitamin B1 deficiency causing neurological dysfunction, often from fish-heavy diets containing thiaminase.",
        "description_ja": "チアミナーゼを含む魚類中心の食事によるビタミンB1欠乏で神経症状を呈する。",
        "urgency": "high",
        "recommended_tests": ["血液検査", "食事内容評価", "神経学的検査"],
    },
    # ── Water Quality / Toxicology ────────────────────────────────────
    {
        "name": "Ammonia Poisoning",
        "name_ja": "アンモニア中毒",
        "symptoms": {"skin_redness", "hemorrhage", "gasping", "erratic_swimming", "lethargy", "sudden_death", "gill_abnormality"},
        "description": "Toxic exposure to elevated ammonia levels in water causing gill and skin damage.",
        "description_ja": "水中アンモニア濃度上昇による鰓・皮膚の障害。",
        "urgency": "emergency",
        "recommended_tests": ["水質検査（アンモニア）", "鰓検査", "血液検査"],
    },
    {
        "name": "Nitrite Poisoning",
        "name_ja": "亜硝酸中毒",
        "symptoms": {"lethargy", "pale_coloration", "gasping", "erratic_swimming", "sudden_death"},
        "description": "Nitrite toxicity impairing oxygen transport (methemoglobinemia) in aquatic amphibians.",
        "description_ja": "亜硝酸塩の毒性によるメトヘモグロビン血症で酸素輸送が障害される。",
        "urgency": "emergency",
        "recommended_tests": ["水質検査（亜硝酸）", "血液検査"],
    },
    {
        "name": "Chlorine / Chloramine Toxicity",
        "name_ja": "塩素・クロラミン中毒",
        "symptoms": {"skin_redness", "excessive_mucus", "gasping", "erratic_swimming", "lethargy", "sudden_death"},
        "description": "Exposure to chlorinated tap water causing acute skin and gill damage.",
        "description_ja": "塩素処理水への曝露による急性の皮膚・鰓障害。",
        "urgency": "emergency",
        "recommended_tests": ["水質検査（残留塩素）", "身体検査"],
    },
    {
        "name": "Chemical Toxicity (Pesticides/Metals)",
        "name_ja": "化学物質中毒（農薬・重金属）",
        "symptoms": {"seizures", "incoordination", "lethargy", "anorexia", "sudden_death", "skin_lesions"},
        "description": "Poisoning from environmental contaminants such as pesticides, herbicides, or heavy metals.",
        "description_ja": "農薬、除草剤、重金属などの環境汚染物質による中毒。",
        "urgency": "emergency",
        "recommended_tests": ["毒物スクリーニング", "水質検査", "血液検査"],
    },
    {
        "name": "Ammonia Burn",
        "name_ja": "アンモニア熱傷",
        "symptoms": {"skin_redness", "skin_ulcers", "skin_lesions", "excessive_mucus", "lethargy"},
        "description": "Chemical burn to skin and mucous membranes from chronic elevated ammonia levels.",
        "description_ja": "慢性的なアンモニア高濃度環境による皮膚・粘膜の化学的熱傷。",
        "urgency": "moderate",
        "recommended_tests": ["水質検査", "皮膚検査", "身体検査"],
    },
    # ── Environmental / Physical ──────────────────────────────────────
    {
        "name": "Thermal Stress (Hyperthermia)",
        "name_ja": "温熱ストレス（高体温症）",
        "symptoms": {"hyperactivity", "erratic_swimming", "gasping", "lethargy", "seizures", "sudden_death"},
        "description": "Heat stress from excessively high environmental temperatures exceeding species tolerance.",
        "description_ja": "種の耐性を超える高温環境による熱ストレス。",
        "urgency": "high",
        "recommended_tests": ["環境温度測定", "身体検査"],
    },
    {
        "name": "Thermal Stress (Hypothermia)",
        "name_ja": "低温ストレス（低体温症）",
        "symptoms": {"lethargy", "anorexia", "weakness", "reluctance_to_move", "color_change"},
        "description": "Cold stress from environmental temperatures below species requirements.",
        "description_ja": "種の要求温度を下回る低温環境による低温ストレス。",
        "urgency": "moderate",
        "recommended_tests": ["環境温度測定", "身体検査"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"sunken_eyes", "dry_skin", "decreased_skin_elasticity", "lethargy", "anorexia", "weight_loss", "dehydration"},
        "description": "Fluid loss from inadequate humidity, soaking opportunities, or illness.",
        "description_ja": "湿度不足、浸水機会の欠如、または疾病による体液喪失。",
        "urgency": "high",
        "recommended_tests": ["身体検査", "血液検査", "飼育環境評価"],
    },
    {
        "name": "Trauma / Abrasions",
        "name_ja": "外傷・擦傷",
        "symptoms": {"abrasions", "wound", "hemorrhage", "skin_lesions", "lethargy", "anorexia"},
        "description": "Physical injuries from enclosure hazards, handling, or conspecific aggression.",
        "description_ja": "飼育環境の危険物、ハンドリング、同種間攻撃による物理的損傷。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "創傷培養", "X線検査"],
    },
    # ── Edema / Fluid Disorders ───────────────────────────────────────
    {
        "name": "Edema / Hydrops (Dropsy)",
        "name_ja": "浮腫・水腫（腹水症）",
        "symptoms": {"edema", "bloating", "ascites", "lethargy", "anorexia", "dyspnea", "buoyancy_problems"},
        "description": "Generalized or localized fluid accumulation due to renal, hepatic, or cardiac dysfunction.",
        "description_ja": "腎臓・肝臓・心臓機能障害による全身性または局所的な液体貯留。",
        "urgency": "high",
        "recommended_tests": ["超音波検査", "血液生化学検査", "腹水穿刺検査", "X線検査"],
    },
    {
        "name": "Gas Bubble Disease",
        "name_ja": "ガス泡病",
        "symptoms": {"subcutaneous_gas", "buoyancy_problems", "edema", "lethargy", "erratic_swimming", "sudden_death"},
        "description": "Gas supersaturation in water causing subcutaneous emphysema and vascular gas emboli.",
        "description_ja": "水中のガス過飽和により皮下気腫や血管ガス塞栓を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["水質検査（溶存酸素）", "身体検査", "X線検査"],
    },
    # ── Gastrointestinal ──────────────────────────────────────────────
    {
        "name": "Intestinal Impaction",
        "name_ja": "腸閉塞（腸インパクション）",
        "symptoms": {"constipation", "bloating", "anorexia", "lethargy", "reluctance_to_move"},
        "description": "Gastrointestinal obstruction from ingestion of substrate, oversized prey, or foreign bodies.",
        "description_ja": "床材、大きすぎる餌、異物の摂取による消化管閉塞。",
        "urgency": "high",
        "recommended_tests": ["X線検査", "超音波検査", "身体検査"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物摂取",
        "symptoms": {"anorexia", "bloating", "regurgitation", "lethargy", "constipation"},
        "description": "Ingestion of non-food items (substrate, gravel) causing gastrointestinal obstruction.",
        "description_ja": "床材や砂利などの非食物の摂取による消化管閉塞。",
        "urgency": "high",
        "recommended_tests": ["X線検査", "超音波検査", "身体検査"],
    },
    {
        "name": "Gastric Overload",
        "name_ja": "胃過負荷",
        "symptoms": {"bloating", "regurgitation", "lethargy", "anorexia"},
        "description": "Overfeeding leading to gastric distension and potential regurgitation.",
        "description_ja": "過剰給餌による胃拡張と吐き戻し。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "X線検査", "食事評価"],
    },
    # ── Prolapse ──────────────────────────────────────────────────────
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"cloacal_prolapse", "lethargy", "anorexia", "hemorrhage", "swelling"},
        "description": "Protrusion of cloacal tissue, often due to straining, parasites, or reproductive issues.",
        "description_ja": "いきみ、寄生虫、生殖器の問題などによる総排泄腔組織の脱出。",
        "urgency": "emergency",
        "recommended_tests": ["身体検査", "糞便検査", "X線検査"],
    },
    {
        "name": "Gastric Prolapse",
        "name_ja": "胃脱",
        "symptoms": {"gastric_prolapse", "anorexia", "lethargy", "hemorrhage"},
        "description": "Eversion of the stomach through the mouth, a serious emergency requiring immediate treatment.",
        "description_ja": "胃が口から反転脱出する緊急状態。",
        "urgency": "emergency",
        "recommended_tests": ["身体検査", "X線検査"],
    },
    {
        "name": "Intestinal Prolapse",
        "name_ja": "腸脱",
        "symptoms": {"intestinal_prolapse", "lethargy", "anorexia", "hemorrhage", "swelling"},
        "description": "Protrusion of intestinal tissue from the cloaca, requiring prompt veterinary intervention.",
        "description_ja": "総排泄腔からの腸管組織の脱出。速やかな獣医処置が必要。",
        "urgency": "emergency",
        "recommended_tests": ["身体検査", "X線検査"],
    },
    # ── Developmental / Growth ────────────────────────────────────────
    {
        "name": "Spindly Leg Syndrome",
        "name_ja": "スピンドリーレッグ症候群",
        "symptoms": {"spindly_legs", "weakness", "inability_to_feed", "failure_to_thrive", "limb_deformity"},
        "description": "Developmental disorder in metamorphosing froglets causing thin, non-functional limbs; linked to nutritional or environmental factors.",
        "description_ja": "変態中の子ガエルに発生する四肢の発達異常で、栄養・環境因子と関連する。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "飼育環境評価", "食事内容評価"],
    },
    {
        "name": "Short Body Syndrome (SBS)",
        "name_ja": "ショートボディ症候群",
        "symptoms": {"spinal_deformity", "failure_to_thrive", "weakness", "abnormal_posture"},
        "description": "Congenital or developmental truncation of the axial skeleton in tadpoles and froglets.",
        "description_ja": "オタマジャクシおよび子ガエルにおける先天的・発達的な軸骨格短縮。",
        "urgency": "moderate",
        "recommended_tests": ["X線検査", "身体検査"],
    },
    # ── Neoplasia ─────────────────────────────────────────────────────
    {
        "name": "Neoplasia / Tumors",
        "name_ja": "腫瘍性疾患",
        "symptoms": {"mass_growth", "weight_loss", "anorexia", "lethargy", "swelling"},
        "description": "Benign or malignant tumors affecting skin, liver, kidneys, or other organs.",
        "description_ja": "皮膚、肝臓、腎臓その他の臓器に発生する良性または悪性腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["組織生検", "X線検査", "超音波検査", "血液検査"],
    },
    # ── Eye Diseases ──────────────────────────────────────────────────
    {
        "name": "Corneal Lipidosis",
        "name_ja": "角膜脂質症",
        "symptoms": {"corneal_opacity", "cloudy_eyes"},
        "description": "Lipid deposition in the cornea causing cloudiness; often related to high-fat diets.",
        "description_ja": "高脂肪食などに関連する角膜への脂質沈着による白濁。",
        "urgency": "low",
        "recommended_tests": ["眼科検査", "血液脂質検査", "食事内容評価"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cataracts", "cloudy_eyes", "inability_to_feed"},
        "description": "Lens opacity impairing vision; may be congenital, nutritional, or age-related.",
        "description_ja": "水晶体の混濁による視力障害。先天性、栄養性、加齢性がある。",
        "urgency": "low",
        "recommended_tests": ["眼科検査", "超音波検査"],
    },
    {
        "name": "Periorbital Edema",
        "name_ja": "眼窩周囲浮腫",
        "symptoms": {"eye_swelling", "edema", "lethargy"},
        "description": "Swelling around the eyes associated with systemic disease, infection, or water quality issues.",
        "description_ja": "全身疾患、感染、水質問題に関連する眼周囲の腫脹。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "血液検査", "水質検査"],
    },
    # ── Organ Failure ─────────────────────────────────────────────────
    {
        "name": "Renal Failure",
        "name_ja": "腎不全",
        "symptoms": {"edema", "bloating", "anorexia", "lethargy", "weight_loss", "organ_failure"},
        "description": "Kidney dysfunction from infection, toxins, or chronic disease leading to fluid imbalance.",
        "description_ja": "感染、毒素、慢性疾患による腎機能障害で体液バランスが崩れる。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "尿検査", "超音波検査"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"anorexia", "lethargy", "bloating", "weight_loss", "color_change", "organ_failure"},
        "description": "Fatty liver disease from overfeeding, obesity, or metabolic dysfunction.",
        "description_ja": "過剰給餌、肥満、代謝障害による脂肪肝。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "超音波検査", "肝生検"],
    },
    # ── Shedding / Integument ─────────────────────────────────────────
    {
        "name": "Dysecdysis (Abnormal Shedding)",
        "name_ja": "脱皮不全",
        "symptoms": {"skin_shedding", "excessive_shedding", "dry_skin", "skin_lesions", "lethargy"},
        "description": "Difficulty or incomplete shedding of skin, often due to low humidity or underlying disease.",
        "description_ja": "湿度不足や基礎疾患による脱皮困難または不完全な脱皮。",
        "urgency": "low",
        "recommended_tests": ["身体検査", "飼育環境評価", "皮膚検査"],
    },
    # ── Spring / Seasonal ─────────────────────────────────────────────
    {
        "name": "Spring Disease (Post-hibernation Syndrome)",
        "name_ja": "春病（冬眠後症候群）",
        "symptoms": {"lethargy", "anorexia", "edema", "red_legs", "hemorrhage", "weakness"},
        "description": "Post-hibernation immunosuppression leading to bacterial septicemia; common in wild-caught specimens.",
        "description_ja": "冬眠後の免疫抑制に伴う細菌性敗血症。野生捕獲個体に多い。",
        "urgency": "high",
        "recommended_tests": ["血液検査", "細菌培養", "身体検査"],
    },
    # ── Miscellaneous ─────────────────────────────────────────────────
    {
        "name": "Anorexia (Multifactorial)",
        "name_ja": "食欲不振（多因子性）",
        "symptoms": {"anorexia", "weight_loss", "lethargy"},
        "description": "Loss of appetite from stress, environmental issues, illness, or husbandry problems.",
        "description_ja": "ストレス、環境問題、疾病、飼育管理の問題による食欲低下。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "血液検査", "飼育環境評価", "糞便検査"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満症",
        "symptoms": {"bloating", "lethargy", "reluctance_to_move"},
        "description": "Excessive body condition from overfeeding; predisposes to hepatic lipidosis and organ failure.",
        "description_ja": "過剰給餌による過体重。脂肪肝や臓器不全の素因となる。",
        "urgency": "low",
        "recommended_tests": ["身体検査", "食事内容評価", "血液検査"],
    },
    {
        "name": "Tail Rot / Necrotic Dermatitis",
        "name_ja": "尾腐れ・壊死性皮膚炎",
        "symptoms": {"tail_rot", "necrosis", "skin_lesions", "lethargy", "anorexia"},
        "description": "Progressive necrosis of the tail or limb tips, often bacterial in origin, associated with poor water quality.",
        "description_ja": "水質悪化に伴う細菌性の尾や四肢末端の進行性壊死。",
        "urgency": "high",
        "recommended_tests": ["細菌培養", "水質検査", "身体検査"],
    },
    {
        "name": "Gill Necrosis (Larval)",
        "name_ja": "鰓壊死（幼生期）",
        "symptoms": {"gill_abnormality", "fin_rot", "gasping", "lethargy", "rapid_breathing"},
        "description": "Bacterial or environmental damage to external gills in larval amphibians.",
        "description_ja": "細菌感染や環境要因による両生類幼生の外鰓障害。",
        "urgency": "high",
        "recommended_tests": ["水質検査", "鰓スクレイピング", "細菌培養"],
    },

    # ── 追加疾患 (Additional Diseases) ──
    {
        "name": "Batrachochytrium salamandrivorans (Bsal) - Systemic",
        "name_ja": "バトラコキトリウム・サラマンドリボランス全身型",
        "symptoms": {"anorexia", "lethargy", "rapid_death", "skin_hemorrhage", "skin_ulceration"},
        "description": "Systemic Bsal infection causing severe ulcerative skin disease and high mortality in urodeles.",
        "description_ja": "有尾類に重度の潰瘍性皮膚疾患と高致死率を引き起こすBsal全身型感染症。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_Bsal", "skin_swab", "histopathology"],
    },
    {
        "name": "Perkinsea Infection",
        "name_ja": "パーキンシア感染症",
        "symptoms": {"internal_hemorrhage", "lethargy", "liver_enlargement", "sudden_death"},
        "description": "Protist parasite causing mass mortality events in larval and adult amphibians.",
        "description_ja": "幼生および成体の両生類に大量死を引き起こす原生生物寄生虫。",
        "urgency": "emergency",
        "recommended_tests": ["histopathology", "PCR_perkinsea", "liver_biopsy"],
    },
    {
        "name": "Lucke Tumor Herpesvirus (Renal Carcinoma)",
        "name_ja": "ルッケ腫瘍ヘルペスウイルス（腎癌）",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy", "weight_loss"},
        "description": "Herpesvirus-associated renal adenocarcinoma in leopard frogs.",
        "description_ja": "ヒョウガエルにおけるヘルペスウイルス関連腎腺癌。",
        "urgency": "high",
        "recommended_tests": ["histopathology", "PCR_herpesvirus", "ultrasound"],
    },
    {
        "name": "Frog Virus 3 (FV3)",
        "name_ja": "カエルウイルス3型（FV3）",
        "symptoms": {"edema", "lethargy", "organ_failure", "skin_hemorrhage", "sudden_death"},
        "description": "Type species of Ranavirus causing hemorrhagic disease and multi-organ necrosis.",
        "description_ja": "ラナウイルスの基準種で、出血性疾患と多臓器壊死を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_FV3", "histopathology", "virus_isolation"],
    },
    {
        "name": "Ambystoma Tigrinum Virus (ATV)",
        "name_ja": "タイガーサラマンダーウイルス",
        "symptoms": {"edema", "hemorrhage", "lethargy", "skin_lesions", "sudden_death"},
        "description": "Ranavirus causing disease primarily in tiger salamanders and related species.",
        "description_ja": "主にタイガーサラマンダーと関連種に疾患を引き起こすラナウイルス。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_ATV", "histopathology"],
    },
    {
        "name": "Calicivirus Infection",
        "name_ja": "カリシウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "skin_ulceration", "skin_vesicles"},
        "description": "Calicivirus causing vesicular skin disease in amphibians.",
        "description_ja": "両生類に水疱性皮膚疾患を引き起こすカリシウイルス。",
        "urgency": "high",
        "recommended_tests": ["PCR_calicivirus", "histopathology", "skin_biopsy"],
    },
    {
        "name": "Adenovirus Infection",
        "name_ja": "アデノウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "liver_enlargement", "sudden_death"},
        "description": "Adenovirus causing hepatitis and systemic disease.",
        "description_ja": "アデノウイルスによる肝炎と全身性疾患。",
        "urgency": "high",
        "recommended_tests": ["PCR_adenovirus", "histopathology"],
    },
    {
        "name": "Papillomavirus Infection",
        "name_ja": "パピローマウイルス感染症",
        "symptoms": {"skin_papillomas", "wart_like_growths"},
        "description": "Papillomavirus causing papillomatous skin lesions in anurans.",
        "description_ja": "無尾類に皮膚乳頭腫を引き起こすパピローマウイルス。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Aeromonas hydrophila Infection (Acute)",
        "name_ja": "エロモナス・ハイドロフィラ急性感染症",
        "symptoms": {"edema", "lethargy", "red_legs", "septicemia", "skin_hemorrhage"},
        "description": "Acute Aeromonas infection causing severe red leg and septicemia.",
        "description_ja": "急性エロモナス感染による重度のレッドレッグと敗血症。",
        "urgency": "emergency",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Pseudomonas Infection",
        "name_ja": "緑膿菌感染症",
        "symptoms": {"lethargy", "respiratory_distress", "septicemia", "skin_lesions"},
        "description": "Pseudomonas aeruginosa causing dermatitis and septicemia.",
        "description_ja": "緑膿菌による皮膚炎と敗血症。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "gram_stain"],
    },
    {
        "name": "Citrobacter Infection",
        "name_ja": "シトロバクター感染症",
        "symptoms": {"lethargy", "septicemia", "skin_ulceration"},
        "description": "Citrobacter freundii causing ulcerative skin disease and septicemia.",
        "description_ja": "シトロバクター・フロインディによる潰瘍性皮膚疾患と敗血症。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing"],
    },
    {
        "name": "Flavobacterium Infection",
        "name_ja": "フラボバクテリウム感染症",
        "symptoms": {"gill_necrosis", "lethargy", "skin_erosion", "tail_rot"},
        "description": "Flavobacterium causing skin erosion and gill disease, especially in larvae.",
        "description_ja": "フラボバクテリウムによる皮膚びらんと鰓疾患。特に幼生に多い。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "skin_scraping", "gill_biopsy"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"anorexia", "diarrhea", "lethargy", "weight_loss"},
        "description": "Salmonella spp. infection; zoonotic concern.",
        "description_ja": "サルモネラ属感染症。人獣共通感染症の懸念あり。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "PCR_salmonella"],
    },
    {
        "name": "Elizabethkingia meningoseptica Infection",
        "name_ja": "エリザベスキンギア感染症",
        "symptoms": {"lethargy", "neurological_signs", "septicemia", "skin_lesions"},
        "description": "Elizabethkingia meningoseptica causing septicemia and meningitis.",
        "description_ja": "エリザベスキンギア・メニンゴセプティカによる敗血症と髄膜炎。",
        "urgency": "emergency",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Erysipelas",
        "name_ja": "丹毒",
        "symptoms": {"septicemia", "skin_lesions", "sudden_death"},
        "description": "Erysipelothrix rhusiopathiae causing septicemia.",
        "description_ja": "エリシペロスリクスによる敗血症。",
        "urgency": "emergency",
        "recommended_tests": ["bacterial_culture", "histopathology"],
    },
    {
        "name": "Basidiobolus Infection",
        "name_ja": "バシディオボルス感染症",
        "symptoms": {"granulomatous_lesions", "lethargy", "skin_masses"},
        "description": "Basidiobolus ranarum causing subcutaneous zygomycosis.",
        "description_ja": "バシディオボルス・ラナルムによる皮下接合菌症。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "biopsy", "histopathology"],
    },
    {
        "name": "Fusarium Infection",
        "name_ja": "フザリウム感染症",
        "symptoms": {"lethargy", "skin_discoloration", "skin_lesions"},
        "description": "Fusarium spp. causing cutaneous mycosis.",
        "description_ja": "フザリウム属による皮膚真菌症。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_biopsy"],
    },
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"lethargy", "respiratory_distress", "skin_lesions", "weight_loss"},
        "description": "Aspergillus spp. causing respiratory and cutaneous disease.",
        "description_ja": "アスペルギルス属による呼吸器・皮膚疾患。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "histopathology", "radiography"],
    },
    {
        "name": "Dermocystidium Infection",
        "name_ja": "デルモシスチジウム感染症",
        "symptoms": {"lethargy", "skin_cysts", "skin_nodules"},
        "description": "Dermocystidium spp. causing dermal cysts in amphibians.",
        "description_ja": "デルモシスチジウム属による両生類の皮膚嚢胞。",
        "urgency": "moderate",
        "recommended_tests": ["skin_biopsy", "histopathology"],
    },
    {
        "name": "Trypanosomiasis",
        "name_ja": "トリパノソーマ症",
        "symptoms": {"anemia", "edema", "lethargy", "weight_loss"},
        "description": "Trypanosoma spp. blood parasite transmitted by leeches.",
        "description_ja": "ヒル媒介のトリパノソーマ属血液寄生虫。",
        "urgency": "moderate",
        "recommended_tests": ["blood_smear", "PCR_trypanosoma"],
    },
    {
        "name": "Myxozoan Infection",
        "name_ja": "粘液胞子虫感染症",
        "symptoms": {"lethargy", "organ_cysts", "skin_cysts", "weight_loss"},
        "description": "Myxozoan parasites forming cysts in skin and internal organs.",
        "description_ja": "皮膚と内臓に嚢胞を形成する粘液胞子虫。",
        "urgency": "moderate",
        "recommended_tests": ["histopathology", "skin_biopsy"],
    },
    {
        "name": "Trematode Encystment (Heavy Burden)",
        "name_ja": "吸虫被嚢（重度寄生）",
        "symptoms": {"lethargy", "limb_deformity", "skin_cysts", "weight_loss"},
        "description": "Heavy trematode metacercariae encystment causing limb deformities and organ damage.",
        "description_ja": "吸虫メタセルカリアの重度被嚢による肢奇形と臓器障害。",
        "urgency": "moderate",
        "recommended_tests": ["histopathology", "fecal_examination", "radiography"],
    },
    {
        "name": "Oxyurid (Pinworm) Infection",
        "name_ja": "蟯虫感染症",
        "symptoms": {"anorexia", "diarrhea", "weight_loss"},
        "description": "Pinworm infestation of the GI tract.",
        "description_ja": "消化管の蟯虫寄生。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "fecal_examination"],
    },
    {
        "name": "Rhabdias Lungworm",
        "name_ja": "ラブディアス肺虫症",
        "symptoms": {"lethargy", "open_mouth_breathing", "respiratory_distress", "weight_loss"},
        "description": "Rhabdias spp. lungworm in the lungs of frogs and toads.",
        "description_ja": "カエル・ヒキガエルの肺のラブディアス属肺虫。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "lung_wash", "radiography"],
    },
    {
        "name": "Strongyloides Infection",
        "name_ja": "糞線虫症",
        "symptoms": {"diarrhea", "lethargy", "weight_loss"},
        "description": "Strongyloides spp. with auto-infection capability.",
        "description_ja": "自家感染能を持つ糞線虫属感染症。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_examination"],
    },
    {
        "name": "Acanthocephalan Infection",
        "name_ja": "鉤頭虫感染症",
        "symptoms": {"anorexia", "intestinal_obstruction", "weight_loss"},
        "description": "Thorny-headed worms causing intestinal inflammation.",
        "description_ja": "鉤頭虫による腸管炎症。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_examination"],
    },
    {
        "name": "Mite Infestation (Hannemania)",
        "name_ja": "ダニ寄生症（ハンネマニア）",
        "symptoms": {"lethargy", "orange_red_nodules", "skin_lesions"},
        "description": "Hannemania spp. intradermal mite infestation in anurans.",
        "description_ja": "ハンネマニア属の無尾類皮内ダニ寄生。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "biopsy"],
    },
    {
        "name": "Myiasis (Fly Strike)",
        "name_ja": "蝿蛆症",
        "symptoms": {"lethargy", "maggots_visible", "skin_lesions", "tissue_necrosis"},
        "description": "Fly larval infestation causing tissue destruction.",
        "description_ja": "ハエ幼虫による組織破壊。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_examination", "wound_debridement"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "ダニ寄生症（マダニ）",
        "symptoms": {"anemia", "lethargy", "skin_lesions"},
        "description": "External tick parasitism in terrestrial amphibians.",
        "description_ja": "陸生両生類の外部マダニ寄生。",
        "urgency": "moderate",
        "recommended_tests": ["clinical_examination", "tick_removal"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"rapid_growth", "skin_masses", "ulceration"},
        "description": "Malignant fibrous tissue neoplasia.",
        "description_ja": "悪性線維組織腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"skin_masses", "ulcerated_lesions", "weight_loss"},
        "description": "Malignant epithelial neoplasia.",
        "description_ja": "悪性上皮性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"lethargy", "organ_enlargement", "weight_loss"},
        "description": "Lymphoid neoplasia affecting multiple organs.",
        "description_ja": "多臓器に影響するリンパ系腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "CBC"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ",
        "symptoms": {"dark_skin_masses", "skin_lesions"},
        "description": "Melanocyte-derived neoplasia.",
        "description_ja": "メラノサイト由来腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Hepatocellular Carcinoma",
        "name_ja": "肝細胞癌",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy"},
        "description": "Primary malignant liver tumor.",
        "description_ja": "原発性悪性肝腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy", "histopathology"],
    },
    {
        "name": "Renal Adenocarcinoma",
        "name_ja": "腎腺癌",
        "symptoms": {"abdominal_distension", "lethargy", "weight_loss"},
        "description": "Malignant kidney neoplasia, sometimes herpesvirus-associated.",
        "description_ja": "悪性腎腫瘍。ヘルペスウイルス関連の場合がある。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy", "histopathology"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "limb_swelling", "weight_loss"},
        "description": "Malignant bone tumor.",
        "description_ja": "悪性骨腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "biopsy", "histopathology"],
    },
    {
        "name": "Limb Fractures / Trauma",
        "name_ja": "四肢骨折・外傷",
        "symptoms": {"inability_to_use_limb", "lameness", "limb_swelling"},
        "description": "Fractures from trauma or metabolic bone disease.",
        "description_ja": "外傷やMBDによる骨折。",
        "urgency": "high",
        "recommended_tests": ["radiography", "blood_chemistry"],
    },
    {
        "name": "Spinal Injury / Vertebral Fracture",
        "name_ja": "脊椎損傷・椎体骨折",
        "symptoms": {"hind_limb_weakness", "incontinence", "paralysis"},
        "description": "Vertebral fracture or spinal cord injury causing paresis.",
        "description_ja": "椎骨骨折や脊髄損傷による不全麻痺。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "neurological_examination"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism",
        "name_ja": "栄養性二次性上皮小体機能亢進症",
        "symptoms": {"bone_deformity", "fractures", "jaw_softening", "weakness"},
        "description": "Ca:P:D3 imbalance causing excessive PTH and bone resorption.",
        "description_ja": "Ca:P:D3不均衡による上皮小体ホルモン過剰と骨吸収。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "radiography", "dietary_review"],
    },
    {
        "name": "Vitamin E Deficiency",
        "name_ja": "ビタミンE欠乏症",
        "symptoms": {"lethargy", "muscle_weakness", "neurological_signs"},
        "description": "Vitamin E deficiency causing muscular dystrophy and neurological signs.",
        "description_ja": "ビタミンE欠乏による筋ジストロフィーと神経症状。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review"],
    },
    {
        "name": "Biotin Deficiency",
        "name_ja": "ビオチン欠乏症",
        "symptoms": {"dermatitis", "poor_shedding", "skin_lesions"},
        "description": "Biotin deficiency causing skin problems.",
        "description_ja": "ビオチン欠乏による皮膚障害。",
        "urgency": "low",
        "recommended_tests": ["dietary_history", "response_to_supplementation"],
    },
    {
        "name": "Iodine Deficiency (Goiter)",
        "name_ja": "ヨウ素欠乏症（甲状腺腫）",
        "symptoms": {"lethargy", "metamorphosis_failure", "neck_swelling", "obesity"},
        "description": "Iodine deficiency causing thyroid goiter and metamorphosis failure in larvae.",
        "description_ja": "ヨウ素欠乏による甲状腺腫と幼生の変態障害。",
        "urgency": "moderate",
        "recommended_tests": ["thyroid_panel", "dietary_review"],
    },
    {
        "name": "Protein Deficiency",
        "name_ja": "タンパク質欠乏症",
        "symptoms": {"immunosuppression", "muscle_wasting", "weight_loss"},
        "description": "Inadequate protein intake causing muscle wasting.",
        "description_ja": "タンパク質不足による筋消耗。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_analysis", "blood_chemistry"],
    },
    {
        "name": "Hypoglycemia",
        "name_ja": "低血糖症",
        "symptoms": {"collapse", "lethargy", "seizures", "weakness"},
        "description": "Low blood sugar from starvation or hepatic disease.",
        "description_ja": "飢餓や肝疾患による低血糖。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry"],
    },
    {
        "name": "UV Light Deficiency",
        "name_ja": "紫外線不足症",
        "symptoms": {"bone_weakness", "lethargy", "poor_appetite"},
        "description": "Inadequate UVB for species requiring it for D3 synthesis.",
        "description_ja": "D3合成にUVBが必要な種における紫外線不足。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "husbandry_review"],
    },
    {
        "name": "Lead Toxicosis",
        "name_ja": "鉛中毒",
        "symptoms": {"anorexia", "lethargy", "neurological_signs", "seizures"},
        "description": "Lead poisoning from environmental contamination.",
        "description_ja": "環境汚染による鉛中毒。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "blood_chemistry"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"anorexia", "lethargy", "neurological_signs"},
        "description": "Zinc poisoning from galvanized fixtures in enclosures.",
        "description_ja": "飼育ケージの亜鉛メッキ金具からの亜鉛中毒。",
        "urgency": "high",
        "recommended_tests": ["blood_zinc_level", "blood_chemistry"],
    },
    {
        "name": "Copper Toxicosis",
        "name_ja": "銅中毒",
        "symptoms": {"anorexia", "death", "lethargy", "skin_discoloration"},
        "description": "Copper poisoning from copper-treated water or fixtures.",
        "description_ja": "銅処理水や銅金具からの銅中毒。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_testing", "blood_chemistry"],
    },
    {
        "name": "pH Shock",
        "name_ja": "pHショック",
        "symptoms": {"erratic_swimming", "lethargy", "skin_irritation", "sudden_death"},
        "description": "Sudden pH change in aquatic environment causing osmotic stress.",
        "description_ja": "水環境の急激なpH変化による浸透圧ストレス。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_testing", "clinical_examination"],
    },
    {
        "name": "Low Dissolved Oxygen",
        "name_ja": "溶存酸素低下症",
        "symptoms": {"erratic_swimming", "gasping_at_surface", "lethargy"},
        "description": "Hypoxia from inadequate water oxygenation.",
        "description_ja": "水中酸素化不足による低酸素症。",
        "urgency": "high",
        "recommended_tests": ["water_quality_testing", "dissolved_oxygen_measurement"],
    },
    {
        "name": "High Nitrate Toxicity",
        "name_ja": "高硝酸塩毒性",
        "symptoms": {"anorexia", "immunosuppression", "lethargy", "skin_irritation"},
        "description": "Chronic elevated nitrate levels causing immunosuppression and organ damage.",
        "description_ja": "慢性的な硝酸塩高値による免疫抑制と臓器障害。",
        "urgency": "moderate",
        "recommended_tests": ["water_quality_testing", "blood_chemistry"],
    },
    {
        "name": "Columnaris Disease (Flavobacterium columnare)",
        "name_ja": "カラムナリス病",
        "symptoms": {"fin_rot", "gill_necrosis", "lethargy", "skin_erosion"},
        "description": "Flavobacterium columnare causing skin erosion and gill disease in aquatic amphibians.",
        "description_ja": "フラボバクテリウム・コラムナーレによる水棲両生類の皮膚びらんと鰓疾患。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "skin_scraping", "gill_biopsy"],
    },
    {
        "name": "Aeromonas Chronic Infection",
        "name_ja": "エロモナス慢性感染症",
        "symptoms": {"chronic_edema", "lethargy", "skin_ulceration", "weight_loss"},
        "description": "Chronic Aeromonas infection causing non-healing skin ulcers.",
        "description_ja": "エロモナスの慢性感染による治癒しない皮膚潰瘍。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "biopsy"],
    },
    {
        "name": "Oodinium (Velvet Disease)",
        "name_ja": "ウーディニウム症（ベルベット病）",
        "symptoms": {"appetite_loss", "gold_dust_appearance", "lethargy", "skin_discoloration"},
        "description": "Oodinium dinoflagellate infection causing velvet-like skin coating in aquatic amphibians.",
        "description_ja": "水棲両生類にベルベット様皮膚被覆を引き起こすウーディニウム渦鞭毛虫感染症。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Vorticella Infestation",
        "name_ja": "ツリガネムシ寄生症",
        "symptoms": {"gill_irritation", "lethargy", "white_fuzzy_appearance"},
        "description": "Vorticella ciliate protozoan attachment to skin and gills, often in poor water quality.",
        "description_ja": "水質悪化時に皮膚と鰓に付着するツリガネムシ繊毛虫。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy", "water_quality_testing"],
    },
    {
        "name": "Planarian Infestation",
        "name_ja": "プラナリア寄生",
        "symptoms": {"gill_damage", "lethargy", "skin_irritation"},
        "description": "Planarian flatworms damaging gills and skin in larval amphibians.",
        "description_ja": "幼生両生類の鰓と皮膚を損傷するプラナリア扁形動物。",
        "urgency": "moderate",
        "recommended_tests": ["microscopy", "water_quality_testing"],
    },
    {
        "name": "Enteric Flagellate Infection",
        "name_ja": "腸管鞭毛虫感染症",
        "symptoms": {"anorexia", "diarrhea", "weight_loss"},
        "description": "Flagellate protozoan overgrowth in the GI tract.",
        "description_ja": "消化管における鞭毛虫原虫の過増殖。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_smear"],
    },
    {
        "name": "Gastric Torsion",
        "name_ja": "胃捻転",
        "symptoms": {"abdominal_distension", "lethargy", "sudden_death"},
        "description": "Torsion of the stomach from overeating or prey too large.",
        "description_ja": "過食や大きすぎる餌による胃捻転。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "clinical_examination"],
    },
    {
        "name": "Reproductive Failure / Egg Retention",
        "name_ja": "繁殖障害・卵停滞",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy", "straining"},
        "description": "Failure to oviposit causing egg retention and coelomitis.",
        "description_ja": "産卵障害による卵停滞と体腔炎。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "blood_chemistry"],
    },
    {
        "name": "Hemolytic Anemia",
        "name_ja": "溶血性貧血",
        "symptoms": {"lethargy", "pale_skin", "weakness"},
        "description": "Red blood cell destruction from parasites or toxins.",
        "description_ja": "寄生虫や毒素による赤血球破壊。",
        "urgency": "high",
        "recommended_tests": ["CBC", "blood_smear"],
    },
    {
        "name": "Nephrocalcinosis",
        "name_ja": "腎石灰沈着症",
        "symptoms": {"anorexia", "edema", "lethargy"},
        "description": "Calcium deposition in kidneys.",
        "description_ja": "腎臓へのカルシウム沈着。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "histopathology"],
    },
    {
        "name": "Photosensitization",
        "name_ja": "光線過敏症",
        "symptoms": {"skin_blistering", "skin_redness"},
        "description": "Skin damage from photosensitizing compounds.",
        "description_ja": "光増感物質による皮膚損傷。",
        "urgency": "moderate",
        "recommended_tests": ["skin_biopsy", "environmental_review"],
    },
    {
        "name": "Anasarca (Generalized Edema / Bloat)",
        "name_ja": "全身浮腫・膨満",
        "symptoms": {"anorexia", "generalized_swelling", "lethargy", "respiratory_distress"},
        "description": "Severe generalized edema from organ failure or sepsis.",
        "description_ja": "臓器不全や敗血症による重度全身浮腫。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "coelomocentesis", "CBC"],
    },
    {
        "name": "Organ Prolapse (Gastric/Intestinal/Cloacal)",
        "name_ja": "臓器脱（胃・腸・総排泄腔）",
        "symptoms": {"anorexia", "lethargy", "straining", "tissue_protruding"},
        "description": "Prolapse of internal organs, often secondary to infection or straining.",
        "description_ja": "感染や努責に続発する内臓脱出。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_examination", "radiography"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"abdominal_distension", "edema", "lethargy", "respiratory_distress"},
        "description": "Heart failure with fluid accumulation.",
        "description_ja": "液体貯留を伴う心不全。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "blood_chemistry"],
    },
    {
        "name": "Hepatitis",
        "name_ja": "肝炎",
        "symptoms": {"anorexia", "jaundice", "lethargy", "liver_enlargement"},
        "description": "Liver inflammation from bacterial, viral, or toxic causes.",
        "description_ja": "細菌・ウイルス・毒素による肝臓の炎症。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_biopsy", "histopathology"],
    },
    {
        "name": "Pancreatitis",
        "name_ja": "膵炎",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy"},
        "description": "Pancreatic inflammation causing metabolic dysfunction.",
        "description_ja": "膵臓の炎症による代謝機能障害。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound"],
    },
    {
        "name": "Axolotl Gill Curl",
        "name_ja": "アホロートル鰓カール",
        "symptoms": {"gill_curling", "gill_shrinkage", "lethargy"},
        "description": "Forward curling of gills in axolotls due to poor water quality or genetics.",
        "description_ja": "水質不良や遺伝によるアホロートルの鰓前方カール。",
        "urgency": "moderate",
        "recommended_tests": ["water_quality_testing", "clinical_examination"],
    },
    {
        "name": "Axolotl Floating Disorder",
        "name_ja": "アホロートル浮遊障害",
        "symptoms": {"abdominal_distension", "buoyancy_problems", "inability_to_sink"},
        "description": "Gas accumulation in the GI tract or coelomic cavity causing buoyancy problems.",
        "description_ja": "消化管や体腔のガス蓄積による浮力障害。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "water_quality_testing", "dietary_review"],
    },
    {
        "name": "Limb Deformity (Developmental)",
        "name_ja": "肢奇形（発育性）",
        "symptoms": {"extra_limbs", "limb_deformity", "missing_digits"},
        "description": "Developmental limb deformities from parasites, chemicals, or UV exposure.",
        "description_ja": "寄生虫・化学物質・UV照射による発育性肢奇形。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "environmental_testing", "histopathology"],
    },


    # ── 追加疾患2 ──
    {
        "name": "Disseminated Granulomatous Disease",
        "name_ja": "播種性肉芽腫性疾患",
        "symptoms": {"lethargy", "organ_enlargement", "skin_nodules", "weight_loss"},
        "description": "Multi-organ granulomas from mycobacterial or fungal causes.",
        "description_ja": "マイコバクテリアや真菌による多臓器肉芽腫。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "acid_fast_stain"],
    },
    {
        "name": "Chronic Dehydration (Terrestrial Species)",
        "name_ja": "慢性脱水（陸生種）",
        "symptoms": {"anorexia", "lethargy", "sunken_eyes", "wrinkled_skin"},
        "description": "Long-term inadequate humidity causing dehydration in terrestrial amphibians.",
        "description_ja": "陸生両生類における長期的な湿度不足による脱水。",
        "urgency": "moderate",
        "recommended_tests": ["clinical_examination", "husbandry_review"],
    },
    {
        "name": "Substrate Impaction",
        "name_ja": "床材インパクション",
        "symptoms": {"abdominal_distension", "anorexia", "constipation"},
        "description": "GI obstruction from ingestion of substrate materials.",
        "description_ja": "床材の摂取による消化管閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "contrast_study"],
    },
    {
        "name": "Metamorphosis Failure (Neoteny Complications)",
        "name_ja": "変態障害（幼形成熟合併症）",
        "symptoms": {"failure_to_metamorphose", "gill_retention", "stunted_growth"},
        "description": "Failure to complete metamorphosis due to thyroid dysfunction or environmental factors.",
        "description_ja": "甲状腺機能障害や環境因子による変態完了の障害。",
        "urgency": "moderate",
        "recommended_tests": ["thyroid_panel", "water_quality_testing", "husbandry_review"],
    },
    {
        "name": "Thermal Burn (Heat Lamp)",
        "name_ja": "熱傷（ヒートランプ）",
        "symptoms": {"lethargy", "skin_blistering", "skin_discoloration"},
        "description": "Burns from direct contact with heat lamps or hot surfaces.",
        "description_ja": "ヒートランプや高温面との直接接触による熱傷。",
        "urgency": "high",
        "recommended_tests": ["clinical_examination", "wound_assessment"],
    },

]


def analyze_symptoms(
    symptoms: List[str],
    age_stage: str = "",
    breed: str | None = None,
    *,
    onset: str | None = None,
    age_years: float | None = None,
    species: str | None = None,
    lab_values: dict | None = None,
) -> Dict[str, Any]:
    """両生類用の鑑別診断エンジン。

    Args:
        symptoms: ユーザーが報告した症状のリスト
        age_stage: 任意の年齢/ライフステージ情報
        breed: 任意の種名情報

    Returns:
        辞書形式の分析結果
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species, lab_values=lab_values)
