"""bird_diseases.py – 鳥類共通の疾患データと鑑別診断

鳥類全般に見られる疾患を包括的に掲載し、症状から鑑別診断候補を導き出す
エンジンを提供します。具体的な診断は必ず獣医師にご相談ください。
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── ウイルス性感染症 (Viral Infectious Diseases) ──
    {
        "name": "Psittacine Beak and Feather Disease (PBFD)",
        "name_ja": "嘴羽毛病（PBFD）",
        "symptoms": {"feather_loss", "abnormal_feathers", "beak_deformity", "immunosuppression", "weight_loss", "lethargy"},
        "description": "Circovirus infection causing progressive feather dystrophy, beak necrosis, and immunosuppression in psittacines.",
        "description_ja": "サーコウイルスによる進行性の羽毛異常、嘴壊死、免疫抑制を引き起こすオウム目の感染症。",
        "urgency": "high",
        "recommended_tests": ["PCR_blood", "PCR_feather", "biopsy"],
    },
    {
        "name": "Proventricular Dilatation Disease (PDD / Bornavirus)",
        "name_ja": "腺胃拡張症（PDD／ボルナウイルス）",
        "symptoms": {"regurgitation", "weight_loss", "undigested_food_in_droppings", "crop_stasis", "lethargy", "neurological_signs"},
        "description": "Avian bornavirus-induced ganglioneuritis affecting the GI tract and CNS, causing proventricular dilatation.",
        "description_ja": "鳥ボルナウイルスによる神経節神経炎で、消化管および中枢神経系に影響し腺胃拡張を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["radiography", "fluoroscopy", "PCR_bornavirus", "biopsy_crop"],
    },
    {
        "name": "Avian Polyomavirus",
        "name_ja": "鳥ポリオーマウイルス感染症",
        "symptoms": {"sudden_death", "lethargy", "appetite_loss", "abdominal_distension", "subcutaneous_hemorrhage", "feather_abnormalities"},
        "description": "Polyomavirus infection causing acute death in neonates and feather abnormalities in older birds.",
        "description_ja": "ポリオーマウイルス感染症で、幼鳥の急死や成鳥の羽毛異常を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_blood", "PCR_cloacal_swab", "histopathology"],
    },
    {
        "name": "Avian Poxvirus",
        "name_ja": "鳥痘",
        "symptoms": {"skin_lesions", "crusty_lesions_on_face", "oral_plaques", "labored_breathing", "eye_swelling", "appetite_loss"},
        "description": "Poxvirus infection presenting as cutaneous nodules (dry form) or diphtheritic membranes in the oral cavity (wet form).",
        "description_ja": "ポックスウイルス感染症で、皮膚結節（乾燥型）または口腔内ジフテリア様膜（湿潤型）として現れる。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "PCR_poxvirus"],
    },
    {
        "name": "Newcastle Disease",
        "name_ja": "ニューカッスル病",
        "symptoms": {"respiratory_distress", "neurological_signs", "diarrhea_green", "torticollis", "paralysis", "sudden_death"},
        "description": "Highly contagious paramyxovirus infection causing respiratory, neurological, and GI signs; reportable disease.",
        "description_ja": "パラミクソウイルスによる高度伝染性疾患で、呼吸器・神経・消化器症状を引き起こす届出疾病。",
        "urgency": "emergency",
        "recommended_tests": ["virus_isolation", "PCR_NDV", "serology"],
    },
    {
        "name": "Avian Influenza",
        "name_ja": "鳥インフルエンザ",
        "symptoms": {"respiratory_distress", "nasal_discharge", "diarrhea", "sudden_death", "cyanosis", "edema_head", "drop_in_egg_production"},
        "description": "Influenza A virus infection ranging from mild to highly pathogenic forms; reportable disease.",
        "description_ja": "A型インフルエンザウイルス感染症で、軽症から高病原性まで様々。届出疾病。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_influenza", "virus_isolation", "serology", "cloacal_swab"],
    },
    {
        "name": "Pacheco\'s Disease (Psittacid Herpesvirus)",
        "name_ja": "パチェコ病（オウム目ヘルペスウイルス）",
        "symptoms": {"sudden_death", "lethargy", "diarrhea_yellow_green", "regurgitation", "liver_enlargement", "nasal_discharge"},
        "description": "Psittacid herpesvirus-1 infection causing acute hepatic necrosis and high mortality in psittacines.",
        "description_ja": "オウム目ヘルペスウイルス1型による急性肝壊死を引き起こし、高い致死率を示す。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_herpesvirus", "histopathology", "liver_biopsy"],
    },
    {
        "name": "Paramyxovirus Infection (PMV-1/2/3)",
        "name_ja": "パラミクソウイルス感染症",
        "symptoms": {"torticollis", "neurological_signs", "paralysis", "diarrhea_green", "respiratory_distress", "tremors"},
        "description": "Paramyxovirus strains causing neurological and respiratory disease, particularly in pigeons and psittacines.",
        "description_ja": "パラミクソウイルスによる神経・呼吸器疾患で、特にハトやオウム目に多い。",
        "urgency": "high",
        "recommended_tests": ["serology", "virus_isolation", "PCR_paramyxovirus"],
    },
    {
        "name": "Avian Reovirus Infection",
        "name_ja": "鳥レオウイルス感染症",
        "symptoms": {"lameness", "joint_swelling", "diarrhea", "lethargy", "weight_loss", "stunted_growth"},
        "description": "Reovirus causing viral arthritis/tenosynovitis and immunosuppression.",
        "description_ja": "レオウイルスによるウイルス性関節炎・腱鞘炎および免疫抑制。",
        "urgency": "moderate",
        "recommended_tests": ["virus_isolation", "PCR_reovirus", "histopathology"],
    },
    {
        "name": "Avian Adenovirus Infection",
        "name_ja": "鳥アデノウイルス感染症",
        "symptoms": {"diarrhea", "lethargy", "liver_enlargement", "sudden_death", "respiratory_distress", "appetite_loss"},
        "description": "Adenovirus infection causing hepatitis, enteritis, and respiratory disease in various bird species.",
        "description_ja": "アデノウイルスによる肝炎、腸炎、呼吸器疾患を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["PCR_adenovirus", "histopathology", "virus_isolation"],
    },
    # ── 細菌性感染症 (Bacterial Infectious Diseases) ──
    {
        "name": "Psittacosis / Chlamydiosis",
        "name_ja": "オウム病（クラミジア症）",
        "symptoms": {"nasal_discharge", "conjunctivitis", "diarrhea_green", "lethargy", "respiratory_distress", "liver_enlargement", "weight_loss"},
        "description": "Chlamydia psittaci infection causing respiratory, hepatic, and systemic disease; zoonotic.",
        "description_ja": "クラミジア・シタッシによる呼吸器・肝臓・全身性疾患。人獣共通感染症。",
        "urgency": "high",
        "recommended_tests": ["PCR_chlamydia", "serology", "CBC", "liver_panel"],
    },
    {
        "name": "Avian Tuberculosis (Mycobacteriosis)",
        "name_ja": "鳥結核（抗酸菌症）",
        "symptoms": {"weight_loss", "lethargy", "diarrhea", "liver_enlargement", "granulomas", "lameness"},
        "description": "Chronic Mycobacterium avium infection causing granulomatous disease in multiple organs.",
        "description_ja": "マイコバクテリウム・アビウムによる慢性肉芽腫性疾患で、複数臓器に影響する。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "PCR_mycobacterium", "biopsy", "radiography"],
    },
    {
        "name": "Mycoplasmosis",
        "name_ja": "マイコプラズマ症",
        "symptoms": {"nasal_discharge", "conjunctivitis", "sinusitis", "respiratory_distress", "lethargy", "swollen_infraorbital_sinus"},
        "description": "Mycoplasma infection causing chronic upper respiratory disease and sinusitis.",
        "description_ja": "マイコプラズマによる慢性上部気道疾患および副鼻腔炎。",
        "urgency": "moderate",
        "recommended_tests": ["PCR_mycoplasma", "culture", "serology"],
    },
    {
        "name": "E. coli Infection (Colibacillosis)",
        "name_ja": "大腸菌感染症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "polyuria", "joint_swelling", "respiratory_distress"},
        "description": "Escherichia coli infection causing enteritis, septicemia, and secondary infections.",
        "description_ja": "大腸菌による腸炎、敗血症、二次感染を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Pseudomonas Infection",
        "name_ja": "緑膿菌感染症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "sinusitis", "skin_lesions", "lethargy", "foul_smelling_discharge"},
        "description": "Pseudomonas aeruginosa infection often secondary to immunosuppression or poor hygiene.",
        "description_ja": "免疫抑制や衛生不良に二次的に発生する緑膿菌感染症。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "cytology"],
    },
    {
        "name": "Klebsiella Infection",
        "name_ja": "クレブシエラ感染症",
        "symptoms": {"respiratory_distress", "diarrhea", "lethargy", "sinusitis", "nasal_discharge", "polyuria"},
        "description": "Klebsiella species causing respiratory and GI infections, often antibiotic-resistant.",
        "description_ja": "クレブシエラ属による呼吸器・消化管感染症で、抗生物質耐性を示すことが多い。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "weight_loss", "sudden_death", "joint_swelling"},
        "description": "Salmonella infection causing enteritis and systemic disease; zoonotic concern.",
        "description_ja": "サルモネラ菌による腸炎および全身性疾患。人獣共通感染症。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "fecal_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Staphylococcal Infection",
        "name_ja": "ブドウ球菌感染症",
        "symptoms": {"skin_lesions", "bumblefoot", "joint_swelling", "lethargy", "abscess", "lameness"},
        "description": "Staphylococcus aureus infection causing pododermatitis, arthritis, and abscesses.",
        "description_ja": "黄色ブドウ球菌による趾瘤症、関節炎、膿瘍を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "cytology"],
    },
    {
        "name": "Streptococcal Infection",
        "name_ja": "レンサ球菌感染症",
        "symptoms": {"lethargy", "respiratory_distress", "joint_swelling", "diarrhea", "sudden_death", "appetite_loss"},
        "description": "Streptococcus species causing septicemia, respiratory disease, and arthritis.",
        "description_ja": "レンサ球菌による敗血症、呼吸器疾患、関節炎。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Pasteurellosis",
        "name_ja": "パスツレラ症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "sudden_death", "swollen_joints", "diarrhea"},
        "description": "Pasteurella multocida infection often from cat bites/scratches, causing septicemia.",
        "description_ja": "猫の咬傷・引っかき傷からのパスツレラ・ムルトシダ感染で、敗血症を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "wound_culture", "CBC"],
    },
    {
        "name": "Bordetella Infection",
        "name_ja": "ボルデテラ感染症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "sneezing", "conjunctivitis", "lethargy", "voice_change"},
        "description": "Bordetella avium infection causing upper respiratory disease, especially in young birds.",
        "description_ja": "ボルデテラ・アビウムによる上部気道疾患で、特に幼鳥に多い。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "PCR_bordetella", "tracheal_wash"],
    },
    {
        "name": "Citrobacter Infection",
        "name_ja": "シトロバクター感染症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "respiratory_distress", "weight_loss"},
        "description": "Citrobacter species causing GI and systemic infections in immunocompromised birds.",
        "description_ja": "免疫不全の鳥におけるシトロバクター属による消化管・全身感染症。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    # ── 真菌性疾患 (Fungal Diseases) ──
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"labored_breathing", "weight_loss", "lethargy", "voice_change", "nasal_discharge", "tail_bobbing"},
        "description": "Fungal infection primarily affecting the respiratory tract, caused by Aspergillus species.",
        "description_ja": "アスペルギルス属による真菌感染症で、主に呼吸器系に影響する。",
        "urgency": "high",
        "recommended_tests": ["radiography", "endoscopy", "fungal_culture", "aspergillus_antigen_test"],
    },
    {
        "name": "Candidiasis",
        "name_ja": "カンジダ症",
        "symptoms": {"oral_plaques", "regurgitation", "crop_stasis", "appetite_loss", "white_patches_in_mouth", "lethargy"},
        "description": "Candida albicans overgrowth in the crop and oral cavity, often secondary to antibiotic use.",
        "description_ja": "抗生物質使用に二次的に発生するカンジダ・アルビカンスの口腔・嗉嚢内増殖。",
        "urgency": "moderate",
        "recommended_tests": ["crop_cytology", "gram_stain", "fungal_culture"],
    },
    {
        "name": "Megabacteriosis (Avian Gastric Yeast / AGY)",
        "name_ja": "メガバクテリア症（AGY）",
        "symptoms": {"weight_loss", "regurgitation", "undigested_food_in_droppings", "lethargy", "appetite_loss", "fluffed_feathers"},
        "description": "Macrorhabdus ornithogaster infection of the proventriculus causing chronic wasting.",
        "description_ja": "マクロラブダス・オルニトガスターによる腺胃感染症で、慢性消耗を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["fecal_gram_stain", "fecal_wet_mount", "endoscopy"],
    },
    {
        "name": "Cryptococcosis",
        "name_ja": "クリプトコッカス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "neurological_signs", "lethargy", "weight_loss", "granulomas"},
        "description": "Cryptococcus neoformans infection causing respiratory and CNS disease.",
        "description_ja": "クリプトコッカス・ネオフォルマンスによる呼吸器・中枢神経疾患。",
        "urgency": "high",
        "recommended_tests": ["cryptococcal_antigen_test", "cytology", "fungal_culture", "radiography"],
    },
    {
        "name": "Mucormycosis (Zygomycosis)",
        "name_ja": "ムコール症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "facial_swelling", "lethargy", "weight_loss", "skin_lesions"},
        "description": "Opportunistic fungal infection by Mucorales causing invasive respiratory and systemic disease.",
        "description_ja": "ムコール目による日和見真菌感染症で、侵襲性の呼吸器・全身疾患を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "fungal_culture"],
    },
    # ── 呼吸器疾患 (Respiratory Diseases) ──
    {
        "name": "Sinusitis",
        "name_ja": "副鼻腔炎",
        "symptoms": {"swollen_infraorbital_sinus", "nasal_discharge", "sneezing", "facial_swelling", "lethargy", "appetite_loss"},
        "description": "Inflammation of the infraorbital sinuses from bacterial, fungal, or viral causes.",
        "description_ja": "細菌・真菌・ウイルスによる眼窩下洞の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["sinus_flush_cytology", "bacterial_culture", "radiography"],
    },
    {
        "name": "Rhinitis",
        "name_ja": "鼻炎",
        "symptoms": {"nasal_discharge", "sneezing", "head_shaking", "labored_breathing", "periorbital_swelling"},
        "description": "Inflammation of the nasal passages causing discharge and sneezing.",
        "description_ja": "鼻腔の炎症により鼻汁やくしゃみを引き起こす。",
        "urgency": "low",
        "recommended_tests": ["nasal_flush_cytology", "bacterial_culture", "choanal_swab"],
    },
    {
        "name": "Air Sacculitis",
        "name_ja": "気嚢炎",
        "symptoms": {"labored_breathing", "tail_bobbing", "lethargy", "weight_loss", "respiratory_distress", "voice_change"},
        "description": "Infection or inflammation of the air sacs, often from Aspergillus, bacteria, or Chlamydia.",
        "description_ja": "アスペルギルス、細菌、クラミジアなどによる気嚢の感染・炎症。",
        "urgency": "high",
        "recommended_tests": ["radiography", "endoscopy", "air_sac_wash_cytology", "fungal_culture"],
    },
    {
        "name": "Tracheal Obstruction",
        "name_ja": "気管閉塞",
        "symptoms": {"severe_respiratory_distress", "stridor", "open_mouth_breathing", "cyanosis", "voice_change", "lethargy"},
        "description": "Mechanical blockage of the trachea by foreign body, abscess, or granuloma.",
        "description_ja": "異物、膿瘍、肉芽腫による気管の機械的閉塞。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "endoscopy", "CT_scan"],
    },
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"labored_breathing", "tail_bobbing", "lethargy", "nasal_discharge", "appetite_loss", "weight_loss", "respiratory_distress"},
        "description": "Bacterial, fungal, or viral infection of the lung parenchyma.",
        "description_ja": "細菌・真菌・ウイルスによる肺実質の感染症。",
        "urgency": "high",
        "recommended_tests": ["radiography", "tracheal_wash", "bacterial_culture", "CBC"],
    },
    {
        "name": "Air Sac Mites (Sternostoma tracheacolum)",
        "name_ja": "気嚢ダニ症（ステルノストマ）",
        "symptoms": {"labored_breathing", "clicking_breathing_sounds", "voice_change", "tail_bobbing", "open_mouth_breathing", "lethargy"},
        "description": "Parasitic mite infestation of the trachea and air sacs, common in finches and canaries.",
        "description_ja": "気管・気嚢に寄生するダニ感染症で、フィンチやカナリアに多い。",
        "urgency": "moderate",
        "recommended_tests": ["transillumination_trachea", "tracheal_wash", "fecal_exam"],
    },
    # ── 消化器疾患 (Gastrointestinal Diseases) ──
    {
        "name": "Crop Stasis (Crop Slowdown)",
        "name_ja": "嗉嚢停滞",
        "symptoms": {"crop_not_emptying", "regurgitation", "crop_distension", "lethargy", "appetite_loss", "sour_crop_odor"},
        "description": "Failure of the crop to empty properly due to infection, obstruction, or motility disorder.",
        "description_ja": "感染、閉塞、運動障害による嗉嚢内容物の排出不全。",
        "urgency": "high",
        "recommended_tests": ["crop_cytology", "radiography", "crop_culture", "gram_stain"],
    },
    {
        "name": "Crop Burn (Thermal Ingluvitis)",
        "name_ja": "嗉嚢火傷",
        "symptoms": {"crop_fistula", "crop_distension", "regurgitation", "appetite_loss", "lethargy", "skin_lesions"},
        "description": "Thermal injury to the crop from overheated hand-feeding formula, causing necrosis and fistula formation.",
        "description_ja": "加熱しすぎた挿し餌による嗉嚢の熱傷で、壊死や瘻孔形成を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiography", "crop_endoscopy"],
    },
    {
        "name": "Crop Foreign Body",
        "name_ja": "嗉嚢内異物",
        "symptoms": {"crop_distension", "regurgitation", "appetite_loss", "lethargy", "crop_not_emptying"},
        "description": "Ingestion of foreign material causing crop impaction or obstruction.",
        "description_ja": "異物摂取による嗉嚢の食滞または閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "contrast_radiography", "crop_endoscopy"],
    },
    {
        "name": "Ingluvitis (Crop Infection)",
        "name_ja": "嗉嚢炎",
        "symptoms": {"regurgitation", "crop_distension", "appetite_loss", "white_patches_in_mouth", "sour_crop_odor", "lethargy"},
        "description": "Infection of the crop lining by bacteria, yeast (Candida), or trichomonads.",
        "description_ja": "細菌、酵母（カンジダ）、トリコモナスによる嗉嚢粘膜の感染症。",
        "urgency": "moderate",
        "recommended_tests": ["crop_cytology", "gram_stain", "crop_culture"],
    },
    {
        "name": "Proventriculitis",
        "name_ja": "腺胃炎",
        "symptoms": {"regurgitation", "weight_loss", "appetite_loss", "lethargy", "undigested_food_in_droppings", "vomiting"},
        "description": "Inflammation of the proventriculus caused by infection, PDD, or toxins.",
        "description_ja": "感染、PDD、毒素による腺胃の炎症。",
        "urgency": "high",
        "recommended_tests": ["radiography", "fluoroscopy", "biopsy_crop", "CBC"],
    },
    {
        "name": "Ventriculitis (Gizzard Inflammation)",
        "name_ja": "筋胃炎",
        "symptoms": {"weight_loss", "regurgitation", "lethargy", "undigested_food_in_droppings", "appetite_loss", "dark_droppings"},
        "description": "Inflammation of the ventriculus (gizzard) from infection, foreign body, or heavy metal ingestion.",
        "description_ja": "感染、異物、重金属摂取による筋胃の炎症。",
        "urgency": "high",
        "recommended_tests": ["radiography", "heavy_metal_panel", "endoscopy"],
    },
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_protruding_from_vent", "straining", "bloody_droppings", "lethargy", "appetite_loss"},
        "description": "Protrusion of cloacal tissue through the vent, often from straining, infection, or masses.",
        "description_ja": "排泄孔からの総排泄腔組織の脱出で、いきみ、感染、腫瘤が原因となる。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "cloacal_culture", "radiography", "biopsy"],
    },
    {
        "name": "Cloacal Papillomatosis",
        "name_ja": "総排泄腔乳頭腫症",
        "symptoms": {"tissue_protruding_from_vent", "bloody_droppings", "straining", "weight_loss", "foul_smelling_discharge"},
        "description": "Papilloma virus-induced growths in the cloaca, associated with bile duct carcinoma in some species.",
        "description_ja": "パピローマウイルスによる総排泄腔の腫瘤で、一部の種では胆管癌と関連する。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology", "cloacal_exam", "PCR_papillomavirus"],
    },
    {
        "name": "Enteritis",
        "name_ja": "腸炎",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "weight_loss", "fluffed_feathers", "dehydration"},
        "description": "Inflammation of the intestines from bacterial, viral, parasitic, or dietary causes.",
        "description_ja": "細菌、ウイルス、寄生虫、食事性の原因による腸の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_gram_stain", "fecal_culture", "fecal_float", "CBC"],
    },
    {
        "name": "Gastrointestinal Foreign Body",
        "name_ja": "消化管異物",
        "symptoms": {"vomiting", "regurgitation", "appetite_loss", "lethargy", "abdominal_distension", "weight_loss"},
        "description": "Foreign material lodged in the GI tract causing obstruction.",
        "description_ja": "消化管内に停滞した異物による閉塞。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "contrast_radiography", "ultrasound", "endoscopy"],
    },
    # ── 肝臓疾患 (Hepatic Diseases) ──
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"obesity", "lethargy", "overgrown_beak", "overgrown_nails", "liver_enlargement", "breathing_difficulty", "poor_feather_quality"},
        "description": "Excessive fat accumulation in the liver, common in Amazon parrots and budgerigars on seed-only diets.",
        "description_ja": "肝臓への過度の脂肪蓄積で、種子食のみのアマゾンインコやセキセイインコに多い。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "liver_panel", "bile_acids"],
    },
    {
        "name": "Hepatitis",
        "name_ja": "肝炎",
        "symptoms": {"lethargy", "appetite_loss", "diarrhea_green", "liver_enlargement", "biliverdinuria", "weight_loss", "feather_discoloration"},
        "description": "Liver inflammation from infectious (bacterial, viral, chlamydial) or toxic causes.",
        "description_ja": "感染性（細菌、ウイルス、クラミジア）または中毒性の肝臓の炎症。",
        "urgency": "high",
        "recommended_tests": ["liver_panel", "bile_acids", "radiography", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Hemochromatosis (Iron Storage Disease)",
        "name_ja": "ヘモクロマトーシス（鉄蓄積症）",
        "symptoms": {"lethargy", "liver_enlargement", "abdominal_distension", "ascites", "respiratory_distress", "weight_loss"},
        "description": "Excessive iron deposition in the liver, common in toucans, mynahs, and birds of paradise.",
        "description_ja": "肝臓への過度の鉄沈着で、オオハシ、ムクドリ、フウチョウに多い。",
        "urgency": "high",
        "recommended_tests": ["liver_panel", "serum_iron", "liver_biopsy", "radiography"],
    },
    {
        "name": "Aflatoxicosis",
        "name_ja": "アフラトキシン中毒",
        "symptoms": {"appetite_loss", "lethargy", "liver_enlargement", "diarrhea", "weight_loss", "immunosuppression", "sudden_death"},
        "description": "Toxic liver damage from aflatoxins produced by Aspergillus flavus in contaminated feed.",
        "description_ja": "汚染飼料中のアスペルギルス・フラバスが産生するアフラトキシンによる肝毒性。",
        "urgency": "high",
        "recommended_tests": ["liver_panel", "bile_acids", "feed_analysis", "histopathology"],
    },
    {
        "name": "Hepatic Amyloidosis",
        "name_ja": "肝アミロイドーシス",
        "symptoms": {"liver_enlargement", "lethargy", "weight_loss", "ascites", "sudden_death", "appetite_loss"},
        "description": "Amyloid protein deposition in the liver associated with chronic inflammation, common in waterfowl.",
        "description_ja": "慢性炎症に関連した肝臓へのアミロイドタンパク沈着で、水禽に多い。",
        "urgency": "high",
        "recommended_tests": ["liver_biopsy", "histopathology", "liver_panel", "ultrasound"],
    },
    # ── 腎臓疾患 (Renal Diseases) ──
    {
        "name": "Renal Failure (Acute / Chronic)",
        "name_ja": "腎不全（急性／慢性）",
        "symptoms": {"polyuria", "polydipsia", "lethargy", "weight_loss", "dehydration", "gout_deposits", "lameness"},
        "description": "Loss of kidney function from infection, toxins, dehydration, or age-related degeneration.",
        "description_ja": "感染、毒素、脱水、加齢性変性による腎機能の喪失。",
        "urgency": "high",
        "recommended_tests": ["uric_acid_level", "CBC", "radiography", "ultrasound", "renal_biopsy"],
    },
    {
        "name": "Articular Gout",
        "name_ja": "関節痛風",
        "symptoms": {"joint_swelling", "lameness", "white_deposits_on_joints", "lethargy", "appetite_loss", "pain_vocalization"},
        "description": "Uric acid crystal deposition in joints due to hyperuricemia from renal insufficiency.",
        "description_ja": "腎不全による高尿酸血症に伴う関節への尿酸結晶沈着。",
        "urgency": "high",
        "recommended_tests": ["uric_acid_level", "radiography", "joint_aspirate", "renal_panel"],
    },
    {
        "name": "Visceral Gout",
        "name_ja": "内臓痛風",
        "symptoms": {"lethargy", "appetite_loss", "weight_loss", "dehydration", "sudden_death", "polyuria"},
        "description": "Uric acid deposition on visceral organ surfaces due to severe renal failure.",
        "description_ja": "重度の腎不全による内臓表面への尿酸沈着。",
        "urgency": "emergency",
        "recommended_tests": ["uric_acid_level", "CBC", "radiography", "necropsy"],
    },
    {
        "name": "Nephritis",
        "name_ja": "腎炎",
        "symptoms": {"polyuria", "lethargy", "weight_loss", "diarrhea", "dehydration", "appetite_loss"},
        "description": "Kidney inflammation from bacterial or viral infection.",
        "description_ja": "細菌またはウイルス感染による腎臓の炎症。",
        "urgency": "high",
        "recommended_tests": ["uric_acid_level", "CBC", "bacterial_culture", "radiography"],
    },
    {
        "name": "Renal Tumor (Renal Adenocarcinoma)",
        "name_ja": "腎腫瘍（腎腺癌）",
        "symptoms": {"lameness", "leg_paralysis", "abdominal_distension", "weight_loss", "polyuria", "lethargy"},
        "description": "Malignant kidney neoplasm causing unilateral leg paralysis from sciatic nerve compression.",
        "description_ja": "坐骨神経圧迫による片側肢麻痺を引き起こす悪性腎腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "biopsy", "CT_scan"],
    },
    # ── 内分泌疾患 (Endocrine Diseases) ──
    {
        "name": "Thyroid Goiter (Thyroid Hyperplasia)",
        "name_ja": "甲状腺腫",
        "symptoms": {"respiratory_distress", "regurgitation", "crop_distension", "voice_change", "weight_gain", "lethargy"},
        "description": "Thyroid gland enlargement from iodine deficiency, common in budgerigars on all-seed diets.",
        "description_ja": "ヨウ素欠乏による甲状腺の腫大で、種子食のセキセイインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "thyroid_hormone_panel", "ultrasound"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "appetite_increase", "poor_feather_quality"},
        "description": "Pancreatic islet cell dysfunction causing hyperglycemia, rare in birds.",
        "description_ja": "膵島細胞の機能障害による高血糖で、鳥では稀。",
        "urgency": "moderate",
        "recommended_tests": ["blood_glucose", "fructosamine", "CBC", "radiography"],
    },
    # ── 栄養性疾患 (Nutritional Diseases) ──
    {
        "name": "Vitamin A Deficiency (Hypovitaminosis A)",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"oral_plaques", "nasal_discharge", "sneezing", "poor_feather_quality", "blunted_choanal_papillae", "white_patches_in_mouth", "respiratory_distress"},
        "description": "Deficiency causing squamous metaplasia of epithelial surfaces, common in seed-diet birds.",
        "description_ja": "上皮表面の扁平上皮化生を引き起こすビタミンA欠乏で、種子食の鳥に多い。",
        "urgency": "moderate",
        "recommended_tests": ["plasma_vitamin_A", "choanal_exam", "physical_exam"],
    },
    {
        "name": "Calcium Deficiency (Hypocalcemia)",
        "name_ja": "カルシウム欠乏症（低カルシウム血症）",
        "symptoms": {"seizures", "tremors", "egg_binding", "weakness", "fractures", "lethargy", "poor_bone_density"},
        "description": "Inadequate calcium intake causing metabolic bone disease, seizures, and egg binding.",
        "description_ja": "カルシウム摂取不足による代謝性骨疾患、痙攣、卵詰まり。",
        "urgency": "high",
        "recommended_tests": ["ionized_calcium", "radiography", "CBC", "total_calcium"],
    },
    {
        "name": "Vitamin D Deficiency",
        "name_ja": "ビタミンD欠乏症",
        "symptoms": {"weakness", "fractures", "poor_bone_density", "lethargy", "stunted_growth", "bowed_legs"},
        "description": "Insufficient vitamin D3 causing impaired calcium metabolism and rickets.",
        "description_ja": "ビタミンD3不足によるカルシウム代謝障害およびくる病。",
        "urgency": "moderate",
        "recommended_tests": ["vitamin_D_level", "ionized_calcium", "radiography"],
    },
    {
        "name": "Iodine Deficiency",
        "name_ja": "ヨウ素欠乏症",
        "symptoms": {"respiratory_distress", "regurgitation", "weight_gain", "lethargy", "voice_change", "crop_distension"},
        "description": "Thyroid dysfunction from insufficient iodine causing goiter, mainly in budgerigars.",
        "description_ja": "ヨウ素不足による甲状腺機能障害で甲状腺腫を引き起こし、主にセキセイインコに見られる。",
        "urgency": "moderate",
        "recommended_tests": ["thyroid_hormone_panel", "radiography"],
    },
    {
        "name": "Iron Storage Disease (non-hemochromatosis)",
        "name_ja": "鉄蓄積症",
        "symptoms": {"lethargy", "liver_enlargement", "weight_loss", "respiratory_distress", "ascites", "abdominal_distension"},
        "description": "Iron overload in susceptible species (toucans, mynahs) from high-iron diets.",
        "description_ja": "高鉄分食による感受性種（オオハシ、ムクドリ）の鉄過剰。",
        "urgency": "high",
        "recommended_tests": ["serum_iron", "ferritin", "liver_biopsy", "liver_panel"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"obesity", "breathing_difficulty", "lethargy", "lipomas", "hepatic_lipidosis_signs", "poor_feather_quality", "reduced_activity"},
        "description": "Excess body fat from high-fat seed diets and lack of exercise, predisposing to hepatic lipidosis.",
        "description_ja": "高脂肪種子食と運動不足による過体重で、脂肪肝の素因となる。",
        "urgency": "moderate",
        "recommended_tests": ["body_condition_score", "radiography", "liver_panel", "cholesterol"],
    },
    {
        "name": "Malnutrition / Cachexia",
        "name_ja": "栄養失調／悪液質",
        "symptoms": {"weight_loss", "muscle_wasting", "lethargy", "poor_feather_quality", "immunosuppression", "weakness", "stunted_growth"},
        "description": "Generalized nutritional deficiency from inadequate diet or chronic disease.",
        "description_ja": "不適切な食事または慢性疾患による全身的な栄養欠乏。",
        "urgency": "moderate",
        "recommended_tests": ["CBC", "total_protein", "albumin", "physical_exam"],
    },
    {
        "name": "Vitamin E / Selenium Deficiency",
        "name_ja": "ビタミンE／セレン欠乏症",
        "symptoms": {"neurological_signs", "weakness", "torticollis", "muscle_wasting", "lethargy", "poor_feather_quality"},
        "description": "Deficiency causing encephalomalacia, myopathy, and immune dysfunction.",
        "description_ja": "脳軟化症、筋障害、免疫機能障害を引き起こすビタミンE／セレン欠乏。",
        "urgency": "moderate",
        "recommended_tests": ["vitamin_E_level", "selenium_level", "CBC"],
    },
    # ── 羽毛・皮膚疾患 (Feather and Skin Diseases) ──
    {
        "name": "Feather Plucking (Feather Destructive Behavior)",
        "name_ja": "毛引き症（羽毛破壊行動）",
        "symptoms": {"feather_loss", "feather_plucking", "skin_irritation", "self_mutilation", "bald_patches", "stress_bars_on_feathers"},
        "description": "Self-inflicted feather damage from medical, psychological, or environmental causes.",
        "description_ja": "医学的、心理的、環境的原因による自己誘発性の羽毛損傷。",
        "urgency": "moderate",
        "recommended_tests": ["CBC", "liver_panel", "thyroid_hormone_panel", "skin_biopsy", "behavioral_assessment"],
    },
    {
        "name": "French Molt (Budgerigar Fledgling Disease)",
        "name_ja": "フレンチモルト",
        "symptoms": {"feather_loss", "abnormal_feathers", "inability_to_fly", "stunted_growth", "feather_abnormalities"},
        "description": "Polyomavirus-associated feather disorder in young budgerigars causing flight/tail feather loss.",
        "description_ja": "若齢セキセイインコのポリオーマウイルス関連羽毛障害で、風切羽・尾羽の脱落を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["PCR_polyomavirus", "feather_biopsy", "physical_exam"],
    },
    {
        "name": "Folliculitis",
        "name_ja": "毛包炎",
        "symptoms": {"feather_loss", "skin_lesions", "swelling", "pain_vocalization", "redness_around_feather_follicles"},
        "description": "Bacterial or fungal infection of feather follicles causing inflammation.",
        "description_ja": "細菌または真菌による毛包の感染性炎症。",
        "urgency": "moderate",
        "recommended_tests": ["skin_cytology", "bacterial_culture", "skin_biopsy"],
    },
    {
        "name": "Pododermatitis (Bumblefoot)",
        "name_ja": "趾瘤症（バンブルフット）",
        "symptoms": {"bumblefoot", "lameness", "swollen_feet", "pain_vocalization", "reluctance_to_perch", "foot_lesions"},
        "description": "Plantar surface infection/inflammation from improper perching, obesity, or vitamin A deficiency.",
        "description_ja": "不適切な止まり木、肥満、ビタミンA欠乏による足底の感染・炎症。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "bacterial_culture", "radiography_feet", "biopsy"],
    },
    {
        "name": "Feather Cysts",
        "name_ja": "羽毛嚢胞",
        "symptoms": {"feather_cysts", "swelling", "feather_loss", "skin_lesions", "recurrent_lumps"},
        "description": "Abnormal feather growth curling within the follicle forming a keratin-filled cyst.",
        "description_ja": "毛包内で異常な羽毛が巻き込まれてケラチン充満嚢胞を形成する。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "cytology", "surgical_excision_biopsy"],
    },
    {
        "name": "Xanthomas",
        "name_ja": "黄色腫",
        "symptoms": {"yellow_skin_masses", "skin_lesions", "swelling", "feather_loss"},
        "description": "Cholesterol and lipid deposits forming yellowish masses under the skin, associated with hyperlipidemia.",
        "description_ja": "高脂血症に関連した皮下の黄色い脂質沈着腫瘤。",
        "urgency": "low",
        "recommended_tests": ["cholesterol", "lipid_panel", "biopsy", "histopathology"],
    },
    {
        "name": "Squamous Cell Carcinoma (Skin)",
        "name_ja": "扁平上皮癌（皮膚）",
        "symptoms": {"skin_lesions", "ulcerated_masses", "weight_loss", "lethargy", "bleeding"},
        "description": "Malignant skin tumor arising from squamous epithelium, often on uropygial gland or feet.",
        "description_ja": "扁平上皮から発生する悪性皮膚腫瘍で、尾脂腺や足に多い。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiography", "CT_scan"],
    },
    {
        "name": "Dermatitis",
        "name_ja": "皮膚炎",
        "symptoms": {"skin_irritation", "feather_loss", "redness_around_feather_follicles", "itching", "skin_lesions", "flaking_skin"},
        "description": "Inflammation of the skin from bacterial, fungal, allergic, or environmental causes.",
        "description_ja": "細菌、真菌、アレルギー、環境因子による皮膚の炎症。",
        "urgency": "low",
        "recommended_tests": ["skin_cytology", "bacterial_culture", "fungal_culture", "skin_biopsy"],
    },
    # ── 筋骨格系疾患 (Musculoskeletal Diseases) ──
    {
        "name": "Metabolic Bone Disease (MBD / Rickets)",
        "name_ja": "代謝性骨疾患（くる病）",
        "symptoms": {"fractures", "bowed_legs", "weakness", "poor_bone_density", "stunted_growth", "tremors", "inability_to_perch"},
        "description": "Calcium/phosphorus/vitamin D imbalance causing soft, deformed bones in growing birds.",
        "description_ja": "カルシウム／リン／ビタミンDの不均衡により成長中の鳥の骨が軟化・変形する。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ionized_calcium", "phosphorus", "vitamin_D_level"],
    },
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"fractures", "lameness", "wing_droop", "inability_to_fly", "pain_vocalization", "swelling"},
        "description": "Broken bones from trauma, metabolic bone disease, or pathological causes.",
        "description_ja": "外傷、代謝性骨疾患、病的原因による骨の破損。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "physical_exam", "CBC"],
    },
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "卵詰まり（難産）",
        "symptoms": {"egg_binding", "straining", "lethargy", "fluffed_feathers", "abdominal_distension", "leg_paralysis", "sitting_on_cage_floor"},
        "description": "Inability to pass an egg due to calcium deficiency, obesity, or oviductal dysfunction.",
        "description_ja": "カルシウム欠乏、肥満、卵管機能障害による卵の排出不能。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ionized_calcium", "physical_exam", "ultrasound"],
    },
    {
        "name": "Splay Leg (Spraddle Leg)",
        "name_ja": "開脚症",
        "symptoms": {"splay_legs", "inability_to_perch", "lameness", "stunted_growth"},
        "description": "Lateral deviation of one or both legs in neonatal birds from improper substrate or nutrition.",
        "description_ja": "不適切な床材や栄養不良による幼鳥の片側または両側肢の側方偏位。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Arthritis",
        "name_ja": "関節炎",
        "symptoms": {"joint_swelling", "lameness", "pain_vocalization", "reluctance_to_perch", "lethargy", "weight_loss"},
        "description": "Joint inflammation from infection (septic), gout, or degenerative causes.",
        "description_ja": "感染（化膿性）、痛風、変性による関節の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "joint_aspirate", "uric_acid_level", "bacterial_culture"],
    },
    {
        "name": "Osteoporosis",
        "name_ja": "骨粗鬆症",
        "symptoms": {"fractures", "weakness", "poor_bone_density", "lethargy", "egg_binding"},
        "description": "Reduced bone density from chronic calcium depletion, especially in chronic egg-laying hens.",
        "description_ja": "慢性的なカルシウム欠乏による骨密度低下で、特に慢性産卵鳥に多い。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "ionized_calcium", "total_calcium", "vitamin_D_level"],
    },
    {
        "name": "Constricted Toe Syndrome",
        "name_ja": "絞扼趾症候群",
        "symptoms": {"swollen_toes", "constriction_band_on_toe", "necrotic_toe", "lameness"},
        "description": "Fibrous constriction ring around toes in neonates causing ischemia, common in eclectus and macaws.",
        "description_ja": "幼鳥の趾に線維性絞扼輪が形成され虚血を引き起こす。エクレクタスやコンゴウインコに多い。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    # ── 神経疾患 (Neurological Diseases) ──
    {
        "name": "PDD Neurological Form",
        "name_ja": "PDD神経型",
        "symptoms": {"neurological_signs", "seizures", "ataxia", "tremors", "head_tilt", "blindness", "paralysis"},
        "description": "CNS manifestation of avian bornavirus causing encephalitis and neuropathy.",
        "description_ja": "鳥ボルナウイルスの中枢神経系症状で、脳炎および神経障害を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["PCR_bornavirus", "MRI", "CSF_analysis", "histopathology"],
    },
    {
        "name": "Lead Poisoning (Neurological)",
        "name_ja": "鉛中毒（神経型）",
        "symptoms": {"seizures", "ataxia", "blindness", "head_tilt", "tremors", "weakness", "paralysis", "dark_droppings"},
        "description": "CNS toxicity from lead ingestion causing seizures, ataxia, and visual impairment.",
        "description_ja": "鉛摂取による中枢神経毒性で、痙攣、運動失調、視覚障害を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "radiography", "CBC", "zinc_protoporphyrin"],
    },
    {
        "name": "Head Trauma",
        "name_ja": "頭部外傷",
        "symptoms": {"neurological_signs", "ataxia", "head_tilt", "loss_of_consciousness", "bleeding", "seizures", "blindness"},
        "description": "Traumatic brain injury from collision with windows, walls, or ceiling fans.",
        "description_ja": "窓、壁、天井扇風機との衝突による外傷性脳損傷。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiography", "CT_scan", "neurological_exam"],
    },
    {
        "name": "Seizure Disorder",
        "name_ja": "痙攣性疾患",
        "symptoms": {"seizures", "loss_of_consciousness", "tremors", "falling_off_perch", "ataxia", "disorientation"},
        "description": "Recurrent seizures from metabolic, toxic, infectious, or idiopathic causes.",
        "description_ja": "代謝性、中毒性、感染性、特発性の原因による反復性痙攣。",
        "urgency": "emergency",
        "recommended_tests": ["CBC", "blood_glucose", "ionized_calcium", "blood_lead_level", "radiography"],
    },
    {
        "name": "Star-Gazing (Opisthotonus)",
        "name_ja": "スターゲイジング（後弓反張）",
        "symptoms": {"star_gazing", "torticollis", "neurological_signs", "ataxia", "tremors", "inability_to_perch"},
        "description": "Dorsal neck extension posture indicating CNS disease from infection, toxins, or nutritional deficiency.",
        "description_ja": "感染、毒素、栄養欠乏による中枢神経疾患を示す背側頸部伸展姿勢。",
        "urgency": "high",
        "recommended_tests": ["CBC", "blood_lead_level", "vitamin_E_level", "PCR_paramyxovirus", "radiography"],
    },
    # ── 生殖器疾患 (Reproductive Diseases) ──
    {
        "name": "Egg Yolk Peritonitis",
        "name_ja": "卵黄性腹膜炎",
        "symptoms": {"abdominal_distension", "lethargy", "appetite_loss", "respiratory_distress", "weight_loss", "fluffed_feathers", "penguin_stance"},
        "description": "Free yolk material in the coelomic cavity causing peritonitis, often from ectopic ovulation.",
        "description_ja": "異所性排卵などによる体腔内の遊離卵黄物質が腹膜炎を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound", "coelomic_fluid_analysis", "CBC"],
    },
    {
        "name": "Chronic Egg Laying",
        "name_ja": "慢性産卵",
        "symptoms": {"excessive_egg_laying", "weight_loss", "lethargy", "calcium_depletion_signs", "poor_feather_quality", "egg_binding"},
        "description": "Persistent egg production depleting calcium and nutritional reserves.",
        "description_ja": "持続的な産卵によるカルシウムおよび栄養素の枯渇。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "ionized_calcium", "CBC", "hormonal_panel"],
    },
    {
        "name": "Oviductal Prolapse",
        "name_ja": "卵管脱",
        "symptoms": {"tissue_protruding_from_vent", "straining", "lethargy", "bloody_droppings", "appetite_loss"},
        "description": "Eversion of the oviduct through the cloaca, often during egg laying.",
        "description_ja": "産卵時などに卵管が総排泄腔から反転脱出する。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiography", "CBC"],
    },
    {
        "name": "Testicular Tumor",
        "name_ja": "精巣腫瘍",
        "symptoms": {"abdominal_distension", "cere_color_change", "weight_loss", "lethargy", "lameness", "feminization_signs"},
        "description": "Neoplasia of the testes, relatively common in budgerigars, causing hormonal changes.",
        "description_ja": "精巣の腫瘍で、セキセイインコに比較的多く、ホルモン変化を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "hormonal_panel", "biopsy"],
    },
    {
        "name": "Ovarian Tumor",
        "name_ja": "卵巣腫瘍",
        "symptoms": {"abdominal_distension", "lethargy", "weight_loss", "ascites", "respiratory_distress", "lameness"},
        "description": "Neoplasia of the ovary causing coelomic effusion and organ compression.",
        "description_ja": "卵巣の腫瘍で、体腔液貯留や臓器圧迫を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "coelomic_fluid_analysis", "biopsy"],
    },
    {
        "name": "Cystic Ovarian Disease",
        "name_ja": "卵巣嚢腫",
        "symptoms": {"abdominal_distension", "lethargy", "chronic_egg_laying_signs", "respiratory_distress", "weight_loss"},
        "description": "Fluid-filled cysts on the ovary causing abdominal distension and discomfort.",
        "description_ja": "卵巣上の液体充満嚢胞で、腹部膨満と不快感を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "radiography", "hormonal_panel", "coelomic_fluid_analysis"],
    },
    # ── 腫瘍性疾患 (Oncological Diseases) ──
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"lipomas", "subcutaneous_mass", "obesity", "difficulty_flying", "weight_gain", "lethargy"},
        "description": "Benign fatty tumor common in obese budgerigars, Amazons, and rose-breasted cockatoos.",
        "description_ja": "肥満のセキセイインコ、アマゾンインコ、モモイロインコに多い良性脂肪腫瘍。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "radiography", "cholesterol"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"subcutaneous_mass", "weight_loss", "lethargy", "ulcerated_masses", "swelling"},
        "description": "Malignant mesenchymal tumor of fibrous tissue, locally invasive.",
        "description_ja": "線維組織の悪性間葉系腫瘍で、局所浸潤性。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiography", "CT_scan"],
    },
    {
        "name": "Papilloma",
        "name_ja": "乳頭腫",
        "symptoms": {"oral_plaques", "tissue_protruding_from_vent", "skin_lesions", "regurgitation", "foul_smelling_discharge"},
        "description": "Benign epithelial growths caused by papillomavirus, found in oral cavity, cloaca, and skin.",
        "description_ja": "パピローマウイルスによる良性上皮性腫瘤で、口腔、総排泄腔、皮膚に発生。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology", "PCR_papillomavirus"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "lethargy", "liver_enlargement", "splenomegaly", "subcutaneous_mass", "appetite_loss"},
        "description": "Malignant lymphocyte proliferation affecting multiple organs.",
        "description_ja": "複数臓器に影響する悪性リンパ球増殖。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "CBC", "radiography", "ultrasound"],
    },
    {
        "name": "Pituitary Adenoma",
        "name_ja": "下垂体腺腫",
        "symptoms": {"neurological_signs", "blindness", "polydipsia", "polyuria", "obesity", "lethargy"},
        "description": "Benign pituitary gland tumor causing hormonal imbalances and neurological signs.",
        "description_ja": "下垂体の良性腫瘍で、ホルモン不均衡と神経症状を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["CT_scan", "MRI", "hormonal_panel", "radiography"],
    },
    {
        "name": "Bile Duct Carcinoma (Cholangiocarcinoma)",
        "name_ja": "胆管癌",
        "symptoms": {"liver_enlargement", "weight_loss", "lethargy", "appetite_loss", "biliverdinuria", "abdominal_distension"},
        "description": "Malignant bile duct tumor, often associated with papillomatosis in Amazon parrots.",
        "description_ja": "胆管の悪性腫瘍で、アマゾンインコの乳頭腫症と関連することが多い。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "liver_biopsy", "histopathology", "liver_panel"],
    },
    # ── 寄生虫疾患 (Parasitic Diseases) ──
    {
        "name": "Feather Mites",
        "name_ja": "羽毛ダニ",
        "symptoms": {"feather_loss", "itching", "feather_damage", "restlessness", "poor_feather_quality"},
        "description": "External mite infestation living on feather shafts causing feather damage.",
        "description_ja": "羽軸に寄生する外部ダニ感染で、羽毛損傷を引き起こす。",
        "urgency": "low",
        "recommended_tests": ["feather_exam_microscopy", "skin_scraping", "scotch_tape_test"],
    },
    {
        "name": "Red Mites (Dermanyssus gallinae)",
        "name_ja": "ワクモ（赤ダニ）",
        "symptoms": {"restlessness", "anemia", "itching", "lethargy", "weight_loss", "feather_loss", "nocturnal_distress"},
        "description": "Blood-feeding nocturnal mites hiding in cage crevices, causing anemia in heavy infestations.",
        "description_ja": "ケージの隙間に潜む夜行性吸血ダニで、大量寄生で貧血を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["cage_inspection_nocturnal", "CBC", "skin_scraping"],
    },
    {
        "name": "Lice (Mallophaga)",
        "name_ja": "羽シラミ",
        "symptoms": {"itching", "feather_damage", "restlessness", "poor_feather_quality", "feather_loss"},
        "description": "Chewing lice infesting feathers and skin, causing irritation and feather damage.",
        "description_ja": "羽毛や皮膚に寄生する咀嚼シラミで、刺激や羽毛損傷を引き起こす。",
        "urgency": "low",
        "recommended_tests": ["feather_exam_microscopy", "visual_inspection"],
    },
    {
        "name": "Roundworms (Ascaridia)",
        "name_ja": "回虫症（アスカリディア）",
        "symptoms": {"weight_loss", "diarrhea", "lethargy", "undigested_food_in_droppings", "abdominal_distension", "vomiting"},
        "description": "Intestinal nematode infection common in aviary birds and those with outdoor access.",
        "description_ja": "飼鳥舎の鳥や屋外アクセスのある鳥に多い腸管線虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_direct_smear", "fecal_PCR"],
    },
    {
        "name": "Tapeworms (Cestodes)",
        "name_ja": "条虫症",
        "symptoms": {"weight_loss", "diarrhea", "lethargy", "tapeworm_segments_in_droppings", "appetite_loss"},
        "description": "Cestode infestation requiring intermediate hosts, seen in birds with insect access.",
        "description_ja": "中間宿主を必要とする条虫感染で、昆虫にアクセスできる鳥に見られる。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "fecal_direct_smear", "physical_exam"],
    },
    {
        "name": "Capillaria (Hairworm)",
        "name_ja": "毛細線虫症（キャピラリア）",
        "symptoms": {"weight_loss", "diarrhea", "lethargy", "regurgitation", "oral_plaques", "crop_stasis"},
        "description": "Thread-like nematode infecting the crop, esophagus, and intestines.",
        "description_ja": "嗉嚢、食道、腸に感染する糸状の線虫。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "crop_cytology", "fecal_direct_smear"],
    },
    {
        "name": "Coccidia",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "bloody_droppings", "weight_loss", "lethargy", "dehydration", "fluffed_feathers"},
        "description": "Protozoan intestinal parasite causing enteritis, particularly in young or stressed birds.",
        "description_ja": "原虫性腸管寄生虫で、特に若鳥やストレス下の鳥に腸炎を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_direct_smear", "fecal_PCR"],
    },
    {
        "name": "Giardiasis",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "weight_loss", "feather_plucking", "itching", "lethargy", "malodorous_droppings"},
        "description": "Giardia protozoan infection of the intestines, common in cockatiels.",
        "description_ja": "ジアルジア原虫の腸管感染で、オカメインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_direct_smear", "fecal_antigen_test", "fecal_PCR"],
    },
    {
        "name": "Trichomoniasis",
        "name_ja": "トリコモナス症",
        "symptoms": {"oral_plaques", "regurgitation", "appetite_loss", "white_patches_in_mouth", "weight_loss", "labored_breathing"},
        "description": "Trichomonas gallinae infection causing caseous lesions in the oral cavity and crop.",
        "description_ja": "トリコモナス・ガリネによる口腔・嗉嚢の乾酪性病変。",
        "urgency": "high",
        "recommended_tests": ["crop_wet_mount", "crop_cytology", "oral_swab"],
    },
    {
        "name": "Atoxoplasmosis",
        "name_ja": "アトキソプラズマ症",
        "symptoms": {"lethargy", "fluffed_feathers", "weight_loss", "liver_enlargement", "sudden_death", "diarrhea"},
        "description": "Atoxoplasma (Isospora) infection causing hepatitis and systemic disease in passerines.",
        "description_ja": "アトキソプラズマ（イソスポラ）による肝炎および全身性疾患で、スズメ目に多い。",
        "urgency": "high",
        "recommended_tests": ["impression_smear", "histopathology", "fecal_float", "CBC"],
    },
    {
        "name": "Knemidocoptes (Scaly Face/Leg Mites)",
        "name_ja": "疥癬ダニ症（顔・脚の鱗状ダニ）",
        "symptoms": {"crusty_lesions_on_face", "crusty_lesions_on_legs", "beak_deformity", "itching", "feather_loss", "thickened_skin"},
        "description": "Burrowing mite causing honeycomb-like crusts on beak, cere, and feet, common in budgerigars.",
        "description_ja": "嘴、蝋膜、足にハニカム状の痂皮を形成する穿孔性ダニで、セキセイインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    # ── 心臓疾患 (Cardiac Diseases) ──
    {
        "name": "Atherosclerosis",
        "name_ja": "動脈硬化症",
        "symptoms": {"lethargy", "respiratory_distress", "sudden_death", "exercise_intolerance", "weight_loss", "collapse"},
        "description": "Cholesterol plaque buildup in arteries, common in older Amazons, macaws, and African greys.",
        "description_ja": "動脈内のコレステロールプラーク蓄積で、高齢のアマゾン、コンゴウ、ヨウムに多い。",
        "urgency": "high",
        "recommended_tests": ["radiography", "echocardiography", "cholesterol", "ECG"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"respiratory_distress", "lethargy", "ascites", "exercise_intolerance", "cyanosis", "weight_loss", "collapse"},
        "description": "Inadequate cardiac output causing fluid accumulation and systemic compromise.",
        "description_ja": "心拍出量不足による体液貯留と全身状態の悪化。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "echocardiography", "ECG", "CBC"],
    },
    {
        "name": "Pericardial Effusion",
        "name_ja": "心嚢液貯留",
        "symptoms": {"respiratory_distress", "lethargy", "muffled_heart_sounds", "exercise_intolerance", "collapse", "ascites"},
        "description": "Fluid accumulation in the pericardial sac compromising cardiac function.",
        "description_ja": "心嚢内の液体貯留により心機能が障害される。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "radiography", "pericardiocentesis", "cytology"],
    },
    # ── 中毒性疾患 (Toxicological Diseases) ──
    {
        "name": "PTFE / Teflon Toxicosis",
        "name_ja": "PTFE／テフロン中毒",
        "symptoms": {"sudden_death", "respiratory_distress", "cyanosis", "falling_off_perch", "labored_breathing"},
        "description": "Acute fatal respiratory toxicity from overheated PTFE-coated cookware fumes.",
        "description_ja": "過熱されたPTFEコーティング調理器具の煙による急性致死性呼吸器中毒。",
        "urgency": "emergency",
        "recommended_tests": ["history_of_exposure", "necropsy", "lung_histopathology"],
    },
    {
        "name": "Avocado Toxicity",
        "name_ja": "アボカド中毒",
        "symptoms": {"respiratory_distress", "lethargy", "sudden_death", "fluffed_feathers", "cardiac_arrest_signs", "weakness"},
        "description": "Persin toxin in avocado causing myocardial necrosis and respiratory failure.",
        "description_ja": "アボカドのペルシンによる心筋壊死と呼吸不全。",
        "urgency": "emergency",
        "recommended_tests": ["history_of_ingestion", "ECG", "physical_exam"],
    },
    {
        "name": "Lead Poisoning (Plumbism)",
        "name_ja": "鉛中毒",
        "symptoms": {"regurgitation", "seizures", "ataxia", "lethargy", "diarrhea_green", "weight_loss", "polyuria", "dark_droppings", "blindness"},
        "description": "Systemic toxicity from ingesting lead-containing materials such as paint, curtain weights, or stained glass.",
        "description_ja": "塗料、カーテンウェイト、ステンドグラスなどの鉛含有物質の摂取による全身中毒。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "radiography", "CBC", "zinc_protoporphyrin"],
    },
    {
        "name": "Zinc Poisoning",
        "name_ja": "亜鉛中毒",
        "symptoms": {"regurgitation", "diarrhea", "lethargy", "weight_loss", "polyuria", "anemia", "weakness"},
        "description": "Toxicity from ingesting galvanized metal, zinc-coated cage wire, or zinc coins.",
        "description_ja": "亜鉛メッキ金属、亜鉛コーティングケージワイヤー、亜鉛硬貨の摂取による中毒。",
        "urgency": "high",
        "recommended_tests": ["blood_zinc_level", "radiography", "CBC"],
    },
    {
        "name": "Copper Poisoning",
        "name_ja": "銅中毒",
        "symptoms": {"regurgitation", "diarrhea", "lethargy", "liver_enlargement", "weight_loss", "dark_droppings"},
        "description": "Hepatotoxicity from copper ingestion or copper-containing water sources.",
        "description_ja": "銅の摂取または銅含有水源による肝毒性。",
        "urgency": "high",
        "recommended_tests": ["liver_panel", "serum_copper_level", "radiography", "liver_biopsy"],
    },
    {
        "name": "Chocolate Toxicity",
        "name_ja": "チョコレート中毒",
        "symptoms": {"vomiting", "diarrhea", "seizures", "hyperactivity", "tremors", "cardiac_arrest_signs", "sudden_death"},
        "description": "Theobromine and caffeine toxicity from chocolate ingestion causing cardiac and neurological signs.",
        "description_ja": "チョコレート摂取によるテオブロミンおよびカフェイン中毒で、心臓・神経症状を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["history_of_ingestion", "ECG", "physical_exam"],
    },
    # ── 行動異常 (Behavioral Disorders) ──
    {
        "name": "Feather Destructive Behavior (FDB)",
        "name_ja": "羽毛破壊行動",
        "symptoms": {"feather_plucking", "feather_loss", "bald_patches", "self_mutilation", "stress_bars_on_feathers", "skin_irritation"},
        "description": "Complex behavioral disorder with feather damaging, multifactorial etiology including stress and boredom.",
        "description_ja": "ストレスや退屈を含む多因子的病因による羽毛損傷を伴う複雑な行動障害。",
        "urgency": "moderate",
        "recommended_tests": ["behavioral_assessment", "CBC", "liver_panel", "thyroid_hormone_panel", "skin_biopsy"],
    },
    {
        "name": "Screaming (Excessive Vocalization)",
        "name_ja": "過剰発声（叫び行動）",
        "symptoms": {"screaming", "aggression", "restlessness", "stereotypic_behavior"},
        "description": "Excessive vocalization from attention-seeking, hormonal, environmental, or fear-based causes.",
        "description_ja": "注意引き、ホルモン、環境、恐怖に基づく過剰な発声行動。",
        "urgency": "low",
        "recommended_tests": ["behavioral_assessment", "physical_exam", "hormonal_panel"],
    },
    {
        "name": "Self-Mutilation",
        "name_ja": "自傷行為",
        "symptoms": {"self_mutilation", "bleeding", "skin_lesions", "feather_loss", "open_wounds"},
        "description": "Severe self-inflicted tissue damage beyond feather plucking, requiring urgent intervention.",
        "description_ja": "毛引きを超えた重度の自己誘発性組織損傷で、緊急介入を要する。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "CBC", "behavioral_assessment", "skin_biopsy", "liver_panel"],
    },
    {
        "name": "Phobic Behavior",
        "name_ja": "恐怖症行動",
        "symptoms": {"feather_plucking", "thrashing_in_cage", "night_frights", "self_mutilation", "restlessness", "screaming"},
        "description": "Extreme fear responses to specific stimuli or generalized anxiety, common in cockatoos.",
        "description_ja": "特定の刺激や全般的な不安に対する極端な恐怖反応で、オウムに多い。",
        "urgency": "moderate",
        "recommended_tests": ["behavioral_assessment", "physical_exam"],
    },
    # ── 眼科疾患 (Ophthalmological Diseases) ──
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"conjunctivitis", "eye_discharge", "eye_swelling", "eye_rubbing", "lethargy"},
        "description": "Inflammation of the conjunctiva from bacterial, viral, chlamydial, or irritant causes.",
        "description_ja": "細菌、ウイルス、クラミジア、刺激物による結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["eye_culture", "conjunctival_cytology", "PCR_chlamydia", "ophthalmologic_exam"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"vision_loss", "eye_cloudiness", "clumsiness", "reluctance_to_fly", "lethargy"},
        "description": "Opacity of the lens causing vision impairment, from age, trauma, or nutritional deficiency.",
        "description_ja": "加齢、外傷、栄養欠乏による水晶体混濁で視力障害を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmologic_exam", "slit_lamp_exam", "ultrasound_eye"],
    },
    {
        "name": "Uveitis",
        "name_ja": "ぶどう膜炎",
        "symptoms": {"eye_swelling", "eye_discharge", "vision_loss", "eye_cloudiness", "photophobia", "lethargy"},
        "description": "Inflammation of the uveal tract from infection, trauma, or immune-mediated causes.",
        "description_ja": "感染、外傷、免疫介在性の原因によるぶどう膜の炎症。",
        "urgency": "high",
        "recommended_tests": ["ophthalmologic_exam", "eye_culture", "CBC", "serology"],
    },
    {
        "name": "Periorbital Abscess (Retrobulbar Abscess)",
        "name_ja": "眼窩周囲膿瘍",
        "symptoms": {"eye_swelling", "periorbital_swelling", "facial_swelling", "lethargy", "appetite_loss", "nasal_discharge"},
        "description": "Abscess formation behind or around the eye from sinusitis or ascending infection.",
        "description_ja": "副鼻腔炎や上行性感染による眼窩後部または周囲の膿瘍形成。",
        "urgency": "high",
        "recommended_tests": ["radiography", "CT_scan", "bacterial_culture", "cytology"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "abnormal_feathers": {"ja": "異常羽毛", "en": "Abnormal feathers"},
    "abscess": {"ja": "膿瘍", "en": "Abscess"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "appetite_increase": {"ja": "食欲増進", "en": "Increased appetite"},
    "appetite_loss": {"ja": "食欲不振", "en": "Loss of appetite"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    "ataxia": {"ja": "運動失調", "en": "Ataxia"},
    "bald_patches": {"ja": "脱羽部位", "en": "Bald patches"},
    "beak_deformity": {"ja": "嘴変形", "en": "Beak deformity"},
    "biliverdinuria": {"ja": "ビリベルジン尿", "en": "Biliverdinuria (green urates)"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "blindness": {"ja": "失明", "en": "Blindness"},
    "bloody_droppings": {"ja": "血便", "en": "Bloody droppings"},
    "blunted_choanal_papillae": {"ja": "鈍化した後鼻孔乳頭", "en": "Blunted choanal papillae"},
    "bowed_legs": {"ja": "弯曲肢", "en": "Bowed legs"},
    "breathing_difficulty": {"ja": "呼吸困難", "en": "Breathing difficulty"},
    "bumblefoot": {"ja": "趾瘤症", "en": "Bumblefoot"},
    "calcium_depletion_signs": {"ja": "カルシウム欠乏徴候", "en": "Calcium depletion signs"},
    "cardiac_arrest_signs": {"ja": "心停止徴候", "en": "Cardiac arrest signs"},
    "cere_color_change": {"ja": "蝋膜の色変化", "en": "Cere color change"},
    "chronic_egg_laying_signs": {"ja": "慢性産卵徴候", "en": "Chronic egg laying signs"},
    "clicking_breathing_sounds": {"ja": "クリック音呼吸", "en": "Clicking breathing sounds"},
    "clumsiness": {"ja": "動作のぎこちなさ", "en": "Clumsiness"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "constriction_band_on_toe": {"ja": "趾の絞扼帯", "en": "Constriction band on toe"},
    "crop_distension": {"ja": "嗉嚢膨満", "en": "Crop distension"},
    "crop_fistula": {"ja": "嗉嚢瘻", "en": "Crop fistula"},
    "crop_not_emptying": {"ja": "嗉嚢内容物停滞", "en": "Crop not emptying"},
    "crop_stasis": {"ja": "嗉嚢停滞", "en": "Crop stasis"},
    "crusty_lesions_on_face": {"ja": "顔面の痂皮性病変", "en": "Crusty lesions on face"},
    "crusty_lesions_on_legs": {"ja": "脚の痂皮性病変", "en": "Crusty lesions on legs"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "dark_droppings": {"ja": "暗色便", "en": "Dark droppings"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "diarrhea_green": {"ja": "緑色下痢", "en": "Green diarrhea"},
    "diarrhea_yellow_green": {"ja": "黄緑色下痢", "en": "Yellow-green diarrhea"},
    "difficulty_flying": {"ja": "飛行困難", "en": "Difficulty flying"},
    "disorientation": {"ja": "見当識障害", "en": "Disorientation"},
    "drop_in_egg_production": {"ja": "産卵率低下", "en": "Drop in egg production"},
    "edema_head": {"ja": "頭部浮腫", "en": "Head edema"},
    "egg_binding": {"ja": "卵詰まり", "en": "Egg binding"},
    "excessive_egg_laying": {"ja": "過剰産卵", "en": "Excessive egg laying"},
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise intolerance"},
    "eye_cloudiness": {"ja": "眼の混濁", "en": "Eye cloudiness"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "eye_rubbing": {"ja": "眼をこする", "en": "Eye rubbing"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "falling_off_perch": {"ja": "止まり木からの落下", "en": "Falling off perch"},
    "feather_abnormalities": {"ja": "羽毛異常", "en": "Feather abnormalities"},
    "feather_cysts": {"ja": "羽毛嚢胞", "en": "Feather cysts"},
    "feather_damage": {"ja": "羽毛損傷", "en": "Feather damage"},
    "feather_discoloration": {"ja": "羽毛変色", "en": "Feather discoloration"},
    "feather_loss": {"ja": "脱羽", "en": "Feather loss"},
    "feather_plucking": {"ja": "毛引き", "en": "Feather plucking"},
    "feminization_signs": {"ja": "雌性化徴候", "en": "Feminization signs"},
    "flaking_skin": {"ja": "皮膚の剥離", "en": "Flaking skin"},
    "fluffed_feathers": {"ja": "羽毛膨らませ", "en": "Fluffed feathers"},
    "foot_lesions": {"ja": "足部病変", "en": "Foot lesions"},
    "foul_smelling_discharge": {"ja": "悪臭を伴う排出物", "en": "Foul-smelling discharge"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "gout_deposits": {"ja": "痛風沈着", "en": "Gout deposits"},
    "granulomas": {"ja": "肉芽腫", "en": "Granulomas"},
    "head_shaking": {"ja": "頭振り", "en": "Head shaking"},
    "head_tilt": {"ja": "頭部傾斜", "en": "Head tilt"},
    "hepatic_lipidosis_signs": {"ja": "肝リピドーシス徴候", "en": "Hepatic lipidosis signs"},
    "hyperactivity": {"ja": "過活動", "en": "Hyperactivity"},
    "immunosuppression": {"ja": "免疫抑制", "en": "Immunosuppression"},
    "inability_to_fly": {"ja": "飛行不能", "en": "Inability to fly"},
    "inability_to_perch": {"ja": "止まり木に止まれない", "en": "Inability to perch"},
    "itching": {"ja": "掻痒", "en": "Itching"},
    "joint_swelling": {"ja": "関節腫脹", "en": "Joint swelling"},
    "labored_breathing": {"ja": "努力呼吸", "en": "Labored breathing"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "leg_paralysis": {"ja": "脚麻痺", "en": "Leg paralysis"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "lipomas": {"ja": "脂肪腫", "en": "Lipomas"},
    "liver_enlargement": {"ja": "肝腫大", "en": "Liver enlargement"},
    "loss_of_consciousness": {"ja": "意識消失", "en": "Loss of consciousness"},
    "malodorous_droppings": {"ja": "悪臭便", "en": "Malodorous droppings"},
    "muffled_heart_sounds": {"ja": "心音減弱", "en": "Muffled heart sounds"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal discharge"},
    "necrotic_toe": {"ja": "壊死趾", "en": "Necrotic toe"},
    "neurological_signs": {"ja": "神経症状", "en": "Neurological signs"},
    "night_frights": {"ja": "夜間パニック", "en": "Night frights"},
    "nocturnal_distress": {"ja": "夜間の苦痛", "en": "Nocturnal distress"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "open_mouth_breathing": {"ja": "開口呼吸", "en": "Open-mouth breathing"},
    "open_wounds": {"ja": "開放創", "en": "Open wounds"},
    "oral_plaques": {"ja": "口腔内プラーク", "en": "Oral plaques"},
    "overgrown_beak": {"ja": "嘴過長", "en": "Overgrown beak"},
    "overgrown_nails": {"ja": "爪過長", "en": "Overgrown nails"},
    "pain_vocalization": {"ja": "疼痛発声", "en": "Pain vocalization"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "penguin_stance": {"ja": "ペンギン姿勢", "en": "Penguin stance"},
    "periorbital_swelling": {"ja": "眼窩周囲腫脹", "en": "Periorbital swelling"},
    "photophobia": {"ja": "羞明", "en": "Photophobia"},
    "polydipsia": {"ja": "多飲", "en": "Polydipsia"},
    "polyuria": {"ja": "多尿", "en": "Polyuria"},
    "poor_bone_density": {"ja": "骨密度低下", "en": "Poor bone density"},
    "poor_feather_quality": {"ja": "羽毛質低下", "en": "Poor feather quality"},
    "recurrent_lumps": {"ja": "再発性腫瘤", "en": "Recurrent lumps"},
    "redness_around_feather_follicles": {"ja": "毛包周囲の発赤", "en": "Redness around feather follicles"},
    "reduced_activity": {"ja": "活動量低下", "en": "Reduced activity"},
    "regurgitation": {"ja": "吐き戻し", "en": "Regurgitation"},
    "reluctance_to_fly": {"ja": "飛ぶことへの消極性", "en": "Reluctance to fly"},
    "reluctance_to_perch": {"ja": "止まり木への消極性", "en": "Reluctance to perch"},
    "respiratory_distress": {"ja": "呼吸窮迫", "en": "Respiratory distress"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "screaming": {"ja": "叫び", "en": "Screaming"},
    "seizures": {"ja": "痙攣", "en": "Seizures"},
    "self_mutilation": {"ja": "自傷行為", "en": "Self-mutilation"},
    "severe_respiratory_distress": {"ja": "重度呼吸窮迫", "en": "Severe respiratory distress"},
    "sinusitis": {"ja": "副鼻腔炎", "en": "Sinusitis"},
    "sitting_on_cage_floor": {"ja": "ケージ底に座る", "en": "Sitting on cage floor"},
    "skin_irritation": {"ja": "皮膚刺激", "en": "Skin irritation"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "sour_crop_odor": {"ja": "嗉嚢の酸臭", "en": "Sour crop odor"},
    "splay_legs": {"ja": "開脚", "en": "Splay legs"},
    "splenomegaly": {"ja": "脾腫", "en": "Splenomegaly"},
    "star_gazing": {"ja": "スターゲイジング", "en": "Star-gazing"},
    "stereotypic_behavior": {"ja": "常同行動", "en": "Stereotypic behavior"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "stress_bars_on_feathers": {"ja": "羽毛のストレスバー", "en": "Stress bars on feathers"},
    "stridor": {"ja": "喘鳴", "en": "Stridor"},
    "stunted_growth": {"ja": "発育不良", "en": "Stunted growth"},
    "subcutaneous_hemorrhage": {"ja": "皮下出血", "en": "Subcutaneous hemorrhage"},
    "subcutaneous_mass": {"ja": "皮下腫瘤", "en": "Subcutaneous mass"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "swollen_feet": {"ja": "足の腫脹", "en": "Swollen feet"},
    "swollen_infraorbital_sinus": {"ja": "眼窩下洞腫脹", "en": "Swollen infraorbital sinus"},
    "swollen_joints": {"ja": "関節腫脹", "en": "Swollen joints"},
    "swollen_toes": {"ja": "趾の腫脹", "en": "Swollen toes"},
    "tail_bobbing": {"ja": "尾振り呼吸", "en": "Tail bobbing"},
    "tapeworm_segments_in_droppings": {"ja": "糞中の条虫片節", "en": "Tapeworm segments in droppings"},
    "thickened_skin": {"ja": "皮膚肥厚", "en": "Thickened skin"},
    "thrashing_in_cage": {"ja": "ケージ内での暴れ", "en": "Thrashing in cage"},
    "tissue_protruding_from_vent": {"ja": "排泄孔からの組織脱出", "en": "Tissue protruding from vent"},
    "torticollis": {"ja": "斜頸", "en": "Torticollis"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "ulcerated_masses": {"ja": "潰瘍化腫瘤", "en": "Ulcerated masses"},
    "undigested_food_in_droppings": {"ja": "糞中の未消化食物", "en": "Undigested food in droppings"},
    "vision_loss": {"ja": "視力喪失", "en": "Vision loss"},
    "voice_change": {"ja": "声の変化", "en": "Voice change"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "white_deposits_on_joints": {"ja": "関節上の白色沈着物", "en": "White deposits on joints"},
    "white_patches_in_mouth": {"ja": "口腔内白色斑", "en": "White patches in mouth"},
    "wing_droop": {"ja": "翼下垂", "en": "Wing droop"},
    "yellow_skin_masses": {"ja": "黄色皮膚腫瘤", "en": "Yellow skin masses"},
}


def analyze_symptoms(
    symptoms: List[str], age_stage: str = "", breed: str | None = None
) -> Dict[str, Any]:
    """鳥類用の鑑別診断関数。"""
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
