"""Chinchilla disease dictionary and analysis module.

Comprehensive disease reference covering dental, gastrointestinal,
dermatological, respiratory, urinary, reproductive, musculoskeletal,
neurological, ophthalmological, cardiac, metabolic, infectious, parasitic,
and oncological conditions commonly seen in chinchillas.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic


DISEASES: List[Dict[str, Any]] = [
    # ── Dental ──────────────────────────────────────────────────────────
    {
        "name": "Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "difficulty_eating", "pawing_at_mouth"},
        "description": "Misalignment of incisors or cheek teeth preventing normal chewing. Very common in chinchillas due to continuously growing teeth.",
        "description_ja": "切歯または臼歯の不整合により正常な咀嚼ができない状態です。常生歯であるチンチラでは非常に多い疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    {
        "name": "Molar Elongation",
        "name_ja": "臼歯過長症",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "difficulty_eating", "eye_discharge"},
        "description": "Overgrowth of molar teeth causing sharp spurs that lacerate the tongue or cheeks. Apical elongation can compress the nasolacrimal duct.",
        "description_ja": "臼歯の過長により鋭い突起が舌や頬を傷つけます。根尖部の伸長は鼻涙管を圧迫することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs", "ct_scan"],
    },
    {
        "name": "Dental Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "drooling", "appetite_loss", "nasal_discharge", "eye_discharge", "pain"},
        "description": "Periapical infection of tooth roots forming an abscess in the jaw. May erode through bone and cause facial swelling.",
        "description_ja": "歯根周囲の感染により顎骨に膿瘍が形成されます。骨を侵食して顔面腫脹を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiographs", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Slobbers (Ptyalism)",
        "name_ja": "流涎症",
        "symptoms": {"drooling", "wet_chin", "matted_fur_chin", "appetite_loss", "weight_loss"},
        "description": "Excessive salivation typically secondary to dental disease causing wet, matted fur on the chin and chest.",
        "description_ja": "通常は歯科疾患に続発する過度の流涎で、顎や胸部の被毛が濡れて固まります。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    # ── Gastrointestinal ────────────────────────────────────────────────
    {
        "name": "GI Stasis",
        "name_ja": "消化管うっ滞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "small_dry_feces", "lethargy", "abdominal_pain", "hunched_posture"},
        "description": "Slowing or cessation of normal gastrointestinal motility. A common and potentially life-threatening condition in chinchillas.",
        "description_ja": "消化管の蠕動運動が低下または停止する状態です。チンチラでは一般的で生命を脅かす可能性があります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_radiographs", "physical_exam", "blood_panel"],
    },
    {
        "name": "Bloat (Gastric Tympany)",
        "name_ja": "鼓腸症",
        "symptoms": {"abdominal_distension", "abdominal_pain", "lethargy", "appetite_loss", "dyspnea", "hunched_posture"},
        "description": "Accumulation of gas in the stomach or intestines causing painful distension. Can progress rapidly to shock.",
        "description_ja": "胃または腸にガスが貯留して痛みを伴う膨満を引き起こします。急速にショック状態に進行する可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_radiographs", "physical_exam"],
    },
    {
        "name": "Constipation",
        "name_ja": "便秘",
        "symptoms": {"reduced_fecal_output", "small_dry_feces", "straining_to_defecate", "appetite_loss", "lethargy"},
        "description": "Difficulty passing feces often due to dehydration, dietary insufficiency, or GI motility issues.",
        "description_ja": "脱水、食事の不足、または消化管蠕動の問題により排便が困難になる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_radiographs", "physical_exam", "diet_history"],
    },
    {
        "name": "Diarrhea",
        "name_ja": "下痢",
        "symptoms": {"loose_stool", "soiled_perineum", "dehydration", "lethargy", "appetite_loss"},
        "description": "Loose or watery stools that may indicate dietary issues, infection, or parasites. Can cause rapid dehydration.",
        "description_ja": "軟便や水様便で、食事の問題、感染症、寄生虫などが原因となります。急速に脱水を引き起こす可能性があります。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "fecal_culture", "blood_panel"],
    },
    {
        "name": "Enteritis",
        "name_ja": "腸炎",
        "symptoms": {"diarrhea", "loose_stool", "appetite_loss", "lethargy", "dehydration", "abdominal_pain"},
        "description": "Inflammation of the intestinal lining caused by bacterial, viral, or parasitic pathogens.",
        "description_ja": "細菌、ウイルス、寄生虫などの病原体による腸管粘膜の炎症です。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "fecal_culture", "blood_panel", "abdominal_radiographs"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス",
        "symptoms": {"appetite_loss", "weight_loss", "lethargy", "jaundice", "abdominal_distension"},
        "description": "Fatty infiltration of the liver often triggered by anorexia or obesity. Common in chinchillas that stop eating.",
        "description_ja": "食欲不振や肥満がきっかけで肝臓に脂肪が蓄積する疾患です。食事を停止したチンチラに多く見られます。",
        "urgency": "high",
        "recommended_tests": ["blood_panel", "liver_enzymes", "abdominal_ultrasound"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"tissue_protruding_anus", "straining_to_defecate", "diarrhea", "bleeding_rectum", "pain"},
        "description": "Protrusion of rectal tissue through the anus, often associated with chronic diarrhea or straining.",
        "description_ja": "慢性の下痢やいきみに伴い、直腸組織が肛門から突出する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_exam"],
    },
    {
        "name": "Cecal Torsion",
        "name_ja": "盲腸捻転",
        "symptoms": {"abdominal_distension", "abdominal_pain", "lethargy", "appetite_loss", "collapse", "shock"},
        "description": "Rotation of the cecum cutting off blood supply. A surgical emergency with rapid clinical deterioration.",
        "description_ja": "盲腸が捻転して血液供給が遮断される外科的緊急疾患です。急速に臨床状態が悪化します。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_radiographs", "abdominal_ultrasound", "blood_panel"],
    },
    # ── Dermatological ──────────────────────────────────────────────────
    {
        "name": "Fur Slip",
        "name_ja": "ファースリップ（脱毛）",
        "symptoms": {"fur_loss_patches", "bare_skin_patches", "stress"},
        "description": "Release of large patches of fur as a defense mechanism when handled roughly or stressed. Unique to chinchillas.",
        "description_ja": "乱暴な取り扱いやストレス時に防御機構として大きな毛の塊が抜け落ちる現象です。チンチラ特有の反応です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Fur Ring",
        "name_ja": "ファーリング（陰茎毛輪）",
        "symptoms": {"fur_ring_penis", "excessive_grooming_genital", "penile_swelling", "straining_to_urinate", "pain"},
        "description": "Ring of fur wrapped around the penis constricting blood flow. Requires manual removal to prevent necrosis.",
        "description_ja": "毛が陰茎に巻き付いて血流を阻害する状態です。壊死を防ぐため手動での除去が必要です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "genital_exam"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"fur_loss_patches", "crusty_skin", "scaling_skin", "redness_skin", "itching"},
        "description": "Fungal skin infection caused by Trichophyton mentagrophytes. Causes circular patches of hair loss with scaly skin.",
        "description_ja": "Trichophyton mentagrophytesによる真菌性皮膚感染症です。鱗屑を伴う円形の脱毛を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "woods_lamp"],
    },
    {
        "name": "Fur Chewing (Barbering)",
        "name_ja": "毛噛み（バーバリング）",
        "symptoms": {"fur_chewing", "patchy_short_fur", "stress", "boredom_signs"},
        "description": "Self-barbering or barbering of cage mates. Often behavioral due to stress, boredom, or dietary deficiency.",
        "description_ja": "自分自身またはケージメイトの毛を噛む行動です。ストレス、退屈、栄養不足による行動的要因が多いです。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "diet_history", "behavioral_assessment"],
    },
    {
        "name": "Ear Dermatitis",
        "name_ja": "耳介皮膚炎",
        "symptoms": {"ear_flaking", "ear_redness", "ear_thickening", "itching", "head_shaking"},
        "description": "Flaking, crusting, and thickening of the ear pinnae. May be related to low humidity or fungal infection.",
        "description_ja": "耳介の剥離、痂皮、肥厚が見られます。低湿度や真菌感染に関連することがあります。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "fungal_culture", "physical_exam"],
    },
    {
        "name": "Bumblefoot (Pododermatitis)",
        "name_ja": "足底皮膚炎（バンブルフット）",
        "symptoms": {"swollen_feet", "limping", "reluctance_to_move", "redness_skin", "pain"},
        "description": "Inflammation and infection of the foot pads from wire-bottomed cages or inactivity. Can progress to deep infection.",
        "description_ja": "金網床ケージや運動不足による足底の炎症と感染です。深部感染に進行する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs_limb", "culture_sensitivity"],
    },
    # ── Respiratory ─────────────────────────────────────────────────────
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"dyspnea", "nasal_discharge", "lethargy", "appetite_loss", "wheezing", "coughing"},
        "description": "Bacterial or fungal infection of the lungs. Often caused by Pseudomonas, Bordetella, or Streptococcus.",
        "description_ja": "細菌または真菌による肺の感染症です。Pseudomonas、Bordetella、Streptococcusが原因となることが多いです。",
        "urgency": "high",
        "recommended_tests": ["thoracic_radiographs", "blood_panel", "culture_sensitivity", "pulse_oximetry"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部気道感染症",
        "symptoms": {"nasal_discharge", "sneezing", "wheezing", "lethargy", "appetite_loss", "eye_discharge"},
        "description": "Infection of the nasal passages and upper airways. May progress to pneumonia if untreated.",
        "description_ja": "鼻腔および上気道の感染症です。未治療の場合、肺炎に進行する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "nasal_culture", "thoracic_radiographs"],
    },
    {
        "name": "Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"excessive_panting", "lethargy", "collapse", "red_ears", "drooling", "recumbency", "seizures"},
        "description": "Life-threatening overheating. Chinchillas are extremely heat-sensitive; temperatures above 26°C (80°F) are dangerous.",
        "description_ja": "生命を脅かす過熱状態です。チンチラは非常に暑さに弱く、26°C以上の環境は危険です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "body_temperature", "blood_panel"],
    },
    # ── Urinary ─────────────────────────────────────────────────────────
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"straining_to_urinate", "blood_in_urine", "frequent_urination", "vocalization_pain", "appetite_loss"},
        "description": "Formation of calcium carbonate stones in the bladder or urethra. Common in chinchillas fed excessive calcium.",
        "description_ja": "膀胱または尿道に炭酸カルシウム結石が形成される疾患です。過剰なカルシウム摂取のチンチラに多く見られます。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "abdominal_radiographs", "abdominal_ultrasound"],
    },
    {
        "name": "Chronic Kidney Disease",
        "name_ja": "慢性腎臓病",
        "symptoms": {"increased_water_intake", "increased_urination", "weight_loss", "appetite_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function leading to uremia and electrolyte imbalances.",
        "description_ja": "腎機能が進行性に低下し、尿毒症や電解質異常を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_panel", "urinalysis", "abdominal_ultrasound"],
    },
    {
        "name": "Urinary Tract Infection",
        "name_ja": "尿路感染症",
        "symptoms": {"frequent_urination", "straining_to_urinate", "blood_in_urine", "vocalization_pain", "lethargy"},
        "description": "Bacterial infection of the bladder or urethra causing dysuria and hematuria.",
        "description_ja": "膀胱または尿道の細菌感染により排尿困難や血尿が起こります。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "abdominal_radiographs"],
    },
    {
        "name": "Calcium Deposits (Tissue Calcification)",
        "name_ja": "組織石灰化",
        "symptoms": {"stiffness", "lethargy", "weight_loss", "appetite_loss", "organ_dysfunction"},
        "description": "Metastatic calcification of soft tissues due to dietary calcium-phosphorus imbalance.",
        "description_ja": "食事中のカルシウム・リン比の不均衡による軟部組織の転移性石灰化です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_panel", "radiographs_whole_body", "diet_history"],
    },
    # ── Reproductive ────────────────────────────────────────────────────
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"prolonged_labor", "straining", "lethargy", "vaginal_discharge", "abdominal_pain", "distress"},
        "description": "Difficulty giving birth. Chinchillas have long gestation (111 days) and kits are born precocial; large kits can cause obstruction.",
        "description_ja": "分娩困難です。チンチラの妊娠期間は111日と長く、仔は早成性であるため、大きな仔が産道を閉塞する可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_radiographs", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "appetite_loss", "lethargy", "increased_water_intake", "abdominal_distension", "fever"},
        "description": "Bacterial infection of the uterus with pus accumulation. Requires surgical intervention.",
        "description_ja": "子宮内に細菌感染と膿が蓄積する疾患です。外科的介入が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "blood_panel", "vaginal_cytology"],
    },
    {
        "name": "Penile Fur Ring",
        "name_ja": "陰茎毛輪",
        "symptoms": {"fur_ring_penis", "excessive_grooming_genital", "penile_swelling", "paraphimosis", "vocalization_pain"},
        "description": "Hair accumulation forming a constricting ring around the penis during mating. Can cause paraphimosis and tissue necrosis.",
        "description_ja": "交配時に毛が陰茎に巻き付いて絞扼輪を形成します。嵌頓包茎や組織壊死を引き起こす可能性があります。",
        "urgency": "high",
        "recommended_tests": ["genital_exam", "physical_exam"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"swollen_mammary", "redness_mammary", "fever", "appetite_loss", "lethargy", "pain"},
        "description": "Infection and inflammation of the mammary glands in nursing females.",
        "description_ja": "授乳中の雌の乳腺における感染と炎症です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "milk_cytology", "culture_sensitivity"],
    },
    {
        "name": "Metritis",
        "name_ja": "子宮炎",
        "symptoms": {"vaginal_discharge", "fever", "lethargy", "appetite_loss", "dehydration"},
        "description": "Postpartum inflammation and infection of the uterus. Can progress to sepsis.",
        "description_ja": "産後の子宮の炎症と感染です。敗血症に進行する可能性があります。",
        "urgency": "high",
        "recommended_tests": ["blood_panel", "abdominal_ultrasound", "vaginal_cytology"],
    },
    # ── Musculoskeletal ─────────────────────────────────────────────────
    {
        "name": "Tibial Fracture",
        "name_ja": "脛骨骨折",
        "symptoms": {"limping", "non_weight_bearing", "swelling_limb", "vocalization_pain", "reluctance_to_move"},
        "description": "Fracture of the tibia, the most common long bone fracture in chinchillas. Often from cage injuries or improper handling.",
        "description_ja": "チンチラで最も一般的な長骨骨折である脛骨の骨折です。ケージ事故や不適切な取り扱いが原因となることが多いです。",
        "urgency": "high",
        "recommended_tests": ["radiographs_limb", "physical_exam"],
    },
    {
        "name": "Limb Fracture (General)",
        "name_ja": "四肢骨折（一般）",
        "symptoms": {"limping", "non_weight_bearing", "swelling_limb", "pain", "abnormal_limb_position"},
        "description": "Fracture of any limb bone from falls, cage entrapment, or rough handling.",
        "description_ja": "落下、ケージへの挟み込み、乱暴な取り扱いによる四肢の骨折です。",
        "urgency": "high",
        "recommended_tests": ["radiographs_limb", "physical_exam"],
    },
    {
        "name": "Cage Injuries",
        "name_ja": "ケージ外傷",
        "symptoms": {"wounds", "bleeding", "swelling_limb", "limping", "pain"},
        "description": "Traumatic injuries from getting feet or legs caught in cage wire, exercise wheels, or cage accessories.",
        "description_ja": "ケージの金網、回し車、ケージアクセサリーに足や脚が挟まれることによる外傷です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs_limb", "wound_assessment"],
    },
    {
        "name": "Muscle Wasting",
        "name_ja": "筋萎縮",
        "symptoms": {"weight_loss", "weakness", "reluctance_to_move", "lethargy", "reduced_activity"},
        "description": "Progressive loss of muscle mass often secondary to chronic illness, dental disease, or inadequate nutrition.",
        "description_ja": "慢性疾患、歯科疾患、不適切な栄養に続発して筋肉量が進行性に減少する状態です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_panel", "physical_exam", "diet_history"],
    },
    # ── Neurological ────────────────────────────────────────────────────
    {
        "name": "Seizures",
        "name_ja": "てんかん発作",
        "symptoms": {"seizures", "tremors", "collapse", "disorientation", "vocalization_pain", "paddling_limbs"},
        "description": "Involuntary convulsions that may be caused by metabolic disorders, toxins, heat stroke, or infection.",
        "description_ja": "代謝障害、中毒、熱中症、感染症などが原因となる不随意の痙攣です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_panel", "neurological_exam", "body_temperature"],
    },
    {
        "name": "Lead Poisoning",
        "name_ja": "鉛中毒",
        "symptoms": {"seizures", "lethargy", "appetite_loss", "diarrhea", "tremors", "weight_loss"},
        "description": "Toxicity from ingestion of lead-containing materials such as paint or solder. Causes neurological and GI signs.",
        "description_ja": "塗料やはんだなどの鉛含有物質の摂取による中毒です。神経症状と消化器症状を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "blood_panel", "abdominal_radiographs"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "circling", "nystagmus", "loss_of_balance", "falling", "disorientation"},
        "description": "Dysfunction of the vestibular system causing head tilt and loss of balance. May be due to otitis or CNS disease.",
        "description_ja": "前庭系の機能障害により斜頸や平衡感覚の喪失が起こります。中耳炎や中枢神経疾患が原因の場合があります。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "skull_radiographs", "ct_scan", "otoscopic_exam"],
    },
    {
        "name": "Listeriosis",
        "name_ja": "リステリア症",
        "symptoms": {"head_tilt", "circling", "seizures", "lethargy", "appetite_loss", "fever", "disorientation"},
        "description": "Infection with Listeria monocytogenes causing meningoencephalitis. Spread through contaminated food or bedding.",
        "description_ja": "Listeria monocytogenesの感染による髄膜脳炎です。汚染された食物や敷材を介して広がります。",
        "urgency": "emergency",
        "recommended_tests": ["blood_panel", "neurological_exam", "culture_sensitivity", "csf_analysis"],
    },
    {
        "name": "Heat Stroke (Neurological)",
        "name_ja": "熱中症（神経症状）",
        "symptoms": {"seizures", "excessive_panting", "red_ears", "collapse", "recumbency", "disorientation", "tremors"},
        "description": "Severe heat stroke presenting with neurological signs including seizures and loss of consciousness.",
        "description_ja": "痙攣や意識消失などの神経症状を呈する重度の熱中症です。",
        "urgency": "emergency",
        "recommended_tests": ["body_temperature", "blood_panel", "neurological_exam"],
    },
    # ── Ophthalmological ────────────────────────────────────────────────
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "squinting", "eye_swelling", "pawing_at_face"},
        "description": "Inflammation of the conjunctival membranes. May be caused by dust bath irritation, infection, or dental disease.",
        "description_ja": "結膜の炎症です。砂浴びの刺激、感染症、歯科疾患が原因となることがあります。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "eye_culture"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"eye_discharge", "squinting", "eye_redness", "cloudiness_eye", "pain", "pawing_at_face"},
        "description": "Erosion of the corneal surface from trauma, foreign body, or infection. Painful and may lead to perforation.",
        "description_ja": "外傷、異物、感染による角膜表面の侵食です。痛みを伴い、穿孔に至る可能性があります。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudiness_eye", "vision_impairment", "bumping_into_objects", "behavioral_changes"},
        "description": "Opacity of the lens leading to vision loss. May be age-related or secondary to diabetes.",
        "description_ja": "水晶体の混濁により視力が低下します。加齢性またはの糖尿病に続発することがあります。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose"],
    },
    # ── Cardiac ─────────────────────────────────────────────────────────
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"dyspnea", "lethargy", "exercise_intolerance", "cyanosis", "collapse", "weight_loss"},
        "description": "Disease of the heart muscle causing reduced cardiac output. May present with sudden death in chinchillas.",
        "description_ja": "心筋の疾患により心拍出量が低下します。チンチラでは突然死として発症することがあります。",
        "urgency": "high",
        "recommended_tests": ["thoracic_radiographs", "echocardiography", "electrocardiogram"],
    },
    {
        "name": "Heart Murmur",
        "name_ja": "心雑音",
        "symptoms": {"exercise_intolerance", "lethargy", "dyspnea", "reduced_activity"},
        "description": "Abnormal heart sound detected on auscultation. May indicate underlying valvular or myocardial disease.",
        "description_ja": "聴診で検出される異常な心音です。弁膜疾患や心筋疾患の存在を示唆する場合があります。",
        "urgency": "moderate",
        "recommended_tests": ["echocardiography", "thoracic_radiographs", "electrocardiogram"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"dyspnea", "lethargy", "cyanosis", "abdominal_distension", "exercise_intolerance", "coughing", "collapse"},
        "description": "Inability of the heart to pump adequate blood leading to fluid accumulation in the lungs or abdomen.",
        "description_ja": "心臓が十分な血液を送り出せず、肺や腹腔に体液が貯留する状態です。",
        "urgency": "emergency",
        "recommended_tests": ["thoracic_radiographs", "echocardiography", "blood_panel", "electrocardiogram"],
    },
    # ── Metabolic ───────────────────────────────────────────────────────
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"increased_water_intake", "increased_urination", "weight_loss", "lethargy", "cataracts_sign"},
        "description": "Insulin resistance or deficiency causing hyperglycemia. Relatively uncommon but reported in chinchillas.",
        "description_ja": "インスリン抵抗性または欠乏による高血糖症です。チンチラでは比較的まれですが報告されています。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "blood_panel", "urinalysis"],
    },
    {
        "name": "Vitamin Deficiency",
        "name_ja": "ビタミン欠乏症",
        "symptoms": {"fur_loss_patches", "weight_loss", "lethargy", "weakness", "poor_coat_quality"},
        "description": "Deficiencies in vitamins A, E, or B complex causing dermatological and systemic signs.",
        "description_ja": "ビタミンA、E、またはB群の欠乏により皮膚症状および全身症状が現れます。",
        "urgency": "moderate",
        "recommended_tests": ["blood_panel", "diet_history"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"seizures", "tremors", "weakness", "muscle_twitching", "appetite_loss"},
        "description": "Low blood calcium levels, often seen in late pregnancy or lactation. Can trigger seizures.",
        "description_ja": "血中カルシウム濃度の低下で、妊娠後期や授乳期に多く見られます。痙攣を引き起こす可能性があります。",
        "urgency": "high",
        "recommended_tests": ["blood_panel", "ionized_calcium"],
    },
    {
        "name": "Ketosis (Pregnancy Toxemia)",
        "name_ja": "ケトーシス（妊娠中毒症）",
        "symptoms": {"appetite_loss", "lethargy", "weakness", "seizures", "collapse", "acetone_breath"},
        "description": "Metabolic disorder in late pregnancy or early lactation due to negative energy balance. Often fatal.",
        "description_ja": "妊娠後期または授乳初期のエネルギー不足による代謝障害です。しばしば致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_panel", "urine_ketones"],
    },
    # ── Infectious ──────────────────────────────────────────────────────
    {
        "name": "Pseudomonas Infection",
        "name_ja": "緑膿菌感染症",
        "symptoms": {"nasal_discharge", "dyspnea", "lethargy", "appetite_loss", "eye_discharge", "fever"},
        "description": "Infection with Pseudomonas aeruginosa, a common opportunistic pathogen in chinchillas causing respiratory and systemic disease.",
        "description_ja": "チンチラの日和見病原体であるPseudomonas aeruginosaによる感染症で、呼吸器および全身症状を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "blood_panel", "thoracic_radiographs"],
    },
    {
        "name": "Pasteurella Infection",
        "name_ja": "パスツレラ感染症",
        "symptoms": {"nasal_discharge", "sneezing", "dyspnea", "lethargy", "fever", "abscesses"},
        "description": "Infection with Pasteurella multocida causing respiratory disease, abscesses, or septicemia.",
        "description_ja": "Pasteurella multocidaの感染による呼吸器疾患、膿瘍、または敗血症です。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "blood_panel", "thoracic_radiographs"],
    },
    {
        "name": "Listeria Infection",
        "name_ja": "リステリア感染症",
        "symptoms": {"circling", "head_tilt", "seizures", "appetite_loss", "lethargy", "fever", "sudden_death"},
        "description": "Systemic infection with Listeria monocytogenes causing encephalitis and septicemia. High mortality.",
        "description_ja": "Listeria monocytogenesの全身感染により脳炎や敗血症を引き起こします。致死率が高い疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_panel", "culture_sensitivity", "neurological_exam", "csf_analysis"],
    },
    {
        "name": "Giardiasis",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "loose_stool", "weight_loss", "dehydration", "appetite_loss", "soiled_perineum"},
        "description": "Protozoal infection of the intestines by Giardia species causing chronic intermittent diarrhea.",
        "description_ja": "ジアルジア属の原虫による腸管感染症で、慢性的な間欠性下痢を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "giardia_antigen_test"],
    },
    {
        "name": "Streptococcal Infection",
        "name_ja": "レンサ球菌感染症",
        "symptoms": {"lethargy", "appetite_loss", "fever", "nasal_discharge", "dyspnea", "sudden_death"},
        "description": "Infection with Streptococcus species causing pneumonia, septicemia, or lymphadenitis.",
        "description_ja": "Streptococcus属の感染により肺炎、敗血症、またはリンパ節炎を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "blood_panel", "thoracic_radiographs"],
    },
    # ── Parasitic ───────────────────────────────────────────────────────
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "appetite_loss", "lethargy", "bloody_stool"},
        "description": "Intestinal infection by Eimeria species causing diarrhea and weight loss, especially in young chinchillas.",
        "description_ja": "Eimeria属による腸管感染症で、特に若いチンチラで下痢と体重減少を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_exam"],
    },
    {
        "name": "Fur Mites",
        "name_ja": "毛ダニ症",
        "symptoms": {"itching", "fur_loss_patches", "scaling_skin", "dandruff", "restlessness"},
        "description": "Infestation with ectoparasites such as Cheyletiella or Demodex causing pruritis and hair loss.",
        "description_ja": "ツメダニやニキビダニなどの外部寄生虫の感染により掻痒と脱毛を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "fur_pluck_exam", "microscopy"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"diarrhea", "weight_loss", "appetite_loss", "dehydration", "lethargy"},
        "description": "Intestinal infection by Cryptosporidium species. Often subclinical but can cause serious disease in immunocompromised animals.",
        "description_ja": "クリプトスポリジウム属による腸管感染症です。無症候性のことが多いが、免疫不全の動物では重篤化する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "acid_fast_stain"],
    },
    # ── Oncological ─────────────────────────────────────────────────────
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"subcutaneous_mass", "slow_growing_mass", "soft_mass"},
        "description": "Benign fatty tumor presenting as a soft, movable subcutaneous mass. Usually non-problematic unless large.",
        "description_ja": "柔らかく可動性のある皮下腫瘤として現れる良性脂肪腫瘍です。大きくならない限り通常は問題ありません。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "cytology"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "appetite_loss", "lethargy", "enlarged_lymph_nodes", "abdominal_distension"},
        "description": "Malignant cancer of the lymphatic system. Can affect multiple organs and carries a poor prognosis.",
        "description_ja": "リンパ系の悪性腫瘍です。複数の臓器に影響を及ぼす可能性があり、予後不良です。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "blood_panel", "abdominal_ultrasound", "biopsy"],
    },
    {
        "name": "Ovarian Tumors",
        "name_ja": "卵巣腫瘍",
        "symptoms": {"abdominal_distension", "fur_loss_patches", "lethargy", "weight_loss", "behavioral_changes"},
        "description": "Neoplasia of the ovaries, which may secrete hormones causing alopecia and behavioral changes.",
        "description_ja": "卵巣の腫瘍性病変で、ホルモンを分泌して脱毛や行動変化を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "blood_panel", "hormone_panel", "biopsy"],
    },
    {
        "name": "Mammary Tumors",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "swollen_mammary", "weight_loss", "lethargy"},
        "description": "Benign or malignant tumors of the mammary glands. More common in intact females.",
        "description_ja": "乳腺の良性または悪性腫瘍です。未避妊の雌に多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "cytology", "thoracic_radiographs", "biopsy"],
    },
    # ── Additional Conditions ───────────────────────────────────────────
    {
        "name": "Otitis Media / Interna",
        "name_ja": "中耳炎・内耳炎",
        "symptoms": {"head_tilt", "loss_of_balance", "head_shaking", "ear_discharge", "appetite_loss", "nystagmus"},
        "description": "Infection of the middle or inner ear causing vestibular signs. Often secondary to upper respiratory infection.",
        "description_ja": "中耳または内耳の感染により前庭症状が現れます。上部気道感染症に続発することが多いです。",
        "urgency": "high",
        "recommended_tests": ["otoscopic_exam", "skull_radiographs", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Intussusception",
        "name_ja": "腸重積",
        "symptoms": {"abdominal_pain", "lethargy", "appetite_loss", "bloody_stool", "vomiting", "abdominal_distension"},
        "description": "Telescoping of one segment of intestine into another causing obstruction and ischemia.",
        "description_ja": "腸管の一部が他の部分に陥入して閉塞と虚血を引き起こす疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_radiographs", "blood_panel"],
    },
    {
        "name": "Spinal Injury",
        "name_ja": "脊椎損傷",
        "symptoms": {"hind_limb_paralysis", "non_weight_bearing", "urinary_incontinence", "fecal_incontinence", "pain"},
        "description": "Trauma to the spine from falls or cage accidents causing partial or complete paralysis.",
        "description_ja": "落下やケージ事故による脊椎の外傷で、部分的または完全な麻痺を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["spinal_radiographs", "neurological_exam", "ct_scan"],
    },
    {
        "name": "Dermatitis (Contact / Allergic)",
        "name_ja": "接触性・アレルギー性皮膚炎",
        "symptoms": {"redness_skin", "itching", "fur_loss_patches", "scaling_skin", "swelling_skin"},
        "description": "Skin inflammation caused by contact allergens such as bedding materials or cleaning products.",
        "description_ja": "敷材や洗浄剤などの接触アレルゲンによる皮膚の炎症です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "skin_scraping", "allergy_testing"],
    },
    {
        "name": "Bite Wounds",
        "name_ja": "咬傷",
        "symptoms": {"wounds", "bleeding", "swelling_skin", "abscesses", "pain", "fur_loss_patches"},
        "description": "Traumatic injuries from fighting with cage mates. Can develop secondary bacterial infections or abscesses.",
        "description_ja": "ケージメイトとの喧嘩による外傷です。二次的な細菌感染や膿瘍に発展する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "culture_sensitivity"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "reduced_activity", "difficulty_grooming", "hepatic_lipidosis_risk"},
        "description": "Excessive body weight from overfeeding treats and seeds. Predisposes to hepatic lipidosis and other conditions.",
        "description_ja": "おやつや種子の過剰給餌による過体重です。肝リピドーシスなどの疾患のリスクを高めます。",
        "urgency": "low",
        "recommended_tests": ["body_condition_scoring", "diet_history", "blood_panel"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水",
        "symptoms": {"dehydration", "skin_tenting", "sunken_eyes", "lethargy", "appetite_loss", "reduced_fecal_output"},
        "description": "Fluid deficit from inadequate water intake, diarrhea, or environmental heat. Can rapidly become life-threatening.",
        "description_ja": "水分摂取不足、下痢、環境の暑さによる体液不足です。急速に生命を脅かす状態になる可能性があります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "blood_panel", "packed_cell_volume"],
    },
    {
        "name": "Impacted Cecotrophs",
        "name_ja": "盲腸便貯留",
        "symptoms": {"soiled_perineum", "odor", "reduced_fecal_output", "appetite_loss", "lethargy"},
        "description": "Accumulation of soft cecotrophs around the perineum due to obesity, dental pain, or spinal problems.",
        "description_ja": "肥満、歯科疾患の痛み、脊椎の問題により盲腸便が肛門周囲に蓄積する状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "perineal_exam", "diet_history"],
    },
    {
        "name": "Aspiration Pneumonia",
        "name_ja": "誤嚥性肺炎",
        "symptoms": {"dyspnea", "coughing", "nasal_discharge", "lethargy", "fever", "appetite_loss"},
        "description": "Lung infection caused by inhalation of food, water, or oral medications into the airways.",
        "description_ja": "食物、水、経口薬の気道への吸引による肺感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["thoracic_radiographs", "blood_panel", "pulse_oximetry"],
    },
    {
        "name": "Skin Abscess",
        "name_ja": "皮膚膿瘍",
        "symptoms": {"subcutaneous_mass", "swelling_skin", "pain", "fever", "draining_wound"},
        "description": "Localized bacterial infection forming a pocket of pus under the skin. May require surgical drainage.",
        "description_ja": "皮下に膿の袋が形成される局所的な細菌感染です。外科的排膿が必要な場合があります。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "cytology", "physical_exam"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # General / systemic
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite Loss"},
    "weight_loss": {"ja": "体重減少", "en": "Weight Loss"},
    "weight_gain": {"ja": "体重増加", "en": "Weight Gain"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "collapse": {"ja": "虚脱・失神", "en": "Collapse / Fainting"},
    "shock": {"ja": "ショック", "en": "Shock"},
    "sudden_death": {"ja": "突然死", "en": "Sudden Death"},
    "pain": {"ja": "痛み", "en": "Pain"},
    "stress": {"ja": "ストレス", "en": "Stress"},
    "reduced_activity": {"ja": "活動量低下", "en": "Reduced Activity"},
    "distress": {"ja": "苦悶", "en": "Distress"},
    "recumbency": {"ja": "起立不能", "en": "Recumbency"},
    # Dental / oral
    "drooling": {"ja": "よだれ・流涎", "en": "Drooling / Hypersalivation"},
    "difficulty_eating": {"ja": "食事困難", "en": "Difficulty Eating"},
    "pawing_at_mouth": {"ja": "口を前肢でかく", "en": "Pawing at Mouth"},
    "wet_chin": {"ja": "濡れた顎", "en": "Wet Chin"},
    "matted_fur_chin": {"ja": "顎の被毛固着", "en": "Matted Fur on Chin"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial Swelling"},
    # Gastrointestinal
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal Pain"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal Distension"},
    "reduced_fecal_output": {"ja": "糞便量減少", "en": "Reduced Fecal Output"},
    "small_dry_feces": {"ja": "小さく乾燥した糞", "en": "Small Dry Feces"},
    "loose_stool": {"ja": "軟便", "en": "Loose Stool"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "bloody_stool": {"ja": "血便", "en": "Bloody Stool"},
    "straining_to_defecate": {"ja": "排便時のいきみ", "en": "Straining to Defecate"},
    "tissue_protruding_anus": {"ja": "肛門からの組織脱出", "en": "Tissue Protruding from Anus"},
    "bleeding_rectum": {"ja": "直腸出血", "en": "Rectal Bleeding"},
    "soiled_perineum": {"ja": "肛門周囲の汚れ", "en": "Soiled Perineum"},
    "hunched_posture": {"ja": "前かがみ姿勢", "en": "Hunched Posture"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "odor": {"ja": "異臭", "en": "Abnormal Odor"},
    "acetone_breath": {"ja": "アセトン臭の呼気", "en": "Acetone Breath"},
    # Dermatological
    "fur_loss_patches": {"ja": "部分的な脱毛", "en": "Patchy Fur Loss"},
    "bare_skin_patches": {"ja": "皮膚露出部", "en": "Bare Skin Patches"},
    "fur_chewing": {"ja": "毛噛み", "en": "Fur Chewing"},
    "patchy_short_fur": {"ja": "まだらに短い被毛", "en": "Patchy Short Fur"},
    "crusty_skin": {"ja": "痂皮のある皮膚", "en": "Crusty Skin"},
    "scaling_skin": {"ja": "鱗屑", "en": "Scaling Skin"},
    "redness_skin": {"ja": "皮膚の発赤", "en": "Skin Redness"},
    "swelling_skin": {"ja": "皮膚の腫脹", "en": "Skin Swelling"},
    "itching": {"ja": "掻痒", "en": "Itching / Pruritis"},
    "dandruff": {"ja": "フケ", "en": "Dandruff"},
    "poor_coat_quality": {"ja": "被毛質の低下", "en": "Poor Coat Quality"},
    "boredom_signs": {"ja": "退屈の兆候", "en": "Signs of Boredom"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "draining_wound": {"ja": "排膿創", "en": "Draining Wound"},
    # Ear
    "ear_flaking": {"ja": "耳の剥離", "en": "Ear Flaking"},
    "ear_redness": {"ja": "耳の発赤", "en": "Ear Redness"},
    "ear_thickening": {"ja": "耳の肥厚", "en": "Ear Thickening"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear Discharge"},
    "head_shaking": {"ja": "頭を振る", "en": "Head Shaking"},
    # Respiratory
    "dyspnea": {"ja": "呼吸困難", "en": "Dyspnea / Difficulty Breathing"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal Discharge"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "excessive_panting": {"ja": "過度のパンティング", "en": "Excessive Panting"},
    "red_ears": {"ja": "耳の充血", "en": "Red / Flushed Ears"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    # Urinary
    "straining_to_urinate": {"ja": "排尿時のいきみ", "en": "Straining to Urinate"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in Urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent Urination"},
    "increased_water_intake": {"ja": "飲水量増加", "en": "Increased Water Intake"},
    "increased_urination": {"ja": "尿量増加", "en": "Increased Urination"},
    "urinary_incontinence": {"ja": "尿失禁", "en": "Urinary Incontinence"},
    # Reproductive
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal Discharge"},
    "prolonged_labor": {"ja": "遷延分娩", "en": "Prolonged Labor"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "fur_ring_penis": {"ja": "陰茎の毛輪", "en": "Fur Ring on Penis"},
    "excessive_grooming_genital": {"ja": "陰部の過度なグルーミング", "en": "Excessive Genital Grooming"},
    "penile_swelling": {"ja": "陰茎の腫脹", "en": "Penile Swelling"},
    "paraphimosis": {"ja": "嵌頓包茎", "en": "Paraphimosis"},
    "swollen_mammary": {"ja": "乳腺の腫脹", "en": "Swollen Mammary Glands"},
    "redness_mammary": {"ja": "乳腺の発赤", "en": "Mammary Redness"},
    "mammary_mass": {"ja": "乳腺腫瘤", "en": "Mammary Mass"},
    # Musculoskeletal
    "limping": {"ja": "跛行", "en": "Limping"},
    "non_weight_bearing": {"ja": "患肢非負重", "en": "Non-Weight Bearing"},
    "swelling_limb": {"ja": "肢の腫脹", "en": "Limb Swelling"},
    "abnormal_limb_position": {"ja": "異常な肢位", "en": "Abnormal Limb Position"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to Move"},
    "swollen_feet": {"ja": "足の腫脹", "en": "Swollen Feet"},
    "wounds": {"ja": "傷", "en": "Wounds"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    # Neurological
    "seizures": {"ja": "痙攣発作", "en": "Seizures"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "head_tilt": {"ja": "斜頸", "en": "Head Tilt"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "loss_of_balance": {"ja": "平衡感覚喪失", "en": "Loss of Balance"},
    "falling": {"ja": "転倒", "en": "Falling"},
    "disorientation": {"ja": "見当識障害", "en": "Disorientation"},
    "paddling_limbs": {"ja": "四肢の漕ぐような運動", "en": "Paddling Limbs"},
    "muscle_twitching": {"ja": "筋攣縮", "en": "Muscle Twitching"},
    "hind_limb_paralysis": {"ja": "後肢麻痺", "en": "Hind Limb Paralysis"},
    "fecal_incontinence": {"ja": "便失禁", "en": "Fecal Incontinence"},
    # Ophthalmological
    "eye_discharge": {"ja": "眼脂", "en": "Eye Discharge"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye Redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye Swelling"},
    "squinting": {"ja": "目を細める", "en": "Squinting"},
    "cloudiness_eye": {"ja": "眼の白濁", "en": "Cloudiness of Eye"},
    "vision_impairment": {"ja": "視力障害", "en": "Vision Impairment"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into Objects"},
    "pawing_at_face": {"ja": "顔を前肢でかく", "en": "Pawing at Face"},
    "sunken_eyes": {"ja": "眼球陥没", "en": "Sunken Eyes"},
    # Cardiac
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise Intolerance"},
    # Metabolic
    "cataracts_sign": {"ja": "白内障の兆候", "en": "Cataracts Sign"},
    "skin_tenting": {"ja": "皮膚ツルゴール低下", "en": "Skin Tenting"},
    "organ_dysfunction": {"ja": "臓器機能障害", "en": "Organ Dysfunction"},
    "hepatic_lipidosis_risk": {"ja": "肝リピドーシスリスク", "en": "Hepatic Lipidosis Risk"},
    "difficulty_grooming": {"ja": "グルーミング困難", "en": "Difficulty Grooming"},
    # Infectious / general signs
    "abscesses": {"ja": "膿瘍", "en": "Abscesses"},
    "vocalization_pain": {"ja": "痛みによる鳴き声", "en": "Vocalization from Pain"},
    "behavioral_changes": {"ja": "行動変化", "en": "Behavioral Changes"},
    # Oncological
    "subcutaneous_mass": {"ja": "皮下腫瘤", "en": "Subcutaneous Mass"},
    "slow_growing_mass": {"ja": "緩徐に増大する腫瘤", "en": "Slow-Growing Mass"},
    "soft_mass": {"ja": "軟らかい腫瘤", "en": "Soft Mass"},
    "enlarged_lymph_nodes": {"ja": "リンパ節腫大", "en": "Enlarged Lymph Nodes"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species)
