"""Degu disease dictionary and symptom analysis module.

Degus (Octodon degus) are small rodents native to Chile with unique health
concerns.  They are notably unable to metabolize sugar, making diabetes
mellitus and secondary cataracts extremely common.  This module catalogues
50+ diseases across endocrine, dental, dermatological, respiratory,
gastrointestinal, musculoskeletal, neurological, ophthalmological, renal,
hepatic, reproductive, and neoplastic categories.
"""

from __future__ import annotations

from typing import Any, Dict, List

from . import prevalence_data
from .helpers import ADVICE, analyze_symptoms_generic

# ---------------------------------------------------------------------------
# Disease database
# ---------------------------------------------------------------------------

DISEASES: List[Dict[str, Any]] = [
    # ── Endocrine / Metabolic ──────────────────────────────────────────────
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "hyperglycemia"},
        "description": "Degus cannot metabolize sugar; diabetes is extremely common and causes increased thirst, urination, and weight loss.",
        "description_ja": "デグーは糖を代謝できず、糖尿病は非常に多い。多飲多尿や体重減少を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "urinalysis", "fructosamine"],
    },
    {
        "name": "Diabetic Ketoacidosis",
        "name_ja": "糖尿病性ケトアシドーシス",
        "symptoms": {"lethargy", "vomiting", "dehydration", "rapid_breathing", "collapse"},
        "description": "Life-threatening complication of uncontrolled diabetes with ketone accumulation.",
        "description_ja": "未治療の糖尿病が悪化しケトン体が蓄積する致命的な合併症。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_gas", "ketone_test", "urinalysis"],
    },
    {
        "name": "Insulin Resistance",
        "name_ja": "インスリン抵抗性",
        "symptoms": {"obesity", "polyuria", "polydipsia", "hyperglycemia"},
        "description": "Chronic insulin resistance leading to persistent hyperglycemia despite normal insulin levels.",
        "description_ja": "慢性的なインスリン抵抗性により、正常なインスリン値にもかかわらず持続的な高血糖が起こる。",
        "urgency": "moderate",
        "recommended_tests": ["blood_glucose", "insulin_level", "fructosamine"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "lethargy", "reduced_activity", "obesity"},
        "description": "Excessive body weight from overfeeding or high-sugar diet, predisposing to diabetes.",
        "description_ja": "過食や高糖質食による体重過多。糖尿病の素因となる。",
        "urgency": "moderate",
        "recommended_tests": ["body_condition_score", "blood_glucose"],
    },
    {
        "name": "Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"rapid_breathing", "lethargy", "collapse", "drooling", "seizures"},
        "description": "Degus are sensitive to heat; temperatures above 30°C can cause heat stroke.",
        "description_ja": "デグーは暑さに弱く、30℃以上で熱中症を起こしやすい。",
        "urgency": "emergency",
        "recommended_tests": ["body_temperature", "physical_exam", "blood_work"],
    },
    {
        "name": "Hypothermia",
        "name_ja": "低体温症",
        "symptoms": {"lethargy", "shivering", "cold_extremities", "collapse"},
        "description": "Dangerously low body temperature from cold exposure or severe illness.",
        "description_ja": "低温環境や重篤な疾患による危険な低体温。",
        "urgency": "emergency",
        "recommended_tests": ["body_temperature", "blood_glucose", "physical_exam"],
    },

    # ── Ophthalmological ───────────────────────────────────────────────────
    {
        "name": "Diabetic Cataracts",
        "name_ja": "糖尿病性白内障",
        "symptoms": {"cloudy_eyes", "vision_loss", "bumping_into_objects", "hyperglycemia"},
        "description": "Lens opacification secondary to chronic hyperglycemia; extremely common in degus.",
        "description_ja": "慢性的な高血糖に続発する水晶体の混濁。デグーでは非常に多い。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose", "slit_lamp_exam"],
    },
    {
        "name": "Senile Cataracts",
        "name_ja": "老年性白内障",
        "symptoms": {"cloudy_eyes", "vision_loss", "bumping_into_objects"},
        "description": "Age-related lens opacity unrelated to diabetes, seen in older degus.",
        "description_ja": "加齢に伴う水晶体の混濁で、糖尿病とは無関係に高齢デグーに見られる。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam", "slit_lamp_exam"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "squinting", "eye_swelling"},
        "description": "Inflammation of the conjunctiva from irritants, bedding dust, or infection.",
        "description_ja": "刺激物、床材の粉塵、感染による結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "bacterial_culture", "fluorescein_stain"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "eye_discharge", "eye_redness", "cloudy_eyes", "pawing_at_eye"},
        "description": "Erosion of the corneal surface from trauma or infection.",
        "description_ja": "外傷や感染による角膜表面の損傷。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam"],
    },

    # ── Dental ─────────────────────────────────────────────────────────────
    {
        "name": "Dental Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "facial_swelling", "teeth_grinding"},
        "description": "Misalignment of constantly growing teeth causing pain and inability to eat.",
        "description_ja": "常生歯の噛み合わせ不良により痛みや摂食困難を生じる。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    {
        "name": "Incisor Overgrowth",
        "name_ja": "切歯過長",
        "symptoms": {"drooling", "appetite_loss", "visible_tooth_overgrowth", "weight_loss"},
        "description": "Excessive growth of incisors preventing normal food prehension.",
        "description_ja": "切歯の過度な伸長により正常な食物の把持ができなくなる。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    {
        "name": "Molar Spurs",
        "name_ja": "臼歯棘",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "facial_swelling"},
        "description": "Sharp points on molars that lacerate tongue or cheeks.",
        "description_ja": "臼歯にできる鋭い突起が舌や頬を傷つける。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiographs", "endoscopy"],
    },
    {
        "name": "Tooth Root Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "eye_discharge", "nasal_discharge", "weight_loss"},
        "description": "Infection at the tooth root causing swelling and potential sinus involvement.",
        "description_ja": "歯根の感染により腫脹し、副鼻腔に波及することがある。",
        "urgency": "high",
        "recommended_tests": ["skull_radiographs", "CT_scan", "bacterial_culture"],
    },

    # ── Dermatological ─────────────────────────────────────────────────────
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"hair_loss", "crusty_skin", "itching", "circular_lesions"},
        "description": "Fungal skin infection causing circular patches of hair loss.",
        "description_ja": "真菌による皮膚感染症で、円形の脱毛斑が生じる。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "wood_lamp"],
    },
    {
        "name": "Fur Mites (Demodex / Notoedres)",
        "name_ja": "毛包虫症",
        "symptoms": {"itching", "hair_loss", "crusty_skin", "scaly_skin", "scratching"},
        "description": "Ectoparasitic infestation causing intense itching and hair loss.",
        "description_ja": "外部寄生虫による激しいかゆみと脱毛。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Tail Degloving Injury",
        "name_ja": "尾部脱皮損傷",
        "symptoms": {"tail_injury", "bleeding", "exposed_bone", "pain"},
        "description": "The tail skin slips off when grabbed; degus shed tail skin as a defense mechanism.",
        "description_ja": "尻尾を掴まれると皮膚が剥がれる。デグーの防御機構だが、再生しない。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Barbering (Over-grooming)",
        "name_ja": "バーバリング（過剰毛繕い）",
        "symptoms": {"hair_loss", "patchy_fur", "stress_behavior"},
        "description": "Excessive grooming of self or cage-mates due to stress or boredom.",
        "description_ja": "ストレスや退屈による過度な毛繕いで、自身や同居個体の毛が薄くなる。",
        "urgency": "low",
        "recommended_tests": ["behavioral_assessment", "skin_scraping"],
    },
    {
        "name": "Bite Wounds / Abscess",
        "name_ja": "咬傷・膿瘍",
        "symptoms": {"swelling", "pain", "discharge", "lethargy", "fever"},
        "description": "Wounds from cage-mate aggression that become infected and form abscesses.",
        "description_ja": "同居個体との争いによる咬傷が感染し膿瘍を形成する。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "bacterial_culture", "cytology"],
    },
    {
        "name": "Contact Dermatitis",
        "name_ja": "接触性皮膚炎",
        "symptoms": {"skin_redness", "itching", "hair_loss", "crusty_skin"},
        "description": "Skin irritation from contact with bedding, cleaning products, or other irritants.",
        "description_ja": "床材や洗浄剤などとの接触による皮膚の炎症。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "skin_scraping", "allergy_testing"],
    },

    # ── Musculoskeletal ────────────────────────────────────────────────────
    {
        "name": "Bumblefoot (Pododermatitis)",
        "name_ja": "趾瘤症（バンブルフット）",
        "symptoms": {"swollen_feet", "lameness", "foot_sores", "reluctance_to_move"},
        "description": "Infection and inflammation of the footpad from wire flooring or unsanitary conditions.",
        "description_ja": "金網の床や不衛生な環境による足底の感染と炎症。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs", "bacterial_culture"],
    },
    {
        "name": "Limb Fracture",
        "name_ja": "四肢骨折",
        "symptoms": {"lameness", "swelling", "pain", "limb_deformity", "reluctance_to_move"},
        "description": "Broken bones from falls, wheel injuries, or cage entrapment.",
        "description_ja": "落下、回し車の事故、ケージへの挟まりによる骨折。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam"],
    },
    {
        "name": "Spinal Fracture",
        "name_ja": "脊椎骨折",
        "symptoms": {"hind_leg_paralysis", "pain", "incontinence", "reluctance_to_move"},
        "description": "Fracture of the vertebral column from falls or trauma causing paralysis.",
        "description_ja": "落下や外傷による脊椎の骨折で麻痺を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "neurological_exam"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "reduced_activity", "stiffness", "reluctance_to_move"},
        "description": "Degenerative joint disease common in aging degus.",
        "description_ja": "加齢に伴う関節の変性疾患。",
        "urgency": "low",
        "recommended_tests": ["radiographs", "physical_exam"],
    },

    # ── Respiratory ────────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部気道感染症",
        "symptoms": {"sneezing", "nasal_discharge", "lethargy", "appetite_loss"},
        "description": "Bacterial or viral infection of the upper airways.",
        "description_ja": "細菌またはウイルスによる上部気道の感染症。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "physical_exam", "radiographs"],
    },
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"labored_breathing", "nasal_discharge", "lethargy", "appetite_loss", "cyanosis"},
        "description": "Infection or inflammation of the lungs, often secondary to URI.",
        "description_ja": "肺の感染または炎症で、しばしば上部気道感染に続発する。",
        "urgency": "high",
        "recommended_tests": ["chest_radiographs", "blood_work", "bacterial_culture"],
    },
    {
        "name": "Aspiration Pneumonia",
        "name_ja": "誤嚥性肺炎",
        "symptoms": {"labored_breathing", "coughing", "lethargy", "fever", "nasal_discharge"},
        "description": "Lung infection from inhaling food or fluid, often due to improper syringe feeding.",
        "description_ja": "食物や液体の誤嚥による肺感染。不適切なシリンジ給餌が原因になりやすい。",
        "urgency": "emergency",
        "recommended_tests": ["chest_radiographs", "blood_work"],
    },

    # ── Gastrointestinal ───────────────────────────────────────────────────
    {
        "name": "Gastrointestinal Stasis",
        "name_ja": "消化管うっ滞",
        "symptoms": {"appetite_loss", "bloating", "reduced_fecal_output", "lethargy", "teeth_grinding"},
        "description": "Slowing or cessation of gut motility from stress, diet, or pain.",
        "description_ja": "ストレスや食事、痛みによる腸管運動の低下または停止。",
        "urgency": "high",
        "recommended_tests": ["abdominal_radiographs", "physical_exam"],
    },
    {
        "name": "Bloat (Gastric Dilation)",
        "name_ja": "鼓脹症",
        "symptoms": {"bloating", "pain", "lethargy", "rapid_breathing", "appetite_loss"},
        "description": "Gas accumulation in the stomach causing distension and pain.",
        "description_ja": "胃内のガス蓄積により膨満と痛みが生じる。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_radiographs", "physical_exam"],
    },
    {
        "name": "Diarrhea (Non-specific)",
        "name_ja": "下痢（非特異的）",
        "symptoms": {"diarrhea", "dehydration", "lethargy", "appetite_loss"},
        "description": "Loose stools from dietary changes, stress, or infection.",
        "description_ja": "食事の変更、ストレス、感染による軟便。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_culture", "physical_exam"],
    },
    {
        "name": "Constipation",
        "name_ja": "便秘",
        "symptoms": {"reduced_fecal_output", "straining", "bloating", "appetite_loss"},
        "description": "Difficulty passing stools due to dehydration, low fiber, or obstruction.",
        "description_ja": "脱水、低繊維食、閉塞による排便困難。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_radiographs", "physical_exam"],
    },
    {
        "name": "Intestinal Parasites",
        "name_ja": "腸内寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "bloating", "rough_coat"},
        "description": "Infestation with protozoa or helminths causing diarrhea and poor condition.",
        "description_ja": "原虫や蠕虫の寄生により下痢や状態悪化を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_smear"],
    },
    {
        "name": "Giardiasis",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "weight_loss", "bloating", "dehydration"},
        "description": "Protozoal infection of the intestine causing chronic watery diarrhea.",
        "description_ja": "ジアルジア原虫による腸管感染で慢性的な水様下痢を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "giardia_antigen_test"],
    },
    {
        "name": "Intestinal Obstruction",
        "name_ja": "腸閉塞",
        "symptoms": {"appetite_loss", "bloating", "pain", "lethargy", "reduced_fecal_output"},
        "description": "Foreign body or mass blocking the intestinal lumen.",
        "description_ja": "異物や腫瘤による腸管の閉塞。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_radiographs", "ultrasound"],
    },

    # ── Hepatic ────────────────────────────────────────────────────────────
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"appetite_loss", "lethargy", "weight_loss", "jaundice", "distended_abdomen"},
        "description": "Excessive fat accumulation in the liver, often linked to obesity or anorexia.",
        "description_ja": "肝臓への過度な脂肪蓄積。肥満や食欲不振と関連することが多い。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_enzymes", "ultrasound"],
    },
    {
        "name": "Liver Disease (Chronic)",
        "name_ja": "慢性肝疾患",
        "symptoms": {"jaundice", "weight_loss", "lethargy", "distended_abdomen", "appetite_loss"},
        "description": "Progressive liver dysfunction from toxins, infection, or metabolic disease.",
        "description_ja": "毒素、感染、代謝性疾患による進行性の肝機能障害。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_enzymes", "ultrasound", "biopsy"],
    },

    # ── Renal ──────────────────────────────────────────────────────────────
    {
        "name": "Chronic Kidney Disease",
        "name_ja": "慢性腎臓病",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function common in aging degus.",
        "description_ja": "加齢に伴う進行性の腎機能低下。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "ultrasound"],
    },
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"straining", "blood_in_urine", "frequent_urination", "pain"},
        "description": "Formation of mineral stones in the urinary tract.",
        "description_ja": "尿路内でのミネラル結石の形成。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "radiographs", "ultrasound"],
    },
    {
        "name": "Urinary Tract Infection",
        "name_ja": "尿路感染症",
        "symptoms": {"frequent_urination", "blood_in_urine", "straining", "lethargy"},
        "description": "Bacterial infection of the bladder or urethra.",
        "description_ja": "膀胱または尿道の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture"],
    },

    # ── Neoplasia ──────────────────────────────────────────────────────────
    {
        "name": "Mammary Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "swelling", "weight_loss", "lethargy"},
        "description": "Benign or malignant growth in the mammary tissue.",
        "description_ja": "乳腺組織の良性または悪性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "radiographs", "histopathology"],
    },
    {
        "name": "Skin Tumor",
        "name_ja": "皮膚腫瘍",
        "symptoms": {"skin_mass", "ulceration", "hair_loss", "swelling"},
        "description": "Neoplastic growth on the skin surface or subcutaneous tissue.",
        "description_ja": "皮膚表面や皮下組織の腫瘍性増殖。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "histopathology"],
    },
    {
        "name": "Abdominal Tumor",
        "name_ja": "腹腔内腫瘍",
        "symptoms": {"distended_abdomen", "weight_loss", "appetite_loss", "lethargy"},
        "description": "Internal neoplasia causing abdominal distension and systemic decline.",
        "description_ja": "腹腔内の腫瘍により腹部膨満と全身状態の悪化が生じる。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_work", "biopsy"],
    },

    # ── Reproductive ───────────────────────────────────────────────────────
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "lethargy", "appetite_loss", "distended_abdomen", "polydipsia"},
        "description": "Uterine infection with pus accumulation; life-threatening in intact females.",
        "description_ja": "子宮内に膿が蓄積する感染症。未避妊の雌で致命的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "blood_work", "radiographs"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "lethargy", "vaginal_discharge", "pain", "restlessness"},
        "description": "Difficulty giving birth due to fetal malpresentation or maternal factors.",
        "description_ja": "胎児の位置異常や母体要因による分娩困難。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "physical_exam"],
    },
    {
        "name": "Testicular Tumor",
        "name_ja": "精巣腫瘍",
        "symptoms": {"testicular_swelling", "asymmetric_testes", "lethargy"},
        "description": "Neoplastic growth in one or both testes.",
        "description_ja": "片側または両側の精巣に生じる腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "fine_needle_aspirate", "histopathology"],
    },

    # ── Neurological ───────────────────────────────────────────────────────
    {
        "name": "Seizures (Epilepsy)",
        "name_ja": "てんかん発作",
        "symptoms": {"seizures", "collapse", "disorientation", "drooling"},
        "description": "Recurrent seizure activity that may be idiopathic or secondary to metabolic disease.",
        "description_ja": "特発性または代謝性疾患に続発する反復性のてんかん発作。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "blood_glucose", "neurological_exam"],
    },
    {
        "name": "Stroke (Cerebrovascular Accident)",
        "name_ja": "脳卒中",
        "symptoms": {"head_tilt", "circling", "loss_of_balance", "seizures", "disorientation"},
        "description": "Vascular event in the brain causing acute neurological deficits.",
        "description_ja": "脳内の血管障害により急性の神経症状が出現する。",
        "urgency": "emergency",
        "recommended_tests": ["neurological_exam", "blood_work", "MRI"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "loss_of_balance", "circling", "nystagmus"},
        "description": "Dysfunction of the vestibular system causing balance problems.",
        "description_ja": "前庭系の機能障害によるバランス異常。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "otoscopic_exam", "radiographs"],
    },
    {
        "name": "Hind Limb Paralysis",
        "name_ja": "後肢麻痺",
        "symptoms": {"hind_leg_paralysis", "incontinence", "dragging_legs", "pain"},
        "description": "Loss of hind limb function from spinal injury, stroke, or disc disease.",
        "description_ja": "脊髄損傷、脳卒中、椎間板疾患による後肢機能の喪失。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "neurological_exam", "MRI"],
    },

    # ── Cardiac ────────────────────────────────────────────────────────────
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"labored_breathing", "lethargy", "cyanosis", "reduced_activity", "collapse"},
        "description": "Heart unable to pump effectively, leading to fluid buildup.",
        "description_ja": "心臓のポンプ機能低下による体液貯留。",
        "urgency": "emergency",
        "recommended_tests": ["chest_radiographs", "echocardiography", "blood_work"],
    },
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"labored_breathing", "lethargy", "reduced_activity", "collapse"},
        "description": "Disease of the heart muscle leading to impaired cardiac function.",
        "description_ja": "心筋の疾患により心機能が障害される。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_radiographs", "ECG"],
    },

    # ── Additional conditions ──────────────────────────────────────────────
    {
        "name": "Ear Infection (Otitis)",
        "name_ja": "耳感染症（外耳炎）",
        "symptoms": {"head_tilt", "scratching_ear", "ear_discharge", "loss_of_balance"},
        "description": "Infection of the outer or middle ear from bacteria or mites.",
        "description_ja": "細菌やダニによる外耳または中耳の感染。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "ear_cytology", "bacterial_culture"],
    },
    {
        "name": "Vitamin C Deficiency (Scurvy)",
        "name_ja": "ビタミンC欠乏症（壊血病）",
        "symptoms": {"lethargy", "swollen_joints", "lameness", "rough_coat", "bleeding_gums"},
        "description": "Degus may develop scurvy when dietary vitamin C is insufficient.",
        "description_ja": "食事中のビタミンC不足により壊血病を発症することがある。",
        "urgency": "moderate",
        "recommended_tests": ["blood_work", "physical_exam"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "rapid_breathing", "collapse", "dehydration"},
        "description": "Systemic bacterial infection with bloodstream involvement.",
        "description_ja": "血流への細菌侵入を伴う全身性の細菌感染。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "blood_work", "physical_exam"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"dehydration", "lethargy", "sunken_eyes", "reduced_activity"},
        "description": "Insufficient fluid intake or excessive fluid loss from illness.",
        "description_ja": "水分摂取不足や疾病による過度な水分喪失。",
        "urgency": "moderate",
        "recommended_tests": ["skin_turgor_test", "blood_work", "physical_exam"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"tissue_protrusion_anus", "straining", "bloody_stool", "lethargy"},
        "description": "Protrusion of the rectal lining through the anus, often from straining or parasites.",
        "description_ja": "いきみや寄生虫により直腸粘膜が肛門から突出する。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_exam"],
    },
    {
        "name": "Diabetes-related Neuropathy",
        "name_ja": "糖尿病性神経障害",
        "symptoms": {"hind_leg_paralysis", "dragging_legs", "loss_of_balance", "hyperglycemia"},
        "description": "Nerve damage from chronic hyperglycemia causing weakness in the hind limbs.",
        "description_ja": "慢性的な高血糖による神経障害で後肢の衰弱が生じる。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "neurological_exam"],
    },
    {
        "name": "Diabetes Mellitus - Type 1 (Juvenile Onset)",
        "name_ja": "糖尿病 - 1型（若年発症）",
        "symptoms": {"excessive_hunger", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Insulin-dependent diabetes in young degus with autoimmune destruction of beta cells. Degus are the most common rodent model for diabetes research.",
        "description_ja": "ベータ細胞の自己免疫破壊による若いデグーのインスリン依存性糖尿病。デグーは糖尿病研究で最も一般的な齧歯類モデルです。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "fructosamine", "urinalysis"],
    },
    {
        "name": "Diabetes Mellitus - Type 2 (Diet-Induced)",
        "name_ja": "糖尿病 - 2型（食事誘発性）",
        "symptoms": {"lethargy", "obesity", "polydipsia", "polyuria", "poor_coat"},
        "description": "Non-insulin dependent diabetes from high-sugar diet. Degus are extremely sensitive to dietary sugar and develop diabetes readily.",
        "description_ja": "高糖質食による非インスリン依存性糖尿病。デグーは食事中の糖に非常に敏感で、容易に糖尿病を発症します。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "fructosamine", "diet_review"],
    },
    {
        "name": "Diabetic Retinopathy",
        "name_ja": "糖尿病性網膜症",
        "symptoms": {"bumping_into_objects", "dilated_pupils", "vision_loss"},
        "description": "Progressive retinal damage from chronic hyperglycaemia causing blindness.",
        "description_ja": "慢性高血糖による進行性の網膜損傷で失明を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose", "fundoscopy"],
    },
    {
        "name": "Diabetic Nephropathy",
        "name_ja": "糖尿病性腎症",
        "symptoms": {"edema", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Progressive kidney damage from chronic diabetes causing proteinuria and eventual renal failure.",
        "description_ja": "慢性糖尿病による進行性の腎障害で、タンパク尿と最終的な腎不全を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_ultrasound"],
    },
    {
        "name": "Diabetic Foot Ulcer",
        "name_ja": "糖尿病性足潰瘍",
        "symptoms": {"foot_swelling", "foot_ulceration", "lameness", "slow_wound_healing"},
        "description": "Non-healing foot ulcers from diabetic neuropathy and impaired circulation. Often complicated by secondary infection.",
        "description_ja": "糖尿病性神経障害と循環障害による非治癒性足潰瘍。二次感染により複雑化することが多いです。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "wound_culture", "foot_xray"],
    },
    {
        "name": "Dental Malocclusion - Molar (Acquired)",
        "name_ja": "不正咬合 - 臼歯（後天性）",
        "symptoms": {"appetite_loss", "drooling", "eye_discharge", "selective_eating", "weight_loss"},
        "description": "Acquired molar overgrowth and spur formation from inadequate wear. Extremely common in captive degus lacking proper abrasive diet.",
        "description_ja": "適切な摩耗の不足による後天性臼歯過長とスパー形成。適切な研磨性食事を欠く飼育下デグーに非常に多いです。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_xray", "dental_endoscopy"],
    },
    {
        "name": "Dental Malocclusion - Incisor (Congenital)",
        "name_ja": "不正咬合 - 切歯（先天性）",
        "symptoms": {"difficulty_eating", "drooling", "visible_tooth_overgrowth", "weight_loss"},
        "description": "Congenital misalignment of incisors preventing normal gnawing and requiring regular trimming.",
        "description_ja": "先天性の切歯不整列で、正常な齧りを妨げ、定期的なトリミングが必要です。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "skull_xray", "physical_exam"],
    },
    {
        "name": "Tooth Root Elongation",
        "name_ja": "歯根伸長",
        "symptoms": {"appetite_loss", "drooling", "epiphora", "jaw_swelling", "nasal_discharge"},
        "description": "Apical elongation of tooth roots penetrating into the nasal cavity (upper) or through the mandible (lower).",
        "description_ja": "歯根の根尖伸長で、鼻腔（上顎）または下顎を貫通します。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "ct_scan", "dental_exam"],
    },
    {
        "name": "Mandibular Abscess (Dental Origin)",
        "name_ja": "下顎膿瘍（歯原性）",
        "symptoms": {"appetite_loss", "draining_tract", "drooling", "jaw_swelling", "weight_loss"},
        "description": "Abscess of the mandible originating from infected tooth roots. Requires aggressive long-term treatment.",
        "description_ja": "感染した歯根から発生する下顎の膿瘍。積極的な長期治療が必要です。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "culture_sensitivity", "ct_scan"],
    },
    {
        "name": "Enamel Hypoplasia",
        "name_ja": "エナメル質形成不全",
        "symptoms": {"difficulty_eating", "drooling", "tooth_discoloration", "tooth_fracture"},
        "description": "Developmental defect in enamel formation causing weak, discolored teeth prone to fracture.",
        "description_ja": "エナメル質形成の発達障害で、骨折しやすい弱く変色した歯になります。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "skull_xray", "physical_exam"],
    },
    {
        "name": "Bumblefoot - Advanced (Osteomyelitis)",
        "name_ja": "趾瘤症 - 進行型（骨髄炎）",
        "symptoms": {"bone_infection", "foot_ulceration", "lameness", "reluctance_to_move", "severe_foot_swelling"},
        "description": "Advanced pododermatitis with deep infection extending into bone causing osteomyelitis. May require digit amputation.",
        "description_ja": "骨に及ぶ深部感染を伴う進行した趾瘤症で骨髄炎を引き起こします。指切断が必要な場合があります。",
        "urgency": "high",
        "recommended_tests": ["foot_xray", "culture_sensitivity", "physical_exam"],
    },
    {
        "name": "Tail Degloving - Complete",
        "name_ja": "尾部皮膚剥離 - 完全型",
        "symptoms": {"bleeding", "exposed_tail_bone", "pain", "tail_necrosis"},
        "description": "Complete avulsion of tail skin exposing the vertebrae. Degu tails are extremely fragile and dislodge easily as a defence mechanism.",
        "description_ja": "尾の皮膚が完全に剥離し椎骨が露出。デグーの尾は防衛機構として非常にもろく容易に剥離します。",
        "urgency": "high",
        "recommended_tests": ["tail_xray", "physical_exam", "wound_assessment"],
    },
    {
        "name": "Tail Amputation Stump Infection",
        "name_ja": "尾切断部感染",
        "symptoms": {"discharge", "fever", "lethargy", "swelling_at_tail_stump"},
        "description": "Infection of the tail stump following degloving injury or surgical amputation requiring antibiotic therapy.",
        "description_ja": "皮膚剥離損傷または外科的切断後の尾断端の感染で、抗生物質療法が必要です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_culture", "physical_exam", "tail_xray"],
    },
    {
        "name": "Fur Chewing (Barbering) - Severe",
        "name_ja": "毛噛み（バーバリング）- 重症型",
        "symptoms": {"extensive_hair_loss", "rough_coat", "skin_lesions", "stress_signs"},
        "description": "Severe self or social barbering causing extensive alopecia. May indicate stress, boredom, or nutritional deficiency.",
        "description_ja": "広範な脱毛を引き起こす重度の自己または社会的バーバリング。ストレス、退屈、栄養欠乏を示す可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "behavioral_assessment", "diet_review"],
    },
    {
        "name": "Sarcoptic Mange",
        "name_ja": "疥癬",
        "symptoms": {"hair_loss", "intense_itching", "skin_crusting", "skin_thickening", "weight_loss"},
        "description": "Sarcoptes scabiei mite infestation causing severe pruritus, crusting, and secondary infection.",
        "description_ja": "ヒゼンダニの寄生で、重度の掻痒、痂皮形成、二次感染を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    {
        "name": "Lice Infestation",
        "name_ja": "シラミ寄生症",
        "symptoms": {"hair_loss", "pruritus", "restlessness", "visible_lice"},
        "description": "Infestation by species-specific lice causing pruritus and poor coat condition.",
        "description_ja": "種特異的なシラミの寄生で、掻痒と被毛状態の悪化を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["coat_exam", "microscopy", "physical_exam"],
    },
    {
        "name": "Trichophyton mentagrophytes (Ringworm) - Extensive",
        "name_ja": "白癬菌感染 - 広範囲型",
        "symptoms": {"circular_hair_loss", "crusting", "skin_scaling", "widespread_lesions"},
        "description": "Extensive dermatophyte infection covering large areas of the body. Zoonotic to humans.",
        "description_ja": "体の広い範囲に及ぶ広範な皮膚糸状菌感染。ヒトへの人獣共通感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "wood_lamp", "skin_scraping"],
    },
    {
        "name": "Bacterial Pneumonia (Acute)",
        "name_ja": "細菌性肺炎（急性）",
        "symptoms": {"appetite_loss", "fever", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Acute bacterial lung infection often secondary to stress, overcrowding, or viral upper respiratory infection.",
        "description_ja": "ストレス、過密飼育、ウイルス性上気道感染に続発することが多い急性細菌性肺感染です。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "tracheal_wash", "culture_sensitivity"],
    },
    {
        "name": "Mycoplasma Infection",
        "name_ja": "マイコプラズマ感染症",
        "symptoms": {"chronic_sneezing", "conjunctivitis", "nasal_discharge", "respiratory_distress"},
        "description": "Chronic respiratory infection by Mycoplasma pulmonis causing persistent rhinitis and potential pneumonia.",
        "description_ja": "マイコプラズマ・プルモニスによる慢性呼吸器感染で、持続的な鼻炎と肺炎の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_testing", "chest_xray", "nasal_swab"],
    },
    {
        "name": "Bordetella Pneumonia",
        "name_ja": "ボルデテラ肺炎",
        "symptoms": {"coughing", "fever", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Severe pneumonia caused by Bordetella bronchiseptica, potentially fatal in young or immunocompromised degus.",
        "description_ja": "ボルデテラ・ブロンキセプティカによる重症肺炎で、若齢や免疫不全のデグーに致死的になり得ます。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "tracheal_wash", "culture_sensitivity"],
    },
    {
        "name": "Clostridial Enteritis",
        "name_ja": "クロストリジウム腸炎",
        "symptoms": {"abdominal_distension", "dehydration", "diarrhea", "lethargy", "sudden_death"},
        "description": "Toxin-mediated enteritis from Clostridium species, often secondary to antibiotic use or dietary changes.",
        "description_ja": "クロストリジウム属菌による毒素介在性腸炎で、抗生物質使用や食事変更に続発することが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_culture", "fecal_toxin_assay", "blood_chemistry"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"appetite_loss", "diarrhea", "fever", "lethargy", "sudden_death"},
        "description": "Bacterial infection by Salmonella species causing enteritis and septicaemia. Zoonotic risk.",
        "description_ja": "サルモネラ属による細菌感染で、腸炎と敗血症を引き起こします。人獣共通感染症のリスクがあります。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "blood_culture", "blood_chemistry"],
    },
    {
        "name": "E. coli Enteritis",
        "name_ja": "大腸菌性腸炎",
        "symptoms": {"appetite_loss", "dehydration", "diarrhea", "lethargy"},
        "description": "Pathogenic E. coli infection causing acute diarrhea, particularly in young or stressed degus.",
        "description_ja": "病原性大腸菌感染による急性下痢で、特に若齢やストレス下のデグーに多いです。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "blood_chemistry", "physical_exam"],
    },
    {
        "name": "Cecal Dysbiosis",
        "name_ja": "盲腸内細菌叢異常",
        "symptoms": {"abdominal_pain", "appetite_loss", "diarrhea", "gas", "soft_stool"},
        "description": "Disruption of normal cecal microbiome from inappropriate diet or antibiotic use.",
        "description_ja": "不適切な食事や抗生物質使用による盲腸の正常な微生物叢の撹乱です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "physical_exam", "diet_review"],
    },
    {
        "name": "Gastric Ulceration",
        "name_ja": "胃潰瘍",
        "symptoms": {"abdominal_pain", "appetite_loss", "dark_stool", "teeth_grinding", "weight_loss"},
        "description": "Erosion and ulceration of the gastric mucosa from stress, NSAID use, or Helicobacter infection.",
        "description_ja": "ストレス、NSAID使用、ヘリコバクター感染による胃粘膜の糜爛と潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_occult_blood", "blood_chemistry"],
    },
    {
        "name": "Cecal Impaction",
        "name_ja": "盲腸嵌頓",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "reduced_fecal_output"},
        "description": "Impaction of the cecum with dried ingesta from dehydration or low fibre diet.",
        "description_ja": "脱水や低繊維食による乾燥した内容物の盲腸嵌頓です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "physical_exam", "abdominal_palpation"],
    },
    {
        "name": "Intussusception",
        "name_ja": "腸重積症",
        "symptoms": {"abdominal_pain", "bloody_stool", "dehydration", "lethargy", "vomiting"},
        "description": "Telescoping of one intestinal segment into another causing obstruction and ischemia.",
        "description_ja": "腸の一部が別の部分に陥入し、閉塞と虚血を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray", "physical_exam"],
    },
    {
        "name": "Hepatic Coccidiosis",
        "name_ja": "肝コクシジウム症",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Coccidia infection affecting the liver causing bile duct hyperplasia and potential liver failure.",
        "description_ja": "肝臓に影響するコクシジウム感染で、胆管過形成と肝不全の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["fecal_flotation", "blood_chemistry", "liver_ultrasound"],
    },
    {
        "name": "Pinworm Infection (Syphacia)",
        "name_ja": "蟯虫感染（シファシア）",
        "symptoms": {"perianal_irritation", "poor_coat", "restlessness", "weight_loss"},
        "description": "Common intestinal nematode infection usually causing mild signs but can be significant in immunocompromised animals.",
        "description_ja": "通常軽度の症状を引き起こす一般的な腸管線虫感染ですが、免疫不全動物では重要です。",
        "urgency": "low",
        "recommended_tests": ["fecal_flotation", "perianal_tape_test", "physical_exam"],
    },
    {
        "name": "Tapeworm Infection",
        "name_ja": "条虫感染症",
        "symptoms": {"perianal_irritation", "poor_coat", "visible_proglottids", "weight_loss"},
        "description": "Cestode infection causing weight loss and potential intestinal obstruction in heavy burdens.",
        "description_ja": "条虫感染で、重度寄生では体重減少と腸閉塞の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_exam", "physical_exam"],
    },
    {
        "name": "Nephrolithiasis",
        "name_ja": "腎結石症",
        "symptoms": {"appetite_loss", "back_pain", "blood_in_urine", "polydipsia"},
        "description": "Formation of calculi within the kidneys causing obstruction and progressive renal damage.",
        "description_ja": "腎臓内の結石形成で、閉塞と進行性の腎障害を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "renal_ultrasound", "urinalysis"],
    },
    {
        "name": "Pyelonephritis",
        "name_ja": "腎盂腎炎",
        "symptoms": {"appetite_loss", "back_pain", "fever", "lethargy", "polydipsia"},
        "description": "Ascending bacterial infection of the kidney from lower urinary tract disease.",
        "description_ja": "下部尿路疾患からの上行性腎臓細菌感染です。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "urine_culture", "renal_ultrasound"],
    },
    {
        "name": "Urethral Obstruction",
        "name_ja": "尿道閉塞",
        "symptoms": {"abdominal_pain", "lethargy", "straining_to_urinate", "vocalization"},
        "description": "Blockage of the urethra by calculi preventing urination. Life-threatening if complete.",
        "description_ja": "結石による尿道の閉塞で排尿不能。完全閉塞は生命を脅かします。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "abdominal_xray", "urinalysis"],
    },
    {
        "name": "Ovarian Cysts",
        "name_ja": "卵巣嚢胞",
        "symptoms": {"abdominal_distension", "behavioral_changes", "hair_loss", "vulvar_swelling"},
        "description": "Fluid-filled ovarian cysts causing hormonal disturbances and bilateral alopecia in intact females.",
        "description_ja": "未避妊の雌のホルモン障害と両側性脱毛を引き起こす液体で満たされた卵巣嚢胞です。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "hormone_panel", "physical_exam"],
    },
    {
        "name": "Endometritis",
        "name_ja": "子宮内膜炎",
        "symptoms": {"appetite_loss", "fever", "lethargy", "vaginal_discharge"},
        "description": "Inflammation and infection of the uterine lining, which may progress to pyometra.",
        "description_ja": "子宮内膜の炎症と感染で、子宮蓄膿症に進行する可能性があります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "vaginal_cytology", "blood_chemistry"],
    },
    {
        "name": "Pregnancy Toxemia",
        "name_ja": "妊娠中毒症",
        "symptoms": {"appetite_loss", "lethargy", "rapid_breathing", "seizures", "weakness"},
        "description": "Metabolic crisis in late-pregnant degus from negative energy balance causing ketosis.",
        "description_ja": "妊娠後期のデグーの負のエネルギーバランスによるケトーシスを伴う代謝危機です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"appetite_loss", "fever", "mammary_redness", "mammary_swelling", "pain"},
        "description": "Bacterial infection of the mammary glands in lactating females.",
        "description_ja": "授乳中の雌の乳腺の細菌感染です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "milk_culture", "blood_chemistry"],
    },
    {
        "name": "Retained Fetus",
        "name_ja": "胎児残留",
        "symptoms": {"abdominal_distension", "fever", "lethargy", "vaginal_discharge"},
        "description": "Failure to deliver all pups during birth, leading to infection and toxaemia.",
        "description_ja": "分娩時にすべての子を排出できない状態で、感染と毒血症に至ります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Neonatal Mortality",
        "name_ja": "新生児死亡",
        "symptoms": {"failure_to_thrive", "hypothermia", "weakness"},
        "description": "Death of pups in the first week of life from maternal neglect, cold, or congenital defects.",
        "description_ja": "母親の育児放棄、低温、先天性欠陥による生後1週間以内の子の死亡です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "necropsy", "environmental_review"],
    },
    {
        "name": "Pericardial Effusion",
        "name_ja": "心嚢液貯留",
        "symptoms": {"exercise_intolerance", "lethargy", "muffled_heart_sounds", "respiratory_distress"},
        "description": "Fluid accumulation around the heart causing cardiac tamponade and reduced output.",
        "description_ja": "心臓周囲の液体蓄積で心タンポナーデと拍出量低下を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "chest_xray", "pericardiocentesis"],
    },
    {
        "name": "Aortic Calcification",
        "name_ja": "大動脈石灰化",
        "symptoms": {"exercise_intolerance", "hind_limb_weakness", "lethargy", "sudden_death"},
        "description": "Calcification of major vessels, common in diabetic degus or those with dietary calcium-phosphorus imbalance.",
        "description_ja": "主要血管の石灰化で、糖尿病デグーやカルシウム-リンバランス不均衡のデグーに多いです。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "blood_chemistry", "echocardiography"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"appetite_loss", "lethargy", "lymph_node_swelling", "splenomegaly", "weight_loss"},
        "description": "Neoplastic proliferation of lymphocytes affecting lymph nodes, spleen, and other organs.",
        "description_ja": "リンパ節、脾臓、他の臓器に影響するリンパ球の腫瘍性増殖です。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "cbc", "abdominal_ultrasound"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"rapid_growth", "skin_masses", "ulceration", "weight_loss"},
        "description": "Malignant connective tissue tumour. Can occur at any body site.",
        "description_ja": "悪性結合組織腫瘍。体のどの部位にも発生し得ます。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"slow_growing_lump", "subcutaneous_mass"},
        "description": "Benign fatty tumour commonly found subcutaneously. Usually non-problematic.",
        "description_ja": "皮下に一般的に見られる良性脂肪腫瘍。通常問題ありません。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "physical_exam"],
    },
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"bleeding_from_mass", "skin_masses", "ulceration", "weight_loss"},
        "description": "Malignant epithelial tumour of the skin or oral cavity.",
        "description_ja": "皮膚や口腔の悪性上皮腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Hepatocellular Carcinoma",
        "name_ja": "肝細胞癌",
        "symptoms": {"abdominal_distension", "jaundice", "lethargy", "weight_loss"},
        "description": "Primary malignant liver tumour with poor prognosis.",
        "description_ja": "予後不良の原発性悪性肝臓腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["liver_ultrasound", "blood_chemistry", "fine_needle_aspirate"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "limb_swelling", "pain", "pathological_fracture"},
        "description": "Malignant bone tumour with metastatic potential, primarily affecting long bones.",
        "description_ja": "転移能を持つ悪性骨腫瘍で、主に長管骨に発生します。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "chest_xray", "biopsy"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism",
        "name_ja": "栄養性二次性副甲状腺機能亢進症",
        "symptoms": {"bone_pain", "lameness", "pathological_fractures", "soft_jaw"},
        "description": "Excessive parathyroid hormone from calcium-phosphorus dietary imbalance causing bone demineralisation.",
        "description_ja": "カルシウム-リン食事不均衡による副甲状腺ホルモンの過剰分泌で、骨の脱灰を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "xray", "diet_review"],
    },
    {
        "name": "Alzheimer's-like Disease",
        "name_ja": "アルツハイマー様疾患",
        "symptoms": {"behavioral_changes", "confusion", "disorientation", "lethargy", "memory_loss"},
        "description": "Age-related neurodegenerative disease in degus with beta-amyloid plaques similar to human Alzheimer's. Degus are a natural model for this disease.",
        "description_ja": "ヒトのアルツハイマー病に類似したベータアミロイド斑を持つデグーの加齢性神経変性疾患。デグーはこの疾患の自然モデルです。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "behavioral_assessment", "physical_exam"],
    },
    {
        "name": "Cognitive Dysfunction (Senile)",
        "name_ja": "認知機能障害（老齢性）",
        "symptoms": {"decreased_social_interaction", "disorientation", "repetitive_behavior", "sleep_pattern_changes"},
        "description": "Age-related cognitive decline in older degus causing altered behaviour and social withdrawal.",
        "description_ja": "高齢デグーの加齢関連認知機能低下で、行動変化と社会的引きこもりを引き起こします。",
        "urgency": "low",
        "recommended_tests": ["neurological_exam", "physical_exam", "behavioral_assessment"],
    },
    {
        "name": "Peripheral Neuropathy (Diabetic)",
        "name_ja": "末梢神経障害（糖尿病性）",
        "symptoms": {"abnormal_gait", "hind_limb_weakness", "muscle_wasting", "reduced_reflexes"},
        "description": "Nerve damage from chronic hyperglycaemia causing progressive hind limb weakness and ataxia.",
        "description_ja": "慢性高血糖による神経損傷で、進行性の後肢脱力と運動失調を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "blood_glucose", "physical_exam"],
    },
    {
        "name": "Femoral Fracture",
        "name_ja": "大腿骨骨折",
        "symptoms": {"lameness", "limb_swelling", "non_weight_bearing", "pain"},
        "description": "Fracture of the femur from falls, cage injuries, or metabolic bone disease.",
        "description_ja": "落下、ケージ内外傷、代謝性骨疾患による大腿骨の骨折です。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Tibial Fracture",
        "name_ja": "脛骨骨折",
        "symptoms": {"crepitus", "lameness", "limb_swelling", "pain"},
        "description": "Fracture of the tibia, common from exercise wheel injuries or falls.",
        "description_ja": "回し車の怪我や落下による脛骨の骨折です。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "physical_exam"],
    },
    {
        "name": "Patellar Luxation",
        "name_ja": "膝蓋骨脱臼",
        "symptoms": {"abnormal_gait", "intermittent_lameness", "limb_stiffness"},
        "description": "Displacement of the kneecap causing intermittent lameness.",
        "description_ja": "膝蓋骨の脱臼で間欠的な跛行を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["orthopedic_exam", "limb_xray"],
    },
    {
        "name": "Exercise Wheel Injury",
        "name_ja": "回し車による外傷",
        "symptoms": {"lameness", "limb_fracture", "skin_abrasion", "tail_injury"},
        "description": "Injuries from inappropriate exercise wheels (wire mesh, spoked) causing tail degloving, limb fractures, and abrasions.",
        "description_ja": "不適切な回し車（金網、スポーク付き）による尾の皮膚剥離、四肢骨折、擦過傷です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "xray", "wound_assessment"],
    },
    {
        "name": "Toxicosis (Plant Poisoning)",
        "name_ja": "中毒症（植物中毒）",
        "symptoms": {"diarrhea", "drooling", "lethargy", "seizures", "sudden_death"},
        "description": "Poisoning from ingestion of toxic houseplants or treated wood during out-of-cage time.",
        "description_ja": "ケージ外での活動中に有毒な観葉植物や処理済み木材を摂取することによる中毒です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"anemia", "appetite_loss", "jaundice", "lethargy"},
        "description": "Poisoning from chewing galvanised cage components causing haemolytic anaemia.",
        "description_ja": "亜鉛メッキされたケージ部品を齧ることによる溶血性貧血を伴う中毒です。",
        "urgency": "high",
        "recommended_tests": ["cbc", "serum_zinc_level", "blood_chemistry"],
    },
    {
        "name": "Sand Bath Impaction",
        "name_ja": "砂浴びによる閉塞",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "reduced_fecal_output"},
        "description": "Gastrointestinal impaction from ingestion of sand bath material. Degus may eat sand bath dust.",
        "description_ja": "砂浴び材料の摂取による消化管閉塞。デグーは砂浴びの砂を食べることがあります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "physical_exam", "abdominal_palpation"],
    },
    {
        "name": "Social Stress (Single Housing)",
        "name_ja": "社会的ストレス（単独飼育）",
        "symptoms": {"aggression", "barbering", "lethargy", "poor_coat", "stereotypic_behavior"},
        "description": "Chronic stress from solitary housing. Degus are highly social animals that must be housed in groups.",
        "description_ja": "単独飼育による慢性ストレス。デグーは高度に社会的な動物で、群れで飼育する必要があります。",
        "urgency": "moderate",
        "recommended_tests": ["behavioral_assessment", "environmental_review", "physical_exam"],
    },
    {
        "name": "Corneal Dystrophy",
        "name_ja": "角膜ジストロフィー",
        "symptoms": {"corneal_opacity", "eye_discharge", "vision_loss"},
        "description": "Inherited or age-related degenerative corneal disease. May be associated with diabetes.",
        "description_ja": "遺伝性または加齢性の変性性角膜疾患。糖尿病と関連する可能性があります。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose", "physical_exam"],
    },
    {
        "name": "Glaucoma",
        "name_ja": "緑内障",
        "symptoms": {"enlarged_eye", "eye_pain", "eye_redness", "vision_loss"},
        "description": "Increased intraocular pressure causing optic nerve damage and progressive vision loss.",
        "description_ja": "眼内圧の上昇による視神経損傷と進行性視力喪失です。",
        "urgency": "high",
        "recommended_tests": ["tonometry", "ophthalmic_exam", "physical_exam"],
    },
    {
        "name": "Cage Aggression (Territorial)",
        "name_ja": "ケージ攻撃性（縄張り）",
        "symptoms": {"aggression", "bite_wounds", "hair_loss", "stress_signs"},
        "description": "Territorial aggression between degus, particularly when introducing new members to an established group.",
        "description_ja": "デグー間の縄張り攻撃性で、特に確立されたグループに新しいメンバーを導入する際に見られます。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "wound_assessment", "behavioral_assessment"],
    },
    {
        "name": "Hypothyroidism",
        "name_ja": "甲状腺機能低下症",
        "symptoms": {"cold_intolerance", "lethargy", "obesity", "poor_coat"},
        "description": "Reduced thyroid hormone production causing metabolic slowdown and weight gain.",
        "description_ja": "甲状腺ホルモン産生の低下による代謝低下と体重増加です。",
        "urgency": "low",
        "recommended_tests": ["thyroid_panel", "blood_chemistry", "physical_exam"],
    },
]


# ---------------------------------------------------------------------------
# Symptom name lookup
# ---------------------------------------------------------------------------

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # Endocrine / Metabolic
    "polyuria": {"ja": "多尿", "en": "Polyuria"},
    "polydipsia": {"ja": "多飲", "en": "Polydipsia"},
    "hyperglycemia": {"ja": "高血糖", "en": "Hyperglycemia"},
    "weight_loss": {"ja": "体重減少", "en": "Weight Loss"},
    "weight_gain": {"ja": "体重増加", "en": "Weight Gain"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "lethargy": {"ja": "無気力・元気消失", "en": "Lethargy"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "shivering": {"ja": "震え", "en": "Shivering"},
    "cold_extremities": {"ja": "四肢の冷感", "en": "Cold Extremities"},
    # Ophthalmological
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy Eyes"},
    "vision_loss": {"ja": "視力低下", "en": "Vision Loss"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into Objects"},
    "eye_discharge": {"ja": "眼脂・目やに", "en": "Eye Discharge"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye Redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye Swelling"},
    "squinting": {"ja": "眼を細める", "en": "Squinting"},
    "pawing_at_eye": {"ja": "眼を前足で掻く", "en": "Pawing at Eye"},
    "sunken_eyes": {"ja": "眼の陥没", "en": "Sunken Eyes"},
    # Dental
    "drooling": {"ja": "流涎・よだれ", "en": "Drooling"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite Loss"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth Grinding"},
    "visible_tooth_overgrowth": {"ja": "歯の過長が目視できる", "en": "Visible Tooth Overgrowth"},
    "facial_swelling": {"ja": "顔面の腫脹", "en": "Facial Swelling"},
    "bleeding_gums": {"ja": "歯肉出血", "en": "Bleeding Gums"},
    # Dermatological
    "hair_loss": {"ja": "脱毛", "en": "Hair Loss"},
    "crusty_skin": {"ja": "痂皮形成", "en": "Crusty Skin"},
    "scaly_skin": {"ja": "鱗屑", "en": "Scaly Skin"},
    "itching": {"ja": "かゆみ", "en": "Itching"},
    "scratching": {"ja": "引っ掻き行動", "en": "Scratching"},
    "circular_lesions": {"ja": "円形の病変", "en": "Circular Lesions"},
    "patchy_fur": {"ja": "まだらな被毛", "en": "Patchy Fur"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin Redness"},
    "skin_mass": {"ja": "皮膚の腫瘤", "en": "Skin Mass"},
    "ulceration": {"ja": "潰瘍", "en": "Ulceration"},
    "stress_behavior": {"ja": "ストレス行動", "en": "Stress Behavior"},
    # Tail
    "tail_injury": {"ja": "尾部の損傷", "en": "Tail Injury"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "exposed_bone": {"ja": "骨の露出", "en": "Exposed Bone"},
    # Musculoskeletal
    "swollen_feet": {"ja": "足の腫脹", "en": "Swollen Feet"},
    "foot_sores": {"ja": "足底の傷", "en": "Foot Sores"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "limb_deformity": {"ja": "四肢の変形", "en": "Limb Deformity"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to Move"},
    "stiffness": {"ja": "硬直・こわばり", "en": "Stiffness"},
    "swollen_joints": {"ja": "関節の腫脹", "en": "Swollen Joints"},
    "hind_leg_paralysis": {"ja": "後肢麻痺", "en": "Hind Leg Paralysis"},
    "dragging_legs": {"ja": "後肢を引きずる", "en": "Dragging Hind Legs"},
    # Respiratory
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal Discharge"},
    "labored_breathing": {"ja": "努力性呼吸", "en": "Labored Breathing"},
    "rapid_breathing": {"ja": "頻呼吸", "en": "Rapid Breathing"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    # Gastrointestinal
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "bloating": {"ja": "膨満", "en": "Bloating"},
    "reduced_fecal_output": {"ja": "排便量の減少", "en": "Reduced Fecal Output"},
    "straining": {"ja": "いきみ・排便困難", "en": "Straining"},
    "rough_coat": {"ja": "被毛の荒れ", "en": "Rough Coat"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "bloody_stool": {"ja": "血便", "en": "Bloody Stool"},
    "tissue_protrusion_anus": {"ja": "肛門からの組織突出", "en": "Tissue Protrusion from Anus"},
    # General
    "pain": {"ja": "疼痛", "en": "Pain"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "discharge": {"ja": "分泌物・排膿", "en": "Discharge"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    "reduced_activity": {"ja": "活動量の低下", "en": "Reduced Activity"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "distended_abdomen": {"ja": "腹部膨満", "en": "Distended Abdomen"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "incontinence": {"ja": "失禁", "en": "Incontinence"},
    # Urinary
    "blood_in_urine": {"ja": "血尿", "en": "Blood in Urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent Urination"},
    # Reproductive
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal Discharge"},
    "mammary_mass": {"ja": "乳腺の腫瘤", "en": "Mammary Mass"},
    "testicular_swelling": {"ja": "精巣の腫脹", "en": "Testicular Swelling"},
    "asymmetric_testes": {"ja": "精巣の左右差", "en": "Asymmetric Testes"},
    # Neurological
    "seizures": {"ja": "痙攣・発作", "en": "Seizures"},
    "disorientation": {"ja": "見当識障害", "en": "Disorientation"},
    "head_tilt": {"ja": "斜頸", "en": "Head Tilt"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "loss_of_balance": {"ja": "平衡感覚の喪失", "en": "Loss of Balance"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    # Ear
    "scratching_ear": {"ja": "耳を掻く", "en": "Scratching Ear"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear Discharge"},

    # --- 追加症状 (DISEASES内で使用されている未登録項目) ---
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal pain"},
    "abnormal_gait": {"ja": "異常歩行", "en": "Abnormal gait"},
    "aggression": {"ja": "Aggression", "en": "Aggression"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "back_pain": {"ja": "Back Pain", "en": "Back Pain"},
    "barbering": {"ja": "Barbering", "en": "Barbering"},
    "behavioral_changes": {"ja": "行動変化", "en": "Behavioral changes"},
    "bite_wounds": {"ja": "Bite Wounds", "en": "Bite Wounds"},
    "bleeding_from_mass": {"ja": "Bleeding From Mass", "en": "Bleeding From Mass"},
    "bone_infection": {"ja": "Bone Infection", "en": "Bone Infection"},
    "bone_pain": {"ja": "Bone Pain", "en": "Bone Pain"},
    "chronic_sneezing": {"ja": "Chronic Sneezing", "en": "Chronic Sneezing"},
    "circular_hair_loss": {"ja": "Circular Hair Loss", "en": "Circular Hair Loss"},
    "cold_intolerance": {"ja": "Cold Intolerance", "en": "Cold Intolerance"},
    "confusion": {"ja": "Confusion", "en": "Confusion"},
    "conjunctivitis": {"ja": "Conjunctivitis", "en": "Conjunctivitis"},
    "corneal_opacity": {"ja": "Corneal Opacity", "en": "Corneal Opacity"},
    "crepitus": {"ja": "捻髪音", "en": "Crepitus"},
    "crusting": {"ja": "Crusting", "en": "Crusting"},
    "dark_stool": {"ja": "Dark Stool", "en": "Dark Stool"},
    "decreased_social_interaction": {"ja": "Decreased Social Interaction", "en": "Decreased Social Interaction"},
    "difficulty_eating": {"ja": "Difficulty Eating", "en": "Difficulty Eating"},
    "dilated_pupils": {"ja": "Dilated Pupils", "en": "Dilated Pupils"},
    "draining_tract": {"ja": "Draining Tract", "en": "Draining Tract"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "enlarged_eye": {"ja": "Enlarged Eye", "en": "Enlarged Eye"},
    "epiphora": {"ja": "Epiphora", "en": "Epiphora"},
    "excessive_hunger": {"ja": "Excessive Hunger", "en": "Excessive Hunger"},
    "exercise_intolerance": {"ja": "Exercise Intolerance", "en": "Exercise Intolerance"},
    "exposed_tail_bone": {"ja": "Exposed Tail Bone", "en": "Exposed Tail Bone"},
    "extensive_hair_loss": {"ja": "Extensive Hair Loss", "en": "Extensive Hair Loss"},
    "eye_pain": {"ja": "Eye Pain", "en": "Eye Pain"},
    "failure_to_thrive": {"ja": "Failure To Thrive", "en": "Failure To Thrive"},
    "foot_swelling": {"ja": "Foot Swelling", "en": "Foot Swelling"},
    "foot_ulceration": {"ja": "Foot Ulceration", "en": "Foot Ulceration"},
    "gas": {"ja": "Gas", "en": "Gas"},
    "hind_limb_weakness": {"ja": "後肢の衰弱", "en": "Hind limb weakness"},
    "hypothermia": {"ja": "低体温", "en": "Hypothermia"},
    "intense_itching": {"ja": "Intense Itching", "en": "Intense Itching"},
    "intermittent_lameness": {"ja": "Intermittent Lameness", "en": "Intermittent Lameness"},
    "jaw_swelling": {"ja": "Jaw Swelling", "en": "Jaw Swelling"},
    "limb_fracture": {"ja": "Limb Fracture", "en": "Limb Fracture"},
    "limb_stiffness": {"ja": "Limb Stiffness", "en": "Limb Stiffness"},
    "limb_swelling": {"ja": "四肢腫脹", "en": "Limb swelling"},
    "lymph_node_swelling": {"ja": "Lymph Node Swelling", "en": "Lymph Node Swelling"},
    "mammary_redness": {"ja": "Mammary Redness", "en": "Mammary Redness"},
    "mammary_swelling": {"ja": "Mammary Swelling", "en": "Mammary Swelling"},
    "memory_loss": {"ja": "Memory Loss", "en": "Memory Loss"},
    "muffled_heart_sounds": {"ja": "Muffled Heart Sounds", "en": "Muffled Heart Sounds"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "non_weight_bearing": {"ja": "Non Weight Bearing", "en": "Non Weight Bearing"},
    "pathological_fracture": {"ja": "Pathological Fracture", "en": "Pathological Fracture"},
    "pathological_fractures": {"ja": "Pathological Fractures", "en": "Pathological Fractures"},
    "perianal_irritation": {"ja": "Perianal Irritation", "en": "Perianal Irritation"},
    "poor_coat": {"ja": "Poor Coat", "en": "Poor Coat"},
    "pruritus": {"ja": "Pruritus", "en": "Pruritus"},
    "rapid_growth": {"ja": "Rapid Growth", "en": "Rapid Growth"},
    "reduced_reflexes": {"ja": "Reduced Reflexes", "en": "Reduced Reflexes"},
    "repetitive_behavior": {"ja": "Repetitive Behavior", "en": "Repetitive Behavior"},
    "respiratory_distress": {"ja": "呼吸窮迫", "en": "Respiratory distress"},
    "selective_eating": {"ja": "Selective Eating", "en": "Selective Eating"},
    "severe_foot_swelling": {"ja": "Severe Foot Swelling", "en": "Severe Foot Swelling"},
    "skin_abrasion": {"ja": "Skin Abrasion", "en": "Skin Abrasion"},
    "skin_crusting": {"ja": "Skin Crusting", "en": "Skin Crusting"},
    "skin_lesions": {"ja": "Skin Lesions", "en": "Skin Lesions"},
    "skin_masses": {"ja": "皮膚腫瘤", "en": "Skin masses"},
    "skin_scaling": {"ja": "Skin Scaling", "en": "Skin Scaling"},
    "skin_thickening": {"ja": "Skin Thickening", "en": "Skin Thickening"},
    "sleep_pattern_changes": {"ja": "Sleep Pattern Changes", "en": "Sleep Pattern Changes"},
    "slow_growing_lump": {"ja": "Slow Growing Lump", "en": "Slow Growing Lump"},
    "slow_wound_healing": {"ja": "Slow Wound Healing", "en": "Slow Wound Healing"},
    "soft_jaw": {"ja": "Soft Jaw", "en": "Soft Jaw"},
    "soft_stool": {"ja": "Soft Stool", "en": "Soft Stool"},
    "splenomegaly": {"ja": "脾腫", "en": "Splenomegaly"},
    "stereotypic_behavior": {"ja": "Stereotypic Behavior", "en": "Stereotypic Behavior"},
    "straining_to_urinate": {"ja": "排尿困難", "en": "Straining to urinate"},
    "stress_signs": {"ja": "Stress Signs", "en": "Stress Signs"},
    "subcutaneous_mass": {"ja": "Subcutaneous Mass", "en": "Subcutaneous Mass"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "swelling_at_tail_stump": {"ja": "Swelling At Tail Stump", "en": "Swelling At Tail Stump"},
    "tail_necrosis": {"ja": "Tail Necrosis", "en": "Tail Necrosis"},
    "tooth_discoloration": {"ja": "Tooth Discoloration", "en": "Tooth Discoloration"},
    "tooth_fracture": {"ja": "Tooth Fracture", "en": "Tooth Fracture"},
    "visible_lice": {"ja": "Visible Lice", "en": "Visible Lice"},
    "visible_proglottids": {"ja": "Visible Proglottids", "en": "Visible Proglottids"},
    "vocalization": {"ja": "Vocalization", "en": "Vocalization"},
    "vulvar_swelling": {"ja": "外陰部腫脹", "en": "Vulvar swelling"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "widespread_lesions": {"ja": "Widespread Lesions", "en": "Widespread Lesions"},
}


# ---------------------------------------------------------------------------
# Public analysis function
# ---------------------------------------------------------------------------

def analyze_symptoms(
    symptoms: List[str],
    age_stage: str = "",
    breed: str | None = None,
    *,
    onset: str | None = None,
    age_years: float | None = None,
    species: str | None = None,
    lab_values: dict | None = None,
    gender: str | None = None,
) -> Dict[str, Any]:
    """Run differential diagnosis for degus based on reported symptoms."""
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species, lab_values=lab_values, gender=gender, prevalence_map=prevalence_data.SPECIES_PREVALENCE.get("degu", {}))
