"""exotic_other_diseases.py – その他エキゾチック動物の一般的な疾患

ミニブタ、アライグマ、スカンク、プレーリードッグ、ワラビーなど
特定分類に含まれないエキゾチックアニマルを対象とした疾患データベースです。
症状から鑑別診断候補を提示する際に使用します。
この情報は教育目的であり、診断は獣医師にご相談ください。
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import analyze_symptoms_generic, ADVICE


SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "depression": {"ja": "元気消失", "en": "Depression"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    # Skin / Integument
    "dermatitis": {"ja": "皮膚炎", "en": "Dermatitis"},
    "hair_loss": {"ja": "脱毛", "en": "Hair loss"},
    "pruritus": {"ja": "掻痒", "en": "Pruritus"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "skin_crusting": {"ja": "皮膚の痂皮", "en": "Skin crusting"},
    "skin_thickening": {"ja": "皮膚の肥厚", "en": "Skin thickening"},
    "sunburn": {"ja": "日焼け", "en": "Sunburn"},
    "abscesses": {"ja": "膿瘍", "en": "Abscesses"},
    "lumps": {"ja": "腫瘤", "en": "Lumps/masses"},
    "diamond_skin_lesions": {"ja": "菱形皮膚病変", "en": "Diamond-shaped skin lesions"},
    "urticaria": {"ja": "蕁麻疹", "en": "Urticaria/hives"},
    "wound": {"ja": "創傷", "en": "Wound"},
    # Respiratory
    "coughing": {"ja": "咳", "en": "Coughing"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal discharge"},
    "dyspnea": {"ja": "呼吸困難", "en": "Dyspnea"},
    "rapid_breathing": {"ja": "頻呼吸", "en": "Rapid breathing"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "open_mouth_breathing": {"ja": "開口呼吸", "en": "Open-mouth breathing"},
    "snout_deformity": {"ja": "吻部変形", "en": "Snout deformity"},
    # Gastrointestinal
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "bloating": {"ja": "腹部膨満", "en": "Bloating"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "rectal_prolapse": {"ja": "直腸脱", "en": "Rectal prolapse"},
    "melena": {"ja": "黒色便", "en": "Melena (dark/tarry stool)"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth grinding (bruxism)"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal pain"},
    # Musculoskeletal
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "joint_swelling": {"ja": "関節腫脹", "en": "Joint swelling"},
    "hoof_abnormality": {"ja": "蹄異常", "en": "Hoof abnormality"},
    "overgrown_hooves": {"ja": "蹄の過成長", "en": "Overgrown hooves"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to move"},
    "soft_bones": {"ja": "骨軟化", "en": "Soft bones"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    # Neurological
    "seizures": {"ja": "痙攣", "en": "Seizures"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "incoordination": {"ja": "運動失調", "en": "Incoordination"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "muscle_spasms": {"ja": "筋痙攣", "en": "Muscle spasms"},
    "opisthotonos": {"ja": "後弓反張", "en": "Opisthotonos"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "sudden_collapse": {"ja": "突然の虚脱", "en": "Sudden collapse"},
    "hypersensitivity": {"ja": "過敏症", "en": "Hypersensitivity to touch/stimuli"},
    # Urinary / Reproductive
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal discharge"},
    "dystocia": {"ja": "難産", "en": "Dystocia"},
    "mammary_swelling": {"ja": "乳腺腫脹", "en": "Mammary swelling"},
    "straining_urinate": {"ja": "排尿困難", "en": "Straining to urinate"},
    "hematuria": {"ja": "血尿", "en": "Hematuria"},
    "polyuria": {"ja": "多尿", "en": "Polyuria"},
    "polydipsia": {"ja": "多飲", "en": "Polydipsia"},
    # Eyes
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    # Dental
    "malocclusion": {"ja": "不正咬合", "en": "Malocclusion"},
    "overgrown_teeth": {"ja": "歯の過成長", "en": "Overgrown teeth"},
    "oral_lesions": {"ja": "口腔内病変", "en": "Oral lesions"},
    "difficulty_eating": {"ja": "摂食困難", "en": "Difficulty eating"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    # Other
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "self_mutilation": {"ja": "自傷行為", "en": "Self-mutilation"},
    "regurgitation": {"ja": "吐き戻し", "en": "Regurgitation"},
    "pale_mucous_membranes": {"ja": "粘膜蒼白", "en": "Pale mucous membranes"},
    "enlarged_lymph_nodes": {"ja": "リンパ節腫大", "en": "Enlarged lymph nodes"},
    "alopecia_tail": {"ja": "尾部脱毛", "en": "Tail alopecia"},
    "heat_stress": {"ja": "熱中症", "en": "Heat stress"},
    "hypothermia": {"ja": "低体温症", "en": "Hypothermia"},
    "back_pain": {"ja": "背部痛", "en": "Back pain"},
    "squealing": {"ja": "悲鳴", "en": "Squealing/vocalizing in pain"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
}


DISEASES: List[Dict[str, Any]] = [
    # ══════════════════════════════════════════════════════════════════
    # MINI PIG DISEASES
    # ══════════════════════════════════════════════════════════════════
    {
        "name": "Erysipelas",
        "name_ja": "豚丹毒",
        "symptoms": {"fever", "diamond_skin_lesions", "lameness", "joint_swelling", "lethargy", "anorexia", "sudden_death"},
        "description": "Bacterial infection by Erysipelothrix rhusiopathiae causing characteristic diamond-shaped skin lesions, arthritis, and potentially fatal septicemia in pigs.",
        "description_ja": "豚丹毒菌による細菌感染で特徴的な菱形皮膚病変、関節炎、致死的敗血症を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["血液培養", "細菌培養", "血液検査", "関節液検査"],
    },
    {
        "name": "Atrophic Rhinitis",
        "name_ja": "萎縮性鼻炎",
        "symptoms": {"sneezing", "nasal_discharge", "snout_deformity", "coughing", "dyspnea", "anorexia"},
        "description": "Progressive bacterial rhinitis (Bordetella bronchiseptica, Pasteurella multocida) causing turbinate atrophy and snout deviation.",
        "description_ja": "ボルデテラ菌等による進行性鼻炎で鼻甲介萎縮と吻部偏位を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["鼻腔スワブ培養", "X線検査", "CT検査"],
    },
    {
        "name": "Dippity Pig Syndrome",
        "name_ja": "ディッピーピッグ症候群",
        "symptoms": {"squealing", "back_pain", "skin_lesions", "skin_redness", "sudden_collapse", "reluctance_to_move"},
        "description": "Acute idiopathic condition in mini pigs causing painful oozing skin lesions along the back with sudden onset of weakness in the hindquarters.",
        "description_ja": "ミニブタに発生する急性特発性疾患で背部に有痛性浸出性皮膚病変と後躯の脱力を呈する。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "血液検査", "皮膚検査"],
    },
    {
        "name": "Porcine Stress Syndrome (Malignant Hyperthermia)",
        "name_ja": "豚ストレス症候群（悪性高熱症）",
        "symptoms": {"fever", "tremors", "muscle_spasms", "rapid_breathing", "sudden_collapse", "sudden_death"},
        "description": "Genetic disorder triggered by stress causing rapid rise in body temperature, muscle rigidity, and potentially death.",
        "description_ja": "ストレスにより誘発される遺伝性疾患で急激な体温上昇、筋硬直、突然死を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["遺伝子検査（RYR1）", "血液ガス分析", "CK測定"],
    },
    {
        "name": "Sarcoptic Mange (Porcine)",
        "name_ja": "豚疥癬",
        "symptoms": {"pruritus", "skin_crusting", "hair_loss", "skin_thickening", "dermatitis", "skin_redness"},
        "description": "Sarcoptes scabiei var. suis infestation causing intense pruritus, crusty lesions, and alopecia.",
        "description_ja": "ブタヒゼンダニの寄生による激しい掻痒、痂皮形成、脱毛。",
        "urgency": "moderate",
        "recommended_tests": ["皮膚スクレイピング", "顕微鏡検査", "皮膚生検"],
    },
    {
        "name": "Gastric Ulcers (Porcine)",
        "name_ja": "胃潰瘍（豚）",
        "symptoms": {"anorexia", "melena", "vomiting", "pale_mucous_membranes", "weakness", "teeth_grinding", "sudden_death"},
        "description": "Erosion and ulceration of the pars esophagea of the stomach, common in stressed or grain-fed pigs.",
        "description_ja": "ストレスや穀物主体の食餌に関連する胃食道部の潰瘍。",
        "urgency": "high",
        "recommended_tests": ["糞便潜血検査", "血液検査", "胃内視鏡検査"],
    },
    {
        "name": "Porcine Obesity",
        "name_ja": "豚の肥満症",
        "symptoms": {"obesity", "lethargy", "reluctance_to_move", "lameness", "dyspnea"},
        "description": "Excessive body condition from overfeeding; predisposes to arthritis, hepatic lipidosis, and cardiovascular disease.",
        "description_ja": "過剰給餌による過体重。関節炎、脂肪肝、心血管疾患の素因となる。",
        "urgency": "moderate",
        "recommended_tests": ["体重測定", "血液生化学検査", "栄養評価", "X線検査"],
    },
    {
        "name": "Sunburn (Porcine)",
        "name_ja": "日焼け（豚）",
        "symptoms": {"sunburn", "skin_redness", "skin_lesions", "skin_crusting", "squealing"},
        "description": "UV radiation damage to exposed, lightly pigmented skin in outdoor pigs.",
        "description_ja": "屋外飼育のブタにおける紫外線による淡色皮膚の損傷。",
        "urgency": "low",
        "recommended_tests": ["身体検査", "皮膚検査"],
    },
    {
        "name": "Hoof Overgrowth / Cracks (Porcine)",
        "name_ja": "蹄過成長・蹄裂（豚）",
        "symptoms": {"overgrown_hooves", "hoof_abnormality", "lameness", "reluctance_to_move"},
        "description": "Overgrowth, cracking, or infection of hooves due to improper substrate or lack of trimming.",
        "description_ja": "不適切な床材や蹄切り不足による蹄の過成長、亀裂、感染。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "蹄検査", "X線検査"],
    },
    {
        "name": "Porcine Reproductive Disorders",
        "name_ja": "豚の繁殖障害",
        "symptoms": {"vaginal_discharge", "dystocia", "mammary_swelling", "fever", "anorexia", "lethargy"},
        "description": "Reproductive issues including metritis, mastitis, dystocia, and agalactia in intact female pigs.",
        "description_ja": "未避妊の雌ブタにおける子宮炎、乳腺炎、難産、無乳症などの繁殖関連疾患。",
        "urgency": "high",
        "recommended_tests": ["超音波検査", "血液検査", "膣スワブ培養"],
    },
    {
        "name": "Porcine Pneumonia",
        "name_ja": "豚肺炎",
        "symptoms": {"coughing", "dyspnea", "nasal_discharge", "fever", "lethargy", "anorexia", "rapid_breathing"},
        "description": "Bacterial or viral pneumonia (Mycoplasma, Pasteurella, swine influenza) causing respiratory compromise.",
        "description_ja": "マイコプラズマ、パスツレラ、豚インフルエンザなどによる細菌性・ウイルス性肺炎。",
        "urgency": "high",
        "recommended_tests": ["胸部X線検査", "気管洗浄液培養", "血液検査", "PCR検査"],
    },
    {
        "name": "Tetanus (Porcine)",
        "name_ja": "破傷風（豚）",
        "symptoms": {"stiffness", "muscle_spasms", "opisthotonos", "seizures", "difficulty_eating", "hypersensitivity"},
        "description": "Clostridium tetani toxin causing progressive muscle rigidity and spasms, often from wound contamination.",
        "description_ja": "破傷風菌毒素による進行性の筋硬直と痙攣。創傷の汚染から発症する。",
        "urgency": "emergency",
        "recommended_tests": ["身体検査", "創傷検査", "血液検査"],
    },
    {
        "name": "Leptospirosis (Porcine)",
        "name_ja": "レプトスピラ症（豚）",
        "symptoms": {"fever", "jaundice", "anorexia", "lethargy", "hematuria", "vomiting", "vaginal_discharge"},
        "description": "Spirochete infection causing hepatorenal disease; zoonotic concern for owners.",
        "description_ja": "レプトスピラによる肝腎疾患。飼い主への人獣共通感染症リスクあり。",
        "urgency": "high",
        "recommended_tests": ["血清学的検査（MAT）", "PCR検査", "血液生化学検査", "尿検査"],
    },
    {
        "name": "Intestinal Parasitism (Porcine)",
        "name_ja": "腸管寄生虫症（豚）",
        "symptoms": {"diarrhea", "weight_loss", "bloating", "anorexia", "bloody_stool", "lethargy"},
        "description": "Gastrointestinal parasitism by Ascaris, Trichuris, coccidia, or other helminths.",
        "description_ja": "回虫、鞭虫、コクシジウム等の消化管寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["糞便検査", "糞便浮遊法", "顕微鏡検査"],
    },
    {
        "name": "Swine Influenza",
        "name_ja": "豚インフルエンザ",
        "symptoms": {"fever", "coughing", "nasal_discharge", "sneezing", "lethargy", "anorexia", "dyspnea"},
        "description": "Influenza A virus infection causing acute respiratory illness; zoonotic potential.",
        "description_ja": "A型インフルエンザウイルスによる急性呼吸器疾患。人獣共通感染症リスクあり。",
        "urgency": "high",
        "recommended_tests": ["鼻腔スワブPCR", "血清学的検査", "胸部X線検査"],
    },
    # ══════════════════════════════════════════════════════════════════
    # GENERAL EXOTIC MAMMAL DISEASES
    # ══════════════════════════════════════════════════════════════════
    # ── Metabolic ─────────────────────────────────────────────────────
    {
        "name": "Metabolic Bone Disease (Exotic Mammal)",
        "name_ja": "代謝性骨疾患（エキゾチック哺乳類）",
        "symptoms": {"soft_bones", "fractures", "lameness", "weakness", "lethargy", "tremors"},
        "description": "Calcium, phosphorus, or vitamin D imbalance causing skeletal deformities and pathological fractures.",
        "description_ja": "カルシウム・リン・ビタミンDの不均衡による骨格変形と病的骨折。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "X線検査", "食事内容評価"],
    },
    {
        "name": "Hepatic Lipidosis (Exotic Mammal)",
        "name_ja": "肝リピドーシス（エキゾチック哺乳類）",
        "symptoms": {"anorexia", "jaundice", "lethargy", "weight_loss", "vomiting", "depression"},
        "description": "Fatty infiltration of the liver from anorexia, obesity, or metabolic stress; common in overweight exotic mammals.",
        "description_ja": "食欲不振、肥満、代謝性ストレスによる肝臓への脂肪浸潤。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "超音波検査", "肝生検"],
    },
    {
        "name": "Diabetes Mellitus (Exotic Mammal)",
        "name_ja": "糖尿病（エキゾチック哺乳類）",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "obesity"},
        "description": "Insulin dysfunction causing hyperglycemia; seen in obese exotic mammals, especially mini pigs and raccoons.",
        "description_ja": "インスリン機能障害による高血糖症。肥満のエキゾチック哺乳類に多い。",
        "urgency": "high",
        "recommended_tests": ["血糖値測定", "フルクトサミン", "尿検査", "血液生化学検査"],
    },
    {
        "name": "Hypocalcemia (Exotic Mammal)",
        "name_ja": "低カルシウム血症（エキゾチック哺乳類）",
        "symptoms": {"tremors", "seizures", "weakness", "muscle_spasms", "lethargy", "anorexia"},
        "description": "Low blood calcium causing neuromuscular dysfunction, often in lactating or poorly supplemented animals.",
        "description_ja": "血中カルシウム低下による神経筋機能障害。授乳期やサプリメント不足の個体に多い。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "イオン化カルシウム測定"],
    },
    # ── Respiratory ───────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection (Exotic Mammal)",
        "name_ja": "上部気道感染症（エキゾチック哺乳類）",
        "symptoms": {"sneezing", "nasal_discharge", "eye_discharge", "lethargy", "anorexia", "wheezing"},
        "description": "Bacterial or viral infection of the upper respiratory tract; common under stress or poor ventilation.",
        "description_ja": "上部気道の細菌性・ウイルス性感染。ストレスや換気不良で多発。",
        "urgency": "moderate",
        "recommended_tests": ["鼻腔スワブ培養", "血液検査", "X線検査"],
    },
    {
        "name": "Pneumonia (Exotic Mammal)",
        "name_ja": "肺炎（エキゾチック哺乳類）",
        "symptoms": {"coughing", "dyspnea", "rapid_breathing", "fever", "lethargy", "anorexia", "nasal_discharge"},
        "description": "Lower respiratory infection from bacteria, fungi, or viruses causing consolidation of lung tissue.",
        "description_ja": "細菌、真菌、ウイルスによる下気道感染で肺実質の硬化を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["胸部X線検査", "気管洗浄液検査", "血液検査", "培養感受性試験"],
    },
    # ── Gastrointestinal ──────────────────────────────────────────────
    {
        "name": "Gastrointestinal Stasis",
        "name_ja": "消化管うっ滞",
        "symptoms": {"anorexia", "bloating", "constipation", "lethargy", "teeth_grinding", "abdominal_pain"},
        "description": "Reduced or absent GI motility from stress, pain, diet, or dehydration; common across exotic mammals.",
        "description_ja": "ストレス、疼痛、食事、脱水による消化管運動の低下または停止。",
        "urgency": "high",
        "recommended_tests": ["腹部X線検査", "身体検査", "血液検査"],
    },
    {
        "name": "Gastric Dilatation",
        "name_ja": "胃拡張",
        "symptoms": {"bloating", "dyspnea", "abdominal_pain", "lethargy", "sudden_death"},
        "description": "Acute distension of the stomach with gas or fluid, potentially life-threatening.",
        "description_ja": "ガスや液体による急性胃拡張。生命を脅かす可能性がある。",
        "urgency": "emergency",
        "recommended_tests": ["腹部X線検査", "身体検査", "血液ガス分析"],
    },
    {
        "name": "Enteritis / Colitis (Exotic Mammal)",
        "name_ja": "腸炎・大腸炎（エキゾチック哺乳類）",
        "symptoms": {"diarrhea", "bloody_stool", "anorexia", "dehydration", "lethargy", "abdominal_pain"},
        "description": "Inflammation of the intestinal tract from infection, dietary issues, or stress.",
        "description_ja": "感染、食事の問題、ストレスによる腸管の炎症。",
        "urgency": "high",
        "recommended_tests": ["糞便検査", "糞便培養", "血液検査", "腹部X線検査"],
    },
    {
        "name": "Intestinal Parasitism (Exotic Mammal)",
        "name_ja": "腸管寄生虫症（エキゾチック哺乳類）",
        "symptoms": {"diarrhea", "weight_loss", "bloating", "anorexia", "lethargy"},
        "description": "Helminth or protozoal infection of the gastrointestinal tract.",
        "description_ja": "蠕虫または原虫による消化管寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["糞便浮遊法", "糞便塗抹検査", "顕微鏡検査"],
    },
    {
        "name": "Rectal Prolapse (Exotic Mammal)",
        "name_ja": "直腸脱（エキゾチック哺乳類）",
        "symptoms": {"rectal_prolapse", "bloody_stool", "diarrhea", "lethargy"},
        "description": "Protrusion of rectal tissue from the anus, often secondary to diarrhea, parasites, or straining.",
        "description_ja": "下痢、寄生虫、いきみに続発する直腸組織の肛門からの脱出。",
        "urgency": "high",
        "recommended_tests": ["身体検査", "糞便検査", "血液検査"],
    },
    # ── Dental ────────────────────────────────────────────────────────
    {
        "name": "Dental Malocclusion (Exotic Mammal)",
        "name_ja": "不正咬合（エキゾチック哺乳類）",
        "symptoms": {"malocclusion", "overgrown_teeth", "drooling", "difficulty_eating", "weight_loss", "anorexia"},
        "description": "Misalignment or overgrowth of teeth, especially in rodents, lagomorphs, and prairie dogs with continuously growing teeth.",
        "description_ja": "歯の不整列または過成長。常生歯を持つ齧歯類やプレーリードッグに多い。",
        "urgency": "moderate",
        "recommended_tests": ["口腔内検査", "頭部X線検査", "CT検査"],
    },
    {
        "name": "Dental Abscess (Exotic Mammal)",
        "name_ja": "歯根膿瘍（エキゾチック哺乳類）",
        "symptoms": {"facial_swelling", "abscesses", "anorexia", "drooling", "difficulty_eating", "eye_discharge"},
        "description": "Periapical infection causing facial swelling and pain; may extend to retrobulbar space.",
        "description_ja": "歯根周囲の感染による顔面腫脹と疼痛。眼窩後方へ波及することもある。",
        "urgency": "high",
        "recommended_tests": ["頭部X線検査", "CT検査", "細菌培養", "血液検査"],
    },
    # ── Reproductive ──────────────────────────────────────────────────
    {
        "name": "Pyometra (Exotic Mammal)",
        "name_ja": "子宮蓄膿症（エキゾチック哺乳類）",
        "symptoms": {"vaginal_discharge", "fever", "lethargy", "anorexia", "bloating", "polydipsia", "polyuria"},
        "description": "Bacterial infection of the uterus with pus accumulation; potentially fatal without surgery.",
        "description_ja": "子宮内の細菌感染による膿の蓄積。外科手術なしでは致命的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["超音波検査", "血液検査", "腹部X線検査"],
    },
    {
        "name": "Dystocia (Exotic Mammal)",
        "name_ja": "難産（エキゾチック哺乳類）",
        "symptoms": {"dystocia", "lethargy", "abdominal_pain", "vaginal_discharge", "depression"},
        "description": "Difficulty during parturition requiring veterinary intervention.",
        "description_ja": "分娩時の困難。獣医師の介入が必要。",
        "urgency": "emergency",
        "recommended_tests": ["超音波検査", "X線検査", "身体検査"],
    },
    {
        "name": "Mammary Tumors (Exotic Mammal)",
        "name_ja": "乳腺腫瘍（エキゾチック哺乳類）",
        "symptoms": {"mammary_swelling", "lumps", "weight_loss", "lethargy"},
        "description": "Benign or malignant mammary neoplasia; common in intact female exotic mammals.",
        "description_ja": "未避妊の雌エキゾチック哺乳類に多い良性または悪性の乳腺腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["細胞診", "組織生検", "胸部X線検査", "超音波検査"],
    },
    # ── Neurological ──────────────────────────────────────────────────
    {
        "name": "Baylisascaris Encephalitis",
        "name_ja": "バイリスアスカリス脳炎",
        "symptoms": {"incoordination", "head_tilt", "circling", "seizures", "paralysis", "lethargy"},
        "description": "Larval migrans of the raccoon roundworm (Baylisascaris procyonis) causing severe CNS disease; zoonotic risk.",
        "description_ja": "アライグマ回虫の幼虫移行による重篤な中枢神経疾患。人獣共通感染症リスクあり。",
        "urgency": "emergency",
        "recommended_tests": ["血液検査", "血清学的検査", "MRI検査", "糞便検査"],
    },
    {
        "name": "Canine Distemper (Raccoon/Skunk)",
        "name_ja": "犬ジステンパー（アライグマ・スカンク）",
        "symptoms": {"nasal_discharge", "eye_discharge", "coughing", "seizures", "incoordination", "lethargy", "anorexia", "fever"},
        "description": "Paramyxovirus infection causing respiratory, GI, and neurological disease in raccoons, skunks, and other wildlife.",
        "description_ja": "パラミクソウイルスによるアライグマ・スカンク等の呼吸器・消化器・神経疾患。",
        "urgency": "emergency",
        "recommended_tests": ["PCR検査", "血清学的検査", "血液検査"],
    },
    {
        "name": "Rabies (Exotic Mammal)",
        "name_ja": "狂犬病（エキゾチック哺乳類）",
        "symptoms": {"aggression", "paralysis", "incoordination", "seizures", "drooling", "self_mutilation", "sudden_death"},
        "description": "Fatal lyssavirus infection affecting the CNS; major zoonotic concern. Reportable disease.",
        "description_ja": "中枢神経系を侵す致死的リッサウイルス感染症。重大な人獣共通感染症。届出疾病。",
        "urgency": "emergency",
        "recommended_tests": ["脳組織検査（死後）", "蛍光抗体法"],
    },
    {
        "name": "Vestibular Disease (Exotic Mammal)",
        "name_ja": "前庭疾患（エキゾチック哺乳類）",
        "symptoms": {"head_tilt", "circling", "incoordination", "lethargy", "anorexia"},
        "description": "Inner ear or CNS disorder causing balance disturbance; may be infectious, traumatic, or idiopathic.",
        "description_ja": "内耳またはCNSの障害によるバランス異常。感染性、外傷性、特発性がある。",
        "urgency": "moderate",
        "recommended_tests": ["神経学的検査", "耳鏡検査", "X線検査", "CT/MRI検査"],
    },
    # ── Dermatological ────────────────────────────────────────────────
    {
        "name": "Dermatophytosis / Ringworm (Exotic Mammal)",
        "name_ja": "皮膚糸状菌症（エキゾチック哺乳類）",
        "symptoms": {"hair_loss", "skin_crusting", "skin_lesions", "pruritus"},
        "description": "Fungal infection of the skin by Trichophyton or Microsporum spp.; zoonotic potential.",
        "description_ja": "白癬菌等の皮膚糸状菌による皮膚感染症。人獣共通感染症リスクあり。",
        "urgency": "moderate",
        "recommended_tests": ["ウッド灯検査", "真菌培養", "皮膚スクレイピング", "DTM培地"],
    },
    {
        "name": "External Parasites (Mites/Fleas/Ticks)",
        "name_ja": "外部寄生虫（ダニ・ノミ・マダニ）",
        "symptoms": {"pruritus", "hair_loss", "dermatitis", "skin_crusting", "skin_redness", "lethargy"},
        "description": "Infestation by ectoparasites causing dermatitis, pruritus, and potential disease transmission.",
        "description_ja": "外部寄生虫の寄生による皮膚炎、掻痒、疾病伝播のリスク。",
        "urgency": "moderate",
        "recommended_tests": ["皮膚スクレイピング", "顕微鏡検査", "被毛検査"],
    },
    {
        "name": "Subcutaneous Abscess (Exotic Mammal)",
        "name_ja": "皮下膿瘍（エキゾチック哺乳類）",
        "symptoms": {"abscesses", "swelling", "fever", "lethargy", "wound"},
        "description": "Localized bacterial infection forming walled-off pus pockets; common from bite wounds or foreign bodies.",
        "description_ja": "咬傷や異物から発生する限局性細菌感染による膿瘍形成。",
        "urgency": "moderate",
        "recommended_tests": ["細胞診", "細菌培養", "感受性試験", "血液検査"],
    },
    {
        "name": "Contact Dermatitis (Exotic Mammal)",
        "name_ja": "接触性皮膚炎（エキゾチック哺乳類）",
        "symptoms": {"dermatitis", "skin_redness", "pruritus", "hair_loss", "skin_lesions"},
        "description": "Skin inflammation from contact with irritants such as bedding, cleaning chemicals, or substrates.",
        "description_ja": "床材、洗浄剤、基材などの刺激物との接触による皮膚炎。",
        "urgency": "low",
        "recommended_tests": ["身体検査", "皮膚検査", "飼育環境評価"],
    },
    # ── Nutritional ───────────────────────────────────────────────────
    {
        "name": "Vitamin C Deficiency (Scurvy-like)",
        "name_ja": "ビタミンC欠乏症",
        "symptoms": {"weakness", "joint_swelling", "lameness", "hair_loss", "lethargy", "anorexia"},
        "description": "Ascorbic acid deficiency causing connective tissue and vascular dysfunction; relevant for guinea pig-like exotics.",
        "description_ja": "アスコルビン酸欠乏による結合組織・血管機能障害。",
        "urgency": "moderate",
        "recommended_tests": ["血液検査", "食事内容評価"],
    },
    {
        "name": "Vitamin A Deficiency (Exotic Mammal)",
        "name_ja": "ビタミンA欠乏症（エキゾチック哺乳類）",
        "symptoms": {"skin_lesions", "eye_discharge", "cloudy_eyes", "anorexia", "weakness"},
        "description": "Hypovitaminosis A causing epithelial metaplasia, ocular disease, and immunosuppression.",
        "description_ja": "ビタミンA不足による上皮化生、眼疾患、免疫抑制。",
        "urgency": "moderate",
        "recommended_tests": ["血液検査", "食事内容評価", "眼科検査"],
    },
    {
        "name": "Iron Storage Disease (Hemochromatosis)",
        "name_ja": "鉄蓄積症（ヘモクロマトーシス）",
        "symptoms": {"lethargy", "weight_loss", "anorexia", "jaundice", "edema", "dyspnea"},
        "description": "Excessive iron deposition in organs, particularly the liver; seen in some exotic species on inappropriate diets.",
        "description_ja": "不適切な食事による臓器、特に肝臓への過剰な鉄沈着。",
        "urgency": "high",
        "recommended_tests": ["血清鉄・フェリチン測定", "肝生検", "血液生化学検査"],
    },
    # ── Environmental Stress ──────────────────────────────────────────
    {
        "name": "Heat Stress / Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"heat_stress", "rapid_breathing", "lethargy", "open_mouth_breathing", "seizures", "sudden_death"},
        "description": "Hyperthermia from high ambient temperature exceeding thermoregulatory capacity.",
        "description_ja": "環境温度が体温調節能力を超えることによる高体温症。",
        "urgency": "emergency",
        "recommended_tests": ["体温測定", "血液ガス分析", "血液検査"],
    },
    {
        "name": "Hypothermia / Cold Stress",
        "name_ja": "低温ストレス・低体温症",
        "symptoms": {"hypothermia", "lethargy", "weakness", "reluctance_to_move", "anorexia"},
        "description": "Dangerously low body temperature from cold exposure or debilitation.",
        "description_ja": "寒冷曝露や衰弱による危険な低体温。",
        "urgency": "high",
        "recommended_tests": ["体温測定", "血液検査", "血糖値測定"],
    },
    {
        "name": "Obesity (Exotic Mammal)",
        "name_ja": "肥満症（エキゾチック哺乳類）",
        "symptoms": {"obesity", "lethargy", "reluctance_to_move", "dyspnea", "lameness"},
        "description": "Excessive body fat from overfeeding and inadequate exercise; predisposes to multiple organ diseases.",
        "description_ja": "過剰給餌と運動不足による過体重。多臓器疾患の素因となる。",
        "urgency": "moderate",
        "recommended_tests": ["体重測定", "BCS評価", "血液生化学検査", "栄養評価"],
    },
    # ── Tumors ────────────────────────────────────────────────────────
    {
        "name": "Lymphoma (Exotic Mammal)",
        "name_ja": "リンパ腫（エキゾチック哺乳類）",
        "symptoms": {"enlarged_lymph_nodes", "weight_loss", "lethargy", "anorexia", "edema"},
        "description": "Malignant proliferation of lymphoid tissue; relatively common neoplasia in exotic mammals.",
        "description_ja": "リンパ組織の悪性増殖。エキゾチック哺乳類に比較的多い腫瘍。",
        "urgency": "high",
        "recommended_tests": ["リンパ節細胞診", "血液検査", "超音波検査", "X線検査"],
    },
    {
        "name": "Cutaneous Neoplasia (Exotic Mammal)",
        "name_ja": "皮膚腫瘍（エキゾチック哺乳類）",
        "symptoms": {"lumps", "skin_lesions", "hair_loss", "weight_loss"},
        "description": "Benign or malignant skin tumors including fibrosarcoma, squamous cell carcinoma, and papilloma.",
        "description_ja": "線維肉腫、扁平上皮癌、乳頭腫などの良性または悪性皮膚腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["細胞診", "組織生検", "X線検査"],
    },
    # ── Infectious ────────────────────────────────────────────────────
    {
        "name": "Plague (Prairie Dog)",
        "name_ja": "ペスト（プレーリードッグ）",
        "symptoms": {"fever", "enlarged_lymph_nodes", "lethargy", "anorexia", "dyspnea", "sudden_death"},
        "description": "Yersinia pestis infection; highly fatal in prairie dogs with zoonotic risk. Reportable disease.",
        "description_ja": "ペスト菌感染。プレーリードッグでは致死率が高く、人獣共通感染症リスクあり。届出疾病。",
        "urgency": "emergency",
        "recommended_tests": ["血液培養", "リンパ節穿刺", "PCR検査", "血清学的検査"],
    },
    {
        "name": "Tularemia (Exotic Mammal)",
        "name_ja": "野兎病（エキゾチック哺乳類）",
        "symptoms": {"fever", "enlarged_lymph_nodes", "lethargy", "anorexia", "sudden_death"},
        "description": "Francisella tularensis infection causing acute febrile illness; zoonotic risk from handling infected animals.",
        "description_ja": "野兎病菌による急性発熱性疾患。感染動物の取り扱いによる人獣共通感染症リスクあり。",
        "urgency": "emergency",
        "recommended_tests": ["血液培養", "血清学的検査", "PCR検査"],
    },
    {
        "name": "Salmonellosis (Exotic Mammal)",
        "name_ja": "サルモネラ症（エキゾチック哺乳類）",
        "symptoms": {"diarrhea", "fever", "anorexia", "lethargy", "dehydration", "bloody_stool"},
        "description": "Bacterial infection causing enteritis and potential septicemia; zoonotic concern.",
        "description_ja": "サルモネラ菌による腸炎および敗血症のリスク。人獣共通感染症。",
        "urgency": "high",
        "recommended_tests": ["糞便培養", "血液検査", "感受性試験"],
    },
    # ── Wallaby / Macropod-specific ───────────────────────────────────
    {
        "name": "Lumpy Jaw (Macropod)",
        "name_ja": "顎骨骨髄炎（マクロポッド）",
        "symptoms": {"facial_swelling", "difficulty_eating", "drooling", "weight_loss", "anorexia", "oral_lesions"},
        "description": "Progressive mandibular or maxillary osteomyelitis in wallabies and kangaroos; often fatal if untreated.",
        "description_ja": "ワラビーやカンガルーにおける進行性の顎骨骨髄炎。未治療では致死的。",
        "urgency": "high",
        "recommended_tests": ["頭部X線検査", "CT検査", "細菌培養", "血液検査"],
    },
    {
        "name": "Stress Myopathy (Capture Myopathy)",
        "name_ja": "ストレス性ミオパチー（捕獲ミオパチー）",
        "symptoms": {"weakness", "reluctance_to_move", "muscle_wasting", "sudden_collapse", "sudden_death", "hematuria"},
        "description": "Rhabdomyolysis from extreme stress or physical exertion during capture or transport; common in wallabies and other wildlife.",
        "description_ja": "捕獲や輸送時の極度のストレスによる横紋筋融解症。ワラビー等の野生動物に多い。",
        "urgency": "emergency",
        "recommended_tests": ["CK/AST測定", "血液検査", "尿検査（ミオグロビン）"],
    },
    {
        "name": "Toxoplasmosis (Wallaby/Marsupial)",
        "name_ja": "トキソプラズマ症（有袋類）",
        "symptoms": {"lethargy", "anorexia", "dyspnea", "incoordination", "seizures", "sudden_death"},
        "description": "Toxoplasma gondii infection causing acute fatal disease in macropods and other marsupials.",
        "description_ja": "トキソプラズマ原虫による有袋類の急性致死性疾患。",
        "urgency": "emergency",
        "recommended_tests": ["血清学的検査", "PCR検査", "組織病理検査"],
    },
    # ── Urinary ───────────────────────────────────────────────────────
    {
        "name": "Urolithiasis (Exotic Mammal)",
        "name_ja": "尿路結石症（エキゾチック哺乳類）",
        "symptoms": {"straining_urinate", "hematuria", "abdominal_pain", "lethargy", "anorexia"},
        "description": "Formation of urinary calculi causing obstruction and pain; diet-related in many species.",
        "description_ja": "食事に関連する尿路結石の形成による閉塞と疼痛。",
        "urgency": "high",
        "recommended_tests": ["尿検査", "腹部X線検査", "超音波検査", "血液検査"],
    },
    {
        "name": "Renal Disease (Exotic Mammal)",
        "name_ja": "腎疾患（エキゾチック哺乳類）",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "anorexia", "dehydration"},
        "description": "Acute or chronic kidney dysfunction from infection, toxins, or age-related degeneration.",
        "description_ja": "感染、毒素、加齢変性による急性または慢性の腎機能障害。",
        "urgency": "high",
        "recommended_tests": ["血液生化学検査", "尿検査", "超音波検査"],
    },
    # ── Miscellaneous ─────────────────────────────────────────────────
    {
        "name": "Pododermatitis (Bumblefoot)",
        "name_ja": "趾瘤症（バンブルフット）",
        "symptoms": {"lameness", "skin_lesions", "swelling", "reluctance_to_move"},
        "description": "Chronic pressure sore on the plantar surface of the feet; common in overweight or cage-housed exotic mammals.",
        "description_ja": "足裏の慢性圧迫潰瘍。肥満やケージ飼育のエキゾチック哺乳類に多い。",
        "urgency": "moderate",
        "recommended_tests": ["身体検査", "X線検査", "細菌培養"],
    },
    {
        "name": "Adrenal Disease (Exotic Mammal)",
        "name_ja": "副腎疾患（エキゾチック哺乳類）",
        "symptoms": {"hair_loss", "alopecia_tail", "pruritus", "lethargy", "aggression", "polyuria", "polydipsia"},
        "description": "Adrenal hyperplasia or neoplasia causing hormonal imbalances; common in ferret-like exotics.",
        "description_ja": "副腎過形成または腫瘍によるホルモン異常。フェレット様エキゾチック動物に多い。",
        "urgency": "moderate",
        "recommended_tests": ["ホルモン検査", "超音波検査", "血液検査"],
    },
    {
        "name": "Heart Disease (Exotic Mammal)",
        "name_ja": "心疾患（エキゾチック哺乳類）",
        "symptoms": {"dyspnea", "lethargy", "edema", "sudden_collapse", "coughing", "weakness"},
        "description": "Cardiomyopathy or valvular disease causing congestive heart failure.",
        "description_ja": "心筋症や弁膜疾患によるうっ血性心不全。",
        "urgency": "high",
        "recommended_tests": ["胸部X線検査", "心エコー検査", "心電図", "血液検査"],
    },
]


def analyze_symptoms(
    symptoms: List[str],
    age_stage: str = "",
    breed: str | None = None,
) -> Dict[str, Any]:
    """その他エキゾチック動物用の鑑別診断エンジン。

    Args:
        symptoms: ユーザーが報告した症状のリスト
        age_stage: 任意の年齢/ライフステージ情報
        breed: 任意の種名情報

    Returns:
        辞書形式の分析結果
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
