"""Ferret disease dictionary and analysis module.

Comprehensive database covering endocrine, gastrointestinal, cardiac,
respiratory, oncological, dermatological, urinary, reproductive,
musculoskeletal, neurological, infectious, dental, parasitic, metabolic
and hematological conditions commonly seen in domestic ferrets.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic


DISEASES: List[Dict[str, Any]] = [
    # ── Endocrine ──────────────────────────────────────────────────────
    {
        "name": "Insulinoma",
        "name_ja": "インスリノーマ",
        "symptoms": {"lethargy", "seizures", "collapse", "hypoglycemia", "drooling", "hind_leg_weakness", "weight_loss", "pawing_at_mouth"},
        "description": "Extremely common pancreatic beta-cell tumor causing episodic hypoglycemia, weakness, and seizures.",
        "description_ja": "膵臓のβ細胞腫瘍により低血糖が繰り返し起こり、虚脱や痙攣がみられます。フェレットで非常に多い疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "insulin_level", "abdominal_ultrasound"],
    },
    {
        "name": "Adrenal Disease",
        "name_ja": "副腎疾患",
        "symptoms": {"hair_loss", "itching", "vulvar_swelling", "aggression", "muscle_wasting", "excessive_grooming", "weight_loss", "thinning_skin"},
        "description": "Extremely common condition where adrenal glands overproduce sex hormones, causing bilateral symmetric alopecia.",
        "description_ja": "副腎からの性ホルモン過剰分泌により左右対称の脱毛やかゆみが起こります。フェレットで非常に多い疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "ultrasound", "adrenal_panel"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "lethargy", "cataracts"},
        "description": "Rare endocrine disorder with impaired insulin production or resistance, causing hyperglycemia.",
        "description_ja": "インスリン分泌不全や抵抗性により高血糖となる内分泌疾患です。フェレットではまれです。",
        "urgency": "moderate",
        "recommended_tests": ["blood_glucose", "fructosamine", "urinalysis"],
    },
    {
        "name": "Hyperadrenocorticism (Cushing's)",
        "name_ja": "副腎皮質機能亢進症（クッシング症候群）",
        "symptoms": {"hair_loss", "pot_belly", "muscle_wasting", "excessive_thirst", "lethargy"},
        "description": "Excess cortisol production causing characteristic signs including abdominal distension and hair loss.",
        "description_ja": "副腎からのコルチゾール過剰産生により腹部膨満や脱毛がみられます。",
        "urgency": "moderate",
        "recommended_tests": ["cortisol_test", "ultrasound", "acth_stimulation"],
    },
    # ── Gastrointestinal ───────────────────────────────────────────────
    {
        "name": "GI Foreign Body",
        "name_ja": "消化管異物",
        "symptoms": {"vomiting", "appetite_loss", "lethargy", "abdominal_pain", "diarrhea", "dehydration", "teeth_grinding"},
        "description": "Ferrets commonly ingest rubber and foam objects causing GI obstruction; a surgical emergency.",
        "description_ja": "ゴムやスポンジなどの異物を飲み込み消化管閉塞を起こします。外科的緊急疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "barium_study"],
    },
    {
        "name": "Helicobacter Mustelae Gastritis",
        "name_ja": "ヘリコバクター胃炎",
        "symptoms": {"appetite_loss", "vomiting", "black_tarry_stool", "weight_loss", "teeth_grinding", "drooling"},
        "description": "Nearly all ferrets carry Helicobacter mustelae; stress or immunosuppression can trigger clinical gastritis and ulcers.",
        "description_ja": "ほぼ全てのフェレットがヘリコバクター菌を保有しており、ストレス等で胃炎・胃潰瘍を発症します。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_test", "gastric_biopsy", "cbc"],
    },
    {
        "name": "Inflammatory Bowel Disease (IBD)",
        "name_ja": "炎症性腸疾患（IBD）",
        "symptoms": {"diarrhea", "weight_loss", "appetite_loss", "vomiting", "mucoid_stool", "lethargy"},
        "description": "Chronic infiltration of inflammatory cells into the intestinal wall causing malabsorption.",
        "description_ja": "腸壁への炎症細胞浸潤により慢性的な下痢や体重減少がみられます。",
        "urgency": "moderate",
        "recommended_tests": ["intestinal_biopsy", "cbc", "fecal_test", "abdominal_ultrasound"],
    },
    {
        "name": "Eosinophilic Enteritis",
        "name_ja": "好酸球性腸炎",
        "symptoms": {"diarrhea", "weight_loss", "appetite_loss", "thickened_intestines", "lethargy"},
        "description": "Eosinophilic infiltration of the GI tract causing chronic diarrhea and wasting, common in young ferrets.",
        "description_ja": "好酸球の消化管浸潤による慢性下痢と削痩がみられ、若いフェレットに多いです。",
        "urgency": "moderate",
        "recommended_tests": ["intestinal_biopsy", "cbc", "fecal_test"],
    },
    {
        "name": "Megaesophagus",
        "name_ja": "巨大食道症",
        "symptoms": {"regurgitation", "weight_loss", "coughing", "aspiration_pneumonia_signs", "appetite_loss"},
        "description": "Dilation and hypomotility of the esophagus leading to regurgitation and risk of aspiration pneumonia.",
        "description_ja": "食道の拡張と運動低下により吐出が起こり、誤嚥性肺炎のリスクがあります。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "barium_swallow", "fluoroscopy"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"rectal_protrusion", "straining_to_defecate", "bloody_stool", "diarrhea"},
        "description": "Protrusion of rectal tissue, often secondary to chronic diarrhea or straining.",
        "description_ja": "慢性下痢やいきみにより直腸組織が脱出します。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_test"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"appetite_loss", "lethargy", "jaundice", "weight_loss", "vomiting", "diarrhea"},
        "description": "Fat accumulation in liver cells due to anorexia or metabolic stress; can be fatal if untreated.",
        "description_ja": "食欲不振や代謝ストレスにより肝臓に脂肪が蓄積し、重篤化することがあります。",
        "urgency": "high",
        "recommended_tests": ["liver_enzymes", "abdominal_ultrasound", "liver_biopsy"],
    },
    {
        "name": "Coccidia (GI)",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "bloody_stool", "dehydration", "weight_loss", "lethargy", "rectal_prolapse"},
        "description": "Protozoal infection of the intestines, especially in young or immunocompromised ferrets.",
        "description_ja": "原虫による腸管感染症で、若齢や免疫低下のフェレットに多くみられます。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Epizootic Catarrhal Enteritis (ECE / Green Slime Disease)",
        "name_ja": "流行性カタル性腸炎（ECE）",
        "symptoms": {"green_diarrhea", "mucoid_stool", "appetite_loss", "lethargy", "dehydration", "vomiting", "weight_loss"},
        "description": "Highly contagious coronavirus causing profuse green mucoid diarrhea; can be fatal in older ferrets.",
        "description_ja": "コロナウイルスによる伝染性腸炎で、緑色の粘液性下痢が特徴です。高齢フェレットでは致死的になり得ます。",
        "urgency": "high",
        "recommended_tests": ["fecal_test", "cbc", "biochemistry"],
    },
    {
        "name": "Gastric Ulcer",
        "name_ja": "胃潰瘍",
        "symptoms": {"black_tarry_stool", "appetite_loss", "vomiting", "teeth_grinding", "drooling", "abdominal_pain", "lethargy"},
        "description": "Ulceration of the gastric lining, often associated with Helicobacter or stress.",
        "description_ja": "ヘリコバクター菌やストレスに関連した胃粘膜の潰瘍形成です。",
        "urgency": "high",
        "recommended_tests": ["fecal_occult_blood", "gastric_biopsy", "cbc"],
    },
    # ── Cardiac ────────────────────────────────────────────────────────
    {
        "name": "Dilated Cardiomyopathy (DCM)",
        "name_ja": "拡張型心筋症（DCM）",
        "symptoms": {"lethargy", "coughing", "difficulty_breathing", "exercise_intolerance", "weight_loss", "abdominal_distension", "hind_leg_weakness"},
        "description": "Very common heart disease in ferrets; the heart muscle weakens and chambers dilate, reducing cardiac output.",
        "description_ja": "フェレットで非常に多い心疾患で、心筋が弱まり心腔が拡大して心拍出量が低下します。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "ecg"],
    },
    {
        "name": "Hypertrophic Cardiomyopathy (HCM)",
        "name_ja": "肥大型心筋症（HCM）",
        "symptoms": {"lethargy", "difficulty_breathing", "exercise_intolerance", "heart_murmur", "collapse"},
        "description": "Thickening of the heart muscle reducing ventricular filling; less common than DCM in ferrets.",
        "description_ja": "心筋の肥厚により心室の充満が障害される心疾患です。DCMより頻度は低いです。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "ecg"],
    },
    {
        "name": "Valvular Heart Disease",
        "name_ja": "弁膜症",
        "symptoms": {"heart_murmur", "lethargy", "coughing", "exercise_intolerance", "difficulty_breathing"},
        "description": "Degeneration of heart valves causing regurgitation and progressive heart failure.",
        "description_ja": "心臓弁の変性により逆流が起こり、進行性の心不全を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["echocardiography", "chest_xray"],
    },
    {
        "name": "Heartworm Disease",
        "name_ja": "フィラリア症",
        "symptoms": {"coughing", "difficulty_breathing", "lethargy", "exercise_intolerance", "collapse", "abdominal_distension"},
        "description": "Even a single heartworm can be fatal in ferrets due to their small heart size.",
        "description_ja": "フェレットは心臓が小さいため、一匹のフィラリアでも致死的になり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["heartworm_antigen_test", "chest_xray", "echocardiography"],
    },
    # ── Respiratory ────────────────────────────────────────────────────
    {
        "name": "Influenza (Human Flu)",
        "name_ja": "インフルエンザ",
        "symptoms": {"sneezing", "nasal_discharge", "lethargy", "fever", "appetite_loss", "coughing", "watery_eyes"},
        "description": "Ferrets are highly susceptible to human influenza viruses; transmission occurs bidirectionally.",
        "description_ja": "フェレットはヒトインフルエンザウイルスに感受性が高く、双方向に感染します。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_influenza", "chest_xray", "physical_exam"],
    },
    {
        "name": "Bacterial Pneumonia",
        "name_ja": "細菌性肺炎",
        "symptoms": {"difficulty_breathing", "coughing", "nasal_discharge", "fever", "lethargy", "appetite_loss"},
        "description": "Bacterial lung infection, often secondary to influenza or aspiration.",
        "description_ja": "インフルエンザや誤嚥に続発することが多い細菌性の肺感染症です。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "cbc", "culture_sensitivity"],
    },
    {
        "name": "Upper Respiratory Infection (URI)",
        "name_ja": "上部気道感染症",
        "symptoms": {"sneezing", "nasal_discharge", "watery_eyes", "lethargy", "appetite_loss"},
        "description": "Viral or bacterial infection of the upper airways causing sneezing and discharge.",
        "description_ja": "ウイルスまたは細菌による上気道の感染で、くしゃみや鼻汁がみられます。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "nasal_swab"],
    },
    {
        "name": "Pleural Effusion",
        "name_ja": "胸水",
        "symptoms": {"difficulty_breathing", "lethargy", "exercise_intolerance", "cyanosis", "appetite_loss"},
        "description": "Fluid accumulation in the chest cavity compressing the lungs; may be cardiac or neoplastic in origin.",
        "description_ja": "胸腔内に液体が貯留し肺を圧迫します。心臓疾患や腫瘍が原因となることが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "thoracocentesis", "fluid_analysis", "echocardiography"],
    },
    # ── Oncological ────────────────────────────────────────────────────
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"lymph_node_enlargement", "weight_loss", "lethargy", "appetite_loss", "difficulty_breathing", "diarrhea", "splenomegaly"},
        "description": "Very common cancer in ferrets; can be lymphocytic or lymphoblastic, affecting multiple organs.",
        "description_ja": "フェレットで非常に多い悪性腫瘍で、全身のリンパ組織に影響を及ぼします。",
        "urgency": "high",
        "recommended_tests": ["lymph_node_biopsy", "cbc", "chest_xray", "abdominal_ultrasound"],
    },
    {
        "name": "Adrenal Tumor (Adenoma / Adenocarcinoma)",
        "name_ja": "副腎腫瘍（腺腫・腺癌）",
        "symptoms": {"hair_loss", "vulvar_swelling", "aggression", "prostatic_enlargement", "muscle_wasting", "itching"},
        "description": "Neoplastic growth of the adrenal gland causing hormonal imbalances; very common in ferrets over 3 years.",
        "description_ja": "副腎の腫瘍性増殖によりホルモン異常が起こります。3歳以上のフェレットで非常に多いです。",
        "urgency": "moderate",
        "recommended_tests": ["adrenal_panel", "ultrasound", "hormone_panel"],
    },
    {
        "name": "Chordoma",
        "name_ja": "脊索腫",
        "symptoms": {"tail_mass", "swelling", "pain", "difficulty_defecating"},
        "description": "A slow-growing cartilaginous tumor typically found at the tip of the tail in ferrets.",
        "description_ja": "フェレットの尾端に発生しやすい軟骨性の緩徐に増殖する腫瘍です。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "xray"],
    },
    {
        "name": "Mast Cell Tumor (Cutaneous)",
        "name_ja": "肥満細胞腫（皮膚型）",
        "symptoms": {"skin_nodules", "itching", "redness", "skin_crusting"},
        "description": "Common benign skin tumor in ferrets appearing as raised, often itchy nodules.",
        "description_ja": "フェレットに多い良性の皮膚腫瘍で、かゆみを伴う隆起した結節として現れます。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy"],
    },
    {
        "name": "Skin Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"skin_mass", "ulcerated_skin_lesion", "weight_loss", "lethargy"},
        "description": "Malignant skin tumor that may ulcerate; less common but requires prompt treatment.",
        "description_ja": "潰瘍化することのある悪性皮膚腫瘍で、早期の治療が必要です。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "chest_xray", "fine_needle_aspirate"],
    },
    {
        "name": "Sebaceous Gland Tumor",
        "name_ja": "皮脂腺腫瘍",
        "symptoms": {"skin_nodules", "skin_mass"},
        "description": "Benign growths arising from sebaceous glands, common in older ferrets.",
        "description_ja": "皮脂腺由来の良性腫瘍で、高齢フェレットに多くみられます。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy"],
    },
    {
        "name": "Basal Cell Tumor",
        "name_ja": "基底細胞腫",
        "symptoms": {"skin_nodules", "skin_mass", "hair_loss"},
        "description": "Generally benign skin neoplasm; one of the more common cutaneous tumors in ferrets.",
        "description_ja": "一般的に良性の皮膚腫瘍で、フェレットの皮膚腫瘍の中では比較的多いです。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"skin_mass", "swelling", "pain", "lethargy", "weight_loss"},
        "description": "Malignant tumor of fibrous connective tissue that can be locally invasive.",
        "description_ja": "線維性結合組織の悪性腫瘍で、局所浸潤性を示すことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "chest_xray", "ct_scan"],
    },
    # ── Dermatological ─────────────────────────────────────────────────
    {
        "name": "Adrenal Alopecia",
        "name_ja": "副腎性脱毛",
        "symptoms": {"hair_loss", "thinning_skin", "itching", "vulvar_swelling"},
        "description": "Bilateral symmetric hair loss caused by adrenal hormone excess; the hallmark of adrenal disease.",
        "description_ja": "副腎ホルモン過剰による左右対称の脱毛で、副腎疾患の代表的症状です。",
        "urgency": "moderate",
        "recommended_tests": ["adrenal_panel", "ultrasound"],
    },
    {
        "name": "Ear Mites (Otodectes cynotis)",
        "name_ja": "耳ダニ症",
        "symptoms": {"ear_scratching", "ear_discharge", "head_shaking", "dark_ear_wax"},
        "description": "Very common ectoparasite causing dark waxy ear discharge and intense scratching.",
        "description_ja": "暗褐色の耳垢と激しい掻痒を引き起こす非常に一般的な外部寄生虫症です。",
        "urgency": "low",
        "recommended_tests": ["otoscopic_exam", "ear_swab_microscopy"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"hair_loss", "skin_crusting", "redness", "circular_lesions"},
        "description": "Fungal skin infection causing circular patches of hair loss; can spread to humans.",
        "description_ja": "円形の脱毛斑を引き起こす真菌感染症で、ヒトにも伝播する可能性があります。",
        "urgency": "low",
        "recommended_tests": ["fungal_culture", "woods_lamp", "skin_scraping"],
    },
    {
        "name": "Flea Dermatitis",
        "name_ja": "ノミ性皮膚炎",
        "symptoms": {"itching", "hair_loss", "redness", "skin_crusting", "flea_dirt"},
        "description": "Skin irritation and allergic reaction to flea bites.",
        "description_ja": "ノミの咬傷に対するアレルギー反応による皮膚炎です。",
        "urgency": "low",
        "recommended_tests": ["flea_comb", "skin_scraping"],
    },
    {
        "name": "Tail Alopecia (Rat Tail)",
        "name_ja": "尾部脱毛（ラットテイル）",
        "symptoms": {"tail_hair_loss", "blackheads_on_tail"},
        "description": "Seasonal or hormonal hair loss on the tail, sometimes with comedones; often benign.",
        "description_ja": "季節性またはホルモン性の尾部脱毛で、面皰を伴うこともあります。通常良性です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "hormone_panel"],
    },
    {
        "name": "Sarcoptic Mange",
        "name_ja": "疥癬",
        "symptoms": {"intense_itching", "hair_loss", "skin_crusting", "redness", "thickened_skin"},
        "description": "Burrowing mite infestation causing severe pruritus and crusty skin lesions.",
        "description_ja": "ヒゼンダニの寄生により激しいかゆみとかさぶた状の皮膚病変が生じます。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "physical_exam"],
    },
    # ── Urinary ────────────────────────────────────────────────────────
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"straining_to_urinate", "bloody_urine", "frequent_urination", "abdominal_pain", "vocalization_during_urination"},
        "description": "Formation of urinary stones (often struvite or cystine), potentially causing obstruction.",
        "description_ja": "尿路に結石（ストルバイトやシスチンが多い）が形成され、閉塞を起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "abdominal_xray", "abdominal_ultrasound"],
    },
    {
        "name": "Prostatic Cysts (Adrenal-related)",
        "name_ja": "前立腺嚢胞（副腎関連）",
        "symptoms": {"straining_to_urinate", "urinary_obstruction", "abdominal_distension", "lethargy", "dribbling_urine"},
        "description": "Hormone-driven prostatic enlargement and cyst formation in neutered males with adrenal disease.",
        "description_ja": "副腎疾患に関連したホルモン異常により去勢雄の前立腺が肥大・嚢胞化します。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "adrenal_panel", "urinalysis"],
    },
    {
        "name": "Chronic Kidney Disease",
        "name_ja": "慢性腎臓病",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "appetite_loss", "lethargy", "dehydration", "vomiting"},
        "description": "Progressive loss of kidney function leading to uremia and electrolyte imbalances.",
        "description_ja": "腎機能の進行性低下により尿毒症や電解質異常が生じます。",
        "urgency": "moderate",
        "recommended_tests": ["bun_creatinine", "urinalysis", "abdominal_ultrasound"],
    },
    {
        "name": "Urinary Tract Infection (UTI)",
        "name_ja": "尿路感染症",
        "symptoms": {"frequent_urination", "straining_to_urinate", "bloody_urine", "foul_smelling_urine", "lethargy"},
        "description": "Bacterial infection of the urinary tract causing dysuria and hematuria.",
        "description_ja": "尿路の細菌感染により排尿困難や血尿がみられます。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "cbc"],
    },
    {
        "name": "Renal Cysts",
        "name_ja": "腎嚢胞",
        "symptoms": {"excessive_thirst", "excessive_urination", "abdominal_distension", "appetite_loss"},
        "description": "Fluid-filled cysts in the kidneys that may impair function over time.",
        "description_ja": "腎臓に液体で満たされた嚢胞が形成され、時間とともに腎機能が低下することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "bun_creatinine"],
    },
    # ── Reproductive ───────────────────────────────────────────────────
    {
        "name": "Aplastic Anemia (Estrogen Toxicity)",
        "name_ja": "再生不良性貧血（エストロゲン中毒）",
        "symptoms": {"hair_loss", "vulvar_swelling", "lethargy", "pale_gums", "bleeding", "appetite_loss", "weakness"},
        "description": "Fatal bone marrow suppression in unspayed females due to prolonged estrogen exposure from continuous estrus.",
        "description_ja": "未避妊雌の持続発情によるエストロゲン過剰で致死的な骨髄抑制が起こります。",
        "urgency": "emergency",
        "recommended_tests": ["cbc", "blood_smear", "estrogen_level", "bone_marrow_biopsy"],
    },
    {
        "name": "Vulvar Swelling (Adrenal-related)",
        "name_ja": "陰門腫脹（副腎関連）",
        "symptoms": {"vulvar_swelling", "hair_loss", "itching", "discharge"},
        "description": "Enlarged vulva in spayed females due to adrenal hormone production mimicking estrus.",
        "description_ja": "避妊済み雌で副腎ホルモンにより疑似発情状態となり陰門が腫脹します。",
        "urgency": "moderate",
        "recommended_tests": ["adrenal_panel", "hormone_panel", "ultrasound"],
    },
    {
        "name": "Prostatic Disease (Adrenal-related)",
        "name_ja": "前立腺疾患（副腎関連）",
        "symptoms": {"straining_to_urinate", "straining_to_defecate", "prostatic_enlargement", "dribbling_urine", "urinary_obstruction"},
        "description": "Prostatic hyperplasia or abscess in neutered males secondary to adrenal disease.",
        "description_ja": "副腎疾患に続発する去勢雄の前立腺肥大または膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "adrenal_panel", "urinalysis", "culture_sensitivity"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vulvar_discharge", "lethargy", "appetite_loss", "fever", "abdominal_distension", "excessive_thirst"},
        "description": "Infection of the uterus in intact females; life-threatening without surgery.",
        "description_ja": "未避妊雌の子宮感染症で、外科的処置なしでは致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["cbc", "abdominal_ultrasound", "biochemistry"],
    },
    # ── Musculoskeletal ────────────────────────────────────────────────
    {
        "name": "Posterior Paresis / Hind Leg Weakness",
        "name_ja": "後肢不全麻痺",
        "symptoms": {"hind_leg_weakness", "dragging_hind_legs", "difficulty_walking", "muscle_wasting"},
        "description": "Common sign in ferrets; may result from insulinoma, spinal disease, or cardiac disease.",
        "description_ja": "フェレットで一般的な症状で、インスリノーマ、脊椎疾患、心疾患など多因子性です。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "spinal_xray", "neurological_exam", "echocardiography"],
    },
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"limping", "swelling", "pain", "inability_to_bear_weight", "vocalization"},
        "description": "Broken bones from falls, being stepped on, or caught in cage doors.",
        "description_ja": "落下、踏みつけ、ケージに挟まるなどの外傷による骨折です。",
        "urgency": "high",
        "recommended_tests": ["xray", "physical_exam"],
    },
    {
        "name": "Osteoporosis",
        "name_ja": "骨粗鬆症",
        "symptoms": {"fractures_spontaneous", "hind_leg_weakness", "pain", "lethargy"},
        "description": "Decreased bone density from metabolic or nutritional causes, increasing fracture risk.",
        "description_ja": "代謝性または栄養性の原因で骨密度が低下し、骨折リスクが増加します。",
        "urgency": "moderate",
        "recommended_tests": ["xray", "calcium_phosphorus_levels", "biochemistry"],
    },
    {
        "name": "Intervertebral Disc Disease",
        "name_ja": "椎間板疾患",
        "symptoms": {"hind_leg_weakness", "pain", "difficulty_walking", "urinary_incontinence", "vocalization"},
        "description": "Herniation or degeneration of spinal discs causing nerve compression and paresis.",
        "description_ja": "椎間板のヘルニアや変性により神経圧迫と不全麻痺が起こります。",
        "urgency": "high",
        "recommended_tests": ["spinal_xray", "mri", "neurological_exam"],
    },
    # ── Neurological ───────────────────────────────────────────────────
    {
        "name": "Canine Distemper",
        "name_ja": "犬ジステンパー",
        "symptoms": {"nasal_discharge", "rash", "fever", "seizures", "crusty_foot_pads", "appetite_loss", "lethargy", "eye_discharge"},
        "description": "Nearly 100% fatal paramyxovirus infection; vaccination is essential for all ferrets.",
        "description_ja": "致死率ほぼ100%のパラミクソウイルス感染症。全フェレットに予防接種が不可欠です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_distemper", "cbc", "physical_exam"],
    },
    {
        "name": "Aleutian Disease (ADV)",
        "name_ja": "アリューシャン病（ADV）",
        "symptoms": {"weight_loss", "lethargy", "hind_leg_weakness", "black_tarry_stool", "muscle_wasting", "recurrent_infections"},
        "description": "Chronic parvovirus infection causing immune-mediated vasculitis and progressive wasting.",
        "description_ja": "パルボウイルスによる慢性感染症で、免疫介在性血管炎と進行性削痩を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["adv_antibody_test", "serum_protein_electrophoresis", "cbc"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "circling", "nystagmus", "loss_of_balance", "vomiting", "lethargy"},
        "description": "Dysfunction of the vestibular system causing head tilt, circling, and loss of balance.",
        "description_ja": "前庭系の機能障害により頭部傾斜、旋回運動、平衡感覚喪失が起こります。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "ear_exam", "mri"],
    },
    {
        "name": "Rabies",
        "name_ja": "狂犬病",
        "symptoms": {"behavior_change", "aggression", "seizures", "paralysis", "drooling", "difficulty_swallowing"},
        "description": "Fatal viral zoonosis; ferrets should be vaccinated with approved rabies vaccine.",
        "description_ja": "致死的なウイルス性人獣共通感染症。承認されたワクチンによる予防接種が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["fluorescent_antibody_test"],
    },
    {
        "name": "Seizure Disorder (Epilepsy)",
        "name_ja": "てんかん（痙攣性疾患）",
        "symptoms": {"seizures", "collapse", "drooling", "paddling", "confusion", "vocalization"},
        "description": "Recurrent seizures from idiopathic or secondary causes; must differentiate from insulinoma.",
        "description_ja": "特発性または続発性の反復性痙攣で、インスリノーマとの鑑別が必要です。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "neurological_exam", "mri", "cbc"],
    },
    # ── Infectious ─────────────────────────────────────────────────────
    {
        "name": "Ferret Systemic Coronavirus (FRSCV)",
        "name_ja": "フェレット全身性コロナウイルス感染症",
        "symptoms": {"weight_loss", "diarrhea", "lethargy", "appetite_loss", "abdominal_distension", "fever", "lymph_node_enlargement"},
        "description": "A distinct coronavirus causing systemic pyogranulomatous inflammation resembling feline FIP.",
        "description_ja": "猫FIPに類似した全身性肉芽腫性炎症を引き起こすコロナウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["cbc", "biochemistry", "abdominal_ultrasound", "biopsy"],
    },
    {
        "name": "Bacterial Skin Abscess",
        "name_ja": "細菌性皮膚膿瘍",
        "symptoms": {"swelling", "pain", "skin_mass", "fever", "discharge"},
        "description": "Localized bacterial infection from bite wounds or skin injuries forming a pus-filled pocket.",
        "description_ja": "咬傷や皮膚損傷から細菌感染が起こり、膿瘍を形成します。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "physical_exam", "cbc"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "vomiting", "fever", "appetite_loss", "dehydration", "lethargy"},
        "description": "Bacterial gastroenteritis from contaminated food; zoonotic concern.",
        "description_ja": "汚染食物による細菌性胃腸炎で、人獣共通感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "cbc"],
    },
    {
        "name": "Campylobacteriosis",
        "name_ja": "カンピロバクター症",
        "symptoms": {"diarrhea", "mucoid_stool", "appetite_loss", "lethargy"},
        "description": "Bacterial GI infection that may cause intermittent mucoid diarrhea, especially in young ferrets.",
        "description_ja": "特に若いフェレットで間欠性の粘液性下痢を引き起こす細菌性消化管感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "cbc"],
    },
    # ── Dental ─────────────────────────────────────────────────────────
    {
        "name": "Dental Disease / Periodontal Disease",
        "name_ja": "歯科疾患・歯周病",
        "symptoms": {"bad_breath", "drooling", "appetite_loss", "pawing_at_mouth", "teeth_discoloration"},
        "description": "Plaque and tartar accumulation leading to gingivitis and potential tooth loss.",
        "description_ja": "歯垢・歯石の蓄積により歯肉炎や歯の喪失を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "dental_xray"],
    },
    {
        "name": "Dental Tartar / Calculus",
        "name_ja": "歯石",
        "symptoms": {"bad_breath", "teeth_discoloration", "gum_redness", "appetite_loss"},
        "description": "Mineralized plaque on teeth causing gingival inflammation and discomfort.",
        "description_ja": "歯に付着した石灰化歯垢が歯肉の炎症と不快感を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["dental_exam"],
    },
    {
        "name": "Broken / Fractured Teeth",
        "name_ja": "歯の破折",
        "symptoms": {"pawing_at_mouth", "drooling", "appetite_loss", "pain", "teeth_discoloration"},
        "description": "Cracked or broken teeth from chewing hard objects; may expose pulp and cause infection.",
        "description_ja": "硬い物を噛んで歯が折れ、歯髄露出や感染を起こすことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "dental_xray"],
    },
    {
        "name": "Tooth Root Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "drooling", "pain", "bad_breath", "nasal_discharge"},
        "description": "Infection at the root of a tooth causing facial swelling and pain.",
        "description_ja": "歯根部の感染により顔面腫脹と疼痛が生じます。",
        "urgency": "moderate",
        "recommended_tests": ["dental_xray", "physical_exam", "cbc"],
    },
    # ── Parasitic ──────────────────────────────────────────────────────
    {
        "name": "Flea Infestation",
        "name_ja": "ノミ寄生症",
        "symptoms": {"itching", "flea_dirt", "hair_loss", "redness", "restlessness"},
        "description": "Infestation by fleas causing pruritus, anemia in severe cases, and potential tapeworm transmission.",
        "description_ja": "ノミの寄生により掻痒、重症例では貧血、条虫伝播の可能性があります。",
        "urgency": "low",
        "recommended_tests": ["flea_comb", "physical_exam"],
    },
    {
        "name": "Intestinal Parasites (Roundworm / Hookworm)",
        "name_ja": "腸管寄生虫症（回虫・鉤虫）",
        "symptoms": {"diarrhea", "weight_loss", "pot_belly", "lethargy", "appetite_loss"},
        "description": "Internal parasitic infestation affecting nutrient absorption; more common in young ferrets.",
        "description_ja": "栄養吸収を障害する腸管寄生虫症で、若齢フェレットに多くみられます。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Giardia",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "mucoid_stool", "weight_loss", "appetite_loss", "dehydration"},
        "description": "Protozoal intestinal parasite causing chronic intermittent diarrhea.",
        "description_ja": "慢性間欠性の下痢を引き起こす原虫性の腸管寄生虫症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_antigen_test", "fecal_smear"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "appetite_loss"},
        "description": "Protozoal infection causing watery diarrhea; zoonotic and difficult to treat.",
        "description_ja": "水様性下痢を引き起こす原虫感染症で、人獣共通で治療が困難です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_antigen_test", "fecal_smear"],
    },
    # ── Metabolic ──────────────────────────────────────────────────────
    {
        "name": "Hypoglycemia (Insulinoma-related)",
        "name_ja": "低血糖症（インスリノーマ関連）",
        "symptoms": {"hypoglycemia", "lethargy", "seizures", "collapse", "drooling", "hind_leg_weakness", "confusion", "staring"},
        "description": "Dangerously low blood sugar episodes from insulinoma; can cause seizures and death.",
        "description_ja": "インスリノーマによる危険な低血糖発作で、痙攣や死亡を引き起こす可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "insulin_level"],
    },
    {
        "name": "Splenomegaly",
        "name_ja": "脾臓腫大",
        "symptoms": {"splenomegaly", "abdominal_distension", "lethargy", "appetite_loss"},
        "description": "Enlarged spleen; extremely common in ferrets and often benign (extramedullary hematopoiesis), but may indicate lymphoma.",
        "description_ja": "脾臓の腫大。フェレットで非常に多く、良性（髄外造血）のことが多いですが、リンパ腫の可能性もあります。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "fine_needle_aspirate", "cbc"],
    },
    {
        "name": "Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"panting", "lethargy", "collapse", "drooling", "redness", "seizures", "vomiting"},
        "description": "Ferrets are very heat sensitive; temperatures above 80°F (27°C) can be dangerous.",
        "description_ja": "フェレットは暑さに非常に弱く、27°C以上の環境は危険です。",
        "urgency": "emergency",
        "recommended_tests": ["rectal_temperature", "cbc", "biochemistry"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"dehydration", "lethargy", "tented_skin", "dry_gums", "sunken_eyes", "appetite_loss"},
        "description": "Fluid deficit from diarrhea, vomiting, or inadequate water intake; can rapidly become critical.",
        "description_ja": "下痢、嘔吐、水分摂取不足による体液不足で、急速に重篤化することがあります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "biochemistry", "packed_cell_volume"],
    },
    # ── Hematological ──────────────────────────────────────────────────
    {
        "name": "Hyperestrogenism-induced Anemia",
        "name_ja": "高エストロゲン血症性貧血",
        "symptoms": {"pale_gums", "lethargy", "weakness", "hair_loss", "bleeding", "petechiae"},
        "description": "Severe pancytopenia from estrogen-mediated bone marrow suppression in intact females or adrenal disease.",
        "description_ja": "未避妊雌や副腎疾患によるエストロゲン過剰で骨髄抑制を起こし、重度の汎血球減少がみられます。",
        "urgency": "emergency",
        "recommended_tests": ["cbc", "blood_smear", "estrogen_level", "bone_marrow_biopsy"],
    },
    {
        "name": "Lymphocytosis / Leukemia",
        "name_ja": "リンパ球増多症・白血病",
        "symptoms": {"lymph_node_enlargement", "lethargy", "weight_loss", "splenomegaly", "appetite_loss"},
        "description": "Elevated lymphocyte count that may indicate chronic inflammation or lymphoproliferative disease.",
        "description_ja": "リンパ球数の増加で、慢性炎症やリンパ増殖性疾患を示唆することがあります。",
        "urgency": "high",
        "recommended_tests": ["cbc", "blood_smear", "bone_marrow_biopsy", "lymph_node_biopsy"],
    },
    {
        "name": "Thrombocytopenia",
        "name_ja": "血小板減少症",
        "symptoms": {"petechiae", "bleeding", "bruising", "lethargy", "pale_gums"},
        "description": "Low platelet count causing bleeding tendencies; may be immune-mediated or secondary to bone marrow disease.",
        "description_ja": "血小板数の減少により出血傾向がみられます。免疫介在性または骨髄疾患に続発します。",
        "urgency": "high",
        "recommended_tests": ["cbc", "blood_smear", "coagulation_panel"],
    },
    # ── Miscellaneous / Behavioral ─────────────────────────────────────
    {
        "name": "Hairballs (Trichobezoars)",
        "name_ja": "毛球症",
        "symptoms": {"vomiting", "appetite_loss", "lethargy", "weight_loss", "thin_stool"},
        "description": "Accumulation of swallowed hair in the stomach or intestines; especially during shedding season.",
        "description_ja": "換毛期に飲み込んだ毛が胃腸内に蓄積します。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_xray", "physical_exam"],
    },
    {
        "name": "Vaccine Reaction",
        "name_ja": "ワクチン反応",
        "symptoms": {"vomiting", "diarrhea", "lethargy", "facial_swelling", "difficulty_breathing", "collapse", "hives"},
        "description": "Ferrets are prone to anaphylactic reactions to distemper and rabies vaccines; monitor for 30+ minutes post-vaccination.",
        "description_ja": "フェレットはジステンパー・狂犬病ワクチンでアナフィラキシー反応を起こしやすいです。接種後30分以上の観察が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Gastric Dilation / Bloat",
        "name_ja": "胃拡張・鼓腸",
        "symptoms": {"abdominal_distension", "abdominal_pain", "lethargy", "vomiting", "difficulty_breathing", "collapse"},
        "description": "Acute gastric dilation which can be life-threatening; requires immediate veterinary attention.",
        "description_ja": "急性の胃拡張で生命を脅かすことがあり、直ちに獣医師の処置が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "physical_exam"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cataracts", "cloudy_eyes", "bumping_into_objects"},
        "description": "Lens opacity that can be age-related or secondary to diabetes; may cause blindness.",
        "description_ja": "加齢性または糖尿病に続発する水晶体の混濁で、失明の原因となることがあります。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "watery_eyes", "eye_discharge", "pawing_at_face", "redness"},
        "description": "Damage to the corneal surface from trauma or infection; painful and requires prompt treatment.",
        "description_ja": "外傷や感染による角膜表面の損傷で、痛みを伴い早急な治療が必要です。",
        "urgency": "moderate",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam"],
    },
    {
        "name": "Proliferative Colitis",
        "name_ja": "増殖性大腸炎",
        "symptoms": {"diarrhea", "bloody_stool", "rectal_prolapse", "weight_loss", "straining_to_defecate"},
        "description": "Desulfovibrio-associated colitis in young ferrets causing bloody mucoid diarrhea.",
        "description_ja": "若いフェレットに見られるDesulfovibrio菌関連の大腸炎で、粘血便がみられます。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_test", "rectal_biopsy", "cbc"],
    },
    {
        "name": "Cholangiohepatitis",
        "name_ja": "胆管肝炎",
        "symptoms": {"jaundice", "appetite_loss", "lethargy", "vomiting", "weight_loss", "abdominal_pain"},
        "description": "Inflammation of the bile ducts and liver causing jaundice and systemic illness.",
        "description_ja": "胆管と肝臓の炎症により黄疸や全身性疾患が生じます。",
        "urgency": "high",
        "recommended_tests": ["liver_enzymes", "abdominal_ultrasound", "cbc", "liver_biopsy"],
    },
    {
        "name": "Pancreatic Exocrine Insufficiency",
        "name_ja": "膵外分泌不全",
        "symptoms": {"diarrhea", "weight_loss", "large_fatty_stool", "appetite_increase"},
        "description": "Insufficient digestive enzyme production leading to maldigestion and nutrient malabsorption.",
        "description_ja": "消化酵素の産生不足により消化不良と栄養吸収障害が起こります。",
        "urgency": "moderate",
        "recommended_tests": ["tli_test", "fecal_test", "biochemistry"],
    },
    {
        "name": "Myasthenia Gravis",
        "name_ja": "重症筋無力症",
        "symptoms": {"muscle_weakness", "exercise_intolerance", "regurgitation", "difficulty_swallowing", "collapse"},
        "description": "Autoimmune neuromuscular disorder causing progressive muscle weakness and fatigue.",
        "description_ja": "自己免疫性の神経筋疾患で、進行性の筋力低下と易疲労がみられます。",
        "urgency": "high",
        "recommended_tests": ["acetylcholine_receptor_antibody", "chest_xray", "neurological_exam"],
    },
    {
        "name": "Disseminated Idiopathic Myofasciitis (DIM)",
        "name_ja": "播種性特発性筋膜炎（DIM）",
        "symptoms": {"fever", "lethargy", "appetite_loss", "difficulty_walking", "pain", "swelling"},
        "description": "Inflammatory condition affecting muscles and fascia in young ferrets; cause unknown.",
        "description_ja": "若いフェレットの筋肉と筋膜に影響する炎症性疾患で、原因不明です。",
        "urgency": "high",
        "recommended_tests": ["cbc", "biochemistry", "muscle_biopsy"],
    },
    {
        "name": "Hepatomegaly",
        "name_ja": "肝腫大",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "jaundice", "weight_loss"},
        "description": "Enlarged liver from various causes including hepatic lipidosis, neoplasia, or cardiac disease.",
        "description_ja": "脂肪肝、腫瘍、心疾患など様々な原因による肝臓の腫大です。",
        "urgency": "moderate",
        "recommended_tests": ["liver_enzymes", "abdominal_ultrasound", "cbc"],
    },
    {
        "name": "Adrenal Cyst",
        "name_ja": "副腎嚢胞",
        "symptoms": {"hair_loss", "vulvar_swelling", "lethargy", "aggression"},
        "description": "Non-neoplastic cystic enlargement of adrenal glands producing excess hormones.",
        "description_ja": "副腎の非腫瘍性嚢胞性腫大で、過剰なホルモン産生を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "adrenal_panel"],
    },
    {
        "name": "Pododermatitis (Bumblefoot)",
        "name_ja": "趾皮膚炎（バンブルフット）",
        "symptoms": {"swollen_feet", "limping", "redness", "pain", "ulcerated_skin_lesion"},
        "description": "Inflammation and infection of the foot pads from wire cage flooring or obesity.",
        "description_ja": "金網ケージの床や肥満による足底の炎症・感染です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture_sensitivity"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "lethargy", "difficulty_walking", "exercise_intolerance"},
        "description": "Excess body fat often from overfeeding or high-carb diets; increases disease risk.",
        "description_ja": "過食や高炭水化物食による過剰な体脂肪蓄積で、疾患リスクが増加します。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "body_condition_score"],
    },
    {
        "name": "Choanal Atresia",
        "name_ja": "後鼻孔閉鎖症",
        "symptoms": {"difficulty_breathing", "nasal_discharge", "open_mouth_breathing", "snoring"},
        "description": "Congenital narrowing or closure of the posterior nasal passages causing breathing difficulty.",
        "description_ja": "先天性の後鼻孔の狭窄または閉鎖により呼吸困難が生じます。",
        "urgency": "moderate",
        "recommended_tests": ["ct_scan", "rhinoscopy"],
    },
    {
        "name": "Osteoma",
        "name_ja": "骨腫",
        "symptoms": {"skin_mass", "swelling", "pain"},
        "description": "Benign bone tumor occasionally found in ferrets, typically as a hard mass.",
        "description_ja": "フェレットで時折見られる良性の骨腫瘍で、通常硬い腫瘤として触知されます。",
        "urgency": "low",
        "recommended_tests": ["xray", "biopsy"],
    },
]


SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # General
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite Loss"},
    "weight_loss": {"ja": "体重減少", "en": "Weight Loss"},
    "weight_gain": {"ja": "体重増加", "en": "Weight Gain"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "collapse": {"ja": "虚脱・失神", "en": "Collapse / Fainting"},
    "pain": {"ja": "疼痛", "en": "Pain"},
    "vocalization": {"ja": "鳴き声（痛み）", "en": "Vocalization (Pain)"},
    "confusion": {"ja": "混乱", "en": "Confusion"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    # Neurological
    "seizures": {"ja": "痙攣", "en": "Seizures"},
    "head_tilt": {"ja": "斜頸", "en": "Head Tilt"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "loss_of_balance": {"ja": "平衡感覚喪失", "en": "Loss of Balance"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "hind_leg_weakness": {"ja": "後肢衰弱", "en": "Hind Leg Weakness"},
    "dragging_hind_legs": {"ja": "後肢を引きずる", "en": "Dragging Hind Legs"},
    "difficulty_walking": {"ja": "歩行困難", "en": "Difficulty Walking"},
    "paddling": {"ja": "パドリング動作", "en": "Paddling"},
    "staring": {"ja": "凝視", "en": "Staring"},
    # Gastrointestinal
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "green_diarrhea": {"ja": "緑色下痢", "en": "Green Diarrhea"},
    "mucoid_stool": {"ja": "粘液便", "en": "Mucoid Stool"},
    "black_tarry_stool": {"ja": "黒色タール便", "en": "Black Tarry Stool"},
    "bloody_stool": {"ja": "血便", "en": "Bloody Stool"},
    "thin_stool": {"ja": "細い便", "en": "Thin / Ribbon-like Stool"},
    "large_fatty_stool": {"ja": "大量の脂肪便", "en": "Large Fatty Stool"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth Grinding (Bruxism)"},
    "drooling": {"ja": "よだれ", "en": "Drooling"},
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal Pain"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal Distension"},
    "rectal_protrusion": {"ja": "直腸脱出", "en": "Rectal Protrusion"},
    "rectal_prolapse": {"ja": "直腸脱", "en": "Rectal Prolapse"},
    "straining_to_defecate": {"ja": "排便時のいきみ", "en": "Straining to Defecate"},
    "regurgitation": {"ja": "吐出", "en": "Regurgitation"},
    "difficulty_swallowing": {"ja": "嚥下困難", "en": "Difficulty Swallowing"},
    "thickened_intestines": {"ja": "腸壁肥厚", "en": "Thickened Intestines"},
    "appetite_increase": {"ja": "食欲亢進", "en": "Increased Appetite"},
    # Skin / Coat
    "hair_loss": {"ja": "脱毛", "en": "Hair Loss"},
    "tail_hair_loss": {"ja": "尾部脱毛", "en": "Tail Hair Loss"},
    "itching": {"ja": "かゆみ", "en": "Itching"},
    "intense_itching": {"ja": "激しいかゆみ", "en": "Intense Itching"},
    "redness": {"ja": "発赤", "en": "Redness"},
    "skin_crusting": {"ja": "皮膚のかさぶた", "en": "Skin Crusting"},
    "skin_nodules": {"ja": "皮膚結節", "en": "Skin Nodules"},
    "skin_mass": {"ja": "皮膚腫瘤", "en": "Skin Mass"},
    "thinning_skin": {"ja": "皮膚の菲薄化", "en": "Thinning Skin"},
    "thickened_skin": {"ja": "皮膚肥厚", "en": "Thickened Skin"},
    "circular_lesions": {"ja": "円形病変", "en": "Circular Lesions"},
    "flea_dirt": {"ja": "ノミの糞", "en": "Flea Dirt"},
    "blackheads_on_tail": {"ja": "尾部の面皰", "en": "Blackheads on Tail"},
    "ulcerated_skin_lesion": {"ja": "潰瘍性皮膚病変", "en": "Ulcerated Skin Lesion"},
    "hives": {"ja": "蕁麻疹", "en": "Hives"},
    "rash": {"ja": "発疹", "en": "Rash"},
    "petechiae": {"ja": "点状出血", "en": "Petechiae"},
    "bruising": {"ja": "あざ・皮下出血", "en": "Bruising"},
    "crusty_foot_pads": {"ja": "足底のかさぶた", "en": "Crusty Foot Pads"},
    "swollen_feet": {"ja": "足の腫れ", "en": "Swollen Feet"},
    # Respiratory
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "difficulty_breathing": {"ja": "呼吸困難", "en": "Difficulty Breathing"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal Discharge"},
    "open_mouth_breathing": {"ja": "開口呼吸", "en": "Open Mouth Breathing"},
    "panting": {"ja": "パンティング", "en": "Panting"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "aspiration_pneumonia_signs": {"ja": "誤嚥性肺炎徴候", "en": "Aspiration Pneumonia Signs"},
    "snoring": {"ja": "いびき", "en": "Snoring"},
    # Cardiac
    "heart_murmur": {"ja": "心雑音", "en": "Heart Murmur"},
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise Intolerance"},
    # Urinary
    "excessive_thirst": {"ja": "多飲", "en": "Excessive Thirst"},
    "excessive_urination": {"ja": "多尿", "en": "Excessive Urination"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent Urination"},
    "straining_to_urinate": {"ja": "排尿時のいきみ", "en": "Straining to Urinate"},
    "bloody_urine": {"ja": "血尿", "en": "Bloody Urine"},
    "foul_smelling_urine": {"ja": "悪臭尿", "en": "Foul-smelling Urine"},
    "dribbling_urine": {"ja": "尿漏れ", "en": "Dribbling Urine"},
    "urinary_obstruction": {"ja": "尿閉", "en": "Urinary Obstruction"},
    "urinary_incontinence": {"ja": "尿失禁", "en": "Urinary Incontinence"},
    "vocalization_during_urination": {"ja": "排尿時の鳴き声", "en": "Vocalization During Urination"},
    # Reproductive
    "vulvar_swelling": {"ja": "陰門腫脹", "en": "Vulvar Swelling"},
    "vulvar_discharge": {"ja": "陰門分泌物", "en": "Vulvar Discharge"},
    "discharge": {"ja": "分泌物", "en": "Discharge"},
    "prostatic_enlargement": {"ja": "前立腺肥大", "en": "Prostatic Enlargement"},
    # Eyes
    "watery_eyes": {"ja": "流涙", "en": "Watery Eyes"},
    "eye_discharge": {"ja": "目やに", "en": "Eye Discharge"},
    "cataracts": {"ja": "白内障", "en": "Cataracts"},
    "cloudy_eyes": {"ja": "目の混濁", "en": "Cloudy Eyes"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into Objects"},
    "squinting": {"ja": "目を細める", "en": "Squinting"},
    "pawing_at_face": {"ja": "顔を掻く", "en": "Pawing at Face"},
    # Ear
    "ear_scratching": {"ja": "耳を掻く", "en": "Ear Scratching"},
    "ear_discharge": {"ja": "耳だれ", "en": "Ear Discharge"},
    "head_shaking": {"ja": "頭を振る", "en": "Head Shaking"},
    "dark_ear_wax": {"ja": "暗褐色の耳垢", "en": "Dark Ear Wax"},
    # Dental / Oral
    "bad_breath": {"ja": "口臭", "en": "Bad Breath"},
    "pawing_at_mouth": {"ja": "口を掻く", "en": "Pawing at Mouth"},
    "teeth_discoloration": {"ja": "歯の変色", "en": "Teeth Discoloration"},
    "gum_redness": {"ja": "歯肉の発赤", "en": "Gum Redness"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial Swelling"},
    # Musculoskeletal
    "limping": {"ja": "跛行", "en": "Limping"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "inability_to_bear_weight": {"ja": "体重負荷不能", "en": "Inability to Bear Weight"},
    "muscle_wasting": {"ja": "筋肉萎縮", "en": "Muscle Wasting"},
    "muscle_weakness": {"ja": "筋力低下", "en": "Muscle Weakness"},
    "fractures_spontaneous": {"ja": "自然骨折", "en": "Spontaneous Fractures"},
    "pot_belly": {"ja": "太鼓腹", "en": "Pot Belly"},
    # Hematological
    "pale_gums": {"ja": "歯肉蒼白", "en": "Pale Gums"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "splenomegaly": {"ja": "脾臓腫大", "en": "Splenomegaly"},
    "lymph_node_enlargement": {"ja": "リンパ節腫大", "en": "Lymph Node Enlargement"},
    "recurrent_infections": {"ja": "反復性感染", "en": "Recurrent Infections"},
    # Metabolic
    "hypoglycemia": {"ja": "低血糖", "en": "Hypoglycemia"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "tented_skin": {"ja": "皮膚テント形成", "en": "Tented Skin (Dehydration)"},
    "dry_gums": {"ja": "歯肉乾燥", "en": "Dry Gums"},
    "sunken_eyes": {"ja": "眼球陥凹", "en": "Sunken Eyes"},
    # Behavioral
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "behavior_change": {"ja": "行動変化", "en": "Behavior Change"},
    "excessive_grooming": {"ja": "過度なグルーミング", "en": "Excessive Grooming"},
    # Other
    "tail_mass": {"ja": "尾部腫瘤", "en": "Tail Mass"},
    "difficulty_defecating": {"ja": "排便困難", "en": "Difficulty Defecating"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species)
