"""fish_diseases.py – 観賞魚の代表的な疾患

淡水魚・海水魚（錦鯉、金魚、熱帯魚等）に発生する代表的な疾患を網羅的に
取り上げ、簡易的な鑑別診断を提供するモジュールです。情報は教育目的であり、
専門的な診断や治療は獣医師が行うべきです。
"""

from __future__ import annotations

from typing import Any, Dict, List

from . import prevalence_data
from .helpers import ADVICE, analyze_symptoms_generic, enrich_diseases

# Category mapping for symptom checkbox UI
SYMPTOM_CATEGORIES: Dict[str, str] = {
    # 体表・外観
    "white_spots": "skin", "cotton_like_growth": "skin", "fin_rot": "skin",
    "scale_loss": "skin", "raised_scales": "skin", "ulcers": "skin",
    "redness_skin": "skin", "mucus_overproduction": "skin",
    "discoloration": "skin", "dark_coloration": "skin", "white_film": "skin",
    "gold_dust": "skin", "lumps_nodules": "skin", "spots_black": "skin",
    "worm_like_parasites": "parasites", "anchor_worm": "parasites",
    # 鰭
    "clamped_fins": "fins", "frayed_fins": "fins", "fin_hemorrhage": "fins",
    # 眼
    "pop_eye": "eyes", "cloudy_eye": "eyes", "sunken_eye": "eyes",
    # 鰓
    "gill_redness": "gills", "gill_paleness": "gills", "gill_swelling": "gills",
    "gill_mucus": "gills", "rapid_gill_movement": "gills",
    # 行動
    "flashing": "behavior", "lethargy": "behavior", "loss_of_appetite": "behavior",
    "gasping_surface": "behavior", "erratic_swimming": "behavior",
    "loss_of_balance": "behavior", "swimming_upside_down": "behavior",
    "hiding": "behavior", "isolation": "behavior", "head_shaking": "behavior",
    "spinning": "behavior",
    # 腹部・体型
    "bloating": "body", "emaciation": "body", "dropsy": "body", "bent_spine": "body",
    # 排泄
    "white_stringy_feces": "digestive", "trailing_feces": "digestive",
    # 呼吸
    "labored_breathing": "respiratory",
    # 繁殖
    "egg_binding": "reproductive",
    # 急変
    "sudden_death": "emergency", "mass_mortality": "emergency",
}

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # 体表・外観
    "white_spots": {"ja": "白点（白い斑点）", "en": "White spots"},
    "cotton_like_growth": {"ja": "綿状の付着物", "en": "Cotton-like growth"},
    "fin_rot": {"ja": "鰭の溶解・崩壊", "en": "Fin rot / erosion"},
    "scale_loss": {"ja": "鱗の脱落", "en": "Scale loss"},
    "raised_scales": {"ja": "鱗の逆立ち（松かさ）", "en": "Raised scales (pinecone)"},
    "ulcers": {"ja": "潰瘍・ただれ", "en": "Ulcers / sores"},
    "redness_skin": {"ja": "体表の充血・発赤", "en": "Skin redness / hemorrhage"},
    "mucus_overproduction": {"ja": "粘液の過剰分泌", "en": "Excess mucus production"},
    "discoloration": {"ja": "体色の変化・退色", "en": "Color change / fading"},
    "dark_coloration": {"ja": "体色の黒化", "en": "Darkening of body color"},
    "white_film": {"ja": "白い膜状の付着", "en": "White film on body"},
    "gold_dust": {"ja": "金粉状の付着（コショウ病）", "en": "Gold dust appearance"},
    "lumps_nodules": {"ja": "しこり・結節", "en": "Lumps / nodules"},
    "worm_like_parasites": {"ja": "糸状の寄生虫が見える", "en": "Visible worm-like parasites"},
    "anchor_worm": {"ja": "イカリムシの付着", "en": "Anchor worm attached"},
    "spots_black": {"ja": "黒い斑点", "en": "Black spots"},
    # 鰭・尾
    "clamped_fins": {"ja": "鰭をたたんでいる", "en": "Clamped fins"},
    "frayed_fins": {"ja": "鰭がボロボロ", "en": "Frayed / ragged fins"},
    "fin_hemorrhage": {"ja": "鰭の充血", "en": "Fin hemorrhage"},
    # 眼
    "pop_eye": {"ja": "眼球突出（ポップアイ）", "en": "Pop-eye (exophthalmia)"},
    "cloudy_eye": {"ja": "目の白濁", "en": "Cloudy eye"},
    "sunken_eye": {"ja": "眼球陥没", "en": "Sunken eye"},
    # 鰓
    "gill_redness": {"ja": "鰓の充血", "en": "Gill redness"},
    "gill_paleness": {"ja": "鰓の退色・蒼白", "en": "Pale gills"},
    "gill_swelling": {"ja": "鰓の腫脹", "en": "Gill swelling"},
    "gill_mucus": {"ja": "鰓の粘液過多", "en": "Excess gill mucus"},
    "rapid_gill_movement": {"ja": "鰓蓋の速い動き", "en": "Rapid opercular movement"},
    # 行動
    "flashing": {"ja": "体を擦りつける（フラッシング）", "en": "Flashing / scratching"},
    "lethargy": {"ja": "活動低下・沈下", "en": "Lethargy / bottom sitting"},
    "loss_of_appetite": {"ja": "食欲不振", "en": "Loss of appetite"},
    "gasping_surface": {"ja": "水面でパクパク（鼻上げ）", "en": "Gasping at surface"},
    "erratic_swimming": {"ja": "異常遊泳（暴れる）", "en": "Erratic / darting swimming"},
    "loss_of_balance": {"ja": "平衡感覚の喪失", "en": "Loss of balance / listing"},
    "swimming_upside_down": {"ja": "転覆（逆さまに泳ぐ）", "en": "Swimming upside down"},
    "hiding": {"ja": "隠れて出てこない", "en": "Hiding behavior"},
    "isolation": {"ja": "群れから離れる", "en": "Isolation from group"},
    "head_shaking": {"ja": "頭を振る", "en": "Head shaking"},
    "spinning": {"ja": "旋回遊泳", "en": "Spinning / whirling"},
    # 腹部・体型
    "bloating": {"ja": "腹部膨満", "en": "Abdominal bloating / swelling"},
    "emaciation": {"ja": "痩せ（やつれ）", "en": "Emaciation / wasting"},
    "dropsy": {"ja": "腹水・浮腫", "en": "Dropsy / edema"},
    "bent_spine": {"ja": "脊椎の湾曲", "en": "Bent / curved spine"},
    # 排泄
    "white_stringy_feces": {"ja": "白い糸状の糞", "en": "White stringy feces"},
    "trailing_feces": {"ja": "糞がぶら下がる", "en": "Trailing feces"},
    # 呼吸
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    # 繁殖
    "egg_binding": {"ja": "過抱卵", "en": "Egg binding"},
    # 急変
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "mass_mortality": {"ja": "大量死", "en": "Mass mortality"},
}

DISEASES: List[Dict[str, Any]] = [
    {
        "name": "Ichthyophthirius (White Spot Disease / Ich)",
        "name_ja": "白点病（イクチオフチリウス症）",
        "symptoms": {"white_spots", "flashing", "clamped_fins", "lethargy", "loss_of_appetite", "rapid_gill_movement"},
        "description": "Caused by the ciliate protozoan Ichthyophthirius multifiliis. One of the most common and recognizable freshwater fish diseases.",
        "description_ja": "繊毛虫イクチオフチリウス・ムルチフィリスによる感染症。淡水魚で最も一般的で認知度の高い疾患の一つ。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy", "water_quality_test"],
        "causes": "Parasitic infection by the ciliate protozoan Ichthyophthirius multifiliis. Triggered by rapid temperature changes, stress, and immunosuppression.",
        "causes_ja": "繊毛虫 Ichthyophthirius multifiliis の寄生。水温の急変、ストレス、免疫低下が発症を誘発。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "成熟した栄養体（トロフォント）が上皮細胞下に寄生し、宿主組織を摂食しながら白い嚢胞（白点）を形成する。成熟後に魚体を離脱し底部でシストを形成、内部で分裂して数百の遊走子（セロント）を放出する。遊走子が新たな宿主に侵入し感染が爆発的に拡大。鰓への大量寄生は呼吸障害を引き起こし致死的となる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "水温を28-30°Cに上昇させ生活環を加速。0.3-0.5%塩水浴、メチレンブルー、マラカイトグリーン、ホルマリン浴。遊走子ステージでのみ薬剤が有効。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "新規導入魚の検疫（2-4週間）、水温の急変回避、適切な水質管理、過密飼育の回避。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期発見・治療で予後良好。重症例や鰓への大量寄生は致死的。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Columnaris Disease",
        "name_ja": "カラムナリス病（尾ぐされ病・口ぐされ病）",
        "symptoms": {"fin_rot", "frayed_fins", "ulcers", "white_film", "cotton_like_growth", "gill_redness", "lethargy", "loss_of_appetite"},
        "description": "Bacterial infection caused by Flavobacterium columnare. Affects skin, fins, and gills.",
        "description_ja": "Flavobacterium columnare による細菌感染症。皮膚、鰭、鰓に病変を形成。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy", "bacterial_culture", "water_quality_test"],
        "causes": "Bacterial infection by Flavobacterium columnare. Predisposed by high water temperature (>20°C), poor water quality, overcrowding, and skin injuries.",
        "causes_ja": "Flavobacterium columnare による細菌感染。高水温（20°C以上）、水質悪化、過密飼育、皮膚損傷が素因。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "F. columnare は損傷した上皮や鰓組織に付着・コロニー形成し、強力なタンパク分解酵素（コンドロイチナーゼ等）を産生して組織を融解する。鰭や皮膚の壊死が進行し、鰓感染では呼吸上皮の破壊により急性呼吸不全を引き起こす。敗血症に移行すると予後不良。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "抗菌薬浴（オキソリン酸、カナマイシン）、塩水浴、水質改善。重症例では薬餌投与。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "水質管理の徹底、過密飼育回避、ストレス軽減、外傷防止。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期の皮膚・鰭病変は治療反応良好。鰓型は急性経過で致死率が高い。敗血症例は予後不良。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Aeromonas / Motile Aeromonad Septicemia",
        "name_ja": "エロモナス感染症（運動性エロモナス敗血症）",
        "symptoms": {"ulcers", "redness_skin", "raised_scales", "dropsy", "pop_eye", "fin_hemorrhage", "lethargy", "loss_of_appetite", "bloating"},
        "description": "Opportunistic bacterial infection by Aeromonas hydrophila and related species, often secondary to stress or poor water quality.",
        "description_ja": "Aeromonas hydrophila 等による日和見細菌感染。ストレスや水質悪化が発症の背景にあることが多い。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "water_quality_test", "blood_smear"],
        "causes": "Opportunistic infection by Aeromonas hydrophila and related motile aeromonads. Precipitated by stress, poor water quality, overcrowding, temperature fluctuations, and immunosuppression.",
        "causes_ja": "Aeromonas hydrophila 等の運動性エロモナス属菌による日和見感染。ストレス、水質悪化、過密飼育、水温変動、免疫低下が誘因。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "A. hydrophila はアエロリシン等の溶血毒素、タンパク分解酵素、エラスターゼを産生し、血管内皮と組織を障害する。毒素による血管透過性亢進が出血性敗血症を引き起こし、腎糸球体障害による体液貯留が松かさ（立鱗）・腹水を形成。肝腎の壊死が進行すると多臓器不全に至る。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "抗菌薬浴（オキソリン酸、エンロフロキサシン）、薬餌、水質改善。松かさ病や腹水を伴う重症例は治療困難。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "水質管理、適正な飼育密度、栄養管理、ストレス軽減。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "局所感染（潰瘍のみ）は早期治療で回復可能。松かさ病・腹水を伴う全身感染は予後不良で致死率が高い。",
        "onset_pattern": {"acute", "subacute", "chronic"},
    },
    {
        "name": "Saprolegnia (Water Mold / Cotton Wool Disease)",
        "name_ja": "水カビ病（サプロレグニア症）",
        "symptoms": {"cotton_like_growth", "white_film", "lethargy", "loss_of_appetite", "ulcers"},
        "description": "Fungal infection caused by Saprolegnia and related oomycetes. Often secondary to skin damage or immunosuppression.",
        "description_ja": "サプロレグニア等の卵菌類による真菌感染。皮膚損傷や免疫低下に続発することが多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy", "water_quality_test"],
        "causes": "Infection by oomycete water molds (Saprolegnia, Achlya). Almost always secondary to skin trauma, bacterial infection, or immunosuppression from stress and poor water quality.",
        "causes_ja": "卵菌類（サプロレグニア、アクリア）による感染。ほぼ常に皮膚外傷、細菌感染、ストレス・水質悪化による免疫低下に続発。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "遊走子が損傷した皮膚や壊死組織に付着・発芽し、菌糸が真皮深層に侵入して壊死を拡大する。菌糸は浸透圧調節機能を破壊し、淡水魚では体液の過剰流入を引き起こす。広範な感染は浸透圧バランスの崩壊と二次的細菌感染により致死的となる。卵への感染は受精卵・未受精卵ともに壊死させる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "メチレンブルー浴、マラカイトグリーン浴、塩水浴（0.3-0.5%）。原因の除去（外傷治療、水質改善）。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "外傷防止、水質管理、適正水温維持、過密飼育回避。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "局所感染は早期治療で予後良好。広範な感染や鰓への波及は予後不良。根本原因の是正が再発防止に不可欠。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Velvet Disease (Oodinium / Piscinoodinium)",
        "name_ja": "コショウ病（ウーディニウム症）",
        "symptoms": {"gold_dust", "flashing", "clamped_fins", "rapid_gill_movement", "lethargy", "loss_of_appetite", "labored_breathing"},
        "description": "Parasitic infection caused by Piscinoodinium (freshwater) or Amyloodinium (marine). Often mistaken for Ich but spots are finer.",
        "description_ja": "淡水では Piscinoodinium、海水では Amyloodinium による寄生虫感染。白点病に似るが斑点はより微細。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy", "water_quality_test"],
        "causes": "Parasitic dinoflagellate infection by Piscinoodinium pillulare (freshwater) or Amyloodinium ocellatum (marine). Stress, poor water quality, and lack of quarantine facilitate outbreaks.",
        "causes_ja": "渦鞭毛虫 Piscinoodinium pillulare（淡水）または Amyloodinium ocellatum（海水）による寄生虫感染。ストレス、水質悪化、検疫不足が集団発生を助長。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "栄養体が鰓・皮膚上皮に根状突起（rhizocyst）を挿入して宿主細胞から栄養を吸収する。鰓上皮の広範な破壊は酸素交換能を著しく低下させ急性呼吸不全を引き起こす。葉緑体を持つため光合成も行い、遮光が治療に有効。皮膚のバリア機能破壊により浸透圧異常と二次感染のリスクが上昇する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "銅イオン製剤（海水）、メチレンブルー・アクリフラビン（淡水）、遮光（光合成阻害）、水温上昇。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "新規導入魚の検疫、適切な水質管理、過密飼育回避、ストレス軽減。海水魚は銅による予防浴も有効。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期発見・治療で予後良好。鰓への大量寄生は急性死を引き起こし、海水魚の Amyloodinium は特に致死率が高い。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Swim Bladder Disorder",
        "name_ja": "浮袋障害（転覆病）",
        "symptoms": {"loss_of_balance", "swimming_upside_down", "bloating", "loss_of_appetite", "lethargy"},
        "description": "Buoyancy disorder affecting the swim bladder. Common in fancy goldfish and bettas. May be caused by diet, infection, or congenital defects.",
        "description_ja": "浮袋の機能障害による浮力異常。琉金等の改良品種の金魚やベタに多い。食餌、感染、先天的異常が原因。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "xray", "water_quality_test"],
        "causes": "Multifactorial: dietary causes (overfeeding, constipation, air swallowing), bacterial infection of the swim bladder, congenital deformities in fancy goldfish breeds, and compression by enlarged organs or tumors.",
        "causes_ja": "多因子性: 食餌性（過食、便秘、空気の嚥下）、浮袋の細菌感染、改良品種金魚の先天的奇形、腫大臓器や腫瘍による圧迫。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "浮袋は気体の分泌・吸収により浮力を調節する。便秘や過食による消化管膨満が浮袋を物理的に圧迫し、気体量の調節を妨げる。細菌感染は浮袋壁の炎症・肥厚を引き起こし、気体交換機能を障害。改良品種では体型の変形により浮袋が物理的に歪み、慢性的な浮力異常を呈する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "3日間の絶食後、茹でた剥き餌（グリーンピース等）を給餌。水温を適正範囲に。細菌感染が疑われる場合は抗菌薬。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "適量給餌の徹底、消化しやすい餌の使用、浮上性餌の浸漬、適正水温維持、便秘予防。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "食餌性の一時的な転覆は絶食・食餌改善で回復することが多い。先天性や慢性例は完治困難だが生存は可能。細菌感染例は抗菌薬治療で改善しうる。",
        "onset_pattern": {"acute", "chronic"},
    },
    {
        "name": "Dropsy (Pinecone Disease)",
        "name_ja": "松かさ病（立鱗病・腹水症）",
        "symptoms": {"raised_scales", "bloating", "dropsy", "pop_eye", "lethargy", "loss_of_appetite", "redness_skin"},
        "description": "Symptom complex characterized by fluid accumulation and scale protrusion. Usually indicates severe organ failure (kidney/liver) or systemic infection.",
        "description_ja": "体液貯留と鱗の逆立ちを特徴とする症候群。通常、重度の臓器不全（腎/肝）または全身感染を示す。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "water_quality_test", "blood_chemistry"],
        "causes": "End-stage manifestation of severe systemic bacterial infection (Aeromonas, Pseudomonas), kidney failure, liver disease, or viral infection. Underlying causes include chronic poor water quality and immunosuppression.",
        "causes_ja": "重度の全身性細菌感染（エロモナス、シュードモナス）、腎不全、肝疾患、ウイルス感染の末期症状。慢性的な水質悪化と免疫低下が背景。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "腎臓の重度障害（糸球体腎炎・尿細管壊死）により体液の浸透圧調節が破綻し、体腔内に体液が貯留（腹水）する。体腔内圧の上昇が鱗の付け根の結合組織を押し上げ、松かさ状の立鱗を呈する。眼球後方の液体貯留が眼球突出（ポップアイ）を引き起こす。腎不全による代謝老廃物の蓄積が全身状態を悪化させる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "エプソムソルト浴（硫酸マグネシウム）、抗菌薬浴・薬餌、水質改善。予後は一般に不良。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "水質管理の徹底（アンモニア・亜硝酸ゼロ維持）、適正飼育密度、栄養バランスの良い給餌、ストレス軽減、初期の細菌感染の迅速な治療。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "一般に予後不良。早期の軽症例では回復の可能性があるが、重度の立鱗・腹水は治療困難。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Anchor Worm (Lernaea)",
        "name_ja": "イカリムシ症（レルネア症）",
        "symptoms": {"anchor_worm", "flashing", "redness_skin", "ulcers", "lethargy", "loss_of_appetite"},
        "description": "Parasitic copepod Lernaea that embeds in fish skin. Visible as thread-like protrusions from the body.",
        "description_ja": "寄生性カイアシ類レルネアが皮膚に突き刺さる。糸状の突起物として肉眼で確認可能。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_scrape_microscopy"],
        "causes": "Parasitic copepod Lernaea cyprinacea and related species. Introduced via infected fish or contaminated water. Warm water temperatures accelerate the life cycle.",
        "causes_ja": "寄生性カイアシ類 Lernaea cyprinacea 等の感染。感染魚や汚染水を介して持ち込まれる。高水温で生活環が加速。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "雌成虫が頭部のアンカー状突起を魚の筋肉組織深部に埋没させ固着する。組織の機械的破壊と持続的な炎症反応が潰瘍を形成し、二次的な細菌・真菌感染の侵入門戸となる。大量寄生は慢性的な出血と栄養消耗を引き起こし、成長遅延や貧血の原因となる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "ピンセットで成虫を除去後、傷口を消毒。トリクロルホン（ジプテレックス）浴、レバミゾール浴。幼虫対策も必要。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "新規導入魚の検疫と目視検査、池・水槽の定期的な寄生虫チェック、高水温期の予防的薬浴。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "少数寄生は除去・薬浴で予後良好。大量寄生による二次感染は治療が長期化するが回復可能。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Fish Lice (Argulus)",
        "name_ja": "ウオジラミ症（アルグルス症）",
        "symptoms": {"flashing", "redness_skin", "ulcers", "worm_like_parasites", "lethargy", "erratic_swimming"},
        "description": "Parasitic crustacean Argulus that attaches to skin and feeds on blood. Visible as flat, disc-shaped parasites.",
        "description_ja": "寄生性甲殻類アルグルスが皮膚に付着し吸血。平らな円盤状の寄生虫として肉眼で確認可能。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam"],
        "causes": "Parasitic branchiuran crustacean Argulus (fish louse). Transmitted via direct contact with infected fish or contaminated water containing larvae.",
        "causes_ja": "寄生性鰓尾類 Argulus（ウオジラミ）の感染。感染魚との直接接触または幼虫を含む汚染水を介して伝播。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "Argulus は吸盤と棘で魚体に付着し、針状の口器（stylet）で皮膚を穿刺して血液・体液を吸引する。唾液中の抗凝固物質と消化酵素が局所の炎症・出血を引き起こす。穿刺部位は細菌・ウイルスの侵入門戸となり、コイ春ウイルス血症（SVC）等のベクターともなりうる。大量寄生は貧血とストレスを引き起こす。",
        "treatment": "Treatment includes appropriate antiparasitic medication, environmental decontamination, and supportive care. Repeat treatments may be necessary to address lifecycle stages.",
        "treatment_ja": "トリクロルホン浴、ピンセットによる除去、塩水浴。池では水の完全入れ替えも有効。",
        "prevention": "Prevention includes regular parasite screening and treatment, environmental sanitation, quarantine of new animals, and avoiding overcrowding.",
        "prevention_ja": "新規導入魚の検疫・目視検査、池の定期的な寄生虫モニタリング、卵が産み付けられた基質の除去。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "少数寄生は除去・薬浴で完治可能。大量寄生でも適切な治療で予後良好。二次感染がない限り致死的になることは稀。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Gill Flukes (Dactylogyrus)",
        "name_ja": "鰓吸虫症（ダクチロギルス症）",
        "symptoms": {"rapid_gill_movement", "gasping_surface", "gill_redness", "gill_mucus", "flashing", "lethargy", "loss_of_appetite"},
        "description": "Monogenean trematode parasites infecting the gills. Causes respiratory distress and secondary bacterial infections.",
        "description_ja": "鰓に寄生する単生吸虫。呼吸困難と二次的な細菌感染を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["gill_biopsy_microscopy", "skin_scrape_microscopy"],
        "causes": "Monogenean trematode parasites of the genus Dactylogyrus. Oviparous (egg-laying), with eggs resistant to treatment. Introduced via infected fish.",
        "causes_ja": "単生吸虫ダクチロギルス属の寄生。卵生で、卵は薬剤に抵抗性を持つ。感染魚を介して持ち込まれる。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "鉤（haptor）の辺縁鉤と中央鉤で鰓弁に機械的に付着し、上皮細胞と粘液を摂食する。付着部位の上皮過形成と粘液過分泌が鰓弁の癒合を引き起こし、有効なガス交換面積を減少させる。重度感染では低酸素血症に至る。損傷した鰓組織は細菌の侵入門戸となり、二次感染が呼吸障害を悪化させる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "プラジカンテル浴、ホルマリン浴、トリクロルホン浴。重症例では抗菌薬の併用。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "新規導入魚の検疫、導入前の予防的薬浴（プラジカンテル）、過密飼育回避、定期的な鰓の顕微鏡検査。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期治療で予後良好。卵が薬剤抵抗性のため反復投薬が必要。鰓への重度寄生による呼吸不全は致死的となりうる。",
        "onset_pattern": {"acute", "subacute"},
    },
    # --- Additional diseases (batch 2) ---
    {
        "name": "Skin Flukes (Gyrodactylus)",
        "name_ja": "皮膚吸虫症（ギロダクチルス症）",
        "symptoms": {"flashing", "mucus_overproduction", "clamped_fins", "redness_skin", "ulcers", "lethargy"},
        "description": "Monogenean parasite infecting the skin and fins. Viviparous (live-bearing), so populations can explode rapidly.",
        "description_ja": "皮膚と鰭に寄生する単生吸虫。胎生のため個体数が急速に増加しうる。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy"],
        "causes": "Monogenean trematode parasites of the genus Gyrodactylus. Viviparous (live-bearing) allowing rapid population growth. Transmitted by direct fish-to-fish contact.",
        "causes_ja": "単生吸虫ギロダクチルス属の寄生。胎生のため急速な個体数増加が可能。魚同士の直接接触により伝播。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "辺縁鉤で皮膚上皮に付着し、表皮細胞を摂食する。胎生で体内に次世代（さらにその次世代）を内包するため、1個体から爆発的に増殖する。広範な上皮損傷が粘液過分泌と皮膚バリア破壊を引き起こし、浸透圧調節障害と二次感染の素因となる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "プラジカンテル浴、ホルマリン浴、塩水浴。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "新規導入魚の検疫・皮膚スクレーピング検査、過密飼育回避、ストレス軽減。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "薬浴治療に良好に反応する。卵のステージがないため単回治療で効果的。免疫低下魚では再感染に注意。",
        "onset_pattern": {"subacute"},
    },
    {
        "name": "Hole-in-the-Head Disease (HITH / HLLE)",
        "name_ja": "穴あき病（頭部穿孔症・HLLE）",
        "symptoms": {"ulcers", "discoloration", "loss_of_appetite", "lethargy", "emaciation", "white_stringy_feces"},
        "description": "Erosive condition affecting the head and lateral line. Linked to Hexamita/Spironucleus, poor diet, and water quality.",
        "description_ja": "頭部と側線に潰瘍性病変を形成。ヘキサミタ/スピロヌクレウス、栄養不良、水質悪化が関連。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam_microscopy", "water_quality_test", "skin_scrape_microscopy"],
        "causes": "Multifactorial: associated with Hexamita/Spironucleus flagellate infection, vitamin/mineral deficiencies (especially vitamin C, D, calcium), poor water quality, use of activated carbon, and inadequate diet in cichlids and discus.",
        "causes_ja": "多因子性: ヘキサミタ/スピロヌクレウス鞭毛虫感染、ビタミン・ミネラル欠乏（特にビタミンC、D、カルシウム）、水質悪化、活性炭の使用、シクリッド・ディスカスにおける不適切な食餌が関連。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "正確な病態は未解明だが、腸管内ヘキサミタの全身播種と栄養欠乏の複合作用と考えられている。鞭毛虫が感覚孔（側線系）周囲の組織に侵入・増殖し、局所の壊死と穿孔を引き起こす。ビタミン・ミネラル欠乏は上皮再生を障害し、活性炭による微量元素の吸着が病態を悪化させる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "メトロニダゾール浴または薬餌、栄養改善（ビタミン・ミネラル補給）、水質改善、活性炭除去。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "バランスの良い栄養（ビタミン・ミネラル豊富な餌）、定期的な換水、活性炭フィルターの見直し、ストレス軽減。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期治療と栄養改善で病変は治癒しうるが、瘢痕が残ることがある。進行例では治療反応が遅い。根本原因の是正が必須。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Hexamita / Spironucleus (Internal Flagellates)",
        "name_ja": "ヘキサミタ症（内部鞭毛虫症）",
        "symptoms": {"white_stringy_feces", "loss_of_appetite", "emaciation", "dark_coloration", "lethargy", "hiding"},
        "description": "Internal flagellate protozoan infection. Common in cichlids, discus, and angelfish.",
        "description_ja": "内部寄生性鞭毛虫感染。シクリッド、ディスカス、エンゼルフィッシュに多い。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam_microscopy"],
        "causes": "Diplomonad flagellate protozoans Hexamita and Spironucleus. Often present as commensals; clinical disease triggered by stress, overcrowding, poor water quality, and inadequate nutrition.",
        "causes_ja": "六鞭毛虫ヘキサミタおよびスピロヌクレウスの感染。常在菌として存在することが多く、ストレス、過密、水質悪化、栄養不良が臨床症状を誘発。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "鞭毛虫が腸管内で増殖し、腸粘膜上皮に付着・侵入して栄養吸収を阻害する。腸管の炎症と粘液過分泌により白色糸状の糞便を呈する。慢性感染では栄養吸収障害による削痩と成長遅延が進行。全身播種すると腎臓や胆嚢に感染が及び、穴あき病（HITH）の発症に関連する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "メトロニダゾール薬餌または浴、水温上昇、栄養改善。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "ストレス軽減、適正飼育密度、高品質な多様な餌の給餌、定期的な水質管理、新規導入魚の検疫。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期のメトロニダゾール治療で予後良好。慢性の削痩・穴あき病合併例は治療に時間を要するが回復可能。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Mycobacteriosis (Fish Tuberculosis)",
        "name_ja": "抗酸菌症（魚結核）",
        "symptoms": {"emaciation", "lethargy", "loss_of_appetite", "ulcers", "bent_spine", "pop_eye", "scale_loss", "dark_coloration"},
        "description": "Chronic bacterial infection caused by Mycobacterium marinum and related species. Zoonotic — can cause granulomas in humans.",
        "description_ja": "Mycobacterium marinum 等による慢性細菌感染。人獣共通感染症 — ヒトに肉芽腫を形成しうる。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "histopathology", "pcr"],
        "causes": "Chronic infection by Mycobacterium marinum, M. fortuitum, and M. chelonae. Transmitted via ingestion of infected tissue, contaminated water, or open wounds. Ubiquitous in aquatic environments.",
        "causes_ja": "Mycobacterium marinum、M. fortuitum、M. chelonae 等による慢性感染。感染組織の摂食、汚染水、開放創を介して伝播。水環境に広く分布。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "抗酸菌はマクロファージに貪食されるが細胞内で殺菌を回避して生存・増殖する。肉芽腫性炎症が肝臓、腎臓、脾臓、腸間膜に形成され、臓器実質を徐々に置換する。慢性的な臓器障害が栄養吸収不全、削痩、脊椎変形（椎体の肉芽腫性破壊）を引き起こす。人獣共通感染症であり、ヒトでは「フィッシュタンク肉芽腫」を生じる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "効果的な治療法はない。感染魚の隔離・淘汰が推奨。水槽・器具の徹底消毒。素手での取り扱いを避ける。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "感染魚の早期隔離・淘汰、死魚の速やかな除去、水槽・器具の消毒、手袋着用による取り扱い、新規導入魚の検疫。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "予後不良。慢性進行性で治癒は困難。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Ammonia Poisoning",
        "name_ja": "アンモニア中毒",
        "symptoms": {"gasping_surface", "gill_redness", "redness_skin", "lethargy", "erratic_swimming", "loss_of_appetite", "rapid_gill_movement", "mucus_overproduction"},
        "description": "Toxic condition caused by elevated ammonia levels, typically in new or overstocked aquariums.",
        "description_ja": "アンモニア濃度の上昇による中毒。新規立ち上げ水槽や過密飼育水槽で発生しやすい。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_test"],
        "causes": "Elevated total ammonia nitrogen (TAN) from fish waste, uneaten food, and decaying organic matter. Common in new tanks lacking established nitrifying bacteria (new tank syndrome), overstocked tanks, and after filter failure.",
        "causes_ja": "魚の排泄物、残餌、腐敗有機物からの総アンモニア態窒素（TAN）の上昇。硝化細菌が確立していない新規水槽（ニュータンクシンドローム）、過密水槽、フィルター故障後に多発。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "非イオン化アンモニア（NH3）は鰓上皮を通過して血中に入り、中枢神経系に直接毒性を発揮する。鰓上皮の化学的熱傷は粘液過分泌と上皮過形成を引き起こし、ガス交換効率を低下させる。高濃度では鰓毛細血管の拡張と出血（鰓の充血）が生じる。血中アンモニアの上昇は脳浮腫と痙攣を引き起こし致死的となる。",
        "treatment": "Treatment includes decontamination (if recent ingestion), specific antidotes where available, supportive care, fluid therapy, and monitoring of organ function.",
        "treatment_ja": "即座に大量換水（50-75%）。バクテリア添加剤の使用、給餌量の削減、アンモニア除去剤の使用。",
        "prevention": "Prevention includes removing access to toxic substances, using pet-safe products, proper storage of medications and chemicals, and educating owners about common toxins.",
        "prevention_ja": "水槽の適切な立ち上げ（サイクリング）、過密飼育回避、適切なフィルター、定期的な水質検査。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期の換水で予後良好。慢性低濃度暴露は鰓の不可逆的損傷を引き起こす。急性高濃度暴露は迅速に対応しなければ致死的。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Nitrite Poisoning (Brown Blood Disease)",
        "name_ja": "亜硝酸中毒（褐色血液病）",
        "symptoms": {"gasping_surface", "gill_paleness", "lethargy", "dark_coloration", "rapid_gill_movement", "sudden_death"},
        "description": "Caused by elevated nitrite levels which convert hemoglobin to methemoglobin, reducing oxygen-carrying capacity.",
        "description_ja": "亜硝酸濃度の上昇によりヘモグロビンがメトヘモグロビンに変換され、酸素運搬能が低下。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_test"],
        "causes": "Elevated nitrite (NO2-) from incomplete nitrification cycle. Common during tank cycling when Nitrobacter/Nitrospira populations are insufficient to convert nitrite to nitrate. Also occurs after filter disruption or antibiotic use.",
        "causes_ja": "不完全な硝化サイクルによる亜硝酸（NO2-）の上昇。硝化細菌（Nitrobacter/Nitrospira）が不十分な水槽サイクリング中に多発。フィルター障害や抗菌薬使用後にも発生。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "亜硝酸イオンが鰓の塩素イオン取り込み経路を介して血中に入り、ヘモグロビンのFe2+をFe3+に酸化してメトヘモグロビンを形成する。メトヘモグロビンは酸素と結合できないため、組織への酸素供給が著しく低下する。血液が褐色を呈し（褐色血液病）、鰓は暗褐色に退色する。重度の組織低酸素は臓器不全と急死を引き起こす。",
        "treatment": "Treatment includes decontamination (if recent ingestion), specific antidotes where available, supportive care, fluid therapy, and monitoring of organ function.",
        "treatment_ja": "大量換水、塩の添加（0.1-0.3% — 塩素イオンが亜硝酸の取り込みを阻害）、エアレーション強化。",
        "prevention": "Prevention includes removing access to toxic substances, using pet-safe products, proper storage of medications and chemicals, and educating owners about common toxins.",
        "prevention_ja": "水槽の適切なサイクリング、定期的な水質検査（特に亜硝酸）、過密飼育回避、フィルターの適切な維持管理。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期の換水と塩添加で回復可能。重度のメトヘモグロビン血症（>50%）は致死的。慢性低濃度暴露は免疫低下と二次感染の素因となる。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "pH Shock",
        "name_ja": "pH ショック",
        "symptoms": {"erratic_swimming", "gasping_surface", "mucus_overproduction", "lethargy", "sudden_death", "mass_mortality"},
        "description": "Acute stress caused by rapid pH changes. Even small rapid shifts can be fatal.",
        "description_ja": "急激なpH変化によるショック。わずかな急変でも致死的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_test"],
        "causes": "Rapid pH change (>0.3 units/hour) due to large water changes without pH matching, CO2 system malfunction, substrate dissolution, or biological acidification. Both acidic and alkaline shifts are harmful.",
        "causes_ja": "pH合わせなしの大量換水、CO2システムの故障、底床の溶解、生物学的酸性化による急激なpH変化（毎時0.3単位以上）。酸性・アルカリ性いずれの方向の急変も有害。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "急激なpH変化は鰓上皮の粘液層を破壊し、イオン交換機能を障害する。酸性ショックでは鰓上皮の凝固壊死とカルシウム沈着が生じ、アルカリショックでは粘液溶解と上皮の融解壊死が起こる。電解質バランス（Na+、Cl-、K+）の急激な崩壊が心機能障害と神経筋機能不全を引き起こし、急死に至る。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "緩やかな水質調整。急変の原因特定と除去。重度のショックには回復困難な場合がある。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "換水時のpH・水温合わせ、CO2添加装置の安全弁設置、KH（炭酸塩硬度）の適正維持によるpH緩衝能の確保。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "軽度のpH変動からは回復可能。急激な大幅変動（1単位以上）は致死率が高く、生存魚でも鰓と腎臓に不可逆的損傷を残すことがある。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Costia (Ichthyobodo)",
        "name_ja": "コスチア症（イクチオボド症）",
        "symptoms": {"mucus_overproduction", "white_film", "flashing", "clamped_fins", "gill_mucus", "rapid_gill_movement", "lethargy"},
        "description": "Protozoan ectoparasite that causes excessive mucus production and skin irritation.",
        "description_ja": "体表に寄生する原虫。過剰な粘液産生と皮膚刺激を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy"],
        "causes": "Flagellate protozoan ectoparasite Ichthyobodo necator (formerly Costia necatrix). Opportunistic; outbreaks linked to low water temperature, stress, and immunosuppression.",
        "causes_ja": "鞭毛虫性外部寄生原虫 Ichthyobodo necator（旧名 Costia necatrix）の感染。日和見的で、低水温、ストレス、免疫低下時に集団発生。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "鞭毛で皮膚・鰓上皮に付着し、細胞質を吸引して摂食する。広範な上皮損傷に対する防御反応として粘液の過剰分泌が起こり、体表が白い膜状に覆われる。鰓では粘液過多と上皮過形成がガス交換を阻害し呼吸困難を引き起こす。重度感染では皮膚バリア破壊による浸透圧調節障害が致死的となる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "ホルマリン浴、塩水浴、マラカイトグリーン浴、水温上昇。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "ストレス軽減、適正水温��持、新規導入魚の検疫、過密飼育回避。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期治療で予後良好。薬浴に良好に反応する。鰓への重度寄生で呼吸不全に至った場合は予後不良。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Trichodina",
        "name_ja": "トリコディナ症",
        "symptoms": {"flashing", "mucus_overproduction", "gill_mucus", "clamped_fins", "lethargy", "loss_of_appetite", "white_film"},
        "description": "Ciliate protozoan ectoparasite. Usually secondary to poor water quality or immunosuppression.",
        "description_ja": "体表に寄生する繊毛虫。水質悪化や免疫低下に続発することが多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy"],
        "causes": "Ciliate protozoan ectoparasites of the genus Trichodina. Often commensal at low numbers; clinical disease occurs when populations increase due to poor water quality, overcrowding, or immunosuppression.",
        "causes_ja": "繊毛虫トリコディナ属の外部寄生。少数では共生的だが、水質悪化、過密飼育、免疫低下により個体数が増加すると臨床症状を呈する。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "円盤状の歯環（denticle ring）で上皮を削り取りながら回転し、上皮細胞と粘液を摂食する。広範な上皮損傷が反応性粘液過分泌を引き起こす。鰓寄生では過形成と粘液過多がガス交換を阻害。皮膚バリアの破壊は二次的な細菌・真菌感染の素因となる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "ホルマリン浴、塩水浴、水質改善。根本原因の是正が重要。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "水質管理の徹底、過密飼育回避、ストレス軽減、新規導入魚の検疫。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "薬浴と水質改善で予後良好。根本原因を是正しないと再発する。重度の鰓感染以外は致死的になることは稀。",
        "onset_pattern": {"subacute"},
    },
    {
        "name": "Lymphocystis",
        "name_ja": "リンホシスチス病",
        "symptoms": {"lumps_nodules", "white_spots", "clamped_fins"},
        "description": "Viral disease causing cauliflower-like growths on skin and fins. Self-limiting in most cases.",
        "description_ja": "皮膚と鰭にカリフラワー状の増殖物を形成するウイルス性疾患。多くの場合は自然治癒。",
        "urgency": "low",
        "recommended_tests": ["histopathology"],
        "causes": "Iridovirus (Lymphocystivirus) infection. Transmitted through direct contact or contaminated water. Skin abrasions facilitate viral entry. Stress and immunosuppression trigger clinical disease.",
        "causes_ja": "イリドウイルス（リンホシスチスウイルス）の感染。直接接触または汚染水を介して伝播。皮膚の擦過傷がウイルス侵入を助長。ストレスと免疫低下が発症を誘発。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "ウイルスが線維芽細胞に感染し、感染細胞を正常の数万倍に肥大化させる（巨大細胞化）。肥大した感染細胞が集合してカリフラワー状の腫瘤を形成する。病変は主に体表と鰭に限局し、内臓への播種は稀。免疫応答により数週間〜数ヶ月で自然退縮するが、口周囲や鰓の大きな病変は摂餌障害や呼吸障害を起こしうる。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "特異的治療なし。自然治癒を待つ。二次感染予防に水質管理。重度の場合は外科的除去。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "感染魚の隔離、ストレス軽減、外傷防止、水質管理の徹底。新規導入魚の検疫。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "予後良好。多くの場合、免疫応答により数週間〜数ヶ月で自然治癒する。再発は稀だが免疫低下時に起こりうる。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Koi Herpesvirus Disease (KHV / CyHV-3)",
        "name_ja": "コイヘルペスウイルス病（KHV）",
        "symptoms": {"gill_redness", "gill_swelling", "gill_paleness", "gasping_surface", "lethargy", "loss_of_appetite", "sunken_eye", "mucus_overproduction", "mass_mortality"},
        "description": "Highly contagious viral disease of common and koi carp. Notifiable disease in many countries. Mortality can reach 80-100%.",
        "description_ja": "マゴイ・ニシキゴイの高伝染性ウイルス疾患。多くの国で届出義務あり。致死率は80-100%に達しうる。",
        "urgency": "emergency",
        "recommended_tests": ["pcr", "virus_isolation", "histopathology"],
        "causes": "Cyprinid herpesvirus 3 (CyHV-3). Highly species-specific to common carp and koi. Transmitted via direct contact, contaminated water, and fomites. Disease occurs at water temperatures of 18-28°C.",
        "causes_ja": "コイヘルペスウイルス3型（CyHV-3）の感染。マゴイ・ニシキゴイに高度に種特異的。直接接触、汚染水、媒介物を介して伝播。水温18-28°Cで発症。",
        "pathophysiology": "Viral particles enter host cells, hijack cellular machinery for replication, and cause cell lysis or immune-mediated damage. The host immune response may contribute to tissue pathology.",
        "pathophysiology_ja": "CyHV-3は鰓上皮と皮膚に親和性を持ち、感染細胞の壊死と脱落を引き起こす。鰓の壊死性炎症は呼吸上皮を広範に破壊し、重度の呼吸障害と浸透圧調節障害をもたらす。ウイルス血症により腎臓・脾臓・肝臓にも壊死が生じる。免疫抑制作用により二次的な細菌感染が重篤化する。生残魚は白血球にウイルスを潜伏感染させキャリアとなる。",
        "treatment": "Treatment is primarily supportive, including fluid therapy, nutritional support, and secondary infection prevention. Antiviral agents may be used where available and indicated.",
        "treatment_ja": "特異的治療なし。発症水域の隔離・移動制限。水温を30°C以上に上昇させることで症状が軽減する場合がある（キャリア化のリスクあり）。",
        "prevention": "Prevention includes vaccination where available, quarantine of new animals, biosecurity measures, proper hygiene, and avoiding contact with infected animals.",
        "prevention_ja": "新規導入魚の検疫（21日以上、18-25°Cで）、PCR検査による導入前スクリーニング、感染施設からの魚の導入禁止、器具の消毒。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "予後極めて不良。生残魚はキャリアとなり感染源となる。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Spring Viremia of Carp (SVC)",
        "name_ja": "コイ春ウイルス血症（SVC）",
        "symptoms": {"bloating", "dropsy", "pop_eye", "redness_skin", "fin_hemorrhage", "lethargy", "loss_of_appetite", "erratic_swimming", "mass_mortality"},
        "description": "Viral disease of cyprinids caused by Rhabdovirus carpio. Occurs in spring when water temperatures rise to 10-17°C.",
        "description_ja": "ラブドウイルス・カルピオによるコイ科魚類のウイルス疾患。水温が10-17°Cに上昇する春に発生。",
        "urgency": "emergency",
        "recommended_tests": ["pcr", "virus_isolation"],
        "causes": "Carp sprivivirus (Rhabdovirus carpio). Affects cyprinids including common carp, koi, goldfish. Transmitted via water, feces, and ectoparasites. Occurs seasonally in spring (10-17°C).",
        "causes_ja": "コイ・スプリビウイルス（ラブドウイルス・カルピオ）の感染。マゴイ、ニシキゴイ、金魚等のコイ科魚類に感染。水、糞便、外部寄生虫を介して伝播。春季（水温10-17°C）に季節的に発生。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "ウイルスは鰓を介して侵入しウイルス血症を起こす。血管内皮の感染と壊死により広範な出血（皮膚・鰭・内臓の点状出血）が生じる。腎臓の壊死は浸透圧調節障害と腹水の原因となる。肝臓・脾臓・造血組織の壊死により免疫機能が低下し、二次的な細菌感染（特にエロモナス）が重篤化する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "特異的治療なし。支持療法、二次感染予防、ストレス軽減。届出義務のある疾患。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "検疫の徹底、水温上昇期の魚移動制限、ストレス軽減、感染地域からの魚導入回避。届出義務疾患のため行政への報告が必要。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "予後不良。致死率は高く、特に幼魚で重篤。水温が17°Cを超えると症状は軽減するが、生残魚はキャリアとなりうる。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Neon Tetra Disease (Pleistophora)",
        "name_ja": "ネオン病（プレイストフォラ症）",
        "symptoms": {"discoloration", "emaciation", "bent_spine", "isolation", "loss_of_appetite", "erratic_swimming"},
        "description": "Microsporidian infection (Pleistophora hyphessobryconis) affecting small tetras. Causes progressive muscle degeneration.",
        "description_ja": "微胞子虫（Pleistophora hyphessobryconis）による感染。小型テトラに多く、進行性の筋肉変性を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["histopathology", "skin_scrape_microscopy"],
        "causes": "Microsporidian parasite Pleistophora hyphessobryconis. Primarily affects neon tetras and related small characins. Transmitted by ingestion of spores from infected tissue or contaminated water.",
        "causes_ja": "微胞子虫 Pleistophora hyphessobryconis の感染。主にネオンテトラおよび近縁の小型カラシン科に感染。感染組織や汚染水からの胞子摂取により伝播。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "経口摂取された胞子が腸管壁を貫通し、血流を介して骨格筋に到達する。筋線維内で胞子が増殖し、筋細胞を内側から破壊する。進行性の筋肉変性により体色の退色（ネオンストライプの白化）、脊椎の湾曲、遊泳障害が生じる。感染魚の死後に放出された胞子が水中に拡散し、他の魚が摂食して感染が拡大する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "効果的な治療法なし。感染魚の隔離・淘汰。水槽・器具の消毒。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "感染魚の早期発見と隔離・淘汰、死魚の速やかな除去（胞子拡散防止）、信頼できる供給元からの購入、新規導入魚の検疫。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "予後不良。治癒は見込めない。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "過抱卵（卵詰まり）",
        "symptoms": {"egg_binding", "bloating", "lethargy", "loss_of_appetite", "hiding"},
        "description": "Inability to release eggs. Common in goldfish, bettas, and cichlids. Can lead to secondary infections.",
        "description_ja": "卵を排出できない状態。金魚、ベタ、シクリッドに多い。二次感染を引き起こしうる。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "ultrasound"],
        "causes": "Inability to expel mature eggs. Caused by absence of spawning partner or stimuli, poor water conditions, nutritional deficiency, obesity, infection of the reproductive tract, or egg overproduction.",
        "causes_ja": "成熟卵を排出できない状態。産卵パートナーや産卵刺激の欠如、水質不良、栄養不足、肥満、生殖管の感染、卵の過剰産生が原因。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "排出されない卵が卵巣・輸卵管内に滞留し、腹腔内圧を上昇させる。滞留卵の変性・壊死が腹膜炎や敗血症の原因となる。卵巣の腫大が消化管を圧迫し食欲不振を引き起こす。重症例では体腔液の貯留と二次的な細菌感染が生じ、全身状態が悪化する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "水温上昇、エプソムソルト浴、産卵基質の設置。重症例では麻酔下での用手排卵。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "適切な産卵環境の整備（産卵基質、パートナーの存在）、適正な栄養管理、繁殖期の水温・光周期の管理。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期の環境改善・用手排卵で予後良好。卵の壊死・腹膜炎に進行した場合は予後不良。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Marine Ich (Cryptocaryon irritans)",
        "name_ja": "海水白点病（クリプトカリオン症）",
        "symptoms": {"white_spots", "flashing", "clamped_fins", "rapid_gill_movement", "loss_of_appetite", "lethargy", "labored_breathing"},
        "description": "Marine equivalent of freshwater Ich, caused by Cryptocaryon irritans. Extremely common in marine aquariums.",
        "description_ja": "淡水白点病の海水版。Cryptocaryon irritans による。海水水槽で極めて一般的。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy"],
        "causes": "Ciliate protozoan Cryptocaryon irritans. Extremely common in marine aquariums. Stress from capture, transport, and acclimation triggers outbreaks. Lifecycle is slower than freshwater Ich.",
        "causes_ja": "繊毛虫 Cryptocaryon irritans の感染。海水水槽で極めて一般的。捕獲・輸送・馴致のストレスが発症を誘発。淡水白点病より生活環が長い。",
        "pathophysiology": "The pathological process involves tissue injury, inflammatory response, and progressive functional impairment. Without intervention, compensatory mechanisms may be overwhelmed, leading to clinical deterioration.",
        "pathophysiology_ja": "栄養体が皮膚・鰓上皮下に寄生し組織を摂食する。淡水白点病と類似するが、生活環が長く（数週間）、シスト期が長期間休眠可能なため根絶が困難。鰓への大量寄生は呼吸上皮を破壊し急性呼吸不全を引き起こす。皮膚バリアの破壊は二次的な細菌感染を助長する。",
        "treatment": "Treatment should be tailored to the specific condition and includes appropriate medical or surgical intervention, supportive care, pain management, and regular monitoring of treatment response.",
        "treatment_ja": "銅イオン製剤（治療用水槽で）、低比重法（hyposalinity 1.009）、ホルマリン浴。サンゴ・無脊椎水槽では銅は使用不可。",
        "prevention": "Prevention includes appropriate husbandry, balanced nutrition, regular veterinary examinations, stress reduction, and prompt treatment of early signs of illness.",
        "prevention_ja": "新規導入魚の検疫（6-8週間推奨）、銅による予防浴、ストレス軽減、魚無し期間（fallow period: 72日以上）による水槽内の寄生虫根絶。",
        "prognosis": "Prognosis depends on severity, timeliness of treatment, and response to therapy. Early intervention generally improves outcomes.",
        "prognosis_ja": "早期治療で予後良好。鰓への大量寄生は致死的。生活環が長いため治療は数週間を要する。検疫の徹底が最も効果的な予防。",
        "onset_pattern": {"acute", "subacute"},
    },
]


def analyze_symptoms(
    symptoms: List[str],
    age_stage: str = "",
    breed: str = None,
    *,
    onset: str = None,
    age_years: float = None,
    species: str = None,
    lab_values: dict = None,
    gender: str = None,
    vaccines: list = None,
    vaccination_status: str = None,
) -> Dict[str, Any]:
    return analyze_symptoms_generic(
        symptoms,
        DISEASES,
        SYMPTOM_NAMES,
        ADVICE,
        onset=onset,
        age_years=age_years,
        breed=breed,
        species=species or "fish",
        lab_values=lab_values,
        gender=gender,
        vaccines=vaccines,
        vaccination_status=vaccination_status,
        prevalence_map=prevalence_data.SPECIES_PREVALENCE.get("fish", {}),
    )


DISEASES = enrich_diseases(DISEASES, "fish")
