"""fish_diseases.py – 観賞魚の代表的な疾患

淡水魚・海水魚（錦鯉、金魚、熱帯魚等）に発生する代表的な疾患を網羅的に
取り上げ、簡易的な鑑別診断を提供するモジュールです。情報は教育目的であり、
専門的な診断や治療は獣医師が行うべきです。
"""

from __future__ import annotations

from typing import Any, Dict, List

from . import prevalence_data
from .helpers import ADVICE, analyze_symptoms_generic, enrich_diseases

# Category mapping for symptom checkbox UI
SYMPTOM_CATEGORIES: Dict[str, str] = {
    # 体表・外観
    "white_spots": "skin", "cotton_like_growth": "skin", "fin_rot": "skin",
    "scale_loss": "skin", "raised_scales": "skin", "ulcers": "skin",
    "redness_skin": "skin", "mucus_overproduction": "skin",
    "discoloration": "skin", "dark_coloration": "skin", "white_film": "skin",
    "gold_dust": "skin", "lumps_nodules": "skin", "spots_black": "skin",
    "worm_like_parasites": "parasites", "anchor_worm": "parasites",
    # 鰭
    "clamped_fins": "fins", "frayed_fins": "fins", "fin_hemorrhage": "fins",
    # 眼
    "pop_eye": "eyes", "cloudy_eye": "eyes", "sunken_eye": "eyes",
    # 鰓
    "gill_redness": "gills", "gill_paleness": "gills", "gill_swelling": "gills",
    "gill_mucus": "gills", "rapid_gill_movement": "gills",
    # 行動
    "flashing": "behavior", "lethargy": "behavior", "loss_of_appetite": "behavior",
    "gasping_surface": "behavior", "erratic_swimming": "behavior",
    "loss_of_balance": "behavior", "swimming_upside_down": "behavior",
    "hiding": "behavior", "isolation": "behavior", "head_shaking": "behavior",
    "spinning": "behavior",
    # 腹部・体型
    "bloating": "body", "emaciation": "body", "dropsy": "body", "bent_spine": "body",
    # 排泄
    "white_stringy_feces": "digestive", "trailing_feces": "digestive",
    # 呼吸
    "labored_breathing": "respiratory",
    # 繁殖
    "egg_binding": "reproductive",
    # 急変
    "sudden_death": "emergency", "mass_mortality": "emergency",
}

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # 体表・外観
    "white_spots": {"ja": "白点（白い斑点）", "en": "White spots"},
    "cotton_like_growth": {"ja": "綿状の付着物", "en": "Cotton-like growth"},
    "fin_rot": {"ja": "鰭の溶解・崩壊", "en": "Fin rot / erosion"},
    "scale_loss": {"ja": "鱗の脱落", "en": "Scale loss"},
    "raised_scales": {"ja": "鱗の逆立ち（松かさ）", "en": "Raised scales (pinecone)"},
    "ulcers": {"ja": "潰瘍・ただれ", "en": "Ulcers / sores"},
    "redness_skin": {"ja": "体表の充血・発赤", "en": "Skin redness / hemorrhage"},
    "mucus_overproduction": {"ja": "粘液の過剰分泌", "en": "Excess mucus production"},
    "discoloration": {"ja": "体色の変化・退色", "en": "Color change / fading"},
    "dark_coloration": {"ja": "体色の黒化", "en": "Darkening of body color"},
    "white_film": {"ja": "白い膜状の付着", "en": "White film on body"},
    "gold_dust": {"ja": "金粉状の付着（コショウ病）", "en": "Gold dust appearance"},
    "lumps_nodules": {"ja": "しこり・結節", "en": "Lumps / nodules"},
    "worm_like_parasites": {"ja": "糸状の寄生虫が見える", "en": "Visible worm-like parasites"},
    "anchor_worm": {"ja": "イカリムシの付着", "en": "Anchor worm attached"},
    "spots_black": {"ja": "黒い斑点", "en": "Black spots"},
    # 鰭・尾
    "clamped_fins": {"ja": "鰭をたたんでいる", "en": "Clamped fins"},
    "frayed_fins": {"ja": "鰭がボロボロ", "en": "Frayed / ragged fins"},
    "fin_hemorrhage": {"ja": "鰭の充血", "en": "Fin hemorrhage"},
    # 眼
    "pop_eye": {"ja": "眼球突出（ポップアイ）", "en": "Pop-eye (exophthalmia)"},
    "cloudy_eye": {"ja": "目の白濁", "en": "Cloudy eye"},
    "sunken_eye": {"ja": "眼球陥没", "en": "Sunken eye"},
    # 鰓
    "gill_redness": {"ja": "鰓の充血", "en": "Gill redness"},
    "gill_paleness": {"ja": "鰓の退色・蒼白", "en": "Pale gills"},
    "gill_swelling": {"ja": "鰓の腫脹", "en": "Gill swelling"},
    "gill_mucus": {"ja": "鰓の粘液過多", "en": "Excess gill mucus"},
    "rapid_gill_movement": {"ja": "鰓蓋の速い動き", "en": "Rapid opercular movement"},
    # 行動
    "flashing": {"ja": "体を擦りつける（フラッシング）", "en": "Flashing / scratching"},
    "lethargy": {"ja": "活動低下・沈下", "en": "Lethargy / bottom sitting"},
    "loss_of_appetite": {"ja": "食欲不振", "en": "Loss of appetite"},
    "gasping_surface": {"ja": "水面でパクパク（鼻上げ）", "en": "Gasping at surface"},
    "erratic_swimming": {"ja": "異常遊泳（暴れる）", "en": "Erratic / darting swimming"},
    "loss_of_balance": {"ja": "平衡感覚の喪失", "en": "Loss of balance / listing"},
    "swimming_upside_down": {"ja": "転覆（逆さまに泳ぐ）", "en": "Swimming upside down"},
    "hiding": {"ja": "隠れて出てこない", "en": "Hiding behavior"},
    "isolation": {"ja": "群れから離れる", "en": "Isolation from group"},
    "head_shaking": {"ja": "頭を振る", "en": "Head shaking"},
    "spinning": {"ja": "旋回遊泳", "en": "Spinning / whirling"},
    # 腹部・体型
    "bloating": {"ja": "腹部膨満", "en": "Abdominal bloating / swelling"},
    "emaciation": {"ja": "痩せ（やつれ）", "en": "Emaciation / wasting"},
    "dropsy": {"ja": "腹水・浮腫", "en": "Dropsy / edema"},
    "bent_spine": {"ja": "脊椎の湾曲", "en": "Bent / curved spine"},
    # 排泄
    "white_stringy_feces": {"ja": "白い糸状の糞", "en": "White stringy feces"},
    "trailing_feces": {"ja": "糞がぶら下がる", "en": "Trailing feces"},
    # 呼吸
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    # 繁殖
    "egg_binding": {"ja": "過抱卵", "en": "Egg binding"},
    # 急変
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "mass_mortality": {"ja": "大量死", "en": "Mass mortality"},
}

DISEASES: List[Dict[str, Any]] = [
    {
        "name": "Ichthyophthirius (White Spot Disease / Ich)",
        "name_ja": "白点病（イクチオフチリウス症）",
        "symptoms": {"white_spots", "flashing", "clamped_fins", "lethargy", "loss_of_appetite", "rapid_gill_movement"},
        "description": "Caused by the ciliate protozoan Ichthyophthirius multifiliis. One of the most common and recognizable freshwater fish diseases.",
        "description_ja": "繊毛虫イクチオフチリウス・ムルチフィリスによる感染症。淡水魚で最も一般的で認知度の高い疾患の一つ。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy", "water_quality_test"],
        "causes": "Parasitic infection by the ciliate protozoan Ichthyophthirius multifiliis. Rapid temperature changes, stress, and immunosuppression trigger outbreaks.",
        "causes_ja": "繊毛虫 Ichthyophthirius multifiliis の寄生。水温の急変、ストレス、免疫低下が発症を誘発。",
        "pathophysiology": "Trophonts burrow into the epidermis, feeding on host cells and causing focal necrosis. The resulting white cysts rupture, releasing tomonts that encyst on surfaces and divide into hundreds of infective theronts. Massive gill parasitism leads to respiratory failure.",
        "pathophysiology_ja": "栄養体（トロフォント）が表皮に侵入し宿主細胞を摂食、局所壊死を起こす。白い嚢胞が破裂しトモントが放出され、基質上でシストを形成し数百の感染性テロントに分裂。鰓への大量寄生は呼吸不全を招く。",
        "treatment": "水温を28-30°Cに上昇させ生活環を加速。0.3-0.5%塩水浴、メチレンブルー、マラカイトグリーン、ホルマリン浴。遊走子ステージでのみ薬剤が有効。",
        "treatment_ja": "水温を28-30°Cに上昇させ生活環を加速。0.3-0.5%塩水浴、メチレンブルー、マラカイトグリーン、ホルマリン浴。遊走子ステージでのみ薬剤が有効。",
        "prevention": "新規導入魚の検疫（2-4週間）、水温の急変回避、適切な水質管理、過密飼育の回避。",
        "prevention_ja": "新規導入魚の検疫（2-4週間）、水温の急変回避、適切な水質管理、過密飼育の回避。",
        "prognosis": "早期発見・治療で予後良好。重症例や鰓への大量寄生は致死的。",
        "prognosis_ja": "早期発見・治療で予後良好。重症例や鰓への大量寄生は致死的。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Columnaris Disease",
        "name_ja": "カラムナリス病（尾ぐされ病・口ぐされ病）",
        "symptoms": {"fin_rot", "frayed_fins", "ulcers", "white_film", "cotton_like_growth", "gill_redness", "lethargy", "loss_of_appetite"},
        "description": "Bacterial infection caused by Flavobacterium columnare. Affects skin, fins, and gills.",
        "description_ja": "Flavobacterium columnare による細菌感染症。皮膚、鰭、鰓に病変を形成。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy", "bacterial_culture", "water_quality_test"],
        "treatment": "抗菌薬浴（オキソリン酸、カナマイシン）、塩水浴、水質改善。重症例では薬餌投与。",
        "treatment_ja": "抗菌薬浴（オキソリン酸、カナマイシン）、塩水浴、水質改善。重症例では薬餌投与。",
        "causes": "Bacterial infection by Flavobacterium columnare. Triggered by elevated water temperature (>20°C), skin injuries, and poor water quality.",
        "causes_ja": "Flavobacterium columnare による細菌感染。高水温（20°C超）、皮膚損傷、水質悪化が誘因。",
        "pathophysiology": "F. columnare adheres to damaged epithelium via adhesins, producing extracellular proteases that degrade skin, fin, and gill tissue. The bacteria form characteristic columnar aggregates. Gill involvement impairs gas exchange, leading to hypoxia.",
        "pathophysiology_ja": "F. columnare は付着因子により損傷上皮に接着し、細胞外プロテアーゼで皮膚・鰭・鰓組織を分解する。特徴的な柱状集塊を形成。鰓病変はガス交換を障害し低酸素症を招く。",
        "prevention": "水質管理の徹底、過密飼育回避、ストレス軽減、外傷防止。",
        "prevention_ja": "水質管理の徹底、過密飼育回避、ストレス軽減、外傷防止。",
        "prognosis": "Fair with early treatment. Gill involvement or systemic spread significantly worsens prognosis.",
        "prognosis_ja": "早期治療で予後はやや良好。鰓病変や全身播種は予後を著しく悪化させる。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Aeromonas / Motile Aeromonad Septicemia",
        "name_ja": "エロモナス感染症（運動性エロモナス敗血症）",
        "symptoms": {"ulcers", "redness_skin", "raised_scales", "dropsy", "pop_eye", "fin_hemorrhage", "lethargy", "loss_of_appetite", "bloating"},
        "description": "Opportunistic bacterial infection by Aeromonas hydrophila and related species, often secondary to stress or poor water quality.",
        "description_ja": "Aeromonas hydrophila 等による日和見細菌感染。ストレスや水質悪化が発症の背景にあることが多い。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "water_quality_test", "blood_smear"],
        "treatment": "抗菌薬浴（オキソリン酸、エンロフロキサシン）、薬餌、水質改善。松かさ病や腹水を伴う重症例は治療困難。",
        "treatment_ja": "抗菌薬浴（オキソリン酸、エンロフロキサシン）、薬餌、水質改善。松かさ病や腹水を伴う重症例は治療困難。",
        "causes": "Opportunistic infection by Aeromonas hydrophila and related motile aeromonads. Stress, overcrowding, skin wounds, and poor water quality predispose.",
        "causes_ja": "Aeromonas hydrophila 等の運動性エロモナスによる日和見感染。ストレス、過密、皮膚創傷、水質悪化が素因。",
        "pathophysiology": "Aeromonas produces aerolysin, hemolysins, and proteases that destroy host tissues. Bacteremia leads to septic emboli in kidney, liver, and spleen. Renal failure causes fluid retention (dropsy) and scale edema (pinecone appearance). Endotoxemia may cause hemorrhagic septicemia.",
        "pathophysiology_ja": "エロモナスはエロリジン、溶血素、プロテアーゼを産生し宿主組織を破壊。菌血症により腎・肝・脾に敗血性塞栓が生じる。腎不全が体液貯留（腹水）と鱗浮腫（松かさ）を引き起こす。内毒素血症は出血性敗血症の原因となりうる。",
        "prevention": "水質管理、適正な飼育密度、栄養管理、ストレス軽減。外傷のある魚の速やかな隔離・治療。",
        "prevention_ja": "水質管理、適正な飼育密度、栄養管理、ストレス軽減。外傷のある魚の速やかな隔離・治療。",
        "prognosis": "Poor once dropsy/pinecone scales develop. Early ulcerative lesions respond better to antibiotic therapy.",
        "prognosis_ja": "松かさ病・腹水発症後の予後は不良。初期の潰瘍性病変は抗菌薬治療に比較的よく反応する。",
        "onset_pattern": {"acute", "subacute", "chronic"},
    },
    {
        "name": "Saprolegnia (Water Mold / Cotton Wool Disease)",
        "name_ja": "水カビ病（サプロレグニア症）",
        "symptoms": {"cotton_like_growth", "white_film", "lethargy", "loss_of_appetite", "ulcers"},
        "description": "Fungal infection caused by Saprolegnia and related oomycetes. Often secondary to skin damage or immunosuppression.",
        "description_ja": "サプロレグニア等の卵菌類による真菌感染。皮膚損傷や免疫低下に続発することが多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy", "water_quality_test"],
        "treatment": "メチレンブルー浴、マラカイトグリーン浴、塩水浴（0.3-0.5%）。原因の除去（外傷治療、水質改善）。",
        "treatment_ja": "メチレンブルー浴、マラカイトグリーン浴、塩水浴（0.3-0.5%）。原因の除去（外傷治療、水質改善）。",
        "causes": "Infection by oomycete water molds (Saprolegnia, Achlya). Ubiquitous in freshwater; becomes pathogenic when skin defenses are compromised by wounds, handling, or immunosuppression.",
        "causes_ja": "卵菌類（サプロレグニア、アクリア）による感染。淡水中に普遍的に存在し、創傷・取扱い・免疫低下で皮膚防御が破綻すると病原性を発揮。",
        "pathophysiology": "Zoospores colonize damaged tissue, germinating into hyphae that penetrate the epidermis and dermis. Hyphal growth causes tissue necrosis with characteristic cotton-like mycelial masses. Osmoregulatory disruption occurs in severe cases as the skin barrier is lost.",
        "pathophysiology_ja": "遊走子が損傷組織にコロニーを形成し、菌糸が表皮・真皮に侵入。菌糸の増殖が組織壊死を引き起こし、特徴的な綿状の菌糸塊を形成。重症例では皮膚バリア喪失により浸透圧調節障害が生じる。",
        "prevention": "外傷防止、水質管理、適正水温維持、過密飼育回避。",
        "prevention_ja": "外傷防止、水質管理、適正水温維持、過密飼育回避。",
        "prognosis": "Good with early treatment if underlying cause is addressed. Extensive lesions covering >30% of body surface carry poor prognosis due to osmoregulatory collapse.",
        "prognosis_ja": "原因が除去されれば早期治療で予後良好。体表面積30%超の広範病変は浸透圧調節破綻により予後不良。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Velvet Disease (Oodinium / Piscinoodinium)",
        "name_ja": "コショウ病（ウーディニウム症）",
        "symptoms": {"gold_dust", "flashing", "clamped_fins", "rapid_gill_movement", "lethargy", "loss_of_appetite", "labored_breathing"},
        "description": "Parasitic infection caused by Piscinoodinium (freshwater) or Amyloodinium (marine). Often mistaken for Ich but spots are finer.",
        "description_ja": "淡水では Piscinoodinium、海水では Amyloodinium による寄生虫感染。白点病に似るが斑点はより微細。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy", "water_quality_test"],
        "treatment": "銅イオン製剤（海水）、メチレンブルー・アクリフラビン（淡水）、遮光（光合成阻害）、水温上昇。",
        "treatment_ja": "銅イオン製剤（海水）、メチレンブルー・アクリフラビン（淡水）、遮光（光合成阻害）、水温上昇。",
        "causes": "Parasitic dinoflagellate Piscinoodinium pillulare (freshwater) or Amyloodinium ocellatum (marine). Outbreaks triggered by stress, new introductions without quarantine, and suboptimal water quality.",
        "causes_ja": "寄生性渦鞭毛虫 Piscinoodinium pillulare（淡水）または Amyloodinium ocellatum（海水）。ストレス、検疫なしの新規導入、水質不良が誘因。",
        "pathophysiology": "Trophonts attach to gill and skin epithelium, penetrating host cells via a feeding stalk (stomopode). The parasite contains chloroplasts and is photosynthetic. Massive gill infestation severely impairs respiration. Skin damage leads to osmotic stress and secondary infections.",
        "pathophysiology_ja": "栄養体が鰓・皮膚上皮に付着し、摂食柄（ストモポード）で宿主細胞に侵入。本寄生虫は葉緑体を持ち光合成を行う。鰓への大量寄生は呼吸を著しく障害。皮膚損傷は浸透圧ストレスと二次感染を招く。",
        "prevention": "新規魚の検疫（2週間以上）、導入時の淡水浴（海水魚）、水質管理、ストレス軽減。",
        "prevention_ja": "新規魚の検疫（2週間以上）、導入時の淡水浴（海水魚）、水質管理、ストレス軽減。",
        "prognosis": "Good with early detection and treatment. Heavy gill infestation can be rapidly fatal, especially in marine fish (Amyloodinium).",
        "prognosis_ja": "早期発見・治療で予後良好。鰓への重度寄生は急速に致死的、特に海水魚（アミルウーディニウム）。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Swim Bladder Disorder",
        "name_ja": "浮袋障害（転覆病）",
        "symptoms": {"loss_of_balance", "swimming_upside_down", "bloating", "loss_of_appetite", "lethargy"},
        "description": "Buoyancy disorder affecting the swim bladder. Common in fancy goldfish and bettas. May be caused by diet, infection, or congenital defects.",
        "description_ja": "浮袋の機能障害による浮力異常。琉金等の改良品種の金魚やベタに多い。食餌、感染、先天的異常が原因。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "xray", "water_quality_test"],
        "treatment": "3日間の絶食後、茹でた剥き餌（グリーンピース等）を給餌。水温を適正範囲に。細菌感染が疑われる場合は抗菌薬。",
        "treatment_ja": "3日間の絶食後、茹でた剥き餌（グリーンピース等）を給餌。水温を適正範囲に。細菌感染が疑われる場合は抗菌薬。",
        "causes": "Multifactorial: dietary (overfeeding, air-gulping dry food), bacterial infection of swim bladder, congenital malformation in fancy breeds (ryukin, oranda, telescope eye goldfish), or physical trauma.",
        "causes_ja": "多因子性：食餌性（過給餌、乾燥飼料の空気嚥下）、浮袋の細菌感染、改良品種（琉金、オランダ、出目金）の先天的奇形、または物理的外傷。",
        "pathophysiology": "The swim bladder regulates buoyancy via gas secretion/absorption. Inflammation, infection, or physical compression (from constipation, fatty liver, or polycystic kidney) impairs bladder function. In fancy goldfish, the shortened body compresses abdominal organs against the swim bladder.",
        "pathophysiology_ja": "浮袋はガスの分泌・吸収により浮力を調節。炎症、感染、物理的圧迫（便秘、脂肪肝、多嚢胞腎）が浮袋機能を障害。改良金魚では短縮した体型が腹腔臓器を浮袋に圧迫する。",
        "prevention": "沈下性の餌を使用、適正量の給餌、水温管理。改良金魚は構造的に罹りやすいため予防には限界がある。",
        "prevention_ja": "沈下性の餌を使用、適正量の給餌、水温管理。改良金魚は構造的に罹りやすいため予防には限界がある。",
        "prognosis": "Variable. Dietary causes often resolve with fasting. Congenital cases in fancy goldfish are chronic and recurrent. Bacterial swim bladder infections carry guarded prognosis.",
        "prognosis_ja": "予後は原因による。食餌性は絶食で改善することが多い。改良金魚の先天性は慢性・再発性。細菌性浮袋感染の予後は慎重。",
        "onset_pattern": {"acute", "chronic"},
    },
    {
        "name": "Dropsy (Pinecone Disease)",
        "name_ja": "松かさ病（立鱗病・腹水症）",
        "symptoms": {"raised_scales", "bloating", "dropsy", "pop_eye", "lethargy", "loss_of_appetite", "redness_skin"},
        "description": "Symptom complex characterized by fluid accumulation and scale protrusion. Usually indicates severe organ failure (kidney/liver) or systemic infection.",
        "description_ja": "体液貯留と鱗の逆立ちを特徴とする症候群。通常、重度の臓器不全（腎/肝）または全身感染を示す。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "water_quality_test", "blood_chemistry"],
        "treatment": "エプソムソルト浴（硫酸マグネシウム）、抗菌薬浴・薬餌、水質改善。予後は一般に不良。",
        "treatment_ja": "エプソムソルト浴（硫酸マグネシウム）、抗菌薬浴・薬餌、水質改善。予後は一般に不良。",
        "causes": "Not a single disease but a symptom complex. Most commonly caused by Aeromonas or Pseudomonas bacterial septicemia leading to kidney failure. Also seen with mycobacteriosis, viral infections, and internal organ neoplasia.",
        "causes_ja": "単一の疾患ではなく症候群。最も多い原因はエロモナスやシュードモナスの細菌性敗血症による腎不全。抗酸菌症、ウイルス感染、内臓腫瘍でも発生。",
        "pathophysiology": "Renal failure (from infection, toxins, or neoplasia) impairs osmoregulation. The kidney cannot excrete water and electrolytes, causing fluid accumulation in the coelomic cavity (ascites) and subcutaneous edema that pushes scales outward (pinecone appearance). Hepatic failure compounds fluid retention.",
        "pathophysiology_ja": "腎不全（感染、毒素、腫瘍による）が浸透圧調節を障害。腎臓が水分・電解質を排泄できず、体腔内に液体が貯留（腹水）し、皮下浮腫が鱗を外側に押し上げる（松かさ）。肝不全が体液貯留を悪化させる。",
        "prevention": "適切な水質管理、ストレス軽減、適正な飼育密度。初期症状（軽度の腹部膨満）の段階での早期対応が重要。",
        "prevention_ja": "適切な水質管理、ストレス軽減、適正な飼育密度。初期症状（軽度の腹部膨満）の段階での早期対応が重要。",
        "prognosis": "一般に予後不良。早期の軽症例では回復の可能性があるが、重度の立鱗・腹水は治療困難。",
        "prognosis_ja": "一般に予後不良。早期の軽症例では回復の可能性があるが、重度の立鱗・腹水は治療困難。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Anchor Worm (Lernaea)",
        "name_ja": "イカリムシ症（レルネア症）",
        "symptoms": {"anchor_worm", "flashing", "redness_skin", "ulcers", "lethargy", "loss_of_appetite"},
        "description": "Parasitic copepod Lernaea that embeds in fish skin. Visible as thread-like protrusions from the body.",
        "description_ja": "寄生性カイアシ類レルネアが皮膚に突き刺さる。糸状の突起物として肉眼で確認可能。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_scrape_microscopy"],
        "treatment": "ピンセットで成虫を除去後、傷口を消毒。トリクロルホン（ジプテレックス）浴、レバミゾール浴。幼虫対策も必要。",
        "treatment_ja": "ピンセットで成虫を除去後、傷口を消毒。トリクロルホン（ジプテレックス）浴、レバミゾール浴。幼虫対策も必要。",
        "causes": "Parasitic copepod Lernaea cyprinacea. Adult females embed in host skin via an anchor-shaped attachment organ. Common in pond fish; introduced via untreated live food or new fish.",
        "causes_ja": "寄生性カイアシ類 Lernaea cyprinacea。成虫メスがイカリ状の付着器官で宿主皮膚に侵入。池魚に多く、未処理の生餌や新規導入魚から侵入。",
        "pathophysiology": "The female anchor worm penetrates skin and muscle with its cephalic anchor, causing tissue necrosis and hemorrhage at the attachment site. Secondary bacterial and fungal infections develop around the wound. Larval stages (nauplius, copepodid) are free-swimming and attach to gills before maturing.",
        "pathophysiology_ja": "メスのイカリムシが頭部のイカリで皮膚・筋肉に侵入し、付着部に組織壊死と出血を起こす。創傷周囲に二次的な細菌・真菌感染が発生。幼虫期（ノープリウス、コペポダイト）は遊泳性で鰓に付着してから成熟。",
        "prevention": "新規導入魚の検疫、生餌の処理、池の定期的なモニタリング。感染魚の早期発見・除去。",
        "prevention_ja": "新規導入魚の検疫、生餌の処理、池の定期的なモニタリング。感染魚の早期発見・除去。",
        "prognosis": "Good with prompt manual removal and wound care. Heavy infestations in small fish can be debilitating. Larval control is necessary to prevent reinfestation.",
        "prognosis_ja": "速やかな手作業除去と創傷ケアで予後良好。小型魚への大量寄生は衰弱を招く。再寄生防止には幼虫対策が必要。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Fish Lice (Argulus)",
        "name_ja": "ウオジラミ症（アルグルス症）",
        "symptoms": {"flashing", "redness_skin", "ulcers", "worm_like_parasites", "lethargy", "erratic_swimming"},
        "description": "Parasitic crustacean Argulus that attaches to skin and feeds on blood. Visible as flat, disc-shaped parasites.",
        "description_ja": "寄生性甲殻類アルグルスが皮膚に付着し吸血。平らな円盤状の寄生虫として肉眼で確認可能。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam"],
        "treatment": "トリクロルホン浴、ピンセットによる除去、塩水浴。池では水の完全入れ替えも有効。",
        "treatment_ja": "トリクロルホン浴、ピンセットによる除去、塩水浴。池では水の完全入れ替えも有効。",
        "causes": "Parasitic branchiuran crustacean Argulus spp. Free-swimming adults attach to host skin via suction cups and feed on blood and tissue fluids. Common in pond-reared fish.",
        "causes_ja": "寄生性鰓尾類甲殻類 Argulus 属。遊泳性の成虫が吸盤で宿主皮膚に付着し、血液と組織液を吸引。池飼育の魚に多い。",
        "pathophysiology": "Argulus pierces skin with a pre-oral stylet, injecting cytolytic toxins that cause local hemorrhage and tissue necrosis. The feeding wounds serve as entry points for secondary bacterial infections. Heavy infestations cause anemia and chronic stress.",
        "pathophysiology_ja": "アルグルスは前口針で皮膚を穿刺し、細胞溶解毒素を注入して局所出血と組織壊死を起こす。摂食創は二次細菌感染の侵入口となる。大量寄生は貧血と慢性ストレスを引き起こす。",
        "prevention": "新規魚の検疫、池への野生魚の侵入防止、定期的な目視検査。",
        "prevention_ja": "新規魚の検疫、池への野生魚の侵入防止、定期的な目視検査。",
        "prognosis": "Good with treatment. Argulus is readily controlled with organophosphates. Recurrence is common without environmental control of free-swimming stages.",
        "prognosis_ja": "治療により予後良好。有機リン剤で効果的に駆除可能。遊泳期の環境対策なしでは再発しやすい。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Gill Flukes (Dactylogyrus)",
        "name_ja": "鰓吸虫症（ダクチロギルス症）",
        "symptoms": {"rapid_gill_movement", "gasping_surface", "gill_redness", "gill_mucus", "flashing", "lethargy", "loss_of_appetite"},
        "description": "Monogenean trematode parasites infecting the gills. Causes respiratory distress and secondary bacterial infections.",
        "description_ja": "鰓に寄生する単生吸虫。呼吸困難と二次的な細菌感染を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["gill_biopsy_microscopy", "skin_scrape_microscopy"],
        "treatment": "プラジカンテル浴、ホルマリン浴、トリクロルホン浴。重症例では抗菌薬の併用。",
        "treatment_ja": "プラジカンテル浴、ホルマリン浴、トリクロルホン浴。重症例では抗菌薬の併用。",
        "causes": "Monogenean trematode Dactylogyrus spp. (oviparous, egg-laying). Primarily infects gills. Introduced via new fish or contaminated water/equipment.",
        "causes_ja": "単生吸虫 Dactylogyrus 属（卵生）。主に鰓に寄生。新規導入魚や汚染された水・器具から侵入。",
        "pathophysiology": "Dactylogyrus attaches to gill lamellae via opisthaptoral hooks, causing epithelial hyperplasia and lamellar fusion. Excess mucus production clogs gills. The resulting impaired gas exchange leads to hypoxia, and damaged gill tissue is susceptible to secondary bacterial infections.",
        "pathophysiology_ja": "ダクチロギルスは後吸盤の鉤で鰓弁に付着し、上皮過形成と弁融合を引き起こす。過剰粘液産生が鰓を閉塞。ガス交換障害は低酸素症を招き、損傷した鰓組織は二次細菌感染に脆弱となる。",
        "prevention": "新規魚の検疫、適切な水質管理、過密飼育回避。検疫期間中のプラジカンテル予防的処理。",
        "prevention_ja": "新規魚の検疫、適切な水質管理、過密飼育回避。検疫期間中のプラジカンテル予防的処理。",
        "prognosis": "Good with prompt antiparasitic treatment. Untreated heavy gill infestations can be fatal due to respiratory failure.",
        "prognosis_ja": "速やかな駆虫治療で予後良好。未治療の重度鰓寄生は呼吸不全により致死的となりうる。",
        "onset_pattern": {"acute", "subacute"},
    },
    # --- Additional diseases (batch 2) ---
    {
        "name": "Skin Flukes (Gyrodactylus)",
        "name_ja": "皮膚吸虫症（ギロダクチルス症）",
        "symptoms": {"flashing", "mucus_overproduction", "clamped_fins", "redness_skin", "ulcers", "lethargy"},
        "description": "Monogenean parasite infecting the skin and fins. Viviparous (live-bearing), so populations can explode rapidly.",
        "description_ja": "皮膚と鰭に寄生する単生吸虫。胎生のため個体数が急速に増加しうる。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy"],
        "treatment": "プラジカンテル浴、ホルマリン浴、塩水浴。",
        "treatment_ja": "プラジカンテル浴、ホルマリン浴、塩水浴。",
        "causes": "Monogenean trematode Gyrodactylus spp. (viviparous — gives live birth). Primarily infects skin and fins. Populations can explode rapidly as each parasite carries a developing embryo.",
        "causes_ja": "単生吸虫 Gyrodactylus 属（胎生）。主に皮膚と鰭に寄生。各虫体が発育中の胚を持つため個体数が急速に爆発的増加しうる。",
        "pathophysiology": "Hooks of the opisthaptor damage skin epithelium, causing irritation and excess mucus production. Chronic infestation leads to epidermal erosion, ulceration, and secondary bacterial/fungal infections. Neonatal fish and immunocompromised individuals are most susceptible.",
        "pathophysiology_ja": "後吸盤の鉤が皮膚上皮を損傷し、刺激と過剰粘液産生を引き起こす。慢性寄生は表皮びらん、潰瘍化、二次細菌・真菌感染を招く。新生仔魚と免疫低下個体が最も感受性が高い。",
        "prevention": "新規魚の検疫（プラジカンテル浴推奨）、過密回避、水質管理。",
        "prevention_ja": "新規魚の検疫（プラジカンテル浴推奨）、過密回避、水質管理。",
        "prognosis": "Good with treatment. Requires multiple treatments to break the reproductive cycle due to viviparous reproduction.",
        "prognosis_ja": "治療により予後良好。胎生のため生殖サイクル遮断に複数回の治療が必要。",
        "onset_pattern": {"subacute"},
    },
    {
        "name": "Hole-in-the-Head Disease (HITH / HLLE)",
        "name_ja": "穴あき病（頭部穿孔症・HLLE）",
        "symptoms": {"ulcers", "discoloration", "loss_of_appetite", "lethargy", "emaciation", "white_stringy_feces"},
        "description": "Erosive condition affecting the head and lateral line. Linked to Hexamita/Spironucleus, poor diet, and water quality.",
        "description_ja": "頭部と側線に潰瘍性病変を形成。ヘキサミタ/スピロヌクレウス、栄養不良、水質悪化が関連。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam_microscopy", "water_quality_test", "skin_scrape_microscopy"],
        "treatment": "メトロニダゾール浴または薬餌、栄養改善（ビタミン・ミネラル補給）、水質改善、活性炭除去。",
        "treatment_ja": "メトロニダゾール浴または薬餌、栄養改善（ビタミン・ミネラル補給）、水質改善、活性炭除去。",
        "causes": "Multifactorial. Linked to intestinal Hexamita/Spironucleus flagellate infection, vitamin/mineral deficiency (especially vitamin C and D), chronic poor water quality, and use of activated carbon filtering that removes trace elements.",
        "causes_ja": "多因子性。腸管内のヘキサミタ/スピロヌクレウス鞭毛虫感染、ビタミン・ミネラル欠乏（特にビタミンC・D）、慢性的な水質不良、微量元素を除去する活性炭フィルターの使用が関連。",
        "pathophysiology": "Sensory pits of the lateral line and head erode through a combination of flagellate-induced inflammation and nutritional deficiency of structural minerals. Lesions start as small pits that progressively enlarge into deep craters. The lateral line system, essential for detecting water movement, is permanently damaged in advanced cases.",
        "pathophysiology_ja": "側線と頭部の感覚孔が、鞭毛虫による炎症と構造的ミネラルの栄養不足の複合作用でびらんする。病変は小さな穴から始まり、進行性に深いクレーターに拡大。水流感知に不可欠な側線系は進行例で永続的に損傷される。",
        "prevention": "栄養豊富で多様な食餌（ビタミン・ミネラル強化）、定期的な水換え、活性炭の長期使用を避ける。",
        "prevention_ja": "栄養豊富で多様な食餌（ビタミン・ミネラル強化）、定期的な水換え、活性炭の長期使用を避ける。",
        "prognosis": "Chronic and slowly progressive. Early-stage lesions may heal with dietary correction and metronidazole. Advanced deep craters are irreversible and leave permanent scarring.",
        "prognosis_ja": "慢性かつ緩徐進行性。初期病変は食餌改善とメトロニダゾールで治癒しうる。進行した深いクレーターは不可逆的で永続的な瘢痕を残す。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Hexamita / Spironucleus (Internal Flagellates)",
        "name_ja": "ヘキサミタ症（内部鞭毛虫症）",
        "symptoms": {"white_stringy_feces", "loss_of_appetite", "emaciation", "dark_coloration", "lethargy", "hiding"},
        "description": "Internal flagellate protozoan infection. Common in cichlids, discus, and angelfish.",
        "description_ja": "内部寄生性鞭毛虫感染。シクリッド、ディスカス、エンゼルフィッシュに多い。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam_microscopy"],
        "treatment": "メトロニダゾール薬餌または浴、水温上昇、栄養改善。",
        "treatment_ja": "メトロニダゾール薬餌または浴、水温上昇、栄養改善。",
        "causes": "Intestinal flagellate protozoa Hexamita salmonis or Spironucleus spp. Stress, poor diet, overcrowding, and suboptimal water quality allow the normally commensal organisms to proliferate pathologically.",
        "causes_ja": "腸管鞭毛虫 Hexamita salmonis または Spironucleus 属。ストレス、栄養不良、過密、水質不良により、通常は共生的な微生物が病的に増殖。",
        "pathophysiology": "Flagellates colonize the intestinal lumen and invade mucosal epithelium, causing malabsorption and chronic enteritis. Nutrient malabsorption leads to progressive emaciation and white stringy mucoid feces. Systemic spread to other organs (gall bladder, kidney) can occur in severe cases.",
        "pathophysiology_ja": "鞭毛虫が腸管内腔にコロニーを形成し粘膜上皮に侵入、吸収不良と慢性腸炎を引き起こす。栄養吸収障害は進行性の消耗と白い糸状粘液便を招く。重症例では他臓器（胆嚢、腎臓）への全身播種が起こりうる。",
        "prevention": "バランスの取れた栄養豊富な食餌、過密回避、定期的な水換え。新規魚の検疫。",
        "prevention_ja": "バランスの取れた栄養豊富な食餌、過密回避、定期的な水換え。新規魚の検疫。",
        "prognosis": "Fair to good with early metronidazole treatment and dietary improvement. Advanced cases with systemic involvement carry guarded prognosis.",
        "prognosis_ja": "早期のメトロニダゾール治療と食餌改善でやや良好〜良好。全身播種を伴う進行例の予後は慎重。",
        "onset_pattern": {"subacute", "chronic"},
    },
    {
        "name": "Mycobacteriosis (Fish Tuberculosis)",
        "name_ja": "抗酸菌症（魚結核）",
        "symptoms": {"emaciation", "lethargy", "loss_of_appetite", "ulcers", "bent_spine", "pop_eye", "scale_loss", "dark_coloration"},
        "description": "Chronic bacterial infection caused by Mycobacterium marinum and related species. Zoonotic — can cause granulomas in humans.",
        "description_ja": "Mycobacterium marinum 等による慢性細菌感染。人獣共通感染症 — ヒトに肉芽腫を形成しうる。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "histopathology", "pcr"],
        "treatment": "効果的な治療法はない。感染魚の隔離・淘汰が推奨。水槽・器具の徹底消毒。素手での取り扱いを避ける。",
        "treatment_ja": "効果的な治療法はない。感染魚の隔離・淘汰が推奨。水槽・器具の徹底消毒。素手での取り扱いを避ける。",
        "causes": "Chronic infection by Mycobacterium marinum, M. fortuitum, or M. chelonae. Transmitted via ingestion of infected tissue, contaminated water, or open wounds. Zoonotic risk — can cause skin granulomas in humans (fish tank granuloma).",
        "causes_ja": "Mycobacterium marinum、M. fortuitum、M. chelonae による慢性感染。感染組織の摂食、汚染水、開放創から伝播。人獣共通感染症 — ヒトに皮膚肉芽腫（フィッシュタンク肉芽腫）を起こしうる。",
        "pathophysiology": "Mycobacteria survive within macrophages, forming granulomas in multiple organs (kidney, liver, spleen, skin). Chronic granulomatous inflammation leads to progressive organ destruction and cachexia. The intracellular survival strategy makes the infection refractory to most antibiotic treatments.",
        "pathophysiology_ja": "抗酸菌はマクロファージ内で生存し、複数臓器（腎、肝、脾、皮膚）に肉芽腫を形成。慢性肉芽腫性炎症が進行性の臓器破壊と悪液質を招く。細胞内生存戦略により大半の抗菌薬治療に抵抗性。",
        "prevention": "新規魚の検疫と観察、死魚の速やかな除去、器具の消毒。感染が疑われる水槽での素手作業を避ける（手袋着用）。",
        "prevention_ja": "新規魚の検疫と観察、死魚の速やかな除去、器具の消毒。感染が疑われる水槽での素手作業を避ける（手袋着用）。",
        "prognosis": "予後不良。慢性進行性で治癒は困難。",
        "prognosis_ja": "予後不良。慢性進行性で治癒は困難。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Ammonia Poisoning",
        "name_ja": "アンモニア中毒",
        "symptoms": {"gasping_surface", "gill_redness", "redness_skin", "lethargy", "erratic_swimming", "loss_of_appetite", "rapid_gill_movement", "mucus_overproduction"},
        "description": "Toxic condition caused by elevated ammonia levels, typically in new or overstocked aquariums.",
        "description_ja": "アンモニア濃度の上昇による中毒。新規立ち上げ水槽や過密飼育水槽で発生しやすい。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_test"],
        "treatment": "即座に大量換水（50-75%）。バクテリア添加剤の使用、給餌量の削減、アンモニア除去剤の使用。",
        "treatment_ja": "即座に大量換水（50-75%）。バクテリア添加剤の使用、給餌量の削減、アンモニア除去剤の使用。",
        "causes": "Accumulation of unionized ammonia (NH3) from fish waste, uneaten food, and decaying organic matter. Most common in new tanks lacking established nitrifying bacteria (New Tank Syndrome), overstocked tanks, or after filter failure.",
        "causes_ja": "魚の排泄物、残餌、有機物分解からの非イオン化アンモニア（NH3）の蓄積。硝化細菌が定着していない新規水槽（ニュータンクシンドローム）、過密水槽、フィルター故障後に最も多い。",
        "pathophysiology": "Unionized ammonia (NH3) crosses gill membranes and is directly cytotoxic. It damages gill epithelium causing edema, hyperplasia, and lamellar fusion, impairing gas exchange. NH3 also crosses the blood-brain barrier, causing CNS excitation (erratic swimming) followed by depression. Chronic sublethal exposure causes gill hyperplasia and immunosuppression.",
        "pathophysiology_ja": "非イオン化アンモニア（NH3）は鰓膜を通過し直接細胞毒性を示す。鰓上皮を損傷し浮腫、過形成、弁融合を起こしガス交換を障害。NH3は血液脳関門も通過し、CNS興奮（異常遊泳）後に抑制を引き起こす。慢性亜致死濃度暴露は鰓過形成と免疫抑制を引き起こす。",
        "prevention": "水槽の適切な立ち上げ（サイクリング）、過密飼育回避、適切なフィルター、定期的な水質検査。",
        "prevention_ja": "水槽の適切な立ち上げ（サイクリング）、過密飼育回避、適切なフィルター、定期的な水質検査。",
        "prognosis": "Good if caught early and water is corrected promptly. Chronic gill damage may persist. Severe acute exposure can cause mass mortality.",
        "prognosis_ja": "早期発見・速やかな水質是正で予後良好。慢性の鰓損傷は持続しうる。重度の急性暴露は大量死を招く。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Nitrite Poisoning (Brown Blood Disease)",
        "name_ja": "亜硝酸中毒（褐色血液病）",
        "symptoms": {"gasping_surface", "gill_paleness", "lethargy", "dark_coloration", "rapid_gill_movement", "sudden_death"},
        "description": "Caused by elevated nitrite levels which convert hemoglobin to methemoglobin, reducing oxygen-carrying capacity.",
        "description_ja": "亜硝酸濃度の上昇によりヘモグロビンがメトヘモグロビンに変換され、酸素運搬能が低下。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_test"],
        "treatment": "大量換水、塩の添加（0.1-0.3% — 塩素イオンが亜硝酸の取り込みを阻害）、エアレーション強化。",
        "treatment_ja": "大量換水、塩の添加（0.1-0.3% — 塩素イオンが亜硝酸の取り込みを阻害）、エアレーション強化。",
        "causes": "Accumulation of nitrite (NO2-) from incomplete nitrification. Occurs during tank cycling when Nitrosomonas bacteria convert ammonia to nitrite faster than Nitrospira/Nitrobacter convert nitrite to nitrate.",
        "causes_ja": "不完全な硝化による亜硝酸（NO2-）の蓄積。水槽の立ち上げ期にニトロソモナスがアンモニアを亜硝酸に変換する速度がニトロスピラ/ニトロバクターの硝酸への変換速度を上回る時に発生。",
        "pathophysiology": "Nitrite is actively absorbed across gills via chloride channels. It oxidizes hemoglobin to methemoglobin (MetHb), which cannot bind oxygen. Blood turns chocolate-brown. Even with adequate dissolved oxygen, tissues become hypoxic. Chloride ion (from salt addition) competitively inhibits nitrite uptake at the gill.",
        "pathophysiology_ja": "亜硝酸は鰓の塩素チャネルを介して能動的に吸収される。ヘモグロビンをメトヘモグロビン（MetHb）に酸化し、酸素結合能を失わせる。血液はチョコレート褐色に変色。溶存酸素が十分でも組織は低酸素に陥る。塩素イオン（塩添加）は鰓での亜硝酸取り込みを競合的に阻害する。",
        "prevention": "水槽の適切なサイクリング、定期的な水質検査（特にNO2-）、過密回避、十分な生物ろ過。",
        "prevention_ja": "水槽の適切なサイクリング、定期的な水質検査（特にNO2-）、過密回避、十分な生物ろ過。",
        "prognosis": "Good if treated promptly with water changes and salt. Severe methemoglobinemia (>70% MetHb) is usually fatal.",
        "prognosis_ja": "速やかな換水と塩添加で予後良好。重度のメトヘモグロビン血症（MetHb 70%超）は通常致死的。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "pH Shock",
        "name_ja": "pH ショック",
        "symptoms": {"erratic_swimming", "gasping_surface", "mucus_overproduction", "lethargy", "sudden_death", "mass_mortality"},
        "description": "Acute stress caused by rapid pH changes. Even small rapid shifts can be fatal.",
        "description_ja": "急激なpH変化によるショック。わずかな急変でも致死的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["water_quality_test"],
        "treatment": "緩やかな水質調整。急変の原因特定と除去。重度のショックには回復困難な場合がある。",
        "treatment_ja": "緩やかな水質調整。急変の原因特定と除去。重度のショックには回復困難な場合がある。",
        "causes": "Rapid pH change (>0.5 units in <24h) from large water changes without matching pH, substrate changes, medication overdose, or CO2 system malfunction. Both acid and alkaline crashes are dangerous.",
        "causes_ja": "急激なpH変化（24時間以内に0.5以上）。pH未調整の大量換水、底砂変更、薬剤過量投与、CO2システム故障が原因。酸性・アルカリ性いずれの急変も危険。",
        "pathophysiology": "Rapid pH change disrupts the ionic balance across gill membranes. Acid pH denatures gill mucus and damages epithelium; alkaline pH causes ammonia toxicity (higher proportion of toxic NH3). Osmotic stress leads to electrolyte imbalance, mucus hypersecretion, and epithelial necrosis. Severe cases result in cardiovascular collapse.",
        "pathophysiology_ja": "急激なpH変化が鰓膜を介したイオンバランスを破壊。酸性pHは鰓粘液を変性させ上皮を損傷、アルカリ性pHはアンモニア毒性を増大（毒性NH3の比率上昇）。浸透圧ストレスが電解質不均衡、粘液過分泌、上皮壊死を招く。重症例は心血管虚脱に至る。",
        "prevention": "換水時のpH合わせ、CO2システムの安全装置（ソレノイドバルブ）設置、pH計による定期モニタリング。",
        "prevention_ja": "換水時のpH合わせ、CO2システムの安全装置（ソレノイドバルブ）設置、pH計による定期モニタリング。",
        "prognosis": "Depends on severity and speed of correction. Mild pH shifts are reversible. Acute crashes causing mass mortality are usually irreversible.",
        "prognosis_ja": "重症度と是正速度に依存。軽度のpH変動は可逆的。大量死を伴う急性の崩壊は通常不可逆。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Costia (Ichthyobodo)",
        "name_ja": "コスチア症（イクチオボド症）",
        "symptoms": {"mucus_overproduction", "white_film", "flashing", "clamped_fins", "gill_mucus", "rapid_gill_movement", "lethargy"},
        "description": "Protozoan ectoparasite that causes excessive mucus production and skin irritation.",
        "description_ja": "体表に寄生する原虫。過剰な粘液産生と皮膚刺激を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy"],
        "treatment": "ホルマリン浴、塩水浴、マラカイトグリーン浴、水温上昇。",
        "treatment_ja": "ホルマリン浴、塩水浴、マラカイトグリーン浴、水温上昇。",
        "causes": "Flagellate protozoan Ichthyobodo necator (formerly Costia). Normally present at low levels; becomes pathogenic under stress, poor water quality, or cold temperatures (<15°C).",
        "causes_ja": "鞭毛虫 Ichthyobodo necator（旧名コスチア）。通常は低レベルで存在し、ストレス、水質不良、低水温（15°C未満）で病原性を発揮。",
        "pathophysiology": "Ichthyobodo attaches to skin and gill epithelium via a ventral feeding groove, lysing host cells. Massive mucus hypersecretion creates a characteristic grey-white film. Gill infestation impairs gas exchange. The parasite divides rapidly by binary fission, with populations doubling in hours under favorable conditions.",
        "pathophysiology_ja": "イクチオボドが腹側の摂食溝で皮膚・鰓上皮に付着し宿主細胞を溶解。大量の粘液過分泌が特徴的な灰白色の膜を形成。鰓寄生はガス交換を障害。好条件下では二分裂により数時間で個体数が倍増。",
        "prevention": "水質管理、ストレス軽減、過密回避。新規魚の検疫。",
        "prevention_ja": "水質管理、ストレス軽減、過密回避。新規魚の検疫。",
        "prognosis": "Good with prompt treatment. Heavy gill infestation in fry/juveniles can cause rapid mortality.",
        "prognosis_ja": "速やかな治療で予後良好。仔魚・稚魚の重度鰓寄生は急速な死亡を招きうる。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Trichodina",
        "name_ja": "トリコディナ症",
        "symptoms": {"flashing", "mucus_overproduction", "gill_mucus", "clamped_fins", "lethargy", "loss_of_appetite", "white_film"},
        "description": "Ciliate protozoan ectoparasite. Usually secondary to poor water quality or immunosuppression.",
        "description_ja": "体表に寄生する繊毛虫。水質悪化や免疫低下に続発することが多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scrape_microscopy"],
        "treatment": "ホルマリン浴、塩水浴、水質改善。根本原因の是正が重要。",
        "treatment_ja": "ホルマリン浴、塩水浴、水質改善。根本原因の是正が重要。",
        "causes": "Ciliate protozoan ectoparasite Trichodina spp. Disc-shaped, rotates on the fish surface. Usually secondary to immunosuppression from poor water quality, overcrowding, or chronic stress.",
        "causes_ja": "繊毛虫外部寄生虫 Trichodina 属。円盤状で魚体表面を回転移動。通常、水質不良・過密・慢性ストレスによる免疫低下に続発。",
        "pathophysiology": "Trichodina glides over skin and gill surfaces using its ciliary girdle, feeding on epithelial cells and bacteria. The central denticle ring causes mechanical abrasion. Chronic irritation leads to epithelial hyperplasia and excess mucus production. Trichodina is often an indicator of suboptimal husbandry rather than a primary pathogen.",
        "pathophysiology_ja": "トリコディナは繊毛帯で皮膚・鰓表面を滑走し、上皮細胞と細菌を摂食。中央の歯状リングが機械的摩擦を引き起こす。慢性的な刺激が上皮過形成と過剰粘液産生を招く。トリコディナは一次病原体というより飼育管理不良の指標であることが多い。",
        "prevention": "適切な水質管理（特にアンモニア・亜硝酸）、過密回避、定期的な水換え。",
        "prevention_ja": "適切な水質管理（特にアンモニア・亜硝酸）、過密回避、定期的な水換え。",
        "prognosis": "Excellent once water quality is corrected. Trichodina rarely causes mortality on its own but indicates underlying husbandry issues that must be addressed.",
        "prognosis_ja": "水質改善により予後は極めて良好。トリコディナ単独での致死はまれだが、対処すべき飼育管理上の問題を示唆する。",
        "onset_pattern": {"subacute"},
    },
    {
        "name": "Lymphocystis",
        "name_ja": "リンホシスチス病",
        "symptoms": {"lumps_nodules", "white_spots", "clamped_fins"},
        "description": "Viral disease causing cauliflower-like growths on skin and fins. Self-limiting in most cases.",
        "description_ja": "皮膚と鰭にカリフラワー状の増殖物を形成するウイルス性疾患。多くの場合は自然治癒。",
        "urgency": "low",
        "recommended_tests": ["histopathology"],
        "treatment": "特異的治療なし。自然治癒を待つ。二次感染予防に水質管理。重度の場合は外科的除去。",
        "treatment_ja": "特異的治療なし。自然治癒を待つ。二次感染予防に水質管理。重度の場合は外科的除去。",
        "causes": "Iridovirus (Lymphocystis disease virus, LCDV). Transmitted via direct contact with infected fish or contaminated water. Stress and skin abrasions facilitate infection.",
        "causes_ja": "イリドウイルス（リンホシスチス病ウイルス、LCDV）。感染魚との接触または汚染水を介して伝播。ストレスと皮膚擦過が感染を促進。",
        "pathophysiology": "LCDV infects dermal fibroblasts, causing massive cellular hypertrophy (cells enlarge up to 100,000x normal size). The enlarged cells form characteristic grape-like or cauliflower-like clusters on skin and fins. The virus does not cause systemic infection; the immune system eventually clears it.",
        "pathophysiology_ja": "LCDVが真皮線維芽細胞に感染し、著明な細胞肥大（正常の最大10万倍）を引き起こす。肥大した細胞が皮膚・鰭にブドウ状またはカリフラワー状の集塊を形成。全身感染は起こさず、最終的に免疫系がウイルスを排除する。",
        "prevention": "新規魚の検疫・観察、ストレス軽減、外傷防止。",
        "prevention_ja": "新規魚の検疫・観察、ストレス軽減、外傷防止。",
        "prognosis": "Excellent. Self-limiting disease that typically resolves in weeks to months. Rarely life-threatening unless lesions obstruct the mouth or gills.",
        "prognosis_ja": "予後は極めて良好。自然治癒する疾患で通常数週間〜数ヶ月で消退。口や鰓を閉塞しない限り生命を脅かすことはまれ。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Koi Herpesvirus Disease (KHV / CyHV-3)",
        "name_ja": "コイヘルペスウイルス病（KHV）",
        "symptoms": {"gill_redness", "gill_swelling", "gill_paleness", "gasping_surface", "lethargy", "loss_of_appetite", "sunken_eye", "mucus_overproduction", "mass_mortality"},
        "description": "Highly contagious viral disease of common and koi carp. Notifiable disease in many countries. Mortality can reach 80-100%.",
        "description_ja": "マゴイ・ニシキゴイの高伝染性ウイルス疾患。多くの国で届出義務あり。致死率は80-100%に達しうる。",
        "urgency": "emergency",
        "recommended_tests": ["pcr", "virus_isolation", "histopathology"],
        "treatment": "特異的治療なし。発症水域の隔離・移動制限。水温を30°C以上に上昇させることで症状が軽減する場合がある（キャリア化のリスクあり）。",
        "treatment_ja": "特異的治療なし。発症水域の隔離・移動制限。水温を30°C以上に上昇させることで症状が軽減する場合がある（キャリア化のリスクあり）。",
        "causes": "Cyprinid herpesvirus 3 (CyHV-3). Highly contagious; transmitted via water, mucus, feces, and fomites. Active at 18-28°C (peak at 22-25°C). Affects only common carp (Cyprinus carpio) and koi.",
        "causes_ja": "コイヘルペスウイルス3型（CyHV-3）。極めて感染力が強く、水、粘液、糞便、媒介物を介して伝播。18-28°C（ピーク22-25°C）で活性化。マゴイとニシキゴイのみが感受性。",
        "pathophysiology": "CyHV-3 targets gill, kidney, and intestinal epithelium. Gill necrosis causes respiratory failure — the primary cause of death. Skin produces thick mucus that subsequently sloughs off, leaving the fish vulnerable to secondary infections. Surviving fish become latent carriers with virus persisting in leukocytes.",
        "pathophysiology_ja": "CyHV-3は鰓、腎臓、腸管上皮を標的とする。鰓壊死が呼吸不全を引き起こし、主要な死因となる。皮膚は厚い粘液を産生し、その後剥離して二次感染に脆弱となる。生残魚はウイルスが白血球に潜伏する潜伏キャリアとなる。",
        "prevention": "新規コイの厳格な検疫（3-4週間、18-25°Cで）、水系の隔離、器具の消毒。一部の国ではワクチンが利用可能だがキャリア化のリスクあり。",
        "prevention_ja": "新規コイの厳格な検疫（3-4週間、18-25°Cで）、水系の隔離、器具の消毒。一部の国ではワクチンが利用可能だがキャリア化のリスクあり。",
        "prognosis": "予後極めて不良。生残魚はキャリアとなり感染源となる。",
        "prognosis_ja": "予後極めて不良。生残魚はキャリアとなり感染源となる。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Spring Viremia of Carp (SVC)",
        "name_ja": "コイ春ウイルス血症（SVC）",
        "symptoms": {"bloating", "dropsy", "pop_eye", "redness_skin", "fin_hemorrhage", "lethargy", "loss_of_appetite", "erratic_swimming", "mass_mortality"},
        "description": "Viral disease of cyprinids caused by Rhabdovirus carpio. Occurs in spring when water temperatures rise to 10-17°C.",
        "description_ja": "ラブドウイルス・カルピオによるコイ科魚類のウイルス疾患。水温が10-17°Cに上昇する春に発生。",
        "urgency": "emergency",
        "recommended_tests": ["pcr", "virus_isolation"],
        "treatment": "特異的治療なし。支持療法、二次感染予防、ストレス軽減。届出義務のある疾患。",
        "treatment_ja": "特異的治療なし。支持療法、二次感染予防、ストレス軽減。届出義務のある疾患。",
        "causes": "Carp sprivivirus (Rhabdovirus carpio). Transmitted via water, feces, and ectoparasites (fish lice, leeches). Occurs when water temperature rises to 10-17°C in spring. Notifiable disease (OIE-listed).",
        "causes_ja": "コイスプリビウイルス（ラブドウイルス・カルピオ）。水、糞便、外部寄生虫（ウオジラミ、ヒル）を介して伝播。春の水温上昇（10-17°C）時に発生。届出義務疾患（OIE指定）。",
        "pathophysiology": "The virus targets vascular endothelium, causing widespread vasculitis and hemorrhage in internal organs. Kidney and spleen necrosis leads to fluid accumulation (ascites/dropsy). Viremia results in petechial hemorrhages in skin, fins, and peritoneum. Immunosuppression from viral infection facilitates secondary bacterial septicemia.",
        "pathophysiology_ja": "ウイルスが血管内皮を標的とし、広範な血管炎と内臓出血を引き起こす。腎臓・脾臓の壊死が体液貯留（腹水/浮腫）を招く。ウイルス血症により皮膚・鰭・腹膜に点状出血が生じる。ウイルス感染による免疫抑制が二次細菌性敗血症を促進。",
        "prevention": "輸入魚の検疫、水温10-17°C域での新規導入の回避、外部寄生虫の駆除（媒介予防）。",
        "prevention_ja": "輸入魚の検疫、水温10-17°C域での新規導入の回避、外部寄生虫の駆除（媒介予防）。",
        "prognosis": "Poor. Mortality rates of 30-70% are typical. Survivors may develop immunity but can remain carriers.",
        "prognosis_ja": "予後不良。致死率は通常30-70%。生残魚は免疫を獲得しうるがキャリアとなる可能性あり。",
        "onset_pattern": {"acute"},
    },
    {
        "name": "Neon Tetra Disease (Pleistophora)",
        "name_ja": "ネオン病（プレイストフォラ症）",
        "symptoms": {"discoloration", "emaciation", "bent_spine", "isolation", "loss_of_appetite", "erratic_swimming"},
        "description": "Microsporidian infection (Pleistophora hyphessobryconis) affecting small tetras. Causes progressive muscle degeneration.",
        "description_ja": "微胞子虫（Pleistophora hyphessobryconis）による感染。小型テトラに多く、進行性の筋肉変性を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["histopathology", "skin_scrape_microscopy"],
        "treatment": "効果的な治療法なし。感染魚の隔離・淘汰。水槽・器具の消毒。",
        "treatment_ja": "効果的な治療法なし。感染魚の隔離・淘汰。水槽・器具の消毒。",
        "causes": "Microsporidian parasite Pleistophora hyphessobryconis. Transmitted by ingestion of spores from infected tissue (cannibalism of dead fish) or contaminated water. Primarily affects neon tetras, cardinal tetras, and other small Characidae.",
        "causes_ja": "微胞子虫 Pleistophora hyphessobryconis。感染組織（死魚の共食い）や汚染水からの胞子摂取で伝播。主にネオンテトラ、カージナルテトラ等の小型カラシン科に感染。",
        "pathophysiology": "Spores germinate in the intestine and spread systemically via blood. Sporoplasms invade skeletal muscle fibers, replacing myofibrils with masses of spores. Progressive muscle degeneration causes the characteristic fading of the neon stripe (due to destruction of iridophores overlying damaged muscle). Spinal deformity results from asymmetric muscle loss.",
        "pathophysiology_ja": "胞子が腸管内で発芽し血行性に全身播種。スポロプラズムが骨格筋線維に侵入し、筋原線維を大量の胞子に置換。進行性の筋肉変性がネオンストライプの退色を引き起こす（損傷した筋肉上の虹色素胞の破壊による）。非対称の筋肉消失が脊椎変形を招く。",
        "prevention": "死魚の速やかな除去（共食いによる伝播防止）、新規テトラの検疫・観察、感染水槽の器具の隔離。",
        "prevention_ja": "死魚の速やかな除去（共食いによる伝播防止）、新規テトラの検疫・観察、感染水槽の器具の隔離。",
        "prognosis": "予後不良。治癒は見込めない。",
        "prognosis_ja": "予後不良。治癒は見込めない。",
        "onset_pattern": {"chronic"},
    },
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "過抱卵（卵詰まり）",
        "symptoms": {"egg_binding", "bloating", "lethargy", "loss_of_appetite", "hiding"},
        "description": "Inability to release eggs. Common in goldfish, bettas, and cichlids. Can lead to secondary infections.",
        "description_ja": "卵を排出できない状態。金魚、ベタ、シクリッドに多い。二次感染を引き起こしうる。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "ultrasound"],
        "treatment": "水温上昇、エプソムソルト浴、産卵基質の設置。重症例では麻酔下での用手排卵。",
        "treatment_ja": "水温上昇、エプソムソルト浴、産卵基質の設置。重症例では麻酔下での用手排卵。",
        "causes": "Failure to release mature eggs. Causes include absence of spawning triggers (no male present, wrong temperature, no spawning substrate), oviduct obstruction, poor nutrition, or hormonal imbalance. Common in goldfish, bettas, and mouth-brooding cichlids.",
        "causes_ja": "成熟卵の排出不全。産卵刺激の欠如（雄不在、水温不適、産卵基質なし）、卵管閉塞、栄養不良、ホルモン不均衡が原因。金魚、ベタ、マウスブルーダー型シクリッドに多い。",
        "pathophysiology": "Retained eggs undergo necrosis within the ovary, triggering peritonitis and bacterial infection of the coelomic cavity. The distended abdomen compresses swim bladder and other organs. Egg peritonitis can progress to septicemia. In chronic cases, eggs may calcify.",
        "pathophysiology_ja": "貯留卵が卵巣内で壊死し、腹膜炎と体腔内の細菌感染を誘発。膨満した腹部が浮袋と他臓器を圧迫。卵性腹膜炎は敗血症に進行しうる。慢性例では卵が石灰化することがある。",
        "prevention": "適切な雌雄比での飼育、産卵に適した水温と基質の提供、バランスの取れた栄養。",
        "prevention_ja": "適切な雌雄比での飼育、産卵に適した水温と基質の提供、バランスの取れた栄養。",
        "prognosis": "Good if addressed early with environmental manipulation. Poor once egg peritonitis or septicemia develops.",
        "prognosis_ja": "環境調整による早期対応で予後良好。卵性腹膜炎や敗血症に進行した場合は予後不良。",
        "onset_pattern": {"acute", "subacute"},
    },
    {
        "name": "Marine Ich (Cryptocaryon irritans)",
        "name_ja": "海水白点病（クリプトカリオン症）",
        "symptoms": {"white_spots", "flashing", "clamped_fins", "rapid_gill_movement", "loss_of_appetite", "lethargy", "labored_breathing"},
        "description": "Marine equivalent of freshwater Ich, caused by Cryptocaryon irritans. Extremely common in marine aquariums.",
        "description_ja": "淡水白点病の海水版。Cryptocaryon irritans による。海水水槽で極めて一般的。",
        "urgency": "high",
        "recommended_tests": ["skin_scrape_microscopy"],
        "treatment": "銅イオン製剤（治療用水槽で）、低比重法（hyposalinity 1.009）、ホルマリン浴。サンゴ・無脊椎水槽では銅は使用不可。",
        "treatment_ja": "銅イオン製剤（治療用水槽で）、低比重法（hyposalinity 1.009）、ホルマリン浴。サンゴ・無脊椎水槽では銅は使用不可。",
        "causes": "Ciliate protozoan Cryptocaryon irritans. The marine counterpart of freshwater Ich. Introduced via new fish, live rock, or invertebrates without proper quarantine. Stress and suboptimal water parameters trigger outbreaks.",
        "causes_ja": "繊毛虫 Cryptocaryon irritans。淡水白点病の海水版。新規導入魚、ライブロック、無脊椎動物から検疫なしで侵入。ストレスと水質不良が発症を誘発。",
        "pathophysiology": "Life cycle similar to freshwater Ich but longer (2-6 weeks depending on temperature). Trophonts feed within the epithelium of skin and gills. Heavy gill parasitism causes respiratory distress. Unlike freshwater Ich, Cryptocaryon tomonts are more resistant to treatment and the free-swimming theront stage is longer-lived, making eradication more challenging.",
        "pathophysiology_ja": "生活環は淡水白点病と類似するがより長い（水温により2-6週間）。栄養体が皮膚・鰓の上皮内で摂食。重度の鰓寄生は呼吸困難を引き起こす。淡水白点病と異なり、クリプトカリオンのトモントは治療に対する抵抗性が高く、遊走子の寿命も長いため駆除がより困難。",
        "prevention": "全新規魚の厳格な検疫（4-6週間）、導入前の銅治療または低比重処理。リーフタンクでは無脊椎動物も72時間以上の隔離が推奨。",
        "prevention_ja": "全新規魚の厳格な検疫（4-6週間）、導入前の銅治療または低比重処理。リーフタンクでは無脊椎動物も72時間以上の隔離が推奨。",
        "prognosis": "Good with early copper treatment in a hospital tank. Eradication from display tanks requires 6+ weeks of fallow period (no fish). Untreated outbreaks in marine tanks often result in total fish loss.",
        "prognosis_ja": "治療用水槽での早期銅治療で予後良好。ディスプレイ水槽からの駆除には6週間以上の魚なし期間が必要。未治療の海水水槽での発症は全魚喪失に至ることが多い。",
        "onset_pattern": {"acute", "subacute"},
    },
]


def analyze_symptoms(
    symptoms: List[str],
    age_stage: str = "",
    breed: str = None,
    *,
    onset: str = None,
    age_years: float = None,
    species: str = None,
    lab_values: dict = None,
    gender: str = None,
    vaccines: list = None,
    vaccination_status: str = None,
) -> Dict[str, Any]:
    return analyze_symptoms_generic(
        symptoms,
        DISEASES,
        SYMPTOM_NAMES,
        ADVICE,
        onset=onset,
        age_years=age_years,
        breed=breed,
        species=species or "fish",
        lab_values=lab_values,
        gender=gender,
        vaccines=vaccines,
        vaccination_status=vaccination_status,
        prevalence_map=prevalence_data.SPECIES_PREVALENCE.get("fish", {}),
    )


DISEASES = enrich_diseases(DISEASES, "fish")
