"""Guinea pig disease dictionary and analysis module."""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── 栄養性 ──
    {
        "name": "Scurvy (Vitamin C Deficiency)",
        "name_ja": "壊血病（ビタミンC欠乏症）",
        "symptoms": {"lameness", "joint_swelling", "lethargy", "rough_coat", "weight_loss", "bleeding_gums"},
        "description": "Guinea pigs cannot synthesize vitamin C; deficiency causes joint pain and hemorrhage.",
        "description_ja": "モルモットはビタミンCを合成できず、欠乏により関節痛や出血を生じる。",
        "urgency": "high",
        "recommended_tests": ["dietary_review", "radiography", "blood_chemistry"],
    },
    # ── 歯科 ──
    {
        "name": "Dental Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "overgrown_teeth"},
        "description": "Misalignment of cheek teeth causing spurs and tongue/cheek entrapment.",
        "description_ja": "臼歯の不整合によるスパー形成と舌・頬の挟み込み。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Slobbers (Dental-related Drooling)",
        "name_ja": "スロバーズ（歯科関連流涎）",
        "symptoms": {"drooling", "wet_chin", "appetite_loss", "weight_loss"},
        "description": "Excessive drooling from molar spurs cutting tongue or cheeks.",
        "description_ja": "臼歯のスパーが舌や頬を傷つけることによる過度の流涎。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Dental Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "drooling", "eye_discharge"},
        "description": "Tooth root infection causing jaw swelling.",
        "description_ja": "歯根感染による顎の腫脹。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "ct_scan", "bacterial_culture"],
    },
    # ── 消化器系 ──
    {
        "name": "GI Stasis",
        "name_ja": "消化管うっ滞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "lethargy", "abdominal_distension"},
        "description": "Slowdown of gut motility from stress, pain, or dietary issues.",
        "description_ja": "ストレス、疼痛、食事問題による腸管運動の低下。",
        "urgency": "high",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Bloat (Gastric Dilation)",
        "name_ja": "鼓脹症（胃拡張）",
        "symptoms": {"abdominal_distension", "labored_breathing", "lethargy", "appetite_loss", "pain"},
        "description": "Acute gas distension of the stomach or intestines.",
        "description_ja": "胃または腸のガスによる急性拡張。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Diarrhea (Non-specific)",
        "name_ja": "下痢（非特異的）",
        "symptoms": {"diarrhea", "dehydration", "appetite_loss", "weight_loss"},
        "description": "Loose stools from diet change, stress, or infection.",
        "description_ja": "食事変化、ストレス、感染による軟便。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "dietary_review"],
    },
    {
        "name": "Constipation / Impaction",
        "name_ja": "便秘・糞塊閉塞",
        "symptoms": {"constipation", "reduced_fecal_output", "straining", "appetite_loss"},
        "description": "Difficulty passing stool, may require manual removal in older boars.",
        "description_ja": "排便困難で、高齢オスでは手動除去が必要な場合がある。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Enteritis (Bacterial)",
        "name_ja": "細菌性腸炎",
        "symptoms": {"diarrhea", "dehydration", "lethargy", "appetite_loss", "bloody_stool"},
        "description": "Bacterial infection of the intestines (Salmonella, E. coli, Clostridium).",
        "description_ja": "サルモネラ、大腸菌、クロストリジウムなどによる腸の細菌感染。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "complete_blood_count"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"rectal_prolapse", "straining", "bloody_stool"},
        "description": "Protrusion of rectal tissue secondary to diarrhea or straining.",
        "description_ja": "下痢やいきみに続発する直腸組織の脱出。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス",
        "symptoms": {"appetite_loss", "lethargy", "jaundice", "weight_loss"},
        "description": "Fatty liver from anorexia or obesity.",
        "description_ja": "食欲不振や肥満による脂肪肝。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound"],
    },
    # ── 呼吸器系 ──
    {
        "name": "Pneumonia (Bordetella)",
        "name_ja": "肺炎（ボルデテラ）",
        "symptoms": {"labored_breathing", "nasal_discharge", "sneezing", "lethargy", "appetite_loss"},
        "description": "Bordetella bronchiseptica bacterial pneumonia, common and often fatal.",
        "description_ja": "ボルデテラ菌による細菌性肺炎で、よく見られ致死的なことが多い。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bacterial_culture"],
    },
    {
        "name": "Pneumonia (Streptococcal)",
        "name_ja": "肺炎（レンサ球菌）",
        "symptoms": {"labored_breathing", "nasal_discharge", "lethargy", "fever", "sudden_death"},
        "description": "Streptococcus pneumoniae lung infection.",
        "description_ja": "肺炎球菌による肺感染。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bacterial_culture"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"sneezing", "nasal_discharge", "eye_discharge", "wheezing"},
        "description": "Infection of nasal passages and sinuses.",
        "description_ja": "鼻腔および副鼻腔の感染。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "bacterial_culture"],
    },
    # ── 皮膚科 ──
    {
        "name": "Trixacarus Mange (Sarcoptic Mange)",
        "name_ja": "トリキサカルス疥癬",
        "symptoms": {"severe_itching", "hair_loss", "skin_crusting", "seizures_from_pain", "scratching"},
        "description": "Severe burrowing mite infestation causing extreme pruritus, may trigger seizures.",
        "description_ja": "穿孔性ダニの重度寄生で強い痒みを引き起こし、痙攣を誘発することがある。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Static Lice (Gliricola/Gyropus)",
        "name_ja": "シラミ寄生",
        "symptoms": {"itching", "hair_loss", "visible_parasites", "scratching"},
        "description": "Chewing lice visible as small moving insects on fur.",
        "description_ja": "被毛上に小さな動く虫として見えるシラミの寄生。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "microscopy"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"hair_loss", "skin_crusting", "circular_lesions", "skin_flaking"},
        "description": "Trichophyton mentagrophytes fungal infection.",
        "description_ja": "白癬菌による真菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "woods_lamp"],
    },
    {
        "name": "Barbering",
        "name_ja": "毛引き行動",
        "symptoms": {"hair_loss", "skin_redness"},
        "description": "Fur chewing by self or dominant cage mate.",
        "description_ja": "自己または優位な同居個体による毛噛み。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review"],
    },
    {
        "name": "Pododermatitis (Bumblefoot)",
        "name_ja": "趾瘤症（バンブルフット）",
        "symptoms": {"foot_sores", "lameness", "swelling", "pain"},
        "description": "Pressure sores on feet from wire or hard flooring and obesity.",
        "description_ja": "金網や硬い床面と肥満による足裏の圧迫性潰瘍。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Skin Abscess",
        "name_ja": "皮膚膿瘍",
        "symptoms": {"skin_lump", "swelling", "discharge", "pain"},
        "description": "Localized bacterial infection, often from bite wounds.",
        "description_ja": "咬傷から生じる限局性の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "bacterial_culture"],
    },
    {
        "name": "Alopecia (Hormonal)",
        "name_ja": "脱毛症（ホルモン性）",
        "symptoms": {"hair_loss", "bilateral_symmetry", "skin_darkening"},
        "description": "Symmetrical hair loss from ovarian cysts or adrenal issues.",
        "description_ja": "卵巣嚢胞や副腎異常による対称性の脱毛。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "ultrasound"],
    },
    # ── 生殖器系 ──
    {
        "name": "Ovarian Cysts",
        "name_ja": "卵巣嚢胞",
        "symptoms": {"bilateral_hair_loss", "abdominal_distension", "skin_crusting", "aggression"},
        "description": "Very common in intact sows over 1 year; may cause bilateral flank alopecia.",
        "description_ja": "1歳以上の未避妊メスに非常に多く、両側腹部の脱毛を引き起こすことがある。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "hormone_panel"],
    },
    {
        "name": "Pregnancy Toxemia (Ketosis)",
        "name_ja": "妊娠中毒症（ケトーシス）",
        "symptoms": {"appetite_loss", "lethargy", "labored_breathing", "seizures", "sudden_death"},
        "description": "Metabolic emergency in late pregnancy, especially in obese sows.",
        "description_ja": "妊娠後期の代謝性緊急疾患で、特に肥満メスに多い。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "vaginal_bleeding", "lethargy", "abdominal_distension"},
        "description": "Difficulty giving birth, common if first pregnancy after 7 months of age.",
        "description_ja": "分娩困難で、7ヶ月齢以降の初産に多い。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "abdominal_distension", "lethargy", "appetite_loss", "fever"},
        "description": "Uterine infection with pus accumulation.",
        "description_ja": "子宮の細菌感染による膿の蓄積。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "complete_blood_count"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "mammary_redness", "fever", "appetite_loss"},
        "description": "Infection of the mammary glands.",
        "description_ja": "乳腺の感染。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "physical_exam"],
    },
    {
        "name": "Mammary Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "skin_lump", "weight_loss"},
        "description": "Benign or malignant mammary gland tumors.",
        "description_ja": "良性または悪性の乳腺腫瘍。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy"],
    },
    # ── 感染症 ──
    {
        "name": "Cervical Lymphadenitis (Lumps Disease)",
        "name_ja": "頸部リンパ節炎（ランプス病）",
        "symptoms": {"neck_swelling", "abscess", "discharge", "appetite_loss"},
        "description": "Streptococcus zooepidemicus causing swollen cervical lymph nodes.",
        "description_ja": "ストレプトコッカス・ズーエピデミクスによる頸部リンパ節の腫脹。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "bacterial_culture"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "sudden_death"},
        "description": "Zoonotic bacterial infection, often fatal in guinea pigs.",
        "description_ja": "人獣共通の細菌感染で、モルモットではしばしば致命的。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_culture", "complete_blood_count"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "appetite_loss", "labored_breathing", "sudden_death"},
        "description": "Systemic bacterial infection.",
        "description_ja": "全身性細菌感染。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count"],
    },
    # ── 泌尿器系 ──
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"blood_in_urine", "straining_to_urinate", "pain", "frequent_urination"},
        "description": "Calcium carbonate or oxalate stones in the urinary tract.",
        "description_ja": "炭酸カルシウムまたはシュウ酸カルシウム結石。",
        "urgency": "high",
        "recommended_tests": ["radiography", "urinalysis", "ultrasound"],
    },
    {
        "name": "Cystitis",
        "name_ja": "膀胱炎",
        "symptoms": {"blood_in_urine", "frequent_urination", "straining_to_urinate", "pain"},
        "description": "Bacterial bladder infection.",
        "description_ja": "膀胱の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "bacterial_culture"],
    },
    {
        "name": "Chronic Renal Failure",
        "name_ja": "慢性腎不全",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function.",
        "description_ja": "腎機能の進行性低下。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    # ── 循環器系 ──
    {
        "name": "Heart Disease",
        "name_ja": "心疾患",
        "symptoms": {"labored_breathing", "lethargy", "cyanosis", "reduced_activity"},
        "description": "Various cardiac conditions in older guinea pigs.",
        "description_ja": "高齢モルモットの各種心疾患。",
        "urgency": "high",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Pericardial Effusion",
        "name_ja": "心嚢液貯留",
        "symptoms": {"labored_breathing", "lethargy", "weakness", "muffled_heart_sounds"},
        "description": "Fluid accumulation around the heart.",
        "description_ja": "心臓周囲の液体貯留。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "radiography"],
    },
    # ── 眼科 ──
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "squinting"},
        "description": "Inflammation of the conjunctiva.",
        "description_ja": "結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "bacterial_culture"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "eye_discharge", "cloudy_eyes", "pain"},
        "description": "Erosion of the cornea from hay or bedding injury.",
        "description_ja": "牧草や床材による角膜のびらん。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudy_eyes", "vision_loss"},
        "description": "Lens opacity in older guinea pigs or from diabetes.",
        "description_ja": "高齢や糖尿病による水晶体の混濁。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam"],
    },
    {
        "name": "Entropion",
        "name_ja": "眼瞼内反",
        "symptoms": {"squinting", "eye_discharge", "eye_redness"},
        "description": "Inward rolling eyelid causing corneal irritation.",
        "description_ja": "眼瞼の内反による角膜刺激。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam"],
    },
    {
        "name": "Pea Eye (Conjunctival Protrusion)",
        "name_ja": "ピーアイ（結膜突出）",
        "symptoms": {"eye_swelling", "conjunctival_mass"},
        "description": "Fatty protrusion of the conjunctiva, common in certain breeds.",
        "description_ja": "結膜の脂肪性突出で、特定の品種に多い。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam"],
    },
    # ── 内分泌・代謝 ──
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy"},
        "description": "Insulin resistance or deficiency.",
        "description_ja": "インスリン抵抗性または不足。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "urinalysis"],
    },
    {
        "name": "Cushing's Disease",
        "name_ja": "クッシング病",
        "symptoms": {"hair_loss", "increased_thirst", "increased_urination", "abdominal_distension"},
        "description": "Adrenal gland overproduction of cortisol.",
        "description_ja": "副腎の過剰コルチゾール産生。",
        "urgency": "high",
        "recommended_tests": ["hormone_panel", "ultrasound"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "reduced_activity", "labored_breathing"},
        "description": "Excess weight from overfeeding and lack of exercise.",
        "description_ja": "過食と運動不足による過体重。",
        "urgency": "low",
        "recommended_tests": ["weight_assessment", "dietary_review"],
    },
    # ── 腫瘍 ──
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "lethargy", "enlarged_lymph_nodes", "appetite_loss"},
        "description": "Malignant lymphatic cancer.",
        "description_ja": "悪性リンパ系腫瘍。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "complete_blood_count"],
    },
    {
        "name": "Skin Tumor",
        "name_ja": "皮膚腫瘍",
        "symptoms": {"skin_lump", "skin_mass_growth", "ulceration"},
        "description": "Trichofolliculoma or other skin tumors.",
        "description_ja": "毛包腫などの皮膚腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "cytology"],
    },
    {
        "name": "Uterine Tumor",
        "name_ja": "子宮腫瘍",
        "symptoms": {"vaginal_bleeding", "abdominal_distension", "weight_loss"},
        "description": "Leiomyoma or other uterine neoplasia.",
        "description_ja": "平滑筋腫などの子宮腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy"],
    },
    # ── 神経系 ──
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "loss_of_balance", "nystagmus", "circling"},
        "description": "Inner ear or brain disorder affecting balance.",
        "description_ja": "内耳または脳の障害で平衡感覚に影響する。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "neurological_exam"],
    },
    {
        "name": "Seizures",
        "name_ja": "痙攣発作",
        "symptoms": {"seizures", "loss_of_consciousness", "tremors", "paddling"},
        "description": "Convulsions from mite pain, toxins, metabolic disease, or pregnancy toxemia.",
        "description_ja": "ダニの痛み、毒素、代謝性疾患、妊娠中毒症による痙攣。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "neurological_exam"],
    },
    {
        "name": "Hind Limb Paralysis",
        "name_ja": "後肢麻痺",
        "symptoms": {"hind_limb_paralysis", "urinary_incontinence", "fecal_incontinence"},
        "description": "Paralysis from spinal injury, vitamin C deficiency, or infection.",
        "description_ja": "脊椎損傷、ビタミンC欠乏、感染による麻痺。",
        "urgency": "high",
        "recommended_tests": ["radiography", "blood_chemistry"],
    },
    # ── 運動器系 ──
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"lameness", "pain", "limb_deformity", "swelling"},
        "description": "Bone fractures from falls or improper handling.",
        "description_ja": "落下や不適切な取り扱いによる骨折。",
        "urgency": "high",
        "recommended_tests": ["radiography"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "stiffness", "reduced_activity", "pain"},
        "description": "Degenerative joint disease.",
        "description_ja": "変性性関節疾患。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    # ── 耳 ──
    {
        "name": "Otitis Media / Interna",
        "name_ja": "中耳炎・内耳炎",
        "symptoms": {"head_tilt", "loss_of_balance", "scratching_ears", "ear_discharge"},
        "description": "Middle or inner ear infection.",
        "description_ja": "中耳または内耳の感染。",
        "urgency": "high",
        "recommended_tests": ["otoscopic_exam", "radiography"],
    },
    {
        "name": "Ear Mites",
        "name_ja": "耳ダニ",
        "symptoms": {"scratching_ears", "head_shaking", "ear_crusting"},
        "description": "Mite infestation of the ear canal.",
        "description_ja": "耳道のダニ寄生。",
        "urgency": "low",
        "recommended_tests": ["otoscopic_exam", "microscopy"],
    },
    # ── 寄生虫 ──
    {
        "name": "Gastrointestinal Parasites",
        "name_ja": "消化管寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "rough_coat"},
        "description": "Infection with various intestinal worms or protozoa.",
        "description_ja": "各種腸内寄生虫や原虫の感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Coccidiosis",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "bloody_stool"},
        "description": "Protozoal parasite infection.",
        "description_ja": "原虫寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float"],
    },
    # ── 環境 ──
    {
        "name": "Heatstroke",
        "name_ja": "熱中症",
        "symptoms": {"labored_breathing", "lethargy", "drooling", "weakness", "seizures"},
        "description": "Hyperthermia; guinea pigs are very sensitive to heat above 26°C.",
        "description_ja": "高体温症で、モルモットは26°C以上の暑さに非常に弱い。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "physical_exam"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"dehydration", "lethargy", "sunken_eyes", "skin_tenting"},
        "description": "Insufficient fluid intake or excess loss.",
        "description_ja": "水分摂取不足または過剰喪失。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Antibiotic Toxicity",
        "name_ja": "抗生物質中毒",
        "symptoms": {"diarrhea", "appetite_loss", "lethargy", "sudden_death"},
        "description": "Fatal dysbiosis from antibiotics unsafe for guinea pigs.",
        "description_ja": "モルモットに不安全な抗生物質による致死的菌交代現象。",
        "urgency": "emergency",
        "recommended_tests": ["medication_review", "fecal_exam"],
    },
    # ── その他 ──
    {
        "name": "Self-Mutilation",
        "name_ja": "自傷行為",
        "symptoms": {"skin_wounds", "hair_loss", "bleeding", "pain"},
        "description": "Self-inflicted injuries from extreme pruritus or stress.",
        "description_ja": "強い掻痒やストレスによる自傷。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "physical_exam"],
    },
    {
        "name": "Fly Strike (Myiasis)",
        "name_ja": "ハエウジ症",
        "symptoms": {"maggots_visible", "foul_odor", "skin_wounds", "lethargy"},
        "description": "Blowfly larvae infestation, life-threatening.",
        "description_ja": "クロバエの幼虫寄生で、致命的。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Boar Impaction (Perineal Sac)",
        "name_ja": "オスの会陰嚢閉塞",
        "symptoms": {"fecal_accumulation", "perianal_swelling", "foul_odor", "straining"},
        "description": "Accumulation of feces in the perineal sac of older boars.",
        "description_ja": "高齢オスの会陰嚢への糞便蓄積。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Cheilitis (Lip Sores)",
        "name_ja": "口唇炎",
        "symptoms": {"lip_crusting", "scabs_around_mouth", "pain"},
        "description": "Crusty sores on the lips, may be bacterial or fungal.",
        "description_ja": "口唇の痂皮性潰瘍で、細菌性または真菌性。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "fungal_culture"],
    },
    {
        "name": "Interstitial Nephritis",
        "name_ja": "間質性腎炎",
        "symptoms": {"increased_thirst", "weight_loss", "lethargy"},
        "description": "Chronic kidney inflammation.",
        "description_ja": "慢性腎臓の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    {
        "name": "Adrenal Disease",
        "name_ja": "副腎疾患",
        "symptoms": {"hair_loss", "bilateral_hair_loss", "lethargy", "skin_darkening"},
        "description": "Adrenal gland tumors or hyperplasia.",
        "description_ja": "副腎腫瘍または過形成。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "hormone_panel"],
    },
    {
        "name": "Fungal Dermatitis",
        "name_ja": "真菌性皮膚炎",
        "symptoms": {"hair_loss", "skin_crusting", "skin_flaking", "itching"},
        "description": "Superficial fungal infection of the skin.",
        "description_ja": "皮膚の表在性真菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping"],
    },
    {
        "name": "Testicular Tumor",
        "name_ja": "精巣腫瘍",
        "symptoms": {"testicular_swelling", "asymmetric_testes"},
        "description": "Tumors of the testes.",
        "description_ja": "精巣の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy"],
    },
    {
        "name": "Vitamin A Deficiency",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"rough_coat", "eye_discharge", "skin_flaking", "weight_loss"},
        "description": "Deficiency causing skin and eye problems.",
        "description_ja": "皮膚・眼の問題を引き起こす欠乏症。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_review"],
    },
    {
        "name": "Abdominal Hernia",
        "name_ja": "腹壁ヘルニア",
        "symptoms": {"abdominal_distension", "skin_lump", "pain"},
        "description": "Protrusion of abdominal contents through the body wall.",
        "description_ja": "腹壁を通じた腹腔内容物の突出。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "ultrasound"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "joint_swelling": {"ja": "関節腫脹", "en": "Joint swelling"},
    "lethargy": {"ja": "元気消失", "en": "Lethargy"},
    "rough_coat": {"ja": "被毛粗剛", "en": "Rough coat"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "bleeding_gums": {"ja": "歯肉出血", "en": "Bleeding gums"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite loss"},
    "overgrown_teeth": {"ja": "歯の過成長", "en": "Overgrown teeth"},
    "wet_chin": {"ja": "濡れた顎", "en": "Wet chin"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "reduced_fecal_output": {"ja": "糞量減少", "en": "Reduced fecal output"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    "pain": {"ja": "痛み", "en": "Pain"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "rectal_prolapse": {"ja": "直腸脱", "en": "Rectal prolapse"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "severe_itching": {"ja": "強い掻痒", "en": "Severe itching"},
    "hair_loss": {"ja": "脱毛", "en": "Hair loss"},
    "skin_crusting": {"ja": "皮膚痂皮", "en": "Skin crusting"},
    "seizures_from_pain": {"ja": "痛みによる痙攣", "en": "Seizures from pain"},
    "scratching": {"ja": "掻き壊し", "en": "Scratching"},
    "itching": {"ja": "掻痒", "en": "Itching"},
    "visible_parasites": {"ja": "寄生虫の目視", "en": "Visible parasites"},
    "skin_flaking": {"ja": "皮膚の剥離", "en": "Skin flaking"},
    "circular_lesions": {"ja": "円形病変", "en": "Circular lesions"},
    "skin_redness": {"ja": "皮膚発赤", "en": "Skin redness"},
    "foot_sores": {"ja": "足裏の潰瘍", "en": "Foot sores"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "skin_lump": {"ja": "皮膚の腫瘤", "en": "Skin lump"},
    "discharge": {"ja": "分泌物", "en": "Discharge"},
    "bilateral_symmetry": {"ja": "両側対称性", "en": "Bilateral symmetry"},
    "skin_darkening": {"ja": "皮膚の色素沈着", "en": "Skin darkening"},
    "bilateral_hair_loss": {"ja": "両側性脱毛", "en": "Bilateral hair loss"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "seizures": {"ja": "痙攣発作", "en": "Seizures"},
    "vaginal_bleeding": {"ja": "膣出血", "en": "Vaginal bleeding"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal discharge"},
    "mammary_swelling": {"ja": "乳腺腫脹", "en": "Mammary swelling"},
    "mammary_redness": {"ja": "乳腺発赤", "en": "Mammary redness"},
    "mammary_mass": {"ja": "乳腺腫瘤", "en": "Mammary mass"},
    "neck_swelling": {"ja": "頸部腫脹", "en": "Neck swelling"},
    "abscess": {"ja": "膿瘍", "en": "Abscess"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in urine"},
    "straining_to_urinate": {"ja": "排尿時のいきみ", "en": "Straining to urinate"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent urination"},
    "increased_thirst": {"ja": "多飲", "en": "Increased thirst"},
    "increased_urination": {"ja": "多尿", "en": "Increased urination"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "reduced_activity": {"ja": "活動性低下", "en": "Reduced activity"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "muffled_heart_sounds": {"ja": "心音減弱", "en": "Muffled heart sounds"},
    "squinting": {"ja": "眼を細める", "en": "Squinting"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "vision_loss": {"ja": "視力喪失", "en": "Vision loss"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "conjunctival_mass": {"ja": "結膜の腫瘤", "en": "Conjunctival mass"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "enlarged_lymph_nodes": {"ja": "リンパ節腫大", "en": "Enlarged lymph nodes"},
    "skin_mass_growth": {"ja": "皮膚腫瘤の増大", "en": "Growing skin mass"},
    "ulceration": {"ja": "潰瘍化", "en": "Ulceration"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "loss_of_balance": {"ja": "平衡感覚喪失", "en": "Loss of balance"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "loss_of_consciousness": {"ja": "意識消失", "en": "Loss of consciousness"},
    "tremors": {"ja": "震え", "en": "Tremors"},
    "paddling": {"ja": "パドリング", "en": "Paddling"},
    "hind_limb_paralysis": {"ja": "後肢麻痺", "en": "Hind limb paralysis"},
    "urinary_incontinence": {"ja": "尿失禁", "en": "Urinary incontinence"},
    "fecal_incontinence": {"ja": "糞便失禁", "en": "Fecal incontinence"},
    "limb_deformity": {"ja": "四肢変形", "en": "Limb deformity"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "scratching_ears": {"ja": "耳を掻く", "en": "Scratching ears"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear discharge"},
    "head_shaking": {"ja": "頭を振る", "en": "Head shaking"},
    "ear_crusting": {"ja": "耳の痂皮", "en": "Ear crusting"},
    "sunken_eyes": {"ja": "眼の陥没", "en": "Sunken eyes"},
    "skin_tenting": {"ja": "皮膚テンティング", "en": "Skin tenting"},
    "skin_wounds": {"ja": "皮膚の傷", "en": "Skin wounds"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "maggots_visible": {"ja": "ウジ虫の目視", "en": "Maggots visible"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "fecal_accumulation": {"ja": "糞便蓄積", "en": "Fecal accumulation"},
    "perianal_swelling": {"ja": "肛門周囲腫脹", "en": "Perianal swelling"},
    "lip_crusting": {"ja": "口唇の痂皮", "en": "Lip crusting"},
    "scabs_around_mouth": {"ja": "口周囲の痂皮", "en": "Scabs around mouth"},
    "testicular_swelling": {"ja": "精巣腫大", "en": "Testicular swelling"},
    "asymmetric_testes": {"ja": "精巣の左右差", "en": "Asymmetric testes"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
