"""Guinea pig disease dictionary and analysis module.

Comprehensive coverage of guinea pig diseases across all major categories:
respiratory, gastrointestinal, dermatological, urinary, reproductive,
musculoskeletal, ophthalmological, neurological, cardiac, metabolic,
dental, oncological, infectious, and parasitic conditions.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic


DISEASES: List[Dict[str, Any]] = [
    # ── Respiratory ──────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection (URI)",
        "name_ja": "上部気道感染症",
        "symptoms": {"nasal_discharge", "sneezing", "labored_breathing", "lethargy", "appetite_loss", "crusty_eyes"},
        "description": "Bacterial infection of the upper airways, very common and potentially fatal in guinea pigs if untreated.",
        "description_ja": "上気道の細菌感染症で、モルモットでは非常に一般的であり、治療しないと致命的になる可能性があります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "nasal_culture", "chest_x_ray"],
    },
    {
        "name": "Bacterial Pneumonia",
        "name_ja": "細菌性肺炎",
        "symptoms": {"labored_breathing", "wheezing", "lethargy", "appetite_loss", "nasal_discharge", "fever", "weight_loss"},
        "description": "Severe lung infection, often caused by Bordetella or Streptococcus. Can be rapidly fatal.",
        "description_ja": "ボルデテラやレンサ球菌による重度の肺感染症で、急速に致命的になることがあります。",
        "urgency": "emergency",
        "recommended_tests": ["chest_x_ray", "blood_work", "nasal_culture", "lung_auscultation"],
    },
    {
        "name": "Bordetella bronchiseptica Infection",
        "name_ja": "ボルデテラ感染症",
        "symptoms": {"sneezing", "nasal_discharge", "labored_breathing", "wheezing", "lethargy", "fever"},
        "description": "Highly contagious bacterial respiratory infection, often contracted from rabbits or dogs.",
        "description_ja": "ウサギや犬から感染する可能性のある、非常に伝染性の高い細菌性呼吸器感染症です。",
        "urgency": "high",
        "recommended_tests": ["nasal_culture", "chest_x_ray", "blood_work"],
    },
    {
        "name": "Streptococcus pneumoniae Infection",
        "name_ja": "肺炎球菌感染症",
        "symptoms": {"labored_breathing", "nasal_discharge", "lethargy", "fever", "head_tilt", "appetite_loss"},
        "description": "Bacterial infection that can cause pneumonia, meningitis, and otitis in guinea pigs.",
        "description_ja": "肺炎、髄膜炎、中耳炎を引き起こす可能性のある細菌感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_work", "culture_sensitivity", "chest_x_ray"],
    },
    {
        "name": "Pleuritis",
        "name_ja": "胸膜炎",
        "symptoms": {"labored_breathing", "lethargy", "appetite_loss", "fever", "pain_on_touch"},
        "description": "Inflammation of the pleural membranes, often secondary to pneumonia.",
        "description_ja": "胸膜の炎症で、肺炎に続発することが多い疾患です。",
        "urgency": "high",
        "recommended_tests": ["chest_x_ray", "ultrasound", "blood_work"],
    },
    # ── Gastrointestinal ─────────────────────────────────────────────────
    {
        "name": "GI Stasis",
        "name_ja": "消化管うっ滞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "lethargy", "bloated_abdomen", "teeth_grinding"},
        "description": "Slowdown or cessation of gut motility, a life-threatening emergency in guinea pigs.",
        "description_ja": "消化管の運動性の低下または停止で、モルモットでは命に関わる緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_x_ray", "physical_exam", "blood_work"],
    },
    {
        "name": "Bloat (Gastric Dilation)",
        "name_ja": "鼓脹症（胃拡張）",
        "symptoms": {"bloated_abdomen", "lethargy", "appetite_loss", "labored_breathing", "teeth_grinding", "restlessness"},
        "description": "Rapid distension of the stomach with gas, extremely dangerous and often fatal without treatment.",
        "description_ja": "胃がガスで急速に拡張する状態で、治療しないと致命的になることが多い疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_x_ray", "physical_exam"],
    },
    {
        "name": "Diarrhea",
        "name_ja": "下痢",
        "symptoms": {"diarrhea", "dehydration", "lethargy", "appetite_loss", "weight_loss"},
        "description": "Loose or watery stools from various causes including diet, infection, or antibiotics.",
        "description_ja": "食事、感染、抗生物質など様々な原因による軟便や水様便です。",
        "urgency": "high",
        "recommended_tests": ["stool_culture", "fecal_exam", "blood_work"],
    },
    {
        "name": "Bacterial Enteritis",
        "name_ja": "細菌性腸炎",
        "symptoms": {"diarrhea", "bloated_abdomen", "lethargy", "appetite_loss", "dehydration", "fever"},
        "description": "Bacterial infection of the intestines, often from Clostridium or E. coli overgrowth.",
        "description_ja": "クロストリジウムや大腸菌の過剰増殖による腸の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["stool_culture", "fecal_exam", "blood_work"],
    },
    {
        "name": "Antibiotic-Associated Enterotoxemia",
        "name_ja": "抗生物質関連腸毒素血症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "dehydration", "bloated_abdomen", "hypothermia"},
        "description": "Fatal disruption of gut flora caused by inappropriate antibiotics (penicillin, amoxicillin, etc.).",
        "description_ja": "不適切な抗生物質（ペニシリン、アモキシシリン等）による致命的な腸内細菌叢の破壊です。",
        "urgency": "emergency",
        "recommended_tests": ["stool_culture", "blood_work", "physical_exam"],
    },
    {
        "name": "Cecal Impaction",
        "name_ja": "盲腸閉塞",
        "symptoms": {"reduced_fecal_output", "bloated_abdomen", "appetite_loss", "lethargy", "weight_loss"},
        "description": "Blockage of the cecum with compacted material, preventing normal digestion.",
        "description_ja": "盲腸に圧縮された内容物が詰まり、正常な消化を妨げる状態です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_x_ray", "physical_exam", "ultrasound"],
    },
    {
        "name": "Intestinal Parasites",
        "name_ja": "腸内寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "rough_coat", "appetite_loss", "bloated_abdomen"},
        "description": "Parasitic worm infestation of the gastrointestinal tract.",
        "description_ja": "消化管の寄生虫感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_flotation"],
    },
    {
        "name": "Gastric Ulcers",
        "name_ja": "胃潰瘍",
        "symptoms": {"appetite_loss", "teeth_grinding", "weight_loss", "lethargy", "bloody_stool"},
        "description": "Ulceration of the stomach lining, often related to stress or NSAID use.",
        "description_ja": "ストレスやNSAIDの使用に関連する胃粘膜の潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "blood_work", "abdominal_x_ray"],
    },
    # ── Dermatological ───────────────────────────────────────────────────
    {
        "name": "Fungal Dermatitis (Ringworm)",
        "name_ja": "皮膚糸状菌症（白癬）",
        "symptoms": {"hair_loss", "crusty_skin", "itching", "scaling", "circular_patches"},
        "description": "Fungal skin infection caused by Trichophyton mentagrophytes, producing circular bald patches.",
        "description_ja": "白癬菌による皮膚の真菌感染症で、円形の脱毛斑を生じます。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "fungal_culture", "wood_lamp_exam"],
    },
    {
        "name": "Sarcoptic Mange (Trixacarus caviae)",
        "name_ja": "疥癬（トリキサカルスダニ）",
        "symptoms": {"severe_itching", "hair_loss", "crusty_skin", "seizures", "self_mutilation", "pain_on_touch", "restlessness"},
        "description": "Intensely itchy parasitic mite infestation that can cause seizures from pain and distress.",
        "description_ja": "激しい痒みを引き起こすダニの寄生で、痛みやストレスから発作を起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "physical_exam"],
    },
    {
        "name": "Static Lice (Gliricola porcelli)",
        "name_ja": "シラミ寄生症",
        "symptoms": {"itching", "hair_loss", "rough_coat", "restlessness", "visible_parasites"},
        "description": "Lice infestation visible as small insects moving through the fur.",
        "description_ja": "被毛の中に小さな虫が見えるシラミの寄生症です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_scraping", "coat_exam"],
    },
    {
        "name": "Barbering",
        "name_ja": "毛引き（バーバリング）",
        "symptoms": {"hair_loss", "patchy_fur", "stress_signs"},
        "description": "Hair chewing by cage mates or self-barbering due to stress, boredom, or dominance.",
        "description_ja": "ストレス、退屈、支配関係によるケージメイトまたは自己による毛の咀嚼です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "behavioral_assessment"],
    },
    {
        "name": "Pododermatitis (Bumblefoot)",
        "name_ja": "足底皮膚炎（バンブルフット）",
        "symptoms": {"limping", "swollen_feet", "foot_sores", "reluctance_to_move", "pain_on_touch"},
        "description": "Painful infection of the foot pads from wire flooring, obesity, or unsanitary conditions.",
        "description_ja": "金網の床、肥満、不衛生な環境による足底の痛みを伴う感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "x_rays", "culture_sensitivity"],
    },
    {
        "name": "Sebaceous Cyst",
        "name_ja": "皮脂嚢胞",
        "symptoms": {"skin_lump", "hair_loss", "discharge_from_lump"},
        "description": "Benign cyst formed by blocked sebaceous glands, common on the back and rump.",
        "description_ja": "皮脂腺の閉塞により形成される良性の嚢胞で、背中や臀部に好発します。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "fine_needle_aspirate"],
    },
    {
        "name": "Flystrike (Myiasis)",
        "name_ja": "蝿蛆症",
        "symptoms": {"lethargy", "foul_odor", "visible_parasites", "skin_wounds", "appetite_loss", "restlessness"},
        "description": "Maggot infestation of wounds or soiled fur, rapidly life-threatening.",
        "description_ja": "傷口や汚れた被毛に蛆が寄生する状態で、急速に命に関わります。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Contact Dermatitis",
        "name_ja": "接触性皮膚炎",
        "symptoms": {"hair_loss", "redness", "itching", "foot_sores"},
        "description": "Skin irritation from contact with bedding materials, cleaning products, or urine.",
        "description_ja": "敷材、洗剤、尿への接触による皮膚の炎症です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "skin_scraping"],
    },
    {
        "name": "Abscess (Subcutaneous)",
        "name_ja": "皮下膿瘍",
        "symptoms": {"skin_lump", "swelling", "pain_on_touch", "fever", "discharge_from_lump"},
        "description": "Localized pocket of pus under the skin, often from bite wounds or dental disease.",
        "description_ja": "咬傷や歯科疾患に起因することが多い、皮下の限局的な膿の溜まりです。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "physical_exam"],
    },
    # ── Urinary ──────────────────────────────────────────────────────────
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"blood_in_urine", "straining_to_urinate", "squealing_when_urinating", "appetite_loss", "lethargy", "hunched_posture"},
        "description": "Calcium-based stones in the bladder or urethra, very common in guinea pigs.",
        "description_ja": "膀胱や尿道のカルシウム系結石で、モルモットで非常に多い疾患です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_x_ray", "urinalysis", "ultrasound"],
    },
    {
        "name": "Urinary Tract Infection (UTI)",
        "name_ja": "尿路感染症",
        "symptoms": {"blood_in_urine", "frequent_urination", "straining_to_urinate", "squealing_when_urinating", "foul_smelling_urine"},
        "description": "Bacterial infection of the urinary tract, common in sows.",
        "description_ja": "尿路の細菌感染症で、雌に多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "abdominal_x_ray"],
    },
    {
        "name": "Bladder Sludge",
        "name_ja": "膀胱スラッジ",
        "symptoms": {"blood_in_urine", "gritty_urine", "straining_to_urinate", "frequent_urination"},
        "description": "Calcium sediment accumulation in the bladder from excess dietary calcium.",
        "description_ja": "過剰な食事性カルシウムによる膀胱内のカルシウム沈殿物の蓄積です。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_x_ray", "urinalysis", "diet_history"],
    },
    {
        "name": "Chronic Kidney Disease",
        "name_ja": "慢性腎臓病",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "lethargy", "appetite_loss", "dehydration"},
        "description": "Progressive deterioration of kidney function, more common in older guinea pigs.",
        "description_ja": "腎機能の進行性の悪化で、高齢のモルモットに多く見られます。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "urinalysis", "ultrasound"],
    },
    {
        "name": "Urethral Obstruction",
        "name_ja": "尿道閉塞",
        "symptoms": {"straining_to_urinate", "no_urination", "bloated_abdomen", "lethargy", "squealing_when_urinating", "pain_on_touch"},
        "description": "Complete blockage of the urethra by a stone, a life-threatening emergency.",
        "description_ja": "結石による尿道の完全閉塞で、命に関わる緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_x_ray", "ultrasound", "blood_work"],
    },
    # ── Reproductive ─────────────────────────────────────────────────────
    {
        "name": "Ovarian Cysts",
        "name_ja": "卵巣嚢腫",
        "symptoms": {"bilateral_hair_loss", "bloated_abdomen", "crusty_nipples", "hormonal_behavior", "lethargy"},
        "description": "Fluid-filled cysts on the ovaries, extremely common in unspayed sows over 2 years.",
        "description_ja": "卵巣にできる液体で満たされた嚢胞で、2歳以上の未避妊の雌に非常に多い疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "abdominal_x_ray", "hormonal_panel"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "lethargy", "vaginal_bleeding", "distress_vocalizations", "no_delivery"},
        "description": "Difficulty giving birth, especially dangerous if the sow is bred after 8 months of age.",
        "description_ja": "分娩困難で、8か月齢以降に初めて交配した場合は特に危険です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_x_ray", "ultrasound", "physical_exam"],
    },
    {
        "name": "Pregnancy Toxemia (Ketosis)",
        "name_ja": "妊娠中毒症（ケトーシス）",
        "symptoms": {"appetite_loss", "lethargy", "labored_breathing", "seizures", "muscle_spasms", "sudden_death_risk"},
        "description": "Metabolic crisis in late pregnancy or early postpartum, often fatal. Obese sows at highest risk.",
        "description_ja": "妊娠後期または産後早期の代謝性危機で、しばしば致命的です。肥満の雌で最もリスクが高くなります。",
        "urgency": "emergency",
        "recommended_tests": ["blood_work", "urinalysis", "blood_glucose"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "bloated_abdomen", "lethargy", "appetite_loss", "excessive_thirst", "fever"},
        "description": "Pus-filled infection of the uterus requiring emergency surgery.",
        "description_ja": "子宮内に膿が溜まる感染症で、緊急手術が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "blood_work", "abdominal_x_ray"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"swollen_mammary_glands", "fever", "pain_on_touch", "lethargy", "appetite_loss", "redness"},
        "description": "Bacterial infection of the mammary glands, usually in nursing sows.",
        "description_ja": "授乳中の雌に多い乳腺の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "blood_work"],
    },
    {
        "name": "Uterine Tumors",
        "name_ja": "子宮腫瘍",
        "symptoms": {"vaginal_bleeding", "bloated_abdomen", "weight_loss", "lethargy", "appetite_loss"},
        "description": "Neoplasia of the uterus, more common in older unspayed sows.",
        "description_ja": "子宮の腫瘍で、高齢の未避妊雌に多く見られます。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "abdominal_x_ray", "blood_work"],
    },
    # ── Musculoskeletal ──────────────────────────────────────────────────
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"limping", "swelling", "pain_on_touch", "reluctance_to_move", "distress_vocalizations"},
        "description": "Broken bones from falls, rough handling, or entrapment in cage components.",
        "description_ja": "落下、粗暴な扱い、ケージ部品への挟み込みによる骨折です。",
        "urgency": "high",
        "recommended_tests": ["x_rays", "physical_exam"],
    },
    {
        "name": "Scurvy-Related Arthritis",
        "name_ja": "壊血病関連関節炎",
        "symptoms": {"swollen_joints", "limping", "pain_on_touch", "reluctance_to_move", "teeth_grinding", "rough_coat"},
        "description": "Joint inflammation caused by severe vitamin C deficiency.",
        "description_ja": "重度のビタミンC欠乏によって引き起こされる関節の炎症です。",
        "urgency": "high",
        "recommended_tests": ["x_rays", "blood_work", "diet_history"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"limping", "stiffness", "reluctance_to_move", "weight_loss", "lethargy"},
        "description": "Degenerative joint disease, common in older or obese guinea pigs.",
        "description_ja": "高齢または肥満のモルモットに多い変性関節疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["x_rays", "physical_exam"],
    },
    {
        "name": "Splay Leg",
        "name_ja": "開脚症",
        "symptoms": {"limping", "splayed_legs", "reluctance_to_move"},
        "description": "Congenital or acquired condition where legs splay outward, affecting mobility.",
        "description_ja": "脚が外側に開いてしまう先天性または後天性の疾患で、運動能力に影響します。",
        "urgency": "moderate",
        "recommended_tests": ["x_rays", "physical_exam"],
    },
    # ── Ophthalmological ─────────────────────────────────────────────────
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"crusty_eyes", "eye_discharge", "swollen_eyes", "redness", "squinting"},
        "description": "Inflammation of the conjunctiva from infection, allergens, or hay dust.",
        "description_ja": "感染、アレルゲン、牧草の粉塵による結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["eye_exam", "fluorescein_stain", "culture_sensitivity"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "eye_discharge", "cloudy_eye", "redness", "pain_on_touch"},
        "description": "Erosion of the corneal surface, often from hay poke injuries or infection.",
        "description_ja": "牧草による刺傷や感染による角膜表面の損傷です。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "eye_exam"],
    },
    {
        "name": "Pea Eye (Conjunctival Protrusion)",
        "name_ja": "ピーアイ（結膜突出）",
        "symptoms": {"protruding_tissue_from_eye", "swollen_eyes", "eye_discharge"},
        "description": "Fatty conjunctival protrusion, common in certain breeds. Usually cosmetic but can become irritated.",
        "description_ja": "脂肪性の結膜突出で、特定の品種に多い。通常は外見上の問題ですが、炎症を起こすことがあります。",
        "urgency": "low",
        "recommended_tests": ["eye_exam", "physical_exam"],
    },
    {
        "name": "Fatty Eye (Osseous Choristoma)",
        "name_ja": "脂肪眼",
        "symptoms": {"protruding_tissue_from_eye", "eye_discharge", "squinting"},
        "description": "Benign fatty or bony growth behind the eye, breed-related, rarely causes problems.",
        "description_ja": "眼球後方の良性の脂肪性または骨性の増殖で、品種に関連し、問題を起こすことは稀です。",
        "urgency": "low",
        "recommended_tests": ["eye_exam", "physical_exam"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudy_eye", "vision_loss", "bumping_into_objects"},
        "description": "Opacity of the lens, can be age-related or secondary to diabetes.",
        "description_ja": "水晶体の混濁で、加齢や糖尿病に関連します。",
        "urgency": "low",
        "recommended_tests": ["eye_exam", "blood_glucose"],
    },
    {
        "name": "Entropion",
        "name_ja": "眼瞼内反症",
        "symptoms": {"squinting", "eye_discharge", "crusty_eyes", "redness"},
        "description": "Inward rolling of the eyelid causing corneal irritation, may be congenital.",
        "description_ja": "まぶたが内側に巻き込み角膜を刺激する疾患で、先天性の場合があります。",
        "urgency": "moderate",
        "recommended_tests": ["eye_exam", "physical_exam"],
    },
    # ── Neurological ─────────────────────────────────────────────────────
    {
        "name": "Head Tilt (Torticollis)",
        "name_ja": "斜頸",
        "symptoms": {"head_tilt", "loss_of_balance", "circling", "nystagmus", "appetite_loss"},
        "description": "Abnormal head posture caused by ear infection, stroke, or other neurological disease.",
        "description_ja": "中耳炎、脳卒中、その他の神経疾患による異常な頭位です。",
        "urgency": "high",
        "recommended_tests": ["x_rays", "blood_work", "ear_exam", "ct_scan"],
    },
    {
        "name": "Stroke (Cerebrovascular Accident)",
        "name_ja": "脳卒中",
        "symptoms": {"head_tilt", "loss_of_balance", "circling", "lethargy", "nystagmus", "paralysis"},
        "description": "Sudden neurological event from bleeding or clotting in the brain.",
        "description_ja": "脳内の出血や血栓による突発性の神経学的事象です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_work", "ct_scan", "physical_exam"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "loss_of_balance", "nystagmus", "circling", "rolling"},
        "description": "Dysfunction of the vestibular system affecting balance and orientation.",
        "description_ja": "平衡感覚と方向感覚に影響する前庭系の機能障害です。",
        "urgency": "high",
        "recommended_tests": ["ear_exam", "x_rays", "ct_scan", "blood_work"],
    },
    {
        "name": "Seizures",
        "name_ja": "発作（てんかん）",
        "symptoms": {"seizures", "loss_of_balance", "muscle_spasms", "loss_of_consciousness", "drooling"},
        "description": "Episodes of involuntary muscle activity, can be caused by mites, toxins, or metabolic issues.",
        "description_ja": "ダニ、毒素、代謝性疾患などが原因となる不随意な筋活動のエピソードです。",
        "urgency": "emergency",
        "recommended_tests": ["blood_work", "blood_glucose", "physical_exam", "skin_scraping"],
    },
    # ── Cardiac ──────────────────────────────────────────────────────────
    {
        "name": "Heart Disease (Cardiomyopathy)",
        "name_ja": "心疾患（心筋症）",
        "symptoms": {"labored_breathing", "lethargy", "exercise_intolerance", "weight_loss", "coughing", "cyanosis"},
        "description": "Heart muscle disease, often undiagnosed until advanced. Dilated cardiomyopathy most common.",
        "description_ja": "心筋の疾患で、進行するまで診断されないことが多い。拡張型心筋症が最も一般的です。",
        "urgency": "high",
        "recommended_tests": ["echocardiogram", "chest_x_ray", "electrocardiogram"],
    },
    {
        "name": "Pericardial Effusion",
        "name_ja": "心嚢液貯留",
        "symptoms": {"labored_breathing", "lethargy", "exercise_intolerance", "muffled_heart_sounds", "cyanosis"},
        "description": "Fluid accumulation around the heart, compressing cardiac function.",
        "description_ja": "心臓周囲の液体貯留により心機能が圧迫される状態です。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiogram", "chest_x_ray", "ultrasound"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"labored_breathing", "lethargy", "coughing", "exercise_intolerance", "bloated_abdomen", "cyanosis"},
        "description": "End-stage heart disease where the heart cannot pump effectively.",
        "description_ja": "心臓が効果的に血液を送り出せなくなった末期の心疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiogram", "chest_x_ray", "blood_work", "electrocardiogram"],
    },
    # ── Metabolic ────────────────────────────────────────────────────────
    {
        "name": "Scurvy (Vitamin C Deficiency)",
        "name_ja": "壊血病（ビタミンC欠乏症）",
        "symptoms": {"lethargy", "swollen_joints", "pain_on_touch", "rough_coat", "appetite_loss", "weight_loss", "limping", "bleeding_gums"},
        "description": "Guinea pigs cannot synthesize vitamin C. Deficiency causes joint pain, bleeding, and death if untreated.",
        "description_ja": "モルモットはビタミンCを合成できません。欠乏すると関節痛、出血、治療しなければ死に至ります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "blood_work", "diet_history", "x_rays"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "exercise_intolerance", "difficulty_grooming", "labored_breathing"},
        "description": "Excess body weight increasing risk of pododermatitis, heart disease, and pregnancy toxemia.",
        "description_ja": "過体重で、足底皮膚炎、心疾患、妊娠中毒症のリスクを高めます。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "diet_history", "blood_work"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "cataracts_sign", "lethargy"},
        "description": "Inability to regulate blood sugar levels, uncommon but possible in guinea pigs.",
        "description_ja": "血糖値を調節できない疾患で、モルモットでは稀ですが発症の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["blood_glucose", "urinalysis", "blood_work"],
    },
    {
        "name": "Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"labored_breathing", "drooling", "lethargy", "restlessness", "collapse", "redness"},
        "description": "Overheating above 26°C / 80°F. Guinea pigs are very susceptible to heat stress.",
        "description_ja": "26°C以上の過熱状態です。モルモットは暑さに非常に弱い動物です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_work"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"muscle_spasms", "seizures", "lethargy", "weakness"},
        "description": "Low blood calcium levels, sometimes seen in nursing sows.",
        "description_ja": "血中カルシウム濃度の低下で、授乳中の雌に見られることがあります。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "physical_exam"],
    },
    # ── Dental ───────────────────────────────────────────────────────────
    {
        "name": "Dental Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "weight_loss", "appetite_loss", "difficulty_eating", "wet_chin", "teeth_grinding"},
        "description": "Misalignment or overgrowth of teeth preventing proper chewing. Extremely common.",
        "description_ja": "歯の配列異常や過成長により正常な咀嚼ができない状態で、非常に多い疾患です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_x_ray", "ct_scan"],
    },
    {
        "name": "Elongated Tooth Roots",
        "name_ja": "歯根伸長",
        "symptoms": {"eye_discharge", "crusty_eyes", "drooling", "appetite_loss", "weight_loss", "nasal_discharge"},
        "description": "Overgrown molar roots pushing into the nasal cavity or eye sockets, causing chronic pain.",
        "description_ja": "伸長した臼歯の根が鼻腔や眼窩に侵入し、慢性的な痛みを引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_x_ray", "ct_scan", "oral_exam"],
    },
    {
        "name": "Dental Abscess",
        "name_ja": "歯科膿瘍",
        "symptoms": {"facial_swelling", "drooling", "appetite_loss", "weight_loss", "difficulty_eating", "foul_odor"},
        "description": "Infection around tooth roots forming a pus pocket in the jaw, very common.",
        "description_ja": "歯根周囲の感染により顎に膿の溜まりが形成される、非常に多い疾患です。",
        "urgency": "high",
        "recommended_tests": ["skull_x_ray", "ct_scan", "culture_sensitivity", "oral_exam"],
    },
    {
        "name": "Incisor Overgrowth",
        "name_ja": "切歯過成長",
        "symptoms": {"difficulty_eating", "drooling", "weight_loss", "visible_tooth_overgrowth"},
        "description": "Front teeth growing too long, often secondary to molar malocclusion.",
        "description_ja": "前歯の過成長で、臼歯の不正咬合に続発することが多い疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_x_ray"],
    },
    {
        "name": "Cheek Teeth Spurs",
        "name_ja": "臼歯棘形成",
        "symptoms": {"drooling", "difficulty_eating", "appetite_loss", "weight_loss", "mouth_sores"},
        "description": "Sharp spurs on molars that lacerate the tongue and cheeks, causing extreme pain.",
        "description_ja": "臼歯にできる鋭い棘が舌や頬を傷つけ、激しい痛みを引き起こします。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_x_ray"],
    },
    # ── Oncological ──────────────────────────────────────────────────────
    {
        "name": "Mammary Tumors",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"skin_lump", "mammary_mass", "weight_loss", "lethargy"},
        "description": "Benign or malignant tumors of the mammary glands, can occur in both sexes.",
        "description_ja": "乳腺の良性または悪性腫瘍で、雌雄ともに発症します。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "x_rays"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "lethargy", "appetite_loss", "swollen_lymph_nodes", "labored_breathing"},
        "description": "Cancer of the lymphatic system, one of the most common neoplasms in guinea pigs.",
        "description_ja": "リンパ系の悪性腫瘍で、モルモットで最も一般的な腫瘍の一つです。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "fine_needle_aspirate", "biopsy", "chest_x_ray"],
    },
    {
        "name": "Trichofolliculoma",
        "name_ja": "毛包腫",
        "symptoms": {"skin_lump", "hair_loss", "discharge_from_lump"},
        "description": "Benign hair follicle tumor, most common skin tumor in guinea pigs. Usually on the rump.",
        "description_ja": "モルモットで最も一般的な皮膚腫瘍である良性の毛包腫瘍で、臀部に好発します。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "physical_exam"],
    },
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"skin_lump", "weight_gain"},
        "description": "Benign fatty tumor under the skin, usually soft and movable.",
        "description_ja": "皮下の良性脂肪腫瘍で、通常柔らかく可動性があります。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "physical_exam"],
    },
    {
        "name": "Skin Squamous Cell Carcinoma",
        "name_ja": "皮膚扁平上皮癌",
        "symptoms": {"skin_wounds", "skin_lump", "hair_loss", "bleeding_from_mass"},
        "description": "Malignant skin cancer, can occur on ears, feet, or body.",
        "description_ja": "皮膚の悪性腫瘍で、耳、足、体に発生することがあります。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "fine_needle_aspirate", "x_rays"],
    },
    {
        "name": "Pulmonary Adenoma",
        "name_ja": "肺腺腫",
        "symptoms": {"labored_breathing", "weight_loss", "lethargy", "coughing"},
        "description": "Benign lung tumor, relatively common incidental finding in older guinea pigs.",
        "description_ja": "良性の肺腫瘍で、高齢モルモットの偶発的所見として比較的多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["chest_x_ray", "ct_scan", "blood_work"],
    },
    {
        "name": "Leukemia",
        "name_ja": "白血病",
        "symptoms": {"lethargy", "weight_loss", "appetite_loss", "swollen_lymph_nodes", "fever"},
        "description": "Cancer of the blood-forming tissues, causing abnormal white blood cell production.",
        "description_ja": "造血組織の悪性腫瘍で、白血球の異常産生を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "bone_marrow_biopsy", "physical_exam"],
    },
    # ── Infectious ───────────────────────────────────────────────────────
    {
        "name": "Chlamydiosis (Chlamydia caviae)",
        "name_ja": "クラミジア症",
        "symptoms": {"crusty_eyes", "eye_discharge", "nasal_discharge", "sneezing", "vaginal_discharge"},
        "description": "Bacterial infection primarily causing conjunctivitis, endemic in many guinea pig colonies.",
        "description_ja": "主に結膜炎を引き起こす細菌感染症で、多くのモルモットコロニーに常在します。",
        "urgency": "moderate",
        "recommended_tests": ["eye_exam", "culture_sensitivity", "pcr_test"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "fever", "weight_loss", "sudden_death_risk"},
        "description": "Serious bacterial infection that can cause septicemia. Zoonotic risk to humans.",
        "description_ja": "敗血症を引き起こす重篤な細菌感染症で、人への感染リスクもあります。",
        "urgency": "emergency",
        "recommended_tests": ["stool_culture", "blood_work", "fecal_exam"],
    },
    {
        "name": "Lymphocytic Choriomeningitis Virus (LCMV)",
        "name_ja": "リンパ球性脈絡髄膜炎ウイルス",
        "symptoms": {"lethargy", "weight_loss", "rough_coat", "seizures", "paralysis"},
        "description": "Viral infection transmissible to humans (zoonotic), often subclinical in guinea pigs.",
        "description_ja": "人にも感染可能なウイルス感染症で、モルモットでは無症状のことが多い。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "pcr_test", "serology"],
    },
    {
        "name": "Staphylococcal Infection",
        "name_ja": "ブドウ球菌感染症",
        "symptoms": {"skin_wounds", "crusty_skin", "hair_loss", "swelling", "fever", "pain_on_touch"},
        "description": "Bacterial skin infection causing abscesses, cellulitis, or septicemia.",
        "description_ja": "膿瘍、蜂巣炎、敗血症を引き起こす皮膚の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "blood_work", "physical_exam"],
    },
    {
        "name": "Streptococcal Lymphadenitis (Lumps)",
        "name_ja": "連鎖球菌性リンパ節炎",
        "symptoms": {"swollen_lymph_nodes", "facial_swelling", "nasal_discharge", "lethargy", "appetite_loss"},
        "description": "Cervical lymph node swelling caused by Streptococcus zooepidemicus, often called 'lumps'.",
        "description_ja": "ストレプトコッカス・ズーエピデミクスによる頸部リンパ節の腫脹で、一般に「ランプス」と呼ばれます。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "physical_exam"],
    },
    # ── Parasitic ────────────────────────────────────────────────────────
    {
        "name": "Coccidia",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "lethargy", "rough_coat"},
        "description": "Protozoal intestinal parasite, primarily affects young guinea pigs.",
        "description_ja": "原虫性の腸管寄生虫で、主に若いモルモットに影響します。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_flotation"],
    },
    {
        "name": "Demodex Mites",
        "name_ja": "ニキビダニ症",
        "symptoms": {"hair_loss", "crusty_skin", "scaling", "itching"},
        "description": "Demodectic mange caused by Demodex caviae, less common than Trixacarus.",
        "description_ja": "デモデックスダニによる毛包虫症で、トリキサカルスより少ない。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "physical_exam"],
    },
    {
        "name": "Fur Mites (Chirodiscoides caviae)",
        "name_ja": "毛ダニ症",
        "symptoms": {"itching", "rough_coat", "hair_loss", "visible_parasites"},
        "description": "Non-burrowing mites living on the fur, causing mild to moderate irritation.",
        "description_ja": "被毛上に寄生する非穿孔性のダニで、軽度から中等度の刺激を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["coat_exam", "skin_scraping", "physical_exam"],
    },
    {
        "name": "Pinworms (Paraspidodera uncinata)",
        "name_ja": "蟯虫症",
        "symptoms": {"weight_loss", "rough_coat", "perianal_irritation"},
        "description": "Common intestinal nematode, usually asymptomatic unless heavy burden.",
        "description_ja": "一般的な腸管線虫で、多量寄生でなければ通常無症状です。",
        "urgency": "low",
        "recommended_tests": ["fecal_exam", "fecal_flotation"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "lethargy"},
        "description": "Protozoal parasite infection affecting the intestines. Zoonotic potential.",
        "description_ja": "腸管に影響する原虫感染症で、人への感染の可能性もあります。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "pcr_test"],
    },
    # ── Ear Conditions ───────────────────────────────────────────────────
    {
        "name": "Otitis Media/Interna (Middle/Inner Ear Infection)",
        "name_ja": "中耳炎・内耳炎",
        "symptoms": {"head_tilt", "loss_of_balance", "appetite_loss", "ear_discharge", "pain_on_touch"},
        "description": "Infection of the middle or inner ear, a common cause of head tilt in guinea pigs.",
        "description_ja": "中耳または内耳の感染症で、モルモットの斜頸の一般的な原因です。",
        "urgency": "high",
        "recommended_tests": ["ear_exam", "x_rays", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Otitis Externa (Outer Ear Infection)",
        "name_ja": "外耳炎",
        "symptoms": {"head_shaking", "ear_discharge", "itching", "redness", "ear_odor"},
        "description": "Infection or inflammation of the outer ear canal.",
        "description_ja": "外耳道の感染または炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ear_exam", "ear_cytology", "culture_sensitivity"],
    },
    # ── Additional Conditions ────────────────────────────────────────────
    {
        "name": "Impaction (Perineal Sac)",
        "name_ja": "肛門嚢閉塞",
        "symptoms": {"foul_odor", "difficulty_defecating", "perianal_irritation", "reduced_fecal_output"},
        "description": "Accumulation of fecal material and sebum in the perineal sac, common in older boars.",
        "description_ja": "会陰嚢に糞便や皮脂が蓄積する状態で、高齢の雄に多い。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Boar Glue (Excessive Grease Gland Secretion)",
        "name_ja": "ボアグルー（脂腺過分泌）",
        "symptoms": {"greasy_coat", "foul_odor", "hair_loss", "crusty_skin"},
        "description": "Overactive grease gland on the rump, primarily in intact boars.",
        "description_ja": "臀部の脂腺の過活動で、主に未去勢の雄に見られます。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Cystitis",
        "name_ja": "膀胱炎",
        "symptoms": {"blood_in_urine", "frequent_urination", "straining_to_urinate", "hunched_posture", "squealing_when_urinating"},
        "description": "Inflammation of the bladder wall, often associated with infection or stones.",
        "description_ja": "膀胱壁の炎症で、感染や結石に関連することが多い。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "abdominal_x_ray"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"appetite_loss", "lethargy", "weight_loss", "jaundice", "dehydration"},
        "description": "Fat accumulation in the liver, often triggered by anorexia or pregnancy toxemia.",
        "description_ja": "肝臓への脂肪蓄積で、食欲不振や妊娠中毒症を契機に発症することが多い。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "ultrasound", "physical_exam"],
    },
    {
        "name": "Adrenal Disease",
        "name_ja": "副腎疾患",
        "symptoms": {"bilateral_hair_loss", "lethargy", "excessive_thirst", "weight_loss", "skin_thinning"},
        "description": "Dysfunction of the adrenal glands causing hormonal imbalance.",
        "description_ja": "副腎の機能障害によるホルモンバランスの乱れです。",
        "urgency": "moderate",
        "recommended_tests": ["blood_work", "hormonal_panel", "ultrasound"],
    },
    {
        "name": "Cervical Lymphadenitis",
        "name_ja": "頸部リンパ節炎",
        "symptoms": {"swollen_lymph_nodes", "facial_swelling", "appetite_loss", "lethargy"},
        "description": "Swollen neck lymph nodes, often from bacterial infection spreading from the oral cavity.",
        "description_ja": "口腔内からの細菌感染の広がりによる頸部リンパ節の腫脹です。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "blood_work"],
    },
    {
        "name": "Ileus",
        "name_ja": "腸閉塞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "bloated_abdomen", "lethargy", "teeth_grinding", "hunched_posture"},
        "description": "Functional obstruction of the bowel without physical blockage.",
        "description_ja": "物理的な閉塞なしに腸の機能的停止が起こる状態です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_x_ray", "physical_exam", "blood_work"],
    },
    {
        "name": "Anal Prolapse",
        "name_ja": "肛門脱",
        "symptoms": {"visible_prolapse", "straining", "bloody_stool", "restlessness"},
        "description": "Protrusion of rectal tissue through the anus, often from straining or diarrhea.",
        "description_ja": "いきみや下痢により直腸組織が肛門から突出する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_exam"],
    },
    {
        "name": "Alopecia (Non-specific Hair Loss)",
        "name_ja": "脱毛症（非特異性）",
        "symptoms": {"hair_loss", "patchy_fur", "stress_signs"},
        "description": "Hair loss from hormonal, nutritional, or stress-related causes.",
        "description_ja": "ホルモン、栄養、ストレスに関連する脱毛症です。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "fungal_culture", "blood_work", "hormonal_panel"],
    },
    {
        "name": "Calcification of Soft Tissues (Metastatic Calcification)",
        "name_ja": "軟部組織石灰化",
        "symptoms": {"stiffness", "pain_on_touch", "weight_loss", "lethargy"},
        "description": "Calcium deposits in organs and soft tissues from dietary calcium excess.",
        "description_ja": "過剰な食事性カルシウムによる臓器や軟部組織へのカルシウム沈着です。",
        "urgency": "moderate",
        "recommended_tests": ["x_rays", "blood_work", "diet_history"],
    },
    {
        "name": "Retained Fetus",
        "name_ja": "胎仔遺残",
        "symptoms": {"vaginal_discharge", "lethargy", "appetite_loss", "bloated_abdomen", "fever"},
        "description": "Dead fetus remaining in the uterus after parturition, causing sepsis.",
        "description_ja": "分娩後に死亡した胎仔が子宮内に残留し、敗血症を引き起こす状態です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_x_ray", "ultrasound", "blood_work"],
    },
    {
        "name": "Rectal Impaction",
        "name_ja": "直腸閉塞",
        "symptoms": {"reduced_fecal_output", "straining", "lethargy", "appetite_loss", "bloated_abdomen"},
        "description": "Blockage of the rectum with compacted feces.",
        "description_ja": "圧縮された糞便による直腸の閉塞です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "abdominal_x_ray"],
    },
    {
        "name": "Fungal Pneumonia (Aspergillosis)",
        "name_ja": "真菌性肺炎（アスペルギルス症）",
        "symptoms": {"labored_breathing", "nasal_discharge", "weight_loss", "lethargy", "wheezing"},
        "description": "Rare fungal infection of the lungs, usually in immunocompromised individuals.",
        "description_ja": "免疫不全の個体に見られる稀な肺の真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["chest_x_ray", "fungal_culture", "blood_work"],
    },
    {
        "name": "Vitamin A Deficiency",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"rough_coat", "eye_discharge", "weight_loss", "poor_growth"},
        "description": "Nutritional deficiency affecting skin, eyes, and growth.",
        "description_ja": "皮膚、目、成長に影響する栄養欠乏症です。",
        "urgency": "moderate",
        "recommended_tests": ["diet_history", "blood_work", "physical_exam"],
    },
    {
        "name": "Hay Poke Injury",
        "name_ja": "牧草による刺傷",
        "symptoms": {"squinting", "eye_discharge", "swollen_eyes", "nasal_discharge"},
        "description": "Eye or nasal injury from sharp hay stalks, very common in guinea pigs.",
        "description_ja": "鋭い牧草の茎による目や鼻の損傷で、モルモットで非常に多い。",
        "urgency": "moderate",
        "recommended_tests": ["eye_exam", "fluorescein_stain"],
    },
    {
        "name": "Testicular Tumors",
        "name_ja": "精巣腫瘍",
        "symptoms": {"testicular_swelling", "weight_loss", "lethargy", "bilateral_hair_loss"},
        "description": "Tumors of the testes, more common in older intact boars.",
        "description_ja": "精巣の腫瘍で、高齢の未去勢雄に多い。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "ultrasound", "fine_needle_aspirate"],
    },
    {
        "name": "Inguinal Hernia",
        "name_ja": "鼠径ヘルニア",
        "symptoms": {"groin_swelling", "pain_on_touch", "appetite_loss", "lethargy"},
        "description": "Protrusion of abdominal contents through the inguinal canal.",
        "description_ja": "腹部内容物が鼠径管を通じて突出する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "ultrasound", "abdominal_x_ray"],
    },
    {
        "name": "Scurvy - Acute Form",
        "name_ja": "壊血病 - 急性型",
        "symptoms": {"joint_swelling", "lameness", "lethargy", "pain", "reluctance_to_move", "vocalization"},
        "description": "Acute vitamin C deficiency causing hemorrhage into joints and muscles, severe pain, and inability to walk. Guinea pigs cannot synthesize vitamin C.",
        "description_ja": "急性ビタミンC欠乏により関節や筋肉への出血、重度の痛み、歩行不能を引き起こします。モルモットはビタミンCを合成できません。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "vitamin_c_level", "joint_xray"],
    },
    {
        "name": "Scurvy-Related Gum Disease",
        "name_ja": "壊血病関連歯肉疾患",
        "symptoms": {"appetite_loss", "bleeding_gums", "drooling", "loose_teeth", "weight_loss"},
        "description": "Gingival inflammation, bleeding, and tooth loosening caused by vitamin C deficiency affecting collagen synthesis.",
        "description_ja": "ビタミンC欠乏によるコラーゲン合成障害に起因する歯肉炎症、出血、歯の動揺です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "vitamin_c_level", "dental_xray"],
    },
    {
        "name": "Ovarian Cysts - Serous",
        "name_ja": "卵巣嚢胞 - 漿液性",
        "symptoms": {"abdominal_distension", "aggressive_behavior", "bilateral_hair_loss", "crusty_nipples", "mounting_behavior"},
        "description": "Serous fluid-filled ovarian cysts extremely common in intact female guinea pigs over 2 years, causing hormonal signs and flank alopecia.",
        "description_ja": "2歳以上の未避妊雌モルモットに非常に多い漿液性卵巣嚢胞で、ホルモン症状と側腹部脱毛を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "hormone_panel", "physical_exam"],
    },
    {
        "name": "Ovarian Cysts - Follicular",
        "name_ja": "卵巣嚢胞 - 濾胞性",
        "symptoms": {"abdominal_distension", "hair_loss", "persistent_estrus", "vulvar_swelling"},
        "description": "Hormone-producing follicular cysts causing persistent estrus signs and significant bilateral alopecia.",
        "description_ja": "ホルモン産生性濾胞嚢胞で、持続的な発情兆候と著明な両側性脱毛を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "hormone_panel", "physical_exam"],
    },
    {
        "name": "Bumblefoot - Grade I",
        "name_ja": "趾瘤症 - グレードI",
        "symptoms": {"foot_redness", "mild_swelling_feet", "thinning_foot_skin"},
        "description": "Early-stage pododermatitis with redness and mild swelling of footpads, typically from wire flooring or rough substrate.",
        "description_ja": "金網床や粗い床材による足裏の発赤と軽度腫脹を伴う初期段階の趾瘤症です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "environmental_review"],
    },
    {
        "name": "Bumblefoot - Grade III-IV",
        "name_ja": "趾瘤症 - グレードIII-IV",
        "symptoms": {"bone_infection", "foot_ulceration", "lameness", "reluctance_to_move", "severe_foot_swelling"},
        "description": "Advanced pododermatitis with deep ulceration, tendon involvement, and osteomyelitis requiring aggressive treatment.",
        "description_ja": "深い潰瘍、腱の関与、骨髄炎を伴う進行した趾瘤症で、積極的な治療が必要です。",
        "urgency": "high",
        "recommended_tests": ["foot_xray", "culture_sensitivity", "biopsy"],
    },
    {
        "name": "Trixacarus caviae (Sarcoptic Mange) - Severe",
        "name_ja": "トリキサカルス疥癬 - 重症型",
        "symptoms": {"hair_loss", "intense_itching", "seizures", "self_mutilation", "skin_thickening", "weight_loss"},
        "description": "Severe sarcoptic mange infestation causing such intense pruritus that guinea pigs may seizure from pain and distress.",
        "description_ja": "重度の疥癬感染で、痛みと苦痛によりモルモットが痙攣を起こすほどの激しい掻痒を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    {
        "name": "Cervical Lymphadenitis (Streptococcus zooepidemicus)",
        "name_ja": "頸部リンパ節炎（ストレプトコッカス・ズーエピデミカス）",
        "symptoms": {"abscess", "appetite_loss", "cervical_swelling", "fever", "lethargy"},
        "description": "Bacterial infection causing abscesses in cervical lymph nodes, commonly called 'lumps'. Can progress to septicaemia.",
        "description_ja": "頸部リンパ節に膿瘍を形成する細菌感染で、通称「しこり」。敗血症に進行することがあります。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "blood_chemistry"],
    },
    {
        "name": "Bordetella Pneumonia",
        "name_ja": "ボルデテラ肺炎",
        "symptoms": {"appetite_loss", "coughing", "fever", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Severe pneumonia caused by Bordetella bronchiseptica, often fatal. Guinea pigs are extremely susceptible to this organism.",
        "description_ja": "ボルデテラ・ブロンキセプティカによる重症肺炎で、しばしば致死的です。モルモットはこの菌に非常に感受性が高いです。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "tracheal_wash", "culture_sensitivity"],
    },
    {
        "name": "Streptococcus pneumoniae Pneumonia",
        "name_ja": "肺炎球菌性肺炎",
        "symptoms": {"fever", "lethargy", "nasal_discharge", "respiratory_distress", "sudden_death"},
        "description": "Acute bacterial pneumonia that can be rapidly fatal in guinea pigs. May present as sudden death without premonitory signs.",
        "description_ja": "モルモットで急速に致死的となり得る急性細菌性肺炎。前駆症状なく突然死として現れることがあります。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "blood_culture", "culture_sensitivity"],
    },
    {
        "name": "Adenovirus Infection",
        "name_ja": "アデノウイルス感染症",
        "symptoms": {"appetite_loss", "lethargy", "nasal_discharge", "pneumonia", "sudden_death"},
        "description": "Viral respiratory infection that can cause fatal pneumonia in guinea pigs, particularly in young or immunocompromised animals.",
        "description_ja": "モルモットに致死的な肺炎を引き起こすウイルス性呼吸器感染で、特に若齢や免疫不全の個体に多いです。",
        "urgency": "high",
        "recommended_tests": ["pcr_testing", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Chlamydial Conjunctivitis",
        "name_ja": "クラミジア結膜炎",
        "symptoms": {"bilateral_eye_involvement", "conjunctival_redness", "eye_discharge", "squinting"},
        "description": "Conjunctivitis caused by Chlamydia caviae, often bilateral. Can be subclinical in carrier animals.",
        "description_ja": "クラミジア・カビエによる結膜炎で、しばしば両側性です。保菌動物では無症状のことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["conjunctival_swab", "pcr_testing", "ophthalmic_exam"],
    },
    {
        "name": "Cytomegalovirus Infection",
        "name_ja": "サイトメガロウイルス感染症",
        "symptoms": {"immunosuppression", "lethargy", "salivary_gland_swelling", "weight_loss"},
        "description": "Infection by guinea pig cytomegalovirus causing salivary gland enlargement and potential immunosuppression.",
        "description_ja": "モルモットサイトメガロウイルスによる感染で、唾液腺腫大と免疫抑制の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_testing", "blood_chemistry", "physical_exam"],
    },
    {
        "name": "Rotavirus Enteritis",
        "name_ja": "ロタウイルス性腸炎",
        "symptoms": {"appetite_loss", "dehydration", "diarrhea", "lethargy", "weight_loss"},
        "description": "Viral enteritis primarily affecting young guinea pigs, causing watery diarrhea and dehydration.",
        "description_ja": "主に若いモルモットに発症するウイルス性腸炎で、水様性下痢と脱水を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["fecal_pcr", "physical_exam", "fecal_exam"],
    },
    {
        "name": "Clostridial Enterotoxemia",
        "name_ja": "クロストリジウム腸毒素血症",
        "symptoms": {"abdominal_distension", "dehydration", "diarrhea", "lethargy", "sudden_death"},
        "description": "Overgrowth of toxin-producing Clostridium species following antibiotic use or dietary changes. Often rapidly fatal.",
        "description_ja": "抗生物質使用や食事変更後の毒素産生クロストリジウム属菌の異常増殖。しばしば急速に致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_toxin_assay", "fecal_culture", "blood_chemistry"],
    },
    {
        "name": "Yersinia pseudotuberculosis Infection",
        "name_ja": "仮性結核菌感染症",
        "symptoms": {"diarrhea", "lethargy", "lymph_node_swelling", "sudden_death", "weight_loss"},
        "description": "Bacterial infection causing caseous lymphadenitis and granulomatous lesions in multiple organs. Zoonotic potential.",
        "description_ja": "複数臓器に乾酪性リンパ節炎と肉芽腫性病変を引き起こす細菌感染。人獣共通感染症の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["blood_culture", "fecal_culture", "necropsy"],
    },
    {
        "name": "Balantidium Infection",
        "name_ja": "バランチジウム感染症",
        "symptoms": {"dehydration", "diarrhea", "lethargy", "weight_loss"},
        "description": "Protozoal infection of the large intestine by Balantidium coli, usually subclinical but can cause disease in stressed animals.",
        "description_ja": "大腸のバランチジウム・コリによる原虫感染で、通常は無症状ですがストレス下の動物では発症することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_smear", "physical_exam"],
    },
    {
        "name": "Cryptosporidium wrairi Infection",
        "name_ja": "クリプトスポリジウム・ライリ感染症",
        "symptoms": {"dehydration", "diarrhea", "poor_growth", "weight_loss"},
        "description": "Species-specific Cryptosporidium infection causing chronic diarrhea and failure to thrive in young guinea pigs.",
        "description_ja": "種特異的なクリプトスポリジウム感染で、若いモルモットに慢性下痢と発育不良を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_acid_fast_stain", "fecal_pcr", "physical_exam"],
    },
    {
        "name": "Encephalitozoon cuniculi Infection",
        "name_ja": "エンセファリトゾーン・クニクリ感染症",
        "symptoms": {"ataxia", "head_tilt", "hind_limb_weakness", "renal_failure", "weight_loss"},
        "description": "Microsporidian parasite infection causing granulomatous encephalitis and nephritis, less common than in rabbits.",
        "description_ja": "肉芽腫性脳炎と腎炎を引き起こす微胞子虫感染で、ウサギほど一般的ではありません。",
        "urgency": "high",
        "recommended_tests": ["serology", "urinalysis", "neurological_exam"],
    },
    {
        "name": "Trichofolliculoma (Basal Cell Tumor)",
        "name_ja": "毛包腫（基底細胞腫）",
        "symptoms": {"hair_loss_around_mass", "skin_masses", "slow_growing_lump"},
        "description": "Benign hair follicle tumour, the most common skin neoplasia in guinea pigs. Typically found on the rump area.",
        "description_ja": "良性毛包腫瘍で、モルモットで最も一般的な皮膚腫瘍です。通常は臀部に見られます。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "physical_exam"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"rapid_growth", "skin_masses", "ulceration", "weight_loss"},
        "description": "Malignant connective tissue tumour that can occur anywhere on the body. Local recurrence is common after surgery.",
        "description_ja": "体のどこにでも発生する悪性結合組織腫瘍。手術後の局所再発が一般的です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Lung Adenocarcinoma",
        "name_ja": "肺腺癌",
        "symptoms": {"coughing", "exercise_intolerance", "lethargy", "respiratory_distress", "weight_loss"},
        "description": "Primary lung tumour, relatively common in guinea pigs. May metastasize to other organs.",
        "description_ja": "原発性肺腫瘍で、モルモットに比較的多く見られます。他の臓器に転移することがあります。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "fine_needle_aspirate", "blood_chemistry"],
    },
    {
        "name": "Uterine Adenocarcinoma",
        "name_ja": "子宮腺癌",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "vaginal_bleeding", "weight_loss"},
        "description": "Malignant tumour of the uterine lining, relatively common in intact does over 3 years of age.",
        "description_ja": "子宮内膜の悪性腫瘍で、3歳以上の未避妊雌に比較的多く見られます。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray", "histopathology"],
    },
    {
        "name": "Ovarian Teratoma",
        "name_ja": "卵巣奇形腫",
        "symptoms": {"abdominal_distension", "hair_loss", "lethargy", "weight_gain"},
        "description": "Rare ovarian tumour containing tissues from multiple germ cell layers, including teeth, hair, and bone.",
        "description_ja": "歯、毛、骨を含む複数の胚細胞層からの組織を含む稀な卵巣腫瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray", "histopathology"],
    },
    {
        "name": "Leukemia (Lymphocytic)",
        "name_ja": "白血病（リンパ球性）",
        "symptoms": {"anemia", "lethargy", "lymph_node_swelling", "splenomegaly", "weight_loss"},
        "description": "Neoplastic proliferation of lymphocytes in the blood, associated with retrovirus in guinea pigs (guinea pig leukemia virus).",
        "description_ja": "血中リンパ球の腫瘍性増殖で、モルモットではレトロウイルス（モルモット白血病ウイルス）に関連します。",
        "urgency": "high",
        "recommended_tests": ["cbc", "blood_smear", "bone_marrow_aspirate"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "limb_swelling", "pain", "pathological_fracture", "weight_loss"},
        "description": "Malignant bone tumour with high potential for pulmonary metastasis. Can affect any bone.",
        "description_ja": "肺転移の高い可能性を持つ悪性骨腫瘍。どの骨にも発生し得ます。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "chest_xray", "biopsy"],
    },
    {
        "name": "Ketosis (Non-pregnant)",
        "name_ja": "ケトーシス（非妊娠）",
        "symptoms": {"appetite_loss", "lethargy", "rapid_breathing", "sweet_breath_odor", "weakness"},
        "description": "Ketosis in non-pregnant guinea pigs from prolonged anorexia or stress, causing hepatic lipidosis and metabolic derangement.",
        "description_ja": "長期の食欲不振やストレスによる非妊娠モルモットのケトーシスで、肝リピドーシスと代謝異常を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "blood_glucose", "urinalysis"],
    },
    {
        "name": "Calcium Phosphorus Imbalance",
        "name_ja": "カルシウム-リン不均衡",
        "symptoms": {"bone_pain", "lameness", "pathological_fracture", "teeth_problems", "weight_loss"},
        "description": "Dietary imbalance in calcium and phosphorus ratios leading to metabolite bone disease and soft tissue calcification.",
        "description_ja": "食事中のカルシウムとリンの比率の不均衡による代謝性骨疾患と軟部組織石灰化です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "xray", "diet_review"],
    },
    {
        "name": "Hypovitaminosis A",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"eye_discharge", "infertility", "poor_coat", "poor_growth", "weight_loss"},
        "description": "Vitamin A deficiency causing keratinisation of epithelial tissues, reproductive failure, and impaired immunity.",
        "description_ja": "ビタミンA欠乏により上皮組織の角化、繁殖障害、免疫機能低下を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "diet_review", "physical_exam"],
    },
    {
        "name": "Vitamin E / Selenium Deficiency",
        "name_ja": "ビタミンE/セレン欠乏症",
        "symptoms": {"lethargy", "muscle_weakness", "poor_coat", "stiff_gait", "sudden_death"},
        "description": "Nutritional deficiency causing white muscle disease (muscular dystrophy) and potentially sudden cardiac death.",
        "description_ja": "白筋病（筋ジストロフィー）と心臓突然死を引き起こす可能性のある栄養欠乏症です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "vitamin_e_level", "muscle_biopsy"],
    },
    {
        "name": "Grease Gland Infection",
        "name_ja": "脂腺感染",
        "symptoms": {"crusting_at_rump", "foul_odor_from_rump", "hair_loss_rump", "skin_infection"},
        "description": "Bacterial infection of the grease gland (caudal gland) on the rump, particularly common in intact males.",
        "description_ja": "臀部の脂腺（尾側腺）の細菌感染で、特に未去勢の雄に多いです。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture", "cytology"],
    },
    {
        "name": "Ringworm (Trichophyton mentagrophytes)",
        "name_ja": "皮膚糸状菌症（トリコフィトン・メンタグロフィテス）",
        "symptoms": {"circular_hair_loss", "crusting", "mild_itching", "skin_scaling"},
        "description": "Dermatophyte fungal infection causing circular areas of alopecia with scaling. Zoonotic to humans.",
        "description_ja": "鱗屑を伴う円形脱毛を引き起こす皮膚糸状菌感染。ヒトへの人獣共通感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "wood_lamp", "skin_scraping"],
    },
    {
        "name": "Chirodiscoides caviae Infestation",
        "name_ja": "キロディスコイデス・カビエ寄生",
        "symptoms": {"hair_loss", "mild_itching", "poor_coat", "visible_mites_on_fur"},
        "description": "Non-burrowing fur mite specific to guinea pigs, usually causing mild signs unless in heavy infestation.",
        "description_ja": "モルモット特異的な非穿孔性毛ダニで、重度の寄生でない限り通常軽度の症状です。",
        "urgency": "low",
        "recommended_tests": ["coat_exam", "microscopy", "skin_scraping"],
    },
    {
        "name": "Pasteurella multocida Infection",
        "name_ja": "パスツレラ・マルトシダ感染症",
        "symptoms": {"abscesses", "fever", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Bacterial infection causing respiratory disease, abscesses, and septicaemia in guinea pigs.",
        "description_ja": "モルモットに呼吸器疾患、膿瘍、敗血症を引き起こす細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Klebsiella Pneumonia",
        "name_ja": "クレブシエラ肺炎",
        "symptoms": {"fever", "lethargy", "nasal_discharge", "respiratory_distress", "sudden_death"},
        "description": "Severe bacterial pneumonia caused by Klebsiella pneumoniae, often resistant to multiple antibiotics.",
        "description_ja": "クレブシエラ・ニューモニエによる重症細菌性肺炎で、しばしば多剤耐性です。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "tracheal_wash", "culture_sensitivity"],
    },
    {
        "name": "Mycoplasma Infection",
        "name_ja": "マイコプラズマ感染症",
        "symptoms": {"conjunctivitis", "nasal_discharge", "respiratory_distress", "sneezing"},
        "description": "Chronic respiratory infection by Mycoplasma species causing persistent rhinitis and potentially pneumonia.",
        "description_ja": "マイコプラズマ属による慢性呼吸器感染で、持続的な鼻炎と肺炎の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_testing", "chest_xray", "nasal_swab"],
    },
    {
        "name": "Renal Calculi",
        "name_ja": "腎結石",
        "symptoms": {"appetite_loss", "blood_in_urine", "pain", "polydipsia", "polyuria"},
        "description": "Formation of calcium-based stones in the kidneys, common in guinea pigs due to unique calcium metabolism.",
        "description_ja": "腎臓内のカルシウムベースの結石形成で、独特なカルシウム代謝のためモルモットに多いです。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "renal_ultrasound", "urinalysis"],
    },
    {
        "name": "Ureteral Calculi",
        "name_ja": "尿管結石",
        "symptoms": {"appetite_loss", "blood_in_urine", "hunched_posture", "lethargy", "pain"},
        "description": "Stone lodged in the ureter causing obstruction and hydronephrosis. Requires urgent surgical intervention.",
        "description_ja": "尿管に嵌頓した結石で、閉塞と水腎症を引き起こします。緊急外科介入が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "renal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Pyelonephritis",
        "name_ja": "腎盂腎炎",
        "symptoms": {"appetite_loss", "back_pain", "fever", "lethargy", "polydipsia"},
        "description": "Ascending bacterial infection of the kidney, often secondary to lower urinary tract disease.",
        "description_ja": "下部尿路疾患に続発することが多い腎臓の上行性細菌感染です。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "urine_culture", "renal_ultrasound"],
    },
    {
        "name": "Preputial Obstruction",
        "name_ja": "包皮閉塞",
        "symptoms": {"genital_swelling", "licking_genital_area", "pain", "straining_to_urinate"},
        "description": "Accumulation of smegma, hay, or bedding in the preputial fold causing urinary obstruction in males.",
        "description_ja": "包皮のひだに恥垢、干し草、床材が蓄積し、雄の排尿閉塞を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "genital_exam", "urinalysis"],
    },
    {
        "name": "Perineal Sac Impaction",
        "name_ja": "肛門嚢嵌頓",
        "symptoms": {"fecal_accumulation_perineum", "foul_odor", "skin_irritation_perineum", "straining_to_defecate"},
        "description": "Accumulation of faecal material and secretions in the perineal sac, common in older boars.",
        "description_ja": "肛門嚢に糞便物質と分泌物が蓄積する状態で、高齢の雄に多いです。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "perineal_exam"],
    },
    {
        "name": "Aortic Calcification",
        "name_ja": "大動脈石灰化",
        "symptoms": {"exercise_intolerance", "hind_limb_weakness", "lethargy", "sudden_death"},
        "description": "Dystrophic or metastatic calcification of the aorta and major arteries, often subclinical until vessel occlusion.",
        "description_ja": "大動脈と主要動脈の変性性または転移性石灰化で、血管閉塞まで無症状のことが多いです。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "echocardiography", "blood_chemistry"],
    },
    {
        "name": "Dilated Cardiomyopathy",
        "name_ja": "拡張型心筋症",
        "symptoms": {"abdominal_distension", "exercise_intolerance", "lethargy", "respiratory_distress", "sudden_death"},
        "description": "Dilation and weakening of the heart chambers leading to congestive heart failure. Associated with vitamin C deficiency.",
        "description_ja": "心室の拡張と弱化によるうっ血性心不全。ビタミンC欠乏と関連します。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Tricuspid Valve Disease",
        "name_ja": "三尖弁疾患",
        "symptoms": {"abdominal_distension", "exercise_intolerance", "lethargy", "peripheral_edema"},
        "description": "Degeneration or insufficiency of the tricuspid valve causing right-sided heart failure.",
        "description_ja": "三尖弁の変性または不全による右心不全です。",
        "urgency": "moderate",
        "recommended_tests": ["echocardiography", "chest_xray", "physical_exam"],
    },
    {
        "name": "Hepatic Cyst",
        "name_ja": "肝嚢胞",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "weight_loss"},
        "description": "Fluid-filled cysts within the liver, which may be single or multiple. Usually incidental but can cause compression.",
        "description_ja": "肝臓内の液体で満たされた嚢胞で、単発または多発性。通常偶発的ですが圧迫を引き起こすことがあります。",
        "urgency": "low",
        "recommended_tests": ["abdominal_ultrasound", "blood_chemistry", "physical_exam"],
    },
    {
        "name": "Pancreatic Islet Cell Tumor",
        "name_ja": "膵島細胞腫瘍",
        "symptoms": {"collapse", "lethargy", "seizures", "tremors", "weakness"},
        "description": "Functional tumour of the pancreatic islet cells causing hypoglycaemia from excess insulin production.",
        "description_ja": "過剰インスリン産生により低血糖を引き起こす膵島細胞の機能性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "insulin_level", "abdominal_ultrasound"],
    },
    {
        "name": "Mandibular Elongation",
        "name_ja": "下顎歯根伸長",
        "symptoms": {"appetite_loss", "drooling", "eye_discharge", "jaw_swelling", "weight_loss"},
        "description": "Elongation of mandibular cheek tooth roots penetrating the ventral mandible, causing palpable lumps and osteomyelitis.",
        "description_ja": "下顎臼歯の歯根が下顎骨底部を貫通し、触知可能なしこりと骨髄炎を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "ct_scan", "dental_exam"],
    },
    {
        "name": "Maxillary Tooth Root Elongation",
        "name_ja": "上顎歯根伸長",
        "symptoms": {"appetite_loss", "epiphora", "eye_discharge", "facial_swelling", "nasal_discharge"},
        "description": "Elongation of upper cheek tooth roots into the nasal cavity or orbit causing epiphora and nasal discharge.",
        "description_ja": "上顎臼歯の歯根が鼻腔や眼窩に伸長し、流涙と鼻汁を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "ct_scan", "ophthalmic_exam"],
    },
    {
        "name": "Oral Papilloma",
        "name_ja": "口腔パピローマ",
        "symptoms": {"appetite_loss", "difficulty_eating", "drooling", "visible_mass_in_mouth"},
        "description": "Benign papillomatous growth in the oral cavity that may interfere with eating and prehension.",
        "description_ja": "口腔内の良性乳頭腫様増殖物で、摂食と把持を妨げることがあります。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "biopsy", "dental_exam"],
    },
    {
        "name": "Tibial Fracture",
        "name_ja": "脛骨骨折",
        "symptoms": {"crepitus", "lameness", "limb_swelling", "non_weight_bearing", "pain"},
        "description": "Fracture of the tibia from falls, improper handling, or metabolic bone disease. Common fracture site in guinea pigs.",
        "description_ja": "落下、不適切な取り扱い、代謝性骨疾患による脛骨の骨折。モルモットで一般的な骨折部位です。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Elbow Osteoarthritis",
        "name_ja": "肘関節骨関節炎",
        "symptoms": {"joint_swelling", "lameness", "reluctance_to_move", "stiff_gait"},
        "description": "Degenerative joint disease of the elbow, common in obese or aged guinea pigs.",
        "description_ja": "肘の変形性関節症で、肥満または高齢のモルモットに多いです。",
        "urgency": "moderate",
        "recommended_tests": ["joint_xray", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Toe Nail Overgrowth / Curling",
        "name_ja": "爪の過長/巻き爪",
        "symptoms": {"bleeding_from_nail", "curled_nails", "foot_pain", "lameness"},
        "description": "Excessive nail growth curling into the footpad causing pain, infection, and difficulty walking.",
        "description_ja": "爪の過度の成長により足裏に巻き込み、痛み、感染、歩行困難を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "foot_exam"],
    },
    {
        "name": "Interstitial Pneumonia",
        "name_ja": "間質性肺炎",
        "symptoms": {"coughing", "exercise_intolerance", "lethargy", "respiratory_distress", "weight_loss"},
        "description": "Chronic inflammation of the lung interstitium causing progressive respiratory compromise.",
        "description_ja": "肺間質の慢性炎症で、進行性の呼吸機能障害を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["chest_xray", "blood_gas_analysis", "lung_biopsy"],
    },
    {
        "name": "Follicular Cyst",
        "name_ja": "毛包嚢胞",
        "symptoms": {"hair_loss_around_cyst", "skin_cyst", "slow_growing_lump"},
        "description": "Benign cystic structure derived from hair follicles, filled with keratin debris. Common benign skin lesion.",
        "description_ja": "毛包由来の良性嚢胞構造で、ケラチン残渣で満たされています。一般的な良性皮膚病変です。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "physical_exam"],
    },
    {
        "name": "Fly Strike Prevention (At-Risk)",
        "name_ja": "ハエ侵襲予防（リスクあり）",
        "symptoms": {"mobility_issues", "obesity", "soiled_perineum", "urine_staining"},
        "description": "Guinea pigs with predisposing factors (obesity, diarrhea, wounds) at high risk for fly strike in warm weather.",
        "description_ja": "素因（肥満、下痢、創傷）を持つモルモットは暖かい天候でハエ侵襲のリスクが高いです。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "perineal_exam", "environmental_review"],
    },
    {
        "name": "Toxemia of Pregnancy (Late Gestation)",
        "name_ja": "妊娠中毒症（妊娠後期）",
        "symptoms": {"appetite_loss", "coma", "lethargy", "rapid_breathing", "seizures", "sudden_death"},
        "description": "Severe metabolic crisis in late pregnancy or early lactation from negative energy balance. Mortality rate is very high.",
        "description_ja": "妊娠後期または授乳初期の負のエネルギーバランスによる重度の代謝危機。死亡率は非常に高いです。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Pubic Symphysis Fusion",
        "name_ja": "恥骨結合癒合",
        "symptoms": {"abdominal_pain", "dystocia", "inability_to_deliver", "lethargy"},
        "description": "Fusion of the pubic symphysis in sows bred after 7-8 months of age for the first time, preventing normal delivery.",
        "description_ja": "7-8ヶ月齢以降に初めて交配された雌の恥骨結合の癒合で、正常分娩を妨げます。",
        "urgency": "emergency",
        "recommended_tests": ["pelvic_xray", "physical_exam", "abdominal_ultrasound"],
    },
    {
        "name": "Endometrial Hyperplasia",
        "name_ja": "子宮内膜過形成",
        "symptoms": {"abdominal_distension", "bloody_vaginal_discharge", "lethargy", "vaginal_discharge"},
        "description": "Proliferation of the uterine lining, often progressing to cystic endometrial hyperplasia and pyometra.",
        "description_ja": "子宮内膜の増殖で、嚢胞性子宮内膜過形成と子宮蓄膿症に進行することが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "vaginal_cytology", "physical_exam"],
    },
    {
        "name": "Fetal Macrosomia",
        "name_ja": "胎児巨大症",
        "symptoms": {"abdominal_distension", "dystocia", "lethargy", "straining"},
        "description": "Overly large foetuses causing dystocia, particularly in sows with small litters where pups grow larger.",
        "description_ja": "過度に大きな胎児による難産で、特に産仔数が少なく子が大きくなる雌に多いです。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Galactostasis",
        "name_ja": "乳汁うっ滞",
        "symptoms": {"appetite_loss", "fever", "mammary_pain", "mammary_swelling"},
        "description": "Accumulation and stasis of milk in the mammary glands, which may progress to mastitis if not managed.",
        "description_ja": "乳腺への乳汁蓄積とうっ滞で、管理されなければ乳腺炎に進行することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "mammary_exam", "cytology"],
    },
    {
        "name": "Hay Poke (Corneal)",
        "name_ja": "干し草による角膜刺傷",
        "symptoms": {"corneal_opacity", "eye_discharge", "eye_redness", "pawing_at_eye", "squinting"},
        "description": "Corneal injury from timothy hay or other sharp forage material penetrating the eye surface.",
        "description_ja": "チモシーや他の鋭い牧草による角膜表面への刺傷です。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam", "physical_exam"],
    },
    {
        "name": "Hay Poke (Nasal)",
        "name_ja": "干し草による鼻腔内刺入",
        "symptoms": {"head_shaking", "nasal_discharge", "pawing_at_nose", "sneezing"},
        "description": "Hay or grass seed lodged in the nasal passage causing unilateral nasal discharge and persistent sneezing.",
        "description_ja": "干し草や草の種子が鼻腔に入り込み、片側性の鼻汁と持続的なくしゃみを引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_exam", "skull_xray", "rhinoscopy"],
    },
]


SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # General / systemic
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite Loss"},
    "weight_loss": {"ja": "体重減少", "en": "Weight Loss"},
    "weight_gain": {"ja": "体重増加", "en": "Weight Gain"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "hypothermia": {"ja": "低体温", "en": "Hypothermia"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    "sudden_death_risk": {"ja": "突然死リスク", "en": "Sudden Death Risk"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "pain_on_touch": {"ja": "触ると痛がる", "en": "Pain on Touch"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth Grinding (Bruxism)"},
    "stress_signs": {"ja": "ストレス徴候", "en": "Stress Signs"},
    "poor_growth": {"ja": "発育不良", "en": "Poor Growth"},
    "hunched_posture": {"ja": "背中を丸めた姿勢", "en": "Hunched Posture"},
    # Respiratory
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal Discharge"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "labored_breathing": {"ja": "努力呼吸", "en": "Labored Breathing"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "muffled_heart_sounds": {"ja": "心音減弱", "en": "Muffled Heart Sounds"},
    # Gastrointestinal
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "bloated_abdomen": {"ja": "腹部膨満", "en": "Bloated Abdomen"},
    "reduced_fecal_output": {"ja": "排便量減少", "en": "Reduced Fecal Output"},
    "bloody_stool": {"ja": "血便", "en": "Bloody Stool"},
    "foul_odor": {"ja": "悪臭", "en": "Foul Odor"},
    "difficulty_defecating": {"ja": "排便困難", "en": "Difficulty Defecating"},
    "visible_prolapse": {"ja": "脱出が目に見える", "en": "Visible Prolapse"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "perianal_irritation": {"ja": "肛門周囲の刺激", "en": "Perianal Irritation"},
    # Dermatological
    "hair_loss": {"ja": "脱毛", "en": "Hair Loss"},
    "bilateral_hair_loss": {"ja": "左右対称の脱毛", "en": "Bilateral Hair Loss"},
    "patchy_fur": {"ja": "斑状の被毛喪失", "en": "Patchy Fur"},
    "crusty_skin": {"ja": "痂皮形成", "en": "Crusty Skin"},
    "scaling": {"ja": "鱗屑", "en": "Scaling"},
    "itching": {"ja": "痒み", "en": "Itching"},
    "severe_itching": {"ja": "激しい痒み", "en": "Severe Itching"},
    "circular_patches": {"ja": "円形の脱毛斑", "en": "Circular Bald Patches"},
    "rough_coat": {"ja": "被毛の荒れ", "en": "Rough Coat"},
    "redness": {"ja": "発赤", "en": "Redness"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "skin_lump": {"ja": "皮膚のしこり", "en": "Skin Lump"},
    "skin_wounds": {"ja": "皮膚の傷", "en": "Skin Wounds"},
    "discharge_from_lump": {"ja": "しこりからの分泌物", "en": "Discharge from Lump"},
    "self_mutilation": {"ja": "自傷行為", "en": "Self Mutilation"},
    "visible_parasites": {"ja": "目に見える寄生虫", "en": "Visible Parasites"},
    "greasy_coat": {"ja": "脂ぎった被毛", "en": "Greasy Coat"},
    "skin_thinning": {"ja": "皮膚の菲薄化", "en": "Skin Thinning"},
    "bleeding_from_mass": {"ja": "腫瘤からの出血", "en": "Bleeding from Mass"},
    "mammary_mass": {"ja": "乳腺のしこり", "en": "Mammary Mass"},
    # Musculoskeletal
    "limping": {"ja": "跛行", "en": "Limping"},
    "swollen_joints": {"ja": "関節の腫れ", "en": "Swollen Joints"},
    "swollen_feet": {"ja": "足の腫れ", "en": "Swollen Feet"},
    "foot_sores": {"ja": "足底の潰瘍", "en": "Foot Sores"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to Move"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "splayed_legs": {"ja": "開脚", "en": "Splayed Legs"},
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise Intolerance"},
    # Ophthalmological
    "crusty_eyes": {"ja": "目やに", "en": "Crusty Eyes"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye Discharge"},
    "swollen_eyes": {"ja": "眼の腫れ", "en": "Swollen Eyes"},
    "squinting": {"ja": "目を細める", "en": "Squinting"},
    "cloudy_eye": {"ja": "眼の混濁", "en": "Cloudy Eye"},
    "protruding_tissue_from_eye": {"ja": "眼からの組織突出", "en": "Protruding Tissue from Eye"},
    "vision_loss": {"ja": "視力低下", "en": "Vision Loss"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into Objects"},
    "cataracts_sign": {"ja": "白内障徴候", "en": "Cataracts Sign"},
    # Neurological
    "head_tilt": {"ja": "斜頸", "en": "Head Tilt"},
    "loss_of_balance": {"ja": "平衡失調", "en": "Loss of Balance"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "rolling": {"ja": "ローリング", "en": "Rolling"},
    "seizures": {"ja": "発作", "en": "Seizures"},
    "muscle_spasms": {"ja": "筋痙攣", "en": "Muscle Spasms"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "loss_of_consciousness": {"ja": "意識消失", "en": "Loss of Consciousness"},
    # Dental
    "drooling": {"ja": "よだれ", "en": "Drooling"},
    "difficulty_eating": {"ja": "摂食困難", "en": "Difficulty Eating"},
    "wet_chin": {"ja": "顎の濡れ", "en": "Wet Chin"},
    "facial_swelling": {"ja": "顔面の腫脹", "en": "Facial Swelling"},
    "visible_tooth_overgrowth": {"ja": "歯の過成長", "en": "Visible Tooth Overgrowth"},
    "mouth_sores": {"ja": "口内の傷", "en": "Mouth Sores"},
    "bleeding_gums": {"ja": "歯茎の出血", "en": "Bleeding Gums"},
    # Urinary
    "blood_in_urine": {"ja": "血尿", "en": "Blood in Urine"},
    "straining_to_urinate": {"ja": "排尿困難", "en": "Straining to Urinate"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent Urination"},
    "excessive_thirst": {"ja": "多飲", "en": "Excessive Thirst"},
    "excessive_urination": {"ja": "多尿", "en": "Excessive Urination"},
    "squealing_when_urinating": {"ja": "排尿時の鳴き声", "en": "Squealing when Urinating"},
    "foul_smelling_urine": {"ja": "悪臭のする尿", "en": "Foul Smelling Urine"},
    "gritty_urine": {"ja": "ざらつきのある尿", "en": "Gritty Urine"},
    "no_urination": {"ja": "無尿", "en": "No Urination"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    # Reproductive
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal Discharge"},
    "vaginal_bleeding": {"ja": "膣出血", "en": "Vaginal Bleeding"},
    "crusty_nipples": {"ja": "乳頭の痂皮", "en": "Crusty Nipples"},
    "hormonal_behavior": {"ja": "ホルモン性行動変化", "en": "Hormonal Behavior Changes"},
    "swollen_mammary_glands": {"ja": "乳腺の腫脹", "en": "Swollen Mammary Glands"},
    "no_delivery": {"ja": "分娩停止", "en": "No Delivery"},
    "distress_vocalizations": {"ja": "苦痛の鳴き声", "en": "Distress Vocalizations"},
    "testicular_swelling": {"ja": "精巣の腫れ", "en": "Testicular Swelling"},
    "groin_swelling": {"ja": "鼠径部の腫れ", "en": "Groin Swelling"},
    # Lymphatic
    "swollen_lymph_nodes": {"ja": "リンパ節腫脹", "en": "Swollen Lymph Nodes"},
    # Ear
    "ear_discharge": {"ja": "耳だれ", "en": "Ear Discharge"},
    "head_shaking": {"ja": "頭を振る", "en": "Head Shaking"},
    "ear_odor": {"ja": "耳の悪臭", "en": "Ear Odor"},
    # Grooming
    "difficulty_grooming": {"ja": "グルーミング困難", "en": "Difficulty Grooming"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species)
