"""Hamster disease dictionary and analysis module."""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── 消化器系 ──
    {
        "name": "Wet Tail (Proliferative Ileitis)",
        "name_ja": "ウェットテイル（増殖性回腸炎）",
        "symptoms": {"wet_tail", "diarrhea", "lethargy", "appetite_loss", "dehydration", "hunched_posture"},
        "description": "Severe bacterial enteritis caused by Lawsonia intracellularis, most common in young hamsters.",
        "description_ja": "ローソニア菌による重度の細菌性腸炎で、若いハムスターに最も多い。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_exam", "bacterial_culture"],
    },
    {
        "name": "Tyzzer's Disease",
        "name_ja": "ティザー病",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "sudden_death", "dehydration"},
        "description": "Acute bacterial infection caused by Clostridium piliforme, often fatal.",
        "description_ja": "クロストリジウム・ピリフォルメによる急性細菌感染症で、致死率が高い。",
        "urgency": "emergency",
        "recommended_tests": ["necropsy", "histopathology"],
    },
    {
        "name": "Diarrhea (Non-specific)",
        "name_ja": "下痢（非特異的）",
        "symptoms": {"diarrhea", "dehydration", "appetite_loss", "weight_loss"},
        "description": "Loose stools from dietary changes, stress, or mild infections.",
        "description_ja": "食事変化、ストレス、軽度感染による軟便。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "dietary_review"],
    },
    {
        "name": "Constipation",
        "name_ja": "便秘",
        "symptoms": {"constipation", "abdominal_distension", "appetite_loss", "straining"},
        "description": "Difficulty passing stool due to dehydration, low fiber, or obstruction.",
        "description_ja": "脱水、低繊維食、閉塞による排便困難。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"rectal_prolapse", "straining", "diarrhea", "bloody_stool"},
        "description": "Protrusion of rectal tissue, often secondary to severe diarrhea.",
        "description_ja": "重度の下痢に続発する直腸組織の脱出。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Intussusception",
        "name_ja": "腸重積",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "bloody_stool"},
        "description": "Telescoping of intestinal segments, often following severe enteritis.",
        "description_ja": "重度の腸炎に続発する腸管の重積。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Gastrointestinal Parasites",
        "name_ja": "消化管寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "appetite_loss", "rough_coat"},
        "description": "Infection with pinworms, tapeworms, or other intestinal parasites.",
        "description_ja": "蟯虫、条虫などの腸内寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Clostridiosis",
        "name_ja": "クロストリジウム感染症",
        "symptoms": {"diarrhea", "abdominal_distension", "sudden_death", "appetite_loss"},
        "description": "Clostridium difficile or perfringens enterotoxemia, often antibiotic-related.",
        "description_ja": "クロストリジウム腸毒素血症で、抗生物質関連が多い。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_toxin_test", "bacterial_culture"],
    },
    {
        "name": "Coccidiosis",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "rough_coat", "bloody_stool"},
        "description": "Protozoal parasite infection of the intestines.",
        "description_ja": "腸の原虫寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物摂取",
        "symptoms": {"appetite_loss", "lethargy", "abdominal_distension"},
        "description": "Ingestion of bedding, plastic, or other non-food items causing obstruction.",
        "description_ja": "床材やプラスチックなどの誤食による閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    # ── 頬袋疾患 ──
    {
        "name": "Cheek Pouch Impaction",
        "name_ja": "頬袋閉塞",
        "symptoms": {"cheek_swelling", "appetite_loss", "drooling", "pawing_at_mouth"},
        "description": "Food or bedding material becomes lodged in the cheek pouch.",
        "description_ja": "食物や床材が頬袋に詰まった状態。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "physical_exam"],
    },
    {
        "name": "Cheek Pouch Prolapse",
        "name_ja": "頬袋脱",
        "symptoms": {"cheek_pouch_prolapse", "drooling", "appetite_loss", "oral_mass"},
        "description": "Eversion of the cheek pouch lining, visible as a pink mass near the mouth.",
        "description_ja": "頬袋の内壁が反転し、口の近くにピンク色の腫瘤として見える。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Cheek Pouch Abscess",
        "name_ja": "頬袋膿瘍",
        "symptoms": {"cheek_swelling", "facial_swelling", "appetite_loss", "discharge"},
        "description": "Bacterial infection of the cheek pouch causing pus accumulation.",
        "description_ja": "頬袋の細菌感染による膿の蓄積。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "cytology"],
    },
    # ── 歯科 ──
    {
        "name": "Dental Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "weight_loss", "appetite_loss", "overgrown_teeth", "pawing_at_mouth"},
        "description": "Misalignment of incisors preventing proper wearing, leading to overgrowth.",
        "description_ja": "切歯の不整合により適切な摩耗が妨げられ過成長する。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Dental Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "drooling", "weight_loss", "eye_discharge"},
        "description": "Root infection causing facial swelling, may extend to the eye orbit.",
        "description_ja": "歯根感染による顔面腫脹、眼窩に波及することがある。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "bacterial_culture"],
    },
    # ── 呼吸器系 ──
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"labored_breathing", "nasal_discharge", "sneezing", "lethargy", "appetite_loss"},
        "description": "Bacterial or viral lung infection, often secondary to stress.",
        "description_ja": "ストレスに続発する細菌性またはウイルス性の肺感染症。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bacterial_culture"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"sneezing", "nasal_discharge", "wheezing", "eye_discharge"},
        "description": "Infection of the upper airways causing sneezing and nasal discharge.",
        "description_ja": "上気道感染によるくしゃみや鼻水。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "bacterial_culture"],
    },
    {
        "name": "Sendai Virus Infection",
        "name_ja": "センダイウイルス感染症",
        "symptoms": {"sneezing", "nasal_discharge", "labored_breathing", "lethargy", "rough_coat"},
        "description": "Respiratory virus that can cause severe pneumonia.",
        "description_ja": "重度の肺炎を引き起こすことがある呼吸器ウイルス。",
        "urgency": "high",
        "recommended_tests": ["serology", "pcr_test"],
    },
    # ── 皮膚科 ──
    {
        "name": "Demodex Mange",
        "name_ja": "ニキビダニ症",
        "symptoms": {"hair_loss", "dry_skin", "itching", "skin_crusting"},
        "description": "Skin mite infestation by Demodex species causing patchy hair loss.",
        "description_ja": "ニキビダニの寄生による斑状の脱毛。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Sarcoptic Mange",
        "name_ja": "疥癬",
        "symptoms": {"severe_itching", "hair_loss", "skin_crusting", "skin_redness", "scratching"},
        "description": "Intensely pruritic skin mite infestation.",
        "description_ja": "強い痒みを伴う疥癬虫の寄生。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Notoedres Mange",
        "name_ja": "ノトエドレス症",
        "symptoms": {"severe_itching", "skin_crusting", "hair_loss", "ear_crusting"},
        "description": "Burrowing mite infestation causing intense itching, especially on ears.",
        "description_ja": "穿孔性ダニの寄生による強い痒みと痂皮形成、特に耳に多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"hair_loss", "skin_crusting", "circular_lesions", "dry_skin"},
        "description": "Fungal skin infection causing circular patches of hair loss.",
        "description_ja": "真菌感染による円形の脱毛斑。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "woods_lamp", "skin_scraping"],
    },
    {
        "name": "Skin Abscess",
        "name_ja": "皮膚膿瘍",
        "symptoms": {"skin_lump", "swelling", "discharge", "pain", "fever"},
        "description": "Localized bacterial infection from bite wounds.",
        "description_ja": "咬傷から生じる限局性の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "bacterial_culture"],
    },
    {
        "name": "Fight Wound Infection",
        "name_ja": "喧嘩傷感染",
        "symptoms": {"wound", "swelling", "discharge", "pain", "hair_loss"},
        "description": "Bite wounds from cage mates that become infected.",
        "description_ja": "同居個体からの咬傷の感染。",
        "urgency": "moderate",
        "recommended_tests": ["wound_culture", "physical_exam"],
    },
    {
        "name": "Alopecia (Non-parasitic)",
        "name_ja": "脱毛症（非寄生虫性）",
        "symptoms": {"hair_loss", "dry_skin", "rough_coat"},
        "description": "Hair loss from nutritional deficiency, hormonal issues, or barbering.",
        "description_ja": "栄養不足、ホルモン異常、毛引きによる脱毛。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "dietary_review", "hormone_panel"],
    },
    {
        "name": "Flea Infestation",
        "name_ja": "ノミ寄生",
        "symptoms": {"itching", "scratching", "hair_loss", "skin_redness", "visible_parasites"},
        "description": "External parasite infestation causing pruritus.",
        "description_ja": "外部寄生虫による掻痒。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    # ── 腫瘍 ──
    {
        "name": "Mammary Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"skin_lump", "mammary_mass", "weight_loss", "lethargy"},
        "description": "Common tumor in female hamsters, may be benign or malignant.",
        "description_ja": "メスのハムスターに多い腫瘍で、良性または悪性。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "radiography"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "lethargy", "appetite_loss", "enlarged_lymph_nodes", "skin_lump"},
        "description": "Malignant cancer of the lymphatic system.",
        "description_ja": "リンパ系の悪性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "complete_blood_count"],
    },
    {
        "name": "Skin Tumor (General)",
        "name_ja": "皮膚腫瘍",
        "symptoms": {"skin_lump", "skin_mass_growth", "ulceration"},
        "description": "Various skin tumors including melanoma, papilloma, and fibroma.",
        "description_ja": "メラノーマ、乳頭腫、線維腫などの各種皮膚腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "biopsy"],
    },
    {
        "name": "Adrenal Tumor",
        "name_ja": "副腎腫瘍",
        "symptoms": {"hair_loss", "increased_thirst", "increased_urination", "abdominal_distension", "lethargy"},
        "description": "Tumor of the adrenal gland causing hormonal imbalances.",
        "description_ja": "副腎の腫瘍によるホルモン異常。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "hormone_panel"],
    },
    {
        "name": "Uterine Tumor",
        "name_ja": "子宮腫瘍",
        "symptoms": {"vaginal_bleeding", "abdominal_distension", "weight_loss", "appetite_loss"},
        "description": "Neoplasia of the uterus in intact female hamsters.",
        "description_ja": "未避妊メスの子宮の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "biopsy"],
    },
    {
        "name": "Intestinal Tumor",
        "name_ja": "腸管腫瘍",
        "symptoms": {"weight_loss", "diarrhea", "bloody_stool", "appetite_loss", "abdominal_distension"},
        "description": "Tumors of the gastrointestinal tract.",
        "description_ja": "消化管の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "biopsy"],
    },
    {
        "name": "Scent Gland Tumor",
        "name_ja": "臭腺腫瘍",
        "symptoms": {"skin_lump", "skin_crusting", "ulceration", "licking_flank"},
        "description": "Neoplasia of the flank scent glands, common in male Syrian hamsters.",
        "description_ja": "脇腹の臭腺の腫瘍で、オスのゴールデンハムスターに多い。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "cytology"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ（悪性黒色腫）",
        "symptoms": {"dark_skin_lesion", "skin_lump", "skin_mass_growth"},
        "description": "Malignant pigmented skin tumor.",
        "description_ja": "悪性の色素性皮膚腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Testicular Tumor",
        "name_ja": "精巣腫瘍",
        "symptoms": {"testicular_swelling", "asymmetric_testes", "weight_loss"},
        "description": "Tumors of the testes in intact male hamsters.",
        "description_ja": "未去勢オスの精巣腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy"],
    },
    {
        "name": "Liver Tumor",
        "name_ja": "肝臓腫瘍",
        "symptoms": {"abdominal_distension", "weight_loss", "lethargy", "jaundice", "appetite_loss"},
        "description": "Primary or metastatic liver tumors.",
        "description_ja": "原発性または転移性の肝臓腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "blood_chemistry", "biopsy"],
    },
    # ── 内分泌・代謝 ──
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "appetite_increase", "lethargy"},
        "description": "Insulin resistance/deficiency, especially common in Campbell's dwarf hamsters.",
        "description_ja": "インスリン抵抗性/不足で、キャンベルハムスターに特に多い。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "urinalysis", "fructosamine"],
    },
    {
        "name": "Cushing's Disease",
        "name_ja": "クッシング病",
        "symptoms": {"hair_loss", "increased_thirst", "increased_urination", "abdominal_distension", "thin_skin"},
        "description": "Excess cortisol from adrenal or pituitary tumors.",
        "description_ja": "副腎または下垂体腫瘍による過剰コルチゾール産生。",
        "urgency": "high",
        "recommended_tests": ["hormone_panel", "ultrasound"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "reduced_activity", "labored_breathing"},
        "description": "Excess body weight from overfeeding and inadequate exercise.",
        "description_ja": "過食と運動不足による過体重。",
        "urgency": "low",
        "recommended_tests": ["weight_assessment", "dietary_review"],
    },
    {
        "name": "Amyloidosis",
        "name_ja": "アミロイドーシス",
        "symptoms": {"weight_loss", "lethargy", "increased_thirst", "edema", "appetite_loss"},
        "description": "Deposition of amyloid protein in organs, especially kidneys and liver.",
        "description_ja": "腎臓や肝臓へのアミロイドタンパク質の沈着。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "biopsy", "urinalysis"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"lethargy", "appetite_loss", "weight_loss", "jaundice", "abdominal_distension"},
        "description": "Fat accumulation in the liver from obesity or anorexia.",
        "description_ja": "肥満や食欲不振による肝臓への脂肪蓄積。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound"],
    },
    # ── 循環器系 ──
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"labored_breathing", "lethargy", "cyanosis", "edema", "reduced_activity"},
        "description": "Heart muscle disease, common in older hamsters.",
        "description_ja": "高齢ハムスターに多い心筋疾患。",
        "urgency": "high",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"labored_breathing", "lethargy", "edema", "cyanosis", "ascites", "coughing"},
        "description": "Heart failure leading to fluid accumulation.",
        "description_ja": "心不全による液体貯留。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Atrial Thrombosis",
        "name_ja": "心房血栓症",
        "symptoms": {"labored_breathing", "cyanosis", "sudden_death", "lethargy", "hind_limb_weakness"},
        "description": "Blood clot in the heart atrium, often with cardiomyopathy.",
        "description_ja": "心房内の血栓形成で、心筋症に関連することが多い。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography"],
    },
    # ── 泌尿器系 ──
    {
        "name": "Chronic Renal Failure",
        "name_ja": "慢性腎不全",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function in older hamsters.",
        "description_ja": "高齢ハムスターの腎機能の進行性低下。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    {
        "name": "Urolithiasis",
        "name_ja": "尿路結石症",
        "symptoms": {"blood_in_urine", "straining", "frequent_urination", "pain"},
        "description": "Mineral stone formation in the urinary bladder.",
        "description_ja": "膀胱内の結石形成。",
        "urgency": "high",
        "recommended_tests": ["radiography", "urinalysis", "ultrasound"],
    },
    {
        "name": "Cystitis",
        "name_ja": "膀胱炎",
        "symptoms": {"blood_in_urine", "frequent_urination", "straining", "discomfort"},
        "description": "Bacterial infection of the urinary bladder.",
        "description_ja": "膀胱の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "bacterial_culture"],
    },
    # ── 神経系 ──
    {
        "name": "Cage Paralysis",
        "name_ja": "ケージ麻痺",
        "symptoms": {"hind_limb_weakness", "paralysis", "muscle_wasting", "reduced_activity"},
        "description": "Hind limb paralysis from vitamin deficiency and lack of exercise.",
        "description_ja": "ビタミン欠乏と運動不足による後肢麻痺。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "dietary_review", "radiography"],
    },
    {
        "name": "Stroke",
        "name_ja": "脳卒中",
        "symptoms": {"head_tilt", "circling", "loss_of_balance", "paralysis", "disorientation"},
        "description": "Disruption of blood supply to the brain, more common in older hamsters.",
        "description_ja": "脳への血液供給の途絶で、高齢ハムスターに多い。",
        "urgency": "emergency",
        "recommended_tests": ["neurological_exam", "physical_exam"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "circling", "loss_of_balance", "nystagmus", "disorientation"},
        "description": "Inner ear or brain disorder affecting balance.",
        "description_ja": "内耳または脳の障害で平衡感覚に影響する。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "neurological_exam"],
    },
    {
        "name": "Epilepsy / Seizures",
        "name_ja": "てんかん／痙攣",
        "symptoms": {"seizures", "tremors", "disorientation", "loss_of_balance", "unconsciousness"},
        "description": "Involuntary convulsive episodes, may be genetic or metabolic.",
        "description_ja": "不随意の痙攣発作で、遺伝的または代謝性のことがある。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "neurological_exam"],
    },
    # ── 眼科 ──
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudy_eyes", "vision_loss", "bumping_into_objects"},
        "description": "Lens opacity, common in diabetic and elderly hamsters.",
        "description_ja": "水晶体の混濁で、糖尿病や高齢のハムスターに多い。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose"],
    },
    {
        "name": "Glaucoma",
        "name_ja": "緑内障",
        "symptoms": {"eye_bulging", "eye_redness", "pain", "cloudy_eyes", "vision_loss"},
        "description": "Increased intraocular pressure causing eye enlargement.",
        "description_ja": "眼圧上昇による眼球肥大。",
        "urgency": "high",
        "recommended_tests": ["tonometry", "ophthalmic_exam"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "eye_swelling", "squinting"},
        "description": "Inflammation of the conjunctiva from infection or irritation.",
        "description_ja": "感染や刺激による結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "bacterial_culture"],
    },
    {
        "name": "Eye Proptosis",
        "name_ja": "眼球突出",
        "symptoms": {"eye_bulging", "eye_redness", "pain"},
        "description": "Protrusion of the eyeball from retrobulbar abscess or trauma.",
        "description_ja": "眼窩後方の膿瘍や外傷による眼球の突出。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmic_exam", "skull_radiography"],
    },
    {
        "name": "Entropion",
        "name_ja": "眼瞼内反",
        "symptoms": {"squinting", "eye_discharge", "eye_redness"},
        "description": "Inward rolling of the eyelid causing corneal irritation.",
        "description_ja": "眼瞼が内側に巻き込み角膜を刺激する。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam"],
    },
    # ── 耳 ──
    {
        "name": "Otitis",
        "name_ja": "外耳炎・中耳炎",
        "symptoms": {"head_tilt", "scratching_ears", "ear_discharge", "pain", "loss_of_balance"},
        "description": "Bacterial infection of the ear canal or middle ear.",
        "description_ja": "外耳道または中耳の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "bacterial_culture"],
    },
    # ── 感染症 ──
    {
        "name": "Hamster Polyomavirus",
        "name_ja": "ハムスターポリオーマウイルス",
        "symptoms": {"skin_lump", "hair_loss", "wasting", "lethargy"},
        "description": "Viral infection causing skin tumors and lymphoma.",
        "description_ja": "皮膚腫瘍やリンパ腫を引き起こすウイルス感染。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Lymphocytic Choriomeningitis (LCMV)",
        "name_ja": "リンパ球性脈絡髄膜炎",
        "symptoms": {"lethargy", "weight_loss", "tremors", "seizures", "hunched_posture"},
        "description": "Zoonotic viral infection; hamsters may be asymptomatic carriers.",
        "description_ja": "人獣共通のウイルス感染症で、無症候性キャリアになることがある。",
        "urgency": "high",
        "recommended_tests": ["serology", "pcr_test"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "dehydration", "sudden_death"},
        "description": "Bacterial infection with zoonotic potential.",
        "description_ja": "人獣共通のサルモネラ菌感染。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "complete_blood_count"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "appetite_loss", "labored_breathing", "sudden_death"},
        "description": "Systemic bacterial infection spreading through the bloodstream.",
        "description_ja": "血流を介した全身性細菌感染。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count"],
    },
    # ── 運動器系 ──
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"lameness", "pain", "swelling", "limb_deformity", "reduced_activity"},
        "description": "Broken bones from falls, wheel injuries, or cage bar accidents.",
        "description_ja": "落下、回し車事故、ケージの隙間による骨折。",
        "urgency": "high",
        "recommended_tests": ["radiography"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "reduced_activity", "stiffness", "pain"},
        "description": "Degenerative joint disease in older hamsters.",
        "description_ja": "高齢ハムスターの変性性関節疾患。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    # ── 生殖器系 ──
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "abdominal_distension", "lethargy", "appetite_loss", "increased_thirst"},
        "description": "Bacterial infection of the uterus with pus accumulation.",
        "description_ja": "子宮の細菌感染による膿の蓄積。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "radiography", "complete_blood_count"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "vaginal_bleeding", "lethargy", "abdominal_distension"},
        "description": "Difficulty giving birth.",
        "description_ja": "分娩困難。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "mammary_redness", "fever", "appetite_loss", "lethargy"},
        "description": "Bacterial infection of the mammary glands in nursing females.",
        "description_ja": "授乳中のメスの乳腺感染。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "bacterial_culture"],
    },
    # ── 環境・栄養 ──
    {
        "name": "Heatstroke",
        "name_ja": "熱中症",
        "symptoms": {"labored_breathing", "lethargy", "weakness", "drooling", "unconsciousness"},
        "description": "Hyperthermia from high ambient temperature; hamsters are very heat-sensitive.",
        "description_ja": "高温環境による高体温症で、ハムスターは熱に非常に弱い。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "physical_exam"],
    },
    {
        "name": "Hibernation / Torpor",
        "name_ja": "擬似冬眠",
        "symptoms": {"unresponsiveness", "cold_body", "slow_breathing", "stiffness"},
        "description": "State of torpor triggered by cold temperatures; can be mistaken for death.",
        "description_ja": "低温により誘発される仮死状態。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "physical_exam"],
    },
    {
        "name": "Vitamin Deficiency",
        "name_ja": "ビタミン欠乏症",
        "symptoms": {"hair_loss", "rough_coat", "lethargy", "weight_loss", "muscle_wasting"},
        "description": "Deficiency of vitamins D, E, or B complex.",
        "description_ja": "ビタミンD、E、B群の欠乏。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_review", "blood_chemistry"],
    },
    {
        "name": "Antibiotic Toxicity",
        "name_ja": "抗生物質中毒",
        "symptoms": {"diarrhea", "appetite_loss", "lethargy", "dehydration", "sudden_death"},
        "description": "Fatal dysbiosis from antibiotics toxic to hamsters (penicillin, erythromycin, lincomycin).",
        "description_ja": "ハムスターに有害な抗生物質による致死的菌交代現象。",
        "urgency": "emergency",
        "recommended_tests": ["medication_review", "fecal_exam"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"dehydration", "lethargy", "dry_skin", "sunken_eyes", "skin_tenting"},
        "description": "Insufficient fluid intake or excess fluid loss.",
        "description_ja": "水分摂取不足または過剰な水分喪失。",
        "urgency": "high",
        "recommended_tests": ["skin_turgor_test", "physical_exam"],
    },
    # ── 行動 ──
    {
        "name": "Stress-Related Behaviors",
        "name_ja": "ストレス関連行動",
        "symptoms": {"bar_chewing", "excessive_grooming", "aggression", "reduced_activity"},
        "description": "Stereotypic behaviors from inadequate cage size or enrichment.",
        "description_ja": "不適切なケージサイズやエンリッチメント不足による常同行動。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review"],
    },
    {
        "name": "Barbering",
        "name_ja": "毛引き",
        "symptoms": {"hair_loss", "skin_redness", "excessive_grooming"},
        "description": "Excessive fur chewing by self or cage mate.",
        "description_ja": "自己または同居個体による過度の毛噛み。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "skin_scraping"],
    },
    # ── その他 ──
    {
        "name": "Scent Gland Inflammation",
        "name_ja": "臭腺炎",
        "symptoms": {"skin_crusting", "swelling", "discharge", "licking_flank"},
        "description": "Infection or inflammation of the flank scent glands.",
        "description_ja": "脇腹の臭腺の感染または炎症。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "physical_exam"],
    },
    {
        "name": "Polycystic Disease",
        "name_ja": "多嚢胞性疾患",
        "symptoms": {"abdominal_distension", "weight_loss", "lethargy"},
        "description": "Cyst formation in liver, kidneys, or other organs.",
        "description_ja": "肝臓、腎臓などの臓器の嚢胞形成。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "blood_chemistry"],
    },
    {
        "name": "Hypothyroidism",
        "name_ja": "甲状腺機能低下症",
        "symptoms": {"weight_gain", "lethargy", "hair_loss", "dry_skin", "cold_intolerance"},
        "description": "Underactive thyroid gland causing metabolic slowdown.",
        "description_ja": "甲状腺機能低下による代謝の低下。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "blood_chemistry"],
    },
    {
        "name": "Splenomegaly",
        "name_ja": "脾腫",
        "symptoms": {"abdominal_distension", "lethargy", "weight_loss"},
        "description": "Enlarged spleen from infection, lymphoma, or amyloidosis.",
        "description_ja": "感染、リンパ腫、アミロイドーシスによる脾臓腫大。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "complete_blood_count", "cytology"],
    },
    {
        "name": "Nasal Tumor",
        "name_ja": "鼻腔腫瘍",
        "symptoms": {"nasal_discharge", "sneezing", "facial_swelling", "labored_breathing"},
        "description": "Tumors within the nasal cavity.",
        "description_ja": "鼻腔内の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "biopsy"],
    },
    {
        "name": "Tail Slip (Degloving)",
        "name_ja": "テイルスリップ",
        "symptoms": {"tail_injury", "bleeding", "pain"},
        "description": "Loss of tail skin from improper handling.",
        "description_ja": "不適切な取り扱いによる尾の皮膚喪失。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Proliferative Colitis",
        "name_ja": "増殖性大腸炎",
        "symptoms": {"diarrhea", "weight_loss", "rectal_prolapse", "bloody_stool"},
        "description": "Thickening of the colon wall causing chronic diarrhea.",
        "description_ja": "結腸壁の肥厚による慢性下痢。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "histopathology"],
    },
    {
        "name": "Pneumocystis Pneumonia",
        "name_ja": "ニューモシスチス肺炎",
        "symptoms": {"labored_breathing", "weight_loss", "lethargy", "coughing"},
        "description": "Opportunistic fungal lung infection in immunocompromised hamsters.",
        "description_ja": "免疫不全ハムスターの日和見真菌性肺感染。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bronchoalveolar_lavage"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "wet_tail": {"ja": "ウェットテイル（肛門周囲の汚れ）", "en": "Wet tail (soiled perianal area)"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "lethargy": {"ja": "元気消失", "en": "Lethargy"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite loss"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "hunched_posture": {"ja": "猫背姿勢", "en": "Hunched posture"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "rectal_prolapse": {"ja": "直腸脱", "en": "Rectal prolapse"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "rough_coat": {"ja": "被毛粗剛", "en": "Rough coat"},
    "cheek_swelling": {"ja": "頬の腫れ", "en": "Cheek swelling"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "pawing_at_mouth": {"ja": "口を掻く", "en": "Pawing at mouth"},
    "cheek_pouch_prolapse": {"ja": "頬袋脱", "en": "Cheek pouch prolapse"},
    "oral_mass": {"ja": "口腔内腫瘤", "en": "Oral mass"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "discharge": {"ja": "分泌物", "en": "Discharge"},
    "overgrown_teeth": {"ja": "歯の過成長", "en": "Overgrown teeth"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "hair_loss": {"ja": "脱毛", "en": "Hair loss"},
    "dry_skin": {"ja": "乾燥肌", "en": "Dry skin"},
    "itching": {"ja": "掻痒", "en": "Itching"},
    "skin_crusting": {"ja": "皮膚痂皮", "en": "Skin crusting"},
    "severe_itching": {"ja": "強い掻痒", "en": "Severe itching"},
    "skin_redness": {"ja": "皮膚発赤", "en": "Skin redness"},
    "scratching": {"ja": "掻き壊し", "en": "Scratching"},
    "circular_lesions": {"ja": "円形病変", "en": "Circular lesions"},
    "skin_lump": {"ja": "皮膚の腫瘤", "en": "Skin lump"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "pain": {"ja": "痛み", "en": "Pain"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "wound": {"ja": "創傷", "en": "Wound"},
    "mammary_mass": {"ja": "乳腺腫瘤", "en": "Mammary mass"},
    "enlarged_lymph_nodes": {"ja": "リンパ節腫大", "en": "Enlarged lymph nodes"},
    "skin_mass_growth": {"ja": "皮膚腫瘤の増大", "en": "Growing skin mass"},
    "ulceration": {"ja": "潰瘍化", "en": "Ulceration"},
    "increased_thirst": {"ja": "多飲", "en": "Increased thirst"},
    "increased_urination": {"ja": "多尿", "en": "Increased urination"},
    "vaginal_bleeding": {"ja": "膣出血", "en": "Vaginal bleeding"},
    "appetite_increase": {"ja": "食欲亢進", "en": "Increased appetite"},
    "thin_skin": {"ja": "皮膚の菲薄化", "en": "Thin skin"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "reduced_activity": {"ja": "活動性低下", "en": "Reduced activity"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "hind_limb_weakness": {"ja": "後肢の脱力", "en": "Hind limb weakness"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent urination"},
    "discomfort": {"ja": "不快感", "en": "Discomfort"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "loss_of_balance": {"ja": "平衡感覚喪失", "en": "Loss of balance"},
    "disorientation": {"ja": "見当識障害", "en": "Disorientation"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "seizures": {"ja": "痙攣発作", "en": "Seizures"},
    "tremors": {"ja": "震え", "en": "Tremors"},
    "unconsciousness": {"ja": "意識消失", "en": "Unconsciousness"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "vision_loss": {"ja": "視力喪失", "en": "Vision loss"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into objects"},
    "eye_bulging": {"ja": "眼球突出", "en": "Eye bulging"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "squinting": {"ja": "眼を細める", "en": "Squinting"},
    "scratching_ears": {"ja": "耳を掻く", "en": "Scratching ears"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear discharge"},
    "wasting": {"ja": "衰弱", "en": "Wasting"},
    "visible_parasites": {"ja": "寄生虫の目視", "en": "Visible parasites"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "limb_deformity": {"ja": "四肢変形", "en": "Limb deformity"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal discharge"},
    "mammary_swelling": {"ja": "乳腺腫脹", "en": "Mammary swelling"},
    "mammary_redness": {"ja": "乳腺発赤", "en": "Mammary redness"},
    "testicular_swelling": {"ja": "精巣腫大", "en": "Testicular swelling"},
    "asymmetric_testes": {"ja": "精巣の左右差", "en": "Asymmetric testes"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "unresponsiveness": {"ja": "無反応", "en": "Unresponsiveness"},
    "cold_body": {"ja": "体の冷え", "en": "Cold body"},
    "slow_breathing": {"ja": "呼吸緩徐", "en": "Slow breathing"},
    "sunken_eyes": {"ja": "眼の陥没", "en": "Sunken eyes"},
    "skin_tenting": {"ja": "皮膚テンティング", "en": "Skin tenting"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "bar_chewing": {"ja": "ケージ齧り", "en": "Bar chewing"},
    "excessive_grooming": {"ja": "過度のグルーミング", "en": "Excessive grooming"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "tail_injury": {"ja": "尾の損傷", "en": "Tail injury"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "licking_flank": {"ja": "脇腹を舐める", "en": "Licking flank area"},
    "dark_skin_lesion": {"ja": "暗色皮膚病変", "en": "Dark skin lesion"},
    "ear_crusting": {"ja": "耳の痂皮", "en": "Ear crusting"},
    "cold_intolerance": {"ja": "寒さに弱い", "en": "Cold intolerance"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
