"""Hamster disease dictionary and analysis module."""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic
from . import prevalence_data
from api.disease_loader import load_diseases

DISEASES: List[Dict[str, Any]] = [
    # ── 消化器系 ──
    {
        "name": "Wet Tail (Proliferative Ileitis)",
        "name_ja": "ウェットテイル（増殖性回腸炎）",
        "symptoms": {"wet_tail", "diarrhea", "lethargy", "appetite_loss", "dehydration", "hunched_posture"},
        "description": "Severe bacterial enteritis caused by Lawsonia intracellularis, most common in young hamsters.",
        "description_ja": "ローソニア菌による重度の細菌性腸炎で、若いハムスターに最も多い。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_exam", "bacterial_culture"],
    },
    {
        "name": "Tyzzer's Disease",
        "name_ja": "ティザー病",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "sudden_death", "dehydration"},
        "description": "Acute bacterial infection caused by Clostridium piliforme, often fatal.",
        "description_ja": "クロストリジウム・ピリフォルメによる急性細菌感染症で、致死率が高い。",
        "urgency": "emergency",
        "recommended_tests": ["necropsy", "histopathology"],
    },
    {
        "name": "Diarrhea (Non-specific)",
        "name_ja": "下痢（非特異的）",
        "symptoms": {"diarrhea", "dehydration", "appetite_loss", "weight_loss"},
        "description": "Loose stools from dietary changes, stress, or mild infections.",
        "description_ja": "食事変化、ストレス、軽度感染による軟便。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "dietary_review"],
    },
    {
        "name": "Constipation",
        "name_ja": "便秘",
        "symptoms": {"constipation", "abdominal_distension", "appetite_loss", "straining"},
        "description": "Difficulty passing stool due to dehydration, low fiber, or obstruction.",
        "description_ja": "脱水、低繊維食、閉塞による排便困難。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"rectal_prolapse", "straining", "diarrhea", "bloody_stool"},
        "description": "Protrusion of rectal tissue, often secondary to severe diarrhea.",
        "description_ja": "重度の下痢に続発する直腸組織の脱出。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Intussusception",
        "name_ja": "腸重積",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "bloody_stool"},
        "description": "Telescoping of intestinal segments, often following severe enteritis.",
        "description_ja": "重度の腸炎に続発する腸管の重積。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Gastrointestinal Parasites",
        "name_ja": "消化管寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "appetite_loss", "rough_coat"},
        "description": "Infection with pinworms, tapeworms, or other intestinal parasites.",
        "description_ja": "蟯虫、条虫などの腸内寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Tapeworm Infection (Hymenolepis)",
        "name_ja": "条虫症（膜様条虫）",
        "symptoms": {"weight_loss", "visible_worms_in_stool", "appetite_loss", "rough_coat", "perianal_irritation"},
        "description": "Infection by Hymenolepis species tapeworms, potentially zoonotic, causing weight loss and poor coat condition.",
        "description_ja": "膜様条虫（ヒメノレピス属）による感染症で、人獣共通感染の可能性があり、体重減少や被毛の悪化を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Pinworm Infection (Syphacia)",
        "name_ja": "蟯虫症",
        "symptoms": {"perianal_irritation", "visible_worms_in_stool", "rough_coat", "weight_loss"},
        "description": "Infection by Syphacia obvelata pinworms, usually subclinical but may cause perianal itching and restlessness.",
        "description_ja": "蟯虫（シファシア属）による感染症で、通常は無症状だが肛門周囲の掻痒を生じることがある。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "tape_test"],
    },
    {
        "name": "Clostridiosis",
        "name_ja": "クロストリジウム感染症",
        "symptoms": {"diarrhea", "abdominal_distension", "sudden_death", "appetite_loss"},
        "description": "Clostridium difficile or perfringens enterotoxemia, often antibiotic-related.",
        "description_ja": "クロストリジウム腸毒素血症で、抗生物質関連が多い。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_toxin_test", "bacterial_culture"],
    },
    {
        "name": "Coccidiosis",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "rough_coat", "bloody_stool"},
        "description": "Protozoal parasite infection of the intestines.",
        "description_ja": "腸の原虫寄生虫感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_smear"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物摂取",
        "symptoms": {"appetite_loss", "lethargy", "abdominal_distension"},
        "description": "Ingestion of bedding, plastic, or other non-food items causing obstruction.",
        "description_ja": "床材やプラスチックなどの誤食による閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    # ── 頬袋疾患 ──
    {
        "name": "Cheek Pouch Impaction",
        "name_ja": "頬袋閉塞",
        "symptoms": {"cheek_swelling", "appetite_loss", "drooling", "pawing_at_mouth"},
        "description": "Food or bedding material becomes lodged in the cheek pouch.",
        "description_ja": "食物や床材が頬袋に詰まった状態。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "physical_exam"],
    },
    {
        "name": "Cheek Pouch Prolapse",
        "name_ja": "頬袋脱",
        "symptoms": {"cheek_pouch_prolapse", "drooling", "appetite_loss", "oral_mass"},
        "description": "Eversion of the cheek pouch lining, visible as a pink mass near the mouth.",
        "description_ja": "頬袋の内壁が反転し、口の近くにピンク色の腫瘤として見える。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Cheek Pouch Abscess",
        "name_ja": "頬袋膿瘍",
        "symptoms": {"cheek_swelling", "facial_swelling", "appetite_loss", "discharge"},
        "description": "Bacterial infection of the cheek pouch causing pus accumulation.",
        "description_ja": "頬袋の細菌感染による膿の蓄積。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "cytology"],
    },
    # ── 歯科 ──
    {
        "name": "Dental Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "weight_loss", "appetite_loss", "overgrown_teeth", "pawing_at_mouth"},
        "description": "Misalignment of incisors preventing proper wearing, leading to overgrowth.",
        "description_ja": "切歯の不整合により適切な摩耗が妨げられ過成長する。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Dental Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "drooling", "weight_loss", "eye_discharge"},
        "description": "Root infection causing facial swelling, may extend to the eye orbit.",
        "description_ja": "歯根感染による顔面腫脹、眼窩に波及することがある。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "bacterial_culture"],
    },
    # ── 呼吸器系 ──
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"labored_breathing", "nasal_discharge", "sneezing", "lethargy", "appetite_loss"},
        "description": "Bacterial or viral lung infection, often secondary to stress.",
        "description_ja": "ストレスに続発する細菌性またはウイルス性の肺感染症。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bacterial_culture"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"sneezing", "nasal_discharge", "wheezing", "eye_discharge"},
        "description": "Infection of the upper airways causing sneezing and nasal discharge.",
        "description_ja": "上気道感染によるくしゃみや鼻水。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "bacterial_culture"],
    },
    {
        "name": "Sendai Virus Infection",
        "name_ja": "センダイウイルス感染症",
        "symptoms": {"sneezing", "nasal_discharge", "labored_breathing", "lethargy", "rough_coat"},
        "description": "Respiratory virus that can cause severe pneumonia.",
        "description_ja": "重度の肺炎を引き起こすことがある呼吸器ウイルス。",
        "urgency": "high",
        "recommended_tests": ["serology", "pcr_test"],
    },
    # ── 皮膚科 ──
    {
        "name": "Demodex Mange",
        "name_ja": "ニキビダニ症",
        "symptoms": {"hair_loss", "dry_skin", "itching", "skin_crusting"},
        "description": "Skin mite infestation by Demodex species causing patchy hair loss.",
        "description_ja": "ニキビダニの寄生による斑状の脱毛。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Sarcoptic Mange",
        "name_ja": "疥癬",
        "symptoms": {"severe_itching", "hair_loss", "skin_crusting", "skin_redness", "scratching"},
        "description": "Intensely pruritic skin mite infestation.",
        "description_ja": "強い痒みを伴う疥癬虫の寄生。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Notoedres Mange",
        "name_ja": "ノトエドレス症",
        "symptoms": {"severe_itching", "skin_crusting", "hair_loss", "ear_crusting"},
        "description": "Burrowing mite infestation causing intense itching, especially on ears.",
        "description_ja": "穿孔性ダニの寄生による強い痒みと痂皮形成、特に耳に多い。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"hair_loss", "skin_crusting", "circular_lesions", "dry_skin"},
        "description": "Fungal skin infection causing circular patches of hair loss.",
        "description_ja": "真菌感染による円形の脱毛斑。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "woods_lamp", "skin_scraping"],
    },
    {
        "name": "Skin Abscess",
        "name_ja": "皮膚膿瘍",
        "symptoms": {"skin_lump", "swelling", "discharge", "pain", "fever"},
        "description": "Localized bacterial infection from bite wounds.",
        "description_ja": "咬傷から生じる限局性の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "bacterial_culture"],
    },
    {
        "name": "Fight Wound Infection",
        "name_ja": "喧嘩傷感染",
        "symptoms": {"wound", "swelling", "discharge", "pain", "hair_loss"},
        "description": "Bite wounds from cage mates that become infected.",
        "description_ja": "同居個体からの咬傷の感染。",
        "urgency": "moderate",
        "recommended_tests": ["wound_culture", "physical_exam"],
    },
    {
        "name": "Alopecia (Non-parasitic)",
        "name_ja": "脱毛症（非寄生虫性）",
        "symptoms": {"hair_loss", "dry_skin", "rough_coat"},
        "description": "Hair loss from nutritional deficiency, hormonal issues, or barbering.",
        "description_ja": "栄養不足、ホルモン異常、毛引きによる脱毛。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "dietary_review", "hormone_panel"],
    },
    {
        "name": "Flea Infestation",
        "name_ja": "ノミ寄生",
        "symptoms": {"itching", "scratching", "hair_loss", "skin_redness", "visible_parasites"},
        "description": "External parasite infestation causing pruritus.",
        "description_ja": "外部寄生虫による掻痒。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    # ── 腫瘍 ──
    {
        "name": "Mammary Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"skin_lump", "mammary_mass", "weight_loss", "lethargy"},
        "description": "Common tumor in female hamsters, may be benign or malignant.",
        "description_ja": "メスのハムスターに多い腫瘍で、良性または悪性。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "radiography"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "lethargy", "appetite_loss", "enlarged_lymph_nodes", "skin_lump"},
        "description": "Malignant cancer of the lymphatic system.",
        "description_ja": "リンパ系の悪性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "complete_blood_count"],
    },
    {
        "name": "Skin Tumor (General)",
        "name_ja": "皮膚腫瘍",
        "symptoms": {"skin_lump", "skin_mass_growth", "ulceration"},
        "description": "Various skin tumors including melanoma, papilloma, and fibroma.",
        "description_ja": "メラノーマ、乳頭腫、線維腫などの各種皮膚腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "biopsy"],
    },
    {
        "name": "Adrenal Tumor",
        "name_ja": "副腎腫瘍",
        "symptoms": {"hair_loss", "increased_thirst", "increased_urination", "abdominal_distension", "lethargy"},
        "description": "Tumor of the adrenal gland causing hormonal imbalances.",
        "description_ja": "副腎の腫瘍によるホルモン異常。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "hormone_panel"],
    },
    {
        "name": "Uterine Tumor",
        "name_ja": "子宮腫瘍",
        "symptoms": {"vaginal_bleeding", "abdominal_distension", "weight_loss", "appetite_loss"},
        "description": "Neoplasia of the uterus in intact female hamsters.",
        "description_ja": "未避妊メスの子宮の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "biopsy"],
    },
    {
        "name": "Intestinal Tumor",
        "name_ja": "腸管腫瘍",
        "symptoms": {"weight_loss", "diarrhea", "bloody_stool", "appetite_loss", "abdominal_distension"},
        "description": "Tumors of the gastrointestinal tract.",
        "description_ja": "消化管の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "biopsy"],
    },
    {
        "name": "Scent Gland Tumor",
        "name_ja": "臭腺腫瘍",
        "symptoms": {"skin_lump", "skin_crusting", "ulceration", "licking_flank"},
        "description": "Neoplasia of the flank scent glands, common in male Syrian hamsters.",
        "description_ja": "脇腹の臭腺の腫瘍で、オスのゴールデンハムスターに多い。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "cytology"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ（悪性黒色腫）",
        "symptoms": {"dark_skin_lesion", "skin_lump", "skin_mass_growth"},
        "description": "Malignant pigmented skin tumor.",
        "description_ja": "悪性の色素性皮膚腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Testicular Tumor",
        "name_ja": "精巣腫瘍",
        "symptoms": {"testicular_swelling", "asymmetric_testes", "weight_loss"},
        "description": "Tumors of the testes in intact male hamsters.",
        "description_ja": "未去勢オスの精巣腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy"],
    },
    {
        "name": "Liver Tumor",
        "name_ja": "肝臓腫瘍",
        "symptoms": {"abdominal_distension", "weight_loss", "lethargy", "jaundice", "appetite_loss"},
        "description": "Primary or metastatic liver tumors.",
        "description_ja": "原発性または転移性の肝臓腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "blood_chemistry", "biopsy"],
    },
    # ── 内分泌・代謝 ──
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "appetite_increase", "lethargy"},
        "description": "Insulin resistance/deficiency, especially common in Campbell's dwarf hamsters.",
        "description_ja": "インスリン抵抗性/不足で、キャンベルハムスターに特に多い。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "urinalysis", "fructosamine"],
    },
    {
        "name": "Cushing's Disease",
        "name_ja": "クッシング病",
        "symptoms": {"hair_loss", "increased_thirst", "increased_urination", "abdominal_distension", "thin_skin"},
        "description": "Excess cortisol from adrenal or pituitary tumors.",
        "description_ja": "副腎または下垂体腫瘍による過剰コルチゾール産生。",
        "urgency": "high",
        "recommended_tests": ["hormone_panel", "ultrasound"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "reduced_activity", "labored_breathing"},
        "description": "Excess body weight from overfeeding and inadequate exercise.",
        "description_ja": "過食と運動不足による過体重。",
        "urgency": "low",
        "recommended_tests": ["weight_assessment", "dietary_review"],
    },
    {
        "name": "Anorexia (Non-specific)",
        "name_ja": "食欲不振（非特異的）",
        "symptoms": {"appetite_loss", "weight_loss", "lethargy", "dehydration"},
        "description": "Refusal to eat from pain, stress, dental issues, systemic illness, or environmental changes.",
        "description_ja": "疼痛、ストレス、歯科疾患、全身疾患、環境変化などによる採食拒否。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "oral_exam"],
    },
    {
        "name": "Amyloidosis",
        "name_ja": "アミロイドーシス",
        "symptoms": {"weight_loss", "lethargy", "increased_thirst", "edema", "appetite_loss"},
        "description": "Deposition of amyloid protein in organs, especially kidneys and liver.",
        "description_ja": "腎臓や肝臓へのアミロイドタンパク質の沈着。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "biopsy", "urinalysis"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"lethargy", "appetite_loss", "weight_loss", "jaundice", "abdominal_distension"},
        "description": "Fat accumulation in the liver from obesity or anorexia.",
        "description_ja": "肥満や食欲不振による肝臓への脂肪蓄積。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound"],
    },
    # ── 循環器系 ──
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"labored_breathing", "lethargy", "cyanosis", "edema", "reduced_activity"},
        "description": "Heart muscle disease, common in older hamsters.",
        "description_ja": "高齢ハムスターに多い心筋疾患。",
        "urgency": "high",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"labored_breathing", "lethargy", "edema", "cyanosis", "ascites", "coughing"},
        "description": "Heart failure leading to fluid accumulation.",
        "description_ja": "心不全による液体貯留。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Atrial Thrombosis",
        "name_ja": "心房血栓症",
        "symptoms": {"labored_breathing", "cyanosis", "sudden_death", "lethargy", "hind_limb_weakness"},
        "description": "Blood clot in the heart atrium, often with cardiomyopathy.",
        "description_ja": "心房内の血栓形成で、心筋症に関連することが多い。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography"],
    },
    # ── 泌尿器系 ──
    {
        "name": "Chronic Renal Failure",
        "name_ja": "慢性腎不全",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function in older hamsters.",
        "description_ja": "高齢ハムスターの腎機能の進行性低下。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    {
        "name": "Urolithiasis",
        "name_ja": "尿路結石症",
        "symptoms": {"blood_in_urine", "straining", "frequent_urination", "pain"},
        "description": "Mineral stone formation in the urinary bladder.",
        "description_ja": "膀胱内の結石形成。",
        "urgency": "high",
        "recommended_tests": ["radiography", "urinalysis", "ultrasound"],
    },
    {
        "name": "Cystitis",
        "name_ja": "膀胱炎",
        "symptoms": {"blood_in_urine", "frequent_urination", "straining", "discomfort"},
        "description": "Bacterial infection of the urinary bladder.",
        "description_ja": "膀胱の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "bacterial_culture"],
    },
    # ── 神経系 ──
    {
        "name": "Cage Paralysis",
        "name_ja": "ケージ麻痺",
        "symptoms": {"hind_limb_weakness", "paralysis", "muscle_wasting", "reduced_activity"},
        "description": "Hind limb paralysis from vitamin deficiency and lack of exercise.",
        "description_ja": "ビタミン欠乏と運動不足による後肢麻痺。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "dietary_review", "radiography"],
    },
    {
        "name": "Stroke",
        "name_ja": "脳卒中",
        "symptoms": {"head_tilt", "circling", "loss_of_balance", "paralysis", "disorientation"},
        "description": "Disruption of blood supply to the brain, more common in older hamsters.",
        "description_ja": "脳への血液供給の途絶で、高齢ハムスターに多い。",
        "urgency": "emergency",
        "recommended_tests": ["neurological_exam", "physical_exam"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "circling", "loss_of_balance", "nystagmus", "disorientation"},
        "description": "Inner ear or brain disorder affecting balance.",
        "description_ja": "内耳または脳の障害で平衡感覚に影響する。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "neurological_exam"],
    },
    {
        "name": "Epilepsy / Seizures",
        "name_ja": "てんかん／痙攣",
        "symptoms": {"seizures", "tremors", "disorientation", "loss_of_balance", "unconsciousness"},
        "description": "Involuntary convulsive episodes, may be genetic or metabolic.",
        "description_ja": "不随意の痙攣発作で、遺伝的または代謝性のことがある。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "neurological_exam"],
    },
    # ── 眼科 ──
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudy_eyes", "vision_loss", "bumping_into_objects"},
        "description": "Lens opacity, common in diabetic and elderly hamsters.",
        "description_ja": "水晶体の混濁で、糖尿病や高齢のハムスターに多い。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose"],
    },
    {
        "name": "Glaucoma",
        "name_ja": "緑内障",
        "symptoms": {"eye_bulging", "eye_redness", "pain", "cloudy_eyes", "vision_loss"},
        "description": "Increased intraocular pressure causing eye enlargement.",
        "description_ja": "眼圧上昇による眼球肥大。",
        "urgency": "high",
        "recommended_tests": ["tonometry", "ophthalmic_exam"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "eye_swelling", "squinting"},
        "description": "Inflammation of the conjunctiva from infection or irritation.",
        "description_ja": "感染や刺激による結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "bacterial_culture"],
    },
    {
        "name": "Eye Proptosis",
        "name_ja": "眼球突出",
        "symptoms": {"eye_bulging", "eye_redness", "pain"},
        "description": "Protrusion of the eyeball from retrobulbar abscess or trauma.",
        "description_ja": "眼窩後方の膿瘍や外傷による眼球の突出。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmic_exam", "skull_radiography"],
    },
    {
        "name": "Entropion",
        "name_ja": "眼瞼内反",
        "symptoms": {"squinting", "eye_discharge", "eye_redness"},
        "description": "Inward rolling of the eyelid causing corneal irritation.",
        "description_ja": "眼瞼が内側に巻き込み角膜を刺激する。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam"],
    },
    # ── 耳 ──
    {
        "name": "Otitis",
        "name_ja": "外耳炎・中耳炎",
        "symptoms": {"head_tilt", "scratching_ears", "ear_discharge", "pain", "loss_of_balance"},
        "description": "Bacterial infection of the ear canal or middle ear.",
        "description_ja": "外耳道または中耳の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "bacterial_culture"],
    },
    # ── 感染症 ──
    {
        "name": "Hamster Polyomavirus",
        "name_ja": "ハムスターポリオーマウイルス",
        "symptoms": {"skin_lump", "hair_loss", "wasting", "lethargy"},
        "description": "Viral infection causing skin tumors and lymphoma.",
        "description_ja": "皮膚腫瘍やリンパ腫を引き起こすウイルス感染。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Lymphocytic Choriomeningitis (LCMV)",
        "name_ja": "リンパ球性脈絡髄膜炎",
        "symptoms": {"lethargy", "weight_loss", "tremors", "seizures", "hunched_posture"},
        "description": "Zoonotic viral infection; hamsters may be asymptomatic carriers.",
        "description_ja": "人獣共通のウイルス感染症で、無症候性キャリアになることがある。",
        "urgency": "high",
        "recommended_tests": ["serology", "pcr_test"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "dehydration", "sudden_death"},
        "description": "Bacterial infection with zoonotic potential.",
        "description_ja": "人獣共通のサルモネラ菌感染。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "complete_blood_count"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "appetite_loss", "labored_breathing", "sudden_death"},
        "description": "Systemic bacterial infection spreading through the bloodstream.",
        "description_ja": "血流を介した全身性細菌感染。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count"],
    },
    # ── 運動器系 ──
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"lameness", "pain", "swelling", "limb_deformity", "reduced_activity"},
        "description": "Broken bones from falls, wheel injuries, or cage bar accidents.",
        "description_ja": "落下、回し車事故、ケージの隙間による骨折。",
        "urgency": "high",
        "recommended_tests": ["radiography"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "reduced_activity", "stiffness", "pain"},
        "description": "Degenerative joint disease in older hamsters.",
        "description_ja": "高齢ハムスターの変性性関節疾患。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    # ── 生殖器系 ──
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "abdominal_distension", "lethargy", "appetite_loss", "increased_thirst"},
        "description": "Bacterial infection of the uterus with pus accumulation.",
        "description_ja": "子宮の細菌感染による膿の蓄積。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "radiography", "complete_blood_count"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "vaginal_bleeding", "lethargy", "abdominal_distension"},
        "description": "Difficulty giving birth.",
        "description_ja": "分娩困難。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "mammary_redness", "fever", "appetite_loss", "lethargy"},
        "description": "Bacterial infection of the mammary glands in nursing females.",
        "description_ja": "授乳中のメスの乳腺感染。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "bacterial_culture"],
    },
    # ── 環境・栄養 ──
    {
        "name": "Heatstroke",
        "name_ja": "熱中症",
        "symptoms": {"labored_breathing", "lethargy", "weakness", "drooling", "unconsciousness"},
        "description": "Hyperthermia from high ambient temperature; hamsters are very heat-sensitive.",
        "description_ja": "高温環境による高体温症で、ハムスターは熱に非常に弱い。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "physical_exam"],
    },
    {
        "name": "Hibernation / Torpor",
        "name_ja": "擬似冬眠",
        "symptoms": {"unresponsiveness", "cold_body", "slow_breathing", "stiffness"},
        "description": "State of torpor triggered by cold temperatures; can be mistaken for death.",
        "description_ja": "低温により誘発される仮死状態。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "physical_exam"],
    },
    {
        "name": "Vitamin Deficiency",
        "name_ja": "ビタミン欠乏症",
        "symptoms": {"hair_loss", "rough_coat", "lethargy", "weight_loss", "muscle_wasting"},
        "description": "Deficiency of vitamins D, E, or B complex.",
        "description_ja": "ビタミンD、E、B群の欠乏。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_review", "blood_chemistry"],
    },
    {
        "name": "Antibiotic Toxicity",
        "name_ja": "抗生物質中毒",
        "symptoms": {"diarrhea", "appetite_loss", "lethargy", "dehydration", "sudden_death"},
        "description": "Fatal dysbiosis from antibiotics toxic to hamsters (penicillin, erythromycin, lincomycin).",
        "description_ja": "ハムスターに有害な抗生物質による致死的菌交代現象。",
        "urgency": "emergency",
        "recommended_tests": ["medication_review", "fecal_exam"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"dehydration", "lethargy", "dry_skin", "sunken_eyes", "skin_tenting"},
        "description": "Insufficient fluid intake or excess fluid loss.",
        "description_ja": "水分摂取不足または過剰な水分喪失。",
        "urgency": "high",
        "recommended_tests": ["skin_turgor_test", "physical_exam"],
    },
    # ── 行動 ──
    {
        "name": "Stress-Related Behaviors",
        "name_ja": "ストレス関連行動",
        "symptoms": {"bar_chewing", "excessive_grooming", "aggression", "reduced_activity"},
        "description": "Stereotypic behaviors from inadequate cage size or enrichment.",
        "description_ja": "不適切なケージサイズやエンリッチメント不足による常同行動。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review"],
    },
    {
        "name": "Barbering",
        "name_ja": "毛引き",
        "symptoms": {"hair_loss", "skin_redness", "excessive_grooming"},
        "description": "Excessive fur chewing by self or cage mate.",
        "description_ja": "自己または同居個体による過度の毛噛み。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "skin_scraping"],
    },
    # ── その他 ──
    {
        "name": "Scent Gland Inflammation",
        "name_ja": "臭腺炎",
        "symptoms": {"skin_crusting", "swelling", "discharge", "licking_flank"},
        "description": "Infection or inflammation of the flank scent glands.",
        "description_ja": "脇腹の臭腺の感染または炎症。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "physical_exam"],
    },
    {
        "name": "Polycystic Disease",
        "name_ja": "多嚢胞性疾患",
        "symptoms": {"abdominal_distension", "weight_loss", "lethargy"},
        "description": "Cyst formation in liver, kidneys, or other organs.",
        "description_ja": "肝臓、腎臓などの臓器の嚢胞形成。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "blood_chemistry"],
    },
    {
        "name": "Hypothyroidism",
        "name_ja": "甲状腺機能低下症",
        "symptoms": {"weight_gain", "lethargy", "hair_loss", "dry_skin", "cold_intolerance"},
        "description": "Underactive thyroid gland causing metabolic slowdown.",
        "description_ja": "甲状腺機能低下による代謝の低下。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "blood_chemistry"],
    },
    {
        "name": "Splenomegaly",
        "name_ja": "脾腫",
        "symptoms": {"abdominal_distension", "lethargy", "weight_loss"},
        "description": "Enlarged spleen from infection, lymphoma, or amyloidosis.",
        "description_ja": "感染、リンパ腫、アミロイドーシスによる脾臓腫大。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "complete_blood_count", "cytology"],
    },
    {
        "name": "Nasal Tumor",
        "name_ja": "鼻腔腫瘍",
        "symptoms": {"nasal_discharge", "sneezing", "facial_swelling", "labored_breathing"},
        "description": "Tumors within the nasal cavity.",
        "description_ja": "鼻腔内の腫瘍。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "biopsy"],
    },
    {
        "name": "Tail Slip (Degloving)",
        "name_ja": "テイルスリップ",
        "symptoms": {"tail_injury", "bleeding", "pain"},
        "description": "Loss of tail skin from improper handling.",
        "description_ja": "不適切な取り扱いによる尾の皮膚喪失。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Proliferative Colitis",
        "name_ja": "増殖性大腸炎",
        "symptoms": {"diarrhea", "weight_loss", "rectal_prolapse", "bloody_stool"},
        "description": "Thickening of the colon wall causing chronic diarrhea.",
        "description_ja": "結腸壁の肥厚による慢性下痢。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "histopathology"],
    },
    {
        "name": "Pneumocystis Pneumonia",
        "name_ja": "ニューモシスチス肺炎",
        "symptoms": {"labored_breathing", "weight_loss", "lethargy", "coughing"},
        "description": "Opportunistic fungal lung infection in immunocompromised hamsters.",
        "description_ja": "免疫不全ハムスターの日和見真菌性肺感染。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bronchoalveolar_lavage"],
    },
    {
        "name": "Cheek Pouch Eversion",
        "name_ja": "頬袋反転",
        "symptoms": {"appetite_loss", "drooling", "pawing_at_mouth", "visible_tissue_from_mouth"},
        "description": "Complete eversion (turning inside out) of the cheek pouch, often caused by sticky foods or excessive grooming. Requires manual reduction or surgical intervention.",
        "description_ja": "頬袋が完全に反転する状態で、粘着性の食べ物や過度のグルーミングが原因となります。用手整復または外科的介入が必要です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "oral_exam"],
    },
    {
        "name": "Cheek Pouch Tumor",
        "name_ja": "頬袋腫瘍",
        "symptoms": {"appetite_loss", "drooling", "facial_swelling", "visible_mass_in_mouth", "weight_loss"},
        "description": "Neoplastic growth within the cheek pouch, including squamous cell carcinoma and papilloma. May cause difficulty eating.",
        "description_ja": "頬袋内の腫瘍性増殖で、扁平上皮癌やパピローマを含みます。摂食困難を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "fine_needle_aspirate", "biopsy"],
    },
    {
        "name": "Cheek Pouch Mycosis",
        "name_ja": "頬袋真菌症",
        "symptoms": {"appetite_loss", "drooling", "facial_swelling", "foul_odor_from_mouth"},
        "description": "Fungal infection of the cheek pouch lining, often from stored food becoming mouldy within the pouch.",
        "description_ja": "頬袋内膜の真菌感染で、頬袋内に貯蔵された食物がカビることが原因となります。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "culture", "cytology"],
    },
    {
        "name": "Hibernation Syndrome",
        "name_ja": "冬眠症候群",
        "symptoms": {"cold_body", "curled_posture", "lethargy", "slow_breathing", "unresponsiveness"},
        "description": "Pseudo-hibernation triggered by cold temperatures (<15°C), short daylight, or inadequate nutrition. Can be fatal if not reversed promptly.",
        "description_ja": "低温（15°C以下）、短い日照時間、栄養不足により引き起こされる擬似冬眠。速やかに回復させなければ致死的になり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "blood_glucose", "physical_exam"],
    },
    {
        "name": "Proliferative Ileitis (Chronic Form)",
        "name_ja": "増殖性回腸炎（慢性型）",
        "symptoms": {"intermittent_diarrhea", "lethargy", "poor_coat", "recurrent_soft_stool", "weight_loss"},
        "description": "Chronic form of Lawsonia intracellularis infection with recurring bouts of diarrhea and progressive weight loss.",
        "description_ja": "ローソニア・イントラセルラリス感染の慢性型で、下痢の再発と進行性体重減少を伴います。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_pcr", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Campylobacteriosis",
        "name_ja": "カンピロバクター症",
        "symptoms": {"abdominal_pain", "appetite_loss", "dehydration", "diarrhea", "lethargy"},
        "description": "Bacterial enteritis caused by Campylobacter species, causing watery to bloody diarrhea. Zoonotic potential.",
        "description_ja": "カンピロバクター属による細菌性腸炎で、水様から血液混じりの下痢を引き起こします。人獣共通感染症の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Helicobacter Gastritis",
        "name_ja": "ヘリコバクター胃炎",
        "symptoms": {"abdominal_pain", "appetite_loss", "lethargy", "vomiting", "weight_loss"},
        "description": "Chronic gastritis associated with Helicobacter species infection, which may contribute to gastric ulceration and lymphoma.",
        "description_ja": "ヘリコバクター属感染に関連する慢性胃炎で、胃潰瘍やリンパ腫に寄与する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["gastric_biopsy", "pcr_testing", "blood_chemistry"],
    },
    {
        "name": "Clostridium difficile Enteritis",
        "name_ja": "クロストリジウム・ディフィシル腸炎",
        "symptoms": {"abdominal_distension", "appetite_loss", "dehydration", "diarrhea", "lethargy"},
        "description": "Toxin-mediated enteritis following antibiotic disruption of normal gut flora. Can be rapidly fatal.",
        "description_ja": "抗生物質による正常腸内細菌叢の撹乱に続く毒素介在性腸炎。急速に致死的になり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_toxin_assay", "fecal_culture", "physical_exam"],
    },
    {
        "name": "Intestinal Torsion",
        "name_ja": "腸捻転",
        "symptoms": {"abdominal_distension", "abdominal_pain", "lethargy", "shock", "sudden_death"},
        "description": "Rotation of intestinal loops on their mesenteric axis causing vascular compromise and rapid necrosis.",
        "description_ja": "腸管ループが腸間膜軸を中心に回転し、血管障害と急速な壊死を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "physical_exam", "emergency_surgery"],
    },
    {
        "name": "Intestinal Impaction",
        "name_ja": "腸閉塞（糞便嵌頓）",
        "symptoms": {"abdominal_distension", "abdominal_pain", "appetite_loss", "lethargy", "reduced_fecal_output"},
        "description": "Blockage of the intestine with dried faecal material or bedding, often from dehydration or inappropriate substrate.",
        "description_ja": "脱水や不適切な床材による乾燥した糞便物質や床材での腸閉塞です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "physical_exam", "abdominal_palpation"],
    },
    {
        "name": "Hepatic Tumor",
        "name_ja": "肝臓腫瘍",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Primary hepatic neoplasia or metastatic disease affecting the liver, relatively common in aged hamsters.",
        "description_ja": "肝臓原発の腫瘍または転移性疾患で、高齢ハムスターに比較的よく見られます。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "blood_chemistry", "fine_needle_aspirate"],
    },
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"bleeding_from_mass", "skin_masses", "ulceration", "weight_loss"},
        "description": "Malignant epithelial tumour that can arise on the skin, in the oral cavity, or cheek pouches of hamsters.",
        "description_ja": "皮膚、口腔、頬袋に発生する悪性上皮腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"lethargy", "rapid_growth", "skin_masses", "weight_loss"},
        "description": "Malignant connective tissue tumour arising from fibroblasts, one of the more common soft tissue sarcomas in hamsters.",
        "description_ja": "線維芽細胞から発生する悪性結合組織腫瘍で、ハムスターでより一般的な軟部組織肉腫の一つです。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Papilloma",
        "name_ja": "パピローマ（乳頭腫）",
        "symptoms": {"skin_masses", "skin_thickening", "wart_like_growths"},
        "description": "Benign epithelial tumour caused by papillomavirus, appearing as raised wart-like growths on the skin.",
        "description_ja": "パピローマウイルスによる良性上皮腫瘍で、皮膚上に隆起した疣贅様の増殖として現れます。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "biopsy", "histopathology"],
    },
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"slow_growing_lump", "subcutaneous_mass"},
        "description": "Benign fatty tumour commonly found subcutaneously. Usually non-problematic unless restricting movement.",
        "description_ja": "皮下に一般的に見られる良性脂肪腫瘍。運動を妨げない限り通常問題ありません。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "physical_exam"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "lethargy", "limb_swelling", "pain", "weight_loss"},
        "description": "Malignant bone tumour with high metastatic potential. Can affect any bone but most common in long bones.",
        "description_ja": "高い転移能を持つ悪性骨腫瘍。どの骨にも発生し得ますが、長管骨に最も多いです。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "chest_xray", "biopsy"],
    },
    {
        "name": "Pituitary Tumor",
        "name_ja": "下垂体腫瘍",
        "symptoms": {"circling", "head_tilt", "lethargy", "seizures", "vision_loss", "weight_loss"},
        "description": "Neoplasia of the pituitary gland causing neurological signs and potential hormonal imbalances.",
        "description_ja": "下垂体の腫瘍で、神経学的徴候やホルモン不均衡を引き起こす可能性があります。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "mri", "hormone_panel"],
    },
    {
        "name": "Ovarian Cysts",
        "name_ja": "卵巣嚢胞",
        "symptoms": {"abdominal_distension", "aggressive_behavior", "hair_loss", "vaginal_discharge"},
        "description": "Fluid-filled cysts on the ovaries causing hormonal disturbances, abdominal enlargement, and bilateral hair loss.",
        "description_ja": "卵巣上の液体で満たされた嚢胞で、ホルモン障害、腹部膨張、両側性脱毛を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "physical_exam", "hormone_panel"],
    },
    {
        "name": "Pregnancy Toxemia",
        "name_ja": "妊娠中毒症",
        "symptoms": {"appetite_loss", "lethargy", "rapid_breathing", "seizures", "weakness"},
        "description": "Metabolic disorder in late-pregnant or lactating hamsters caused by negative energy balance, leading to hepatic lipidosis and ketosis.",
        "description_ja": "妊娠後期または授乳中のハムスターの負のエネルギーバランスによる代謝障害で、肝リピドーシスとケトーシスを引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Neonatal Cannibalism",
        "name_ja": "新生児食殺",
        "symptoms": {"blood_stains_in_nest", "maternal_stress", "missing_pups"},
        "description": "Consumption of newborn pups by the mother, triggered by stress, disturbance, inadequate nutrition, or first-time mothering.",
        "description_ja": "ストレス、妨害、栄養不足、初産による母親による新生児の食殺です。",
        "urgency": "moderate",
        "recommended_tests": ["environmental_review", "nutritional_assessment", "stress_evaluation"],
    },
    {
        "name": "Retained Fetus",
        "name_ja": "胎児残留",
        "symptoms": {"abdominal_distension", "appetite_loss", "fever", "lethargy", "vaginal_discharge"},
        "description": "Failure to deliver all foetuses during birth, leading to infection, toxaemia, and potentially death if not treated.",
        "description_ja": "分娩時にすべての胎児を排出できない状態で、感染、毒血症、未治療では死に至る可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Uterine Prolapse",
        "name_ja": "子宮脱",
        "symptoms": {"bleeding", "lethargy", "straining", "tissue_protrusion_from_vulva"},
        "description": "Protrusion of the uterus through the vulva, usually occurring during or shortly after parturition.",
        "description_ja": "子宮が外陰部を通じて突出する状態で、通常分娩中または分娩直後に発生します。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry"],
    },
    {
        "name": "Cryptorchidism",
        "name_ja": "停留精巣",
        "symptoms": {"absent_testicle", "behavioral_changes", "inguinal_swelling"},
        "description": "Failure of one or both testes to descend into the scrotum. Retained testes have increased risk of neoplasia.",
        "description_ja": "片方または両方の精巣が陰嚢に下降しない状態。停留精巣は腫瘍のリスクが増加します。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "abdominal_ultrasound"],
    },
    {
        "name": "Diabetic Ketoacidosis",
        "name_ja": "糖尿病性ケトアシドーシス",
        "symptoms": {"appetite_loss", "dehydration", "lethargy", "rapid_breathing", "sweet_breath_odor", "weakness"},
        "description": "Severe complication of uncontrolled diabetes mellitus with accumulation of ketone bodies causing metabolic acidosis.",
        "description_ja": "制御不能な糖尿病の重篤な合併症で、ケトン体の蓄積により代謝性アシドーシスを引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Diabetic Cataracts",
        "name_ja": "糖尿病性白内障",
        "symptoms": {"bumping_into_objects", "cloudy_eyes", "vision_loss"},
        "description": "Rapid onset cataracts secondary to diabetes mellitus due to osmotic changes in the lens from glucose accumulation.",
        "description_ja": "糖尿病に続発する急速な白内障で、グルコース蓄積による水晶体の浸透圧変化が原因です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "blood_glucose", "physical_exam"],
    },
    {
        "name": "Diabetic Nephropathy",
        "name_ja": "糖尿病性腎症",
        "symptoms": {"lethargy", "polydipsia", "polyuria", "poor_coat", "weight_loss"},
        "description": "Progressive kidney damage resulting from long-standing diabetes mellitus, leading to chronic renal failure.",
        "description_ja": "長期にわたる糖尿病による進行性の腎障害で、慢性腎不全に至ります。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_ultrasound"],
    },
    {
        "name": "Insulin Resistance",
        "name_ja": "インスリン抵抗性",
        "symptoms": {"lethargy", "obesity", "polydipsia", "polyuria", "poor_coat"},
        "description": "Reduced cellular response to insulin, often precursor to overt diabetes, particularly common in Chinese hamsters.",
        "description_ja": "インスリンに対する細胞応答の低下で、顕性糖尿病の前段階であることが多く、チャイニーズハムスターに特に多いです。",
        "urgency": "moderate",
        "recommended_tests": ["blood_glucose", "insulin_level", "physical_exam"],
    },
    {
        "name": "Hypoglycemia",
        "name_ja": "低血糖症",
        "symptoms": {"lethargy", "seizures", "tremors", "unresponsiveness", "weakness"},
        "description": "Dangerously low blood sugar levels causing neurological signs, from starvation, insulin overdose, or insulinoma.",
        "description_ja": "飢餓、インスリン過剰投与、インスリノーマによる危険な低血糖で、神経症状を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Hyperadrenocorticism (Cushing's Syndrome)",
        "name_ja": "副腎皮質機能亢進症（クッシング症候群）",
        "symptoms": {"abdominal_distension", "hair_loss", "polydipsia", "polyuria", "skin_thinning"},
        "description": "Excess cortisol production from adrenal gland or pituitary tumour causing metabolic and dermatological changes.",
        "description_ja": "副腎腺腫または下垂体腫瘍からの過剰コルチゾール産生で、代謝および皮膚科的変化を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Thyroid Carcinoma",
        "name_ja": "甲状腺癌",
        "symptoms": {"cervical_mass", "difficulty_swallowing", "respiratory_distress", "weight_loss"},
        "description": "Malignant tumour of the thyroid gland, which may be functional or non-functional, causing local compression.",
        "description_ja": "甲状腺の悪性腫瘍で、機能性または非機能性で、局所圧迫を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["cervical_ultrasound", "fine_needle_aspirate", "thyroid_panel"],
    },
    {
        "name": "Iron Storage Disease (Hemochromatosis)",
        "name_ja": "鉄蓄積症（ヘモクロマトーシス）",
        "symptoms": {"abdominal_distension", "jaundice", "lethargy", "weight_loss"},
        "description": "Pathological accumulation of iron in organs, particularly the liver, leading to organ damage and failure.",
        "description_ja": "臓器、特に肝臓への病的な鉄蓄積で、臓器障害と機能不全を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "liver_biopsy", "serum_iron"],
    },
    {
        "name": "Hypervitaminosis A",
        "name_ja": "ビタミンA過剰症",
        "symptoms": {"bone_pain", "hair_loss", "lethargy", "skin_lesions", "weight_loss"},
        "description": "Toxic accumulation of vitamin A from excessive supplementation causing dermatological and skeletal abnormalities.",
        "description_ja": "過剰な補給によるビタミンAの中毒性蓄積で、皮膚科的および骨格異常を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "xray", "diet_review"],
    },
    {
        "name": "Vitamin E Deficiency",
        "name_ja": "ビタミンE欠乏症",
        "symptoms": {"infertility", "lethargy", "muscle_weakness", "poor_coat", "weight_loss"},
        "description": "Nutritional deficiency causing muscular dystrophy, reproductive failure, and oxidative tissue damage.",
        "description_ja": "筋ジストロフィー、繁殖障害、酸化的組織損傷を引き起こす栄養欠乏症です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "diet_review", "muscle_biopsy"],
    },
    {
        "name": "Pneumothorax",
        "name_ja": "気胸",
        "symptoms": {"cyanosis", "lethargy", "open_mouth_breathing", "rapid_breathing", "respiratory_distress"},
        "description": "Accumulation of air in the pleural space causing lung collapse, often from trauma or spontaneous rupture.",
        "description_ja": "胸腔内の空気蓄積による肺虚脱で、外傷または自然破裂が原因となります。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "physical_exam", "thoracocentesis"],
    },
    {
        "name": "Mycoplasma Infection",
        "name_ja": "マイコプラズマ感染症",
        "symptoms": {"conjunctivitis", "lethargy", "nasal_discharge", "respiratory_distress", "sneezing"},
        "description": "Respiratory infection by Mycoplasma pulmonis or related species, causing chronic rhinitis and pneumonia.",
        "description_ja": "マイコプラズマ・プルモニスまたは関連種による呼吸器感染で、慢性鼻炎と肺炎を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_testing", "chest_xray", "culture"],
    },
    {
        "name": "Pasteurellosis",
        "name_ja": "パスツレラ症",
        "symptoms": {"abscesses", "lethargy", "nasal_discharge", "respiratory_distress", "sneezing"},
        "description": "Bacterial infection by Pasteurella species causing respiratory disease, abscesses, and septicaemia.",
        "description_ja": "パスツレラ属による細菌感染で、呼吸器疾患、膿瘍、敗血症を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Streptococcal Infection",
        "name_ja": "レンサ球菌感染症",
        "symptoms": {"cervical_abscess", "fever", "lethargy", "nasal_discharge", "skin_lesions"},
        "description": "Infection by Streptococcus species causing cervical lymphadenitis (lumpy jaw), pneumonia, or septicaemia.",
        "description_ja": "レンサ球菌属による感染で、頸部リンパ節炎、肺炎、敗血症を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "blood_chemistry", "fine_needle_aspirate"],
    },
    {
        "name": "Staphylococcal Dermatitis",
        "name_ja": "ブドウ球菌性皮膚炎",
        "symptoms": {"abscess_formation", "hair_loss", "pruritus", "skin_crusting", "skin_lesions"},
        "description": "Skin infection by Staphylococcus aureus causing pyoderma, abscesses, and ulcerative dermatitis.",
        "description_ja": "黄色ブドウ球菌による皮膚感染で、膿皮症、膿瘍、潰瘍性皮膚炎を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "cytology", "physical_exam"],
    },
    {
        "name": "Pseudomonas Infection",
        "name_ja": "緑膿菌感染症",
        "symptoms": {"fever", "green_discharge", "lethargy", "otitis", "skin_lesions"},
        "description": "Opportunistic bacterial infection often associated with contaminated water bottles or moist environments.",
        "description_ja": "汚染された給水ボトルや湿った環境に関連することが多い日和見細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Dermatitis (Contact)",
        "name_ja": "接触性皮膚炎",
        "symptoms": {"foot_sores", "hair_loss", "pruritus", "skin_lesions", "skin_redness"},
        "description": "Inflammatory skin reaction from contact with irritant bedding materials (cedar, pine shavings) or cleaning chemicals.",
        "description_ja": "刺激性の床材（杉、松の削り屑）や洗浄剤との接触による炎症性皮膚反応です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "skin_scraping", "environmental_review"],
    },
    {
        "name": "Pododermatitis (Bumblefoot)",
        "name_ja": "趾瘤症（バンブルフット）",
        "symptoms": {"foot_sores", "foot_swelling", "lameness", "pain", "reluctance_to_move"},
        "description": "Inflammation and infection of the footpads from wire flooring, obesity, or rough substrate. Can progress to osteomyelitis.",
        "description_ja": "金網床、肥満、粗い床材による足裏の炎症と感染。骨髄炎に進行することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "foot_xray", "culture"],
    },
    {
        "name": "Fur Slip",
        "name_ja": "毛抜け（ファースリップ）",
        "symptoms": {"bald_patches", "hair_loss", "skin_exposure"},
        "description": "Release of patches of fur as a stress response or defence mechanism when handled roughly or frightened.",
        "description_ja": "乱暴に扱われたり驚いたりした際のストレス反応または防衛機構として毛が抜ける現象です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "stress_evaluation"],
    },
    {
        "name": "Dermal Melanocytoma",
        "name_ja": "皮膚メラノサイトーマ",
        "symptoms": {"pigmented_skin_mass", "skin_masses", "slow_growing_lump"},
        "description": "Benign melanocytic tumour of the skin, appearing as a darkly pigmented raised nodule.",
        "description_ja": "皮膚の良性メラノサイト腫瘍で、暗い色素沈着した隆起性結節として現れます。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "physical_exam"],
    },
    {
        "name": "Mast Cell Tumor",
        "name_ja": "肥満細胞腫",
        "symptoms": {"pruritus", "skin_masses", "skin_redness", "ulceration"},
        "description": "Neoplasia of mast cells in the skin, which may release histamine causing local inflammation and systemic effects.",
        "description_ja": "皮膚の肥満細胞の腫瘍で、ヒスタミンを放出し局所炎症と全身性影響を引き起こすことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "histopathology"],
    },
    {
        "name": "Basal Cell Tumor",
        "name_ja": "基底細胞腫",
        "symptoms": {"skin_masses", "slow_growing_lump", "ulceration"},
        "description": "Common benign skin tumour in hamsters arising from basal cells of the epidermis.",
        "description_ja": "表皮の基底細胞から発生するハムスターに一般的な良性皮膚腫瘍です。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "physical_exam"],
    },
    {
        "name": "Trichoepithelioma",
        "name_ja": "毛包上皮腫",
        "symptoms": {"hair_loss_around_mass", "skin_masses", "slow_growing_lump"},
        "description": "Benign tumour derived from hair follicle epithelium, common in older hamsters.",
        "description_ja": "毛包上皮由来の良性腫瘍で、高齢ハムスターに一般的です。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "histopathology", "physical_exam"],
    },
    {
        "name": "Keratoconjunctivitis",
        "name_ja": "角結膜炎",
        "symptoms": {"corneal_opacity", "eye_discharge", "eye_redness", "photophobia", "squinting"},
        "description": "Combined inflammation of the cornea and conjunctiva, often from bedding dust, infection, or desiccation.",
        "description_ja": "角膜と結膜の複合炎症で、床材の粉塵、感染、乾燥が原因となります。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "culture"],
    },
    {
        "name": "Retrobulbar Abscess",
        "name_ja": "後眼窩膿瘍",
        "symptoms": {"appetite_loss", "exophthalmos", "eye_discharge", "facial_swelling"},
        "description": "Abscess behind the eyeball, often secondary to dental disease, causing protrusion of the globe.",
        "description_ja": "眼球後方の膿瘍で、歯科疾患に続発することが多く、眼球突出を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "orbital_ultrasound", "dental_exam"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"corneal_opacity", "eye_discharge", "eye_redness", "pawing_at_eye", "squinting"},
        "description": "Erosion or ulceration of the corneal surface from trauma, bedding irritation, or infection.",
        "description_ja": "外傷、床材刺激、感染による角膜表面の糜爛または潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam", "culture"],
    },
    {
        "name": "Harderian Gland Tumor",
        "name_ja": "ハーダー腺腫瘍",
        "symptoms": {"exophthalmos", "eye_discharge", "facial_swelling", "red_discharge_around_eye"},
        "description": "Neoplasia of the Harderian gland (retrobulbar lacrimal gland) causing progressive exophthalmos.",
        "description_ja": "ハーダー腺（後眼窩涙腺）の腫瘍で、進行性の眼球突出を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["orbital_ultrasound", "fine_needle_aspirate", "ct_scan"],
    },
    {
        "name": "Chromodacryorrhea (Red Tears)",
        "name_ja": "赤色涙液症（赤い涙）",
        "symptoms": {"red_discharge_around_eye", "red_nasal_discharge", "stress_signs"},
        "description": "Porphyrin-stained secretion from the Harderian gland giving the appearance of bloody tears. Indicator of stress or illness.",
        "description_ja": "ハーダー腺からのポルフィリン染色分泌物で、血の涙のように見えます。ストレスや病気の指標です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "stress_evaluation", "blood_chemistry"],
    },
    {
        "name": "Urethral Obstruction",
        "name_ja": "尿道閉塞",
        "symptoms": {"abdominal_pain", "blood_in_urine", "lethargy", "straining_to_urinate", "vocalization"},
        "description": "Blockage of the urethra by calculi or protein plugs preventing urination. Life-threatening if complete obstruction.",
        "description_ja": "結石やタンパク栓による尿道の閉塞で排尿不能。完全閉塞は生命を脅かします。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "abdominal_xray", "urinalysis"],
    },
    {
        "name": "Nephrolithiasis",
        "name_ja": "腎結石症",
        "symptoms": {"appetite_loss", "blood_in_urine", "lethargy", "polydipsia", "polyuria"},
        "description": "Formation of calculi within the kidneys, which may cause obstruction, infection, and progressive renal damage.",
        "description_ja": "腎臓内の結石形成で、閉塞、感染、進行性腎障害を引き起こす可能性があります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "renal_ultrasound", "urinalysis"],
    },
    {
        "name": "Renal Amyloidosis",
        "name_ja": "腎アミロイドーシス",
        "symptoms": {"edema", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Deposition of amyloid protein in the kidneys causing progressive renal failure, common in aged Syrian hamsters.",
        "description_ja": "腎臓へのアミロイドタンパク沈着で進行性腎不全を引き起こし、高齢シリアンハムスターに一般的です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_biopsy"],
    },
    {
        "name": "Hepatic Amyloidosis",
        "name_ja": "肝アミロイドーシス",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Amyloid deposition in the liver causing hepatomegaly and progressive liver failure.",
        "description_ja": "肝臓へのアミロイド沈着で肝腫大と進行性肝不全を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_ultrasound", "liver_biopsy"],
    },
    {
        "name": "Cardiac Amyloidosis",
        "name_ja": "心アミロイドーシス",
        "symptoms": {"edema", "exercise_intolerance", "lethargy", "respiratory_distress", "sudden_death"},
        "description": "Amyloid deposition in the heart causing restrictive cardiomyopathy and congestive heart failure.",
        "description_ja": "心臓へのアミロイド沈着で拘束型心筋症とうっ血性心不全を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Vertebral Fracture",
        "name_ja": "椎骨骨折",
        "symptoms": {"fecal_incontinence", "hind_limb_paralysis", "pain", "urinary_incontinence"},
        "description": "Fracture of vertebral bones from falls or rough handling, causing spinal cord damage and paralysis.",
        "description_ja": "落下や乱暴な取り扱いによる椎骨の骨折で、脊髄損傷と麻痺を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["spinal_xray", "neurological_exam", "physical_exam"],
    },
    {
        "name": "Digit Fracture",
        "name_ja": "指骨骨折",
        "symptoms": {"bleeding_from_foot", "lameness", "pain", "toe_swelling"},
        "description": "Fracture of toe bones, often from catching feet in cage wire or exercise wheel spokes.",
        "description_ja": "ケージのワイヤーや回し車のスポークに足が挟まることによる指骨の骨折です。",
        "urgency": "moderate",
        "recommended_tests": ["foot_xray", "physical_exam"],
    },
    {
        "name": "Splay Leg",
        "name_ja": "開脚症",
        "symptoms": {"inability_to_stand", "mobility_issues", "splayed_limbs"},
        "description": "Congenital or neonatal condition where legs splay laterally, preventing normal locomotion. May be from slippery surfaces.",
        "description_ja": "足が横に開いてしまう先天性または新生児期の状態で、正常な移動を妨げます。滑りやすい床面が原因となることがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "limb_xray"],
    },
    {
        "name": "Exercise Wheel Injury",
        "name_ja": "回し車による外傷",
        "symptoms": {"bleeding", "lameness", "limb_swelling", "skin_abrasion", "tail_injury"},
        "description": "Injuries from wire or barred exercise wheels including tail degloving, limb fractures, and skin abrasions.",
        "description_ja": "ワイヤーまたは棒状の回し車による外傷で、尾の皮膚剥離、四肢骨折、皮膚擦過傷を含みます。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "xray", "wound_assessment"],
    },
    {
        "name": "Bite Wound Abscess",
        "name_ja": "咬傷膿瘍",
        "symptoms": {"draining_wound", "fever", "lethargy", "pain", "subcutaneous_swelling"},
        "description": "Abscess formation from infected bite wounds sustained during fights with cage mates.",
        "description_ja": "ケージメイトとの喧嘩で負った咬傷の感染による膿瘍形成です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "fine_needle_aspirate"],
    },
    {
        "name": "Cage Aggression Syndrome",
        "name_ja": "ケージ攻撃症候群",
        "symptoms": {"aggression", "bite_wounds", "hair_loss", "stress_signs", "weight_loss"},
        "description": "Chronic stress and aggression from territorial disputes in group-housed hamsters, especially Syrians.",
        "description_ja": "集団飼育されたハムスター、特にシリアンハムスターにおける縄張り争いによる慢性ストレスと攻撃性です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "environmental_review", "behavioral_assessment"],
    },
    {
        "name": "Stereotypic Behavior (Bar Chewing)",
        "name_ja": "常同行動（バーチューイング）",
        "symptoms": {"hair_loss", "repetitive_bar_chewing", "stress_signs", "teeth_damage"},
        "description": "Repetitive non-functional behaviour indicating poor welfare, environmental deprivation, or inadequate cage size.",
        "description_ja": "不十分な福祉、環境の貧困、ケージサイズの不足を示す反復的な無意味行動です。",
        "urgency": "low",
        "recommended_tests": ["behavioral_assessment", "dental_exam", "environmental_review"],
    },
    {
        "name": "Ear Mites (Notoedres)",
        "name_ja": "耳ダニ（ノトエドレス）",
        "symptoms": {"ear_crusting", "ear_scratching", "hair_loss_around_ears", "head_shaking"},
        "description": "Mite infestation of the ear pinnae and surrounding skin by Notoedres species, causing intense pruritus.",
        "description_ja": "ノトエドレス属による耳介および周囲皮膚のダニ寄生で、強い掻痒を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    {
        "name": "Fur Mites (Demodex criceti)",
        "name_ja": "毛包虫症（デモデックス・クリセティ）",
        "symptoms": {"dry_flaky_skin", "hair_loss", "skin_crusting", "skin_thickening"},
        "description": "Species-specific Demodex mite causing alopecia and dermatitis, often emerging during immunosuppression or old age.",
        "description_ja": "種特異的なデモデックスダニで、免疫抑制や老齢時に脱毛と皮膚炎を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy", "biopsy"],
    },
    {
        "name": "Tapeworm (Rodentolepis nana)",
        "name_ja": "条虫症（ロデントレピス・ナナ）",
        "symptoms": {"diarrhea", "perianal_irritation", "poor_coat", "weight_loss"},
        "description": "Dwarf tapeworm infection that has zoonotic potential, transmitted through fecal-oral route. Often subclinical.",
        "description_ja": "人獣共通感染症の可能性がある小型条虫感染で、糞口経路で伝播します。しばしば無症状です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_exam", "physical_exam"],
    },
    {
        "name": "Endoparasites (Mixed Infection)",
        "name_ja": "内部寄生虫症（混合感染）",
        "symptoms": {"abdominal_distension", "diarrhea", "lethargy", "poor_coat", "weight_loss"},
        "description": "Co-infection with multiple intestinal parasites including pinworms, tapeworms, and protozoa.",
        "description_ja": "蟯虫、条虫、原虫を含む複数の腸管寄生虫との同時感染です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_smear", "physical_exam"],
    },
    {
        "name": "Acute Gastric Dilation",
        "name_ja": "急性胃拡張",
        "symptoms": {"abdominal_distension", "abdominal_pain", "lethargy", "rapid_breathing", "shock"},
        "description": "Acute distension of the stomach with gas or fluid, which can rapidly lead to cardiovascular compromise and death.",
        "description_ja": "ガスや液体による胃の急性拡張で、急速に心血管障害と死亡に至る可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Toxicosis (Plant Poisoning)",
        "name_ja": "中毒症（植物中毒）",
        "symptoms": {"diarrhea", "drooling", "lethargy", "seizures", "sudden_death", "tremors"},
        "description": "Poisoning from ingestion of toxic plants or substances including houseplants, treated wood, or pesticides.",
        "description_ja": "観葉植物、処理済み木材、殺虫剤などの有毒植物や物質の摂取による中毒です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"anemia", "appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Poisoning from ingestion of galvanised cage components or zinc-coated objects causing haemolytic anaemia.",
        "description_ja": "亜鉛メッキされたケージ部品や亜鉛コーティング物質の摂取による溶血性貧血を伴う中毒です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "cbc", "serum_zinc_level"],
    },
    {
        "name": "Myocardial Fibrosis",
        "name_ja": "心筋線維症",
        "symptoms": {"exercise_intolerance", "lethargy", "respiratory_distress", "sudden_death"},
        "description": "Progressive replacement of cardiac muscle with fibrous tissue, leading to heart failure. Common in aged hamsters.",
        "description_ja": "心筋が線維組織に進行的に置換される状態で、心不全に至ります。高齢ハムスターに一般的です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "physical_exam"],
    },
    {
        "name": "Valvular Endocardiosis",
        "name_ja": "弁膜内膜症",
        "symptoms": {"exercise_intolerance", "heart_murmur", "lethargy", "respiratory_distress"},
        "description": "Degenerative thickening and nodular deformation of heart valves, leading to valvular insufficiency.",
        "description_ja": "心臓弁の変性性肥厚と結節性変形で、弁不全に至ります。",
        "urgency": "moderate",
        "recommended_tests": ["echocardiography", "chest_xray", "physical_exam"],
    },
    # ── Additional diseases to reach 190 ──
    {
        "name": "Wet Tail - Chronic Form",
        "name_ja": "ウェットテイル（慢性型）",
        "symptoms": {"wet_tail", "weight_loss", "rough_coat", "diarrhea", "dehydration"},
        "description": "Chronic proliferative ileitis causing persistent weight loss and intermittent diarrhea.",
        "description_ja": "慢性増殖性回腸炎により持続的な体重減少と間欠性下痢を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "bacterial_culture", "radiography"],
    },
    {
        "name": "Wet Tail - Neonatal Form",
        "name_ja": "ウェットテイル（新生児型）",
        "symptoms": {"wet_tail", "diarrhea", "sudden_death", "dehydration", "hunched_posture"},
        "description": "Peracute form in weaning-age hamsters (3-8 weeks) with rapid dehydration and high mortality.",
        "description_ja": "離乳期（3〜8週齢）のハムスターに見られる超急性型で、急速な脱水と高い死亡率を伴う。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_exam", "physical_exam"],
    },
    {
        "name": "Cheek Pouch Eversion",
        "name_ja": "頬袋外反",
        "symptoms": {"cheek_pouch_prolapse", "drooling", "pawing_at_mouth", "appetite_loss"},
        "description": "Complete eversion of the cheek pouch lining through the oral opening, requiring surgical replacement.",
        "description_ja": "頬袋の内膜が口から完全に外反し、外科的な整復が必要な状態。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "oral_exam"],
    },
    {
        "name": "Cheek Pouch Tumor",
        "name_ja": "頬袋腫瘍",
        "symptoms": {"cheek_swelling", "facial_swelling", "appetite_loss", "weight_loss"},
        "description": "Neoplastic growth within the cheek pouch, most commonly squamous cell carcinoma or papilloma.",
        "description_ja": "頬袋内の腫瘍性増殖で、扁平上皮癌や乳頭腫が最も多い。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "radiography"],
    },
    {
        "name": "Hamster Polyomavirus - Clinical Form",
        "name_ja": "ハムスターポリオーマウイルス（臨床型）",
        "symptoms": {"skin_lump", "hair_loss", "weight_loss", "lethargy"},
        "description": "Polyomavirus causing lymphoma, cutaneous epithelioma, and trichoepithelioma in Syrian hamsters.",
        "description_ja": "シリアンハムスターにリンパ腫、皮膚上皮腫、毛包上皮腫を引き起こすポリオーマウイルス。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "pcr_testing"],
    },
    {
        "name": "Hamster Polyomavirus - Subclinical Carrier",
        "name_ja": "ハムスターポリオーマウイルス（不顕性キャリア）",
        "symptoms": {"reduced_activity", "weight_loss"},
        "description": "Asymptomatic carrier state that may progress to tumour formation under immunosuppression.",
        "description_ja": "無症候性キャリア状態で、免疫抑制下で腫瘍形成に進行する可能性がある。",
        "urgency": "low",
        "recommended_tests": ["serology", "pcr_testing"],
    },
    {
        "name": "Lymphocytic Choriomeningitis (LCMV) - Acute",
        "name_ja": "リンパ球性脈絡髄膜炎（急性型）",
        "symptoms": {"lethargy", "fever", "seizures", "tremors", "weight_loss"},
        "description": "Zoonotic arenavirus infection causing meningitis in hamsters; important public health concern.",
        "description_ja": "ハムスターに髄膜炎を引き起こす人獣共通アレナウイルス感染症で、公衆衛生上重要。",
        "urgency": "high",
        "recommended_tests": ["serology", "pcr_testing", "histopathology"],
    },
    {
        "name": "Demodex Mange - Localized",
        "name_ja": "ニキビダニ症（局所型）",
        "symptoms": {"hair_loss", "dry_skin", "itching"},
        "description": "Localized Demodex criceti or D. aurati infestation causing focal alopecia, common in immunocompetent hamsters.",
        "description_ja": "免疫正常なハムスターに多いニキビダニの局所感染で、限局性脱毛を引き起こす。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Demodex Mange - Generalized",
        "name_ja": "ニキビダニ症（全身型）",
        "symptoms": {"hair_loss", "dry_skin", "severe_itching", "skin_crusting", "weight_loss"},
        "description": "Generalized demodicosis indicating underlying immunosuppression from Cushing's or lymphoma.",
        "description_ja": "全身性ニキビダニ症で、クッシング病やリンパ腫による免疫抑制を示唆する。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "blood_work", "biopsy"],
    },
    {
        "name": "Cushing's Disease - Early Stage",
        "name_ja": "クッシング病（初期）",
        "symptoms": {"hair_loss", "increased_thirst", "increased_urination", "appetite_increase"},
        "description": "Early hyperadrenocorticism with bilateral symmetric alopecia and polydipsia/polyuria.",
        "description_ja": "両側対称性脱毛と多飲多尿を伴う初期の副腎皮質機能亢進症。",
        "urgency": "moderate",
        "recommended_tests": ["acth_stimulation", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Cushing's Disease - Advanced",
        "name_ja": "クッシング病（進行期）",
        "symptoms": {"hair_loss", "thin_skin", "weight_gain", "increased_thirst", "skin_crusting", "lethargy"},
        "description": "Advanced hyperadrenocorticism with skin thinning, secondary infections, and muscle wasting.",
        "description_ja": "皮膚の菲薄化、二次感染、筋萎縮を伴う進行した副腎皮質機能亢進症。",
        "urgency": "high",
        "recommended_tests": ["acth_stimulation", "ultrasound", "blood_chemistry"],
    },
    {
        "name": "Atrial Thrombosis - Acute",
        "name_ja": "心房血栓症（急性）",
        "symptoms": {"cyanosis", "labored_breathing", "sudden_death", "hind_limb_weakness", "lethargy"},
        "description": "Acute left atrial thrombosis causing pulmonary oedema and sudden death, common in older hamsters.",
        "description_ja": "左心房血栓による肺水腫と突然死で、高齢ハムスターに多い。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "chest_xray"],
    },
    {
        "name": "Atrial Thrombosis - Chronic",
        "name_ja": "心房血栓症（慢性）",
        "symptoms": {"lethargy", "labored_breathing", "edema", "reduced_activity", "cyanosis"},
        "description": "Chronic atrial thrombosis with progressive congestive heart failure and peripheral oedema.",
        "description_ja": "慢性心房血栓症による進行性うっ血性心不全と末梢浮腫。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Amyloidosis - Renal",
        "name_ja": "アミロイドーシス（腎型）",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy", "edema"},
        "description": "Amyloid protein deposition in renal tissue causing progressive nephropathy and renal failure.",
        "description_ja": "腎組織へのアミロイドタンパク沈着により進行性の腎症と腎不全を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "blood_chemistry", "renal_biopsy"],
    },
    {
        "name": "Amyloidosis - Hepatic",
        "name_ja": "アミロイドーシス（肝型）",
        "symptoms": {"jaundice", "weight_loss", "lethargy", "ascites", "appetite_loss"},
        "description": "Amyloid deposition in liver causing hepatomegaly, jaundice, and hepatic failure.",
        "description_ja": "肝臓へのアミロイド沈着により肝腫大、黄疸、肝不全を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_biopsy", "ultrasound"],
    },
    {
        "name": "Polycystic Disease - Hepatic",
        "name_ja": "多発性嚢胞性疾患（肝型）",
        "symptoms": {"abdominal_distension", "appetite_loss", "weight_loss", "lethargy"},
        "description": "Multiple cysts in the liver, common in older hamsters, causing progressive hepatomegaly.",
        "description_ja": "高齢ハムスターに多い肝臓の多発性嚢胞で、進行性の肝腫大を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "blood_chemistry"],
    },
    {
        "name": "Polycystic Disease - Renal",
        "name_ja": "多発性嚢胞性疾患（腎型）",
        "symptoms": {"increased_thirst", "increased_urination", "abdominal_distension", "weight_loss"},
        "description": "Multiple cysts in the kidneys causing progressive renal insufficiency.",
        "description_ja": "腎臓の多発性嚢胞により進行性の腎機能不全を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Hibernation Syndrome - Mild",
        "name_ja": "冬眠症候群（軽度）",
        "symptoms": {"reduced_activity", "cold_body", "slow_breathing", "lethargy"},
        "description": "Torpor state from low ambient temperature or short light cycles; hamster is responsive when warmed.",
        "description_ja": "低温環境や短い日照により冬眠状態に入るが、加温すると反応が戻る軽度の状態。",
        "urgency": "moderate",
        "recommended_tests": ["body_temperature", "physical_exam"],
    },
    {
        "name": "Hibernation Syndrome - Severe",
        "name_ja": "冬眠症候群（重度）",
        "symptoms": {"unresponsiveness", "cold_body", "slow_breathing", "weakness"},
        "description": "Deep torpor with hypothermia, bradycardia, and minimal response; may be mistaken for death.",
        "description_ja": "低体温、徐脈、極小の反応を伴う深い冬眠状態で、死亡と誤認されることがある。",
        "urgency": "high",
        "recommended_tests": ["body_temperature", "heart_rate", "blood_glucose"],
    },
    {
        "name": "Cage Paralysis - Early",
        "name_ja": "ケージ麻痺（初期）",
        "symptoms": {"hind_limb_weakness", "stiffness", "reduced_activity"},
        "description": "Early muscle atrophy and joint stiffness from insufficient exercise in small cages.",
        "description_ja": "小さなケージでの運動不足による初期の筋萎縮と関節硬直。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Cage Paralysis - Advanced",
        "name_ja": "ケージ麻痺（進行期）",
        "symptoms": {"paralysis", "muscle_wasting", "hind_limb_weakness", "lameness"},
        "description": "Advanced disuse atrophy with irreversible muscle wasting and hindlimb dysfunction.",
        "description_ja": "不可逆的な筋萎縮と後肢機能障害を伴う進行した廃用性萎縮。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiography", "neurological_exam"],
    },
    {
        "name": "Tyzzer's Disease - Subclinical",
        "name_ja": "ティザー病（不顕性）",
        "symptoms": {"rough_coat", "weight_loss", "reduced_activity"},
        "description": "Subclinical Clostridium piliforme carrier state that may activate under stress or immunosuppression.",
        "description_ja": "ストレスや免疫抑制下で活性化する可能性のあるクロストリジウム・ピリフォルメの不顕性キャリア状態。",
        "urgency": "low",
        "recommended_tests": ["serology", "fecal_exam"],
    },
    {
        "name": "Dental Overgrowth (Molar)",
        "name_ja": "臼歯過長",
        "symptoms": {"overgrown_teeth", "drooling", "appetite_loss", "weight_loss"},
        "description": "Molar overgrowth causing sharp spurs that lacerate the tongue or cheek mucosa.",
        "description_ja": "臼歯の過長により鋭い突起が舌や頬粘膜を傷つける。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Pyoderma",
        "name_ja": "膿皮症",
        "symptoms": {"skin_redness", "discharge", "hair_loss", "skin_crusting", "pain"},
        "description": "Bacterial skin infection causing pustules and crusting, often from fight wounds or self-trauma.",
        "description_ja": "闘争傷や自傷による細菌性皮膚感染で、膿疱や痂皮を形成する。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "cytology", "skin_scraping"],
    },
    {
        "name": "Mammary Fibroadenoma",
        "name_ja": "乳腺線維腺腫",
        "symptoms": {"mammary_mass", "swelling", "weight_loss"},
        "description": "Benign mixed mammary tumour, more common in intact female hamsters.",
        "description_ja": "未避妊の雌ハムスターに多い良性の乳腺混合腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "radiography"],
    },
    {
        "name": "Melanocytoma",
        "name_ja": "メラノサイトーマ",
        "symptoms": {"dark_skin_lesion", "skin_lump"},
        "description": "Benign melanocytic tumour presenting as a pigmented nodule, common in hamsters.",
        "description_ja": "色素性結節として現れるメラノサイトの良性腫瘍で、ハムスターに多い。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy"],
    },
    {
        "name": "Harderian Gland Tumor",
        "name_ja": "ハーダー腺腫瘍",
        "symptoms": {"eye_bulging", "eye_discharge", "eye_redness"},
        "description": "Neoplasia of the Harderian gland behind the eye causing exophthalmos.",
        "description_ja": "眼球後方のハーダー腺の腫瘍で、眼球突出を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["orbital_ultrasound", "ct_scan", "biopsy"],
    },
    {
        "name": "Ear Canal Tumor",
        "name_ja": "耳道腫瘍",
        "symptoms": {"scratching_ears", "ear_discharge", "head_tilt", "swelling"},
        "description": "Ceruminous gland adenoma or carcinoma within the ear canal.",
        "description_ja": "耳道内の耳垢腺腺腫または腺癌。",
        "urgency": "high",
        "recommended_tests": ["otoscopy", "biopsy", "ct_scan"],
    },
    {
        "name": "Uterine Endometrial Hyperplasia",
        "name_ja": "子宮内膜過形成",
        "symptoms": {"vaginal_bleeding", "vaginal_discharge", "abdominal_distension"},
        "description": "Cystic endometrial hyperplasia predisposing to pyometra in intact female hamsters.",
        "description_ja": "嚢胞性子宮内膜過形成で、未避妊の雌ハムスターでは子宮蓄膿症に進行しやすい。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "blood_chemistry"],
    },
    {
        "name": "Testicular Abscess",
        "name_ja": "精巣膿瘍",
        "symptoms": {"testicular_swelling", "asymmetric_testes", "pain", "fever"},
        "description": "Bacterial infection forming an abscess within the testicle from ascending infection or haematogenous spread.",
        "description_ja": "上行感染や血行性播種による精巣内膿瘍形成。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "bacterial_culture"],
    },
    {
        "name": "Cardiac Myodegeneration",
        "name_ja": "心筋変性",
        "symptoms": {"lethargy", "labored_breathing", "reduced_activity", "cyanosis"},
        "description": "Age-related myocardial degeneration and fibrosis leading to cardiac dysfunction.",
        "description_ja": "加齢に伴う心筋変性と線維化により心機能障害が起こる。",
        "urgency": "moderate",
        "recommended_tests": ["echocardiography", "chest_xray"],
    },
    {
        "name": "Gastric Bloat (Acute)",
        "name_ja": "急性胃鼓脹",
        "symptoms": {"abdominal_distension", "lethargy", "appetite_loss", "labored_breathing"},
        "description": "Acute gastric distension with gas from dietary indiscretion or GI obstruction.",
        "description_ja": "食事の不摂生や消化管閉塞によるガスによる急性胃拡張。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Cerebrovascular Accident (Stroke)",
        "name_ja": "脳血管障害（脳卒中）",
        "symptoms": {"head_tilt", "circling", "paralysis", "disorientation", "seizures"},
        "description": "Cerebral ischaemia or haemorrhage causing acute neurological deficits, common in geriatric hamsters.",
        "description_ja": "脳虚血や脳出血による急性神経障害で、高齢ハムスターに多い。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "physical_exam"],
    },

    {
        "name": "Flank Gland Hyperplasia",
        "name_ja": "側腹腺過形成",
        "symptoms": {"licking_flank", "dark_skin_lesion", "hair_loss", "skin_crusting"},
        "description": "Benign enlargement and hyperkeratosis of the flank scent glands, more prominent in male Syrian hamsters.",
        "description_ja": "シリアンハムスターの雄に多い側腹臭腺の良性肥大と過角化。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "cytology"],
    },

]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "wet_tail": {"ja": "ウェットテイル（肛門周囲の汚れ）", "en": "Wet tail (soiled perianal area)"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "lethargy": {"ja": "元気消失", "en": "Lethargy"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite loss"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "hunched_posture": {"ja": "猫背姿勢", "en": "Hunched posture"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "rectal_prolapse": {"ja": "直腸脱", "en": "Rectal prolapse"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "rough_coat": {"ja": "被毛粗剛", "en": "Rough coat"},
    "cheek_swelling": {"ja": "頬の腫れ", "en": "Cheek swelling"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "pawing_at_mouth": {"ja": "口を掻く", "en": "Pawing at mouth"},
    "cheek_pouch_prolapse": {"ja": "頬袋脱", "en": "Cheek pouch prolapse"},
    "oral_mass": {"ja": "口腔内腫瘤", "en": "Oral mass"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "discharge": {"ja": "分泌物", "en": "Discharge"},
    "overgrown_teeth": {"ja": "歯の過成長", "en": "Overgrown teeth"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "hair_loss": {"ja": "脱毛", "en": "Hair loss"},
    "dry_skin": {"ja": "乾燥肌", "en": "Dry skin"},
    "itching": {"ja": "掻痒", "en": "Itching"},
    "skin_crusting": {"ja": "皮膚痂皮", "en": "Skin crusting"},
    "severe_itching": {"ja": "強い掻痒", "en": "Severe itching"},
    "skin_redness": {"ja": "皮膚発赤", "en": "Skin redness"},
    "scratching": {"ja": "掻き壊し", "en": "Scratching"},
    "circular_lesions": {"ja": "円形病変", "en": "Circular lesions"},
    "skin_lump": {"ja": "皮膚の腫瘤", "en": "Skin lump"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "pain": {"ja": "痛み", "en": "Pain"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "wound": {"ja": "創傷", "en": "Wound"},
    "mammary_mass": {"ja": "乳腺腫瘤", "en": "Mammary mass"},
    "enlarged_lymph_nodes": {"ja": "リンパ節腫大", "en": "Enlarged lymph nodes"},
    "skin_mass_growth": {"ja": "皮膚腫瘤の増大", "en": "Growing skin mass"},
    "ulceration": {"ja": "潰瘍化", "en": "Ulceration"},
    "increased_thirst": {"ja": "多飲", "en": "Increased thirst"},
    "increased_urination": {"ja": "多尿", "en": "Increased urination"},
    "vaginal_bleeding": {"ja": "膣出血", "en": "Vaginal bleeding"},
    "appetite_increase": {"ja": "食欲亢進", "en": "Increased appetite"},
    "thin_skin": {"ja": "皮膚の菲薄化", "en": "Thin skin"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "reduced_activity": {"ja": "活動性低下", "en": "Reduced activity"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "hind_limb_weakness": {"ja": "後肢の脱力", "en": "Hind limb weakness"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent urination"},
    "discomfort": {"ja": "不快感", "en": "Discomfort"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "loss_of_balance": {"ja": "平衡感覚喪失", "en": "Loss of balance"},
    "disorientation": {"ja": "見当識障害", "en": "Disorientation"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "seizures": {"ja": "痙攣発作", "en": "Seizures"},
    "tremors": {"ja": "震え", "en": "Tremors"},
    "unconsciousness": {"ja": "意識消失", "en": "Unconsciousness"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "vision_loss": {"ja": "視力喪失", "en": "Vision loss"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into objects"},
    "eye_bulging": {"ja": "眼球突出", "en": "Eye bulging"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "squinting": {"ja": "眼を細める", "en": "Squinting"},
    "scratching_ears": {"ja": "耳を掻く", "en": "Scratching ears"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear discharge"},
    "wasting": {"ja": "衰弱", "en": "Wasting"},
    "visible_parasites": {"ja": "寄生虫の目視", "en": "Visible parasites"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "limb_deformity": {"ja": "四肢変形", "en": "Limb deformity"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal discharge"},
    "mammary_swelling": {"ja": "乳腺腫脹", "en": "Mammary swelling"},
    "mammary_redness": {"ja": "乳腺発赤", "en": "Mammary redness"},
    "testicular_swelling": {"ja": "精巣腫大", "en": "Testicular swelling"},
    "asymmetric_testes": {"ja": "精巣の左右差", "en": "Asymmetric testes"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "unresponsiveness": {"ja": "無反応", "en": "Unresponsiveness"},
    "cold_body": {"ja": "体の冷え", "en": "Cold body"},
    "slow_breathing": {"ja": "呼吸緩徐", "en": "Slow breathing"},
    "sunken_eyes": {"ja": "眼の陥没", "en": "Sunken eyes"},
    "skin_tenting": {"ja": "皮膚テンティング", "en": "Skin tenting"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "bar_chewing": {"ja": "ケージ齧り", "en": "Bar chewing"},
    "excessive_grooming": {"ja": "過度のグルーミング", "en": "Excessive grooming"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "tail_injury": {"ja": "尾の損傷", "en": "Tail injury"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "licking_flank": {"ja": "脇腹を舐める", "en": "Licking flank area"},
    "dark_skin_lesion": {"ja": "暗色皮膚病変", "en": "Dark skin lesion"},
    "ear_crusting": {"ja": "耳の痂皮", "en": "Ear crusting"},
    "cold_intolerance": {"ja": "寒さに弱い", "en": "Cold intolerance"},
    "visible_worms_in_stool": {"ja": "便中の虫体", "en": "Visible worms in stool"},
    "perianal_irritation": {"ja": "肛門周囲の刺激", "en": "Perianal irritation"},

    # --- 追加症状 (DISEASES内で使用されている未登録項目) ---
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal pain"},
    "abscess_formation": {"ja": "Abscess Formation", "en": "Abscess Formation"},
    "abscesses": {"ja": "Abscesses", "en": "Abscesses"},
    "absent_testicle": {"ja": "Absent Testicle", "en": "Absent Testicle"},
    "aggressive_behavior": {"ja": "Aggressive Behavior", "en": "Aggressive Behavior"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "bald_patches": {"ja": "Bald Patches", "en": "Bald Patches"},
    "behavioral_changes": {"ja": "行動変化", "en": "Behavioral changes"},
    "bite_wounds": {"ja": "Bite Wounds", "en": "Bite Wounds"},
    "bleeding_from_foot": {"ja": "Bleeding From Foot", "en": "Bleeding From Foot"},
    "bleeding_from_mass": {"ja": "Bleeding From Mass", "en": "Bleeding From Mass"},
    "blood_stains_in_nest": {"ja": "Blood Stains In Nest", "en": "Blood Stains In Nest"},
    "bone_pain": {"ja": "Bone Pain", "en": "Bone Pain"},
    "cervical_abscess": {"ja": "Cervical Abscess", "en": "Cervical Abscess"},
    "cervical_mass": {"ja": "Cervical Mass", "en": "Cervical Mass"},
    "conjunctivitis": {"ja": "Conjunctivitis", "en": "Conjunctivitis"},
    "corneal_opacity": {"ja": "Corneal Opacity", "en": "Corneal Opacity"},
    "curled_posture": {"ja": "Curled Posture", "en": "Curled Posture"},
    "difficulty_swallowing": {"ja": "Difficulty Swallowing", "en": "Difficulty Swallowing"},
    "draining_wound": {"ja": "Draining Wound", "en": "Draining Wound"},
    "dry_flaky_skin": {"ja": "乾燥落屑性皮膚", "en": "Dry flaky skin"},
    "ear_scratching": {"ja": "耳掻き", "en": "Ear scratching"},
    "exercise_intolerance": {"ja": "Exercise Intolerance", "en": "Exercise Intolerance"},
    "exophthalmos": {"ja": "Exophthalmos", "en": "Exophthalmos"},
    "fecal_incontinence": {"ja": "Fecal Incontinence", "en": "Fecal Incontinence"},
    "foot_sores": {"ja": "Foot Sores", "en": "Foot Sores"},
    "foot_swelling": {"ja": "Foot Swelling", "en": "Foot Swelling"},
    "foul_odor_from_mouth": {"ja": "Foul Odor From Mouth", "en": "Foul Odor From Mouth"},
    "green_discharge": {"ja": "Green Discharge", "en": "Green Discharge"},
    "hair_loss_around_ears": {"ja": "Hair Loss Around Ears", "en": "Hair Loss Around Ears"},
    "hair_loss_around_mass": {"ja": "Hair Loss Around Mass", "en": "Hair Loss Around Mass"},
    "head_shaking": {"ja": "Head Shaking", "en": "Head Shaking"},
    "heart_murmur": {"ja": "Heart Murmur", "en": "Heart Murmur"},
    "hind_limb_paralysis": {"ja": "後肢麻痺", "en": "Hind limb paralysis"},
    "inability_to_stand": {"ja": "Inability To Stand", "en": "Inability To Stand"},
    "infertility": {"ja": "Infertility", "en": "Infertility"},
    "inguinal_swelling": {"ja": "Inguinal Swelling", "en": "Inguinal Swelling"},
    "intermittent_diarrhea": {"ja": "Intermittent Diarrhea", "en": "Intermittent Diarrhea"},
    "limb_swelling": {"ja": "四肢腫脹", "en": "Limb swelling"},
    "maternal_stress": {"ja": "Maternal Stress", "en": "Maternal Stress"},
    "missing_pups": {"ja": "Missing Pups", "en": "Missing Pups"},
    "mobility_issues": {"ja": "Mobility Issues", "en": "Mobility Issues"},
    "muscle_weakness": {"ja": "筋力低下", "en": "Muscle weakness"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "open_mouth_breathing": {"ja": "Open Mouth Breathing", "en": "Open Mouth Breathing"},
    "otitis": {"ja": "Otitis", "en": "Otitis"},
    "pawing_at_eye": {"ja": "Pawing At Eye", "en": "Pawing At Eye"},
    "photophobia": {"ja": "Photophobia", "en": "Photophobia"},
    "pigmented_skin_mass": {"ja": "Pigmented Skin Mass", "en": "Pigmented Skin Mass"},
    "polydipsia": {"ja": "Polydipsia", "en": "Polydipsia"},
    "polyuria": {"ja": "Polyuria", "en": "Polyuria"},
    "poor_coat": {"ja": "Poor Coat", "en": "Poor Coat"},
    "pruritus": {"ja": "Pruritus", "en": "Pruritus"},
    "rapid_breathing": {"ja": "頻呼吸", "en": "Rapid breathing"},
    "rapid_growth": {"ja": "Rapid Growth", "en": "Rapid Growth"},
    "recurrent_soft_stool": {"ja": "Recurrent Soft Stool", "en": "Recurrent Soft Stool"},
    "red_discharge_around_eye": {"ja": "Red Discharge Around Eye", "en": "Red Discharge Around Eye"},
    "red_nasal_discharge": {"ja": "Red Nasal Discharge", "en": "Red Nasal Discharge"},
    "reduced_fecal_output": {"ja": "Reduced Fecal Output", "en": "Reduced Fecal Output"},
    "reluctance_to_move": {"ja": "Reluctance To Move", "en": "Reluctance To Move"},
    "repetitive_bar_chewing": {"ja": "Repetitive Bar Chewing", "en": "Repetitive Bar Chewing"},
    "respiratory_distress": {"ja": "呼吸窮迫", "en": "Respiratory distress"},
    "shock": {"ja": "Shock", "en": "Shock"},
    "skin_abrasion": {"ja": "Skin Abrasion", "en": "Skin Abrasion"},
    "skin_exposure": {"ja": "Skin Exposure", "en": "Skin Exposure"},
    "skin_lesions": {"ja": "Skin Lesions", "en": "Skin Lesions"},
    "skin_masses": {"ja": "皮膚腫瘤", "en": "Skin masses"},
    "skin_thickening": {"ja": "Skin Thickening", "en": "Skin Thickening"},
    "skin_thinning": {"ja": "Skin Thinning", "en": "Skin Thinning"},
    "slow_growing_lump": {"ja": "Slow Growing Lump", "en": "Slow Growing Lump"},
    "splayed_limbs": {"ja": "Splayed Limbs", "en": "Splayed Limbs"},
    "straining_to_urinate": {"ja": "排尿困難", "en": "Straining to urinate"},
    "stress_signs": {"ja": "Stress Signs", "en": "Stress Signs"},
    "subcutaneous_mass": {"ja": "Subcutaneous Mass", "en": "Subcutaneous Mass"},
    "subcutaneous_swelling": {"ja": "Subcutaneous Swelling", "en": "Subcutaneous Swelling"},
    "sweet_breath_odor": {"ja": "Sweet Breath Odor", "en": "Sweet Breath Odor"},
    "teeth_damage": {"ja": "Teeth Damage", "en": "Teeth Damage"},
    "tissue_protrusion_from_vulva": {"ja": "Tissue Protrusion From Vulva", "en": "Tissue Protrusion From Vulva"},
    "toe_swelling": {"ja": "Toe Swelling", "en": "Toe Swelling"},
    "urinary_incontinence": {"ja": "Urinary Incontinence", "en": "Urinary Incontinence"},
    "visible_mass_in_mouth": {"ja": "Visible Mass In Mouth", "en": "Visible Mass In Mouth"},
    "visible_tissue_from_mouth": {"ja": "Visible Tissue From Mouth", "en": "Visible Tissue From Mouth"},
    "vocalization": {"ja": "Vocalization", "en": "Vocalization"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "wart_like_growths": {"ja": "疣贅様増殖", "en": "Wart-like growths"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None, lab_values: dict | None = None, gender=None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, load_diseases("hamster", DISEASES), SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species, lab_values=lab_values, gender=gender, prevalence_map=prevalence_data.SPECIES_PREVALENCE.get("hamster", {}))
