"""hedgehog_diseases.py – ハリネズミの疾患データベースと鑑別診断

ハリネズミに多く見られる60以上の疾患を網羅し、与えられた症状から鑑別診断を行う
簡易エンジンを提供します。実際の診断は獣医師の判断を必要とし、本データは教育
目的の参考情報です。
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic


DISEASES: List[Dict[str, Any]] = [
    # ──────────────────────────────────────────────
    # Dermatological
    # ──────────────────────────────────────────────
    {
        "name": "Mite Infestation (Caparinia)",
        "name_ja": "疥癬ダニ感染症（カパリニア）",
        "symptoms": {"quill_loss", "scratching", "flaky_skin", "crusting", "irritability"},
        "description": "Caparinia tripilis mites are the most common ectoparasite in hedgehogs, causing intense itching and quill loss.",
        "description_ja": "ハリネズミに最も多い外部寄生虫であるカパリニアダニによる感染症で、強い痒みと針の脱落を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    {
        "name": "Quilling (Physiological)",
        "name_ja": "クイリング（生理的針交換）",
        "symptoms": {"quill_loss", "new_quill_growth", "irritability"},
        "description": "Normal shedding and replacement of juvenile quills in young hedgehogs, typically occurring at 6-12 weeks of age.",
        "description_ja": "幼若ハリネズミに見られる正常な針の生え変わりで、通常生後6〜12週に起こります。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"quill_loss", "flaky_skin", "crusting", "skin_lesions", "alopecia"},
        "description": "Fungal infection caused by Trichophyton or Microsporum species, producing crusty skin lesions and quill loss.",
        "description_ja": "トリコフィトンやミクロスポルムによる真菌感染症で、痂皮を伴う皮膚病変と針の脱落を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "woods_lamp"],
    },
    {
        "name": "Dry Skin",
        "name_ja": "乾燥性皮膚炎",
        "symptoms": {"flaky_skin", "scratching", "dull_quills"},
        "description": "Common condition often caused by low humidity, excessive bathing, or poor diet.",
        "description_ja": "低湿度、過度な入浴、不適切な食事などにより起こる一般的な皮膚の乾燥です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    {
        "name": "Skin Abscess",
        "name_ja": "皮膚膿瘍",
        "symptoms": {"swelling", "pain", "discharge", "lethargy", "fever"},
        "description": "Localized bacterial infection forming a pocket of pus, often from bite wounds or quill injuries.",
        "description_ja": "咬傷や針の損傷から生じることが多い、膿の溜まった限局性の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "cytology"],
    },
    {
        "name": "Cutaneous Squamous Cell Carcinoma",
        "name_ja": "皮膚扁平上皮癌",
        "symptoms": {"skin_mass", "ulcerated_lesion", "quill_loss", "weight_loss"},
        "description": "Malignant skin tumor that can appear as an ulcerated or raised mass on the skin surface.",
        "description_ja": "皮膚表面に潰瘍性またな隆起性の腫瘤として現れる悪性皮膚腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiography"],
    },
    {
        "name": "Dermatitis (Bacterial)",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_lesions", "redness", "discharge", "scratching", "crusting"},
        "description": "Bacterial skin infection causing inflammation, often secondary to mite infestation or trauma.",
        "description_ja": "ダニ感染や外傷に続発することが多い、細菌による皮膚の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "culture_sensitivity", "cytology"],
    },
    # ──────────────────────────────────────────────
    # Oncological
    # ──────────────────────────────────────────────
    {
        "name": "Oral Squamous Cell Carcinoma",
        "name_ja": "口腔扁平上皮癌",
        "symptoms": {"oral_mass", "drooling", "appetite_loss", "weight_loss", "bloody_mouth", "facial_swelling"},
        "description": "Highly prevalent malignant tumor of the oral cavity in hedgehogs, causing difficulty eating and drooling.",
        "description_ja": "ハリネズミに非常に多い口腔内の悪性腫瘍で、摂食困難や流涎を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "biopsy", "radiography", "ct_scan"],
    },
    {
        "name": "Mammary Gland Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "mammary_discharge", "swelling", "weight_loss", "lethargy"},
        "description": "Common neoplasia in female hedgehogs; can be benign or malignant with potential for metastasis.",
        "description_ja": "雌のハリネズミに多い腫瘍で、良性・悪性の両方があり転移の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "radiography", "ultrasound"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "appetite_loss", "lethargy", "lymph_node_enlargement", "splenomegaly"},
        "description": "Systemic cancer of the lymphatic system; one of the more common neoplasias in hedgehogs.",
        "description_ja": "リンパ系の全身性腫瘍で、ハリネズミに比較的多く見られる腫瘍の一つです。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "fine_needle_aspirate", "biopsy", "radiography", "ultrasound"],
    },
    {
        "name": "Uterine Adenocarcinoma",
        "name_ja": "子宮腺癌",
        "symptoms": {"vaginal_bleeding", "abdominal_distension", "weight_loss", "lethargy", "appetite_loss"},
        "description": "Malignant tumor of the uterus, very common in intact female hedgehogs over 3 years old.",
        "description_ja": "子宮の悪性腫瘍で、3歳以上の未避妊の雌ハリネズミに非常に多く見られます。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "blood_work", "histopathology"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"skin_mass", "rapid_growth", "weight_loss", "lethargy"},
        "description": "Aggressive malignant tumor arising from connective tissue, often on the limbs or body wall.",
        "description_ja": "結合組織から発生する悪性腫瘍で、四肢や体壁に多く見られます。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiography"],
    },
    {
        "name": "Mast Cell Tumor",
        "name_ja": "肥満細胞腫",
        "symptoms": {"skin_mass", "swelling", "redness", "ulcerated_lesion"},
        "description": "Neoplasia of mast cells that can present as cutaneous nodules; may be locally aggressive.",
        "description_ja": "皮膚の結節として現れる肥満細胞の腫瘍で、局所的に悪性化することがあります。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "histopathology"],
    },
    {
        "name": "Hemangiosarcoma",
        "name_ja": "血管肉腫",
        "symptoms": {"lethargy", "weakness", "pale_mucous_membranes", "abdominal_distension", "collapse"},
        "description": "Aggressive vascular tumor that can cause internal bleeding; often affects the spleen or liver.",
        "description_ja": "脾臓や肝臓に多い血管由来の悪性腫瘍で、内出血を引き起こすことがあります。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "blood_work", "radiography", "histopathology"],
    },
    {
        "name": "Sebaceous Gland Adenoma",
        "name_ja": "皮脂腺腫",
        "symptoms": {"skin_mass", "slow_growth"},
        "description": "Benign tumor of the sebaceous glands presenting as a small, slow-growing cutaneous mass.",
        "description_ja": "皮脂腺から発生する良性腫瘍で、小さくゆっくりと成長する皮膚腫瘤です。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy"],
    },
    # ──────────────────────────────────────────────
    # Gastrointestinal
    # ──────────────────────────────────────────────
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "inability_to_curl", "decreased_activity", "fatty_deposits"},
        "description": "Extremely common in captive hedgehogs due to overfeeding and insufficient exercise; predisposes to hepatic lipidosis.",
        "description_ja": "過食と運動不足による飼育下のハリネズミに非常に多い状態で、肝リピドーシスの素因となります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_work", "dietary_review"],
    },
    {
        "name": "Diarrhea (Non-specific)",
        "name_ja": "下痢（非特異的）",
        "symptoms": {"diarrhea", "dehydration", "appetite_loss", "lethargy"},
        "description": "Loose or watery stools caused by dietary changes, stress, infection, or parasites.",
        "description_ja": "食事の変更、ストレス、感染症、寄生虫などによる軟便や水様便です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_culture", "blood_work"],
    },
    {
        "name": "Gastrointestinal Foreign Body",
        "name_ja": "消化管内異物",
        "symptoms": {"vomiting", "appetite_loss", "lethargy", "abdominal_pain", "constipation"},
        "description": "Ingestion of indigestible material causing obstruction; hedgehogs may chew on cage bedding or rubber items.",
        "description_ja": "ケージの床材やゴム製品を噛むことで起こる消化管閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "physical_exam"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"appetite_loss", "lethargy", "jaundice", "weight_loss", "hepatomegaly"},
        "description": "Fatty liver disease common in obese hedgehogs or those that stop eating; can be life-threatening.",
        "description_ja": "肥満や食欲不振のハリネズミに多い脂肪肝で、致死的になることがあります。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "liver_enzymes", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Enteritis",
        "name_ja": "腸炎",
        "symptoms": {"diarrhea", "bloody_stool", "appetite_loss", "dehydration", "abdominal_pain", "lethargy"},
        "description": "Inflammation of the intestinal tract caused by bacteria, viruses, or parasites.",
        "description_ja": "細菌、ウイルス、寄生虫による腸管の炎症です。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "fecal_culture", "blood_work", "radiography"],
    },
    {
        "name": "Colitis",
        "name_ja": "大腸炎",
        "symptoms": {"diarrhea", "mucoid_stool", "straining_to_defecate", "bloody_stool"},
        "description": "Inflammation of the large intestine causing mucoid or bloody diarrhea.",
        "description_ja": "粘液性または血液性の下痢を引き起こす大腸の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_culture", "blood_work"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"tissue_protruding_from_anus", "straining_to_defecate", "bloody_stool", "lethargy"},
        "description": "Protrusion of rectal tissue through the anus, often associated with enteritis or straining.",
        "description_ja": "腸炎やいきみに伴う直腸組織の肛門からの脱出です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_exam", "radiography"],
    },
    # ──────────────────────────────────────────────
    # Dental
    # ──────────────────────────────────────────────
    {
        "name": "Periodontal Disease",
        "name_ja": "歯周病",
        "symptoms": {"bad_breath", "drooling", "appetite_loss", "tartar_buildup", "tooth_loss", "facial_swelling"},
        "description": "Very common in hedgehogs over 2 years old; accumulation of plaque and tartar leading to gum disease and tooth loss.",
        "description_ja": "2歳以上のハリネズミに非常に多く、歯垢・歯石の蓄積により歯肉炎や歯の脱落を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "dental_radiography", "blood_work"],
    },
    {
        "name": "Gingivitis",
        "name_ja": "歯肉炎",
        "symptoms": {"red_gums", "bad_breath", "drooling", "appetite_loss"},
        "description": "Inflammation of the gums, often an early sign of periodontal disease.",
        "description_ja": "歯肉の炎症で、歯周病の初期症状であることが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "dental_radiography"],
    },
    {
        "name": "Tooth Root Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "drooling", "pain", "bad_breath"},
        "description": "Infection at the root of a tooth causing facial swelling and pain.",
        "description_ja": "歯根部の感染症で、顔面の腫脹と疼痛を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "dental_radiography", "culture_sensitivity"],
    },
    {
        "name": "Dental Tartar",
        "name_ja": "歯石",
        "symptoms": {"tartar_buildup", "bad_breath", "red_gums"},
        "description": "Accumulation of hardened plaque on teeth; very common in pet hedgehogs fed soft diets.",
        "description_ja": "歯面への�ite硬化した歯垢の蓄積で、軟らかい食事を与えられたハリネズミに多いです。",
        "urgency": "low",
        "recommended_tests": ["oral_exam", "dental_radiography"],
    },
    # ──────────────────────────────────────────────
    # Respiratory
    # ──────────────────────────────────────────────
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"nasal_discharge", "labored_breathing", "lethargy", "appetite_loss", "sneezing", "coughing"},
        "description": "Bacterial or fungal infection of the lungs; can be life-threatening if untreated.",
        "description_ja": "細菌または真菌による肺の感染症で、未治療では致命的になりえます。",
        "urgency": "high",
        "recommended_tests": ["radiography", "blood_work", "culture_sensitivity", "tracheal_wash"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部気道感染症",
        "symptoms": {"nasal_discharge", "sneezing", "labored_breathing", "lethargy", "appetite_loss"},
        "description": "Infection of the nasal passages and upper airways, often bacterial in origin.",
        "description_ja": "鼻腔および上気道の感染症で、多くは細菌性です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography", "nasal_culture"],
    },
    {
        "name": "Mycobacteriosis (Pulmonary)",
        "name_ja": "マイコバクテリア症（肺型）",
        "symptoms": {"weight_loss", "labored_breathing", "coughing", "lethargy", "appetite_loss"},
        "description": "Mycobacterial infection that can affect the lungs and other organs; zoonotic potential.",
        "description_ja": "肺や他臓器に影響するマイコバクテリア感染症で、人獣共通感染症の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["radiography", "acid_fast_staining", "pcr", "biopsy"],
    },
    # ──────────────────────────────────────────────
    # Neurological
    # ──────────────────────────────────────────────
    {
        "name": "Wobbly Hedgehog Syndrome (WHS)",
        "name_ja": "ふらつき症候群（WHS）",
        "symptoms": {"ataxia", "hindlimb_weakness", "muscle_wasting", "falling_over", "progressive_paralysis", "weight_loss"},
        "description": "Progressive demyelinating disease unique to hedgehogs causing progressive paralysis; genetic in origin with no cure.",
        "description_ja": "ハリネズミ特有の進行性脱髄疾患で、後肢の麻痺から全身へ進行します。遺伝性で治療法はありません。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "physical_exam", "histopathology_postmortem"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "circling", "ataxia", "nystagmus", "falling_over"},
        "description": "Inner ear or central nervous system disorder causing loss of balance and head tilt.",
        "description_ja": "内耳または中枢神経系の障害により平衡感覚の喪失と斜頸を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "otoscopic_exam", "radiography", "ct_scan"],
    },
    {
        "name": "Seizures",
        "name_ja": "てんかん発作",
        "symptoms": {"seizures", "collapse", "disorientation", "paddling", "lethargy"},
        "description": "Involuntary neurological episodes that can result from toxins, metabolic disease, brain tumors, or WHS.",
        "description_ja": "毒素、代謝性疾患、脳腫瘍、WHSなどが原因で起こる不随意的な神経学的発作です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_work", "neurological_exam", "radiography", "ct_scan"],
    },
    {
        "name": "Brain Tumor",
        "name_ja": "脳腫瘍",
        "symptoms": {"seizures", "circling", "head_tilt", "behavioral_changes", "ataxia", "appetite_loss"},
        "description": "Intracranial neoplasia causing progressive neurological signs.",
        "description_ja": "進行性の神経学的兆候を引き起こす頭蓋内腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "ct_scan", "mri"],
    },
    # ──────────────────────────────────────────────
    # Cardiac
    # ──────────────────────────────────────────────
    {
        "name": "Dilated Cardiomyopathy",
        "name_ja": "拡張型心筋症",
        "symptoms": {"labored_breathing", "lethargy", "weakness", "exercise_intolerance", "coughing", "collapse"},
        "description": "Enlargement and weakening of the heart muscle, reducing its ability to pump blood effectively.",
        "description_ja": "心筋の拡張と弱化により、心臓のポンプ機能が低下する疾患です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiography", "electrocardiogram"],
    },
    {
        "name": "Cardiomyopathy (General)",
        "name_ja": "心筋症",
        "symptoms": {"lethargy", "labored_breathing", "weakness", "ascites", "exercise_intolerance"},
        "description": "Disease of the heart muscle that is relatively common in older hedgehogs.",
        "description_ja": "高齢のハリネズミに比較的多い心筋の疾患です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiography", "blood_work", "electrocardiogram"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"labored_breathing", "lethargy", "ascites", "coughing", "weakness", "collapse", "cyanosis"},
        "description": "End-stage cardiac disease where the heart can no longer meet the body's circulatory needs.",
        "description_ja": "心臓が身体の循環需要を満たせなくなる末期の心疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "radiography", "blood_work", "electrocardiogram"],
    },
    # ──────────────────────────────────────────────
    # Musculoskeletal
    # ──────────────────────────────────────────────
    {
        "name": "Limb Fracture",
        "name_ja": "四肢骨折",
        "symptoms": {"lameness", "swelling", "pain", "limb_not_bearing_weight", "crying"},
        "description": "Broken bone in the legs, often caused by falls, entrapment in cage accessories, or running wheel injuries.",
        "description_ja": "ケージの器具への挟み込みや回し車による事故で起こる四肢の骨折です。",
        "urgency": "high",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "stiffness", "decreased_activity", "pain", "reluctance_to_curl"},
        "description": "Degenerative joint disease common in older or obese hedgehogs.",
        "description_ja": "高齢や肥満のハリネズミに多い変性性関節疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Leg Injury (Soft Tissue)",
        "name_ja": "脚の軟部組織損傷",
        "symptoms": {"lameness", "swelling", "pain", "decreased_activity"},
        "description": "Sprains, strains, or bruising of leg soft tissues from cage injuries or falls.",
        "description_ja": "ケージ内での事故や落下による脚の捻挫、筋肉損傷、打撲です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Toe Loss / Necrosis",
        "name_ja": "趾壊死・趾脱落",
        "symptoms": {"swollen_foot", "discolored_toes", "lameness", "fiber_constriction"},
        "description": "Thread or fiber wrapped around toes cutting off blood supply; common cage hazard for hedgehogs.",
        "description_ja": "繊維が趾に巻きつき血流を遮断する状態で、ハリネズミに多いケージ内の事故です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    # ──────────────────────────────────────────────
    # Ophthalmological
    # ──────────────────────────────────────────────
    {
        "name": "Proptosis (Eye Protrusion)",
        "name_ja": "眼球突出",
        "symptoms": {"eye_bulging", "eye_discharge", "pain", "swelling"},
        "description": "Forward displacement of the eyeball, often caused by retrobulbar abscess or trauma.",
        "description_ja": "眼球後部の膿瘍や外傷により眼球が前方に突出する状態です。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmic_exam", "radiography", "ultrasound"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "eye_squinting", "swelling"},
        "description": "Inflammation of the conjunctiva due to infection, irritation, or allergies.",
        "description_ja": "感染、刺激、アレルギーによる結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "culture_sensitivity", "fluorescein_stain"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"eye_squinting", "eye_discharge", "eye_cloudiness", "pain", "eye_redness"},
        "description": "Defect in the corneal surface, often from trauma or bedding irritation.",
        "description_ja": "外傷や床材の刺激による角膜表面の欠損です。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam", "culture_sensitivity"],
    },
    {
        "name": "Retrobulbar Abscess",
        "name_ja": "眼球後膿瘍",
        "symptoms": {"eye_bulging", "pain", "appetite_loss", "facial_swelling", "fever"},
        "description": "Bacterial abscess behind the eye causing proptosis; often related to tooth root infection.",
        "description_ja": "歯根感染に関連することが多い眼球後部の細菌性膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "radiography", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"eye_cloudiness", "vision_loss", "bumping_into_objects"},
        "description": "Opacification of the lens; may be age-related or secondary to other disease.",
        "description_ja": "加齢や他の疾患に続発する水晶体の混濁です。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic_exam"],
    },
    # ──────────────────────────────────────────────
    # Urinary
    # ──────────────────────────────────────────────
    {
        "name": "Chronic Kidney Disease",
        "name_ja": "慢性腎臓病",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "appetite_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function; common in older hedgehogs.",
        "description_ja": "高齢のハリネズミに多い、進行性の腎機能低下です。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "urinalysis", "ultrasound"],
    },
    {
        "name": "Cystitis",
        "name_ja": "膀胱炎",
        "symptoms": {"bloody_urine", "frequent_urination", "straining_to_urinate", "pain"},
        "description": "Bacterial infection or inflammation of the urinary bladder.",
        "description_ja": "細菌感染や炎症による膀胱の疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "ultrasound"],
    },
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"bloody_urine", "straining_to_urinate", "frequent_urination", "pain", "appetite_loss"},
        "description": "Formation of mineral stones in the urinary tract causing obstruction and discomfort.",
        "description_ja": "尿路内に鉱物性の結石が形成され、閉塞や不快感を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "urinalysis", "urine_culture"],
    },
    {
        "name": "Urinary Tract Infection",
        "name_ja": "尿路感染症",
        "symptoms": {"frequent_urination", "bloody_urine", "straining_to_urinate", "lethargy", "fever"},
        "description": "Bacterial infection of the urinary tract causing inflammation and discomfort.",
        "description_ja": "細菌による尿路の感染症で、炎症や不快感を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "blood_work"],
    },
    # ──────────────────────────────────────────────
    # Reproductive
    # ──────────────────────────────────────────────
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "abdominal_distension", "lethargy", "appetite_loss", "excessive_thirst", "fever"},
        "description": "Life-threatening uterine infection with pus accumulation; requires emergency surgery.",
        "description_ja": "子宮内に膿が蓄積する致命的な感染症で、緊急手術が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "blood_work", "radiography"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "lethargy", "vaginal_discharge", "abdominal_pain", "distress"},
        "description": "Difficulty giving birth; hedgehog litters can become stuck due to large fetal size or uterine inertia.",
        "description_ja": "胎子のサイズが大きい場合や子宮無力症により出産困難になる状態です。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound", "physical_exam"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "mammary_redness", "pain", "fever", "appetite_loss", "lethargy"},
        "description": "Bacterial infection of the mammary glands in nursing females.",
        "description_ja": "授乳中の雌に起こる乳腺の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "blood_work"],
    },
    {
        "name": "Uterine Polyps",
        "name_ja": "子宮ポリープ",
        "symptoms": {"vaginal_bleeding", "vaginal_discharge", "lethargy"},
        "description": "Benign growths in the uterine lining that can cause intermittent bleeding.",
        "description_ja": "子宮内膜の良性増殖で、間欠的な出血を引き起こすことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "blood_work", "histopathology"],
    },
    # ──────────────────────────────────────────────
    # Metabolic
    # ──────────────────────────────────────────────
    {
        "name": "Hypothermia / Hibernation Attempt",
        "name_ja": "低体温症・冬眠兆候",
        "symptoms": {"lethargy", "cold_body", "unresponsiveness", "curled_tightly", "decreased_activity"},
        "description": "African pygmy hedgehogs cannot truly hibernate; temperatures below 20C can trigger torpor which is life-threatening.",
        "description_ja": "ヨツユビハリネズミは冬眠できず、20度以下の温度で致命的な低体温状態に陥ります。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "temperature_check", "blood_work"],
    },
    {
        "name": "Heatstroke",
        "name_ja": "熱中症",
        "symptoms": {"panting", "lethargy", "unresponsiveness", "drooling", "collapse", "hot_body"},
        "description": "Overheating from ambient temperatures above 30C; hedgehogs are very heat-sensitive.",
        "description_ja": "30度以上の環境温度による過熱状態で、ハリネズミは暑さに非常に弱いです。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "temperature_check", "blood_work"],
    },
    {
        "name": "Fatty Liver Disease (Non-obese)",
        "name_ja": "脂肪肝（非肥満型）",
        "symptoms": {"appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Hepatic lipidosis that can occur in non-obese hedgehogs due to anorexia from other illnesses.",
        "description_ja": "他の疾患による食欲不振から発症する脂肪肝で、肥満でなくても起こりえます。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "liver_enzymes", "ultrasound"],
    },
    # ──────────────────────────────────────────────
    # Infectious
    # ──────────────────────────────────────────────
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "lethargy", "appetite_loss", "weight_loss", "dehydration"},
        "description": "Bacterial infection by Salmonella species; zoonotic risk to owners through fecal-oral route.",
        "description_ja": "サルモネラ菌による細菌感染症で、糞口経路で飼い主への感染リスクがあります。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "blood_work", "fecal_exam"],
    },
    {
        "name": "Mycobacteriosis (Disseminated)",
        "name_ja": "マイコバクテリア症（播種型）",
        "symptoms": {"weight_loss", "lethargy", "skin_lesions", "lymph_node_enlargement", "appetite_loss"},
        "description": "Systemic mycobacterial infection affecting multiple organs; hedgehogs are particularly susceptible.",
        "description_ja": "複数の臓器に影響する全身性のマイコバクテリア感染症で、ハリネズミは特に感受性が高いです。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_staining", "pcr", "biopsy", "blood_work", "radiography"],
    },
    {
        "name": "Herpesvirus Infection",
        "name_ja": "ヘルペスウイルス感染症",
        "symptoms": {"nasal_discharge", "appetite_loss", "lethargy", "weight_loss", "labored_breathing"},
        "description": "Viral infection that can cause respiratory and systemic signs in hedgehogs.",
        "description_ja": "ハリネズミに呼吸器症状や全身症状を引き起こすウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr", "blood_work", "radiography"],
    },
    # ──────────────────────────────────────────────
    # Parasitic
    # ──────────────────────────────────────────────
    {
        "name": "Tick Infestation",
        "name_ja": "マダニ寄生",
        "symptoms": {"visible_parasites", "scratching", "lethargy", "anemia"},
        "description": "Tick attachment, more common in wild or outdoor hedgehogs; can transmit diseases.",
        "description_ja": "野生や屋外飼育のハリネズミに多いマダニの寄生で、疾病を媒介することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_work"],
    },
    {
        "name": "Flea Infestation",
        "name_ja": "ノミ寄生",
        "symptoms": {"scratching", "visible_parasites", "flaky_skin", "irritability", "alopecia"},
        "description": "Flea parasitism causing skin irritation and pruritus.",
        "description_ja": "ノミの寄生により皮膚の刺激と掻痒を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "flea_comb_exam"],
    },
    {
        "name": "Internal Parasites (Intestinal Worms)",
        "name_ja": "腸内寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "appetite_loss", "bloating", "visible_worms_in_stool"},
        "description": "Intestinal helminth infections including roundworms and tapeworms.",
        "description_ja": "回虫や条虫などの腸管内寄生虫感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_exam"],
    },
    {
        "name": "Lungworm Infection",
        "name_ja": "肺虫感染症",
        "symptoms": {"coughing", "labored_breathing", "nasal_discharge", "weight_loss", "lethargy"},
        "description": "Crenosoma striatum and other lungworm species infect hedgehog airways; common in wild hedgehogs.",
        "description_ja": "クレノソーマなどの肺虫がハリネズミの気道に感染する疾患で、野生個体に多いです。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam_baermann", "radiography", "tracheal_wash"],
    },
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム感染症",
        "symptoms": {"diarrhea", "bloody_stool", "dehydration", "weight_loss", "lethargy"},
        "description": "Protozoal infection of the intestinal tract causing diarrhea, especially in young or stressed hedgehogs.",
        "description_ja": "若齢やストレス下のハリネズミに多い腸管の原虫感染症で、下痢を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_exam"],
    },
    {
        "name": "Ear Mites",
        "name_ja": "耳ダニ症",
        "symptoms": {"ear_scratching", "head_shaking", "ear_discharge", "crusting"},
        "description": "Mite infestation of the ear canal causing irritation and waxy discharge.",
        "description_ja": "耳道内のダニ寄生により刺激と蝋状の分泌物を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "ear_swab_microscopy"],
    },
    # ──────────────────────────────────────────────
    # Additional Oncological
    # ──────────────────────────────────────────────
    {
        "name": "Intestinal Adenocarcinoma",
        "name_ja": "腸腺癌",
        "symptoms": {"weight_loss", "diarrhea", "bloody_stool", "appetite_loss", "lethargy", "abdominal_distension"},
        "description": "Malignant tumor of the intestinal lining; hedgehogs are predisposed to GI neoplasia.",
        "description_ja": "腸管粘膜の悪性腫瘍で、ハリネズミは消化管腫瘍になりやすいです。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "biopsy", "blood_work"],
    },
    {
        "name": "Hepatocellular Carcinoma",
        "name_ja": "肝細胞癌",
        "symptoms": {"appetite_loss", "weight_loss", "jaundice", "hepatomegaly", "lethargy", "abdominal_distension"},
        "description": "Primary liver cancer; may develop from chronic hepatic lipidosis or other liver diseases.",
        "description_ja": "原発性の肝臓癌で、慢性肝リピドーシスや他の肝疾患から発展することがあります。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "ultrasound", "biopsy", "liver_enzymes"],
    },
    {
        "name": "Ovarian Tumor",
        "name_ja": "卵巣腫瘍",
        "symptoms": {"abdominal_distension", "lethargy", "appetite_loss", "weight_loss", "vaginal_discharge"},
        "description": "Neoplasia of the ovary; can cause hormonal imbalances and abdominal enlargement.",
        "description_ja": "卵巣の腫瘍で、ホルモン異常や腹部膨満を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "blood_work", "radiography", "histopathology"],
    },
    # ──────────────────────────────────────────────
    # Additional conditions
    # ──────────────────────────────────────────────
    {
        "name": "Self-anointing (Normal Behavior)",
        "name_ja": "唾液塗布行動（正常行動）",
        "symptoms": {"foaming_at_mouth", "contorting_body", "spreading_saliva"},
        "description": "Normal hedgehog behavior where they produce frothy saliva and spread it on their quills when encountering new scents.",
        "description_ja": "新しい匂いに接した際に泡状の唾液を産生し針に塗布する正常な行動です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Balloon Syndrome",
        "name_ja": "バルーン症候群",
        "symptoms": {"subcutaneous_emphysema", "swelling", "distension", "lethargy"},
        "description": "Subcutaneous emphysema causing the hedgehog to inflate like a balloon; caused by air leaking under the skin from respiratory damage.",
        "description_ja": "呼吸器の損傷により皮下に空気が漏れ、風船のように膨張する皮下気腫です。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "physical_exam", "blood_work"],
    },
    {
        "name": "Ear Infection (Otitis)",
        "name_ja": "耳感染症（外耳炎）",
        "symptoms": {"ear_scratching", "head_shaking", "ear_discharge", "pain", "head_tilt"},
        "description": "Bacterial or fungal infection of the ear canal causing pain and discharge.",
        "description_ja": "細菌または真菌による耳道の感染症で、疼痛と分泌物を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "culture_sensitivity", "cytology"],
    },
    {
        "name": "Adrenal Disease",
        "name_ja": "副腎疾患",
        "symptoms": {"alopecia", "weight_loss", "lethargy", "excessive_thirst", "muscle_wasting"},
        "description": "Adrenal gland dysfunction causing hormonal imbalances; can be neoplastic or hyperplastic.",
        "description_ja": "副腎機能障害によるホルモン異常で、腫瘍性または過形成性のことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["blood_work", "hormone_panel", "ultrasound"],
    },
    {
        "name": "Penile Prolapse / Paraphimosis",
        "name_ja": "陰茎脱出・嵌頓包茎",
        "symptoms": {"penile_protrusion", "swelling", "pain", "licking_genital_area", "distress"},
        "description": "Inability to retract the penis; can occur from fiber constriction, trauma, or infection.",
        "description_ja": "繊維の絡みつき、外傷、感染により陰茎が陥頓する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "culture_sensitivity"],
    },
    {
        "name": "Green Stool (Stress/Diet)",
        "name_ja": "緑色便（ストレス・食事性）",
        "symptoms": {"green_stool", "appetite_loss", "behavioral_changes"},
        "description": "Green-colored feces caused by stress, diet change, or rapid GI transit; very common in newly acquired hedgehogs.",
        "description_ja": "ストレス、食事変更、消化管通過の促進による緑色便で、新規導入個体に非常に多いです。",
        "urgency": "low",
        "recommended_tests": ["fecal_exam", "husbandry_review"],
    },
    {
        "name": "Anemia",
        "name_ja": "貧血",
        "symptoms": {"pale_mucous_membranes", "lethargy", "weakness", "appetite_loss", "labored_breathing"},
        "description": "Reduced red blood cell count from parasites, chronic disease, blood loss, or bone marrow disease.",
        "description_ja": "寄生虫、慢性疾患、出血、骨髄疾患などによる赤血球の減少です。",
        "urgency": "high",
        "recommended_tests": ["blood_work", "fecal_exam", "blood_smear"],
    },
    {
        "name": "Intervertebral Disc Disease",
        "name_ja": "椎間板疾患",
        "symptoms": {"hindlimb_weakness", "pain", "ataxia", "reluctance_to_curl", "crying"},
        "description": "Disc degeneration or herniation causing spinal cord compression and pain.",
        "description_ja": "椎間板の変性やヘルニアにより脊髄圧迫と疼痛を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["radiography", "neurological_exam", "ct_scan", "mri"],
    },
    {
        "name": "Splenic Disease",
        "name_ja": "脾臓疾患",
        "symptoms": {"splenomegaly", "lethargy", "abdominal_distension", "weight_loss", "appetite_loss"},
        "description": "Splenic enlargement from various causes including neoplasia, infection, or extramedullary hematopoiesis.",
        "description_ja": "腫瘍、感染、髄外造血などさまざまな原因による脾臓の腫大です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "blood_work", "fine_needle_aspirate"],
    },
    {
        "name": "Wobbly Hedgehog Syndrome (WHS) - Early Stage",
        "name_ja": "ふらつきハリネズミ症候群（WHS）- 初期段階",
        "symptoms": {"falling_over_occasionally", "mild_ataxia", "muscle_twitching", "stumbling"},
        "description": "Early-stage progressive demyelinating disease showing mild hind limb ataxia. Genetic, with no cure. Important to differentiate from other neurological diseases.",
        "description_ja": "軽度の後肢運動失調を示す初期段階の進行性脱髄疾患。遺伝性で治療法なし。他の神経疾患との鑑別が重要です。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "physical_exam", "genetic_testing"],
    },
    {
        "name": "Wobbly Hedgehog Syndrome (WHS) - Advanced",
        "name_ja": "ふらつきハリネズミ症候群（WHS）- 進行期",
        "symptoms": {"hind_limb_paralysis", "inability_to_curl", "incontinence", "muscle_wasting", "weight_loss"},
        "description": "Advanced WHS with complete paralysis, muscle atrophy, and inability to curl into a defensive ball. Quality of life assessment needed.",
        "description_ja": "完全麻痺、筋萎縮、防御的な丸まり不能を伴う進行したWHS。生活の質の評価が必要です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "quality_of_life_assessment", "physical_exam"],
    },
    {
        "name": "Squamous Cell Carcinoma (Oral) - Advanced",
        "name_ja": "扁平上皮癌（口腔）- 進行型",
        "symptoms": {"difficulty_eating", "drooling", "facial_swelling", "foul_breath", "weight_loss"},
        "description": "Advanced oral squamous cell carcinoma with local invasion. Hedgehogs have extremely high cancer rates (~50% of pet hedgehogs develop tumours).",
        "description_ja": "局所浸潤を伴う進行した口腔扁平上皮癌。ハリネズミは非常に高い癌発生率を持ちます（ペットハリネズミの約50%が腫瘍を発症）。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_xray", "biopsy"],
    },
    {
        "name": "Mammary Adenocarcinoma",
        "name_ja": "乳腺腺癌",
        "symptoms": {"bloody_discharge_from_mass", "lethargy", "mammary_mass", "ulceration", "weight_loss"},
        "description": "Malignant mammary tumour common in female hedgehogs. High metastatic rate to lungs and lymph nodes.",
        "description_ja": "雌ハリネズミに一般的な悪性乳腺腫瘍。肺とリンパ節への高い転移率があります。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "chest_xray", "abdominal_ultrasound"],
    },
    {
        "name": "Uterine Adenocarcinoma - Metastatic",
        "name_ja": "子宮腺癌 - 転移性",
        "symptoms": {"abdominal_distension", "lethargy", "respiratory_distress", "vaginal_bleeding", "weight_loss"},
        "description": "Advanced uterine cancer with metastasis to lungs, liver, or other organs. Very common in intact females over 3 years.",
        "description_ja": "肺、肝臓、他の臓器への転移を伴う進行した子宮癌。3歳以上の未避妊雌に非常に多いです。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Ovarian Granulosa Cell Tumor",
        "name_ja": "卵巣顆粒膜細胞腫",
        "symptoms": {"abdominal_distension", "hair_loss", "lethargy", "vaginal_discharge"},
        "description": "Hormone-producing ovarian tumour causing endometrial changes and potentially abdominal effusion.",
        "description_ja": "ホルモン産生性卵巣腫瘍で、子宮内膜変化と腹水の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "hormone_panel", "physical_exam"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "limb_swelling", "pain", "pathological_fracture", "weight_loss"},
        "description": "Malignant bone tumour relatively common in hedgehogs. Poor prognosis with high metastatic potential.",
        "description_ja": "ハリネズミに比較的多い悪性骨腫瘍。高い転移能を持ち予後不良です。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "chest_xray", "biopsy"],
    },
    {
        "name": "Cutaneous Mast Cell Tumor",
        "name_ja": "皮膚肥満細胞腫",
        "symptoms": {"pruritus", "skin_masses", "skin_redness", "ulceration"},
        "description": "Mast cell neoplasia of the skin, which may release histamine causing local and systemic effects.",
        "description_ja": "皮膚の肥満細胞腫瘍で、ヒスタミンを放出し局所的・全身的影響を引き起こすことがあります。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "histopathology"],
    },
    {
        "name": "Intestinal Leiomyosarcoma",
        "name_ja": "腸管平滑筋肉腫",
        "symptoms": {"abdominal_mass", "appetite_loss", "bloody_stool", "diarrhea", "weight_loss"},
        "description": "Malignant smooth muscle tumour of the intestinal wall causing obstruction, haemorrhage, and metastasis.",
        "description_ja": "腸壁の悪性平滑筋腫瘍で、閉塞、出血、転移を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "biopsy", "chest_xray"],
    },
    {
        "name": "Splenic Hemangiosarcoma",
        "name_ja": "脾臓血管肉腫",
        "symptoms": {"abdominal_distension", "pale_gums", "rapid_breathing", "sudden_collapse", "weakness"},
        "description": "Highly malignant vascular tumour of the spleen that may rupture causing fatal internal haemorrhage.",
        "description_ja": "脾臓の高度悪性血管腫瘍で、破裂すると致死的な内部出血を引き起こす可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "cbc", "blood_chemistry"],
    },
    {
        "name": "Hepatic Hemangiosarcoma",
        "name_ja": "肝臓血管肉腫",
        "symptoms": {"abdominal_distension", "jaundice", "lethargy", "sudden_collapse", "weight_loss"},
        "description": "Malignant vascular tumour of the liver with high risk of metastasis and haemoabdomen.",
        "description_ja": "転移と血液腹のリスクが高い肝臓の悪性血管腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["liver_ultrasound", "blood_chemistry", "cbc"],
    },
    {
        "name": "Pituitary Adenoma",
        "name_ja": "下垂体腺腫",
        "symptoms": {"circling", "head_pressing", "lethargy", "neurological_signs", "vision_loss"},
        "description": "Benign pituitary tumour causing neurological signs from compression of surrounding brain tissue.",
        "description_ja": "周囲の脳組織の圧迫により神経症状を引き起こす良性下垂体腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "mri", "blood_chemistry"],
    },
    {
        "name": "Hibernation Attempt - Severe",
        "name_ja": "冬眠試行 - 重症型",
        "symptoms": {"cold_body", "cool_belly", "curled_tightly", "unresponsiveness", "very_slow_breathing"},
        "description": "African pygmy hedgehogs cannot truly hibernate and hypothermic torpor is life-threatening. Body temperature drops dangerously low.",
        "description_ja": "アフリカンピグミーハリネズミは真の冬眠ができず、低体温性嗜眠は生命を脅かします。体温が危険なほど低下します。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "blood_glucose", "physical_exam"],
    },
    {
        "name": "Caparinia Mange (Severe)",
        "name_ja": "カパリニアダニ症（重症型）",
        "symptoms": {"pruritus", "severe_quill_loss", "skin_flaking", "thick_crusting", "weight_loss"},
        "description": "Heavy Caparinia tripilis mite infestation causing extensive quill loss, thick crusts, and secondary bacterial infection.",
        "description_ja": "カパリニア・トリピリスの重度寄生で、広範な針の脱落、厚い痂皮、二次細菌感染を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    {
        "name": "Quill Mites (Chorioptes)",
        "name_ja": "針ダニ（コリオプテス）",
        "symptoms": {"dandruff", "dry_flaky_skin", "mild_itching", "quill_loss"},
        "description": "Surface-dwelling mites causing mild quill loss and flaky skin. Less severe than Caparinia but still requires treatment.",
        "description_ja": "表面寄生性ダニで軽度の針の脱落と鱗屑を引き起こします。カパリニアほど重度ではありませんが治療が必要です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy", "tape_test"],
    },
    {
        "name": "Demodex Mange",
        "name_ja": "ニキビダニ症",
        "symptoms": {"dry_skin", "quill_loss", "skin_lesions", "skin_thickening"},
        "description": "Demodex mite infestation causing localized or generalized skin disease and quill loss.",
        "description_ja": "ニキビダニの寄生による限局性または全身性の皮膚疾患と針の脱落です。",
        "urgency": "moderate",
        "recommended_tests": ["deep_skin_scraping", "microscopy", "biopsy"],
    },
    {
        "name": "Dermatophytosis (Severe)",
        "name_ja": "皮膚糸状菌症（重症型）",
        "symptoms": {"crusting_skin", "quill_base_crusting", "quill_loss", "skin_flaking"},
        "description": "Extensive ringworm infection with widespread quill loss, crusty skin, and potential secondary infection. Zoonotic.",
        "description_ja": "広範な針の脱落、痂皮状皮膚、二次感染の可能性を伴う広範な白癬感染。人獣共通感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "wood_lamp", "skin_scraping"],
    },
    {
        "name": "Bacterial Quill Folliculitis",
        "name_ja": "細菌性針毛包炎",
        "symptoms": {"pain", "pustules_at_quill_base", "quill_loss", "swelling_at_quill_base"},
        "description": "Bacterial infection of quill follicles causing quill loss and painful pustules at the base of quills.",
        "description_ja": "針毛包の細菌感染で、針の脱落と針基部の有痛性膿疱を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "cytology", "physical_exam"],
    },
    {
        "name": "Allergic Dermatitis",
        "name_ja": "アレルギー性皮膚炎",
        "symptoms": {"dry_skin", "pruritus", "quill_loss", "skin_redness"},
        "description": "Allergic skin reaction to bedding materials (cedar, pine), cleaning products, or food ingredients.",
        "description_ja": "床材（杉、松）、洗浄剤、食品成分に対するアレルギー性皮膚反応です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "skin_scraping", "environmental_review"],
    },
    {
        "name": "Mycobacterium avium Infection",
        "name_ja": "マイコバクテリウム・アビウム感染症",
        "symptoms": {"diarrhea", "lethargy", "lymph_node_swelling", "respiratory_distress", "weight_loss"},
        "description": "Systemic infection by M. avium complex causing disseminated granulomatous disease. Often fatal.",
        "description_ja": "M.アビウムコンプレックスによる全身性感染で、播種性肉芽腫性疾患を引き起こします。しばしば致死的です。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "culture", "biopsy"],
    },
    {
        "name": "Salmonellosis - Asymptomatic Carrier",
        "name_ja": "サルモネラ症 - 無症候性キャリア",
        "symptoms": {"no_obvious_symptoms"},
        "description": "Hedgehogs may carry Salmonella without clinical signs, posing zoonotic risk to owners, especially immunocompromised individuals.",
        "description_ja": "ハリネズミは臨床症状なくサルモネラを保菌し、特に免疫不全の飼い主に人獣共通感染症のリスクがあります。",
        "urgency": "low",
        "recommended_tests": ["fecal_culture", "physical_exam"],
    },
    {
        "name": "Staphylococcal Dermatitis",
        "name_ja": "ブドウ球菌性皮膚炎",
        "symptoms": {"crusting", "pruritus", "pustules", "quill_loss", "skin_lesions"},
        "description": "Skin infection by Staphylococcus species causing pyoderma and crusting, often secondary to mite damage.",
        "description_ja": "ブドウ球菌属による皮膚感染で、しばしばダニ損傷に続発する膿皮症と痂皮形成です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "cytology", "physical_exam"],
    },
    {
        "name": "Streptococcal Septicemia",
        "name_ja": "レンサ球菌敗血症",
        "symptoms": {"anorexia", "fever", "lethargy", "rapid_breathing", "sudden_death"},
        "description": "Acute systemic Streptococcus infection causing septicemia and multi-organ failure.",
        "description_ja": "急性全身性レンサ球菌感染で、敗血症と多臓器不全を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "cbc", "blood_chemistry"],
    },
    {
        "name": "Aspiration Pneumonia",
        "name_ja": "誤嚥性肺炎",
        "symptoms": {"coughing", "fever", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Pneumonia from aspiration of food or oral secretions, often during force-feeding or from dental disease.",
        "description_ja": "強制給餌時や歯科疾患による食物や口腔分泌物の誤嚥による肺炎です。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "tracheal_wash", "culture_sensitivity"],
    },
    {
        "name": "Verminous Pneumonia (Crenosoma)",
        "name_ja": "虫性肺炎（クレノソーマ）",
        "symptoms": {"coughing", "lethargy", "nasal_discharge", "respiratory_distress", "weight_loss"},
        "description": "Lungworm infection by Crenosoma striatum causing chronic cough and progressive respiratory disease in hedgehogs.",
        "description_ja": "クレノソーマ・ストリアタムによる肺虫感染で、ハリネズミに慢性咳と進行性呼吸器疾患を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["fecal_baermann", "chest_xray", "tracheal_wash"],
    },
    {
        "name": "Capillaria Hepatica Infection",
        "name_ja": "カピラリア・ヘパティカ感染",
        "symptoms": {"abdominal_distension", "jaundice", "lethargy", "weight_loss"},
        "description": "Hepatic nematode infection causing granulomatous hepatitis and progressive liver failure.",
        "description_ja": "肝臓の線虫感染で、肉芽腫性肝炎と進行性肝不全を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["liver_biopsy", "blood_chemistry", "liver_ultrasound"],
    },
    {
        "name": "Fluke Infection (Brachylaemus)",
        "name_ja": "吸虫感染（ブラキレムス）",
        "symptoms": {"diarrhea", "lethargy", "poor_appetite", "weight_loss"},
        "description": "Intestinal fluke infection from ingestion of infected slugs or snails. Causes chronic intestinal inflammation.",
        "description_ja": "感染したナメクジやカタツムリの摂取による腸管吸虫感染。慢性的な腸管炎症を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_sedimentation", "physical_exam"],
    },
    {
        "name": "Thorny-Headed Worm Infection",
        "name_ja": "鉤頭虫感染",
        "symptoms": {"bloody_stool", "diarrhea", "lethargy", "weight_loss"},
        "description": "Infection by acanthocephalan parasites causing intestinal wall damage and inflammation.",
        "description_ja": "鉤頭虫による感染で、腸壁損傷と炎症を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Giardiasis",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "poor_appetite", "soft_stool", "weight_loss"},
        "description": "Protozoal infection by Giardia species causing chronic diarrhea and malabsorption.",
        "description_ja": "ジアルジア属による原虫感染で、慢性下痢と吸収不良を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_antigen_test", "physical_exam"],
    },
    {
        "name": "Renal Amyloidosis",
        "name_ja": "腎アミロイドーシス",
        "symptoms": {"edema", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Amyloid protein deposition in the kidneys causing progressive renal failure. Common in older hedgehogs.",
        "description_ja": "腎臓へのアミロイドタンパク沈着で進行性腎不全を引き起こします。高齢ハリネズミに多いです。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_biopsy"],
    },
    {
        "name": "Nephrolithiasis",
        "name_ja": "腎結石症",
        "symptoms": {"appetite_loss", "blood_in_urine", "lethargy", "straining_to_urinate"},
        "description": "Formation of calculi in the kidneys causing pain, obstruction, and potential renal damage.",
        "description_ja": "腎臓内の結石形成で、痛み、閉塞、腎障害の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "renal_ultrasound", "urinalysis"],
    },
    {
        "name": "Pyelonephritis",
        "name_ja": "腎盂腎炎",
        "symptoms": {"appetite_loss", "back_pain", "blood_in_urine", "fever", "lethargy"},
        "description": "Ascending bacterial infection of the kidney from lower urinary tract disease.",
        "description_ja": "下部尿路疾患からの上行性腎臓細菌感染です。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "urine_culture", "renal_ultrasound"],
    },
    {
        "name": "Urethral Obstruction",
        "name_ja": "尿道閉塞",
        "symptoms": {"abdominal_distension", "lethargy", "straining_to_urinate", "vocalization"},
        "description": "Complete or partial blockage of the urethra by calculi or mucus plugs. Life-threatening if complete.",
        "description_ja": "結石や粘液栓による尿道の完全または部分的閉塞。完全閉塞は生命を脅かします。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "abdominal_xray", "urinalysis"],
    },
    {
        "name": "Pregnancy Toxemia",
        "name_ja": "妊娠中毒症",
        "symptoms": {"appetite_loss", "lethargy", "seizures", "sudden_death", "weakness"},
        "description": "Metabolic crisis in late-pregnant hedgehogs from negative energy balance causing hepatic lipidosis and ketosis.",
        "description_ja": "妊娠後期のハリネズミの負のエネルギーバランスによる肝リピドーシスとケトーシスを伴う代謝危機です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Retained Fetus",
        "name_ja": "胎児残留",
        "symptoms": {"abdominal_distension", "fever", "lethargy", "vaginal_discharge"},
        "description": "Failure to deliver all hoglets during birth, leading to infection and toxaemia.",
        "description_ja": "分娩時にすべての子を排出できない状態で、感染と毒血症に至ります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Neonatal Mortality / Cannibalism",
        "name_ja": "新生児死亡/食殺",
        "symptoms": {"blood_in_nest", "maternal_stress", "missing_hoglets"},
        "description": "Death or consumption of newborn hoglets by the mother, triggered by stress, disturbance, or inadequate nutrition.",
        "description_ja": "ストレス、妨害、栄養不足により母親による新生児の死亡または食殺です。",
        "urgency": "moderate",
        "recommended_tests": ["environmental_review", "nutritional_assessment"],
    },
    {
        "name": "Orchitis",
        "name_ja": "精巣炎",
        "symptoms": {"fever", "lethargy", "pain", "testicular_swelling"},
        "description": "Inflammation or infection of the testes, which may become abscessed.",
        "description_ja": "精巣の炎症または感染で、膿瘍化することがあります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "scrotal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Testicular Neoplasia",
        "name_ja": "精巣腫瘍",
        "symptoms": {"abdominal_distension", "asymmetric_testes", "testicular_enlargement"},
        "description": "Tumour of the testicle including seminoma, Sertoli cell tumour, and interstitial cell tumour.",
        "description_ja": "セミノーマ、セルトリ細胞腫、間質細胞腫を含む精巣の腫瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["scrotal_ultrasound", "fine_needle_aspirate", "physical_exam"],
    },
    {
        "name": "Penile Necrosis",
        "name_ja": "陰茎壊死",
        "symptoms": {"foul_odor", "lethargy", "penile_discoloration", "straining_to_urinate"},
        "description": "Necrosis of the penis from chronic paraphimosis, constrictive bands, or vascular compromise.",
        "description_ja": "慢性嵌頓包茎、締め付け帯、血管障害による陰茎の壊死です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "urinalysis", "blood_chemistry"],
    },
    {
        "name": "Dilated Cardiomyopathy - Advanced",
        "name_ja": "拡張型心筋症 - 進行型",
        "symptoms": {"ascites", "collapse", "cyanosis", "exercise_intolerance", "respiratory_distress"},
        "description": "End-stage dilated cardiomyopathy with severe heart failure, ascites, and pulmonary oedema.",
        "description_ja": "重度の心不全、腹水、肺水腫を伴う末期拡張型心筋症です。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Valvular Heart Disease",
        "name_ja": "弁膜性心疾患",
        "symptoms": {"coughing", "exercise_intolerance", "heart_murmur", "lethargy"},
        "description": "Degeneration or insufficiency of heart valves causing abnormal blood flow and progressive heart failure.",
        "description_ja": "心臓弁の変性または不全で、異常な血流と進行性心不全を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["echocardiography", "chest_xray", "physical_exam"],
    },
    {
        "name": "Hepatic Lipidosis (Obesity-Related)",
        "name_ja": "肝リピドーシス（肥満関連）",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "obesity"},
        "description": "Fatty liver disease secondary to obesity, extremely common in captive hedgehogs fed inappropriate diets.",
        "description_ja": "肥満に続発する脂肪肝で、不適切な食事を与えられた飼育下ハリネズミに非常に多いです。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_ultrasound", "physical_exam"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"cataracts", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Insulin deficiency or resistance causing hyperglycaemia. Often associated with obesity in pet hedgehogs.",
        "description_ja": "インスリン欠乏または抵抗性による高血糖。ペットハリネズミでは肥満に関連することが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["blood_glucose", "fructosamine", "urinalysis"],
    },
    {
        "name": "Hypothyroidism",
        "name_ja": "甲状腺機能低下症",
        "symptoms": {"cold_intolerance", "constipation", "lethargy", "obesity", "poor_coat"},
        "description": "Reduced thyroid hormone production causing metabolic slowdown and weight gain.",
        "description_ja": "甲状腺ホルモン産生の低下による代謝低下と体重増加です。",
        "urgency": "low",
        "recommended_tests": ["thyroid_panel", "blood_chemistry", "physical_exam"],
    },
    {
        "name": "Obesity (Severe / Morbid)",
        "name_ja": "肥満（重度/病的）",
        "symptoms": {"exercise_intolerance", "hepatic_lipidosis_signs", "inability_to_curl", "skin_folds"},
        "description": "Severe obesity preventing normal behaviour (curling, running). Leads to hepatic lipidosis and shortened lifespan.",
        "description_ja": "正常な行動（丸まり、走行）を妨げる重度の肥満。肝リピドーシスと寿命短縮につながります。",
        "urgency": "moderate",
        "recommended_tests": ["body_condition_score", "blood_chemistry", "diet_review"],
    },
    {
        "name": "Gastric Dilation / Bloat",
        "name_ja": "胃拡張/鼓脹症",
        "symptoms": {"abdominal_distension", "collapse", "lethargy", "pain", "rapid_breathing"},
        "description": "Acute distension of the stomach with gas or fluid. Rapidly fatal if not treated.",
        "description_ja": "ガスや液体による胃の急性拡張。治療しないと急速に致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Intestinal Intussusception",
        "name_ja": "腸重積症",
        "symptoms": {"abdominal_pain", "bloody_stool", "dehydration", "lethargy", "vomiting"},
        "description": "Telescoping of one segment of intestine into another, causing obstruction and ischemia.",
        "description_ja": "腸の一部が別の部分に陥入し、閉塞と虚血を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray", "physical_exam"],
    },
    {
        "name": "Intestinal Foreign Body",
        "name_ja": "腸管異物",
        "symptoms": {"abdominal_pain", "appetite_loss", "lethargy", "reduced_fecal_output", "vomiting"},
        "description": "Ingestion of non-digestible objects (rubber, fabric, plastic) causing intestinal obstruction.",
        "description_ja": "ゴム、布、プラスチックなどの非消化性物質の摂取による腸閉塞です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Pancreatitis",
        "name_ja": "膵炎",
        "symptoms": {"abdominal_pain", "appetite_loss", "diarrhea", "lethargy", "vomiting"},
        "description": "Inflammation of the pancreas, often associated with high-fat diets in captive hedgehogs.",
        "description_ja": "膵臓の炎症で、飼育下ハリネズミでは高脂肪食に関連することが多いです。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "lipase_level", "abdominal_ultrasound"],
    },
    {
        "name": "Dental Fracture",
        "name_ja": "歯の骨折",
        "symptoms": {"appetite_loss", "difficulty_eating", "drooling", "face_rubbing"},
        "description": "Fracture of a tooth from trauma or chewing hard objects, potentially exposing the pulp cavity.",
        "description_ja": "外傷や硬い物を噛むことによる歯の骨折で、歯髄腔が露出する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "skull_xray", "oral_exam"],
    },
    {
        "name": "Eye Abscess (Retrobulbar)",
        "name_ja": "眼膿瘍（後眼窩）",
        "symptoms": {"appetite_loss", "exophthalmos", "eye_discharge", "facial_swelling"},
        "description": "Abscess behind the eye causing progressive proptosis, often secondary to dental disease.",
        "description_ja": "歯科疾患に続発することが多い眼球後方の膿瘍で、進行性の眼球突出を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "orbital_ultrasound", "dental_exam"],
    },
    {
        "name": "Corneal Laceration",
        "name_ja": "角膜裂傷",
        "symptoms": {"corneal_opacity", "eye_discharge", "pain", "squinting", "vision_loss"},
        "description": "Traumatic cut or tear of the cornea from quill injury, cage wire, or sharp objects.",
        "description_ja": "針、ケージのワイヤー、鋭利な物による角膜の外傷性切傷または裂傷です。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam", "physical_exam"],
    },
    {
        "name": "Glaucoma",
        "name_ja": "緑内障",
        "symptoms": {"enlarged_eye", "eye_pain", "eye_redness", "vision_loss"},
        "description": "Increased intraocular pressure causing optic nerve damage and progressive vision loss.",
        "description_ja": "眼内圧の上昇による視神経損傷と進行性視力喪失です。",
        "urgency": "high",
        "recommended_tests": ["tonometry", "ophthalmic_exam", "physical_exam"],
    },
    {
        "name": "Toxicosis (Cleaning Products)",
        "name_ja": "中毒症（洗浄剤）",
        "symptoms": {"drooling", "lethargy", "respiratory_distress", "seizures", "skin_irritation"},
        "description": "Poisoning from exposure to cleaning products, pesticides, or other household chemicals.",
        "description_ja": "洗浄剤、殺虫剤、その他の家庭用化学物質への暴露による中毒です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Spinal Fracture",
        "name_ja": "脊椎骨折",
        "symptoms": {"hind_limb_paralysis", "inability_to_curl", "incontinence", "pain"},
        "description": "Fracture of vertebral bones from falls or crush injuries causing spinal cord damage.",
        "description_ja": "落下や圧迫損傷による椎骨の骨折で、脊髄損傷を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["spinal_xray", "neurological_exam", "physical_exam"],
    },
    {
        "name": "Digit Amputation Wound",
        "name_ja": "指切断創",
        "symptoms": {"bleeding", "limping", "missing_toe", "wound_infection"},
        "description": "Traumatic loss of a toe from thread wrapping, cage wire entrapment, or wheel injuries. Common in hedgehogs.",
        "description_ja": "糸の巻き付き、ケージワイヤーの絡まり、回し車の怪我による指の外傷性喪失。ハリネズミに多いです。",
        "urgency": "high",
        "recommended_tests": ["foot_xray", "wound_assessment", "physical_exam"],
    },
    {
        "name": "Thread / Hair Tourniquet (Toe)",
        "name_ja": "糸/毛の締め付け（指）",
        "symptoms": {"limping", "swollen_toe", "toe_discoloration", "toe_necrosis"},
        "description": "Constriction of a toe by thread, hair, or fibre cutting off blood supply. Requires emergency removal.",
        "description_ja": "糸、毛、繊維による指の締め付けで血液供給が遮断されます。緊急除去が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "foot_exam"],
    },
    {
        "name": "Hepatic Neoplasia (General)",
        "name_ja": "肝臓腫瘍（一般）",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Various liver tumours including hepatocellular adenoma, cholangiocarcinoma, and metastatic disease.",
        "description_ja": "肝細胞腺腫、胆管癌、転移性疾患を含む様々な肝臓腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["liver_ultrasound", "blood_chemistry", "fine_needle_aspirate"],
    },
    {
        "name": "Adrenal Cortical Tumor",
        "name_ja": "副腎皮質腫瘍",
        "symptoms": {"hair_loss", "polydipsia", "polyuria", "skin_thinning", "weight_gain"},
        "description": "Neoplasia of the adrenal cortex causing Cushing's-like signs from excess cortisol production.",
        "description_ja": "過剰コルチゾール産生によるクッシング様徴候を引き起こす副腎皮質の腫瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Interstitial Nephritis",
        "name_ja": "間質性腎炎",
        "symptoms": {"lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Chronic inflammation of the renal interstitium causing progressive kidney damage. Common in aged hedgehogs.",
        "description_ja": "腎間質の慢性炎症で進行性の腎障害を引き起こします。高齢ハリネズミに多いです。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_ultrasound"],
    },
    {
        "name": "Pneumothorax",
        "name_ja": "気胸",
        "symptoms": {"cyanosis", "lethargy", "rapid_breathing", "respiratory_distress"},
        "description": "Air in the pleural space causing lung collapse, from trauma or spontaneous rupture.",
        "description_ja": "外傷または自然破裂による胸腔内の空気で肺虚脱を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["chest_xray", "physical_exam", "thoracocentesis"],
    },
    {
        "name": "Autoimmune Hemolytic Anemia",
        "name_ja": "自己免疫性溶血性貧血",
        "symptoms": {"dark_urine", "jaundice", "lethargy", "pale_mucous_membranes", "weakness"},
        "description": "Immune-mediated destruction of red blood cells causing acute anaemia and jaundice.",
        "description_ja": "免疫介在性の赤血球破壊で急性貧血と黄疸を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["cbc", "coombs_test", "blood_chemistry"],
    },
    {
        "name": "Chordoma (Spinal)",
        "name_ja": "脊索腫（脊椎）",
        "symptoms": {"hind_limb_weakness", "incontinence", "pain", "tail_mass"},
        "description": "Rare tumour arising from notochordal remnants, typically at the tail base or sacral region.",
        "description_ja": "脊索遺残から発生する稀な腫瘍で、通常尾の基部または仙骨部に発生します。",
        "urgency": "moderate",
        "recommended_tests": ["spinal_xray", "biopsy", "mri"],
    },
]


SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # Dermatological symptoms
    "quill_loss": {"ja": "針の脱落", "en": "Quill loss"},
    "new_quill_growth": {"ja": "新しい針の成長", "en": "New quill growth"},
    "scratching": {"ja": "掻痒・引っ掻き", "en": "Scratching"},
    "flaky_skin": {"ja": "皮膚の剥離・フケ", "en": "Flaky skin"},
    "crusting": {"ja": "痂皮形成", "en": "Crusting"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "skin_mass": {"ja": "皮膚の腫瘤", "en": "Skin mass"},
    "ulcerated_lesion": {"ja": "潰瘍性病変", "en": "Ulcerated lesion"},
    "redness": {"ja": "発赤", "en": "Redness"},
    "alopecia": {"ja": "脱毛", "en": "Hair / quill loss (alopecia)"},
    "dull_quills": {"ja": "針のつやの喪失", "en": "Dull quills"},
    "irritability": {"ja": "易刺激性", "en": "Irritability"},
    # General / systemic
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite loss"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "pain": {"ja": "疼痛", "en": "Pain"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "discharge": {"ja": "分泌物", "en": "Discharge"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    "distress": {"ja": "苦悶", "en": "Distress"},
    "crying": {"ja": "鳴き声（痛み）", "en": "Crying / vocalizing in pain"},
    "decreased_activity": {"ja": "活動性の低下", "en": "Decreased activity"},
    # GI symptoms
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "mucoid_stool": {"ja": "粘液便", "en": "Mucoid stool"},
    "green_stool": {"ja": "緑色便", "en": "Green stool"},
    "visible_worms_in_stool": {"ja": "便中の虫体", "en": "Visible worms in stool"},
    "bloating": {"ja": "腹部膨満", "en": "Bloating"},
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal pain"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "straining_to_defecate": {"ja": "排便時のいきみ", "en": "Straining to defecate"},
    "tissue_protruding_from_anus": {"ja": "肛門からの組織脱出", "en": "Tissue protruding from anus"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "hepatomegaly": {"ja": "肝腫大", "en": "Hepatomegaly"},
    # Oral / dental
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "bad_breath": {"ja": "口臭", "en": "Bad breath"},
    "tartar_buildup": {"ja": "歯石の蓄積", "en": "Tartar buildup"},
    "tooth_loss": {"ja": "歯の脱落", "en": "Tooth loss"},
    "red_gums": {"ja": "歯肉の発赤", "en": "Red gums"},
    "oral_mass": {"ja": "口腔内の腫瘤", "en": "Oral mass"},
    "bloody_mouth": {"ja": "口腔内出血", "en": "Bloody mouth"},
    "facial_swelling": {"ja": "顔面の腫脹", "en": "Facial swelling"},
    # Respiratory
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal discharge"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    "panting": {"ja": "パンティング", "en": "Panting"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    # Neurological
    "ataxia": {"ja": "運動失調", "en": "Ataxia"},
    "hindlimb_weakness": {"ja": "後肢の脱力", "en": "Hindlimb weakness"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "falling_over": {"ja": "転倒", "en": "Falling over"},
    "progressive_paralysis": {"ja": "進行性麻痺", "en": "Progressive paralysis"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "seizures": {"ja": "てんかん発作", "en": "Seizures"},
    "disorientation": {"ja": "失見当識", "en": "Disorientation"},
    "paddling": {"ja": "遊泳運動", "en": "Paddling"},
    "behavioral_changes": {"ja": "行動変化", "en": "Behavioral changes"},
    # Cardiac
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise intolerance"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    # Musculoskeletal
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "limb_not_bearing_weight": {"ja": "患肢の免荷", "en": "Not bearing weight on limb"},
    "reluctance_to_curl": {"ja": "丸まることへの抵抗", "en": "Reluctance to curl"},
    "inability_to_curl": {"ja": "丸まれない", "en": "Inability to curl into a ball"},
    "swollen_foot": {"ja": "足の腫脹", "en": "Swollen foot"},
    "discolored_toes": {"ja": "趾の変色", "en": "Discolored toes"},
    "fiber_constriction": {"ja": "繊維の絞扼", "en": "Fiber / thread constriction"},
    # Ophthalmological
    "eye_bulging": {"ja": "眼球突出", "en": "Eye bulging / proptosis"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye redness"},
    "eye_squinting": {"ja": "眼の細め", "en": "Eye squinting"},
    "eye_cloudiness": {"ja": "眼の白濁", "en": "Eye cloudiness"},
    "vision_loss": {"ja": "視力低下", "en": "Vision loss"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into objects"},
    # Urinary
    "excessive_thirst": {"ja": "多飲", "en": "Excessive thirst"},
    "excessive_urination": {"ja": "多尿", "en": "Excessive urination"},
    "bloody_urine": {"ja": "血尿", "en": "Bloody urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent urination"},
    "straining_to_urinate": {"ja": "排尿時のいきみ", "en": "Straining to urinate"},
    # Reproductive
    "vaginal_bleeding": {"ja": "膣出血", "en": "Vaginal bleeding"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal discharge"},
    "mammary_mass": {"ja": "乳腺の腫瘤", "en": "Mammary mass"},
    "mammary_discharge": {"ja": "乳腺からの分泌物", "en": "Mammary discharge"},
    "mammary_swelling": {"ja": "乳腺の腫脹", "en": "Mammary swelling"},
    "mammary_redness": {"ja": "乳腺の発赤", "en": "Mammary redness"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "penile_protrusion": {"ja": "陰茎突出", "en": "Penile protrusion"},
    "licking_genital_area": {"ja": "陰部を舐める", "en": "Licking genital area"},
    # Metabolic
    "cold_body": {"ja": "体の冷え", "en": "Cold body"},
    "hot_body": {"ja": "体の過熱", "en": "Hot body"},
    "unresponsiveness": {"ja": "無反応", "en": "Unresponsiveness"},
    "curled_tightly": {"ja": "強く丸まっている", "en": "Curled up tightly"},
    "fatty_deposits": {"ja": "脂肪の蓄積", "en": "Fatty deposits"},
    # Parasitic
    "visible_parasites": {"ja": "目に見える寄生虫", "en": "Visible parasites"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "ear_scratching": {"ja": "耳を掻く", "en": "Ear scratching"},
    "head_shaking": {"ja": "頭を振る", "en": "Head shaking"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear discharge"},
    # Other
    "lymph_node_enlargement": {"ja": "リンパ節腫大", "en": "Lymph node enlargement"},
    "splenomegaly": {"ja": "脾腫", "en": "Splenomegaly"},
    "pale_mucous_membranes": {"ja": "粘膜の蒼白", "en": "Pale mucous membranes"},
    "rapid_growth": {"ja": "急速な成長", "en": "Rapid growth"},
    "slow_growth": {"ja": "緩徐な成長", "en": "Slow growth"},
    "foaming_at_mouth": {"ja": "口の泡立ち", "en": "Foaming at mouth"},
    "contorting_body": {"ja": "体をねじる", "en": "Contorting body"},
    "spreading_saliva": {"ja": "唾液を塗る", "en": "Spreading saliva on quills"},
    "subcutaneous_emphysema": {"ja": "皮下気腫", "en": "Subcutaneous emphysema"},
    "distension": {"ja": "膨張", "en": "Distension"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    """ハリネズミ用の鑑別診断エンジン。

    与えられた症状リストに基づいて候補疾患と推奨検査を返します。

    Args:
        symptoms: ユーザーが報告した症状のリスト
        age_stage: 任意の年齢層情報
        breed: 品種情報（ハリネズミでは通常未使用）

    Returns:
        辞書形式の分析結果
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
