"""Lizard disease dictionary and analysis module.

This module defines a comprehensive list of diseases commonly seen in
captive and wild lizards (Lacertilia / Sauria) including bearded dragons,
leopard geckos, chameleons, iguanas, monitors, and other popular species.
It exposes an ``analyze_symptoms`` function that leverages the generic
species helper to produce differential diagnosis results.

The information provided here is for educational purposes only and should
not replace professional veterinary diagnosis and treatment.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── Metabolic / Nutritional ──────────────────────────────────────────
    {
        "name": "Metabolic Bone Disease (MBD)",
        "name_ja": "代謝性骨疾患（MBD）",
        "symptoms": {"soft_bones", "tremors", "weakness", "lethargy", "fractures", "swollen_limbs", "jaw_softening", "anorexia", "rubber_jaw"},
        "description": "The most common nutritional disorder in captive lizards, caused by calcium deficiency, phosphorus imbalance, or inadequate UVB exposure.",
        "description_ja": "飼育下のトカゲで最も多い栄養性疾患で、カルシウム不足、リン比の不均衡、UVB不足が原因です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "radiographs", "husbandry_review"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism (NSHP)",
        "name_ja": "栄養性二次性副甲状腺機能亢進症",
        "symptoms": {"soft_bones", "tremors", "fractures", "jaw_softening", "weakness", "lethargy", "rubber_jaw"},
        "description": "Chronic calcium deficiency causing parathyroid hormone over-secretion and bone resorption.",
        "description_ja": "慢性的なカルシウム不足により副甲状腺ホルモンが過剰分泌され骨吸収が起こる疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "pth_levels", "radiographs"],
    },
    {
        "name": "Vitamin A Deficiency (Hypovitaminosis A)",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"swollen_eyes", "conjunctivitis", "skin_lesions", "respiratory_distress", "anorexia", "lethargy"},
        "description": "Dietary vitamin A insufficiency causing squamous metaplasia of epithelial tissues.",
        "description_ja": "食事中のビタミンA不足により上皮組織の扁平上皮化生を引き起こす疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_a_levels", "ophthalmic_exam", "dietary_review"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"soft_bones", "weakness", "lethargy", "tremors", "anorexia"},
        "description": "Inadequate UVB exposure or dietary vitamin D3 impairing calcium absorption.",
        "description_ja": "UVB照射不足または食事性ビタミンD3不足によりカルシウム吸収が障害される状態です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_d3", "blood_calcium_phosphorus", "husbandry_review"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"tremors", "muscle_twitching", "seizures", "weakness", "lethargy", "anorexia"},
        "description": "Critically low blood calcium causing neuromuscular dysfunction, especially in gravid females.",
        "description_ja": "特に抱卵中の雌で神経筋機能障害を引き起こす血中カルシウムの著しい低下です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_calcium", "ionized_calcium", "blood_chemistry"],
    },
    {
        "name": "Hypervitaminosis A",
        "name_ja": "ビタミンA過剰症",
        "symptoms": {"skin_lesions", "skin_sloughing", "lethargy", "anorexia"},
        "description": "Toxicity from excessive vitamin A supplementation causing epithelial damage.",
        "description_ja": "ビタミンAの過剰投与により上皮組織の損傷を引き起こす中毒症です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_a_levels", "dietary_review"],
    },
    {
        "name": "Hypervitaminosis D3",
        "name_ja": "ビタミンD3過剰症",
        "symptoms": {"anorexia", "lethargy", "excessive_thirst", "excessive_urination", "weakness"},
        "description": "Over-supplementation of vitamin D3 causing hypercalcemia and soft tissue mineralization.",
        "description_ja": "ビタミンD3の過剰摂取により高カルシウム血症と軟部組織の石灰化を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium", "blood_chemistry", "radiographs"],
    },
    {
        "name": "Chronic Malnutrition",
        "name_ja": "慢性栄養不良",
        "symptoms": {"weight_loss", "weakness", "lethargy", "anorexia", "poor_body_condition"},
        "description": "Long-term inadequate nutrition leading to wasting and immune suppression.",
        "description_ja": "長期的な栄養不足による消耗と免疫抑制です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review", "physical_exam"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"excessive_weight", "fat_deposits", "lethargy", "difficulty_moving"},
        "description": "Excess body fat from overfeeding and insufficient exercise, predisposing to hepatic lipidosis.",
        "description_ja": "過食と運動不足による過剰な体脂肪蓄積で、脂肪肝のリスクがあります。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "body_condition_scoring", "dietary_review"],
    },
    # ── Viral Diseases ───────────────────────────────────────────────────
    {
        "name": "Atadenovirus Infection (ADV)",
        "name_ja": "アタデノウイルス感染症（ADV）",
        "symptoms": {"anorexia", "lethargy", "diarrhea", "neurological_signs", "weight_loss", "liver_enlargement", "sudden_death", "failure_to_thrive"},
        "description": "Extremely common viral infection in bearded dragons causing hepatitis, enteritis, and immunosuppression; often fatal in juveniles.",
        "description_ja": "フトアゴヒゲトカゲに非常に多いウイルス感染症で、肝炎、腸炎、免疫抑制を引き起こし、幼体では致死的です。",
        "urgency": "high",
        "recommended_tests": ["pcr_atadenovirus", "liver_function_tests", "liver_biopsy", "complete_blood_count"],
    },
    {
        "name": "Adenovirus Infection (Non-Atadenovirus)",
        "name_ja": "アデノウイルス感染症（非アタデノ）",
        "symptoms": {"anorexia", "lethargy", "diarrhea", "neurological_signs", "weight_loss"},
        "description": "Adenovirus infection in non-bearded dragon lizard species causing hepatitis and GI disease.",
        "description_ja": "フトアゴヒゲトカゲ以外のトカゲ種で肝炎と消化器疾患を引き起こすアデノウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_adenovirus", "liver_function_tests", "complete_blood_count"],
    },
    {
        "name": "Herpesvirus Infection",
        "name_ja": "ヘルペスウイルス感染症",
        "symptoms": {"mouth_lesions", "stomatitis", "nasal_discharge", "lethargy", "anorexia"},
        "description": "Herpesvirus causing stomatitis, papillomas, or systemic disease in certain lizard species.",
        "description_ja": "特定のトカゲ種で口内炎、乳頭腫、全身性疾患を引き起こすヘルペスウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_herpesvirus", "oral_swab", "biopsy"],
    },
    {
        "name": "Paramyxovirus Infection",
        "name_ja": "パラミクソウイルス感染症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "neurological_signs", "lethargy", "anorexia"},
        "description": "Contagious viral infection causing respiratory and neurological disease in lizards.",
        "description_ja": "トカゲに呼吸器・神経疾患を引き起こす伝染性ウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_paramyxovirus", "radiographs", "complete_blood_count"],
    },
    {
        "name": "Iridovirus / Ranavirus Infection",
        "name_ja": "イリドウイルス・ラナウイルス感染症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "edema", "sudden_death"},
        "description": "Systemic viral disease causing hemorrhagic disease in various lizard species.",
        "description_ja": "各種トカゲに出血性疾患を引き起こす全身性ウイルス疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_ranavirus", "histopathology", "complete_blood_count"],
    },
    # ── Fungal Diseases ──────────────────────────────────────────────────
    {
        "name": "Yellow Fungus Disease (CANV - Chrysosporium anamorph of Nannizziopsis vriesii)",
        "name_ja": "黄色真菌症（CANV）",
        "symptoms": {"yellow_skin_patches", "skin_lesions", "crusty_patches", "dysecdysis", "anorexia", "lethargy", "skin_necrosis"},
        "description": "Highly aggressive and often fatal fungal infection primarily affecting bearded dragons, causing deep dermal necrosis.",
        "description_ja": "主にフトアゴヒゲトカゲに影響する高侵攻性で致死的な真菌感染症で、深部皮膚壊死を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["fungal_culture", "skin_biopsy", "pcr_canv", "histopathology"],
    },
    {
        "name": "Dermatophytosis (Fungal Skin Infection)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"skin_lesions", "scale_discoloration", "dysecdysis", "crusty_patches"},
        "description": "Superficial fungal infection of the skin by dermatophyte organisms.",
        "description_ja": "皮膚糸状菌による皮膚の表在性真菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "skin_biopsy"],
    },
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "weight_loss"},
        "description": "Fungal infection by Aspergillus spp. affecting the respiratory tract.",
        "description_ja": "アスペルギルス属真菌による呼吸器の真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "radiographs", "tracheal_wash"],
    },
    # ── Respiratory ──────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection (URI)",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"nasal_discharge", "wheezing", "open_mouth_breathing", "lethargy", "anorexia"},
        "description": "Bacterial or viral infection of the nasal passages and upper airways, commonly linked to low temperatures.",
        "description_ja": "低温環境に関連する鼻腔・上気道の細菌・ウイルス感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "culture_sensitivity", "physical_exam"],
    },
    {
        "name": "Pneumonia (Lower Respiratory Infection)",
        "name_ja": "肺炎（下部呼吸器感染症）",
        "symptoms": {"open_mouth_breathing", "respiratory_distress", "wheezing", "nasal_discharge", "lethargy", "anorexia", "mucus_in_mouth"},
        "description": "Bacterial or fungal lung infection, potentially life-threatening if untreated.",
        "description_ja": "未治療の場合に生命を脅かす可能性のある肺の細菌・真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "tracheal_wash", "culture_sensitivity", "complete_blood_count"],
    },
    # ── Oral / Stomatitis ────────────────────────────────────────────────
    {
        "name": "Infectious Stomatitis (Mouth Rot)",
        "name_ja": "感染性口内炎（マウスロット）",
        "symptoms": {"mouth_lesions", "swollen_gums", "mucus_in_mouth", "anorexia", "drooling", "oral_hemorrhage"},
        "description": "Bacterial infection of the oral cavity causing caseous exudate, gum swelling, and tissue necrosis.",
        "description_ja": "口腔の細菌感染により乾酪性浸出液、歯肉腫脹、組織壊死を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Periodontal Disease",
        "name_ja": "歯周病",
        "symptoms": {"swollen_gums", "mouth_lesions", "anorexia", "facial_swelling"},
        "description": "Inflammation and infection of the tissues surrounding the teeth, especially in acrodont species (bearded dragons, chameleons).",
        "description_ja": "特にアクロドント種（フトアゴヒゲトカゲ、カメレオン）で歯の周囲組織に炎症・感染が起こる疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "radiographs", "culture_sensitivity"],
    },
    # ── Parasitic ────────────────────────────────────────────────────────
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "lethargy", "bloody_stool"},
        "description": "Protozoal infection by Isospora or Eimeria species, extremely common in bearded dragons.",
        "description_ja": "フトアゴヒゲトカゲに非常に多いイソスポラ属やアイメリア属原虫による感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Pinworm (Oxyurid) Infection",
        "name_ja": "蟯虫感染",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "straining"},
        "description": "Common oxyurid nematode infection in herbivorous and omnivorous lizards.",
        "description_ja": "草食性・雑食性トカゲに多い蟯虫の感染症です。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"weight_loss", "anorexia", "lethargy", "diarrhea", "dehydration", "body_swelling"},
        "description": "Chronic protozoal infection by Cryptosporidium spp. causing wasting, especially in leopard geckos.",
        "description_ja": "特にヒョウモントカゲモドキで消耗を引き起こすクリプトスポリジウム属原虫の慢性感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_cryptosporidium", "acid_fast_stain", "gastric_biopsy"],
    },
    {
        "name": "Mite Infestation (Ectoparasites)",
        "name_ja": "ダニ寄生（外部寄生虫）",
        "symptoms": {"skin_irritation", "visible_mites", "dysecdysis", "lethargy", "anorexia", "excessive_soaking"},
        "description": "External mite infestation causing irritation and potential disease transmission.",
        "description_ja": "刺激と疾病伝播リスクを伴う外部寄生ダニの感染です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_scraping", "mite_identification"],
    },
    {
        "name": "Internal Nematodes (Roundworms)",
        "name_ja": "内部線虫（回虫）感染",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "lethargy"},
        "description": "Gastrointestinal roundworm infection including ascarids and strongylids.",
        "description_ja": "回虫類や円虫類による消化管の線虫感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam", "complete_blood_count"],
    },
    {
        "name": "Amoebic Infection (Entamoeba)",
        "name_ja": "アメーバ感染症",
        "symptoms": {"diarrhea", "bloody_stool", "anorexia", "weight_loss", "lethargy"},
        "description": "Pathogenic amoebic infection causing colitis, especially in herbivorous lizards.",
        "description_ja": "特に草食性トカゲで大腸炎を引き起こす病原性アメーバ感染症です。",
        "urgency": "high",
        "recommended_tests": ["fecal_wet_mount", "pcr_entamoeba", "fecal_exam"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "マダニ寄生",
        "symptoms": {"visible_parasites", "skin_lesions", "anorexia", "lethargy"},
        "description": "External tick parasitism, more common in wild-caught specimens.",
        "description_ja": "野生捕獲個体に多い外部マダニ寄生です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "tick_identification"],
    },
    {
        "name": "Myiasis (Fly Strike)",
        "name_ja": "蝿蛆症",
        "symptoms": {"skin_lesions", "visible_larvae", "foul_odor", "lethargy", "anorexia"},
        "description": "Fly larval infestation of open wounds or soiled skin areas.",
        "description_ja": "開放創や汚れた皮膚にハエの幼虫が寄生する疾患です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment"],
    },
    # ── Skin / Integument ────────────────────────────────────────────────
    {
        "name": "Dysecdysis (Retained Shed)",
        "name_ja": "脱皮不全",
        "symptoms": {"dysecdysis", "retained_skin", "skin_constriction", "lethargy", "anorexia"},
        "description": "Incomplete shedding caused by low humidity, dehydration, or underlying disease; can cause digit and tail necrosis.",
        "description_ja": "低湿度、脱水、基礎疾患による不完全な脱皮で、指や尾の壊死を引き起こす可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review", "skin_exam"],
    },
    {
        "name": "Toe Necrosis from Retained Shed",
        "name_ja": "脱皮残りによる趾壊死",
        "symptoms": {"toe_discoloration", "toe_swelling", "skin_constriction", "lameness"},
        "description": "Ischemic necrosis of toes from circumferential constriction by retained shed skin.",
        "description_ja": "脱皮残りの皮膚による環状絞扼で趾が虚血性壊死を起こす状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    {
        "name": "Tail Autotomy Infection",
        "name_ja": "自切部位感染",
        "symptoms": {"tail_wound", "swelling", "foul_odor", "anorexia", "lethargy"},
        "description": "Bacterial infection at the site of tail autotomy (self-amputation), preventing proper regeneration.",
        "description_ja": "尾の自切（自己切断）部位の細菌感染で、適切な再生を妨げます。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "culture_sensitivity", "physical_exam"],
    },
    {
        "name": "Thermal Burns",
        "name_ja": "熱傷",
        "symptoms": {"skin_burns", "skin_lesions", "blisters", "scale_discoloration", "anorexia", "lethargy"},
        "description": "Burns from direct contact with unregulated heat sources such as heat rocks and ceramic heaters.",
        "description_ja": "ヒートロック、セラミックヒーターなどとの直接接触による火傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    {
        "name": "Scale Rot (Ulcerative Dermatitis)",
        "name_ja": "スケイルロット（潰瘍性皮膚炎）",
        "symptoms": {"scale_discoloration", "skin_lesions", "foul_odor", "blisters", "skin_necrosis"},
        "description": "Bacterial skin infection from prolonged contact with damp, soiled substrate.",
        "description_ja": "湿った不衛生な床材との長期接触による皮膚の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "skin_biopsy", "husbandry_review"],
    },
    {
        "name": "Bacterial Dermatitis",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_lesions", "skin_redness", "swelling", "foul_odor", "lethargy"},
        "description": "Bacterial skin infection causing inflammation and potential ulceration.",
        "description_ja": "炎症と潰瘍化の可能性を伴う皮膚の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Subcutaneous Abscess",
        "name_ja": "皮下膿瘍",
        "symptoms": {"swelling", "firm_mass", "anorexia", "lethargy"},
        "description": "Encapsulated caseous abscess under the skin, common in lizards.",
        "description_ja": "トカゲに多い皮膚下の被包化された乾酪性膿瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "radiographs"],
    },
    {
        "name": "Rostral Abrasion (Nose Rub)",
        "name_ja": "吻部擦過傷（ノーズラブ）",
        "symptoms": {"nose_abrasion", "facial_swelling", "skin_lesions"},
        "description": "Snout abrasion from rubbing against enclosure walls, common in iguanas and monitors.",
        "description_ja": "イグアナやオオトカゲに多いケージ壁面への擦り付けによる吻部の擦過傷です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    # ── Gastrointestinal ─────────────────────────────────────────────────
    {
        "name": "Gastrointestinal Impaction (Substrate Impaction)",
        "name_ja": "消化管閉塞（床材インパクション）",
        "symptoms": {"anorexia", "constipation", "lethargy", "abdominal_swelling", "straining"},
        "description": "GI blockage from ingested loose substrate (sand, walnut shell, gravel), very common in bearded dragons.",
        "description_ja": "砂、ウォルナットシェル、砂利などの床材摂取による消化管閉塞で、フトアゴヒゲトカゲに非常に多いです。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam", "ultrasound"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物誤飲",
        "symptoms": {"anorexia", "regurgitation", "abdominal_swelling", "lethargy", "constipation"},
        "description": "Ingestion of non-food items such as decorations, substrate, or enrichment objects.",
        "description_ja": "装飾品、床材、エンリッチメント用品などの非食品の誤飲です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "contrast_study"],
    },
    {
        "name": "Gastroenteritis",
        "name_ja": "胃腸炎",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "regurgitation", "dehydration"},
        "description": "Inflammation of the GI tract from bacterial, parasitic, or dietary causes.",
        "description_ja": "細菌、寄生虫、食事性の原因による胃腸の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "jaundice", "abdominal_swelling"},
        "description": "Excessive fat deposition in the liver, common in obese lizards or during prolonged anorexia.",
        "description_ja": "肥満のトカゲや長期の食欲不振で多い肝臓への過剰な脂肪沈着です。",
        "urgency": "high",
        "recommended_tests": ["liver_function_tests", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "weight_loss"},
        "description": "Salmonella bacterial infection; lizards are common asymptomatic carriers with zoonotic potential.",
        "description_ja": "サルモネラ菌感染症で、トカゲは人畜共通感染のリスクのある無症候性保菌者です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "blood_culture"],
    },
    # ── Eye Diseases ─────────────────────────────────────────────────────
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"swollen_eyes", "eye_discharge", "conjunctivitis", "anorexia"},
        "description": "Inflammation of the conjunctiva from bacterial infection, foreign bodies, or vitamin A deficiency.",
        "description_ja": "細菌感染、異物、ビタミンA欠乏による結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "eye_culture", "blood_vitamin_a_levels"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"cloudy_eyes", "eye_discharge", "eye_swelling", "anorexia"},
        "description": "Ulceration of the cornea from trauma, desiccation, or infection.",
        "description_ja": "外傷、乾燥、感染による角膜の潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "eye_culture"],
    },
    {
        "name": "Periocular Abscess",
        "name_ja": "眼周囲膿瘍",
        "symptoms": {"swollen_eyes", "eye_swelling", "anorexia", "lethargy"},
        "description": "Abscess formation around or behind the eye, often from vitamin A deficiency.",
        "description_ja": "ビタミンA欠乏に関連する眼周囲または眼後方の膿瘍形成です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fine_needle_aspirate", "blood_vitamin_a_levels"],
    },
    {
        "name": "Proptosis (Eye Prolapse)",
        "name_ja": "眼球突出症",
        "symptoms": {"bulging_eye", "eye_swelling", "anorexia", "lethargy"},
        "description": "Abnormal protrusion of the eyeball from infection, abscess, or space-occupying lesion.",
        "description_ja": "感染、膿瘍、占拠性病変による眼球の異常突出です。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmic_exam", "ultrasound", "radiographs"],
    },
    # ── Reproductive ─────────────────────────────────────────────────────
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "卵塞（難産）",
        "symptoms": {"straining", "anorexia", "lethargy", "abdominal_swelling", "restlessness", "cloacal_swelling", "digging_behavior"},
        "description": "Inability to lay eggs due to calcium deficiency, lack of nesting site, or oversized eggs.",
        "description_ja": "カルシウム不足、産卵場所の欠如、過大卵により卵を産めない状態です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "blood_calcium"],
    },
    {
        "name": "Pre-ovulatory Follicular Stasis",
        "name_ja": "排卵前卵胞停滞",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "weight_loss"},
        "description": "Failure of ovarian follicles to ovulate, common in chameleons and bearded dragons.",
        "description_ja": "カメレオンやフトアゴヒゲトカゲに多い卵巣卵胞が排卵されない状態です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_chemistry"],
    },
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "straining", "anorexia", "lethargy"},
        "description": "Protrusion of cloacal tissue, which may involve colon, oviduct, or urinary bladder.",
        "description_ja": "結腸、卵管、膀胱が関与する可能性のある総排泄腔組織の突出です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs", "ultrasound"],
    },
    {
        "name": "Hemipenal Prolapse",
        "name_ja": "半陰茎脱出",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "swelling"},
        "description": "Prolapse of hemipenes in male lizards, requiring prompt veterinary attention.",
        "description_ja": "雄トカゲの半陰茎脱出で、迅速な獣医の処置が必要です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    # ── Gout ─────────────────────────────────────────────────────────────
    {
        "name": "Articular Gout",
        "name_ja": "関節痛風",
        "symptoms": {"swollen_joints", "joint_pain", "lameness", "lethargy", "anorexia"},
        "description": "Uric acid crystal deposition in joints from renal dysfunction or chronic dehydration.",
        "description_ja": "腎機能障害や慢性脱水による尿酸結晶の関節への沈着です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "radiographs", "joint_aspiration"],
    },
    {
        "name": "Visceral Gout",
        "name_ja": "内臓痛風",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "sudden_death"},
        "description": "Uric acid deposition on internal organs, often secondary to renal failure.",
        "description_ja": "腎不全に続発する内臓への尿酸沈着です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    # ── Renal / Urinary ──────────────────────────────────────────────────
    {
        "name": "Renal Failure (Chronic Kidney Disease)",
        "name_ja": "腎不全",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "edema", "gout_tophi"},
        "description": "Progressive kidney failure, common in iguanas and other lizards on high-protein diets.",
        "description_ja": "高タンパク食のイグアナやその他のトカゲに多い進行性の腎不全です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Bladder Stones (Urolithiasis)",
        "name_ja": "膀胱結石",
        "symptoms": {"straining", "anorexia", "lethargy", "abdominal_swelling"},
        "description": "Urate or calcium-based calculi in the urinary bladder.",
        "description_ja": "尿酸塩またはカルシウム系の膀胱結石です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "urinalysis"],
    },
    # ── Dehydration / General ────────────────────────────────────────────
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"sunken_eyes", "wrinkled_skin", "decreased_skin_elasticity", "lethargy", "anorexia", "dry_mucous_membranes"},
        "description": "Insufficient fluid intake common in species that prefer to drink from moving water (chameleons).",
        "description_ja": "流れる水から飲水を好む種（カメレオン）などで多い水分摂取不足です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "packed_cell_volume"],
    },
    {
        "name": "Anorexia (Non-specific)",
        "name_ja": "食欲不振（非特異的）",
        "symptoms": {"anorexia", "weight_loss", "lethargy"},
        "description": "Refusal to eat from husbandry issues, stress, seasonal changes, or underlying disease.",
        "description_ja": "飼育環境の問題、ストレス、季節変化、基礎疾患による摂食拒否です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "blood_chemistry", "husbandry_review"],
    },
    # ── Septicemia / Systemic ────────────────────────────────────────────
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "petechia", "respiratory_distress", "sudden_death"},
        "description": "Systemic bacterial infection in the bloodstream, life-threatening if not treated promptly.",
        "description_ja": "迅速な治療が行われないと生命を脅かす血流中の全身性細菌感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count", "blood_chemistry"],
    },
    # ── Neurological ─────────────────────────────────────────────────────
    {
        "name": "Neurological Syndrome (Non-specific)",
        "name_ja": "神経学的症候群",
        "symptoms": {"neurological_signs", "head_tilt", "circling", "tremors", "seizures", "stargazing"},
        "description": "Neurological dysfunction from adenovirus (ADV), metabolic, toxic, or congenital causes.",
        "description_ja": "アデノウイルス（ADV）、代謝性、中毒性、先天性の原因による神経機能障害です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "pcr_atadenovirus", "blood_chemistry"],
    },
    {
        "name": "Spinal Osteopathy / Spondylosis",
        "name_ja": "脊椎骨症/脊椎症",
        "symptoms": {"paralysis", "difficulty_moving", "weakness", "abnormal_posture"},
        "description": "Degenerative or infectious spinal changes causing motor dysfunction.",
        "description_ja": "脊椎の変性または感染性変化により運動機能障害を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ct_mri", "neurological_exam"],
    },
    # ── Neoplasia ────────────────────────────────────────────────────────
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"firm_mass", "skin_lesions", "ulcerated_mass", "weight_loss", "anorexia"},
        "description": "Malignant epithelial tumor, relatively common in lizards.",
        "description_ja": "トカゲで比較的多い上皮性の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "anorexia", "lethargy", "swelling", "organ_enlargement"},
        "description": "Malignant lymphoid tumor affecting multiple organ systems.",
        "description_ja": "複数の臓器系に影響するリンパ組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "complete_blood_count", "ultrasound"],
    },
    {
        "name": "Hepatocellular Carcinoma",
        "name_ja": "肝細胞癌",
        "symptoms": {"anorexia", "lethargy", "abdominal_swelling", "weight_loss", "jaundice"},
        "description": "Malignant liver tumor, occasionally seen in lizards.",
        "description_ja": "トカゲで時折見られる肝臓の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["liver_function_tests", "ultrasound", "biopsy"],
    },
    # ── Organ Failure ────────────────────────────────────────────────────
    {
        "name": "Liver Failure (Hepatopathy)",
        "name_ja": "肝不全",
        "symptoms": {"anorexia", "lethargy", "jaundice", "weight_loss", "abdominal_swelling"},
        "description": "Severe liver dysfunction from infectious, toxic, or metabolic causes.",
        "description_ja": "感染性、中毒性、代謝性の原因による重篤な肝機能障害です。",
        "urgency": "emergency",
        "recommended_tests": ["liver_function_tests", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Cardiac Disease",
        "name_ja": "心疾患",
        "symptoms": {"lethargy", "edema", "respiratory_distress", "weakness"},
        "description": "Heart disease including cardiomyopathy and pericardial effusion.",
        "description_ja": "心筋症や心嚢液貯留を含む心疾患です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiographs"],
    },
    # ── Miscellaneous ────────────────────────────────────────────────────
    {
        "name": "Hyperthermia (Heat Stroke)",
        "name_ja": "高体温症（熱中症）",
        "symptoms": {"open_mouth_breathing", "lethargy", "weakness", "neurological_signs", "sudden_death"},
        "description": "Dangerously elevated body temperature from heat source malfunction or inadequate thermal gradient.",
        "description_ja": "熱源の故障や不適切な温度勾配による危険な体温上昇です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry"],
    },
    {
        "name": "Hypothermia",
        "name_ja": "低体温症",
        "symptoms": {"lethargy", "anorexia", "weakness", "slow_reflexes"},
        "description": "Sub-optimal body temperature suppressing digestion and immune function.",
        "description_ja": "消化と免疫機能を抑制する適切な温度を下回る体温です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "temperature_check", "husbandry_review"],
    },
    {
        "name": "Trauma / Bite Wounds",
        "name_ja": "外傷・咬傷",
        "symptoms": {"skin_lesions", "bleeding", "swelling", "anorexia", "lethargy"},
        "description": "Physical injuries from cage mates, predators, or handling accidents.",
        "description_ja": "同居個体、捕食者、取り扱い事故による物理的損傷です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Stress Syndrome",
        "name_ja": "ストレス症候群",
        "symptoms": {"anorexia", "lethargy", "color_change", "hiding_behavior", "glass_surfing"},
        "description": "Chronic stress from improper husbandry, cohabitation, or inadequate enclosure size.",
        "description_ja": "不適切な飼育環境、同居飼育、不十分なケージサイズによる慢性的ストレスです。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "physical_exam"],
    },
    {
        "name": "Toxicosis (Poisoning)",
        "name_ja": "中毒症",
        "symptoms": {"neurological_signs", "tremors", "seizures", "anorexia", "lethargy", "sudden_death"},
        "description": "Exposure to toxic substances including pesticides, toxic plants, or contaminated insects.",
        "description_ja": "殺虫剤、有毒植物、汚染された昆虫などの有毒物質への暴露です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Peritonitis / Coelomitis",
        "name_ja": "腹膜炎・体腔炎",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "pain_response", "respiratory_distress"},
        "description": "Inflammation of the coelomic cavity from egg rupture, organ perforation, or bacterial infection.",
        "description_ja": "卵の破裂、臓器穿孔、細菌感染による体腔の炎症です。",
        "urgency": "emergency",
        "recommended_tests": ["coelomic_fluid_analysis", "ultrasound", "blood_chemistry"],
    },
    {
        "name": "Osteomyelitis",
        "name_ja": "骨髄炎",
        "symptoms": {"swelling", "lameness", "anorexia", "lethargy", "firm_mass"},
        "description": "Bacterial bone infection, often secondary to stomatitis or bite wounds.",
        "description_ja": "口内炎や咬傷に続発する骨の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "bone_culture", "complete_blood_count"],
    },
    {
        "name": "Temporal Gland Disorder (Iguanas)",
        "name_ja": "側頭腺障害（イグアナ）",
        "symptoms": {"head_swelling", "facial_swelling", "lethargy", "anorexia"},
        "description": "Hyperplasia or infection of the subtympanic shield / temporal gland in iguanas.",
        "description_ja": "イグアナの鼓室下板・側頭腺の過形成または感染です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "fine_needle_aspirate", "radiographs"],
    },
    {
        "name": "Femoral Pore Impaction / Infection",
        "name_ja": "大腿孔閉塞・感染",
        "symptoms": {"swollen_femoral_pores", "skin_lesions", "lameness", "anorexia"},
        "description": "Blockage and potential infection of the femoral pores, common in iguanas and bearded dragons.",
        "description_ja": "イグアナやフトアゴヒゲトカゲに多い大腿孔の閉塞と感染の可能性です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture_sensitivity"],
    },
    {
        "name": "Chameleon Edema Syndrome",
        "name_ja": "カメレオン浮腫症候群",
        "symptoms": {"edema", "lethargy", "anorexia", "abdominal_swelling", "limb_swelling"},
        "description": "Generalized edema in chameleons from organ failure, over-supplementation, or systemic infection.",
        "description_ja": "臓器不全、サプリメント過剰、全身感染によるカメレオンの全身性浮腫です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound", "complete_blood_count"],
    },
    {
        "name": "Mycobacteriosis",
        "name_ja": "マイコバクテリウム症",
        "symptoms": {"weight_loss", "anorexia", "skin_lesions", "lethargy", "granulomatous_lesions"},
        "description": "Chronic granulomatous infection by Mycobacterium spp.",
        "description_ja": "マイコバクテリウム属菌による慢性肉芽腫性感染症です。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "culture", "biopsy"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "soft_bones": {"ja": "骨軟化", "en": "Soft bones"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "swollen_limbs": {"ja": "四肢の腫脹", "en": "Swollen limbs"},
    "jaw_softening": {"ja": "顎の軟化", "en": "Jaw softening"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "rubber_jaw": {"ja": "ラバージョー", "en": "Rubber jaw"},
    "swollen_eyes": {"ja": "眼腫脹", "en": "Swollen eyes"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory distress"},
    "skin_sloughing": {"ja": "皮膚剥離", "en": "Skin sloughing"},
    "excessive_thirst": {"ja": "多飲", "en": "Excessive thirst"},
    "excessive_urination": {"ja": "多尿", "en": "Excessive urination"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "poor_body_condition": {"ja": "低体格スコア", "en": "Poor body condition"},
    "excessive_weight": {"ja": "過体重", "en": "Excessive weight"},
    "fat_deposits": {"ja": "脂肪沈着", "en": "Fat deposits"},
    "difficulty_moving": {"ja": "運動困難", "en": "Difficulty moving"},
    "muscle_twitching": {"ja": "筋肉のピクつき", "en": "Muscle twitching"},
    "seizures": {"ja": "発作", "en": "Seizures"},
    "neurological_signs": {"ja": "神経学的徴候", "en": "Neurological signs"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "liver_enlargement": {"ja": "肝臓肥大", "en": "Liver enlargement"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "failure_to_thrive": {"ja": "発育不良", "en": "Failure to thrive"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "mouth_lesions": {"ja": "口腔内病変", "en": "Mouth lesions"},
    "stomatitis": {"ja": "口内炎", "en": "Stomatitis"},
    "skin_hemorrhage": {"ja": "皮膚出血", "en": "Skin hemorrhage"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "yellow_skin_patches": {"ja": "黄色の皮膚斑", "en": "Yellow skin patches"},
    "crusty_patches": {"ja": "痂皮性斑", "en": "Crusty patches"},
    "dysecdysis": {"ja": "脱皮不全", "en": "Dysecdysis"},
    "skin_necrosis": {"ja": "皮膚壊死", "en": "Skin necrosis"},
    "scale_discoloration": {"ja": "鱗の変色", "en": "Scale discoloration"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "open_mouth_breathing": {"ja": "口を開けて呼吸", "en": "Open-mouth breathing"},
    "mucus_in_mouth": {"ja": "口腔内粘液", "en": "Mucus in mouth"},
    "swollen_gums": {"ja": "歯肉腫脹", "en": "Swollen gums"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "oral_hemorrhage": {"ja": "口腔出血", "en": "Oral hemorrhage"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "skin_irritation": {"ja": "皮膚の刺激感", "en": "Skin irritation"},
    "visible_mites": {"ja": "肉眼で確認できるダニ", "en": "Visible mites"},
    "excessive_soaking": {"ja": "過度の水浸し", "en": "Excessive soaking"},
    "visible_parasites": {"ja": "肉眼で確認できる寄生虫", "en": "Visible parasites"},
    "body_swelling": {"ja": "体の腫脹", "en": "Body swelling"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "visible_larvae": {"ja": "肉眼で確認できる幼虫", "en": "Visible larvae"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "retained_skin": {"ja": "残皮", "en": "Retained skin"},
    "skin_constriction": {"ja": "皮膚の絞扼", "en": "Skin constriction"},
    "toe_discoloration": {"ja": "趾の変色", "en": "Toe discoloration"},
    "toe_swelling": {"ja": "趾の腫脹", "en": "Toe swelling"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "tail_wound": {"ja": "尾の傷", "en": "Tail wound"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "skin_burns": {"ja": "皮膚の火傷", "en": "Skin burns"},
    "blisters": {"ja": "水疱", "en": "Blisters"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "firm_mass": {"ja": "硬い腫瘤", "en": "Firm mass"},
    "nose_abrasion": {"ja": "吻部の擦過傷", "en": "Nose abrasion"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "abdominal_swelling": {"ja": "腹部膨満", "en": "Abdominal swelling"},
    "regurgitation": {"ja": "吐出", "en": "Regurgitation"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "bulging_eye": {"ja": "眼球突出", "en": "Bulging eye"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "cloacal_swelling": {"ja": "総排泄腔の腫脹", "en": "Cloacal swelling"},
    "digging_behavior": {"ja": "掘る行動", "en": "Digging behavior"},
    "tissue_prolapse": {"ja": "組織脱出", "en": "Tissue prolapse"},
    "swollen_joints": {"ja": "関節腫脹", "en": "Swollen joints"},
    "joint_pain": {"ja": "関節痛", "en": "Joint pain"},
    "gout_tophi": {"ja": "痛風結節", "en": "Gout tophi"},
    "sunken_eyes": {"ja": "眼窩陥没", "en": "Sunken eyes"},
    "wrinkled_skin": {"ja": "しわのある皮膚", "en": "Wrinkled skin"},
    "decreased_skin_elasticity": {"ja": "皮膚弾力低下", "en": "Decreased skin elasticity"},
    "dry_mucous_membranes": {"ja": "粘膜乾燥", "en": "Dry mucous membranes"},
    "petechia": {"ja": "点状出血", "en": "Petechiae"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "stargazing": {"ja": "スターゲイジング", "en": "Stargazing"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "abnormal_posture": {"ja": "異常姿勢", "en": "Abnormal posture"},
    "ulcerated_mass": {"ja": "潰瘍化した腫瘤", "en": "Ulcerated mass"},
    "organ_enlargement": {"ja": "臓器肥大", "en": "Organ enlargement"},
    "color_change": {"ja": "体色変化", "en": "Color change"},
    "hiding_behavior": {"ja": "隠れ行動", "en": "Hiding behavior"},
    "glass_surfing": {"ja": "ガラスサーフィン", "en": "Glass surfing"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "slow_reflexes": {"ja": "反射低下", "en": "Slow reflexes"},
    "pain_response": {"ja": "疼痛反応", "en": "Pain response"},
    "head_swelling": {"ja": "頭部の腫脹", "en": "Head swelling"},
    "swollen_femoral_pores": {"ja": "大腿孔の腫脹", "en": "Swollen femoral pores"},
    "limb_swelling": {"ja": "四肢の腫脹", "en": "Limb swelling"},
    "granulomatous_lesions": {"ja": "肉芽腫性病変", "en": "Granulomatous lesions"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    """Analyze lizard symptoms and return suspected diseases.

    Parameters
    ----------
    symptoms:
        A list of symptom identifier strings.
    age_stage:
        Optional age stage descriptor.
    breed:
        Optional species/morph; included for interface compatibility.

    Returns
    -------
    dict
        Analysis result in the standard differential diagnosis format.
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
