"""Parrot disease dictionary and analysis module."""
from __future__ import annotations
from typing import Any, Dict, List
from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # === Viral Diseases ===
    {
        "name": "Psittacine Beak and Feather Disease (PBFD)",
        "name_ja": "オウム類嘴羽毛病（PBFD）",
        "symptoms": {"feather_loss", "beak_deformity", "immunosuppression", "lethargy", "weight_loss", "abnormal_feathers"},
        "description": "Circovirus infection causing progressive feather dystrophy and beak necrosis, often fatal in young birds.",
        "description_ja": "サーコウイルス感染による進行性の羽毛異栄養症と嘴壊死。若鳥では致死的になることが多い。",
        "urgency": "high",
        "recommended_tests": ["PCR for circovirus", "feather biopsy", "CBC"],
    },
    {
        "name": "Proventricular Dilatation Disease (PDD) / Bornavirus",
        "name_ja": "腺胃拡張症（PDD）／ボルナウイルス感染症",
        "symptoms": {"weight_loss", "regurgitation", "undigested_seeds_in_droppings", "crop_stasis", "ataxia", "seizures", "lethargy"},
        "description": "Avian bornavirus causes ganglioneuritis of the GI tract and CNS, leading to GI stasis and neurological signs.",
        "description_ja": "鳥ボルナウイルスによる消化管・中枢神経系の神経節炎。消化管停滞と神経症状を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["anti-ganglioside antibody test", "crop biopsy", "PCR for bornavirus", "radiographs"],
    },
    {
        "name": "Psittacosis (Chlamydiosis)",
        "name_ja": "オウム病（クラミジア症）",
        "symptoms": {"respiratory_distress", "nasal_discharge", "conjunctivitis", "lethargy", "anorexia", "lime_green_droppings", "weight_loss"},
        "description": "Chlamydia psittaci infection causing respiratory and systemic illness; zoonotic risk to humans.",
        "description_ja": "クラミジア・シッタシ感染による呼吸器・全身性疾患。人獣共通感染症である。",
        "urgency": "high",
        "recommended_tests": ["PCR for Chlamydia psittaci", "serology", "CBC", "liver panel"],
    },
    {
        "name": "Avian Polyomavirus",
        "name_ja": "鳥ポリオーマウイルス感染症",
        "symptoms": {"lethargy", "anorexia", "subcutaneous_hemorrhage", "abdominal_distension", "sudden_death", "feather_abnormalities"},
        "description": "Highly contagious virus causing acute death in nestlings; older birds may be carriers.",
        "description_ja": "雛鳥に急性死を引き起こす高度に伝染性のウイルス。成鳥はキャリアとなる場合がある。",
        "urgency": "emergency",
        "recommended_tests": ["PCR for polyomavirus", "necropsy", "histopathology"],
    },
    {
        "name": "Pacheco's Disease",
        "name_ja": "パチェコ病",
        "symptoms": {"sudden_death", "lethargy", "anorexia", "lime_green_droppings", "nasal_discharge", "bloody_droppings"},
        "description": "Psittacid herpesvirus infection causing acute hepatic necrosis; high mortality rate.",
        "description_ja": "オウム目ヘルペスウイルスによる急性肝壊死。致死率が高い。",
        "urgency": "emergency",
        "recommended_tests": ["PCR for herpesvirus", "liver biopsy", "necropsy"],
    },
    {
        "name": "Avian Poxvirus",
        "name_ja": "鳥痘",
        "symptoms": {"skin_lesions", "crusty_lesions_on_face", "oral_plaques", "respiratory_distress", "conjunctivitis"},
        "description": "Poxvirus causing dry (cutaneous) or wet (diphtheritic) forms; spread by mosquitoes and direct contact.",
        "description_ja": "ポックスウイルスによる乾燥型（皮膚型）または湿潤型（ジフテリア型）の病変。蚊や直接接触で伝播。",
        "urgency": "moderate",
        "recommended_tests": ["skin biopsy", "histopathology", "PCR"],
    },
    {
        "name": "Papillomatosis",
        "name_ja": "乳頭腫症",
        "symptoms": {"oral_plaques", "cloacal_mass", "regurgitation", "bloody_droppings", "difficulty_eating"},
        "description": "Herpesvirus-associated papillomas of the oral cavity, cloaca, and GI tract; common in Amazons and macaws.",
        "description_ja": "ヘルペスウイルス関連の口腔・総排泄腔・消化管の乳頭腫。アマゾンやコンゴウインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology", "endoscopy"],
    },
    {
        "name": "Avian Influenza",
        "name_ja": "鳥インフルエンザ",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "sudden_death", "diarrhea", "cyanosis"},
        "description": "Influenza A virus causing respiratory and systemic disease; reportable disease with zoonotic potential.",
        "description_ja": "インフルエンザAウイルスによる呼吸器・全身性疾患。届出義務のある人獣共通感染症。",
        "urgency": "emergency",
        "recommended_tests": ["PCR for influenza", "virus isolation", "serology"],
    },
    {
        "name": "Newcastle Disease",
        "name_ja": "ニューカッスル病",
        "symptoms": {"respiratory_distress", "ataxia", "seizures", "torticollis", "paralysis", "diarrhea", "sudden_death"},
        "description": "Paramyxovirus causing severe respiratory and neurological signs; highly contagious and reportable.",
        "description_ja": "パラミクソウイルスによる重度の呼吸器・神経症状。高度に伝染性で届出義務がある。",
        "urgency": "emergency",
        "recommended_tests": ["virus isolation", "PCR", "serology"],
    },
    # === Bacterial Diseases ===
    {
        "name": "Bacterial Pneumonia",
        "name_ja": "細菌性肺炎",
        "symptoms": {"respiratory_distress", "tail_bobbing", "open_mouth_breathing", "nasal_discharge", "lethargy", "anorexia"},
        "description": "Bacterial infection of the lungs and air sacs causing severe respiratory compromise.",
        "description_ja": "肺および気嚢の細菌感染による重度の呼吸障害。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "culture and sensitivity", "CBC", "tracheal wash"],
    },
    {
        "name": "Air Sacculitis",
        "name_ja": "気嚢炎",
        "symptoms": {"respiratory_distress", "tail_bobbing", "open_mouth_breathing", "lethargy", "weight_loss"},
        "description": "Infection or inflammation of the avian air sacs, commonly from bacterial or fungal causes.",
        "description_ja": "鳥類の気嚢の感染または炎症。細菌性または真菌性が多い。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "endoscopy", "culture", "CBC"],
    },
    {
        "name": "Sinusitis",
        "name_ja": "副鼻腔炎",
        "symptoms": {"nasal_discharge", "facial_swelling", "sneezing", "respiratory_distress", "head_shaking"},
        "description": "Infection of the infraorbital sinus, common in Amazons and African Greys; may require flushing.",
        "description_ja": "眼窩下洞の感染。アマゾンやヨウムに多く、洗浄が必要になることがある。",
        "urgency": "moderate",
        "recommended_tests": ["sinus aspirate culture", "radiographs", "CT scan"],
    },
    {
        "name": "Cloacitis",
        "name_ja": "総排泄腔炎",
        "symptoms": {"bloody_droppings", "straining_to_defecate", "cloacal_swelling", "vent_soiling", "lethargy"},
        "description": "Inflammation of the cloaca from bacterial, fungal, or parasitic causes.",
        "description_ja": "細菌・真菌・寄生虫による総排泄腔の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["cloacal culture", "cytology", "fecal exam"],
    },
    {
        "name": "Bumblefoot (Pododermatitis)",
        "name_ja": "趾瘤症（バンブルフット）",
        "symptoms": {"foot_swelling", "lameness", "reluctance_to_perch", "skin_lesions"},
        "description": "Bacterial infection of the plantar surface of the foot, often from inappropriate perching surfaces.",
        "description_ja": "不適切な止まり木による足底面の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["radiographs of feet", "culture", "cytology"],
    },
    {
        "name": "Gram-negative Bacterial Infection",
        "name_ja": "グラム陰性菌感染症",
        "symptoms": {"diarrhea", "regurgitation", "lethargy", "anorexia", "weight_loss"},
        "description": "Overgrowth of pathogenic gram-negative bacteria in the GI tract causing enteritis.",
        "description_ja": "消化管における病原性グラム陰性菌の過剰増殖による腸炎。",
        "urgency": "moderate",
        "recommended_tests": ["gram stain", "fecal culture", "sensitivity testing"],
    },
    {
        "name": "Mycobacteriosis (Avian Tuberculosis)",
        "name_ja": "マイコバクテリウム症（鳥結核）",
        "symptoms": {"weight_loss", "diarrhea", "lethargy", "anorexia", "abdominal_distension", "lameness"},
        "description": "Chronic wasting disease caused by Mycobacterium avium; zoonotic concern.",
        "description_ja": "マイコバクテリウム・アビウムによる慢性消耗性疾患。人獣共通感染症の懸念がある。",
        "urgency": "high",
        "recommended_tests": ["acid-fast stain", "PCR", "biopsy", "radiographs"],
    },
    # === Fungal Diseases ===
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"respiratory_distress", "tail_bobbing", "voice_change", "lethargy", "anorexia", "weight_loss"},
        "description": "Fungal infection by Aspergillus species affecting the respiratory tract; common in immunosuppressed birds.",
        "description_ja": "アスペルギルス属真菌による呼吸器感染。免疫抑制された鳥に多い。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "endoscopy", "fungal culture", "aspergillus antigen test", "CBC"],
    },
    {
        "name": "Candidiasis",
        "name_ja": "カンジダ症",
        "symptoms": {"oral_plaques", "regurgitation", "crop_stasis", "anorexia", "white_patches_in_mouth"},
        "description": "Candida albicans overgrowth in the crop and oral cavity, often secondary to antibiotic use or immunosuppression.",
        "description_ja": "抗生物質使用や免疫抑制に続発するカンジダ・アルビカンスの過剰増殖。嗉嚢と口腔に多い。",
        "urgency": "moderate",
        "recommended_tests": ["crop wash cytology", "fungal culture", "gram stain"],
    },
    {
        "name": "Macrorhabdosis (Megabacteriosis / AGY)",
        "name_ja": "マクロラブドス症（メガバクテリア症）",
        "symptoms": {"weight_loss", "regurgitation", "undigested_seeds_in_droppings", "lethargy", "anorexia"},
        "description": "Macrorhabdus ornithogaster (formerly megabacteria) infection of the proventriculus and ventriculus.",
        "description_ja": "マクロラブドス・オルニトガスター（旧メガバクテリア）による前胃・筋胃の感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal gram stain", "crop/fecal wet mount", "endoscopy"],
    },
    {
        "name": "Cryptococcosis",
        "name_ja": "クリプトコッカス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "facial_swelling", "ataxia", "lethargy"},
        "description": "Systemic fungal infection caused by Cryptococcus neoformans; may affect sinuses and CNS.",
        "description_ja": "クリプトコッカス・ネオフォルマンスによる全身性真菌感染。副鼻腔やCNSに影響することがある。",
        "urgency": "high",
        "recommended_tests": ["cryptococcal antigen test", "cytology", "culture", "CT scan"],
    },
    # === Parasitic Diseases ===
    {
        "name": "Sarcocystosis",
        "name_ja": "サルコシスティス症",
        "symptoms": {"sudden_death", "lethargy", "respiratory_distress", "muscle_weakness", "anorexia"},
        "description": "Sarcocystis falcatula causing acute pulmonary disease; high mortality in Old World parrots.",
        "description_ja": "サルコシスティス・ファルカツラによる急性肺疾患。旧世界オウム類で致死率が高い。",
        "urgency": "emergency",
        "recommended_tests": ["histopathology", "PCR", "necropsy"],
    },
    {
        "name": "Giardiasis",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "weight_loss", "feather_plucking", "dry_flaky_skin", "anorexia"},
        "description": "Giardia protozoan infection causing chronic loose droppings and feather picking, especially in cockatiels.",
        "description_ja": "ジアルジア原虫感染による慢性軟便と羽毛むしり。特にオカメインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["fecal wet mount", "fecal antigen test", "trichrome stain"],
    },
    {
        "name": "Intestinal Parasites (Roundworms/Tapeworms)",
        "name_ja": "腸内寄生虫症（回虫・条虫）",
        "symptoms": {"weight_loss", "diarrhea", "lethargy", "anorexia", "abdominal_distension"},
        "description": "Ascaridia, Capillaria, or tapeworm infections of the GI tract.",
        "description_ja": "回虫属、毛細線虫属、または条虫による消化管感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal flotation", "fecal wet mount", "direct smear"],
    },
    {
        "name": "Knemidocoptes Mite Infestation (Scaly Face/Leg)",
        "name_ja": "疥癬ダニ症（鱗状顔面・脚疾患）",
        "symptoms": {"beak_deformity", "crusty_lesions_on_face", "skin_lesions", "lameness", "foot_swelling"},
        "description": "Burrowing mites causing proliferative lesions on beak, cere, face, and legs.",
        "description_ja": "嘴、蝋膜、顔面、脚に増殖性病変を引き起こす穿孔性ダニ。",
        "urgency": "moderate",
        "recommended_tests": ["skin scraping", "microscopy"],
    },
    # === Toxicities ===
    {
        "name": "Heavy Metal Poisoning (Lead/Zinc)",
        "name_ja": "重金属中毒（鉛・亜鉛）",
        "symptoms": {"ataxia", "seizures", "regurgitation", "lethargy", "weight_loss", "bloody_droppings", "polyuria"},
        "description": "Ingestion of lead or zinc from cage hardware, paint, or household items causing GI and neurological signs.",
        "description_ja": "ケージ部品、塗料、家庭用品からの鉛・亜鉛摂取による消化器・神経症状。",
        "urgency": "emergency",
        "recommended_tests": ["blood lead/zinc levels", "radiographs", "CBC", "biochemistry panel"],
    },
    {
        "name": "PTFE Toxicosis (Teflon Poisoning)",
        "name_ja": "PTFE中毒（テフロン中毒）",
        "symptoms": {"sudden_death", "respiratory_distress", "cyanosis", "open_mouth_breathing"},
        "description": "Inhalation of polytetrafluoroethylene fumes from overheated non-stick cookware; rapidly fatal.",
        "description_ja": "加熱された非粘着調理器具からのPTFEヒューム吸入。急速に致死的。",
        "urgency": "emergency",
        "recommended_tests": ["history of exposure", "necropsy", "lung histopathology"],
    },
    {
        "name": "Avocado Toxicity",
        "name_ja": "アボカド中毒",
        "symptoms": {"respiratory_distress", "lethargy", "anorexia", "sudden_death", "abdominal_distension"},
        "description": "Persin in avocado causes myocardial necrosis and respiratory failure in parrots.",
        "description_ja": "アボカドに含まれるペルシンがオウム類の心筋壊死と呼吸不全を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["history of ingestion", "cardiac monitoring", "radiographs"],
    },
    {
        "name": "Chocolate Toxicity",
        "name_ja": "チョコレート中毒",
        "symptoms": {"regurgitation", "diarrhea", "seizures", "lethargy", "hyperactivity"},
        "description": "Theobromine and caffeine in chocolate cause cardiac and neurological toxicity in parrots.",
        "description_ja": "チョコレートに含まれるテオブロミンとカフェインがオウム類の心臓・神経毒性を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["history of ingestion", "cardiac monitoring", "supportive care assessment"],
    },
    {
        "name": "Smoke/Fume Inhalation Toxicosis",
        "name_ja": "煙・ガス吸入中毒",
        "symptoms": {"respiratory_distress", "cyanosis", "lethargy", "open_mouth_breathing", "sudden_death"},
        "description": "Inhalation of smoke, aerosols, or toxic household fumes damaging the sensitive avian respiratory system.",
        "description_ja": "煙、エアロゾル、家庭用有毒ガスの吸入による鳥類呼吸器系の損傷。",
        "urgency": "emergency",
        "recommended_tests": ["history of exposure", "radiographs", "blood gas analysis"],
    },
    {
        "name": "Plant Toxicity",
        "name_ja": "植物中毒",
        "symptoms": {"regurgitation", "diarrhea", "lethargy", "anorexia", "seizures"},
        "description": "Ingestion of toxic houseplants (e.g., dieffenbachia, philodendron, lilies) causing GI and systemic signs.",
        "description_ja": "有毒な観葉植物（ディフェンバキア、フィロデンドロン、ユリ等）の摂取による消化器・全身症状。",
        "urgency": "high",
        "recommended_tests": ["history of plant exposure", "CBC", "biochemistry panel"],
    },
    # === Nutritional Diseases ===
    {
        "name": "Vitamin A Deficiency (Hypovitaminosis A)",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"oral_plaques", "nasal_discharge", "sneezing", "skin_lesions", "respiratory_distress", "white_patches_in_mouth"},
        "description": "Common in seed-only diets causing squamous metaplasia of mucous membranes and immune suppression.",
        "description_ja": "種子のみの食餌で多い。粘膜の扁平上皮化生と免疫抑制を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["dietary history", "vitamin A blood level", "oral exam"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"seizures", "muscle_weakness", "egg_binding", "tremors", "ataxia", "lethargy"},
        "description": "Low blood calcium causing neuromuscular signs; common in African Greys and egg-laying females.",
        "description_ja": "低血中カルシウムによる神経筋症状。ヨウムや産卵中の雌に多い。",
        "urgency": "high",
        "recommended_tests": ["ionized calcium level", "total calcium", "biochemistry panel"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"muscle_weakness", "seizures", "beak_deformity", "fractures", "lethargy"},
        "description": "Insufficient vitamin D3 leading to poor calcium absorption; common in indoor birds without UV light.",
        "description_ja": "ビタミンD3不足によるカルシウム吸収不良。紫外線を浴びない室内飼育鳥に多い。",
        "urgency": "moderate",
        "recommended_tests": ["vitamin D3 level", "ionized calcium", "radiographs"],
    },
    {
        "name": "Iron Storage Disease (Hemochromatosis)",
        "name_ja": "鉄貯蔵病（ヘモクロマトーシス）",
        "symptoms": {"lethargy", "abdominal_distension", "respiratory_distress", "anorexia", "weight_loss"},
        "description": "Excessive iron accumulation in the liver; more common in toucans and mynahs but also seen in lories.",
        "description_ja": "肝臓への過剰な鉄蓄積。オオハシやキュウカンチョウに多いがローリーでも見られる。",
        "urgency": "high",
        "recommended_tests": ["liver biopsy", "serum iron panel", "liver ultrasound"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "respiratory_distress", "lethargy", "lipomas", "difficulty_flying"},
        "description": "Excessive body fat from high-fat seed diets and insufficient exercise; predisposes to hepatic lipidosis.",
        "description_ja": "高脂肪種子食と運動不足による過剰体脂肪。肝リピドーシスの素因となる。",
        "urgency": "low",
        "recommended_tests": ["body condition scoring", "radiographs", "lipid panel", "liver panel"],
    },
    {
        "name": "Iodine Deficiency (Thyroid Hyperplasia)",
        "name_ja": "ヨウ素欠乏症（甲状腺過形成）",
        "symptoms": {"respiratory_distress", "voice_change", "regurgitation", "weight_gain"},
        "description": "Thyroid enlargement due to dietary iodine deficiency, compressing the trachea and crop.",
        "description_ja": "食餌性ヨウ素欠乏による甲状腺腫大。気管と嗉嚢を圧迫する。",
        "urgency": "moderate",
        "recommended_tests": ["radiographs", "thyroid hormone levels", "dietary history"],
    },
    # === Metabolic / Organ Diseases ===
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"lethargy", "anorexia", "weight_loss", "abnormal_droppings", "abdominal_distension", "beak_overgrowth"},
        "description": "Fat accumulation in the liver from high-fat diets; common in Amazons and cockatoos.",
        "description_ja": "高脂肪食による肝臓への脂肪蓄積。アマゾンやオウムに多い。",
        "urgency": "high",
        "recommended_tests": ["bile acids", "liver panel", "radiographs", "ultrasound", "liver biopsy"],
    },
    {
        "name": "Liver Disease (Hepatitis)",
        "name_ja": "肝疾患（肝炎）",
        "symptoms": {"lime_green_droppings", "lethargy", "anorexia", "weight_loss", "abdominal_distension", "polyuria"},
        "description": "Hepatic inflammation from infectious, toxic, or metabolic causes presenting with biliverdinuria.",
        "description_ja": "感染性、毒性、代謝性原因による肝炎。ビリベルジン尿を呈する。",
        "urgency": "high",
        "recommended_tests": ["bile acids", "AST", "liver panel", "radiographs", "ultrasound"],
    },
    {
        "name": "Renal Disease",
        "name_ja": "腎疾患",
        "symptoms": {"polyuria", "lethargy", "anorexia", "weight_loss", "lameness", "abdominal_distension"},
        "description": "Kidney dysfunction from infection, toxins, or age-related degeneration; may cause unilateral leg paresis.",
        "description_ja": "感染、毒素、加齢性変性による腎機能障害。片側性の脚麻痺を引き起こすことがある。",
        "urgency": "high",
        "recommended_tests": ["uric acid", "biochemistry panel", "radiographs", "ultrasound"],
    },
    {
        "name": "Gout (Articular and Visceral)",
        "name_ja": "痛風（関節型・内臓型）",
        "symptoms": {"lameness", "foot_swelling", "joint_swelling", "lethargy", "anorexia", "polyuria"},
        "description": "Uric acid crystal deposition in joints or viscera from renal insufficiency or high-protein diet.",
        "description_ja": "腎不全や高タンパク食による関節・内臓への尿酸結晶沈着。",
        "urgency": "high",
        "recommended_tests": ["uric acid level", "radiographs", "joint aspirate", "renal panel"],
    },
    {
        "name": "Atherosclerosis",
        "name_ja": "動脈硬化症",
        "symptoms": {"sudden_death", "lethargy", "respiratory_distress", "exercise_intolerance", "seizures"},
        "description": "Plaque buildup in major arteries; common in older Amazons, African Greys, and cockatoos on high-fat diets.",
        "description_ja": "主要動脈のプラーク蓄積。高脂肪食の高齢アマゾン、ヨウム、オウムに多い。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "echocardiography", "lipid panel", "necropsy"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "anorexia"},
        "description": "Pancreatic islet cell dysfunction causing hyperglycemia; rare but reported in parrots.",
        "description_ja": "膵島細胞機能障害による高血糖。稀だがオウム類で報告されている。",
        "urgency": "moderate",
        "recommended_tests": ["blood glucose", "fructosamine", "biochemistry panel"],
    },
    {
        "name": "Pancreatitis",
        "name_ja": "膵炎",
        "symptoms": {"regurgitation", "anorexia", "lethargy", "weight_loss", "abnormal_droppings"},
        "description": "Inflammation of the pancreas causing digestive enzyme release and abdominal pain.",
        "description_ja": "膵臓の炎症による消化酵素の放出と腹痛。",
        "urgency": "high",
        "recommended_tests": ["amylase", "lipase", "biochemistry panel", "radiographs"],
    },
    # === Reproductive Diseases ===
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "卵塞（卵詰まり）",
        "symptoms": {"egg_binding", "straining_to_defecate", "abdominal_distension", "lethargy", "respiratory_distress", "lameness"},
        "description": "Inability to pass a formed egg; can be life-threatening from pressure on nerves and organs.",
        "description_ja": "形成された卵を排出できない状態。神経・臓器への圧迫で致命的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ionized calcium", "ultrasound", "physical exam"],
    },
    {
        "name": "Chronic Egg Laying",
        "name_ja": "慢性産卵",
        "symptoms": {"egg_binding", "weight_loss", "lethargy", "muscle_weakness", "fractures"},
        "description": "Excessive egg production depleting calcium and protein reserves; common in cockatoos and cockatiels.",
        "description_ja": "過剰な産卵によるカルシウムとタンパク質の消耗。オウムやオカメインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["ionized calcium", "radiographs", "hormone panel"],
    },
    {
        "name": "Egg Yolk Peritonitis",
        "name_ja": "卵黄性腹膜炎",
        "symptoms": {"abdominal_distension", "lethargy", "anorexia", "respiratory_distress", "abnormal_droppings"},
        "description": "Free yolk material in the coelomic cavity causing septic or sterile peritonitis.",
        "description_ja": "体腔内の遊離卵黄物質による敗血症性または無菌性腹膜炎。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "coelomic fluid analysis", "CBC"],
    },
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"cloacal_mass", "straining_to_defecate", "bloody_droppings", "vent_soiling"},
        "description": "Protrusion of cloacal tissue through the vent, often from straining, infection, or masses.",
        "description_ja": "肛門から総排泄腔組織が突出する状態。いきみ、感染、腫瘤が原因となることが多い。",
        "urgency": "emergency",
        "recommended_tests": ["physical exam", "cloacal culture", "radiographs", "biopsy"],
    },
    # === GI Diseases ===
    {
        "name": "Crop Stasis (Slow Crop / Crop Impaction)",
        "name_ja": "嗉嚢停滞（嗉嚢うっ滞）",
        "symptoms": {"crop_stasis", "regurgitation", "anorexia", "lethargy", "weight_loss"},
        "description": "Delayed crop emptying from infection, foreign body, or motility disorder.",
        "description_ja": "感染、異物、運動障害による嗉嚢排出遅延。",
        "urgency": "high",
        "recommended_tests": ["crop palpation", "radiographs", "crop wash cytology"],
    },
    {
        "name": "Crop Burns",
        "name_ja": "嗉嚢火傷",
        "symptoms": {"crop_stasis", "regurgitation", "anorexia", "lethargy", "skin_lesions"},
        "description": "Thermal injury to the crop from hand-feeding formula that is too hot; may cause crop fistula.",
        "description_ja": "高温の挿し餌による嗉嚢の熱傷。嗉嚢瘻を引き起こすことがある。",
        "urgency": "high",
        "recommended_tests": ["physical exam", "crop endoscopy", "radiographs"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物摂取",
        "symptoms": {"regurgitation", "anorexia", "lethargy", "crop_stasis", "abdominal_distension"},
        "description": "Ingestion of non-food objects causing obstruction or irritation in the GI tract.",
        "description_ja": "非食物の摂取による消化管の閉塞または刺激。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "fluoroscopy", "endoscopy"],
    },
    {
        "name": "Cloacal Papilloma",
        "name_ja": "総排泄腔乳頭腫",
        "symptoms": {"bloody_droppings", "cloacal_mass", "straining_to_defecate", "vent_soiling"},
        "description": "Benign papillomatous growth in the cloaca; herpesvirus associated; common in Amazons and macaws.",
        "description_ja": "総排泄腔の良性乳頭腫性増殖。ヘルペスウイルス関連。アマゾンやコンゴウインコに多い。",
        "urgency": "moderate",
        "recommended_tests": ["cloacal exam", "biopsy", "histopathology"],
    },
    {
        "name": "Gastric (Ventricular) Foreign Body",
        "name_ja": "胃（筋胃）内異物",
        "symptoms": {"regurgitation", "weight_loss", "anorexia", "lethargy", "abnormal_droppings"},
        "description": "Metal, plastic, or other foreign material lodged in the ventriculus impeding digestion.",
        "description_ja": "金属、プラスチック等の異物が筋胃に停滞し消化を妨げる。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "fluoroscopy", "endoscopy"],
    },
    # === Behavioral / Dermatological ===
    {
        "name": "Feather Destructive Behavior (Feather Plucking)",
        "name_ja": "羽毛破壊行動（毛引き症）",
        "symptoms": {"feather_plucking", "feather_loss", "skin_lesions", "dry_flaky_skin"},
        "description": "Self-inflicted feather damage from stress, boredom, medical issues, or environmental factors.",
        "description_ja": "ストレス、退屈、医学的問題、環境要因による自傷的羽毛損傷。",
        "urgency": "moderate",
        "recommended_tests": ["full medical workup", "behavioral assessment", "hormone panel", "skin biopsy"],
    },
    {
        "name": "Self-Mutilation",
        "name_ja": "自咬症（自傷行為）",
        "symptoms": {"self_mutilation", "skin_lesions", "bleeding", "feather_loss"},
        "description": "Severe self-injurious behavior causing tissue damage; may involve chest, legs, or wings.",
        "description_ja": "組織損傷を引き起こす重度の自傷行為。胸、脚、翼に及ぶことがある。",
        "urgency": "high",
        "recommended_tests": ["behavioral assessment", "neurological exam", "skin biopsy", "CBC"],
    },
    {
        "name": "Psittacine Stress Syndrome",
        "name_ja": "オウム目ストレス症候群",
        "symptoms": {"feather_plucking", "anorexia", "screaming", "aggression", "stereotypic_behavior"},
        "description": "Chronic stress from inadequate socialization, environment, or routine changes leading to behavioral disorders.",
        "description_ja": "不適切な社会化、環境、日課の変化による慢性ストレスが行動障害を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["behavioral assessment", "corticosterone levels", "environmental review"],
    },
    {
        "name": "Contact Dermatitis",
        "name_ja": "接触性皮膚炎",
        "symptoms": {"skin_lesions", "feather_loss", "foot_swelling", "dry_flaky_skin"},
        "description": "Skin irritation from contact with irritants such as cleaners, metals, or treated wood.",
        "description_ja": "洗剤、金属、処理木材等の刺激物との接触による皮膚炎。",
        "urgency": "low",
        "recommended_tests": ["skin biopsy", "environmental history", "allergy testing"],
    },
    # === Orthopedic / Trauma ===
    {
        "name": "Fractures",
        "name_ja": "骨折",
        "symptoms": {"lameness", "wing_droop", "inability_to_fly", "swelling", "pain_vocalization"},
        "description": "Broken bones from trauma, falls, or metabolic bone disease; wings and legs most commonly affected.",
        "description_ja": "外傷、落下、代謝性骨疾患による骨折。翼と脚が最も多い。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "calcium levels", "physical exam"],
    },
    {
        "name": "Beak Malocclusion",
        "name_ja": "嘴不正咬合",
        "symptoms": {"beak_deformity", "difficulty_eating", "beak_overgrowth", "weight_loss"},
        "description": "Misalignment of the upper and lower beak causing difficulty eating; may be congenital or acquired.",
        "description_ja": "上下嘴の不整合による摂食困難。先天性または後天性がある。",
        "urgency": "moderate",
        "recommended_tests": ["physical exam", "radiographs", "nutritional assessment"],
    },
    {
        "name": "Beak Overgrowth",
        "name_ja": "嘴過長症",
        "symptoms": {"beak_overgrowth", "difficulty_eating", "weight_loss"},
        "description": "Excessive beak growth often secondary to liver disease, PBFD, or lack of wear surfaces.",
        "description_ja": "肝疾患、PBFD、または摩耗面不足による嘴の過剰成長。",
        "urgency": "low",
        "recommended_tests": ["liver panel", "PBFD PCR", "nutritional history"],
    },
    {
        "name": "Constricted Toe Syndrome",
        "name_ja": "趾絞扼症候群",
        "symptoms": {"foot_swelling", "lameness", "dry_flaky_skin"},
        "description": "Constriction of toes by dried skin or fibers in neonates, compromising blood supply.",
        "description_ja": "新生鳥における乾燥皮膚や繊維による趾の絞扼。血行が障害される。",
        "urgency": "high",
        "recommended_tests": ["physical exam", "humidity assessment"],
    },
    {
        "name": "Wing Trauma / Soft Tissue Injury",
        "name_ja": "翼外傷・軟部組織損傷",
        "symptoms": {"wing_droop", "inability_to_fly", "swelling", "bleeding", "pain_vocalization"},
        "description": "Sprains, bruises, or lacerations of the wing from flight accidents, cage injuries, or attacks.",
        "description_ja": "飛行事故、ケージ外傷、攻撃による翼の捻挫、打撲、裂傷。",
        "urgency": "moderate",
        "recommended_tests": ["radiographs", "physical exam", "wound culture if open"],
    },
    # === Ophthalmological ===
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"vision_loss", "eye_cloudiness", "clumsiness"},
        "description": "Opacity of the lens causing vision impairment; may be age-related, traumatic, or nutritional.",
        "description_ja": "水晶体の混濁による視力障害。加齢性、外傷性、栄養性がある。",
        "urgency": "low",
        "recommended_tests": ["ophthalmic exam", "slit lamp exam", "ocular ultrasound"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"conjunctivitis", "eye_discharge", "eye_swelling", "head_shaking"},
        "description": "Inflammation of the conjunctiva from infection, irritants, or vitamin A deficiency.",
        "description_ja": "感染、刺激物、ビタミンA欠乏による結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic exam", "conjunctival culture", "cytology"],
    },
    {
        "name": "Periorbital Abscess",
        "name_ja": "眼窩周囲膿瘍",
        "symptoms": {"facial_swelling", "eye_swelling", "eye_discharge", "lethargy"},
        "description": "Abscess formation around the eye, often from sinusitis or vitamin A deficiency.",
        "description_ja": "副鼻腔炎やビタミンA欠乏による眼周囲の膿瘍形成。",
        "urgency": "high",
        "recommended_tests": ["CT scan", "aspirate culture", "vitamin A level"],
    },
    # === Neoplastic ===
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"lipomas", "weight_gain", "difficulty_flying", "lethargy"},
        "description": "Benign fatty tumors common in overweight budgies, Amazons, and rose-breasted cockatoos.",
        "description_ja": "肥満のセキセイインコ、アマゾン、モモイロインコに多い良性脂肪腫瘍。",
        "urgency": "low",
        "recommended_tests": ["fine needle aspirate", "radiographs", "biopsy"],
    },
    {
        "name": "Internal Tumors (Neoplasia)",
        "name_ja": "内部腫瘍（腫瘍性疾患）",
        "symptoms": {"weight_loss", "abdominal_distension", "lethargy", "anorexia", "lameness", "abnormal_droppings"},
        "description": "Various malignant or benign tumors of internal organs including kidney, liver, and gonadal tumors.",
        "description_ja": "腎臓、肝臓、生殖腺を含む内臓の様々な悪性・良性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "biopsy", "CT scan", "CBC"],
    },
    {
        "name": "Xanthoma",
        "name_ja": "黄色腫",
        "symptoms": {"skin_lesions", "lipomas", "feather_loss"},
        "description": "Yellow fatty skin masses associated with hyperlipidemia; common on wing tips and keel.",
        "description_ja": "高脂血症に関連する黄色の脂肪性皮膚腫瘤。翼端と竜骨に多い。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "lipid panel", "dietary history"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"swelling", "skin_lesions", "weight_loss", "lethargy"},
        "description": "Malignant connective tissue tumor that can occur in skin or internal organs of parrots.",
        "description_ja": "オウム類の皮膚または内臓に発生する悪性結合組織腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs", "CT scan"],
    },
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"skin_lesions", "oral_plaques", "difficulty_eating", "weight_loss", "beak_deformity"},
        "description": "Malignant epithelial tumor occurring in the skin, beak, or oral cavity of parrots.",
        "description_ja": "オウム類の皮膚、嘴、口腔に発生する悪性上皮性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs", "CT scan"],
    },
    # === Respiratory ===
    {
        "name": "Tracheal Obstruction",
        "name_ja": "気管閉塞",
        "symptoms": {"respiratory_distress", "open_mouth_breathing", "voice_change", "cyanosis"},
        "description": "Blockage of the trachea by foreign body, granuloma, or mass causing acute respiratory distress.",
        "description_ja": "異物、肉芽腫、腫瘤による気管閉塞。急性呼吸困難を引き起こす。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "endoscopy", "CT scan"],
    },
    {
        "name": "Aspiration Pneumonia",
        "name_ja": "誤嚥性肺炎",
        "symptoms": {"respiratory_distress", "tail_bobbing", "lethargy", "anorexia", "nasal_discharge"},
        "description": "Pneumonia from aspiration of food or liquid into the airways, common during hand-feeding.",
        "description_ja": "挿し餌中に多い、食物や液体の気道への誤嚥による肺炎。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "tracheal wash", "culture and sensitivity"],
    },
    # === Endocrine ===
    {
        "name": "Hypothyroidism",
        "name_ja": "甲状腺機能低下症",
        "symptoms": {"weight_gain", "lethargy", "feather_abnormalities", "dry_flaky_skin", "obesity_related_signs"},
        "description": "Underactive thyroid gland causing metabolic slowdown; may contribute to obesity and poor feathering.",
        "description_ja": "甲状腺機能の低下による代謝減速。肥満や羽毛不良の一因となりうる。",
        "urgency": "moderate",
        "recommended_tests": ["thyroid hormone levels", "cholesterol", "CBC"],
    },
    {
        "name": "Adrenal Disease",
        "name_ja": "副腎疾患",
        "symptoms": {"feather_plucking", "polyuria", "polydipsia", "weight_loss", "lethargy"},
        "description": "Adrenal gland dysfunction causing hormonal imbalance; may present with feather picking and PU/PD.",
        "description_ja": "副腎機能障害によるホルモン異常。毛引きや多尿・多飲を呈することがある。",
        "urgency": "moderate",
        "recommended_tests": ["adrenal panel", "ACTH stimulation test", "biochemistry panel"],
    },
    # === Neurological ===
    {
        "name": "Avian Ganglioneuritis",
        "name_ja": "鳥類神経節炎",
        "symptoms": {"ataxia", "seizures", "paralysis", "regurgitation", "weight_loss"},
        "description": "Inflammatory disease of the peripheral nervous system; often associated with bornavirus.",
        "description_ja": "末梢神経系の炎症性疾患。ボルナウイルスと関連することが多い。",
        "urgency": "high",
        "recommended_tests": ["bornavirus PCR", "crop biopsy", "CSF analysis"],
    },
    {
        "name": "Epilepsy / Idiopathic Seizures",
        "name_ja": "てんかん・特発性けいれん",
        "symptoms": {"seizures", "ataxia", "tremors", "loss_of_consciousness"},
        "description": "Recurrent seizures without identifiable structural cause; diagnosis of exclusion.",
        "description_ja": "構造的原因が特定できない反復性けいれん。除外診断となる。",
        "urgency": "high",
        "recommended_tests": ["CBC", "biochemistry panel", "heavy metal screen", "CT/MRI"],
    },
    # === Cardiovascular ===
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"respiratory_distress", "exercise_intolerance", "lethargy", "abdominal_distension", "cyanosis"},
        "description": "Heart failure leading to fluid accumulation; associated with atherosclerosis in older parrots.",
        "description_ja": "心不全による体液貯留。高齢オウム類の動脈硬化と関連する。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "radiographs", "ECG", "cardiac biomarkers"],
    },
    {
        "name": "Pericardial Effusion",
        "name_ja": "心嚢液貯留",
        "symptoms": {"respiratory_distress", "lethargy", "exercise_intolerance", "cyanosis", "sudden_death"},
        "description": "Fluid accumulation around the heart compressing cardiac function.",
        "description_ja": "心臓周囲の液体貯留による心機能圧迫。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "radiographs", "pericardiocentesis", "cytology"],
    },
    # === Miscellaneous ===
    {
        "name": "Feather Cyst",
        "name_ja": "羽嚢腫",
        "symptoms": {"skin_lesions", "swelling", "feather_abnormalities"},
        "description": "Cystic mass formed when a growing feather fails to erupt through the skin follicle.",
        "description_ja": "成長中の羽毛が皮膚の毛包から突出できずに形成される嚢胞性腫瘤。",
        "urgency": "low",
        "recommended_tests": ["physical exam", "fine needle aspirate", "surgical excision"],
    },
    {
        "name": "Proventricular Dilatation (non-PDD causes)",
        "name_ja": "前胃拡張（PDD以外の原因）",
        "symptoms": {"regurgitation", "weight_loss", "undigested_seeds_in_droppings", "anorexia", "crop_stasis"},
        "description": "Proventricular enlargement from heavy metal toxicity, foreign body, or other non-bornavirus causes.",
        "description_ja": "重金属中毒、異物、ボルナウイルス以外の原因による前胃拡張。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "heavy metal screen", "fluoroscopy", "endoscopy"],
    },
    {
        "name": "Heat Stroke (Hyperthermia)",
        "name_ja": "熱中症（高体温症）",
        "symptoms": {"open_mouth_breathing", "wing_spreading", "lethargy", "seizures", "sudden_death"},
        "description": "Overheating from direct sunlight, poor ventilation, or high ambient temperature.",
        "description_ja": "直射日光、換気不良、高い環境温度による過熱。",
        "urgency": "emergency",
        "recommended_tests": ["body temperature", "CBC", "biochemistry panel"],
    },
    {
        "name": "Hypothermia",
        "name_ja": "低体温症",
        "symptoms": {"lethargy", "fluffed_feathers", "anorexia", "tremors", "loss_of_consciousness"},
        "description": "Dangerously low body temperature from cold exposure or severe illness.",
        "description_ja": "寒冷曝露や重篤な疾患による危険な低体温。",
        "urgency": "emergency",
        "recommended_tests": ["body temperature", "CBC", "blood glucose"],
    },
    {
        "name": "Night Fright (Thrashing Syndrome)",
        "name_ja": "夜間パニック症候群",
        "symptoms": {"feather_loss", "bleeding", "wing_droop", "fractures", "self_mutilation"},
        "description": "Sudden nocturnal panic causing birds to thrash in their cage, risking injury.",
        "description_ja": "突然の夜間パニックでケージ内で暴れ、外傷のリスクがある。",
        "urgency": "moderate",
        "recommended_tests": ["physical exam for injuries", "environmental assessment"],
    },
    {
        "name": "Chronic Rhinitis",
        "name_ja": "慢性鼻炎",
        "symptoms": {"nasal_discharge", "sneezing", "head_shaking", "respiratory_distress"},
        "description": "Persistent nasal inflammation from bacterial, fungal, or environmental irritants.",
        "description_ja": "細菌、真菌、環境刺激物による持続的な鼻腔の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["nasal flush culture", "radiographs", "CT scan"],
    },
    {
        "name": "Choanal Atresia / Choanal Slit Abnormality",
        "name_ja": "後鼻孔閉鎖・後鼻孔裂異常",
        "symptoms": {"nasal_discharge", "respiratory_distress", "oral_plaques", "sneezing"},
        "description": "Blunting or papillomatous changes of the choanal slit associated with vitamin A deficiency or infection.",
        "description_ja": "ビタミンA欠乏や感染に関連する後鼻孔裂の鈍化または乳頭腫性変化。",
        "urgency": "moderate",
        "recommended_tests": ["oral exam", "choanal culture", "vitamin A level"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"regurgitation", "diarrhea", "polyuria", "lethargy", "weight_loss", "seizures"},
        "description": "Zinc ingestion from galvanized cage wire, clips, or hardware causing GI and systemic toxicity.",
        "description_ja": "亜鉛メッキケージ金具やクリップからの亜鉛摂取による消化器・全身性中毒。",
        "urgency": "high",
        "recommended_tests": ["blood zinc levels", "radiographs", "CBC"],
    },
    {
        "name": "Metabolic Bone Disease",
        "name_ja": "代謝性骨疾患",
        "symptoms": {"fractures", "beak_deformity", "lameness", "muscle_weakness", "seizures"},
        "description": "Bone weakening from calcium, phosphorus, or vitamin D3 imbalance; common in growing chicks.",
        "description_ja": "カルシウム、リン、ビタミンD3の不均衡による骨の脆弱化。成長期の雛に多い。",
        "urgency": "moderate",
        "recommended_tests": ["radiographs", "ionized calcium", "phosphorus", "vitamin D3 level"],
    },
    {
        "name": "Allergic Respiratory Disease",
        "name_ja": "アレルギー性呼吸器疾患",
        "symptoms": {"respiratory_distress", "sneezing", "nasal_discharge", "conjunctivitis"},
        "description": "Hypersensitivity reaction to dust, dander, aerosols, or environmental allergens.",
        "description_ja": "粉塵、皮屑、エアロゾル、環境アレルゲンに対する過敏反応。",
        "urgency": "moderate",
        "recommended_tests": ["environmental history", "radiographs", "CBC with differential"],
    },
    {
        "name": "Gonadal Neoplasia",
        "name_ja": "生殖腺腫瘍",
        "symptoms": {"abdominal_distension", "lameness", "weight_loss", "feather_abnormalities", "cere_color_change"},
        "description": "Tumors of the ovary or testis causing hormonal changes and space-occupying effects.",
        "description_ja": "卵巣または精巣の腫瘍によるホルモン変化と占拠性効果。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "hormone panel", "exploratory surgery"],
    },
    {
        "name": "Splay Leg (Spraddle Leg)",
        "name_ja": "開脚症",
        "symptoms": {"lameness", "inability_to_perch", "muscle_weakness"},
        "description": "Lateral deviation of one or both legs in neonates from improper substrate or nutritional deficiency.",
        "description_ja": "不適切な床材や栄養不足による新生鳥の片脚または両脚の側方偏位。",
        "urgency": "moderate",
        "recommended_tests": ["physical exam", "radiographs", "nutritional assessment"],
    },
    {
        "name": "Psittacine Proventricular Worm (Spirurids)",
        "name_ja": "オウム目前胃寄生虫（旋尾線虫類）",
        "symptoms": {"weight_loss", "regurgitation", "anorexia", "undigested_seeds_in_droppings"},
        "description": "Spirurid nematode parasites in the proventriculus causing ulceration and wasting.",
        "description_ja": "前胃の旋尾線虫寄生による潰瘍形成と消耗。",
        "urgency": "moderate",
        "recommended_tests": ["fecal flotation", "endoscopy", "fecal wet mount"],
    },
    {
        "name": "Feather Folliculitis",
        "name_ja": "羽毛毛包炎",
        "symptoms": {"skin_lesions", "feather_loss", "abnormal_feathers", "swelling"},
        "description": "Bacterial or fungal infection of feather follicles causing painful, inflamed follicles.",
        "description_ja": "細菌または真菌による羽毛毛包の感染。疼痛を伴う毛包の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["skin biopsy", "culture", "cytology"],
    },
    {
        "name": "Hemorrhagic Syndrome / Coagulopathy",
        "name_ja": "出血性症候群・凝固障害",
        "symptoms": {"bleeding", "subcutaneous_hemorrhage", "bloody_droppings", "lethargy"},
        "description": "Abnormal bleeding tendency from liver disease, toxin exposure, or clotting factor deficiency.",
        "description_ja": "肝疾患、毒素曝露、凝固因子欠乏による異常出血傾向。",
        "urgency": "emergency",
        "recommended_tests": ["coagulation panel", "liver panel", "CBC", "heavy metal screen"],
    },
    {
        "name": "Polyfolliculosis",
        "name_ja": "多毛包症",
        "symptoms": {"abnormal_feathers", "skin_lesions", "feather_loss"},
        "description": "Multiple feathers growing from a single follicle, often seen in lovebirds and cockatoos.",
        "description_ja": "単一毛包から複数の羽毛が成長する状態。ボタンインコやオウムに多い。",
        "urgency": "low",
        "recommended_tests": ["skin biopsy", "histopathology"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "feather_loss": {"ja": "羽毛脱落", "en": "Feather loss"},
    "beak_deformity": {"ja": "嘴変形", "en": "Beak deformity"},
    "immunosuppression": {"ja": "免疫抑制", "en": "Immunosuppression"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "abnormal_feathers": {"ja": "異常羽毛", "en": "Abnormal feathers"},
    "regurgitation": {"ja": "吐き戻し", "en": "Regurgitation"},
    "undigested_seeds_in_droppings": {"ja": "便中未消化種子", "en": "Undigested seeds in droppings"},
    "crop_stasis": {"ja": "嗉嚢停滞", "en": "Crop stasis"},
    "ataxia": {"ja": "運動失調", "en": "Ataxia"},
    "seizures": {"ja": "けいれん", "en": "Seizures"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory distress"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal discharge"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "lime_green_droppings": {"ja": "黄緑色便", "en": "Lime green droppings"},
    "subcutaneous_hemorrhage": {"ja": "皮下出血", "en": "Subcutaneous hemorrhage"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "feather_abnormalities": {"ja": "羽毛異常", "en": "Feather abnormalities"},
    "bloody_droppings": {"ja": "血便", "en": "Bloody droppings"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "crusty_lesions_on_face": {"ja": "顔面の痂皮性病変", "en": "Crusty lesions on face"},
    "oral_plaques": {"ja": "口腔内プラーク", "en": "Oral plaques"},
    "cloacal_mass": {"ja": "総排泄腔腫瘤", "en": "Cloacal mass"},
    "difficulty_eating": {"ja": "摂食困難", "en": "Difficulty eating"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "torticollis": {"ja": "斜頸", "en": "Torticollis"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "tail_bobbing": {"ja": "尾振り呼吸", "en": "Tail bobbing"},
    "open_mouth_breathing": {"ja": "開口呼吸", "en": "Open mouth breathing"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "head_shaking": {"ja": "頭振り", "en": "Head shaking"},
    "cloacal_swelling": {"ja": "総排泄腔腫脹", "en": "Cloacal swelling"},
    "vent_soiling": {"ja": "肛門周囲汚染", "en": "Vent soiling"},
    "straining_to_defecate": {"ja": "排便困難", "en": "Straining to defecate"},
    "foot_swelling": {"ja": "足の腫脹", "en": "Foot swelling"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "reluctance_to_perch": {"ja": "止まり木に乗りたがらない", "en": "Reluctance to perch"},
    "voice_change": {"ja": "声の変化", "en": "Voice change"},
    "white_patches_in_mouth": {"ja": "口腔内白斑", "en": "White patches in mouth"},
    "dry_flaky_skin": {"ja": "乾燥落屑性皮膚", "en": "Dry flaky skin"},
    "polyuria": {"ja": "多尿", "en": "Polyuria"},
    "muscle_weakness": {"ja": "筋力低下", "en": "Muscle weakness"},
    "egg_binding": {"ja": "卵塞", "en": "Egg binding"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "abnormal_droppings": {"ja": "異常便", "en": "Abnormal droppings"},
    "beak_overgrowth": {"ja": "嘴過長", "en": "Beak overgrowth"},
    "joint_swelling": {"ja": "関節腫脹", "en": "Joint swelling"},
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise intolerance"},
    "polydipsia": {"ja": "多飲", "en": "Polydipsia"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "lipomas": {"ja": "脂肪腫", "en": "Lipomas"},
    "difficulty_flying": {"ja": "飛行困難", "en": "Difficulty flying"},
    "feather_plucking": {"ja": "羽毛むしり", "en": "Feather plucking"},
    "self_mutilation": {"ja": "自傷行為", "en": "Self-mutilation"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "screaming": {"ja": "叫び", "en": "Screaming"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "stereotypic_behavior": {"ja": "常同行動", "en": "Stereotypic behavior"},
    "wing_droop": {"ja": "翼下垂", "en": "Wing droop"},
    "inability_to_fly": {"ja": "飛行不能", "en": "Inability to fly"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "pain_vocalization": {"ja": "疼痛発声", "en": "Pain vocalization"},
    "vision_loss": {"ja": "視力喪失", "en": "Vision loss"},
    "eye_cloudiness": {"ja": "眼の混濁", "en": "Eye cloudiness"},
    "clumsiness": {"ja": "動作のぎこちなさ", "en": "Clumsiness"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "fluffed_feathers": {"ja": "羽毛膨らませ", "en": "Fluffed feathers"},
    "loss_of_consciousness": {"ja": "意識消失", "en": "Loss of consciousness"},
    "wing_spreading": {"ja": "翼を広げる", "en": "Wing spreading"},
    "hyperactivity": {"ja": "過活動", "en": "Hyperactivity"},
    "inability_to_perch": {"ja": "止まり木に止まれない", "en": "Inability to perch"},
    "cere_color_change": {"ja": "蝋膜の色変化", "en": "Cere color change"},
    "obesity_related_signs": {"ja": "肥満関連徴候", "en": "Obesity-related signs"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species)
