# ============================================================================
# Species Prevalence Data for Stepwise Differential Diagnosis
# ============================================================================
# This module provides prevalence classifications for diseases across 19 species
# Based on veterinary epidemiology and clinical practice patterns
#
# Tiers:
# - very_common (1.4x): Diseases seen daily/weekly (parasites, respiratory, GI)
# - common (1.2x): Diseases seen regularly (endocrine, neoplasia, systemic)
# - uncommon (0.9x): Occasional presentations (breed-specific, genetic)
# - rare (0.7x): Rarely encountered (exotic conditions, syndromes)
#
# DATA SOURCES:
# - Primary: Ettinger & Feldman (2017), Nelson & Couto (2019),
#   Quesenberry & Carpenter (2020), Mader & Divers (2019)
# - Epidemiological: O'Neill et al. (2013) UK dog populations,
#   BanfieldPet Hospital State of Pet Health Reports (2019-2024)
# - Japanese context: 犬と猫の治療薬ガイド EduOne (2024),
#   日本獣医師会 小動物臨床部会 症例統計
#
# LIMITATIONS:
# - Prevalence tiers are primarily based on English-language veterinary
#   literature and may not fully reflect regional differences (e.g.,
#   heartworm is common in Japan but rare in the UK).
# - Exotic species prevalence is less well-documented and relies heavily
#   on clinical experience rather than epidemiological studies.
# - Tiers represent general clinical frequency, not population prevalence.
#
# IMPORTANT: Disease names must EXACTLY match the "name" field in the
# corresponding species disease module (api/species/*_diseases.py).
# ============================================================================

SPECIES_PREVALENCE = {
    # ==================================================================
    # DOG — 50 entries
    # ==================================================================
    "dog": {
        # very_common — daily/weekly presentations
        "Ear Infection (Otitis)": "very_common",
        "Periodontal Disease": "very_common",
        "Allergic Dermatitis": "very_common",
        "Flea Allergy Dermatitis": "very_common",
        "Gastroenteritis": "very_common",
        "Intestinal Parasites": "very_common",
        "Osteoarthritis": "very_common",
        "Pyoderma": "very_common",
        "Mange (Demodex/Sarcoptes)": "very_common",
        # common — regular presentations
        "Urinary Tract Infection": "common",
        "Hypothyroidism": "common",
        "Cushing's Disease": "common",
        "Diabetes Mellitus": "common",
        "Pancreatitis": "common",
        "Gastric Dilatation-Volvulus (GDV/Bloat)": "common",
        "Intervertebral Disc Disease (IVDD)": "common",
        "Cruciate Ligament Injury": "common",
        "Canine Parvovirus": "common",
        "Kennel Cough (Bordetella)": "common",
        "Leptospirosis": "common",
        "Pyometra": "common",
        "Mammary Tumor": "common",
        "Lymphoma": "common",
        "Mast Cell Tumor": "common",
        "Hemangiosarcoma": "common",
        "Cataracts": "common",
        "Glaucoma": "common",
        "Epilepsy": "common",
        "Kidney Disease (CKD)": "common",
        "Heart Disease/CHF": "common",
        "Mitral Valve Disease (MMVD)": "common",
        "Dilated Cardiomyopathy (DCM)": "common",
        "Patellar Luxation": "common",
        "Hip Dysplasia": "common",
        "Heartworm Disease": "common",
        "Corneal Ulcer": "common",
        "Cherry Eye": "common",
        "Inflammatory Bowel Disease (IBD)": "common",
        "Anal Sac Disease": "common",
        "Foreign Body Obstruction": "common",
        "Tracheal Collapse": "common",
        "Lyme Disease": "common",
        # uncommon
        "Addison's Disease": "uncommon",
        "Megaesophagus": "uncommon",
        "Exocrine Pancreatic Insufficiency (EPI)": "uncommon",
        "Immune-Mediated Hemolytic Anemia": "uncommon",
        "Autoimmune Thrombocytopenia (ITP)": "uncommon",
        "Myasthenia Gravis": "uncommon",
        "Systemic Lupus Erythematosus (SLE)": "uncommon",
        # rare
        "Portosystemic Shunt (Liver Shunt)": "rare",
        "Pheochromocytoma": "rare",
        "Insulinoma": "rare",
        # --- Expanded dog entries (523 additional) ---
        "Acanthomatous Ameloblastoma": "uncommon",
        "Acetaminophen Toxicosis": "common",
        "Acral Lick Dermatitis": "very_common",
        "Alopecia X": "uncommon",
        "Anal Sac Adenocarcinoma": "uncommon",
        "Anaplasmosis": "uncommon",
        "Anticoagulant Rodenticide Toxicosis": "common",
        "Aortic Stenosis": "uncommon",
        "Aspiration Pneumonia": "common",
        "Atrial Fibrillation": "uncommon",
        "Aural Hematoma": "common",
        "Babesiosis": "uncommon",
        "Benign Prostatic Hyperplasia": "common",
        "Brachycephalic Airway Syndrome": "common",
        "Brain Tumor": "uncommon",
        "Boxer Arrhythmogenic Right Ventricular Cardiomyopathy": "common",
        "Caffeine Toxicosis": "common",
        "Canine Atopic Dermatitis": "very_common",
        "Canine Cognitive Dysfunction Syndrome": "common",
        "Canine Distemper": "common",
        "Canine Infectious Hepatitis": "common",
        "Canine Papillomatosis": "common",
        "Cavalier King Charles Spaniel Mitral Valve Disease (Early-Onset)": "common",
        "Chocolate Toxicosis": "common",
        "Chronic Bronchitis": "common",
        "Chronic Hepatitis": "common",
        "Chronic Otitis Media": "very_common",
        "Chylothorax": "uncommon",
        "Cognitive Dysfunction Syndrome (CDS)": "common",
        "Colitis": "common",
        "Corneal Dystrophy": "common",
        "Cranial Cruciate Ligament Rupture": "common",
        "Cutaneous Histiocytoma": "common",
        "Degenerative Myelopathy": "uncommon",
        "Diabetic Ketoacidosis (DKA)": "uncommon",
        "Diaphragmatic Hernia": "uncommon",
        "Discospondylitis": "uncommon",
        "Disseminated Intravascular Coagulation (DIC)": "uncommon",
        "Doberman Dilated Cardiomyopathy (Occult)": "common",
        "Dystocia": "common",
        "Ear Mite Infestation (Otodectes)": "common",
        "Eclampsia (Milk Fever)": "common",
        "Ectropion": "common",
        "Ehrlichiosis": "uncommon",
        "Elbow Dysplasia": "common",
        "Entropion": "common",
        "Esophageal Foreign Body": "common",
        "Ethylene Glycol Poisoning (Antifreeze)": "uncommon",
        "Eye Infection (Conjunctivitis)": "very_common",
        "Fear Aggression": "common",
        "Fibrosarcoma": "uncommon",
        "Gallbladder Mucocele": "uncommon",
        "Gastric Foreign Body": "common",
        "Grape/Raisin Toxicosis": "common",
        "Hemorrhagic Gastroenteritis (HGE)": "very_common",
        "Histiocytic Sarcoma": "rare",
        "Hookworm Infection": "very_common",
        "Horner's Syndrome": "uncommon",
        "Hydrocephalus": "uncommon",
        "Immune-Mediated Hemolytic Anemia (IMHA)": "uncommon",
        "Immune-Mediated Polyarthritis": "uncommon",
        "Inner Ear Infection (Otitis Interna)": "very_common",
        "Keratoconjunctivitis Sicca (Dry Eye)": "very_common",
        "Laryngeal Paralysis": "uncommon",
        "Lens Luxation": "common",
        "Malassezia Dermatitis": "very_common",
        "Marijuana Toxicosis": "common",
        "Masticatory Muscle Myositis": "uncommon",
        "Medial Patellar Luxation": "common",
        "Melanoma": "uncommon",
        "Meningioma": "uncommon",
        "Mushroom Toxicosis": "common",
        "NSAID Toxicosis": "common",
        "Nasal Tumor": "uncommon",
        "Nictitans Gland Prolapse (Cherry Eye)": "common",
        "Noise Phobia": "common",
        "Oral Melanoma": "uncommon",
        "Oral Papillomatosis": "common",
        "Osteosarcoma": "uncommon",
        "Panosteitis": "uncommon",
        "Patent Ductus Arteriosus (PDA)": "uncommon",
        "Pemphigus Foliaceus": "uncommon",
        "Perianal Fistula": "uncommon",
        "Pericardial Effusion": "uncommon",
        "Perineal Hernia": "uncommon",
        "Pneumonia": "common",
        "Progressive Retinal Atrophy (PRA)": "uncommon",
        "Prostatic Abscess": "common",
        "Protein-Losing Enteropathy (PLE)": "uncommon",
        "Pulmonary Hypertension": "uncommon",
        "Pyelonephritis": "common",
        "Rabies": "uncommon",
        "Rodenticide Poisoning": "common",
        "Roundworm Infection (Toxocara)": "common",
        "Sago Palm Toxicosis": "common",
        "Salmon Poisoning Disease": "common",
        "Sarcoptic Mange (Scabies)": "common",
        "Separation Anxiety": "common",
        "Snail Bait (Metaldehyde) Poisoning": "common",
        "Splenic Hemangiosarcoma": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Steroid-Responsive Meningitis-Arteritis (SRMA)": "uncommon",
        "Tapeworm Infection (Dipylidium/Echinococcus)": "common",
        "Testicular Tumor": "common",
        "Thyroid Carcinoma": "uncommon",
        "Tick Paralysis": "common",
        "Tooth Abscess": "common",
        "Tooth Fracture": "common",
        "Transitional Cell Carcinoma": "uncommon",
        "Uterine Stump Pyometra": "common",
        "Vestibular Disease": "common",
        "Vitamin D Toxicosis": "common",
        "Whipworm Infection (Trichuris)": "common",
        "Xylitol Toxicosis": "common",
        "Zinc Toxicosis": "common",
        "von Willebrand Disease": "uncommon",
    },

    # ==================================================================
    # CAT — 230+ entries (expanded from ~73)
    # ==================================================================
    "cat": {
        # very_common
        "Feline Upper Respiratory Infection": "very_common",
        "Feline Herpesvirus (FHV-1) Infection": "very_common",
        "Feline Calicivirus Infection": "very_common",
        "Feline Panleukopenia (Feline Distemper)": "very_common",
        "Feline Leukemia Virus (FeLV)": "very_common",
        "Feline Immunodeficiency Virus (FIV)": "very_common",
        "Gastroenteritis": "very_common",
        "Intestinal Parasitism": "very_common",
        "Feline Otitis Externa": "very_common",
        "Urinary Tract Infection (UTI)": "very_common",
        "Flea Allergy Dermatitis": "very_common",
        "Feline Lower Urinary Tract Disease (FLUTD)": "very_common",
        "Feline Idiopathic Cystitis (FIC)": "very_common",
        "Hyperthyroidism": "very_common",
        "Chronic Kidney Disease (CKD)": "very_common",
        "Periodontal Disease": "very_common",
        "Roundworm Infection (Toxocara cati)": "very_common",
        "Tapeworm Infection (Dipylidium caninum)": "very_common",
        "Ear Mite Infestation (Otodectes cynotis)": "very_common",
        "Flea Infestation": "very_common",
        "Dermatophytosis (Ringworm)": "very_common",
        # common
        "Feline Chlamydiosis": "common",
        "Constipation / Obstipation": "common",
        "Megacolon": "common",
        "Corneal Ulcer": "common",
        "Hepatic Lipidosis (Fatty Liver Disease)": "common",
        "Diabetes Mellitus": "common",
        "Systemic Hypertension": "common",
        "Hypertrophic Cardiomyopathy (HCM)": "common",
        "Feline Asthma": "common",
        "Feline Chronic Gingivostomatitis": "common",
        "Alimentary Lymphoma": "common",
        "Mammary Tumor": "common",
        "Hypothyroidism (Iatrogenic)": "common",
        "Feline Anterior Uveitis": "common",
        "Inflammatory Bowel Disease (IBD)": "common",
        "Feline Pancreatitis": "common",
        "Feline Tooth Resorption (FORL)": "common",
        "Conjunctivitis": "common",
        "Atopic Dermatitis": "common",
        "Food Allergy Dermatitis": "common",
        "Urolithiasis (Bladder Stones)": "common",
        "Gastrointestinal Lymphoma": "common",
        "Feline Epilepsy": "common",
        "Osteoarthritis (Degenerative Joint Disease)": "common",
        "Dilated Cardiomyopathy (DCM)": "common",
        "Squamous Cell Carcinoma (Oral)": "common",
        "Squamous Cell Carcinoma (Cutaneous)": "common",
        "Injection-Site Sarcoma (Fibrosarcoma)": "common",
        "Feline Heartworm Disease": "common",
        "Cholangitis / Cholangiohepatitis": "common",
        "Miliary Dermatitis": "common",
        "Psychogenic Alopecia": "common",
        "Hookworm Infection": "common",
        "Giardiasis": "common",
        "Coccidia Infection": "common",
        # uncommon
        "Feline Infectious Peritonitis (FIP) - Wet Form": "uncommon",
        "Feline Infectious Peritonitis (FIP) - Dry Form": "uncommon",
        "Aortic Thromboembolism (Saddle Thrombus)": "uncommon",
        "Renal Lymphoma": "uncommon",
        "Feline Interstitial Nephritis": "uncommon",
        "Feline Glomerulonephritis": "uncommon",
        "Diabetic Ketoacidosis (DKA)": "uncommon",
        "Polycystic Kidney Disease (PKD)": "uncommon",
        "Immune-Mediated Hemolytic Anemia (IMHA)": "uncommon",
        "Pemphigus Foliaceus": "uncommon",
        "Restrictive Cardiomyopathy": "uncommon",
        "Pericardial Effusion": "uncommon",
        # rare
        "Amyloidosis": "rare",
        "Hyperaldosteronism (Conn's Syndrome)": "rare",
        "Acromegaly (Hypersomatotropism)": "rare",
        "Portosystemic Shunt": "rare",
        "Myasthenia Gravis": "rare",
        # --- Expanded cat entries (80+ additional) ---
        # very_common
        "Gingivitis and Periodontal Disease": "very_common",
        "Cat Bite Abscess": "very_common",
        "Foreign Body Obstruction": "very_common",
        "Feline Acne": "very_common",
        "Feline Chronic Vomiting (Idiopathic)": "very_common",
        "Feline Gastric Hairball Obstruction": "very_common",
        "Feline Linear Foreign Body": "very_common",
        "Feline Litter Box Aversion": "very_common",
        "Territorial Marking / Urine Spraying": "very_common",
        # common — seen monthly
        "Asthma": "common",
        "Chronic Kidney Disease": "common",
        "Chronic Rhinosinusitis": "common",
        "Cataracts": "common",
        "Feline Anxiety Disorder": "common",
        "Feline Cognitive Dysfunction Syndrome": "common",
        "Feline Herpesviral Keratitis": "common",
        "Feline Chronic Bronchitis": "common",
        "Feline Chronic Colitis": "common",
        "Feline Chronic Pancreatitis": "common",
        "Feline Eosinophilic Keratoconjunctivitis": "common",
        "Eosinophilic Granuloma Complex - Eosinophilic Plaque": "common",
        "Eosinophilic Granuloma Complex - Eosinophilic Ulcer": "common",
        "Eosinophilic Granuloma Complex - Linear Granuloma": "common",
        "Feline Oral Eosinophilic Granuloma": "common",
        "Feline Malassezia Dermatitis": "common",
        "Feline Cheyletiellosis (Walking Dandruff)": "common",
        "Feline Symmetric Alopecia": "common",
        "Feline Tail Gland Hyperplasia (Stud Tail)": "common",
        "Feline Anal Sac Disease": "common",
        "Feline Aural Hematoma": "common",
        "Entropion": "common",
        "Glaucoma": "common",
        "Retinal Detachment": "common",
        "Hypertensive Retinopathy": "common",
        "Feline Iris Melanosis": "common",
        "Tooth Root Abscess": "common",
        "Nasopharyngeal Polyp": "common",
        "Feline Nasal Polyp": "common",
        "Heartworm-Associated Respiratory Disease (HARD)": "common",
        "Pyometra": "common",
        "Dystocia (Difficult Birth)": "common",
        "Cryptorchidism": "common",
        "Mammary Hyperplasia (Fibroadenomatous Change)": "common",
        "Feline Mammary Carcinoma (Triple Negative)": "common",
        "Mast Cell Tumor (Cutaneous)": "common",
        "Feline Congestive Heart Failure": "common",
        "Feline Arterial Hypertension (Secondary)": "common",
        "Pica": "common",
        "Redirected Aggression": "common",
        "Separation Anxiety": "common",
        "Feline Hyperesthesia Syndrome": "common",
        "Triaditis": "common",
        "Feline Neutrophilic Cholangitis": "common",
        "Feline Lymphocytic Cholangitis": "common",
        "Feline Struvite Urolithiasis": "common",
        "Feline Calcium Oxalate Urolithiasis": "common",
        "Urinary Obstruction (Blocked Cat)": "common",
        "Feline Urethral Plug": "common",
        "Acute Kidney Injury (AKI)": "common",
        "Lily Toxicosis": "common",
        "Permethrin Toxicosis": "common",
        "Rodenticide Poisoning (Anticoagulant)": "common",
        "Acetaminophen (Paracetamol) Toxicosis": "common",
        "Feline Pyrethroid Toxicosis (Topical)": "common",
        "Fracture": "common",
        "High-Rise Syndrome": "common",
        # uncommon — several times per year
        "FIP Neurological Form": "uncommon",
        "Feline Infectious Anemia (Hemoplasma)": "uncommon",
        "Mycoplasma haemofelis Infection (Feline Infectious Anemia)": "uncommon",
        "Cryptococcosis": "uncommon",
        "Toxoplasmosis": "uncommon",
        "Feline Congenital Portosystemic Shunt": "uncommon",
        "Feline Hepatic Amyloidosis": "uncommon",
        "Chylothorax": "uncommon",
        "Pleural Effusion": "uncommon",
        "Pyothorax": "uncommon",
        "Feline Pneumothorax": "uncommon",
        "Diaphragmatic Hernia": "uncommon",
        "Mediastinal Lymphoma": "uncommon",
        "Nasal Lymphoma": "uncommon",
        "Hepatic Lymphoma": "uncommon",
        "Large Granular Lymphocyte Lymphoma": "uncommon",
        "Meningioma": "uncommon",
        "Osteosarcoma": "uncommon",
        "Basal Cell Tumor": "uncommon",
        "Feline Cutaneous Lymphoma": "uncommon",
        "Feline Fibrosarcoma (Non-Injection Site)": "uncommon",
        "Hemangiosarcoma": "uncommon",
        "Feline Oral Squamous Cell Carcinoma (Sublingual)": "uncommon",
        "Feline Squamous Cell Carcinoma (Nasal Planum)": "uncommon",
        "Intestinal Adenocarcinoma": "uncommon",
        "Feline Pancreatic Adenocarcinoma": "uncommon",
        "Feline Taurine Deficiency Cardiomyopathy": "uncommon",
        "Feline Hypertrophic Cardiomyopathy (Obstructive)": "uncommon",
        "Feline Mitral Valve Disease": "uncommon",
        "Corneal Sequestrum": "uncommon",
        "Feline Dry Eye (Keratoconjunctivitis Sicca)": "uncommon",
        "Feline Idiopathic Vestibular Disease": "uncommon",
        "Vestibular Disease": "uncommon",
        "Feline Audiogenic Reflex Seizures (FARS)": "uncommon",
        "Feline Status Epilepticus": "uncommon",
        "Feline Megaesophagus": "uncommon",
        "Feline Idiopathic Megacolon": "uncommon",
        "Feline Toxic Megacolon": "uncommon",
        "Immune-Mediated Polyarthritis": "uncommon",
        "Immune-Mediated Thrombocytopenia (ITP)": "uncommon",
        "Feline Exocrine Pancreatic Insufficiency (EPI)": "uncommon",
        "Ethylene Glycol (Antifreeze) Poisoning": "uncommon",
        "NSAID Toxicosis": "uncommon",
        "Feline Onion/Garlic Toxicosis": "uncommon",
        "Feline Marijuana Toxicosis": "uncommon",
        "Essential Oil Toxicosis": "uncommon",
        "Hypokalemic Polymyopathy": "uncommon",
        "Nutritional Secondary Hyperparathyroidism": "uncommon",
        "Thiamine Deficiency (Vitamin B1)": "uncommon",
        "Feline Stomatitis (Non-Lymphoplasmacytic)": "uncommon",
        "Feline Protein-Losing Enteropathy": "uncommon",
        "Pyelonephritis": "uncommon",
        "Feline Ureteral Obstruction": "uncommon",
        "Feline Bordetellosis": "uncommon",
        "Feline Pneumonia": "uncommon",
        "Feline Pulmonary Edema": "uncommon",
        "Feline Compulsive Disorder": "uncommon",
        "Feline Night Vocalization Syndrome": "uncommon",
        "Cerebellar Hypoplasia": "uncommon",
        "Hydrocephalus": "uncommon",
        "Hip Dysplasia": "uncommon",
        "Luxating Patella": "uncommon",
        "Scottish Fold Osteochondrodysplasia": "uncommon",
        # rare — <0.5% prevalence
        "Feline Primary Hyperaldosteronism (Conn's Syndrome)": "rare",
        "Feline Pheochromocytoma": "rare",
        "Insulinoma": "rare",
        "Hyperadrenocorticism (Cushing's Disease)": "rare",
        "Hypoadrenocorticism (Addison's Disease)": "rare",
        "Feline Hyperparathyroidism (Primary)": "rare",
        "Feline Pituitary Dwarfism": "rare",
        "Pituitary Tumor": "rare",
        "Feline Acquired Myasthenia Gravis": "rare",
        "Systemic Lupus Erythematosus (SLE)": "rare",
        "Feline Degenerative Myelopathy": "rare",
        "Feline Ischemic Encephalopathy": "rare",
        "Dysautonomia (Key-Gaskell Syndrome)": "rare",
        "Plague (Yersinia pestis)": "rare",
        "Tularemia": "rare",
        "Feline Leishmaniasis": "rare",
        "Feline Leptospirosis": "rare",
        "Rabies": "rare",
        "Feline Botulism": "rare",
        "Cytauxzoon felis (Acute Cytauxzoonosis)": "rare",
        "Feline Hemophilia A": "rare",
        "Feline von Willebrand Disease": "rare",
        "Disseminated Intravascular Coagulation (DIC)": "rare",
        "Feline Pythiosis": "rare",
        "Feline Histoplasmosis": "rare",
        "Sporotrichosis": "rare",
        "Lissencephaly": "rare",
        "Manx Syndrome": "rare",
        "Polydactyly": "rare",
    },

    # ==================================================================
    # RABBIT — 35+ entries (expanded from ~23)
    # ==================================================================
    "rabbit": {
        # very_common
        "Gastrointestinal Stasis": "very_common",
        "Dental Malocclusion": "very_common",
        "Molar Spurs": "very_common",
        "Incisor Overgrowth": "very_common",
        "Pasteurellosis (Snuffles)": "very_common",
        "Upper Respiratory Infection": "very_common",
        "Coccidiosis (Intestinal)": "very_common",
        "Hepatic Coccidiosis": "very_common",
        "Otitis Externa": "very_common",
        "Dermatophytosis (Ringworm)": "very_common",
        "Conjunctivitis": "very_common",
        "Pinworms (Passalurus ambiguus)": "very_common",
        "Fur Mites (Cheyletiella parasitovorax)": "very_common",
        "Ear Mites (Psoroptes cuniculi)": "very_common",
        # common
        "Encephalitozoon cuniculi (E. cuniculi)": "common",
        "Myxomatosis": "common",
        "Rabbit Haemorrhagic Disease (RHDV/VHD)": "common",
        "RHDV2": "common",
        "Uterine Adenocarcinoma": "common",
        "Pododermatitis (Sore Hocks)": "common",
        "Vestibular Disease": "common",
        "Otitis Media / Interna": "common",
        "Subcutaneous Abscess": "common",
        "Tooth Root Abscess": "common",
        "Urinary Sludge": "common",
        "Urolithiasis (Bladder Stones)": "common",
        "Trichobezoar (Hairball)": "common",
        "Obesity": "common",
        "Intestinal Coccidiosis": "common",
        "Myiasis (Flystrike)": "common",
        "Pyometra": "common",
        "Hind Limb Paresis / Paralysis": "common",
        # uncommon
        "Treponematosis (Rabbit Syphilis)": "uncommon",
        "Bordetella Infection": "uncommon",
        "Mycoplasmosis": "uncommon",
        "Megacolon": "uncommon",
        "Ileus (Paralytic)": "uncommon",
        "Colonic Impaction": "uncommon",
        "Sarcoptic Mange": "uncommon",
        "Thymoma": "uncommon",
        "Lymphoma": "uncommon",
        # rare
        "Klebsiella Pneumonia": "rare",
        "Cecoliths": "rare",
        "Pulmonary Edema": "rare",
        "Pulmonary Fibrosis": "rare",
        "Pyothorax": "rare",
        "Cecal Tympany": "rare",
        # --- Expanded rabbit entries ---
        "Cheek Tooth Overgrowth": "very_common",
        "Barbering (Fur Chewing)": "very_common",
        "Cecotrophy Disorders": "very_common",
        "Alopecia (Non-specific)": "very_common",
        "Constipation": "common",
        "Corneal Ulcer": "common",
        "Cataracts": "common",
        "Chronic Kidney Disease": "common",
        "Clostridial Enterotoxemia": "common",
        "Colitis": "common",
        "Cystitis": "common",
        "Diarrhea (Acute)": "common",
        "Heatstroke": "common",
        "Mastitis": "common",
        "Dehydration": "common",
        "Snuffles (Bordetella)": "common",
        "Bladder Sludge (Hypercalciuria)": "common",
        "Cuterebra (Bot Fly Larva)": "uncommon",
        "Congestive Heart Failure": "uncommon",
        "Hepatic Lipidosis": "uncommon",
        "Dystocia": "uncommon",
        "Splenic Torsion": "rare",
        "Chordoma": "rare",
        "Buphthalmia (Congenital Glaucoma)": "rare",
        "Cerebellar Hypoplasia": "rare",
        # --- Additional rabbit entries ---
        "Encephalitozoonosis": "very_common",
        "Cheyletiella Mange (Fur Mites)": "very_common",
        "Dental Abscess": "very_common",
        "Dental Fistula": "common",
        "Periodontal Disease": "common",
        "E. coli Enteritis": "common",
        "Mucoid Enteropathy": "common",
        "Giardiasis": "common",
        "Bordetella Bronchiseptica Infection": "common",
        "Dewlap Fold Dermatitis": "common",
        "Red Urine (Non-pathological)": "common",
        "Urine Scald": "common",
        "Pseudopregnancy": "common",
        "Hutch Burn": "common",
        "Nail Overgrowth": "common",
        "Flystrike (Myiasis)": "common",
        "Rhinitis": "common",
        "Staphylococcal Dermatitis": "uncommon",
        "Enterotoxemia": "uncommon",
        "Diabetes Mellitus": "uncommon",
        "Endometrial Hyperplasia": "uncommon",
        "Rabbit Hemorrhagic Disease (RHD)": "uncommon",
        "Tyzzer's Disease": "rare",
        "Rabbit Poxvirus Infection": "rare",
    },

    # ==================================================================
    # BIRD — 28+ entries (expanded from ~16)
    # ==================================================================
    "bird": {
        # very_common
        "Psittacosis / Chlamydiosis": "very_common",
        "Aspergillosis": "very_common",
        "Feather Plucking (Feather Destructive Behavior)": "very_common",
        "Vitamin A Deficiency (Hypovitaminosis A)": "very_common",
        "Gastrointestinal Parasitic Disease": "very_common",
        "Candidiasis": "very_common",
        "Ingluvitis (Crop Infection)": "very_common",
        "Crop Stasis (Crop Slowdown)": "very_common",
        "E. coli Infection (Colibacillosis)": "very_common",
        "Dermatitis": "very_common",
        # common
        "Psittacine Beak and Feather Disease (PBFD)": "common",
        "Proventricular Dilatation Disease (PDD / Bornavirus)": "common",
        "Avian Polyomavirus": "common",
        "Megabacteriosis (Avian Gastric Yeast / AGY)": "common",
        "Egg Binding (Dystocia)": "common",
        "Articular Gout": "common",
        "Visceral Gout": "common",
        "Obesity": "common",
        "Sinusitis": "common",
        "Rhinitis": "common",
        "Hepatic Lipidosis (Fatty Liver Disease)": "common",
        "Metabolic Bone Disease (MBD / Rickets)": "common",
        "Pododermatitis (Bumblefoot)": "common",
        "Pneumonia": "common",
        "Lymphoma": "common",
        "Calcium Deficiency (Hypocalcemia)": "common",
        "Air Sacculitis": "common",
        "Enteritis": "common",
        # uncommon
        "Avian Bornavirus (ABV)": "uncommon",
        "Hemochromatosis (Iron Storage Disease)": "uncommon",
        "Newcastle Disease": "uncommon",
        "Cryptococcosis": "uncommon",
        "Cloacal Prolapse": "uncommon",
        # --- Expanded bird entries ---
        "Avian Pox": "very_common",
        "Scaly Face/Leg Mite (Knemidocoptes)": "very_common",
        "Giardiasis": "very_common",
        "Trichomoniasis (Canker)": "very_common",
        "Pacheco's Disease (Herpesvirus)": "common",
        "Crop Burns (Thermal Injury)": "common",
        "Avian Mycobacteriosis": "common",
        "Renal Disease": "common",
        "Goiter (Thyroid Hyperplasia / Iodine Deficiency)": "common",
        "Cloacitis": "common",
        "Xanthoma": "common",
        "Papillomatosis": "common",
        "Feather Cyst": "common",
        "Zinc Toxicosis (Heavy Metal Poisoning)": "common",
        "Lead Poisoning": "common",
        "Atherosclerosis": "common",
        "Ovarian Tumor": "uncommon",
        "Renal Tumor": "uncommon",
        "Choanal Atresia": "uncommon",
        "Avian Influenza": "rare",
        "Fibrosarcoma": "rare",
        # --- Additional bird entries ---
        "Roundworm (Ascaridia)": "very_common",
        "Lice (Mallophaga)": "very_common",
        "Red Mite (Dermanyssus)": "very_common",
        "Feather Mites": "very_common",
        "Egg Binding": "common",
        "Egg Peritonitis": "common",
        "Chronic Egg Laying": "common",
        "Salpingitis": "common",
        "Iron Storage Disease (Hemochromatosis)": "common",
        "Fatty Liver Disease": "common",
        "Tracheal Mite (Sternostoma)": "common",
        "Capillaria (Hairworm)": "common",
        "Syngamus (Gapeworm)": "common",
        "Fracture (Wing)": "common",
        "Fracture (Leg)": "common",
        "Night Fright Injury": "common",
        "Crop Impaction": "common",
        "Foreign Body Ingestion": "common",
        "Psittacosis (Chlamydiosis)": "common",
        "Salmonellosis": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Lipoma": "uncommon",
        "Pituitary Tumor": "uncommon",
        "Testicular Tumor": "uncommon",
        "Hepatocellular Carcinoma": "rare",
        "Hemangiosarcoma": "rare",
    },

    # ==================================================================
    # REPTILE — 22+ entries (expanded from ~12)
    # ==================================================================
    "reptile": {
        # very_common
        "Metabolic Bone Disease (MBD)": "very_common",
        "Upper Respiratory Infection (URI)": "very_common",
        "Lower Respiratory Infection (Pneumonia)": "very_common",
        "Internal Parasites (Nematodes)": "very_common",
        "Dysecdysis (Retained Shed)": "very_common",
        "Shell Rot (Ulcerative Shell Disease)": "very_common",
        "Vitamin A Deficiency (Hypovitaminosis A)": "very_common",
        "External Mites (Ophionyssus)": "very_common",
        "Dehydration": "very_common",
        # common
        "Infectious Stomatitis (Mouth Rot)": "common",
        "Gastrointestinal Impaction": "common",
        "Thermal Burns": "common",
        "Scale Rot (Ulcerative Dermatitis)": "common",
        "Egg Binding (Dystocia)": "common",
        "Pre-ovulatory Follicular Stasis": "common",
        "Subcutaneous Abscess": "common",
        "Coccidia Infection": "common",
        "Cryptosporidiosis": "common",
        "Rostral Abrasion (Nose Rub)": "common",
        "Pneumonia": "common",
        "Nutritional Secondary Hyperparathyroidism": "common",
        # uncommon
        "Articular Gout": "uncommon",
        "Visceral Gout": "uncommon",
        "Inclusion Body Disease (IBD)": "uncommon",
        "Septicemia (Blood Poisoning)": "uncommon",
        "Hepatic Lipidosis (Fatty Liver Disease)": "uncommon",
        # rare
        "Adenovirus Infection": "rare",
        "Paramyxovirus Infection": "rare",
        # --- Expanded reptile entries ---
        "Dermatitis (Bacterial)": "very_common",
        "Herpesvirus Infection": "common",
        "Cloacal Prolapse": "common",
        "Flagellate Protozoal Infection": "common",
        "Obesity": "common",
        "Aural Abscess (Ear Abscess)": "common",
        "Hypocalcemia": "common",
        "Osteomyelitis": "uncommon",
        "Renal Disease (Chronic)": "uncommon",
        "Hemipenal Prolapse": "uncommon",
        "Nematode Infection (Internal)": "very_common",
        "Fungal Dermatitis": "uncommon",
        "Hepatic Lipidosis": "uncommon",
        "Salmonellosis": "uncommon",
        "Neoplasia (General)": "uncommon",
        "Pentastomid Infection": "rare",
        "Chlamydiosis": "rare",
        "Mycobacteriosis": "rare",
        "Iridovirus Infection": "rare",
        "Intussusception": "rare",
        # --- Additional reptile entries ---
        "Stomatitis (Mouth Rot)": "very_common",
        "Mite Infestation (Ophionyssus)": "very_common",
        "Constipation": "very_common",
        "Substrate Impaction": "common",
        "Blister Disease": "common",
        "Gout (Articular)": "common",
        "Gout (Visceral)": "common",
        "Burns": "common",
        "Fracture (Limb)": "common",
        "Foreign Body Ingestion": "common",
        "Conjunctivitis": "common",
        "Corneal Ulcer": "common",
        "Bite Wounds": "common",
        "Spectacle Retention": "common",
        "Egg Yolk Coelomitis": "uncommon",
        "Hexamita Infection": "uncommon",
        "Lymphoma": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Fibrosarcoma": "uncommon",
        "Poxvirus Infection": "rare",
        "Sunshine Virus (Sunshinevirus)": "rare",
    },

    # ==================================================================
    # FISH — 25 entries (expanded from ~10)
    # ==================================================================
    "fish": {
        # very_common
        "Ichthyophthirius (White Spot Disease / Ich)": "very_common",
        "Columnaris Disease": "very_common",
        "Ammonia Poisoning": "very_common",
        "Swim Bladder Disorder": "very_common",
        "Aeromonas / Motile Aeromonad Septicemia": "very_common",
        "Saprolegnia (Water Mold / Cotton Wool Disease)": "very_common",
        "Nitrite Poisoning (Brown Blood Disease)": "very_common",
        "Skin Flukes (Gyrodactylus)": "very_common",
        "Marine Ich (Cryptocaryon irritans)": "very_common",
        # common
        "Dropsy (Pinecone Disease)": "common",
        "Velvet Disease (Oodinium / Piscinoodinium)": "common",
        "Anchor Worm (Lernaea)": "common",
        "Gill Flukes (Dactylogyrus)": "common",
        "Hexamita / Spironucleus (Internal Flagellates)": "common",
        "Costia (Ichthyobodo)": "common",
        "Fish Lice (Argulus)": "common",
        "Hole-in-the-Head Disease (HITH / HLLE)": "common",
        "Trichodina": "common",
        "pH Shock": "common",
        # uncommon
        "Lymphocystis": "uncommon",
        "Neon Tetra Disease (Pleistophora)": "uncommon",
        "Mycobacteriosis (Fish Tuberculosis)": "uncommon",
        "Egg Binding (Dystocia)": "uncommon",
        # rare
        "Koi Herpesvirus Disease (KHV / CyHV-3)": "rare",
        "Spring Viremia of Carp (SVC)": "rare",
    },

    # ==================================================================
    # HAMSTER — 25+ entries (expanded from ~12)
    # ==================================================================
    "hamster": {
        # very_common
        "Wet Tail (Proliferative Ileitis)": "very_common",
        "Cheek Pouch Impaction": "very_common",
        "Diarrhea (Non-specific)": "very_common",
        "Upper Respiratory Infection": "very_common",
        "Dental Malocclusion": "very_common",
        "Dental Overgrowth (Molar)": "very_common",
        "Flank Gland Dermatitis": "very_common",
        "Gastrointestinal Parasites": "very_common",
        "Demodex Mange": "very_common",
        # common
        "Diabetes Mellitus": "common",
        "Lymphoma": "common",
        "Dilated Cardiomyopathy": "common",
        "Pneumonia": "common",
        "Amyloidosis": "common",
        "Ringworm (Dermatophytosis)": "common",
        "Mammary Tumor": "common",
        "Skin Abscess": "common",
        "Conjunctivitis": "common",
        "Cataracts": "common",
        "Hibernation / Torpor": "common",
        "Intestinal Impaction": "common",
        "Obesity": "common",
        "Cheek Pouch Prolapse": "common",
        "Cystitis": "common",
        # uncommon
        "Cushing's Disease": "uncommon",
        "Congestive Heart Failure": "uncommon",
        "Chronic Renal Failure": "uncommon",
        "Hamster Polyomavirus": "uncommon",
        "Adrenal Tumor": "uncommon",
        # rare
        "Lymphocytic Choriomeningitis (LCMV)": "rare",
        # --- Expanded hamster entries ---
        "Cheek Pouch Abscess": "very_common",
        "Mite Infestation": "very_common",
        "Barbering (Fur Chewing)": "very_common",
        "Ear Infection": "common",
        "Rectal Prolapse": "common",
        "Heatstroke": "common",
        "Pyometra": "common",
        "Testicular Tumor": "common",
        "Skin Tumor": "common",
        "Tyzzer's Disease (Clostridium piliforme)": "common",
        "Intussusception": "common",
        "Uterine Tumor": "common",
        "Constipation": "common",
        "Hypothermia": "common",
        "Malocclusion (Incisor)": "common",
        "Abdominal Tumor": "uncommon",
        "Hepatic Lipidosis": "uncommon",
        "Chronic Renal Disease": "uncommon",
        "Atrial Thrombosis": "uncommon",
        "Hyperthyroidism": "rare",
        "Cerebellar Ataxia": "rare",
        # --- Additional hamster entries ---
        "Hamster Polyomavirus - Clinical Form": "very_common",
        "Chromodacryorrhea (Red Tears)": "very_common",
        "Cheek Pouch Eversion": "common",
        "Cheek Pouch Mycosis": "common",
        "Hibernation Attempt (Torpor)": "common",
        "Flank Gland Hyperplasia": "common",
        "Flank Gland Tumor": "common",
        "Corneal Ulcer": "common",
        "Pinworm Infection (Syphacia)": "common",
        "Helicobacter Gastritis": "common",
        "Scent Gland Infection": "common",
        "Exophthalmos": "common",
        "Fracture (Limb)": "common",
        "Exercise Wheel Injury": "common",
        "Bite Wounds": "common",
        "Mammary Adenocarcinoma": "uncommon",
        "Harderian Gland Tumor": "uncommon",
        "Pituitary Tumor": "uncommon",
        "Sendai Virus Infection": "uncommon",
        "Amyloidosis - Hepatic": "uncommon",
        "Tyzzer's Disease": "rare",
        "Cerebrovascular Accident (Stroke)": "rare",
        "Pneumocystis Pneumonia": "rare",
    },

    # ==================================================================
    # GUINEA PIG — 25+ entries (expanded from ~14)
    # ==================================================================
    "guinea_pig": {
        # very_common
        "Scurvy (Vitamin C Deficiency)": "very_common",
        "Upper Respiratory Infection (URI)": "very_common",
        "Bacterial Pneumonia": "very_common",
        "Dental Malocclusion": "very_common",
        "Intestinal Parasites": "very_common",
        "Otitis Externa (Outer Ear Infection)": "very_common",
        "Sarcoptic Mange (Trixacarus caviae)": "very_common",
        "Ovarian Cysts": "very_common",
        "Fungal Dermatitis (Ringworm)": "very_common",
        "Diarrhea": "very_common",
        "Staphylococcal Pododermatitis": "very_common",
        "Pneumonia (Bacterial)": "very_common",
        # common
        "Pododermatitis (Bumblefoot)": "common",
        "Urolithiasis (Bladder Stones)": "common",
        "GI Stasis": "common",
        "Obesity": "common",
        "Barbering": "common",
        "Bladder Sludge": "common",
        "Urinary Tract Infection (UTI)": "common",
        "Static Lice (Gliricola porcelli)": "common",
        "Bordetella bronchiseptica Infection": "common",
        "Streptococcus pneumoniae Infection": "common",
        "Conjunctivitis": "common",
        "Elongated Tooth Roots": "common",
        "Mastitis": "common",
        "Renal Calculi": "common",
        "Sebaceous Cyst": "common",
        # uncommon
        "Salmonellosis": "uncommon",
        "Pregnancy Toxemia (Ketosis)": "uncommon",
        "Diabetes Mellitus": "uncommon",
        "Lymphoma": "uncommon",
        "Chronic Kidney Disease": "uncommon",
        "Antibiotic-Associated Enterotoxemia": "uncommon",
        # rare
        "Lymphocytic Choriomeningitis Virus (LCMV)": "rare",
        "Leukemia": "rare",
        # --- Expanded guinea pig entries ---
        "Cervical Lymphadenitis (Lumps)": "very_common",
        "Lice Infestation (Gyropus/Gliricola)": "very_common",
        "Heat Stroke": "very_common",
        "Malocclusion (Cheek Teeth)": "very_common",
        "Skin Abscess": "common",
        "Alopecia": "common",
        "Cystitis": "common",
        "Dystocia": "common",
        "Gastric Dilation / Bloat": "common",
        "Intestinal Torsion": "common",
        "Mammary Tumor": "common",
        "Trichofolliculoma": "common",
        "Ovarian Cystic Disease": "common",
        "Pneumonia (Viral)": "common",
        "Rectal Prolapse": "common",
        "Foot Abscess": "common",
        "Hepatic Lipidosis": "uncommon",
        "Heart Disease": "uncommon",
        "Hyperthyroidism": "uncommon",
        "Fibrosarcoma": "rare",
        "Osteosarcoma": "rare",
        # --- Additional guinea pig entries ---
        "Hay Poke Injury": "very_common",
        "Chirodiscoides caviae Infestation": "very_common",
        "Nail Overgrowth": "very_common",
        "Chlamydiosis (Chlamydia caviae)": "common",
        "Bordetella Pneumonia": "common",
        "Bumblefoot (Pododermatitis)": "common",
        "Boar Glue (Excessive Grease Gland Secretion)": "common",
        "Corneal Ulcer": "common",
        "Perineal Sac Impaction": "common",
        "Dental Abscess": "common",
        "Gastric Ulcer": "common",
        "Flystrike (Myiasis)": "common",
        "Ileus": "common",
        "Ovarian Cysts - Follicular": "common",
        "Slobbers (Dental-related Ptyalism)": "common",
        "Cecal Dysbiosis": "uncommon",
        "Dilated Cardiomyopathy": "uncommon",
        "Intestinal Adenocarcinoma": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Trixacarus caviae Mange": "uncommon",
        "Cytomegalovirus Infection": "rare",
        "Lymphocytic Choriomeningitis (LCMV)": "rare",
    },

    # ==================================================================
    # FERRET — 22+ entries (expanded from ~10)
    # ==================================================================
    "ferret": {
        # very_common
        "Adrenal Disease": "very_common",
        "Insulinoma": "very_common",
        "Intestinal Parasites (Roundworm / Hookworm)": "very_common",
        "Upper Respiratory Infection (URI)": "very_common",
        "Ear Mites (Otodectes cynotis)": "very_common",
        "Dental Disease / Periodontal Disease": "very_common",
        # common
        "Lymphoma": "common",
        "Splenomegaly": "common",
        "Dilated Cardiomyopathy (DCM)": "common",
        "GI Foreign Body": "common",
        "Influenza (Human Flu)": "common",
        "Epizootic Catarrhal Enteritis (ECE / Green Slime Disease)": "common",
        "Aplastic Anemia (Estrogen Toxicity)": "common",
        "Helicobacter Mustelae Gastritis": "common",
        "Adrenal Alopecia": "common",
        "Adrenal Tumor (Adenoma / Adenocarcinoma)": "common",
        "Flea Dermatitis": "common",
        "Aleutian Disease (ADV)": "common",
        "Posterior Paresis / Hind Leg Weakness": "common",
        "Hairballs (Trichobezoars)": "common",
        # uncommon
        "Heartworm Disease": "uncommon",
        "Otitis Media/Interna": "uncommon",
        "Hypertrophic Cardiomyopathy (HCM)": "uncommon",
        "Ferret Systemic Coronavirus (FRSCV)": "uncommon",
        "Proliferative Colitis": "uncommon",
        # rare
        "Canine Distemper": "rare",
        "Rabies": "rare",
        "Chordoma": "rare",
    },

    # ==================================================================
    # HEDGEHOG — 22+ entries (expanded from ~10)
    # ==================================================================
    "hedgehog": {
        # very_common
        "Mite Infestation (Caparinia)": "very_common",
        "Obesity": "very_common",
        "Dental Disease": "very_common",
        "Upper Respiratory Infection": "very_common",
        "Dermatitis (Bacterial)": "very_common",
        "GI Stasis": "very_common",
        "Quilling (Physiological)": "very_common",
        "Internal Parasites (Intestinal Worms)": "very_common",
        # common
        "Wobbly Hedgehog Syndrome (WHS)": "common",
        "Ringworm (Dermatophytosis)": "common",
        "Periodontal Disease": "common",
        "Gingivitis": "common",
        "Pneumonia": "common",
        "Fatty Liver Disease": "common",
        "Hypothermia / Hibernation Attempt": "common",
        "Conjunctivitis": "common",
        "Cutaneous Squamous Cell Carcinoma": "common",
        "Mammary Gland Tumor": "common",
        "Lymphoma": "common",
        "Salmonellosis": "common",
        "Diarrhea (Non-specific)": "common",
        "Ear Infection (Otitis)": "common",
        "Tick Infestation": "common",
        "Flea Infestation": "common",
        # uncommon
        "Dilated Cardiomyopathy": "uncommon",
        "Chronic Kidney Disease": "uncommon",
        "Proptosis (Eye Protrusion)": "uncommon",
        "Uterine Adenocarcinoma": "uncommon",
        "Hemangiosarcoma": "uncommon",
        # rare
        "Herpesvirus Infection": "rare",
        "Balloon Syndrome": "rare",
    },

    # ==================================================================
    # AMPHIBIAN
    # ==================================================================
    "amphibian": {
        "Nematode Infection": "very_common",
        "Aeromonas Infection": "very_common",
        "Aspergillosis": "very_common",
        "Vitamin A Deficiency": "very_common",
        "Chytridiomycosis (Bd)": "very_common",
        "Ranavirus Infection": "common",
        "Red Leg Syndrome": "very_common",
        "Edema / Hydrops (Dropsy)": "common",
        "Stomatitis (Mouth Rot)": "common",
        "Intestinal Impaction": "common",
        "Thermal Burns": "uncommon",
        "Thermal Stress (Hypothermia)": "uncommon",
        # --- Expanded amphibian entries ---
        "Bacterial Dermatitis": "very_common",
        "Mycobacteriosis": "very_common",
        "Metabolic Bone Disease (MBD)": "very_common",
        "Nutritional Secondary Hyperparathyroidism": "very_common",
        "Saprolegniasis (Water Mold)": "very_common",
        "Dehydration": "common",
        "Obesity": "common",
        "Foreign Body Ingestion": "common",
        "Parasitic Dermatitis": "common",
        "Chromomycosis": "common",
        "Trematode Infection": "common",
        "Ammonia Toxicity": "common",
        "Prolapse (Cloacal/Gastric)": "common",
        "Corneal Lipidosis": "uncommon",
        "Renal Disease": "uncommon",
        "Neoplasia (General)": "uncommon",
        "Thiamine Deficiency": "uncommon",
        "Septicemia": "uncommon",
        "Iridovirus Infection": "rare",
        "Lucke Tumor (Renal Carcinoma)": "rare",
        # --- Additional amphibian entries ---
        "Chytridiomycosis (Batrachochytrium dendrobatidis)": "very_common",
        "Flavobacterium Infection": "very_common",
        "Columnaris Disease (Flavobacterium columnare)": "common",
        "Constipation": "common",
        "Egg Binding (Dystocia)": "common",
        "Fracture (Limb)": "common",
        "Intestinal Obstruction": "common",
        "Nitrite Poisoning": "common",
        "Gastroenteritis": "common",
        "Saprolegnia Infection": "common",
        "Cloacal Prolapse": "common",
        "Spindly Leg Syndrome": "common",
        "Axolotl Floating Disorder": "common",
        "Gas Bubble Disease": "uncommon",
        "Lymphoma": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Myxozoan Infection": "uncommon",
        "Batrachochytrium salamandrivorans (Bsal)": "uncommon",
        "Calicivirus Infection": "rare",
        "Perkinsea Infection": "rare",
    },

    # ==================================================================
    # CHINCHILLA
    # ==================================================================
    "chinchilla": {
        "Upper Respiratory Infection": "very_common",
        "Diarrhea": "very_common",
        "Dental Malocclusion - Incisor": "very_common",
        "Dental Malocclusion - Molar Spurs": "very_common",
        "GI Stasis": "very_common",
        "Fur Mites": "very_common",
        "Pneumonia": "common",
        "Dermatophytosis (Ringworm)": "common",
        "Conjunctivitis": "common",
        "Heat Stroke": "common",
        "Intussusception": "uncommon",
        "Intussusception - Chinchilla": "uncommon",
        "Cecal Impaction": "uncommon",
        "Cecal Torsion": "rare",
        "Bloat (Gastric Tympany)": "uncommon",
        # --- Expanded chinchilla entries ---
        "Fur Slip": "very_common",
        "Fur Chewing (Barbering)": "very_common",
        "Dental Root Elongation": "very_common",
        "Ear Infection": "common",
        "Constipation": "common",
        "Cataracts": "common",
        "Diabetes Mellitus": "common",
        "Urolithiasis": "common",
        "Skin Abscess": "common",
        "Otitis Media": "common",
        "Penile Fur Ring": "common",
        "Rectal Prolapse": "common",
        "Fatty Liver Disease": "common",
        "Cardiomyopathy": "uncommon",
        "Lymphoma": "uncommon",
        "Listeriosis": "uncommon",
        "Giardiasis": "uncommon",
        "Pyometra": "uncommon",
        "Toxoplasmosis": "rare",
        "Chordoma": "rare",
        # --- Additional chinchilla entries ---
        "Dental Abscess": "very_common",
        "Dental Disease (Molar Elongation)": "very_common",
        "Slobbers (Dental-Related)": "very_common",
        "Bumblefoot (Pododermatitis)": "common",
        "Calcium Deficiency": "common",
        "Dental Resorption": "common",
        "Fracture (Limb)": "common",
        "Fur Ring (Penile)": "common",
        "Heatstroke (Chinchilla-Specific)": "common",
        "Intestinal Obstruction": "common",
        "Malocclusion - Progressive": "common",
        "Otitis Media/Interna": "common",
        "Pregnancy Toxemia": "common",
        "Rhinitis": "common",
        "Dental Disease - Resorptive Lesions": "uncommon",
        "Dilated Cardiomyopathy": "uncommon",
        "Encephalitozoon cuniculi Infection": "uncommon",
        "Hepatic Lipidosis": "uncommon",
        "Mammary Tumor": "uncommon",
        "Osteomyelitis": "uncommon",
        "Squamous Cell Carcinoma": "rare",
        "Iron Storage Disease": "rare",
    },

    # ==================================================================
    # DEGU
    # ==================================================================
    "degu": {
        "Upper Respiratory Infection": "very_common",
        "Dental Disease": "very_common",
        "Diabetes Mellitus": "very_common",
        "Diarrhea": "very_common",
        "Senile Cataracts": "very_common",
        "Sand Bath Dermatitis": "very_common",
        "GI Stasis": "common",
        "Intestinal Parasites": "common",
        "Seizures": "common",
        "Lymphoma": "common",
        # --- Expanded degu entries ---
        "Skin Abscess": "very_common",
        "Fur Chewing (Barbering)": "very_common",
        "Tail Degloving Injury": "very_common",
        "Bumblefoot (Pododermatitis)": "very_common",
        "Dental Malocclusion": "very_common",
        "Ringworm (Dermatophytosis)": "common",
        "Ear Infection": "common",
        "Constipation": "common",
        "Obesity": "common",
        "Conjunctivitis": "common",
        "Pneumonia": "common",
        "Heatstroke": "common",
        "Elodontoma (Dental Tumor)": "common",
        "Hepatic Lipidosis": "uncommon",
        "Cardiomyopathy": "uncommon",
        "Uterine Tumor": "uncommon",
        "Mammary Tumor": "uncommon",
        "Chronic Kidney Disease": "uncommon",
        "Septicemia": "rare",
        "Toxoplasmosis": "rare",
        # --- Additional degu entries ---
        "Incisor Overgrowth": "very_common",
        "Molar Elongation": "very_common",
        "Molar Spurs": "very_common",
        "Cataracts (Diabetic)": "very_common",
        "Dental Abscess": "common",
        "Diabetic Cataracts": "common",
        "Diabetic Ketoacidosis": "common",
        "Fracture": "common",
        "Giardiasis": "common",
        "Heat Stroke": "common",
        "Intestinal Parasitism": "common",
        "Nail Overgrowth": "common",
        "Tail Slip (Degloving)": "common",
        "Tooth Root Abscess": "common",
        "Urinary Tract Infection": "common",
        "Bloat (Gastric Dilation)": "uncommon",
        "Cecal Impaction": "uncommon",
        "Fibrosarcoma": "uncommon",
        "Ovarian Cyst": "uncommon",
        "Diabetes-Related Cataracts": "uncommon",
        "Alzheimer's-like Disease": "rare",
        "Cognitive Dysfunction (Senile)": "rare",
    },

    # ==================================================================
    # EXOTIC OTHER
    # ==================================================================
    "exotic_other": {
        "Intestinal Parasitism": "very_common",
        "Upper Respiratory Infection": "very_common",
        "Nutritional Deficiency": "very_common",
        "Contact Dermatitis": "very_common",
        "Metabolic Bone Disease": "common",
        "Dermatophytosis (Ringworm)": "common",
        "Lymphoma": "common",
        # --- Expanded exotic_other entries ---
        "Dental Disease": "very_common",
        "Gastrointestinal Parasites": "very_common",
        "Skin Infection (Bacterial)": "very_common",
        "Obesity": "very_common",
        "Dehydration": "common",
        "GI Stasis": "common",
        "Pneumonia": "common",
        "Heatstroke": "common",
        "Skin Abscess": "common",
        "Conjunctivitis": "common",
        "Diarrhea (Non-specific)": "common",
        "Constipation": "common",
        "Mite Infestation": "common",
        "Trauma / Fracture": "common",
        "Hepatic Lipidosis": "uncommon",
        "Renal Disease": "uncommon",
        "Neoplasia (General)": "uncommon",
        "Cardiomyopathy": "uncommon",
        "Septicemia": "rare",
        "Chlamydiosis": "rare",
        # --- Additional exotic_other entries ---
        "Ferret Adrenal Gland Disease": "very_common",
        "Ferret Insulinoma": "very_common",
        "Hedgehog Skin Mites (Caparinia tripilis)": "very_common",
        "Hedgehog Ringworm (Trichophyton)": "very_common",
        "Ferret Lymphoma": "common",
        "Ferret ECE (Epizootic Catarrhal Enteritis)": "common",
        "Ferret Helicobacter Gastritis": "common",
        "Ferret Aleutian Disease": "common",
        "Hedgehog Wobbly Hedgehog Syndrome (WHS)": "common",
        "Hedgehog Obesity": "common",
        "Hedgehog Cardiomyopathy": "common",
        "Ich (White Spot Disease)": "common",
        "Swim Bladder Disease": "common",
        "Fin Rot": "common",
        "Dippity Pig Syndrome": "common",
        "Mange (Sarcoptic)": "common",
        "Hoof Overgrowth / Cracks (Porcine)": "common",
        "Sugar Glider Self-Mutilation": "uncommon",
        "Sugar Glider Nutritional Osteodystrophy": "uncommon",
        "Odontoma (Prairie Dog)": "uncommon",
        "Koi Herpesvirus Disease (KHV)": "uncommon",
        "Ferret Canine Distemper": "rare",
        "Monkeypox": "rare",
        "Plague (Yersinia pestis)": "rare",
    },

    # ==================================================================
    # LIZARD
    # ==================================================================
    "lizard": {
        "Mite Infestation (Ectoparasites)": "very_common",
        "Respiratory Infection": "very_common",
        "Metabolic Bone Disease (MBD)": "very_common",
        "Vitamin A Deficiency": "very_common",
        "Dysecdysis (Retained Shed)": "very_common",
        "Scale Rot (Ulcerative Dermatitis)": "very_common",
        "Stomatitis (Mouth Rot)": "very_common",
        "Gastrointestinal Impaction (Substrate Impaction)": "common",
        "Pre-ovulatory Follicular Stasis": "common",
        "Abscess": "common",
        "Thermal Burns": "common",
        # --- Additional lizard entries ---
        "Coccidia Infection": "very_common",
        "Dehydration": "very_common",
        "Internal Nematodes (Roundworms)": "very_common",
        "Constipation": "very_common",
        "Egg Binding (Dystocia)": "common",
        "Corneal Ulcer": "common",
        "Conjunctivitis": "common",
        "Bite Wounds": "common",
        "Fracture (Limb)": "common",
        "Obesity": "common",
        "Tail Autotomy Complication": "common",
        "Toe Necrosis (Retained Shed)": "common",
        "Gout (Articular)": "common",
        "Gout (Visceral)": "common",
        "Sand Impaction": "common",
        "Aural Abscess": "common",
        "Atadenovirus Infection": "uncommon",
        "Nannizziopsis Dermatitis": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Lymphoma": "uncommon",
        "Hepatic Lipidosis": "uncommon",
        "Bearded Dragon Adenovirus": "uncommon",
        "Inclusion Body Disease (IBD)": "rare",
        "Chameleon Edema Syndrome": "rare",
    },

    # ==================================================================
    # PARAKEET
    # ==================================================================
    "parakeet": {
        "Psittacosis (Chlamydiosis)": "very_common",
        "Aspergillosis": "very_common",
        "Upper Respiratory Infection": "very_common",
        "Nutritional Deficiency (General)": "very_common",
        "Scaly Face Mite (Knemidocoptes)": "very_common",
        "Feather Plucking": "very_common",
        "Avian Pox": "common",
        "Giardiasis": "common",
        "Fatty Liver Disease": "common",
        "Sinusitis": "common",
        # --- Additional parakeet entries ---
        "Megabacteriosis (AGY)": "very_common",
        "Candidiasis (Crop Mycosis)": "very_common",
        "Goiter": "very_common",
        "Knemidocoptes Mange (Scaly Face)": "very_common",
        "Macrorhabdus ornithogaster (Parakeet)": "common",
        "Egg Binding": "common",
        "Egg Peritonitis": "common",
        "Chronic Egg Laying": "common",
        "Iodine Deficiency (Thyroid Hyperplasia)": "common",
        "Crop Stasis": "common",
        "Fracture (Wing)": "common",
        "Night Fright Injury": "common",
        "Lead Poisoning": "common",
        "Zinc Toxicosis": "common",
        "Lipoma": "common",
        "French Moult": "common",
        "Sour Crop": "common",
        "Renal Adenocarcinoma (Parakeet)": "uncommon",
        "Testicular Tumor (Cere Color Change)": "uncommon",
        "Budgerigar Fledgling Disease": "uncommon",
        "Xanthoma": "uncommon",
        "Psittacine Beak and Feather Disease (PBFD)": "uncommon",
        "Pacheco's Disease": "rare",
        "Polyomavirus Infection": "rare",
        "Budgerigar Herpesvirus": "rare",
    },

    # ==================================================================
    # PARROT
    # ==================================================================
    "parrot": {
        "Psittacosis (Chlamydiosis)": "very_common",
        "Aspergillosis": "very_common",
        "Chronic Respiratory Disease": "very_common",
        "Nutritional Deficiency (General)": "very_common",
        "Intestinal Parasites (Roundworms/Tapeworms)": "very_common",
        "Feather Plucking": "very_common",
        "Avian Polyomavirus": "common",
        "Avian Bornavirus (ABV)": "common",
        "Fatty Liver Disease": "common",
        "Atherosclerosis": "common",
        "Lymphoma": "common",
        "Bacterial Pneumonia": "uncommon",
        # --- Additional parrot entries ---
        "Candidiasis (Crop Mycosis)": "very_common",
        "Vitamin A Deficiency": "very_common",
        "Rhinitis": "very_common",
        "Sinusitis": "common",
        "Egg Binding": "common",
        "Egg Peritonitis": "common",
        "Chronic Egg Laying": "common",
        "Psittacine Beak and Feather Disease (PBFD)": "common",
        "Proventricular Dilatation Disease (PDD)": "common",
        "Crop Stasis": "common",
        "Crop Impaction": "common",
        "Lead Poisoning": "common",
        "Zinc Toxicosis": "common",
        "Gout (Visceral/Articular)": "common",
        "Obesity": "common",
        "Lipoma": "common",
        "Self-Mutilation": "common",
        "Behavioral Feather Destructive Disorder": "common",
        "Fracture (Wing)": "common",
        "Knemidocoptes Mange (Scaly Face)": "uncommon",
        "Hepatic Amyloidosis": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Pacheco's Disease": "rare",
        "Iron Storage Disease (Hemochromatosis)": "rare",
        "Macaw Wasting Disease": "rare",
    },

    # ==================================================================
    # SNAKE
    # ==================================================================
    "snake": {
        "Hemoparasites (Blood Parasites)": "very_common",
        "Respiratory Infection": "very_common",
        "Inclusion Body Disease (IBD)": "very_common",
        "Infectious Stomatitis (Mouth Rot)": "very_common",
        "Regurgitation Syndrome": "very_common",
        "Snake Mites (Ophionyssus natricis)": "very_common",
        "Pneumonia": "common",
        "Metabolic Bone Disease (MBD)": "common",
        "Vitamin A Deficiency": "common",
        "Gastrointestinal Impaction": "common",
        "Scale Rot": "common",
        # --- Additional snake entries ---
        "Dysecdysis (Retained Shed)": "very_common",
        "Anorexia (Behavioral)": "very_common",
        "Dehydration": "very_common",
        "Constipation": "very_common",
        "Blister Disease": "common",
        "Burns": "common",
        "Cryptosporidiosis": "common",
        "Spectacle Retention": "common",
        "Prey Bite Injury": "common",
        "Rostral Abrasion": "common",
        "Stomatitis (Mouth Rot)": "common",
        "Retained Spectacle": "common",
        "Penile/Hemipenal Prolapse": "common",
        "Substrate Impaction": "common",
        "Internal Nematodes (Roundworms)": "common",
        "Boid Nidovirus (Ball Python Nidovirus)": "uncommon",
        "Snake Fungal Disease (Ophidiomyces)": "uncommon",
        "Gout (Visceral)": "uncommon",
        "Lymphoma": "uncommon",
        "Arenavirus Infection": "uncommon",
        "Paramyxovirus Infection": "rare",
        "Kinking (Spinal Deformity)": "rare",
        "Sunshine Virus (Reptarenavirus)": "rare",
    },

    # ==================================================================
    # SUGAR GLIDER
    # ==================================================================
    "sugar_glider": {
        "Malnutrition / Nutritional Deficiency": "very_common",
        "Upper Respiratory Infection": "very_common",
        "Intestinal Parasitism": "very_common",
        "Contact Dermatitis": "very_common",
        "GI Stasis": "very_common",
        "Dental Disease / Tartar Buildup": "very_common",
        "Metabolic Bone Disease (MBD)": "common",
        "Lymphoma": "common",
        "Septicemia": "common",
        "Self-Mutilation - Stress-Induced": "common",
        # --- Additional sugar glider entries ---
        "Nutritional Osteodystrophy (MBD)": "very_common",
        "Obesity": "very_common",
        "Stress-Induced Alopecia": "very_common",
        "Calcium Deficiency": "very_common",
        "Self-Mutilation": "common",
        "Dental Caries": "common",
        "Periodontal Disease": "common",
        "Patagium Tear": "common",
        "Corneal Ulcer": "common",
        "Diarrhea": "common",
        "Constipation": "common",
        "Hepatic Lipidosis": "common",
        "Hind Leg Paralysis": "common",
        "Pouch Infection (Marsupial)": "common",
        "Fracture": "common",
        "Lumpy Jaw (Mandibular Abscess)": "common",
        "Depression / Stress Syndrome": "common",
        "Joey Rejection": "common",
        "Urinary Tract Infection": "uncommon",
        "Mammary Tumor": "uncommon",
        "Ovarian Cyst": "uncommon",
        "Toxoplasmosis": "uncommon",
        "Iron Storage Disease (Hemochromatosis)": "rare",
        "Renal Amyloidosis": "rare",
    },

    # ==================================================================
    # TORTOISE
    # ==================================================================
    "tortoise": {
        "Respiratory Infection": "very_common",
        "Coccidia": "very_common",
        "Metabolic Bone Disease (MBD)": "very_common",
        "Vitamin A Deficiency": "very_common",
        "Shell Rot (Ulcerative Shell Disease)": "very_common",
        "Stomatitis (Mouth Rot)": "very_common",
        "Pneumonia": "common",
        "Dysecdysis (Retained Shed)": "common",
        "Gastrointestinal Impaction (Constipation)": "common",
        "Abscess": "common",
        "Nutritional Secondary Hyperparathyroidism": "common",
        # --- Additional tortoise entries ---
        "Dehydration": "very_common",
        "Intestinal Nematodes (Roundworms)": "very_common",
        "Oxyurid Infection": "very_common",
        "Beak Overgrowth": "very_common",
        "Nail Overgrowth": "very_common",
        "Shell Pyramiding": "common",
        "Shell Fracture": "common",
        "Bladder Stone": "common",
        "Constipation": "common",
        "Rhinitis": "common",
        "Hexamita Infection": "common",
        "Herpesvirus Infection": "common",
        "Mycoplasmosis (Mycoplasma agassizii / testudineum)": "common",
        "Runny Nose Syndrome (RNS)": "common",
        "Gout (Articular)": "common",
        "Gout (Visceral)": "common",
        "Foreign Body Ingestion": "common",
        "Egg Binding (Dystocia)": "common",
        "Hepatic Lipidosis": "uncommon",
        "Fibrosarcoma": "uncommon",
        "Squamous Cell Carcinoma": "uncommon",
        "Tortoise Intranuclear Coccidia (TINC)": "uncommon",
        "Ranavirus Infection": "rare",
        "Tortoise Herpesvirus": "rare",
    },
}


def get_prevalence_for_species(species: str) -> dict[str, str]:
    """Get prevalence mapping for a specific species.

    Parameters
    ----------
    species : str
        Species key (e.g., 'cat', 'rabbit', 'bird')

    Returns
    -------
    dict[str, str]
        Mapping of disease names to prevalence tiers
    """
    return SPECIES_PREVALENCE.get(species, {})
