"""Rabbit disease dictionary and analysis module."""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── 消化器系 ──
    {
        "name": "GI Stasis (Gastrointestinal Hypomotility)",
        "name_ja": "消化管うっ滞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "lethargy", "abdominal_distension", "teeth_grinding"},
        "description": "Slowdown or cessation of gut motility, a life-threatening emergency in rabbits.",
        "description_ja": "消化管の運動低下または停止で、ウサギの致命的な緊急疾患。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Gastric Bloat / Dilation",
        "name_ja": "胃拡張・鼓脹症",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "teeth_grinding", "rapid_breathing"},
        "description": "Acute gas or fluid distension of the stomach, can be rapidly fatal.",
        "description_ja": "胃のガスまたは液体による急性拡張で、急速に致死的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Mucoid Enteropathy",
        "name_ja": "粘液性腸症",
        "symptoms": {"mucoid_stool", "diarrhea", "appetite_loss", "dehydration", "abdominal_distension"},
        "description": "Excessive mucus production in the intestines, common in young rabbits.",
        "description_ja": "腸管での過剰な粘液産生で、若いウサギに多い。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "radiography"],
    },
    {
        "name": "Cecal Dysbiosis",
        "name_ja": "盲腸内細菌叢異常",
        "symptoms": {"diarrhea", "soft_cecotropes", "appetite_loss", "lethargy"},
        "description": "Imbalance of cecal microflora from diet or antibiotics.",
        "description_ja": "食事や抗生物質による盲腸内の細菌叢の不均衡。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "dietary_review"],
    },
    {
        "name": "Intestinal Obstruction",
        "name_ja": "腸閉塞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "abdominal_distension", "lethargy", "teeth_grinding"},
        "description": "Blockage from hair, carpet fibers, or other ingested material.",
        "description_ja": "毛、カーペット繊維などの異物による腸管の閉塞。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"appetite_loss", "lethargy", "weight_loss", "jaundice"},
        "description": "Fat accumulation in the liver, often secondary to anorexia.",
        "description_ja": "食欲不振に続発する肝臓への脂肪蓄積。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound"],
    },
    {
        "name": "Enteritis (Bacterial)",
        "name_ja": "細菌性腸炎",
        "symptoms": {"diarrhea", "dehydration", "lethargy", "appetite_loss", "bloody_stool"},
        "description": "Bacterial infection of the intestines (E. coli, Clostridium, etc.).",
        "description_ja": "大腸菌やクロストリジウムなどによる腸の細菌感染。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "complete_blood_count"],
    },
    {
        "name": "Cecal Impaction",
        "name_ja": "盲腸閉塞",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "abdominal_distension", "weight_loss"},
        "description": "Impaction of the cecum with dehydrated material.",
        "description_ja": "脱水した内容物による盲腸の閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Liver Lobe Torsion",
        "name_ja": "肝葉捻転",
        "symptoms": {"sudden_lethargy", "appetite_loss", "abdominal_distension", "pale_mucous_membranes"},
        "description": "Rotation of a liver lobe cutting off blood supply, acute emergency.",
        "description_ja": "肝葉の回転による血液供給の遮断で、急性の緊急疾患。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "complete_blood_count"],
    },
    # ── 歯科 ──
    {
        "name": "Dental Malocclusion (Incisors)",
        "name_ja": "切歯不正咬合",
        "symptoms": {"overgrown_teeth", "drooling", "appetite_loss", "weight_loss"},
        "description": "Misalignment of incisor teeth leading to overgrowth.",
        "description_ja": "切歯の不整合による過成長。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Dental Malocclusion (Cheek Teeth)",
        "name_ja": "臼歯不正咬合",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "facial_abscess", "eye_discharge"},
        "description": "Spur formation on molar teeth causing tongue/cheek injury.",
        "description_ja": "臼歯のスパー形成による舌・頬の損傷。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiography"],
    },
    {
        "name": "Dental Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_abscess", "facial_swelling", "appetite_loss", "eye_discharge", "nasal_discharge"},
        "description": "Root infection causing jaw swelling, common with molar disease.",
        "description_ja": "歯根感染による顎の腫脹で、臼歯疾患に多い。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "ct_scan", "bacterial_culture"],
    },
    {
        "name": "Tooth Root Elongation",
        "name_ja": "歯根伸長",
        "symptoms": {"eye_discharge", "epiphora", "appetite_loss", "facial_swelling"},
        "description": "Abnormal growth of tooth roots into the jaw, may affect tear ducts.",
        "description_ja": "歯根の顎骨内への異常伸長で、涙管に影響することがある。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "ct_scan"],
    },
    # ── 呼吸器系 ──
    {
        "name": "Pasteurellosis (Snuffles)",
        "name_ja": "パスツレラ症（スナッフル）",
        "symptoms": {"sneezing", "nasal_discharge", "eye_discharge", "head_tilt", "abscess"},
        "description": "Pasteurella multocida infection causing upper respiratory and systemic disease.",
        "description_ja": "パスツレラ菌感染による上部呼吸器疾患および全身性疾患。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "radiography"],
    },
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"labored_breathing", "nasal_discharge", "lethargy", "appetite_loss", "cyanosis"},
        "description": "Bacterial lung infection, often secondary to Pasteurella.",
        "description_ja": "パスツレラに続発することの多い細菌性肺感染。",
        "urgency": "high",
        "recommended_tests": ["radiography", "bacterial_culture"],
    },
    {
        "name": "Thymoma",
        "name_ja": "胸腺腫",
        "symptoms": {"labored_breathing", "eye_bulging", "bilateral_exophthalmos", "reduced_activity"},
        "description": "Tumor of the thymus gland compressing lungs and blood vessels.",
        "description_ja": "胸腺の腫瘍が肺や血管を圧迫する。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ct_scan", "cytology"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"sneezing", "nasal_discharge", "labored_breathing"},
        "description": "Infection of the nasal passages and sinuses.",
        "description_ja": "鼻腔および副鼻腔の感染。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "bacterial_culture"],
    },
    # ── 寄生虫 ──
    {
        "name": "Encephalitozoon cuniculi",
        "name_ja": "エンセファリトゾーン症",
        "symptoms": {"head_tilt", "loss_of_balance", "hind_limb_weakness", "urinary_incontinence", "cataracts"},
        "description": "Microsporidian parasite affecting brain, kidneys, and eyes.",
        "description_ja": "脳、腎臓、眼に影響する微胞子虫寄生虫。",
        "urgency": "high",
        "recommended_tests": ["serology", "urinalysis", "blood_chemistry"],
    },
    {
        "name": "Coccidiosis (Intestinal)",
        "name_ja": "腸コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "appetite_loss"},
        "description": "Eimeria species infecting the intestinal tract.",
        "description_ja": "アイメリア属による腸管感染。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float"],
    },
    {
        "name": "Coccidiosis (Hepatic)",
        "name_ja": "肝コクシジウム症",
        "symptoms": {"weight_loss", "appetite_loss", "jaundice", "abdominal_distension", "lethargy"},
        "description": "Eimeria stiedae infecting the liver and bile ducts.",
        "description_ja": "アイメリア・スティーダエによる肝臓・胆管の感染。",
        "urgency": "high",
        "recommended_tests": ["fecal_float", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Pinworm Infection (Passalurus)",
        "name_ja": "蟯虫症",
        "symptoms": {"perianal_irritation", "soft_cecotropes", "rough_coat"},
        "description": "Common intestinal pinworm usually causing minimal clinical signs.",
        "description_ja": "通常は軽微な症状の一般的な腸内蟯虫。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "perianal_tape_test"],
    },
    {
        "name": "Ear Mites (Psoroptes cuniculi)",
        "name_ja": "ウサギ耳ダニ症",
        "symptoms": {"ear_crusting", "head_shaking", "scratching_ears", "ear_discharge"},
        "description": "Mite infestation of the ear canal causing thick brown crusts.",
        "description_ja": "耳道のダニ寄生で、厚い茶色の痂皮を形成する。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "microscopy"],
    },
    {
        "name": "Fur Mites (Cheyletiella)",
        "name_ja": "ツメダニ症",
        "symptoms": {"dandruff", "itching", "hair_loss", "skin_flaking"},
        "description": "Surface mite causing 'walking dandruff' on the back.",
        "description_ja": "背中に「歩くフケ」を引き起こす表面性ダニ。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "tape_test"],
    },
    {
        "name": "Myiasis (Fly Strike)",
        "name_ja": "ハエウジ症",
        "symptoms": {"maggots_visible", "foul_odor", "lethargy", "skin_wounds", "pain"},
        "description": "Blowfly larvae infestation of skin, often around perineum. Life-threatening.",
        "description_ja": "クロバエの幼虫が皮膚に寄生し、会陰部周囲に多い。致命的。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam"],
    },
    # ── 感染症 ──
    {
        "name": "Myxomatosis",
        "name_ja": "粘液腫症",
        "symptoms": {"eyelid_swelling", "genital_swelling", "skin_nodules", "fever", "lethargy", "nasal_discharge"},
        "description": "Viral disease transmitted by fleas/mosquitoes, often fatal.",
        "description_ja": "ノミや蚊で伝播するウイルス疾患で、致死率が高い。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_test", "biopsy"],
    },
    {
        "name": "Rabbit Hemorrhagic Disease (RHDV/VHD)",
        "name_ja": "ウサギ出血病（VHD）",
        "symptoms": {"sudden_death", "nasal_bleeding", "fever", "lethargy", "seizures"},
        "description": "Highly fatal calicivirus causing acute liver failure and hemorrhage.",
        "description_ja": "急性肝不全と出血を引き起こす致死率の高いカリシウイルス。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_test", "necropsy"],
    },
    {
        "name": "Rabbit Syphilis (Treponematosis)",
        "name_ja": "ウサギ梅毒（トレポネーマ症）",
        "symptoms": {"genital_lesions", "nasal_crusting", "lip_crusting", "skin_ulcers"},
        "description": "Treponema cuniculi causing crusty lesions around nose, lips, and genitals.",
        "description_ja": "トレポネーマ菌による鼻、唇、外陰部周囲の痂皮性病変。",
        "urgency": "moderate",
        "recommended_tests": ["dark_field_microscopy", "serology"],
    },
    # ── 皮膚科 ──
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"hair_loss", "skin_crusting", "circular_lesions", "skin_flaking"},
        "description": "Fungal skin infection causing circular patches of hair loss.",
        "description_ja": "真菌感染による円形の脱毛斑。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "woods_lamp"],
    },
    {
        "name": "Pododermatitis (Sore Hocks)",
        "name_ja": "飛節潰瘍（ソアホック）",
        "symptoms": {"foot_sores", "lameness", "swelling", "pain", "bleeding"},
        "description": "Pressure sores on the hind feet from hard/wire flooring or obesity.",
        "description_ja": "硬い床や肥満による後足の圧迫性潰瘍。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiography"],
    },
    {
        "name": "Subcutaneous Abscess",
        "name_ja": "皮下膿瘍",
        "symptoms": {"abscess", "swelling", "discharge", "pain"},
        "description": "Thick-walled pus-filled pocket, commonly from Pasteurella.",
        "description_ja": "パスツレラ菌による厚い壁の膿瘍。",
        "urgency": "moderate",
        "recommended_tests": ["cytology", "bacterial_culture"],
    },
    {
        "name": "Barbering / Fur Pulling",
        "name_ja": "毛引き行動",
        "symptoms": {"hair_loss", "skin_redness", "overgrooming"},
        "description": "Self or mutual fur pulling due to stress, boredom, or hormonal causes.",
        "description_ja": "ストレス、退屈、ホルモン異常による自己または相互の毛引き。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "hormone_panel"],
    },
    # ── 運動器系 ──
    {
        "name": "Splay Leg",
        "name_ja": "開脚症",
        "symptoms": {"splayed_limbs", "inability_to_stand", "reduced_activity"},
        "description": "Congenital or developmental condition where legs splay outward.",
        "description_ja": "先天性または発達性の四肢外転変形。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Spinal Fracture / Luxation",
        "name_ja": "脊椎骨折・脱臼",
        "symptoms": {"hind_limb_paralysis", "urinary_incontinence", "fecal_incontinence", "pain"},
        "description": "Fracture of lumbar spine from improper handling or panic, often fatal.",
        "description_ja": "不適切な取り扱いやパニックによる腰椎骨折で、致命的なことが多い。",
        "urgency": "emergency",
        "recommended_tests": ["radiography"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "reduced_activity", "stiffness", "difficulty_hopping"},
        "description": "Degenerative joint disease in older rabbits.",
        "description_ja": "高齢ウサギの変性性関節疾患。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Fractures (Long Bone)",
        "name_ja": "長管骨骨折",
        "symptoms": {"lameness", "limb_deformity", "pain", "swelling"},
        "description": "Fractures from falls, mishandling, or cage entrapment.",
        "description_ja": "落下、不適切な取り扱い、ケージへの挟み込みによる骨折。",
        "urgency": "high",
        "recommended_tests": ["radiography"],
    },
    # ── 神経系 ──
    {
        "name": "Vestibular Disease (Otitis Media/Interna)",
        "name_ja": "前庭疾患（中耳炎・内耳炎）",
        "symptoms": {"head_tilt", "loss_of_balance", "nystagmus", "circling", "rolling"},
        "description": "Inner ear infection causing loss of balance and head tilt.",
        "description_ja": "内耳感染による平衡感覚喪失と斜頸。",
        "urgency": "high",
        "recommended_tests": ["otoscopic_exam", "radiography", "ct_scan"],
    },
    {
        "name": "Hind Limb Paresis/Paralysis",
        "name_ja": "後肢不全麻痺・麻痺",
        "symptoms": {"hind_limb_paralysis", "hind_limb_weakness", "urinary_incontinence"},
        "description": "Weakness or paralysis of hind legs from spinal, E. cuniculi, or spondylosis.",
        "description_ja": "脊椎、エンセファリトゾーン、脊椎症による後肢の脱力または麻痺。",
        "urgency": "high",
        "recommended_tests": ["radiography", "serology", "neurological_exam"],
    },
    {
        "name": "Seizures",
        "name_ja": "痙攣発作",
        "symptoms": {"seizures", "loss_of_consciousness", "tremors", "paddling"},
        "description": "Convulsive episodes from E. cuniculi, toxins, or metabolic disease.",
        "description_ja": "エンセファリトゾーン、毒素、代謝性疾患による痙攣。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "serology", "neurological_exam"],
    },
    # ── 生殖器系 ──
    {
        "name": "Uterine Adenocarcinoma",
        "name_ja": "子宮腺癌",
        "symptoms": {"vaginal_bleeding", "abdominal_distension", "weight_loss", "lethargy"},
        "description": "Most common cancer in intact female rabbits over 3 years old.",
        "description_ja": "3歳以上の未避妊メスウサギで最も多い癌。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "biopsy"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "abdominal_distension", "lethargy", "appetite_loss", "fever"},
        "description": "Bacterial infection of the uterus with pus accumulation.",
        "description_ja": "子宮の細菌感染による膿の蓄積。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "complete_blood_count"],
    },
    {
        "name": "Pregnancy Toxemia",
        "name_ja": "妊娠中毒症",
        "symptoms": {"lethargy", "appetite_loss", "seizures", "sudden_death"},
        "description": "Ketosis in late pregnancy or postpartum, often in obese does.",
        "description_ja": "妊娠後期または産後のケトーシスで、肥満メスに多い。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "vaginal_bleeding", "lethargy", "abdominal_distension"},
        "description": "Difficulty giving birth.",
        "description_ja": "分娩困難。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "mammary_redness", "fever", "appetite_loss"},
        "description": "Bacterial infection of the mammary glands.",
        "description_ja": "乳腺の細菌感染。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "physical_exam"],
    },
    {
        "name": "Uterine Hyperplasia / Endometrial Venous Aneurysm",
        "name_ja": "子宮内膜過形成・静脈瘤",
        "symptoms": {"vaginal_bleeding", "anemia", "lethargy"},
        "description": "Endometrial changes causing intermittent vaginal bleeding.",
        "description_ja": "子宮内膜の変化による間欠的な膣出血。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "complete_blood_count"],
    },
    {
        "name": "Orchitis / Epididymitis",
        "name_ja": "精巣炎・精巣上体炎",
        "symptoms": {"testicular_swelling", "pain", "fever", "lethargy"},
        "description": "Infection or inflammation of the testes or epididymis.",
        "description_ja": "精巣または精巣上体の感染・炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "bacterial_culture"],
    },
    # ── 眼科 ──
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "squinting"},
        "description": "Inflammation of the conjunctiva from infection or irritation.",
        "description_ja": "感染や刺激による結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "bacterial_culture"],
    },
    {
        "name": "Dacryocystitis (Blocked Tear Duct)",
        "name_ja": "涙嚢炎（涙管閉塞）",
        "symptoms": {"epiphora", "eye_discharge", "facial_abscess"},
        "description": "Infection/blockage of the nasolacrimal duct, often from dental disease.",
        "description_ja": "歯科疾患に続発することの多い鼻涙管の感染・閉塞。",
        "urgency": "moderate",
        "recommended_tests": ["skull_radiography", "nasolacrimal_flush"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudy_eyes", "vision_loss", "cataracts"},
        "description": "Lens opacity, may be congenital or from E. cuniculi.",
        "description_ja": "水晶体の混濁で、先天性またはエンセファリトゾーン由来。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "serology"],
    },
    {
        "name": "Glaucoma",
        "name_ja": "緑内障",
        "symptoms": {"eye_bulging", "eye_redness", "pain", "vision_loss"},
        "description": "Increased intraocular pressure.",
        "description_ja": "眼圧上昇。",
        "urgency": "high",
        "recommended_tests": ["tonometry", "ophthalmic_exam"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "eye_discharge", "eye_redness", "cloudy_eyes"},
        "description": "Erosion of the corneal surface from trauma, hay poke, or infection.",
        "description_ja": "外傷、牧草の刺入、感染による角膜表面のびらん。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam"],
    },
    # ── 泌尿器系 ──
    {
        "name": "Bladder Sludge (Hypercalciuria)",
        "name_ja": "膀胱スラッジ（高カルシウム尿症）",
        "symptoms": {"blood_in_urine", "straining_to_urinate", "thick_white_urine", "reduced_activity"},
        "description": "Accumulation of calcium sediment in the bladder.",
        "description_ja": "膀胱内のカルシウム沈殿物の蓄積。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "urinalysis"],
    },
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"blood_in_urine", "straining_to_urinate", "pain", "frequent_urination"},
        "description": "Calcium carbonate stones in the urinary tract.",
        "description_ja": "尿路の炭酸カルシウム結石。",
        "urgency": "high",
        "recommended_tests": ["radiography", "urinalysis", "ultrasound"],
    },
    {
        "name": "Renal Failure (Chronic)",
        "name_ja": "慢性腎不全",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy", "dehydration"},
        "description": "Progressive kidney function loss, may be from E. cuniculi.",
        "description_ja": "腎機能の進行性低下で、エンセファリトゾーン由来のことがある。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis"],
    },
    {
        "name": "Urinary Tract Infection",
        "name_ja": "尿路感染症",
        "symptoms": {"blood_in_urine", "frequent_urination", "straining_to_urinate", "foul_urine"},
        "description": "Bacterial infection of the bladder or urethra.",
        "description_ja": "膀胱または尿道の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "bacterial_culture"],
    },
    # ── 腫瘍 ──
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "lethargy", "enlarged_lymph_nodes", "appetite_loss"},
        "description": "Malignant lymphatic cancer.",
        "description_ja": "悪性リンパ系腫瘍。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy", "complete_blood_count"],
    },
    {
        "name": "Mammary Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "skin_lump", "weight_loss"},
        "description": "Benign or malignant mammary gland tumors.",
        "description_ja": "良性または悪性の乳腺腫瘍。",
        "urgency": "high",
        "recommended_tests": ["cytology", "biopsy"],
    },
    {
        "name": "Skin Tumor",
        "name_ja": "皮膚腫瘍",
        "symptoms": {"skin_lump", "skin_mass_growth", "ulceration"},
        "description": "Various tumors including papilloma, fibroma, and squamous cell carcinoma.",
        "description_ja": "乳頭腫、線維腫、扁平上皮癌などの皮膚腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "cytology"],
    },
    # ── 循環器系 ──
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"labored_breathing", "lethargy", "cyanosis", "reduced_activity"},
        "description": "Heart muscle disease in older rabbits.",
        "description_ja": "高齢ウサギの心筋疾患。",
        "urgency": "high",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"labored_breathing", "ascites", "lethargy", "cyanosis", "coughing"},
        "description": "Heart failure with fluid accumulation.",
        "description_ja": "液体貯留を伴う心不全。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    # ── 内分泌・代謝 ──
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "reduced_activity", "cecotrope_accumulation"},
        "description": "Excess weight from overfeeding and lack of exercise.",
        "description_ja": "過食と運動不足による過体重。",
        "urgency": "low",
        "recommended_tests": ["weight_assessment", "dietary_review"],
    },
    {
        "name": "Hypoglycemia",
        "name_ja": "低血糖症",
        "symptoms": {"weakness", "seizures", "lethargy", "tremors"},
        "description": "Abnormally low blood sugar, often in young or anorexic rabbits.",
        "description_ja": "異常に低い血糖値で、若齢や食欲不振のウサギに多い。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose"],
    },
    # ── 環境・栄養 ──
    {
        "name": "Heatstroke",
        "name_ja": "熱中症",
        "symptoms": {"labored_breathing", "lethargy", "drooling", "weakness", "seizures"},
        "description": "Hyperthermia from high ambient temperature; rabbits are very heat-sensitive.",
        "description_ja": "高温環境による高体温症で、ウサギは熱に非常に弱い。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "physical_exam"],
    },
    {
        "name": "Vitamin D Toxicity",
        "name_ja": "ビタミンD中毒",
        "symptoms": {"increased_thirst", "weight_loss", "lethargy", "kidney_calcification"},
        "description": "Excessive vitamin D causing soft tissue calcification.",
        "description_ja": "過剰なビタミンDによる軟部組織の石灰化。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "radiography"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"dehydration", "lethargy", "sunken_eyes", "skin_tenting"},
        "description": "Insufficient fluid intake or excess fluid loss.",
        "description_ja": "水分摂取不足または過剰な水分喪失。",
        "urgency": "high",
        "recommended_tests": ["skin_turgor_test", "physical_exam"],
    },
    # ── その他 ──
    {
        "name": "Gastrointestinal Staphylococcal Infection",
        "name_ja": "消化管ブドウ球菌感染症",
        "symptoms": {"diarrhea", "dehydration", "appetite_loss", "weight_loss"},
        "description": "Staphylococcal enteritis, especially in young kits.",
        "description_ja": "特に若齢仔ウサギのブドウ球菌性腸炎。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "complete_blood_count"],
    },
    {
        "name": "Spondylosis",
        "name_ja": "脊椎症",
        "symptoms": {"reduced_activity", "stiffness", "hind_limb_weakness", "difficulty_hopping"},
        "description": "Degenerative vertebral changes in older rabbits.",
        "description_ja": "高齢ウサギの変性性脊椎変化。",
        "urgency": "moderate",
        "recommended_tests": ["radiography"],
    },
    {
        "name": "Otitis Externa",
        "name_ja": "外耳炎",
        "symptoms": {"scratching_ears", "head_shaking", "ear_discharge", "ear_crusting"},
        "description": "Infection of the external ear canal.",
        "description_ja": "外耳道の感染。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "bacterial_culture"],
    },
    {
        "name": "Head Tilt (Torticollis)",
        "name_ja": "斜頸",
        "symptoms": {"head_tilt", "loss_of_balance", "nystagmus", "rolling"},
        "description": "Characteristic head tilt from E. cuniculi, ear infection, or stroke.",
        "description_ja": "エンセファリトゾーン、耳感染、脳卒中による特徴的な斜頸。",
        "urgency": "high",
        "recommended_tests": ["serology", "otoscopic_exam", "radiography"],
    },
    {
        "name": "Antibiotic Toxicity",
        "name_ja": "抗生物質中毒",
        "symptoms": {"diarrhea", "appetite_loss", "lethargy", "sudden_death"},
        "description": "Fatal dysbiosis from antibiotics unsafe for rabbits.",
        "description_ja": "ウサギに不安全な抗生物質による致死的菌交代現象。",
        "urgency": "emergency",
        "recommended_tests": ["medication_review", "fecal_exam"],
    },
    {
        "name": "Anal Gland Impaction",
        "name_ja": "肛門腺閉塞",
        "symptoms": {"perianal_irritation", "foul_odor", "scooting"},
        "description": "Buildup of waxy secretions in the scent glands flanking the anus.",
        "description_ja": "肛門両側の臭腺の分泌物の蓄積。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Hairball / Trichobezoar",
        "name_ja": "毛球症",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "abdominal_distension"},
        "description": "Accumulation of hair in the stomach contributing to GI stasis.",
        "description_ja": "胃内の毛球蓄積により消化管うっ滞に寄与する。",
        "urgency": "high",
        "recommended_tests": ["radiography", "physical_exam"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "appetite_loss", "labored_breathing", "sudden_death"},
        "description": "Systemic bacterial infection.",
        "description_ja": "全身性細菌感染。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count"],
    },
    {
        "name": "Hutch Burn / Urine Scald",
        "name_ja": "尿やけ",
        "symptoms": {"perianal_irritation", "hair_loss", "skin_redness", "skin_ulcers"},
        "description": "Skin irritation and ulceration from prolonged contact with urine-soaked bedding.",
        "description_ja": "尿で汚れた床材との長時間接触による皮膚刺激と潰瘍。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    {
        "name": "Aortic Arteriosclerosis",
        "name_ja": "大動脈硬化症",
        "symptoms": {"hind_limb_weakness", "lethargy", "reduced_activity"},
        "description": "Hardening of the aorta in older rabbits, reducing blood flow.",
        "description_ja": "高齢ウサギの大動脈硬化による血流低下。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "echocardiography"],
    },
    {
        "name": "Lead Poisoning",
        "name_ja": "鉛中毒",
        "symptoms": {"appetite_loss", "lethargy", "seizures", "anemia", "weight_loss"},
        "description": "Ingestion of lead paint or other lead-containing items.",
        "description_ja": "鉛塗料やその他の鉛含有物の摂取。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "radiography"],
    },
    {
        "name": "Intervertebral Disc Disease",
        "name_ja": "椎間板疾患",
        "symptoms": {"hind_limb_weakness", "pain", "reduced_activity", "urinary_incontinence"},
        "description": "Disc herniation or degeneration causing spinal cord compression.",
        "description_ja": "椎間板ヘルニアまたは変性による脊髄圧迫。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ct_scan", "mri"],
    },
    {
        "name": "Perineal Dermatitis",
        "name_ja": "会陰部皮膚炎",
        "symptoms": {"perianal_irritation", "hair_loss", "skin_redness", "foul_odor"},
        "description": "Skin inflammation around the perineum from urine/fecal soiling.",
        "description_ja": "尿・糞便汚染による会陰部の皮膚炎。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    {
        "name": "Encephalitozoon cuniculi - Renal Form",
        "name_ja": "エンセファリトゾーン症（腎型）",
        "symptoms": {"increased_thirst", "increased_urination", "weight_loss", "lethargy"},
        "description": "Renal manifestation of E. cuniculi causing chronic interstitial nephritis.",
        "description_ja": "エンセファリトゾーンの腎臓型で、慢性間質性腎炎を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["serology", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Tularemia",
        "name_ja": "野兎病",
        "symptoms": {"fever", "lethargy", "enlarged_lymph_nodes", "sudden_death"},
        "description": "Francisella tularensis infection, zoonotic and often rapidly fatal.",
        "description_ja": "フランシセラ菌感染で、人獣共通感染症であり急速に致死的。",
        "urgency": "emergency",
        "recommended_tests": ["serology", "blood_culture"],
    },
    {
        "name": "Papillomatosis",
        "name_ja": "乳頭腫症",
        "symptoms": {"skin_nodules", "skin_lump"},
        "description": "Viral papillomas appearing as wart-like growths.",
        "description_ja": "ウイルス性乳頭腫でイボ状の増殖。",
        "urgency": "low",
        "recommended_tests": ["biopsy"],
    },
    {
        "name": "Gastric Ulcer",
        "name_ja": "胃潰瘍",
        "symptoms": {"appetite_loss", "teeth_grinding", "lethargy", "bloody_stool"},
        "description": "Ulceration of the stomach lining from stress or NSAID use.",
        "description_ja": "ストレスやNSAID使用による胃粘膜の潰瘍。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_occult_blood"],
    },
    {
        "name": "Red Urine (Normal / Porphyrins)",
        "name_ja": "赤色尿（正常・ポルフィリン）",
        "symptoms": {"red_urine", "no_other_symptoms"},
        "description": "Plant pigment-tinged urine that is normal; must be distinguished from hematuria.",
        "description_ja": "植物色素による正常な赤色尿で、血尿との鑑別が必要。",
        "urgency": "low",
        "recommended_tests": ["urinalysis"],
    },
    {
        "name": "Bordetella Infection",
        "name_ja": "ボルデテラ感染症",
        "symptoms": {"sneezing", "nasal_discharge", "labored_breathing", "lethargy"},
        "description": "Bordetella bronchiseptica respiratory infection.",
        "description_ja": "ボルデテラ菌による呼吸器感染。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "radiography"],
    },
    {
        "name": "Dermal Papillomatosis (Shope)",
        "name_ja": "ショープ乳頭腫",
        "symptoms": {"skin_nodules", "horn_like_growths"},
        "description": "Viral papillomas that may develop horn-like keratinous growths.",
        "description_ja": "角質性の角状増殖を形成するウイルス性乳頭腫。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Hepatic Coccidiosis",
        "name_ja": "肝臓コクシジウム症",
        "symptoms": {"jaundice", "weight_loss", "appetite_loss", "abdominal_distension"},
        "description": "Severe form of coccidiosis affecting the liver.",
        "description_ja": "肝臓に影響する重度のコクシジウム症。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "blood_chemistry"],
    },
    {
        "name": "Abscess (Retrobulbar)",
        "name_ja": "眼窩後部膿瘍",
        "symptoms": {"eye_bulging", "eye_discharge", "facial_swelling"},
        "description": "Abscess behind the eye, usually from tooth root infection.",
        "description_ja": "通常は歯根感染に由来する眼の後方の膿瘍。",
        "urgency": "high",
        "recommended_tests": ["skull_radiography", "ct_scan"],
    },
    {
        "name": "Calcium Deficiency / Metabolic Bone Disease",
        "name_ja": "カルシウム欠乏症・代謝性骨疾患",
        "symptoms": {"fractures", "lameness", "teeth_grinding", "reduced_activity"},
        "description": "Weakened bones from inadequate calcium or vitamin D.",
        "description_ja": "カルシウムまたはビタミンD不足による骨の脆弱化。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "blood_chemistry"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite loss"},
    "reduced_fecal_output": {"ja": "糞量減少", "en": "Reduced fecal output"},
    "lethargy": {"ja": "元気消失", "en": "Lethargy"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth grinding (bruxism)"},
    "rapid_breathing": {"ja": "呼吸促迫", "en": "Rapid breathing"},
    "mucoid_stool": {"ja": "粘液便", "en": "Mucoid stool"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "soft_cecotropes": {"ja": "軟盲腸便", "en": "Soft cecotropes"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "sudden_lethargy": {"ja": "急性の元気消失", "en": "Sudden lethargy"},
    "pale_mucous_membranes": {"ja": "粘膜蒼白", "en": "Pale mucous membranes"},
    "overgrown_teeth": {"ja": "歯の過成長", "en": "Overgrown teeth"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "facial_abscess": {"ja": "顔面膿瘍", "en": "Facial abscess"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "epiphora": {"ja": "流涙", "en": "Epiphora (excessive tearing)"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "abscess": {"ja": "膿瘍", "en": "Abscess"},
    "labored_breathing": {"ja": "呼吸困難", "en": "Labored breathing"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "eye_bulging": {"ja": "眼球突出", "en": "Eye bulging"},
    "bilateral_exophthalmos": {"ja": "両側性眼球突出", "en": "Bilateral exophthalmos"},
    "reduced_activity": {"ja": "活動性低下", "en": "Reduced activity"},
    "loss_of_balance": {"ja": "平衡感覚喪失", "en": "Loss of balance"},
    "hind_limb_weakness": {"ja": "後肢の脱力", "en": "Hind limb weakness"},
    "urinary_incontinence": {"ja": "尿失禁", "en": "Urinary incontinence"},
    "cataracts": {"ja": "白内障", "en": "Cataracts"},
    "perianal_irritation": {"ja": "肛門周囲の刺激", "en": "Perianal irritation"},
    "rough_coat": {"ja": "被毛粗剛", "en": "Rough coat"},
    "ear_crusting": {"ja": "耳の痂皮", "en": "Ear crusting"},
    "head_shaking": {"ja": "頭を振る", "en": "Head shaking"},
    "scratching_ears": {"ja": "耳を掻く", "en": "Scratching ears"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear discharge"},
    "dandruff": {"ja": "フケ", "en": "Dandruff"},
    "itching": {"ja": "掻痒", "en": "Itching"},
    "hair_loss": {"ja": "脱毛", "en": "Hair loss"},
    "skin_flaking": {"ja": "皮膚の剥離", "en": "Skin flaking"},
    "maggots_visible": {"ja": "ウジ虫の目視", "en": "Maggots visible"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "skin_wounds": {"ja": "皮膚の傷", "en": "Skin wounds"},
    "pain": {"ja": "痛み", "en": "Pain"},
    "eyelid_swelling": {"ja": "眼瞼腫脹", "en": "Eyelid swelling"},
    "genital_swelling": {"ja": "外陰部腫脹", "en": "Genital swelling"},
    "skin_nodules": {"ja": "皮膚結節", "en": "Skin nodules"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "nasal_bleeding": {"ja": "鼻出血", "en": "Nasal bleeding"},
    "seizures": {"ja": "痙攣発作", "en": "Seizures"},
    "genital_lesions": {"ja": "外陰部病変", "en": "Genital lesions"},
    "nasal_crusting": {"ja": "鼻の痂皮", "en": "Nasal crusting"},
    "lip_crusting": {"ja": "口唇の痂皮", "en": "Lip crusting"},
    "skin_ulcers": {"ja": "皮膚潰瘍", "en": "Skin ulcers"},
    "skin_crusting": {"ja": "皮膚痂皮", "en": "Skin crusting"},
    "circular_lesions": {"ja": "円形病変", "en": "Circular lesions"},
    "foot_sores": {"ja": "足裏の潰瘍", "en": "Foot sores"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "discharge": {"ja": "分泌物", "en": "Discharge"},
    "skin_redness": {"ja": "皮膚発赤", "en": "Skin redness"},
    "overgrooming": {"ja": "過度のグルーミング", "en": "Overgrooming"},
    "splayed_limbs": {"ja": "四肢の外転", "en": "Splayed limbs"},
    "inability_to_stand": {"ja": "起立不能", "en": "Inability to stand"},
    "hind_limb_paralysis": {"ja": "後肢麻痺", "en": "Hind limb paralysis"},
    "fecal_incontinence": {"ja": "糞便失禁", "en": "Fecal incontinence"},
    "limb_deformity": {"ja": "四肢変形", "en": "Limb deformity"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "difficulty_hopping": {"ja": "ホッピング困難", "en": "Difficulty hopping"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "rolling": {"ja": "転がり", "en": "Rolling"},
    "loss_of_consciousness": {"ja": "意識消失", "en": "Loss of consciousness"},
    "tremors": {"ja": "震え", "en": "Tremors"},
    "paddling": {"ja": "パドリング（足の空振り）", "en": "Paddling"},
    "vaginal_bleeding": {"ja": "膣出血", "en": "Vaginal bleeding"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal discharge"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "mammary_swelling": {"ja": "乳腺腫脹", "en": "Mammary swelling"},
    "mammary_redness": {"ja": "乳腺発赤", "en": "Mammary redness"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "testicular_swelling": {"ja": "精巣腫大", "en": "Testicular swelling"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye redness"},
    "squinting": {"ja": "眼を細める", "en": "Squinting"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "vision_loss": {"ja": "視力喪失", "en": "Vision loss"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in urine"},
    "straining_to_urinate": {"ja": "排尿時のいきみ", "en": "Straining to urinate"},
    "thick_white_urine": {"ja": "白濁尿", "en": "Thick white urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent urination"},
    "increased_thirst": {"ja": "多飲", "en": "Increased thirst"},
    "increased_urination": {"ja": "多尿", "en": "Increased urination"},
    "foul_urine": {"ja": "悪臭尿", "en": "Foul-smelling urine"},
    "enlarged_lymph_nodes": {"ja": "リンパ節腫大", "en": "Enlarged lymph nodes"},
    "mammary_mass": {"ja": "乳腺腫瘤", "en": "Mammary mass"},
    "skin_lump": {"ja": "皮膚の腫瘤", "en": "Skin lump"},
    "skin_mass_growth": {"ja": "皮膚腫瘤の増大", "en": "Growing skin mass"},
    "ulceration": {"ja": "潰瘍化", "en": "Ulceration"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "weight_gain": {"ja": "体重増加", "en": "Weight gain"},
    "cecotrope_accumulation": {"ja": "盲腸便の蓄積", "en": "Cecotrope accumulation"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "sunken_eyes": {"ja": "眼の陥没", "en": "Sunken eyes"},
    "skin_tenting": {"ja": "皮膚テンティング", "en": "Skin tenting"},
    "kidney_calcification": {"ja": "腎臓石灰化", "en": "Kidney calcification"},
    "scooting": {"ja": "お尻引きずり", "en": "Scooting"},
    "red_urine": {"ja": "赤色尿", "en": "Red urine"},
    "no_other_symptoms": {"ja": "その他の症状なし", "en": "No other symptoms"},
    "horn_like_growths": {"ja": "角状の増殖", "en": "Horn-like growths"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
