"""Rabbit disease dictionary and analysis module."""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    {
        "name": "Gastrointestinal Stasis",
        "name_ja": "消化管うっ滞",
        "symptoms": {"appetite_loss", "lethargy", "abdominal_pain", "reduced_fecal_output", "teeth_grinding", "hunched_posture"},
        "description": "A potentially life-threatening slowdown or complete cessation of gut motility, often triggered by stress, pain, dehydration, or inadequate fibre intake.",
        "description_ja": "ストレス、痛み、脱水、繊維不足などが原因で消化管の蠕動が低下または停止する、命に関わる疾患です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "abdominal_xray", "blood_chemistry"],
    },
    {
        "name": "Gastric Dilation (Bloat)",
        "name_ja": "胃拡張（鼓脹症）",
        "symptoms": {"abdominal_distension", "abdominal_pain", "lethargy", "appetite_loss", "teeth_grinding", "rapid_breathing"},
        "description": "Acute distension of the stomach with gas or fluid. Can rapidly become fatal if untreated.",
        "description_ja": "胃がガスや液体で急激に膨張する状態。未治療では急速に致死的になり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "physical_exam", "blood_gas_analysis"],
    },
    {
        "name": "Mucoid Enteropathy",
        "name_ja": "粘液性腸症",
        "symptoms": {"mucus_in_stool", "diarrhea", "abdominal_distension", "appetite_loss", "lethargy", "dehydration"},
        "description": "A condition characterised by excessive mucus production in the intestine, often seen in young rabbits. Can cause impaction and dehydration.",
        "description_ja": "腸内で過剰な粘液が産生される疾患で、若いウサギに多く見られます。閉塞や脱水を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "abdominal_xray", "fecal_exam"],
    },
    {
        "name": "Cecal Dysbiosis",
        "name_ja": "盲腸内細菌叢異常",
        "symptoms": {"soft_stool", "diarrhea", "abdominal_pain", "appetite_loss", "gas", "abnormal_cecotropes"},
        "description": "Disruption of the normal cecal microbiome, often caused by inappropriate diet, antibiotics, or stress.",
        "description_ja": "不適切な食事、抗生物質、ストレスなどにより盲腸の正常な微生物叢が乱れる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "physical_exam", "diet_review"],
    },
    {
        "name": "Acute Enteritis",
        "name_ja": "急性腸炎",
        "symptoms": {"diarrhea", "dehydration", "lethargy", "appetite_loss", "abdominal_pain", "fever"},
        "description": "Acute inflammation of the intestinal tract, commonly caused by bacterial infection (Clostridium, E. coli) or dietary indiscretion.",
        "description_ja": "細菌感染（クロストリジウム、大腸菌）や食事の不摂生による急性の腸管炎症です。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "blood_chemistry", "abdominal_xray"],
    },
    {
        "name": "Enterotoxemia",
        "name_ja": "腸管毒素血症",
        "symptoms": {"diarrhea", "lethargy", "sudden_death", "dehydration", "hypothermia", "abdominal_distension"},
        "description": "Overgrowth of Clostridium spiroforme or perfringens producing toxins that cause severe diarrhea and rapid death.",
        "description_ja": "クロストリジウム属菌の異常増殖により毒素が産生され、重度の下痢と急死を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_culture", "blood_chemistry", "necropsy"],
    },
    {
        "name": "Intestinal Obstruction",
        "name_ja": "腸閉塞",
        "symptoms": {"appetite_loss", "abdominal_pain", "abdominal_distension", "reduced_fecal_output", "lethargy", "teeth_grinding"},
        "description": "Complete or partial blockage of the intestine, often from ingested fur or foreign material. A surgical emergency.",
        "description_ja": "摂取した毛や異物による腸の完全または部分的な閉塞。外科的緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Hepatic Coccidiosis",
        "name_ja": "肝コクシジウム症",
        "symptoms": {"appetite_loss", "weight_loss", "jaundice", "abdominal_distension", "diarrhea", "lethargy"},
        "description": "Infection of the liver by Eimeria stiedai, causing bile duct hyperplasia and hepatic failure, primarily in young rabbits.",
        "description_ja": "アイメリア・スティーダイによる肝臓感染で、胆管過形成や肝不全を引き起こし、主に若いウサギに見られます。",
        "urgency": "high",
        "recommended_tests": ["fecal_flotation", "blood_chemistry", "liver_ultrasound"],
    },
    {
        "name": "Intestinal Coccidiosis",
        "name_ja": "腸コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "appetite_loss", "lethargy", "blood_in_stool"},
        "description": "Infection of the intestine by various Eimeria species causing diarrhea and weight loss, most severe in young rabbits.",
        "description_ja": "各種アイメリア属による腸感染で、下痢や体重減少を引き起こし、若いウサギで重症化します。",
        "urgency": "high",
        "recommended_tests": ["fecal_flotation", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Dental Malocclusion",
        "name_ja": "歯の不正咬合",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "facial_swelling", "teeth_grinding", "difficulty_eating"},
        "description": "Misalignment or overgrowth of incisors and/or cheek teeth preventing normal occlusion, leading to spurs and soft tissue injury.",
        "description_ja": "切歯や臼歯の不整列や過長により正常な咬合ができず、棘状突起が軟部組織を傷つけます。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs", "ct_scan"],
    },
    {
        "name": "Molar Spurs",
        "name_ja": "臼歯棘状突起",
        "symptoms": {"drooling", "appetite_loss", "weight_loss", "difficulty_eating", "facial_swelling", "eye_discharge"},
        "description": "Sharp points forming on cheek teeth that lacerate the tongue or buccal mucosa, causing pain and inability to eat.",
        "description_ja": "臼歯に鋭い棘状突起が形成され、舌や頬粘膜を傷つけ、痛みや食事困難を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    {
        "name": "Incisor Overgrowth",
        "name_ja": "切歯過長",
        "symptoms": {"difficulty_eating", "drooling", "weight_loss", "visible_tooth_overgrowth"},
        "description": "Excessive growth of the incisor teeth, often due to genetic malocclusion or insufficient wear from diet.",
        "description_ja": "遺伝的不正咬合や食事による摩耗不足が原因で切歯が過度に伸長する状態です。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    {
        "name": "Tooth Root Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "appetite_loss", "drooling", "eye_discharge", "nasal_discharge", "weight_loss"},
        "description": "Bacterial infection at the root of a tooth, forming a localised abscess that may extend into the jaw or orbit.",
        "description_ja": "歯根部の細菌感染により膿瘍が形成され、顎や眼窩に波及することがあります。",
        "urgency": "high",
        "recommended_tests": ["skull_radiographs", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Tooth Root Elongation",
        "name_ja": "歯根伸長",
        "symptoms": {"eye_discharge", "epiphora", "appetite_loss", "facial_swelling", "nasal_discharge"},
        "description": "Apical elongation of molar or premolar roots into the orbit or nasal cavity, causing dacryocystitis or retrobulbar pressure.",
        "description_ja": "臼歯や前臼歯の歯根が眼窩や鼻腔に伸長し、涙嚢炎や球後圧迫を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skull_radiographs", "ct_scan", "ophthalmologic_exam"],
    },
    {
        "name": "Pasteurellosis (Snuffles)",
        "name_ja": "パスツレラ症（スナッフル）",
        "symptoms": {"nasal_discharge", "sneezing", "conjunctivitis", "head_tilt", "abscess", "respiratory_distress"},
        "description": "Multisystemic infection by Pasteurella multocida causing upper respiratory disease, abscesses, otitis, and potentially septicaemia.",
        "description_ja": "パスツレラ・ムルトシダによる多臓器感染で、上部呼吸器疾患、膿瘍、中耳炎、敗血症を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "nasal_swab", "skull_radiographs", "complete_blood_count"],
    },
    {
        "name": "Bacterial Pneumonia",
        "name_ja": "細菌性肺炎",
        "symptoms": {"respiratory_distress", "nasal_discharge", "fever", "lethargy", "appetite_loss", "cyanosis"},
        "description": "Bacterial infection of the lungs, often secondary to pasteurellosis. Can be rapidly fatal in rabbits.",
        "description_ja": "肺の細菌感染で、パスツレラ症に続発することが多く、急速に致死的になり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["thoracic_radiographs", "complete_blood_count", "culture_sensitivity"],
    },
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"sneezing", "nasal_discharge", "conjunctivitis", "lethargy", "appetite_loss"},
        "description": "Infection of the nasal passages and sinuses, commonly caused by Pasteurella, Bordetella, or Staphylococcus.",
        "description_ja": "パスツレラ、ボルデテラ、ブドウ球菌などによる鼻腔・副鼻腔の感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_swab", "culture_sensitivity", "skull_radiographs"],
    },
    {
        "name": "Thymoma",
        "name_ja": "胸腺腫",
        "symptoms": {"respiratory_distress", "exophthalmos", "third_eyelid_protrusion", "lethargy", "weight_loss", "exercise_intolerance"},
        "description": "Neoplasm of the thymus gland in the cranial mediastinum causing respiratory compromise and bilateral exophthalmos.",
        "description_ja": "前縦隔の胸腺腫瘍で、呼吸障害と両側性の眼球突出を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["thoracic_radiographs", "ct_scan", "fine_needle_aspirate", "complete_blood_count"],
    },
    {
        "name": "Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"rapid_breathing", "lethargy", "recumbency", "seizures", "hyperthermia", "salivation"},
        "description": "Life-threatening hyperthermia, rabbits are highly susceptible to heat stress above 28-30 degrees Celsius.",
        "description_ja": "致死的な高体温症。ウサギは28〜30度以上の暑さに非常に弱い動物です。",
        "urgency": "emergency",
        "recommended_tests": ["rectal_temperature", "blood_chemistry", "blood_gas_analysis"],
    },
    {
        "name": "Urinary Sludge",
        "name_ja": "尿路スラッジ（砂状尿）",
        "symptoms": {"thick_white_urine", "straining_to_urinate", "urine_staining", "lethargy", "appetite_loss", "hunched_posture"},
        "description": "Accumulation of calcium carbonate sediment in the bladder causing thick, paste-like urine and discomfort.",
        "description_ja": "膀胱内に�炭酸カルシウムの沈殿物が蓄積し、ペースト状の尿と不快感を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "abdominal_xray", "abdominal_ultrasound"],
    },
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"straining_to_urinate", "blood_in_urine", "appetite_loss", "teeth_grinding", "hunched_posture", "frequent_urination"},
        "description": "Formation of calcium-based calculi in the kidneys, ureters, or bladder causing pain, haematuria, and potential obstruction.",
        "description_ja": "腎臓、尿管、膀胱にカルシウム系結石が形成され、痛み、血尿、閉塞を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "urinalysis", "abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Chronic Renal Failure",
        "name_ja": "慢性腎不全",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "appetite_loss", "lethargy", "dehydration"},
        "description": "Progressive and irreversible loss of kidney function leading to azotaemia, electrolyte imbalances, and uraemia.",
        "description_ja": "腎機能の進行性かつ不可逆的な低下により、高窒素血症、電解質異常、尿毒症を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_ultrasound"],
    },
    {
        "name": "Acute Renal Failure",
        "name_ja": "急性腎不全",
        "symptoms": {"appetite_loss", "lethargy", "decreased_urination", "dehydration", "hypothermia", "seizures"},
        "description": "Sudden loss of kidney function from toxin exposure, infection, or obstruction. May be reversible with prompt treatment.",
        "description_ja": "毒物曝露、感染、閉塞による腎機能の急激な低下。迅速な治療で回復の可能性があります。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "urinalysis", "abdominal_ultrasound"],
    },
    {
        "name": "Encephalitozoon cuniculi (E. cuniculi)",
        "name_ja": "エンセファリトゾーン・クニクリ感染症",
        "symptoms": {"head_tilt", "nystagmus", "hind_limb_weakness", "urinary_incontinence", "cataracts", "ataxia"},
        "description": "Obligate intracellular microsporidian parasite causing granulomatous encephalitis, nephritis, and phacoclastic uveitis.",
        "description_ja": "偏性細胞内寄生微胞子虫で、肉芽腫性脳炎、腎炎、水晶体起因性ぶどう膜炎を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["e_cuniculi_titre", "blood_chemistry", "urinalysis", "ophthalmologic_exam"],
    },
    {
        "name": "Pinworms (Passalurus ambiguus)",
        "name_ja": "蟯虫症",
        "symptoms": {"perianal_irritation", "soft_stool", "weight_loss", "restlessness"},
        "description": "Common intestinal nematode infestation. Usually subclinical but heavy burdens may cause perianal irritation.",
        "description_ja": "一般的な腸管線虫感染。通常は無症状ですが、大量感染では肛門周囲の刺激を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["fecal_flotation", "scotch_tape_test"],
    },
    {
        "name": "Ear Mites (Psoroptes cuniculi)",
        "name_ja": "耳ダニ症",
        "symptoms": {"ear_crusting", "head_shaking", "ear_scratching", "ear_discharge", "head_tilt"},
        "description": "Infestation of the ear canal by Psoroptes cuniculi mites, causing thick crusty exudate and intense pruritus.",
        "description_ja": "ウサギキュウセンヒゼンダニによる耳道感染で、厚い痂皮性滲出物と強い掻痒感を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "ear_swab_microscopy"],
    },
    {
        "name": "Fur Mites (Cheyletiella parasitovorax)",
        "name_ja": "ツメダニ症",
        "symptoms": {"dandruff", "hair_loss", "itching", "skin_flaking", "restlessness"},
        "description": "Surface-dwelling mite causing excessive dandruff (walking dandruff), mild pruritus, and patchy alopecia.",
        "description_ja": "体表に寄生するダニで、過剰なフケ（歩くフケ）、軽度の掻痒感、斑状脱毛を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "scotch_tape_test", "dermatologic_exam"],
    },
    {
        "name": "Myiasis (Flystrike)",
        "name_ja": "ハエウジ症（フライストライク）",
        "symptoms": {"maggots_visible", "skin_wounds", "lethargy", "appetite_loss", "foul_odor", "restlessness"},
        "description": "Invasion of living tissue by fly larvae (blowflies), often in soiled perineal areas. Rapidly fatal if untreated.",
        "description_ja": "ハエの幼虫が生体組織に侵入する疾患で、汚染された会陰部に多発。未治療では急速に致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "wound_assessment", "complete_blood_count"],
    },
    {
        "name": "Sarcoptic Mange",
        "name_ja": "疥癬",
        "symptoms": {"intense_itching", "hair_loss", "skin_crusting", "skin_thickening", "restlessness"},
        "description": "Burrowing mite infestation causing intense pruritus, crusting, and hyperkeratosis, primarily on the face and ears.",
        "description_ja": "穿孔性ダニの感染で、主に顔や耳に強い掻痒感、痂皮形成、角質増殖を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "dermatologic_exam"],
    },
    {
        "name": "Myxomatosis",
        "name_ja": "粘液腫症",
        "symptoms": {"eyelid_swelling", "genital_swelling", "nasal_discharge", "fever", "lethargy", "skin_nodules"},
        "description": "Highly lethal viral disease (Myxoma virus) transmitted by fleas and mosquitoes. Causes oedematous swelling and skin tumours.",
        "description_ja": "ノミや蚊が媒介する致死率の高いウイルス疾患。浮腫性腫脹と皮膚腫瘍を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_signs", "pcr_test", "histopathology"],
    },
    {
        "name": "Rabbit Haemorrhagic Disease (RHDV/VHD)",
        "name_ja": "ウサギ出血病（RHDV/VHD）",
        "symptoms": {"sudden_death", "epistaxis", "bloody_nasal_discharge", "fever", "lethargy", "seizures"},
        "description": "Highly contagious and usually fatal calicivirus infection causing acute hepatic necrosis and disseminated intravascular coagulation.",
        "description_ja": "高度に伝染性で通常致死的なカリシウイルス感染症。急性肝壊死と播種性血管内凝固を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_test", "necropsy", "liver_histopathology"],
    },
    {
        "name": "RHDV2",
        "name_ja": "ウサギ出血病2型",
        "symptoms": {"sudden_death", "lethargy", "fever", "jaundice", "epistaxis", "appetite_loss"},
        "description": "Variant strain of rabbit haemorrhagic disease virus affecting rabbits of all ages including kits, with variable mortality.",
        "description_ja": "ウサギ出血病ウイルスの変異株で、仔ウサギを含む全年齢のウサギに感染し、致死率は変動します。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_test", "necropsy", "serology"],
    },
    {
        "name": "Treponematosis (Rabbit Syphilis)",
        "name_ja": "トレポネーマ症（ウサギ梅毒）",
        "symptoms": {"genital_lesions", "nasal_lesions", "lip_crusting", "facial_crusting", "ulceration"},
        "description": "Infection by Treponema cuniculi causing crusty lesions around the nose, lips, eyelids, and genitalia.",
        "description_ja": "トレポネーマ・クニクリによる感染で、鼻、口唇、眼瞼、生殖器周囲に痂皮性病変を形成します。",
        "urgency": "moderate",
        "recommended_tests": ["clinical_signs", "biopsy", "serology"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症（白癬）",
        "symptoms": {"circular_hair_loss", "skin_crusting", "dandruff", "itching"},
        "description": "Fungal skin infection, most commonly Trichophyton mentagrophytes, causing circular patches of alopecia with scaling.",
        "description_ja": "トリコフィトン・メンタグロフィテスなどによる真菌性皮膚感染で、鱗屑を伴う円形脱毛を形成します。",
        "urgency": "low",
        "recommended_tests": ["fungal_culture", "skin_scraping", "woods_lamp"],
    },
    {
        "name": "Pododermatitis (Sore Hocks)",
        "name_ja": "足底皮膚炎（ソアホック）",
        "symptoms": {"foot_lesions", "lameness", "reluctance_to_move", "weight_shifting", "foot_swelling"},
        "description": "Ulcerative dermatitis of the plantar surface of the hind feet, caused by pressure, wire flooring, obesity, or poor hygiene.",
        "description_ja": "後肢足底面の潰瘍性皮膚炎で、圧迫、金網床、肥満、不衛生が原因となります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Subcutaneous Abscess",
        "name_ja": "皮下膿瘍",
        "symptoms": {"abscess", "swelling", "lethargy", "appetite_loss", "fever"},
        "description": "Encapsulated bacterial infection forming thick caseous pus, commonly Pasteurella or Staphylococcus. Difficult to resolve.",
        "description_ja": "パスツレラやブドウ球菌による被包性細菌感染で、濃厚なチーズ様の膿を形成します。治癒困難です。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "fine_needle_aspirate", "radiographs"],
    },
    {
        "name": "Retrobulbar Abscess",
        "name_ja": "球後膿瘍",
        "symptoms": {"exophthalmos", "eye_discharge", "appetite_loss", "facial_swelling", "third_eyelid_protrusion"},
        "description": "Abscess behind the eye, often arising from molar root infection, causing progressive exophthalmos.",
        "description_ja": "臼歯の歯根感染から波及することが多い眼球後方の膿瘍で、進行性の眼球突出を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_radiographs", "ct_scan", "ophthalmologic_exam"],
    },
    {
        "name": "Mandibular Abscess",
        "name_ja": "下顎膿瘍",
        "symptoms": {"jaw_swelling", "drooling", "appetite_loss", "facial_swelling", "weight_loss"},
        "description": "Deep-seated abscess of the mandible, typically arising from dental disease or penetrating wound.",
        "description_ja": "歯科疾患や刺創から生じる下顎の深部膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["skull_radiographs", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Splay Leg",
        "name_ja": "開脚症",
        "symptoms": {"limb_splaying", "inability_to_stand", "difficulty_moving"},
        "description": "Congenital or developmental condition where one or more limbs splay laterally, preventing normal locomotion.",
        "description_ja": "先天的または発達性の疾患で、四肢が外側に開き正常な移動ができなくなります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Spinal Fracture / Luxation",
        "name_ja": "脊椎骨折・脱臼",
        "symptoms": {"hind_limb_paralysis", "urinary_incontinence", "fecal_incontinence", "pain_response_loss", "recumbency"},
        "description": "Fracture or luxation of vertebrae, often lumbar, from improper handling, sudden movements, or trauma. Often results in permanent paralysis.",
        "description_ja": "不適切な取り扱いや急な動き、外傷による脊椎の骨折や脱臼。永続的な麻痺に至ることが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["spinal_radiographs", "neurological_exam", "ct_scan"],
    },
    {
        "name": "Osteoarthritis",
        "name_ja": "変形性関節症",
        "symptoms": {"lameness", "reluctance_to_move", "stiffness", "decreased_activity", "difficulty_grooming"},
        "description": "Degenerative joint disease causing chronic pain and reduced mobility, common in older or obese rabbits.",
        "description_ja": "関節の変性疾患で、慢性的な痛みと運動性低下を引き起こし、高齢や肥満のウサギに多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["radiographs", "physical_exam", "pain_assessment"],
    },
    {
        "name": "Fracture (Long Bone)",
        "name_ja": "長管骨骨折",
        "symptoms": {"lameness", "swelling", "pain_on_palpation", "non_weight_bearing", "crepitus"},
        "description": "Fracture of a limb bone, rabbits have relatively fragile bones and are prone to fractures from falls or improper handling.",
        "description_ja": "四肢骨の骨折。ウサギは骨が比較的脆く、落下や不適切な取り扱いで骨折しやすいです。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam"],
    },
    {
        "name": "Vertebral Spondylosis",
        "name_ja": "脊椎変形性脊椎症",
        "symptoms": {"stiffness", "reluctance_to_move", "hunched_posture", "hind_limb_weakness", "decreased_activity"},
        "description": "Degenerative changes of the vertebral column with bony spur formation, common in elderly rabbits.",
        "description_ja": "脊柱の変性変化で骨棘が形成される疾患。高齢のウサギに多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["spinal_radiographs", "neurological_exam"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "nystagmus", "ataxia", "circling", "rolling", "appetite_loss"},
        "description": "Dysfunction of the vestibular system (peripheral or central) causing head tilt, ataxia, and nystagmus. Common causes include E. cuniculi and otitis media/interna.",
        "description_ja": "前庭系の機能障害（末梢性または中枢性）で、斜頸、運動失調、眼振を引き起こします。主な原因はE. cuniculiと中耳・内耳炎です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "skull_radiographs", "e_cuniculi_titre", "ct_scan"],
    },
    {
        "name": "Otitis Media / Interna",
        "name_ja": "中耳炎・内耳炎",
        "symptoms": {"head_tilt", "nystagmus", "ear_discharge", "facial_nerve_paralysis", "appetite_loss", "ataxia"},
        "description": "Bacterial infection of the middle and/or inner ear, commonly from Pasteurella extension. Causes vestibular signs.",
        "description_ja": "パスツレラの波及による中耳・内耳の細菌感染。前庭症状を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_radiographs", "ct_scan", "culture_sensitivity", "otoscopic_exam"],
    },
    {
        "name": "Otitis Externa",
        "name_ja": "外耳炎",
        "symptoms": {"ear_discharge", "ear_scratching", "head_shaking", "ear_redness", "ear_odor"},
        "description": "Inflammation or infection of the external ear canal, from bacteria, yeast, or mite infestation.",
        "description_ja": "細菌、酵母、ダニ感染による外耳道の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "ear_swab_microscopy", "culture_sensitivity"],
    },
    {
        "name": "Hind Limb Paresis / Paralysis",
        "name_ja": "後肢不全麻痺・麻痺",
        "symptoms": {"hind_limb_weakness", "hind_limb_paralysis", "urinary_incontinence", "dragging_hind_legs", "muscle_atrophy"},
        "description": "Weakness or complete loss of motor function in the hind limbs from spinal injury, E. cuniculi, spondylosis, or neoplasia.",
        "description_ja": "脊髄損傷、E. cuniculi、脊椎症、腫瘍による後肢の筋力低下または完全な運動機能喪失です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "spinal_radiographs", "e_cuniculi_titre", "mri"],
    },
    {
        "name": "Seizures / Epilepsy",
        "name_ja": "てんかん・痙攣発作",
        "symptoms": {"seizures", "loss_of_consciousness", "paddling", "salivation", "urinary_incontinence"},
        "description": "Abnormal neuronal discharge causing convulsions, from E. cuniculi encephalitis, toxins, metabolic disease, or idiopathic epilepsy.",
        "description_ja": "E. cuniculi脳炎、毒物、代謝性疾患、特発性てんかんによる異常な神経放電で痙攣を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["neurological_exam", "blood_chemistry", "e_cuniculi_titre", "mri"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "lethargy", "appetite_loss", "abdominal_distension", "excessive_thirst", "fever"},
        "description": "Bacterial infection of the uterus with pus accumulation, a life-threatening condition requiring emergency ovariohysterectomy.",
        "description_ja": "子宮内に膿が蓄積する細菌感染。緊急の卵巣子宮摘出術が必要な致命的疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "complete_blood_count", "blood_chemistry", "abdominal_xray"],
    },
    {
        "name": "Uterine Adenocarcinoma",
        "name_ja": "子宮腺癌",
        "symptoms": {"bloody_vaginal_discharge", "blood_in_urine", "abdominal_distension", "lethargy", "appetite_loss", "weight_loss"},
        "description": "Most common neoplasm in unspayed female rabbits over 3-4 years. Incidence approaches 60-80% in intact does over 5 years.",
        "description_ja": "3〜4歳以上の未避妊メスウサギで最も多い腫瘍。5歳以上の未避妊メスでは60〜80%の発生率に達します。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "thoracic_radiographs", "blood_chemistry", "histopathology"],
    },
    {
        "name": "Endometrial Hyperplasia",
        "name_ja": "子宮内膜過形成",
        "symptoms": {"bloody_vaginal_discharge", "blood_in_urine", "mammary_gland_changes", "lethargy"},
        "description": "Proliferative thickening of the uterine lining, often a precursor to uterine adenocarcinoma in intact does.",
        "description_ja": "子宮内膜の増殖性肥厚で、未避妊メスウサギの子宮腺癌の前駆病変となることが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray", "histopathology"],
    },
    {
        "name": "Pregnancy Toxemia (Ketosis)",
        "name_ja": "妊娠中毒症（ケトーシス）",
        "symptoms": {"appetite_loss", "lethargy", "weakness", "seizures", "acetone_breath", "sudden_death"},
        "description": "Metabolic disorder in late pregnancy or pseudopregnancy in obese does, causing hepatic lipidosis and ketoacidosis.",
        "description_ja": "肥満したメスウサギの妊娠後期や偽妊娠時に起こる代謝障害で、肝リピドーシスとケトアシドーシスを引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "urinalysis", "blood_glucose", "liver_ultrasound"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "mammary_redness", "fever", "lethargy", "appetite_loss", "painful_mammary"},
        "description": "Bacterial infection of the mammary glands, most common in lactating does. Can progress to septicaemia.",
        "description_ja": "授乳中のメスウサギに多い乳腺の細菌感染。敗血症に進行することがあります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Pseudopregnancy",
        "name_ja": "偽妊娠",
        "symptoms": {"nest_building", "fur_pulling", "mammary_swelling", "aggression", "appetite_changes"},
        "description": "Hormonal condition mimicking pregnancy with nest building and fur pulling, lasting approximately 16-18 days.",
        "description_ja": "妊娠を模倣するホルモン性疾患で、巣作りや毛むしりが見られ、約16〜18日間持続します。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "abdominal_ultrasound"],
    },
    {
        "name": "Dystocia",
        "name_ja": "難産",
        "symptoms": {"straining", "bloody_vaginal_discharge", "lethargy", "restlessness", "abdominal_contractions"},
        "description": "Difficulty giving birth, uncommon in rabbits but can occur with oversized kits, malpresentation, or uterine inertia.",
        "description_ja": "分娩困難。ウサギでは稀ですが、過大児、胎位異常、子宮無力症で起こり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_redness", "eye_discharge", "epiphora", "eyelid_swelling", "squinting"},
        "description": "Inflammation of the conjunctiva from bacterial infection (Pasteurella), irritants, allergens, or dental disease.",
        "description_ja": "細菌感染（パスツレラ）、刺激物、アレルゲン、歯科疾患による結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmologic_exam", "fluorescein_stain", "culture_sensitivity"],
    },
    {
        "name": "Dacryocystitis",
        "name_ja": "涙嚢炎",
        "symptoms": {"epiphora", "eye_discharge", "facial_wetness", "conjunctivitis", "nasal_discharge"},
        "description": "Infection or obstruction of the nasolacrimal duct, frequently caused by dental root elongation or Pasteurella infection.",
        "description_ja": "歯根伸長やパスツレラ感染による鼻涙管の感染または閉塞です。",
        "urgency": "moderate",
        "recommended_tests": ["nasolacrimal_duct_flush", "skull_radiographs", "culture_sensitivity"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "epiphora", "eye_redness", "corneal_opacity", "eye_discharge"},
        "description": "Erosion of the corneal epithelium from trauma, foreign body, or infection. Requires prompt treatment to prevent perforation.",
        "description_ja": "外傷、異物、感染による角膜上皮のびらん。穿孔を防ぐため迅速な治療が必要です。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmologic_exam", "culture_sensitivity"],
    },
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"lens_opacity", "vision_loss", "bumping_into_objects", "cataracts"},
        "description": "Opacity of the lens, may be congenital, age-related, or caused by E. cuniculi phacoclastic uveitis.",
        "description_ja": "水晶体の混濁。先天性、加齢性、またはE. cuniculi起因性ぶどう膜炎が原因となります。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmologic_exam", "e_cuniculi_titre", "ocular_ultrasound"],
    },
    {
        "name": "Glaucoma",
        "name_ja": "緑内障",
        "symptoms": {"buphthalmos", "eye_redness", "vision_loss", "eye_pain", "corneal_opacity"},
        "description": "Increased intraocular pressure causing globe enlargement and pain. May be primary or secondary to uveitis or lens luxation.",
        "description_ja": "眼圧上昇により眼球拡大と痛みを引き起こします。原発性またはぶどう膜炎・水晶体脱臼に続発します。",
        "urgency": "high",
        "recommended_tests": ["tonometry", "ophthalmologic_exam", "ocular_ultrasound"],
    },
    {
        "name": "Uveitis",
        "name_ja": "ぶどう膜炎",
        "symptoms": {"eye_redness", "squinting", "epiphora", "miosis", "lens_opacity", "eye_pain"},
        "description": "Inflammation of the uveal tract, commonly associated with E. cuniculi (phacoclastic uveitis) or Pasteurella infection.",
        "description_ja": "ぶどう膜の炎症で、E. cuniculi（水晶体起因性ぶどう膜炎）やパスツレラ感染に関連して起こります。",
        "urgency": "high",
        "recommended_tests": ["ophthalmologic_exam", "e_cuniculi_titre", "complete_blood_count"],
    },
    {
        "name": "Lens Luxation",
        "name_ja": "水晶体脱臼",
        "symptoms": {"eye_pain", "eye_redness", "corneal_opacity", "vision_loss", "lens_opacity"},
        "description": "Displacement of the lens from its normal position, often secondary to chronic uveitis or glaucoma.",
        "description_ja": "水晶体が正常な位置から移動する状態で、慢性ぶどう膜炎や緑内障に続発することが多いです。",
        "urgency": "high",
        "recommended_tests": ["ophthalmologic_exam", "ocular_ultrasound", "tonometry"],
    },
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"respiratory_distress", "exercise_intolerance", "lethargy", "cyanosis", "sudden_death", "weight_loss"},
        "description": "Primary disease of the heart muscle (dilated or hypertrophic) leading to congestive heart failure.",
        "description_ja": "心筋の原発性疾患（拡張型または肥大型）で、うっ血性心不全に至ります。",
        "urgency": "high",
        "recommended_tests": ["thoracic_radiographs", "echocardiography", "electrocardiogram"],
    },
    {
        "name": "Congestive Heart Failure",
        "name_ja": "うっ血性心不全",
        "symptoms": {"respiratory_distress", "exercise_intolerance", "lethargy", "cyanosis", "abdominal_distension", "weight_loss"},
        "description": "Inability of the heart to maintain adequate output, leading to pulmonary oedema and/or pleural effusion.",
        "description_ja": "心臓が十分な拍出量を維持できず、肺水腫や胸水を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["thoracic_radiographs", "echocardiography", "electrocardiogram", "blood_chemistry"],
    },
    {
        "name": "Atherosclerosis",
        "name_ja": "動脈硬化症",
        "symptoms": {"lethargy", "exercise_intolerance", "sudden_death", "weakness"},
        "description": "Deposition of lipid plaques in arterial walls. Rabbits are naturally susceptible, especially with high-fat diets.",
        "description_ja": "動脈壁への脂質プラークの沈着。ウサギは自然に感受性が高く、高脂肪食で増悪します。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "echocardiography", "lipid_panel"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "appetite_loss", "lymph_node_enlargement", "lethargy", "abdominal_distension", "respiratory_distress"},
        "description": "Malignant neoplasm of lymphoid tissue. Can be multicentric, mediastinal, alimentary, or cutaneous.",
        "description_ja": "リンパ組織の悪性腫瘍。多中心型、縦隔型、消化管型、皮膚型があります。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "complete_blood_count", "thoracic_radiographs", "abdominal_ultrasound"],
    },
    {
        "name": "Mammary Gland Tumour",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "mammary_swelling", "ulceration", "weight_loss", "lethargy"},
        "description": "Benign or malignant neoplasm of the mammary gland. Both adenocarcinomas and fibroadenomas occur in rabbits.",
        "description_ja": "乳腺の良性または悪性腫瘍。ウサギでは腺癌と線維腺腫の両方が発生します。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "thoracic_radiographs", "histopathology"],
    },
    {
        "name": "Testicular Tumour",
        "name_ja": "精巣腫瘍",
        "symptoms": {"testicular_enlargement", "testicular_asymmetry", "aggression", "lethargy"},
        "description": "Neoplasm of the testicle including interstitial cell tumours and seminomas. More common in older intact males.",
        "description_ja": "精巣の腫瘍で、間質細胞腫やセミノーマが含まれます。高齢の未去勢オスに多いです。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "fine_needle_aspirate", "histopathology"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"excessive_weight", "decreased_activity", "difficulty_grooming", "cecotrope_impaction", "pododermatitis_signs"},
        "description": "Excessive body fat accumulation from overfeeding and insufficient exercise, predisposing to hepatic lipidosis, pododermatitis, and GI stasis.",
        "description_ja": "過食と運動不足による過剰な体脂肪蓄積で、肝リピドーシス、足底皮膚炎、消化管うっ滞の素因となります。",
        "urgency": "moderate",
        "recommended_tests": ["body_condition_scoring", "blood_chemistry", "diet_review"],
    },
    {
        "name": "Hepatic Lipidosis",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"appetite_loss", "lethargy", "jaundice", "weight_loss", "dehydration", "hepatomegaly"},
        "description": "Fatty infiltration of the liver, often triggered by anorexia in obese rabbits. Can rapidly become fatal.",
        "description_ja": "肝臓への脂肪浸潤で、肥満ウサギの食欲不振時に誘発されることが多く、急速に致死的になり得ます。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "liver_ultrasound", "bile_acids"],
    },
    {
        "name": "Barbering (Fur Chewing)",
        "name_ja": "毛むしり（バーバリング）",
        "symptoms": {"hair_loss", "fur_chewing", "bald_patches", "skin_irritation"},
        "description": "Self or companion fur chewing behaviour caused by boredom, stress, nutritional deficiency, or hormonal imbalance.",
        "description_ja": "退屈、ストレス、栄養不足、ホルモン異常が原因で自分や同居ウサギの毛を噛む行動です。",
        "urgency": "low",
        "recommended_tests": ["diet_review", "hormone_panel", "dermatologic_exam"],
    },
    {
        "name": "Aggression",
        "name_ja": "攻撃行動",
        "symptoms": {"biting", "lunging", "growling", "territorial_marking"},
        "description": "Hormonal, fear-based, or pain-related aggressive behaviour. Intact rabbits are more commonly affected.",
        "description_ja": "ホルモン、恐怖、痛みに関連した攻撃行動。未避妊・未去勢のウサギに多く見られます。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "hormone_panel", "pain_assessment"],
    },
    {
        "name": "Trichobezoar (Hairball)",
        "name_ja": "毛球症",
        "symptoms": {"appetite_loss", "reduced_fecal_output", "abdominal_distension", "lethargy", "teeth_grinding"},
        "description": "Accumulation of ingested hair in the stomach. In rabbits, this is usually secondary to GI stasis rather than a primary condition.",
        "description_ja": "胃内に摂取した毛が蓄積する状態。ウサギでは通常、消化管うっ滞に続発して起こります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Megacolon",
        "name_ja": "巨大結腸症",
        "symptoms": {"constipation", "abdominal_distension", "reduced_fecal_output", "small_fecal_pellets", "lethargy"},
        "description": "Chronic dilation of the colon with impaired motility, associated with the En/en gene in spotted rabbits.",
        "description_ja": "結腸の慢性的な拡張と運動障害で、スポット柄のウサギのEn/en遺伝子に関連します。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_xray", "physical_exam", "barium_series"],
    },
    {
        "name": "Gastric Ulceration",
        "name_ja": "胃潰瘍",
        "symptoms": {"appetite_loss", "teeth_grinding", "blood_in_stool", "lethargy", "abdominal_pain"},
        "description": "Erosion of the gastric mucosa from stress, NSAID use, or concurrent illness.",
        "description_ja": "ストレス、NSAIDの使用、併発疾患による胃粘膜のびらんです。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "fecal_occult_blood", "blood_chemistry"],
    },
    {
        "name": "Cecal Impaction",
        "name_ja": "盲腸閉塞",
        "symptoms": {"appetite_loss", "abdominal_distension", "reduced_fecal_output", "lethargy", "dehydration"},
        "description": "Impaction of the cecum with dehydrated contents, hay, or foreign material causing obstruction.",
        "description_ja": "脱水した内容物、干し草、異物による盲腸の閉塞です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"tissue_protrusion_anus", "straining", "blood_in_stool", "diarrhea"},
        "description": "Protrusion of rectal mucosa through the anus, often secondary to chronic diarrhea, coccidiosis, or straining.",
        "description_ja": "直腸粘膜が肛門から突出する状態で、慢性下痢、コクシジウム症、いきみに続発します。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_exam", "abdominal_xray"],
    },
    {
        "name": "Tyzzer Disease",
        "name_ja": "ティザー病",
        "symptoms": {"diarrhea", "lethargy", "sudden_death", "dehydration", "jaundice"},
        "description": "Acute, often fatal infection by Clostridium piliforme causing necrotising hepatitis and enteritis, mainly in young or stressed rabbits.",
        "description_ja": "クロストリジウム・ピリフォルメによる急性で致死的な感染症。壊死性肝炎と腸炎を引き起こし、若いまたはストレス下のウサギに多いです。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "necropsy", "histopathology"],
    },
    {
        "name": "Staphylococcal Infection",
        "name_ja": "ブドウ球菌感染症",
        "symptoms": {"abscess", "skin_lesions", "fever", "lethargy", "pododermatitis_signs"},
        "description": "Infection by Staphylococcus aureus causing abscesses, pododermatitis, mastitis, or septicaemia.",
        "description_ja": "黄色ブドウ球菌による感染で、膿瘍、足底皮膚炎、乳腺炎、敗血症を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["culture_sensitivity", "complete_blood_count", "physical_exam"],
    },
    {
        "name": "Bordetella Infection",
        "name_ja": "ボルデテラ感染症",
        "symptoms": {"sneezing", "nasal_discharge", "conjunctivitis", "respiratory_distress"},
        "description": "Respiratory infection by Bordetella bronchiseptica, often co-infecting with Pasteurella.",
        "description_ja": "ボルデテラ・ブロンキセプティカによる呼吸器感染で、パスツレラとの混合感染が多いです。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_swab", "culture_sensitivity", "thoracic_radiographs"],
    },
    {
        "name": "Encephalitozoonosis - Renal Form",
        "name_ja": "エンセファリトゾーン症（腎型）",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "hind_limb_weakness", "urinary_incontinence"},
        "description": "Renal manifestation of E. cuniculi infection causing chronic interstitial nephritis and progressive renal failure.",
        "description_ja": "E. cuniculi感染の腎臓型で、慢性間質性腎炎と進行性腎不全を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["e_cuniculi_titre", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Viral Papillomatosis",
        "name_ja": "ウイルス性乳頭腫症",
        "symptoms": {"skin_growths", "wart_like_lesions"},
        "description": "Benign skin tumours caused by Shope papilloma virus, primarily on ears and face of cottontail rabbits but occasionally domestic rabbits.",
        "description_ja": "ショープ乳頭腫ウイルスによる良性皮膚腫瘍で、主にワタオウサギの耳や顔に見られますが、家庭のウサギにも発生します。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Dermatitis (Non-specific)",
        "name_ja": "皮膚炎（非特異的）",
        "symptoms": {"hair_loss", "skin_redness", "itching", "skin_crusting", "skin_lesions"},
        "description": "Inflammation of the skin from various causes including contact irritants, urine scald, or allergic reactions.",
        "description_ja": "接触刺激物、尿やけ、アレルギー反応など様々な原因による皮膚の炎症です。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "dermatologic_exam", "culture_sensitivity"],
    },
    {
        "name": "Urine Scald",
        "name_ja": "尿やけ（尿性皮膚炎）",
        "symptoms": {"perineal_redness", "hair_loss", "skin_irritation", "urine_staining", "foul_odor"},
        "description": "Chemical burn of the perineal skin from chronic urine contact, often secondary to urinary incontinence, obesity, or mobility issues.",
        "description_ja": "慢性的な尿接触による会陰部皮膚の化学的火傷で、尿失禁、肥満、運動障害に続発します。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "urinalysis", "diet_review"],
    },
    {
        "name": "Alopecia (Non-specific)",
        "name_ja": "脱毛症（非特異的）",
        "symptoms": {"hair_loss", "bald_patches", "skin_flaking"},
        "description": "Hair loss from various causes including hormonal imbalance, nutritional deficiency, parasites, or dermatophytosis.",
        "description_ja": "ホルモン異常、栄養不足、寄生虫、皮膚糸状菌症など様々な原因による脱毛です。",
        "urgency": "low",
        "recommended_tests": ["skin_scraping", "fungal_culture", "hormone_panel", "diet_review"],
    },
    {
        "name": "Demodex Mange",
        "name_ja": "毛包虫症（ニキビダニ症）",
        "symptoms": {"hair_loss", "skin_crusting", "skin_thickening", "skin_lesions"},
        "description": "Rare mite infestation by Demodex cuniculi, often indicating underlying immunosuppression.",
        "description_ja": "デモデックス・クニクリによる稀なダニ感染で、基礎疾患として免疫抑制があることが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "dermatologic_exam", "complete_blood_count"],
    },
    {
        "name": "Nephrolithiasis (Kidney Stones)",
        "name_ja": "腎結石症",
        "symptoms": {"blood_in_urine", "appetite_loss", "lethargy", "abdominal_pain", "weight_loss"},
        "description": "Formation of calculi in the renal pelvis, primarily calcium carbonate. Can lead to hydronephrosis and renal failure.",
        "description_ja": "腎盂における結石の形成で、主に炭酸カルシウムから成ります。水腎症や腎不全に至ることがあります。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "renal_ultrasound", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Urethral Obstruction",
        "name_ja": "尿道閉塞",
        "symptoms": {"straining_to_urinate", "inability_to_urinate", "abdominal_pain", "lethargy", "vocalization"},
        "description": "Complete blockage of the urethra by calculi or sludge, a life-threatening emergency requiring immediate catheterisation.",
        "description_ja": "結石やスラッジによる尿道の完全閉塞。即座にカテーテル処置が必要な致命的緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "urinalysis", "blood_chemistry"],
    },
    {
        "name": "Cystitis",
        "name_ja": "膀胱炎",
        "symptoms": {"frequent_urination", "straining_to_urinate", "blood_in_urine", "thick_white_urine", "hunched_posture"},
        "description": "Bacterial infection of the bladder, often concurrent with urinary sludge or calculi.",
        "description_ja": "膀胱の細菌感染で、尿路スラッジや結石を併発することが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "abdominal_xray"],
    },
    {
        "name": "Red Urine (Non-pathological)",
        "name_ja": "赤色尿（非病的）",
        "symptoms": {"red_urine", "normal_behavior"},
        "description": "Normal porphyrin pigment excretion causing red-orange discolouration of urine. Not to be confused with haematuria.",
        "description_ja": "ポルフィリン色素の正常な排泄により尿が赤橙色に変色する状態。血尿と混同してはいけません。",
        "urgency": "low",
        "recommended_tests": ["urinalysis", "urine_dipstick"],
    },
    {
        "name": "Pleural Effusion",
        "name_ja": "胸水",
        "symptoms": {"respiratory_distress", "exercise_intolerance", "cyanosis", "lethargy", "appetite_loss"},
        "description": "Accumulation of fluid in the pleural space from cardiac disease, infection, or neoplasia.",
        "description_ja": "心疾患、感染、腫瘍による胸腔内の液体貯留です。",
        "urgency": "emergency",
        "recommended_tests": ["thoracic_radiographs", "thoracocentesis", "fluid_analysis", "echocardiography"],
    },
    {
        "name": "Aspiration Pneumonia",
        "name_ja": "誤嚥性肺炎",
        "symptoms": {"respiratory_distress", "coughing", "fever", "nasal_discharge", "lethargy"},
        "description": "Lung infection following inhalation of food, liquid, or vomitus, often from improper syringe feeding.",
        "description_ja": "食物、液体、嘔吐物の吸入による肺感染で、不適切なシリンジ給餌が原因となることが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["thoracic_radiographs", "complete_blood_count", "culture_sensitivity"],
    },
    {
        "name": "Nasal Polyps",
        "name_ja": "鼻腔ポリープ",
        "symptoms": {"sneezing", "nasal_discharge", "noisy_breathing", "epistaxis"},
        "description": "Benign growths in the nasal passages causing obstruction, chronic discharge, and sneezing.",
        "description_ja": "鼻腔内の良性腫瘤で、閉塞、慢性鼻汁、くしゃみを引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["skull_radiographs", "ct_scan", "rhinoscopy"],
    },
    {
        "name": "Pulmonary Abscess",
        "name_ja": "肺膿瘍",
        "symptoms": {"respiratory_distress", "lethargy", "appetite_loss", "weight_loss", "fever"},
        "description": "Encapsulated bacterial infection within the lung parenchyma, often from Pasteurella haematogenous spread.",
        "description_ja": "パスツレラの血行性播種による肺実質内の被包性細菌感染です。",
        "urgency": "high",
        "recommended_tests": ["thoracic_radiographs", "complete_blood_count", "culture_sensitivity"],
    },
    {
        "name": "Torticollis (Wry Neck)",
        "name_ja": "斜頸",
        "symptoms": {"head_tilt", "circling", "nystagmus", "rolling", "ataxia"},
        "description": "Persistent lateral flexion of the head and neck, most commonly from E. cuniculi or otitis media/interna.",
        "description_ja": "頭部と頸部の持続的な側方屈曲で、E. cuniculiや中耳・内耳炎が最も一般的な原因です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "e_cuniculi_titre", "skull_radiographs"],
    },
    {
        "name": "Facial Nerve Paralysis",
        "name_ja": "顔面神経麻痺",
        "symptoms": {"facial_drooping", "inability_to_blink", "drooling", "facial_nerve_paralysis"},
        "description": "Paralysis of cranial nerve VII, often secondary to otitis media or E. cuniculi infection.",
        "description_ja": "第VII脳神経の麻痺で、中耳炎やE. cuniculi感染に続発することが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "skull_radiographs", "ct_scan"],
    },
    {
        "name": "Perineal Dermatitis",
        "name_ja": "会陰部皮膚炎",
        "symptoms": {"perineal_redness", "hair_loss", "foul_odor", "skin_irritation", "urine_staining"},
        "description": "Inflammation and infection of the perineal skin, often from urine/faecal soiling in obese or disabled rabbits.",
        "description_ja": "肥満や運動障害のあるウサギで尿・糞便汚染による会陰部皮膚の炎症と感染です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_culture", "urinalysis"],
    },
    {
        "name": "Orchitis",
        "name_ja": "精巣炎",
        "symptoms": {"testicular_enlargement", "testicular_swelling", "fever", "lethargy", "pain_on_palpation"},
        "description": "Inflammation or infection of the testicles, commonly from Pasteurella or Treponema. Can lead to abscessation.",
        "description_ja": "パスツレラやトレポネーマによる精巣の炎症・感染。膿瘍化することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "abdominal_ultrasound"],
    },
    {
        "name": "Hydrometra",
        "name_ja": "子宮水腫",
        "symptoms": {"abdominal_distension", "weight_gain", "lethargy", "decreased_activity"},
        "description": "Accumulation of sterile fluid in the uterus, often discovered incidentally or with gradually enlarging abdomen.",
        "description_ja": "子宮内に無菌性液体が貯留する状態で、偶発的にまたは腹部の漸進的な増大で発見されます。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray"],
    },
    {
        "name": "Ovarian Cysts",
        "name_ja": "卵巣嚢胞",
        "symptoms": {"aggression", "territorial_marking", "hair_loss", "mammary_swelling", "abdominal_distension"},
        "description": "Fluid-filled cysts on the ovaries causing hormonal imbalances and behavioural changes in intact does.",
        "description_ja": "卵巣上の液体貯留嚢胞で、ホルモン異常と未避妊メスの行動変化を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "hormone_panel"],
    },
    {
        "name": "Toxicosis - Plant Poisoning",
        "name_ja": "植物中毒",
        "symptoms": {"diarrhea", "seizures", "salivation", "lethargy", "appetite_loss", "sudden_death"},
        "description": "Poisoning from ingestion of toxic plants such as lily of the valley, foxglove, nightshade, or rhubarb leaves.",
        "description_ja": "スズラン、ジギタリス、ナス科植物、ルバーブの葉などの有毒植物を摂取したことによる中毒です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "blood_gas_analysis", "toxicology_screen"],
    },
    {
        "name": "Antibiotic-Associated Enterotoxemia",
        "name_ja": "抗生物質関連腸管毒素血症",
        "symptoms": {"diarrhea", "appetite_loss", "lethargy", "dehydration", "hypothermia", "sudden_death"},
        "description": "Fatal dysbiosis caused by inappropriate antibiotics (penicillin oral, lincomycin, clindamycin, erythromycin) disrupting cecal flora.",
        "description_ja": "不適切な抗生物質（経口ペニシリン、リンコマイシン、クリンダマイシン、エリスロマイシン）による盲腸内細菌叢の破壊で致死的な菌交代症を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_culture", "blood_chemistry", "complete_blood_count"],
    },
    {
        "name": "Lead Poisoning",
        "name_ja": "鉛中毒",
        "symptoms": {"appetite_loss", "lethargy", "seizures", "ataxia", "blindness", "weight_loss"},
        "description": "Toxicity from ingestion of lead-containing paint, solder, or other materials. Causes neurological and gastrointestinal signs.",
        "description_ja": "鉛含有塗料、はんだなどの摂取による中毒。神経症状と消化器症状を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "abdominal_xray", "complete_blood_count"],
    },
    {
        "name": "Vitamin A Deficiency",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"reproductive_failure", "hydrocephalus_kits", "skin_lesions", "eye_problems"},
        "description": "Deficiency from inadequate diet causing reproductive failure, congenital defects in kits, and skin/eye problems.",
        "description_ja": "不適切な食事によるビタミンA欠乏で、繁殖障害、仔ウサギの先天性異常、皮膚・眼の問題を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["diet_review", "blood_chemistry", "vitamin_a_level"],
    },
    {
        "name": "Vitamin D Toxicity",
        "name_ja": "ビタミンD中毒",
        "symptoms": {"excessive_thirst", "excessive_urination", "appetite_loss", "weight_loss", "soft_tissue_calcification"},
        "description": "Over-supplementation causing hypercalcaemia, soft tissue mineralisation, and renal damage.",
        "description_ja": "過剰補給による高カルシウム血症、軟部組織の石灰化、腎障害を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "abdominal_xray", "urinalysis"],
    },
    {
        "name": "Calcium Deficiency",
        "name_ja": "カルシウム欠乏症",
        "symptoms": {"lameness", "fractures", "teeth_grinding", "muscle_tremors", "weakness"},
        "description": "Nutritional secondary hyperparathyroidism from inadequate calcium or imbalanced calcium-phosphorus ratio.",
        "description_ja": "カルシウム不足またはカルシウム・リン比の不均衡による栄養性二次性上皮小体機能亢進症です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "radiographs", "diet_review"],
    },
    {
        "name": "Hypercalcaemia",
        "name_ja": "高カルシウム血症",
        "symptoms": {"excessive_thirst", "excessive_urination", "thick_white_urine", "appetite_loss", "lethargy"},
        "description": "Elevated blood calcium levels from excessive dietary calcium, renal dysfunction, or neoplasia.",
        "description_ja": "過剰な食事性カルシウム、腎機能障害、腫瘍による血中カルシウム値の上昇です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "urinalysis", "abdominal_xray"],
    },
    {
        "name": "Pericarditis",
        "name_ja": "心膜炎",
        "symptoms": {"respiratory_distress", "lethargy", "exercise_intolerance", "muffled_heart_sounds"},
        "description": "Inflammation of the pericardium, often infectious (Pasteurella) causing pericardial effusion.",
        "description_ja": "心膜の炎症で、パスツレラなどの感染により心嚢液貯留を引き起こすことが多いです。",
        "urgency": "high",
        "recommended_tests": ["thoracic_radiographs", "echocardiography", "electrocardiogram"],
    },
    {
        "name": "Aortic Aneurysm",
        "name_ja": "大動脈瘤",
        "symptoms": {"sudden_death", "hind_limb_weakness", "lethargy"},
        "description": "Dilation and potential rupture of the aorta, associated with atherosclerosis and hypertension in rabbits.",
        "description_ja": "大動脈の拡張と潜在的な破裂で、ウサギの動脈硬化症や高血圧に関連します。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "thoracic_radiographs", "blood_chemistry"],
    },
    {
        "name": "Ear Haematoma (Aural Haematoma)",
        "name_ja": "耳血腫",
        "symptoms": {"ear_swelling", "head_shaking", "ear_scratching", "ear_thickening"},
        "description": "Collection of blood between the skin and cartilage of the pinna from head shaking or scratching secondary to ear disease.",
        "description_ja": "耳疾患に伴う頭振りや耳掻きにより、耳介の皮膚と軟骨間に血液が貯留する状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "otoscopic_exam"],
    },
    {
        "name": "Snuffles - Chronic",
        "name_ja": "慢性スナッフル",
        "symptoms": {"chronic_nasal_discharge", "sneezing", "matted_forepaws", "conjunctivitis", "weight_loss"},
        "description": "Chronic upper respiratory infection with persistent nasal discharge and sneezing, refractory to treatment.",
        "description_ja": "持続的な鼻汁とくしゃみを伴う慢性上部呼吸器感染で、治療に抵抗性を示します。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_swab", "culture_sensitivity", "skull_radiographs", "ct_scan"],
    },
    {
        "name": "Sinusitis",
        "name_ja": "副鼻腔炎",
        "symptoms": {"nasal_discharge", "sneezing", "facial_swelling", "appetite_loss", "head_tilt"},
        "description": "Bacterial infection of the paranasal sinuses, frequently from Pasteurella extension or dental root involvement.",
        "description_ja": "パスツレラの波及や歯根の関与による副鼻腔の細菌感染です。",
        "urgency": "moderate",
        "recommended_tests": ["skull_radiographs", "ct_scan", "culture_sensitivity"],
    },
    {
        "name": "Lipoma",
        "name_ja": "脂肪腫",
        "symptoms": {"subcutaneous_mass", "normal_behavior"},
        "description": "Benign fatty tumour found subcutaneously, generally slow-growing and clinically insignificant unless large.",
        "description_ja": "皮下に見られる良性脂肪腫瘍で、通常は緩徐に増殖し大きくなければ臨床的に問題ありません。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "physical_exam"],
    },
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"skin_ulceration", "non_healing_wound", "skin_mass", "weight_loss"},
        "description": "Malignant skin tumour that can occur on the face, ears, or body. Locally invasive with potential for metastasis.",
        "description_ja": "顔、耳、体に発生し得る悪性皮膚腫瘍。局所浸潤性で転移の可能性があります。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "thoracic_radiographs"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"rapidly_growing_mass", "skin_mass", "weight_loss", "lameness"},
        "description": "Malignant tumour of fibrous connective tissue. Can occur at injection sites or spontaneously.",
        "description_ja": "線維性結合組織の悪性腫瘍。注射部位や自然発生的に生じることがあります。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "thoracic_radiographs", "ct_scan"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ（黒色腫）",
        "symptoms": {"pigmented_mass", "skin_mass", "ulceration"},
        "description": "Pigmented skin tumour that may be benign or malignant. Rare in rabbits but documented.",
        "description_ja": "良性または悪性の色素性皮膚腫瘍。ウサギでは稀ですが報告があります。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Basal Cell Tumour",
        "name_ja": "基底細胞腫",
        "symptoms": {"skin_mass", "hair_loss", "ulceration"},
        "description": "Common skin tumour in rabbits arising from basal cells of the epidermis. Usually benign.",
        "description_ja": "表皮の基底細胞から発生するウサギでよく見られる皮膚腫瘍。通常は良性です。",
        "urgency": "low",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "histopathology"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "swelling", "non_weight_bearing", "pain_on_palpation", "weight_loss"},
        "description": "Malignant bone tumour causing progressive lameness and swelling. Prognosis is generally poor.",
        "description_ja": "進行性の跛行と腫脹を引き起こす悪性骨腫瘍。予後は一般に不良です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "biopsy", "thoracic_radiographs", "histopathology"],
    },
    {
        "name": "Splenic Torsion",
        "name_ja": "脾臓捻転",
        "symptoms": {"acute_abdominal_pain", "lethargy", "appetite_loss", "abdominal_distension", "pale_mucous_membranes"},
        "description": "Rotation of the spleen on its vascular pedicle causing venous congestion and potential necrosis.",
        "description_ja": "脾臓が血管茎を軸に回転し、静脈うっ血と壊死を引き起こす緊急疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "complete_blood_count", "blood_chemistry"],
    },
    {
        "name": "Hepatic Lobe Torsion",
        "name_ja": "肝葉捻転",
        "symptoms": {"acute_abdominal_pain", "lethargy", "appetite_loss", "pale_mucous_membranes", "abdominal_distension"},
        "description": "Torsion of a hepatic lobe causing acute pain, anaemia, and potential liver failure. Surgical emergency.",
        "description_ja": "肝葉の捻転により急性痛、貧血、肝不全を引き起こす外科的緊急疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "blood_chemistry", "complete_blood_count"],
    },
    {
        "name": "Peritonitis",
        "name_ja": "腹膜炎",
        "symptoms": {"abdominal_pain", "fever", "lethargy", "appetite_loss", "abdominal_distension", "hunched_posture"},
        "description": "Inflammation of the peritoneum from ruptured viscus, infection, or surgical complication.",
        "description_ja": "臓器穿孔、感染、手術合併症による腹膜の炎症です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "complete_blood_count", "blood_chemistry", "abdominocentesis"],
    },
    {
        "name": "Anal Gland Impaction",
        "name_ja": "肛門腺貯留",
        "symptoms": {"scooting", "perianal_irritation", "foul_odor", "licking_perianal_area"},
        "description": "Impaction of the inguinal scent glands with waxy secretion, causing discomfort and foul odour.",
        "description_ja": "鼠径臭腺にワックス状の分泌物が貯留し、不快感と悪臭を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Flea Infestation",
        "name_ja": "ノミ寄生症",
        "symptoms": {"itching", "hair_loss", "flea_dirt", "restlessness", "skin_redness"},
        "description": "Infestation with Spilopsyllus cuniculi or cat/dog fleas causing pruritus and potential myxomatosis transmission.",
        "description_ja": "ウサギノミまたは犬猫ノミの寄生で、掻痒感と粘液腫症の伝播リスクがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "flea_comb", "dermatologic_exam"],
    },
    {
        "name": "Fly Strike Prevention Needed",
        "name_ja": "フライストライク予防必要",
        "symptoms": {"perineal_soiling", "obesity_signs", "diarrhea", "decreased_activity"},
        "description": "Identification of risk factors for myiasis: soiled perineum, obesity, dental disease, or mobility problems requiring preventive care.",
        "description_ja": "ハエウジ症のリスク因子（会陰部汚染、肥満、歯科疾患、運動障害）の特定と予防ケアが必要です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "body_condition_scoring", "diet_review"],
    },
    {
        "name": "Hepatic Cyst",
        "name_ja": "肝嚢胞",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "hepatomegaly"},
        "description": "Single or multiple fluid-filled cysts in the liver, may be congenital or acquired. Usually incidental finding.",
        "description_ja": "肝臓内の単発または多発性の液体貯留嚢胞で、先天性または後天性。通常は偶発的に発見されます。",
        "urgency": "low",
        "recommended_tests": ["abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Adrenal Disease",
        "name_ja": "副腎疾患",
        "symptoms": {"hair_loss", "aggression", "excessive_thirst", "excessive_urination", "lethargy"},
        "description": "Adrenal gland hyperplasia or neoplasia causing hormonal excess. Less common than in ferrets but documented.",
        "description_ja": "副腎の過形成または腫瘍によるホルモン過剰。フェレットほど多くはありませんが報告があります。",
        "urgency": "moderate",
        "recommended_tests": ["hormone_panel", "abdominal_ultrasound", "blood_chemistry"],
    },
    {
        "name": "Hypoglycaemia",
        "name_ja": "低血糖症",
        "symptoms": {"weakness", "seizures", "lethargy", "loss_of_consciousness", "muscle_tremors"},
        "description": "Critically low blood glucose from hepatic lipidosis, sepsis, pregnancy toxemia, or prolonged anorexia.",
        "description_ja": "肝リピドーシス、敗血症、妊娠中毒症、長期食欲不振による危険な低血糖です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "complete_blood_count"],
    },
    {
        "name": "Intervertebral Disc Disease",
        "name_ja": "椎間板疾患",
        "symptoms": {"hind_limb_weakness", "hunched_posture", "reluctance_to_move", "urinary_incontinence", "pain_on_palpation"},
        "description": "Degeneration or herniation of intervertebral discs causing spinal cord compression and neurological deficits.",
        "description_ja": "椎間板の変性や脱出により脊髄圧迫と神経学的障害を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["spinal_radiographs", "mri", "neurological_exam"],
    },
    {
        "name": "Nutritional Osteodystrophy",
        "name_ja": "栄養性骨異栄養症",
        "symptoms": {"lameness", "fractures", "swelling", "reluctance_to_move", "teeth_grinding"},
        "description": "Bone weakening from improper calcium/phosphorus ratio or vitamin D metabolism, especially in growing rabbits.",
        "description_ja": "不適切なカルシウム・リン比やビタミンD代謝異常による骨の脆弱化で、成長期のウサギに多いです。",
        "urgency": "moderate",
        "recommended_tests": ["radiographs", "blood_chemistry", "diet_review"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "ダニ寄生症（マダニ）",
        "symptoms": {"tick_visible", "skin_irritation", "lethargy", "fever"},
        "description": "Attachment of ticks to the skin causing local irritation and potential transmission of tick-borne diseases.",
        "description_ja": "マダニが皮膚に付着し、局所刺激とダニ媒介性疾患の伝播リスクを引き起こします。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "tick_identification"],
    },
    {
        "name": "Cuterebra Infestation",
        "name_ja": "ウマバエ幼虫寄生症",
        "symptoms": {"subcutaneous_swelling", "breathing_hole_in_skin", "restlessness", "skin_mass"},
        "description": "Subcutaneous parasitism by Cuterebra fly larvae (bot fly), creating a warble with a breathing pore in the skin.",
        "description_ja": "ウマバエの幼虫が皮下に寄生し、皮膚に呼吸孔を持つ膨隆を形成します。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "wound_assessment"],
    },
    {
        "name": "Retained Foetus",
        "name_ja": "胎仔遺残",
        "symptoms": {"vaginal_discharge", "lethargy", "appetite_loss", "abdominal_distension", "fever"},
        "description": "Failure to deliver one or more foetuses, leading to foetal death, mummification, or sepsis.",
        "description_ja": "一匹以上の胎仔が分娩されず、胎仔の死亡、ミイラ化、敗血症に至ります。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "complete_blood_count"],
    },
    {
        "name": "Vaginal Prolapse",
        "name_ja": "膣脱",
        "symptoms": {"tissue_protrusion_vulva", "straining", "bloody_vaginal_discharge", "restlessness"},
        "description": "Protrusion of vaginal tissue through the vulva, occurring peripartum or from straining.",
        "description_ja": "分娩前後やいきみにより膣組織が外陰部から突出する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "abdominal_xray"],
    },
    {
        "name": "Ketoacidosis",
        "name_ja": "ケトアシドーシス",
        "symptoms": {"appetite_loss", "lethargy", "acetone_breath", "rapid_breathing", "dehydration", "weakness"},
        "description": "Severe metabolic acidosis from fat breakdown producing excess ketone bodies. Associated with hepatic lipidosis and pregnancy toxemia.",
        "description_ja": "脂肪分解による過剰なケトン体産生で生じる重度の代謝性アシドーシス。肝リピドーシスや妊娠中毒症に関連します。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "blood_gas_analysis", "urinalysis", "blood_glucose"],
    },
    {
        "name": "Septicaemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "hypothermia", "rapid_breathing", "pale_mucous_membranes", "sudden_death"},
        "description": "Systemic bacterial infection in the bloodstream causing septic shock and multi-organ failure.",
        "description_ja": "血流中の全身性細菌感染で敗血症性ショックと多臓器不全を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count", "blood_chemistry"],
    },
    {
        "name": "Conjunctival Overgrowth (Pseudopterygium)",
        "name_ja": "結膜過成長（偽翼状片）",
        "symptoms": {"membrane_over_eye", "eye_discharge", "vision_loss"},
        "description": "Proliferative conjunctival tissue growing over the cornea, more common in certain breeds such as Dutch and dwarf.",
        "description_ja": "結膜組織が角膜上に増殖する状態で、ダッチやドワーフなどの品種に多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmologic_exam", "biopsy"],
    },
    {
        "name": "Proptosis (Globe Prolapse)",
        "name_ja": "眼球突出（眼球脱出）",
        "symptoms": {"eye_prolapse", "eye_swelling", "eye_redness", "blindness"},
        "description": "Forward displacement of the eyeball beyond the eyelids from trauma or retrobulbar disease. Emergency requiring immediate intervention.",
        "description_ja": "外傷や球後疾患により眼球が眼瞼を超えて前方に変位する緊急疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmologic_exam", "skull_radiographs"],
    },
    {
        "name": "Polydipsia / Polyuria",
        "name_ja": "多飲多尿",
        "symptoms": {"excessive_thirst", "excessive_urination", "wet_bedding"},
        "description": "Increased water intake and urine output from renal disease, E. cuniculi, diabetes (rare), or behavioural causes.",
        "description_ja": "腎疾患、E. cuniculi、糖尿病（稀）、行動的原因による飲水量と尿量の増加です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "urinalysis", "e_cuniculi_titre"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"excessive_thirst", "excessive_urination", "weight_loss", "cataracts", "lethargy"},
        "description": "Rare endocrine disorder in rabbits characterised by hyperglycaemia and glucosuria.",
        "description_ja": "ウサギでは稀な内分泌疾患で、高血糖と糖尿を特徴とします。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "blood_chemistry", "urinalysis", "fructosamine"],
    },
    {
        "name": "Intussusception",
        "name_ja": "腸重積",
        "symptoms": {"acute_abdominal_pain", "appetite_loss", "lethargy", "blood_in_stool", "abdominal_distension"},
        "description": "Telescoping of one portion of intestine into an adjacent segment, causing obstruction and ischaemia.",
        "description_ja": "腸の一部が隣接する部分に陥入し、閉塞と虚血を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_ultrasound", "abdominal_xray", "physical_exam"],
    },
    {
        "name": "Cecal Tympany",
        "name_ja": "盲腸鼓脹症",
        "symptoms": {"abdominal_distension", "abdominal_pain", "appetite_loss", "reduced_fecal_output", "gas"},
        "description": "Excessive gas accumulation in the cecum causing distension and pain, often from dietary indiscretion.",
        "description_ja": "食事の不摂生による盲腸内の過剰ガス蓄積で、膨満と痛みを引き起こします。",
        "urgency": "high",
        "recommended_tests": ["abdominal_xray", "physical_exam"],
    },
    {
        "name": "Chronic Weight Loss (Marasmus)",
        "name_ja": "慢性体重減少（消耗症）",
        "symptoms": {"weight_loss", "muscle_wasting", "appetite_loss", "lethargy", "poor_coat"},
        "description": "Progressive weight loss from chronic dental disease, renal failure, neoplasia, or malabsorption.",
        "description_ja": "慢性歯科疾患、腎不全、腫瘍、吸収不良による進行性の体重減少です。",
        "urgency": "moderate",
        "recommended_tests": ["complete_blood_count", "blood_chemistry", "fecal_exam", "abdominal_ultrasound"],
    },
    {
        "name": "Wet Dewlap (Moist Dermatitis)",
        "name_ja": "肉垂の湿性皮膚炎",
        "symptoms": {"dewlap_wetness", "hair_loss", "skin_redness", "skin_infection", "foul_odor"},
        "description": "Chronic moisture of the dewlap from drooling or water bowls causing bacterial or fungal dermatitis.",
        "description_ja": "流涎や水入れによる肉垂の慢性的な湿潤が原因で細菌性・真菌性皮膚炎を引き起こします。",
        "urgency": "low",
        "recommended_tests": ["dermatologic_exam", "culture_sensitivity", "diet_review"],
    },
    {
        "name": "Spay Complications (Post-operative)",
        "name_ja": "避妊手術後合併症",
        "symptoms": {"appetite_loss", "lethargy", "abdominal_pain", "swelling", "fever"},
        "description": "Post-operative complications including GI stasis, infection, dehiscence, or adhesions following ovariohysterectomy.",
        "description_ja": "卵巣子宮摘出術後の消化管うっ滞、感染、縫合離開、癒着などの術後合併症です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "abdominal_xray", "complete_blood_count"],
    },
]


SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "abdominal_contractions": {"ja": "腹部収縮", "en": "Abdominal Contractions"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal Distension"},
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal Pain"},
    "abnormal_cecotropes": {"ja": "異常な盲腸便", "en": "Abnormal Cecotropes"},
    "abscess": {"ja": "膿瘍", "en": "Abscess"},
    "acetone_breath": {"ja": "アセトン臭の呼気", "en": "Acetone Breath"},
    "acute_abdominal_pain": {"ja": "急性腹痛", "en": "Acute Abdominal Pain"},
    "aggression": {"ja": "攻撃性", "en": "Aggression"},
    "appetite_changes": {"ja": "食欲の変化", "en": "Appetite Changes"},
    "appetite_loss": {"ja": "食欲不振", "en": "Appetite Loss"},
    "ataxia": {"ja": "運動失調", "en": "Ataxia"},
    "bald_patches": {"ja": "禿斑", "en": "Bald Patches"},
    "biting": {"ja": "咬みつき", "en": "Biting"},
    "blindness": {"ja": "失明", "en": "Blindness"},
    "blood_in_stool": {"ja": "血便", "en": "Blood in Stool"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in Urine"},
    "bloody_nasal_discharge": {"ja": "血性鼻汁", "en": "Bloody Nasal Discharge"},
    "bloody_vaginal_discharge": {"ja": "血性膣分泌物", "en": "Bloody Vaginal Discharge"},
    "breathing_hole_in_skin": {"ja": "皮膚の呼吸孔", "en": "Breathing Hole in Skin"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into Objects"},
    "buphthalmos": {"ja": "牛眼（眼球拡大）", "en": "Buphthalmos"},
    "cataracts": {"ja": "白内障", "en": "Cataracts"},
    "cecotrope_impaction": {"ja": "盲腸便の貯留", "en": "Cecotrope Impaction"},
    "chronic_nasal_discharge": {"ja": "慢性鼻汁", "en": "Chronic Nasal Discharge"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "circular_hair_loss": {"ja": "円形脱毛", "en": "Circular Hair Loss"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "corneal_opacity": {"ja": "角膜混濁", "en": "Corneal Opacity"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "crepitus": {"ja": "捻髪音", "en": "Crepitus"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "dandruff": {"ja": "フケ", "en": "Dandruff"},
    "decreased_activity": {"ja": "活動量低下", "en": "Decreased Activity"},
    "decreased_urination": {"ja": "排尿量減少", "en": "Decreased Urination"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "dewlap_wetness": {"ja": "肉垂の湿潤", "en": "Dewlap Wetness"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "difficulty_eating": {"ja": "食事困難", "en": "Difficulty Eating"},
    "difficulty_grooming": {"ja": "グルーミング困難", "en": "Difficulty Grooming"},
    "difficulty_moving": {"ja": "移動困難", "en": "Difficulty Moving"},
    "dragging_hind_legs": {"ja": "後肢の引きずり", "en": "Dragging Hind Legs"},
    "drooling": {"ja": "よだれ・流涎", "en": "Drooling / Hypersalivation"},
    "ear_crusting": {"ja": "耳の痂皮形成", "en": "Ear Crusting"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear Discharge"},
    "ear_odor": {"ja": "耳の悪臭", "en": "Ear Odor"},
    "ear_redness": {"ja": "耳の発赤", "en": "Ear Redness"},
    "ear_scratching": {"ja": "耳を掻く", "en": "Ear Scratching"},
    "ear_swelling": {"ja": "耳の腫脹", "en": "Ear Swelling"},
    "ear_thickening": {"ja": "耳の肥厚", "en": "Ear Thickening"},
    "epiphora": {"ja": "流涙", "en": "Epiphora (Tearing)"},
    "epistaxis": {"ja": "鼻出血", "en": "Epistaxis (Nosebleed)"},
    "excessive_thirst": {"ja": "多飲", "en": "Excessive Thirst"},
    "excessive_urination": {"ja": "多尿", "en": "Excessive Urination"},
    "excessive_weight": {"ja": "過体重", "en": "Excessive Weight"},
    "exercise_intolerance": {"ja": "運動不耐性", "en": "Exercise Intolerance"},
    "exophthalmos": {"ja": "眼球突出", "en": "Exophthalmos"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye Discharge"},
    "eye_pain": {"ja": "眼の痛み", "en": "Eye Pain"},
    "eye_problems": {"ja": "眼の異常", "en": "Eye Problems"},
    "eye_prolapse": {"ja": "眼球脱出", "en": "Eye Prolapse"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye Redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye Swelling"},
    "eyelid_swelling": {"ja": "眼瞼腫脹", "en": "Eyelid Swelling"},
    "facial_crusting": {"ja": "顔面の痂皮形成", "en": "Facial Crusting"},
    "facial_drooping": {"ja": "顔面の垂れ下がり", "en": "Facial Drooping"},
    "facial_nerve_paralysis": {"ja": "顔面神経麻痺", "en": "Facial Nerve Paralysis"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial Swelling"},
    "facial_wetness": {"ja": "顔面の湿潤", "en": "Facial Wetness"},
    "fecal_incontinence": {"ja": "便失禁", "en": "Fecal Incontinence"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "flea_dirt": {"ja": "ノミの糞", "en": "Flea Dirt"},
    "foot_lesions": {"ja": "足の病変", "en": "Foot Lesions"},
    "foot_swelling": {"ja": "足の腫脹", "en": "Foot Swelling"},
    "foul_odor": {"ja": "悪臭", "en": "Foul Odor"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent Urination"},
    "fur_chewing": {"ja": "毛を噛む", "en": "Fur Chewing"},
    "fur_pulling": {"ja": "毛むしり", "en": "Fur Pulling"},
    "gas": {"ja": "ガス貯留", "en": "Gas"},
    "genital_lesions": {"ja": "生殖器の病変", "en": "Genital Lesions"},
    "genital_swelling": {"ja": "生殖器の腫脹", "en": "Genital Swelling"},
    "growling": {"ja": "唸り声", "en": "Growling"},
    "hair_loss": {"ja": "脱毛", "en": "Hair Loss"},
    "head_shaking": {"ja": "頭を振る", "en": "Head Shaking"},
    "head_tilt": {"ja": "斜頸", "en": "Head Tilt"},
    "hepatomegaly": {"ja": "肝腫大", "en": "Hepatomegaly"},
    "hind_limb_paralysis": {"ja": "後肢麻痺", "en": "Hind Limb Paralysis"},
    "hind_limb_weakness": {"ja": "後肢の筋力低下", "en": "Hind Limb Weakness"},
    "hunched_posture": {"ja": "背中を丸めた姿勢", "en": "Hunched Posture"},
    "hydrocephalus_kits": {"ja": "仔ウサギの水頭症", "en": "Hydrocephalus in Kits"},
    "hyperthermia": {"ja": "高体温", "en": "Hyperthermia"},
    "hypothermia": {"ja": "低体温", "en": "Hypothermia"},
    "inability_to_blink": {"ja": "瞬きできない", "en": "Inability to Blink"},
    "inability_to_stand": {"ja": "起立不能", "en": "Inability to Stand"},
    "inability_to_urinate": {"ja": "排尿不能", "en": "Inability to Urinate"},
    "intense_itching": {"ja": "強い掻痒感", "en": "Intense Itching"},
    "itching": {"ja": "掻痒感", "en": "Itching"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "jaw_swelling": {"ja": "顎の腫脹", "en": "Jaw Swelling"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "lens_opacity": {"ja": "水晶体混濁", "en": "Lens Opacity"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "licking_perianal_area": {"ja": "肛門周囲を舐める", "en": "Licking Perianal Area"},
    "limb_splaying": {"ja": "四肢の開脚", "en": "Limb Splaying"},
    "lip_crusting": {"ja": "口唇の痂皮形成", "en": "Lip Crusting"},
    "loss_of_consciousness": {"ja": "意識消失", "en": "Loss of Consciousness"},
    "lunging": {"ja": "突進行動", "en": "Lunging"},
    "lymph_node_enlargement": {"ja": "リンパ節腫大", "en": "Lymph Node Enlargement"},
    "maggots_visible": {"ja": "ウジの可視", "en": "Maggots Visible"},
    "mammary_gland_changes": {"ja": "乳腺の変化", "en": "Mammary Gland Changes"},
    "mammary_mass": {"ja": "乳腺の腫瘤", "en": "Mammary Mass"},
    "mammary_redness": {"ja": "乳腺の発赤", "en": "Mammary Redness"},
    "mammary_swelling": {"ja": "乳腺の腫脹", "en": "Mammary Swelling"},
    "matted_forepaws": {"ja": "前足の汚れ固着", "en": "Matted Forepaws"},
    "membrane_over_eye": {"ja": "眼を覆う膜", "en": "Membrane over Eye"},
    "miosis": {"ja": "縮瞳", "en": "Miosis"},
    "mucus_in_stool": {"ja": "粘液便", "en": "Mucus in Stool"},
    "muffled_heart_sounds": {"ja": "心音減弱", "en": "Muffled Heart Sounds"},
    "muscle_atrophy": {"ja": "筋萎縮", "en": "Muscle Atrophy"},
    "muscle_tremors": {"ja": "筋肉の震え", "en": "Muscle Tremors"},
    "muscle_wasting": {"ja": "筋肉の消耗", "en": "Muscle Wasting"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal Discharge"},
    "nasal_lesions": {"ja": "鼻の病変", "en": "Nasal Lesions"},
    "nest_building": {"ja": "巣作り行動", "en": "Nest Building"},
    "noisy_breathing": {"ja": "呼吸雑音", "en": "Noisy Breathing"},
    "non_healing_wound": {"ja": "治癒しない傷", "en": "Non-healing Wound"},
    "non_weight_bearing": {"ja": "患肢免重", "en": "Non-weight Bearing"},
    "normal_behavior": {"ja": "正常な行動", "en": "Normal Behavior"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "obesity_signs": {"ja": "肥満の徴候", "en": "Obesity Signs"},
    "paddling": {"ja": "遊泳運動", "en": "Paddling"},
    "pain_on_palpation": {"ja": "触診時の痛み", "en": "Pain on Palpation"},
    "pain_response_loss": {"ja": "痛覚反応消失", "en": "Pain Response Loss"},
    "painful_mammary": {"ja": "乳腺の疼痛", "en": "Painful Mammary"},
    "pale_mucous_membranes": {"ja": "粘膜蒼白", "en": "Pale Mucous Membranes"},
    "perianal_irritation": {"ja": "肛門周囲の刺激", "en": "Perianal Irritation"},
    "perineal_redness": {"ja": "会陰部の発赤", "en": "Perineal Redness"},
    "perineal_soiling": {"ja": "会陰部の汚れ", "en": "Perineal Soiling"},
    "pigmented_mass": {"ja": "色素性腫瘤", "en": "Pigmented Mass"},
    "pododermatitis_signs": {"ja": "足底皮膚炎の徴候", "en": "Pododermatitis Signs"},
    "poor_coat": {"ja": "被毛の粗剛", "en": "Poor Coat"},
    "rapid_breathing": {"ja": "速い呼吸", "en": "Rapid Breathing"},
    "rapidly_growing_mass": {"ja": "急速に増大する腫瘤", "en": "Rapidly Growing Mass"},
    "recumbency": {"ja": "横臥", "en": "Recumbency"},
    "red_urine": {"ja": "赤色尿", "en": "Red Urine"},
    "reduced_fecal_output": {"ja": "糞便量減少", "en": "Reduced Fecal Output"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to Move"},
    "reproductive_failure": {"ja": "繁殖障害", "en": "Reproductive Failure"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory Distress"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "rolling": {"ja": "転がり", "en": "Rolling"},
    "salivation": {"ja": "流涎", "en": "Salivation"},
    "scooting": {"ja": "お尻を擦りつける", "en": "Scooting"},
    "seizures": {"ja": "痙攣発作", "en": "Seizures"},
    "skin_crusting": {"ja": "皮膚の痂皮形成", "en": "Skin Crusting"},
    "skin_flaking": {"ja": "皮膚の剥離", "en": "Skin Flaking"},
    "skin_growths": {"ja": "皮膚の増殖物", "en": "Skin Growths"},
    "skin_infection": {"ja": "皮膚感染", "en": "Skin Infection"},
    "skin_irritation": {"ja": "皮膚の刺激", "en": "Skin Irritation"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin Lesions"},
    "skin_mass": {"ja": "皮膚の腫瘤", "en": "Skin Mass"},
    "skin_nodules": {"ja": "皮膚結節", "en": "Skin Nodules"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin Redness"},
    "skin_thickening": {"ja": "皮膚の肥厚", "en": "Skin Thickening"},
    "skin_ulceration": {"ja": "皮膚の潰瘍", "en": "Skin Ulceration"},
    "skin_wounds": {"ja": "皮膚の傷", "en": "Skin Wounds"},
    "small_fecal_pellets": {"ja": "小さな糞粒", "en": "Small Fecal Pellets"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "soft_stool": {"ja": "軟便", "en": "Soft Stool"},
    "soft_tissue_calcification": {"ja": "軟部組織の石灰化", "en": "Soft Tissue Calcification"},
    "squinting": {"ja": "目を細める", "en": "Squinting"},
    "stiffness": {"ja": "硬直", "en": "Stiffness"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "straining_to_urinate": {"ja": "排尿時のいきみ", "en": "Straining to Urinate"},
    "subcutaneous_mass": {"ja": "皮下腫瘤", "en": "Subcutaneous Mass"},
    "subcutaneous_swelling": {"ja": "皮下腫脹", "en": "Subcutaneous Swelling"},
    "sudden_death": {"ja": "突然死", "en": "Sudden Death"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth Grinding"},
    "territorial_marking": {"ja": "テリトリーマーキング", "en": "Territorial Marking"},
    "testicular_asymmetry": {"ja": "精巣の非対称", "en": "Testicular Asymmetry"},
    "testicular_enlargement": {"ja": "精巣腫大", "en": "Testicular Enlargement"},
    "testicular_swelling": {"ja": "精巣腫脹", "en": "Testicular Swelling"},
    "thick_white_urine": {"ja": "濃厚な白色尿", "en": "Thick White Urine"},
    "third_eyelid_protrusion": {"ja": "瞬膜突出", "en": "Third Eyelid Protrusion"},
    "tick_visible": {"ja": "マダニの可視", "en": "Tick Visible"},
    "tissue_protrusion_anus": {"ja": "肛門からの組織突出", "en": "Tissue Protrusion from Anus"},
    "tissue_protrusion_vulva": {"ja": "外陰部からの組織突出", "en": "Tissue Protrusion from Vulva"},
    "ulceration": {"ja": "潰瘍形成", "en": "Ulceration"},
    "urinary_incontinence": {"ja": "尿失禁", "en": "Urinary Incontinence"},
    "urine_staining": {"ja": "尿による染み", "en": "Urine Staining"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal Discharge"},
    "visible_tooth_overgrowth": {"ja": "目に見える歯の過長", "en": "Visible Tooth Overgrowth"},
    "vision_loss": {"ja": "視力低下", "en": "Vision Loss"},
    "vocalization": {"ja": "発声（鳴き声）", "en": "Vocalization"},
    "wart_like_lesions": {"ja": "疣贅様病変", "en": "Wart-like Lesions"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "weight_gain": {"ja": "体重増加", "en": "Weight Gain"},
    "weight_loss": {"ja": "体重減少", "en": "Weight Loss"},
    "weight_shifting": {"ja": "体重移動", "en": "Weight Shifting"},
    "wet_bedding": {"ja": "寝床の濡れ", "en": "Wet Bedding"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None) -> Dict[str, Any]:
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species)
