"""Reptile disease dictionary and analysis module.

This module defines a comprehensive list of diseases commonly seen across
reptile species (snakes, lizards, turtles, tortoises, crocodilians) and
exposes an ``analyze_symptoms`` function that leverages the generic species
helper to produce differential diagnosis results.

The information provided here is for educational purposes only and should
not replace professional veterinary diagnosis and treatment.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── Metabolic / Nutritional ──────────────────────────────────────────
    {
        "name": "Metabolic Bone Disease (MBD)",
        "name_ja": "代謝性骨疾患（MBD）",
        "symptoms": {"soft_bones", "tremors", "weakness", "lethargy", "fractures", "swollen_limbs", "jaw_softening", "anorexia"},
        "description": "A nutritional disorder caused by calcium deficiency, phosphorus imbalance, or inadequate UVB exposure, leading to weakened and deformed bones.",
        "description_ja": "カルシウム不足、リン比の不均衡、またはUVB不足により骨が軟化・変形する栄養性疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "radiographs", "uvb_husbandry_review"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism",
        "name_ja": "栄養性二次性副甲状腺機能亢進症",
        "symptoms": {"soft_bones", "tremors", "fractures", "jaw_softening", "weakness", "lethargy"},
        "description": "Over-secretion of parathyroid hormone due to chronic calcium deficiency or vitamin D3 insufficiency.",
        "description_ja": "慢性的なカルシウム不足またはビタミンD3不足による副甲状腺ホルモンの過剰分泌です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "pth_levels", "radiographs"],
    },
    {
        "name": "Vitamin A Deficiency (Hypovitaminosis A)",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"swollen_eyes", "nasal_discharge", "respiratory_distress", "anorexia", "skin_lesions", "lethargy"},
        "description": "Insufficient dietary vitamin A causing squamous metaplasia of epithelial tissues, particularly affecting eyes and respiratory tract.",
        "description_ja": "食事中のビタミンA不足により上皮組織の扁平上皮化生を引き起こし、特に目や呼吸器に影響します。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_a_levels", "physical_exam", "dietary_review"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"soft_bones", "weakness", "lethargy", "tremors", "anorexia"},
        "description": "Lack of vitamin D3 from inadequate UVB exposure or dietary sources, impairing calcium absorption.",
        "description_ja": "UVB照射不足または食事からのビタミンD3不足により、カルシウムの吸収が阻害されます。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_d3", "blood_calcium_phosphorus", "husbandry_review"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"tremors", "muscle_twitching", "seizures", "weakness", "lethargy", "anorexia"},
        "description": "Critically low blood calcium levels causing neuromuscular dysfunction.",
        "description_ja": "血中カルシウムの著しい低下により神経筋機能障害を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["blood_calcium", "ionized_calcium", "blood_chemistry"],
    },
    {
        "name": "Hypervitaminosis A",
        "name_ja": "ビタミンA過剰症",
        "symptoms": {"skin_lesions", "skin_sloughing", "lethargy", "anorexia", "swelling"},
        "description": "Toxicity from excessive vitamin A supplementation causing epithelial damage.",
        "description_ja": "ビタミンAの過剰投与により上皮組織の損傷を引き起こす中毒症です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_a_levels", "liver_function_tests", "dietary_review"],
    },
    {
        "name": "Hypervitaminosis D3",
        "name_ja": "ビタミンD3過剰症",
        "symptoms": {"anorexia", "lethargy", "excessive_thirst", "excessive_urination", "weakness"},
        "description": "Over-supplementation of vitamin D3 causing hypercalcemia and soft tissue mineralization.",
        "description_ja": "ビタミンD3の過剰摂取により高カルシウム血症と軟部組織の石�ite化を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium", "blood_chemistry", "radiographs"],
    },
    {
        "name": "Thiamine (Vitamin B1) Deficiency",
        "name_ja": "チアミン（ビタミンB1）欠乏症",
        "symptoms": {"neurological_signs", "tremors", "head_tilt", "weakness", "anorexia"},
        "description": "Deficiency of thiamine, often from feeding frozen-thawed fish diets, causing neurological dysfunction.",
        "description_ja": "主に冷凍解凍した魚の給餌により起こるチアミン欠乏で、神経学的異常を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_thiamine_levels", "neurological_exam", "dietary_review"],
    },
    {
        "name": "Iron Storage Disease (Hemochromatosis)",
        "name_ja": "鉄蓄積症（ヘモクロマトーシス）",
        "symptoms": {"lethargy", "anorexia", "weight_loss", "abdominal_swelling"},
        "description": "Excessive iron accumulation in liver and other organs, occasionally seen in certain reptile species.",
        "description_ja": "肝臓やその他の臓器への過剰な鉄蓄積です。",
        "urgency": "moderate",
        "recommended_tests": ["liver_function_tests", "blood_iron_levels", "liver_biopsy"],
    },
    # ── Articular / Visceral Gout ────────────────────────────────────────
    {
        "name": "Articular Gout",
        "name_ja": "関節痛風",
        "symptoms": {"swollen_joints", "joint_pain", "lameness", "lethargy", "anorexia"},
        "description": "Deposition of uric acid crystals in joints due to renal dysfunction or chronic dehydration.",
        "description_ja": "腎機能障害や慢性的な脱水により尿酸結晶が関節に沈着する疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "radiographs", "joint_aspiration"],
    },
    {
        "name": "Visceral Gout",
        "name_ja": "内臓痛風",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "sudden_death"},
        "description": "Uric acid crystal deposition on internal organs, often secondary to renal failure.",
        "description_ja": "腎不全に続発し、内臓表面に尿酸結晶が沈着する重篤な疾患です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "radiographs", "ultrasound"],
    },
    # ── Respiratory ──────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection (URI)",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"nasal_discharge", "open_mouth_breathing", "wheezing", "lethargy", "anorexia"},
        "description": "Bacterial, viral, or fungal infection of the upper respiratory tract, commonly linked to poor husbandry.",
        "description_ja": "低温・湿度管理不良などに関連する上部呼吸器の細菌・ウイルス・真菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "culture_sensitivity", "radiographs"],
    },
    {
        "name": "Lower Respiratory Infection (Pneumonia)",
        "name_ja": "下部呼吸器感染症（肺炎）",
        "symptoms": {"open_mouth_breathing", "respiratory_distress", "wheezing", "nasal_discharge", "lethargy", "anorexia", "mucus_in_mouth"},
        "description": "Bacterial or fungal infection of the lungs, often progressing from untreated upper respiratory infection.",
        "description_ja": "未治療の上部呼吸器感染症から進行することが多い肺の細菌・真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "tracheal_wash", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Mycoplasma Respiratory Infection",
        "name_ja": "マイコプラズマ呼吸器感染症",
        "symptoms": {"nasal_discharge", "wheezing", "lethargy", "anorexia", "swollen_eyes"},
        "description": "Chronic respiratory disease caused by Mycoplasma spp., common in tortoises and other chelonians.",
        "description_ja": "マイコプラズマ属菌による慢性呼吸器疾患で、リクガメに多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_mycoplasma", "nasal_culture", "radiographs"],
    },
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "weight_loss"},
        "description": "Fungal infection caused by Aspergillus spp. affecting the respiratory tract.",
        "description_ja": "アスペルギルス属真菌による呼吸器の真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "radiographs", "endoscopy"],
    },
    # ── Oral / Stomatitis ────────────────────────────────────────────────
    {
        "name": "Infectious Stomatitis (Mouth Rot)",
        "name_ja": "感染性口内炎（マウスロット）",
        "symptoms": {"mouth_lesions", "swollen_gums", "mucus_in_mouth", "anorexia", "drooling", "oral_hemorrhage"},
        "description": "Bacterial infection of the oral cavity causing inflammation, caseous exudate, and tissue necrosis.",
        "description_ja": "口腔内の細菌感染により炎症、乾酪性浸出液、組織壊死を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Oral Abscess",
        "name_ja": "口腔膿瘍",
        "symptoms": {"mouth_lesions", "swelling", "anorexia", "drooling", "facial_swelling"},
        "description": "Localized bacterial infection forming an abscess within the oral cavity.",
        "description_ja": "口腔内に限局性の細菌感染により膿瘍が形成される疾患です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "radiographs"],
    },
    # ── Parasitic ────────────────────────────────────────────────────────
    {
        "name": "Internal Parasites (Nematodes)",
        "name_ja": "内部寄生虫（線虫）",
        "symptoms": {"weight_loss", "anorexia", "diarrhea", "lethargy", "regurgitation"},
        "description": "Gastrointestinal infection with roundworms including ascarids and strongylids.",
        "description_ja": "回虫類や円虫類による消化管の寄生虫感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_float", "complete_blood_count"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"weight_loss", "regurgitation", "anorexia", "lethargy", "diarrhea", "body_swelling"},
        "description": "Protozoal infection caused by Cryptosporidium spp., particularly devastating in snakes and lizards.",
        "description_ja": "クリプトスポリジウム属原虫による感染症で、特にヘビやトカゲで深刻です。",
        "urgency": "high",
        "recommended_tests": ["pcr_cryptosporidium", "acid_fast_stain", "gastric_biopsy"],
    },
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "lethargy", "bloody_stool"},
        "description": "Protozoal infection of the intestinal tract by Isospora or Eimeria species.",
        "description_ja": "イソスポラ属やアイメリア属原虫による腸管の寄生虫感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_float"],
    },
    {
        "name": "Amoebic Infection (Entamoeba)",
        "name_ja": "アメーバ感染症",
        "symptoms": {"diarrhea", "bloody_stool", "anorexia", "weight_loss", "lethargy"},
        "description": "Infection with Entamoeba invadens causing severe colitis, particularly in snakes and lizards.",
        "description_ja": "エンタメーバ・インバデンスによる重度の大腸炎で、特にヘビやトカゲに多いです。",
        "urgency": "high",
        "recommended_tests": ["fecal_exam", "fecal_wet_mount", "pcr_entamoeba"],
    },
    {
        "name": "Hexamita Infection",
        "name_ja": "ヘキサミタ感染症",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "lethargy"},
        "description": "Flagellate protozoal infection affecting the gastrointestinal tract, commonly seen in chelonians.",
        "description_ja": "鞭毛虫による消化管の感染症で、カメ類に多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_exam"],
    },
    {
        "name": "External Mites (Ophionyssus)",
        "name_ja": "外部寄生ダニ（ヘビダニ）",
        "symptoms": {"excessive_soaking", "skin_irritation", "visible_mites", "lethargy", "anorexia", "dysecdysis"},
        "description": "Ectoparasitic mite infestation, most common in snakes but can affect all reptiles.",
        "description_ja": "外部寄生ダニの感染で、ヘビに最も多いですが全ての爬虫類に影響し得ます。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_scraping", "mite_identification"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "マダニ寄生",
        "symptoms": {"visible_mites", "skin_lesions", "anorexia", "lethargy", "anemia"},
        "description": "External parasitism by ticks, which can also transmit blood-borne pathogens.",
        "description_ja": "マダニの外部寄生で、血液媒介性病原体の伝播リスクもあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "complete_blood_count", "blood_smear"],
    },
    {
        "name": "Pentastomid Infection",
        "name_ja": "舌虫症",
        "symptoms": {"respiratory_distress", "open_mouth_breathing", "nasal_discharge", "lethargy"},
        "description": "Internal parasitic infection by pentastomids (tongue worms) affecting the respiratory tract.",
        "description_ja": "舌虫（五口動物）による呼吸器内部の寄生虫感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "endoscopy", "fecal_exam"],
    },
    {
        "name": "Myiasis (Fly Strike)",
        "name_ja": "蝿蛆症（ハエウジ症）",
        "symptoms": {"skin_lesions", "visible_larvae", "foul_odor", "lethargy", "anorexia"},
        "description": "Infestation of open wounds or moist skin folds by fly larvae (maggots).",
        "description_ja": "開放創や湿った皮膚のひだにハエの幼虫が寄生する疾患です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_culture"],
    },
    # ── Skin / Integument ────────────────────────────────────────────────
    {
        "name": "Dysecdysis (Retained Shed)",
        "name_ja": "脱皮不全",
        "symptoms": {"dysecdysis", "retained_skin", "skin_constriction", "lethargy", "anorexia"},
        "description": "Incomplete or abnormal shedding of skin, often caused by low humidity or underlying illness.",
        "description_ja": "低湿度や基礎疾患により脱皮が不完全になる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review", "skin_exam"],
    },
    {
        "name": "Scale Rot (Ulcerative Dermatitis)",
        "name_ja": "スケイルロット（潰瘍性皮膚炎）",
        "symptoms": {"scale_discoloration", "skin_lesions", "blisters", "foul_odor", "lethargy", "anorexia"},
        "description": "Bacterial infection of the ventral scales caused by prolonged contact with damp or soiled substrate.",
        "description_ja": "湿った不衛生な床材との長期接触により腹部の鱗に細菌感染が起こる疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "skin_biopsy", "husbandry_review"],
    },
    {
        "name": "Blister Disease",
        "name_ja": "水疱症",
        "symptoms": {"blisters", "skin_lesions", "scale_discoloration", "lethargy"},
        "description": "Fluid-filled blisters on the skin, typically from overly damp substrate conditions.",
        "description_ja": "過度に湿った床材により皮膚に水疱が形成される疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_exam", "culture_sensitivity", "husbandry_review"],
    },
    {
        "name": "Thermal Burns",
        "name_ja": "熱傷",
        "symptoms": {"skin_burns", "skin_lesions", "blisters", "scale_discoloration", "anorexia", "lethargy"},
        "description": "Burns caused by unregulated heat sources such as heat rocks, lamps, or heating pads.",
        "description_ja": "ヒートロック、ランプ、ヒーティングパッドなどの温度管理不良による火傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    {
        "name": "Dermatophytosis (Fungal Skin Infection)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"skin_lesions", "scale_discoloration", "dysecdysis", "crusty_patches"},
        "description": "Fungal infection of the skin caused by dermatophyte organisms.",
        "description_ja": "皮膚糸状菌による皮膚の真菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "skin_biopsy"],
    },
    {
        "name": "Bacterial Dermatitis",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_lesions", "skin_redness", "swelling", "foul_odor", "lethargy"},
        "description": "Bacterial infection of the skin causing inflammation, redness, and potential ulceration.",
        "description_ja": "皮膚の細菌感染により炎症、発赤、潰瘍化を引き起こす疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Subcutaneous Abscess",
        "name_ja": "皮下膿瘍",
        "symptoms": {"swelling", "firm_mass", "anorexia", "lethargy"},
        "description": "Encapsulated bacterial infection forming a firm, caseous abscess under the skin.",
        "description_ja": "皮膚の下に被包化された細菌感染により硬い乾酪性膿瘍が形成される疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "radiographs"],
    },
    {
        "name": "Rostral Abrasion (Nose Rub)",
        "name_ja": "吻部擦過傷（ノーズラブ）",
        "symptoms": {"nose_abrasion", "facial_swelling", "skin_lesions", "anorexia"},
        "description": "Abrasion of the snout from repeated rubbing against enclosure walls, common in snakes.",
        "description_ja": "ケージ壁面への繰り返し擦り付けにより吻部が擦過傷を起こす状態です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    # ── Shell Diseases (Chelonians) ──────────────────────────────────────
    {
        "name": "Shell Rot (Ulcerative Shell Disease)",
        "name_ja": "甲羅腐敗症",
        "symptoms": {"shell_discoloration", "shell_soft_spots", "foul_odor", "shell_pitting", "anorexia", "lethargy"},
        "description": "Bacterial or fungal infection of the shell causing erosion and necrosis of scutes.",
        "description_ja": "甲羅の細菌・真菌感染により甲板の侵食と壊死を引き起こす疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["shell_exam", "shell_culture", "radiographs"],
    },
    {
        "name": "Shell Fracture / Trauma",
        "name_ja": "甲羅骨折・外傷",
        "symptoms": {"shell_crack", "bleeding", "shell_displacement", "lethargy", "anorexia"},
        "description": "Physical damage to the shell from falls, predator attacks, or vehicle strikes.",
        "description_ja": "落下、捕食者の攻撃、車両との接触などによる甲羅の物理的損傷です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "wound_assessment", "complete_blood_count"],
    },
    {
        "name": "Pyramiding",
        "name_ja": "ピラミッディング（甲羅の隆起異常）",
        "symptoms": {"shell_pyramiding", "abnormal_shell_growth"},
        "description": "Abnormal upward growth of shell scutes, primarily linked to improper diet, humidity, and husbandry.",
        "description_ja": "甲板が異常に隆起する成長異常で、主に不適切な食事や湿度管理が原因です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "dietary_review", "husbandry_review"],
    },
    # ── Gastrointestinal ─────────────────────────────────────────────────
    {
        "name": "Gastrointestinal Impaction",
        "name_ja": "消化管閉塞（インパクション）",
        "symptoms": {"anorexia", "constipation", "lethargy", "abdominal_swelling", "straining"},
        "description": "Blockage of the GI tract from ingested substrate, foreign bodies, or large food items.",
        "description_ja": "床材、異物、大きな餌の摂取による消化管の閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam", "ultrasound"],
    },
    {
        "name": "Gastroenteritis",
        "name_ja": "胃腸炎",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "regurgitation", "dehydration"},
        "description": "Inflammation of the stomach and intestines from bacterial, viral, or parasitic causes.",
        "description_ja": "細菌、ウイルス、寄生虫による胃腸の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物誤飲",
        "symptoms": {"anorexia", "regurgitation", "abdominal_swelling", "lethargy", "constipation"},
        "description": "Ingestion of non-food items such as substrate, decorations, or bedding material.",
        "description_ja": "床材、装飾品、敷材などの非食品の誤飲です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "contrast_study"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "jaundice", "abdominal_swelling"},
        "description": "Excessive fat accumulation in the liver, often from obesity or prolonged anorexia.",
        "description_ja": "肥満や長期の食欲不振による肝臓への過剰な脂肪蓄積です。",
        "urgency": "high",
        "recommended_tests": ["liver_function_tests", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "weight_loss", "dehydration"},
        "description": "Bacterial infection by Salmonella spp.; reptiles are often asymptomatic carriers but can develop clinical disease under stress.",
        "description_ja": "サルモネラ属菌による感染症で、爬虫類は無症候性保菌者であることが多いですが、ストレス下で発症することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "blood_culture", "complete_blood_count"],
    },
    # ── Dehydration / General ────────────────────────────────────────────
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"sunken_eyes", "wrinkled_skin", "decreased_skin_elasticity", "lethargy", "anorexia", "dry_mucous_membranes"},
        "description": "Insufficient fluid intake or excessive fluid loss leading to systemic compromise.",
        "description_ja": "水分摂取の不足または過度な水分喪失による全身状態の悪化です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "packed_cell_volume"],
    },
    {
        "name": "Anorexia (Non-specific)",
        "name_ja": "食欲不振（非特異的）",
        "symptoms": {"anorexia", "weight_loss", "lethargy"},
        "description": "Refusal to eat, which can be caused by illness, improper husbandry, stress, or seasonal changes.",
        "description_ja": "疾病、不適切な飼育環境、ストレス、季節変化などによる摂食拒否です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "blood_chemistry", "husbandry_review", "fecal_exam"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"excessive_weight", "fat_deposits", "lethargy", "difficulty_moving"},
        "description": "Excess body fat from overfeeding or lack of exercise, predisposing to hepatic lipidosis and other conditions.",
        "description_ja": "過食や運動不足による過剰な体脂肪蓄積で、脂肪肝などの疾患を引き起こすリスクがあります。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "body_condition_scoring", "dietary_review"],
    },
    # ── Viral Diseases ───────────────────────────────────────────────────
    {
        "name": "Inclusion Body Disease (IBD)",
        "name_ja": "封入体病（IBD）",
        "symptoms": {"neurological_signs", "stargazing", "regurgitation", "anorexia", "head_tilt", "tremors", "paralysis"},
        "description": "Fatal arenavirus infection primarily affecting boid snakes, causing severe neurological and gastrointestinal signs.",
        "description_ja": "主にボア科のヘビに影響する致死性のアレナウイルス感染症で、重篤な神経学的・消化器症状を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_ibd", "liver_biopsy", "complete_blood_count"],
    },
    {
        "name": "Adenovirus Infection",
        "name_ja": "アデノウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "diarrhea", "neurological_signs", "weight_loss", "sudden_death"},
        "description": "Viral infection particularly severe in bearded dragons (Atadenovirus) and some snake species.",
        "description_ja": "特にフトアゴヒゲトカゲ（アタデノウイルス）や一部のヘビで重症化するウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_adenovirus", "liver_biopsy", "complete_blood_count"],
    },
    {
        "name": "Paramyxovirus Infection",
        "name_ja": "パラミクソウイルス感染症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "neurological_signs", "open_mouth_breathing", "sudden_death"},
        "description": "Highly contagious viral infection in snakes causing severe pneumonia and neurological disease.",
        "description_ja": "ヘビに重篤な肺炎と神経疾患を引き起こす高度伝染性のウイルス感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_paramyxovirus", "hemagglutination_inhibition", "radiographs"],
    },
    {
        "name": "Nidovirus Infection",
        "name_ja": "ニドウイルス感染症",
        "symptoms": {"respiratory_distress", "open_mouth_breathing", "mucus_in_mouth", "wheezing", "lethargy", "anorexia"},
        "description": "Viral respiratory infection increasingly recognized in ball pythons and other snake species.",
        "description_ja": "ボールパイソンやその他のヘビで認識が増えているウイルス性呼吸器感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_nidovirus", "oral_swab", "tracheal_wash"],
    },
    {
        "name": "Herpesvirus Infection",
        "name_ja": "ヘルペスウイルス感染症",
        "symptoms": {"nasal_discharge", "mouth_lesions", "anorexia", "lethargy", "stomatitis", "conjunctivitis"},
        "description": "Herpesvirus causing stomatitis, rhinitis, and hepatitis, especially in chelonians.",
        "description_ja": "特にカメ類で口内炎、鼻炎、肝炎を引き起こすヘルペスウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_herpesvirus", "viral_isolation", "liver_function_tests"],
    },
    {
        "name": "Ranavirus Infection",
        "name_ja": "ラナウイルス感染症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "edema", "sudden_death"},
        "description": "Iridovirus family pathogen causing systemic hemorrhagic disease in chelonians and other reptiles.",
        "description_ja": "カメ類やその他の爬虫類に全身性出血性疾患を引き起こすイリドウイルス科の病原体です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_ranavirus", "histopathology", "complete_blood_count"],
    },
    {
        "name": "Iridovirus Infection",
        "name_ja": "イリドウイルス感染症",
        "symptoms": {"skin_lesions", "lethargy", "anorexia", "edema", "skin_hemorrhage"},
        "description": "Systemic viral disease caused by iridoviruses, affecting multiple organ systems.",
        "description_ja": "イリドウイルスによる全身性ウイルス疾患で、複数の臓器系に影響します。",
        "urgency": "high",
        "recommended_tests": ["pcr_iridovirus", "histopathology", "complete_blood_count"],
    },
    # ── Septicemia / Systemic ────────────────────────────────────────────
    {
        "name": "Septicemia (Blood Poisoning)",
        "name_ja": "敗血症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "petechia", "respiratory_distress", "sudden_death"},
        "description": "Systemic bacterial infection in the bloodstream, often secondary to wounds, burns, or other infections.",
        "description_ja": "創傷、火傷、その他の感染症に続発する血流中の全身性細菌感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count", "blood_chemistry"],
    },
    # ── Eye Diseases ─────────────────────────────────────────────────────
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"swollen_eyes", "eye_discharge", "conjunctivitis", "anorexia"},
        "description": "Inflammation of the conjunctiva from bacterial infection, foreign bodies, or vitamin A deficiency.",
        "description_ja": "細菌感染、異物、ビタミンA欠乏による結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "eye_culture", "blood_vitamin_a_levels"],
    },
    {
        "name": "Retained Spectacle (Retained Eye Cap)",
        "name_ja": "スペクタクル脱皮不全（アイキャップ残留）",
        "symptoms": {"cloudy_eyes", "retained_spectacle", "dysecdysis", "eye_swelling"},
        "description": "Failure to shed the spectacle (eye cap) in snakes and some geckos, potentially causing infection.",
        "description_ja": "ヘビや一部のヤモリでスペクタクル（眼鏡）が脱皮されない状態で、感染のリスクがあります。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "physical_exam", "husbandry_review"],
    },
    {
        "name": "Subspectacular Abscess",
        "name_ja": "スペクタクル下膿瘍",
        "symptoms": {"eye_swelling", "cloudy_eyes", "bulging_eye", "anorexia"},
        "description": "Abscess formation beneath the spectacle in snakes, requiring surgical drainage.",
        "description_ja": "ヘビのスペクタクル下に膿瘍が形成される疾患で、外科的排膿が必要です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "culture_sensitivity", "ultrasound"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"cloudy_eyes", "eye_discharge", "eye_swelling", "anorexia"},
        "description": "Ulceration of the cornea from trauma, infection, or desiccation.",
        "description_ja": "外傷、感染、乾燥による角膜の潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "eye_culture"],
    },
    # ── Reproductive ─────────────────────────────────────────────────────
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "卵塞（難産）",
        "symptoms": {"straining", "lethargy", "anorexia", "abdominal_swelling", "restlessness", "cloacal_swelling"},
        "description": "Inability to pass eggs due to obstruction, poor muscle tone, calcium deficiency, or environmental factors.",
        "description_ja": "閉塞、筋力低下、カルシウム欠乏、環境要因により卵を排出できない状態です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "blood_calcium"],
    },
    {
        "name": "Pre-ovulatory Follicular Stasis",
        "name_ja": "排卵前卵胞停滞",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "weight_loss"},
        "description": "Failure of ovarian follicles to ovulate normally, leading to follicular enlargement and potential coelomitis.",
        "description_ja": "卵巣卵胞が正常に排卵されず、卵胞肥大や体腔炎を引き起こす可能性がある状態です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_chemistry"],
    },
    {
        "name": "Post-ovulatory Egg Stasis",
        "name_ja": "排卵後卵停滞",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "straining"},
        "description": "Retention of eggs in the oviduct after ovulation, requiring medical or surgical intervention.",
        "description_ja": "排卵後に卵管内に卵が停滞する状態で、内科的または外科的介入が必要です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "blood_calcium"],
    },
    # ── Prolapse ─────────────────────────────────────────────────────────
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "straining", "anorexia", "lethargy"},
        "description": "Protrusion of cloacal tissue, which may involve the colon, oviduct, or urinary bladder.",
        "description_ja": "総排泄腔組織の突出で、結腸、卵管、膀胱が関与する場合があります。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs", "ultrasound"],
    },
    {
        "name": "Hemipenal Prolapse",
        "name_ja": "半陰茎脱出",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "swelling"},
        "description": "Prolapse of one or both hemipenes in male snakes and lizards.",
        "description_ja": "雄のヘビやトカゲで片方または両方の半陰茎が脱出する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    {
        "name": "Gastric/Intestinal Prolapse",
        "name_ja": "胃・腸管脱出",
        "symptoms": {"tissue_prolapse", "anorexia", "lethargy", "abdominal_swelling"},
        "description": "Protrusion of stomach or intestinal tissue through the cloaca, a life-threatening condition.",
        "description_ja": "胃や腸管組織が総排泄腔から突出する生命を脅かす状態です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    # ── Renal / Urinary ──────────────────────────────────────────────────
    {
        "name": "Renal Failure (Chronic Kidney Disease)",
        "name_ja": "腎不全（慢性腎疾患）",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "edema", "gout_tophi"},
        "description": "Progressive loss of kidney function, common in reptiles fed high-protein diets or suffering chronic dehydration.",
        "description_ja": "高タンパク食や慢性的な脱水により進行する腎機能の喪失です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound", "kidney_biopsy"],
    },
    {
        "name": "Bladder Stones (Urolithiasis)",
        "name_ja": "膀胱結石（尿路結石症）",
        "symptoms": {"straining", "anorexia", "lethargy", "abdominal_swelling", "bloody_urates"},
        "description": "Formation of mineral calculi in the urinary bladder, common in herbivorous reptiles.",
        "description_ja": "草食性爬虫類に多い膀胱内のミネラル結石の形成です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "urinalysis"],
    },
    # ── Neurological ─────────────────────────────────────────────────────
    {
        "name": "Neurological Syndrome (Non-specific)",
        "name_ja": "神経学的症候群（非特異的）",
        "symptoms": {"neurological_signs", "head_tilt", "circling", "tremors", "seizures", "stargazing"},
        "description": "Neurological dysfunction from infectious, metabolic, toxic, or congenital causes.",
        "description_ja": "感染性、代謝性、中毒性、先天性の原因による神経機能障害です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "blood_chemistry", "radiographs", "ct_mri"],
    },
    {
        "name": "Spinal Osteopathy / Spondylosis",
        "name_ja": "脊椎骨症/脊椎症",
        "symptoms": {"paralysis", "difficulty_moving", "weakness", "abnormal_posture"},
        "description": "Degenerative or infectious changes in the spinal vertebrae causing compression or pain.",
        "description_ja": "脊椎の変性または感染性変化により圧迫や疼痛を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ct_mri", "neurological_exam"],
    },
    # ── Neoplasia ────────────────────────────────────────────────────────
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"firm_mass", "skin_lesions", "ulcerated_mass", "weight_loss", "anorexia"},
        "description": "Malignant tumor of epithelial origin, one of the more common neoplasms in reptiles.",
        "description_ja": "爬虫類で比較的多い上皮由来の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "anorexia", "lethargy", "swelling", "organ_enlargement"},
        "description": "Malignant neoplasm of lymphoid tissue that can affect multiple organ systems.",
        "description_ja": "複数の臓器系に影響し得るリンパ組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "complete_blood_count", "radiographs", "ultrasound"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"firm_mass", "swelling", "weight_loss", "lethargy"},
        "description": "Malignant connective tissue tumor occasionally seen in reptiles.",
        "description_ja": "爬虫類で時折見られる結合組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ（悪性黒色腫）",
        "symptoms": {"dark_skin_mass", "skin_lesions", "firm_mass"},
        "description": "Pigmented tumor arising from melanocytes, seen in various reptile species.",
        "description_ja": "メラノサイト由来の色素性腫瘍で、様々な爬虫類種で見られます。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    # ── Organ Failure / Systemic ─────────────────────────────────────────
    {
        "name": "Liver Failure (Hepatopathy)",
        "name_ja": "肝不全（肝疾患）",
        "symptoms": {"anorexia", "lethargy", "jaundice", "weight_loss", "abdominal_swelling", "edema"},
        "description": "Severe liver dysfunction from infectious, toxic, or metabolic causes.",
        "description_ja": "感染性、中毒性、代謝性の原因による重篤な肝機能障害です。",
        "urgency": "emergency",
        "recommended_tests": ["liver_function_tests", "blood_chemistry", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Cardiac Disease",
        "name_ja": "心疾患",
        "symptoms": {"lethargy", "edema", "respiratory_distress", "weakness", "sudden_death"},
        "description": "Heart disease including cardiomyopathy and pericardial effusion in reptiles.",
        "description_ja": "心筋症や心嚢液貯留を含む爬虫類の心疾患です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiographs", "electrocardiogram"],
    },
    # ── Miscellaneous ────────────────────────────────────────────────────
    {
        "name": "Frostbite / Cold Injury",
        "name_ja": "凍傷・低温障害",
        "symptoms": {"skin_discoloration", "skin_necrosis", "lethargy", "anorexia", "tissue_swelling"},
        "description": "Tissue damage from exposure to temperatures below the species' tolerance range.",
        "description_ja": "種の耐性温度範囲を下回る温度への暴露による組織損傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "blood_chemistry"],
    },
    {
        "name": "Hyperthermia (Heat Stroke)",
        "name_ja": "高体温症（熱中症）",
        "symptoms": {"open_mouth_breathing", "lethargy", "weakness", "neurological_signs", "sudden_death"},
        "description": "Dangerously elevated body temperature from excessive heat exposure or inadequate thermal gradient.",
        "description_ja": "過度の熱暴露や不適切な温度勾配による危険な体温上昇です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry", "husbandry_review"],
    },
    {
        "name": "Hypothermia",
        "name_ja": "低体温症",
        "symptoms": {"lethargy", "anorexia", "weakness", "slow_reflexes"},
        "description": "Body temperature below optimal range, suppressing immune function and digestion.",
        "description_ja": "体温が適切な範囲を下回り、免疫機能と消化を抑制する状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "temperature_check", "husbandry_review"],
    },
    {
        "name": "Trauma / Bite Wounds",
        "name_ja": "外傷・咬傷",
        "symptoms": {"skin_lesions", "bleeding", "swelling", "anorexia", "lethargy"},
        "description": "Physical injuries from cage mates, prey items, or handling accidents.",
        "description_ja": "同居個体、餌動物、取り扱い事故による物理的損傷です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Stress Syndrome",
        "name_ja": "ストレス症候群",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "color_change", "hiding_behavior"},
        "description": "Chronic stress from improper husbandry, overcrowding, or inadequate hiding spots.",
        "description_ja": "不適切な飼育環境、過密飼育、隠れ場所不足による慢性的ストレスです。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "physical_exam"],
    },
    {
        "name": "Regurgitation Syndrome",
        "name_ja": "吐出症候群",
        "symptoms": {"regurgitation", "anorexia", "weight_loss", "lethargy"},
        "description": "Chronic regurgitation of prey items from infectious, husbandry, or handling causes.",
        "description_ja": "感染性、飼育環境、取り扱いの原因による餌の慢性的な吐出です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "radiographs", "husbandry_review"],
    },
    {
        "name": "Toxicosis (Poisoning)",
        "name_ja": "中毒症",
        "symptoms": {"neurological_signs", "tremors", "seizures", "anorexia", "lethargy", "sudden_death"},
        "description": "Exposure to toxic substances such as pesticides, toxic plants, or contaminated water.",
        "description_ja": "殺虫剤、有毒植物、汚染水などの有毒物質への暴露です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "toxicology_screen", "physical_exam"],
    },
    {
        "name": "Chronic Malnutrition",
        "name_ja": "慢性栄養不良",
        "symptoms": {"weight_loss", "weakness", "lethargy", "anorexia", "poor_body_condition"},
        "description": "Long-term inadequate nutrition leading to wasting and immune suppression.",
        "description_ja": "長期的な栄養不足による消耗と免疫抑制です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review", "physical_exam"],
    },
    {
        "name": "Yellow Fungus Disease (Chrysosporium anamorph of Nannizziopsis vriesii - CANV)",
        "name_ja": "黄色真菌症（CANV）",
        "symptoms": {"yellow_skin_patches", "skin_lesions", "crusty_patches", "dysecdysis", "anorexia", "lethargy"},
        "description": "Aggressive fungal infection causing yellow-brown crusting lesions, primarily in bearded dragons and other lizards.",
        "description_ja": "主にフトアゴヒゲトカゲなどのトカゲで黄褐色の痂皮性病変を引き起こす侵攻性真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "skin_biopsy", "pcr_canv"],
    },
    {
        "name": "Osteomyelitis",
        "name_ja": "骨髄炎",
        "symptoms": {"swelling", "lameness", "anorexia", "lethargy", "firm_mass"},
        "description": "Bacterial infection of bone tissue, often secondary to bite wounds or hematogenous spread.",
        "description_ja": "咬傷や血行性播種に続発する骨組織の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "bone_culture", "complete_blood_count"],
    },
    {
        "name": "Peritonitis / Coelomitis",
        "name_ja": "腹膜炎・体腔炎",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "pain_response", "respiratory_distress"},
        "description": "Inflammation of the coelomic cavity from egg rupture, organ perforation, or bacterial infection.",
        "description_ja": "卵の破裂、臓器穿孔、細菌感染による体腔の炎症です。",
        "urgency": "emergency",
        "recommended_tests": ["coelomic_fluid_analysis", "ultrasound", "blood_chemistry"],
    },
    {
        "name": "Panophthalmitis",
        "name_ja": "全眼球炎",
        "symptoms": {"bulging_eye", "eye_swelling", "eye_discharge", "anorexia", "lethargy"},
        "description": "Severe infection of the entire eye, often requiring enucleation.",
        "description_ja": "眼球全体の重度の感染症で、しばしば摘出が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmic_exam", "eye_culture", "ultrasound"],
    },
    {
        "name": "Chlamydiosis",
        "name_ja": "クラミジア症",
        "symptoms": {"conjunctivitis", "nasal_discharge", "lethargy", "anorexia", "respiratory_distress"},
        "description": "Intracellular bacterial infection caused by Chlamydia spp. affecting eyes and respiratory system.",
        "description_ja": "クラミジア属菌による細胞内細菌感染症で、目と呼吸器系に影響します。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_chlamydia", "conjunctival_swab", "complete_blood_count"],
    },
    {
        "name": "Mycobacteriosis",
        "name_ja": "マイコバクテリウム症",
        "symptoms": {"weight_loss", "anorexia", "skin_lesions", "lethargy", "granulomatous_lesions"},
        "description": "Chronic infection caused by Mycobacterium spp. forming granulomas in multiple organs.",
        "description_ja": "マイコバクテリウム属菌による慢性感染症で、複数の臓器に肉芽腫を形成します。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "culture", "biopsy", "radiographs"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "soft_bones": {"ja": "骨軟化", "en": "Soft bones"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "swollen_limbs": {"ja": "四肢の腫脹", "en": "Swollen limbs"},
    "jaw_softening": {"ja": "顎の軟化", "en": "Jaw softening"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "swollen_eyes": {"ja": "眼腫脹", "en": "Swollen eyes"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory distress"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "skin_sloughing": {"ja": "皮膚剥離", "en": "Skin sloughing"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "excessive_thirst": {"ja": "多飲", "en": "Excessive thirst"},
    "excessive_urination": {"ja": "多尿", "en": "Excessive urination"},
    "muscle_twitching": {"ja": "筋肉のピクつき", "en": "Muscle twitching"},
    "seizures": {"ja": "発作", "en": "Seizures"},
    "neurological_signs": {"ja": "神経学的徴候", "en": "Neurological signs"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "open_mouth_breathing": {"ja": "口を開けて呼吸", "en": "Open-mouth breathing"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "mucus_in_mouth": {"ja": "口腔内粘液", "en": "Mucus in mouth"},
    "mouth_lesions": {"ja": "口腔内病変", "en": "Mouth lesions"},
    "swollen_gums": {"ja": "歯肉腫脹", "en": "Swollen gums"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "oral_hemorrhage": {"ja": "口腔出血", "en": "Oral hemorrhage"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "regurgitation": {"ja": "吐出", "en": "Regurgitation"},
    "body_swelling": {"ja": "体の腫脹", "en": "Body swelling"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "excessive_soaking": {"ja": "過度の水浸し", "en": "Excessive soaking"},
    "skin_irritation": {"ja": "皮膚の刺激感", "en": "Skin irritation"},
    "visible_mites": {"ja": "肉眼で確認できるダニ", "en": "Visible mites"},
    "dysecdysis": {"ja": "脱皮不全", "en": "Dysecdysis"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "visible_larvae": {"ja": "肉眼で確認できる幼虫", "en": "Visible larvae"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "retained_skin": {"ja": "残皮", "en": "Retained skin"},
    "skin_constriction": {"ja": "皮膚の絞扼", "en": "Skin constriction"},
    "scale_discoloration": {"ja": "鱗の変色", "en": "Scale discoloration"},
    "blisters": {"ja": "水疱", "en": "Blisters"},
    "skin_burns": {"ja": "皮膚の火傷", "en": "Skin burns"},
    "crusty_patches": {"ja": "痂皮性斑", "en": "Crusty patches"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "firm_mass": {"ja": "硬い腫瘤", "en": "Firm mass"},
    "nose_abrasion": {"ja": "吻部の擦過傷", "en": "Nose abrasion"},
    "shell_discoloration": {"ja": "甲羅の変色", "en": "Shell discoloration"},
    "shell_soft_spots": {"ja": "甲羅の軟化部", "en": "Shell soft spots"},
    "shell_pitting": {"ja": "甲羅の陥凹", "en": "Shell pitting"},
    "shell_crack": {"ja": "甲羅の亀裂", "en": "Shell crack"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "shell_displacement": {"ja": "甲羅の変位", "en": "Shell displacement"},
    "shell_pyramiding": {"ja": "甲羅のピラミッディング", "en": "Shell pyramiding"},
    "abnormal_shell_growth": {"ja": "甲羅の異常成長", "en": "Abnormal shell growth"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "abdominal_swelling": {"ja": "腹部膨満", "en": "Abdominal swelling"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "sunken_eyes": {"ja": "眼窩陥没", "en": "Sunken eyes"},
    "wrinkled_skin": {"ja": "しわのある皮膚", "en": "Wrinkled skin"},
    "decreased_skin_elasticity": {"ja": "皮膚弾力低下", "en": "Decreased skin elasticity"},
    "dry_mucous_membranes": {"ja": "粘膜乾燥", "en": "Dry mucous membranes"},
    "excessive_weight": {"ja": "過体重", "en": "Excessive weight"},
    "fat_deposits": {"ja": "脂肪沈着", "en": "Fat deposits"},
    "difficulty_moving": {"ja": "運動困難", "en": "Difficulty moving"},
    "stargazing": {"ja": "スターゲイジング", "en": "Stargazing"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "skin_hemorrhage": {"ja": "皮膚出血", "en": "Skin hemorrhage"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "petechia": {"ja": "点状出血", "en": "Petechiae"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "retained_spectacle": {"ja": "スペクタクル残留", "en": "Retained spectacle"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "bulging_eye": {"ja": "眼球突出", "en": "Bulging eye"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "cloacal_swelling": {"ja": "総排泄腔の腫脹", "en": "Cloacal swelling"},
    "tissue_prolapse": {"ja": "組織脱出", "en": "Tissue prolapse"},
    "gout_tophi": {"ja": "痛風結節", "en": "Gout tophi"},
    "bloody_urates": {"ja": "血性尿酸塩", "en": "Bloody urates"},
    "swollen_joints": {"ja": "関節腫脹", "en": "Swollen joints"},
    "joint_pain": {"ja": "関節痛", "en": "Joint pain"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "abnormal_posture": {"ja": "異常姿勢", "en": "Abnormal posture"},
    "ulcerated_mass": {"ja": "潰瘍化した腫瘤", "en": "Ulcerated mass"},
    "organ_enlargement": {"ja": "臓器肥大", "en": "Organ enlargement"},
    "dark_skin_mass": {"ja": "暗色の皮膚腫瘤", "en": "Dark skin mass"},
    "color_change": {"ja": "体色変化", "en": "Color change"},
    "hiding_behavior": {"ja": "隠れ行動", "en": "Hiding behavior"},
    "poor_body_condition": {"ja": "低体格スコア", "en": "Poor body condition"},
    "yellow_skin_patches": {"ja": "黄色の皮膚斑", "en": "Yellow skin patches"},
    "skin_discoloration": {"ja": "皮膚変色", "en": "Skin discoloration"},
    "skin_necrosis": {"ja": "皮膚壊死", "en": "Skin necrosis"},
    "tissue_swelling": {"ja": "組織の腫脹", "en": "Tissue swelling"},
    "slow_reflexes": {"ja": "反射低下", "en": "Slow reflexes"},
    "pain_response": {"ja": "疼痛反応", "en": "Pain response"},
    "granulomatous_lesions": {"ja": "肉芽腫性病変", "en": "Granulomatous lesions"},
    "stomatitis": {"ja": "口内炎", "en": "Stomatitis"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    """Analyze reptile symptoms and return suspected diseases.

    Parameters
    ----------
    symptoms:
        A list of symptom identifier strings.
    age_stage:
        Optional age stage descriptor.
    breed:
        Optional species/breed; included for interface compatibility.

    Returns
    -------
    dict
        Analysis result in the standard differential diagnosis format.
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
