"""Snake disease dictionary and analysis module.

This module defines a comprehensive list of diseases commonly seen in
captive and wild snakes (Serpentes) and exposes an ``analyze_symptoms``
function that leverages the generic species helper to produce differential
diagnosis results.

The information provided here is for educational purposes only and should
not replace professional veterinary diagnosis and treatment.
"""

from __future__ import annotations

from typing import Any, Dict, List

from . import prevalence_data
from .helpers import ADVICE, analyze_symptoms_generic, enrich_diseases

DISEASES: List[Dict[str, Any]] = [
    # ── Viral Diseases ───────────────────────────────────────────────────
    {
        "name": "Inclusion Body Disease (IBD)",
        "name_ja": "封入体病（IBD）",
        "symptoms": {"neurological_signs", "stargazing", "regurgitation", "anorexia", "head_tilt", "tremors", "paralysis", "loss_of_righting_reflex"},
        "description": "Fatal arenavirus infection primarily affecting boid snakes (boas and pythons), causing progressive neurological and gastrointestinal dysfunction.",
        "description_ja": "主にボア科のヘビに影響する致死性アレナウイルス感染症で、進行性の神経学的・消化器機能障害を引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_ibd", "liver_biopsy", "blood_smear", "complete_blood_count"],
    },
    {
        "name": "Paramyxovirus Infection",
        "name_ja": "パラミクソウイルス感染症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "neurological_signs", "open_mouth_breathing", "stargazing", "sudden_death"},
        "description": "Highly contagious viral infection causing severe pneumonia and neurological disease, especially in viperids and colubrids.",
        "description_ja": "特にクサリヘビ科やナミヘビ科で重篤な肺炎と神経疾患を引き起こす高度伝染性ウイルス感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_paramyxovirus", "hemagglutination_inhibition", "radiographs", "tracheal_wash"],
    },
    {
        "name": "Nidovirus Infection",
        "name_ja": "ニドウイルス感染症",
        "symptoms": {"respiratory_distress", "open_mouth_breathing", "mucus_in_mouth", "wheezing", "lethargy", "anorexia"},
        "description": "Viral respiratory infection increasingly recognized in ball pythons and other python species, causing proliferative pneumonia.",
        "description_ja": "ボールパイソンやその他のニシキヘビで認識が増えている増殖性肺炎を引き起こすウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_nidovirus", "oral_swab", "tracheal_wash", "radiographs"],
    },
    {
        "name": "Adenovirus Infection",
        "name_ja": "アデノウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "neurological_signs", "weight_loss", "diarrhea", "sudden_death"},
        "description": "Viral infection causing hepatitis and enteritis, often fatal in young snakes.",
        "description_ja": "肝炎と腸炎を引き起こすウイルス感染症で、幼蛇では致死的なことが多いです。",
        "urgency": "high",
        "recommended_tests": ["pcr_adenovirus", "liver_function_tests", "liver_biopsy"],
    },
    {
        "name": "Reovirus Infection",
        "name_ja": "レオウイルス感染症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "pneumonia_signs"},
        "description": "Viral respiratory pathogen that can cause pneumonia and tracheitis in snakes.",
        "description_ja": "ヘビに肺炎と気管炎を引き起こすウイルス性呼吸器病原体です。",
        "urgency": "high",
        "recommended_tests": ["pcr_reovirus", "tracheal_wash", "radiographs"],
    },
    {
        "name": "Sunshine Virus (Reptile Sunshinevirus)",
        "name_ja": "サンシャインウイルス感染症",
        "symptoms": {"neurological_signs", "stargazing", "tremors", "anorexia", "lethargy"},
        "description": "Emerging paramyxovirus-like pathogen causing neurological disease in pythons.",
        "description_ja": "ニシキヘビに神経疾患を引き起こすパラミクソウイルス様の新興病原体です。",
        "urgency": "high",
        "recommended_tests": ["pcr_sunshinevirus", "neurological_exam", "complete_blood_count"],
    },
    {
        "name": "Ophidian Herpesvirus Infection",
        "name_ja": "ヘビヘルペスウイルス感染症",
        "symptoms": {"mouth_lesions", "stomatitis", "nasal_discharge", "anorexia", "lethargy"},
        "description": "Herpesvirus causing stomatitis, esophagitis, and pneumonia in various snake species.",
        "description_ja": "各種ヘビに口内炎、食道炎、肺炎を引き起こすヘルペスウイルス感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_herpesvirus", "oral_swab", "biopsy"],
    },
    # ── Respiratory ──────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection (URI)",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"nasal_discharge", "wheezing", "open_mouth_breathing", "lethargy", "anorexia"},
        "description": "Bacterial or viral infection of the nasal passages and glottis, often from suboptimal temperatures.",
        "description_ja": "不適切な温度管理に関連する鼻腔・声門の細菌・ウイルス感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "culture_sensitivity", "physical_exam"],
    },
    {
        "name": "Pneumonia (Lower Respiratory Infection)",
        "name_ja": "肺炎（下部呼吸器感染症）",
        "symptoms": {"open_mouth_breathing", "respiratory_distress", "wheezing", "nasal_discharge", "lethargy", "anorexia", "mucus_in_mouth", "elevated_head_posture"},
        "description": "Severe bacterial, viral, or fungal infection of the lung, often progressing from untreated URI.",
        "description_ja": "未治療のURIから進行することの多い肺の重篤な細菌・ウイルス・真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "tracheal_wash", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "weight_loss"},
        "description": "Fungal infection of the respiratory tract by Aspergillus spp.",
        "description_ja": "アスペルギルス属真菌による呼吸器の真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "radiographs", "tracheal_wash"],
    },
    # ── Oral / Stomatitis ────────────────────────────────────────────────
    {
        "name": "Infectious Stomatitis (Mouth Rot)",
        "name_ja": "感染性口内炎（マウスロット）",
        "symptoms": {"mouth_lesions", "swollen_gums", "mucus_in_mouth", "anorexia", "drooling", "oral_hemorrhage", "facial_swelling"},
        "description": "Bacterial infection of the oral cavity with caseous exudate, tissue necrosis, and potential osteomyelitis of the jaw.",
        "description_ja": "乾酪性浸出液、組織壊死、顎の骨髄炎の可能性を伴う口腔の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "radiographs", "complete_blood_count"],
    },
    {
        "name": "Oral Abscess",
        "name_ja": "口腔膿瘍",
        "symptoms": {"mouth_lesions", "swelling", "facial_swelling", "anorexia"},
        "description": "Localized abscess in the oral cavity, often secondary to stomatitis or prey-related trauma.",
        "description_ja": "口内炎や餌による外傷に続発する口腔内の限局性膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "radiographs"],
    },
    # ── Parasitic ────────────────────────────────────────────────────────
    {
        "name": "Snake Mites (Ophionyssus natricis)",
        "name_ja": "ヘビダニ（オフィオニッスス）",
        "symptoms": {"excessive_soaking", "skin_irritation", "visible_mites", "lethargy", "anorexia", "dysecdysis", "rubbing_against_objects"},
        "description": "Ectoparasitic mite infestation; the most common external parasite in captive snakes.",
        "description_ja": "飼育下のヘビで最も一般的な外部寄生ダニの感染です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "mite_identification"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"regurgitation", "weight_loss", "body_swelling", "anorexia", "lethargy", "mid_body_swelling"},
        "description": "Chronic protozoal infection by Cryptosporidium serpentis causing hypertrophic gastritis, especially in snakes.",
        "description_ja": "クリプトスポリジウム・セルペンティスによる肥大性胃炎を引き起こす慢性原虫感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_cryptosporidium", "acid_fast_stain", "gastric_biopsy"],
    },
    {
        "name": "Amoebic Infection (Entamoeba invadens)",
        "name_ja": "アメーバ感染症",
        "symptoms": {"diarrhea", "bloody_stool", "anorexia", "weight_loss", "lethargy", "mucus_in_stool"},
        "description": "Fatal protozoal colitis caused by Entamoeba invadens; highly pathogenic in snakes.",
        "description_ja": "エンタメーバ・インバデンスによる致死的な原虫性大腸炎で、ヘビに高度に病原性があります。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_wet_mount", "pcr_entamoeba", "fecal_exam"],
    },
    {
        "name": "Internal Nematodes (Roundworms)",
        "name_ja": "内部線虫（回虫）感染",
        "symptoms": {"weight_loss", "anorexia", "regurgitation", "diarrhea", "lethargy"},
        "description": "Gastrointestinal roundworm infection including ascarids, strongylids, and rhabditids.",
        "description_ja": "回虫類、円虫類、桿線虫類を含む消化管の線虫感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam", "complete_blood_count"],
    },
    {
        "name": "Pentastomid Infection (Tongue Worms)",
        "name_ja": "舌虫症",
        "symptoms": {"respiratory_distress", "open_mouth_breathing", "nasal_discharge", "lethargy"},
        "description": "Internal parasitism by pentastomids affecting the respiratory tract, especially in wild-caught snakes.",
        "description_ja": "特に野生捕獲のヘビで呼吸器に影響する舌虫の寄生です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "endoscopy", "fecal_exam"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "マダニ寄生",
        "symptoms": {"visible_parasites", "skin_lesions", "anorexia", "lethargy", "anemia"},
        "description": "External tick parasitism, more common in wild-caught or outdoor-kept snakes.",
        "description_ja": "野生捕獲または屋外飼育のヘビに多い外部マダニ寄生です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "tick_identification", "complete_blood_count"],
    },
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "lethargy"},
        "description": "Intestinal protozoal infection by Eimeria or Isospora species.",
        "description_ja": "アイメリア属やイソスポラ属原虫による腸管の感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    # ── Skin / Integument ────────────────────────────────────────────────
    {
        "name": "Blister Disease (Vesicular Dermatitis)",
        "name_ja": "水疱症（水疱性皮膚炎）",
        "symptoms": {"blisters", "skin_lesions", "scale_discoloration", "lethargy", "anorexia"},
        "description": "Fluid-filled blisters on ventral scales from overly damp or unsanitary substrate conditions.",
        "description_ja": "過度に湿った不衛生な床材により腹部の鱗に水疱が形成される疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_exam", "culture_sensitivity", "husbandry_review"],
    },
    {
        "name": "Scale Rot (Ulcerative Dermatitis)",
        "name_ja": "スケイルロット（潰瘍性皮膚炎）",
        "symptoms": {"scale_discoloration", "skin_lesions", "foul_odor", "blisters", "skin_necrosis", "anorexia"},
        "description": "Progressive bacterial infection of ventral scales causing necrosis and ulceration.",
        "description_ja": "腹部の鱗の進行性細菌感染により壊死と潰瘍化を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["skin_culture", "skin_biopsy", "husbandry_review"],
    },
    {
        "name": "Dysecdysis (Retained Shed)",
        "name_ja": "脱皮不全",
        "symptoms": {"dysecdysis", "retained_skin", "skin_constriction", "lethargy", "anorexia", "dull_coloration"},
        "description": "Incomplete shedding caused by low humidity, dehydration, mites, or underlying illness.",
        "description_ja": "低湿度、脱水、ダニ、基礎疾患による不完全な脱皮です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review", "skin_exam"],
    },
    {
        "name": "Retained Spectacle (Retained Eye Cap)",
        "name_ja": "スペクタクル脱皮不全",
        "symptoms": {"cloudy_eyes", "retained_spectacle", "dysecdysis", "eye_swelling"},
        "description": "Failure to shed the spectacle (eye cap), which can layer and cause infection if untreated.",
        "description_ja": "スペクタクル（眼鏡）が脱皮されない状態で、未治療だと層が重なり感染を起こす可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "physical_exam", "husbandry_review"],
    },
    {
        "name": "Thermal Burns",
        "name_ja": "熱傷",
        "symptoms": {"skin_burns", "skin_lesions", "blisters", "scale_discoloration", "anorexia", "lethargy"},
        "description": "Burns from direct contact with unregulated heat sources (heat rocks, ceramic heaters, lamps).",
        "description_ja": "ヒートロック、セラミックヒーター、ランプなどの温度管理不良による火傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    {
        "name": "Dermatophytosis (Fungal Skin Infection)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"skin_lesions", "scale_discoloration", "dysecdysis", "crusty_patches"},
        "description": "Fungal infection of the skin by dermatophyte organisms.",
        "description_ja": "皮膚糸状菌による皮膚の真菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "skin_biopsy"],
    },
    {
        "name": "Bacterial Dermatitis",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_lesions", "skin_redness", "swelling", "foul_odor", "skin_necrosis"},
        "description": "Bacterial skin infection causing inflammation, ulceration, and potential septicemia.",
        "description_ja": "炎症、潰瘍化、敗血症の可能性を伴う皮膚の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Rostral Abrasion (Nose Rub)",
        "name_ja": "吻部擦過傷（ノーズラブ）",
        "symptoms": {"nose_abrasion", "facial_swelling", "skin_lesions", "anorexia"},
        "description": "Chronic abrasion of the snout from repeated rubbing against enclosure walls, especially common in wild-caught snakes.",
        "description_ja": "特に野生捕獲のヘビでケージ壁面への繰り返し擦り付けにより吻部が擦過傷を起こす状態です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    # ── Gastrointestinal ─────────────────────────────────────────────────
    {
        "name": "Regurgitation Syndrome",
        "name_ja": "吐出症候群",
        "symptoms": {"regurgitation", "anorexia", "weight_loss", "lethargy", "dehydration"},
        "description": "Chronic regurgitation of prey items from infectious agents, handling stress, incorrect temperatures, or oversized prey.",
        "description_ja": "感染因子、取り扱いストレス、不適切な温度、過大な餌による慢性的な吐出です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "radiographs", "husbandry_review", "pcr_cryptosporidium"],
    },
    {
        "name": "Gastrointestinal Impaction",
        "name_ja": "消化管閉塞",
        "symptoms": {"anorexia", "constipation", "lethargy", "abdominal_swelling", "straining"},
        "description": "GI blockage from ingested substrate or inability to digest large prey items at suboptimal temperatures.",
        "description_ja": "床材の摂取や不適切な温度での大きな餌の消化不良による消化管閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam", "ultrasound"],
    },
    {
        "name": "Gastroenteritis",
        "name_ja": "胃腸炎",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "regurgitation", "dehydration"},
        "description": "Inflammation of the GI tract from bacterial, viral, or parasitic causes.",
        "description_ja": "細菌、ウイルス、寄生虫による胃腸の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "jaundice", "abdominal_swelling"},
        "description": "Excessive fat accumulation in the liver from overfeeding or prolonged anorexia.",
        "description_ja": "過食や長期の食欲不振による肝臓への過剰な脂肪蓄積です。",
        "urgency": "high",
        "recommended_tests": ["liver_function_tests", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "weight_loss", "dehydration"},
        "description": "Salmonella bacterial infection; snakes are common asymptomatic carriers.",
        "description_ja": "サルモネラ菌感染症で、ヘビは一般的な無症候性保菌者です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "blood_culture", "complete_blood_count"],
    },
    # ── Metabolic / Nutritional ──────────────────────────────────────────
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"excessive_weight", "fat_deposits", "lethargy", "difficulty_moving", "scale_spreading"},
        "description": "Excess body fat from overfeeding, predisposing to hepatic lipidosis and reproductive issues.",
        "description_ja": "過食による過剰な体脂肪蓄積で、脂肪肝や繁殖障害のリスクがあります。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "body_condition_scoring", "dietary_review"],
    },
    {
        "name": "Anorexia (Non-specific)",
        "name_ja": "食欲不振（非特異的）",
        "symptoms": {"anorexia", "weight_loss", "lethargy"},
        "description": "Refusal to eat from stress, seasonal changes, pre-shed, gravidity, or underlying disease.",
        "description_ja": "ストレス、季節変化、脱皮前、妊娠、基礎疾患による摂食拒否です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "blood_chemistry", "husbandry_review", "fecal_exam"],
    },
    {
        "name": "Hypoglycemia",
        "name_ja": "低血糖症",
        "symptoms": {"weakness", "tremors", "seizures", "lethargy", "neurological_signs"},
        "description": "Dangerously low blood sugar, often in neonates or following prolonged anorexia.",
        "description_ja": "新生仔や長期の食欲不振後に見られる危険な血糖低下です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry"],
    },
    {
        "name": "Vitamin Deficiency (General)",
        "name_ja": "ビタミン欠乏症（一般）",
        "symptoms": {"anorexia", "lethargy", "weakness", "skin_lesions", "neurological_signs"},
        "description": "Nutritional deficiency from feeding a monotonous or incomplete diet.",
        "description_ja": "単調または不完全な食事による栄養欠乏です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review"],
    },
    # ── Dehydration / General ────────────────────────────────────────────
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"sunken_eyes", "wrinkled_skin", "decreased_skin_elasticity", "lethargy", "anorexia", "retained_skin"},
        "description": "Insufficient fluid intake or excessive loss; common in snakes without adequate water access.",
        "description_ja": "適切な水へのアクセスがないヘビに多い水分摂取不足または過度な喪失です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "packed_cell_volume"],
    },
    # ── Septicemia / Systemic ────────────────────────────────────────────
    {
        "name": "Septicemia (Blood Poisoning)",
        "name_ja": "敗血症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "petechia", "respiratory_distress", "scale_discoloration", "sudden_death"},
        "description": "Systemic bacterial infection, often secondary to bite wounds, thermal burns, or stomatitis.",
        "description_ja": "咬傷、熱傷、口内炎に続発する全身性細菌感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count", "blood_chemistry"],
    },
    {
        "name": "Subcutaneous Abscess",
        "name_ja": "皮下膿瘍",
        "symptoms": {"swelling", "firm_mass", "anorexia", "lethargy"},
        "description": "Encapsulated caseous abscess under the skin from bacterial infection.",
        "description_ja": "細菌感染による皮膚下の被包化された乾酪性膿瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "radiographs"],
    },
    # ── Eye Diseases ─────────────────────────────────────────────────────
    {
        "name": "Subspectacular Abscess",
        "name_ja": "スペクタクル下膿瘍",
        "symptoms": {"eye_swelling", "cloudy_eyes", "bulging_eye", "anorexia"},
        "description": "Abscess beneath the spectacle requiring surgical drainage, often from ascending stomatitis.",
        "description_ja": "口内炎からの上行感染によるスペクタクル下の膿瘍で、外科的排膿が必要です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "culture_sensitivity", "ultrasound"],
    },
    {
        "name": "Corneal Opacity / Injury",
        "name_ja": "角膜混濁・損傷",
        "symptoms": {"cloudy_eyes", "eye_discharge", "anorexia"},
        "description": "Damage or opacity of the spectacle or cornea from trauma or infection.",
        "description_ja": "外傷や感染によるスペクタクルまたは角膜の損傷・混濁です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain"],
    },
    {
        "name": "Conjunctivitis / Periocular Swelling",
        "name_ja": "結膜炎・眼周囲腫脹",
        "symptoms": {"swollen_eyes", "eye_discharge", "eye_swelling", "anorexia"},
        "description": "Inflammation around the eye from infection, retained spectacle, or systemic disease.",
        "description_ja": "感染、スペクタクル残留、全身性疾患による眼周囲の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "eye_culture"],
    },
    # ── Reproductive ─────────────────────────────────────────────────────
    {
        "name": "Egg Binding / Dystocia",
        "name_ja": "卵塞・難産",
        "symptoms": {"straining", "anorexia", "lethargy", "abdominal_swelling", "restlessness", "cloacal_swelling"},
        "description": "Inability to pass eggs or deliver live young, often from calcium deficiency or environmental factors.",
        "description_ja": "カルシウム欠乏や環境要因により卵の排出や出産ができない状態です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "blood_calcium"],
    },
    {
        "name": "Pre-ovulatory Follicular Stasis",
        "name_ja": "排卵前卵胞停滞",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "weight_loss"},
        "description": "Ovarian follicles fail to ovulate, becoming enlarged and risking coelomitis.",
        "description_ja": "卵巣卵胞が排卵されず肥大し、体腔炎のリスクがある状態です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_chemistry"],
    },
    {
        "name": "Post-ovulatory Egg Stasis (Slug Retention)",
        "name_ja": "排卵後卵停滞（スラグ残留）",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "straining"},
        "description": "Retention of infertile eggs (slugs) in the oviduct after ovulation.",
        "description_ja": "排卵後の不妊卵（スラグ）が卵管内に停滞する状態です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound"],
    },
    {
        "name": "Hemipenal Prolapse",
        "name_ja": "半陰茎脱出",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "swelling"},
        "description": "Prolapse of one or both hemipenes in male snakes, requiring prompt reduction.",
        "description_ja": "雄ヘビの片方または両方の半陰茎が脱出する状態で、迅速な整復が必要です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    # ── Prolapse ─────────────────────────────────────────────────────────
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "straining", "anorexia", "lethargy"},
        "description": "Protrusion of cloacal tissue, which may involve colon, oviduct, or other organs.",
        "description_ja": "結腸、卵管、その他の臓器が関与する可能性のある総排泄腔組織の突出です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    # ── Renal / Urinary ──────────────────────────────────────────────────
    {
        "name": "Renal Failure",
        "name_ja": "腎不全",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "gout_tophi", "edema"},
        "description": "Progressive kidney failure, often from chronic dehydration or aminoglycoside toxicity.",
        "description_ja": "慢性的な脱水やアミノグリコシド毒性による進行性の腎不全です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Articular Gout",
        "name_ja": "関節痛風",
        "symptoms": {"swollen_joints", "joint_pain", "lameness", "lethargy", "anorexia"},
        "description": "Uric acid crystal deposition in joints from renal dysfunction.",
        "description_ja": "腎機能障害による尿酸結晶の関節への沈着です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "radiographs", "joint_aspiration"],
    },
    {
        "name": "Visceral Gout",
        "name_ja": "内臓痛風",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "sudden_death"},
        "description": "Uric acid deposition on internal organs, often a terminal finding.",
        "description_ja": "内臓への尿酸沈着で、しばしば終末期所見です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    # ── Neurological ─────────────────────────────────────────────────────
    {
        "name": "Neurological Syndrome (Non-specific)",
        "name_ja": "神経学的症候群",
        "symptoms": {"neurological_signs", "stargazing", "head_tilt", "tremors", "seizures", "loss_of_righting_reflex", "circling"},
        "description": "Neurological dysfunction from IBD, paramyxovirus, metabolic, or toxic causes.",
        "description_ja": "IBD、パラミクソウイルス、代謝性、中毒性の原因による神経機能障害です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "pcr_ibd", "pcr_paramyxovirus", "blood_chemistry"],
    },
    {
        "name": "Spinal Osteopathy / Spondylosis",
        "name_ja": "脊椎骨症/脊椎症",
        "symptoms": {"paralysis", "difficulty_moving", "weakness", "abnormal_posture", "kinking"},
        "description": "Degenerative or infectious changes in spinal vertebrae causing pain and motor dysfunction.",
        "description_ja": "脊椎の変性または感染性変化により疼痛と運動機能障害を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ct_mri", "neurological_exam"],
    },
    # ── Neoplasia ────────────────────────────────────────────────────────
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"firm_mass", "skin_lesions", "ulcerated_mass", "weight_loss"},
        "description": "Malignant epithelial tumor, one of the more common neoplasms in snakes.",
        "description_ja": "ヘビで比較的多い上皮性の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"weight_loss", "anorexia", "lethargy", "swelling", "organ_enlargement"},
        "description": "Malignant lymphoid tumor that can affect multiple organ systems.",
        "description_ja": "複数の臓器系に影響し得るリンパ組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "complete_blood_count", "radiographs", "ultrasound"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"firm_mass", "swelling", "weight_loss", "lethargy"},
        "description": "Malignant connective tissue tumor occasionally seen in snakes.",
        "description_ja": "ヘビで時折見られる結合組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    # ── Organ Failure ────────────────────────────────────────────────────
    {
        "name": "Liver Failure (Hepatopathy)",
        "name_ja": "肝不全",
        "symptoms": {"anorexia", "lethargy", "jaundice", "weight_loss", "regurgitation"},
        "description": "Severe liver dysfunction from infectious, toxic, or metabolic causes.",
        "description_ja": "感染性、中毒性、代謝性の原因による重篤な肝機能障害です。",
        "urgency": "emergency",
        "recommended_tests": ["liver_function_tests", "blood_chemistry", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Cardiac Disease",
        "name_ja": "心疾患",
        "symptoms": {"lethargy", "edema", "respiratory_distress", "weakness", "sudden_death"},
        "description": "Heart disease including cardiomyopathy and pericardial effusion.",
        "description_ja": "心筋症や心嚢液貯留を含む心疾患です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiographs"],
    },
    # ── Miscellaneous ────────────────────────────────────────────────────
    {
        "name": "Venom Gland Infection / Abscess",
        "name_ja": "毒腺感染・膿瘍",
        "symptoms": {"facial_swelling", "swelling", "anorexia", "lethargy"},
        "description": "Infection or abscess of the venom gland in venomous snake species.",
        "description_ja": "毒蛇種における毒腺の感染または膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fine_needle_aspirate", "culture_sensitivity"],
    },
    {
        "name": "Trauma / Bite Wounds",
        "name_ja": "外傷・咬傷",
        "symptoms": {"skin_lesions", "bleeding", "swelling", "anorexia", "lethargy"},
        "description": "Physical injuries from prey items, cage mates, or handling accidents.",
        "description_ja": "餌動物、同居個体、取り扱い事故による物理的損傷です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Prey Bite Injury",
        "name_ja": "餌動物による咬傷",
        "symptoms": {"skin_lesions", "bleeding", "swelling", "anorexia"},
        "description": "Injuries from live rodent prey left unattended with the snake.",
        "description_ja": "ヘビと放置された生きた齧歯類の餌による損傷です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "culture_sensitivity"],
    },
    {
        "name": "Stress Syndrome",
        "name_ja": "ストレス症候群",
        "symptoms": {"anorexia", "lethargy", "hiding_behavior", "regurgitation", "defensive_behavior"},
        "description": "Chronic stress from improper husbandry, excessive handling, or inadequate hiding spots.",
        "description_ja": "不適切な飼育環境、過度の取り扱い、隠れ場所不足による慢性的ストレスです。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "physical_exam"],
    },
    {
        "name": "Toxicosis (Poisoning)",
        "name_ja": "中毒症",
        "symptoms": {"neurological_signs", "tremors", "seizures", "anorexia", "lethargy", "sudden_death"},
        "description": "Exposure to toxic substrates, cleaning chemicals, or contaminated prey items.",
        "description_ja": "有毒な床材、洗浄剤、汚染された餌への暴露です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Hyperthermia (Heat Stroke)",
        "name_ja": "高体温症",
        "symptoms": {"open_mouth_breathing", "lethargy", "weakness", "neurological_signs", "sudden_death"},
        "description": "Dangerously elevated body temperature from heat source malfunction or direct sun exposure.",
        "description_ja": "熱源の故障や直射日光による危険な体温上昇です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry"],
    },
    {
        "name": "Hypothermia",
        "name_ja": "低体温症",
        "symptoms": {"lethargy", "anorexia", "weakness", "slow_reflexes"},
        "description": "Sub-optimal body temperature suppressing digestion and immune function.",
        "description_ja": "消化と免疫機能を抑制する適切な温度を下回る体温です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "temperature_check", "husbandry_review"],
    },
    {
        "name": "Peritonitis / Coelomitis",
        "name_ja": "腹膜炎・体腔炎",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "pain_response", "respiratory_distress"},
        "description": "Inflammation of the coelomic cavity from ruptured eggs, organ perforation, or bacterial infection.",
        "description_ja": "卵の破裂、臓器穿孔、細菌感染による体腔の炎症です。",
        "urgency": "emergency",
        "recommended_tests": ["coelomic_fluid_analysis", "ultrasound", "blood_chemistry"],
    },
    {
        "name": "Osteomyelitis",
        "name_ja": "骨髄炎",
        "symptoms": {"swelling", "firm_mass", "anorexia", "lethargy"},
        "description": "Bacterial bone infection, often secondary to mouth rot or bite wounds.",
        "description_ja": "口腔内感染や咬傷に続発する骨の細菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "bone_culture", "complete_blood_count"],
    },
    {
        "name": "Chronic Malnutrition",
        "name_ja": "慢性栄養不良",
        "symptoms": {"weight_loss", "weakness", "lethargy", "anorexia", "poor_body_condition"},
        "description": "Long-term inadequate nutrition from improper feeding practices.",
        "description_ja": "不適切な給餌方法による長期的な栄養不良です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review", "physical_exam"],
    },
    {
        "name": "Mycobacteriosis",
        "name_ja": "マイコバクテリウム症",
        "symptoms": {"weight_loss", "anorexia", "skin_lesions", "lethargy", "granulomatous_lesions"},
        "description": "Chronic granulomatous infection by Mycobacterium spp. affecting multiple organs.",
        "description_ja": "マイコバクテリウム属菌による複数臓器に影響する慢性肉芽腫性感染症です。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "culture", "biopsy"],
    },

    # ── 追加疾患 (Additional Diseases) ──
    {
        "name": "Arenavirus Infection",
        "name_ja": "アレナウイルス感染症",
        "symptoms": {"anorexia", "neurological_signs", "regurgitation", "stargazing", "weight_loss"},
        "description": "Arenavirus associated with inclusion body disease-like syndrome in boid snakes.",
        "description_ja": "ボア科ヘビの封入体病様症候群に関連するアレナウイルス。",
        "urgency": "high",
        "recommended_tests": ["PCR_arenavirus", "blood_smear", "histopathology"],
    },
    {
        "name": "Ferlasvirus Infection",
        "name_ja": "フェルラスウイルス感染症",
        "symptoms": {"lethargy", "nasal_discharge", "oral_mucus", "pneumonia", "respiratory_distress"},
        "description": "Ferlasvirus causing fatal pneumonia in pythons and other snakes.",
        "description_ja": "ニシキヘビなどに致死的な肺炎を引き起こすフェルラスウイルス。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_ferlasvirus", "tracheal_wash", "radiography"],
    },
    {
        "name": "Boid Nidovirus (Ball Python Nidovirus)",
        "name_ja": "ボア科ニドウイルス（ボールパイソンニドウイルス）",
        "symptoms": {"anorexia", "open_mouth_breathing", "oral_mucus", "respiratory_distress", "wheezing"},
        "description": "Nidovirus causing severe and often fatal respiratory disease in ball pythons and boas.",
        "description_ja": "ボールパイソンやボアに重度で致死的な呼吸器疾患を引き起こすニドウイルス。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_nidovirus", "tracheal_wash", "oral_swab", "radiography"],
    },
    {
        "name": "Iridovirus Infection",
        "name_ja": "イリドウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "organ_failure", "skin_lesions", "sudden_death"},
        "description": "Iridovirus causing multi-organ disease and skin lesions.",
        "description_ja": "多臓器疾患と皮膚病変を引き起こすイリドウイルス。",
        "urgency": "high",
        "recommended_tests": ["PCR_iridovirus", "histopathology", "biopsy"],
    },
    {
        "name": "Ranavirus Infection",
        "name_ja": "ラナウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "oral_lesions", "skin_hemorrhage", "sudden_death"},
        "description": "Ranavirus causing systemic hemorrhagic disease in snakes.",
        "description_ja": "ヘビに全身性出血性疾患を引き起こすラナウイルス。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_ranavirus", "histopathology", "virus_isolation"],
    },
    {
        "name": "Poxvirus Infection",
        "name_ja": "ポックスウイルス感染症",
        "symptoms": {"crusty_nodules", "papular_dermatitis", "skin_lesions"},
        "description": "Poxvirus causing cutaneous nodular lesions in snakes.",
        "description_ja": "ヘビに皮膚結節性病変を引き起こすポックスウイルス。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology", "electron_microscopy"],
    },
    {
        "name": "Chlamydiosis",
        "name_ja": "クラミジア症",
        "symptoms": {"anorexia", "lethargy", "liver_enlargement", "respiratory_distress"},
        "description": "Chlamydia spp. causing hepatitis, pneumonia, and granulomatous disease.",
        "description_ja": "クラミジア属による肝炎、肺炎、肉芽腫性疾患。",
        "urgency": "high",
        "recommended_tests": ["PCR_chlamydia", "histopathology", "serology"],
    },
    {
        "name": "Pseudomonas Infection",
        "name_ja": "緑膿菌感染症",
        "symptoms": {"mouth_rot", "respiratory_distress", "septicemia", "skin_lesions"},
        "description": "Pseudomonas aeruginosa causing stomatitis, dermatitis, and pneumonia.",
        "description_ja": "緑膿菌による口内炎、皮膚炎、肺炎。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "gram_stain"],
    },
    {
        "name": "Aeromonas Infection",
        "name_ja": "エロモナス感染症",
        "symptoms": {"lethargy", "mouth_rot", "septicemia", "skin_lesions"},
        "description": "Aeromonas hydrophila causing skin infections and septicemia.",
        "description_ja": "エロモナス・ハイドロフィラによる皮膚感染と敗血症。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Citrobacter Infection",
        "name_ja": "シトロバクター感染症",
        "symptoms": {"lethargy", "mouth_rot", "septicemia", "skin_ulceration"},
        "description": "Citrobacter freundii causing septicemic cutaneous ulcerative disease.",
        "description_ja": "シトロバクター・フロインディによる敗血症性皮膚潰瘍性疾患。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing"],
    },
    {
        "name": "Mycoplasmosis",
        "name_ja": "マイコプラズマ症",
        "symptoms": {"lethargy", "nasal_discharge", "respiratory_distress", "upper_respiratory_signs"},
        "description": "Mycoplasma spp. causing chronic upper respiratory disease.",
        "description_ja": "マイコプラズマ属による慢性上部呼吸器疾患。",
        "urgency": "moderate",
        "recommended_tests": ["PCR_mycoplasma", "tracheal_wash", "bacterial_culture"],
    },
    {
        "name": "Pasteurellosis",
        "name_ja": "パスツレラ症",
        "symptoms": {"lethargy", "respiratory_distress", "septicemia", "sudden_death"},
        "description": "Pasteurella multocida from rodent bites or contaminated prey.",
        "description_ja": "齧歯類咬傷や汚染餌からのパスツレラ・ムルトシダ感染。",
        "urgency": "emergency",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing"],
    },
    {
        "name": "Erysipelas",
        "name_ja": "丹毒",
        "symptoms": {"lethargy", "septicemia", "skin_lesions", "sudden_death"},
        "description": "Erysipelothrix rhusiopathiae causing septicemia in snakes.",
        "description_ja": "エリシペロスリクス・ルシオパシエによるヘビの敗血症。",
        "urgency": "emergency",
        "recommended_tests": ["bacterial_culture", "histopathology"],
    },
    {
        "name": "Yellow Fungus Disease (CANV)",
        "name_ja": "黄色真菌症（CANV）",
        "symptoms": {"crusty_scales", "lethargy", "skin_ulceration", "weight_loss", "yellow_skin_lesions"},
        "description": "Chrysosporium anamorph of Nannizziopsis vriesii causing progressive dermatomycosis.",
        "description_ja": "ナンニチオプシス・ブリエシーのクリソスポリウム・アナモルフによる進行性皮膚真菌症。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "skin_biopsy", "histopathology"],
    },
    {
        "name": "Ophidiomyces ophiodiicola (Snake Fungal Disease - SFD)",
        "name_ja": "ヘビ真菌症（SFD）",
        "symptoms": {"crusty_scales", "dysecdysis", "eye_opacity", "facial_swelling", "skin_nodules"},
        "description": "Emerging fungal disease causing facial disfigurement and skin lesions in wild and captive snakes.",
        "description_ja": "野生・飼育ヘビに顔面変形と皮膚病変を引き起こす新興真菌疾患。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "skin_biopsy", "PCR_ophidiomyces"],
    },
    {
        "name": "Mucormycosis (Zygomycosis)",
        "name_ja": "ムコール症",
        "symptoms": {"granulomatous_lesions", "lethargy", "respiratory_distress", "skin_lesions"},
        "description": "Zygomycete fungal infection causing granulomatous disease.",
        "description_ja": "接合菌による肉芽腫性疾患。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "histopathology", "biopsy"],
    },
    {
        "name": "Hookworm Infection (Kalicephalus)",
        "name_ja": "鉤虫感染症（カリケファルス）",
        "symptoms": {"anemia", "bloody_stool", "lethargy", "weight_loss"},
        "description": "Kalicephalus hookworm causing blood loss and anemia.",
        "description_ja": "カリケファルス鉤虫による失血と貧血。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "CBC", "fecal_examination"],
    },
    {
        "name": "Rhabdias Lungworm",
        "name_ja": "ラブディアス肺虫症",
        "symptoms": {"mucus_in_mouth", "open_mouth_breathing", "respiratory_distress", "weight_loss"},
        "description": "Rhabdias spp. lungworm causing pneumonia.",
        "description_ja": "ラブディアス属肺虫による肺炎。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "tracheal_wash", "radiography"],
    },
    {
        "name": "Strongyloides Infection",
        "name_ja": "糞線虫症",
        "symptoms": {"dehydration", "diarrhea", "lethargy", "weight_loss"},
        "description": "Strongyloides spp. nematode causing enteritis, can auto-infect.",
        "description_ja": "糞線虫属による腸炎で、自家感染能力を持つ。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_examination", "larval_identification"],
    },
    {
        "name": "Acanthocephalan Infection",
        "name_ja": "鉤頭虫感染症",
        "symptoms": {"anorexia", "intestinal_obstruction", "lethargy", "weight_loss"},
        "description": "Thorny-headed worms causing intestinal inflammation and obstruction.",
        "description_ja": "鉤頭虫による腸管炎症と閉塞。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_examination", "radiography"],
    },
    {
        "name": "Cestode (Tapeworm) Infection",
        "name_ja": "条虫感染症",
        "symptoms": {"anorexia", "segments_in_stool", "weight_loss"},
        "description": "Tapeworm infestation from infected prey items.",
        "description_ja": "感染餌から寄生する条虫症。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "fecal_examination"],
    },
    {
        "name": "Flagellate Protozoal Infection",
        "name_ja": "鞭毛虫感染症",
        "symptoms": {"anorexia", "dehydration", "diarrhea", "weight_loss"},
        "description": "Trichomonas, Hexamita, or other flagellates causing GI disease.",
        "description_ja": "トリコモナス、ヘキサミタなどの鞭毛虫による消化器疾患。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_smear"],
    },
    {
        "name": "Ciliate Protozoal Overgrowth",
        "name_ja": "繊毛虫過増殖症",
        "symptoms": {"dehydration", "diarrhea", "weight_loss"},
        "description": "Overgrowth of normal ciliate fauna (Nyctotherus) causing enteritis.",
        "description_ja": "正常繊毛虫叢（ニクトテルス）の過増殖による腸炎。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_smear"],
    },
    {
        "name": "Sarcocystosis",
        "name_ja": "住肉胞子虫症",
        "symptoms": {"lethargy", "muscle_weakness", "sudden_death", "weight_loss"},
        "description": "Sarcocystis spp. causing myositis and systemic disease.",
        "description_ja": "住肉胞子虫属による筋炎と全身性疾患。",
        "urgency": "high",
        "recommended_tests": ["histopathology", "muscle_biopsy"],
    },
    {
        "name": "Chigger Mite Infestation (Trombiculidae)",
        "name_ja": "ツツガムシ寄生症",
        "symptoms": {"dysecdysis", "orange_red_clusters", "pruritus", "skin_lesions"},
        "description": "Trombiculid mite infestation common in wild-caught snakes.",
        "description_ja": "野生捕獲ヘビに多いツツガムシ寄生。",
        "urgency": "low",
        "recommended_tests": ["clinical_examination", "skin_scraping"],
    },
    {
        "name": "Leech Infestation",
        "name_ja": "ヒル寄生症",
        "symptoms": {"anemia", "skin_lesions", "visible_leeches"},
        "description": "External leech parasitism in semi-aquatic snakes.",
        "description_ja": "半水棲ヘビの外部ヒル寄生。",
        "urgency": "moderate",
        "recommended_tests": ["clinical_examination", "leech_removal", "CBC"],
    },
    {
        "name": "Hepatocellular Carcinoma",
        "name_ja": "肝細胞癌",
        "symptoms": {"anorexia", "lethargy", "liver_enlargement", "weight_loss"},
        "description": "Primary malignant liver tumor.",
        "description_ja": "原発性悪性肝腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy", "blood_chemistry", "histopathology"],
    },
    {
        "name": "Renal Cell Carcinoma",
        "name_ja": "腎細胞癌",
        "symptoms": {"anorexia", "lethargy", "posterior_body_swelling", "weight_loss"},
        "description": "Malignant kidney neoplasia causing posterior body enlargement.",
        "description_ja": "後体部腫大を引き起こす悪性腎腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy", "blood_chemistry"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ",
        "symptoms": {"dark_skin_masses", "skin_lesions", "ulcerated_masses"},
        "description": "Melanocyte-derived neoplasia on skin.",
        "description_ja": "皮膚のメラノサイト由来腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Chromatophoroma",
        "name_ja": "色素細胞腫",
        "symptoms": {"skin_color_changes", "skin_masses"},
        "description": "Neoplasia of chromatophore cells causing pigmented tumors.",
        "description_ja": "色素細胞由来の色素性腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Chondrosarcoma",
        "name_ja": "軟骨肉腫",
        "symptoms": {"body_swelling", "difficulty_moving", "weight_loss"},
        "description": "Malignant cartilage tumor.",
        "description_ja": "悪性軟骨腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "biopsy", "histopathology"],
    },
    {
        "name": "Ovarian / Testicular Neoplasia",
        "name_ja": "卵巣・精巣腫瘍",
        "symptoms": {"anorexia", "body_swelling", "lethargy", "reproductive_failure"},
        "description": "Gonadal neoplasia causing body swelling and reproductive dysfunction.",
        "description_ja": "生殖腺腫瘍による体幹腫脹と生殖機能障害。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "radiography", "biopsy"],
    },
    {
        "name": "Spinal Fracture / Vertebral Luxation",
        "name_ja": "脊椎骨折・椎体脱臼",
        "symptoms": {"kinking_of_body", "loss_of_movement_posterior", "paralysis"},
        "description": "Vertebral fracture or dislocation causing paresis or paralysis.",
        "description_ja": "椎骨骨折や脱臼による不全麻痺・麻痺。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "CT_scan", "neurological_examination"],
    },
    {
        "name": "Rib Fractures",
        "name_ja": "肋骨骨折",
        "symptoms": {"lethargy", "pain_on_handling", "swelling_at_site"},
        "description": "Fractured ribs from trauma or metabolic bone disease.",
        "description_ja": "外傷や代謝性骨疾患による肋骨骨折。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "blood_chemistry"],
    },
    {
        "name": "Substrate Impaction",
        "name_ja": "床材インパクション",
        "symptoms": {"anorexia", "body_swelling", "constipation", "regurgitation"},
        "description": "GI obstruction from ingestion of substrate materials.",
        "description_ja": "床材の摂取による消化管閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "contrast_study", "palpation"],
    },
    {
        "name": "Intestinal Volvulus / Intussusception",
        "name_ja": "腸捻転・腸重積",
        "symptoms": {"anorexia", "body_swelling", "regurgitation", "sudden_death"},
        "description": "Twisting or telescoping of intestine causing acute obstruction.",
        "description_ja": "腸管の捻転・嵌入による急性閉塞。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound", "surgical_exploration"],
    },
    {
        "name": "Egg-related Coelomitis",
        "name_ja": "卵関連体腔炎",
        "symptoms": {"anorexia", "body_swelling", "lethargy", "respiratory_distress"},
        "description": "Peritonitis from ruptured follicles or retained eggs.",
        "description_ja": "破裂卵胞や停滞卵による腹膜炎。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "coelomocentesis", "blood_chemistry"],
    },
    {
        "name": "Follicular Stasis (Chronic)",
        "name_ja": "慢性濾胞停滞",
        "symptoms": {"anorexia", "body_swelling", "lethargy"},
        "description": "Chronic retention of pre-ovulatory follicles.",
        "description_ja": "排卵前卵胞の慢性停滞。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "blood_chemistry"],
    },
    {
        "name": "Cloacal Calculi",
        "name_ja": "総排泄腔結石",
        "symptoms": {"cloacal_swelling", "constipation", "straining"},
        "description": "Stone-like concretions in the cloaca.",
        "description_ja": "総排泄腔内の結石。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "cloacal_examination"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"anorexia", "lethargy", "neurological_signs", "regurgitation"},
        "description": "Zinc poisoning from galvanized cage hardware.",
        "description_ja": "亜鉛メッキケージ金具からの亜鉛中毒。",
        "urgency": "high",
        "recommended_tests": ["blood_zinc_level", "radiography", "blood_chemistry"],
    },
    {
        "name": "Lead Toxicosis",
        "name_ja": "鉛中毒",
        "symptoms": {"anorexia", "neurological_signs", "regurgitation", "seizures"},
        "description": "Lead poisoning from ingestion of lead-containing materials.",
        "description_ja": "鉛含有物の摂取による中毒。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "radiography"],
    },
    {
        "name": "Ivermectin Toxicosis",
        "name_ja": "イベルメクチン中毒",
        "symptoms": {"neurological_signs", "paralysis", "tremors"},
        "description": "Ivermectin overdose causing neurological toxicity.",
        "description_ja": "イベルメクチン過剰投与による神経毒性。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_history", "neurological_examination"],
    },
    {
        "name": "Metronidazole Toxicosis",
        "name_ja": "メトロニダゾール中毒",
        "symptoms": {"anorexia", "neurological_signs", "vestibular_signs"},
        "description": "Metronidazole overdose causing CNS toxicity.",
        "description_ja": "メトロニダゾール過剰投与による中枢神経毒性。",
        "urgency": "high",
        "recommended_tests": ["clinical_history", "neurological_examination"],
    },
    {
        "name": "Hyperuricemia / Pre-gout",
        "name_ja": "高尿酸血症・痛風前状態",
        "symptoms": {"anorexia", "kidney_enlargement", "lethargy", "swollen_joints"},
        "description": "Elevated uric acid predisposing to gout.",
        "description_ja": "痛風前段階の高尿酸血症。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "uric_acid", "radiography"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"muscle_twitching", "seizures", "tremors", "weakness"},
        "description": "Low blood calcium causing neuromuscular dysfunction.",
        "description_ja": "低血中カルシウムによる神経筋機能障害。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "ionized_calcium"],
    },
    {
        "name": "Metabolic Bone Disease (MBD)",
        "name_ja": "代謝性骨疾患",
        "symptoms": {"bone_deformity", "fractures", "jaw_softening", "weakness"},
        "description": "Skeletal disease from Ca:P:D3 imbalance, less common in snakes than lizards.",
        "description_ja": "Ca:P:D3不均衡による骨疾患。ヘビではトカゲほど多くない。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "radiography", "dietary_review"],
    },
    {
        "name": "Vitamin A Deficiency",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"dysecdysis", "eye_swelling", "respiratory_distress", "skin_lesions"},
        "description": "Hypovitaminosis A causing squamous metaplasia of epithelial tissues.",
        "description_ja": "ビタミンA欠乏による上皮組織の扁平上皮化生。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_history", "blood_chemistry", "liver_vitamin_A"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"bone_weakness", "lethargy", "poor_feeding_response"},
        "description": "UV/D3 deficiency primarily affecting species that bask.",
        "description_ja": "主に日光浴する種に影響するUV/D3欠乏症。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "vitamin_D3_level", "husbandry_review"],
    },
    {
        "name": "Thiamine Deficiency",
        "name_ja": "チアミン欠乏症",
        "symptoms": {"neurological_signs", "seizures", "stargazing", "tremors"},
        "description": "Thiamine (B1) deficiency from feeding thiaminase-containing fish.",
        "description_ja": "チアミナーゼ含有魚の給餌によるチアミン（B1）欠乏症。",
        "urgency": "high",
        "recommended_tests": ["dietary_history", "response_to_thiamine"],
    },
    {
        "name": "Biotin Deficiency",
        "name_ja": "ビオチン欠乏症",
        "symptoms": {"dysecdysis", "poor_wound_healing", "skin_lesions"},
        "description": "Biotin deficiency from feeding raw egg whites or poor diet.",
        "description_ja": "生卵白の給餌や不適切な食餌によるビオチン欠乏症。",
        "urgency": "low",
        "recommended_tests": ["dietary_history", "response_to_supplementation"],
    },
    {
        "name": "Hypervitaminosis A",
        "name_ja": "ビタミンA過剰症",
        "symptoms": {"anorexia", "lethargy", "skin_sloughing"},
        "description": "Excessive vitamin A supplementation causing toxicity.",
        "description_ja": "ビタミンA過剰投与による中毒。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_history", "blood_chemistry"],
    },
    {
        "name": "Hypervitaminosis D3",
        "name_ja": "ビタミンD3過剰症",
        "symptoms": {"anorexia", "lethargy", "tissue_calcification"},
        "description": "Excessive vitamin D3 causing hypercalcemia.",
        "description_ja": "ビタミンD3過剰による高カルシウム血症。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ionized_calcium", "radiography"],
    },
    {
        "name": "Protein Deficiency / Malnutrition",
        "name_ja": "タンパク質欠乏・栄養不良",
        "symptoms": {"immunosuppression", "lethargy", "muscle_wasting", "weight_loss"},
        "description": "Inadequate nutrition causing muscle wasting and immune dysfunction.",
        "description_ja": "栄養不良による筋消耗と免疫機能障害。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_analysis", "blood_chemistry"],
    },
    {
        "name": "Chronic Dehydration",
        "name_ja": "慢性脱水",
        "symptoms": {"constipation", "lethargy", "sunken_eyes", "wrinkled_skin"},
        "description": "Long-term inadequate hydration causing renal compromise.",
        "description_ja": "長期的な水分不足による腎機能低下。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "PCV", "total_solids"],
    },
    {
        "name": "UV Light Deficiency",
        "name_ja": "紫外線不足症",
        "symptoms": {"bone_weakness", "immunosuppression", "lethargy", "poor_appetite"},
        "description": "Inadequate UVB for species that require it for D3 synthesis.",
        "description_ja": "D3合成にUVBが必要な種における紫外線不足。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "vitamin_D3_level", "husbandry_review"],
    },
    {
        "name": "Constriction Band Necrosis",
        "name_ja": "絞扼帯壊死",
        "symptoms": {"body_swelling", "tail_necrosis", "tissue_discoloration"},
        "description": "Necrosis from retained shed or debris constricting a body segment.",
        "description_ja": "脱皮残留物や異物による体幹部の絞扼壊死。",
        "urgency": "high",
        "recommended_tests": ["clinical_examination", "radiography"],
    },
    {
        "name": "Chronic Respiratory Disease Complex",
        "name_ja": "慢性呼吸器疾患複合",
        "symptoms": {"lethargy", "nasal_discharge", "open_mouth_breathing", "respiratory_distress"},
        "description": "Multi-factorial chronic respiratory disease.",
        "description_ja": "多因子性慢性呼吸器疾患。",
        "urgency": "high",
        "recommended_tests": ["tracheal_wash", "bacterial_culture", "PCR_panel", "radiography"],
    },
    {
        "name": "Anasarca (Generalized Edema)",
        "name_ja": "全身浮腫",
        "symptoms": {"anorexia", "generalized_swelling", "lethargy"},
        "description": "Generalized edema from cardiac, renal, or hepatic failure.",
        "description_ja": "心・腎・肝不全による全身浮腫。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound", "radiography"],
    },
    {
        "name": "Disseminated Granulomatous Disease",
        "name_ja": "播種性肉芽腫性疾患",
        "symptoms": {"lethargy", "organ_enlargement", "skin_nodules", "weight_loss"},
        "description": "Multi-organ granulomas from mycobacterial or fungal causes.",
        "description_ja": "マイコバクテリアや真菌による多臓器肉芽腫。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "acid_fast_stain", "fungal_culture"],
    },
    {
        "name": "Nephrocalcinosis",
        "name_ja": "腎石灰沈着症",
        "symptoms": {"anorexia", "lethargy", "posterior_body_swelling", "weight_loss"},
        "description": "Calcium deposition in kidneys from D3 excess or chronic renal disease.",
        "description_ja": "D3過剰や慢性腎疾患による腎臓へのカルシウム沈着。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "radiography", "ultrasound"],
    },
    {
        "name": "Hemolytic Anemia",
        "name_ja": "溶血性貧血",
        "symptoms": {"lethargy", "pale_mucous_membranes", "weakness"},
        "description": "Red blood cell destruction from parasites, toxins, or immune causes.",
        "description_ja": "寄生虫・毒素・免疫介在性原因による赤血球破壊。",
        "urgency": "high",
        "recommended_tests": ["CBC", "blood_smear", "blood_chemistry"],
    },
    {
        "name": "Hemoparasites (Blood Parasites)",
        "name_ja": "血液寄生虫症",
        "symptoms": {"anemia", "lethargy", "weight_loss"},
        "description": "Hemogregarines and other blood parasites.",
        "description_ja": "ヘモグレガリンなどの血液寄生虫。",
        "urgency": "moderate",
        "recommended_tests": ["blood_smear", "PCR_hemoparasite", "CBC"],
    },
    {
        "name": "Organ Prolapse (Gastric/Intestinal)",
        "name_ja": "臓器脱（胃・腸）",
        "symptoms": {"anorexia", "lethargy", "tissue_protruding_from_cloaca"},
        "description": "Prolapse of stomach or intestine through the cloaca.",
        "description_ja": "胃・腸の総排泄腔からの脱出。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_examination", "radiography"],
    },
    {
        "name": "Burns (Chemical)",
        "name_ja": "化学熱傷",
        "symptoms": {"anorexia", "lethargy", "skin_blistering", "skin_discoloration"},
        "description": "Chemical burns from contact with cleaning agents or substrate chemicals.",
        "description_ja": "清掃剤や床材化学物質との接触による化学熱傷。",
        "urgency": "high",
        "recommended_tests": ["clinical_examination", "wound_assessment", "bacterial_culture"],
    },
    {
        "name": "Drowning / Near-Drowning",
        "name_ja": "溺水・溺水未遂",
        "symptoms": {"cyanosis", "lethargy", "respiratory_distress", "unconsciousness"},
        "description": "Oxygen deprivation from near-drowning in water bowls or enclosures.",
        "description_ja": "水容器やケージ内での溺水による酸素欠乏。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_examination", "radiography"],
    },
    {
        "name": "Aural Abscess (Ear Infection)",
        "name_ja": "耳膿瘍",
        "symptoms": {"anorexia", "head_swelling", "lethargy"},
        "description": "Middle ear abscess, uncommon in snakes but reported.",
        "description_ja": "ヘビでは稀だが報告のある中耳膿瘍。",
        "urgency": "moderate",
        "recommended_tests": ["clinical_examination", "radiography", "bacterial_culture"],
    },
    {
        "name": "Corneal Disease",
        "name_ja": "角膜疾患",
        "symptoms": {"eye_opacity", "eye_swelling", "retained_spectacle"},
        "description": "Corneal infection, ulceration, or spectacle disease.",
        "description_ja": "角膜感染、潰瘍、または眼鏡鱗疾患。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_examination", "cytology", "bacterial_culture"],
    },


    # ── 追加疾患2 (Additional Diseases 2) ──
    {
        "name": "Proliferative Osteoarthritis",
        "name_ja": "増殖性骨関節症",
        "symptoms": {"body_swelling", "difficulty_moving", "lethargy"},
        "description": "Degenerative joint disease with bone proliferation.",
        "description_ja": "骨増殖を伴う変性性関節疾患。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "blood_chemistry"],
    },
    {
        "name": "Photosensitization Dermatitis",
        "name_ja": "光線過敏性皮膚炎",
        "symptoms": {"dermatitis", "skin_blistering", "skin_redness"},
        "description": "Skin damage from photosensitizing compounds with UV exposure.",
        "description_ja": "光増感物質とUV照射による皮膚損傷。",
        "urgency": "moderate",
        "recommended_tests": ["skin_biopsy", "husbandry_review"],
    },
    {
        "name": "Abdominal Wall Hernia",
        "name_ja": "腹壁ヘルニア",
        "symptoms": {"anorexia", "body_swelling", "soft_mass"},
        "description": "Protrusion of coelomic contents through body wall defect.",
        "description_ja": "体壁欠損部からの体腔内容物の脱出。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "ultrasound"],
    },
    {
        "name": "Papillomavirus Infection",
        "name_ja": "パピローマウイルス感染症",
        "symptoms": {"skin_papillomas", "wart_like_growths"},
        "description": "Papillomavirus causing papillomatous skin growths.",
        "description_ja": "パピローマウイルスによる皮膚乳頭腫性増殖。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Bacterial Pneumonia (Chronic)",
        "name_ja": "慢性細菌性肺炎",
        "symptoms": {"anorexia", "lethargy", "mucus_in_mouth", "respiratory_distress", "weight_loss"},
        "description": "Chronic bacterial lung infection from poor husbandry.",
        "description_ja": "不適切な飼育環境に起因する慢性細菌性肺感染。",
        "urgency": "high",
        "recommended_tests": ["tracheal_wash_culture", "sensitivity_testing", "radiography"],
    },
    {
        "name": "Dermal Mycosis (Non-CANV/SFD)",
        "name_ja": "皮膚真菌症（非CANV/SFD型）",
        "symptoms": {"crusty_scales", "discoloration", "skin_lesions"},
        "description": "Fungal skin infection from organisms other than CANV or Ophidiomyces.",
        "description_ja": "CANVやオフィディオミセス以外の真菌による皮膚感染。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_biopsy"],
    },

]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "neurological_signs": {"ja": "神経学的徴候", "en": "Neurological signs"},
    "stargazing": {"ja": "スターゲイジング", "en": "Stargazing"},
    "regurgitation": {"ja": "吐出", "en": "Regurgitation"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "paralysis": {"ja": "麻痺", "en": "Paralysis"},
    "loss_of_righting_reflex": {"ja": "正位反射消失", "en": "Loss of righting reflex"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory distress"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "open_mouth_breathing": {"ja": "口を開けて呼吸", "en": "Open-mouth breathing"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "mucus_in_mouth": {"ja": "口腔内粘液", "en": "Mucus in mouth"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "pneumonia_signs": {"ja": "肺炎症状", "en": "Pneumonia signs"},
    "mouth_lesions": {"ja": "口腔内病変", "en": "Mouth lesions"},
    "stomatitis": {"ja": "口内炎", "en": "Stomatitis"},
    "elevated_head_posture": {"ja": "頭部の挙上姿勢", "en": "Elevated head posture"},
    "swollen_gums": {"ja": "歯肉腫脹", "en": "Swollen gums"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "oral_hemorrhage": {"ja": "口腔出血", "en": "Oral hemorrhage"},
    "facial_swelling": {"ja": "顔面腫脹", "en": "Facial swelling"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "excessive_soaking": {"ja": "過度の水浸し", "en": "Excessive soaking"},
    "skin_irritation": {"ja": "皮膚の刺激感", "en": "Skin irritation"},
    "visible_mites": {"ja": "肉眼で確認できるダニ", "en": "Visible mites"},
    "dysecdysis": {"ja": "脱皮不全", "en": "Dysecdysis"},
    "rubbing_against_objects": {"ja": "物に擦りつける行動", "en": "Rubbing against objects"},
    "body_swelling": {"ja": "体の腫脹", "en": "Body swelling"},
    "mid_body_swelling": {"ja": "体中央部の腫脹", "en": "Mid-body swelling"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "mucus_in_stool": {"ja": "粘液便", "en": "Mucus in stool"},
    "visible_parasites": {"ja": "肉眼で確認できる寄生虫", "en": "Visible parasites"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "blisters": {"ja": "水疱", "en": "Blisters"},
    "scale_discoloration": {"ja": "鱗の変色", "en": "Scale discoloration"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "skin_necrosis": {"ja": "皮膚壊死", "en": "Skin necrosis"},
    "retained_skin": {"ja": "残皮", "en": "Retained skin"},
    "skin_constriction": {"ja": "皮膚の絞扼", "en": "Skin constriction"},
    "dull_coloration": {"ja": "体色のくすみ", "en": "Dull coloration"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "retained_spectacle": {"ja": "スペクタクル残留", "en": "Retained spectacle"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "skin_burns": {"ja": "皮膚の火傷", "en": "Skin burns"},
    "crusty_patches": {"ja": "痂皮性斑", "en": "Crusty patches"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "nose_abrasion": {"ja": "吻部の擦過傷", "en": "Nose abrasion"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "abdominal_swelling": {"ja": "腹部膨満", "en": "Abdominal swelling"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "excessive_weight": {"ja": "過体重", "en": "Excessive weight"},
    "fat_deposits": {"ja": "脂肪沈着", "en": "Fat deposits"},
    "difficulty_moving": {"ja": "運動困難", "en": "Difficulty moving"},
    "scale_spreading": {"ja": "鱗の広がり", "en": "Scale spreading"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "seizures": {"ja": "発作", "en": "Seizures"},
    "sunken_eyes": {"ja": "眼窩陥没", "en": "Sunken eyes"},
    "wrinkled_skin": {"ja": "しわのある皮膚", "en": "Wrinkled skin"},
    "decreased_skin_elasticity": {"ja": "皮膚弾力低下", "en": "Decreased skin elasticity"},
    "skin_hemorrhage": {"ja": "皮膚出血", "en": "Skin hemorrhage"},
    "petechia": {"ja": "点状出血", "en": "Petechiae"},
    "firm_mass": {"ja": "硬い腫瘤", "en": "Firm mass"},
    "bulging_eye": {"ja": "眼球突出", "en": "Bulging eye"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "swollen_eyes": {"ja": "眼腫脹", "en": "Swollen eyes"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "cloacal_swelling": {"ja": "総排泄腔の腫脹", "en": "Cloacal swelling"},
    "tissue_prolapse": {"ja": "組織脱出", "en": "Tissue prolapse"},
    "gout_tophi": {"ja": "痛風結節", "en": "Gout tophi"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "swollen_joints": {"ja": "関節腫脹", "en": "Swollen joints"},
    "joint_pain": {"ja": "関節痛", "en": "Joint pain"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "abnormal_posture": {"ja": "異常姿勢", "en": "Abnormal posture"},
    "kinking": {"ja": "体のキンク（折れ曲がり）", "en": "Kinking"},
    "ulcerated_mass": {"ja": "潰瘍化した腫瘤", "en": "Ulcerated mass"},
    "organ_enlargement": {"ja": "臓器肥大", "en": "Organ enlargement"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "hiding_behavior": {"ja": "隠れ行動", "en": "Hiding behavior"},
    "defensive_behavior": {"ja": "防御行動", "en": "Defensive behavior"},
    "poor_body_condition": {"ja": "低体格スコア", "en": "Poor body condition"},
    "slow_reflexes": {"ja": "反射低下", "en": "Slow reflexes"},
    "pain_response": {"ja": "疼痛反応", "en": "Pain response"},
    "granulomatous_lesions": {"ja": "肉芽腫性病変", "en": "Granulomatous lesions"},

    # --- 追加症状 (DISEASES内で使用されている未登録項目) ---
    "bone_deformity": {"ja": "骨変形", "en": "Bone deformity"},
    "bone_weakness": {"ja": "骨脆弱", "en": "Bone weakness"},
    "crusty_nodules": {"ja": "Crusty Nodules", "en": "Crusty Nodules"},
    "crusty_scales": {"ja": "Crusty Scales", "en": "Crusty Scales"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    "dark_skin_masses": {"ja": "暗色皮膚腫瘤", "en": "Dark skin masses"},
    "dermatitis": {"ja": "皮膚炎", "en": "Dermatitis"},
    "discoloration": {"ja": "Discoloration", "en": "Discoloration"},
    "eye_opacity": {"ja": "Eye Opacity", "en": "Eye Opacity"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "generalized_swelling": {"ja": "Generalized Swelling", "en": "Generalized Swelling"},
    "head_swelling": {"ja": "Head Swelling", "en": "Head Swelling"},
    "immunosuppression": {"ja": "免疫抑制", "en": "Immunosuppression"},
    "intestinal_obstruction": {"ja": "腸閉塞", "en": "Intestinal obstruction"},
    "jaw_softening": {"ja": "顎軟化", "en": "Jaw softening"},
    "kidney_enlargement": {"ja": "Kidney Enlargement", "en": "Kidney Enlargement"},
    "kinking_of_body": {"ja": "Kinking Of Body", "en": "Kinking Of Body"},
    "liver_enlargement": {"ja": "肝臓腫大", "en": "Liver enlargement"},
    "loss_of_movement_posterior": {"ja": "Loss Of Movement Posterior", "en": "Loss Of Movement Posterior"},
    "mouth_rot": {"ja": "Mouth Rot", "en": "Mouth Rot"},
    "muscle_twitching": {"ja": "Muscle Twitching", "en": "Muscle Twitching"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "muscle_weakness": {"ja": "筋力低下", "en": "Muscle weakness"},
    "oral_lesions": {"ja": "口腔内病変", "en": "Oral lesions"},
    "oral_mucus": {"ja": "Oral Mucus", "en": "Oral Mucus"},
    "orange_red_clusters": {"ja": "Orange Red Clusters", "en": "Orange Red Clusters"},
    "organ_failure": {"ja": "Organ Failure", "en": "Organ Failure"},
    "pain_on_handling": {"ja": "Pain On Handling", "en": "Pain On Handling"},
    "pale_mucous_membranes": {"ja": "粘膜蒼白", "en": "Pale mucous membranes"},
    "papular_dermatitis": {"ja": "Papular Dermatitis", "en": "Papular Dermatitis"},
    "pneumonia": {"ja": "Pneumonia", "en": "Pneumonia"},
    "poor_appetite": {"ja": "食欲減退", "en": "Poor appetite"},
    "poor_feeding_response": {"ja": "Poor Feeding Response", "en": "Poor Feeding Response"},
    "poor_wound_healing": {"ja": "Poor Wound Healing", "en": "Poor Wound Healing"},
    "posterior_body_swelling": {"ja": "Posterior Body Swelling", "en": "Posterior Body Swelling"},
    "pruritus": {"ja": "Pruritus", "en": "Pruritus"},
    "reproductive_failure": {"ja": "Reproductive Failure", "en": "Reproductive Failure"},
    "segments_in_stool": {"ja": "Segments In Stool", "en": "Segments In Stool"},
    "septicemia": {"ja": "敗血症", "en": "Septicemia"},
    "skin_blistering": {"ja": "Skin Blistering", "en": "Skin Blistering"},
    "skin_color_changes": {"ja": "Skin Color Changes", "en": "Skin Color Changes"},
    "skin_discoloration": {"ja": "皮膚変色", "en": "Skin discoloration"},
    "skin_masses": {"ja": "皮膚腫瘤", "en": "Skin masses"},
    "skin_nodules": {"ja": "皮膚結節", "en": "Skin nodules"},
    "skin_papillomas": {"ja": "皮膚乳頭腫", "en": "Skin papillomas"},
    "skin_sloughing": {"ja": "Skin Sloughing", "en": "Skin Sloughing"},
    "skin_ulceration": {"ja": "皮膚潰瘍化", "en": "Skin ulceration"},
    "soft_mass": {"ja": "Soft Mass", "en": "Soft Mass"},

    "swelling_at_site": {"ja": "Swelling At Site", "en": "Swelling At Site"},
    "tail_necrosis": {"ja": "Tail Necrosis", "en": "Tail Necrosis"},
    "tissue_calcification": {"ja": "Tissue Calcification", "en": "Tissue Calcification"},
    "tissue_discoloration": {"ja": "Tissue Discoloration", "en": "Tissue Discoloration"},
    "tissue_protruding_from_cloaca": {"ja": "Tissue Protruding From Cloaca", "en": "Tissue Protruding From Cloaca"},
    "ulcerated_masses": {"ja": "Ulcerated Masses", "en": "Ulcerated Masses"},
    "unconsciousness": {"ja": "Unconsciousness", "en": "Unconsciousness"},
    "upper_respiratory_signs": {"ja": "Upper Respiratory Signs", "en": "Upper Respiratory Signs"},
    "vestibular_signs": {"ja": "Vestibular Signs", "en": "Vestibular Signs"},
    "visible_leeches": {"ja": "Visible Leeches", "en": "Visible Leeches"},
    "wart_like_growths": {"ja": "疣贅様増殖", "en": "Wart-like growths"},
    "yellow_skin_lesions": {"ja": "Yellow Skin Lesions", "en": "Yellow Skin Lesions"},
}


# Enrich DISEASES with content from diseases_all_species.json
enrich_diseases(DISEASES, "Snake")


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None, lab_values: dict | None = None, gender=None) -> Dict[str, Any]:
    """Analyze snake symptoms and return suspected diseases.

    Parameters
    ----------
    symptoms:
        A list of symptom identifier strings.
    age_stage:
        Optional age stage descriptor.
    breed:
        Optional species/morph; included for interface compatibility.

    Returns
    -------
    dict
        Analysis result in the standard differential diagnosis format.
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species, lab_values=lab_values, gender=gender, prevalence_map=prevalence_data.SPECIES_PREVALENCE.get("snake", {}))
