"""Sugar glider disease dictionary and symptom analysis module.

Sugar gliders (Petaurus breviceps) are small marsupials kept as exotic pets.
They have unique nutritional needs and are highly prone to metabolic bone
disease (MBD) from calcium/phosphorus imbalance.  Stress-related self-
mutilation, nutritional deficiency, and parasitic infections are also common.
This module catalogues 50+ diseases across nutritional, dermatological,
respiratory, gastrointestinal, ophthalmological, neurological, reproductive,
renal, parasitic, dental, and neoplastic categories.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

# ---------------------------------------------------------------------------
# Disease database
# ---------------------------------------------------------------------------

DISEASES: List[Dict[str, Any]] = [
    # ── Nutritional / Metabolic ────────────────────────────────────────────
    {
        "name": "Metabolic Bone Disease (MBD)",
        "name_ja": "代謝性骨疾患（MBD）",
        "symptoms": {"weakness", "bone_deformity", "seizures", "hind_leg_paralysis", "fractures"},
        "description": "Extremely common condition caused by calcium/phosphorus imbalance or vitamin D3 deficiency leading to soft, fragile bones.",
        "description_ja": "カルシウム・リン比の不均衡やビタミンD3欠乏により骨が脆弱化する非常に多い疾患。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium", "blood_phosphorus", "radiographs", "blood_chemistry"],
    },
    {
        "name": "Calcium Deficiency (Hypocalcemia)",
        "name_ja": "カルシウム欠乏症（低カルシウム血症）",
        "symptoms": {"seizures", "tremors", "weakness", "lethargy", "muscle_twitching"},
        "description": "Acute low blood calcium causing tremors and seizures; often precedes full MBD.",
        "description_ja": "急性の血中カルシウム低下により振戦やてんかん発作が起こる。MBDに先行することが多い。",
        "urgency": "emergency",
        "recommended_tests": ["blood_calcium", "ionized_calcium", "blood_chemistry"],
    },
    {
        "name": "Malnutrition / Nutritional Deficiency",
        "name_ja": "栄養不良・栄養欠乏症",
        "symptoms": {"weight_loss", "lethargy", "rough_coat", "weakness", "poor_appetite"},
        "description": "General nutritional deficiency from improper diet lacking essential vitamins and minerals.",
        "description_ja": "必須ビタミンやミネラルを欠く不適切な食事による全般的な栄養不良。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "physical_exam", "dietary_review"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"weight_gain", "reduced_activity", "lethargy", "difficulty_gliding"},
        "description": "Excessive body weight from overfeeding high-fat or high-sugar foods.",
        "description_ja": "高脂肪・高糖質食の過剰摂取による体重過多。",
        "urgency": "moderate",
        "recommended_tests": ["body_condition_score", "blood_chemistry", "blood_glucose"],
    },
    {
        "name": "Vitamin A Deficiency",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"eye_discharge", "poor_appetite", "rough_coat", "skin_infections", "lethargy"},
        "description": "Insufficient vitamin A causing skin and eye problems.",
        "description_ja": "ビタミンA不足による皮膚・眼の異常。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review", "physical_exam"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"weakness", "bone_deformity", "lethargy", "poor_appetite"},
        "description": "Lack of vitamin D3 impairing calcium absorption; contributes to MBD.",
        "description_ja": "ビタミンD3欠乏によりカルシウム吸収が阻害される。MBDの一因。",
        "urgency": "moderate",
        "recommended_tests": ["blood_calcium", "vitamin_D_level", "radiographs"],
    },
    {
        "name": "Hypoglycemia",
        "name_ja": "低血糖症",
        "symptoms": {"seizures", "tremors", "weakness", "collapse", "disorientation"},
        "description": "Dangerously low blood sugar from fasting, stress, or inadequate diet.",
        "description_ja": "絶食、ストレス、不適切な食事による危険な低血糖。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "physical_exam"],
    },
    {
        "name": "Protein Deficiency",
        "name_ja": "タンパク質欠乏症",
        "symptoms": {"weight_loss", "muscle_wasting", "rough_coat", "lethargy", "poor_wound_healing"},
        "description": "Insufficient dietary protein causing muscle wasting and poor coat condition.",
        "description_ja": "食事中のタンパク質不足による筋肉減少と被毛状態の悪化。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "total_protein", "dietary_review"],
    },
    {
        "name": "Iron Storage Disease (Hemochromatosis)",
        "name_ja": "鉄過剰症（ヘモクロマトーシス）",
        "symptoms": {"lethargy", "weight_loss", "distended_abdomen", "jaundice"},
        "description": "Excessive iron accumulation in organs, particularly the liver.",
        "description_ja": "臓器、特に肝臓への過剰な鉄蓄積。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_enzymes", "serum_iron", "liver_biopsy"],
    },
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"lethargy", "sunken_eyes", "skin_tenting", "reduced_activity", "dry_mucous_membranes"},
        "description": "Fluid deficit from inadequate water intake or illness.",
        "description_ja": "水分摂取不足や疾病による体液の不足。",
        "urgency": "moderate",
        "recommended_tests": ["skin_turgor_test", "blood_work", "physical_exam"],
    },

    # ── Self-mutilation / Behavioral ───────────────────────────────────────
    {
        "name": "Self-mutilation",
        "name_ja": "自傷行為",
        "symptoms": {"self_chewing", "open_wounds", "hair_loss", "bleeding", "stress_behavior"},
        "description": "Compulsive chewing or biting of own body, often tail, limbs, or genitals, triggered by loneliness, stress, or pain.",
        "description_ja": "孤独、ストレス、痛みにより尻尾や四肢、生殖器を強迫的に噛む自傷行為。",
        "urgency": "high",
        "recommended_tests": ["behavioral_assessment", "physical_exam", "pain_evaluation"],
    },
    {
        "name": "Stress-related Alopecia",
        "name_ja": "ストレス性脱毛",
        "symptoms": {"hair_loss", "over_grooming", "stress_behavior", "patchy_fur"},
        "description": "Hair loss from chronic stress, boredom, or improper social housing.",
        "description_ja": "慢性的なストレス、退屈、不適切な社会的飼育環境による脱毛。",
        "urgency": "low",
        "recommended_tests": ["behavioral_assessment", "skin_scraping", "fungal_culture"],
    },
    {
        "name": "Depression / Stress Syndrome",
        "name_ja": "うつ・ストレス症候群",
        "symptoms": {"lethargy", "poor_appetite", "reduced_activity", "stress_behavior", "self_chewing"},
        "description": "Behavioral syndrome in isolated or stressed gliders manifesting as inactivity and anorexia.",
        "description_ja": "孤立やストレス下のグライダーに見られる不活発・食欲不振を主徴とする行動症候群。",
        "urgency": "moderate",
        "recommended_tests": ["behavioral_assessment", "physical_exam", "blood_work"],
    },

    # ── Dermatological ─────────────────────────────────────────────────────
    {
        "name": "Skin Abscess",
        "name_ja": "皮膚膿瘍",
        "symptoms": {"swelling", "discharge", "pain", "lethargy", "fever"},
        "description": "Localized pocket of infection under the skin, often from bite wounds or self-mutilation.",
        "description_ja": "咬傷や自傷による皮下の局所的な感染巣。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "cytology", "physical_exam"],
    },
    {
        "name": "Dermatitis (Bacterial Skin Infection)",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_redness", "discharge", "hair_loss", "crusty_skin", "itching"},
        "description": "Bacterial infection of the skin causing redness, crusting, and hair loss.",
        "description_ja": "細菌感染による皮膚の発赤、痂皮形成、脱毛。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "bacterial_culture", "cytology"],
    },
    {
        "name": "Ringworm (Dermatophytosis)",
        "name_ja": "皮膚糸状菌症",
        "symptoms": {"circular_lesions", "hair_loss", "crusty_skin", "itching"},
        "description": "Fungal skin infection causing characteristic ring-shaped patches of hair loss.",
        "description_ja": "真菌による皮膚感染症で特徴的な円形の脱毛斑が生じる。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "wood_lamp"],
    },
    {
        "name": "Scent Gland Infection",
        "name_ja": "臭腺感染症",
        "symptoms": {"swelling", "discharge", "odor", "hair_loss", "skin_redness"},
        "description": "Infection of the frontal or cloacal scent glands, common in intact males.",
        "description_ja": "前頭部や総排泄腔の臭腺の感染。未去勢の雄に多い。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "cytology", "physical_exam"],
    },

    # ── Parasitic ──────────────────────────────────────────────────────────
    {
        "name": "Giardiasis",
        "name_ja": "ジアルジア症",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "bloating", "lethargy"},
        "description": "Protozoal intestinal infection causing chronic diarrhea and malabsorption.",
        "description_ja": "ジアルジア原虫による腸管感染で慢性的な下痢と吸収不良を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "giardia_antigen_test", "fecal_smear"],
    },
    {
        "name": "Coccidiosis",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "bloody_stool", "weight_loss", "dehydration", "lethargy"},
        "description": "Protozoal infection causing bloody diarrhea, especially in stressed or young gliders.",
        "description_ja": "コクシジウム原虫による感染で、ストレス下や若齢のグライダーに血便を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["fecal_flotation", "fecal_smear"],
    },
    {
        "name": "Mite Infestation (Sarcoptic / Demodex)",
        "name_ja": "ダニ感染症",
        "symptoms": {"itching", "hair_loss", "crusty_skin", "scaly_skin", "scratching"},
        "description": "Ectoparasitic mites causing intense itching and skin irritation.",
        "description_ja": "外部寄生ダニによる激しいかゆみと皮膚の刺激。",
        "urgency": "moderate",
        "recommended_tests": ["skin_scraping", "microscopy"],
    },
    {
        "name": "Flea Infestation",
        "name_ja": "ノミ寄生症",
        "symptoms": {"itching", "scratching", "hair_loss", "skin_redness", "flea_dirt"},
        "description": "Flea parasitism causing pruritus and potential anemia in small gliders.",
        "description_ja": "ノミの寄生によるかゆみと小型グライダーでは貧血の可能性。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "flea_comb", "skin_scraping"],
    },
    {
        "name": "Intestinal Worms (Helminths)",
        "name_ja": "腸内寄生虫症",
        "symptoms": {"diarrhea", "weight_loss", "bloating", "rough_coat", "visible_worms_in_stool"},
        "description": "Roundworm or tapeworm infestation of the gastrointestinal tract.",
        "description_ja": "回虫または条虫による消化管への寄生。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_flotation", "fecal_smear"],
    },
    {
        "name": "Toxoplasmosis",
        "name_ja": "トキソプラズマ症",
        "symptoms": {"lethargy", "poor_appetite", "respiratory_distress", "disorientation", "seizures"},
        "description": "Protozoal infection that can cause systemic disease in sugar gliders.",
        "description_ja": "トキソプラズマ原虫による全身性疾患。",
        "urgency": "high",
        "recommended_tests": ["serology", "blood_work", "fecal_exam"],
    },

    # ── Respiratory ────────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Infection",
        "name_ja": "上部気道感染症",
        "symptoms": {"sneezing", "nasal_discharge", "lethargy", "poor_appetite"},
        "description": "Bacterial or viral infection of the upper airways.",
        "description_ja": "細菌またはウイルスによる上部気道の感染症。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "physical_exam", "radiographs"],
    },
    {
        "name": "Pneumonia",
        "name_ja": "肺炎",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "poor_appetite", "cyanosis"},
        "description": "Infection or inflammation of the lungs; can be bacterial, viral, or aspiration.",
        "description_ja": "細菌、ウイルス、または誤嚥による肺の感染・炎症。",
        "urgency": "high",
        "recommended_tests": ["chest_radiographs", "blood_work", "bacterial_culture"],
    },
    {
        "name": "Aspiration Pneumonia",
        "name_ja": "誤嚥性肺炎",
        "symptoms": {"respiratory_distress", "coughing", "lethargy", "nasal_discharge", "fever"},
        "description": "Lung infection from aspiration of food or formula during hand-feeding.",
        "description_ja": "手乗り給餌中の食物やミルクの誤嚥による肺感染。",
        "urgency": "emergency",
        "recommended_tests": ["chest_radiographs", "blood_work"],
    },

    # ── Gastrointestinal ───────────────────────────────────────────────────
    {
        "name": "Diarrhea (Non-specific)",
        "name_ja": "下痢（非特異的）",
        "symptoms": {"diarrhea", "dehydration", "lethargy", "poor_appetite"},
        "description": "Loose stools from dietary changes, stress, or subclinical infection.",
        "description_ja": "食事の変更、ストレス、不顕性感染による軟便。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_culture", "physical_exam"],
    },
    {
        "name": "Bacterial Enteritis",
        "name_ja": "細菌性腸炎",
        "symptoms": {"diarrhea", "bloody_stool", "lethargy", "dehydration", "poor_appetite"},
        "description": "Bacterial infection of the intestines causing severe diarrhea.",
        "description_ja": "細菌による腸管感染で重度の下痢を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["fecal_culture", "blood_work", "fecal_smear"],
    },
    {
        "name": "Clostridial Enterotoxemia",
        "name_ja": "クロストリジウム性腸管毒素血症",
        "symptoms": {"diarrhea", "bloating", "lethargy", "collapse", "sudden_death_risk"},
        "description": "Overgrowth of Clostridium bacteria producing toxins; often fatal if untreated.",
        "description_ja": "クロストリジウム菌の異常増殖による毒素産生。未治療では致命的になりうる。",
        "urgency": "emergency",
        "recommended_tests": ["fecal_culture", "toxin_assay", "blood_work"],
    },
    {
        "name": "Gastrointestinal Obstruction",
        "name_ja": "消化管閉塞",
        "symptoms": {"poor_appetite", "bloating", "lethargy", "pain", "reduced_fecal_output"},
        "description": "Foreign body or mass blocking the intestinal lumen.",
        "description_ja": "異物や腫瘤による消化管の閉塞。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_radiographs", "ultrasound"],
    },
    {
        "name": "Constipation",
        "name_ja": "便秘",
        "symptoms": {"reduced_fecal_output", "straining", "bloating", "poor_appetite"},
        "description": "Difficulty passing stools from dehydration or low fiber intake.",
        "description_ja": "脱水や低繊維食による排便困難。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_radiographs", "physical_exam"],
    },
    {
        "name": "Rectal Prolapse",
        "name_ja": "直腸脱",
        "symptoms": {"tissue_protrusion_anus", "straining", "bloody_stool", "lethargy"},
        "description": "Protrusion of rectal tissue through the cloaca from straining or parasites.",
        "description_ja": "いきみや寄生虫により直腸組織が総排泄腔から突出する。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fecal_exam"],
    },

    # ── Dental ─────────────────────────────────────────────────────────────
    {
        "name": "Dental Disease / Tartar Buildup",
        "name_ja": "歯科疾患・歯石蓄積",
        "symptoms": {"drooling", "poor_appetite", "facial_swelling", "weight_loss", "bad_breath"},
        "description": "Plaque and tartar accumulation leading to periodontal disease and tooth loss.",
        "description_ja": "プラークや歯石の蓄積による歯周病と歯の喪失。",
        "urgency": "moderate",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },
    {
        "name": "Tooth Root Abscess",
        "name_ja": "歯根膿瘍",
        "symptoms": {"facial_swelling", "poor_appetite", "drooling", "eye_discharge", "weight_loss"},
        "description": "Infection at the tooth root causing facial swelling and pain.",
        "description_ja": "歯根の感染により顔面の腫脹と痛みが生じる。",
        "urgency": "high",
        "recommended_tests": ["skull_radiographs", "CT_scan", "bacterial_culture"],
    },
    {
        "name": "Malocclusion",
        "name_ja": "不正咬合",
        "symptoms": {"drooling", "poor_appetite", "weight_loss", "teeth_grinding"},
        "description": "Misalignment of teeth preventing normal eating.",
        "description_ja": "歯の噛み合わせ不良により正常な摂食ができなくなる。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "skull_radiographs"],
    },

    # ── Ophthalmological ───────────────────────────────────────────────────
    {
        "name": "Cataracts",
        "name_ja": "白内障",
        "symptoms": {"cloudy_eyes", "vision_loss", "bumping_into_objects"},
        "description": "Lens opacification that may be congenital, age-related, or nutritional.",
        "description_ja": "先天性、加齢性、または栄養性の水晶体混濁。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "slit_lamp_exam", "blood_chemistry"],
    },
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"eye_discharge", "eye_redness", "squinting", "eye_swelling"},
        "description": "Inflammation of the conjunctiva from irritants, infection, or allergy.",
        "description_ja": "刺激物、感染、アレルギーによる結膜の炎症。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "bacterial_culture", "fluorescein_stain"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"squinting", "eye_discharge", "eye_redness", "cloudy_eyes", "pawing_at_eye"},
        "description": "Erosion of the corneal surface from trauma or infection.",
        "description_ja": "外傷や感染による角膜表面の損傷。",
        "urgency": "high",
        "recommended_tests": ["fluorescein_stain", "ophthalmic_exam"],
    },
    {
        "name": "Proptosis (Eye Prolapse)",
        "name_ja": "眼球突出",
        "symptoms": {"eye_protrusion", "eye_swelling", "eye_discharge", "pain"},
        "description": "Displacement of the eyeball from the socket, often traumatic.",
        "description_ja": "外傷等による眼球の眼窩からの逸脱。",
        "urgency": "emergency",
        "recommended_tests": ["ophthalmic_exam", "skull_radiographs"],
    },

    # ── Reproductive ───────────────────────────────────────────────────────
    {
        "name": "Penile Paraphimosis",
        "name_ja": "嵌頓包茎（陰茎嵌頓）",
        "symptoms": {"penile_protrusion", "swelling", "self_chewing", "pain", "lethargy"},
        "description": "Inability to retract the penis, often from hair ring constriction; may lead to self-mutilation.",
        "description_ja": "毛のリングによる絞扼等で陰茎を引っ込められなくなる。自傷につながることがある。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "sedation_exam"],
    },
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_protrusion_cloaca", "straining", "lethargy", "pain", "swelling"},
        "description": "Protrusion of cloacal tissue; may involve reproductive or intestinal organs.",
        "description_ja": "総排泄腔の組織が突出し、生殖器や腸管が含まれることがある。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Pyometra",
        "name_ja": "子宮蓄膿症",
        "symptoms": {"vaginal_discharge", "lethargy", "poor_appetite", "distended_abdomen", "fever"},
        "description": "Uterine infection with pus accumulation in intact females.",
        "description_ja": "未避妊の雌で子宮内に膿が蓄積する感染症。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "blood_work", "radiographs"],
    },
    {
        "name": "Mastitis",
        "name_ja": "乳腺炎",
        "symptoms": {"mammary_swelling", "fever", "lethargy", "poor_appetite", "discharge"},
        "description": "Infection of the mammary glands in lactating females.",
        "description_ja": "授乳中の雌に見られる乳腺の感染症。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "cytology", "physical_exam"],
    },
    {
        "name": "Pouch Infection (Joeyitis)",
        "name_ja": "育児嚢感染症",
        "symptoms": {"discharge", "odor", "skin_redness", "swelling", "joey_failure_to_thrive"},
        "description": "Bacterial infection inside the marsupial pouch affecting the joey.",
        "description_ja": "育児嚢内の細菌感染で子供の発育不良を引き起こす。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "cytology", "physical_exam"],
    },

    # ── Neurological ───────────────────────────────────────────────────────
    {
        "name": "Seizures (MBD-related)",
        "name_ja": "てんかん発作（MBD関連）",
        "symptoms": {"seizures", "tremors", "hind_leg_paralysis", "weakness", "collapse"},
        "description": "Seizures secondary to severe calcium deficiency from metabolic bone disease.",
        "description_ja": "代謝性骨疾患による重度のカルシウム欠乏に続発するてんかん発作。",
        "urgency": "emergency",
        "recommended_tests": ["blood_calcium", "blood_glucose", "neurological_exam"],
    },
    {
        "name": "Hind Leg Paralysis",
        "name_ja": "後肢麻痺",
        "symptoms": {"hind_leg_paralysis", "dragging_legs", "incontinence", "weakness"},
        "description": "Loss of hind limb function, commonly from advanced MBD or spinal injury.",
        "description_ja": "進行したMBDや脊髄損傷による後肢機能の喪失。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "blood_calcium", "neurological_exam"],
    },
    {
        "name": "Vestibular Disease",
        "name_ja": "前庭疾患",
        "symptoms": {"head_tilt", "circling", "loss_of_balance", "nystagmus"},
        "description": "Inner ear or central nervous system disorder causing balance problems.",
        "description_ja": "内耳または中枢神経系の障害によるバランス異常。",
        "urgency": "moderate",
        "recommended_tests": ["neurological_exam", "otoscopic_exam", "radiographs"],
    },
    {
        "name": "Head Trauma",
        "name_ja": "頭部外傷",
        "symptoms": {"disorientation", "seizures", "head_tilt", "lethargy", "collapse"},
        "description": "Brain injury from falls or collisions during gliding.",
        "description_ja": "滑空中の落下や衝突による脳損傷。",
        "urgency": "emergency",
        "recommended_tests": ["neurological_exam", "skull_radiographs", "blood_work"],
    },

    # ── Renal / Urinary ────────────────────────────────────────────────────
    {
        "name": "Chronic Kidney Disease",
        "name_ja": "慢性腎臓病",
        "symptoms": {"polyuria", "polydipsia", "weight_loss", "lethargy", "dehydration"},
        "description": "Progressive loss of kidney function; more common in older gliders.",
        "description_ja": "進行性の腎機能低下。高齢のグライダーに多い。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "ultrasound"],
    },
    {
        "name": "Urinary Tract Infection",
        "name_ja": "尿路感染症",
        "symptoms": {"frequent_urination", "blood_in_urine", "straining", "lethargy"},
        "description": "Bacterial infection of the bladder or urethra.",
        "description_ja": "膀胱または尿道の細菌感染。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture"],
    },
    {
        "name": "Urolithiasis (Bladder Stones)",
        "name_ja": "尿路結石症",
        "symptoms": {"straining", "blood_in_urine", "frequent_urination", "pain"},
        "description": "Formation of mineral stones in the urinary tract.",
        "description_ja": "尿路内でのミネラル結石の形成。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "radiographs", "ultrasound"],
    },

    # ── Hepatic ────────────────────────────────────────────────────────────
    {
        "name": "Hepatic Lipidosis (Fatty Liver)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"poor_appetite", "lethargy", "weight_loss", "jaundice", "distended_abdomen"},
        "description": "Fatty liver from improper diet high in fat or from prolonged anorexia.",
        "description_ja": "高脂肪食や長期の食欲不振による脂肪肝。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_enzymes", "ultrasound"],
    },
    {
        "name": "Aflatoxicosis",
        "name_ja": "アフラトキシン中毒",
        "symptoms": {"jaundice", "lethargy", "poor_appetite", "vomiting", "diarrhea"},
        "description": "Liver damage from aflatoxin-contaminated food (spoiled nuts, seeds, or grains).",
        "description_ja": "カビ汚染された食品（ナッツ、種子、穀物）のアフラトキシンによる肝障害。",
        "urgency": "emergency",
        "recommended_tests": ["liver_enzymes", "blood_chemistry", "food_testing"],
    },

    # ── Neoplasia ──────────────────────────────────────────────────────────
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"lymph_node_swelling", "weight_loss", "lethargy", "poor_appetite"},
        "description": "Cancer of the lymphatic system; one of the more reported tumors in sugar gliders.",
        "description_ja": "リンパ系の腫瘍。フクロモモンガで比較的報告の多い腫瘍の一つ。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "blood_work", "radiographs", "histopathology"],
    },
    {
        "name": "Mammary Tumor",
        "name_ja": "乳腺腫瘍",
        "symptoms": {"mammary_mass", "swelling", "weight_loss", "lethargy"},
        "description": "Benign or malignant growth in the mammary tissue.",
        "description_ja": "乳腺組織の良性または悪性腫瘍。",
        "urgency": "high",
        "recommended_tests": ["fine_needle_aspirate", "radiographs", "histopathology"],
    },
    {
        "name": "Skin Tumor",
        "name_ja": "皮膚腫瘍",
        "symptoms": {"skin_mass", "ulceration", "hair_loss", "swelling"},
        "description": "Neoplastic growth on or under the skin.",
        "description_ja": "皮膚または皮下の腫瘍性増殖。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "histopathology"],
    },
    {
        "name": "Abdominal Neoplasia",
        "name_ja": "腹腔内腫瘍",
        "symptoms": {"distended_abdomen", "weight_loss", "poor_appetite", "lethargy"},
        "description": "Internal tumor causing progressive abdominal distension.",
        "description_ja": "腹腔内の腫瘍により進行性の腹部膨満が生じる。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_work", "biopsy"],
    },

    # ── Musculoskeletal ────────────────────────────────────────────────────
    {
        "name": "Limb Fracture",
        "name_ja": "四肢骨折",
        "symptoms": {"lameness", "swelling", "pain", "limb_deformity", "reluctance_to_move"},
        "description": "Broken bones from falls, cage injuries, or advanced MBD.",
        "description_ja": "落下、ケージ内事故、進行したMBDによる骨折。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam", "blood_calcium"],
    },
    {
        "name": "Pathological Fracture (MBD-related)",
        "name_ja": "病的骨折（MBD関連）",
        "symptoms": {"lameness", "bone_deformity", "pain", "swelling", "weakness"},
        "description": "Spontaneous fracture due to severely weakened bones from MBD.",
        "description_ja": "MBDにより著しく脆弱化した骨の自然骨折。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "blood_calcium", "blood_phosphorus"],
    },
    {
        "name": "Patagium Tear (Membrane Injury)",
        "name_ja": "飛膜損傷",
        "symptoms": {"membrane_tear", "bleeding", "pain", "difficulty_gliding"},
        "description": "Tear in the gliding membrane from trauma, cage hardware, or self-mutilation.",
        "description_ja": "外傷、ケージの金具、自傷による飛膜の裂傷。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "wound_assessment"],
    },

    # ── Cardiac ────────────────────────────────────────────────────────────
    {
        "name": "Cardiomyopathy",
        "name_ja": "心筋症",
        "symptoms": {"respiratory_distress", "lethargy", "reduced_activity", "collapse"},
        "description": "Disease of the heart muscle leading to impaired cardiac function.",
        "description_ja": "心筋の疾患により心機能が障害される。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_radiographs", "ECG"],
    },

    # ── Other ──────────────────────────────────────────────────────────────
    {
        "name": "Heat Stroke",
        "name_ja": "熱中症",
        "symptoms": {"rapid_breathing", "lethargy", "collapse", "drooling"},
        "description": "Overheating from exposure to high ambient temperatures.",
        "description_ja": "高温環境への暴露による体温の過上昇。",
        "urgency": "emergency",
        "recommended_tests": ["body_temperature", "physical_exam", "blood_work"],
    },
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"fever", "lethargy", "rapid_breathing", "collapse", "dehydration"},
        "description": "Systemic bloodstream infection from untreated wounds or abscesses.",
        "description_ja": "未治療の傷や膿瘍からの全身性血流感染。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "blood_work", "physical_exam"],
    },
    {
        "name": "Ear Infection (Otitis)",
        "name_ja": "耳感染症（外耳炎）",
        "symptoms": {"head_tilt", "scratching_ear", "ear_discharge", "loss_of_balance"},
        "description": "Infection of the outer or middle ear.",
        "description_ja": "外耳または中耳の感染。",
        "urgency": "moderate",
        "recommended_tests": ["otoscopic_exam", "ear_cytology", "bacterial_culture"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism (NSHP)",
        "name_ja": "栄養性二次性副甲状腺機能亢進症（NSHP）",
        "symptoms": {"hind_limb_weakness", "inability_to_climb", "pathological_fractures", "seizures", "tremors"},
        "description": "Severe metabolic bone disease from improper calcium:phosphorus ratio in diet. The most common fatal disease in captive sugar gliders.",
        "description_ja": "食事中のカルシウム:リン比の不適切さによる重度の代謝性骨疾患。飼育下フクロモモンガの最も一般的な致死的疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "xray", "ionized_calcium"],
    },
    {
        "name": "Self-Mutilation - Penile",
        "name_ja": "自己損傷 - 陰茎",
        "symptoms": {"bleeding", "penile_injury", "penile_tissue_loss", "self_chewing"},
        "description": "Self-directed chewing and trauma to the penis, common in intact males. Often requires penile amputation.",
        "description_ja": "陰茎への自己指向的な咀嚼と外傷で、未去勢の雄に多いです。しばしば陰茎切断が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "wound_assessment", "blood_chemistry"],
    },
    {
        "name": "Self-Mutilation - Tail",
        "name_ja": "自己損傷 - 尾",
        "symptoms": {"bleeding", "tail_chewing", "tail_injury", "tail_tissue_loss"},
        "description": "Self-directed chewing of the tail, often stress-related. May result in partial or complete tail loss.",
        "description_ja": "しばしばストレス関連の尾への自己指向的な咀嚼。部分的または完全な尾の喪失を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "behavioral_assessment", "wound_assessment"],
    },
    {
        "name": "Self-Mutilation - Patagium",
        "name_ja": "自己損傷 - 飛膜",
        "symptoms": {"bleeding", "membrane_chewing", "restlessness", "wound_on_membrane"},
        "description": "Self-directed chewing of the gliding membrane (patagium) from stress, pain, or behavioural disorder.",
        "description_ja": "ストレス、痛み、行動障害による滑空膜（飛膜）への自己指向的な咀嚼です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "behavioral_assessment", "pain_assessment"],
    },
    {
        "name": "Self-Mutilation - Stress-Induced",
        "name_ja": "自己損傷 - ストレス誘発性",
        "symptoms": {"behavioral_changes", "hair_loss", "lethargy", "self_chewing", "skin_wounds"},
        "description": "Compulsive self-injurious behaviour triggered by social isolation, improper housing, or inadequate enrichment.",
        "description_ja": "社会的孤立、不適切な飼育環境、不十分なエンリッチメントにより引き起こされる強迫的な自傷行為です。",
        "urgency": "high",
        "recommended_tests": ["behavioral_assessment", "environmental_review", "physical_exam"],
    },
    {
        "name": "Nutritional Osteodystrophy",
        "name_ja": "栄養性骨異栄養症",
        "symptoms": {"deformities", "lameness", "pain", "soft_bones", "stunted_growth"},
        "description": "Skeletal deformities from chronic nutritional deficiencies in growing joeys, causing bowed legs and jaw malformation.",
        "description_ja": "成長中の子フクロモモンガの慢性栄養欠乏による骨格変形で、弓脚と顎の変形を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["xray", "blood_chemistry", "diet_review"],
    },
    {
        "name": "Ick (Bacterial Skin Infection)",
        "name_ja": "イック（細菌性皮膚感染症）",
        "symptoms": {"crusty_skin", "hair_loss", "lethargy", "odorous_discharge", "skin_lesions"},
        "description": "Severe bacterial dermatitis colloquially called 'ick', causing malodorous weeping lesions and systemic illness.",
        "description_ja": "通称「イック」と呼ばれる重度の細菌性皮膚炎で、悪臭のある浸出性病変と全身性疾患を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skin_culture", "cytology", "blood_chemistry"],
    },
    {
        "name": "Patagium Laceration (Severe)",
        "name_ja": "飛膜裂傷（重症型）",
        "symptoms": {"bleeding", "inability_to_glide", "pain", "torn_membrane"},
        "description": "Severe tear of the gliding membrane from cage injury, fighting, or entrapment. May require surgical repair.",
        "description_ja": "ケージ内外傷、喧嘩、挟まりによる滑空膜の重度の裂傷。外科的修復が必要な場合があります。",
        "urgency": "high",
        "recommended_tests": ["wound_assessment", "physical_exam", "xray"],
    },
    {
        "name": "Patagium Abscess",
        "name_ja": "飛膜膿瘍",
        "symptoms": {"discharge_from_membrane", "lethargy", "membrane_swelling", "pain"},
        "description": "Abscess formation within or adjacent to the gliding membrane from bite wounds or contaminated injuries.",
        "description_ja": "咬傷や汚染された損傷による滑空膜内または隣接部の膿瘍形成です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "fine_needle_aspirate", "culture"],
    },
    {
        "name": "Pouch Infection (Marsupitis)",
        "name_ja": "育児嚢感染（マーシュピティス）",
        "symptoms": {"foul_odor_from_pouch", "joey_death", "pouch_discharge", "pouch_redness"},
        "description": "Bacterial infection of the marsupial pouch in females, potentially fatal to developing joeys.",
        "description_ja": "雌の育児嚢の細菌感染で、発育中の子に致死的な可能性があります。",
        "urgency": "high",
        "recommended_tests": ["pouch_swab_culture", "cytology", "physical_exam"],
    },
    {
        "name": "Joey Rejection",
        "name_ja": "子の拒絶",
        "symptoms": {"abandoned_joey", "hypothermic_joey", "joey_on_cage_floor"},
        "description": "Mother rejecting or ejecting joey from the pouch prematurely, from stress, illness, or first-time mothering.",
        "description_ja": "ストレス、病気、初産による母親の子の拒絶または育児嚢からの早期放出です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam_joey", "temperature_check", "maternal_exam"],
    },
    {
        "name": "Dystocia (Marsupial)",
        "name_ja": "難産（有袋類）",
        "symptoms": {"joey_stuck_in_cloaca", "lethargy", "straining", "vaginal_discharge"},
        "description": "Difficult birth with joey unable to migrate from cloaca to pouch, or maternal complications during delivery.",
        "description_ja": "子がクロアカから育児嚢に移動できない、または分娩中の母体合併症を伴う難産です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "cloacal_exam", "abdominal_xray"],
    },
    {
        "name": "Cloacal Infection",
        "name_ja": "クロアカ感染",
        "symptoms": {"cloacal_discharge", "foul_odor", "straining", "swelling_around_cloaca"},
        "description": "Bacterial infection of the cloaca causing inflammation, discharge, and potential ascending infection.",
        "description_ja": "クロアカの細菌感染で、炎症、分泌物、上行性感染の可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["cloacal_swab_culture", "physical_exam", "cytology"],
    },
    {
        "name": "Cloacal Neoplasia",
        "name_ja": "クロアカ腫瘍",
        "symptoms": {"bleeding_from_cloaca", "cloacal_mass", "straining", "weight_loss"},
        "description": "Tumour arising from the cloacal tissue, which may cause obstruction and systemic illness.",
        "description_ja": "クロアカ組織から発生する腫瘍で、閉塞と全身性疾患を引き起こすことがあります。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "physical_exam", "abdominal_ultrasound"],
    },
    {
        "name": "Scent Gland Hyperplasia",
        "name_ja": "臭腺過形成",
        "symptoms": {"enlarged_scent_gland", "excessive_oily_secretion", "hair_loss_on_head"},
        "description": "Enlargement and overactivity of the frontal (head) or sternal scent gland, common in intact males.",
        "description_ja": "前頭部（頭部）または胸骨臭腺の肥大と機能亢進で、未去勢の雄に多いです。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "cytology"],
    },
    {
        "name": "Scent Gland Tumor",
        "name_ja": "臭腺腫瘍",
        "symptoms": {"bleeding_from_gland", "foul_odor", "scent_gland_mass", "ulceration"},
        "description": "Neoplasia of the scent gland requiring surgical excision. May be benign or malignant.",
        "description_ja": "外科的切除が必要な臭腺の腫瘍。良性または悪性の場合があります。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "biopsy", "physical_exam"],
    },
    {
        "name": "Iron Storage Disease (Hepatic)",
        "name_ja": "鉄蓄積症（肝臓型）",
        "symptoms": {"abdominal_distension", "jaundice", "lethargy", "sudden_death", "weight_loss"},
        "description": "Hemochromatosis with pathological iron deposition in the liver causing hepatic failure. Common in captive sugar gliders.",
        "description_ja": "肝臓への病的鉄沈着による肝不全を伴うヘモクロマトーシス。飼育下フクロモモンガに多いです。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_biopsy", "serum_iron"],
    },
    {
        "name": "Hepatic Neoplasia",
        "name_ja": "肝臓腫瘍",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "weight_loss"},
        "description": "Primary or metastatic liver tumours causing progressive hepatic failure.",
        "description_ja": "進行性肝不全を引き起こす原発性または転移性肝臓腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["liver_ultrasound", "blood_chemistry", "fine_needle_aspirate"],
    },
    {
        "name": "Splenic Lymphoma",
        "name_ja": "脾臓リンパ腫",
        "symptoms": {"appetite_loss", "lethargy", "splenomegaly", "weight_loss"},
        "description": "Lymphoma primarily affecting the spleen causing massive splenomegaly.",
        "description_ja": "主に脾臓に影響するリンパ腫で、著明な脾腫大を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "splenic_aspirate", "cbc"],
    },
    {
        "name": "Renal Neoplasia",
        "name_ja": "腎臓腫瘍",
        "symptoms": {"abdominal_mass", "blood_in_urine", "lethargy", "weight_loss"},
        "description": "Primary renal tumours including renal cell carcinoma and nephroblastoma.",
        "description_ja": "腎細胞癌やネフロブラストーマを含む原発性腎腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["renal_ultrasound", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"rapid_growth", "skin_masses", "ulceration", "weight_loss"},
        "description": "Malignant connective tissue tumour. Can occur at any body site.",
        "description_ja": "悪性結合組織腫瘍。体のどの部位にも発生し得ます。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"bleeding_from_mass", "skin_masses", "ulceration", "weight_loss"},
        "description": "Malignant epithelial tumour that can arise on the skin or in the oral cavity.",
        "description_ja": "皮膚や口腔に発生する悪性上皮腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "chest_xray"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"lameness", "limb_swelling", "pain", "pathological_fracture"},
        "description": "Malignant bone tumour with metastatic potential. Often presents as pathological fracture.",
        "description_ja": "転移能を持つ悪性骨腫瘍。しばしば病的骨折として現れます。",
        "urgency": "high",
        "recommended_tests": ["limb_xray", "chest_xray", "biopsy"],
    },
    {
        "name": "Diabetes Mellitus",
        "name_ja": "糖尿病",
        "symptoms": {"cloudy_eyes", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Insulin deficiency or resistance causing hyperglycaemia. Often associated with high-sugar diets.",
        "description_ja": "インスリン欠乏または抵抗性による高血糖。しばしば高糖質食と関連します。",
        "urgency": "high",
        "recommended_tests": ["blood_glucose", "fructosamine", "urinalysis"],
    },
    {
        "name": "Hypoglycemia (Neonatal)",
        "name_ja": "低血糖症（新生児）",
        "symptoms": {"seizures", "tremors", "unresponsiveness", "weakness"},
        "description": "Dangerously low blood sugar in orphaned or rejected joeys requiring emergency sugar supplementation.",
        "description_ja": "孤児または拒絶された子の危険な低血糖で、緊急の糖補給が必要です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "physical_exam", "temperature_check"],
    },
    {
        "name": "Vitamin A Toxicity",
        "name_ja": "ビタミンA中毒",
        "symptoms": {"bone_pain", "hair_loss", "lethargy", "skin_lesions", "weight_loss"},
        "description": "Hypervitaminosis A from excessive supplementation causing dermatological and skeletal problems.",
        "description_ja": "過剰な補給によるビタミンA過剰症で、皮膚科的・骨格系の問題を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "diet_review", "xray"],
    },
    {
        "name": "Protein-Energy Malnutrition",
        "name_ja": "タンパク質-エネルギー栄養失調",
        "symptoms": {"immunosuppression", "lethargy", "muscle_wasting", "poor_coat", "poor_wound_healing"},
        "description": "Chronic inadequate protein and calorie intake causing wasting, immunosuppression, and organ dysfunction.",
        "description_ja": "慢性的な不十分なタンパク質とカロリー摂取による消耗、免疫抑制、臓器機能障害です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "albumin_level", "diet_review"],
    },
    {
        "name": "Thiamine Deficiency",
        "name_ja": "チアミン欠乏症",
        "symptoms": {"ataxia", "head_tilt", "opisthotonos", "seizures", "tremors"},
        "description": "Vitamin B1 deficiency causing neurological signs, often from feeding thiaminase-containing fish.",
        "description_ja": "チアミナーゼ含有魚の給餌による神経症状を引き起こすビタミンB1欠乏症です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "diet_review", "neurological_exam"],
    },
    {
        "name": "Zinc Deficiency",
        "name_ja": "亜鉛欠乏症",
        "symptoms": {"hair_loss", "immunosuppression", "poor_wound_healing", "skin_lesions"},
        "description": "Nutritional zinc deficiency causing dermatological problems and impaired immune function.",
        "description_ja": "皮膚科的問題と免疫機能低下を引き起こす栄養性亜鉛欠乏症です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "serum_zinc_level", "diet_review"],
    },
    {
        "name": "Gastrointestinal Candidiasis",
        "name_ja": "消化管カンジダ症",
        "symptoms": {"appetite_loss", "diarrhea", "oral_plaques", "weight_loss"},
        "description": "Yeast overgrowth in the GI tract from immunosuppression, antibiotic use, or high-sugar diets.",
        "description_ja": "免疫抑制、抗生物質使用、高糖質食による消化管の酵母過増殖です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "oral_exam", "cytology"],
    },
    {
        "name": "Pasteurellosis",
        "name_ja": "パスツレラ症",
        "symptoms": {"abscesses", "fever", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Bacterial infection by Pasteurella species causing respiratory disease and abscess formation.",
        "description_ja": "パスツレラ属による細菌感染で、呼吸器疾患と膿瘍形成を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["culture_sensitivity", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Mycoplasma Pneumonia",
        "name_ja": "マイコプラズマ肺炎",
        "symptoms": {"coughing", "lethargy", "nasal_discharge", "respiratory_distress", "weight_loss"},
        "description": "Chronic respiratory infection by Mycoplasma species, difficult to eradicate.",
        "description_ja": "マイコプラズマ属による慢性呼吸器感染で、根絶が困難です。",
        "urgency": "high",
        "recommended_tests": ["pcr_testing", "chest_xray", "tracheal_wash"],
    },
    {
        "name": "Klebsiella Septicemia",
        "name_ja": "クレブシエラ敗血症",
        "symptoms": {"diarrhea", "fever", "lethargy", "rapid_breathing", "sudden_death"},
        "description": "Acute systemic Klebsiella infection causing multi-organ failure. Often rapidly fatal.",
        "description_ja": "急性全身性クレブシエラ感染で多臓器不全を引き起こします。しばしば急速に致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "cbc", "blood_chemistry"],
    },
    {
        "name": "Toxoplasmosis (Acute)",
        "name_ja": "トキソプラズマ症（急性）",
        "symptoms": {"hepatitis", "lethargy", "neurological_signs", "pneumonia", "sudden_death"},
        "description": "Acute protozoal infection by Toxoplasma gondii. Marsupials are extremely susceptible and infection is often fatal.",
        "description_ja": "トキソプラズマ・ゴンジイによる急性原虫感染。有袋類は極めて感受性が高く、感染はしばしば致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["serology", "pcr_testing", "blood_chemistry"],
    },
    {
        "name": "Neosporosis",
        "name_ja": "ネオスポラ症",
        "symptoms": {"hind_limb_weakness", "lethargy", "neurological_signs", "weight_loss"},
        "description": "Protozoal infection by Neospora caninum causing neurological and muscular disease.",
        "description_ja": "ネオスポラ・カニナムによる原虫感染で、神経学的・筋疾患を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["serology", "pcr_testing", "neurological_exam"],
    },
    {
        "name": "Pyelonephritis",
        "name_ja": "腎盂腎炎",
        "symptoms": {"appetite_loss", "blood_in_urine", "fever", "lethargy", "polydipsia"},
        "description": "Ascending bacterial infection of the kidneys from lower urinary tract disease.",
        "description_ja": "下部尿路疾患からの上行性腎臓細菌感染です。",
        "urgency": "high",
        "recommended_tests": ["urinalysis", "urine_culture", "renal_ultrasound"],
    },
    {
        "name": "Renal Amyloidosis",
        "name_ja": "腎アミロイドーシス",
        "symptoms": {"edema", "lethargy", "polydipsia", "polyuria", "weight_loss"},
        "description": "Amyloid protein deposition in the kidneys causing progressive renal failure.",
        "description_ja": "腎臓へのアミロイドタンパク沈着で進行性腎不全を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "urinalysis", "renal_biopsy"],
    },
    {
        "name": "Cystitis (Bacterial)",
        "name_ja": "膀胱炎（細菌性）",
        "symptoms": {"blood_in_urine", "foul_smelling_urine", "frequent_urination", "straining_to_urinate"},
        "description": "Bacterial infection of the bladder causing inflammation and haematuria.",
        "description_ja": "膀胱の細菌感染で、炎症と血尿を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "physical_exam"],
    },
    {
        "name": "Dilated Cardiomyopathy",
        "name_ja": "拡張型心筋症",
        "symptoms": {"ascites", "collapse", "exercise_intolerance", "lethargy", "respiratory_distress"},
        "description": "Dilation and weakening of the heart chambers leading to congestive heart failure.",
        "description_ja": "心室の拡張と弱化によるうっ血性心不全です。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "chest_xray", "blood_chemistry"],
    },
    {
        "name": "Pericardial Effusion",
        "name_ja": "心嚢液貯留",
        "symptoms": {"exercise_intolerance", "lethargy", "muffled_heart_sounds", "respiratory_distress"},
        "description": "Fluid accumulation around the heart causing cardiac tamponade.",
        "description_ja": "心臓周囲の液体蓄積で心タンポナーデを引き起こします。",
        "urgency": "emergency",
        "recommended_tests": ["echocardiography", "chest_xray", "pericardiocentesis"],
    },
    {
        "name": "Vertebral Fracture",
        "name_ja": "椎骨骨折",
        "symptoms": {"hind_limb_paralysis", "inability_to_climb", "incontinence", "pain"},
        "description": "Fracture of vertebral bones from falls, cage injuries, or metabolic bone disease.",
        "description_ja": "落下、ケージ内外傷、代謝性骨疾患による椎骨の骨折です。",
        "urgency": "emergency",
        "recommended_tests": ["spinal_xray", "neurological_exam", "physical_exam"],
    },
    {
        "name": "Pelvic Fracture",
        "name_ja": "骨盤骨折",
        "symptoms": {"hind_limb_lameness", "inability_to_climb", "pain", "reluctance_to_move"},
        "description": "Fracture of the pelvis from falls or metabolic bone disease causing severe pain and mobility issues.",
        "description_ja": "落下や代謝性骨疾患による骨盤の骨折で、重度の痛みと移動障害を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["pelvic_xray", "physical_exam", "blood_chemistry"],
    },
    {
        "name": "Digit Fracture / Avulsion",
        "name_ja": "指骨折/剥離",
        "symptoms": {"bleeding", "lameness", "licking_foot", "toe_swelling"},
        "description": "Fracture or avulsion of toes from cage wire, running wheels, or fleece loops catching on toenails.",
        "description_ja": "ケージのワイヤー、回し車、フリースのループに爪が引っかかることによる指の骨折または剥離です。",
        "urgency": "moderate",
        "recommended_tests": ["foot_xray", "physical_exam"],
    },
    {
        "name": "Tail Degloving",
        "name_ja": "尾部皮膚剥離",
        "symptoms": {"bleeding", "exposed_bone", "pain", "tail_injury"},
        "description": "Avulsion of tail skin from being caught in cage doors, wheels, or during improper handling.",
        "description_ja": "ケージのドア、回し車、不適切な取り扱い中に尾の皮膚が剥離する状態です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "tail_xray", "wound_assessment"],
    },
    {
        "name": "Glider Bite Wounds",
        "name_ja": "フクロモモンガ咬傷",
        "symptoms": {"abscess", "bite_wounds", "lethargy", "pain", "swelling"},
        "description": "Bite wound injuries from colony mates, which may become infected and form abscesses.",
        "description_ja": "コロニー仲間からの咬傷で、感染して膿瘍を形成することがあります。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "culture_sensitivity", "physical_exam"],
    },
    {
        "name": "Dental Abscess (Molar)",
        "name_ja": "歯の膿瘍（臼歯）",
        "symptoms": {"appetite_loss", "drooling", "facial_swelling", "weight_loss"},
        "description": "Abscess at the root of a molar tooth causing facial swelling and difficulty eating.",
        "description_ja": "臼歯の歯根部の膿瘍で、顔面腫脹と摂食困難を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "dental_exam", "culture"],
    },
    {
        "name": "Periodontal Disease",
        "name_ja": "歯周病",
        "symptoms": {"appetite_loss", "drooling", "foul_breath", "gum_redness", "loose_teeth"},
        "description": "Inflammation and infection of the gums and supporting structures from tartar and bacterial buildup.",
        "description_ja": "歯石と細菌蓄積による歯肉と支持構造の炎症と感染です。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "oral_exam", "skull_xray"],
    },
    {
        "name": "Incisor Fracture",
        "name_ja": "切歯骨折",
        "symptoms": {"appetite_loss", "bleeding_from_mouth", "difficulty_eating", "drooling"},
        "description": "Fracture of incisor teeth from cage bar chewing or trauma, potentially exposing the pulp.",
        "description_ja": "ケージバーの齧りや外傷による切歯の骨折で、歯髄が露出する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["dental_exam", "skull_xray", "physical_exam"],
    },
    {
        "name": "Pancreatitis",
        "name_ja": "膵炎",
        "symptoms": {"abdominal_pain", "appetite_loss", "diarrhea", "lethargy", "vomiting"},
        "description": "Inflammation of the pancreas often from high-fat or high-sugar diets.",
        "description_ja": "高脂肪または高糖質の食事による膵臓の炎症です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "lipase_level", "abdominal_ultrasound"],
    },
    {
        "name": "Intestinal Candidiasis",
        "name_ja": "腸管カンジダ症",
        "symptoms": {"appetite_loss", "diarrhea", "lethargy", "weight_loss"},
        "description": "Yeast overgrowth in the intestinal tract causing malabsorption and chronic diarrhea.",
        "description_ja": "腸管内の酵母過増殖で吸収不良と慢性下痢を引き起こします。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "fecal_exam", "blood_chemistry"],
    },
    {
        "name": "Stress-Induced Immunosuppression",
        "name_ja": "ストレス誘発性免疫抑制",
        "symptoms": {"lethargy", "poor_wound_healing", "recurrent_infections", "weight_loss"},
        "description": "Chronic stress causing cortisol-mediated immunosuppression and increased susceptibility to infections.",
        "description_ja": "慢性ストレスによるコルチゾール介在性の免疫抑制と感染感受性の増加です。",
        "urgency": "moderate",
        "recommended_tests": ["cbc", "blood_chemistry", "behavioral_assessment"],
    },
    {
        "name": "Hypothermia",
        "name_ja": "低体温症",
        "symptoms": {"cold_body", "curled_posture", "lethargy", "unresponsiveness"},
        "description": "Dangerously low body temperature from cold ambient temperatures. Sugar gliders require warm environments (24-27°C).",
        "description_ja": "低い環境温度による危険な低体温。フクロモモンガは暖かい環境（24-27°C）を必要とします。",
        "urgency": "emergency",
        "recommended_tests": ["temperature_check", "blood_glucose", "physical_exam"],
    },
    {
        "name": "Obesity-Related Hepatic Lipidosis",
        "name_ja": "肥満関連肝リピドーシス",
        "symptoms": {"abdominal_distension", "appetite_loss", "jaundice", "lethargy", "obesity"},
        "description": "Fatty liver disease from chronic overfeeding, especially of high-fat foods like mealworms and nuts.",
        "description_ja": "特にミールワームやナッツなどの高脂肪食の慢性的な過食による脂肪肝です。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "liver_ultrasound", "diet_review"],
    },
    {
        "name": "Nocturnal Vocalization (Barking)",
        "name_ja": "夜間発声（バーキング）",
        "symptoms": {"attention_seeking", "excessive_barking", "nighttime_activity"},
        "description": "Excessive nocturnal barking from loneliness, boredom, or seeking attention. May indicate need for companion glider.",
        "description_ja": "孤独、退屈、注意を引くための過度の夜間発声。仲間のフクロモモンガの必要性を示す場合があります。",
        "urgency": "low",
        "recommended_tests": ["behavioral_assessment", "environmental_review"],
    },
    {
        "name": "Crab-Eating (Self-Mutilation Precursor)",
        "name_ja": "クラビング（自己損傷前兆）",
        "symptoms": {"hair_thinning", "self_grooming_obsessive", "skin_redness", "stress_signs"},
        "description": "Obsessive over-grooming behaviour that may escalate to self-mutilation if underlying cause not addressed.",
        "description_ja": "基礎原因が対処されないと自己損傷にエスカレートする可能性のある強迫的な過度グルーミング行動です。",
        "urgency": "moderate",
        "recommended_tests": ["behavioral_assessment", "physical_exam", "environmental_review"],
    },
    {
        "name": "Encephalitis (Viral)",
        "name_ja": "脳炎（ウイルス性）",
        "symptoms": {"circling", "head_tilt", "lethargy", "seizures", "sudden_death"},
        "description": "Viral inflammation of the brain causing severe neurological signs. Often fatal in marsupials.",
        "description_ja": "脳のウイルス性炎症で、重度の神経症状を引き起こします。有袋類ではしばしば致死的です。",
        "urgency": "emergency",
        "recommended_tests": ["neurological_exam", "pcr_testing", "blood_chemistry"],
    },
    {
        "name": "Otitis Media / Interna",
        "name_ja": "中耳炎/内耳炎",
        "symptoms": {"appetite_loss", "balance_loss", "circling", "head_tilt", "nystagmus"},
        "description": "Deep ear infection affecting the middle or inner ear causing vestibular signs.",
        "description_ja": "中耳または内耳に影響する深部耳感染で、前庭症状を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skull_xray", "otoscopy", "culture_sensitivity"],
    },
    {
        "name": "Corneal Foreign Body",
        "name_ja": "角膜異物",
        "symptoms": {"eye_discharge", "eye_redness", "pawing_at_eye", "squinting"},
        "description": "Foreign material embedded in the cornea from bedding particles, wood chips, or plant material.",
        "description_ja": "床材粒子、木片、植物片による角膜に埋め込まれた異物です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "physical_exam"],
    },
    {
        "name": "Sarcoptic Mange (Severe)",
        "name_ja": "疥癬（重症型）",
        "symptoms": {"intense_itching", "severe_hair_loss", "skin_crusting", "skin_thickening", "weight_loss"},
        "description": "Heavy Sarcoptes scabiei infestation causing severe pruritus, crusting, and secondary infection.",
        "description_ja": "ヒゼンダニの重度の寄生で、重度の掻痒、痂皮形成、二次感染を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["skin_scraping", "microscopy", "physical_exam"],
    },
    {
        "name": "Intestinal Obstruction",
        "name_ja": "腸閉塞",
        "symptoms": {"abdominal_distension", "appetite_loss", "lethargy", "reduced_fecal_output", "vomiting"},
        "description": "Blockage of the intestine from foreign material, tumour, or intussusception.",
        "description_ja": "異物、腫瘍、腸重積による腸の閉塞です。",
        "urgency": "emergency",
        "recommended_tests": ["abdominal_xray", "abdominal_ultrasound", "physical_exam"],
    },
    {
        "name": "Lead Poisoning",
        "name_ja": "鉛中毒",
        "symptoms": {"appetite_loss", "ataxia", "diarrhea", "lethargy", "seizures"},
        "description": "Toxicosis from ingestion of lead paint, solder, or other lead-containing materials during out-of-cage exploration.",
        "description_ja": "ケージ外探索中の鉛塗料、はんだ、その他の鉛含有物質の摂取による中毒症です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "abdominal_xray", "blood_chemistry"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"anemia", "appetite_loss", "jaundice", "lethargy"},
        "description": "Poisoning from chewing galvanised cage components causing haemolytic anaemia.",
        "description_ja": "亜鉛メッキされたケージ部品を齧ることによる溶血性貧血を伴う中毒です。",
        "urgency": "high",
        "recommended_tests": ["cbc", "serum_zinc_level", "blood_chemistry"],
    },
    {
        "name": "Chronic Wasting (Geriatric)",
        "name_ja": "慢性消耗（老齢性）",
        "symptoms": {"decreased_activity", "lethargy", "muscle_wasting", "poor_coat", "progressive_weight_loss"},
        "description": "Progressive weight loss in aged sugar gliders from multi-organ disease, dental problems, or cancer.",
        "description_ja": "多臓器疾患、歯科問題、癌による高齢フクロモモンガの進行性体重減少です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "physical_exam", "abdominal_ultrasound"],
    },
    {
        "name": "Uterine Neoplasia",
        "name_ja": "子宮腫瘍",
        "symptoms": {"abdominal_distension", "lethargy", "vaginal_bleeding", "weight_loss"},
        "description": "Tumour of the uterus in intact females, requiring ovariohysterectomy.",
        "description_ja": "未避妊の雌の子宮腫瘍で、卵巣子宮摘出が必要です。",
        "urgency": "high",
        "recommended_tests": ["abdominal_ultrasound", "blood_chemistry", "physical_exam"],
    },
    {
        "name": "Ovarian Cysts",
        "name_ja": "卵巣嚢胞",
        "symptoms": {"abdominal_distension", "behavioral_changes", "hair_loss", "lethargy"},
        "description": "Fluid-filled ovarian cysts causing hormonal disturbances and abdominal enlargement.",
        "description_ja": "ホルモン障害と腹部膨張を引き起こす液体で満たされた卵巣嚢胞です。",
        "urgency": "moderate",
        "recommended_tests": ["abdominal_ultrasound", "hormone_panel", "physical_exam"],
    },
    {
        "name": "Penile Prolapse (Non-paraphimosis)",
        "name_ja": "陰茎脱出（非嵌頓包茎）",
        "symptoms": {"exposed_penis", "licking_genital_area", "mild_swelling"},
        "description": "Transient penile exposure without constriction, common during mating behaviour. May progress to paraphimosis.",
        "description_ja": "交尾行動中に一般的な、締め付けを伴わない一過性の陰茎露出。嵌頓包茎に進行する可能性があります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "genital_exam"],
    },
]


# ---------------------------------------------------------------------------
# Symptom name lookup
# ---------------------------------------------------------------------------

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    # Nutritional / Metabolic
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "bone_deformity": {"ja": "骨変形", "en": "Bone Deformity"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "seizures": {"ja": "痙攣・発作", "en": "Seizures"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "muscle_twitching": {"ja": "筋肉のけいれん", "en": "Muscle Twitching"},
    "weight_loss": {"ja": "体重減少", "en": "Weight Loss"},
    "weight_gain": {"ja": "体重増加", "en": "Weight Gain"},
    "lethargy": {"ja": "無気力・元気消失", "en": "Lethargy"},
    "poor_appetite": {"ja": "食欲低下", "en": "Poor Appetite"},
    "rough_coat": {"ja": "被毛の荒れ", "en": "Rough Coat"},
    "reduced_activity": {"ja": "活動量の低下", "en": "Reduced Activity"},
    "difficulty_gliding": {"ja": "滑空困難", "en": "Difficulty Gliding"},
    "poor_wound_healing": {"ja": "創傷治癒不良", "en": "Poor Wound Healing"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle Wasting"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "sunken_eyes": {"ja": "眼の陥没", "en": "Sunken Eyes"},
    "skin_tenting": {"ja": "皮膚ツルゴール低下", "en": "Skin Tenting"},
    "dry_mucous_membranes": {"ja": "粘膜の乾燥", "en": "Dry Mucous Membranes"},
    # Self-mutilation / Behavioral
    "self_chewing": {"ja": "自咬行為", "en": "Self-chewing"},
    "open_wounds": {"ja": "開放創", "en": "Open Wounds"},
    "hair_loss": {"ja": "脱毛", "en": "Hair Loss"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "stress_behavior": {"ja": "ストレス行動", "en": "Stress Behavior"},
    "over_grooming": {"ja": "過剰毛繕い", "en": "Over-grooming"},
    "patchy_fur": {"ja": "まだらな被毛", "en": "Patchy Fur"},
    # Dermatological
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "discharge": {"ja": "分泌物・排膿", "en": "Discharge"},
    "pain": {"ja": "疼痛", "en": "Pain"},
    "fever": {"ja": "発熱", "en": "Fever"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin Redness"},
    "crusty_skin": {"ja": "痂皮形成", "en": "Crusty Skin"},
    "scaly_skin": {"ja": "鱗屑", "en": "Scaly Skin"},
    "itching": {"ja": "かゆみ", "en": "Itching"},
    "scratching": {"ja": "引っ掻き行動", "en": "Scratching"},
    "circular_lesions": {"ja": "円形の病変", "en": "Circular Lesions"},
    "skin_infections": {"ja": "皮膚感染", "en": "Skin Infections"},
    "skin_mass": {"ja": "皮膚の腫瘤", "en": "Skin Mass"},
    "ulceration": {"ja": "潰瘍", "en": "Ulceration"},
    "odor": {"ja": "異臭", "en": "Odor"},
    "flea_dirt": {"ja": "ノミの糞", "en": "Flea Dirt"},
    # Parasitic
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "bloating": {"ja": "膨満", "en": "Bloating"},
    "bloody_stool": {"ja": "血便", "en": "Bloody Stool"},
    "visible_worms_in_stool": {"ja": "糞便中の虫体", "en": "Visible Worms in Stool"},
    # Respiratory
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "nasal_discharge": {"ja": "鼻汁", "en": "Nasal Discharge"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory Distress"},
    "rapid_breathing": {"ja": "頻呼吸", "en": "Rapid Breathing"},
    "coughing": {"ja": "咳", "en": "Coughing"},
    "cyanosis": {"ja": "チアノーゼ", "en": "Cyanosis"},
    # Gastrointestinal
    "reduced_fecal_output": {"ja": "排便量の減少", "en": "Reduced Fecal Output"},
    "straining": {"ja": "いきみ・排便困難", "en": "Straining"},
    "vomiting": {"ja": "嘔吐", "en": "Vomiting"},
    "tissue_protrusion_anus": {"ja": "肛門からの組織突出", "en": "Tissue Protrusion from Anus"},
    "sudden_death_risk": {"ja": "突然死のリスク", "en": "Sudden Death Risk"},
    # Dental
    "drooling": {"ja": "流涎・よだれ", "en": "Drooling"},
    "facial_swelling": {"ja": "顔面の腫脹", "en": "Facial Swelling"},
    "bad_breath": {"ja": "口臭", "en": "Bad Breath"},
    "teeth_grinding": {"ja": "歯ぎしり", "en": "Teeth Grinding"},
    # Ophthalmological
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy Eyes"},
    "vision_loss": {"ja": "視力低下", "en": "Vision Loss"},
    "bumping_into_objects": {"ja": "物にぶつかる", "en": "Bumping into Objects"},
    "eye_discharge": {"ja": "眼脂・目やに", "en": "Eye Discharge"},
    "eye_redness": {"ja": "眼の充血", "en": "Eye Redness"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye Swelling"},
    "squinting": {"ja": "眼を細める", "en": "Squinting"},
    "pawing_at_eye": {"ja": "眼を前足で掻く", "en": "Pawing at Eye"},
    "eye_protrusion": {"ja": "眼球突出", "en": "Eye Protrusion"},
    # Reproductive
    "penile_protrusion": {"ja": "陰茎の突出", "en": "Penile Protrusion"},
    "tissue_protrusion_cloaca": {"ja": "総排泄腔からの組織突出", "en": "Tissue Protrusion from Cloaca"},
    "vaginal_discharge": {"ja": "膣分泌物", "en": "Vaginal Discharge"},
    "mammary_swelling": {"ja": "乳腺の腫脹", "en": "Mammary Swelling"},
    "mammary_mass": {"ja": "乳腺の腫瘤", "en": "Mammary Mass"},
    "joey_failure_to_thrive": {"ja": "子供の発育不良", "en": "Joey Failure to Thrive"},
    # Neurological
    "hind_leg_paralysis": {"ja": "後肢麻痺", "en": "Hind Leg Paralysis"},
    "dragging_legs": {"ja": "後肢を引きずる", "en": "Dragging Hind Legs"},
    "disorientation": {"ja": "見当識障害", "en": "Disorientation"},
    "head_tilt": {"ja": "斜頸", "en": "Head Tilt"},
    "circling": {"ja": "旋回運動", "en": "Circling"},
    "loss_of_balance": {"ja": "平衡感覚の喪失", "en": "Loss of Balance"},
    "nystagmus": {"ja": "眼振", "en": "Nystagmus"},
    "incontinence": {"ja": "失禁", "en": "Incontinence"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    # Renal
    "polyuria": {"ja": "多尿", "en": "Polyuria"},
    "polydipsia": {"ja": "多飲", "en": "Polydipsia"},
    "blood_in_urine": {"ja": "血尿", "en": "Blood in Urine"},
    "frequent_urination": {"ja": "頻尿", "en": "Frequent Urination"},
    # Hepatic
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "distended_abdomen": {"ja": "腹部膨満", "en": "Distended Abdomen"},
    # Neoplasia
    "lymph_node_swelling": {"ja": "リンパ節の腫脹", "en": "Lymph Node Swelling"},
    # Musculoskeletal
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "limb_deformity": {"ja": "四肢の変形", "en": "Limb Deformity"},
    "reluctance_to_move": {"ja": "動きたがらない", "en": "Reluctance to Move"},
    "membrane_tear": {"ja": "飛膜の裂傷", "en": "Membrane Tear"},
    # Ear
    "scratching_ear": {"ja": "耳を掻く", "en": "Scratching Ear"},
    "ear_discharge": {"ja": "耳漏", "en": "Ear Discharge"},

    # --- 追加症状 (DISEASES内で使用されている未登録項目) ---
    "abandoned_joey": {"ja": "Abandoned Joey", "en": "Abandoned Joey"},
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "abdominal_mass": {"ja": "Abdominal Mass", "en": "Abdominal Mass"},
    "abdominal_pain": {"ja": "腹痛", "en": "Abdominal pain"},
    "abscess": {"ja": "膿瘍", "en": "Abscess"},
    "abscesses": {"ja": "Abscesses", "en": "Abscesses"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "appetite_loss": {"ja": "食欲低下", "en": "Appetite loss"},
    "ascites": {"ja": "腹水", "en": "Ascites"},
    "ataxia": {"ja": "Ataxia", "en": "Ataxia"},
    "attention_seeking": {"ja": "Attention Seeking", "en": "Attention Seeking"},
    "balance_loss": {"ja": "Balance Loss", "en": "Balance Loss"},
    "behavioral_changes": {"ja": "行動変化", "en": "Behavioral changes"},
    "bite_wounds": {"ja": "Bite Wounds", "en": "Bite Wounds"},
    "bleeding_from_cloaca": {"ja": "Bleeding From Cloaca", "en": "Bleeding From Cloaca"},
    "bleeding_from_gland": {"ja": "Bleeding From Gland", "en": "Bleeding From Gland"},
    "bleeding_from_mass": {"ja": "Bleeding From Mass", "en": "Bleeding From Mass"},
    "bleeding_from_mouth": {"ja": "Bleeding From Mouth", "en": "Bleeding From Mouth"},
    "bone_pain": {"ja": "Bone Pain", "en": "Bone Pain"},
    "cataracts": {"ja": "Cataracts", "en": "Cataracts"},
    "cloacal_discharge": {"ja": "総排泄腔分泌物", "en": "Cloacal discharge"},
    "cloacal_mass": {"ja": "Cloacal Mass", "en": "Cloacal Mass"},
    "cold_body": {"ja": "Cold Body", "en": "Cold Body"},
    "curled_posture": {"ja": "Curled Posture", "en": "Curled Posture"},
    "decreased_activity": {"ja": "活動低下", "en": "Decreased activity"},
    "deformities": {"ja": "Deformities", "en": "Deformities"},
    "difficulty_eating": {"ja": "Difficulty Eating", "en": "Difficulty Eating"},
    "discharge_from_membrane": {"ja": "Discharge From Membrane", "en": "Discharge From Membrane"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "enlarged_scent_gland": {"ja": "Enlarged Scent Gland", "en": "Enlarged Scent Gland"},
    "excessive_barking": {"ja": "Excessive Barking", "en": "Excessive Barking"},
    "excessive_oily_secretion": {"ja": "Excessive Oily Secretion", "en": "Excessive Oily Secretion"},
    "exercise_intolerance": {"ja": "Exercise Intolerance", "en": "Exercise Intolerance"},
    "exposed_bone": {"ja": "Exposed Bone", "en": "Exposed Bone"},
    "exposed_penis": {"ja": "Exposed Penis", "en": "Exposed Penis"},
    "foul_breath": {"ja": "Foul Breath", "en": "Foul Breath"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "foul_odor_from_pouch": {"ja": "Foul Odor From Pouch", "en": "Foul Odor From Pouch"},
    "foul_smelling_urine": {"ja": "Foul Smelling Urine", "en": "Foul Smelling Urine"},
    "gum_redness": {"ja": "Gum Redness", "en": "Gum Redness"},
    "hair_loss_on_head": {"ja": "Hair Loss On Head", "en": "Hair Loss On Head"},
    "hair_thinning": {"ja": "Hair Thinning", "en": "Hair Thinning"},
    "hepatitis": {"ja": "Hepatitis", "en": "Hepatitis"},
    "hind_limb_lameness": {"ja": "Hind Limb Lameness", "en": "Hind Limb Lameness"},
    "hind_limb_paralysis": {"ja": "後肢麻痺", "en": "Hind limb paralysis"},
    "hind_limb_weakness": {"ja": "後肢の衰弱", "en": "Hind limb weakness"},
    "hypothermic_joey": {"ja": "Hypothermic Joey", "en": "Hypothermic Joey"},
    "immunosuppression": {"ja": "免疫抑制", "en": "Immunosuppression"},
    "inability_to_climb": {"ja": "Inability To Climb", "en": "Inability To Climb"},
    "inability_to_glide": {"ja": "Inability To Glide", "en": "Inability To Glide"},
    "intense_itching": {"ja": "Intense Itching", "en": "Intense Itching"},
    "joey_death": {"ja": "Joey Death", "en": "Joey Death"},
    "joey_on_cage_floor": {"ja": "Joey On Cage Floor", "en": "Joey On Cage Floor"},
    "joey_stuck_in_cloaca": {"ja": "Joey Stuck In Cloaca", "en": "Joey Stuck In Cloaca"},
    "licking_foot": {"ja": "Licking Foot", "en": "Licking Foot"},
    "licking_genital_area": {"ja": "Licking Genital Area", "en": "Licking Genital Area"},
    "limb_swelling": {"ja": "四肢腫脹", "en": "Limb swelling"},
    "loose_teeth": {"ja": "Loose Teeth", "en": "Loose Teeth"},
    "membrane_chewing": {"ja": "Membrane Chewing", "en": "Membrane Chewing"},
    "membrane_swelling": {"ja": "Membrane Swelling", "en": "Membrane Swelling"},
    "mild_swelling": {"ja": "Mild Swelling", "en": "Mild Swelling"},
    "muffled_heart_sounds": {"ja": "Muffled Heart Sounds", "en": "Muffled Heart Sounds"},
    "neurological_signs": {"ja": "神経症状", "en": "Neurological signs"},
    "nighttime_activity": {"ja": "Nighttime Activity", "en": "Nighttime Activity"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "odorous_discharge": {"ja": "Odorous Discharge", "en": "Odorous Discharge"},
    "opisthotonos": {"ja": "Opisthotonos", "en": "Opisthotonos"},
    "oral_plaques": {"ja": "Oral Plaques", "en": "Oral Plaques"},
    "pathological_fracture": {"ja": "Pathological Fracture", "en": "Pathological Fracture"},
    "pathological_fractures": {"ja": "Pathological Fractures", "en": "Pathological Fractures"},
    "penile_injury": {"ja": "Penile Injury", "en": "Penile Injury"},
    "penile_tissue_loss": {"ja": "Penile Tissue Loss", "en": "Penile Tissue Loss"},
    "pneumonia": {"ja": "Pneumonia", "en": "Pneumonia"},
    "poor_coat": {"ja": "Poor Coat", "en": "Poor Coat"},
    "pouch_discharge": {"ja": "Pouch Discharge", "en": "Pouch Discharge"},
    "pouch_redness": {"ja": "Pouch Redness", "en": "Pouch Redness"},
    "progressive_weight_loss": {"ja": "Progressive Weight Loss", "en": "Progressive Weight Loss"},
    "rapid_growth": {"ja": "Rapid Growth", "en": "Rapid Growth"},
    "recurrent_infections": {"ja": "Recurrent Infections", "en": "Recurrent Infections"},
    "restlessness": {"ja": "Restlessness", "en": "Restlessness"},
    "scent_gland_mass": {"ja": "Scent Gland Mass", "en": "Scent Gland Mass"},
    "self_grooming_obsessive": {"ja": "Self Grooming Obsessive", "en": "Self Grooming Obsessive"},
    "severe_hair_loss": {"ja": "Severe Hair Loss", "en": "Severe Hair Loss"},
    "skin_crusting": {"ja": "Skin Crusting", "en": "Skin Crusting"},
    "skin_lesions": {"ja": "Skin Lesions", "en": "Skin Lesions"},
    "skin_masses": {"ja": "皮膚腫瘤", "en": "Skin masses"},
    "skin_thickening": {"ja": "Skin Thickening", "en": "Skin Thickening"},
    "skin_wounds": {"ja": "Skin Wounds", "en": "Skin Wounds"},
    "soft_bones": {"ja": "Soft Bones", "en": "Soft Bones"},
    "splenomegaly": {"ja": "脾腫", "en": "Splenomegaly"},
    "straining_to_urinate": {"ja": "排尿困難", "en": "Straining to urinate"},
    "stress_signs": {"ja": "Stress Signs", "en": "Stress Signs"},
    "stunted_growth": {"ja": "発育阻害", "en": "Stunted growth"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "swelling_around_cloaca": {"ja": "Swelling Around Cloaca", "en": "Swelling Around Cloaca"},
    "tail_chewing": {"ja": "Tail Chewing", "en": "Tail Chewing"},
    "tail_injury": {"ja": "Tail Injury", "en": "Tail Injury"},
    "tail_tissue_loss": {"ja": "Tail Tissue Loss", "en": "Tail Tissue Loss"},
    "toe_swelling": {"ja": "Toe Swelling", "en": "Toe Swelling"},
    "torn_membrane": {"ja": "Torn Membrane", "en": "Torn Membrane"},
    "unresponsiveness": {"ja": "Unresponsiveness", "en": "Unresponsiveness"},
    "vaginal_bleeding": {"ja": "Vaginal Bleeding", "en": "Vaginal Bleeding"},
    "wound_on_membrane": {"ja": "Wound On Membrane", "en": "Wound On Membrane"},
}


# ---------------------------------------------------------------------------
# Public analysis function
# ---------------------------------------------------------------------------

def analyze_symptoms(
    symptoms: List[str],
    age_stage: str = "",
    breed: str | None = None,
    *,
    onset: str | None = None,
    age_years: float | None = None,
    species: str | None = None,
    lab_values: dict | None = None,
) -> Dict[str, Any]:
    """Run differential diagnosis for sugar gliders based on reported symptoms."""
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species, lab_values=lab_values)
