"""Tortoise and turtle disease dictionary and analysis module.

This module defines a comprehensive list of diseases commonly seen in
tortoises (Testudinidae) and freshwater turtles, and exposes an
``analyze_symptoms`` function that leverages the generic species helper to
produce differential diagnosis results.

The information provided here is for educational purposes only and should
not replace professional veterinary diagnosis and treatment.
"""

from __future__ import annotations

from typing import Any, Dict, List

from . import prevalence_data
from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── Shell Diseases ───────────────────────────────────────────────────
    {
        "name": "Shell Rot (Ulcerative Shell Disease)",
        "name_ja": "甲羅腐敗症",
        "symptoms": {"shell_discoloration", "shell_soft_spots", "foul_odor", "shell_pitting", "anorexia", "lethargy"},
        "description": "Bacterial or fungal infection eroding shell scutes, often from poor water quality or trauma.",
        "description_ja": "不衛生な水質や外傷により甲板が細菌・真菌感染で侵食される疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["shell_exam", "shell_culture", "radiographs"],
    },
    {
        "name": "Septicemic Cutaneous Ulcerative Disease (SCUD)",
        "name_ja": "敗血症性皮膚潰瘍症（SCUD）",
        "symptoms": {"shell_discoloration", "shell_pitting", "skin_ulcers", "lethargy", "anorexia", "skin_hemorrhage"},
        "description": "Severe bacterial shell and skin disease caused by Citrobacter freundii and other gram-negative bacteria in aquatic turtles.",
        "description_ja": "シトロバクター菌などのグラム陰性菌により水棲ガメに重篤な甲羅・皮膚疾患を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["shell_culture", "blood_culture", "complete_blood_count"],
    },
    {
        "name": "Shell Fracture / Trauma",
        "name_ja": "甲羅骨折・外傷",
        "symptoms": {"shell_crack", "bleeding", "shell_displacement", "lethargy", "anorexia"},
        "description": "Fractures from predator attacks, vehicle strikes, falls, or lawn mower injuries.",
        "description_ja": "捕食者の攻撃、車両接触、落下、芝刈り機などによる甲羅の骨折です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "wound_assessment", "complete_blood_count"],
    },
    {
        "name": "Pyramiding",
        "name_ja": "ピラミッディング",
        "symptoms": {"shell_pyramiding", "abnormal_shell_growth"},
        "description": "Abnormal upward growth of scutes caused by excess protein, low humidity, and inadequate UVB.",
        "description_ja": "過剰なタンパク質、低湿度、UVB不足により甲板が異常に隆起する成長異常です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "dietary_review", "husbandry_review"],
    },
    {
        "name": "Soft Shell (Metabolic Bone Disease in Chelonians)",
        "name_ja": "甲羅軟化（カメの代謝性骨疾患）",
        "symptoms": {"soft_shell", "shell_deformity", "weakness", "lethargy", "anorexia", "tremors"},
        "description": "Softening of the shell due to calcium deficiency, phosphorus imbalance, or inadequate UVB exposure.",
        "description_ja": "カルシウム不足、リンの不均衡、UVB不足による甲羅の軟化です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "radiographs", "husbandry_review"],
    },
    # ── Respiratory ──────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Tract Infection (URTI)",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"nasal_discharge", "wheezing", "open_mouth_breathing", "lethargy", "anorexia", "swollen_eyes"},
        "description": "Common bacterial or viral infection of the nasal passages and trachea, often linked to low temperatures.",
        "description_ja": "低温環境に関連する鼻腔・気管の細菌・ウイルス感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "radiographs", "complete_blood_count"],
    },
    {
        "name": "Pneumonia (Lower Respiratory Infection)",
        "name_ja": "肺炎（下部呼吸器感染症）",
        "symptoms": {"open_mouth_breathing", "respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "listing_to_one_side", "bubbling_nose"},
        "description": "Bacterial or fungal infection of the lungs; aquatic turtles may list to one side when swimming.",
        "description_ja": "肺の細菌・真菌感染症で、水棲ガメでは泳ぐ時に片側に傾くことがあります。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "tracheal_wash", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Runny Nose Syndrome (RNS)",
        "name_ja": "ランニーノーズ症候群",
        "symptoms": {"nasal_discharge", "wheezing", "lethargy", "anorexia"},
        "description": "Chronic rhinitis in tortoises often associated with Mycoplasma or herpesvirus infection.",
        "description_ja": "マイコプラズマやヘルペスウイルス感染に関連するリクガメの慢性鼻炎です。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_mycoplasma", "pcr_herpesvirus", "nasal_culture"],
    },
    {
        "name": "Mycoplasmosis (Mycoplasma agassizii / testudineum)",
        "name_ja": "マイコプラズマ症",
        "symptoms": {"nasal_discharge", "wheezing", "swollen_eyes", "lethargy", "anorexia", "conjunctivitis"},
        "description": "Chronic upper respiratory disease caused by Mycoplasma spp., highly prevalent in desert tortoises.",
        "description_ja": "マイコプラズマ属菌による慢性上部呼吸器疾患で、砂漠リクガメに多発します。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_mycoplasma", "elisa_mycoplasma", "nasal_lavage"],
    },
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "weight_loss"},
        "description": "Systemic fungal infection caused by Aspergillus spp. affecting the respiratory tract.",
        "description_ja": "アスペルギルス属真菌による呼吸器の全身性真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "radiographs", "tracheal_wash"],
    },
    # ── Viral Diseases ───────────────────────────────────────────────────
    {
        "name": "Herpesvirus Infection",
        "name_ja": "ヘルペスウイルス感染症",
        "symptoms": {"mouth_lesions", "nasal_discharge", "stomatitis", "conjunctivitis", "anorexia", "lethargy", "sudden_death"},
        "description": "Herpesvirus causing necrotizing stomatitis, rhinitis, and systemic disease in tortoises.",
        "description_ja": "壊死性口内炎、鼻炎、全身性疾患を引き起こすリクガメのヘルペスウイルス感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_herpesvirus", "oral_swab", "liver_function_tests"],
    },
    {
        "name": "Ranavirus Infection",
        "name_ja": "ラナウイルス感染症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "edema", "nasal_discharge", "sudden_death"},
        "description": "Highly pathogenic iridovirus causing systemic hemorrhagic disease, often fatal in chelonians.",
        "description_ja": "カメ類に致死的な全身性出血性疾患を引き起こす高病原性イリドウイルスです。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_ranavirus", "histopathology", "complete_blood_count"],
    },
    {
        "name": "Iridovirus Infection",
        "name_ja": "イリドウイルス感染症",
        "symptoms": {"skin_lesions", "edema", "lethargy", "anorexia", "skin_hemorrhage"},
        "description": "Systemic viral disease caused by iridoviruses, closely related to ranaviruses.",
        "description_ja": "イリドウイルスによる全身性ウイルス疾患で、ラナウイルスと近縁です。",
        "urgency": "high",
        "recommended_tests": ["pcr_iridovirus", "histopathology", "complete_blood_count"],
    },
    {
        "name": "Tortoise Intranuclear Coccidia (TINC)",
        "name_ja": "リクガメ核内コクシジウム症",
        "symptoms": {"nasal_discharge", "anorexia", "lethargy", "weight_loss", "respiratory_distress"},
        "description": "Emerging disease caused by an intranuclear coccidian parasite affecting tortoise kidneys and respiratory tract.",
        "description_ja": "リクガメの腎臓や呼吸器に影響する核内コクシジウム寄生虫による新興疾患です。",
        "urgency": "high",
        "recommended_tests": ["pcr_tinc", "kidney_biopsy", "urinalysis"],
    },
    # ── Parasitic ────────────────────────────────────────────────────────
    {
        "name": "Intestinal Nematodes (Roundworms)",
        "name_ja": "腸管線虫（回虫）感染",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "lethargy"},
        "description": "Gastrointestinal roundworm infection, common in wild-caught and outdoor tortoises.",
        "description_ja": "野生捕獲個体や屋外飼育のリクガメに多い消化管の回虫感染です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Pinworm (Oxyurid) Infection",
        "name_ja": "蟯虫感染",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "straining"},
        "description": "Common oxyurid nematode infection of the large intestine in herbivorous chelonians.",
        "description_ja": "草食性カメ類の大腸に寄生する一般的な蟯虫感染症です。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Hexamita Infection",
        "name_ja": "ヘキサミタ感染症",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "lethargy", "foul_smelling_stool"},
        "description": "Flagellate protozoal infection of the GI tract and kidneys, common in chelonians.",
        "description_ja": "消化管と腎臓に影響する鞭毛虫感染症で、カメ類に多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_exam", "urinalysis"],
    },
    {
        "name": "Flagellate Protozoa Infection",
        "name_ja": "鞭毛虫感染症",
        "symptoms": {"diarrhea", "anorexia", "weight_loss", "lethargy"},
        "description": "Various flagellate protozoal infections of the GI tract causing chronic diarrhea.",
        "description_ja": "消化管の各種鞭毛虫感染により慢性下痢を引き起こす疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_exam"],
    },
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "bloody_stool", "weight_loss", "anorexia", "lethargy"},
        "description": "Protozoal infection by Eimeria or Isospora species affecting the intestinal tract.",
        "description_ja": "アイメリア属やイソスポラ属原虫による腸管の感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "lethargy", "dehydration"},
        "description": "Protozoal infection by Cryptosporidium spp. causing chronic wasting.",
        "description_ja": "クリプトスポリジウム属原虫による慢性消耗性の感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_cryptosporidium", "acid_fast_stain", "fecal_exam"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "マダニ寄生",
        "symptoms": {"visible_parasites", "skin_lesions", "anorexia", "lethargy"},
        "description": "External tick parasitism, especially in wild or outdoor-kept tortoises.",
        "description_ja": "野生または屋外飼育のリクガメに見られる外部マダニ寄生です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "tick_identification"],
    },
    {
        "name": "Myiasis (Fly Strike)",
        "name_ja": "蝿蛆症",
        "symptoms": {"skin_lesions", "visible_larvae", "foul_odor", "lethargy", "anorexia"},
        "description": "Fly larval infestation in wounds or moist skin folds, common in outdoor tortoises.",
        "description_ja": "屋外飼育のリクガメの傷や湿った皮膚のひだにハエの幼虫が寄生する疾患です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment"],
    },
    # ── Metabolic / Nutritional ──────────────────────────────────────────
    {
        "name": "Metabolic Bone Disease (MBD)",
        "name_ja": "代謝性骨疾患（MBD）",
        "symptoms": {"soft_shell", "weakness", "tremors", "lethargy", "shell_deformity", "fractures", "anorexia"},
        "description": "Calcium deficiency and UVB insufficiency causing shell softening and bone weakness.",
        "description_ja": "カルシウム不足とUVB不足により甲羅軟化と骨弱化を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "radiographs", "husbandry_review"],
    },
    {
        "name": "Vitamin A Deficiency (Hypovitaminosis A)",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"swollen_eyes", "conjunctivitis", "nasal_discharge", "respiratory_distress", "anorexia", "skin_lesions"},
        "description": "Dietary vitamin A insufficiency causing eye swelling and respiratory issues, especially in box turtles.",
        "description_ja": "特にハコガメで目の腫脹と呼吸器症状を引き起こすビタミンA不足です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_a_levels", "ophthalmic_exam", "dietary_review"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"tremors", "muscle_twitching", "seizures", "weakness", "lethargy"},
        "description": "Critically low blood calcium causing muscle spasms, especially in egg-laying females.",
        "description_ja": "特に産卵中の雌で筋肉痙攣を引き起こす血中カルシウムの著しい低下です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_calcium", "ionized_calcium", "blood_chemistry"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"soft_shell", "weakness", "lethargy", "anorexia"},
        "description": "Inadequate UVB or dietary vitamin D3 impairing calcium metabolism.",
        "description_ja": "UVBまたは食事性ビタミンD3の不足によりカルシウム代謝が障害される状態です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_d3", "blood_calcium_phosphorus", "husbandry_review"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism",
        "name_ja": "栄養性二次性副甲状腺機能亢進症",
        "symptoms": {"soft_shell", "shell_deformity", "tremors", "fractures", "weakness"},
        "description": "Chronic calcium deficiency causing excess parathyroid hormone and bone resorption.",
        "description_ja": "慢性的なカルシウム不足により副甲状腺ホルモンが過剰分泌され骨吸収が起こる疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "pth_levels", "radiographs"],
    },
    {
        "name": "Chronic Malnutrition",
        "name_ja": "慢性栄養不良",
        "symptoms": {"weight_loss", "weakness", "lethargy", "anorexia", "poor_body_condition"},
        "description": "Prolonged inadequate diet leading to wasting and immune compromise.",
        "description_ja": "長期的な不適切な食事による消耗と免疫低下です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review", "physical_exam"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"excessive_weight", "fat_deposits", "difficulty_retracting", "lethargy"},
        "description": "Excess body fat from overfeeding, predisposing to hepatic lipidosis and organ compression.",
        "description_ja": "過食による過剰な体脂肪蓄積で、脂肪肝や臓器圧迫のリスクがあります。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "body_condition_scoring", "dietary_review"],
    },
    # ── Gastrointestinal ─────────────────────────────────────────────────
    {
        "name": "Gastrointestinal Impaction (Constipation)",
        "name_ja": "消化管閉塞（便秘）",
        "symptoms": {"anorexia", "constipation", "lethargy", "abdominal_swelling", "straining"},
        "description": "Blockage from ingested substrate, stones, or dehydration-related fecal compaction.",
        "description_ja": "床材、石、脱水による糞便の硬化などによる消化管の閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam", "contrast_study"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物誤飲",
        "symptoms": {"anorexia", "constipation", "abdominal_swelling", "lethargy", "regurgitation"},
        "description": "Ingestion of rocks, substrate, or other non-food items causing GI obstruction.",
        "description_ja": "石、床材、その他の非食品の誤飲による消化管閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "contrast_study"],
    },
    {
        "name": "Gastroenteritis",
        "name_ja": "胃腸炎",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "dehydration", "weight_loss"},
        "description": "Inflammation of the GI tract from bacterial, parasitic, or dietary causes.",
        "description_ja": "細菌、寄生虫、食事性の原因による胃腸の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "jaundice", "abdominal_swelling"},
        "description": "Excessive fat deposition in the liver from obesity or prolonged anorexia.",
        "description_ja": "肥満や長期の食欲不振による肝臓への過剰な脂肪沈着です。",
        "urgency": "high",
        "recommended_tests": ["liver_function_tests", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "dehydration"},
        "description": "Salmonella bacterial infection; chelonians are frequent asymptomatic carriers.",
        "description_ja": "サルモネラ菌感染症で、カメ類は無症候性保菌者であることが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "blood_culture", "complete_blood_count"],
    },
    # ── Oral / Stomatitis ────────────────────────────────────────────────
    {
        "name": "Infectious Stomatitis (Mouth Rot)",
        "name_ja": "感染性口内炎（マウスロット）",
        "symptoms": {"mouth_lesions", "swollen_gums", "mucus_in_mouth", "anorexia", "drooling"},
        "description": "Bacterial infection of the beak and oral cavity causing caseous exudate and necrosis.",
        "description_ja": "嘴と口腔の細菌感染により乾酪性浸出液と壊死を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Beak Overgrowth / Malocclusion",
        "name_ja": "嘴の過成長・不正咬合",
        "symptoms": {"difficulty_eating", "beak_overgrowth", "anorexia", "weight_loss"},
        "description": "Abnormal beak growth preventing normal food prehension, often from MBD or poor diet.",
        "description_ja": "MBDや不適切な食事による嘴の異常成長で正常な摂食が困難になる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs", "dietary_review"],
    },
    # ── Eye Diseases ─────────────────────────────────────────────────────
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"swollen_eyes", "eye_discharge", "conjunctivitis", "anorexia"},
        "description": "Inflammation of the conjunctiva, often secondary to vitamin A deficiency or respiratory infection.",
        "description_ja": "ビタミンA欠乏や呼吸器感染に続発する結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "eye_culture", "blood_vitamin_a_levels"],
    },
    {
        "name": "Periocular Abscess",
        "name_ja": "眼周囲膿瘍",
        "symptoms": {"swollen_eyes", "eye_swelling", "anorexia", "lethargy"},
        "description": "Abscess formation around the eye, often linked to hypovitaminosis A in aquatic turtles.",
        "description_ja": "特に水棲ガメでビタミンA欠乏に関連する眼周囲の膿瘍形成です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fine_needle_aspirate", "blood_vitamin_a_levels"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"cloudy_eyes", "eye_discharge", "eye_swelling", "anorexia"},
        "description": "Ulceration of the cornea from trauma, infection, or poor water quality.",
        "description_ja": "外傷、感染、水質不良による角膜の潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "eye_culture"],
    },
    # ── Renal / Urinary ──────────────────────────────────────────────────
    {
        "name": "Renal Failure (Chronic Kidney Disease)",
        "name_ja": "腎不全",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "edema", "gout_tophi"},
        "description": "Progressive kidney failure, very common in captive tortoises due to chronic dehydration.",
        "description_ja": "慢性的な脱水による飼育下リクガメに非常に多い進行性の腎不全です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Bladder Stones (Urolithiasis)",
        "name_ja": "膀胱結石",
        "symptoms": {"straining", "anorexia", "lethargy", "abdominal_swelling", "bloody_urates"},
        "description": "Urate or calcium-based calculi in the urinary bladder, common in desert tortoises.",
        "description_ja": "砂漠リクガメに多い尿酸塩またはカルシウム系の膀胱結石です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "urinalysis"],
    },
    {
        "name": "Articular Gout",
        "name_ja": "関節痛風",
        "symptoms": {"swollen_joints", "joint_pain", "lameness", "lethargy", "anorexia"},
        "description": "Uric acid crystal deposition in joints due to renal dysfunction or dehydration.",
        "description_ja": "腎機能障害や脱水により尿酸結晶が関節に沈着する疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "radiographs", "joint_aspiration"],
    },
    {
        "name": "Visceral Gout",
        "name_ja": "内臓痛風",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "sudden_death"},
        "description": "Uric acid deposition on internal organs, often fatal and associated with renal failure.",
        "description_ja": "内臓表面への尿酸沈着で、腎不全に関連し致死的なことが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    # ── Reproductive ─────────────────────────────────────────────────────
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "卵塞（難産）",
        "symptoms": {"straining", "anorexia", "lethargy", "restlessness", "digging_behavior", "abdominal_swelling"},
        "description": "Inability to lay eggs, caused by calcium deficiency, oversized eggs, or lack of nesting site.",
        "description_ja": "カルシウム不足、過大卵、産卵場所の欠如などにより卵を産めない状態です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "blood_calcium"],
    },
    {
        "name": "Pre-ovulatory Follicular Stasis",
        "name_ja": "排卵前卵胞停滞",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "weight_loss"},
        "description": "Failure of ovarian follicles to ovulate, leading to coelomitis risk.",
        "description_ja": "卵巣卵胞が排卵されず、体腔炎のリスクがある状態です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_chemistry"],
    },
    # ── Dehydration / General ────────────────────────────────────────────
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"sunken_eyes", "wrinkled_skin", "decreased_skin_elasticity", "lethargy", "anorexia", "dry_mucous_membranes"},
        "description": "Chronic water deprivation causing systemic compromise; extremely common in captive tortoises.",
        "description_ja": "飼育下リクガメに非常に多い慢性的な水分不足による全身状態の悪化です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "packed_cell_volume"],
    },
    {
        "name": "Thermal Burns",
        "name_ja": "熱傷",
        "symptoms": {"skin_burns", "shell_burns", "skin_lesions", "anorexia", "lethargy"},
        "description": "Burns from heat lamps, heat mats, or hot surfaces in the enclosure.",
        "description_ja": "ヒートランプ、ヒートマット、ケージ内の高温面による火傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    {
        "name": "Frostbite / Cold Injury",
        "name_ja": "凍傷・低温障害",
        "symptoms": {"skin_discoloration", "skin_necrosis", "lethargy", "anorexia", "limb_swelling"},
        "description": "Tissue damage from exposure to sub-optimal temperatures, especially during outdoor hibernation.",
        "description_ja": "特に屋外冬眠中の低温暴露による組織損傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Improper Hibernation Complications",
        "name_ja": "不適切な冬眠の合併症",
        "symptoms": {"lethargy", "anorexia", "weight_loss", "dehydration", "respiratory_distress"},
        "description": "Health problems arising from improper brumation conditions including dehydration and respiratory infections.",
        "description_ja": "脱水や呼吸器感染を含む不適切な冬眠条件による健康問題です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "complete_blood_count"],
    },
    # ── Septicemia / Systemic ────────────────────────────────────────────
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "petechia", "respiratory_distress", "sudden_death"},
        "description": "Systemic bacterial infection in the bloodstream, a life-threatening emergency.",
        "description_ja": "血流中の全身性細菌感染症で、生命を脅かす緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count", "blood_chemistry"],
    },
    {
        "name": "Abscess (Subcutaneous)",
        "name_ja": "皮下膿瘍",
        "symptoms": {"swelling", "firm_mass", "anorexia", "lethargy"},
        "description": "Encapsulated bacterial infection forming caseous abscesses, common in chelonians.",
        "description_ja": "カメ類に多い被包化された細菌感染による乾酪性膿瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "radiographs"],
    },
    {
        "name": "Aural Abscess (Ear Abscess)",
        "name_ja": "耳膿瘍",
        "symptoms": {"ear_swelling", "head_swelling", "anorexia", "lethargy"},
        "description": "Caseous abscess of the tympanic cavity, common in box turtles and related to vitamin A deficiency.",
        "description_ja": "ハコガメに多いビタミンA欠乏に関連する鼓室の乾酪性膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fine_needle_aspirate", "blood_vitamin_a_levels"],
    },
    # ── Skin / Integument ────────────────────────────────────────────────
    {
        "name": "Dysecdysis (Retained Shed)",
        "name_ja": "脱皮不全",
        "symptoms": {"dysecdysis", "retained_skin", "skin_constriction", "lethargy"},
        "description": "Incomplete shedding of skin around limbs and tail, common in tortoises with low humidity.",
        "description_ja": "低湿度環境のリクガメで四肢や尾の脱皮が不完全になる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    {
        "name": "Bacterial Dermatitis",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_lesions", "skin_redness", "swelling", "foul_odor"},
        "description": "Bacterial skin infection from poor hygiene or wound contamination.",
        "description_ja": "不衛生な環境や傷の汚染による皮膚の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "culture_sensitivity"],
    },
    {
        "name": "Fungal Shell Disease",
        "name_ja": "真菌性甲羅疾患",
        "symptoms": {"shell_discoloration", "white_patches_on_shell", "shell_soft_spots"},
        "description": "Fungal infection of the shell, especially common in aquatic turtles.",
        "description_ja": "特に水棲ガメに多い甲羅の真菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "shell_exam"],
    },
    {
        "name": "Algae Growth on Shell",
        "name_ja": "甲羅の藻類付着",
        "symptoms": {"green_shell_discoloration", "shell_discoloration"},
        "description": "Excessive algae buildup on the shell of aquatic turtles from poor water quality.",
        "description_ja": "水質不良による水棲ガメの甲羅への過度な藻類の蓄積です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "water_quality_test"],
    },
    # ── Prolapse ─────────────────────────────────────────────────────────
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "straining", "anorexia"},
        "description": "Protrusion of cloacal tissue, potentially involving the colon, oviduct, or bladder.",
        "description_ja": "結腸、卵管、膀胱が関与する可能性のある総排泄腔組織の突出です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs", "ultrasound"],
    },
    {
        "name": "Penile Prolapse",
        "name_ja": "陰茎脱出",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "swelling"},
        "description": "Prolapse of the phallus in male chelonians, requiring prompt veterinary attention.",
        "description_ja": "雄のカメ類の陰茎脱出で、迅速な獣医の処置が必要です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    # ── Neoplasia ────────────────────────────────────────────────────────
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"firm_mass", "skin_lesions", "ulcerated_mass", "weight_loss"},
        "description": "Malignant epithelial tumor, one of the more commonly reported neoplasms in chelonians.",
        "description_ja": "カメ類で比較的多く報告される上皮性の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"firm_mass", "swelling", "weight_loss", "lethargy"},
        "description": "Malignant connective tissue tumor occasionally reported in chelonians.",
        "description_ja": "カメ類で時折報告される結合組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    # ── Neurological ─────────────────────────────────────────────────────
    {
        "name": "Neurological Syndrome",
        "name_ja": "神経学的症候群",
        "symptoms": {"neurological_signs", "head_tilt", "circling", "tremors", "seizures"},
        "description": "Neurological dysfunction from metabolic, infectious, toxic, or traumatic causes.",
        "description_ja": "代謝性、感染性、中毒性、外傷性の原因による神経機能障害です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "blood_chemistry", "radiographs"],
    },
    # ── Organ Failure ────────────────────────────────────────────────────
    {
        "name": "Liver Failure (Hepatopathy)",
        "name_ja": "肝不全",
        "symptoms": {"anorexia", "lethargy", "jaundice", "weight_loss", "abdominal_swelling"},
        "description": "Severe liver dysfunction from toxic, infectious, or metabolic causes.",
        "description_ja": "中毒性、感染性、代謝性の原因による重篤な肝機能障害です。",
        "urgency": "emergency",
        "recommended_tests": ["liver_function_tests", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Cardiac Disease",
        "name_ja": "心疾患",
        "symptoms": {"lethargy", "edema", "respiratory_distress", "weakness"},
        "description": "Heart disease including cardiomyopathy, occasionally diagnosed in chelonians.",
        "description_ja": "心筋症を含む心疾患で、カメ類で時折診断されます。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiographs"],
    },
    # ── Miscellaneous ────────────────────────────────────────────────────
    {
        "name": "Hyperthermia (Heat Stroke)",
        "name_ja": "高体温症（熱中症）",
        "symptoms": {"open_mouth_breathing", "lethargy", "weakness", "neurological_signs"},
        "description": "Dangerously elevated body temperature from excessive heat exposure.",
        "description_ja": "過度の熱暴露による危険な体温上昇です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry"],
    },
    {
        "name": "Drowning / Near-Drowning",
        "name_ja": "溺水・溺水ニアミス",
        "symptoms": {"respiratory_distress", "lethargy", "weakness", "bubbling_nose"},
        "description": "Water aspiration in tortoises placed in too-deep water, a life-threatening emergency.",
        "description_ja": "深すぎる水に入れられたリクガメの水吸引で、生命を脅かす緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Trauma / Bite Wounds",
        "name_ja": "外傷・咬傷",
        "symptoms": {"skin_lesions", "bleeding", "shell_crack", "swelling", "anorexia"},
        "description": "Injuries from predators (dogs, raccoons), other tortoises, or environmental hazards.",
        "description_ja": "捕食者（犬、アライグマ）、他のリクガメ、環境危険物による損傷です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Toxicosis (Poisoning)",
        "name_ja": "中毒症",
        "symptoms": {"neurological_signs", "anorexia", "lethargy", "diarrhea", "tremors"},
        "description": "Ingestion of toxic plants, pesticides, or chemicals.",
        "description_ja": "有毒植物、殺虫剤、化学物質の摂取による中毒です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Peritonitis / Coelomitis",
        "name_ja": "腹膜炎・体腔炎",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "pain_response"},
        "description": "Inflammation of the coelomic cavity, often from ruptured eggs or organ perforation.",
        "description_ja": "卵の破裂や臓器穿孔による体腔の炎症です。",
        "urgency": "emergency",
        "recommended_tests": ["coelomic_fluid_analysis", "ultrasound", "blood_chemistry"],
    },
    {
        "name": "Stress Syndrome (Maladaptation)",
        "name_ja": "ストレス症候群（不適応）",
        "symptoms": {"anorexia", "lethargy", "hiding_behavior", "weight_loss"},
        "description": "Chronic stress from recent relocation, improper environment, or social conflict.",
        "description_ja": "移動、不適切な環境、社会的衝突による慢性的ストレスです。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "physical_exam"],
    },
    {
        "name": "Osteomyelitis",
        "name_ja": "骨髄炎",
        "symptoms": {"swelling", "lameness", "anorexia", "lethargy"},
        "description": "Bacterial bone infection, sometimes secondary to shell trauma.",
        "description_ja": "甲羅外傷に続発することもある細菌性の骨感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "bone_culture", "complete_blood_count"],
    },
    # ── Additional Required Diseases ─────────────────────────────────────
    {
        "name": "Rhinitis",
        "name_ja": "鼻炎",
        "symptoms": {"nasal_discharge", "wheezing", "sneezing", "nasal_congestion", "anorexia", "lethargy"},
        "description": "Inflammation of the nasal mucosa from bacterial, viral, or environmental causes.",
        "description_ja": "細菌性、ウイルス性、環境性の原因による鼻粘膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "pcr_mycoplasma", "pcr_herpesvirus", "radiographs"],
    },
    {
        "name": "Hypovitaminosis D",
        "name_ja": "ビタミンD欠乏症（低ビタミンD症）",
        "symptoms": {"soft_shell", "weakness", "lethargy", "anorexia", "shell_deformity", "tremors"},
        "description": "Insufficient vitamin D from lack of UVB exposure or dietary sources, leading to impaired calcium metabolism and MBD.",
        "description_ja": "UVB照射不足や食事からのビタミンD不足によりカルシウム代謝が障害され代謝性骨疾患を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["blood_vitamin_d3", "blood_calcium_phosphorus", "husbandry_review", "radiographs"],
    },
    {
        "name": "Calcium Deficiency (Dietary Hypocalcemia)",
        "name_ja": "カルシウム欠乏症（食事性低カルシウム血症）",
        "symptoms": {"soft_shell", "tremors", "weakness", "muscle_twitching", "anorexia", "fractures"},
        "description": "Dietary calcium insufficiency causing skeletal weakness and neuromuscular dysfunction.",
        "description_ja": "食事中のカルシウム不足により骨格の衰弱と神経筋機能障害を引き起こす状態です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium", "ionized_calcium", "dietary_review", "radiographs"],
    },
    {
        "name": "Fibrous Osteodystrophy",
        "name_ja": "線維性骨異栄養症",
        "symptoms": {"swollen_limbs", "jaw_swelling", "soft_shell", "shell_deformity", "difficulty_eating", "lameness"},
        "description": "Replacement of bone with fibrous connective tissue due to chronic calcium-phosphorus imbalance.",
        "description_ja": "慢性的なカルシウム・リンの不均衡により骨が線維性結合組織に置換される疾患です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "blood_calcium_phosphorus", "pth_levels", "biopsy"],
    },
    {
        "name": "Generalized Edema",
        "name_ja": "全身性浮腫",
        "symptoms": {"edema", "limb_swelling", "periocular_edema", "lethargy", "anorexia", "respiratory_distress"},
        "description": "Diffuse fluid accumulation in subcutaneous tissues, often indicating renal failure, cardiac disease, or hypoproteinemia.",
        "description_ja": "皮下組織への広範な液体貯留で、腎不全、心疾患、低タンパク血症を示唆します。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "blood_uric_acid", "ultrasound", "urinalysis"],
    },
    {
        "name": "Eye Infection (Infectious Ophthalmitis)",
        "name_ja": "眼感染症（感染性眼炎）",
        "symptoms": {"swollen_eyes", "eye_discharge", "cloudy_eyes", "conjunctivitis", "anorexia", "lethargy"},
        "description": "Bacterial or fungal infection of the eye, often secondary to vitamin A deficiency or poor husbandry.",
        "description_ja": "ビタミンA欠乏や飼育管理不良に続発する眼の細菌・真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "eye_culture", "blood_vitamin_a_levels", "fluorescein_stain"],
    },
    {
        "name": "Chronic Anorexia Syndrome",
        "name_ja": "慢性食欲不振症候群",
        "symptoms": {"anorexia", "weight_loss", "lethargy", "dehydration", "poor_body_condition", "hiding_behavior"},
        "description": "Prolonged refusal to eat from multifactorial causes including husbandry errors, stress, and subclinical disease.",
        "description_ja": "飼育管理の不備、ストレス、不顕性疾患などの多因子性原因による長期の食欲不振です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "fecal_exam", "husbandry_review"],
    },
    {
        "name": "Chronic Diarrhea",
        "name_ja": "慢性下痢",
        "symptoms": {"diarrhea", "weight_loss", "dehydration", "foul_smelling_stool", "anorexia", "lethargy"},
        "description": "Persistent loose stools from parasitic, bacterial, dietary, or environmental causes.",
        "description_ja": "寄生虫、細菌、食事、環境の原因による持続性の軟便・下痢です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "fecal_float", "fecal_culture", "blood_chemistry"],
    },
    {
        "name": "Intestinal Prolapse",
        "name_ja": "腸脱出",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "straining", "anorexia", "visible_tissue_from_cloaca"},
        "description": "Protrusion of intestinal tissue through the cloaca, often due to parasitism, enteritis, or straining.",
        "description_ja": "寄生虫、腸炎、いきみなどにより腸組織が総排泄腔から突出する状態です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs", "fecal_exam"],
    },
    {
        "name": "Mite Infestation",
        "name_ja": "ダニ寄生",
        "symptoms": {"visible_parasites", "skin_irritation", "dysecdysis", "lethargy", "anorexia"},
        "description": "Ectoparasitic mite infestation, less common in tortoises than snakes but still encountered.",
        "description_ja": "リクガメではヘビより少ないが、発生する外部寄生性ダニの寄生です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "skin_scraping", "mite_identification"],
    },
    {
        "name": "Leech Infestation",
        "name_ja": "ヒル寄生",
        "symptoms": {"visible_parasites", "skin_lesions", "anorexia", "lethargy", "bleeding"},
        "description": "Aquatic leech parasitism in freshwater turtles, causing blood loss and potential pathogen transmission.",
        "description_ja": "淡水ガメにおけるヒルの寄生で、失血と病原体伝播のリスクがあります。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "complete_blood_count"],
    },
    {
        "name": "Nematode Lung Infection",
        "name_ja": "線虫性肺感染症",
        "symptoms": {"respiratory_distress", "wheezing", "nasal_discharge", "lethargy", "weight_loss"},
        "description": "Lung nematode (Rhabdias spp.) infection causing pneumonia in chelonians.",
        "description_ja": "ラブジアス属線虫による肺感染で、カメ類に肺炎を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["tracheal_wash", "fecal_exam", "radiographs"],
    },
    {
        "name": "Fibropapillomatosis",
        "name_ja": "線維乳頭腫症",
        "symptoms": {"skin_tumors", "firm_mass", "eye_swelling", "weight_loss", "lethargy"},
        "description": "Herpesvirus-associated fibroepithelial tumors, most common in green sea turtles but also reported in freshwater species.",
        "description_ja": "ヘルペスウイルス関連の線維上皮性腫瘍で、アオウミガメに最も多いが淡水種でも報告されます。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "pcr_herpesvirus"],
    },
    {
        "name": "Adenovirus Infection",
        "name_ja": "アデノウイルス感染症",
        "symptoms": {"anorexia", "lethargy", "diarrhea", "nasal_discharge", "sudden_death"},
        "description": "Viral infection causing hepatitis and enteritis in chelonians, often fatal in Sulcata tortoises.",
        "description_ja": "カメ類に肝炎と腸炎を引き起こすウイルス感染症で、ケヅメリクガメで致死的なことが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_adenovirus", "liver_function_tests", "histopathology"],
    },
    {
        "name": "Paramyxovirus Infection",
        "name_ja": "パラミクソウイルス感染症",
        "symptoms": {"nasal_discharge", "respiratory_distress", "neurological_signs", "lethargy", "anorexia"},
        "description": "Viral respiratory and neurological disease, occasionally reported in chelonians.",
        "description_ja": "カメ類で時折報告されるウイルス性呼吸器・神経疾患です。",
        "urgency": "high",
        "recommended_tests": ["pcr_paramyxovirus", "radiographs", "complete_blood_count"],
    },
    {
        "name": "Poxvirus Infection",
        "name_ja": "ポックスウイルス感染症",
        "symptoms": {"skin_lesions", "skin_papules", "lethargy", "anorexia"},
        "description": "Viral skin disease causing papular lesions, reported in various tortoise species.",
        "description_ja": "各種リクガメで報告される丘疹性皮膚病変を引き起こすウイルス性皮膚疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology", "pcr_poxvirus"],
    },
    {
        "name": "Cloacitis",
        "name_ja": "総排泄腔炎",
        "symptoms": {"cloacal_swelling", "straining", "bloody_urates", "foul_odor", "anorexia"},
        "description": "Inflammation or infection of the cloaca from bacterial, parasitic, or traumatic causes.",
        "description_ja": "細菌、寄生虫、外傷による総排泄腔の炎症・感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["cloacal_culture", "fecal_exam", "physical_exam"],
    },
    {
        "name": "Post-hibernation Anorexia",
        "name_ja": "冬眠後食欲不振",
        "symptoms": {"anorexia", "lethargy", "dehydration", "weight_loss", "sunken_eyes"},
        "description": "Failure to resume feeding after brumation, often due to subclinical infection or inadequate hibernation conditions.",
        "description_ja": "冬眠後に摂食を再開できない状態で、不顕性感染や不適切な冬眠条件が原因となることが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "complete_blood_count", "fecal_exam"],
    },
    {
        "name": "Coelomic Effusion (Ascites)",
        "name_ja": "体腔液貯留（腹水）",
        "symptoms": {"abdominal_swelling", "lethargy", "anorexia", "respiratory_distress", "edema"},
        "description": "Accumulation of fluid in the coelomic cavity due to organ failure, infection, or neoplasia.",
        "description_ja": "臓器不全、感染、腫瘍による体腔内の液体貯留です。",
        "urgency": "high",
        "recommended_tests": ["coelomic_fluid_analysis", "ultrasound", "blood_chemistry", "radiographs"],
    },
    {
        "name": "Urinary Tract Infection",
        "name_ja": "尿路感染症",
        "symptoms": {"bloody_urates", "straining", "foul_odor", "anorexia", "lethargy"},
        "description": "Bacterial infection of the urinary bladder or tract, often concurrent with bladder stones.",
        "description_ja": "膀胱結石を伴うことが多い、膀胱・尿路の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["urinalysis", "urine_culture", "ultrasound"],
    },
    {
        "name": "Tracheal Stricture",
        "name_ja": "気管狭窄",
        "symptoms": {"respiratory_distress", "wheezing", "open_mouth_breathing", "stridor"},
        "description": "Narrowing of the trachea from scarring, infection, or congenital defect.",
        "description_ja": "瘢痕、感染、先天性欠損による気管の狭窄です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "endoscopy", "ct_scan"],
    },
    {
        "name": "Hemoparasitism",
        "name_ja": "血液寄生虫症",
        "symptoms": {"lethargy", "anorexia", "weakness", "pale_mucous_membranes"},
        "description": "Blood parasites (Haemoproteus, Hepatozoon) transmitted by arthropod vectors in wild tortoises.",
        "description_ja": "野生リクガメにおいて節足動物媒介で伝播される血液寄生虫（ヘモプロテウス、ヘパトゾーン）感染です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_smear", "complete_blood_count", "pcr_hemoparasite"],
    },
    {
        "name": "Bone Fracture (Limb)",
        "name_ja": "四肢骨折",
        "symptoms": {"lameness", "limb_swelling", "pain_response", "anorexia", "fractures"},
        "description": "Fracture of limb bones from trauma or pathological weakening due to MBD.",
        "description_ja": "外傷やMBDによる病的脆弱化による四肢の骨折です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "blood_calcium_phosphorus", "physical_exam"],
    },
    {
        "name": "Tail Necrosis",
        "name_ja": "尾壊死",
        "symptoms": {"skin_necrosis", "skin_discoloration", "foul_odor", "swelling"},
        "description": "Ischemic necrosis of the tail from retained shed, constriction bands, or bite trauma.",
        "description_ja": "脱皮残り、絞扼帯、咬傷による尾の虚血性壊死です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Scute Shedding Disorder",
        "name_ja": "甲板脱落異常",
        "symptoms": {"abnormal_shell_growth", "shell_discoloration", "shell_soft_spots", "retained_scutes"},
        "description": "Abnormal retention or premature loss of shell scutes from infection, trauma, or husbandry errors.",
        "description_ja": "感染、外傷、飼育管理の不備による甲板の異常な残存または早期脱落です。",
        "urgency": "moderate",
        "recommended_tests": ["shell_exam", "shell_culture", "husbandry_review"],
    },

    # ── 追加疾患 (Additional Diseases) ──
    {
        "name": "Chelonian Herpesvirus Type 1",
        "name_ja": "カメヘルペスウイルス1型",
        "symptoms": {"anorexia", "conjunctivitis", "lethargy", "nasal_discharge", "oral_plaques", "sudden_death"},
        "description": "Highly pathogenic herpesvirus causing severe stomatitis and rhinitis in Mediterranean tortoises.",
        "description_ja": "地中海リクガメに重度の口内炎と鼻炎を引き起こす高病原性ヘルペスウイルス。",
        "urgency": "emergency",
        "recommended_tests": ["PCR_herpesvirus", "oral_swab", "histopathology"],
    },
    {
        "name": "Chelonian Herpesvirus Type 2",
        "name_ja": "カメヘルペスウイルス2型",
        "symptoms": {"anorexia", "lethargy", "nasal_discharge", "oral_lesions"},
        "description": "Second type of chelonian herpesvirus with different host range and pathogenicity.",
        "description_ja": "異なる宿主域と病原性を持つカメヘルペスウイルスの第2型。",
        "urgency": "high",
        "recommended_tests": ["PCR_herpesvirus", "serology", "histopathology"],
    },
    {
        "name": "Mycobacteriosis (Turtle Tuberculosis)",
        "name_ja": "マイコバクテリア症（カメ結核）",
        "symptoms": {"anorexia", "granulomatous_lesions", "lethargy", "respiratory_distress", "weight_loss"},
        "description": "Mycobacterium spp. infection causing granulomatous disease in multiple organs.",
        "description_ja": "マイコバクテリウム属による多臓器肉芽腫性疾患。",
        "urgency": "high",
        "recommended_tests": ["acid_fast_stain", "bacterial_culture", "PCR_mycobacterium", "biopsy"],
    },
    {
        "name": "Chlamydiosis",
        "name_ja": "クラミジア症",
        "symptoms": {"anorexia", "conjunctivitis", "lethargy", "nasal_discharge", "respiratory_distress"},
        "description": "Chlamydia spp. infection causing respiratory and ocular disease.",
        "description_ja": "クラミジア属による呼吸器・眼疾患。",
        "urgency": "high",
        "recommended_tests": ["PCR_chlamydia", "conjunctival_swab", "serology"],
    },
    {
        "name": "Pasteurellosis",
        "name_ja": "パスツレラ症",
        "symptoms": {"lethargy", "nasal_discharge", "respiratory_distress", "sudden_death", "swollen_joints"},
        "description": "Pasteurella testudinis or P. multocida causing septicemia and respiratory disease.",
        "description_ja": "パスツレラ・テストゥディニスまたはP.ムルトシダによる敗血症・呼吸器疾患。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Pseudomonas Infection",
        "name_ja": "緑膿菌感染症",
        "symptoms": {"lethargy", "respiratory_distress", "shell_lesions", "skin_lesions"},
        "description": "Pseudomonas aeruginosa causing shell rot, skin infections, and pneumonia.",
        "description_ja": "緑膿菌による甲羅腐食、皮膚感染、肺炎。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "gram_stain"],
    },
    {
        "name": "Citrobacter Infection",
        "name_ja": "シトロバクター感染症",
        "symptoms": {"lethargy", "septicemia", "shell_rot", "skin_ulceration"},
        "description": "Citrobacter freundii causing SCUD-like shell and skin disease.",
        "description_ja": "シトロバクター・フロインディによるSCUD様甲羅・皮膚疾患。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "shell_biopsy"],
    },
    {
        "name": "Aeromonas Infection",
        "name_ja": "エロモナス感染症",
        "symptoms": {"lethargy", "septicemia", "shell_rot", "skin_lesions", "swollen_limbs"},
        "description": "Aeromonas hydrophila causing shell disease and septicemia in aquatic chelonians.",
        "description_ja": "エロモナス・ハイドロフィラによる水棲ガメの甲羅疾患と敗血症。",
        "urgency": "high",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing", "CBC"],
    },
    {
        "name": "Beneckea Infection",
        "name_ja": "ベネケア感染症",
        "symptoms": {"lethargy", "shell_lesions", "skin_ulceration"},
        "description": "Marine vibrio-like bacteria causing shell disease in sea turtles.",
        "description_ja": "ウミガメの甲羅疾患を引き起こす海洋ビブリオ様細菌。",
        "urgency": "moderate",
        "recommended_tests": ["bacterial_culture", "sensitivity_testing"],
    },
    {
        "name": "Fusarium Shell Infection",
        "name_ja": "フザリウム甲羅感染症",
        "symptoms": {"crusty_shell_lesions", "shell_discoloration", "shell_softening"},
        "description": "Fusarium spp. fungal infection causing progressive shell degradation.",
        "description_ja": "フザリウム属真菌による進行性甲羅劣化。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "shell_biopsy", "cytology"],
    },
    {
        "name": "Geotrichum Infection",
        "name_ja": "ジオトリクム感染症",
        "symptoms": {"lethargy", "shell_lesions", "skin_lesions"},
        "description": "Geotrichum candidum causing cutaneous mycosis in chelonians.",
        "description_ja": "ジオトリクム・カンディダムによるカメの皮膚真菌症。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "skin_scraping", "histopathology"],
    },
    {
        "name": "Spirorchiid Trematode Infection",
        "name_ja": "スピロルキス吸虫感染症",
        "symptoms": {"anorexia", "lethargy", "neurological_signs", "organ_failure", "sudden_death"},
        "description": "Blood flukes causing granulomatous disease in sea turtles and freshwater turtles.",
        "description_ja": "ウミガメ・淡水ガメに肉芽腫性疾患を引き起こす血液吸虫。",
        "urgency": "high",
        "recommended_tests": ["fecal_examination", "histopathology", "blood_smear"],
    },
    {
        "name": "Nematode Gastritis (Atractis / Alaeuris)",
        "name_ja": "線虫性胃炎（アトラクティス・アラエウリス）",
        "symptoms": {"anorexia", "diarrhea", "regurgitation", "weight_loss"},
        "description": "GI nematode infections specific to chelonians causing gastritis and enteritis.",
        "description_ja": "カメ特有の消化管線虫による胃炎と腸炎。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_examination", "endoscopy"],
    },
    {
        "name": "Acanthocephalan Infection",
        "name_ja": "鉤頭虫感染症",
        "symptoms": {"anorexia", "diarrhea", "intestinal_obstruction", "weight_loss"},
        "description": "Thorny-headed worm infestation of the intestinal tract.",
        "description_ja": "鉤頭虫による腸管寄生。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_examination", "radiography", "endoscopy"],
    },
    {
        "name": "Protozoan Colitis",
        "name_ja": "原虫性大腸炎",
        "symptoms": {"bloody_stool", "dehydration", "diarrhea", "lethargy", "weight_loss"},
        "description": "Colonic protozoan overgrowth (Balantidium, Nyctotherus) causing colitis.",
        "description_ja": "結腸原虫（バランチジウム、ニクトテルス）の過増殖による大腸炎。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_smear", "fecal_examination"],
    },
    {
        "name": "Entamoeba Infection",
        "name_ja": "エンタメーバ感染症",
        "symptoms": {"anorexia", "bloody_stool", "diarrhea", "lethargy", "weight_loss"},
        "description": "Entamoeba invadens causing amoebic dysentery, potentially fatal.",
        "description_ja": "エンタメーバ・インバデンスによるアメーバ性赤痢。致死的な場合がある。",
        "urgency": "high",
        "recommended_tests": ["fecal_wet_mount", "fecal_smear", "PCR_entamoeba"],
    },
    {
        "name": "Hemipenal/Penile Necrosis",
        "name_ja": "陰茎壊死",
        "symptoms": {"anorexia", "discoloration", "swelling", "tissue_protruding_from_cloaca"},
        "description": "Necrosis of prolapsed penis due to prolonged exposure, desiccation, or infection.",
        "description_ja": "長時間の脱出・乾燥・感染による陰茎の壊死。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_examination", "bacterial_culture"],
    },
    {
        "name": "Shell Abscess",
        "name_ja": "甲羅膿瘍",
        "symptoms": {"discharge_from_shell", "foul_odor", "lethargy", "shell_swelling"},
        "description": "Localized bacterial infection under shell scutes forming an abscess.",
        "description_ja": "甲板下の局所細菌感染による膿瘍形成。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "bacterial_culture", "shell_examination"],
    },
    {
        "name": "Shell Deformity (Congenital)",
        "name_ja": "甲羅奇形（先天性）",
        "symptoms": {"abnormal_shell_shape", "asymmetric_growth", "difficulty_moving"},
        "description": "Congenital shell malformation from genetics or incubation temperature abnormalities.",
        "description_ja": "遺伝や孵卵温度異常による先天性甲羅奇形。",
        "urgency": "low",
        "recommended_tests": ["radiography", "clinical_examination"],
    },
    {
        "name": "Substrate Impaction",
        "name_ja": "床材インパクション",
        "symptoms": {"abdominal_distension", "anorexia", "constipation", "lethargy", "straining"},
        "description": "GI obstruction from ingestion of substrate materials.",
        "description_ja": "床材の摂取による消化管閉塞。",
        "urgency": "high",
        "recommended_tests": ["radiography", "contrast_study", "palpation"],
    },
    {
        "name": "Egg-related Coelomitis",
        "name_ja": "卵関連体腔炎",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy", "respiratory_distress"},
        "description": "Peritonitis from ruptured follicles or ectopic eggs.",
        "description_ja": "破裂卵胞や異所性卵による腹膜炎。",
        "urgency": "emergency",
        "recommended_tests": ["ultrasound", "coelomocentesis", "blood_chemistry", "CBC"],
    },
    {
        "name": "Follicular Stasis (Chronic)",
        "name_ja": "慢性濾胞停滞",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy", "weight_change"},
        "description": "Chronic retention of pre-ovulatory follicles causing coelomic distension.",
        "description_ja": "排卵前卵胞の慢性停滞による体腔膨大。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiography", "blood_chemistry"],
    },
    {
        "name": "Cloacal Calculi",
        "name_ja": "総排泄腔結石",
        "symptoms": {"anorexia", "cloacal_swelling", "constipation", "straining"},
        "description": "Stone-like concretions in the cloaca causing obstruction.",
        "description_ja": "総排泄腔内の結石による閉塞。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "cloacal_examination", "ultrasound"],
    },
    {
        "name": "Hepatocellular Carcinoma",
        "name_ja": "肝細胞癌",
        "symptoms": {"anorexia", "lethargy", "liver_enlargement", "weight_loss"},
        "description": "Primary malignant liver tumor in chelonians.",
        "description_ja": "カメの原発性悪性肝腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy", "blood_chemistry", "histopathology"],
    },
    {
        "name": "Renal Cell Carcinoma",
        "name_ja": "腎細胞癌",
        "symptoms": {"anorexia", "hind_limb_swelling", "lethargy", "weight_loss"},
        "description": "Malignant kidney neoplasia causing renal enlargement.",
        "description_ja": "腎腫大を引き起こす悪性腎腫瘍。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "biopsy", "blood_chemistry"],
    },
    {
        "name": "Lymphoma",
        "name_ja": "リンパ腫",
        "symptoms": {"anorexia", "lethargy", "organ_enlargement", "weight_loss"},
        "description": "Lymphoid neoplasia affecting multiple organs.",
        "description_ja": "多臓器に影響するリンパ系腫瘍。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "CBC", "blood_chemistry"],
    },
    {
        "name": "Melanoma",
        "name_ja": "メラノーマ",
        "symptoms": {"dark_skin_masses", "skin_lesions", "ulcerated_masses"},
        "description": "Melanocyte-derived neoplasia on skin or shell.",
        "description_ja": "皮膚や甲羅のメラノサイト由来腫瘍。",
        "urgency": "moderate",
        "recommended_tests": ["biopsy", "histopathology", "fine_needle_aspirate"],
    },
    {
        "name": "Osteosarcoma",
        "name_ja": "骨肉腫",
        "symptoms": {"bone_swelling", "fractures", "lameness", "weight_loss"},
        "description": "Malignant bone tumor in chelonians.",
        "description_ja": "カメの悪性骨腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "biopsy", "histopathology"],
    },
    {
        "name": "Chondrosarcoma",
        "name_ja": "軟骨肉腫",
        "symptoms": {"bone_swelling", "lameness", "palpable_mass"},
        "description": "Malignant cartilage neoplasia.",
        "description_ja": "悪性軟骨腫瘍。",
        "urgency": "high",
        "recommended_tests": ["radiography", "biopsy", "histopathology", "CT_scan"],
    },
    {
        "name": "Ovarian Neoplasia",
        "name_ja": "卵巣腫瘍",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy", "reproductive_failure"},
        "description": "Ovarian tumors causing reproductive dysfunction.",
        "description_ja": "卵巣腫瘍による生殖機能障害。",
        "urgency": "moderate",
        "recommended_tests": ["ultrasound", "radiography", "blood_chemistry"],
    },
    {
        "name": "Zinc Toxicosis",
        "name_ja": "亜鉛中毒",
        "symptoms": {"anorexia", "lethargy", "regurgitation", "weight_loss"},
        "description": "Zinc poisoning from ingestion of galvanized hardware.",
        "description_ja": "亜鉛メッキ金属の摂取による中毒。",
        "urgency": "high",
        "recommended_tests": ["blood_zinc_level", "radiography", "blood_chemistry"],
    },
    {
        "name": "Lead Toxicosis",
        "name_ja": "鉛中毒",
        "symptoms": {"anorexia", "lethargy", "neurological_signs", "seizures"},
        "description": "Lead poisoning from ingestion of lead-containing objects.",
        "description_ja": "鉛含有物の摂取による中毒。",
        "urgency": "emergency",
        "recommended_tests": ["blood_lead_level", "radiography", "blood_chemistry"],
    },
    {
        "name": "Ivermectin Toxicosis",
        "name_ja": "イベルメクチン中毒",
        "symptoms": {"blindness", "neurological_signs", "paralysis", "tremors"},
        "description": "Ivermectin overdose particularly dangerous in chelonians.",
        "description_ja": "特にカメに危険なイベルメクチン過剰投与。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_history", "neurological_examination"],
    },
    {
        "name": "Metronidazole Toxicosis",
        "name_ja": "メトロニダゾール中毒",
        "symptoms": {"anorexia", "head_tilt", "neurological_signs", "vestibular_signs"},
        "description": "Metronidazole overdose causing CNS toxicity.",
        "description_ja": "メトロニダゾール過剰投与による中枢神経毒性。",
        "urgency": "high",
        "recommended_tests": ["clinical_history", "neurological_examination"],
    },
    {
        "name": "Plant Toxicity",
        "name_ja": "植物中毒",
        "symptoms": {"anorexia", "diarrhea", "lethargy", "oral_irritation", "tremors"},
        "description": "Ingestion of toxic plants (buttercup, rhododendron, foxglove, etc.).",
        "description_ja": "キンポウゲ、シャクナゲ、ジギタリスなどの有毒植物摂取。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_history", "blood_chemistry", "supportive_care"],
    },
    {
        "name": "Pesticide / Herbicide Exposure",
        "name_ja": "農薬・除草剤暴露",
        "symptoms": {"anorexia", "diarrhea", "lethargy", "seizures", "tremors"},
        "description": "Toxicity from exposure to garden chemicals while grazing.",
        "description_ja": "放牧中の庭園用化学物質への暴露による中毒。",
        "urgency": "emergency",
        "recommended_tests": ["toxicology_screen", "blood_chemistry", "supportive_care"],
    },
    {
        "name": "Hypoglycemia",
        "name_ja": "低血糖症",
        "symptoms": {"collapse", "lethargy", "seizures", "tremors", "weakness"},
        "description": "Dangerously low blood sugar from starvation or hepatic disease.",
        "description_ja": "飢餓や肝疾患による危険な低血糖。",
        "urgency": "emergency",
        "recommended_tests": ["blood_glucose", "blood_chemistry"],
    },
    {
        "name": "Hyperuricemia",
        "name_ja": "高尿酸血症",
        "symptoms": {"anorexia", "lethargy", "swollen_joints", "white_deposits"},
        "description": "Elevated uric acid predisposing to gout, often from renal disease or dehydration.",
        "description_ja": "腎疾患や脱水に伴う高尿酸血症で、痛風の前段階。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "uric_acid", "radiography"],
    },
    {
        "name": "Hypothyroidism",
        "name_ja": "甲状腺機能低下症",
        "symptoms": {"cold_intolerance", "lethargy", "obesity", "slow_growth"},
        "description": "Insufficient thyroid hormone causing metabolic slowdown.",
        "description_ja": "甲状腺ホルモン不足による代謝低下。",
        "urgency": "moderate",
        "recommended_tests": ["thyroid_panel", "blood_chemistry"],
    },
    {
        "name": "UV Light Deficiency",
        "name_ja": "紫外線不足症",
        "symptoms": {"bone_weakness", "lethargy", "poor_appetite", "poor_growth", "soft_shell"},
        "description": "Inadequate UVB exposure causing vitamin D3 deficiency and MBD.",
        "description_ja": "UVB照射不足によるビタミンD3欠乏とMBD。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "vitamin_D3_level", "husbandry_review"],
    },
    {
        "name": "Biotin Deficiency",
        "name_ja": "ビオチン欠乏症",
        "symptoms": {"dermatitis", "poor_shedding", "skin_lesions"},
        "description": "Biotin deficiency causing skin and shedding problems.",
        "description_ja": "ビオチン欠乏による皮膚・脱皮障害。",
        "urgency": "low",
        "recommended_tests": ["dietary_history", "response_to_supplementation"],
    },
    {
        "name": "Protein Deficiency",
        "name_ja": "タンパク質欠乏・栄養不良",
        "symptoms": {"immunosuppression", "lethargy", "muscle_wasting", "weight_loss"},
        "description": "Inadequate protein intake causing muscle wasting and poor growth.",
        "description_ja": "タンパク質不足による筋消耗と成長不良。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_analysis", "blood_chemistry", "albumin_level"],
    },
    {
        "name": "Chronic Dehydration",
        "name_ja": "慢性脱水",
        "symptoms": {"anorexia", "constipation", "lethargy", "sunken_eyes", "wrinkled_skin"},
        "description": "Long-term inadequate hydration causing renal compromise.",
        "description_ja": "長期的な水分不足による腎機能低下。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "PCV", "total_solids"],
    },
    {
        "name": "Nephrocalcinosis",
        "name_ja": "腎石灰沈着症",
        "symptoms": {"anorexia", "hind_limb_weakness", "lethargy", "weight_loss"},
        "description": "Calcium deposition in kidneys from vitamin D excess or chronic renal disease.",
        "description_ja": "ビタミンD過剰や慢性腎疾患による腎臓へのカルシウム沈着。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "radiography", "ultrasound"],
    },
    {
        "name": "Spinal Trauma / Vertebral Fracture",
        "name_ja": "脊椎外傷・椎体骨折",
        "symptoms": {"hind_limb_weakness", "loss_of_tail_function", "paralysis"},
        "description": "Vertebral fracture or luxation causing paresis or paralysis.",
        "description_ja": "椎骨骨折や脱臼による不全麻痺・麻痺。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "CT_scan", "neurological_examination"],
    },
    {
        "name": "Dog/Cat Attack Injuries",
        "name_ja": "犬・猫による咬傷",
        "symptoms": {"hemorrhage", "lethargy", "limb_injury", "shell_damage", "skin_wounds"},
        "description": "Trauma from predator attacks causing shell fractures and soft tissue injuries.",
        "description_ja": "捕食動物の攻撃による甲羅骨折と軟部組織損傷。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "wound_assessment", "bacterial_culture"],
    },
    {
        "name": "Lawnmower Injury",
        "name_ja": "芝刈り機による損傷",
        "symptoms": {"hemorrhage", "lethargy", "limb_amputation", "shell_damage"},
        "description": "Traumatic injuries from garden machinery including shell fractures and limb loss.",
        "description_ja": "庭園用機械による甲羅骨折・四肢喪失を含む外傷。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "wound_assessment", "surgical_consultation"],
    },
    {
        "name": "Corneal Lipidosis",
        "name_ja": "角膜脂質沈着症",
        "symptoms": {"cloudy_eye", "vision_impairment", "white_corneal_deposits"},
        "description": "Lipid deposition in the cornea causing opacity, associated with high-fat diets.",
        "description_ja": "高脂肪食に関連する角膜へのリピド沈着による混濁。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_examination", "blood_lipid_panel", "dietary_review"],
    },
    {
        "name": "Proliferative Osteoarthritis",
        "name_ja": "増殖性骨関節症",
        "symptoms": {"difficulty_moving", "joint_swelling", "lameness", "lethargy"},
        "description": "Degenerative joint disease with bone proliferation causing chronic pain.",
        "description_ja": "骨増殖を伴う変性性関節疾患で慢性疼痛を引き起こす。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "joint_aspirate", "blood_chemistry"],
    },
    {
        "name": "Intestinal Volvulus",
        "name_ja": "腸捻転",
        "symptoms": {"abdominal_distension", "anorexia", "lethargy", "sudden_death"},
        "description": "Twisting of the intestine causing acute obstruction and necrosis.",
        "description_ja": "腸管の捻転による急性閉塞と壊死。",
        "urgency": "emergency",
        "recommended_tests": ["radiography", "ultrasound", "surgical_exploration"],
    },
    {
        "name": "Chronic Respiratory Disease Complex",
        "name_ja": "慢性呼吸器疾患複合",
        "symptoms": {"anorexia", "lethargy", "nasal_discharge", "respiratory_distress", "weight_loss"},
        "description": "Multi-factorial chronic respiratory disease from combined pathogens and husbandry issues.",
        "description_ja": "複合病原体と飼育管理問題による多因子性慢性呼吸器疾患。",
        "urgency": "high",
        "recommended_tests": ["tracheal_wash", "bacterial_culture", "PCR_panel", "radiography"],
    },
    {
        "name": "Anasarca (Generalized Edema)",
        "name_ja": "全身浮腫",
        "symptoms": {"anorexia", "generalized_swelling", "lethargy", "respiratory_distress"},
        "description": "Generalized subcutaneous edema from organ failure.",
        "description_ja": "臓器不全による全身性皮下浮腫。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ultrasound", "radiography"],
    },
    {
        "name": "Disseminated Granulomatous Disease",
        "name_ja": "播種性肉芽腫性疾患",
        "symptoms": {"anorexia", "lethargy", "organ_enlargement", "weight_loss"},
        "description": "Multi-organ granulomatous inflammation from mycobacterial, fungal, or parasitic causes.",
        "description_ja": "マイコバクテリア・真菌・寄生虫による多臓器肉芽腫性炎症。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "acid_fast_stain", "fungal_culture"],
    },
    {
        "name": "Hemolytic Anemia",
        "name_ja": "溶血性貧血",
        "symptoms": {"anorexia", "lethargy", "pale_mucous_membranes", "weakness"},
        "description": "Red blood cell destruction from infection, toxins, or immune-mediated causes.",
        "description_ja": "感染・毒素・免疫介在性原因による赤血球破壊。",
        "urgency": "high",
        "recommended_tests": ["CBC", "blood_smear", "blood_chemistry"],
    },
    {
        "name": "Hemoparasites (Blood Parasites) - Severe",
        "name_ja": "重度血液寄生虫症",
        "symptoms": {"anemia", "anorexia", "lethargy", "organ_enlargement", "weight_loss"},
        "description": "Heavy blood parasite burden (Hemogregarines, Haemogregarina) causing clinical disease.",
        "description_ja": "ヘモグレガリンなどの重度血液寄生虫負荷による臨床疾患。",
        "urgency": "high",
        "recommended_tests": ["blood_smear", "PCR_hemoparasite", "CBC"],
    },
    {
        "name": "Abdominal Wall Hernia",
        "name_ja": "腹壁ヘルニア",
        "symptoms": {"abdominal_swelling", "anorexia", "soft_mass"},
        "description": "Protrusion of coelomic contents through abdominal wall defect.",
        "description_ja": "腹壁欠損部からの体腔内容物の脱出。",
        "urgency": "moderate",
        "recommended_tests": ["radiography", "ultrasound", "clinical_examination"],
    },
    {
        "name": "Vitamin C Deficiency",
        "name_ja": "ビタミンC欠乏症",
        "symptoms": {"lethargy", "poor_wound_healing", "skin_hemorrhage", "swollen_gums"},
        "description": "Vitamin C deficiency, occasionally reported in chelonians.",
        "description_ja": "カメで稀に報告されるビタミンC欠乏症。",
        "urgency": "moderate",
        "recommended_tests": ["dietary_history", "response_to_supplementation"],
    },
    {
        "name": "Scute Dysplasia / Scute Infection",
        "name_ja": "甲板異形成・甲板感染",
        "symptoms": {"abnormal_scute_growth", "discharge_under_scutes", "scute_lifting"},
        "description": "Abnormal scute development or infection under scutes causing lifting and discharge.",
        "description_ja": "甲板の異常発育または甲板下の感染による剥離と排膿。",
        "urgency": "moderate",
        "recommended_tests": ["shell_examination", "bacterial_culture", "radiography"],
    },


    # ── 追加疾患2 (Additional Diseases 2) ──
    {
        "name": "Cutaneous Papilloma",
        "name_ja": "皮膚乳頭腫",
        "symptoms": {"skin_masses", "wart_like_growths"},
        "description": "Benign papillomatous growths on skin, potentially virus-associated.",
        "description_ja": "ウイルス関連の可能性がある皮膚良性乳頭腫。",
        "urgency": "low",
        "recommended_tests": ["biopsy", "histopathology"],
    },
    {
        "name": "Nutritional Osteodystrophy",
        "name_ja": "栄養性骨異栄養症",
        "symptoms": {"bone_deformity", "fractures", "jaw_softening", "weakness"},
        "description": "Bone disease from Ca:P:D3 imbalance distinct from classic MBD presentation.",
        "description_ja": "Ca:P:D3不均衡による骨疾患で、典型的なMBDとは異なる病態。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "radiography", "dietary_review"],
    },
    {
        "name": "Photosensitization Dermatitis",
        "name_ja": "光線過敏性皮膚炎",
        "symptoms": {"dermatitis", "skin_blistering", "skin_redness"},
        "description": "Skin damage from photosensitizing compounds and UV exposure.",
        "description_ja": "光増感物質とUV照射による皮膚損傷。",
        "urgency": "moderate",
        "recommended_tests": ["skin_biopsy", "dietary_history"],
    },
    {
        "name": "Cecal Impaction",
        "name_ja": "盲腸インパクション",
        "symptoms": {"abdominal_distension", "anorexia", "constipation", "lethargy"},
        "description": "Impaction of the cecum with fibrous material or foreign bodies.",
        "description_ja": "繊維質や異物による盲腸のインパクション。",
        "urgency": "high",
        "recommended_tests": ["radiography", "contrast_study", "palpation"],
    },
    {
        "name": "Prolapsed Bladder",
        "name_ja": "膀胱脱",
        "symptoms": {"lethargy", "straining", "tissue_protruding_from_cloaca"},
        "description": "Prolapse of the urinary bladder through the cloaca.",
        "description_ja": "総排泄腔からの膀胱脱出。",
        "urgency": "emergency",
        "recommended_tests": ["clinical_examination", "radiography"],
    },
    {
        "name": "Cystic Calculi (Bladder Stones) - Urate",
        "name_ja": "膀胱結石（尿酸塩型）",
        "symptoms": {"anorexia", "hematuria", "lethargy", "straining"},
        "description": "Urate-based bladder stones from dehydration or high-protein diet.",
        "description_ja": "脱水や高タンパク食による尿酸塩型膀胱結石。",
        "urgency": "high",
        "recommended_tests": ["radiography", "ultrasound", "blood_chemistry", "urinalysis"],
    },
    {
        "name": "Hypervitaminosis A",
        "name_ja": "ビタミンA過剰症",
        "symptoms": {"bone_deformity", "lethargy", "liver_enlargement", "skin_sloughing"},
        "description": "Excessive vitamin A supplementation causing toxicity.",
        "description_ja": "ビタミンA過剰補給による中毒。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "vitamin_A_level", "dietary_review"],
    },
    {
        "name": "Hypervitaminosis D3",
        "name_ja": "ビタミンD3過剰症",
        "symptoms": {"anorexia", "kidney_calcification", "lethargy", "weakness"},
        "description": "Excessive vitamin D3 causing hypercalcemia and tissue calcification.",
        "description_ja": "ビタミンD3過剰による高カルシウム血症と組織石灰化。",
        "urgency": "high",
        "recommended_tests": ["blood_chemistry", "ionized_calcium", "radiography"],
    },

]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "shell_discoloration": {"ja": "甲羅の変色", "en": "Shell discoloration"},
    "shell_soft_spots": {"ja": "甲羅の軟化部", "en": "Shell soft spots"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "shell_pitting": {"ja": "甲羅の陥凹", "en": "Shell pitting"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "skin_ulcers": {"ja": "皮膚潰瘍", "en": "Skin ulcers"},
    "skin_hemorrhage": {"ja": "皮膚出血", "en": "Skin hemorrhage"},
    "shell_crack": {"ja": "甲羅の亀裂", "en": "Shell crack"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "shell_displacement": {"ja": "甲羅の変位", "en": "Shell displacement"},
    "shell_pyramiding": {"ja": "甲羅のピラミッディング", "en": "Shell pyramiding"},
    "abnormal_shell_growth": {"ja": "甲羅の異常成長", "en": "Abnormal shell growth"},
    "soft_shell": {"ja": "甲羅軟化", "en": "Soft shell"},
    "shell_deformity": {"ja": "甲羅変形", "en": "Shell deformity"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "open_mouth_breathing": {"ja": "口を開けて呼吸", "en": "Open-mouth breathing"},
    "swollen_eyes": {"ja": "眼腫脹", "en": "Swollen eyes"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory distress"},
    "listing_to_one_side": {"ja": "片側に傾く", "en": "Listing to one side"},
    "bubbling_nose": {"ja": "鼻からの泡", "en": "Bubbling from nose"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "mouth_lesions": {"ja": "口腔内病変", "en": "Mouth lesions"},
    "stomatitis": {"ja": "口内炎", "en": "Stomatitis"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "foul_smelling_stool": {"ja": "悪臭便", "en": "Foul-smelling stool"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "visible_parasites": {"ja": "肉眼で確認できる寄生虫", "en": "Visible parasites"},
    "visible_larvae": {"ja": "肉眼で確認できる幼虫", "en": "Visible larvae"},
    "muscle_twitching": {"ja": "筋肉のピクつき", "en": "Muscle twitching"},
    "seizures": {"ja": "発作", "en": "Seizures"},
    "skin_burns": {"ja": "皮膚の火傷", "en": "Skin burns"},
    "shell_burns": {"ja": "甲羅の火傷", "en": "Shell burns"},
    "skin_discoloration": {"ja": "皮膚変色", "en": "Skin discoloration"},
    "skin_necrosis": {"ja": "皮膚壊死", "en": "Skin necrosis"},
    "limb_swelling": {"ja": "四肢の腫脹", "en": "Limb swelling"},
    "petechia": {"ja": "点状出血", "en": "Petechiae"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "firm_mass": {"ja": "硬い腫瘤", "en": "Firm mass"},
    "ear_swelling": {"ja": "耳の腫脹", "en": "Ear swelling"},
    "head_swelling": {"ja": "頭部の腫脹", "en": "Head swelling"},
    "dysecdysis": {"ja": "脱皮不全", "en": "Dysecdysis"},
    "retained_skin": {"ja": "残皮", "en": "Retained skin"},
    "skin_constriction": {"ja": "皮膚の絞扼", "en": "Skin constriction"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "white_patches_on_shell": {"ja": "甲羅の白斑", "en": "White patches on shell"},
    "green_shell_discoloration": {"ja": "甲羅の緑変色", "en": "Green shell discoloration"},
    "tissue_prolapse": {"ja": "組織脱出", "en": "Tissue prolapse"},
    "cloacal_swelling": {"ja": "総排泄腔の腫脹", "en": "Cloacal swelling"},
    "swollen_gums": {"ja": "歯肉腫脹", "en": "Swollen gums"},
    "mucus_in_mouth": {"ja": "口腔内粘液", "en": "Mucus in mouth"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "difficulty_eating": {"ja": "摂食困難", "en": "Difficulty eating"},
    "beak_overgrowth": {"ja": "嘴の過成長", "en": "Beak overgrowth"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "gout_tophi": {"ja": "痛風結節", "en": "Gout tophi"},
    "bloody_urates": {"ja": "血性尿酸塩", "en": "Bloody urates"},
    "swollen_joints": {"ja": "関節腫脹", "en": "Swollen joints"},
    "joint_pain": {"ja": "関節痛", "en": "Joint pain"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "digging_behavior": {"ja": "掘る行動", "en": "Digging behavior"},
    "abdominal_swelling": {"ja": "腹部膨満", "en": "Abdominal swelling"},
    "sunken_eyes": {"ja": "眼窩陥没", "en": "Sunken eyes"},
    "wrinkled_skin": {"ja": "しわのある皮膚", "en": "Wrinkled skin"},
    "decreased_skin_elasticity": {"ja": "皮膚弾力低下", "en": "Decreased skin elasticity"},
    "dry_mucous_membranes": {"ja": "粘膜乾燥", "en": "Dry mucous membranes"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "regurgitation": {"ja": "吐出", "en": "Regurgitation"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "neurological_signs": {"ja": "神経学的徴候", "en": "Neurological signs"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "ulcerated_mass": {"ja": "潰瘍化した腫瘤", "en": "Ulcerated mass"},
    "excessive_weight": {"ja": "過体重", "en": "Excessive weight"},
    "fat_deposits": {"ja": "脂肪沈着", "en": "Fat deposits"},
    "difficulty_retracting": {"ja": "手足の引き込み困難", "en": "Difficulty retracting into shell"},
    "poor_body_condition": {"ja": "低体格スコア", "en": "Poor body condition"},
    "hiding_behavior": {"ja": "隠れ行動", "en": "Hiding behavior"},
    "pain_response": {"ja": "疼痛反応", "en": "Pain response"},
    "sneezing": {"ja": "くしゃみ", "en": "Sneezing"},
    "nasal_congestion": {"ja": "鼻づまり", "en": "Nasal congestion"},
    "swollen_limbs": {"ja": "四肢の腫脹", "en": "Swollen limbs"},
    "jaw_swelling": {"ja": "顎の腫脹", "en": "Jaw swelling"},
    "periocular_edema": {"ja": "眼周囲浮腫", "en": "Periocular edema"},
    "visible_tissue_from_cloaca": {"ja": "総排泄腔からの組織露出", "en": "Visible tissue from cloaca"},
    "skin_irritation": {"ja": "皮膚の刺激", "en": "Skin irritation"},
    "skin_tumors": {"ja": "皮膚腫瘍", "en": "Skin tumors"},
    "skin_papules": {"ja": "皮膚丘疹", "en": "Skin papules"},
    "stridor": {"ja": "喘鳴（吸気性）", "en": "Stridor"},
    "pale_mucous_membranes": {"ja": "粘膜蒼白", "en": "Pale mucous membranes"},
    "retained_scutes": {"ja": "甲板の残存", "en": "Retained scutes"},

    # --- 追加症状 (DISEASES内で使用されている未登録項目) ---
    "abdominal_distension": {"ja": "腹部膨満", "en": "Abdominal distension"},
    "abnormal_scute_growth": {"ja": "Abnormal Scute Growth", "en": "Abnormal Scute Growth"},
    "abnormal_shell_shape": {"ja": "Abnormal Shell Shape", "en": "Abnormal Shell Shape"},
    "anemia": {"ja": "貧血", "en": "Anemia"},
    "asymmetric_growth": {"ja": "Asymmetric Growth", "en": "Asymmetric Growth"},
    "blindness": {"ja": "失明", "en": "Blindness"},
    "bone_deformity": {"ja": "骨変形", "en": "Bone deformity"},
    "bone_swelling": {"ja": "骨腫脹", "en": "Bone swelling"},
    "bone_weakness": {"ja": "骨脆弱", "en": "Bone weakness"},
    "cloudy_eye": {"ja": "Cloudy Eye", "en": "Cloudy Eye"},
    "cold_intolerance": {"ja": "Cold Intolerance", "en": "Cold Intolerance"},
    "collapse": {"ja": "虚脱", "en": "Collapse"},
    "crusty_shell_lesions": {"ja": "Crusty Shell Lesions", "en": "Crusty Shell Lesions"},
    "dark_skin_masses": {"ja": "暗色皮膚腫瘤", "en": "Dark skin masses"},
    "dermatitis": {"ja": "皮膚炎", "en": "Dermatitis"},
    "difficulty_moving": {"ja": "Difficulty Moving", "en": "Difficulty Moving"},
    "discharge_from_shell": {"ja": "Discharge From Shell", "en": "Discharge From Shell"},
    "discharge_under_scutes": {"ja": "Discharge Under Scutes", "en": "Discharge Under Scutes"},
    "discoloration": {"ja": "Discoloration", "en": "Discoloration"},
    "generalized_swelling": {"ja": "Generalized Swelling", "en": "Generalized Swelling"},
    "granulomatous_lesions": {"ja": "肉芽腫性病変", "en": "Granulomatous lesions"},
    "hematuria": {"ja": "Hematuria", "en": "Hematuria"},
    "hemorrhage": {"ja": "出血", "en": "Hemorrhage"},
    "hind_limb_swelling": {"ja": "Hind Limb Swelling", "en": "Hind Limb Swelling"},
    "hind_limb_weakness": {"ja": "後肢の衰弱", "en": "Hind limb weakness"},
    "immunosuppression": {"ja": "免疫抑制", "en": "Immunosuppression"},
    "intestinal_obstruction": {"ja": "腸閉塞", "en": "Intestinal obstruction"},
    "jaw_softening": {"ja": "顎軟化", "en": "Jaw softening"},
    "joint_swelling": {"ja": "関節腫脹", "en": "Joint swelling"},
    "kidney_calcification": {"ja": "腎石灰化", "en": "Kidney calcification"},
    "limb_amputation": {"ja": "Limb Amputation", "en": "Limb Amputation"},
    "limb_injury": {"ja": "Limb Injury", "en": "Limb Injury"},
    "liver_enlargement": {"ja": "肝臓腫大", "en": "Liver enlargement"},
    "loss_of_tail_function": {"ja": "Loss Of Tail Function", "en": "Loss Of Tail Function"},
    "muscle_wasting": {"ja": "筋萎縮", "en": "Muscle wasting"},
    "obesity": {"ja": "肥満", "en": "Obesity"},
    "oral_irritation": {"ja": "Oral Irritation", "en": "Oral Irritation"},
    "oral_lesions": {"ja": "口腔内病変", "en": "Oral lesions"},
    "oral_plaques": {"ja": "Oral Plaques", "en": "Oral Plaques"},
    "organ_enlargement": {"ja": "臓器腫大", "en": "Organ enlargement"},
    "organ_failure": {"ja": "Organ Failure", "en": "Organ Failure"},
    "palpable_mass": {"ja": "Palpable Mass", "en": "Palpable Mass"},
    "paralysis": {"ja": "Paralysis", "en": "Paralysis"},
    "poor_appetite": {"ja": "食欲減退", "en": "Poor appetite"},
    "poor_growth": {"ja": "Poor Growth", "en": "Poor Growth"},
    "poor_shedding": {"ja": "脱皮不全", "en": "Poor shedding"},
    "poor_wound_healing": {"ja": "Poor Wound Healing", "en": "Poor Wound Healing"},
    "reproductive_failure": {"ja": "Reproductive Failure", "en": "Reproductive Failure"},
    "scute_lifting": {"ja": "Scute Lifting", "en": "Scute Lifting"},
    "septicemia": {"ja": "敗血症", "en": "Septicemia"},
    "shell_damage": {"ja": "Shell Damage", "en": "Shell Damage"},
    "shell_lesions": {"ja": "Shell Lesions", "en": "Shell Lesions"},
    "shell_rot": {"ja": "甲羅腐敗", "en": "Shell rot"},
    "shell_softening": {"ja": "甲羅軟化", "en": "Shell softening"},
    "shell_swelling": {"ja": "Shell Swelling", "en": "Shell Swelling"},
    "skin_blistering": {"ja": "Skin Blistering", "en": "Skin Blistering"},
    "skin_masses": {"ja": "皮膚腫瘤", "en": "Skin masses"},
    "skin_sloughing": {"ja": "Skin Sloughing", "en": "Skin Sloughing"},
    "skin_ulceration": {"ja": "皮膚潰瘍化", "en": "Skin ulceration"},
    "skin_wounds": {"ja": "Skin Wounds", "en": "Skin Wounds"},
    "slow_growth": {"ja": "Slow Growth", "en": "Slow Growth"},
    "soft_mass": {"ja": "Soft Mass", "en": "Soft Mass"},
    "tissue_protruding_from_cloaca": {"ja": "Tissue Protruding From Cloaca", "en": "Tissue Protruding From Cloaca"},
    "ulcerated_masses": {"ja": "Ulcerated Masses", "en": "Ulcerated Masses"},
    "vestibular_signs": {"ja": "Vestibular Signs", "en": "Vestibular Signs"},
    "vision_impairment": {"ja": "Vision Impairment", "en": "Vision Impairment"},
    "wart_like_growths": {"ja": "疣贅様増殖", "en": "Wart-like growths"},
    "weight_change": {"ja": "Weight Change", "en": "Weight Change"},
    "white_corneal_deposits": {"ja": "White Corneal Deposits", "en": "White Corneal Deposits"},
    "white_deposits": {"ja": "White Deposits", "en": "White Deposits"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None, *, onset: str | None = None, age_years: float | None = None, species: str | None = None, lab_values: dict | None = None, gender=None) -> Dict[str, Any]:
    """Analyze tortoise/turtle symptoms and return suspected diseases.

    Parameters
    ----------
    symptoms:
        A list of symptom identifier strings.
    age_stage:
        Optional age stage descriptor.
    breed:
        Optional species; included for interface compatibility.

    Returns
    -------
    dict
        Analysis result in the standard differential diagnosis format.
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE, onset=onset, age_years=age_years, breed=breed, species=species, lab_values=lab_values, gender=gender, prevalence_map=prevalence_data.SPECIES_PREVALENCE.get("tortoise", {}))
