"""Tortoise and turtle disease dictionary and analysis module.

This module defines a comprehensive list of diseases commonly seen in
tortoises (Testudinidae) and freshwater turtles, and exposes an
``analyze_symptoms`` function that leverages the generic species helper to
produce differential diagnosis results.

The information provided here is for educational purposes only and should
not replace professional veterinary diagnosis and treatment.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .helpers import ADVICE, analyze_symptoms_generic

DISEASES: List[Dict[str, Any]] = [
    # ── Shell Diseases ───────────────────────────────────────────────────
    {
        "name": "Shell Rot (Ulcerative Shell Disease)",
        "name_ja": "甲羅腐敗症",
        "symptoms": {"shell_discoloration", "shell_soft_spots", "foul_odor", "shell_pitting", "anorexia", "lethargy"},
        "description": "Bacterial or fungal infection eroding shell scutes, often from poor water quality or trauma.",
        "description_ja": "不衛生な水質や外傷により甲板が細菌・真菌感染で侵食される疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["shell_exam", "shell_culture", "radiographs"],
    },
    {
        "name": "Septicemic Cutaneous Ulcerative Disease (SCUD)",
        "name_ja": "敗血症性皮膚潰瘍症（SCUD）",
        "symptoms": {"shell_discoloration", "shell_pitting", "skin_ulcers", "lethargy", "anorexia", "skin_hemorrhage"},
        "description": "Severe bacterial shell and skin disease caused by Citrobacter freundii and other gram-negative bacteria in aquatic turtles.",
        "description_ja": "シトロバクター菌などのグラム陰性菌により水棲ガメに重篤な甲羅・皮膚疾患を引き起こします。",
        "urgency": "high",
        "recommended_tests": ["shell_culture", "blood_culture", "complete_blood_count"],
    },
    {
        "name": "Shell Fracture / Trauma",
        "name_ja": "甲羅骨折・外傷",
        "symptoms": {"shell_crack", "bleeding", "shell_displacement", "lethargy", "anorexia"},
        "description": "Fractures from predator attacks, vehicle strikes, falls, or lawn mower injuries.",
        "description_ja": "捕食者の攻撃、車両接触、落下、芝刈り機などによる甲羅の骨折です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "wound_assessment", "complete_blood_count"],
    },
    {
        "name": "Pyramiding",
        "name_ja": "ピラミッディング",
        "symptoms": {"shell_pyramiding", "abnormal_shell_growth"},
        "description": "Abnormal upward growth of scutes caused by excess protein, low humidity, and inadequate UVB.",
        "description_ja": "過剰なタンパク質、低湿度、UVB不足により甲板が異常に隆起する成長異常です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "dietary_review", "husbandry_review"],
    },
    {
        "name": "Soft Shell (Metabolic Bone Disease in Chelonians)",
        "name_ja": "甲羅軟化（カメの代謝性骨疾患）",
        "symptoms": {"soft_shell", "shell_deformity", "weakness", "lethargy", "anorexia", "tremors"},
        "description": "Softening of the shell due to calcium deficiency, phosphorus imbalance, or inadequate UVB exposure.",
        "description_ja": "カルシウム不足、リンの不均衡、UVB不足による甲羅の軟化です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "radiographs", "husbandry_review"],
    },
    # ── Respiratory ──────────────────────────────────────────────────────
    {
        "name": "Upper Respiratory Tract Infection (URTI)",
        "name_ja": "上部呼吸器感染症",
        "symptoms": {"nasal_discharge", "wheezing", "open_mouth_breathing", "lethargy", "anorexia", "swollen_eyes"},
        "description": "Common bacterial or viral infection of the nasal passages and trachea, often linked to low temperatures.",
        "description_ja": "低温環境に関連する鼻腔・気管の細菌・ウイルス感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["nasal_culture", "radiographs", "complete_blood_count"],
    },
    {
        "name": "Pneumonia (Lower Respiratory Infection)",
        "name_ja": "肺炎（下部呼吸器感染症）",
        "symptoms": {"open_mouth_breathing", "respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "listing_to_one_side", "bubbling_nose"},
        "description": "Bacterial or fungal infection of the lungs; aquatic turtles may list to one side when swimming.",
        "description_ja": "肺の細菌・真菌感染症で、水棲ガメでは泳ぐ時に片側に傾くことがあります。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "tracheal_wash", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Runny Nose Syndrome (RNS)",
        "name_ja": "ランニーノーズ症候群",
        "symptoms": {"nasal_discharge", "wheezing", "lethargy", "anorexia"},
        "description": "Chronic rhinitis in tortoises often associated with Mycoplasma or herpesvirus infection.",
        "description_ja": "マイコプラズマやヘルペスウイルス感染に関連するリクガメの慢性鼻炎です。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_mycoplasma", "pcr_herpesvirus", "nasal_culture"],
    },
    {
        "name": "Mycoplasmosis (Mycoplasma agassizii / testudineum)",
        "name_ja": "マイコプラズマ症",
        "symptoms": {"nasal_discharge", "wheezing", "swollen_eyes", "lethargy", "anorexia", "conjunctivitis"},
        "description": "Chronic upper respiratory disease caused by Mycoplasma spp., highly prevalent in desert tortoises.",
        "description_ja": "マイコプラズマ属菌による慢性上部呼吸器疾患で、砂漠リクガメに多発します。",
        "urgency": "moderate",
        "recommended_tests": ["pcr_mycoplasma", "elisa_mycoplasma", "nasal_lavage"],
    },
    {
        "name": "Aspergillosis",
        "name_ja": "アスペルギルス症",
        "symptoms": {"respiratory_distress", "nasal_discharge", "lethargy", "anorexia", "weight_loss"},
        "description": "Systemic fungal infection caused by Aspergillus spp. affecting the respiratory tract.",
        "description_ja": "アスペルギルス属真菌による呼吸器の全身性真菌感染症です。",
        "urgency": "high",
        "recommended_tests": ["fungal_culture", "radiographs", "tracheal_wash"],
    },
    # ── Viral Diseases ───────────────────────────────────────────────────
    {
        "name": "Herpesvirus Infection",
        "name_ja": "ヘルペスウイルス感染症",
        "symptoms": {"mouth_lesions", "nasal_discharge", "stomatitis", "conjunctivitis", "anorexia", "lethargy", "sudden_death"},
        "description": "Herpesvirus causing necrotizing stomatitis, rhinitis, and systemic disease in tortoises.",
        "description_ja": "壊死性口内炎、鼻炎、全身性疾患を引き起こすリクガメのヘルペスウイルス感染症です。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_herpesvirus", "oral_swab", "liver_function_tests"],
    },
    {
        "name": "Ranavirus Infection",
        "name_ja": "ラナウイルス感染症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "edema", "nasal_discharge", "sudden_death"},
        "description": "Highly pathogenic iridovirus causing systemic hemorrhagic disease, often fatal in chelonians.",
        "description_ja": "カメ類に致死的な全身性出血性疾患を引き起こす高病原性イリドウイルスです。",
        "urgency": "emergency",
        "recommended_tests": ["pcr_ranavirus", "histopathology", "complete_blood_count"],
    },
    {
        "name": "Iridovirus Infection",
        "name_ja": "イリドウイルス感染症",
        "symptoms": {"skin_lesions", "edema", "lethargy", "anorexia", "skin_hemorrhage"},
        "description": "Systemic viral disease caused by iridoviruses, closely related to ranaviruses.",
        "description_ja": "イリドウイルスによる全身性ウイルス疾患で、ラナウイルスと近縁です。",
        "urgency": "high",
        "recommended_tests": ["pcr_iridovirus", "histopathology", "complete_blood_count"],
    },
    {
        "name": "Tortoise Intranuclear Coccidia (TINC)",
        "name_ja": "リクガメ核内コクシジウム症",
        "symptoms": {"nasal_discharge", "anorexia", "lethargy", "weight_loss", "respiratory_distress"},
        "description": "Emerging disease caused by an intranuclear coccidian parasite affecting tortoise kidneys and respiratory tract.",
        "description_ja": "リクガメの腎臓や呼吸器に影響する核内コクシジウム寄生虫による新興疾患です。",
        "urgency": "high",
        "recommended_tests": ["pcr_tinc", "kidney_biopsy", "urinalysis"],
    },
    # ── Parasitic ────────────────────────────────────────────────────────
    {
        "name": "Intestinal Nematodes (Roundworms)",
        "name_ja": "腸管線虫（回虫）感染",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "lethargy"},
        "description": "Gastrointestinal roundworm infection, common in wild-caught and outdoor tortoises.",
        "description_ja": "野生捕獲個体や屋外飼育のリクガメに多い消化管の回虫感染です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Pinworm (Oxyurid) Infection",
        "name_ja": "蟯虫感染",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "straining"},
        "description": "Common oxyurid nematode infection of the large intestine in herbivorous chelonians.",
        "description_ja": "草食性カメ類の大腸に寄生する一般的な蟯虫感染症です。",
        "urgency": "low",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Hexamita Infection",
        "name_ja": "ヘキサミタ感染症",
        "symptoms": {"diarrhea", "weight_loss", "anorexia", "lethargy", "foul_smelling_stool"},
        "description": "Flagellate protozoal infection of the GI tract and kidneys, common in chelonians.",
        "description_ja": "消化管と腎臓に影響する鞭毛虫感染症で、カメ類に多く見られます。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_exam", "urinalysis"],
    },
    {
        "name": "Flagellate Protozoa Infection",
        "name_ja": "鞭毛虫感染症",
        "symptoms": {"diarrhea", "anorexia", "weight_loss", "lethargy"},
        "description": "Various flagellate protozoal infections of the GI tract causing chronic diarrhea.",
        "description_ja": "消化管の各種鞭毛虫感染により慢性下痢を引き起こす疾患です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_wet_mount", "fecal_exam"],
    },
    {
        "name": "Coccidia Infection",
        "name_ja": "コクシジウム症",
        "symptoms": {"diarrhea", "bloody_stool", "weight_loss", "anorexia", "lethargy"},
        "description": "Protozoal infection by Eimeria or Isospora species affecting the intestinal tract.",
        "description_ja": "アイメリア属やイソスポラ属原虫による腸管の感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_float", "fecal_exam"],
    },
    {
        "name": "Cryptosporidiosis",
        "name_ja": "クリプトスポリジウム症",
        "symptoms": {"weight_loss", "diarrhea", "anorexia", "lethargy", "dehydration"},
        "description": "Protozoal infection by Cryptosporidium spp. causing chronic wasting.",
        "description_ja": "クリプトスポリジウム属原虫による慢性消耗性の感染症です。",
        "urgency": "high",
        "recommended_tests": ["pcr_cryptosporidium", "acid_fast_stain", "fecal_exam"],
    },
    {
        "name": "Tick Infestation",
        "name_ja": "マダニ寄生",
        "symptoms": {"visible_parasites", "skin_lesions", "anorexia", "lethargy"},
        "description": "External tick parasitism, especially in wild or outdoor-kept tortoises.",
        "description_ja": "野生または屋外飼育のリクガメに見られる外部マダニ寄生です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "tick_identification"],
    },
    {
        "name": "Myiasis (Fly Strike)",
        "name_ja": "蝿蛆症",
        "symptoms": {"skin_lesions", "visible_larvae", "foul_odor", "lethargy", "anorexia"},
        "description": "Fly larval infestation in wounds or moist skin folds, common in outdoor tortoises.",
        "description_ja": "屋外飼育のリクガメの傷や湿った皮膚のひだにハエの幼虫が寄生する疾患です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment"],
    },
    # ── Metabolic / Nutritional ──────────────────────────────────────────
    {
        "name": "Metabolic Bone Disease (MBD)",
        "name_ja": "代謝性骨疾患（MBD）",
        "symptoms": {"soft_shell", "weakness", "tremors", "lethargy", "shell_deformity", "fractures", "anorexia"},
        "description": "Calcium deficiency and UVB insufficiency causing shell softening and bone weakness.",
        "description_ja": "カルシウム不足とUVB不足により甲羅軟化と骨弱化を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "radiographs", "husbandry_review"],
    },
    {
        "name": "Vitamin A Deficiency (Hypovitaminosis A)",
        "name_ja": "ビタミンA欠乏症",
        "symptoms": {"swollen_eyes", "conjunctivitis", "nasal_discharge", "respiratory_distress", "anorexia", "skin_lesions"},
        "description": "Dietary vitamin A insufficiency causing eye swelling and respiratory issues, especially in box turtles.",
        "description_ja": "特にハコガメで目の腫脹と呼吸器症状を引き起こすビタミンA不足です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_a_levels", "ophthalmic_exam", "dietary_review"],
    },
    {
        "name": "Hypocalcemia",
        "name_ja": "低カルシウム血症",
        "symptoms": {"tremors", "muscle_twitching", "seizures", "weakness", "lethargy"},
        "description": "Critically low blood calcium causing muscle spasms, especially in egg-laying females.",
        "description_ja": "特に産卵中の雌で筋肉痙攣を引き起こす血中カルシウムの著しい低下です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_calcium", "ionized_calcium", "blood_chemistry"],
    },
    {
        "name": "Vitamin D3 Deficiency",
        "name_ja": "ビタミンD3欠乏症",
        "symptoms": {"soft_shell", "weakness", "lethargy", "anorexia"},
        "description": "Inadequate UVB or dietary vitamin D3 impairing calcium metabolism.",
        "description_ja": "UVBまたは食事性ビタミンD3の不足によりカルシウム代謝が障害される状態です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_vitamin_d3", "blood_calcium_phosphorus", "husbandry_review"],
    },
    {
        "name": "Nutritional Secondary Hyperparathyroidism",
        "name_ja": "栄養性二次性副甲状腺機能亢進症",
        "symptoms": {"soft_shell", "shell_deformity", "tremors", "fractures", "weakness"},
        "description": "Chronic calcium deficiency causing excess parathyroid hormone and bone resorption.",
        "description_ja": "慢性的なカルシウム不足により副甲状腺ホルモンが過剰分泌され骨吸収が起こる疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_calcium_phosphorus", "pth_levels", "radiographs"],
    },
    {
        "name": "Chronic Malnutrition",
        "name_ja": "慢性栄養不良",
        "symptoms": {"weight_loss", "weakness", "lethargy", "anorexia", "poor_body_condition"},
        "description": "Prolonged inadequate diet leading to wasting and immune compromise.",
        "description_ja": "長期的な不適切な食事による消耗と免疫低下です。",
        "urgency": "moderate",
        "recommended_tests": ["blood_chemistry", "dietary_review", "physical_exam"],
    },
    {
        "name": "Obesity",
        "name_ja": "肥満",
        "symptoms": {"excessive_weight", "fat_deposits", "difficulty_retracting", "lethargy"},
        "description": "Excess body fat from overfeeding, predisposing to hepatic lipidosis and organ compression.",
        "description_ja": "過食による過剰な体脂肪蓄積で、脂肪肝や臓器圧迫のリスクがあります。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "body_condition_scoring", "dietary_review"],
    },
    # ── Gastrointestinal ─────────────────────────────────────────────────
    {
        "name": "Gastrointestinal Impaction (Constipation)",
        "name_ja": "消化管閉塞（便秘）",
        "symptoms": {"anorexia", "constipation", "lethargy", "abdominal_swelling", "straining"},
        "description": "Blockage from ingested substrate, stones, or dehydration-related fecal compaction.",
        "description_ja": "床材、石、脱水による糞便の硬化などによる消化管の閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "physical_exam", "contrast_study"],
    },
    {
        "name": "Foreign Body Ingestion",
        "name_ja": "異物誤飲",
        "symptoms": {"anorexia", "constipation", "abdominal_swelling", "lethargy", "regurgitation"},
        "description": "Ingestion of rocks, substrate, or other non-food items causing GI obstruction.",
        "description_ja": "石、床材、その他の非食品の誤飲による消化管閉塞です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "contrast_study"],
    },
    {
        "name": "Gastroenteritis",
        "name_ja": "胃腸炎",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "dehydration", "weight_loss"},
        "description": "Inflammation of the GI tract from bacterial, parasitic, or dietary causes.",
        "description_ja": "細菌、寄生虫、食事性の原因による胃腸の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Hepatic Lipidosis (Fatty Liver Disease)",
        "name_ja": "肝リピドーシス（脂肪肝）",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "jaundice", "abdominal_swelling"},
        "description": "Excessive fat deposition in the liver from obesity or prolonged anorexia.",
        "description_ja": "肥満や長期の食欲不振による肝臓への過剰な脂肪沈着です。",
        "urgency": "high",
        "recommended_tests": ["liver_function_tests", "ultrasound", "liver_biopsy"],
    },
    {
        "name": "Salmonellosis",
        "name_ja": "サルモネラ症",
        "symptoms": {"diarrhea", "anorexia", "lethargy", "dehydration"},
        "description": "Salmonella bacterial infection; chelonians are frequent asymptomatic carriers.",
        "description_ja": "サルモネラ菌感染症で、カメ類は無症候性保菌者であることが多いです。",
        "urgency": "moderate",
        "recommended_tests": ["fecal_culture", "blood_culture", "complete_blood_count"],
    },
    # ── Oral / Stomatitis ────────────────────────────────────────────────
    {
        "name": "Infectious Stomatitis (Mouth Rot)",
        "name_ja": "感染性口内炎（マウスロット）",
        "symptoms": {"mouth_lesions", "swollen_gums", "mucus_in_mouth", "anorexia", "drooling"},
        "description": "Bacterial infection of the beak and oral cavity causing caseous exudate and necrosis.",
        "description_ja": "嘴と口腔の細菌感染により乾酪性浸出液と壊死を引き起こす疾患です。",
        "urgency": "high",
        "recommended_tests": ["oral_exam", "culture_sensitivity", "complete_blood_count"],
    },
    {
        "name": "Beak Overgrowth / Malocclusion",
        "name_ja": "嘴の過成長・不正咬合",
        "symptoms": {"difficulty_eating", "beak_overgrowth", "anorexia", "weight_loss"},
        "description": "Abnormal beak growth preventing normal food prehension, often from MBD or poor diet.",
        "description_ja": "MBDや不適切な食事による嘴の異常成長で正常な摂食が困難になる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "radiographs", "dietary_review"],
    },
    # ── Eye Diseases ─────────────────────────────────────────────────────
    {
        "name": "Conjunctivitis",
        "name_ja": "結膜炎",
        "symptoms": {"swollen_eyes", "eye_discharge", "conjunctivitis", "anorexia"},
        "description": "Inflammation of the conjunctiva, often secondary to vitamin A deficiency or respiratory infection.",
        "description_ja": "ビタミンA欠乏や呼吸器感染に続発する結膜の炎症です。",
        "urgency": "moderate",
        "recommended_tests": ["ophthalmic_exam", "eye_culture", "blood_vitamin_a_levels"],
    },
    {
        "name": "Periocular Abscess",
        "name_ja": "眼周囲膿瘍",
        "symptoms": {"swollen_eyes", "eye_swelling", "anorexia", "lethargy"},
        "description": "Abscess formation around the eye, often linked to hypovitaminosis A in aquatic turtles.",
        "description_ja": "特に水棲ガメでビタミンA欠乏に関連する眼周囲の膿瘍形成です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fine_needle_aspirate", "blood_vitamin_a_levels"],
    },
    {
        "name": "Corneal Ulcer",
        "name_ja": "角膜潰瘍",
        "symptoms": {"cloudy_eyes", "eye_discharge", "eye_swelling", "anorexia"},
        "description": "Ulceration of the cornea from trauma, infection, or poor water quality.",
        "description_ja": "外傷、感染、水質不良による角膜の潰瘍です。",
        "urgency": "high",
        "recommended_tests": ["ophthalmic_exam", "fluorescein_stain", "eye_culture"],
    },
    # ── Renal / Urinary ──────────────────────────────────────────────────
    {
        "name": "Renal Failure (Chronic Kidney Disease)",
        "name_ja": "腎不全",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "edema", "gout_tophi"},
        "description": "Progressive kidney failure, very common in captive tortoises due to chronic dehydration.",
        "description_ja": "慢性的な脱水による飼育下リクガメに非常に多い進行性の腎不全です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Bladder Stones (Urolithiasis)",
        "name_ja": "膀胱結石",
        "symptoms": {"straining", "anorexia", "lethargy", "abdominal_swelling", "bloody_urates"},
        "description": "Urate or calcium-based calculi in the urinary bladder, common in desert tortoises.",
        "description_ja": "砂漠リクガメに多い尿酸塩またはカルシウム系の膀胱結石です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "ultrasound", "urinalysis"],
    },
    {
        "name": "Articular Gout",
        "name_ja": "関節痛風",
        "symptoms": {"swollen_joints", "joint_pain", "lameness", "lethargy", "anorexia"},
        "description": "Uric acid crystal deposition in joints due to renal dysfunction or dehydration.",
        "description_ja": "腎機能障害や脱水により尿酸結晶が関節に沈着する疾患です。",
        "urgency": "high",
        "recommended_tests": ["blood_uric_acid", "radiographs", "joint_aspiration"],
    },
    {
        "name": "Visceral Gout",
        "name_ja": "内臓痛風",
        "symptoms": {"anorexia", "lethargy", "weight_loss", "dehydration", "sudden_death"},
        "description": "Uric acid deposition on internal organs, often fatal and associated with renal failure.",
        "description_ja": "内臓表面への尿酸沈着で、腎不全に関連し致死的なことが多いです。",
        "urgency": "emergency",
        "recommended_tests": ["blood_uric_acid", "blood_chemistry", "ultrasound"],
    },
    # ── Reproductive ─────────────────────────────────────────────────────
    {
        "name": "Egg Binding (Dystocia)",
        "name_ja": "卵塞（難産）",
        "symptoms": {"straining", "anorexia", "lethargy", "restlessness", "digging_behavior", "abdominal_swelling"},
        "description": "Inability to lay eggs, caused by calcium deficiency, oversized eggs, or lack of nesting site.",
        "description_ja": "カルシウム不足、過大卵、産卵場所の欠如などにより卵を産めない状態です。",
        "urgency": "emergency",
        "recommended_tests": ["radiographs", "ultrasound", "blood_calcium"],
    },
    {
        "name": "Pre-ovulatory Follicular Stasis",
        "name_ja": "排卵前卵胞停滞",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "weight_loss"},
        "description": "Failure of ovarian follicles to ovulate, leading to coelomitis risk.",
        "description_ja": "卵巣卵胞が排卵されず、体腔炎のリスクがある状態です。",
        "urgency": "high",
        "recommended_tests": ["ultrasound", "radiographs", "blood_chemistry"],
    },
    # ── Dehydration / General ────────────────────────────────────────────
    {
        "name": "Dehydration",
        "name_ja": "脱水症",
        "symptoms": {"sunken_eyes", "wrinkled_skin", "decreased_skin_elasticity", "lethargy", "anorexia", "dry_mucous_membranes"},
        "description": "Chronic water deprivation causing systemic compromise; extremely common in captive tortoises.",
        "description_ja": "飼育下リクガメに非常に多い慢性的な水分不足による全身状態の悪化です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "packed_cell_volume"],
    },
    {
        "name": "Thermal Burns",
        "name_ja": "熱傷",
        "symptoms": {"skin_burns", "shell_burns", "skin_lesions", "anorexia", "lethargy"},
        "description": "Burns from heat lamps, heat mats, or hot surfaces in the enclosure.",
        "description_ja": "ヒートランプ、ヒートマット、ケージ内の高温面による火傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "wound_assessment", "husbandry_review"],
    },
    {
        "name": "Frostbite / Cold Injury",
        "name_ja": "凍傷・低温障害",
        "symptoms": {"skin_discoloration", "skin_necrosis", "lethargy", "anorexia", "limb_swelling"},
        "description": "Tissue damage from exposure to sub-optimal temperatures, especially during outdoor hibernation.",
        "description_ja": "特に屋外冬眠中の低温暴露による組織損傷です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Improper Hibernation Complications",
        "name_ja": "不適切な冬眠の合併症",
        "symptoms": {"lethargy", "anorexia", "weight_loss", "dehydration", "respiratory_distress"},
        "description": "Health problems arising from improper brumation conditions including dehydration and respiratory infections.",
        "description_ja": "脱水や呼吸器感染を含む不適切な冬眠条件による健康問題です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "blood_chemistry", "complete_blood_count"],
    },
    # ── Septicemia / Systemic ────────────────────────────────────────────
    {
        "name": "Septicemia",
        "name_ja": "敗血症",
        "symptoms": {"lethargy", "anorexia", "skin_hemorrhage", "petechia", "respiratory_distress", "sudden_death"},
        "description": "Systemic bacterial infection in the bloodstream, a life-threatening emergency.",
        "description_ja": "血流中の全身性細菌感染症で、生命を脅かす緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_culture", "complete_blood_count", "blood_chemistry"],
    },
    {
        "name": "Abscess (Subcutaneous)",
        "name_ja": "皮下膿瘍",
        "symptoms": {"swelling", "firm_mass", "anorexia", "lethargy"},
        "description": "Encapsulated bacterial infection forming caseous abscesses, common in chelonians.",
        "description_ja": "カメ類に多い被包化された細菌感染による乾酪性膿瘍です。",
        "urgency": "moderate",
        "recommended_tests": ["fine_needle_aspirate", "culture_sensitivity", "radiographs"],
    },
    {
        "name": "Aural Abscess (Ear Abscess)",
        "name_ja": "耳膿瘍",
        "symptoms": {"ear_swelling", "head_swelling", "anorexia", "lethargy"},
        "description": "Caseous abscess of the tympanic cavity, common in box turtles and related to vitamin A deficiency.",
        "description_ja": "ハコガメに多いビタミンA欠乏に関連する鼓室の乾酪性膿瘍です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam", "fine_needle_aspirate", "blood_vitamin_a_levels"],
    },
    # ── Skin / Integument ────────────────────────────────────────────────
    {
        "name": "Dysecdysis (Retained Shed)",
        "name_ja": "脱皮不全",
        "symptoms": {"dysecdysis", "retained_skin", "skin_constriction", "lethargy"},
        "description": "Incomplete shedding of skin around limbs and tail, common in tortoises with low humidity.",
        "description_ja": "低湿度環境のリクガメで四肢や尾の脱皮が不完全になる状態です。",
        "urgency": "moderate",
        "recommended_tests": ["physical_exam", "husbandry_review"],
    },
    {
        "name": "Bacterial Dermatitis",
        "name_ja": "細菌性皮膚炎",
        "symptoms": {"skin_lesions", "skin_redness", "swelling", "foul_odor"},
        "description": "Bacterial skin infection from poor hygiene or wound contamination.",
        "description_ja": "不衛生な環境や傷の汚染による皮膚の細菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["skin_culture", "culture_sensitivity"],
    },
    {
        "name": "Fungal Shell Disease",
        "name_ja": "真菌性甲羅疾患",
        "symptoms": {"shell_discoloration", "white_patches_on_shell", "shell_soft_spots"},
        "description": "Fungal infection of the shell, especially common in aquatic turtles.",
        "description_ja": "特に水棲ガメに多い甲羅の真菌感染症です。",
        "urgency": "moderate",
        "recommended_tests": ["fungal_culture", "shell_exam"],
    },
    {
        "name": "Algae Growth on Shell",
        "name_ja": "甲羅の藻類付着",
        "symptoms": {"green_shell_discoloration", "shell_discoloration"},
        "description": "Excessive algae buildup on the shell of aquatic turtles from poor water quality.",
        "description_ja": "水質不良による水棲ガメの甲羅への過度な藻類の蓄積です。",
        "urgency": "low",
        "recommended_tests": ["physical_exam", "water_quality_test"],
    },
    # ── Prolapse ─────────────────────────────────────────────────────────
    {
        "name": "Cloacal Prolapse",
        "name_ja": "総排泄腔脱",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "straining", "anorexia"},
        "description": "Protrusion of cloacal tissue, potentially involving the colon, oviduct, or bladder.",
        "description_ja": "結腸、卵管、膀胱が関与する可能性のある総排泄腔組織の突出です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs", "ultrasound"],
    },
    {
        "name": "Penile Prolapse",
        "name_ja": "陰茎脱出",
        "symptoms": {"tissue_prolapse", "cloacal_swelling", "swelling"},
        "description": "Prolapse of the phallus in male chelonians, requiring prompt veterinary attention.",
        "description_ja": "雄のカメ類の陰茎脱出で、迅速な獣医の処置が必要です。",
        "urgency": "high",
        "recommended_tests": ["physical_exam"],
    },
    # ── Neoplasia ────────────────────────────────────────────────────────
    {
        "name": "Squamous Cell Carcinoma",
        "name_ja": "扁平上皮癌",
        "symptoms": {"firm_mass", "skin_lesions", "ulcerated_mass", "weight_loss"},
        "description": "Malignant epithelial tumor, one of the more commonly reported neoplasms in chelonians.",
        "description_ja": "カメ類で比較的多く報告される上皮性の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    {
        "name": "Fibrosarcoma",
        "name_ja": "線維肉腫",
        "symptoms": {"firm_mass", "swelling", "weight_loss", "lethargy"},
        "description": "Malignant connective tissue tumor occasionally reported in chelonians.",
        "description_ja": "カメ類で時折報告される結合組織の悪性腫瘍です。",
        "urgency": "high",
        "recommended_tests": ["biopsy", "histopathology", "radiographs"],
    },
    # ── Neurological ─────────────────────────────────────────────────────
    {
        "name": "Neurological Syndrome",
        "name_ja": "神経学的症候群",
        "symptoms": {"neurological_signs", "head_tilt", "circling", "tremors", "seizures"},
        "description": "Neurological dysfunction from metabolic, infectious, toxic, or traumatic causes.",
        "description_ja": "代謝性、感染性、中毒性、外傷性の原因による神経機能障害です。",
        "urgency": "high",
        "recommended_tests": ["neurological_exam", "blood_chemistry", "radiographs"],
    },
    # ── Organ Failure ────────────────────────────────────────────────────
    {
        "name": "Liver Failure (Hepatopathy)",
        "name_ja": "肝不全",
        "symptoms": {"anorexia", "lethargy", "jaundice", "weight_loss", "abdominal_swelling"},
        "description": "Severe liver dysfunction from toxic, infectious, or metabolic causes.",
        "description_ja": "中毒性、感染性、代謝性の原因による重篤な肝機能障害です。",
        "urgency": "emergency",
        "recommended_tests": ["liver_function_tests", "blood_chemistry", "ultrasound"],
    },
    {
        "name": "Cardiac Disease",
        "name_ja": "心疾患",
        "symptoms": {"lethargy", "edema", "respiratory_distress", "weakness"},
        "description": "Heart disease including cardiomyopathy, occasionally diagnosed in chelonians.",
        "description_ja": "心筋症を含む心疾患で、カメ類で時折診断されます。",
        "urgency": "high",
        "recommended_tests": ["echocardiography", "radiographs"],
    },
    # ── Miscellaneous ────────────────────────────────────────────────────
    {
        "name": "Hyperthermia (Heat Stroke)",
        "name_ja": "高体温症（熱中症）",
        "symptoms": {"open_mouth_breathing", "lethargy", "weakness", "neurological_signs"},
        "description": "Dangerously elevated body temperature from excessive heat exposure.",
        "description_ja": "過度の熱暴露による危険な体温上昇です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "blood_chemistry"],
    },
    {
        "name": "Drowning / Near-Drowning",
        "name_ja": "溺水・溺水ニアミス",
        "symptoms": {"respiratory_distress", "lethargy", "weakness", "bubbling_nose"},
        "description": "Water aspiration in tortoises placed in too-deep water, a life-threatening emergency.",
        "description_ja": "深すぎる水に入れられたリクガメの水吸引で、生命を脅かす緊急事態です。",
        "urgency": "emergency",
        "recommended_tests": ["physical_exam", "radiographs"],
    },
    {
        "name": "Trauma / Bite Wounds",
        "name_ja": "外傷・咬傷",
        "symptoms": {"skin_lesions", "bleeding", "shell_crack", "swelling", "anorexia"},
        "description": "Injuries from predators (dogs, raccoons), other tortoises, or environmental hazards.",
        "description_ja": "捕食者（犬、アライグマ）、他のリクガメ、環境危険物による損傷です。",
        "urgency": "moderate",
        "recommended_tests": ["wound_assessment", "radiographs", "culture_sensitivity"],
    },
    {
        "name": "Toxicosis (Poisoning)",
        "name_ja": "中毒症",
        "symptoms": {"neurological_signs", "anorexia", "lethargy", "diarrhea", "tremors"},
        "description": "Ingestion of toxic plants, pesticides, or chemicals.",
        "description_ja": "有毒植物、殺虫剤、化学物質の摂取による中毒です。",
        "urgency": "emergency",
        "recommended_tests": ["blood_chemistry", "toxicology_screen"],
    },
    {
        "name": "Peritonitis / Coelomitis",
        "name_ja": "腹膜炎・体腔炎",
        "symptoms": {"abdominal_swelling", "anorexia", "lethargy", "pain_response"},
        "description": "Inflammation of the coelomic cavity, often from ruptured eggs or organ perforation.",
        "description_ja": "卵の破裂や臓器穿孔による体腔の炎症です。",
        "urgency": "emergency",
        "recommended_tests": ["coelomic_fluid_analysis", "ultrasound", "blood_chemistry"],
    },
    {
        "name": "Stress Syndrome (Maladaptation)",
        "name_ja": "ストレス症候群（不適応）",
        "symptoms": {"anorexia", "lethargy", "hiding_behavior", "weight_loss"},
        "description": "Chronic stress from recent relocation, improper environment, or social conflict.",
        "description_ja": "移動、不適切な環境、社会的衝突による慢性的ストレスです。",
        "urgency": "low",
        "recommended_tests": ["husbandry_review", "physical_exam"],
    },
    {
        "name": "Osteomyelitis",
        "name_ja": "骨髄炎",
        "symptoms": {"swelling", "lameness", "anorexia", "lethargy"},
        "description": "Bacterial bone infection, sometimes secondary to shell trauma.",
        "description_ja": "甲羅外傷に続発することもある細菌性の骨感染症です。",
        "urgency": "high",
        "recommended_tests": ["radiographs", "bone_culture", "complete_blood_count"],
    },
]

SYMPTOM_NAMES: Dict[str, Dict[str, str]] = {
    "shell_discoloration": {"ja": "甲羅の変色", "en": "Shell discoloration"},
    "shell_soft_spots": {"ja": "甲羅の軟化部", "en": "Shell soft spots"},
    "foul_odor": {"ja": "悪臭", "en": "Foul odor"},
    "shell_pitting": {"ja": "甲羅の陥凹", "en": "Shell pitting"},
    "anorexia": {"ja": "食欲不振", "en": "Anorexia"},
    "lethargy": {"ja": "無気力", "en": "Lethargy"},
    "skin_ulcers": {"ja": "皮膚潰瘍", "en": "Skin ulcers"},
    "skin_hemorrhage": {"ja": "皮膚出血", "en": "Skin hemorrhage"},
    "shell_crack": {"ja": "甲羅の亀裂", "en": "Shell crack"},
    "bleeding": {"ja": "出血", "en": "Bleeding"},
    "shell_displacement": {"ja": "甲羅の変位", "en": "Shell displacement"},
    "shell_pyramiding": {"ja": "甲羅のピラミッディング", "en": "Shell pyramiding"},
    "abnormal_shell_growth": {"ja": "甲羅の異常成長", "en": "Abnormal shell growth"},
    "soft_shell": {"ja": "甲羅軟化", "en": "Soft shell"},
    "shell_deformity": {"ja": "甲羅変形", "en": "Shell deformity"},
    "weakness": {"ja": "衰弱", "en": "Weakness"},
    "tremors": {"ja": "振戦", "en": "Tremors"},
    "fractures": {"ja": "骨折", "en": "Fractures"},
    "nasal_discharge": {"ja": "鼻水", "en": "Nasal discharge"},
    "wheezing": {"ja": "喘鳴", "en": "Wheezing"},
    "open_mouth_breathing": {"ja": "口を開けて呼吸", "en": "Open-mouth breathing"},
    "swollen_eyes": {"ja": "眼腫脹", "en": "Swollen eyes"},
    "respiratory_distress": {"ja": "呼吸困難", "en": "Respiratory distress"},
    "listing_to_one_side": {"ja": "片側に傾く", "en": "Listing to one side"},
    "bubbling_nose": {"ja": "鼻からの泡", "en": "Bubbling from nose"},
    "conjunctivitis": {"ja": "結膜炎", "en": "Conjunctivitis"},
    "mouth_lesions": {"ja": "口腔内病変", "en": "Mouth lesions"},
    "stomatitis": {"ja": "口内炎", "en": "Stomatitis"},
    "sudden_death": {"ja": "突然死", "en": "Sudden death"},
    "skin_lesions": {"ja": "皮膚病変", "en": "Skin lesions"},
    "edema": {"ja": "浮腫", "en": "Edema"},
    "weight_loss": {"ja": "体重減少", "en": "Weight loss"},
    "diarrhea": {"ja": "下痢", "en": "Diarrhea"},
    "foul_smelling_stool": {"ja": "悪臭便", "en": "Foul-smelling stool"},
    "bloody_stool": {"ja": "血便", "en": "Bloody stool"},
    "dehydration": {"ja": "脱水", "en": "Dehydration"},
    "straining": {"ja": "いきみ", "en": "Straining"},
    "visible_parasites": {"ja": "肉眼で確認できる寄生虫", "en": "Visible parasites"},
    "visible_larvae": {"ja": "肉眼で確認できる幼虫", "en": "Visible larvae"},
    "muscle_twitching": {"ja": "筋肉のピクつき", "en": "Muscle twitching"},
    "seizures": {"ja": "発作", "en": "Seizures"},
    "skin_burns": {"ja": "皮膚の火傷", "en": "Skin burns"},
    "shell_burns": {"ja": "甲羅の火傷", "en": "Shell burns"},
    "skin_discoloration": {"ja": "皮膚変色", "en": "Skin discoloration"},
    "skin_necrosis": {"ja": "皮膚壊死", "en": "Skin necrosis"},
    "limb_swelling": {"ja": "四肢の腫脹", "en": "Limb swelling"},
    "petechia": {"ja": "点状出血", "en": "Petechiae"},
    "swelling": {"ja": "腫脹", "en": "Swelling"},
    "firm_mass": {"ja": "硬い腫瘤", "en": "Firm mass"},
    "ear_swelling": {"ja": "耳の腫脹", "en": "Ear swelling"},
    "head_swelling": {"ja": "頭部の腫脹", "en": "Head swelling"},
    "dysecdysis": {"ja": "脱皮不全", "en": "Dysecdysis"},
    "retained_skin": {"ja": "残皮", "en": "Retained skin"},
    "skin_constriction": {"ja": "皮膚の絞扼", "en": "Skin constriction"},
    "skin_redness": {"ja": "皮膚の発赤", "en": "Skin redness"},
    "white_patches_on_shell": {"ja": "甲羅の白斑", "en": "White patches on shell"},
    "green_shell_discoloration": {"ja": "甲羅の緑変色", "en": "Green shell discoloration"},
    "tissue_prolapse": {"ja": "組織脱出", "en": "Tissue prolapse"},
    "cloacal_swelling": {"ja": "総排泄腔の腫脹", "en": "Cloacal swelling"},
    "swollen_gums": {"ja": "歯肉腫脹", "en": "Swollen gums"},
    "mucus_in_mouth": {"ja": "口腔内粘液", "en": "Mucus in mouth"},
    "drooling": {"ja": "流涎", "en": "Drooling"},
    "difficulty_eating": {"ja": "摂食困難", "en": "Difficulty eating"},
    "beak_overgrowth": {"ja": "嘴の過成長", "en": "Beak overgrowth"},
    "eye_discharge": {"ja": "眼脂", "en": "Eye discharge"},
    "eye_swelling": {"ja": "眼の腫脹", "en": "Eye swelling"},
    "cloudy_eyes": {"ja": "眼の白濁", "en": "Cloudy eyes"},
    "gout_tophi": {"ja": "痛風結節", "en": "Gout tophi"},
    "bloody_urates": {"ja": "血性尿酸塩", "en": "Bloody urates"},
    "swollen_joints": {"ja": "関節腫脹", "en": "Swollen joints"},
    "joint_pain": {"ja": "関節痛", "en": "Joint pain"},
    "lameness": {"ja": "跛行", "en": "Lameness"},
    "restlessness": {"ja": "落ち着きのなさ", "en": "Restlessness"},
    "digging_behavior": {"ja": "掘る行動", "en": "Digging behavior"},
    "abdominal_swelling": {"ja": "腹部膨満", "en": "Abdominal swelling"},
    "sunken_eyes": {"ja": "眼窩陥没", "en": "Sunken eyes"},
    "wrinkled_skin": {"ja": "しわのある皮膚", "en": "Wrinkled skin"},
    "decreased_skin_elasticity": {"ja": "皮膚弾力低下", "en": "Decreased skin elasticity"},
    "dry_mucous_membranes": {"ja": "粘膜乾燥", "en": "Dry mucous membranes"},
    "constipation": {"ja": "便秘", "en": "Constipation"},
    "regurgitation": {"ja": "吐出", "en": "Regurgitation"},
    "jaundice": {"ja": "黄疸", "en": "Jaundice"},
    "neurological_signs": {"ja": "神経学的徴候", "en": "Neurological signs"},
    "head_tilt": {"ja": "斜頸", "en": "Head tilt"},
    "circling": {"ja": "旋回", "en": "Circling"},
    "ulcerated_mass": {"ja": "潰瘍化した腫瘤", "en": "Ulcerated mass"},
    "excessive_weight": {"ja": "過体重", "en": "Excessive weight"},
    "fat_deposits": {"ja": "脂肪沈着", "en": "Fat deposits"},
    "difficulty_retracting": {"ja": "手足の引き込み困難", "en": "Difficulty retracting into shell"},
    "poor_body_condition": {"ja": "低体格スコア", "en": "Poor body condition"},
    "hiding_behavior": {"ja": "隠れ行動", "en": "Hiding behavior"},
    "pain_response": {"ja": "疼痛反応", "en": "Pain response"},
}


def analyze_symptoms(symptoms: List[str], age_stage: str = "", breed: str | None = None) -> Dict[str, Any]:
    """Analyze tortoise/turtle symptoms and return suspected diseases.

    Parameters
    ----------
    symptoms:
        A list of symptom identifier strings.
    age_stage:
        Optional age stage descriptor.
    breed:
        Optional species; included for interface compatibility.

    Returns
    -------
    dict
        Analysis result in the standard differential diagnosis format.
    """
    return analyze_symptoms_generic(symptoms, DISEASES, SYMPTOM_NAMES, ADVICE)
