"""drug_interactions.py - 薬品-薬品相互作用データベース

獣医臨床で重要な薬品相互作用を網羅。重症度3段階（contraindicated/major/moderate）。

参考文献:
- Plumb's Veterinary Drug Handbook 9th ed.
- BSAVA Small Animal Formulary 10th ed.
- Stockley's Drug Interactions
- Lexicomp Veterinary
"""

from __future__ import annotations

from typing import Any

# 重症度
SEVERITY_CONTRAINDICATED = "contraindicated"  # 禁忌（同時投与禁止）
SEVERITY_MAJOR = "major"  # 重大（特別な監視・用量調整必須）
SEVERITY_MODERATE = "moderate"  # 中等度（注意して使用）

# ---------------------------------------------------------------------------
# 相互作用テーブル
# 各エントリ: drug_a, drug_b は薬品ID（小文字スネークケース）
# ---------------------------------------------------------------------------
INTERACTIONS: list[dict[str, Any]] = [
    # ====== NSAID 関連 ======
    {
        "drug_a": "meloxicam",
        "drug_b": "carprofen",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "COX阻害の重複",
        "effect_en": "Concurrent NSAIDs significantly increase risk of GI ulceration, perforation, and renal toxicity.",
        "effect_ja": "NSAIDsの併用により消化管潰瘍・穿孔・腎毒性のリスクが著しく増加。",
        "management_en": "Do not use concurrently. Wait at least 5-7 days washout when switching NSAIDs.",
        "management_ja": "併用禁忌。NSAID変更時は5-7日のウォッシュアウト期間を設ける。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "meloxicam",
        "drug_b": "prednisolone",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "胃腸粘膜保護の二重阻害",
        "effect_en": "NSAID + corticosteroid combination dramatically increases GI ulceration and bleeding risk.",
        "effect_ja": "NSAIDとコルチコステロイドの併用は消化管潰瘍・出血リスクを劇的に増加。",
        "management_en": "Do not combine. If steroid required, discontinue NSAID first with washout.",
        "management_ja": "併用禁忌。ステロイド必要時はNSAIDを中止しウォッシュアウト後に切替。",
        "ref": "AAHA 2020",
    },
    {
        "drug_a": "carprofen",
        "drug_b": "prednisolone",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "胃腸粘膜保護の二重阻害",
        "effect_en": "NSAID + corticosteroid combination dramatically increases GI ulceration and bleeding risk.",
        "effect_ja": "NSAIDとコルチコステロイドの併用は消化管潰瘍・出血リスクを劇的に増加。",
        "management_en": "Do not combine.",
        "management_ja": "併用禁忌。",
        "ref": "AAHA 2020",
    },
    {
        "drug_a": "meloxicam",
        "drug_b": "furosemide",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎血流低下の相加作用",
        "effect_en": "NSAIDs reduce renal prostaglandin synthesis; combined with diuretic-induced volume depletion increases acute kidney injury risk.",
        "effect_ja": "NSAIDによる腎プロスタグランジン合成抑制と利尿薬の脱水で急性腎障害リスク増加。",
        "management_en": "Monitor BUN/creatinine, ensure hydration. Avoid in dehydrated/azotemic patients.",
        "management_ja": "BUN/クレアチニン監視、水和維持。脱水・高窒素血症患者では回避。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "carprofen",
        "drug_b": "enalapril",
        "severity": SEVERITY_MAJOR,
        "mechanism": "ACE阻害薬の腎保護作用減弱",
        "effect_en": "NSAIDs blunt the antihypertensive and renoprotective effects of ACE inhibitors; risk of AKI in CHF/CKD.",
        "effect_ja": "NSAIDがACE阻害薬の降圧・腎保護作用を減弱。CHF/CKDで急性腎障害リスク。",
        "management_en": "Monitor renal function. Avoid in heart failure or chronic kidney disease.",
        "management_ja": "腎機能監視。心不全・慢性腎臓病では回避。",
        "ref": "ACVIM Cardiac Consensus 2019",
    },
    # ====== α2作動薬 関連 ======
    {
        "drug_a": "medetomidine",
        "drug_b": "atipamezole",
        "severity": SEVERITY_MODERATE,
        "mechanism": "α2拮抗（意図的逆転）",
        "effect_en": "Atipamezole reverses sedation and cardiovascular effects of α2 agonists. Intended interaction.",
        "effect_ja": "アチパメゾールはα2作動薬の鎮静・循環作用を拮抗。意図的相互作用（覚醒剤）。",
        "management_en": "Use as reversal agent. Equal volume IM to medetomidine dose given.",
        "management_ja": "拮抗薬として使用。投与したメデトミジンと同容量をIM。",
        "ref": "Lumb & Jones 5th ed.",
    },
    {
        "drug_a": "medetomidine",
        "drug_b": "epinephrine",
        "severity": SEVERITY_MAJOR,
        "mechanism": "α受容体への競合",
        "effect_en": "α2 agonist + epinephrine may cause severe vasoconstriction, hypertension, and ventricular arrhythmias.",
        "effect_ja": "α2作動薬とエピネフリン併用で重度血管収縮・高血圧・心室性不整脈の可能性。",
        "management_en": "Avoid combination. If epinephrine needed for anaphylaxis, use lowest effective dose.",
        "management_ja": "併用回避。アナフィラキシー時のエピネフリン投与は最小有効用量で。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== アミノグリコシド ======
    {
        "drug_a": "gentamicin",
        "drug_b": "furosemide",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎毒性・耳毒性の相加",
        "effect_en": "Loop diuretic + aminoglycoside synergistically increases nephrotoxicity and ototoxicity.",
        "effect_ja": "ループ利尿薬とアミノグリコシドの併用は相乗的に腎毒性・耳毒性を増加。",
        "management_en": "Avoid concurrent use. If unavoidable, monitor renal function and trough levels closely.",
        "management_ja": "併用回避。やむを得ない場合は腎機能とトラフ濃度を厳重監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "amikacin",
        "drug_b": "furosemide",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎毒性・耳毒性の相加",
        "effect_en": "Loop diuretic + aminoglycoside synergistically increases nephrotoxicity and ototoxicity.",
        "effect_ja": "ループ利尿薬とアミノグリコシドの併用は相乗的に腎毒性・耳毒性を増加。",
        "management_en": "Avoid concurrent use.",
        "management_ja": "併用回避。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "gentamicin",
        "drug_b": "cefazolin",
        "severity": SEVERITY_MODERATE,
        "mechanism": "シナジー（意図的併用）",
        "effect_en": "Synergistic gram-positive + gram-negative coverage. Common surgical prophylaxis combination.",
        "effect_ja": "グラム陽性+陰性の相乗的抗菌スペクトル。周術期予防の一般的併用。",
        "management_en": "Beneficial combination. Monitor renal function for prolonged courses.",
        "management_ja": "有益な併用。長期投与時は腎機能監視。",
        "ref": "BSAVA 10th ed.",
    },
    # ====== フッ化キノロン ======
    {
        "drug_a": "enrofloxacin",
        "drug_b": "theophylline",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP1A2阻害によるテオフィリンクリアランス低下",
        "effect_en": "Fluoroquinolones inhibit theophylline metabolism, leading to elevated levels and toxicity (seizures, arrhythmias).",
        "effect_ja": "フルオロキノロンがテオフィリン代謝を阻害→中毒（痙攣、不整脈）。",
        "management_en": "Reduce theophylline dose by 50% or use alternative antibiotic.",
        "management_ja": "テオフィリン50%減量、または代替抗菌薬を使用。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "enrofloxacin",
        "drug_b": "sucralfate",
        "severity": SEVERITY_MAJOR,
        "mechanism": "GI内でキレート形成",
        "effect_en": "Sucralfate (and antacids, dairy) chelates fluoroquinolones, reducing absorption by >50%.",
        "effect_ja": "スクラルファート（制酸薬・乳製品）がフルオロキノロンとキレート形成し吸収>50%低下。",
        "management_en": "Separate administration by at least 2 hours.",
        "management_ja": "投与間隔を2時間以上空ける。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== トラマドール / セロトニン症候群 ======
    {
        "drug_a": "tramadol",
        "drug_b": "fluoxetine",
        "severity": SEVERITY_MAJOR,
        "mechanism": "セロトニン症候群リスク",
        "effect_en": "Both increase serotonergic activity; combination may cause serotonin syndrome (agitation, hyperthermia, seizures).",
        "effect_ja": "両薬剤がセロトニン作動性活性を増加→セロトニン症候群（興奮、高体温、痙攣）。",
        "management_en": "Avoid combination. If essential, monitor closely for serotonergic signs.",
        "management_ja": "併用回避。必須の場合はセロトニン症候群の徴候を厳重監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "tramadol",
        "drug_b": "selegiline",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "MAO-B阻害+セロトニン作動性",
        "effect_en": "MAOI + serotonergic agent → severe serotonin syndrome risk.",
        "effect_ja": "MAOIとセロトニン作動薬の併用で重度セロトニン症候群リスク。",
        "management_en": "Contraindicated. Allow 14-day washout when switching.",
        "management_ja": "併用禁忌。切替時は14日のウォッシュアウト期間。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== オピオイド ======
    {
        "drug_a": "morphine",
        "drug_b": "acepromazine",
        "severity": SEVERITY_MODERATE,
        "mechanism": "鎮静・呼吸抑制の相加",
        "effect_en": "Common premedication combination. Synergistic sedation and analgesia, but increased respiratory depression risk.",
        "effect_ja": "一般的な前麻酔併用。鎮静・鎮痛は相乗的だが呼吸抑制リスク増加。",
        "management_en": "Useful combination at appropriate doses. Reduce individual doses 25-50%.",
        "management_ja": "適切な用量で有用。個々の用量を25-50%減量。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== 心臓薬 ======
    {
        "drug_a": "digoxin",
        "drug_b": "furosemide",
        "severity": SEVERITY_MAJOR,
        "mechanism": "低カリウム血症によるジゴキシン感受性増加",
        "effect_en": "Furosemide-induced hypokalemia increases digoxin toxicity risk (arrhythmias).",
        "effect_ja": "フロセミドによる低K血症がジゴキシン中毒リスクを増加（不整脈）。",
        "management_en": "Monitor serum potassium and digoxin levels regularly. Supplement K+ as needed.",
        "management_ja": "血清K+とジゴキシン濃度を定期監視。必要に応じKCl補給。",
        "ref": "ACVIM Cardiac Consensus 2019",
    },
    {
        "drug_a": "digoxin",
        "drug_b": "amiodarone",
        "severity": SEVERITY_MAJOR,
        "mechanism": "ジゴキシンクリアランス低下",
        "effect_en": "Amiodarone increases serum digoxin levels by 70-100%.",
        "effect_ja": "アミオダロンがジゴキシン血中濃度を70-100%上昇。",
        "management_en": "Reduce digoxin dose by 50%. Monitor levels.",
        "management_ja": "ジゴキシン50%減量。血中濃度監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 抗痙攣薬 ======
    {
        "drug_a": "phenobarbital",
        "drug_b": "chloramphenicol",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP誘導 vs 阻害",
        "effect_en": "Chloramphenicol inhibits phenobarbital metabolism → toxicity. Phenobarbital induces metabolism of many drugs.",
        "effect_ja": "クロラムフェニコールがフェノバルビタール代謝を阻害→中毒。",
        "management_en": "Avoid combination. Monitor phenobarbital levels if essential.",
        "management_ja": "併用回避。必須の場合はフェノバルビタール血中濃度監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 鎮静拮抗 ======
    {
        "drug_a": "midazolam",
        "drug_b": "flumazenil",
        "severity": SEVERITY_MODERATE,
        "mechanism": "ベンゾジアゼピン拮抗（意図的）",
        "effect_en": "Flumazenil reverses benzodiazepine effects. Intended interaction.",
        "effect_ja": "フルマゼニルはベンゾジアゼピンを拮抗。意図的相互作用。",
        "management_en": "Use as reversal. Risk of resedation due to short half-life of flumazenil.",
        "management_ja": "拮抗薬として使用。フルマゼニル半減期短く再鎮静リスク。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== ステロイド長期 ======
    {
        "drug_a": "prednisolone",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "免疫抑制の相加",
        "effect_en": "Combined immunosuppression increases infection risk and may potentiate ciclosporin toxicity.",
        "effect_ja": "免疫抑制の相加で感染リスク増加、シクロスポリン毒性増強の可能性。",
        "management_en": "Use lowest effective doses. Monitor for infections, BUN/Cr.",
        "management_ja": "最小有効用量で使用。感染、BUN/Crを監視。",
        "ref": "BSAVA 10th ed.",
    },
    # ====== ペニシリン系（小型草食獣禁忌） ======
    {
        "drug_a": "amoxicillin",
        "drug_b": "_oral_route_rabbit",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腸内細菌叢破壊",
        "effect_en": "Oral penicillins/aminopenicillins kill gram-positive gut flora in rabbits/guinea pigs/chinchillas, causing fatal Clostridial enterotoxemia.",
        "effect_ja": "経口ペニシリン系はウサギ・モルモット・チンチラの腸内細菌叢を破壊し致死的クロストリジウム性エンテロトキセミアを引き起こす。",
        "management_en": "Do NOT use oral penicillins in lagomorphs/hindgut fermenters. Parenteral routes generally safer.",
        "management_ja": "ウサギ・後腸発酵動物に経口ペニシリン系禁忌。注射経路は概ね安全。",
        "ref": "BSAVA Manual of Rabbit Medicine 2014",
    },
    # ====== ワルファリン関連 ======
    {
        "drug_a": "warfarin",
        "drug_b": "meloxicam",
        "severity": SEVERITY_MAJOR,
        "mechanism": "蛋白結合競合 + 血小板機能阻害",
        "effect_en": "NSAIDs displace warfarin from protein binding and inhibit platelets → severe bleeding risk.",
        "effect_ja": "NSAIDがワルファリンを蛋白結合から遊離・血小板機能阻害→重度出血リスク。",
        "management_en": "Avoid combination. Monitor PT/INR closely if essential.",
        "management_ja": "併用回避。必須の場合はPT/INRを厳重監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "warfarin",
        "drug_b": "metronidazole",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP2C9阻害",
        "effect_en": "Metronidazole inhibits warfarin metabolism, increasing anticoagulant effect.",
        "effect_ja": "メトロニダゾールがワルファリン代謝を阻害し抗凝固作用を増強。",
        "management_en": "Reduce warfarin dose 30-50%. Monitor PT/INR.",
        "management_ja": "ワルファリン30-50%減量。PT/INR監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== エキゾチックの致死的相互作用 ======
    {
        "drug_a": "fipronil",
        "drug_b": "_species_rabbit",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "フィプロニル感受性",
        "effect_en": "Fipronil is fatal to rabbits even at standard topical doses (seizures, death).",
        "effect_ja": "フィプロニルは標準局所用量でもウサギに致死的（痙攣・死亡）。",
        "management_en": "NEVER use fipronil on rabbits. Use selamectin or imidacloprid instead.",
        "management_ja": "ウサギには絶対使用禁止。セラメクチンまたはイミダクロプリドを使用。",
        "ref": "BSAVA Manual of Rabbit Medicine 2014",
    },
    {
        "drug_a": "fipronil",
        "drug_b": "_species_chinchilla",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "フィプロニル感受性",
        "effect_en": "Fipronil is fatal to chinchillas.",
        "effect_ja": "フィプロニルはチンチラに致死的。",
        "management_en": "NEVER use fipronil on chinchillas.",
        "management_ja": "チンチラには絶対使用禁止。",
        "ref": "Quesenberry & Carpenter 2012",
    },
    {
        "drug_a": "ivermectin",
        "drug_b": "_breed_collie",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "MDR1/ABCB1変異による血液脳関門通過",
        "effect_en": "Collies/Australian Shepherds with MDR1 mutation: high-dose ivermectin causes neurotoxicity (ataxia, coma, death).",
        "effect_ja": "MDR1変異のあるコリー/オーストラリアンシェパード：高用量イベルメクチンで神経毒性（失調、昏睡、死亡）。",
        "management_en": "Test for MDR1 mutation. Avoid high-dose ivermectin in MDR1+/+ or +/-. Heartworm prevention dose is generally safe.",
        "management_ja": "MDR1変異検査。MDR1+/+ または +/- では高用量イベルメクチン回避。フィラリア予防用量は概ね安全。",
        "ref": "Mealey 2004 JAVMA",
    },
    # ====== その他臨床的に重要 ======
    {
        "drug_a": "metoclopramide",
        "drug_b": "ondansetron",
        "severity": SEVERITY_MODERATE,
        "mechanism": "セロトニン受容体作用の重複",
        "effect_en": "Both 5-HT3 effects; concurrent use generally not necessary and may increase QT prolongation.",
        "effect_ja": "両薬剤とも5-HT3作用。併用は通常不要、QT延長リスク増加の可能性。",
        "management_en": "Use one or the other; rarely beneficial in combination.",
        "management_ja": "どちらか一方を使用。併用は稀に有益。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "doxycycline",
        "drug_b": "calcium",
        "severity": SEVERITY_MODERATE,
        "mechanism": "GI内でキレート形成",
        "effect_en": "Calcium (and Mg, Al, Fe) chelates doxycycline, reducing absorption.",
        "effect_ja": "カルシウム（Mg、Al、Feも）がドキシサイクリンとキレート形成し吸収低下。",
        "management_en": "Separate by 2-3 hours. Avoid dairy with doxycycline.",
        "management_ja": "投与間隔を2-3時間空ける。乳製品同時摂取回避。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "ketoconazole",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP3A4阻害（意図的併用あり）",
        "effect_en": "Ketoconazole inhibits ciclosporin metabolism. Often used intentionally to reduce ciclosporin dose/cost.",
        "effect_ja": "ケトコナゾールがシクロスポリン代謝を阻害。意図的併用でシクロスポリン用量・費用削減目的。",
        "management_en": "If intentional: reduce ciclosporin to 25-50%. Monitor levels. If unintentional: same dose adjustment needed.",
        "management_ja": "意図的併用：シクロスポリンを25-50%に減量し血中濃度監視。",
        "ref": "BSAVA 10th ed.",
    },
    {
        "drug_a": "trimethoprim_sulfa",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎毒性の相加",
        "effect_en": "TMS + ciclosporin synergistically increases nephrotoxicity.",
        "effect_ja": "TMSとシクロスポリン併用で相加的腎毒性。",
        "management_en": "Monitor BUN/Cr closely. Consider alternative antibiotic.",
        "management_ja": "BUN/Cr厳重監視。代替抗菌薬を検討。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== NSAID追加 (他のNSAID同士) ======
    {
        "drug_a": "carprofen",
        "drug_b": "firocoxib",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "COX阻害の重複",
        "effect_en": "Concurrent NSAIDs: additive GI ulceration, renal toxicity risk.",
        "effect_ja": "NSAID併用：消化管潰瘍・腎毒性リスク加算。",
        "management_en": "Do not combine. Washout 5-7 days when switching.",
        "management_ja": "併用禁忌。切替時5-7日ウォッシュアウト。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "meloxicam",
        "drug_b": "firocoxib",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "COX阻害の重複",
        "effect_en": "Concurrent NSAIDs: additive GI and renal toxicity.",
        "effect_ja": "NSAID併用禁忌。",
        "management_en": "Do not combine. 5-7 day washout.",
        "management_ja": "併用禁忌。5-7日ウォッシュアウト。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "meloxicam",
        "drug_b": "dexamethasone",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "粘膜保護の二重阻害",
        "effect_en": "NSAID + corticosteroid: dramatically increased GI ulceration risk.",
        "effect_ja": "NSAID+ステロイド：消化管潰瘍リスク劇的増加。",
        "management_en": "Do not combine.",
        "management_ja": "併用禁忌。",
        "ref": "AAHA 2020",
    },
    {
        "drug_a": "carprofen",
        "drug_b": "dexamethasone",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "粘膜保護の二重阻害",
        "effect_en": "NSAID + corticosteroid: GI ulceration risk.",
        "effect_ja": "NSAID+ステロイド：消化管潰瘍リスク。",
        "management_en": "Do not combine.",
        "management_ja": "併用禁忌。",
        "ref": "AAHA 2020",
    },
    {
        "drug_a": "meloxicam",
        "drug_b": "aspirin",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "COX重複+血小板阻害加算",
        "effect_en": "Dual COX inhibition + antiplatelet: severe GI bleeding risk.",
        "effect_ja": "二重COX阻害+抗血小板：重度消化管出血リスク。",
        "management_en": "Do not combine.",
        "management_ja": "併用禁忌。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== NSAIDと腎毒性薬 ======
    {
        "drug_a": "meloxicam",
        "drug_b": "gentamicin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎毒性の相加",
        "effect_en": "NSAID renal prostaglandin reduction + aminoglycoside nephrotoxicity = high AKI risk.",
        "effect_ja": "NSAIDの腎プロスタグランジン低下+アミノグリコシド腎毒性→高AKIリスク。",
        "management_en": "Avoid combination. If essential, aggressive IV fluid support + monitor renal values.",
        "management_ja": "併用回避。必須なら積極的輸液+腎値監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "meloxicam",
        "drug_b": "amphotericin_b",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎毒性の相加",
        "effect_en": "Both nephrotoxic: combined risk of acute kidney injury.",
        "effect_ja": "両薬剤とも腎毒性：急性腎障害リスク相加。",
        "management_en": "Avoid combination.",
        "management_ja": "併用回避。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 麻酔薬関連 ======
    {
        "drug_a": "ketamine",
        "drug_b": "acepromazine",
        "severity": SEVERITY_MODERATE,
        "mechanism": "鎮静・低血圧の相加",
        "effect_en": "Common combination but acepromazine potentiates ketamine CNS effects; reduce doses.",
        "effect_ja": "一般的併用だがアセプロマジンがケタミンCNS作用を増強。用量減量。",
        "management_en": "Reduce individual doses 25-50%. Monitor BP.",
        "management_ja": "個々の用量25-50%減量。血圧監視。",
        "ref": "Lumb & Jones 5th ed.",
    },
    {
        "drug_a": "propofol",
        "drug_b": "fentanyl",
        "severity": SEVERITY_MODERATE,
        "mechanism": "呼吸抑制の相加",
        "effect_en": "Synergistic respiratory depression. Common but requires ventilatory support.",
        "effect_ja": "相乗的呼吸抑制。一般的だが呼吸補助が必要。",
        "management_en": "Have IPPV ready. Reduce propofol induction dose by 30-50%.",
        "management_ja": "IPPV準備。プロポフォール導入量30-50%減量。",
        "ref": "Lumb & Jones 5th ed.",
    },
    {
        "drug_a": "acepromazine",
        "drug_b": "_breed_boxer",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "品種特異的血管拡張過感受性",
        "effect_en": "Boxers are hypersensitive to acepromazine — severe, prolonged hypotension and bradycardia.",
        "effect_ja": "ボクサーはアセプロマジンに過感受性→重度持続性低血圧・徐脈。",
        "management_en": "NEVER use acepromazine in Boxers. Use alternative sedation (dexmedetomidine, butorphanol).",
        "management_ja": "ボクサーにアセプロマジン使用禁止。代替鎮静薬（デクスメデトミジン等）使用。",
        "ref": "BSAVA Manual of Canine/Feline Anaesthesia 3rd ed.",
    },
    {
        "drug_a": "acepromazine",
        "drug_b": "_condition_seizure_history",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "痙攣閾値低下",
        "effect_en": "Acepromazine lowers seizure threshold — contraindicated in epileptic animals.",
        "effect_ja": "アセプロマジンは痙攣閾値を低下→てんかん動物に禁忌。",
        "management_en": "Do NOT use in seizure patients. Use benzodiazepines or α2 agonists instead.",
        "management_ja": "痙攣既往に使用禁止。ベンゾジアゼピンまたはα2作動薬を使用。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "thiopental",
        "drug_b": "_breed_sighthound",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "サイトハウンド脂肪分布異常による遷延",
        "effect_en": "Sighthounds (Greyhound, Whippet) have prolonged recovery from thiopental due to low body fat.",
        "effect_ja": "サイトハウンド（グレイハウンド等）は低体脂肪によりチオペンタール覚醒が遷延。",
        "management_en": "Avoid thiopental in sighthounds. Use propofol or alfaxalone instead.",
        "management_ja": "サイトハウンドにチオペンタール回避。プロポフォール/アルファキサロン使用。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== 抗痙攣薬 ======
    {
        "drug_a": "phenobarbital",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP誘導によるシクロスポリン代謝促進",
        "effect_en": "Phenobarbital induces CYP3A → reduces ciclosporin levels significantly.",
        "effect_ja": "フェノバルビタールがCYP3A誘導→シクロスポリン血中濃度大幅低下。",
        "management_en": "Monitor ciclosporin levels. May need 2-3x dose increase.",
        "management_ja": "シクロスポリン血中濃度監視。2-3倍増量が必要な場合あり。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "phenobarbital",
        "drug_b": "doxycycline",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP誘導によるドキシサイクリン代謝促進",
        "effect_en": "Phenobarbital reduces doxycycline half-life by 50% via CYP induction.",
        "effect_ja": "フェノバルビタールがドキシサイクリン半減期を50%短縮。",
        "management_en": "Increase doxycycline dose or frequency. Consider alternative antibiotic.",
        "management_ja": "ドキシサイクリン増量/頻度増加、または代替抗菌薬。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "phenobarbital",
        "drug_b": "metronidazole",
        "severity": SEVERITY_MODERATE,
        "mechanism": "CYP誘導",
        "effect_en": "Phenobarbital may reduce metronidazole levels. Also both have CNS depression potential.",
        "effect_ja": "フェノバルビタールがメトロニダゾール血中濃度を低下させる可能性。両薬剤CNS抑制。",
        "management_en": "Monitor for therapeutic failure. Dose adjustment may be needed.",
        "management_ja": "治療効果をモニタリング。用量調整の可能性。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "levetiracetam",
        "drug_b": "phenobarbital",
        "severity": SEVERITY_MODERATE,
        "mechanism": "レベチラセタムクリアランス増加",
        "effect_en": "Phenobarbital increases levetiracetam clearance — may need higher levetiracetam doses.",
        "effect_ja": "フェノバルビタールがレベチラセタムクリアランスを増加。",
        "management_en": "Monitor seizure control. May need levetiracetam dose increase.",
        "management_ja": "痙攣コントロールを監視。レベチラセタム増量が必要な場合あり。",
        "ref": "Dewey 2016 JAVMA",
    },
    # ====== 心臓薬追加 ======
    {
        "drug_a": "pimobendan",
        "drug_b": "atenolol",
        "severity": SEVERITY_MAJOR,
        "mechanism": "陽性変力作用と陰性変力作用の拮抗",
        "effect_en": "Beta-blockers antagonize pimobendan's positive inotropic effect.",
        "effect_ja": "β遮断薬がピモベンダンの陽性変力作用を拮抗。",
        "management_en": "Generally avoid combination. If needed, careful dose titration with echo monitoring.",
        "management_ja": "原則併用回避。必須なら心エコーで慎重に用量調整。",
        "ref": "ACVIM Cardiac Consensus 2019",
    },
    {
        "drug_a": "atenolol",
        "drug_b": "diltiazem",
        "severity": SEVERITY_MAJOR,
        "mechanism": "二重AV結節抑制",
        "effect_en": "Both suppress AV conduction — severe bradycardia/heart block risk.",
        "effect_ja": "両薬剤ともAV伝導抑制→重度徐脈/心ブロックリスク。",
        "management_en": "Avoid concurrent use. If needed, start low doses and monitor ECG closely.",
        "management_ja": "併用回避。必須ならECG厳重監視下で低用量から。",
        "ref": "ACVIM 2019",
    },
    {
        "drug_a": "enalapril",
        "drug_b": "spironolactone",
        "severity": SEVERITY_MODERATE,
        "mechanism": "高カリウム血症リスク",
        "effect_en": "Both ACE-I and K-sparing diuretic increase serum potassium. Common cardiac combination but monitor K+.",
        "effect_ja": "ACE阻害薬+K保持性利尿薬で血清K上昇。一般的だがK+監視が必要。",
        "management_en": "Monitor serum potassium regularly. Avoid in renal impairment.",
        "management_ja": "血清K+定期監視。腎機能低下では回避。",
        "ref": "ACVIM Cardiac Consensus 2019",
    },
    {
        "drug_a": "digoxin",
        "drug_b": "diltiazem",
        "severity": SEVERITY_MAJOR,
        "mechanism": "ジゴキシン血中濃度上昇+AV伝導抑制の相加",
        "effect_en": "Diltiazem raises digoxin levels 20-30% AND both suppress AV conduction.",
        "effect_ja": "ジルチアゼムがジゴキシン血中濃度20-30%上昇、AV伝導抑制の相加。",
        "management_en": "Reduce digoxin dose 30%. Monitor levels and ECG.",
        "management_ja": "ジゴキシン30%減量。血中濃度・ECG監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 内分泌 ======
    {
        "drug_a": "methimazole",
        "drug_b": "warfarin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "甲状腺状態変化によるワルファリン代謝変動",
        "effect_en": "As thyroid function normalizes, warfarin metabolism changes — bleeding risk during dose titration.",
        "effect_ja": "甲状腺機能正常化でワルファリン代謝が変動→用量調整中の出血リスク。",
        "management_en": "Monitor PT/INR frequently during methimazole titration.",
        "management_ja": "メチマゾール調整中はPT/INRを頻回監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "trilostane",
        "drug_b": "enalapril",
        "severity": SEVERITY_MODERATE,
        "mechanism": "低アルドステロン+ACE阻害→高K+リスク",
        "effect_en": "Trilostane reduces aldosterone; ACE-I also increases K+. Combined hyperkalemia risk.",
        "effect_ja": "トリロスタン(低アルドステロン)+ACE阻害薬→高K血症リスク。",
        "management_en": "Monitor electrolytes (especially K+). Common combination in cardiac+Cushing's dogs.",
        "management_ja": "電解質（特にK+）監視。心疾患+クッシング犬で一般的併用。",
        "ref": "Ramsey 2017 BSAVA",
    },
    {
        "drug_a": "insulin",
        "drug_b": "prednisolone",
        "severity": SEVERITY_MAJOR,
        "mechanism": "コルチコステロイドのインスリン抵抗性",
        "effect_en": "Corticosteroids cause insulin resistance → hyperglycemia, loss of diabetic control.",
        "effect_ja": "コルチコステロイドがインスリン抵抗性を惹起→高血糖、糖尿病管理の破綻。",
        "management_en": "Avoid steroids in diabetics. If essential, increase insulin dose and monitor BG closely.",
        "management_ja": "糖尿病動物にステロイド回避。必須ならインスリン増量+血糖厳重監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 消化器 ======
    {
        "drug_a": "metoclopramide",
        "drug_b": "maropitant",
        "severity": SEVERITY_MODERATE,
        "mechanism": "制吐機序の重複",
        "effect_en": "Both are antiemetics with different mechanisms. Combination generally safe but rarely necessary.",
        "effect_ja": "両薬剤とも制吐薬。併用は概ね安全だが通常は不要。",
        "management_en": "Use one or the other. Combination occasionally in refractory vomiting.",
        "management_ja": "通常は一方のみ使用。難治性嘔吐で併用する場合あり。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "cisapride",
        "drug_b": "erythromycin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "QT延長の相加",
        "effect_en": "Both prolong QT interval → risk of torsades de pointes.",
        "effect_ja": "両薬剤ともQT延長→トルサード・ド・ポアンツのリスク。",
        "management_en": "Avoid combination. Use alternative prokinetic or antibiotic.",
        "management_ja": "併用回避。代替蠕動促進薬または抗菌薬を使用。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "omeprazole",
        "drug_b": "ketoconazole",
        "severity": SEVERITY_MAJOR,
        "mechanism": "胃酸抑制によるケトコナゾール吸収低下",
        "effect_en": "Ketoconazole requires acidic pH for absorption. PPI eliminates gastric acid → <50% absorption.",
        "effect_ja": "ケトコナゾールは酸性pHで吸収。PPIで胃酸消失→吸収50%以下。",
        "management_en": "Separate by 2h or use alternative antifungal (itraconazole less affected).",
        "management_ja": "2時間以上間隔を空ける、またはイトラコナゾール（影響少）に変更。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 抗菌薬 ======
    {
        "drug_a": "fluoroquinolone",
        "drug_b": "aluminum_hydroxide",
        "severity": SEVERITY_MAJOR,
        "mechanism": "キレート形成による吸収低下",
        "effect_en": "Antacids (Al, Mg, Ca) chelate fluoroquinolones, reducing absorption >50%.",
        "effect_ja": "制酸薬がフルオロキノロンとキレート形成→吸収50%以上低下。",
        "management_en": "Separate administration by ≥2 hours.",
        "management_ja": "投与間隔2時間以上。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "metronidazole",
        "drug_b": "phenobarbital",
        "severity": SEVERITY_MODERATE,
        "mechanism": "CYP誘導+神経毒性の相加",
        "effect_en": "Phenobarbital accelerates metronidazole metabolism. Both cause CNS toxicity at high doses.",
        "effect_ja": "フェノバルビタールがメトロニダゾール代謝を促進。高用量で両薬剤ともCNS毒性。",
        "management_en": "Monitor for neurotoxicity. May need higher metronidazole doses.",
        "management_ja": "神経毒性モニタリング。メトロニダゾール増量が必要な場合あり。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "doxycycline",
        "drug_b": "phenobarbital",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP誘導によるドキシサイクリン半減期短縮",
        "effect_en": "Phenobarbital halves doxycycline half-life. Subtherapeutic levels likely.",
        "effect_ja": "フェノバルビタールがドキシサイクリン半減期を半減。治療域未達の可能性。",
        "management_en": "Increase doxycycline to q8h or use alternative antibiotic.",
        "management_ja": "ドキシサイクリンをq8hに増頻、または代替抗菌薬。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "chloramphenicol",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP阻害によるシクロスポリン毒性増強",
        "effect_en": "Chloramphenicol inhibits CYP3A → elevated ciclosporin levels → nephrotoxicity.",
        "effect_ja": "クロラムフェニコールがCYP3A阻害→シクロスポリン血中濃度上昇→腎毒性。",
        "management_en": "Avoid combination. Monitor ciclosporin levels if essential.",
        "management_ja": "併用回避。必須ならシクロスポリン血中濃度監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 化学療法 ======
    {
        "drug_a": "doxorubicin",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "P-gp阻害によるドキソルビシン毒性増強",
        "effect_en": "Ciclosporin inhibits P-glycoprotein → increased doxorubicin tissue accumulation → cardiotoxicity.",
        "effect_ja": "シクロスポリンがP-gp阻害→ドキソルビシン組織蓄積増加→心毒性。",
        "management_en": "Avoid combination or reduce doxorubicin dose. Cardiac monitoring (echo).",
        "management_ja": "併用回避またはドキソルビシン減量。心臓モニタリング（心エコー）。",
        "ref": "Withrow & Vail Oncology 6th ed.",
    },
    {
        "drug_a": "cisplatin",
        "drug_b": "_species_cat",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "猫における致死的肺水腫",
        "effect_en": "Cisplatin causes fatal pulmonary edema in cats at any dose.",
        "effect_ja": "シスプラチンは猫にいかなる用量でも致死的肺水腫を引き起こす。",
        "management_en": "NEVER use cisplatin in cats. Use carboplatin instead.",
        "management_ja": "猫にシスプラチン使用禁止。カルボプラチンを使用。",
        "ref": "Withrow & Vail Oncology 6th ed.",
    },
    {
        "drug_a": "vincristine",
        "drug_b": "_breed_collie",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "MDR1/ABCB1変異による毒性増強",
        "effect_en": "MDR1 mutation Collies: vincristine neurotoxicity at standard doses (myelosuppression, ileus).",
        "effect_ja": "MDR1変異コリー：標準用量のビンクリスチンで神経毒性（骨髄抑制、イレウス）。",
        "management_en": "Test MDR1 status. Reduce dose 25-50% in MDR1+/+ or +/-.",
        "management_ja": "MDR1検査。MDR1+/+または+/-では25-50%減量。",
        "ref": "Mealey 2008 Vet Clin NA",
    },
    # ====== 抗真菌 ======
    {
        "drug_a": "itraconazole",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP3A4阻害",
        "effect_en": "Itraconazole (like ketoconazole) inhibits ciclosporin metabolism → elevated levels.",
        "effect_ja": "イトラコナゾールがシクロスポリン代謝を阻害→血中濃度上昇。",
        "management_en": "Reduce ciclosporin dose 25-50%. Monitor levels.",
        "management_ja": "シクロスポリン25-50%減量。血中濃度監視。",
        "ref": "BSAVA 10th ed.",
    },
    {
        "drug_a": "itraconazole",
        "drug_b": "phenobarbital",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP誘導によるイトラコナゾール血中濃度低下",
        "effect_en": "Phenobarbital induces CYP → subtherapeutic itraconazole levels.",
        "effect_ja": "フェノバルビタールがCYP誘導→イトラコナゾール治療域未達。",
        "management_en": "Monitor antifungal efficacy. May need increased itraconazole dose.",
        "management_ja": "抗真菌効果をモニタリング。イトラコナゾール増量の可能性。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== オピオイド ======
    {
        "drug_a": "buprenorphine",
        "drug_b": "morphine",
        "severity": SEVERITY_MAJOR,
        "mechanism": "μ受容体部分作動薬+完全作動薬の拮抗",
        "effect_en": "Buprenorphine (partial agonist) displaces full agonists → reduced analgesia or precipitated withdrawal.",
        "effect_ja": "ブプレノルフィン（部分作動薬）が完全作動薬を置換→鎮痛減弱。",
        "management_en": "Do not combine. Wait for one to wear off before administering the other.",
        "management_ja": "併用禁忌。一方の効果消失を待ってから他方を投与。",
        "ref": "Lumb & Jones 5th ed.",
    },
    {
        "drug_a": "butorphanol",
        "drug_b": "morphine",
        "severity": SEVERITY_MAJOR,
        "mechanism": "μ拮抗/κ作動+μ完全作動の混合",
        "effect_en": "Butorphanol (mixed agonist-antagonist) partially antagonizes morphine μ-receptor effects.",
        "effect_ja": "ブトルファノール（混合作動-拮抗薬）がモルヒネμ受容体効果を部分的に拮抗。",
        "management_en": "Avoid sequential use. Choose one opioid class.",
        "management_ja": "逐次的使用回避。一つのオピオイドクラスを選択。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== 行動薬 ======
    {
        "drug_a": "fluoxetine",
        "drug_b": "selegiline",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "セロトニン症候群",
        "effect_en": "SSRI + MAO-B inhibitor → severe serotonin syndrome (hyperthermia, seizures, death).",
        "effect_ja": "SSRI+MAO-B阻害薬→重度セロトニン症候群（高体温、痙攣、死亡）。",
        "management_en": "CONTRAINDICATED. Allow ≥5 week washout (fluoxetine) or 14 days (selegiline) when switching.",
        "management_ja": "併用禁忌。切替時はフルオキセチン5週/セレギリン14日のウォッシュアウト。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "clomipramine",
        "drug_b": "selegiline",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "セロトニン症候群",
        "effect_en": "TCA (serotonergic) + MAO-B inhibitor → serotonin syndrome risk.",
        "effect_ja": "三環系（セロトニン作動性）+MAO-B阻害薬→セロトニン症候群リスク。",
        "management_en": "CONTRAINDICATED. 14-day washout minimum.",
        "management_ja": "併用禁忌。最低14日ウォッシュアウト。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 種特異的追加 ======
    {
        "drug_a": "fipronil",
        "drug_b": "_species_guinea_pig",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "フィプロニル感受性（モルモット）",
        "effect_en": "Fipronil toxicity reported in guinea pigs — seizures, death.",
        "effect_ja": "フィプロニルはモルモットに毒性（痙攣、死亡）の報告。",
        "management_en": "Do NOT use fipronil on guinea pigs. Use selamectin or imidacloprid.",
        "management_ja": "モルモットにフィプロニル使用禁止。セラメクチン/イミダクロプリド。",
        "ref": "Quesenberry & Carpenter 2012",
    },
    {
        "drug_a": "amoxicillin",
        "drug_b": "_oral_route_guinea_pig",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腸内細菌叢破壊",
        "effect_en": "Oral penicillins fatal to guinea pigs (Clostridial dysbiosis). Parenteral safer.",
        "effect_ja": "経口ペニシリン系はモルモットに致死的（クロストリジウム性腸内細菌叢異常）。",
        "management_en": "Do NOT use oral penicillins in guinea pigs.",
        "management_ja": "モルモットに経口ペニシリン系禁忌。",
        "ref": "Hawkins & Bishop 2012",
    },
    {
        "drug_a": "amoxicillin",
        "drug_b": "_oral_route_chinchilla",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腸内細菌叢破壊",
        "effect_en": "Oral penicillins cause fatal dysbiosis in chinchillas.",
        "effect_ja": "経口ペニシリン系はチンチラに致死的。",
        "management_en": "Do NOT use oral penicillins in chinchillas.",
        "management_ja": "チンチラに経口ペニシリン系禁忌。",
        "ref": "Mans & Donnelly 2012",
    },
    {
        "drug_a": "amoxicillin",
        "drug_b": "_oral_route_hamster",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腸内細菌叢破壊",
        "effect_en": "Oral penicillins cause fatal dysbiosis in hamsters.",
        "effect_ja": "経口ペニシリン系はハムスターに致死的。",
        "management_en": "Do NOT use oral penicillins in hamsters. Injectable cephalosporins safer.",
        "management_ja": "ハムスターに経口ペニシリン系禁忌。注射用セファロスポリンは安全。",
        "ref": "Harkness & Wagner 2010",
    },
    {
        "drug_a": "enrofloxacin",
        "drug_b": "_species_cat_retinal",
        "severity": SEVERITY_MAJOR,
        "mechanism": "猫の網膜毒性（高用量）",
        "effect_en": "Enrofloxacin >5 mg/kg in cats → retinal degeneration and blindness.",
        "effect_ja": "エンロフロキサシン>5 mg/kgで猫に網膜変性・失明。",
        "management_en": "NEVER exceed 5 mg/kg/day in cats. Many prefer marbofloxacin or pradofloxacin instead.",
        "management_ja": "猫で5 mg/kg/日を絶対に超えない。マルボフロキサシン/プラドフロキサシンが代替。",
        "ref": "Gelatt 2005 Vet Ophthalmol; FDA CVM 2000",
    },
    # ====== ACE阻害薬+NSAID拡張 ======
    {
        "drug_a": "benazepril",
        "drug_b": "meloxicam",
        "severity": SEVERITY_MAJOR,
        "mechanism": "腎保護作用減弱+腎血流低下",
        "effect_en": "NSAIDs blunt ACE-I renoprotective effect. AKI risk in CKD/CHF patients.",
        "effect_ja": "NSAIDがACE阻害薬の腎保護作用を減弱。CKD/CHF患者でAKIリスク。",
        "management_en": "Monitor renal values. Avoid in dehydrated/azotemic patients.",
        "management_ja": "腎値監視。脱水/高窒素血症では回避。",
        "ref": "IRIS CKD Guidelines 2019",
    },
    {
        "drug_a": "benazepril",
        "drug_b": "furosemide",
        "severity": SEVERITY_MODERATE,
        "mechanism": "相加的降圧+脱水リスク",
        "effect_en": "Common CHF combination. Risk of hypotension and prerenal azotemia if over-diuresed.",
        "effect_ja": "一般的CHF併用。過剰利尿で低血圧・腎前性高窒素血症リスク。",
        "management_en": "Monitor BUN/Cr, BP. Start ACE-I at low dose.",
        "management_ja": "BUN/Cr・血圧監視。ACE阻害薬は低用量から開始。",
        "ref": "ACVIM Cardiac 2019",
    },
    # ====== 抗菌薬追加 ======
    {
        "drug_a": "metronidazole",
        "drug_b": "ciclosporin",
        "severity": SEVERITY_MODERATE,
        "mechanism": "CYP阻害でシクロスポリン上昇の可能性",
        "effect_en": "Metronidazole may moderately increase ciclosporin levels.",
        "effect_ja": "メトロニダゾールがシクロスポリン血中濃度を中等度上昇させる可能性。",
        "management_en": "Monitor ciclosporin levels.",
        "management_ja": "シクロスポリン血中濃度監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "gentamicin",
        "drug_b": "amphotericin_b",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腎毒性の相乗作用",
        "effect_en": "Both highly nephrotoxic — combination dramatically increases AKI risk.",
        "effect_ja": "両薬剤とも強い腎毒性→併用で急性腎障害リスク劇的増加。",
        "management_en": "AVOID combination. Use alternative antibiotic.",
        "management_ja": "併用回避。代替抗菌薬を使用。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "marbofloxacin",
        "drug_b": "sucralfate",
        "severity": SEVERITY_MAJOR,
        "mechanism": "キレート形成による吸収低下",
        "effect_en": "Sucralfate chelates fluoroquinolones (including marbofloxacin) → reduced absorption.",
        "effect_ja": "スクラルファートがフルオロキノロンとキレート形成→吸収低下。",
        "management_en": "Separate by ≥2 hours.",
        "management_ja": "投与間隔2時間以上。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 利尿薬 ======
    {
        "drug_a": "furosemide",
        "drug_b": "digoxin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "低K血症によるジゴキシン中毒",
        "effect_en": "Furosemide-induced hypokalemia potentiates digoxin toxicity (arrhythmias).",
        "effect_ja": "フロセミドによる低K血症がジゴキシン中毒を増強（不整脈）。",
        "management_en": "Monitor K+ and digoxin levels. Supplement KCl as needed.",
        "management_ja": "K+・ジゴキシン血中濃度を定期監視。KCl補給。",
        "ref": "ACVIM 2019",
    },
    {
        "drug_a": "furosemide",
        "drug_b": "cisplatin",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腎毒性の相乗＋耳毒性",
        "effect_en": "Loop diuretics synergize cisplatin nephrotoxicity and ototoxicity.",
        "effect_ja": "ループ利尿薬がシスプラチンの腎毒性・耳毒性を相乗的に増強。",
        "management_en": "Avoid combination.",
        "management_ja": "併用禁忌。",
        "ref": "Withrow & Vail Oncology 6th ed.",
    },
    # ====== 呼吸器 ======
    {
        "drug_a": "theophylline",
        "drug_b": "cimetidine",
        "severity": SEVERITY_MAJOR,
        "mechanism": "CYP阻害によるテオフィリン蓄積",
        "effect_en": "Cimetidine inhibits theophylline metabolism → elevated levels, toxicity (seizures, tachycardia).",
        "effect_ja": "シメチジンがテオフィリン代謝を阻害→中毒（痙攣、頻脈）。",
        "management_en": "Use famotidine/ranitidine instead (no CYP interaction). Or reduce theophylline dose.",
        "management_ja": "シメチジン→ファモチジン/ラニチジンに変更。またはテオフィリン減量。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 免疫抑制 ======
    {
        "drug_a": "azathioprine",
        "drug_b": "allopurinol",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "アザチオプリン代謝阻害→重度骨髄抑制",
        "effect_en": "Allopurinol inhibits xanthine oxidase which metabolizes azathioprine → severe myelosuppression.",
        "effect_ja": "アロプリノールがキサンチンオキシダーゼ阻害→アザチオプリン蓄積→重度骨髄抑制。",
        "management_en": "If combination essential, reduce azathioprine to 25-33% of standard dose. Monitor CBC weekly.",
        "management_ja": "必須の場合アザチオプリンを25-33%に減量。CBC毎週監視。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "azathioprine",
        "drug_b": "_species_cat",
        "severity": SEVERITY_MAJOR,
        "mechanism": "猫のアザチオプリン感受性",
        "effect_en": "Cats are extremely sensitive to azathioprine — fatal myelosuppression at dog doses.",
        "effect_ja": "猫はアザチオプリンに極めて感受性が高い。犬用量で致死的骨髄抑制。",
        "management_en": "Use ONLY q48h at 0.3 mg/kg in cats, OR use chlorambucil instead. Monitor CBC weekly.",
        "management_ja": "猫では0.3 mg/kg q48hのみ使用。クロラムブシルが代替。CBC毎週監視。",
        "ref": "ACVIM Consensus 2010",
    },
    # ====== 皮膚科 ======
    {
        "drug_a": "ciclosporin",
        "drug_b": "grapefruit",
        "severity": SEVERITY_MODERATE,
        "mechanism": "CYP3A4/P-gp阻害",
        "effect_en": "Grapefruit juice inhibits CYP3A4 → increases ciclosporin levels (sometimes used intentionally to reduce cost).",
        "effect_ja": "グレープフルーツジュースがCYP3A4阻害→シクロスポリン血中濃度上昇（コスト削減目的で意図的使用あり）。",
        "management_en": "If intentional: reduce ciclosporin dose and monitor levels.",
        "management_ja": "意図的使用：シクロスポリン減量+血中濃度監視。",
        "ref": "BSAVA 10th ed.",
    },
    # ====== 泌尿器 ======
    {
        "drug_a": "amitriptyline",
        "drug_b": "tramadol",
        "severity": SEVERITY_MAJOR,
        "mechanism": "セロトニン症候群リスク",
        "effect_en": "Both serotonergic — combination increases serotonin syndrome risk.",
        "effect_ja": "両薬剤ともセロトニン作動性→セロトニン症候群リスク増加。",
        "management_en": "Avoid combination. Monitor for hyperthermia, agitation, tremors.",
        "management_ja": "併用回避。高体温・興奮・振戦を監視。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 追加の麻酔関連 ======
    {
        "drug_a": "dexmedetomidine",
        "drug_b": "atipamezole",
        "severity": SEVERITY_MODERATE,
        "mechanism": "α2拮抗（意図的覚醒）",
        "effect_en": "Atipamezole reverses dexmedetomidine. Intended reversal agent.",
        "effect_ja": "アチパメゾールはデクスメデトミジンを拮抗。意図的覚醒薬。",
        "management_en": "Use half the volume (mL) of dexmedetomidine given.",
        "management_ja": "投与したデクスメデトミジンの半量（mL）をIM。",
        "ref": "Lumb & Jones 5th ed.",
    },
    {
        "drug_a": "dexmedetomidine",
        "drug_b": "epinephrine",
        "severity": SEVERITY_MAJOR,
        "mechanism": "α受容体への重複作用",
        "effect_en": "α2 agonist + α1 agonist (epinephrine) → severe hypertension risk.",
        "effect_ja": "α2作動薬+エピネフリン→重度高血圧リスク。",
        "management_en": "Avoid combination. If epinephrine needed, use minimal dose.",
        "management_ja": "併用回避。エピネフリン必須なら最小用量。",
        "ref": "Lumb & Jones 5th ed.",
    },
    {
        "drug_a": "alfaxalone",
        "drug_b": "propofol",
        "severity": SEVERITY_MODERATE,
        "mechanism": "GABA-A相乗作用（呼吸抑制）",
        "effect_en": "Both GABA-A agonists — synergistic respiratory depression if combined.",
        "effect_ja": "両薬剤ともGABA-A作動薬→相乗的呼吸抑制。",
        "management_en": "Use one or the other for induction. If co-induction, reduce both doses.",
        "management_ja": "導入はいずれか一方。併用するなら両薬剤減量。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== 駆虫 ======
    {
        "drug_a": "ivermectin",
        "drug_b": "ketoconazole",
        "severity": SEVERITY_MAJOR,
        "mechanism": "P-gp阻害→イベルメクチンCNS移行増加",
        "effect_en": "Ketoconazole inhibits P-glycoprotein → increased ivermectin brain penetration → neurotoxicity.",
        "effect_ja": "ケトコナゾールがP-gp阻害→イベルメクチン脳移行増加→神経毒性。",
        "management_en": "Avoid concurrent use, especially in MDR1 breeds.",
        "management_ja": "併用回避。特にMDR1品種。",
        "ref": "Mealey 2008",
    },
    {
        "drug_a": "ivermectin",
        "drug_b": "spinosad",
        "severity": SEVERITY_MAJOR,
        "mechanism": "P-gp基質の競合",
        "effect_en": "Spinosad may increase ivermectin levels via P-gp competition → neurotoxicity (especially MDR1 dogs).",
        "effect_ja": "スピノサドがP-gp競合でイベルメクチン血中濃度上昇→神経毒性。",
        "management_en": "Avoid in MDR1 breeds. Use alternative flea product with heartworm prevention.",
        "management_ja": "MDR1品種では回避。代替ノミ駆除薬を使用。",
        "ref": "FDA Safety Alert 2011",
    },
    # ====== 腎毒性相加 ======
    {
        "drug_a": "cisplatin",
        "drug_b": "gentamicin",
        "severity": SEVERITY_CONTRAINDICATED,
        "mechanism": "腎毒性の相乗",
        "effect_en": "Both highly nephrotoxic. Combination → severe AKI.",
        "effect_ja": "両薬剤とも強い腎毒性。併用→重度AKI。",
        "management_en": "AVOID.",
        "management_ja": "併用禁忌。",
        "ref": "Withrow & Vail 6th ed.",
    },
    # ====== DMSO ======
    {
        "drug_a": "dmso",
        "drug_b": "_topical_any",
        "severity": SEVERITY_MODERATE,
        "mechanism": "経皮吸収促進",
        "effect_en": "DMSO enhances percutaneous absorption of ANY compound applied concurrently — risk of toxin absorption.",
        "effect_ja": "DMSOは同時塗布のあらゆる化合物の経皮吸収を促進→毒物吸収リスク。",
        "management_en": "Ensure clean skin before DMSO application. Do not mix with potential toxins.",
        "management_ja": "DMSO塗布前に皮膚を清潔に。潜在的毒物との混合禁止。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 甲状腺関連 ======
    {
        "drug_a": "levothyroxine",
        "drug_b": "calcium",
        "severity": SEVERITY_MODERATE,
        "mechanism": "GI内でキレート形成",
        "effect_en": "Calcium reduces levothyroxine absorption by chelation.",
        "effect_ja": "カルシウムがレボチロキシン吸収をキレートにより低下。",
        "management_en": "Separate by ≥4 hours.",
        "management_ja": "投与間隔4時間以上。",
        "ref": "Plumb's 9th ed.",
    },
    {
        "drug_a": "levothyroxine",
        "drug_b": "sucralfate",
        "severity": SEVERITY_MODERATE,
        "mechanism": "吸収低下",
        "effect_en": "Sucralfate reduces levothyroxine absorption.",
        "effect_ja": "スクラルファートがレボチロキシン吸収を低下。",
        "management_en": "Separate by ≥4 hours.",
        "management_ja": "投与間隔4時間以上。",
        "ref": "Plumb's 9th ed.",
    },
    # ====== 鎮痛CRI ======
    {
        "drug_a": "lidocaine",
        "drug_b": "medetomidine",
        "severity": SEVERITY_MODERATE,
        "mechanism": "心伝導抑制の相加",
        "effect_en": "Both suppress cardiac conduction. Common CRI combination but monitor ECG for bradycardia/blocks.",
        "effect_ja": "両薬剤とも心伝導抑制。一般的CRI併用だがECGで徐脈/ブロック監視。",
        "management_en": "Monitor ECG. Reduce doses if bradycardia develops.",
        "management_ja": "ECG監視。徐脈時は減量。",
        "ref": "Lumb & Jones 5th ed.",
    },
    # ====== 止血関連 ======
    {
        "drug_a": "aspirin",
        "drug_b": "clopidogrel",
        "severity": SEVERITY_MODERATE,
        "mechanism": "二重抗血小板（意図的併用あり）",
        "effect_en": "Dual antiplatelet — increased bleeding risk but sometimes used for thromboprophylaxis.",
        "effect_ja": "二重抗血小板→出血リスク増加だが血栓予防で意図的併用あり。",
        "management_en": "Monitor for bleeding. Intended combination in cardiac cases.",
        "management_ja": "出血モニタリング。心疾患で意図的併用。",
        "ref": "ACVIM Thrombus Consensus 2019",
    },
    {
        "drug_a": "heparin",
        "drug_b": "aspirin",
        "severity": SEVERITY_MAJOR,
        "mechanism": "抗凝固+抗血小板の重複",
        "effect_en": "Dual anticoagulation — significantly increased bleeding risk.",
        "effect_ja": "抗凝固+抗血小板→出血リスク著増。",
        "management_en": "Monitor closely. Reduce heparin dose. Watch for hemorrhage.",
        "management_ja": "厳重監視。ヘパリン減量。出血に注意。",
        "ref": "Plumb's 9th ed.",
    },
]


def normalize_drug_id(drug_id: str) -> str:
    """薬品IDを正規化（小文字・スネークケース）"""
    return (drug_id or "").lower().strip().replace("-", "_").replace(" ", "_")


def find_interactions(drug_ids: list[str]) -> list[dict[str, Any]]:
    """
    与えられた薬品IDリストから相互作用を全て検出する。
    重症度順（contraindicated → major → moderate）でソートして返す。
    """
    if not drug_ids or len(drug_ids) < 1:
        return []

    normalized = {normalize_drug_id(d) for d in drug_ids}
    matches: list[dict[str, Any]] = []
    seen_pairs: set[tuple[str, str]] = set()

    for ix in INTERACTIONS:
        a = normalize_drug_id(ix["drug_a"])
        b = normalize_drug_id(ix["drug_b"])
        # 両方とも入力リストに含まれる場合のみ
        if a in normalized and b in normalized:
            pair = tuple(sorted([a, b]))
            if pair not in seen_pairs:
                seen_pairs.add(pair)
                matches.append({**ix, "drug_a": a, "drug_b": b})

    # 重症度順
    severity_order = {SEVERITY_CONTRAINDICATED: 0, SEVERITY_MAJOR: 1, SEVERITY_MODERATE: 2}
    matches.sort(key=lambda x: severity_order.get(x.get("severity", ""), 99))
    return matches


def find_species_specific_warnings(drug_id: str, species: str) -> list[dict[str, Any]]:
    """
    薬品IDと動物種から、種特異的な禁忌・警告を検出する。
    (e.g., fipronil + rabbit, oral amoxicillin + rabbit)
    """
    drug_n = normalize_drug_id(drug_id)
    species_n = normalize_drug_id(species)
    matches: list[dict[str, Any]] = []

    for ix in INTERACTIONS:
        a = normalize_drug_id(ix["drug_a"])
        b = normalize_drug_id(ix["drug_b"])
        # 種特異的マーカー（_species_xxx, _oral_route_xxx, _breed_xxx）
        if a == drug_n and (b.startswith("_species_") or b.startswith("_oral_route_") or b.startswith("_breed_")):
            target = b.replace("_species_", "").replace("_oral_route_", "").replace("_breed_", "")
            if target == species_n:
                matches.append(ix)
        elif b == drug_n and (a.startswith("_species_") or a.startswith("_oral_route_") or a.startswith("_breed_")):
            target = a.replace("_species_", "").replace("_oral_route_", "").replace("_breed_", "")
            if target == species_n:
                matches.append(ix)

    return matches


def get_all_interactions_for_drug(drug_id: str) -> list[dict[str, Any]]:
    """単一薬品に関わる全相互作用を返す（参考表示用）"""
    drug_n = normalize_drug_id(drug_id)
    matches = []
    for ix in INTERACTIONS:
        a = normalize_drug_id(ix["drug_a"])
        b = normalize_drug_id(ix["drug_b"])
        if a == drug_n or b == drug_n:
            matches.append(ix)

    severity_order = {SEVERITY_CONTRAINDICATED: 0, SEVERITY_MAJOR: 1, SEVERITY_MODERATE: 2}
    matches.sort(key=lambda x: severity_order.get(x.get("severity", ""), 99))
    return matches
