"""Drug batch 21 — additional antiparasitics, antifungals, endocrine, renal, oncology, exotic-specific (40 drugs)."""

DRUGS_BATCH_21 = [
    {
        "id": "selamectin_topical",
        "name": "Selamectin (Revolution)",
        "name_ja": "セラメクチン（レボリューション）",
        "category": "antiparasitic",
        "mechanism": "Macrocyclic lactone; activates glutamate-gated chloride channels causing parasite paralysis",
        "mechanism_ja": "大環状ラクトン系。グルタミン酸作動性塩素チャネル活性化で寄生虫麻痺",
        "species_info": {
            "dog": {
                "dose": "6-12 mg/kg 局所（スポットオン）月1回",
                "notes_ja": "フィラリア予防・ノミ・耳ダニ・疥癬・犬回虫。MDR1変異犬にも安全",
                "notes": "Heartworm prevention, fleas, ear mites, sarcoptic mange, roundworms. Safe in MDR1 dogs",
            },
            "cat": {
                "dose": "6-12 mg/kg 局所 月1回",
                "notes_ja": "フィラリア予防・ノミ・耳ダニ・回虫・鉤虫",
                "notes": "Heartworm prevention, fleas, ear mites, roundworms, hookworms",
            },
            "rabbit": {
                "dose": "6-18 mg/kg 局所 月1回",
                "notes_ja": "耳ダニ（Psoroptes）・ノミ・Cheyletiella",
                "notes": "Ear mites, fleas, Cheyletiella",
            },
            "ferret": {
                "dose": "6-18 mg/kg 局所 月1回",
                "notes_ja": "フィラリア予防・ノミ・耳ダニ",
                "notes": "Heartworm prevention, fleas, ear mites",
            },
            "guinea_pig": {
                "dose": "15-20 mg/kg 局所 月1回",
                "notes_ja": "疥癬ダニ（Trixacarus）",
                "notes": "Sarcoptic mange (Trixacarus)",
            },
            "hedgehog": {"dose": "6-18 mg/kg 局所 月1回", "notes_ja": "ダニ・ノミ", "notes": "Mites, fleas"},
        },
        "side_effects": "Transient local hair loss, mild GI upset (rare)",
        "side_effects_ja": "一過性脱毛（局所）、軽度消化器症状（稀）",
        "contraindications": "None significant; safe in MDR1 mutant breeds",
        "contraindications_ja": "特になし。MDR1変異品種にも安全",
        "drug_interactions": [],
    },
    {
        "id": "fipronil_spray",
        "name": "Fipronil Spray/Spot-on",
        "name_ja": "フィプロニル スプレー/スポットオン（フロントライン）",
        "category": "antiparasitic",
        "mechanism": "GABA receptor antagonist in arthropods; disrupts CNS of fleas and ticks",
        "mechanism_ja": "節足動物のGABA受容体拮抗薬。ノミ・ダニのCNSを攪乱",
        "species_info": {
            "dog": {
                "dose": "スポットオン: 月1回; スプレー: 3-6 mL/kg",
                "notes_ja": "ノミ・マダニ駆除。脂溶性で皮脂腺に蓄積",
                "notes": "Flea/tick treatment. Lipophilic, accumulates in sebaceous glands",
            },
            "cat": {"dose": "スポットオン: 月1回", "notes_ja": "猫のノミ・マダニ", "notes": "Feline fleas/ticks"},
            "rabbit": {
                "dose": "スプレー: 3-6 mL/kg; スポットオンは不可",
                "notes_ja": "ウサギはスプレーのみ。スポットオンは皮膚刺激の報告",
                "notes": "Spray only in rabbits. Spot-on may cause skin irritation",
            },
        },
        "side_effects": "Local skin irritation, salivation (if licked), rare neurological signs",
        "side_effects_ja": "局所皮膚刺激、流涎（舐めた場合）、稀に神経症状",
        "contraindications": "Chinchillas (LETHAL), rabbits (spot-on form), kittens <8 weeks",
        "contraindications_ja": "チンチラ（致死的）、ウサギ（スポットオン）、8週齢未満の子猫",
        "drug_interactions": [],
    },
    {
        "id": "imidacloprid_topical",
        "name": "Imidacloprid 10% Spot-on (Advantage)",
        "name_ja": "イミダクロプリド10%スポットオン（アドバンテージ）",
        "category": "antiparasitic",
        "mechanism": "Neonicotinoid; binds nicotinic acetylcholine receptors in insect CNS",
        "mechanism_ja": "ネオニコチノイド系。昆虫CNSのニコチン性アセチルコリン受容体に結合",
        "species_info": {
            "dog": {
                "dose": "10 mg/kg 局所 月1回",
                "notes_ja": "ノミ駆除・予防。24時間以内に98%駆除",
                "notes": "Flea treatment/prevention. 98% kill within 24h",
            },
            "cat": {"dose": "10 mg/kg 局所 月1回", "notes_ja": "猫のノミ駆除", "notes": "Feline flea treatment"},
            "rabbit": {"dose": "10 mg/kg 局所 月1回", "notes_ja": "ノミ・シラミ", "notes": "Fleas, lice"},
            "ferret": {"dose": "0.4 mL/ferret 局所 月1回", "notes_ja": "フェレットのノミ", "notes": "Ferret fleas"},
        },
        "side_effects": "Transient local irritation, rare allergic reaction",
        "side_effects_ja": "一過性局所刺激、稀にアレルギー反応",
        "contraindications": "Kittens/puppies <8 weeks (depending on product)",
        "contraindications_ja": "8週齢未満の子猫/子犬（製品による）",
        "drug_interactions": [],
    },
    {
        "id": "permethrin_topical",
        "name": "Permethrin (Canine Topical)",
        "name_ja": "ペルメトリン（犬用外用）",
        "category": "antiparasitic",
        "mechanism": "Synthetic pyrethroid; blocks sodium channels in arthropod nervous system",
        "mechanism_ja": "合成ピレスロイド系。節足動物の神経系Naチャネルを遮断",
        "species_info": {
            "dog": {
                "dose": "スポットオン/スプレー: 製品に依存",
                "notes_ja": "ノミ・マダニ・蚊忌避。犬専用。猫には絶対使用禁止（致死的中毒）",
                "notes": "Flea/tick/mosquito repellent. DOG ONLY. NEVER use in cats (fatal toxicity)",
            }
        },
        "side_effects": "Rare in dogs; cats: tremors, seizures, DEATH",
        "side_effects_ja": "犬では稀。猫：振戦、痙攣、死亡",
        "contraindications": "CATS (fatal), cats in household with treated dogs (contact transfer)",
        "contraindications_ja": "猫（致死的）、治療犬と同居する猫（接触移行）",
        "drug_interactions": [],
    },
    {
        "id": "fluconazole_oral",
        "name": "Fluconazole (Oral Antifungal)",
        "name_ja": "フルコナゾール（経口抗真菌薬）",
        "category": "antifungals",
        "mechanism": "Triazole; inhibits fungal 14α-demethylase. Excellent CNS/urinary/ocular penetration",
        "mechanism_ja": "トリアゾール系。真菌14α-デメチラーゼ阻害。CNS/泌尿器/眼への優れた移行性",
        "species_info": {
            "dog": {
                "dose": "5-10 mg/kg PO q12-24h",
                "notes_ja": "ブラストミセス（CNS型）・クリプトコッカス・コクシジオイデス・カンジダUTI",
                "notes": "Blastomycosis (CNS), cryptococcosis, coccidioidomycosis, Candida UTI",
            },
            "cat": {
                "dose": "50-100 mg/cat PO q12-24h",
                "notes_ja": "クリプトコッカス症第一選択。CNS移行良好。長期投与に耐容性良好",
                "notes": "First-line cryptococcosis. Good CNS penetration. Well tolerated long-term",
            },
            "bird": {"dose": "5-10 mg/kg PO q24h", "notes_ja": "カンジダ症", "notes": "Candidiasis"},
            "reptile": {"dose": "5 mg/kg PO q24h", "notes_ja": "真菌感染", "notes": "Fungal infections"},
        },
        "side_effects": "Hepatotoxicity, GI upset, teratogenic",
        "side_effects_ja": "肝毒性、消化器症状、催奇形性",
        "contraindications": "Pregnancy, severe hepatic disease",
        "contraindications_ja": "妊娠、重度肝疾患",
        "drug_interactions": [
            {
                "drug": "ciclosporin",
                "severity": "major",
                "description_ja": "シクロスポリン血中濃度上昇",
                "description": "Increased ciclosporin levels",
            },
            {
                "drug": "warfarin",
                "severity": "major",
                "description_ja": "抗凝固効果増強",
                "description": "Enhanced anticoagulant effect",
            },
        ],
    },
    {
        "id": "itraconazole_oral",
        "name": "Itraconazole (Oral)",
        "name_ja": "イトラコナゾール（経口・イトリゾール）",
        "category": "antifungals",
        "mechanism": "Triazole; broad-spectrum antifungal. Better against dimorphic fungi than fluconazole",
        "mechanism_ja": "トリアゾール系。広域抗真菌薬。二形性真菌にフルコナゾールより有効",
        "species_info": {
            "dog": {
                "dose": "5-10 mg/kg PO q24h（食事と併用で吸収↑）",
                "notes_ja": "ブラストミセス・ヒストプラズマ・アスペルギルス・皮膚糸状菌。食事と一緒に投与",
                "notes": "Blastomycosis, histoplasmosis, aspergillosis, dermatophytosis. Give with food",
            },
            "cat": {
                "dose": "5-10 mg/kg PO q24h",
                "notes_ja": "皮膚糸状菌症（テルビナフィンの代替）・アスペルギルス症",
                "notes": "Dermatophytosis (terbinafine alternative), aspergillosis",
            },
            "horse": {
                "dose": "5 mg/kg PO q24h",
                "notes_ja": "副鼻腔真菌症・真菌性胸膜炎",
                "notes": "Sinonasal mycosis, fungal pleuritis",
            },
            "bird": {
                "dose": "5-10 mg/kg PO q12-24h",
                "notes_ja": "アスペルギルス症第一選択",
                "notes": "First-line aspergillosis",
            },
            "reptile": {"dose": "5 mg/kg PO q24h", "notes_ja": "真菌感染", "notes": "Fungal infections"},
        },
        "side_effects": "Hepatotoxicity, GI upset, vasculitis (high dose), teratogenic",
        "side_effects_ja": "肝毒性、消化器症状、血管炎（高用量）、催奇形性",
        "contraindications": "Hepatic disease, pregnancy, concurrent cisapride",
        "contraindications_ja": "肝疾患、妊娠、シサプリド併用",
        "drug_interactions": [
            {
                "drug": "cisapride",
                "severity": "major",
                "description_ja": "QT延長リスク",
                "description": "QT prolongation risk",
            },
            {
                "drug": "ciclosporin",
                "severity": "major",
                "description_ja": "CsA血中濃度上昇",
                "description": "Increased CsA levels",
            },
        ],
    },
    {
        "id": "trilostane_oral",
        "name": "Trilostane (Vetoryl)",
        "name_ja": "トリロスタン（ベトリル）",
        "category": "endocrine",
        "mechanism": "Competitive inhibitor of 3β-hydroxysteroid dehydrogenase; blocks cortisol synthesis",
        "mechanism_ja": "3β-ヒドロキシステロイド脱水素酵素の競合的阻害薬。コルチゾール合成を遮断",
        "species_info": {
            "dog": {
                "dose": "1-2 mg/kg PO q12h（食事と併用）; ACTHスティム試験で用量調整",
                "notes_ja": "犬のクッシング症候群（PDH/ADH）第一選択。ACTH刺激試験で調整。副腎壊死リスクに注意",
                "notes": "First-line canine Cushing's (PDH/ADH). Adjust by ACTH stim test. Adrenal necrosis risk",
            },
            "ferret": {
                "dose": "1-2 mg/kg PO q12-24h",
                "notes_ja": "フェレットの副腎疾患（外科代替）",
                "notes": "Ferret adrenal disease (surgical alternative)",
            },
        },
        "side_effects": "Lethargy, anorexia, Addisonian crisis, adrenal necrosis, electrolyte abnormalities",
        "side_effects_ja": "倦怠感、食欲不振、アジソンクリーゼ、副腎壊死、電解質異常",
        "contraindications": "Hepatic disease, renal disease, concurrent medications metabolized by CYP",
        "contraindications_ja": "肝疾患、腎疾患",
        "drug_interactions": [
            {
                "drug": "ace_inhibitors",
                "severity": "moderate",
                "description_ja": "高カリウム血症リスク",
                "description": "Hyperkalemia risk",
            },
            {
                "drug": "spironolactone",
                "severity": "moderate",
                "description_ja": "高カリウム血症リスク",
                "description": "Hyperkalemia risk",
            },
        ],
    },
    {
        "id": "cabergoline_prolactin",
        "name": "Cabergoline (Galastop)",
        "name_ja": "カベルゴリン（ギャラストップ）",
        "category": "reproductive",
        "mechanism": "Dopamine D2 agonist; inhibits prolactin secretion from anterior pituitary",
        "mechanism_ja": "ドパミンD2作動薬。下垂体前葉からのプロラクチン分泌を抑制",
        "species_info": {
            "dog": {
                "dose": "5 μg/kg PO q24h × 5-10日",
                "notes_ja": "偽妊娠・乳腺炎後の乳汁分泌抑制・妊娠中絶（プロスタグランジンと併用）",
                "notes": "Pseudopregnancy, lactation suppression, pregnancy termination (with prostaglandin)",
            },
            "cat": {
                "dose": "5 μg/kg PO q24h × 5-7日",
                "notes_ja": "偽妊娠・乳汁分泌抑制",
                "notes": "Pseudopregnancy, lactation suppression",
            },
        },
        "side_effects": "Vomiting (first dose), mild lethargy",
        "side_effects_ja": "嘔吐（初回投与時）、軽度倦怠感",
        "contraindications": "Pregnancy (unless termination intended)",
        "contraindications_ja": "妊娠（中絶目的以外）",
        "drug_interactions": [],
    },
    {
        "id": "prostaglandin_f2a",
        "name": "Prostaglandin F2α (Dinoprost/Lutalyse)",
        "name_ja": "プロスタグランジンF2α（ジノプロスト/ルタライズ）",
        "category": "reproductive",
        "mechanism": "Luteolytic; destroys corpus luteum, contracts uterine smooth muscle",
        "mechanism_ja": "黄体溶解薬。黄体を破壊し、子宮平滑筋を収縮",
        "species_info": {
            "dog": {
                "dose": "100-250 μg/kg SC q12-24h × 5-7日",
                "notes_ja": "子宮蓄膿症（開放性、外科不可の場合）・妊娠中絶。重度副作用あり→入院管理推奨",
                "notes": "Open pyometra (when surgery impossible), pregnancy termination. Severe side effects → hospitalize",
            },
            "cat": {
                "dose": "100-250 μg/kg SC q12-24h × 3-5日",
                "notes_ja": "開放性子宮蓄膿症の内科的治療",
                "notes": "Medical treatment of open pyometra",
            },
            "horse": {
                "dose": "5-10 mg/horse IM 1回",
                "notes_ja": "黄体退行→発情誘発・子宮蓄膿症",
                "notes": "Luteolysis → estrus induction, pyometra",
            },
        },
        "side_effects": "Vomiting, diarrhea, salivation, restlessness, panting, abdominal pain, death (overdose)",
        "side_effects_ja": "嘔吐、下痢、流涎、不穏、パンティング、腹痛、死亡（過量時）",
        "contraindications": "Pregnancy (unless termination), closed-cervix pyometra, asthma",
        "contraindications_ja": "妊娠（中絶目的以外）、閉鎖性子宮蓄膿症、喘息",
        "drug_interactions": [],
    },
    {
        "id": "aluminum_phosphate_binder",
        "name": "Aluminum Hydroxide (Phosphate Binder)",
        "name_ja": "水酸化アルミニウム（リン吸着薬）",
        "category": "miscellaneous",
        "mechanism": "Binds dietary phosphorus in GI tract, preventing absorption; reduces hyperphosphatemia",
        "mechanism_ja": "消化管内で食事中のリンに結合し吸収を防止。高リン血症を軽減",
        "species_info": {
            "dog": {
                "dose": "30-90 mg/kg PO q8-12h（食事と併用）",
                "notes_ja": "CKDの高リン血症管理。食事と一緒に投与（食事中のPを吸着）",
                "notes": "CKD hyperphosphatemia management. Give with food (binds dietary P)",
            },
            "cat": {
                "dose": "30-90 mg/kg PO q8-12h（食事と併用）",
                "notes_ja": "猫のCKDリン管理。IRIS Stage 3-4で必須",
                "notes": "Feline CKD phosphorus management. Essential in IRIS Stage 3-4",
            },
            "rabbit": {"dose": "30 mg/kg PO q8h", "notes_ja": "CKDでの高リン血症", "notes": "CKD hyperphosphatemia"},
            "ferret": {"dose": "30 mg/kg PO q8-12h", "notes_ja": "CKDでの高リン血症", "notes": "CKD hyperphosphatemia"},
        },
        "side_effects": "Constipation, aluminum accumulation (long-term/renal failure)",
        "side_effects_ja": "便秘、アルミニウム蓄積（長期/腎不全時）",
        "contraindications": "None absolute; monitor aluminum levels in severe CKD",
        "contraindications_ja": "絶対的禁忌なし。重度CKDではアルミニウム値モニタリング",
        "drug_interactions": [
            {
                "drug": "fluoroquinolones",
                "severity": "major",
                "description_ja": "キノロン吸収低下（2時間空ける）",
                "description": "Decreased quinolone absorption (separate by 2h)",
            },
            {
                "drug": "tetracyclines",
                "severity": "moderate",
                "description_ja": "吸収低下",
                "description": "Decreased absorption",
            },
        ],
    },
    {
        "id": "amlodipine_feline",
        "name": "Amlodipine (Feline Hypertension)",
        "name_ja": "アムロジピン（猫の高血圧）",
        "category": "cardiovascular",
        "mechanism": "Calcium channel blocker (dihydropyridine); selective arteriolar vasodilation",
        "mechanism_ja": "カルシウムチャネル遮断薬（ジヒドロピリジン系）。選択的細動脈拡張",
        "species_info": {
            "cat": {
                "dose": "0.625-1.25 mg/cat PO q24h",
                "notes_ja": "猫の全身性高血圧第一選択。CKD/甲状腺機能亢進症に伴う高血圧。収縮期血圧<160 mmHg目標",
                "notes": "First-line feline systemic hypertension. CKD/hyperthyroidism-associated. Target SBP <160 mmHg",
            },
            "dog": {
                "dose": "0.1-0.5 mg/kg PO q24h",
                "notes_ja": "犬の全身性高血圧。ACE阻害薬との併用可",
                "notes": "Canine systemic hypertension. Can combine with ACE inhibitors",
            },
        },
        "side_effects": "Hypotension, tachycardia, gingival hyperplasia",
        "side_effects_ja": "低血圧、頻脈、歯肉肥厚",
        "contraindications": "Severe aortic stenosis, hypertrophic cardiomyopathy with outflow obstruction",
        "contraindications_ja": "重度大動脈弁狭窄、流出路閉塞を伴うHCM",
        "drug_interactions": [
            {
                "drug": "beta_blockers",
                "severity": "moderate",
                "description_ja": "過度の降圧・徐脈",
                "description": "Excessive hypotension/bradycardia",
            }
        ],
    },
    {
        "id": "benazepril_ckd",
        "name": "Benazepril (Renal Protectant)",
        "name_ja": "ベナゼプリル（腎保護）",
        "category": "cardiovascular",
        "mechanism": "ACE inhibitor; reduces glomerular capillary pressure via efferent arteriole dilation",
        "mechanism_ja": "ACE阻害薬。輸出細動脈拡張により糸球体毛細血管圧を低下",
        "species_info": {
            "dog": {
                "dose": "0.25-0.5 mg/kg PO q12-24h",
                "notes_ja": "CKDの腎保護・蛋白尿軽減。IRIS推奨",
                "notes": "CKD renal protection, proteinuria reduction. IRIS recommended",
            },
            "cat": {
                "dose": "0.5-1 mg/kg PO q24h",
                "notes_ja": "猫のCKD腎保護。BENRIC試験で猫CKDの生存期間延長が示唆",
                "notes": "Feline CKD renal protection. BENRIC study suggested improved survival",
            },
        },
        "side_effects": "Hyperkalemia, azotemia worsening (dehydrated patients), hypotension",
        "side_effects_ja": "高カリウム血症、高窒素血症増悪（脱水時）、低血圧",
        "contraindications": "Bilateral renal artery stenosis, dehydration, hyperkalemia",
        "contraindications_ja": "両側腎動脈狭窄、脱水、高カリウム血症",
        "drug_interactions": [
            {
                "drug": "potassium_supplements",
                "severity": "major",
                "description_ja": "高カリウム血症リスク",
                "description": "Hyperkalemia risk",
            },
            {
                "drug": "nsaids",
                "severity": "moderate",
                "description_ja": "腎保護効果の減弱",
                "description": "Attenuated renal protective effect",
            },
        ],
    },
    {
        "id": "telmisartan_feline",
        "name": "Telmisartan (Semintra Feline)",
        "name_ja": "テルミサルタン（セミントラ猫用）",
        "category": "cardiovascular",
        "mechanism": "Angiotensin II receptor blocker (ARB); blocks AT1 receptor. Alternative to ACE inhibitors",
        "mechanism_ja": "アンジオテンシンII受容体遮断薬（ARB）。AT1受容体を遮断。ACE阻害薬の代替",
        "species_info": {
            "cat": {
                "dose": "1-2 mg/kg PO q24h（液剤）",
                "notes_ja": "猫のCKD蛋白尿軽減。唯一の猫認可ARB（セミントラ）。高い猫の嗜好性",
                "notes": "Feline CKD proteinuria reduction. Only cat-licensed ARB (Semintra). High palatability",
            },
            "dog": {
                "dose": "1 mg/kg PO q24h",
                "notes_ja": "蛋白尿・高血圧（ACEiの代替/追加）",
                "notes": "Proteinuria, hypertension (alternative/addition to ACEi)",
            },
        },
        "side_effects": "GI upset, hypotension, hyperkalemia",
        "side_effects_ja": "消化器症状、低血圧、高カリウム血症",
        "contraindications": "Pregnancy, dehydration, hyperkalemia",
        "contraindications_ja": "妊娠、脱水、高カリウム血症",
        "drug_interactions": [
            {
                "drug": "ace_inhibitors",
                "severity": "moderate",
                "description_ja": "双重RAAS遮断→高カリウム血症・低血圧リスク",
                "description": "Dual RAAS blockade, hyperkalemia/hypotension risk",
            }
        ],
    },
    {
        "id": "chlorambucil_oral",
        "name": "Chlorambucil (Leukeran)",
        "name_ja": "クロラムブシル（ロイケラン）",
        "category": "antineoplastic",
        "mechanism": "Nitrogen mustard alkylating agent; cross-links DNA strands. Slow-acting, well-tolerated",
        "mechanism_ja": "ナイトロジェンマスタードアルキル化薬。DNA鎖を架橋。緩徐作用で忍容性良好",
        "species_info": {
            "dog": {
                "dose": "4-6 mg/m² PO q24-48h; パルス: 20 mg/m² q14日",
                "notes_ja": "リンパ腫維持療法・慢性リンパ性白血病・IBD（免疫抑制）",
                "notes": "Lymphoma maintenance, CLL, IBD (immunosuppressive)",
            },
            "cat": {
                "dose": "2-6 mg/cat PO q48-72h",
                "notes_ja": "猫の小細胞リンパ腫第一選択（+プレドニゾロン）。IBD/消化管リンパ腫鑑別困難例にも",
                "notes": "First-line feline small cell lymphoma (+prednisolone). Also for IBD/GI lymphoma borderline cases",
            },
        },
        "side_effects": "Bone marrow suppression (delayed, nadir 7-14 days), GI upset, hepatotoxicity",
        "side_effects_ja": "骨髄抑制（遅発性、最低値7-14日）、消化器症状、肝毒性",
        "contraindications": "Bone marrow failure, concurrent myelosuppressive drugs",
        "contraindications_ja": "骨髄不全、骨髄抑制薬併用",
        "drug_interactions": [
            {
                "drug": "azathioprine",
                "severity": "major",
                "description_ja": "骨髄抑制の相加",
                "description": "Additive myelosuppression",
            }
        ],
    },
    {
        "id": "vincristine_injectable",
        "name": "Vincristine Injectable",
        "name_ja": "ビンクリスチン注射",
        "category": "antineoplastic",
        "mechanism": "Vinca alkaloid; inhibits microtubule polymerization arresting mitosis at metaphase",
        "mechanism_ja": "ビンカアルカロイド。微小管重合を阻害し有糸分裂を中期で停止",
        "species_info": {
            "dog": {
                "dose": "0.5-0.7 mg/m² IV 週1回（CHOP protocol）",
                "notes_ja": "リンパ腫（CHOP）・TVT・免疫介在性血小板減少症（血小板放出促進）",
                "notes": "Lymphoma (CHOP), TVT, immune-mediated thrombocytopenia (platelet release)",
            },
            "cat": {
                "dose": "0.5 mg/m² IV 週1回",
                "notes_ja": "猫のリンパ腫（COP protocol）",
                "notes": "Feline lymphoma (COP protocol)",
            },
        },
        "side_effects": "Vesicant (tissue necrosis on extravasation), GI upset, peripheral neuropathy, bone marrow suppression (mild)",
        "side_effects_ja": "組織壊死（血管外漏出時）、消化器症状、末梢神経障害、骨髄抑制（軽度）",
        "contraindications": "Extravasation (vesicant!), severe hepatic disease",
        "contraindications_ja": "血管外漏出（組織壊死薬！）、重度肝疾患",
        "drug_interactions": [],
    },
    {
        "id": "doxorubicin_injectable",
        "name": "Doxorubicin Injectable",
        "name_ja": "ドキソルビシン注射",
        "category": "antineoplastic",
        "mechanism": "Anthracycline; DNA intercalation, topoisomerase II inhibition, free radical generation",
        "mechanism_ja": "アントラサイクリン系。DNA挿入、トポイソメラーゼII阻害、フリーラジカル産生",
        "species_info": {
            "dog": {
                "dose": "30 mg/m² IV q21日; 累積最大量 180-240 mg/m²",
                "notes_ja": "リンパ腫（CHOP）・骨肉腫（術後補助）・血管肉腫。累積心毒性に注意",
                "notes": "Lymphoma (CHOP), osteosarcoma (adjuvant), hemangiosarcoma. Cumulative cardiotoxicity",
            },
            "cat": {
                "dose": "1 mg/kg IV q21日（最大20-25 mg/cat）; 累積6回まで",
                "notes_ja": "猫のリンパ腫・乳腺腫瘍。猫は腎毒性リスク高い→用量制限",
                "notes": "Feline lymphoma, mammary tumor. Cats: higher nephrotoxicity risk → dose limiting",
            },
        },
        "side_effects": "Cardiotoxicity (cumulative), myelosuppression (nadir 7-10 days), GI upset, alopecia (certain breeds), vesicant",
        "side_effects_ja": "心毒性（累積）、骨髄抑制（最低値7-10日）、消化器症状、脱毛（一部品種）、組織壊死（漏出時）",
        "contraindications": "Cardiac disease, cumulative dose limit exceeded, cats with renal disease",
        "contraindications_ja": "心疾患、累積用量上限超過、腎疾患の猫",
        "drug_interactions": [
            {
                "drug": "dexrazoxane",
                "severity": "moderate",
                "description_ja": "心毒性軽減（意図的併用）",
                "description": "Cardioprotection (intentional combination)",
            }
        ],
    },
    {
        "id": "cyclophosphamide_oral",
        "name": "Cyclophosphamide Oral",
        "name_ja": "シクロホスファミド経口",
        "category": "antineoplastic",
        "mechanism": "Nitrogen mustard alkylating agent; requires hepatic activation. Cross-links DNA",
        "mechanism_ja": "ナイトロジェンマスタード系アルキル化薬。肝活性化が必要。DNAを架橋",
        "species_info": {
            "dog": {
                "dose": "200-250 mg/m² PO q21日（CHOP内）; 連日: 50 mg/m² PO q48h",
                "notes_ja": "リンパ腫（CHOP）・免疫介在性疾患。出血性膀胱炎予防にフロセミド併用",
                "notes": "Lymphoma (CHOP), immune-mediated disease. Give furosemide to prevent hemorrhagic cystitis",
            },
            "cat": {
                "dose": "200-250 mg/m² PO q21日",
                "notes_ja": "猫のリンパ腫（COP protocol）",
                "notes": "Feline lymphoma (COP protocol)",
            },
        },
        "side_effects": "Hemorrhagic cystitis (sterile), myelosuppression, GI upset, alopecia",
        "side_effects_ja": "出血性膀胱炎（無菌性）、骨髄抑制、消化器症状、脱毛",
        "contraindications": "Existing cystitis, bone marrow failure",
        "contraindications_ja": "既存の膀胱炎、骨髄不全",
        "drug_interactions": [
            {
                "drug": "azathioprine",
                "severity": "major",
                "description_ja": "骨髄抑制の相加",
                "description": "Additive myelosuppression",
            }
        ],
    },
    {
        "id": "piroxicam_bladder",
        "name": "Piroxicam (Bladder TCC)",
        "name_ja": "ピロキシカム（膀胱移行上皮癌）",
        "category": "antineoplastic",
        "mechanism": "Non-selective COX inhibitor with direct antitumor activity against transitional cell carcinoma",
        "mechanism_ja": "非選択的COX阻害薬。移行上皮癌に対する直接的抗腫瘍活性",
        "species_info": {
            "dog": {
                "dose": "0.3 mg/kg PO q24h",
                "notes_ja": "膀胱移行上皮癌（TCC）。緩和療法として腫瘍安定・縮小効果。GI保護併用推奨",
                "notes": "Bladder TCC. Tumor stabilization/reduction as palliative. GI protection recommended",
            }
        },
        "side_effects": "GI ulceration (high risk), renal injury, hepatotoxicity",
        "side_effects_ja": "消化管潰瘍（高リスク）、腎障害、肝毒性",
        "contraindications": "Renal disease, GI ulceration, concurrent NSAIDs/corticosteroids",
        "contraindications_ja": "腎疾患、消化管潰瘍、NSAID/コルチコステロイド併用",
        "drug_interactions": [
            {
                "drug": "corticosteroids",
                "severity": "major",
                "description_ja": "消化管潰瘍リスクの著明な増加",
                "description": "Markedly increased GI ulceration risk",
            }
        ],
    },
    {
        "id": "palladia_oral",
        "name": "Toceranib (Palladia) Oral",
        "name_ja": "トセラニブ（パラディア）経口",
        "category": "antineoplastic",
        "mechanism": "Multi-targeted receptor tyrosine kinase inhibitor; blocks VEGFR, PDGFR, Kit",
        "mechanism_ja": "マルチターゲット受容体チロシンキナーゼ阻害薬。VEGFR/PDGFR/Kitを遮断",
        "species_info": {
            "dog": {
                "dose": "2.75 mg/kg PO 隔日投与（MWF）",
                "notes_ja": "肥満細胞腫（c-Kit変異）・その他の固形腫瘍。隔日投与で副作用軽減",
                "notes": "Mast cell tumors (c-Kit mutation), other solid tumors. Every-other-day dosing reduces side effects",
            },
            "cat": {
                "dose": "2.5 mg/kg PO 隔日投与",
                "notes_ja": "猫の固形腫瘍（限定的データ）",
                "notes": "Feline solid tumors (limited data)",
            },
        },
        "side_effects": "GI upset, neutropenia, hepatotoxicity, proteinuria, hypertension, muscle pain",
        "side_effects_ja": "消化器症状、好中球減少、肝毒性、蛋白尿、高血圧、筋肉痛",
        "contraindications": "Hepatic disease, existing GI ulceration, concurrent NSAIDs (GI risk)",
        "contraindications_ja": "肝疾患、既存消化管潰瘍、NSAID併用（GIリスク）",
        "drug_interactions": [
            {
                "drug": "nsaids",
                "severity": "major",
                "description_ja": "消化管潰瘍リスク増加",
                "description": "Increased GI ulceration risk",
            }
        ],
    },
    {
        "id": "melatonin_implant",
        "name": "Melatonin (Implant/Oral)",
        "name_ja": "メラトニン（インプラント/経口）",
        "category": "endocrine",
        "mechanism": "Pineal hormone; modulates reproductive and seasonal cycles, inhibits cortisol at adrenal level",
        "mechanism_ja": "松果体ホルモン。生殖・季節周期を調節、副腎レベルでコルチゾールを抑制",
        "species_info": {
            "dog": {
                "dose": "3-6 mg PO q8-12h; インプラント: 8-12 mgを皮下",
                "notes_ja": "季節性脱毛症・アロペシアX・クッシング症候群補助",
                "notes": "Seasonal flank alopecia, alopecia X, Cushing's adjunct",
            },
            "ferret": {
                "dose": "0.5-1 mg PO q24h（夕方）; インプラント5.4mg",
                "notes_ja": "フェレットの副腎疾患（デスロレリンの代替/補助）",
                "notes": "Ferret adrenal disease (deslorelin alternative/adjunct)",
            },
            "hamster": {"dose": "0.5-1 mg PO q24h", "notes_ja": "季節性脱毛", "notes": "Seasonal alopecia"},
        },
        "side_effects": "Mild sedation, rarely increased aggression",
        "side_effects_ja": "軽度鎮静、稀に攻撃性増加",
        "contraindications": "None significant",
        "contraindications_ja": "特になし",
        "drug_interactions": [],
    },
    {
        "id": "methionine_urinary",
        "name": "DL-Methionine (Urinary Acidifier)",
        "name_ja": "DL-メチオニン（尿酸性化薬）",
        "category": "miscellaneous",
        "mechanism": "Metabolized to sulfuric acid, lowering urinary pH",
        "mechanism_ja": "硫酸に代謝され尿pHを低下",
        "species_info": {
            "dog": {
                "dose": "200-500 mg/dog PO q12h",
                "notes_ja": "ストルバイト尿石症の再発予防（食事療法の補助）",
                "notes": "Struvite urolithiasis recurrence prevention (diet adjunct)",
            },
            "cat": {
                "dose": "200-500 mg/cat PO q12h",
                "notes_ja": "猫のストルバイト尿石症予防",
                "notes": "Feline struvite prevention",
            },
        },
        "side_effects": "GI upset, metabolic acidosis (overdose), Heinz body anemia (cats, high dose)",
        "side_effects_ja": "消化器症状、代謝性アシドーシス（過量）、ハインツ小体性貧血（猫、高用量）",
        "contraindications": "Hepatic encephalopathy, metabolic acidosis, calcium oxalate urolithiasis",
        "contraindications_ja": "肝性脳症、代謝性アシドーシス、シュウ酸カルシウム尿石症",
        "drug_interactions": [],
    },
    {
        "id": "potassium_citrate",
        "name": "Potassium Citrate",
        "name_ja": "クエン酸カリウム",
        "category": "miscellaneous",
        "mechanism": "Urinary alkalinizer; metabolized to bicarbonate, increases urinary pH and citrate (inhibits CaOx)",
        "mechanism_ja": "尿アルカリ化薬。重炭酸塩に代謝され尿pHとクエン酸を増加（CaOx結石阻害）",
        "species_info": {
            "dog": {
                "dose": "50-75 mg/kg PO q12h",
                "notes_ja": "シュウ酸カルシウム尿石症の再発予防。尿pH 7.0-7.5目標",
                "notes": "Calcium oxalate urolithiasis prevention. Target urine pH 7.0-7.5",
            },
            "cat": {
                "dose": "40-75 mg/kg PO q12h",
                "notes_ja": "猫のシュウ酸カルシウム結石予防",
                "notes": "Feline calcium oxalate stone prevention",
            },
        },
        "side_effects": "GI upset, hyperkalemia (renal failure)",
        "side_effects_ja": "消化器症状、高カリウム血症（腎不全時）",
        "contraindications": "Struvite urolithiasis (alkalinization worsens), hyperkalemia, obstructive uropathy",
        "contraindications_ja": "ストルバイト尿石症（アルカリ化で悪化）、高カリウム血症、閉塞性尿路疾患",
        "drug_interactions": [],
    },
    {
        "id": "tamsulosin",
        "name": "Tamsulosin",
        "name_ja": "タムスロシン",
        "category": "miscellaneous",
        "mechanism": "Selective α1A-adrenergic antagonist; relaxes urethral and prostatic smooth muscle",
        "mechanism_ja": "選択的α1Aアドレナリン拮抗薬。尿道・前立腺平滑筋を弛緩",
        "species_info": {
            "dog": {
                "dose": "0.04-0.06 mg/kg PO q24h",
                "notes_ja": "前立腺肥大症・尿道閉塞の補助・尿路結石の自然排出促進",
                "notes": "BPH, urethral obstruction adjunct, urolithiasis expulsive therapy",
            },
            "cat": {
                "dose": "0.004-0.006 mg/kg PO q24h",
                "notes_ja": "猫の尿道痙攣・FIC後の尿道弛緩",
                "notes": "Urethral spasm, post-FIC urethral relaxation",
            },
        },
        "side_effects": "Hypotension, dizziness",
        "side_effects_ja": "低血圧、めまい",
        "contraindications": "Severe hypotension",
        "contraindications_ja": "重度低血圧",
        "drug_interactions": [
            {
                "drug": "alpha_blockers",
                "severity": "moderate",
                "description_ja": "低血圧増悪",
                "description": "Worsened hypotension",
            }
        ],
    },
    {
        "id": "pentobarbital_euthanasia",
        "name": "Pentobarbital (Euthanasia Solution)",
        "name_ja": "ペントバルビタール（安楽死液）",
        "category": "anesthetics",
        "mechanism": "Barbiturate; profound CNS depression, respiratory arrest, cardiac arrest at euthanasia doses",
        "mechanism_ja": "バルビツール酸系。安楽死用量で深いCNS抑制→呼吸停止→心停止",
        "species_info": {
            "dog": {
                "dose": "85-100 mg/kg IV（安楽死）",
                "notes_ja": "安楽死のゴールドスタンダード（AVMA Guidelines 2020）。意識消失→呼吸停止→心停止の順",
                "notes": "Gold standard euthanasia (AVMA 2020). Unconsciousness → respiratory arrest → cardiac arrest",
            },
            "cat": {"dose": "85-100 mg/kg IV", "notes_ja": "猫の安楽死", "notes": "Feline euthanasia"},
            "horse": {
                "dose": "85 mg/kg IV",
                "notes_ja": "馬の安楽死。倒れる方向に注意",
                "notes": "Equine euthanasia. Mind direction of recumbency",
            },
            "rabbit": {
                "dose": "85-100 mg/kg IV",
                "notes_ja": "ウサギの安楽死。耳介静脈から",
                "notes": "Rabbit euthanasia. Via auricular vein",
            },
            "bird": {"dose": "100 mg/kg IV/ICe", "notes_ja": "鳥類の安楽死", "notes": "Avian euthanasia"},
            "reptile": {
                "dose": "100 mg/kg IV/ICe",
                "notes_ja": "爬虫類の安楽死。心停止確認に時間要する",
                "notes": "Reptilian euthanasia. Cardiac cessation confirmation takes time",
            },
        },
        "side_effects": "Not applicable (euthanasia agent)",
        "side_effects_ja": "該当なし（安楽死薬）",
        "contraindications": "None for euthanasia use",
        "contraindications_ja": "安楽死目的では禁忌なし",
        "drug_interactions": [],
    },
    {
        "id": "ms222_fish",
        "name": "Tricaine Methanesulfonate (MS-222)",
        "name_ja": "トリカインメタンスルホン酸（MS-222）",
        "category": "anesthetics",
        "mechanism": "Sodium channel blocker; blocks nerve conduction in aquatic animals via immersion",
        "mechanism_ja": "Naチャネル遮断薬。浸漬により水生動物の神経伝導を遮断",
        "species_info": {
            "fish": {
                "dose": "鎮静: 50-100 mg/L; 麻酔: 100-200 mg/L; 安楽死: 250+ mg/L",
                "notes_ja": "魚の標準麻酔薬。pH緩衝（NaHCO3等量添加）が必須。鰓蓋運動でモニタリング",
                "notes": "Standard fish anesthetic. pH buffering required (equal weight NaHCO3). Monitor opercular movement",
            },
            "amphibian": {
                "dose": "鎮静: 0.5-1 g/L 浸漬; 麻酔: 1-3 g/L",
                "notes_ja": "両生類の浸漬麻酔。皮膚吸収。pH緩衝必須",
                "notes": "Amphibian immersion anesthesia. Dermal absorption. Buffer pH essential",
            },
        },
        "side_effects": "Bradycardia, respiratory depression, prolonged recovery at low temperatures",
        "side_effects_ja": "徐脈、呼吸抑制、低温での覚醒遅延",
        "contraindications": "None for aquatic use",
        "contraindications_ja": "水生動物での使用では禁忌なし",
        "drug_interactions": [],
    },
    {
        "id": "eugenol_fish",
        "name": "Eugenol (Clove Oil)",
        "name_ja": "オイゲノール（クローブオイル）",
        "category": "anesthetics",
        "mechanism": "GABA receptor agonist and sodium channel blocker; immersion anesthetic for fish",
        "mechanism_ja": "GABA受容体作動薬＋Naチャネル遮断薬。魚用浸漬麻酔薬",
        "species_info": {
            "fish": {
                "dose": "鎮静: 25-50 mg/L; 麻酔: 40-100 mg/L; 安楽死: 300+ mg/L",
                "notes_ja": "MS-222の安価な代替。エタノールに溶解して使用。FDA未認可だが広く使用",
                "notes": "Inexpensive MS-222 alternative. Dissolve in ethanol first. Not FDA-approved but widely used",
            },
            "amphibian": {
                "dose": "鎮静: 50-100 mg/L 浸漬",
                "notes_ja": "両生類の浸漬鎮静",
                "notes": "Amphibian immersion sedation",
            },
        },
        "side_effects": "Tissue irritation at high concentration, gill damage",
        "side_effects_ja": "高濃度での組織刺激、鰓損傷",
        "contraindications": "Food fish within withdrawal period",
        "contraindications_ja": "食用魚の休薬期間中",
        "drug_interactions": [],
    },
    {
        "id": "alfaprostol",
        "name": "Alfaprostol (Alfavet)",
        "name_ja": "アルファプロストール",
        "category": "reproductive",
        "mechanism": "Synthetic PGF2α analogue; luteolytic with uterotonic activity",
        "mechanism_ja": "合成PGF2αアナログ。黄体溶解・子宮収縮活性",
        "species_info": {
            "horse": {
                "dose": "3 mg/horse IM 1回",
                "notes_ja": "発情同期化・黄体退行",
                "notes": "Estrus synchronization, luteolysis",
            },
            "dog": {"dose": "データ限定的", "notes_ja": "使用データ限定的", "notes": "Limited data"},
        },
        "side_effects": "Sweating, colic (horses), diarrhea",
        "side_effects_ja": "発汗、疝痛（馬）、下痢",
        "contraindications": "Pregnancy, respiratory disease",
        "contraindications_ja": "妊娠、呼吸器疾患",
        "drug_interactions": [],
    },
    {
        "id": "altrenogest",
        "name": "Altrenogest (Regu-Mate)",
        "name_ja": "アルトレノゲスト（レギュメイト）",
        "category": "reproductive",
        "mechanism": "Synthetic progestogen; suppresses estrus and maintains pregnancy by mimicking progesterone",
        "mechanism_ja": "合成プロゲストーゲン。プロゲステロンを模倣し発情を抑制、妊娠を維持",
        "species_info": {
            "horse": {
                "dose": "0.044 mg/kg PO q24h × 15日（発情抑制）",
                "notes_ja": "発情同期化・発情抑制・習慣性流産予防。取扱い者への経皮吸収注意（手袋必須）",
                "notes": "Estrus synchronization/suppression, habitual abortion prevention. HANDLER: wear gloves (dermal absorption)",
            }
        },
        "side_effects": "Prolonged luteal phase, uterine infection (if contaminated)",
        "side_effects_ja": "黄体期延長、子宮感染（汚染時）",
        "contraindications": "Uterine infection, pregnancy (unless maintenance intended)",
        "contraindications_ja": "子宮感染、妊娠（維持目的以外）",
        "drug_interactions": [],
    },
    {
        "id": "domperidone_equine",
        "name": "Domperidone (Equi-Tox)",
        "name_ja": "ドンペリドン（馬用）",
        "category": "gastrointestinal",
        "mechanism": "Peripheral dopamine D2 antagonist; prokinetic + increases prolactin secretion",
        "mechanism_ja": "末梢ドパミンD2拮抗薬。消化管運動促進＋プロラクチン分泌促進",
        "species_info": {
            "horse": {
                "dose": "1.1 mg/kg PO q24h × 10-30日（フェスクー毒性）",
                "notes_ja": "フェスクー（エンドファイト）毒性：泌乳不全・胎盤遅延・妊娠末期の問題を予防",
                "notes": "Fescue toxicosis: prevents agalactia, prolonged gestation, placental problems",
            }
        },
        "side_effects": "Mild colic, diarrhea",
        "side_effects_ja": "軽度疝痛、下痢",
        "contraindications": "None significant",
        "contraindications_ja": "特になし",
        "drug_interactions": [],
    },
    {
        "id": "oxyglobin",
        "name": "Oxyglobin (HBOC)",
        "name_ja": "オキシグロビン（HBOC）",
        "category": "miscellaneous",
        "mechanism": "Hemoglobin-based oxygen carrier; polymerized bovine hemoglobin providing oxygen delivery without RBCs",
        "mechanism_ja": "ヘモグロビンベース酸素運搬体。重合ウシヘモグロビンがRBC不要で酸素を運搬",
        "species_info": {
            "dog": {
                "dose": "10-30 mL/kg IV（最大速度10 mL/kg/hr）",
                "notes_ja": "重度貧血の橋渡し療法（輸血が入手困難な場合）。IMHA・急性出血",
                "notes": "Bridge therapy for severe anemia when transfusion unavailable. IMHA, acute hemorrhage",
            },
            "cat": {
                "dose": "3-5 mL/kg IV slow",
                "notes_ja": "猫は少量で循環過負荷リスク。2-5 mL/kg/hrで投与",
                "notes": "Cats: volume overload risk. Administer at 2-5 mL/kg/hr",
            },
        },
        "side_effects": "Discolored mucous membranes/urine/serum (interferes with lab), volume overload, vasoconstriction",
        "side_effects_ja": "粘膜/尿/血清の変色（検査値への干渉）、循環過負荷、血管収縮",
        "contraindications": "Volume overload, cardiac failure",
        "contraindications_ja": "循環過負荷、心不全",
        "drug_interactions": [],
    },
    {
        "id": "tranexamic_acid_iv",
        "name": "Tranexamic Acid (IV)",
        "name_ja": "トラネキサム酸（静注）",
        "category": "miscellaneous",
        "mechanism": "Antifibrinolytic; competitively inhibits plasminogen activation at lysine-binding sites",
        "mechanism_ja": "抗線溶薬。リジン結合部位でプラスミノーゲン活性化を競合的に阻害",
        "species_info": {
            "dog": {
                "dose": "10-25 mg/kg IV slow q8h; CRI 10 mg/kg/hr",
                "notes_ja": "DIC・重度出血・術中出血管理。RECOVER CPRガイドライン参照",
                "notes": "DIC, severe hemorrhage, surgical hemorrhage control. See RECOVER CPR guidelines",
            },
            "cat": {
                "dose": "10-20 mg/kg IV slow q8h",
                "notes_ja": "重度出血管理",
                "notes": "Severe hemorrhage management",
            },
            "horse": {
                "dose": "10-25 mg/kg IV slow",
                "notes_ja": "EIPH・術中出血",
                "notes": "EIPH, surgical hemorrhage",
            },
        },
        "side_effects": "Nausea, diarrhea, seizures (high dose), thrombosis risk",
        "side_effects_ja": "悪心、下痢、痙攣（高用量）、血栓リスク",
        "contraindications": "Active thromboembolic disease, DIC (relative), subarachnoid hemorrhage",
        "contraindications_ja": "活動性血栓塞栓症、DIC（相対的）、くも膜下出血",
        "drug_interactions": [],
    },
    {
        "id": "vitamin_a_injectable",
        "name": "Vitamin A Injectable",
        "name_ja": "ビタミンA注射",
        "category": "miscellaneous",
        "mechanism": "Fat-soluble vitamin essential for epithelial integrity, immune function, and vision",
        "mechanism_ja": "上皮完全性・免疫機能・視覚に必須の脂溶性ビタミン",
        "species_info": {
            "reptile": {
                "dose": "1,000-5,000 IU/kg IM 1回; 2週後繰返し",
                "notes_ja": "爬虫類のビタミンA欠乏症（低ビタミンA症）。カメ・リクガメで多い。過剰投与に注意",
                "notes": "Reptilian hypovitaminosis A. Common in chelonians. CAUTION: hypervitaminosis A risk",
            },
            "tortoise": {
                "dose": "1,000-2,000 IU/kg IM; 14日後繰返し",
                "notes_ja": "リクガメの目・鼻の腫れ（低ビタミンA）",
                "notes": "Tortoise aural abscess, eye/nasal swelling (hypovitaminosis A)",
            },
            "bird": {
                "dose": "10,000-25,000 IU/kg IM 1回; 必要に応じて繰返し",
                "notes_ja": "鳥類の低ビタミンA症（膿瘍・呼吸器）",
                "notes": "Avian hypovitaminosis A (abscesses, respiratory)",
            },
        },
        "side_effects": "Hypervitaminosis A (overdose: skin peeling, hepatotoxicity)",
        "side_effects_ja": "ビタミンA過剰症（過量投与時：皮膚剥離、肝毒性）",
        "contraindications": "Hypervitaminosis A",
        "contraindications_ja": "ビタミンA過剰症",
        "drug_interactions": [],
    },
    {
        "id": "calcium_glubionate",
        "name": "Calcium Glubionate Syrup",
        "name_ja": "グルビオン酸カルシウムシロップ",
        "category": "miscellaneous",
        "mechanism": "Oral calcium supplement; provides ionized calcium for bone mineralization and nerve function",
        "mechanism_ja": "経口カルシウム補給剤。骨石灰化と神経機能のためのイオン化カルシウムを提供",
        "species_info": {
            "dog": {
                "dose": "1-5 mL/kg PO q8h",
                "notes_ja": "低カルシウム血症・産後子癇（IV補正後の維持）・上皮小体機能低下症",
                "notes": "Hypocalcemia, eclampsia (maintenance after IV correction), hypoparathyroidism",
            },
            "cat": {
                "dose": "1-3 mL/cat PO q8h",
                "notes_ja": "上皮小体機能低下症（術後）・低Ca",
                "notes": "Hypoparathyroidism (post-surgical), hypocalcemia",
            },
            "bird": {
                "dose": "1 mL/kg PO q12h",
                "notes_ja": "卵塞・MBD",
                "notes": "Egg binding, metabolic bone disease",
            },
            "reptile": {
                "dose": "1 mL/kg PO q12-24h",
                "notes_ja": "MBD補助療法（UVBライト・食事改善と併用）",
                "notes": "MBD adjunct (with UVB lighting and diet correction)",
            },
            "guinea_pig": {"dose": "1-2 mL/kg PO q12h", "notes_ja": "妊娠毒血症", "notes": "Pregnancy toxemia"},
            "sugar_glider": {"dose": "1 mL/kg PO q12h", "notes_ja": "低Ca・MBD", "notes": "Hypocalcemia, MBD"},
        },
        "side_effects": "GI upset, hypercalcemia (overdose)",
        "side_effects_ja": "消化器症状、高カルシウム血症（過量）",
        "contraindications": "Hypercalcemia",
        "contraindications_ja": "高カルシウム血症",
        "drug_interactions": [],
    },
    {
        "id": "ferrous_sulfate_oral",
        "name": "Ferrous Sulfate (Oral Iron)",
        "name_ja": "硫酸第一鉄（経口鉄剤）",
        "category": "miscellaneous",
        "mechanism": "Provides elemental iron for hemoglobin synthesis",
        "mechanism_ja": "ヘモグロビン合成のための元素鉄を供給",
        "species_info": {
            "dog": {
                "dose": "5-10 mg/kg（元素鉄として）PO q24h",
                "notes_ja": "鉄欠乏性貧血（慢性出血・鉤虫）。食事と一緒に投与でGI刺激軽減",
                "notes": "Iron deficiency anemia (chronic hemorrhage, hookworm). Give with food",
            },
            "cat": {
                "dose": "50-100 mg/cat PO q24h",
                "notes_ja": "猫の鉄欠乏性貧血",
                "notes": "Feline iron deficiency anemia",
            },
            "bird": {
                "dose": "5-10 mg/kg PO q24h",
                "notes_ja": "鳥類の鉄欠乏性貧血",
                "notes": "Avian iron deficiency anemia",
            },
        },
        "side_effects": "GI upset, black feces, constipation, iron toxicity (overdose)",
        "side_effects_ja": "消化器症状、黒色便、便秘、鉄中毒（過量）",
        "contraindications": "Hemochromatosis, non-iron-deficiency anemia, hemosiderosis",
        "contraindications_ja": "ヘモクロマトーシス、鉄欠乏以外の貧血、ヘモジデローシス",
        "drug_interactions": [
            {
                "drug": "tetracyclines",
                "severity": "moderate",
                "description_ja": "テトラサイクリン吸収低下（2時間空ける）",
                "description": "Decreased tetracycline absorption (separate by 2h)",
            },
            {
                "drug": "antacids",
                "severity": "moderate",
                "description_ja": "鉄吸収低下",
                "description": "Decreased iron absorption",
            },
        ],
    },
    {
        "id": "oxytocin_injectable",
        "name": "Oxytocin Injectable",
        "name_ja": "オキシトシン注射",
        "category": "reproductive",
        "mechanism": "Stimulates uterine smooth muscle contraction and mammary gland milk ejection",
        "mechanism_ja": "子宮平滑筋収縮と乳腺の射乳を促進",
        "species_info": {
            "dog": {
                "dose": "1-5 U/dog IM/IV; 難産: 0.25-0.5 U/kg IM（最大20 U）",
                "notes_ja": "難産（子宮無力時のみ）・産後子宮収縮・胎盤遺残。頸管開大を確認後に使用",
                "notes": "Dystocia (uterine inertia only), postpartum involution, retained placenta. Confirm cervical dilation first",
            },
            "cat": {
                "dose": "0.5-3 U/cat IM; 15-30分間隔で繰返し可",
                "notes_ja": "猫の難産。低用量から開始",
                "notes": "Feline dystocia. Start low",
            },
            "horse": {
                "dose": "5-20 U IV/IM",
                "notes_ja": "胎盤遺残・産後子宮収縮・乳汁分泌促進",
                "notes": "Retained placenta, postpartum involution, milk letdown",
            },
            "rabbit": {"dose": "0.5-3 U/rabbit IM", "notes_ja": "ウサギの難産", "notes": "Rabbit dystocia"},
            "bird": {"dose": "5 U/kg IM", "notes_ja": "卵塞", "notes": "Egg binding"},
            "guinea_pig": {
                "dose": "0.2-3 U/guinea pig IM",
                "notes_ja": "モルモットの難産",
                "notes": "Guinea pig dystocia",
            },
        },
        "side_effects": "Uterine rupture (if obstruction), fetal death (excessive uterine contraction), water intoxication",
        "side_effects_ja": "子宮破裂（閉塞時）、胎児死亡（過度子宮収縮）、水中毒",
        "contraindications": "Mechanical obstruction, malpresentation, closed cervix, fetal oversize",
        "contraindications_ja": "機械的閉塞、胎位異常、頸管未開大、胎児過大",
        "drug_interactions": [],
    },
    {
        "id": "desoxycorticosterone",
        "name": "Desoxycorticosterone Pivalate (DOCP/Percorten-V)",
        "name_ja": "デオキシコルチコステロンピバレート（DOCP/パーコーテンV）",
        "category": "endocrine",
        "mechanism": "Mineralocorticoid replacement; promotes sodium retention and potassium excretion at renal tubule",
        "mechanism_ja": "ミネラルコルチコイド補充。腎尿細管でナトリウム再吸収促進、カリウム排泄促進",
        "species_info": {
            "dog": {
                "dose": "2.2 mg/kg IM/SC q25日（初期）→電解質で間隔調整",
                "notes_ja": "犬のアジソン病（原発性副腎皮質機能低下症）のミネラルコルチコイド補充。プレドニゾロン経口と併用",
                "notes": "Canine Addison's mineralocorticoid replacement. Combine with oral prednisolone",
            }
        },
        "side_effects": "PU/PD (overdose), hypokalemia, injection site reaction",
        "side_effects_ja": "多飲多尿（過量）、低カリウム血症、注射部位反応",
        "contraindications": "None absolute for Addison's replacement",
        "contraindications_ja": "アジソン病補充では絶対的禁忌なし",
        "drug_interactions": [],
    },
    {
        "id": "fludrocortisone",
        "name": "Fludrocortisone Acetate",
        "name_ja": "フルドロコルチゾン酢酸エステル",
        "category": "endocrine",
        "mechanism": "Synthetic mineralocorticoid with some glucocorticoid activity; sodium retention, potassium excretion",
        "mechanism_ja": "合成ミネラルコルチコイド（一部糖質コルチコイド活性あり）。Na再吸収・K排泄",
        "species_info": {
            "dog": {
                "dose": "0.01-0.02 mg/kg PO q12h; 電解質で調整",
                "notes_ja": "アジソン病（DOCPの経口代替）。用量漸増が多い。プレドニゾロン併用不要の場合あり",
                "notes": "Addison's disease (oral DOCP alternative). Often requires dose escalation. May not need concurrent pred",
            },
            "cat": {
                "dose": "0.05-0.1 mg/cat PO q12-24h",
                "notes_ja": "猫のアジソン病（稀）",
                "notes": "Feline Addison's (rare)",
            },
        },
        "side_effects": "PU/PD, weight gain, hypokalemia, hepatomegaly",
        "side_effects_ja": "多飲多尿、体重増加、低カリウム血症、肝腫大",
        "contraindications": "Congestive heart failure, edema",
        "contraindications_ja": "うっ血性心不全、浮腫",
        "drug_interactions": [],
    },
    {
        "id": "critical_care_herbivore",
        "name": "Critical Care (Oxbow)",
        "name_ja": "クリティカルケア（オックスボウ）",
        "category": "gastrointestinal",
        "mechanism": "High-fiber recovery food; timothy hay-based nutritional support for herbivorous species",
        "mechanism_ja": "高繊維回復食。チモシー牧草ベースの草食動物用栄養サポート",
        "species_info": {
            "rabbit": {
                "dose": "10-15 mL/kg PO q4-6h（シリンジ給餌）",
                "notes_ja": "GI stasis・食欲不振時の強制給餌。水で適切な濃度に希釈",
                "notes": "GI stasis, anorexia. Syringe feeding. Dilute with water to appropriate consistency",
            },
            "guinea_pig": {
                "dose": "10-15 mL/kg PO q4-6h",
                "notes_ja": "食欲不振・術後回復。ビタミンC配合版あり",
                "notes": "Anorexia, post-op recovery. Vitamin C-fortified version available",
            },
            "chinchilla": {
                "dose": "10-15 mL/kg PO q4-6h",
                "notes_ja": "GI stasis・食欲不振",
                "notes": "GI stasis, anorexia",
            },
            "hamster": {
                "dose": "少量ずつシリンジ給餌",
                "notes_ja": "食欲不振時の栄養サポート",
                "notes": "Nutritional support for anorexia",
            },
            "degu": {
                "dose": "少量ずつシリンジ給餌",
                "notes_ja": "食欲不振時の栄養サポート",
                "notes": "Nutritional support for anorexia",
            },
            "tortoise": {
                "dose": "10-15 mL/kg PO q6-8h（草食爬虫類版）",
                "notes_ja": "食欲不振のリクガメ",
                "notes": "Anorexic tortoises",
            },
        },
        "side_effects": "None significant; aspiration risk with improper technique",
        "side_effects_ja": "特になし。不適切な手技で誤嚥リスク",
        "contraindications": "Complete GI obstruction, species intolerant to high fiber",
        "contraindications_ja": "完全消化管閉塞、高繊維不耐種",
        "drug_interactions": [],
    },
    {
        "id": "carnivore_care",
        "name": "Carnivore Care (Oxbow)",
        "name_ja": "カーニボアケア（オックスボウ）",
        "category": "gastrointestinal",
        "mechanism": "High-protein recovery food for carnivorous/insectivorous exotic species",
        "mechanism_ja": "肉食/昆虫食エキゾチック動物用の高タンパク回復食",
        "species_info": {
            "ferret": {
                "dose": "10-15 mL/kg PO q4-6h",
                "notes_ja": "食欲不振・インスリノーマ・術後回復",
                "notes": "Anorexia, insulinoma, post-op recovery",
            },
            "hedgehog": {
                "dose": "5-10 mL/kg PO q4-6h",
                "notes_ja": "食欲不振・術後回復",
                "notes": "Anorexia, post-op recovery",
            },
            "sugar_glider": {
                "dose": "少量ずつシリンジ給餌",
                "notes_ja": "食欲不振時の栄養サポート",
                "notes": "Nutritional support for anorexia",
            },
        },
        "side_effects": "None significant",
        "side_effects_ja": "特になし",
        "contraindications": "Herbivorous species",
        "contraindications_ja": "草食動物種",
        "drug_interactions": [],
    },
    {
        "id": "emeraid_ic",
        "name": "Emeraid Intensive Care (Exotic Nutrition)",
        "name_ja": "エメレイド集中ケア",
        "category": "gastrointestinal",
        "mechanism": "Species-specific critical care nutrition: Omnivore, Herbivore, Carnivore, Piscivore formulations",
        "mechanism_ja": "種別の集中栄養ケア：雑食/草食/肉食/魚食用フォーミュレーション",
        "species_info": {
            "bird": {
                "dose": "5%体重/日を4-6回に分割; クロップチューブまたはシリンジ",
                "notes_ja": "鳥類の食欲不振・衰弱時の栄養サポート。Omnivore版使用",
                "notes": "Avian anorexia, debilitation. Use Omnivore formulation",
            },
            "reptile": {
                "dose": "2-3%体重/日を2-3回に分割",
                "notes_ja": "爬虫類の食欲不振。Carnivore版（肉食）またはHerbivore版（草食）を種に応じて",
                "notes": "Reptile anorexia. Use Carnivore or Herbivore per species",
            },
        },
        "side_effects": "Aspiration risk (improper technique), regurgitation",
        "side_effects_ja": "誤嚥リスク（不適切な手技）、吐き戻し",
        "contraindications": "Complete GI obstruction",
        "contraindications_ja": "完全消化管閉塞",
        "drug_interactions": [],
    },
]
