"""Drug batch 11 – CNS, behavioral, anesthetic & analgesic drugs.

References:
  - Plumb's Veterinary Drug Handbook, 10th ed.
  - Overall KL, Clinical Behavioral Medicine for Small Animals, 1997.
  - Lumb & Jones Veterinary Anesthesia and Analgesia, 5th ed.
"""

from __future__ import annotations

DRUGS_BATCH_11: list[dict] = [
    {
        "id": "fluoxetine",
        "name": "Fluoxetine (Reconcile)",
        "name_ja": "フルオキセチン（レコンサイル）",
        "category": "behavioral",
        "mechanism": "Selective serotonin reuptake inhibitor (SSRI). Increases synaptic serotonin by blocking presynaptic reuptake. Onset of clinical effect 4-6 weeks. FDA-approved for canine separation anxiety (Reconcile®).",
        "mechanism_ja": "選択的セロトニン再取り込み阻害薬（SSRI）。シナプス前再取り込み阻害によりセロトニンを増加。臨床効果発現に4-6週間。犬の分離不安にFDA承認済み（レコンサイル®）。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "1-2 mg/kg PO q24h",
                "dosage_ja": "1-2 mg/kg 経口 24時間毎",
                "notes": "Separation anxiety, compulsive disorders, aggression, noise phobia. Combine with behavior modification",
                "notes_ja": "分離不安・強迫性障害・攻撃性・騒音恐怖症。行動修正療法と併用",
            },
            "cat": {
                "safe": True,
                "dosage": "0.5-1 mg/kg PO q24h",
                "dosage_ja": "0.5-1 mg/kg 経口 24時間毎",
                "notes": "Urine marking, inter-cat aggression, psychogenic alopecia, FIC. Start low",
                "notes_ja": "尿マーキング・猫間攻撃性・心因性脱毛・FIC。低用量から開始",
            },
            "bird": {
                "safe": True,
                "dosage": "0.5-2 mg/kg PO q24h",
                "dosage_ja": "0.5-2 mg/kg 経口 24時間毎",
                "notes": "Feather-destructive behavior, stereotypies",
                "notes_ja": "羽毛破壊行動・常同行動",
            },
            "rabbit": {
                "safe": True,
                "dosage": "0.5-1 mg/kg PO q24h",
                "dosage_ja": "0.5-1 mg/kg 経口 24時間毎",
                "notes": "Barbering, self-mutilation; limited data",
                "notes_ja": "毛引き・自傷行為。データ限定的",
            },
            "ferret": {
                "safe": True,
                "dosage": "0.5-1 mg/kg PO q24h",
                "dosage_ja": "0.5-1 mg/kg 経口 24時間毎",
                "notes": "Compulsive behaviors; limited data",
                "notes_ja": "強迫性行動。データ限定的",
            },
            "horse": {
                "safe": True,
                "dosage": "0.25-0.5 mg/kg PO q24h",
                "dosage_ja": "0.25-0.5 mg/kg 経口 24時間毎",
                "notes": "Cribbing, stereotypies; limited evidence",
                "notes_ja": "さく癖・常同行動。エビデンス限定的",
            },
        },
        "side_effects": ["decreased appetite", "lethargy", "GI upset", "restlessness", "urinary retention (rare)"],
        "side_effects_ja": ["食欲減退", "嗜眠", "消化器症状", "不穏", "尿閉（稀）"],
        "contraindications": "Concurrent MAOI use (2-week washout). Seizure disorders (lowers threshold). Hepatic impairment.",
        "contraindications_ja": "MAO阻害薬との併用（2週間の休薬期間が必要）。てんかん（閾値低下）。肝機能障害。",
        "drug_interactions": [
            {
                "drug": "selegiline",
                "effect": "Serotonin syndrome risk (MAO-B + SSRI); 2-week washout required",
                "effect_ja": "セロトニン症候群のリスク（MAO-B＋SSRI）。2週間の休薬期間必要",
            },
            {
                "drug": "tramadol",
                "effect": "Increased serotonin syndrome risk",
                "effect_ja": "セロトニン症候群リスク増加",
            },
            {
                "drug": "trazodone",
                "effect": "Additive serotonergic effects; use caution but commonly combined clinically",
                "effect_ja": "セロトニン作用の相加。注意が必要だが臨床的にはしばしば併用される",
            },
            {
                "drug": "linezolid",
                "effect": "Serotonin syndrome (linezolid has MAO-I activity)",
                "effect_ja": "セロトニン症候群（リネゾリドにMAO阻害活性あり）",
            },
        ],
    },
    {
        "id": "clomipramine",
        "name": "Clomipramine (Clomicalm)",
        "name_ja": "クロミプラミン（クロミカルム）",
        "category": "behavioral",
        "mechanism": "Tricyclic antidepressant (TCA) with predominant serotonin reuptake inhibition. Also blocks norepinephrine reuptake and has anticholinergic, antihistaminic, and alpha-adrenolytic properties.",
        "mechanism_ja": "セロトニン再取り込み阻害が優位な三環系抗うつ薬（TCA）。ノルエピネフリン再取り込みも阻害。抗コリン・抗ヒスタミン・α遮断作用も有する。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "1-3 mg/kg PO q12h (start at 1 mg/kg)",
                "dosage_ja": "1-3 mg/kg 経口 12時間毎（1 mg/kgから開始）",
                "notes": "FDA/EMA-approved for canine separation anxiety (Clomicalm®). Also compulsive disorders, dominance aggression",
                "notes_ja": "犬の分離不安にFDA/EMA承認済み（クロミカルム®）。強迫性障害・優位性攻撃にも",
            },
            "cat": {
                "safe": True,
                "dosage": "0.25-0.5 mg/kg PO q24h",
                "dosage_ja": "0.25-0.5 mg/kg 経口 24時間毎",
                "notes": "Urine spraying, anxiety, psychogenic alopecia",
                "notes_ja": "尿スプレー行動・不安・心因性脱毛",
            },
            "bird": {
                "safe": True,
                "dosage": "0.5-1 mg/kg PO q12-24h",
                "dosage_ja": "0.5-1 mg/kg 経口 12-24時間毎",
                "notes": "Feather destructive behavior; limited data",
                "notes_ja": "羽毛破壊行動。データ限定的",
            },
        },
        "side_effects": ["sedation", "dry mouth", "constipation", "urinary retention", "tachycardia", "weight gain"],
        "side_effects_ja": ["鎮静", "口渇", "便秘", "尿閉", "頻脈", "体重増加"],
        "contraindications": "MAOI use (14-day washout). Cardiac arrhythmias. Urinary retention. Glaucoma. Seizure history.",
        "contraindications_ja": "MAO阻害薬使用（14日間の休薬）。心不整脈。尿閉。緑内障。痙攣の既往。",
        "drug_interactions": [
            {
                "drug": "selegiline",
                "effect": "Serotonin syndrome; contraindicated",
                "effect_ja": "セロトニン症候群。併用禁忌",
            },
            {
                "drug": "cimetidine",
                "effect": "Inhibits TCA metabolism increasing toxicity risk",
                "effect_ja": "TCA代謝を阻害し毒性リスクを増加",
            },
            {
                "drug": "phenobarbital",
                "effect": "Increases TCA metabolism reducing efficacy",
                "effect_ja": "TCA代謝を促進し効果を低下",
            },
        ],
    },
    {
        "id": "amitriptyline",
        "name": "Amitriptyline",
        "name_ja": "アミトリプチリン",
        "category": "behavioral",
        "mechanism": "Tricyclic antidepressant. Inhibits serotonin and norepinephrine reuptake. Strong anticholinergic, antihistaminic, and sedative properties. Also useful for neuropathic pain and FIC.",
        "mechanism_ja": "三環系抗うつ薬。セロトニン・ノルエピネフリン再取り込み阻害。強い抗コリン・抗ヒスタミン・鎮静作用。神経障害性疼痛・FICにも有用。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "1-2 mg/kg PO q12h",
                "dosage_ja": "1-2 mg/kg 経口 12時間毎",
                "notes": "Separation anxiety, neuropathic pain, pruritus. More sedating than clomipramine",
                "notes_ja": "分離不安・神経障害性疼痛・掻痒。クロミプラミンより鎮静作用が強い",
            },
            "cat": {
                "safe": True,
                "dosage": "0.5-2 mg/kg PO q12-24h (2.5-12.5 mg/cat)",
                "dosage_ja": "0.5-2 mg/kg 経口 12-24時間毎（2.5-12.5 mg/頭）",
                "notes": "Feline idiopathic cystitis (FIC), psychogenic alopecia, anxiety. Most commonly prescribed TCA in cats",
                "notes_ja": "猫特発性膀胱炎（FIC）・心因性脱毛・不安。猫で最も処方されるTCA",
            },
            "bird": {
                "safe": True,
                "dosage": "1-2 mg/kg PO q12-24h",
                "dosage_ja": "1-2 mg/kg 経口 12-24時間毎",
                "notes": "Feather plucking; limited data",
                "notes_ja": "毛引き。データ限定的",
            },
        },
        "side_effects": [
            "sedation",
            "weight gain",
            "dry mouth",
            "constipation",
            "urinary retention",
            "cardiac arrhythmias",
        ],
        "side_effects_ja": ["鎮静", "体重増加", "口渇", "便秘", "尿閉", "心不整脈"],
        "contraindications": "MAOI use. Cardiac disease. Glaucoma. Urinary retention. Hepatic disease.",
        "contraindications_ja": "MAO阻害薬使用。心疾患。緑内障。尿閉。肝疾患。",
        "drug_interactions": [
            {
                "drug": "fluoxetine",
                "effect": "Increased TCA levels via CYP inhibition; serotonin syndrome risk",
                "effect_ja": "CYP阻害によりTCA濃度上昇。セロトニン症候群リスク",
            },
            {
                "drug": "acepromazine",
                "effect": "Additive hypotension and sedation",
                "effect_ja": "低血圧・鎮静の相加作用",
            },
            {
                "drug": "tramadol",
                "effect": "Serotonin syndrome risk; additive CNS depression",
                "effect_ja": "セロトニン症候群リスク。CNS抑制の相加",
            },
        ],
    },
    {
        "id": "buspirone",
        "name": "Buspirone",
        "name_ja": "ブスピロン",
        "category": "behavioral",
        "mechanism": "5-HT1A partial agonist. Anxiolytic without sedation, muscle relaxation, or anticonvulsant effects. No abuse potential. 2-4 week onset. Unique mechanism distinct from benzodiazepines.",
        "mechanism_ja": "5-HT1A部分作動薬。鎮静・筋弛緩・抗痙攣作用なしの抗不安薬。乱用の可能性なし。効果発現に2-4週間。ベンゾジアゼピンとは異なる独自の作用機序。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.5-2 mg/kg PO q8-12h",
                "dosage_ja": "0.5-2 mg/kg 経口 8-12時間毎",
                "notes": "Generalized anxiety, fear-based aggression. Less effective than SSRIs for most canine anxiety",
                "notes_ja": "全般性不安・恐怖性攻撃。犬の不安にはSSRIより効果が低いことが多い",
            },
            "cat": {
                "safe": True,
                "dosage": "0.5-1 mg/kg PO q12h (2.5-5 mg/cat)",
                "dosage_ja": "0.5-1 mg/kg 経口 12時間毎（2.5-5 mg/頭）",
                "notes": "Urine marking (especially multi-cat households), inter-cat aggression. More effective in cats than dogs",
                "notes_ja": "尿マーキング（特に多頭飼育）・猫間攻撃性。犬より猫で効果的",
            },
        },
        "side_effects": ["increased affection/friendliness (cats)", "GI upset", "restlessness", "tachycardia"],
        "side_effects_ja": ["社交性増加（猫）", "消化器症状", "不穏", "頻脈"],
        "contraindications": "MAOI use. Hepatic impairment. Seizure disorders.",
        "contraindications_ja": "MAO阻害薬使用。肝機能障害。痙攣性疾患。",
        "drug_interactions": [
            {
                "drug": "fluoxetine",
                "effect": "Increased serotonergic effects; use with caution",
                "effect_ja": "セロトニン作用増強。慎重に使用",
            },
            {
                "drug": "erythromycin",
                "effect": "CYP3A4 inhibition increases buspirone levels",
                "effect_ja": "CYP3A4阻害によりブスピロン濃度上昇",
            },
            {
                "drug": "diazepam",
                "effect": "May be less effective if patient has benzodiazepine tolerance",
                "effect_ja": "ベンゾジアゼピン耐性がある場合効果が低下する可能性",
            },
        ],
    },
    {
        "id": "alprazolam",
        "name": "Alprazolam",
        "name_ja": "アルプラゾラム",
        "category": "behavioral",
        "mechanism": "Triazolobenzodiazepine. Enhances GABA-A receptor activity. Rapid-onset anxiolytic with relatively short duration. Specifically useful for panic and event-based anxiety (storms, fireworks).",
        "mechanism_ja": "トリアゾロベンゾジアゼピン。GABA-A受容体活性を増強。速効性の抗不安薬で比較的短時間作用。パニック・イベント性不安（雷・花火）に特に有用。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.02-0.1 mg/kg PO q4-8h PRN; Storm/noise: 0.02-0.05 mg/kg PO 30-60 min prior",
                "dosage_ja": "0.02-0.1 mg/kg 経口 4-8時間毎 頓用；雷/騒音: 0.02-0.05 mg/kg 30-60分前",
                "notes": "Noise phobia, thunderstorm anxiety, panic. Can worsen fear aggression (disinhibition)",
                "notes_ja": "騒音恐怖症・雷不安・パニック。恐怖性攻撃を悪化させる可能性（脱抑制）",
            },
            "cat": {
                "safe": True,
                "dosage": "0.0125-0.025 mg/kg PO q12h",
                "dosage_ja": "0.0125-0.025 mg/kg 経口 12時間毎",
                "notes": "Anxiety, urine spraying. Paradoxical excitement possible",
                "notes_ja": "不安・尿スプレー行動。逆説的興奮の可能性あり",
            },
        },
        "side_effects": [
            "sedation",
            "ataxia",
            "paradoxical excitement",
            "increased appetite",
            "hepatotoxicity (cats, rare)",
        ],
        "side_effects_ja": ["鎮静", "運動失調", "逆説的興奮", "食欲増進", "肝毒性（猫、稀）"],
        "contraindications": "Liver disease (especially cats—idiosyncratic hepatic necrosis). Aggressive animals (disinhibition). Do not stop abruptly (withdrawal seizures).",
        "contraindications_ja": "肝疾患（特に猫—特異体質性肝壊死）。攻撃的動物（脱抑制）。急な中止不可（離脱性痙攣）。",
        "drug_interactions": [
            {
                "drug": "ketoconazole",
                "effect": "CYP3A4 inhibition markedly increases alprazolam levels and duration",
                "effect_ja": "CYP3A4阻害によりアルプラゾラムの濃度と作用時間が著しく増加",
            },
            {
                "drug": "phenobarbital",
                "effect": "Decreased alprazolam efficacy via enzyme induction",
                "effect_ja": "酵素誘導によりアルプラゾラムの効果低下",
            },
        ],
    },
    {
        "id": "imepitoin",
        "name": "Imepitoin (Pexion)",
        "name_ja": "イメピトイン（ペキシオン）",
        "category": "neurological",
        "mechanism": "Low-affinity partial GABA-A receptor agonist. Anticonvulsant with anxiolytic properties. EMA-approved for canine idiopathic epilepsy and noise-associated anxiety (Pexion®).",
        "mechanism_ja": "低親和性GABA-A受容体部分作動薬。抗痙攣・抗不安作用。犬の特発性てんかんおよび騒音関連不安にEMA承認済み（ペキシオン®）。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "Epilepsy: 10-30 mg/kg PO q12h; Noise anxiety: 20 mg/kg PO q12h (start 2 days before event)",
                "dosage_ja": "てんかん: 10-30 mg/kg 経口 12時間毎；騒音不安: 20 mg/kg 経口 12時間毎（イベント2日前から開始）",
                "notes": "First-line option for newly diagnosed canine epilepsy in EU. Fewer side effects than phenobarbital",
                "notes_ja": "EUでは新規診断の犬てんかんの第一選択。フェノバルビタールより副作用が少ない",
            },
        },
        "side_effects": ["polyphagia", "hyperactivity", "ataxia", "sedation", "polyuria/polydipsia"],
        "side_effects_ja": ["多食", "過活動", "運動失調", "鎮静", "多飲多尿"],
        "contraindications": "Severe hepatic/renal impairment. Not validated for cats. Not for status epilepticus.",
        "contraindications_ja": "重度肝・腎機能障害。猫での有効性未検証。てんかん重積状態には不適。",
        "drug_interactions": [
            {
                "drug": "phenobarbital",
                "effect": "Combined use may increase seizure threshold additively; transition gradually",
                "effect_ja": "併用で痙攣閾値が相加的に上昇する可能性。段階的に移行",
            },
            {
                "drug": "diazepam",
                "effect": "Additive GABAergic effects; may increase sedation",
                "effect_ja": "GABA作用の相加。鎮静が増強される可能性",
            },
        ],
    },
    {
        "id": "pregabalin",
        "name": "Pregabalin",
        "name_ja": "プレガバリン",
        "category": "analgesics",
        "mechanism": "Gabapentinoid. Binds alpha-2-delta subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release. Analgesic for neuropathic pain, anticonvulsant, and anxiolytic.",
        "mechanism_ja": "ガバペンチノイド。電位依存性カルシウムチャネルのα2δサブユニットに結合し興奮性神経伝達物質の放出を抑制。神経障害性疼痛・抗痙攣・抗不安に有効。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "2-4 mg/kg PO q8-12h",
                "dosage_ja": "2-4 mg/kg 経口 8-12時間毎",
                "notes": "Neuropathic pain, refractory epilepsy adjunct, anxiety. More potent and predictable PK than gabapentin",
                "notes_ja": "神経障害性疼痛・難治性てんかん補助・不安。ガバペンチンより強力でPKが予測しやすい",
            },
            "cat": {
                "safe": True,
                "dosage": "1-2 mg/kg PO q12h",
                "dosage_ja": "1-2 mg/kg 経口 12時間毎",
                "notes": "Neuropathic pain (DM, FIP neurological). Pre-visit anxiety: 2 mg/kg PO 90 min prior",
                "notes_ja": "神経障害性疼痛（DM・FIP神経型）。来院前不安: 2 mg/kg 90分前",
            },
        },
        "side_effects": ["sedation", "ataxia", "weight gain", "peripheral edema"],
        "side_effects_ja": ["鎮静", "運動失調", "体重増加", "末梢浮腫"],
        "contraindications": "Renal impairment (dose reduce; renally eliminated). Do not abruptly discontinue (taper over 1 week).",
        "contraindications_ja": "腎機能障害（減量；腎排泄）。突然の中止不可（1週間かけて漸減）。",
        "drug_interactions": [
            {
                "drug": "gabapentin",
                "effect": "Duplicate mechanism; choose one or the other, not both",
                "effect_ja": "作用機序重複。どちらか一方を選択し併用しない",
            },
            {
                "drug": "opioids",
                "effect": "Additive CNS depression; reduce opioid dose by 30-50%",
                "effect_ja": "CNS抑制の相加。オピオイド用量を30-50%減量",
            },
        ],
    },
    {
        "id": "amantadine",
        "name": "Amantadine",
        "name_ja": "アマンタジン",
        "category": "analgesics",
        "mechanism": "NMDA receptor antagonist. Prevents central sensitization (wind-up pain). Used as adjunctive analgesic for chronic/neuropathic pain refractory to NSAIDs and opioids.",
        "mechanism_ja": "NMDA受容体拮抗薬。中枢性感作（ワインドアップ痛）を防止。NSAIDs・オピオイドに抵抗性の慢性・神経障害性疼痛の補助鎮痛薬。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "3-5 mg/kg PO q24h",
                "dosage_ja": "3-5 mg/kg 経口 24時間毎",
                "notes": "OA pain adjunct (add to NSAID), neuropathic pain, cancer pain. KSU study: significant improvement in activity",
                "notes_ja": "OA疼痛補助（NSAIDに追加）・神経障害性疼痛・がん疼痛。KSU研究：活動性の有意な改善",
            },
            "cat": {
                "safe": True,
                "dosage": "3-5 mg/kg PO q24h",
                "dosage_ja": "3-5 mg/kg 経口 24時間毎",
                "notes": "Chronic pain adjunct. Liquid formulation may contain xylitol—check ingredients",
                "notes_ja": "慢性疼痛補助。液剤にキシリトール含有の可能性—成分確認",
            },
        },
        "side_effects": ["GI upset", "agitation", "diarrhea", "dry mouth"],
        "side_effects_ja": ["消化器症状", "興奮", "下痢", "口渇"],
        "contraindications": "Seizure disorders (may lower threshold). Renal impairment (renally excreted).",
        "contraindications_ja": "痙攣性疾患（閾値低下の可能性）。腎機能障害（腎排泄）。",
        "drug_interactions": [
            {
                "drug": "hydrochlorothiazide",
                "effect": "Reduced amantadine renal clearance",
                "effect_ja": "アマンタジンの腎クリアランス低下",
            },
            {
                "drug": "trimethoprim_sulfa",
                "effect": "Reduced amantadine clearance",
                "effect_ja": "アマンタジンのクリアランス低下",
            },
        ],
    },
    {
        "id": "bupivacaine",
        "name": "Bupivacaine",
        "name_ja": "ブピバカイン",
        "category": "anesthetics",
        "mechanism": "Long-acting amide local anesthetic. Blocks sodium channels preventing nerve impulse conduction. Duration 4-8 hours. Used for regional/epidural anesthesia and post-operative wound infiltration.",
        "mechanism_ja": "長時間作用型アミド型局所麻酔薬。ナトリウムチャネル遮断により神経インパルス伝導を阻害。作用時間4-8時間。区域/硬膜外麻酔・術後創傷浸潤に使用。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "Infiltration: 1-2 mg/kg; Epidural: 1 mg/kg (0.5% sol); Nerve block: 0.5-1 mg/kg per site",
                "dosage_ja": "浸潤: 1-2 mg/kg；硬膜外: 1 mg/kg（0.5%液）；神経ブロック: 0.5-1 mg/kg/部位",
                "notes": "Max total dose 2 mg/kg. Do NOT give IV (fatal cardiotoxicity). Liposomal form (Nocita®) lasts 72h",
                "notes_ja": "最大総用量2 mg/kg。静注禁止（致死的心毒性）。リポソーム製剤（ノシータ®）は72時間持続",
            },
            "cat": {
                "safe": True,
                "dosage": "Infiltration: 1-2 mg/kg; Epidural: 1 mg/kg",
                "dosage_ja": "浸潤: 1-2 mg/kg；硬膜外: 1 mg/kg",
                "notes": "Max 2 mg/kg total. Cats more sensitive to cardiotoxicity",
                "notes_ja": "最大総用量2 mg/kg。猫は心毒性に感受性が高い",
            },
            "horse": {
                "safe": True,
                "dosage": "Perineural: 10-20 mL of 0.5% per site; Epidural: 0.04-0.06 mg/kg",
                "dosage_ja": "神経周囲: 0.5%液 10-20 mL/部位；硬膜外: 0.04-0.06 mg/kg",
                "notes": "Peripheral nerve blocks for standing surgery; epidural for perineal procedures",
                "notes_ja": "立位手術用末梢神経ブロック。会陰部処置に硬膜外麻酔",
            },
            "rabbit": {
                "safe": True,
                "dosage": "1-2 mg/kg infiltration; Epidural: 0.75-1 mg/kg",
                "dosage_ja": "浸潤1-2 mg/kg；硬膜外: 0.75-1 mg/kg",
                "notes": "Wound infiltration, dental nerve blocks. EMLA (lidocaine+prilocaine) for venipuncture",
                "notes_ja": "創傷浸潤・歯科神経ブロック。採血にはEMLA（リドカイン＋プリロカイン）",
            },
            "bird": {
                "safe": True,
                "dosage": "1-2 mg/kg infiltration (dilute with saline)",
                "dosage_ja": "浸潤1-2 mg/kg（生食で希釈）",
                "notes": "Surgical site infiltration; dilute to reduce tissue volume",
                "notes_ja": "手術部位浸潤。組織容量を減らすため希釈",
            },
            "reptile": {
                "safe": True,
                "dosage": "1-2 mg/kg infiltration",
                "dosage_ja": "浸潤1-2 mg/kg",
                "notes": "Local anesthesia for minor procedures; slower onset in ectotherms",
                "notes_ja": "軽微な処置の局所麻酔。変温動物では効果発現が遅い",
            },
        },
        "side_effects": [
            "cardiotoxicity (IV injection)",
            "CNS toxicity",
            "tissue irritation",
            "methemoglobinemia (rare)",
        ],
        "side_effects_ja": ["心毒性（静注時）", "CNS毒性", "組織刺激", "メトヘモグロビン血症（稀）"],
        "contraindications": "IV injection (fatal). Total dose must not exceed 2 mg/kg in dogs/cats. Epinephrine-containing formulations: avoid in end-arteries (ears, tail, digits).",
        "contraindications_ja": "静注禁止（致死的）。犬・猫の総用量は2 mg/kgを超えないこと。エピネフリン含有製剤：末端動脈部位（耳・尾・指端）に使用回避。",
        "drug_interactions": [
            {
                "drug": "lidocaine",
                "effect": "Additive local anesthetic toxicity; total combined dose must not exceed safe limits",
                "effect_ja": "局所麻酔薬毒性の相加。合計用量が安全限度を超えないこと",
            },
            {
                "drug": "propranolol",
                "effect": "Decreased bupivacaine hepatic clearance; increased toxicity risk",
                "effect_ja": "ブピバカインの肝クリアランス低下。毒性リスク増加",
            },
        ],
    },
    {
        "id": "etomidate",
        "name": "Etomidate",
        "name_ja": "エトミデート",
        "category": "anesthetics",
        "mechanism": "Non-barbiturate IV induction agent. GABA-A receptor modulation. Minimal cardiovascular effects—ideal for patients with cardiac disease or hemodynamic instability.",
        "mechanism_ja": "非バルビツール酸系静脈麻酔導入薬。GABA-A受容体修飾。心血管系への影響が最小限—心疾患・血行動態不安定な患者に理想的。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "1-3 mg/kg IV (to effect); premedicate to reduce myoclonus",
                "dosage_ja": "1-3 mg/kg 静注（効果が得られるまで）。ミオクローヌス軽減のため前投薬",
                "notes": "Cardiac patients, cesarean section, Addisonian crisis. Single use only (adrenal suppression)",
                "notes_ja": "心疾患・帝王切開・アジソンクリーゼ。1回のみ使用（副腎抑制のため）",
            },
            "cat": {
                "safe": True,
                "dosage": "1-3 mg/kg IV",
                "dosage_ja": "1-3 mg/kg 静注",
                "notes": "Same indications; cats may show more myoclonus",
                "notes_ja": "同様の適応。猫ではミオクローヌスがより顕著な場合あり",
            },
            "horse": {
                "safe": True,
                "dosage": "0.5-1 mg/kg IV (foals); 1-2 mg/kg IV (adults, rarely used)",
                "dosage_ja": "子馬: 0.5-1 mg/kg 静注；成馬: 1-2 mg/kg（稀に使用）",
                "notes": "Neonatal foal resuscitation, cardiac compromised foals",
                "notes_ja": "新生子馬蘇生・心機能低下子馬",
            },
            "rabbit": {
                "safe": True,
                "dosage": "1-2 mg/kg IV",
                "dosage_ja": "1-2 mg/kg 静注",
                "notes": "Cardiac-compromised rabbits; always premedicate",
                "notes_ja": "心機能低下ウサギ。必ず前投薬を行う",
            },
            "ferret": {
                "safe": True,
                "dosage": "1-2 mg/kg IV",
                "dosage_ja": "1-2 mg/kg 静注",
                "notes": "Insulinoma patients at risk of propofol-induced hypotension",
                "notes_ja": "プロポフォール誘発性低血圧リスクのあるインスリノーマ患者",
            },
        },
        "side_effects": [
            "myoclonus",
            "adrenocortical suppression",
            "nausea/vomiting on recovery",
            "pain on injection",
            "hemolysis (propylene glycol vehicle)",
        ],
        "side_effects_ja": [
            "ミオクローヌス",
            "副腎皮質抑制",
            "覚醒時悪心/嘔吐",
            "注射時疼痛",
            "溶血（プロピレングリコール溶媒）",
        ],
        "contraindications": "Repeated dosing or CRI (adrenal suppression). Propylene glycol vehicle causes hemolysis with repeated use.",
        "contraindications_ja": "反復投与・CRI禁止（副腎抑制）。プロピレングリコール溶媒は反復使用で溶血を起こす。",
        "drug_interactions": [
            {
                "drug": "midazolam",
                "effect": "Commonly co-induced to reduce etomidate dose and myoclonus",
                "effect_ja": "エトミデートの用量削減とミオクローヌス軽減のため一般的に併用導入",
            },
            {
                "drug": "fentanyl",
                "effect": "Reduces etomidate induction dose requirements",
                "effect_ja": "エトミデートの導入量を減少",
            },
        ],
    },
    {
        "id": "tiletamine_zolazepam",
        "name": "Tiletamine/Zolazepam (Telazol/Zoletil)",
        "name_ja": "チレタミン・ゾラゼパム（テラゾール/ゾレチル）",
        "category": "anesthetics",
        "mechanism": "Fixed combination: tiletamine (dissociative NMDA antagonist) + zolazepam (benzodiazepine). Provides dissociative anesthesia with muscle relaxation. IM administration possible.",
        "mechanism_ja": "固定配合剤：チレタミン（解離性NMDA拮抗薬）＋ゾラゼパム（ベンゾジアゼピン）。筋弛緩を伴う解離性麻酔。筋注投与可能。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "6-12 mg/kg IM; 3-6 mg/kg IV",
                "dosage_ja": "6-12 mg/kg 筋注；3-6 mg/kg 静注",
                "notes": "Field immobilization, aggressive patients, minor procedures. Prolonged recovery in dogs (tiletamine outlasts zolazepam)",
                "notes_ja": "野外不動化・攻撃的患者・軽微処置。犬では覚醒遅延（チレタミンがゾラゼパムより長く持続）",
            },
            "cat": {
                "safe": True,
                "dosage": "4-12 mg/kg IM; 2-4 mg/kg IV",
                "dosage_ja": "4-12 mg/kg 筋注；2-4 mg/kg 静注",
                "notes": "Smooth recovery in cats (zolazepam outlasts tiletamine). Feral cat TNR",
                "notes_ja": "猫では滑らかな覚醒（ゾラゼパムがチレタミンより長く持続）。野良猫TNRに",
            },
            "ferret": {
                "safe": True,
                "dosage": "12-22 mg/kg IM",
                "dosage_ja": "12-22 mg/kg 筋注",
                "notes": "Quick immobilization for minor procedures",
                "notes_ja": "軽微処置の迅速な不動化",
            },
            "bird": {
                "safe": True,
                "dosage": "5-10 mg/kg IM",
                "dosage_ja": "5-10 mg/kg 筋注",
                "notes": "Immobilization; variable response in different species",
                "notes_ja": "不動化。鳥種により反応にばらつき",
            },
            "reptile": {
                "safe": True,
                "dosage": "5-10 mg/kg IM",
                "dosage_ja": "5-10 mg/kg 筋注",
                "notes": "Chemical restraint; prolonged recovery (hours to days in reptiles)",
                "notes_ja": "化学的保定。爬虫類では覚醒に数時間〜数日",
            },
        },
        "side_effects": [
            "prolonged recovery (dogs)",
            "hypersalivation",
            "muscle rigidity",
            "respiratory depression",
            "hypothermia",
        ],
        "side_effects_ja": ["覚醒遅延（犬）", "流涎", "筋硬直", "呼吸抑制", "低体温"],
        "contraindications": "Renal/hepatic disease (prolonged recovery). Not recommended for CSF collection (increases ICP). Pancreatic disease. Cardiac disease.",
        "contraindications_ja": "腎・肝疾患（覚醒遅延）。CSF採取には非推奨（頭蓋内圧上昇）。膵疾患。心疾患。",
        "drug_interactions": [
            {
                "drug": "chloramphenicol",
                "effect": "Prolongs tiletamine/zolazepam duration (hepatic metabolism inhibition)",
                "effect_ja": "肝代謝阻害によりチレタミン/ゾラゼパムの作用時間延長",
            },
            {
                "drug": "alpha2_agonists",
                "effect": "Commonly combined for field immobilization (additive sedation; lower Telazol dose)",
                "effect_ja": "野外不動化でよく併用（鎮静の相加。テラゾール用量低減）",
            },
        ],
    },
    {
        "id": "oxymorphone",
        "name": "Oxymorphone",
        "name_ja": "オキシモルフォン",
        "category": "analgesics",
        "mechanism": "Full mu-opioid receptor agonist. Potent analgesic approximately 10× more potent than morphine. Does not cause histamine release. Reliable sedation + analgesia.",
        "mechanism_ja": "完全μ-オピオイド受容体作動薬。モルヒネの約10倍の強力な鎮痛薬。ヒスタミン遊離を起こさない。信頼性の高い鎮静＋鎮痛。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.05-0.1 mg/kg IV/IM/SC q4-6h",
                "dosage_ja": "0.05-0.1 mg/kg 静注/筋注/皮下 4-6時間毎",
                "notes": "Premedication, post-operative pain, trauma. No histamine release (unlike morphine)",
                "notes_ja": "前投薬・術後疼痛・外傷。ヒスタミン遊離なし（モルヒネと異なる）",
            },
            "cat": {
                "safe": True,
                "dosage": "0.02-0.05 mg/kg IV/IM q4-6h",
                "dosage_ja": "0.02-0.05 mg/kg 静注/筋注 4-6時間毎",
                "notes": "Cats: lower doses; may cause euphoria/dysphoria",
                "notes_ja": "猫: 低用量。多幸感/不快感の可能性",
            },
            "ferret": {
                "safe": True,
                "dosage": "0.05-0.2 mg/kg IM/SC q6-8h",
                "dosage_ja": "0.05-0.2 mg/kg 筋注/皮下 6-8時間毎",
                "notes": "Post-surgical analgesia",
                "notes_ja": "術後鎮痛",
            },
        },
        "side_effects": [
            "respiratory depression",
            "bradycardia",
            "vomiting (initial dose)",
            "panting (dogs)",
            "constipation",
        ],
        "side_effects_ja": ["呼吸抑制", "徐脈", "嘔吐（初回投与）", "パンティング（犬）", "便秘"],
        "contraindications": "Respiratory compromise. Head trauma (increases ICP). Concurrent CNS depressants (additive). Controlled substance (DEA Schedule II).",
        "contraindications_ja": "呼吸障害。頭部外傷（頭蓋内圧上昇）。CNS抑制薬との併用（相加作用）。規制薬物。",
        "drug_interactions": [
            {
                "drug": "acepromazine",
                "effect": "Commonly combined (neuroleptanalgesia); additive sedation and hypotension",
                "effect_ja": "一般的に併用（神経遮断鎮痛）。鎮静・低血圧の相加作用",
            },
            {
                "drug": "naloxone",
                "effect": "Complete reversal agent for opioid overdose",
                "effect_ja": "オピオイド過量投与の完全拮抗薬",
            },
        ],
    },
    {
        "id": "remifentanil",
        "name": "Remifentanil",
        "name_ja": "レミフェンタニル",
        "category": "analgesics",
        "mechanism": "Ultra-short-acting synthetic mu-opioid agonist. Ester-metabolized by tissue esterases (not hepatic). CRI only. Provides titratable intraoperative analgesia with rapid offset.",
        "mechanism_ja": "超短時間作用型合成μ-オピオイド作動薬。組織エステラーゼで代謝（肝代謝ではない）。CRI専用。調節可能な術中鎮痛と迅速な効果消失。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "CRI: 5-40 μg/kg/hr (load: 1-2 μg/kg IV)",
                "dosage_ja": "CRI: 5-40 μg/kg/時（負荷: 1-2 μg/kg 静注）",
                "notes": "Intraoperative CRI only. MAC reduction 50-70%. Recovery in 5-10 min after stopping",
                "notes_ja": "術中CRI専用。MAC50-70%低下。停止後5-10分で覚醒",
            },
            "cat": {
                "safe": True,
                "dosage": "CRI: 5-30 μg/kg/hr",
                "dosage_ja": "CRI: 5-30 μg/kg/時",
                "notes": "Similar to dogs. Very rapid offset makes transition analgesia essential",
                "notes_ja": "犬と同様。効果消失が非常に速いため移行鎮痛が必須",
            },
            "horse": {
                "safe": True,
                "dosage": "CRI: 0.05-0.1 μg/kg/min IV",
                "dosage_ja": "CRI: 0.05-0.1 μg/kg/分 静注",
                "notes": "TIVA component; provides significant MAC-sparing",
                "notes_ja": "TIVAの構成要素。著明なMAC低下効果",
            },
        },
        "side_effects": [
            "respiratory depression (dose-dependent)",
            "bradycardia",
            "muscle rigidity (bolus)",
            "no residual analgesia",
        ],
        "side_effects_ja": ["呼吸抑制（用量依存性）", "徐脈", "筋硬直（ボーラス投与）", "残存鎮痛なし"],
        "contraindications": "Must be administered as CRI only (never bolus in unsupported patients). Mechanical ventilation availability required.",
        "contraindications_ja": "CRI投与のみ（サポートなしの患者へのボーラス投与禁止）。人工呼吸管理が可能な環境が必要。",
        "drug_interactions": [
            {
                "drug": "propofol",
                "effect": "Synergistic: both reduce each other's required dose in TIVA",
                "effect_ja": "相乗作用：TIVAで互いの必要用量を低減",
            },
            {
                "drug": "naloxone",
                "effect": "Reversal agent, though remifentanil effect ceases rapidly on its own",
                "effect_ja": "拮抗薬。ただしレミフェンタニルの効果は自然に速やかに消失",
            },
        ],
    },
    {
        "id": "atracurium",
        "name": "Atracurium",
        "name_ja": "アトラクリウム",
        "category": "muscle_relaxants",
        "mechanism": "Non-depolarizing neuromuscular blocking agent. Competitive antagonist at nicotinic ACh receptors at the neuromuscular junction. Intermediate duration. Unique Hofmann elimination (organ-independent).",
        "mechanism_ja": "非脱分極性神経筋遮断薬。神経筋接合部ニコチン性ACh受容体の競合的拮抗薬。中間作用時間。Hofmann分解（臓器非依存性代謝）が特徴。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.1-0.2 mg/kg IV; maintenance: 0.05-0.1 mg/kg IV PRN or CRI 3-9 μg/kg/min",
                "dosage_ja": "0.1-0.2 mg/kg 静注；維持: 0.05-0.1 mg/kg 静注頓用またはCRI 3-9 μg/kg/分",
                "notes": "IPPV mandatory. Reverse with neostigmine (+ glycopyrrolate) or sugammadex",
                "notes_ja": "陽圧換気(IPPV)必須。ネオスチグミン（＋グリコピロレート）またはスガマデクスで拮抗",
            },
            "cat": {
                "safe": True,
                "dosage": "0.1-0.2 mg/kg IV",
                "dosage_ja": "0.1-0.2 mg/kg 静注",
                "notes": "Cats may require slightly lower doses. IPPV required throughout",
                "notes_ja": "猫ではやや低用量で効果が得られる場合あり。全期間IPPV必要",
            },
            "horse": {
                "safe": True,
                "dosage": "0.07-0.1 mg/kg IV",
                "dosage_ja": "0.07-0.1 mg/kg 静注",
                "notes": "Facilitate IPPV during general anesthesia. TOF monitoring essential",
                "notes_ja": "全身麻酔中のIPPV促進。TOFモニタリング必須",
            },
            "rabbit": {
                "safe": True,
                "dosage": "0.1-0.3 mg/kg IV",
                "dosage_ja": "0.1-0.3 mg/kg 静注",
                "notes": "Hofmann elimination ideal for rabbits (organ-independent)",
                "notes_ja": "Hofmann分解はウサギに理想的（臓器非依存性）",
            },
            "bird": {
                "safe": True,
                "dosage": "0.25-0.5 mg/kg IV",
                "dosage_ja": "0.25-0.5 mg/kg 静注",
                "notes": "IPPV required in birds; high doses needed",
                "notes_ja": "鳥ではIPPV必須。高用量が必要",
            },
        },
        "side_effects": [
            "histamine release (rapid bolus)",
            "bronchospasm",
            "hypotension",
            "residual paralysis if inadequately reversed",
        ],
        "side_effects_ja": ["ヒスタミン遊離（急速ボーラス）", "気管支痙攣", "低血圧", "不十分な拮抗時の残存麻痺"],
        "contraindications": "Must have IPPV capability. Patient must be unconscious (does not provide analgesia or sedation). Monitor with train-of-four (TOF).",
        "contraindications_ja": "IPPV設備必須。患者は意識下で使用してはならない（鎮痛・鎮静作用なし）。四連刺激（TOF）でモニタリング。",
        "drug_interactions": [
            {
                "drug": "isoflurane",
                "effect": "Inhalant anesthetics potentiate NMB; reduce atracurium dose by 30%",
                "effect_ja": "吸入麻酔薬がNMBを増強。アトラクリウム用量を30%減量",
            },
            {
                "drug": "aminoglycosides",
                "effect": "Potentiate neuromuscular blockade; may prolong paralysis",
                "effect_ja": "神経筋遮断を増強。麻痺が延長する可能性",
            },
            {
                "drug": "neostigmine",
                "effect": "Reversal agent (with glycopyrrolate to prevent bradycardia)",
                "effect_ja": "拮抗薬（徐脈予防のためグリコピロレートと併用）",
            },
        ],
    },
    {
        "id": "succinylcholine",
        "name": "Succinylcholine (Suxamethonium)",
        "name_ja": "スキサメトニウム（サクシニルコリン）",
        "category": "muscle_relaxants",
        "mechanism": "Depolarizing neuromuscular blocker. Mimics ACh at nicotinic receptors causing initial fasciculation then sustained depolarization block. Ultra-short duration (5-10 min). Rapidly hydrolyzed by pseudocholinesterase.",
        "mechanism_ja": "脱分極性神経筋遮断薬。ニコチン受容体でAChを模倣し初期線維束攣縮後に持続的脱分極遮断。超短時間作用（5-10分）。偽コリンエステラーゼで速やかに加水分解。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.3-0.5 mg/kg IV",
                "dosage_ja": "0.3-0.5 mg/kg 静注",
                "notes": "Emergency intubation only. Not reversible—must wait for metabolism. Pretreat with atropine",
                "notes_ja": "緊急挿管時のみ。拮抗不可—代謝を待つ。アトロピンで前処置",
            },
            "cat": {
                "safe": True,
                "dosage": "0.5-1 mg/kg IV",
                "dosage_ja": "0.5-1 mg/kg 静注",
                "notes": "Higher dose than dogs; cats have higher pseudocholinesterase activity",
                "notes_ja": "犬より高用量。猫は偽コリンエステラーゼ活性が高い",
            },
            "horse": {
                "safe": True,
                "dosage": "0.1 mg/kg IV",
                "dosage_ja": "0.1 mg/kg 静注",
                "notes": "Emergency use only. Risk of hyperkalemia in myopathic horses",
                "notes_ja": "緊急時のみ。ミオパチーの馬では高カリウム血症のリスク",
            },
        },
        "side_effects": [
            "malignant hyperthermia",
            "hyperkalemia",
            "bradycardia",
            "muscle fasciculations",
            "jaw rigidity",
            "increased intraocular pressure",
        ],
        "side_effects_ja": ["悪性高熱症", "高カリウム血症", "徐脈", "筋線維束攣縮", "下顎硬直", "眼圧上昇"],
        "contraindications": "Malignant hyperthermia susceptibility. Hyperkalemia. Burns/crush injuries (exaggerated K+ release). Open globe injury. Pseudocholinesterase deficiency.",
        "contraindications_ja": "悪性高熱症の素因。高カリウム血症。熱傷・圧挫傷（K+の過剰遊離）。開放性眼球損傷。偽コリンエステラーゼ欠損。",
        "drug_interactions": [
            {
                "drug": "neostigmine",
                "effect": "Prolongs phase II depolarizing block; do NOT give for reversal",
                "effect_ja": "第II相脱分極遮断を延長。拮抗目的では投与しないこと",
            },
            {
                "drug": "organophosphates",
                "effect": "Prolong succinylcholine duration (pseudocholinesterase inhibition)",
                "effect_ja": "偽コリンエステラーゼ阻害によりスキサメトニウムの作用時間延長",
            },
            {
                "drug": "dantrolene",
                "effect": "Treatment for malignant hyperthermia triggered by succinylcholine",
                "effect_ja": "スキサメトニウムが誘発した悪性高熱症の治療薬",
            },
        ],
    },
    {
        "id": "sertraline",
        "name": "Sertraline",
        "name_ja": "セルトラリン",
        "category": "behavioral",
        "mechanism": "Selective serotonin reuptake inhibitor (SSRI). More potent dopamine reuptake inhibition than other SSRIs. 2-6 week onset for behavioral effects.",
        "mechanism_ja": "選択的セロトニン再取り込み阻害薬（SSRI）。他のSSRIよりドパミン再取り込み阻害作用が強い。行動学的効果発現に2-6週間。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "1-5 mg/kg PO q24h (start at 1 mg/kg)",
                "dosage_ja": "1-5 mg/kg 経口 24時間毎（1 mg/kgから開始）",
                "notes": "Alternative to fluoxetine. Anxiety, compulsive disorders, aggression",
                "notes_ja": "フルオキセチンの代替。不安・強迫性障害・攻撃性",
            },
            "cat": {
                "safe": True,
                "dosage": "0.5-1.5 mg/kg PO q24h",
                "dosage_ja": "0.5-1.5 mg/kg 経口 24時間毎",
                "notes": "Anxiety, urine marking; may have fewer GI side effects than fluoxetine",
                "notes_ja": "不安・尿マーキング。フルオキセチンよりGI副作用が少ない可能性",
            },
            "bird": {
                "safe": True,
                "dosage": "1.5 mg/kg PO q12-24h",
                "dosage_ja": "1.5 mg/kg 経口 12-24時間毎",
                "notes": "Feather destructive behavior; limited data",
                "notes_ja": "羽毛破壊行動。データ限定的",
            },
        },
        "side_effects": ["GI upset", "lethargy", "decreased appetite", "tremor", "agitation"],
        "side_effects_ja": ["消化器症状", "嗜眠", "食欲減退", "振戦", "興奮"],
        "contraindications": "MAOI use (14-day washout). Hepatic impairment. Seizure disorders.",
        "contraindications_ja": "MAO阻害薬使用（14日間の休薬）。肝機能障害。痙攣性疾患。",
        "drug_interactions": [
            {
                "drug": "tramadol",
                "effect": "Serotonin syndrome risk and reduced tramadol analgesic efficacy (CYP2D6 inhibition)",
                "effect_ja": "セロトニン症候群リスクおよびCYP2D6阻害によるトラマドール鎮痛効果低下",
            },
            {
                "drug": "selegiline",
                "effect": "Serotonin syndrome; contraindicated",
                "effect_ja": "セロトニン症候群。併用禁忌",
            },
        ],
    },
    {
        "id": "primidone",
        "name": "Primidone",
        "name_ja": "プリミドン",
        "category": "neurological",
        "mechanism": "Barbiturate anticonvulsant. Metabolized to phenobarbital (active metabolite) and PEMA. Used for refractory epilepsy when phenobarbital alone is inadequate.",
        "mechanism_ja": "バルビツール酸系抗てんかん薬。フェノバルビタール（活性代謝物）とPEMAに代謝。フェノバルビタール単独で不十分な難治性てんかんに使用。",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "10-15 mg/kg PO q8h (initially); adjust based on phenobarbital levels",
                "dosage_ja": "10-15 mg/kg 経口 8時間毎（初期）。フェノバルビタール血中濃度に基づき調整",
                "notes": "Hepatotoxicity risk higher than phenobarbital alone. Monitor liver enzymes and bile acids regularly",
                "notes_ja": "フェノバルビタール単独より肝毒性リスクが高い。肝酵素・胆汁酸を定期モニタリング",
            },
        },
        "side_effects": ["hepatotoxicity", "polydipsia/polyuria/polyphagia", "sedation", "ataxia", "weight gain"],
        "side_effects_ja": ["肝毒性", "多飲多尿多食", "鎮静", "運動失調", "体重増加"],
        "contraindications": "Hepatic disease. Cats (not recommended). Monitor phenobarbital levels—target 15-40 μg/mL.",
        "contraindications_ja": "肝疾患。猫には非推奨。フェノバルビタール血中濃度をモニタリング—目標15-40 μg/mL。",
        "drug_interactions": [
            {
                "drug": "phenobarbital",
                "effect": "Converted to phenobarbital in vivo; do not add phenobarbital on top",
                "effect_ja": "生体内でフェノバルビタールに変換。フェノバルビタールの追加投与不可",
            },
            {
                "drug": "chloramphenicol",
                "effect": "Inhibits primidone/phenobarbital metabolism; toxicity risk",
                "effect_ja": "プリミドン/フェノバルビタール代謝を阻害。毒性リスク",
            },
        ],
    },
]
