"""Drug dictionary batch 2 - additional drugs for VetDict"""

from __future__ import annotations

from typing import Any, Dict, List

DRUGS_BATCH_2: List[Dict[str, Any]] = [
    {
        "id": "digoxin",
        "name": "Digoxin",
        "name_ja": "ジゴキシン",
        "category": "cardiovascular",
        "mechanism": "Cardiac glycoside that inhibits Na+/K+-ATPase, increasing intracellular calcium to enhance cardiac contractility and slow AV conduction",
        "mechanism_ja": "Na+/K+-ATPaseを阻害し、細胞内カルシウムを増加させて心収縮力を増強し、房室伝導を遅延させる強心配糖体",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.005-0.01 mg/kg PO q12h",
                "dosage_ja": "0.005-0.01 mg/kg 経口 12時間ごと",
                "notes": "Monitor serum digoxin levels (1-2 ng/mL therapeutic). Narrow therapeutic index. Reduce dose in renal insufficiency.",
                "notes_ja": "血中ジゴキシン濃度をモニタリング（治療域1-2 ng/mL）。治療域が狭い。腎不全では減量。",
            },
            "cat": {
                "safe": True,
                "dosage": "0.005-0.01 mg/kg PO q48h or 1/4 of 0.125 mg tablet q48h",
                "dosage_ja": "0.005-0.01 mg/kg 経口 48時間ごと",
                "notes": "Cats are more sensitive to digoxin toxicity. Use with extreme caution and monitor levels closely.",
                "notes_ja": "猫はジゴキシン中毒に対してより感受性が高い。極めて慎重に使用し、血中濃度を綿密にモニタリング。",
            },
            "horse": {
                "safe": True,
                "dosage": "0.011 mg/kg IV loading, then 0.0055 mg/kg IV q12h",
                "dosage_ja": "0.011 mg/kg 静注負荷量、その後0.0055 mg/kg 静注 12時間ごと",
                "notes": "Used for atrial fibrillation and CHF. Monitor ECG and serum levels.",
                "notes_ja": "心房細動およびうっ血性心不全に使用。心電図と血中濃度をモニタリング。",
            },
            "rabbit": {
                "safe": False,
                "dosage": "Not recommended",
                "dosage_ja": "推奨されない",
                "notes": "Very narrow therapeutic index in rabbits; avoid use.",
                "notes_ja": "ウサギでは治療域が非常に狭い。使用を避ける。",
            },
            "ferret": {
                "safe": True,
                "dosage": "0.005-0.01 mg/kg PO q12-24h",
                "dosage_ja": "0.005-0.01 mg/kg 経口 12-24時間ごと",
                "notes": "Used for dilated cardiomyopathy. Monitor levels carefully.",
                "notes_ja": "拡張型心筋症に使用。血中濃度を慎重にモニタリング。",
            },
            "bird": {
                "safe": True,
                "dosage": "0.02-0.05 mg/kg PO q12h",
                "dosage_ja": "0.02-0.05 mg/kg 経口 12時間ごと",
                "notes": "Used in avian cardiology. Therapeutic monitoring essential.",
                "notes_ja": "鳥類の心臓病学で使用。治療薬物モニタリングが必須。",
            },
        },
        "side_effects": ["Anorexia", "Vomiting", "Diarrhea", "Cardiac arrhythmias", "Bradycardia", "AV block"],
        "side_effects_ja": ["食欲不振", "嘔吐", "下痢", "心不整脈", "徐脈", "房室ブロック"],
        "contraindications": "Contraindicated in hypokalemia, hypercalcemia, hypertrophic cardiomyopathy, ventricular tachycardia, and severe renal failure. Do not use with quinidine or verapamil without dose adjustment.",
        "contraindications_ja": "低カリウム血症、高カルシウム血症、肥大型心筋症、心室頻拍、重度腎不全では禁忌。キニジンやベラパミルとの併用時は用量調整が必要。",
    },
    # --- Modern drugs added 2026-03 ---
    {
        "id": "lokivetmab",
        "name": "Lokivetmab (Cytopoint)",
        "name_ja": "ロキベトマブ（サイトポイント）",
        "category": "biologics",
        "mechanism": "Caninized anti-IL-31 monoclonal antibody that neutralizes interleukin-31, a key cytokine mediating pruritus in canine atopic dermatitis",
        "mechanism_ja": "犬化抗IL-31モノクローナル抗体。犬アトピー性皮膚炎の掻痒に関与するインターロイキン31を中和する",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "1 mg/kg SC q4-8wk",
                "dosage_ja": "1 mg/kg 皮下注射 4-8週間隔",
                "notes": "Rapid onset (within 24h). Excellent safety profile — no immunosuppression or organ toxicity. Can be combined with other therapies. Duration typically 4-8 weeks.",
                "notes_ja": "速効性（24時間以内）。優れた安全性 — 免疫抑制・臓器毒性なし。他療法と併用可能。持続期間4-8週間。",
            },
            "cat": {
                "safe": False,
                "dosage": "Not approved",
                "dosage_ja": "未承認",
                "notes": "Dog-specific monoclonal antibody. Not for use in cats.",
                "notes_ja": "犬特異的モノクローナル抗体。猫には使用不可。",
            },
        },
        "side_effects": ["Injection site reactions (rare)", "Vomiting (rare, transient)"],
        "side_effects_ja": ["注射部位反応（稀）", "嘔吐（稀、一過性）"],
        "contraindications": "Not for use in cats or other species. Avoid in dogs with known hypersensitivity.",
        "contraindications_ja": "猫および他の動物種には使用不可。過敏症のある犬では避ける。",
    },
    {
        "id": "bedinvetmab",
        "name": "Bedinvetmab (Librela)",
        "name_ja": "ベジンベトマブ（リブレラ）",
        "category": "biologics",
        "mechanism": "Caninized anti-NGF (nerve growth factor) monoclonal antibody that blocks pain signaling in osteoarthritis by neutralizing NGF",
        "mechanism_ja": "犬化抗NGF（神経成長因子）モノクローナル抗体。NGFを中和し変形性関節症の疼痛シグナルを遮断する",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.5-1.0 mg/kg SC once monthly",
                "dosage_ja": "0.5-1.0 mg/kg 皮下注射 月1回",
                "notes": "First-in-class monoclonal antibody for OA pain in dogs. Non-NSAID, non-opioid. No hepatic/renal metabolism. Can use in dogs where NSAIDs are contraindicated. EU/Japan approved.",
                "notes_ja": "犬OA疼痛に対する初のモノクローナル抗体。非NSAID・非オピオイド。肝腎代謝なし。NSAIDs禁忌犬にも使用可能。EU/日本承認済み。",
            },
            "cat": {
                "safe": False,
                "dosage": "Not approved for cats (frunevetmab/Solensia is the feline equivalent)",
                "dosage_ja": "猫には未承認（猫用はフルネベトマブ/ソレンシア）",
                "notes": "Use frunevetmab (Solensia) for feline OA pain.",
                "notes_ja": "猫のOA疼痛にはフルネベトマブ（ソレンシア）を使用。",
            },
        },
        "side_effects": ["Injection site reactions (mild)", "Urinary tract infection (uncommon)"],
        "side_effects_ja": ["注射部位反応（軽度）", "尿路感染（稀）"],
        "contraindications": "Not for use in cats. Not for breeding, pregnant, or lactating dogs. Not recommended in dogs under 12 months or <3 kg.",
        "contraindications_ja": "猫には使用不可。繁殖犬・妊娠犬・授乳犬には不可。12ヶ月齢未満または3kg未満の犬には推奨されない。",
    },
    {
        "id": "frunevetmab",
        "name": "Frunevetmab (Solensia)",
        "name_ja": "フルネベトマブ（ソレンシア）",
        "category": "biologics",
        "mechanism": "Felinized anti-NGF monoclonal antibody for feline osteoarthritis pain. Neutralizes nerve growth factor to reduce pain signaling.",
        "mechanism_ja": "猫化抗NGFモノクローナル抗体。神経成長因子を中和し疼痛シグナルを抑制する猫の変形性関節症治療薬",
        "species_info": {
            "cat": {
                "safe": True,
                "dosage": "1-2.8 mg/kg SC once monthly (dose by weight band)",
                "dosage_ja": "1-2.8 mg/kg 皮下注射 月1回（体重帯別用量）",
                "notes": "First monoclonal antibody approved for cats. For OA pain management. Non-NSAID alternative — especially important since long-term NSAIDs are problematic in cats. EU/US/Japan approved.",
                "notes_ja": "猫に承認された初のモノクローナル抗体。OA疼痛管理用。猫は長期NSAIDが問題となるため非NSAID代替として特に重要。EU/US/日本承認。",
            },
            "dog": {
                "safe": False,
                "dosage": "Not for dogs (use bedinvetmab/Librela)",
                "dosage_ja": "犬には不可（ベジンベトマブ/リブレラを使用）",
                "notes": "Cat-specific antibody.",
                "notes_ja": "猫特異的抗体。",
            },
        },
        "side_effects": ["Injection site reactions (mild)", "Vomiting (rare)"],
        "side_effects_ja": ["注射部位反応（軽度）", "嘔吐（稀）"],
        "contraindications": "Not for dogs. Not for breeding/pregnant/lactating cats. Not for kittens under 12 months.",
        "contraindications_ja": "犬には使用不可。繁殖猫・妊娠猫・授乳猫には不可。12ヶ月齢未満の子猫には不可。",
    },
    {
        "id": "fuzapladib",
        "name": "Fuzapladib Sodium (Brenda)",
        "name_ja": "フザプラジブナトリウム（ブレンダ）",
        "category": "immunosuppressives",
        "mechanism": "Inhibits leukocyte adhesion to vascular endothelium by blocking CD11b/CD18 (Mac-1) integrin, suppressing inflammatory immune response in acute pancreatitis",
        "mechanism_ja": "CD11b/CD18（Mac-1）インテグリンを阻害し白血球の血管内皮への接着を抑制。急性膵炎における炎症性免疫応答を抑制する新規抗炎症薬",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "0.4 mg/kg IV q24h × 5 days",
                "dosage_ja": "0.4 mg/kg 静脈内投与 24時間毎 × 5日間",
                "notes": "Approved in Japan for canine acute pancreatitis. Novel mechanism — inhibits leukocyte vascular adhesion. Administer as slow IV injection. Clinical improvement typically seen within 2-3 days.",
                "notes_ja": "日本で犬の急性膵炎に承認。新規作用機序 — 白血球の血管壁接着を阻害。緩徐静注。通常2-3日以内に臨床的改善。",
            },
            "cat": {
                "safe": False,
                "dosage": "Not approved",
                "dosage_ja": "未承認",
                "notes": "Safety and efficacy not established in cats. Under investigation.",
                "notes_ja": "猫での安全性・有効性は確立されていない。研究中。",
            },
        },
        "side_effects": ["Vomiting (mild, transient)", "Diarrhea (uncommon)", "Injection site reaction"],
        "side_effects_ja": ["嘔吐（軽度、一過性）", "下痢（稀）", "注射部位反応"],
        "contraindications": "Not for use in cats. Avoid in dogs with active systemic infection (immunosuppressive mechanism). Not for chronic pancreatitis.",
        "contraindications_ja": "猫には使用不可。活動性全身感染のある犬では避ける（免疫抑制機序）。慢性膵炎には適応外。",
    },
    {
        "id": "gs441524",
        "name": "GS-441524",
        "name_ja": "GS-441524",
        "category": "antivirals",
        "mechanism": "Nucleoside analog antiviral that inhibits feline coronavirus RNA-dependent RNA polymerase (RdRp), blocking viral replication. Active metabolite of remdesivir.",
        "mechanism_ja": "ヌクレオシドアナログ抗ウイルス薬。猫コロナウイルスのRNA依存性RNAポリメラーゼ（RdRp）を阻害しウイルス複製を遮断。レムデシビルの活性代謝物",
        "species_info": {
            "cat": {
                "safe": True,
                "dosage": "Wet FIP: 4 mg/kg SC q24h × 84 days; Dry/ocular: 6-8 mg/kg; Neurological: 8-10 mg/kg. Oral formulations also available.",
                "dosage_ja": "ウェットFIP: 4 mg/kg 皮下 24時間毎×84日間、ドライ/眼型: 6-8 mg/kg、神経型: 8-10 mg/kg。経口製剤も使用可能。",
                "notes": "Revolutionary treatment for FIP — previously 100% fatal, now >80% remission rate. 84-day treatment course standard. Monitor weight, A/G ratio, AGP. Relapse rate 5-15%, responds to retreatment. Oral GS increasingly available.",
                "notes_ja": "FIP治療の革命的薬剤 — 以前は致死率100%、現在は80%以上の寛解率。84日間投与が標準。体重、A/G比、AGPをモニタリング。再発率5-15%、再治療に反応。経口GS-441524も増加中。",
            },
            "dog": {
                "safe": False,
                "dosage": "Not indicated",
                "dosage_ja": "適応なし",
                "notes": "No indication in dogs. FIP is a feline-specific disease.",
                "notes_ja": "犬には適応なし。FIPは猫特異的疾患。",
            },
        },
        "side_effects": [
            "Injection site reactions (SC administration)",
            "Transient inappetence",
            "Injection site fibrosis with prolonged use",
        ],
        "side_effects_ja": ["注射部位反応（皮下投与）", "一過性食欲低下", "長期投与による注射部位線維化"],
        "contraindications": "Not a registered veterinary drug in most countries (regulatory status varies). Monitor liver and kidney function during treatment.",
        "contraindications_ja": "多くの国で動物用医薬品として未登録（規制状況は国により異なる）。投与中は肝機能・腎機能をモニタリング。",
    },
    {
        "id": "molnupiravir",
        "name": "Molnupiravir",
        "name_ja": "モルヌピラビル",
        "category": "antivirals",
        "mechanism": "Ribonucleoside analog prodrug that introduces copying errors during viral RNA replication (lethal mutagenesis), inhibiting feline coronavirus replication",
        "mechanism_ja": "リボヌクレオシドアナログプロドラッグ。ウイルスRNA複製時にコピーエラーを誘導（致死的変異誘発）し、猫コロナウイルスの複製を阻害",
        "species_info": {
            "cat": {
                "safe": True,
                "dosage": "10-15 mg/kg PO q12h × 84 days",
                "dosage_ja": "10-15 mg/kg 経口 12時間毎 × 84日間",
                "notes": "Alternative antiviral for FIP when GS-441524 is unavailable. Oral administration advantage. Similar 84-day treatment course. Monitor for bone marrow suppression.",
                "notes_ja": "GS-441524が入手困難な場合のFIP代替抗ウイルス薬。経口投与の利点。同様の84日間コース。骨髄抑制をモニタリング。",
            },
            "dog": {
                "safe": False,
                "dosage": "Not indicated",
                "dosage_ja": "適応なし",
                "notes": "No veterinary indication in dogs.",
                "notes_ja": "犬には獣医学的適応なし。",
            },
        },
        "side_effects": ["Bone marrow suppression (monitor CBC)", "GI upset", "Hepatotoxicity (rare)"],
        "side_effects_ja": ["骨髄抑制（CBC要モニタリング）", "消化器症状", "肝毒性（稀）"],
        "contraindications": "Not for breeding animals (potential mutagenicity). Monitor CBC regularly. Off-label use in veterinary medicine.",
        "contraindications_ja": "繁殖動物には不可（変異原性の可能性）。CBCを定期的にモニタリング。獣医学ではオフラベル使用。",
    },
    {
        "id": "deslorelin",
        "name": "Deslorelin Acetate (Suprelorin)",
        "name_ja": "酢酸デスロレリン（スプレソリン）",
        "category": "hormones",
        "mechanism": "GnRH agonist implant that initially stimulates then downregulates pituitary gonadotropin release, achieving chemical castration and suppressing sex hormone production",
        "mechanism_ja": "GnRHアゴニストインプラント。下垂体のゴナドトロピン放出を初期刺激後に下方制御し、化学的去勢と性ホルモン産生抑制を達成",
        "species_info": {
            "dog": {
                "safe": True,
                "dosage": "4.7 mg implant SC (lasts 6-12 months); 9.4 mg implant SC (lasts 12-24 months)",
                "dosage_ja": "4.7 mgインプラント 皮下（持続6-12ヶ月）; 9.4 mgインプラント 皮下（持続12-24ヶ月）",
                "notes": "Chemical castration alternative. Initial flare effect (1-2 weeks of increased hormone). Reversible. Also used off-label for BPH, some behavioral issues.",
                "notes_ja": "化学的去勢の代替。初期フレア効果（1-2週間のホルモン上昇）あり。可逆的。BPHや一部の行動問題にオフラベル使用。",
            },
            "cat": {
                "safe": True,
                "dosage": "4.7 mg implant SC",
                "dosage_ja": "4.7 mgインプラント 皮下",
                "notes": "Used for chemical castration and contraception in cats.",
                "notes_ja": "猫の化学的去勢と避妊に使用。",
            },
            "ferret": {
                "safe": True,
                "dosage": "4.7 mg implant SC (lasts 12-24 months typically)",
                "dosage_ja": "4.7 mgインプラント 皮下（通常12-24ヶ月持続）",
                "notes": "First-line medical treatment for ferret adrenal disease (FAD). Controls alopecia, vulvar swelling, prostatomegaly. Preferred over surgery in many cases.",
                "notes_ja": "フェレット副腎疾患（FAD）の内科的第一選択。脱毛、外陰部腫大、前立腺肥大を制御。多くの場合手術より推奨。",
            },
            "rabbit": {
                "safe": True,
                "dosage": "4.7 mg implant SC",
                "dosage_ja": "4.7 mgインプラント 皮下",
                "notes": "Used for chemical castration and to prevent uterine adenocarcinoma in does.",
                "notes_ja": "化学的去勢および雌ウサギの子宮腺癌予防に使用。",
            },
        },
        "side_effects": [
            "Initial hormone flare (1-2 weeks)",
            "Injection site swelling",
            "Temporary behavioral changes",
        ],
        "side_effects_ja": ["初期ホルモンフレア（1-2週間）", "注射部位腫脹", "一過性の行動変化"],
        "contraindications": "Initial flare may temporarily worsen hormone-dependent conditions. Not for animals intended for immediate breeding.",
        "contraindications_ja": "初期フレアによりホルモン依存性疾患が一時的に悪化する可能性。直近の繁殖予定がある動物には不可。",
    },
]
