"""日本の獣医臨床で使われる商品名・流通名 → 薬品ID の検索エイリアス登録簿。

「バイトリル」（エンロフロキサシン）のように、臨床現場では一般名より商品名で
記憶されている薬品が多い。name / name_ja に商品名が含まれない薬品はこれまで
商品名検索が0件になっていた（利用者報告バグ）。この登録簿の別名は各薬品の
``search_aliases`` にマージされ、(a) 薬品辞書のフロント検索・API検索、
(b) 治療テキスト→関連薬品チップの解決（_build_drug_keyword_index tier-2）
の両方で解決される。

収載基準:
  - 日本で実際に流通する（していた）獣医用・医療用医薬品の商品名のみ
    （獣医用: バイトリル・ドミトール等 / ヒト用で獣医転用が定着: メルカゾール等）
  - 一般語と衝突する商品名は収載しない（例: 「プログラム」「ランダ」は
    通常文に頻出し、治療テキストスキャンで誤チップを生むため除外）
  - name / name_ja に既に含まれる商品名は適用時に自動スキップされるので
    重複収載しても害はないが、原則ここには「欠落しているもの」だけを置く
"""

from __future__ import annotations

# drug_id → 別名タプル（日本語商品名を主、獣医現場で入力されやすい英語商品名を従）
BRAND_NAME_ALIASES: dict[str, tuple[str, ...]] = {
    # --- 抗菌薬 ---
    "enrofloxacin": ("バイトリル", "Baytril"),
    "orbifloxacin": ("ビクタス", "Victas"),
    "marbofloxacin": ("マルボシル", "Marbocyl"),
    "pradofloxacin": ("ベラフロックス", "Veraflox"),
    "amoxicillin": ("サワシリン", "パセトシン"),
    "amoxicillin_clavulanate": ("クラバモックス", "オーグメンチン", "Clavamox", "Augmentin"),
    "ampicillin": ("ビクシリン",),
    "cefazolin": ("セファメジン",),
    "cephalexin": ("リレキシン", "Rilexine"),
    "cefpodoxime": ("シンプリセフ", "バナン", "Simplicef"),
    "ceftiofur": ("エクセネル", "Excenel"),
    "doxycycline": ("ビブラマイシン", "Vibramycin"),
    "minocycline": ("ミノマイシン", "Minomycin"),
    "oxytetracycline": ("テラマイシン", "Terramycin"),
    "tetracycline": ("アクロマイシン",),
    "azithromycin": ("ジスロマック", "Zithromax"),
    "clarithromycin": ("クラリス", "クラリシッド"),
    "erythromycin": ("エリスロシン",),
    "clindamycin": ("アンチローブ", "ダラシン", "Antirobe", "Dalacin"),
    "gentamicin": ("ゲンタシン", "Gentacin"),
    "chloramphenicol": ("クロロマイセチン",),
    "metronidazole": ("フラジール", "Flagyl"),
    "trimethoprim_sulfa": ("バクタ", "トリブリッセン", "ST合剤", "Tribrissen", "Bactrim"),
    "rifampin": ("リファジン",),
    "meropenem": ("メロペン",),
    "florfenicol": ("ニューフロール", "Nuflor"),
    "tylosin": ("タイラン", "Tylan"),
    # --- 抗真菌薬 ---
    "itraconazole": ("イトリゾール", "Itrizole"),
    "ketoconazole": ("ニゾラール", "Nizoral"),
    "fluconazole": ("ジフルカン", "Diflucan"),
    "terbinafine": ("ラミシール", "Lamisil"),
    "amphotericin_b": ("ファンギゾン", "Fungizone"),
    # --- 駆虫薬・外部寄生虫 ---
    "ivermectin": ("アイボメック", "カルドメック", "ハートガード", "Ivomec", "Heartgard"),
    "fenbendazole": ("パナクール", "Panacur"),
    "praziquantel": ("ドロンシット", "ドロンタール", "Droncit", "Drontal"),
    "pyrantel_pamoate": ("コンバントリン",),
    "milbemycin_oxime": ("インターセプター", "Interceptor"),
    "afoxolaner": ("ネクスガード", "NexGard"),
    "sarolaner": ("シンパリカ", "Simparica"),
    "toltrazuril": ("バイコックス", "Baycox"),
    "ponazuril": ("マーキス", "Marquis"),
    "doramectin": ("デクトマックス", "Dectomax"),
    "eprinomectin": ("エプリネックス", "Eprinex"),
    "emodepside": ("プロフェンダー", "Profender"),
    "imidacloprid": ("アドバンテージ",),
    # --- NSAIDs・鎮痛 ---
    "meloxicam": ("メタカム", "Metacam"),
    "grapiprant": ("ガリプラント", "Galliprant"),
    "deracoxib": ("デラマックス", "Deramaxx"),
    "piroxicam": ("フェルデン", "バキソ"),
    "acetaminophen": ("カロナール",),
    "aspirin": ("バファリン",),
    "tramadol": ("トラマール",),
    "fentanyl_patch": ("デュロテップ",),
    "dantrolene": ("ダントリウム",),
    # --- 麻酔・鎮静 ---
    "ketamine": ("ケタラール", "Ketalar"),
    "midazolam": ("ドルミカム", "Dormicum"),
    "diazepam": ("セルシン", "ホリゾン"),
    "thiopental": ("ラボナール",),
    "lidocaine": ("キシロカイン", "Xylocaine"),
    "bupivacaine": ("マーカイン", "Marcaine"),
    "medetomidine": ("ドミトール", "Domitor"),
    "dexmedetomidine": ("デクスドミトール", "Dexdomitor"),
    "atipamezole": ("アンチセダン", "Antisedan"),
    "xylazine": ("セラクタール",),
    "sevoflurane": ("セボフロ", "SevoFlo"),
    "atracurium": ("トラクリウム",),
    "neostigmine": ("ワゴスチグミン",),
    "flumazenil": ("アネキセート",),
    # --- 神経・行動 ---
    "phenobarbital": ("フェノバール", "Phenobal"),
    "zonisamide": ("エクセグラン", "コンセーブ", "Consave"),
    "gabapentin": ("ガバペン",),
    "pregabalin": ("リリカ", "Lyrica"),
    "topiramate": ("トピナ",),
    "alprazolam": ("ソラナックス", "コンスタン"),
    "fluoxetine": ("プロザック", "Prozac"),
    "trazodone": ("レスリン",),
    "sertraline": ("ジェイゾロフト", "Zoloft"),
    "clomipramine": ("アナフラニール",),
    "amantadine": ("シンメトレル",),
    "selegiline": ("アニプリル", "エフピー", "Anipryl"),
    "clonidine": ("カタプレス",),
    # --- 循環器 ---
    "pimobendan": ("ピモベハート", "アカルディ"),
    "digoxin": ("ジゴシン",),
    "atenolol": ("テノーミン",),
    "propranolol": ("インデラル", "Inderal"),
    "carvedilol": ("アーチスト",),
    "diltiazem": ("ヘルベッサー",),
    "verapamil": ("ワソラン",),
    "amiodarone": ("アンカロン",),
    "procainamide": ("アミサリン",),
    "mexiletine": ("メキシチール",),
    "sotalol": ("ソタコール",),
    "ivabradine": ("コララン",),
    "amlodipine": ("アムロジン", "ノルバスク", "Norvasc"),
    "telmisartan": ("セミントラ", "ミカルディス", "Semintra"),
    "imidapril": ("タナトリル",),
    "hydralazine": ("アプレゾリン",),
    "sildenafil": ("バイアグラ", "レバチオ", "Viagra"),
    "tadalafil": ("アドシルカ",),
    "sacubitril_valsartan": ("エンレスト", "Entresto"),
    "torsemide": ("ルプラック", "アップカード", "UpCard"),
    "spironolactone": ("アルダクトン", "Aldactone"),
    "acetazolamide": ("ダイアモックス", "Diamox"),
    "clopidogrel": ("プラビックス", "Plavix"),
    "warfarin": ("ワーファリン",),
    "epinephrine": ("ボスミン",),
    "norepinephrine": ("ノルアドリナリン",),
    "dopamine": ("イノバン",),
    "dobutamine": ("ドブトレックス",),
    "erythropoietin": ("エスポー", "エポジン"),
    # --- 呼吸器 ---
    "aminophylline": ("ネオフィリン",),
    "terbutaline": ("ブリカニール",),
    "salbutamol": ("ベネトリン", "サルタノール"),
    "ipratropium": ("アトロベント",),
    "fluticasone": ("フルタイド",),
    "clenbuterol": ("スパイロペント",),
    "doxapram": ("ドプラム", "Dopram"),
    "dextromethorphan": ("メジコン",),
    # --- 抗ヒスタミン ---
    "diphenhydramine": ("レスタミン",),
    "chlorpheniramine": ("ポララミン",),
    "hydroxyzine": ("アタラックス", "Atarax"),
    "cetirizine": ("ジルテック", "Zyrtec"),
    "loratadine": ("クラリチン", "Claritin"),
    "cyproheptadine": ("ペリアクチン", "Periactin"),
    # --- 消化器 ---
    "famotidine": ("ガスター", "Gaster"),
    "cimetidine": ("タガメット",),
    "ranitidine": ("ザンタック",),
    "omeprazole": ("オメプラール",),
    "esomeprazole": ("ネキシウム", "Nexium"),
    "sucralfate": ("アルサルミン",),
    "misoprostol": ("サイトテック", "Cytotec"),
    "metoclopramide": ("プリンペラン", "Primperan"),
    "domperidone": ("ナウゼリン", "Nauzelin"),
    "mosapride": ("ガスモチン", "プロナミド"),
    "ondansetron": ("ゾフラン", "Zofran"),
    "loperamide": ("ロペミン",),
    "lactulose": ("モニラック", "ラグノス"),
    "ursodiol": ("ウルソ", "Urso"),
    "n_acetylcysteine": ("ムコフィリン",),
    # --- 内分泌 ---
    "methimazole": ("メルカゾール", "Mercazole"),
    "levothyroxine": ("チラーヂン", "チラージン"),
    "trilostane": ("アドレスタン", "デソパン", "Adrestan"),
    "prednisolone": ("プレドニン",),
    "dexamethasone": ("デカドロン", "Decadron"),
    "fludrocortisone": ("フロリネフ", "Florinef"),
    "calcitriol": ("ロカルトロール", "Rocaltrol"),
    "desmopressin": ("ミニリンメルト",),
    "semaglutide": ("オゼンピック", "リベルサス", "Ozempic"),
    "leuprolide": ("リュープリン", "Leuplin"),
    "oxytocin": ("アトニン",),
    "pergolide": ("プラセンド", "Prascend"),
    "deslorelin": ("スプレロリン", "スプレソリン", "Suprelorin"),
    # インスリン製剤 — 治療テキストは「プロジンク 0.5 IU」「グラルギン 1 U」の
    # ように商品名・INN語幹単独で引用するが、正準名では括弧内（stem索引が剥がす）
    # か インスリン プレフィックス付きのため解決不能だった（ProZinc 20 refs）。
    "insulin_pzi": ("プロジンク", "ProZinc"),
    "insulin_vetsulin": ("ベトスリン", "カニンスリン", "Vetsulin", "Caninsulin"),
    "insulin_glargine": ("ランタス", "Lantus"),
    "insulin_detemir": ("レベミル", "Levemir"),
    # --- 免疫抑制・腫瘍 ---
    "cyclosporine": ("ネオーラル", "サンディミュン", "Neoral"),
    "tacrolimus_systemic": ("プログラフ", "Prograf"),
    "tacrolimus_ophthalmic": ("タリムス",),
    "azathioprine": ("イムラン", "アザニン", "Imuran"),
    "mycophenolate": ("セルセプト", "CellCept"),
    "methotrexate": ("メソトレキセート", "リウマトレックス"),
    "cyclophosphamide": ("エンドキサン", "Endoxan"),
    "vincristine": ("オンコビン", "Oncovin"),
    "vinblastine": ("エクザール",),
    "doxorubicin": ("アドリアシン", "アドリアマイシン", "Adriamycin"),
    "carboplatin": ("パラプラチン",),
    "melphalan": ("アルケラン", "Alkeran"),
    "l_asparaginase": ("ロイナーゼ", "Leunase"),
    "hydroxyurea": ("ハイドレア", "Hydrea"),
    "mitotane_oral": ("オペプリム",),
    "toceranib": ("パラディア", "Palladia"),
    # --- 眼科 ---
    "cyclosporine_ophthalmic": ("オプティミューン", "Optimmune"),
    "dorzolamide": ("トルソプト", "Trusopt"),
    "timolol_ophthalmic": ("チモプトール",),
    "latanoprost": ("キサラタン", "Xalatan"),
    "tobramycin_ophthalmic": ("トブレックス", "Tobrex"),
    "ofloxacin_ophthalmic": ("タリビッド",),
    "diclofenac_ophthalmic": ("ジクロード",),
    "pilocarpine": ("サンピロ",),
    "tropicamide": ("ミドリン",),
    "fluorescein": ("フローレス",),
    # --- 泌尿器・その他 ---
    "bethanechol": ("ベサコリン",),
    "tamsulosin": ("ハルナール", "Harnal"),
    "prazosin": ("ミニプレス", "Minipress"),
    "allopurinol": ("ザイロリック", "Zyloric"),
    "alendronate": ("フォサマック", "ボナロン", "Fosamax"),
    # --- 抗ウイルス ---
    "acyclovir": ("ゾビラックス", "Zovirax"),
    "valacyclovir": ("バルトレックス", "Valtrex"),
    # --- 消毒・外用 ---
    "chlorhexidine": ("ヒビテン", "ノルバサン", "Nolvasan"),
    "povidone_iodine": ("イソジン", "Isodine"),
}
